akeneo/pim-community-dev

- CHANGELOG-3.0.md
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/controller/user.js
- src/Akeneo/UserManagement/Bundle/Controller/Rest/UserController.php
- src/Akeneo/UserManagement/Bundle/Manager/UserManager.php
- src/Akeneo/UserManagement/Bundle/Resources/config/controllers.yml
- src/Akeneo/UserManagement/Bundle/Resources/config/validation.yml
- src/Akeneo/UserManagement/Bundle/Resources/translations/messages.en_US.yml
> PIM-8426: Fix user password validation

- src/Akeneo/Platform/config/bundles/liip_imagine.yml
The configuration needs to be validated
> PIM-8409: Add liip_imagine filters for dam thumbnail and dam preview

- src/Akeneo/Pim/Structure/Component/AttributeTypes.php
- src/Akeneo/Pim/Structure/Component/Model/FamilyVariant.php
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/lib/select2.less
Add attribute type for the product related to the asset manager
Add style for the asset  selector
> PIM-8391: Add attribute type asset for product + fix css

- CHANGELOG-3.2.md
- UPGRADE.md
Add docs for elasticsearch mapping update
> TIP-1183: Updating the mapping and adding the doc

- CHANGELOG-2.3.md
- src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/form/variant-navigation/navigation.html
- src/Pim/Bundle/UIBundle/Resources/public/less/components/product-edit-form/VariantNavigation.less
- src/Pim/Bundle/UIBundle/Resources/public/less/lib/select2.less
> PIM-8464: Fix display of the navigation items in case of long variant axis value

- CHANGELOG-2.3.md
- src/Pim/Bundle/CatalogBundle/Resources/config/jobs.yml
- src/Pim/Component/Catalog/Job/ComputeFamilyVariantStructureChangesTasklet.php
- src/Pim/Component/Catalog/spec/Job/ComputeFamilyVariantStructureChangesTaskletSpec.php
We use PQB instead of repository to have pagination.
We use the cache clearer.
> PIM-8462: Fix memory leak in ComputeFamilyVariantStructureChangesTasklet

- CHANGELOG-2.3.md
- app/config/config.yml
- app/config/pim_parameters.yml
- src/Akeneo/Bundle/BatchBundle/Notification/MailNotifier.php
- src/Akeneo/Bundle/BatchBundle/Resources/views/Mails/notification.html.twig
- src/Akeneo/Bundle/BatchBundle/Resources/views/Mails/notification.txt.twig
Add a link to the job in the mail notification
> PIM-8449: Improve job notification by adding a link to the job.

- src/Akeneo/Platform/config/bundles/liip_imagine.yml
> PIM-8409: Add preview configuration for the asset manager

- src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Indexing/ProductAndProductModel/ProductPropertiesNormalizer.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/Indexing/ProductAndProductModel/ProductPropertiesNormalizerSpec.php
> TIP-1185: fix the delta uipload

- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/FilterBox.less
> PIM-8355: fix padding

- frontend/build/compile-less.js
> AOB-569: Allow less files from bundles to be compile

- CHANGELOG-3.0.md
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/filter/product/category.js
> PIM-8413: Fix modal of category selection in product and product model exports

- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/product/locale-switcher.html
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/product/scope-switcher.html
Backport of fix already done in 3.1 and above
> Fix locale and scope switcher in the PEF

- src/Akeneo/Pim/Enrichment/Bundle/Product/Query/Sql/Completeness/SqlGetProductCompletenesses.php
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml
- src/Akeneo/Pim/Enrichment/Component/Product/Model/Projection/ProductCompleteness.php
- src/Akeneo/Pim/Enrichment/Component/Product/Query/GetProductCompletenesses.php
- tests/back/Pim/Enrichment/Integration/Product/Query/Sql/Completeness/GetProductCompletenessesIntegration.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Model/Projection/ProductCompletenessSpec.php
- projection for product completeness
- query to retrieve data from DB
> TIP-1159: Projection model + read query

- src/Oro/Bundle/UserBundle/Controller/UserController.php
- src/Oro/Bundle/UserBundle/Exception/UserCannotBeDeletedException.php
- src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid/action/delete-action.js
- src/Pim/Bundle/UIBundle/Resources/public/js/init-layout.js
- tests/legacy/features/attribute/delete_attribute.feature
This PR allows to display an error message for the user with an explicit message when something goes wrong during the deletion. A small portion of the frontend code is retrieved from the master branch. …
> PIM-8448: send a response with an error message when the user deletion goes wrong

- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/button/Button.less
> DAPI-351: add ghost button style

- .circleci/local-object-storage-setup.sh
Fixes configuration issues that created problems with the new version of the S3 library.
> Fixes object storage configuration

- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/button/Button.less
Add a separated suffix zone to the AknButton
> DAPI-333: Add separated suffix to AknButton

- tests/legacy/features/pim/enrichment/product/datagrid/filtering/filter_products_per_metric.feature
- tests/legacy/features/pim/enrichment/product/datagrid/filtering/filter_products_per_price.feature
- tests/legacy/features/pim/enrichment/product/datagrid/filtering/filter_products_per_text_fields.feature
- tests/legacy/features/pim/enrichment/product/datagrid/filtering/filter_products_per_with_multiple_metrics.feature
- tests/legacy/features/pim/enrichment/product/datagrid/filtering/filter_products_per_with_multiple_number_fields.feature
- tests/legacy/features/pim/enrichment/product/datagrid/filtering/filter_products_per_with_multiple_prices.feature
- tests/legacy/features/pim/enrichment/product/datagrid/filtering/filter_products_per_with_multiple_text_fields.feature
Some critical tests last 3 to 5 minutes on the 6 minutes to run the critical tests. These tests are mainly about the datagrid and testing all the filters.
This is the first attempt to improve it by splitting the test and test only one filter.
We have some other tests that are really slow.
I think we can improve it by investigating few time.
Here is a list of the tests. You can use the command to detect the longest test in your context.
```
curl "https://circleci.com/api/v1.1/project/github/akeneo/pim-enterprise-dev/11488/tests?circle-token=YOUR_TOKEN" |  jq '.tests |= sort_by(.run_time)'
```
```
{
"classname": "Filter products by date field",
"file": "vendor/akeneo/pim-community-dev/tests/legacy/features/pim/enrichment/product/datagrid/f …
```
> Split time consuming tests

- src/Akeneo/Tool/Bundle/ElasticsearchBundle/IndexConfiguration/UpdateIndexMapping.php
- src/Akeneo/Tool/Bundle/ElasticsearchBundle/tests/integration/UpdateIndexMappingIntegration.php
> PIM-8322: fix the command to re-index to be idempotent

- src/Akeneo/Pim/Enrichment/Bundle/Resources/elasticsearch/product_mapping.yml
Index reference data as lowercase as for the option.
See https://github.com/akeneo/pim-community-dev/pull/10192
> TIP-1163: index reference data option as lowercase

- package.json
- yarn.lock
> Fix open lib security issue

- package.json
The goal is to reduce the diff between dev package.json and standard package.json (and also to fix errors)
> Update package json according standard one

- src/Akeneo/Platform/CommunityVersion.php
> Release: Update ce name

- composer.json
> Change branch alias

- UPGRADE.md
> Use aliases in ES

- src/Akeneo/Tool/Bundle/ElasticsearchBundle/Client.php
- src/Akeneo/Tool/Bundle/ElasticsearchBundle/IndexConfiguration/UpdateIndexMapping.php
- src/Akeneo/Tool/Bundle/ElasticsearchBundle/spec/ClientSpec.php
- src/Akeneo/Tool/Bundle/ElasticsearchBundle/tests/integration/UpdateIndexMappingIntegration.php
It uses aliases instead of indexes for all the indexes, in order to be consistent everywhere.
| Changelog updated                 | Todo with Benoit
> TIP-1111: use ES aliases instead of indexes

- CHANGELOG-3.2.md
- UPGRADE.md
Updates the UPGRADE.md file for 3.2
> 3.2 upgrade

- .circleci/config.yml
circleci config validate .circleci/config.yml is ok
> Fix the nightly build config

- CHANGELOG-3.2.md
- UPGRADE.md
* Release 3.2: Update UPGRADE.md and CHANGELOG-3.2.md
> Backport Benoit's PR into 3.2

- UPGRADE.md
> Fix error in the changelog for the release 3.2

- CHANGELOG-2.3.md
- src/Akeneo/Bundle/MeasureBundle/Resources/config/measure.yml
- src/Pim/Bundle/ApiBundle/tests/integration/Controller/MeasureFamily/ListMeasureFamilyIntegration.php
Change 'div' by '/' in Measure
> PIM-8551: Replace div by '/'

- CHANGELOG-3.0.md
- CHANGELOG-3.1.md
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/lib/jquery.jstree.less
Category tree is not scrollable anymore.
> PIM-8560: Fix category tree scroll

- UPGRADE.md
> UPGRADE.md for 3.2

- CHANGELOG-3.0.md
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/lib/jquery.jstree.less
> PIM-8560: Fix maximum height of categories tree to be able to scroll

- CHANGELOG-3.2.md
- src/Akeneo/Platform/CommunityVersion.php
This reverts commit 02cddfb888d114ec8207d88dd843037b439d8397.
> Revert "Preparing version 3.2.0-ALPHA1"

- CHANGELOG-3.1.md
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/lib/jquery.jstree.less
> PIM-8570: Fix category tree display

- src/Akeneo/Tool/Bundle/ApiBundle/tests/integration/ApiTestCase.php
- tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/ErrorListProductEndToEnd.php
It improves the slowest integration test (from 40 sec to 1sec).
It was creating 10 000 products for nothing. The error is triggered by ES whatever how many documents are indexed.
`OK`: Done / …
> Improve test error api

- CHANGELOG-2.3.md
- src/Pim/Bundle/UIBundle/Resources/public/less/lib/jquery.jstree.less
- src/Pim/Bundle/UIBundle/Resources/public/lib/jstree/jquery.jstree.js
> PIM-8572: Fix issue on category selection in product grid

- UPGRADE.md
> Release: Indicate time to index

- app/config/config_behat.yml
- app/config/config_test.yml
- app/config/pim_parameters.yml
- src/Akeneo/Pim/Structure/Bundle/DependencyInjection/AkeneoPimStructureExtension.php
- src/Akeneo/Platform/Bundle/InstallerBundle/Resources/config/services.yml
- src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/services.yml
> TIP-1192 Clean Community edition

- src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/history.html
> PIM-6879: Fix product history display

- UPGRADE.md
- upgrades/schema/remove_orphan_archives.php
> Remove orphan directories in archive_dir

- upgrades/schema/remove_orphan_archives.php
> Fix removal of orphan archives

- CHANGELOG-3.0.md
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/Grid.less
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/product/history.html
> PIM-8591: Fix history author display

- upgrades/schema/remove_orphan_archives.php
> Fix remove orphan archives

- src/Akeneo/Platform/Bundle/ImportExportBundle/Persistence/Filesystem/DeleteOrphanJobExecutionDirectories.php
> Fix delete orphan job execution directories

- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/attributes/create-button.js
> PIM-8409: Remove the hinding of the asset single link button creation

- CHANGELOG-3.0.md
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/FamilyVariant.less
> PIM-8445: Fix variant axes settings CSS style

- src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/ComputeAndPersistProductCompletenessSubscriber.php
- src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/IndexProductModelCompleteDataSubscriber.php
- tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/ComputeAndPersistProductCompletenessSubscriberSpec.php
- tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/IndexProductModelCompleteDataSubscriberSpec.php
It listens on POST_SAVE_ALL instead of POST_SAVE
> TIP-1159: Batch calls to product compute completeness

- src/Akeneo/Pim/Enrichment/Bundle/Product/Query/Sql/Completeness/SqlSaveProductCompletenesses.php
- src/Akeneo/Pim/Enrichment/Component/Product/Query/CannotSaveProductCompletenessCollectionException.php
- src/Akeneo/Pim/Enrichment/Component/Product/Query/SaveProductCompletenesses.php
Adds rollback on transaction if failure on SaveProductCompleteness
> TIP-1159: Exception on SaveCompleteness fail

- src/Akeneo/Pim/Enrichment/Bundle/Command/CalculateCompletenessCommand.php
- src/Akeneo/Pim/Enrichment/Bundle/Command/PurgeProductsCompletenessCommand.php
- src/Akeneo/Pim/Enrichment/Bundle/DependencyInjection/AkeneoPimEnrichmentExtension.php
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/cli_command.yml
- src/Akeneo/Platform/Bundle/InstallerBundle/Command/InstallCommand.php
- src/Akeneo/Platform/Bundle/InstallerBundle/DependencyInjection/PimInstallerExtension.php
- src/Akeneo/Platform/Bundle/InstallerBundle/Resources/config/cli_command.yml
`ContainerAwareCommand` is deprecated in SF4.
Also, we can't use the container in SF4 as service are private by default.
It means we will have too migrate all our commands as services soon or later.
This is a first PR.
Here is the list of the commands in CE, if you are motivated by this amazing adventure.
- src/Akeneo/Tool/Bundle/ApiBundle/Command/ListClientsCommand.php
- src/Akeneo/Tool/Bundle/ApiBundle/Command/RevokeClientCommand.php
- src/Akeneo/Tool/Bundle/ApiBundle/Command/CreateClientCommand.php
- src/Akeneo/Tool/Bundle/BatchQueueBundle/Command/PublishJobToQueueCommand.php
- src/Akeneo/Tool/Bundle/BatchQueueBundle/Command/JobQueueConsumerCommand.php
- src/Akeneo/Tool/Bundle/ConnectorBundle/Command/AnalyzeProductCsvCommand.php
- …
> TIP-901: command not container aware - Part 1

- src/Akeneo/Pim/Enrichment/Bundle/Command/CalculateCompletenessCommand.php
Use interface instead of concrete implementation.
Note: the command was applying the PQB using permission in EE, which should not be the case.
Performance improvement of the commands expected: 30% :tada:  …
> TIP-901: fix the CI

- .circleci/config.yml
- .circleci/wait_docker_up.sh
- src/Akeneo/Pim/Enrichment/Bundle/Command/CalculateCompletenessCommand.php
Copy/past from on boarder + I added ES check.
> GITHUB-9472: wait for Mysql and ES to be up

- src/Akeneo/Pim/Structure/Bundle/DependencyInjection/Configuration.php
- tests/legacy/features/pim/enrichment/reference-data/import/import_attributes.feature
If the reference data configuration is split into multiple files, it does not work.
> Bring back configuration for reference data

- app/bundles.php
- app/config/pim_parameters.yml
- app/config/security.yml
- app/phpunit.xml.dist
- behat.yml.dist
- bin/check-services-instantiability
- bin/console
- composer.json
- composer.lock
- phpstan.neon
- src/Akeneo/Platform/Bundle/ImportExportBundle/Controller/Ui/JobTrackerController.php
- src/Akeneo/Platform/Bundle/InstallerBundle/Command/CheckRequirementsCommand.php
- src/Akeneo/Platform/config/pim.yml
- src/Akeneo/Tool/Bundle/ElasticsearchBundle/DependencyInjection/Configuration.php
- src/Akeneo/UserManagement/Bundle/DependencyInjection/Configuration.php
- src/Kernel.php
- tests/back/Integration/AppKernelTest.php
- web/app.php
Easier to read commit by commit. 
The kernel is now located in `src/Kernel.php` for Symfony4.
ACL support is removed from Symfony. We need an extra `AclBundle`.
> TIP-901: Small fixes towards SF4

- src/Akeneo/Pim/Enrichment/Bundle/Product/Query/Sql/Completeness/SqlGetCompletenessFamilyMasks.php
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/completeness_queries.yml
- src/Akeneo/Pim/Enrichment/Component/Product/Completeness/Model/CompletenessFamilyMask.php
- src/Akeneo/Pim/Enrichment/Component/Product/Completeness/Model/CompletenessFamilyMaskPerChannelAndLocale.php
- src/Akeneo/Pim/Enrichment/Component/Product/Completeness/Query/GetCompletenessFamilyMasks.php
- src/Akeneo/Pim/Enrichment/Component/Product/Completeness/Query/NonExistingFamiliesException.php
- tests/back/Pim/Enrichment/Integration/Product/Query/Sql/Completeness/SqlGetCompletenessFamilyMasksIntegration.php
Description:
This PR adds the family mask as well as for the product.
Integration test as been added
> TIP-1159 [Family Masks]

- CHANGELOG-3.1.md
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/lib/select2.less
- src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/select2-choice-filter.js
- src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/select2-rest-choice-filter.js
- tests/legacy/features/pim/enrichment/product-model/create_product_model.feature
> PIM-8576: Fix attribute options in case of very long strings

- bin/check-pullup
- src/Akeneo/Tool/Bundle/BatchQueueBundle/Query/SqlDeleteJobExecutionMessageOrphansQuery.php
- src/Akeneo/Tool/Bundle/BatchQueueBundle/Resources/config/services.yml
- src/Akeneo/Tool/Bundle/BatchQueueBundle/tests/integration/Query/SqlDeleteJobExecutionMessageOrphansQueryIntegration.php
- src/Akeneo/Tool/Component/BatchQueue/Query/DeleteJobExecutionMessageOrphansQueryInterface.php
It fixes a hole in the "check pull up racket".
> Fix check pull up

- CHANGELOG-3.0.md
- phpspec.yml.dist
- src/Oro/Bundle/DataGridBundle/Extension/Formatter/FormatterExtension.php
- src/Oro/Bundle/DataGridBundle/spec/Extension/Formatter/FormatterExtensionSpec.php
- src/Oro/Bundle/PimDataGridBundle/Query/Sql/ListProductGridAvailableColumns.php
- src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/column-selector.ts
- src/Oro/Bundle/PimDataGridBundle/tests/Integration/Query/Sql/ListProductGridAvailableColumnsIntegration.php
- tests/legacy/features/pim/enrichment/product/datagrid/display_attributes_in_the_grid.feature
| Added integration tests           | y
> PIM-8631: Fix column selector in the case of an attribute code as integer

- src/Akeneo/UserManagement/Bundle/Resources/views/Role/update.html.twig
> Assets pim 8430 front fix

- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/mass-edit/form.html
> PIM-8356: Fix wrong class

- tests/legacy/features/Context/CommandContext.php
- tests/legacy/features/pim/enrichment/product/completeness/display_completeness.feature
- tests/legacy/features/pim/enrichment/product/completeness/remove_completeness.feature
- tests/legacy/features/pim/enrichment/product/completeness/update_completeness.feature
- tests/legacy/features/pim/enrichment/product/datagrid/filtering/filter_products_per_completeness.feature
- tests/legacy/features/pim/enrichment/product/export/convert_metric_values_during_product_export.feature
- tests/legacy/features/pim/enrichment/product/export/export_products.feature
- tests/legacy/features/pim/enrichment/product/export/export_products_and_download_exported_file.feature
- tests/legacy/features/pim/enrichment/product/export/export_products_with_heterogeneous_data.feature
- tests/legacy/features/pim/enrichment/product/export/export_products_with_localized_date.feature
- tests/legacy/features/pim/enrichment/product/export/export_products_with_localized_decimal.feature
- tests/legacy/features/pim/enrichment/product/export/export_products_with_media.feature
- tests/legacy/features/pim/enrichment/product/export/export_products_with_ordered_options.feature
- tests/legacy/features/pim/enrichment/product/export/export_products_without_media.feature
- tests/legacy/features/pim/enrichment/product/export/xlsx/export_products.feature
- tests/legacy/features/pim/enrichment/product/mass-edit/mass_actions_on_all_entities.feature
- tests/legacy/features/pim/enrichment/reference-data/export/export_products_with_reference_data.feature
- tests/legacy/features/pim/enrichment/reference-data/product/completeness.feature
- tests/legacy/features/pim/structure/family/define_the_attribute_requirement.feature
- tests/legacy/features/platform/export/execute_an_export.feature
> TIP-1159: remove use of the calculator in the behat

- CHANGELOG-2.3.md
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/FlatToStandard/ConvertedField.php
- src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/product/edit.yml
- src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/product_model/edit.yml
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/i18n.ts
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/FlatToStandard/ConvertedFieldSpec.php
> Merge 2.3 into 3.0

- CHANGELOG-3.2.md
- src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
> PIM-8583: Add missing translations on role deletion

- src/Akeneo/Pim/Enrichment/Bundle/DependencyInjection/Compiler/ResolveDoctrineTargetModelPass.php
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/entities.yml
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/models.yml
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/validation/completeness.yml
- src/Oro/Bundle/PimDataGridBundle/spec/Normalizer/ProductAssociationNormalizerSpec.php
- tests/back/Pim/Enrichment/Integration/Completeness/AbstractCompletenessTestCase.php
- tests/back/Pim/Enrichment/Integration/Completeness/CompletenessForLocalisableAttributeIntegration.php
- tests/back/Pim/Enrichment/Integration/Completeness/CompletenessForScopableAndLocalisableAttributeIntegration.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/InternalApi/EntityWithFamilyVariantNormalizerSpec.php
Remove useless model classes about completeness.
> TIP-1159: Remove completeness model classes

- src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Query/CompleteFilter.php
- src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Query/VariantProductRatio.php
- src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/InitCompletenessDbSchemaSubscriber.php
- src/Akeneo/Pim/Enrichment/Bundle/Product/Query/Sql/Completeness/SqlSaveProductCompletenesses.php
- src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductGrid/FetchProductModelRowsFromCodes.php
- src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductGrid/FetchProductRowsFromIdentifiers.php
- tests/back/Integration/catalog/technical_sql/200_products.sql
- tests/back/Pim/Enrichment/Integration/Completeness/CalculateCompletenessCommandIntegration.php
- tests/back/Pim/Enrichment/Integration/Fixture/CompletenessFilter.php
- tests/back/Pim/Enrichment/Integration/Product/Query/Sql/Completeness/SaveProductCompletenessesIntegration.php
- upgrades/schema/Version_3_2_20190813091149_remove_missing_attributes_and_ratio_from_completeness.php
- upgrades/schema/Version_4_0_20190813091149_remove_missing_attributes_and_ratio_from_completeness.php
- upgrades/schema/es_delete_unused_indexes.php
| Review and 2 GTM                  | -\
> Tip 1159 remove missing attributes and ratio from completeness

- .circleci/find_non_executed_phpspec.sh
> Add reference-entity and asset manager

- CHANGELOG-4.0.md
- frontend/build/compile-less.js
- frontend/build/update-extensions.js
This PR tests the fix for https://github.com/akeneo/pim-community-dev/pull/10250 
> GITHUB-10247: Fix regex to compile the frontend assets

- bin/docker/pim-dependencies.sh
- composer.json
- composer.lock
- symfony.lock
We need to symfony flex to be able to "compile" the .env file for production (turn `.env` into `.env.local.php`). 
> TIP-1209 Install symfony flex

- .gitignore
Those files must not be commit to the repository.
> TIP-1087: Add .env.***.local file to .gitignore

- .circleci/config.yml
- make-file/dev.mk
We make some targets (which run test) more generic because they can be easily configurable through env vars. Don't you still can add you custom target in the directory `make-file`. The installation step has been split because we want better timing information.
| Tech Doc …
> TIP-1204 Fix little glitches

- CHANGELOG-3.0.md
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/tree-manage.jstree.js
Backport of https://github.com/akeneo/pim-community-dev/pull/10611
> PIM-8713: Fix category tree selector (PIM-8663 backport)

- src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/LoadingMask.less
- tests/front/unit/jest/unit.jest.js
> PIM-8552: New assets tab and display an asset collection

- composer.json
- composer.lock
`behat/mink-selenium2-driver` does not have a `1.3.x-dev` branch alias anymore
> Fix composer dev-requirement version

- .circleci/config.yml
- tests/legacy/features/Context/FixturesContext.php
- tests/legacy/features/pim/enrichment/product/import/import_products.feature
I removed an unstable test because it's already tested in this critical scenario: https://github.com/akeneo/pim-community-dev/blob/3.2/tests/legacy/features/pim/enrichment/product/import/import_products.feature#L29
> Fix import products test

- CHANGELOG-4.0.md
- src/Akeneo/Pim/Enrichment/Component/Product/Builder/EntityWithValuesBuilder.php
- src/Akeneo/Pim/Enrichment/Component/Product/Model/AbstractProduct.php
- src/Akeneo/Pim/Enrichment/Component/Product/Model/ProductInterface.php
- tests/back/Acceptance/spec/Product/InMemoryProductRepositorySpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Model/ProductSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Validator/UniqueAxesCombinationSetSpec.php
> TIP-1160: update setIdentifier method

- config/packages/doctrine.yml
- docker-compose.yml
- src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductGrid/FetchProductRowsFromIdentifiers.php
- src/Akeneo/Platform/Bundle/InstallerBundle/InstallStatusManager/InstallStatusManager.php
- src/Akeneo/Platform/PimRequirements.php
- tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductGrid/AssertRows.php
- tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductGrid/FetchProductModelRowsFromCodesIntegration.php
- tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductGrid/FetchProductRowsFromIdentifiersIntegration.php
Let's use MySQL 8 with the PIM :)
> TIP-1249: upgrade to MySQL 8

- src/Akeneo/Pim/Structure/Bundle/Resources/config/validation/attribute.yml
The option `strict` is mandatory for Symfony 4.
> Fix symfony deprecation

- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/attributes/create-button.js
Linked to changes in https://github.com/akeneo/pim-enterprise-dev/pull/6860
> PIM-8745: Fix hiding of asset collection creation button

- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/attributes/create-button.js
> Fix feature flag raccoons

- CHANGELOG-3.2.md
- src/Akeneo/UserManagement/Bundle/Controller/Rest/UserController.php
Fix an incorrect check for the user token.
> PIM-8767: Fix user security token check

- src/Akeneo/Platform/Bundle/ImportExportBundle/Command/PurgeJobExecutionCommand.php
- src/Akeneo/Platform/Bundle/ImportExportBundle/Purge/PurgeJobExecution.php
- src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/services.yml
- src/Akeneo/Platform/Bundle/InstallerBundle/Command/AssetsCommand.php
- src/Akeneo/Platform/Bundle/InstallerBundle/Command/CheckRequirementsCommand.php
- src/Akeneo/Platform/Bundle/InstallerBundle/Command/DatabaseCommand.php
- src/Akeneo/Platform/Bundle/InstallerBundle/Command/DumpRequirePathsCommand.php
- src/Akeneo/Platform/Bundle/InstallerBundle/Command/InstallCommand.php
- src/Akeneo/Platform/Bundle/InstallerBundle/Command/PrepareRequiredDirectoriesCommand.php
- src/Akeneo/Platform/Bundle/InstallerBundle/Resources/config/cli_command.yml
> TIP-1262 Turn Platform commands into services (exit ContainerAwareCommand) Part 1

- src/Akeneo/Platform/Bundle/InstallerBundle/Command/DatabaseCommand.php
- src/Akeneo/Platform/Bundle/InstallerBundle/Resources/config/cli_command.yml
- tests/back/Pim/Enrichment/Upgrade/RemoveProductEmptyRawValuesIntegration.php
- tests/back/Pim/Enrichment/Upgrade/RemoveProductModelEmptyRawValuesIntegration.php
> Fix EE database installation

- src/Akeneo/Pim/Structure/Component/AttributeTypes.php
- tests/back/Acceptance/Catalog/Context/ProductCreation.php
- tests/back/Acceptance/Catalog/Context/ProductValidation.php
- tests/back/Acceptance/Family/FamilyContext.php
- tests/back/Acceptance/Resources/config/behat/services.yml
Those updates are mainly for missing contexts or adding methods to existing ones.
I also update the product validator used, `@validator` was used, but it should be `@pim_catalog.validator.product`.
> PIM-8689: Update some Acceptance context for test purpose

- tests/front/acceptance/cucumber/tools.js
- tests/front/common/templates/index.html
In this PR I fixed the renderView method to make it work as expected (it was getting a parameter but was not using it and was also rendering views in a weird way). I also added minimal css to our test webpack build to have nice tests (with the new styled components, the tests no have css and look exactly the same as in the real UI. It will help us having more stable tests and also closer to the real result. …
> PIM-8496: new form of acceptance tests

- src/Akeneo/Pim/Enrichment/Bundle/Command/CleanRemovedAttributesFromProductAndProductModelCommand.php
- src/Akeneo/Pim/Enrichment/Bundle/Command/IndexProductModelCommand.php
- src/Akeneo/Pim/Enrichment/Bundle/Command/QueryHelpProductCommand.php
- src/Akeneo/Pim/Enrichment/Bundle/Command/QueryHelpProductModelCommand.php
- src/Akeneo/Pim/Enrichment/Bundle/Command/RefreshProductCommand.php
- src/Akeneo/Pim/Structure/Bundle/ReferenceData/Command/CheckRequirementsCommand.php
- src/Akeneo/Pim/Structure/Bundle/Resources/config/commands.yml
- src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/Command/AggregateVolumesCommand.php
- src/Akeneo/Platform/Bundle/ImportExportBundle/Command/PurgeJobExecutionCommand.php
- src/Akeneo/Platform/Bundle/InstallerBundle/Command/AssetsCommand.php
- src/Akeneo/Platform/Bundle/InstallerBundle/Command/DumpRequirePathsCommand.php
- src/Akeneo/UserManagement/Bundle/Command/CreateUserCommand.php
- src/Akeneo/UserManagement/Bundle/DependencyInjection/PimUserExtension.php
- src/Akeneo/UserManagement/Bundle/Resources/config/commands.yml
> TIP-1262 Turn some commands into services (exit ContainerAwareCommand)

- src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Indexer/ProductAndAncestorsIndexer.php
- src/Akeneo/Pim/Enrichment/Bundle/Product/Query/Sql/GetAncestorProductModelCodes.php
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/elasticsearch.yml
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml
- tests/back/Pim/Enrichment/Integration/Product/Query/Sql/GetAncestorProductModelCodesIntegration.php
- tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Indexer/ProductAndAncestorsIndexerSpec.php
> TIP-1281: Index products and ancestors from a list of product identifiers

- src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Indexer/ProductModelDescendantsAndAncestorsIndexer.php
- src/Akeneo/Pim/Enrichment/Bundle/Product/Query/Sql/GetAncestorAndDescendantProductModelCodes.php
- src/Akeneo/Pim/Enrichment/Bundle/Product/Query/Sql/GetDescendantVariantProductIdentifiers.php
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/elasticsearch.yml
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml
- tests/back/Pim/Enrichment/Integration/Product/Query/Sql/GetAncestorAndDescendantProductModelCodesIntegration.php
- tests/back/Pim/Enrichment/Integration/Product/Query/Sql/GetDescendantVariantProductIdentifiersIntegration.php
- tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Indexer/ProductModelDescendantsAndAncestorsIndexerSpec.php
[TIP-1283](https://akeneo.atlassian.net/browse/TIP-1283) Create ProductModelDescendantsAndAncestorsIndexer
- add GetAncestorAndDescendantProductModelCodes query
- add GetDescendantVariantProductIdentifiers query
- add ProductModelDescendantsAndAncestorsIndexer
| Tech Doc …
> TIP-1283: Create ProductModelDescendantsAndAncestorsIndexer

- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/fetcher/attribute-fetcher.js
Add a cache on the attribute type fetcher
> PIM-8790: add cache clearer on attribute fetcher

- tests/legacy/features/Context/Page/Base/Base.php
- tests/legacy/features/Context/WebUser.php
- tests/legacy/features/pim/enrichment/product/import/import_products_with_associations.feature
- tests/legacy/features/pim/enrichment/product/import/xlsx/import_products_with_associations.feature
- tests/legacy/features/pim/enrichment/product/mass-edit/mass_associate.feature
- tests/legacy/features/pim/enrichment/product/pef/association/associate_product.feature
- tests/legacy/features/pim/enrichment/product/pef/association/update_associations.feature
> PIM-8805: Fix press button in Behat user context

- src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ElasticsearchProjection/GetElasticsearchProductModelProjection.php
Instead of doing:
- query on axes (useless)
- query on attribute set level 1
With all the JOIN, the solution is just to aggregate all the attribute codes per attribute set level:
["1" => ["attribute_code_1", "attribute_code_2", "2" => ["attribute_code_3", "attribute_code_4"]
Note: level 0 is not persisted in database and corresponds to common attributes. We have to calculate it (family attributes MINUS attributes at level 1 and 2).
Note 2: it was pretty easy to do thanks to all the tests :tada:  …
> TIP-1129: improve the query to get ancestors

- CHANGELOG-4.0.md
- src/Akeneo/Pim/Enrichment/Bundle/Command/IndexProductCommand.php
- src/Akeneo/Pim/Enrichment/Bundle/Command/IndexProductModelCommand.php
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/cli_command.yml
This PR takes advantage of the new indexer services to enhance the indexation commands without hydrating the products / product models.
It also lets the index in a clean state by reindexing the whole subtrees (ancestors/descendants)  when specifying specific items to be reindexed (this used to be the case for product models, but not for products) …
> TIP-1288: Refactor indexation commands

- CHANGELOG-4.0.md
- src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/AttributeOption/LocalizableSubscriber.php
- src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/Category/ConfigureCategoryTreeForExportJobsAfterChangingTheChannelCategoryTree.php
- src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/Category/OnDelete/CheckChannelsOnDeletionSubscriber.php
- src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/Category/OnDelete/RemoveCategoryFilterInJobInstanceSubscriber.php
- src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/Category/OnDelete/UpdateIndexesOnCategoryDeletion.php
- src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/Category/OnSave/ConfigureCategoryTreeForExportJobsAfterChangingTheChannelCategoryTree.php
- src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/Db/InitCompletenessDbSchemaSubscriber.php
- src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/EntityWithValues/ComputeEntityRawValuesSubscriber.php
- src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/EntityWithValues/LoadEntityWithValuesSubscriber.php
- src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/Family/ComputeCompletenessOnFamilyUpdateSubscriber.php
- src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/ProductModel/OnDelete/ComputeProductAndAncestorsSubscriber.php
- src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/ProductModel/OnSave/ComputeProductAndAncestorsSubscriber.php
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/event_subscribers.yml
- src/Oro/Bundle/PimDataGridBundle/EventSubscriber/FilterEntityWithValuesSubscriber.php
- tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/AttributeOption/LocalizableSubscriberSpec.php
- tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/Category/ConfigureCategoryTreeForExportJobsAfterChangingTheChannelCategoryTreeSpec.php
- tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/Category/OnDelete/RemoveCategoryFilterInJobInstanceSubscriberSpec.php
- tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/Category/OnSave/ConfigureCategoryTreeForExportJobsAfterChangingTheChannelCategoryTreeSpec.php
- tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/EntityWithValues/ComputeEntityRawValuesSubscriberSpec.php
- tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/EntityWithValues/LoadEntityWithValuesSubscriberSpec.php
- tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/Family/ComputeCompletenessOnFamilyUpdateSubscriberSpec.php
- tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/ProductModel/OnDelete/ComputeProductAndAncestorsSubscriberSpec.php
- tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/ProductModel/OnSave/ComputeProductAndAncestorsSubscriberSpec.php
- Rename `ComputeDescendantCompletenessAndIndexProductAndAncestorsSubscriber` into `ComputeProductAndAncestorsSubscriber` and split in 2 (1 for save, 1 for remove events)
- Re-organize listeners in sub directories
The queries re-organization will be in next PR  
| Tech Doc …
> TIP-1287: refactor listeners

- tests/back/Integration/IntegrationTestsBundle/Loader/FixturesLoader.php
- tests/back/Integration/IntegrationTestsBundle/Resources/config/services.yml
Please have a look to https://github.com/symfony/symfony/issues/31765
> TIP-1262 Do not use getenv because it returns false in SF 4.3

- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/family/form/attributes/attributes.js
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/Grid.less
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/family/tab/attributes/attributes.html
- tests/legacy/features/Context/Page/Family/Edit.php
> AOB-638: Upgrade UI

- Dockerfile
- Makefile
Add to yarn install the `--frozen-lockfile` flag to ensure reproducible dependencies.
> Add frozen-lockfile flag to yarn install

- Dockerfile
- docker-compose.yml
- internal_doc/tests/running_performance_profile.md
Installed done following the documentation of Blackfire here:
https://blackfire.io/docs/integrations/docker
> Install blackfire in dev image

- .circleci/config.yml
- composer.json
- composer.lock
- make-file/dev.mk
- src/Acme/Bundle/AppBundle/Resources/config/savers.yml
- tests/legacy/features/Behat/Context/ImportExportFileContext.php
- tests/legacy/features/Behat/Context/MassEditJobContext.php
- tests/legacy/features/Behat/Context/NavigationContext.php
- tests/legacy/features/Behat/Context/PimContext.php
- tests/legacy/features/Context/FeatureContext.php
- tests/legacy/features/Context/SecurityContext.php
> TIP-1262 Make behat scenarios pass again

- .eslintignore
- tests/front/acceptance/cucumber/world.js
> PIM-8842: Fix js lint ignore

- composer.lock
- src/Akeneo/Apps/back/Application/Command/CreateAppCommand.php
- src/Akeneo/Apps/back/Application/Command/CreateAppHandler.php
- src/Akeneo/Apps/back/Application/Query/FetchAppsHandler.php
- src/Akeneo/Apps/back/Application/Query/FetchAppsQuery.php
- src/Akeneo/Apps/back/Domain/Model/App.php
- src/Akeneo/Apps/back/Domain/Model/AppCode.php
- src/Akeneo/Apps/back/Domain/Model/AppLabel.php
- src/Akeneo/Apps/back/Domain/Model/FlowType.php
- src/Akeneo/Apps/back/Domain/Persistence/Repository/AppRepository.php
- src/Akeneo/Apps/back/Infrastructure/Cli/AppCommand.php
- src/Akeneo/Apps/back/Infrastructure/Install/InstallSubscriber.php
- src/Akeneo/Apps/back/Infrastructure/Install/Query/CreateAppsTableQuery.php
- src/Akeneo/Apps/back/Infrastructure/Persistence/Dbal/DbalAppRepository.php
- src/Akeneo/Apps/back/Infrastructure/Symfony/DependencyInjection/AkeneoAppsExtension.php
- src/Akeneo/Apps/back/Infrastructure/Symfony/Resources/config/cli.yml
- src/Akeneo/Apps/back/Infrastructure/Symfony/Resources/config/handlers.yml
- src/Akeneo/Apps/back/Infrastructure/Symfony/Resources/config/install.yml
- src/Akeneo/Apps/back/Infrastructure/Symfony/Resources/config/repositories.yml
- upgrades/schema/Version_4_0_20191014111427_create_apps_table.php
> API-650: Create and Fetch Apps

- .circleci/config.yml
- composer.json
- config/services/test_fake/services.yml
- make-file/apps.mk
- src/Akeneo/Apps/back/Domain/Model/Write/FlowType.php
- src/Akeneo/Apps/back/Infrastructure/Cli/AppCommand.php
- src/Akeneo/Apps/back/Infrastructure/Persistence/Dbal/Repository/DbalAppRepository.php
- src/Akeneo/Apps/back/Infrastructure/Persistence/InMemory/Repository/InMemoryAppRepository.php
- src/Akeneo/Apps/back/Infrastructure/Symfony/Resources/config/handlers.yml
- src/Akeneo/Apps/back/Infrastructure/Symfony/Resources/config/repositories.yml
- src/Akeneo/Apps/back/tests/Acceptance/Context/AppContext.php
- src/Akeneo/Apps/back/tests/Acceptance/Resources/config/repositories.yml
- src/Akeneo/Apps/back/tests/Acceptance/behat.yml
- src/Akeneo/Apps/back/tests/Acceptance/features/create_an_app.feature
- src/Akeneo/Apps/back/tests/Acceptance/features/display_the_apps.feature
- src/Akeneo/Apps/back/tests/Unit/spec/Domain/Model/Write/FlowTypeSpec.php
> API-650: Adds acceptance scenarios

- src/Akeneo/Apps/back/Application/Command/CreateAppHandler.php
- src/Akeneo/Apps/back/Application/Service/CreateClientInterface.php
- src/Akeneo/Apps/back/Domain/Model/ClientId.php
- src/Akeneo/Apps/back/Domain/Model/Read/App.php
- src/Akeneo/Apps/back/Domain/Model/Write/App.php
- src/Akeneo/Apps/back/Infrastructure/Client/CreateClient.php
- src/Akeneo/Apps/back/Infrastructure/Install/InstallSubscriber.php
- src/Akeneo/Apps/back/Infrastructure/Install/Query/CreateAppsTableQuery.php
- src/Akeneo/Apps/back/Infrastructure/Persistence/Dbal/Repository/DbalAppRepository.php
- src/Akeneo/Apps/back/Infrastructure/Symfony/DependencyInjection/AkeneoAppsExtension.php
- src/Akeneo/Apps/back/Infrastructure/Symfony/Resources/config/client.yml
- src/Akeneo/Apps/back/Infrastructure/Symfony/Resources/config/handlers.yml
- src/Akeneo/Apps/back/tests/.php_cd.php
- src/Akeneo/Apps/back/tests/Integration/Service/CreateClientIntegration.php
- src/Akeneo/Apps/back/tests/Unit/spec/Application/Command/CreateAppHandlerSpec.php
- src/Akeneo/Apps/back/tests/Unit/spec/Domain/Model/ClientIdSpec.php
- src/Akeneo/Apps/back/tests/Unit/spec/Infrastructure/Client/CreateClientSpec.php
> API-652: Create token automatically

- src/Akeneo/Pim/Enrichment/Bundle/StructureVersion/EventListener/StructureVersionUpdater.php
- tests/back/Pim/Enrichment/Specification/Bundle/StructureVersion/EventListener/StructureVersionUpdaterSpec.php
> PIM-8882: reduce number of useless queries during saveAll

- CHANGELOG-3.0.md
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/steps.yml
Fixes an issue happening on mass actions where the batch size differs from the page size of the PQB's cursor, leading to a Doctrine exception
> PIM-8892: Fix product bulk actions on categories

- src/Akeneo/Pim/Enrichment/Component/Product/ProductModel/Filter/ProductModelAttributeFilter.php
- tests/back/Pim/Enrichment/Specification/Component/Product/ProductModel/Filter/ProductAttributeFilterSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/ProductModel/Filter/ProductModelAttributeFilterSpec.php
Fix product model attribute filter when the attribute name is numeric.
> Fix product model attribute filter

- src/Akeneo/Apps/back/Application/Command/CreateAppHandler.php
- src/Akeneo/Apps/back/Domain/Model/ValueObject/AppCode.php
- src/Akeneo/Apps/back/Domain/Model/ValueObject/AppLabel.php
- src/Akeneo/Apps/back/Domain/Model/ValueObject/ClientId.php
- src/Akeneo/Apps/back/Domain/Model/ValueObject/FlowType.php
- src/Akeneo/Apps/back/Domain/Model/Write/App.php
- src/Akeneo/Apps/back/Domain/Validation/App/AppCodeMustBeValid.php
- src/Akeneo/Apps/back/Domain/Validation/App/AppLabelMustBeValid.php
- src/Akeneo/Apps/back/Domain/Validation/App/FlowTypeMustBeValid.php
- src/Akeneo/Apps/back/Infrastructure/Client/CreateClient.php
- src/Akeneo/Apps/back/tests/Integration/Persistence/DbalAppRepositoryIntegration.php
- src/Akeneo/Apps/back/tests/Unit/spec/Application/Command/CreateAppHandlerSpec.php
- src/Akeneo/Apps/back/tests/Unit/spec/Domain/Model/ValueObject/AppCodeSpec.php
- src/Akeneo/Apps/back/tests/Unit/spec/Domain/Model/ValueObject/AppLabelSpec.php
- src/Akeneo/Apps/back/tests/Unit/spec/Domain/Model/ValueObject/ClientIdSpec.php
- src/Akeneo/Apps/back/tests/Unit/spec/Domain/Model/ValueObject/FlowTypeSpec.php
- src/Akeneo/Apps/back/tests/Unit/spec/Domain/Model/Write/AppSpec.php
> API-650: Rework constructors

- make-file/apps.mk
- phpunit.xml.dist
- src/Akeneo/Apps/back/Application/Command/CreateAppHandler.php
- src/Akeneo/Apps/back/Domain/Model/Read/App.php
- src/Akeneo/Apps/back/Domain/Model/ValueObject/AppCode.php
- src/Akeneo/Apps/back/Domain/Model/ValueObject/AppId.php
- src/Akeneo/Apps/back/Domain/Model/ValueObject/AppLabel.php
- src/Akeneo/Apps/back/Domain/Model/ValueObject/ClientId.php
- src/Akeneo/Apps/back/Domain/Model/ValueObject/FlowType.php
- src/Akeneo/Apps/back/Domain/Model/Write/App.php
- src/Akeneo/Apps/back/Domain/Persistence/Repository/AppRepository.php
- src/Akeneo/Apps/back/Domain/Validation/App/AppCodeMustBeValid.php
- src/Akeneo/Apps/back/Domain/Validation/App/AppLabelMustBeValid.php
- src/Akeneo/Apps/back/Domain/Validation/App/FlowTypeMustBeValid.php
- src/Akeneo/Apps/back/Infrastructure/Client/CreateClient.php
- src/Akeneo/Apps/back/Infrastructure/Install/Query/CreateAppsTableQuery.php
- src/Akeneo/Apps/back/Infrastructure/Persistence/Dbal/Repository/DbalAppRepository.php
- src/Akeneo/Apps/back/Infrastructure/Persistence/InMemory/Repository/InMemoryAppRepository.php
- src/Akeneo/Apps/back/tests/.php_cd.php
- src/Akeneo/Apps/back/tests/Integration/Persistence/DbalAppRepositoryIntegration.php
- src/Akeneo/Apps/back/tests/Unit/spec/Application/Command/CreateAppHandlerSpec.php
- src/Akeneo/Apps/back/tests/Unit/spec/Application/Query/FetchAppsHandlerSpec.php
- src/Akeneo/Apps/back/tests/Unit/spec/Domain/Model/Read/AppSpec.php
- src/Akeneo/Apps/back/tests/Unit/spec/Domain/Model/ValueObject/AppCodeSpec.php
- src/Akeneo/Apps/back/tests/Unit/spec/Domain/Model/ValueObject/AppLabelSpec.php
- src/Akeneo/Apps/back/tests/Unit/spec/Domain/Model/ValueObject/ClientIdSpec.php
- src/Akeneo/Apps/back/tests/Unit/spec/Domain/Model/ValueObject/FlowTypeSpec.php
- src/Akeneo/Apps/back/tests/Unit/spec/Domain/Model/Write/AppSpec.php
> API-650: Generate UUID for Apps

- .circleci/config.yml
- .circleci/find_non_executed_phpspec.sh
- config/services/test_fake/services.yml
- make-file/apps.mk
- make-file/dev.mk
- phpspec.yml.dist
- phpunit.xml.dist
- src/Akeneo/Apps/back/Domain/Model/Write/App.php
- src/Akeneo/Apps/back/Infrastructure/Client/Fake/CreateClient.php
- src/Akeneo/Apps/back/Infrastructure/Client/Fos/CreateClient.php
- src/Akeneo/Apps/back/Infrastructure/InternalApi/Controller/AppController.php
- src/Akeneo/Apps/back/Infrastructure/Symfony/Resources/config/client.yml
- src/Akeneo/Apps/back/tests/Acceptance/Resources/config/services.yml
- src/Akeneo/Apps/back/tests/Unit/spec/Infrastructure/Client/Fos/CreateClientSpec.php
- src/Akeneo/Apps/back/tests/phpspec.yml.dist
> API-650: Fix not executed phpspec + Fix phpcs

- src/Akeneo/Apps/back/Application/Command/CreateAppHandler.php
- src/Akeneo/Apps/back/Application/Service/CreateUserInterface.php
- src/Akeneo/Apps/back/Domain/Model/ValueObject/UserId.php
- src/Akeneo/Apps/back/Domain/Model/Write/App.php
- src/Akeneo/Apps/back/Infrastructure/Cli/AppCommand.php
- src/Akeneo/Apps/back/Infrastructure/Install/Query/CreateAppsTableQuery.php
- src/Akeneo/Apps/back/Infrastructure/Persistence/Dbal/Repository/DbalAppRepository.php
- src/Akeneo/Apps/back/Infrastructure/Persistence/InMemory/Repository/InMemoryAppRepository.php
- src/Akeneo/Apps/back/Infrastructure/Symfony/DependencyInjection/AkeneoAppsExtension.php
- src/Akeneo/Apps/back/Infrastructure/Symfony/Resources/config/client.yml
- src/Akeneo/Apps/back/Infrastructure/Symfony/Resources/config/handlers.yml
- src/Akeneo/Apps/back/Infrastructure/Symfony/Resources/config/services.yml
- src/Akeneo/Apps/back/Infrastructure/User/Fake/CreateUser.php
- src/Akeneo/Apps/back/Infrastructure/User/Internal/CreateUser.php
- src/Akeneo/Apps/back/tests/.php_cd.php
- src/Akeneo/Apps/back/tests/Acceptance/Resources/config/services.yml
- src/Akeneo/Apps/back/tests/Integration/Persistence/Repository/DbalAppRepositoryIntegration.php
- src/Akeneo/Apps/back/tests/Integration/Service/CreateUserIntegration.php
- src/Akeneo/Apps/back/tests/Unit/spec/Application/Command/CreateAppHandlerSpec.php
- src/Akeneo/Apps/back/tests/Unit/spec/Domain/Model/ValueObject/UserIdSpec.php
- src/Akeneo/Apps/back/tests/Unit/spec/Domain/Model/Write/AppSpec.php
- src/Akeneo/Apps/back/tests/Unit/spec/Infrastructure/User/Internal/CreateUserSpec.php
> API-708: Create new user when creating a new app

- CHANGELOG-2.3.md
- src/Akeneo/Bundle/BatchQueueBundle/tests/integration/Query/SqlDeleteJobExecutionMessageOrphansQueryIntegration.php
- src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Query/GetChannelActiveLocaleCodes.php
- src/Pim/Bundle/CatalogBundle/EventSubscriber/RemoveLocaleFilterInJobInstancesSubscriber.php
- src/Pim/Bundle/CatalogBundle/tests/integration/EventSubscriber/RemoveAttributeFiltersInJobInstancesOnAttributeDeletionIntegration.php
- src/Pim/Bundle/CatalogBundle/tests/integration/EventSubscriber/RemoveLocaleFilterInJobInstanceSubscriberIntegration.php
> #10955: Remove database prefix in queries

- src/Akeneo/Pim/Enrichment/Component/Product/ProductModel/Filter/ProductModelAttributeFilter.php
- tests/back/Pim/Enrichment/Specification/Component/Product/ProductModel/Filter/ProductAttributeFilterSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/ProductModel/Filter/ProductModelAttributeFilterSpec.php
Necessary fix to use the data-generator's latest version
> Backport ProductModelAttributeFilter fix

- composer.json
- composer.lock
Adds missing requirement for `symfony/yaml` package. (it was previously not installed with `--no-dev` option)
> Add missing symfony/yaml requirement

- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/column.js
> AOB-645: delegate events for multi menu purpose

- src/Akeneo/Apps/back/Infrastructure/InternalApi/Controller/AppController.php
- src/Akeneo/Apps/back/Infrastructure/Symfony/Resources/config/acl.yml
- src/Akeneo/Apps/back/Infrastructure/Symfony/Resources/config/acl_groups.yml
- src/Akeneo/Apps/back/Infrastructure/Symfony/Resources/config/controllers.yml
- src/Akeneo/Apps/back/Infrastructure/Symfony/Resources/config/form_extensions.yml
- src/Akeneo/Apps/back/Infrastructure/Symfony/Resources/translations/messages.en_US.yml
- src/Akeneo/Apps/back/tests/.php_cd.php
> API-719: Add ACL on manage Apps settings

- src/Akeneo/Apps/back/Application/Command/CreateAppHandler.php
- src/Akeneo/Apps/back/Application/Validation/App/CodeMustBeUnique.php
- src/Akeneo/Apps/back/Application/Validation/App/CodeMustBeUniqueValidator.php
- src/Akeneo/Apps/back/Domain/Persistence/Repository/AppRepository.php
- src/Akeneo/Apps/back/Infrastructure/Cli/AppCommand.php
- src/Akeneo/Apps/back/Infrastructure/Persistence/Dbal/Repository/DbalAppRepository.php
- src/Akeneo/Apps/back/Infrastructure/Persistence/InMemory/Repository/InMemoryAppRepository.php
- src/Akeneo/Apps/back/Infrastructure/Symfony/DependencyInjection/AkeneoAppsExtension.php
- src/Akeneo/Apps/back/Infrastructure/Symfony/Resources/config/validation/CreateAppCommand.yml
- src/Akeneo/Apps/back/Infrastructure/Symfony/Resources/config/validators.yml
- src/Akeneo/Apps/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
- src/Akeneo/Apps/back/tests/.php_cd.php
- src/Akeneo/Apps/back/tests/Acceptance/Context/AppContext.php
- src/Akeneo/Apps/back/tests/Acceptance/features/create_an_app.feature
- src/Akeneo/Apps/back/tests/Integration/Persistence/Repository/DbalAppRepositoryIntegration.php
- src/Akeneo/Apps/back/tests/Unit/spec/Application/Validation/App/CodeMustBeUniqueSpec.php
- src/Akeneo/Apps/back/tests/Unit/spec/Application/Validation/App/CodeMustBeUniqueValidatorSpec.php
> API-790: Make Apps code unique

- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/fetcher/attribute-group-fetcher.js
The size limit is not mandatory anymore on this route
> PIM-8693: fix attribute group fetcher

- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/fetcher/attribute-group-fetcher.js
> DO NOT MERGE, ONLY FOR CI PURPOSE

- src/Akeneo/Apps/back/Domain/Model/ValueObject/AppLabel.php
- src/Akeneo/Apps/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
- src/Akeneo/Apps/back/tests/Unit/spec/Domain/Model/ValueObject/AppLabelSpec.php
- src/Akeneo/Apps/back/tests/Unit/spec/Domain/Validation/App/AppCodeMustBeValidSpec.php
- src/Akeneo/Apps/back/tests/Unit/spec/Domain/Validation/App/AppLabelMustBeValidSpec.php
> API-818: App label should be mandatory

- composer.json
- composer.lock
> Fix circular reference

- src/Akeneo/Pim/Enrichment/Component/Product/Factory/NonExistentValuesFilter/NonExistentFileValueFilter.php
- src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/FileValueFactory.php
- src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/ImageValueFactory.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Factory/NonExistentValuesFilter/NonExistentFileValueFilterSpec.php
> Improve the hydration of the products by reducing the number of IO to load the files

- make-file/apps.mk
- src/Akeneo/Apps/back/Application/Command/UpdateAppHandler.php
- src/Akeneo/Apps/back/Application/Query/FetchAppsHandler.php
- src/Akeneo/Apps/back/Domain/Model/Read/AppWithCredentials.php
- src/Akeneo/Apps/back/Domain/Model/Write/App.php
- src/Akeneo/Apps/back/Domain/Persistence/Repository/AppRepository.php
- src/Akeneo/Apps/back/Infrastructure/Install/FileSystemAssetsInstaller.php
- src/Akeneo/Apps/back/Infrastructure/Persistence/Dbal/Repository/DbalAppRepository.php
- src/Akeneo/Apps/back/Infrastructure/Persistence/InMemory/Query/InMemorySelectAppWithCredentialsByCodeQuery.php
- src/Akeneo/Apps/back/Infrastructure/Persistence/InMemory/Repository/InMemoryAppRepository.php
- src/Akeneo/Apps/back/Infrastructure/Symfony/DependencyInjection/AkeneoAppsExtension.php
- src/Akeneo/Apps/back/Infrastructure/Symfony/Resources/config/handlers.yml
- src/Akeneo/Apps/back/Infrastructure/Symfony/Resources/config/validation/UpdateAppCommand.yml
- src/Akeneo/Apps/back/tests/Acceptance/Context/AppContext.php
- src/Akeneo/Apps/back/tests/Acceptance/behat.yml
- src/Akeneo/Apps/back/tests/Acceptance/features/create_an_app.feature
- src/Akeneo/Apps/back/tests/Acceptance/features/update_an_app.feature
- src/Akeneo/Apps/back/tests/Integration/Client/Fos/CreateClientIntegration.php
- src/Akeneo/Apps/back/tests/Integration/Persistence/Dbal/Repository/DbalAppRepositoryIntegration.php
- src/Akeneo/Apps/back/tests/Unit/spec/Application/Command/CreateAppHandlerSpec.php
- src/Akeneo/Apps/back/tests/Unit/spec/Application/Command/UpdateAppHandlerSpec.php
- src/Akeneo/Apps/back/tests/Unit/spec/Application/Query/FetchAppsHandlerSpec.php
- src/Akeneo/Apps/back/tests/Unit/spec/Application/Query/FindAnAppHandlerSpec.php
- src/Akeneo/Apps/back/tests/Unit/spec/Domain/Model/Read/AppWithCredentialsSpec.php
- src/Akeneo/Apps/back/tests/Unit/spec/Domain/Model/Write/AppSpec.php
> API-816: Modify an App [back]

- src/Akeneo/Apps/back/Infrastructure/InternalApi/Controller/AppController.php
- src/Akeneo/Apps/back/Infrastructure/Symfony/Resources/config/controllers.yml
- src/Akeneo/Apps/back/Infrastructure/Symfony/Resources/config/routing_rest.yml
> API-817: Modify an app routing

- src/Akeneo/Platform/config/bundles/liip_imagine.yml
> PIM-8675: add pdf thumbnail support

- internal_doc/enrichment/add_new_attribute_type.md
Adds documentation about extensibility of indexation for custom attribute types
> Document indexation extensibility

- README.md
Fixes the link to the test documentation. 
> Fix the test doc link

- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/base/variables.less
https://github.com/akeneo/pim-enterprise-dev/pull/7152
> DAPI-545: add 2 official green variations

- internal_doc/enrichment/extend_search_engine_format.md
> Document the extensibility of the elasticsearch format for products and product models

- CHANGELOG-3.2.md
- src/Akeneo/Platform/CommunityRequirements.php
https://akeneo.atlassian.net/browse/PIM-6902
> PIM-6902: Add requirement for ES aliases

- CHANGELOG-3.2.md
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/controller/group.js
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/error.js
- src/Akeneo/Platform/CommunityRequirements.php
This page was completely broken.
I use the dedicated service to display error message instead of Modals.
Screenshots are in the ticket https://akeneo.atlassian.net/browse/PIM-8961
> PIM-8961: Fix design of 403 error page

- Dockerfile
- src/Akeneo/Platform/PimRequirements.php
Adds ghostscript dependency in the dockerfile and checks it is installed and has minimum version.
> PIM-8960: Check the GS dependency is installed and has minimum version

- upgrades/schema/Version_4_0_20191031124707_update_from_clients_to_apps.php
> API: Fix migration from id to code

- src/Akeneo/Apps/back/Infrastructure/InternalApi/Controller/AppController.php
- src/Akeneo/Apps/back/Infrastructure/Symfony/Resources/config/controllers.yml
- src/Akeneo/Apps/back/Infrastructure/Symfony/Resources/config/routing_rest.yml
> API-833: Adds routing + controller to regenerate secret

- src/Akeneo/UserManagement/Bundle/Controller/Rest/UserController.php
- src/Akeneo/UserManagement/Bundle/Security/UserProvider.php
- tests/back/Acceptance/User/InMemoryUserRepository.php
- tests/back/Acceptance/spec/User/InMemoryUserRepositorySpec.php
- tests/back/UserManagement/Specification/Bundle/Security/UserProviderSpec.php
see https://akeneo.atlassian.net/browse/PIM-8956
> PIM-8956: Fix security vulnerability

- src/Akeneo/UserManagement/Bundle/Security/UserProvider.php
- tests/back/Acceptance/User/InMemoryUserRepository.php
- tests/back/Acceptance/spec/User/InMemoryUserRepositorySpec.php
- tests/back/UserManagement/Specification/Bundle/Security/UserProviderSpec.php
see https://akeneo.atlassian.net/browse/PIM-8955
> PIM-8955: Fix security vulnerability

- src/Akeneo/Apps/back/Infrastructure/Symfony/Resources/config/handlers.yml
> API-833: Remove public services

- make-file/apps.mk
- src/Akeneo/Apps/back/Infrastructure/Symfony/Resources/config/routing_rest.yml
- src/Akeneo/Apps/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
- src/Akeneo/Apps/front/src/application/apps/components/AppEditForm.tsx
- src/Akeneo/Apps/front/src/application/apps/pages/AppEdit.tsx
- src/Akeneo/Apps/front/src/application/apps/use-update-app.ts
- src/Akeneo/Apps/front/src/application/common/components/PageHeader.tsx
- src/Akeneo/Apps/front/src/application/common/components/form/FormControlInfo.tsx
- src/Akeneo/Apps/front/src/application/shared/fetch/use-fetch.ts
- src/Akeneo/Apps/front/src/application/shared/router/router-context.ts
- src/Akeneo/Apps/front/tests/unit/application/apps/components/AppEditForm.spec.tsx
- src/Akeneo/Apps/front/tests/unit/application/apps/components/__snapshots__/AppEditForm.spec.tsx.snap
- src/Akeneo/Apps/front/tests/unit/application/common/__snapshots__/PageHeader.spec.tsx.snap
New page to edit App settings.
> API-656: Edit App settings

- bin/benchmark_products_api.sh
Use docker image data generator 1.0.
See PIM compatibility https://github.com/akeneo/akeneo-data-generator#pim-compatibility 
> Fix data generator docker image

- bin/benchmark_products_api.sh
Use docker image data generator 2.0.
See PIM compatibility https://github.com/akeneo/akeneo-data-generator#pim-compatibility
:warning: Merge after https://github.com/akeneo/akeneo-data-generator/pull/88 and check that the image is created on docker hub …
> Fix data-generator docker image

- src/Akeneo/UserManagement/Bundle/Resources/views/Role/update.html.twig
> PIM-8914: re-enable acls on assets

- src/Akeneo/Apps/front/src/application/common/components/Figure.tsx
- src/Akeneo/Apps/front/src/application/common/components/Section.tsx
- src/Akeneo/Apps/front/src/application/common/components/form/FormControlInfo.tsx
- src/Akeneo/Apps/front/src/application/common/theme.ts
- src/Akeneo/Apps/front/src/infrastructure/Apps.tsx
- src/Akeneo/Apps/front/tests/unit/application/apps/components/App.spec.tsx
- src/Akeneo/Apps/front/tests/unit/application/apps/components/AppEditForm.spec.tsx
- src/Akeneo/Apps/front/tests/unit/application/apps/components/AppGrid.spec.tsx
- src/Akeneo/Apps/front/tests/unit/application/common/Figure.spec.tsx
- src/Akeneo/Apps/front/tests/unit/application/common/Section.spec.tsx
- src/Akeneo/Apps/front/tests/utils/create-with-theme.tsx
Add a theme for styled-components on Apps
> Add styled-components theme to Apps

- CHANGELOG-4.0.md
- src/Akeneo/Pim/Enrichment/.php_cd.php
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/connector/processors.yml
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/event_subscribers.yml
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/jobs.yml
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/repositories.yml
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/EnsureConsistentAttributeGroupOrderTasklet.php
- src/Akeneo/Pim/Structure/Bundle/DependencyInjection/AkeneoPimStructureExtension.php
- src/Akeneo/Pim/Structure/Bundle/Resources/config/event_subscribers.yml
- src/Akeneo/Pim/Structure/Bundle/Resources/config/processors.yml
- src/Akeneo/Pim/Structure/Bundle/Resources/config/queries.yml
- src/Akeneo/Pim/Structure/Bundle/Resources/config/repositories.yml
- src/Akeneo/Pim/Structure/Bundle/Resources/config/services.yml
- src/Akeneo/Pim/Structure/Bundle/Storage/Sql/FamilyVariantsByAttributeAxes.php
- src/Akeneo/Pim/Structure/Bundle/Storage/Sql/FindAttributeGroupOrdersEqualOrSuperiorTo.php
- src/Akeneo/Pim/Structure/Bundle/Storage/Sql/SqlFindAttributeGroupOrdersEqualOrSuperiorTo.php
- src/Akeneo/Pim/Structure/Component/AttributeGroup/Query/FindAttributeGroupOrdersEqualOrSuperiorTo.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Job/EnsureConsistentAttributeGroupOrderTaskletSpec.php
- tests/back/Pim/Structure/Integration/AttributeGroup/Query/FindAttributeGroupOrdersEqualOrSuperiorToIntegration.php
- tests/back/Pim/Structure/Integration/AttributeGroup/Query/SqlFindAttributeGroupOrdersEqualOrSuperiorToIntegration.php
- tests/back/Pim/Structure/Specification/Bundle/Storage/Sql/FamilyVariantsByAttributeAxesSpec.php
Refactor and clean structure
- Move sql query from `Doctrine` namespace to `Storage` in Structure bounded context (same as Enrichment`)
- Move some services declared in Enrichment to Structure …
> Clean structure services

- CHANGELOG-3.0.md
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/common/select2/family.js
- src/Akeneo/UserManagement/Bundle/Controller/Rest/UserController.php
- src/Akeneo/UserManagement/Bundle/Resources/config/controllers.yml
- src/Akeneo/UserManagement/Bundle/Security/UserProvider.php
- tests/back/UserManagement/Specification/Bundle/Security/UserProviderSpec.php
> Merge 3.0 into 3.2

- make-file/apps.mk
- make-file/test.mk
Enable **Apps** front tests on CircleCI
> Enable Apps front tests on circleci

- src/Oro/Bundle/PimDataGridBundle/Datasource/DatasourceAdapterResolver.php
- src/Oro/Bundle/PimDataGridBundle/Datasource/DatasourceAdapterResolverInterface.php
- src/Oro/Bundle/PimDataGridBundle/Extension/Filter/FilterExtension.php
- src/Oro/Bundle/PimDataGridBundle/Extension/Pager/PagerExtension.php
- src/Oro/Bundle/PimDataGridBundle/Extension/Pager/PagerResolver.php
- src/Oro/Bundle/PimDataGridBundle/Extension/Pager/PagerResolverInterface.php
Because we need to decorate the resolvers in the Onboarder.
See https://github.com/akeneo/pim-onboarder/pull/331
> AOB-739: Introduce interfaces for DatasourceAdapterResolver and PagerResolver

- CHANGELOG-3.0.md
- src/Akeneo/UserManagement/Bundle/Controller/Rest/UserController.php
- tests/legacy/features/user-management/user/edit_user.feature
Backport of https://github.com/akeneo/pim-community-dev/pull/11036 done in 3.2
> PIM-8991: Forbid user without 'list users' permission to access other user data

- src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ElasticsearchProjection/GetElasticsearchProductProjection.php
- tests/back/Pim/Enrichment/Upgrade/RemoveComputeProductModelDescendantJobsIntegration.php
> Fix prefix due to fail during database installation

- src/Akeneo/Apps/back/Infrastructure/InternalApi/Controller/AppController.php
- src/Akeneo/Apps/back/Infrastructure/Symfony/Resources/config/controllers.yml
- src/Akeneo/Apps/back/Infrastructure/Symfony/Resources/config/routing_rest.yml
> API 659: Add internal API

- src/Akeneo/Apps/back/Application/Command/CreateAppHandler.php
- src/Akeneo/Apps/back/Application/Service/CreateClientInterface.php
- src/Akeneo/Apps/back/Domain/Model/Read/AppWithCredentials.php
- src/Akeneo/Apps/back/Domain/Model/Read/Client.php
- src/Akeneo/Apps/back/Domain/Model/Write/App.php
- src/Akeneo/Apps/back/Infrastructure/Client/Fake/CreateClient.php
- src/Akeneo/Apps/back/Infrastructure/Client/Fos/CreateClient.php
- src/Akeneo/Apps/back/Infrastructure/Persistence/Dbal/Query/DbalSelectAppWithCredentialsByCodeQuery.php
- src/Akeneo/Apps/back/Infrastructure/Persistence/Dbal/Repository/DbalAppRepository.php
- src/Akeneo/Apps/back/Infrastructure/Persistence/InMemory/Query/InMemorySelectAppWithCredentialsByCodeQuery.php
- src/Akeneo/Apps/back/Infrastructure/Persistence/InMemory/Repository/InMemoryAppRepository.php
- src/Akeneo/Apps/back/tests/EndToEnd/App/DeleteAppEndToEnd.php
- src/Akeneo/Apps/back/tests/EndToEnd/App/RegenerateAppClientSecretEndToEnd.php
- src/Akeneo/Apps/back/tests/Integration/Client/Fos/CreateClientIntegration.php
- src/Akeneo/Apps/back/tests/Integration/Fixtures/AppLoader.php
- src/Akeneo/Apps/back/tests/Integration/Persistence/Dbal/Query/DbalSelectAppWithCredentialsByCodeQueryIntegration.php
- src/Akeneo/Apps/back/tests/Integration/Persistence/Dbal/Repository/DbalAppRepositoryIntegration.php
- src/Akeneo/Apps/back/tests/Integration/User/Internal/CreateUserIntegration.php
- src/Akeneo/Apps/back/tests/Unit/spec/Application/Command/CreateAppHandlerSpec.php
- src/Akeneo/Apps/back/tests/Unit/spec/Application/Command/DeleteAppHandlerSpec.php
- src/Akeneo/Apps/back/tests/Unit/spec/Application/Command/RegenerateAppSecretHandlerSpec.php
- src/Akeneo/Apps/back/tests/Unit/spec/Application/Command/UpdateAppHandlerSpec.php
- src/Akeneo/Apps/back/tests/Unit/spec/Application/Query/FindAnAppHandlerSpec.php
- src/Akeneo/Apps/back/tests/Unit/spec/Application/Validation/App/CodeMustBeUniqueValidatorSpec.php
- src/Akeneo/Apps/back/tests/Unit/spec/Domain/Model/Read/AppWithCredentialsSpec.php
- src/Akeneo/Apps/back/tests/Unit/spec/Domain/Model/Write/AppSpec.php
- src/Akeneo/Apps/back/tests/Unit/spec/Infrastructure/Client/Fos/CreateClientSpec.php
> API-873: CreateAnApp should return AppCredentials

- src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/validators.en_US.yml
- tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/PartialUpdateListProductEndToEnd.php
- tests/features/pim/enrichment/product/value/product_identifier.feature
> PIM-8894: Fix error message for leading/trailing in SKU validator

- src/Akeneo/Apps/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
- src/Akeneo/Apps/front/src/application/apps/components/AppCredentials.tsx
- src/Akeneo/Apps/front/src/application/apps/components/credentials/CopiableCredential.tsx
- src/Akeneo/Apps/front/src/application/apps/components/credentials/Credential.tsx
- src/Akeneo/Apps/front/src/application/apps/components/credentials/CredentialList.tsx
- src/Akeneo/Apps/front/src/application/apps/copy-text-to-clipboard.ts
- src/Akeneo/Apps/front/src/application/apps/pages/AppEdit.tsx
- src/Akeneo/Apps/front/src/domain/apps/app-credentials.interface.ts
> API-875: Add username/password to Apps credentials

- CHANGELOG-4.0.md
- src/Akeneo/Platform/Bundle/ImportExportBundle/Controller/Ui/JobTrackerController.php
- src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/controllers.yml
- src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/routing/ui/job_tracker.yml
Linked to this PR:
https://github.com/akeneo/pim-community-dev/pull/11006/files#diff-81cda84ee54e550727808587e4fecf35L4
The "download" button of export does not work anymore from the job tracker page.
I put code back.
> Put back removed code

- package.json
- yarn.lock
> AST-141: bump typescript version to 3.7

- src/Akeneo/Tool/Bundle/MeasureBundle/Resources/config/measure.yml
- src/Akeneo/Tool/Bundle/MeasureBundle/tests/EndToEnd/ExternalApi/ListMeasureFamilyEndToEnd.php
Adding two new types of metrics: Time and Brightness
| Added legacy Behats               | No
| Added acceptance tests            | No
| Micro Demo to the PO (Story only) | No
> Time and Brightness unit metrics

- .circleci/run_behat.sh
- tests/legacy/features/user-management/role/edit_user_role_assignations.feature
Makes behat fails on undefined steps.
> Makes behat fails on undefined steps

- src/Akeneo/Apps/back/Infrastructure/Install/Query/CreateAppsTableQuery.php
- upgrades/schema/Version_4_0_20191014111427_create_apps_table.php
| Migration script                  | OK
> API-885: Separate install queries and migration scripts

- src/Akeneo/Apps/back/Application/Command/CreateAppHandler.php
- src/Akeneo/Apps/back/Application/Service/CreateUserInterface.php
- src/Akeneo/Apps/back/Infrastructure/User/Internal/CreateUser.php
- src/Akeneo/Apps/back/tests/Unit/spec/Infrastructure/User/Internal/CreateUserSpec.php
- src/Akeneo/UserManagement/Bundle/Resources/config/model/doctrine/User.orm.yml
- src/Akeneo/UserManagement/Component/Model/User.php
- tests/back/UserManagement/Specification/Component/Model/UserSpec.php
- upgrades/schema/Version_4_0_20191013162543_update_user_table.php
I moved the migration script before the apps' creation as our migration script calls the Apps' creation command.
As it uses the new user it eases the migration process.
`-`: …
> API-769: Adds type column in user table

- src/Akeneo/UserManagement/Bundle/Resources/config/model/doctrine/User.orm.yml
- upgrades/schema/Version_4_0_20191013162543_update_user_table.php
> API-769: Change SQL type column by user_type

- src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/Persistence/Query/Sql/CountUsers.php
- src/Akeneo/UserManagement/Component/Model/User.php
- tests/back/Platform/Integration/CatalogVolumeMonitoring/Persistence/Query/CountUsersIntegration.php
- tests/back/Platform/Specification/Bundle/CatalogVolumeMonitoringBundle/Persistence/Query/Sql/CountUsersSpec.php
> API-882: Change SQL query in the system info

- .circleci/config.yml
- .circleci/detect_structure_changes.sh
- composer.json
- composer.lock
- make-file/test.mk
- phpunit.xml.dist
- upgrades/schema/Version_4_0_20190813091149_remove_missing_attributes_and_ratio_from_completeness.php
- upgrades/schema/Version_4_0_20190822090606_update_empty_raw_values.php
- upgrades/test_schema/ExecuteMigrationTrait.php
- upgrades/test_schema/Version_4_0_20190916122239_remove_product_empty_raw_values_Integration.php
- upgrades/test_schema/Version_4_0_20190917080512_remove_product_model_empty_raw_values_Integration.php
- upgrades/test_schema/Version_4_0_20191004145507_remove_compute_model_descendant_jobs_Integration.php
What's done here:
- TIP-1291: define a migration tests policy
- TIP-1291: define a dedicated suite and job for data migration tests 
- TIP-1293: fix detection of missing structure migrations for EE
For the full description please read https://github.com/akeneo/pim-enterprise-dev/blob/6defd7801598072c3d752437748b519c9a28f699/internal_doc/migrations.md
> TIP-1291/TIP-1293: about migrations

- composer.json
- composer.lock
See https://github.com/advisories/GHSA-79gr-58r3-pwm3 for detailled information
> PIM-9012: Use Symfony ^3.4.35 to fix CVE

- src/Akeneo/Apps/back/Domain/Model/ValueObject/AppCode.php
- src/Akeneo/Apps/back/Domain/Model/ValueObject/AppLabel.php
- src/Akeneo/Apps/back/tests/Unit/spec/Domain/Model/ValueObject/AppCodeSpec.php
- src/Akeneo/Apps/back/tests/Unit/spec/Domain/Model/ValueObject/AppLabelSpec.php
> API-845: Avoid app code & label that have less than 3 characters

- src/Akeneo/Apps/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
- src/Akeneo/Apps/front/src/application/apps/actions/apps-actions.ts
- src/Akeneo/Apps/front/src/application/apps/api-hooks/use-delete-app.ts
- src/Akeneo/Apps/front/src/application/apps/pages/AppDelete.tsx
- src/Akeneo/Apps/front/src/application/apps/pages/AppEdit.tsx
- src/Akeneo/Apps/front/src/application/apps/pages/Index.tsx
- src/Akeneo/Apps/front/src/application/apps/reducers/apps-reducer.ts
- src/Akeneo/Apps/front/src/application/common/components/button/SecondaryActionsButton.tsx
- src/Akeneo/Apps/front/src/application/common/components/index.ts
- src/Akeneo/Apps/front/src/application/shared/fetch-result/fetch-result.ts
- src/Akeneo/Apps/front/src/application/shared/translate/index.ts
- src/Akeneo/Apps/front/src/application/shared/translate/use-translate.ts
- src/Akeneo/Apps/front/src/infrastructure/Apps.tsx
Add delete app action & confirmation modal
> API-874: Add delete app action

- composer.lock
- src/Akeneo/Tool/Bundle/VersioningBundle/Resources/config/model/doctrine/Version.orm.yml
- symfony.lock
- upgrades/schema/Version_4_0_20191205143418_adds_author_index_on_versioning_table.php
> API-891: Adds index on author on versioning table

- tests/back/Integration/IntegrationTestsBundle/DependencyInjection/MakeServicesPublicForTestEnv.php
- tests/back/Integration/TestCase.php
- tests/legacy/features/Behat/Context/HookContext.php
Allow to make public services with FQCN name `Akeneo\...`
> TIP 1271: add HTTP endpoint to check PIM availability

- .circleci/run_phpunit.sh
- config/services/test/test_services.yml
- tests/back/Integration/IntegrationTestsBundle/Loader/FixturesLoader.php
In order to improve test isolation, use docker-run instead of docker exec.
It increases the time to execute tests from 7m40 to 8m53 in EE.
It increases the time to execute tests from 16m50 to 19m30 in EE. …
> Run phpunit with docker run

- package.json
- src/Akeneo/Apps/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
- src/Akeneo/Apps/front/src/application/dashboard/actions/apps-actions.ts
- src/Akeneo/Apps/front/src/application/dashboard/app-state-context.ts
- src/Akeneo/Apps/front/src/application/dashboard/components/AppSelect.tsx
- src/Akeneo/Apps/front/src/application/dashboard/components/Chart.tsx
- src/Akeneo/Apps/front/src/application/dashboard/components/Charts.tsx
- src/Akeneo/Apps/front/src/application/dashboard/components/EventChart.tsx
- src/Akeneo/Apps/front/src/application/dashboard/model/source-app.ts
- src/Akeneo/Apps/front/src/application/dashboard/pages/Dashboard.tsx
- src/Akeneo/Apps/front/src/application/dashboard/pages/Index.tsx
- src/Akeneo/Apps/front/src/application/dashboard/reducers/apps-reducer.ts
- src/Akeneo/Apps/front/src/application/shared/router/BreadcrumbRouterLink.tsx
- src/Akeneo/Apps/front/src/infrastructure/Dashboard.tsx
- yarn.lock
> API-886: PoC Victory

- src/Akeneo/Apps/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
- src/Akeneo/Apps/front/src/application/apps/api-hooks/use-update-app.ts
- src/Akeneo/Apps/front/src/application/apps/components/AppCreateForm.tsx
- src/Akeneo/Apps/front/src/application/apps/pages/AppEdit.tsx
Add App code & label length constraints validation
> API-845: Add App code & label length constraints

- src/Akeneo/Platform/Bundle/InstallerBundle/Command/InstallCommand.php
Removes call to deleted command.
> Removes call to deleted command

- package.json
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/base/variables.less
- webpack.config.js
- yarn.lock
For an EE feature, we need to be able to import CSS in TS.
As EE don't have webpack config, I have to put this in CE :man_shrugging:
> ATR-49: Json Editor

- src/Akeneo/Apps/back/tests/EndToEnd/Audit/CountDailyEventsByAppEndToEnd.php
> Fix CI commenting test

- .circleci/config.yml
- bin/check-services-instantiability
- config/packages/doctrine.yml
- config/services/pim.yml
- make-file/test.mk
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/updaters.yml
This PR fixes non instantiable services and adds check on the CI.
> Fixes non instantiable services

- src/Akeneo/Apps/front/src/application/dashboard/components/Chart.tsx
- src/Akeneo/Apps/front/src/application/dashboard/components/EventChart.tsx
> API-900: Polish app dashboard graph

- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/images/attribute/icon-mediafile.svg
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/images/attribute/icon-medialink.svg
> AST-182: Fix attribute icon (media-file/media-link)

- src/Akeneo/Apps/back/tests/EndToEnd/Audit/CountDailyEventsByAppEndToEnd.php
- src/Akeneo/Apps/back/tests/EndToEnd/WebTestCase.php
> API: Hotfix e2e test with web test case

- CHANGELOG-4.0.md
- Dockerfile
- src/Akeneo/Platform/PimRequirements.php
> DAPI-687: add Aspell as a PIM requirement

- src/Akeneo/Apps/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
- src/Akeneo/Apps/front/src/application/apps/EventChartThemes.ts
- src/Akeneo/Apps/front/src/application/common/components/select/Dropdown.tsx
- src/Akeneo/Apps/front/src/application/common/components/select/Select.tsx
- src/Akeneo/Apps/front/src/application/common/components/select/Selector.tsx
- src/Akeneo/Apps/front/src/application/dashboard/components/Chart.tsx
- src/Akeneo/Apps/front/src/application/dashboard/components/Charts.tsx
- src/Akeneo/Apps/front/src/application/dashboard/components/EventChart.tsx
- src/Akeneo/Apps/front/src/application/dashboard/reducers/dashboard-reducer.ts
- src/Akeneo/Apps/front/src/domain/audit/audit-event-type.enum.ts
> API-864: Display chart for updated products

- src/Akeneo/Apps/front/src/application/apps/EventChartThemes.ts
- src/Akeneo/Apps/front/src/application/dashboard/components/Chart.tsx
- src/Akeneo/Apps/front/src/application/dashboard/components/Charts.tsx
> API-864: Fix glitches

- src/Akeneo/Apps/back/Domain/Audit/Model/Read/DailyEventCount.php
- src/Akeneo/Apps/back/Infrastructure/InternalApi/Controller/AuditController.php
- src/Akeneo/Apps/back/Infrastructure/Persistence/Dbal/Query/DbalSelectAppsEventCountByDayQuery.php
- src/Akeneo/Apps/back/tests/Unit/spec/Domain/Audit/Model/Read/DailyEventCountSpec.php
- src/Akeneo/Apps/back/tests/Unit/spec/Domain/Audit/Model/Read/WeeklyEventCountsSpec.php
- src/Akeneo/Apps/front/src/application/dashboard/components/Chart.tsx
- src/Akeneo/Apps/front/tests/unit/application/apps/components/NoApp.spec.tsx
- src/Akeneo/Apps/front/tests/unit/application/apps/components/__snapshots__/AppGrid.spec.tsx.snap
- src/Akeneo/Apps/front/tests/unit/application/apps/components/__snapshots__/NoApp.spec.tsx.snap
- src/Akeneo/Apps/front/tests/unit/application/common/__snapshots__/Section.spec.tsx.snap
> API-907: Fix Apps audit API response format

- src/Akeneo/Apps/front/src/application/apps/components/ImageUploader.tsx
- src/Akeneo/Apps/front/src/application/common/components/Figure.tsx
- src/Akeneo/Apps/front/tests/unit/application/apps/components/__snapshots__/App.spec.tsx.snap
- src/Akeneo/Apps/front/tests/unit/application/common/__snapshots__/Figure.spec.tsx.snap
Removes the helper behind the mask when we remove the image.
Add an object-fit cover on the app list.
> API-780: Fix glitch

- config/packages/prod/oneup_flysystem.yml
- config/packages/prod_onprem_paas/doctrine.yml
- config/packages/prod_onprem_paas/monolog.yml
- config/packages/prod_onprem_paas/oneup_flysystem.yml
- config/services/prod/storage.yml
- std-build/Kernel.php
Uses same env as EE to be coherent.
> Makes CE env coherent with EE

- src/Akeneo/Apps/front/src/application/dashboard/components/Chart.tsx
This PR fixes a bad typing with the Victory lib that only triggers on the standard edition build.
> Fix Victory typing

- src/Akeneo/Apps/back/Infrastructure/InternalApi/Controller/AppController.php
- src/Akeneo/Apps/back/Infrastructure/Symfony/Resources/public/js/controller/apps.tsx
- src/Akeneo/Apps/back/Infrastructure/Symfony/Resources/public/js/controller/dashboard.tsx
- src/Akeneo/Apps/back/Infrastructure/Symfony/Resources/public/js/dependencies.ts
- src/Akeneo/Apps/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
- src/Akeneo/Apps/front/src/application/apps/components/AppCredentials.tsx
- src/Akeneo/Apps/front/src/application/apps/components/FlowTypeHelper.tsx
- src/Akeneo/Apps/front/src/application/apps/components/NoApp.tsx
- src/Akeneo/Apps/front/src/application/apps/pages/AppDelete.tsx
- src/Akeneo/Apps/front/src/application/apps/pages/AppEdit.tsx
- src/Akeneo/Apps/front/src/application/apps/pages/AppList.tsx
- src/Akeneo/Apps/front/src/application/apps/pages/AppRegenerateSecret.tsx
- src/Akeneo/Apps/front/src/application/common/components/PageError.tsx
- src/Akeneo/Apps/front/src/application/common/components/index.ts
- src/Akeneo/Apps/front/src/application/common/components/select/OptionWithThumbnail.tsx
- src/Akeneo/Apps/front/src/application/dashboard/components/NoApp.tsx
- src/Akeneo/Apps/front/src/application/dashboard/pages/Dashboard.tsx
- src/Akeneo/Apps/front/src/application/shared/security/SecurityGuard.tsx
- src/Akeneo/Apps/front/src/application/shared/security/index.ts
- src/Akeneo/Apps/front/src/application/shared/security/security-context.ts
- src/Akeneo/Apps/front/src/application/shared/security/security.interface.ts
- src/Akeneo/Apps/front/src/application/shared/security/use-security.ts
- src/Akeneo/Apps/front/src/infrastructure/with-contexts.tsx
- src/Akeneo/Apps/front/tests/unit/application/apps/components/__snapshots__/AppGrid.spec.tsx.snap
- src/Akeneo/Apps/front/tests/unit/application/apps/components/__snapshots__/FlowTypeHelper.spec.tsx.snap
- src/Akeneo/Apps/front/tests/unit/application/apps/components/__snapshots__/NoApp.spec.tsx.snap
- src/Akeneo/Apps/front/tests/unit/application/common/__snapshots__/PageHeader.spec.tsx.snap
- src/Akeneo/Apps/front/tests/unit/application/common/__snapshots__/Section.spec.tsx.snap
Without permission
With permission
> API-914: Add helper message when no connections exist

- src/Akeneo/Apps/front/src/application/dashboard/components/Chart.tsx
> API: Fix graph when events are all the same number

- src/Akeneo/Pim/Enrichment/Bundle/Resources/elasticsearch/product_mapping.yml
> DAPI-540: add product rates in ES mapping

- src/Akeneo/Tool/Bundle/ElasticsearchBundle/Resources/config/services.yml
It prevents to run a migration with the prod container. Not detectable with tests as the test container has all services public (done in an Akeneo compiler pass).
`-`: Not …
> Fix migration script getting a private service

- Dockerfile.base
Dedicated PR needed for the Data quality Insights feature.
This PR has to be merged before the feature branch in order to generate the docker image that will be used by the CI.
> Add Aspell binary and dictionnaries in order to build a new docker image

- docker-compose.yml
> Upgrade to Elasticsearch 7.5

- src/Akeneo/Connectivity/Connection/back/Infrastructure/Install/Query/CreateConnectionAuditTableQuery.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Install/Query/CreateConnectionTableQuery.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/Dbal/Query/DbalExtractConnectionsProductEventCountQuery.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/Dbal/Query/DbalSelectConnectionWithCredentialsByCodeQuery.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/Dbal/Query/DbalSelectConnectionsEventCountByDayQuery.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/Dbal/Query/DbalSelectConnectionsQuery.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/Dbal/Repository/DbalConnectionRepository.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/Dbal/Repository/DbalEventCountRepository.php
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Connection/CreateConnectionEndToEnd.php
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Connection/DeleteConnectionEndToEnd.php
- src/Akeneo/Connectivity/Connection/back/tests/Integration/Fixtures/AuditLoader.php
- src/Akeneo/Connectivity/Connection/back/tests/Integration/Persistence/Dbal/Repository/DbalConnectionRepositoryIntegration.php
> API-924: Rename db tables

- make-file/test.mk
> API-925: Rename Apps in tests Makefile

- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/acl.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/messages.en_US.yml
> API-877: Replace i18n App by Connection

- tests/legacy/features/pim/enrichment/product/datagrid/filtering/filter_products_per_number_fields.feature
- tests/legacy/features/pim/enrichment/product/datagrid/filtering/filter_products_per_price.feature
See https://github.com/akeneo/pim-community-dev/pull/11302
Before 4min for the test.
After 35 sec for the test.
> Improve testing of the filters in the datagrid about prices

- CHANGELOG-3.0.md
- src/Akeneo/Platform/Bundle/ImportExportBundle/Command/PurgeJobExecutionCommand.php
- src/Akeneo/Platform/Bundle/ImportExportBundle/Persistence/Filesystem/DeleteOrphanJobExecutionDirectories.php
- src/Akeneo/Platform/Bundle/ImportExportBundle/Purge/PurgeJobExecution.php
- src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/repositories.yml
- src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/services.yml
- tests/back/Integration/IntegrationTestsBundle/Loader/FixturesLoader.php
- tests/back/Platform/Integration/ImportExport/Persistence/Filesystem/DeleteOrphanJobExecutionDirectoriesIntegration.php
> PIM-9039: Backport of TIP-1201

- src/Akeneo/Connectivity/Connection/back/Application/Settings/Command/RegenerateConnectionPasswordCommand.php
- src/Akeneo/Connectivity/Connection/back/Application/Settings/Command/RegenerateConnectionPasswordHandler.php
- src/Akeneo/Connectivity/Connection/back/Application/Settings/Service/RegenerateUserPassword.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Client/Fos/FosRegenerateClientSecret.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/InternalApi/Controller/ConnectionController.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/controllers.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/handlers.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/services.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/User/Internal/RegenerateUserPassword.php
- src/Akeneo/Connectivity/Connection/back/tests/.php_cd.php
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Connection/RegenerateConnectionUserPasswordEndToEnd.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Settings/Command/RegenerateConnectionPasswordCommandSpec.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Settings/Command/RegenerateConnectionPasswordHandlerSpec.php
| Added e2e tests           | OK
> API-829: Add regenerate app password

- std-build/Kernel.php
- std-build/Makefile
- std-build/install-required-files.sh
Adds the `prod` target for standard distrib, same as EE.
> TIP-1346 Adds same prod target for CE than EE

- src/Akeneo/Pim/Enrichment/Component/Product/Completeness/MaskItemGenerator/DefaultMaskItemGenerator.php
- src/Akeneo/Pim/Enrichment/Component/Product/Factory/NonExistentValuesFilter/NonExistentReferenceDataMultiSelectValuesFilter.php
- src/Akeneo/Pim/Enrichment/Component/Product/ValuesFiller/FillMissingProductModelValues.php
- src/Akeneo/Pim/Enrichment/Component/Product/ValuesFiller/FillMissingProductValues.php
- src/Akeneo/Pim/Structure/Bundle/Resources/config/validators.yml
- src/Akeneo/Pim/Structure/Component/AttributeTypes.php
- tests/front/common/builder/user.js
This PR removes all content related to legacy PAM.
> AST-36: Remove PAM

- tests/legacy/features/pim/enrichment/product/datagrid/filtering/filter_products_per_metric.feature
- tests/legacy/features/pim/enrichment/product/datagrid/filtering/filter_products_per_text_fields.feature
See https://github.com/akeneo/pim-community-dev/pull/11302
Before 2 min/test
After 35 sec/test
> Reduce time to test filters on datagrid

- tests/legacy/features/Pim/Behat/Decorator/TabElement/ComparisonPanelDecorator.php
This step is unstable because the click toggle was closing the dropdown on the second spin.
> PIM-9050: Fix unstable legacy behat test

- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Audit/CountDailyEventsByConnectionEndToEnd.php
> API: Fix audit E2e

- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/attributes.js
https://github.com/akeneo/pim-enterprise-dev/pull/7648
> PIM-8923: Avoid product edit form tab switching when going from product model to products

- src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/Dbal/Query/DbalSelectConnectionsEventCountByDayQuery.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
- src/Akeneo/Connectivity/Connection/back/tests/Integration/Fixtures/AuditLoader.php
- src/Akeneo/Connectivity/Connection/front/src/audit/components/EventChart.tsx
- src/Akeneo/Connectivity/Connection/front/src/common/components/select/Select.tsx
- src/Akeneo/Connectivity/Connection/front/src/shared/date-formatter/use-date-formatter.ts
API-928: Display "All" in chart connections list & API-938: Translate chart date with UI locale
Separated in 2 commits
> API-928: Display "All" in chart connections list & API-938: Translate chart date with UI locale

- src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/Dbal/Repository/DbalEventCountRepository.php
> API-913: Make update on duplicate key for audit

- src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/Dbal/Query/DbalSelectConnectionsEventCountByDayQuery.php
> API-928: Fix sql

- config/packages/liip_imagine.yml
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/attributes/create-button.js
With this PR we now load assets from the correct storage
> AST-19: fix preview generation

- CHANGELOG-4.0.md
> Update changelog with 4.0 new features

- src/Akeneo/Connectivity/Connection/back/Infrastructure/Cli/UpdateAuditDataCommand.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/Dbal/Query/DbalExtractConnectionsProductEventCountQuery.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/Dbal/Query/DbalSelectEventDatesToRefreshQuery.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/Dbal/Repository/DbalEventCountRepository.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/cli.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/queries.yml
- src/Akeneo/Connectivity/Connection/back/tests/.php_cd.php
> API-895: Refresh audit data when needed

- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
- src/Akeneo/Connectivity/Connection/front/src/audit/components/NoConnection.tsx
- src/Akeneo/Connectivity/Connection/front/src/audit/pages/Dashboard.tsx
- src/Akeneo/Connectivity/Connection/front/src/settings/components/ConnectionCredentials.tsx
- src/Akeneo/Connectivity/Connection/front/src/settings/components/FlowTypeHelper.tsx
- src/Akeneo/Connectivity/Connection/front/src/settings/components/permissions/ConnectionPermissionsForm.tsx
- src/Akeneo/Connectivity/Connection/front/src/settings/components/permissions/UserGroupSelect.tsx
- src/Akeneo/Connectivity/Connection/front/src/settings/components/permissions/UserRoleSelect.tsx
- src/Akeneo/Connectivity/Connection/front/src/settings/pages/DeleteConnection.tsx
- src/Akeneo/Connectivity/Connection/front/src/settings/pages/ListConnections.tsx
- src/Akeneo/Connectivity/Connection/front/src/settings/pages/RegenerateConnectionPassword.tsx
- src/Akeneo/Connectivity/Connection/front/src/settings/pages/RegenerateConnectionSecret.tsx
- src/Akeneo/Connectivity/Connection/front/tests/unit/settings/components/__snapshots__/FlowTypeHelper.spec.tsx.snap
> API: Remove links from i18n

- src/Akeneo/Connectivity/Connection/back/Infrastructure/Cli/CreateConnectionCommand.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/cli.yml
> API-935: Adds new command to create connection

- upgrades/schema/Version_4_0_20190916122239_remove_product_empty_raw_values.php
- upgrades/schema/Version_4_0_20190917080512_remove_product_model_empty_raw_values.php
- upgrades/schema/Version_4_0_20191004145507_remove_compute_model_descendant_jobs.php
- upgrades/schema/Version_4_0_20191031124707_update_from_clients_to_apps.php
- upgrades/schema/Version_4_0_20191223132437_data_quality_insights_add_dynamic_template.php
> TIP-1367: clean migrations

- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/lib/select2.less
- AST-253: Fix bulk actions asset selector
> AST-253: Fix bulk actions asset selector

- src/Akeneo/Connectivity/Connection/back/Infrastructure/Install/Query/CreateConnectionAuditTableQuery.php
- upgrades/schema/Version_4_0_20191202144736_create_app_audit_table.php
> API: Replace enum column by varchar

- CHANGELOG-4.0.md
- config/packages/fos_auth_server.yml
- config/packages/security.yml
- src/Akeneo/UserManagement/Bundle/Resources/config/providers.yml
- src/Akeneo/UserManagement/Bundle/Security/UserApiProvider.php
- src/Akeneo/UserManagement/Component/Model/UserInterface.php
- tests/back/UserManagement/Specification/Bundle/Security/UserProviderSpec.php
> API-777: Avoid connection to the PIM UI with an API user

- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Audit/CountDailyEventsByConnectionEndToEnd.php
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Connection/UpdateConnectionEndToEnd.php
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/WebTestCase.php
> API: Fix authenticate method for e2e tests

- make-file/connectivity-connection.mk
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/Dbal/Query/DbalSelectConnectionWithCredentialsByCodeQuery.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/InMemory/Query/InMemorySelectConnectionWithCredentialsByCodeQuery.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/InMemory/Repository/InMemoryUserPermissionsRepository.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/User/Fake/CreateUser.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/User/Fake/UpdateUserPermissions.php
- src/Akeneo/Connectivity/Connection/back/tests/Acceptance/Context/ConnectionContext.php
- src/Akeneo/Connectivity/Connection/back/tests/Acceptance/Resources/config/services.yml
- src/Akeneo/Connectivity/Connection/back/tests/Acceptance/behat.yml
- src/Akeneo/Connectivity/Connection/back/tests/Acceptance/features/update_a_connection.feature
- Fix and docs on SelectConnection query
- Fix docker cmd args for consistency
- Add user permissions to UpdateConnection acceptance tests
| Added acceptance tests            | OK
> API-944: Fix acceptance tests for connection update 

- CHANGELOG-3.2.md
- src/Oro/Bundle/DataGridBundle/Datagrid/RequestParameters.php
> PIM-9056: Fix filters with numeric attribute codes for bulk actions

- .circleci/config.yml
Prepare CI nightly configuration for 4.0 branch.
> 4.0 CI config preparation

- src/Akeneo/Tool/Bundle/VersioningBundle/Resources/config/model/doctrine/Version.orm.yml
- upgrades/schema/Version_4_0_202001131458_fix_versioning_indexes.php
I think i can copy / paste this migration in previous versions, because it can be executed whatever the database state.
> PIM-9036: Update versioning indexes

- .circleci/detect_structure_changes.sh
Uses 4.0 branch as the base branch to check migrations against, instead of master.
> Uses 4.0 branch as the base for the migration testing

- std-build/install-required-files.sh
Fixing STD console exec permission
> Std console exec perm

- make-file/connectivity-connection.mk
- src/Akeneo/Connectivity/Connection/back/Application/Settings/Validation/Connection/CodeMustBeUniqueValidator.php
- src/Akeneo/Connectivity/Connection/back/Application/Settings/Validation/Connection/ImageMustExistValidator.php
- src/Akeneo/Connectivity/Connection/back/Domain/Audit/Model/Read/DailyEventCount.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Cli/UpdateAuditDataCommand.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Install/FileSystemAssetsInstaller.php
- src/Akeneo/Connectivity/Connection/back/tests/.php_cd.php
- src/Akeneo/Connectivity/Connection/back/tests/phpstan.neon
> API: Add phpstan

- src/Akeneo/Platform/CommunityVersion.php
* 4.0 CI config preparation
* Updates version name
> Updates version name (#11410)

- upgrades/schema/Version_4_0_20191031124707_update_from_clients_to_connections.php
> TIP-1367: fix connection migration

- webpack.config.js
We now transpile p-queue to avoid errors with firefox. I tested the compilation time and it's pretty much the same.
> Revert 7760 fix ci pqueue

- package.json
- yarn.lock
Add Typescript type defs for Lodash
> Add lodash types

- CHANGELOG-3.0.md
- src/Oro/Bundle/DataGridBundle/Datagrid/RequestParameters.php
Fix filters with numeric attribute codes for bulk actions, backport of https://github.com/akeneo/pim-community-dev/pull/11406
> PIM-9061: Fix filters with numeric attribute codes for bulk actions

- src/Akeneo/UserManagement/Bundle/Controller/Rest/UserController.php
> API-899: Ignore API users in UserController

- src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/variant-navigation.js
Back-Port of https://github.com/akeneo/pim-community-dev/pull/11032
> [Back-Port] PIM-8963: Make variant navigation isCreationGranted method async

- CHANGELOG-3.0.md
- src/Akeneo/Channel/Bundle/Controller/UI/CurrencyController.php
- src/Akeneo/Channel/Bundle/Resources/config/datagrid/currency.yml
- src/Akeneo/Channel/Bundle/Resources/translations/jsmessages.en_US.yml
- src/Akeneo/Pim/Structure/Component/Updater/AttributeUpdater.php
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/TitleContainer.less
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/AssetCollectionField.less
- tests/back/Pim/Structure/Specification/Component/Updater/AttributeUpdaterSpec.php
> PIM-9062: Pull up 3.0 -> 3.2

- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/images/icon-check-green.svg
> DAPI-695 : Fix "Green check icon"

- src/Akeneo/Connectivity/Connection/back/Application/Settings/Command/UpdateConnectionHandler.php
- src/Akeneo/Connectivity/Connection/back/tests/Acceptance/Context/ConnectionContext.php
- src/Akeneo/Connectivity/Connection/back/tests/Acceptance/features/create_a_connection.feature
- src/Akeneo/Connectivity/Connection/back/tests/Acceptance/features/update_a_connection.feature
> API-949: Adds acceptance scenario on Connection features

- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Domain/Audit/Model/Read/WeeklyEventCountsSpec.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Domain/Audit/Model/Write/DailyEventCountSpec.php
> API-951: Cover Connectivity Domain layer with spec tests

- upgrades/schema/Version_4_0_20191031124707_update_from_clients_to_connections.php
- upgrades/test_schema/Version_4_0_20191031124707_update_from_clients_to_connections_Integration.php
> Hotfix migration script for api connections

- make-file/connectivity-connection.mk
- src/Akeneo/Connectivity/Connection/back/tests/phpstan-infra.neon
- src/Akeneo/Connectivity/Connection/back/tests/phpstan.neon
> API-952: Adds phpstan static analysis with different levels depending of the stack

- src/Akeneo/Connectivity/Connection/back/Infrastructure/Client/Fake/FakeRegenerateClientSecret.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/InMemory/Repository/InMemoryConnectionRepository.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/User/Fake/RegenerateUserPassword.php
- src/Akeneo/Connectivity/Connection/back/tests/.php_cd.php
- src/Akeneo/Connectivity/Connection/back/tests/Acceptance/Context/ConnectionContext.php
- src/Akeneo/Connectivity/Connection/back/tests/Acceptance/Resources/config/services.yml
- src/Akeneo/Connectivity/Connection/back/tests/Acceptance/behat.yml
- src/Akeneo/Connectivity/Connection/back/tests/Acceptance/features/regenerate_a_connection_password.feature
- src/Akeneo/Connectivity/Connection/back/tests/Acceptance/features/regenerate_a_connection_secret.feature
> API-949: Adds new acceptance scenario for Secret and Password regeneration

- src/Akeneo/Connectivity/Connection/back/Infrastructure/User/Internal/CreateUser.php
- upgrades/test_schema/Version_4_0_20191031124707_update_from_clients_to_connections_Integration.php
> API-964: Hotfix migration script api_connections to apps user first name does not accept some chars

- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Client/Fos/FosRegenerateClientSecretSpec.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Install/FileSystemAssetsInstallerSpec.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/User/Internal/RegenerateUserPasswordSpec.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/User/Internal/UpdateUserPermissionsSpec.php
> API-958: Cover Infrastructure layer with spec tests

- upgrades/schema/Version_4_0_20200113145800_fix_versioning_indexes.php
> TIP-1367: Fix migration name

- src/Akeneo/Connectivity/Connection/front/src/common/components/__mocks__/Select2.tsx
- src/Akeneo/Connectivity/Connection/front/src/infrastructure/Settings.tsx
- src/Akeneo/Connectivity/Connection/front/src/settings/api-hooks/use-create-connection.ts
- src/Akeneo/Connectivity/Connection/front/src/settings/components/ConnectionCreateForm.tsx
- src/Akeneo/Connectivity/Connection/front/src/settings/components/ConnectionGrid.tsx
- src/Akeneo/Connectivity/Connection/front/src/settings/pages/Index.tsx
- src/Akeneo/Connectivity/Connection/front/src/shared/router/router-context.ts
- src/Akeneo/Connectivity/Connection/front/src/shared/router/router.interface.ts
- src/Akeneo/Connectivity/Connection/front/src/shared/router/use-route.ts
- src/Akeneo/Connectivity/Connection/front/src/shared/translate/Translate.tsx
- src/Akeneo/Connectivity/Connection/front/src/shared/translate/translate-context.ts
- src/Akeneo/Connectivity/Connection/front/src/shared/translate/translate.interface.ts
- src/Akeneo/Connectivity/Connection/front/tests/unit/settings/components/__snapshots__/Connection.spec.tsx.snap
- src/Akeneo/Connectivity/Connection/front/tests/unit/settings/components/__snapshots__/ConnectionGrid.spec.tsx.snap
- src/Akeneo/Connectivity/Connection/front/tests/unit/settings/pages/CreateConnection.spec.tsx
- src/Akeneo/Connectivity/Connection/front/tests/unit/settings/pages/DeleteConnection.spec.tsx
- src/Akeneo/Connectivity/Connection/front/tests/unit/settings/pages/EditConnection.spec.tsx
- src/Akeneo/Connectivity/Connection/front/tests/unit/settings/pages/ListConnections.spec.tsx
- src/Akeneo/Connectivity/Connection/front/tests/unit/settings/pages/RegenerateConnectionPassword.spec.tsx
- src/Akeneo/Connectivity/Connection/front/tests/unit/settings/pages/RegenerateConnectionSecret.spec.tsx
- src/Akeneo/Connectivity/Connection/front/tests/unit/shared/translate/Translate.spec.tsx
- src/Akeneo/Connectivity/Connection/front/tests/utils/test-utils.tsx
Integration tests for each page of Connectivity/Connection/Settings
> API-954: Add integration tests on each page

- src/Akeneo/Connectivity/Connection/front/src/audit/components/Chart.tsx
Remove type definition and let the compiler use the inferred type.
> API-921: Fix Victory style type

- src/Akeneo/Connectivity/Connection/front/src/audit/components/Charts.tsx
- src/Akeneo/Connectivity/Connection/front/src/audit/components/UserSurvey.tsx
> API-957: Add connection dashboard survey url

- src/Akeneo/Connectivity/Connection/front/src/audit/components/Chart.tsx
> API-959: Fix chart data visualization

- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Audit/UpdateAuditDataCommandEndToEnd.php
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/CommandTestCase.php
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Connection/CheckAuthenticationSecurityEndToEnd.php
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Connection/CreateConnectionCommandEndToEnd.php
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Connection/UpdateAuditDataCommandEndToEnd.php
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/WebTestCase.php
- tests/back/Integration/TestCase.php
> API-945: Test End-To-End of Symfony Commands (CLI)

- Dockerfile.base
- composer.json
- composer.lock
- src/Akeneo/Platform/PimRequirements.php
GD is required when there is an image in the PDF
See https://github.com/dompdf/dompdf/wiki/Requirements
> Revert "AST-232: Remove GD from requirements"

- src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/Dbal/Query/DbalExtractConnectionsProductEventCountQuery.php
- src/Akeneo/Connectivity/Connection/back/tests/Integration/Persistence/Dbal/Query/DbalSelectConnectionsEventCountByDayQueryIntegration.php
- src/Akeneo/Connectivity/Connection/back/tests/Integration/Persistence/Dbal/Repository/DbalEventCountRepositoryIntegration.php
> API-947: Adds persistence integration tests

- src/Akeneo/Platform/Bundle/AnalyticsBundle/Resources/config/twig.yml
- src/Akeneo/Platform/Bundle/AnalyticsBundle/Twig/UpdateExtension.php
- src/Akeneo/Platform/Bundle/DashboardBundle/Resources/views/Dashboard/version.html.twig
- src/Akeneo/Platform/VersionProvider.php
- src/Akeneo/Platform/VersionProviderInterface.php
- tests/back/Platform/Specification/Bundle/AnalyticsBundle/Twig/UpdateExtensionSpec.php
- tests/back/Platform/Specification/VersionProviderSpec.php
- Correctly handle SaaS version in dashboard
- Do not display last available patch on SaaS
> Handle SaaS version

- src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/EntityWithFamilyVariantNormalizer.php
- src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/ImageNormalizer.php
- src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/ProductModelNormalizer.php
- src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/ProductNormalizer.php
- src/Akeneo/Platform/CommunityVersion.php
- src/Oro/Bundle/PimDataGridBundle/Datasource/ProductAndProductModelDatasource.php
- src/Oro/Bundle/PimDataGridBundle/Normalizer/ProductAndProductModelRowNormalizer.php
- src/Oro/Bundle/PimDataGridBundle/Normalizer/ProductAssociationNormalizer.php
- src/Oro/Bundle/PimDataGridBundle/Normalizer/ProductModelNormalizer.php
- src/Oro/Bundle/PimDataGridBundle/Normalizer/ProductNormalizer.php
- src/Oro/Bundle/PimDataGridBundle/spec/Datasource/ProductAndProductModelDatasourceSpec.php
- src/Oro/Bundle/PimDataGridBundle/spec/Normalizer/ProductAndProductModelRowNormalizerSpec.php
- src/Oro/Bundle/PimDataGridBundle/spec/Normalizer/ProductAssociationNormalizerSpec.php
- src/Oro/Bundle/PimDataGridBundle/spec/Normalizer/ProductModelNormalizerSpec.php
- src/Oro/Bundle/PimDataGridBundle/spec/Normalizer/ProductNormalizerSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/InternalApi/ProductModelNormalizerSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/InternalApi/ProductNormalizerSpec.php
> AST-234: Use the channelCode to normalize the Image

- tests/back/Pim/Enrichment/EndToEnd/InternalApiTestCase.php
- tests/back/Pim/Enrichment/EndToEnd/Product/Product/InternalApi/DownloadProductPdfEndToEnd.php
> PIM-9081: Add e2e for download product pdf

- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/CatalogVolume.less
> Catalog volume monitoring: add missing icons for asset manager

- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/pim-attributeoptionview.js
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/Grid.less
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/pages/AttributeOptions.less
Fix a style regression on the border of the product grid row
> PIM-8952: Fix AknGrid border

- src/Akeneo/Connectivity/Connection/back/tests/Integration/Persistence/Dbal/Query/DbalSelectConnectionsEventCountByDayQueryIntegration.php
- src/Akeneo/Connectivity/Connection/back/tests/Integration/Persistence/Dbal/Query/DbalSelectEventDatesToRefreshQueryIntegration.php
> API-974: Test Integration SelectEventDatesToRefreshQuery

- bin/check-services-instantiability
> Fix check services in EE

- src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/translations/jsmessages.en_US.yml
> AST-400: Add missing translation key

- behat.yml
- composer.json
- composer.lock
- docker-compose.yml
- tests/legacy/features/Behat/Context/Domain/Enrich/ProductModelContext.php
- tests/legacy/features/Behat/Context/Domain/Enrich/VariantNavigationContext.php
- tests/legacy/features/Behat/Context/NavigationContext.php
- tests/legacy/features/Behat/Decorator/Common/AttributeSelectorDecorator.php
- tests/legacy/features/Behat/Decorator/ContextSwitcherDecorator.php
- tests/legacy/features/Behat/Decorator/Export/Filter/BaseDecorator.php
- tests/legacy/features/Behat/Decorator/Field/Select2Decorator.php
- tests/legacy/features/Context/DataGridContext.php
- tests/legacy/features/Context/FeatureContext.php
- tests/legacy/features/pim/enrichment/product/datagrid/datagrid_views.feature
This PR uses Selenium 3 and a recent Chrome. The previous Firefox version is outdated (2016...) and only represent 0.2% of people.
I waste A LOT of timeon stabilization. Maybe there will still be some unstables left, but I definitively can't fix it alone. I let the team to decide if future unstable tests should be deleted. …
> Selenium 3 + chrome 79 (december 2019)

- src/Akeneo/Connectivity/Connection/front/src/common/components/Select2.tsx
> API-999: Fix FlowType selector

- src/Akeneo/Pim/Structure/Bundle/Resources/config/validators.yml
- src/Akeneo/Pim/Structure/Component/Validator/Constraints/ValidMetricValidator.php
- src/Akeneo/Tool/Bundle/MeasureBundle/Controller/ExternalApi/MeasureFamilyController.php
- src/Akeneo/Tool/Bundle/MeasureBundle/Controller/MeasuresController.php
- src/Akeneo/Tool/Bundle/MeasureBundle/Convert/MeasureConverter.php
- src/Akeneo/Tool/Bundle/MeasureBundle/Provider/LegacyMeasurementProvider.php
- src/Akeneo/Tool/Bundle/MeasureBundle/Resources/config/services.yml
- src/Akeneo/Tool/Bundle/MeasureBundle/spec/Convert/MeasureConverterSpec.php
- src/Akeneo/Tool/Bundle/MeasureBundle/spec/Manager/MeasureManagerSpec.php
- src/Akeneo/Tool/Bundle/MeasureBundle/spec/Provider/LegacyMeasurementProviderSpec.php
- tests/back/Pim/Structure/Specification/Component/Validator/Constraints/ValidMetricValidatorSpec.php
> MET-10: Add measurement provider

- CHANGELOG-3.2.md
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/attributes.js
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/edit-form.js
> PIM-9103: Keep scroll position when switching locale or channel in the PEF

- phpunit.xml.dist
- src/Akeneo/Tool/Bundle/MeasureBundle/Model/MeasurementFamily.php
- src/Akeneo/Tool/Bundle/MeasureBundle/Persistence/MeasurementFamilyRepository.php
- src/Akeneo/Tool/Bundle/MeasureBundle/Persistence/MeasurementFamilyRepositoryInterface.php
- src/Akeneo/Tool/Bundle/MeasureBundle/Provider/LegacyMeasurementProvider.php
- src/Akeneo/Tool/Bundle/MeasureBundle/Resources/config/services.yml
- src/Akeneo/Tool/Bundle/MeasureBundle/tests/Integration/Persistence/MeasurementFamilyRepositoryIntegration.php
- src/Akeneo/Tool/Bundle/MeasureBundle/tests/Integration/Persistence/SqlIntegrationTestCase.php
> MET-12: Add MeasurementFamilyRepository

- src/Akeneo/Connectivity/Connection/back/Infrastructure/Install/InstallSubscriber.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Install/Query/CreateConnectionReadProductTableQuery.php
- upgrades/schema/Version_5_0_20200220092617_create_read_product.php
| Migration script                  | OK
> API-1000: Install + migration connectivity_read_product table

- src/Akeneo/Connectivity/Connection/front/src/shared/formatter/use-date-formatter.ts
- src/Akeneo/Connectivity/Connection/front/tests/src/audit/pages/Dashboard.test.tsx
Use PIM user timezone instead of the browser one
> PIM-9107: Format date with user timezone

- CHANGELOG-5.0.md
> MET-38: Add Changelog & BCs

- src/Akeneo/Connectivity/Connection/back/Domain/Audit/Persistence/Query/PurgeReadProductTableQuery.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Cli/PurgeReadProductTableCommand.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/Dbal/Query/DbalPurgeReadProductTableQuery.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/cli.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/queries.yml
- src/Akeneo/Connectivity/Connection/back/tests/Integration/Persistence/Dbal/Query/DbalPurgeReadProductTableIntegration.php
> API-998: Be able to purge read product table

- src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Completeness/SqlSaveProductCompletenesses.php
We still had 1 deadlock on high concurrency when loading 65500 products.
See https://github.com/akeneo/pim-community-dev/pull/11616, this fix was not enough.
**How to reproduce** 
We reproduced exactly how we got a deadlock with @chanmix51, because we had just an idea before.
Create the table and prepare the fixtures:
```
CREATE TABLE `test_pim_catalog_completeness` (
`id` int(11) NOT NULL AUTO_INCREMENT,
`locale_id` int(11) NOT NULL,
`channel_id` int(11) NOT NULL,
`product_id` int(11) NOT NULL,
`missing_count` int(11) NOT NULL,
`required_count` int(11) NOT NULL,
PRIMARY KEY (`id`),
UNIQUE KEY `searchunique_idx` (`channel_id`,`locale_id`,`product_id`),
KEY `test_IDX_113BA854E559DFD1` (`locale_id`),
KEY `test_IDX_113BA85472F5A1AA` …
```
> PIM-9110: fix the deadlock by adding sleep and randomization

- tests/back/Acceptance/Attribute/InMemoryAttributeRepository.php
- tests/back/Acceptance/Category/InMemoryCategoryRepository.php
- tests/back/Acceptance/Currency/InMemoryCurrencyRepository.php
- tests/back/Acceptance/spec/Attribute/InMemoryAttributeRepositorySpec.php
- tests/back/Acceptance/spec/Category/InMemoryCategoryRepositorySpec.php
Implements some new methods for in memory repositories. Useful for EE.
> RUL-17: implement in memory repository methods

- UPGRADE.md
Corrected the link to the upgrade instructions from 3.2 and 4.0.
> Corrected the link to upgrade 3.2 to 4.0

- Makefile
- akeneo-design-system/Makefile
Add a Makefile command to run the Storybook development server
```sh
make storybook
```
> Dockerize storybook

- akeneo-design-system/.storybook/main.js
- akeneo-design-system/jest.config.js
- akeneo-design-system/package.json
- akeneo-design-system/src/global.d.ts
- akeneo-design-system/tsconfig.json
- akeneo-design-system/yarn.lock
Cleanup Storybook build configuration
> Fix Storybook build config

- internal_doc/standard_format.md
See:
- https://github.com/akeneo/pim-community-dev/blob/3.2/src/Akeneo/Channel/Component/Updater/LocaleUpdater.php#L48
- https://github.com/akeneo/pim-community-dev/blob/3.2/src/Akeneo/Channel/Component/Normalizer/Standard/LocaleNormalizer.php#L22
> Make clear that locale "enabled" property is readonly

- akeneo-design-system/package.json
- akeneo-design-system/webpack.config.js
- akeneo-design-system/yarn.lock
Adding webpack analyzer to track the bundle size overtime.
Just run yarn build:analyzer to see the node modules black hole 😄
More options / configurations will be added in the future.
`-`: Not …
> [akeneo-design-system]: Add webpack analyzer

- composer.json
- composer.lock
- src/Akeneo/Tool/Bundle/ApiBundle/Resources/config/routing/measure_family.yml
- src/Akeneo/Tool/Bundle/ApiBundle/tests/integration/Controller/RootEndpointIntegration.php
- src/Akeneo/Tool/Bundle/MeasureBundle/Application/SaveMeasurementFamily/SaveMeasurementFamilyHandler.php
- src/Akeneo/Tool/Bundle/MeasureBundle/Controller/ExternalApi/JsonSchema/MeasurementFamilyListValidator.php
- src/Akeneo/Tool/Bundle/MeasureBundle/Controller/ExternalApi/JsonSchema/MeasurementFamilyValidator.php
- src/Akeneo/Tool/Bundle/MeasureBundle/Controller/ExternalApi/JsonSchemaErrorsFormatter.php
- src/Akeneo/Tool/Bundle/MeasureBundle/Controller/ExternalApi/SaveMeasurementFamiliesAction.php
- src/Akeneo/Tool/Bundle/MeasureBundle/DependencyInjection/AkeneoMeasureExtension.php
- src/Akeneo/Tool/Bundle/MeasureBundle/Resources/config/api.yml
- src/Akeneo/Tool/Bundle/MeasureBundle/Resources/config/limits.yml
- src/Akeneo/Tool/Bundle/MeasureBundle/Resources/config/services.yml
- src/Akeneo/Tool/Bundle/MeasureBundle/spec/Controller/ExternalApi/JsonSchema/MeasurementFamilyListValidatorSpec.php
- src/Akeneo/Tool/Bundle/MeasureBundle/spec/Controller/ExternalApi/JsonSchema/MeasurementFamilyValidatorSpec.php
- src/Akeneo/Tool/Bundle/MeasureBundle/tests/EndToEnd/ExternalApi/SaveMeasurementFamiliesEndToEnd.php
- symfony.lock
- Add EndToEnd test on Batch create/update of measurements via External API
- Add new route & controller for endpoint
- Add structure of requests validation (via json schema)
- Add JsonSchema validator dependency in CE + specs …
> MET-50: Add CreateOrUpdateMeasurement family endpoint + routes

- src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/attributes.js
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/edit-form.js
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/jstree/jquery.jstree.tree_selector.js
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/variant-navigation.js
- PIM-9126: Pull-up 3.2 -> 4.0
> PIM-9126: Pull-up 3.2 -> 4.0

- .circleci/detect_structure_changes.sh
> Fix detect structure changes from 3.2 to master

- CHANGELOG-4.0.md
- src/Akeneo/Tool/Bundle/MeasureBundle/Resources/translations/jsmessages.en_US.yml
- src/Akeneo/Tool/Bundle/MeasureBundle/Resources/translations/jsmessages.fr_FR.yml
- src/Akeneo/Tool/Bundle/MeasureBundle/Resources/translations/messages.en_US.yml
- src/Akeneo/Tool/Bundle/MeasureBundle/Resources/translations/messages.fr_FR.yml
Fixes #11672 
Other translations will be done in Crowdin.
> PIM-9129: Fix missing brightness measure translations

- tests/back/Acceptance/AttributeOption/InMemoryAttributeOptionRepository.php
- tests/back/Acceptance/Category/InMemoryCategoryRepository.php
- tests/back/Acceptance/Product/InMemoryProductRepository.php
- tests/back/Acceptance/spec/AttributeOption/InMemoryAttributeOptionRepositorySpec.php
- tests/back/Acceptance/spec/Category/InMemoryCategoryRepositorySpec.php
- tests/back/Acceptance/spec/Product/InMemoryProductRepositorySpec.php
Implements `findAll` method for category in memory tests.  
This implem is needed for EE tests
> RUL: implements in memory method

- src/Akeneo/Connectivity/Connection/back/Infrastructure/Install/Query/CreateConnectionAuditTableQuery.php
> API-1011: Update Installer to have the Audit table v2

- src/Akeneo/Pim/Enrichment/Component/Product/Updater/Converter/CollectionToArrayDataConverter.php
- src/Akeneo/Pim/Enrichment/Component/Product/Updater/Converter/CollectionToStringDataConverter.php
- src/Akeneo/Pim/Enrichment/Component/Product/Updater/Converter/DateToStringDataConverter.php
- src/Akeneo/Pim/Enrichment/Component/Product/Updater/Converter/MetricToNumberDataConverter.php
- src/Akeneo/Pim/Enrichment/Component/Product/Updater/Converter/MetricToStringDataConverter.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Updater/Converter/CollectionToStringDataConverterSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Updater/Converter/DateToStringDataConverterSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Updater/Converter/MetricToNumberDataConverterSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Updater/Converter/MetricToStringDataConverterSpec.php
> RUL-39: add converters for dates and metrics

- src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/Db/InitCompletenessDbSchemaSubscriber.php
- src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Completeness/SqlSaveProductCompletenesses.php
- upgrades/schema/Version_5_0_20200309165300_remove_product_foreign_key_pim_catalog_completeness.php
> PIM-9110: remove completeness fk

- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/updaters.yml
- src/Akeneo/Pim/Enrichment/Component/Product/Updater/Converter/CollectionToArrayDataConverter.php
- src/Akeneo/Pim/Enrichment/Component/Product/Updater/Converter/CollectionToStringDataConverter.php
- src/Akeneo/Pim/Enrichment/Component/Product/Updater/Converter/DateToStringDataConverter.php
- src/Akeneo/Pim/Enrichment/Component/Product/Updater/Converter/MetricToNumberDataConverter.php
- src/Akeneo/Pim/Enrichment/Component/Product/Updater/Converter/MetricToStringDataConverter.php
- src/Akeneo/Pim/Enrichment/Component/Product/Updater/Converter/StringToStringDataConverter.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Updater/Converter/CollectionToArrayDataConverterSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Updater/Converter/CollectionToStringDataConverterSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Updater/Converter/DateToStringDataConverterSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Updater/Converter/MetricToNumberDataConverterSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Updater/Converter/MetricToStringDataConverterSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Updater/Converter/NumberToMetricDataConverterSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Updater/Converter/StringToStringDataConverterSpec.php
> RUL-38: Add copiers for collection attributes

- package.json
- yarn.lock
Solves the issue with vulnerability on `serialize-javascript` : https://github.com/advisories/GHSA-h9rv-jmmf-4pgx
> Move webpack to dev dependencies

- .github/CONTRIBUTING.md
Fixes a dead link to contribution guide
> Fix contribution guide link for Github contributors

- src/Akeneo/Channel/Bundle/Resources/translations/jsmessages.en_US.yml
- src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/validators.en_US.yml
- src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml
- src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/messages.en_US.yml
- tests/back/Channel/Integration/Channel/Validation/ChannelValidationIntegration.php
- tests/back/Pim/Structure/Integration/Family/CreateFamilyVariantIntegration.php
- tests/legacy/features/pim/structure/attribute/display_available_field_options.feature
Reverts akeneo/pim-community-dev#11689
> Revert "MET-36: Rename Metric to Measurement in attributes UI"

- src/Akeneo/Connectivity/Connection/front/src/audit/components/ConnectionSelect.tsx
- src/Akeneo/Connectivity/Connection/front/src/audit/components/EventChart.tsx
- src/Akeneo/Connectivity/Connection/front/src/settings/components/ImageUploader.tsx
> Fix connection types pull up

- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
> API-1021: Fix typo "Welcome in" -> "Welcome to"

- CHANGELOG-5.0.md
- src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/ProductModelController.php
- src/Akeneo/Pim/Enrichment/Bundle/Filter/ProductEditDataFilter.php
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/controllers.yml
> PIM-9133 product models

- src/Akeneo/Connectivity/Connection/back/Domain/Audit/Persistence/Query/PurgeAuditProductQuery.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Cli/UpdateAuditDataCommand.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/Dbal/Query/DbalPurgeAuditProductQuery.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/cli.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/queries.yml
- src/Akeneo/Connectivity/Connection/back/tests/Integration/Persistence/Dbal/Query/DbalPurgeAuditProductQueryIntegration.php
> API-1016: Purge audit data

- CHANGELOG-4.0.md
> API-1020: update changelog

- src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/Button.tsx
Adding a styled Button component.
> MET-103: Add Button component

- src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/Dbal/Query/DbalExtractConnectionsProductEventCountQuery.php
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Audit/UpdateAuditDataCommandEndToEnd.php
> API-1008: Extract from versioning only auditable connections

- CHANGELOG-3.0.md
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/pim-init.js
Translate error messages coming from backend in delete dialogs
> PIM-9140: Translate error message from backend in dialogs

- src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/hooks/use-measurement-families.ts
- src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/create-measurement-family/CreateMeasurementFamily.tsx
- src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/FormGroup.tsx
- src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/TextField.tsx
- src/Akeneo/Tool/Bundle/MeasureBundle/tests/EndToEnd/InternalApi/CreateMeasurementFamilyEndToEnd.php
- src/Akeneo/Tool/Bundle/MeasureBundle/tests/front/unit/pages/create-measurement-family/CreateMeasurementFamily.unit.tsx
- src/Akeneo/Tool/Bundle/MeasureBundle/tests/front/unit/pages/create-measurement-family/form/create-measurement-family-form.unit.ts
- src/Akeneo/Tool/Bundle/MeasureBundle/tests/front/unit/pages/create-measurement-family/hooks/use-create-measurement-family-saver.unit.ts
- src/Akeneo/Tool/Bundle/MeasureBundle/tests/front/unit/shared/hooks/use-focus.unit.ts
- src/Akeneo/Tool/Bundle/MeasureBundle/tests/front/unit/shared/hooks/use-shortcut.unit.ts
- tests/front/unit/jest/unit.jest.js
> MET-106: Add unit tests to the create measurement family modals

- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/updaters.yml
- src/Akeneo/Pim/Enrichment/Component/Product/Updater/Converter/CollectionToArrayDataConverter.php
- src/Akeneo/Pim/Enrichment/Component/Product/Updater/Converter/CollectionToStringDataConverter.php
- src/Akeneo/Pim/Enrichment/Component/Product/Updater/Converter/DateToStringDataConverter.php
- src/Akeneo/Pim/Enrichment/Component/Product/Updater/Converter/MetricToNumberDataConverter.php
- src/Akeneo/Pim/Enrichment/Component/Product/Updater/Converter/MetricToStringDataConverter.php
- src/Akeneo/Pim/Enrichment/Component/Product/Updater/Converter/NumberToMetricDataConverter.php
- src/Akeneo/Pim/Enrichment/Component/Product/Updater/Converter/NumberToStringDataConverter.php
- src/Akeneo/Pim/Enrichment/Component/Product/Updater/Converter/StringToStringDataConverter.php
- src/Akeneo/Pim/Enrichment/Component/Product/Updater/Converter/ValueDataConverter.php
- src/Akeneo/Pim/Enrichment/Component/Product/Updater/Converter/ValueDataConverterRegistry.php
- src/Akeneo/Pim/Enrichment/Component/Product/Updater/Copier/HeterogeneousAttributeCopier.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Updater/Converter/CollectionToArrayDataConverterSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Updater/Converter/CollectionToStringDataConverterSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Updater/Converter/DateToStringDataConverterSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Updater/Converter/MetricToNumberDataConverterSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Updater/Converter/MetricToStringDataConverterSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Updater/Converter/NumberToMetricDataConverterSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Updater/Converter/NumberToStringDataConverterSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Updater/Converter/StringToStringDataConverterSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Updater/Converter/ValueDataConverterRegistrySpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Updater/Copier/HeterogeneousAttributeCopierSpec.php
> RUL-37: Introduce attribute copiers for different attribute types

- src/Akeneo/Tool/Bundle/MeasureBundle/Resources/translations/validators.en_US.yml
- src/Akeneo/Tool/Bundle/MeasureBundle/tests/Acceptance/SaveMeasurementFamilyTest.php
Fix translations mistakes made in: https://github.com/akeneo/pim-community-dev/pull/11746
> MET-110: Fix translations

- src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/Dbal/Query/DbalExtractConnectionsProductEventCountQuery.php
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Audit/UpdateAuditDataCommandEndToEnd.php
```
select count(id)
from pim_versioning_version
where
author in ('talend_4950', 'jean_bordelon_3900', 'jambon_8286', 'covid_1788') AND
resource_name = 'Akeneo\\Pim\\Enrichment\\Component\\Product\\Model\\Product' AND
logged_at BETWEEN '2020-03-09 00:00:01' AND '2020-03-17 23:59:59';
-> 920876
```
`APP_ENV=prod docker-compose run -u www-data --rm php php bin/console akeneo:connectivity-audit:update-data`
44s en moyenne …
> Connectivity Audit: fix queries

- CHANGELOG-4.0.md
- src/Akeneo/Connectivity/Connection/back/Domain/Audit/Persistence/Query/PurgeAuditProductQuery.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Cli/UpdateAuditDataCommand.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/Dbal/Query/DbalExtractConnectionsProductEventCountQuery.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/Dbal/Query/DbalPurgeAuditProductQuery.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/cli.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/queries.yml
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Audit/UpdateAuditDataCommandEndToEnd.php
- src/Akeneo/Connectivity/Connection/back/tests/Integration/Persistence/Dbal/Query/DbalPurgeAuditProductQueryIntegration.php
> Merge in pullup

- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
- src/Akeneo/Connectivity/Connection/front/src/audit/components/Chart.tsx
- src/Akeneo/Connectivity/Connection/front/src/audit/components/Charts.tsx
- src/Akeneo/Connectivity/Connection/front/src/audit/components/DataSourceCharts.tsx
- src/Akeneo/Connectivity/Connection/front/src/audit/components/EventChart.tsx
- src/Akeneo/Connectivity/Connection/front/src/audit/event-chart-themes.ts
> API-1031: Move data source graphs next to each other

- akeneo-design-system/.storybook/main.js
- akeneo-design-system/package.json
- akeneo-design-system/src/components/Buttons/PrimaryButton/PrimaryButton.stories.mdx
- akeneo-design-system/yarn.lock
Add ally addon to storybook
https://www.npmjs.com/package/@storybook/addon-a11y
I think this could be cool.
Even if we are not aiming to be fully accessible, the plug in could help to apply some very simple practice.
It's not a PR / compilation blocker.
| Added Specs                       |- …
> [akeneo-design-system]: Add ally addon to storybook

- src/Pim/Bundle/AnalyticsBundle/DataCollector/DBDataCollector.php
- src/Pim/Bundle/AnalyticsBundle/DependencyInjection/PimAnalyticsExtension.php
- src/Pim/Bundle/AnalyticsBundle/Query/EmailDomainsQuery.php
- src/Pim/Bundle/AnalyticsBundle/Query/Sql/EmailDomains.php
- src/Pim/Bundle/AnalyticsBundle/Resources/config/data_collectors.yml
- src/Pim/Bundle/AnalyticsBundle/Resources/config/queries.yml
- src/Pim/Bundle/AnalyticsBundle/Resources/translations/messages.en.yml
- src/Pim/Bundle/AnalyticsBundle/spec/DataCollector/DBDataCollectorSpec.php
- src/Pim/Bundle/AnalyticsBundle/tests/integration/Query/Sql/EmailDomainsIntegration.php
- tests/back/Acceptance/Analytics/Query/Sql/EmailDomainsInMemory.php
- tests/back/Acceptance/Resources/config/pim/repositories.yml
Still useful in 2.3 as it represents 25% of users.
> TIP-1298: add domain name in analytics

- src/Akeneo/Platform/Bundle/AnalyticsBundle/DataCollector/DBDataCollector.php
- src/Akeneo/Platform/Bundle/AnalyticsBundle/DependencyInjection/PimAnalyticsExtension.php
- src/Akeneo/Platform/Bundle/AnalyticsBundle/Query/Sql/EmailDomains.php
- src/Akeneo/Platform/Bundle/AnalyticsBundle/Resources/config/data_collectors.yml
- src/Akeneo/Platform/Bundle/AnalyticsBundle/Resources/config/queries.yml
- src/Akeneo/Platform/Bundle/AnalyticsBundle/Resources/translations/messages.en_US.yml
- src/Akeneo/Tool/Component/Analytics/EmailDomainsQuery.php
- tests/back/Acceptance/Resources/config/behat/services.yml
- tests/back/Platform/Acceptance/Analytics/Query/Sql/EmailDomainsInMemory.php
- tests/back/Platform/Acceptance/Analytics/Resources/config/queries.yml
- tests/back/Platform/Integration/Analytics/Query/Sql/EmailDomainsIntegration.php
- tests/back/Platform/Specification/Bundle/AnalyticsBundle/DataCollector/DBDataCollectorSpec.php
Backport of https://github.com/akeneo/pim-community-dev/pull/10796 in 3.0
> TIP-1298 domain name (#10796)

- src/Akeneo/Connectivity/Connection/back/Domain/Audit/Model/EventTypes.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/InternalApi/Controller/AuditController.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/routing.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/routing/audit.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/routing/connection.yml
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Audit/WeeklyAuditEndToEnd.php
> API-1033: Rename fetch audit data route

- src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/model/measurement-family.ts
- src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/model/validation-error.ts
- src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/common/OperationCollection.tsx
- src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/edit/Edit.tsx
- src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/edit/PropertyTab.tsx
- src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/edit/UnitTab.tsx
- src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/edit/hooks/use-measurement-family-saver.ts
- src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/edit/hooks/use-save-measurement-family-saver.ts
- src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/Button.tsx
- src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/ErrorBadge.tsx
- src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/InputErrors.tsx
- src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/TextField.tsx
- src/Akeneo/Tool/Bundle/MeasureBundle/tests/front/unit/model/measurement-family.unit.ts
- src/Akeneo/Tool/Bundle/MeasureBundle/tests/front/unit/model/validation-error.unit.ts
- src/Akeneo/Tool/Bundle/MeasureBundle/tests/front/unit/pages/common/OperationCollection.unit.tsx
This PR adds the Measurement Family front saver and handles errors on multiple rows, tabs and operations.
> MET-30: As Julia, I can update a measurement family and its units

- src/Pim/Bundle/AnalyticsBundle/DataCollector/DBDataCollector.php
- src/Pim/Bundle/AnalyticsBundle/Resources/config/data_collectors.yml
- src/Pim/Bundle/AnalyticsBundle/spec/DataCollector/DBDataCollectorSpec.php
> PIM-7359: add forgot number attributes

- src/Akeneo/Platform/Bundle/AnalyticsBundle/DataCollector/DBDataCollector.php
- src/Akeneo/Platform/Bundle/AnalyticsBundle/Resources/config/data_collectors.yml
- tests/back/Platform/Specification/Bundle/AnalyticsBundle/DataCollector/DBDataCollectorSpec.php
It was removed in 2.0 (mistake).
> PIM-7359: re-add number of attributes in the tracker

- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
- src/Akeneo/Connectivity/Connection/front/src/audit/components/EventChart.tsx
- src/Akeneo/Connectivity/Connection/front/src/audit/model/weekly-event-counts.ts
> API-1036: Display weekly total on Audit charts

- src/Akeneo/Connectivity/Connection/back/Application/Audit/Command/UpdateDataDestinationProductEventCountCommand.php
- src/Akeneo/Connectivity/Connection/back/Application/Audit/Command/UpdateDataDestinationProductEventCountHandler.php
- src/Akeneo/Connectivity/Connection/back/Application/Audit/Command/UpdateDataSourceProductEventCountCommand.php
- src/Akeneo/Connectivity/Connection/back/Application/Audit/Command/UpdateDataSourceProductEventCountHandler.php
- src/Akeneo/Connectivity/Connection/back/Domain/Audit/Model/EventTypes.php
- src/Akeneo/Connectivity/Connection/back/Domain/Audit/Persistence/Repository/EventCountRepository.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Cli/UpdateAuditDataCommand.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/EventSubscriber/ReadProductsEventSubscriber.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/Dbal/Repository/DbalEventCountRepository.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/DependencyInjection/AkeneoConnectivityConnectionExtension.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/cli.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/event_subscribers.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/handlers.yml
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Audit/SaveReadProductEventCountEndToEnd.php
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Connection/CheckAuthenticationSecurityEndToEnd.php
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/WrongCredentialsConnection/SaveWrongCredentialsConnectionEndToEnd.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Audit/Command/UpdateDataDestinationProductEventCountCommandSpec.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Audit/Command/UpdateDataDestinationProductEventCountHandlerSpec.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Audit/Command/UpdateDataSourceProductEventCountCommandSpec.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Audit/Command/UpdateDataSourceProductEventCountHandlerSpec.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/EventSubscriber/ReadProductsEventSubscriberSpec.php
- src/Akeneo/Tool/Bundle/ApiBundle/tests/integration/ApiTestCase.php
> API-997: Collect ReadProducts events

- src/Akeneo/Tool/Bundle/MeasureBundle/Controller/ExternalApi/JsonSchema/MeasurementFamilyValidator.php
- src/Akeneo/Tool/Bundle/MeasureBundle/Validation/Common/Code.php
- src/Akeneo/Tool/Bundle/MeasureBundle/Validation/Common/CodeValidator.php
- src/Akeneo/Tool/Bundle/MeasureBundle/Validation/Common/LabelCollection.php
- src/Akeneo/Tool/Bundle/MeasureBundle/Validation/Common/LabelCollectionValidator.php
- src/Akeneo/Tool/Bundle/MeasureBundle/Validation/MeasurementFamily/Count.php
- src/Akeneo/Tool/Bundle/MeasureBundle/Validation/MeasurementFamily/CountValidator.php
- src/Akeneo/Tool/Bundle/MeasureBundle/Validation/MeasurementFamily/OperationCount.php
- src/Akeneo/Tool/Bundle/MeasureBundle/Validation/MeasurementFamily/OperationCountValidator.php
- src/Akeneo/Tool/Bundle/MeasureBundle/Validation/MeasurementFamily/OperationValue.php
- src/Akeneo/Tool/Bundle/MeasureBundle/Validation/MeasurementFamily/OperationValueValidator.php
- src/Akeneo/Tool/Bundle/MeasureBundle/Validation/MeasurementFamily/StandardUnitCodeShouldExist.php
- src/Akeneo/Tool/Bundle/MeasureBundle/Validation/MeasurementFamily/StandardUnitCodeShouldExistValidator.php
- src/Akeneo/Tool/Bundle/MeasureBundle/Validation/MeasurementFamily/UnitCount.php
- src/Akeneo/Tool/Bundle/MeasureBundle/Validation/MeasurementFamily/UnitCountValidator.php
- src/Akeneo/Tool/Bundle/MeasureBundle/spec/Controller/ExternalApi/JsonSchema/MeasurementFamilyListValidatorSpec.php
- src/Akeneo/Tool/Bundle/MeasureBundle/spec/Controller/ExternalApi/JsonSchema/MeasurementFamilyValidatorSpec.php
- src/Akeneo/Tool/Bundle/MeasureBundle/spec/Model/LabelCollectionSpec.php
- src/Akeneo/Tool/Bundle/MeasureBundle/tests/Acceptance/AcceptanceTestCase.php
- src/Akeneo/Tool/Bundle/MeasureBundle/tests/Integration/Persistence/MeasurementFamilyRepositoryIntegration.php
- src/Akeneo/Tool/Bundle/MeasureBundle/tests/Integration/SqlIntegrationTestCase.php
> MET-72: Cleanup EE headers

- src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/list/List.tsx
> MET-120: Use the correct helpcenter link for measurement families

- src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/create-unit/CreateUnit.tsx
- src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/create-unit/form/create-unit-form.ts
- src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/create-unit/hooks/use-create-unit-validator.ts
- src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/edit/Edit.tsx
- src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/edit/UnitTab.tsx
- src/Akeneo/Tool/Bundle/MeasureBundle/Validation/Unit/CodeMustBeUniqueValidator.php
- src/Akeneo/Tool/Bundle/MeasureBundle/tests/front/unit/model/measurement-family.unit.ts
- src/Akeneo/Tool/Bundle/MeasureBundle/tests/front/unit/pages/create-measurement-family/hooks/use-create-measurement-family-saver.unit.ts
- src/Akeneo/Tool/Bundle/MeasureBundle/tests/front/unit/pages/create-unit/CreateUnit.unit.tsx
- src/Akeneo/Tool/Bundle/MeasureBundle/tests/front/unit/pages/create-unit/form/create-unit-form.unit.ts
- src/Akeneo/Tool/Bundle/MeasureBundle/tests/front/unit/pages/create-unit/hooks/use-create-unit-validator.unit.ts
- src/Akeneo/Tool/Bundle/MeasureBundle/tests/front/unit/pages/list/MeasurementFamilyTable.unit.tsx
Each commit contains a specific fix, you should review it commit by commit, it should be easier.
> MET-136: Fix feedback on AddUnit modal

- src/Akeneo/Tool/Bundle/MeasureBundle/Persistence/MeasurementFamilyRepository.php
Removing the cache mechanism in the `MeasurementFamilyRepository`.
> MET-117: Remove cache in measurement family repository

- src/Akeneo/Tool/Bundle/MeasureBundle/Persistence/MeasurementFamilyRepository.php
Reverts akeneo/pim-community-dev#11832
> Revert "MET-117: Remove cache in measurement family repository"

- package.json
- src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/edit/Edit.tsx
- src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/edit/UnitTab.tsx
- src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/edit/unit-tab/UnitDetails.tsx
- src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/edit/unit-tab/UnitRow.tsx
- src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/edit/unit-tab/UnitTab.tsx
- src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/edit/unit-tab/index.ts
- src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/ErrorBadge.tsx
- src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/ErrorBlock.tsx
- src/Akeneo/Tool/Bundle/MeasureBundle/Resources/translations/jsmessages.en_US.yml
- src/Akeneo/Tool/Bundle/MeasureBundle/Resources/translations/messages.en_US.yml
- src/Akeneo/Tool/Bundle/MeasureBundle/tests/front/unit/pages/edit/unit-tab/UnitDetails.unit.tsx
- src/Akeneo/Tool/Bundle/MeasureBundle/tests/front/unit/pages/edit/unit-tab/UnitRow.unit.tsx
- tests/front/unit/pimenrich/js/i18n.unit.ts
This PR:
- Fixes delete Measurement Family translation key
- Fixes translations
- Adds leave warning when clicking on breadcrumb
- Tidy up large files
- Add unit tests on `UnitDetails` & `UnitRow` components
`OK`: …
> MET-139: Various fixes after PO feedback

- src/Akeneo/Tool/Bundle/MeasureBundle/Installer/MeasurementInstaller.php
- tests/back/Integration/IntegrationTestsBundle/Loader/FixturesLoader.php
Dropping the Measurement table before creating it.
> MET-152: Drop measurement table before installing it

- .circleci/detect_structure_changes.sh
Handle the installation of the Onboarder bundle during the detection of structure changes.
> TIP-1399: install AOB on detect structure changes

- src/Akeneo/Connectivity/Connection/front/src/settings/components/AuditableHelper.tsx
> API-1053: Update auditable helper in connection edit

- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
- src/Akeneo/Connectivity/Connection/front/src/audit/components/ConnectionSelect.tsx
- src/Akeneo/Connectivity/Connection/front/src/audit/components/DataDestinationCharts.tsx
- src/Akeneo/Connectivity/Connection/front/src/audit/components/DataSourceCharts.tsx
> API-1057: Fix translation in Connection audit charts

- CHANGELOG-3.0.md
- src/Akeneo/UserManagement/.php_cd.php
- src/Akeneo/UserManagement/Bundle/Controller/Rest/UserController.php
The exception was not caught and the basic error message was displayed.
> PIM-9169: Fix error message when deleting user that created a project

- src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/translations/jsmessages.en_US.yml
> Fix translation

- src/Akeneo/Connectivity/Connection/front/tests/src/audit/pages/components/DataDestinationCharts.test.tsx
- src/Akeneo/Connectivity/Connection/front/tests/src/audit/pages/components/DataSourceCharts.test.tsx
> API-1052: Fix connection audit test

- make-file/test.mk
- src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/column-tabs-navigation.js
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/form-tabs.js
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/mass-edit/form/product/associate.js
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/associated-product-row.js
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/associations.js
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/product/tab/associated-product-row.html
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/product/tab/association-panes.html
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/product/tab/associations.html
- src/Oro/Bundle/PimDataGridBundle/Datasource/AssociatedProductDatasource.php
- src/Oro/Bundle/PimDataGridBundle/Datasource/AssociatedProductModelDatasource.php
- src/Oro/Bundle/PimDataGridBundle/Resources/config/datagrid_listeners.yml
- src/Oro/Bundle/PimDataGridBundle/spec/Datasource/AssociatedProductDatasourceSpec.php
- src/Oro/Bundle/PimDataGridBundle/spec/Datasource/AssociatedProductModelDatasourceSpec.php
- tests/legacy/features/pim/enrichment/product/import/import_products_with_associations.feature
- tests/legacy/features/pim/enrichment/product/import/xlsx/import_products_with_associations.feature
- tests/legacy/features/pim/enrichment/product/pef/association/update_associations.feature
This solution is not ideal but it's crazy legacy and I have no idea how it works
> MET-141: Add product link in associations & association count

- package.json
- yarn.lock
Introduce the React Hook Form library. A form library base only on hooks.
https://react-hook-form.com/
https://bundlephobia.com/result?p=react-hook-form@5.2.0
The mutationoberserer dep is here to do the testing.
https://react-hook-form.com/faqs#TestingfailedduetoMutationObserver
| Changelog updated                 |-
| Tech Doc …
> RUL-115: Add React Hook Form Dependency

- src/Akeneo/Connectivity/Connection/back/Infrastructure/Install/InstallSubscriber.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Install/Query/CreateBusinessErrorTableQuery.php
- upgrades/schema/Version_5_0_20200408074907_create_business_error_table.php
- upgrades/test_schema/Version_5_0_20200408074907_create_business_error_table_Integration.php
> API-1066: Install and migration script for business errors

- src/Akeneo/Connectivity/Connection/back/Domain/ErrorManagement/Model/Write/BusinessError.php
- src/Akeneo/Connectivity/Connection/back/Domain/ErrorManagement/Persistence/Repository/BusinessErrorRepository.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/ErrorManagement/ApiBusinessErrorEventSubscriber.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/ErrorManagement/ExtractBusinessErrorsFromApiResponse.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/ErrorManagement/RoutesDictionary.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/Dbal/Repository/DbalApiBusinessErrorRepository.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/event_subscribers.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/repositories.yml
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/ErrorManagement/CollectApiBusinessErrorsEndToEnd.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Domain/ErrorManagement/Model/Write/BusinessErrorSpec.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/ErrorManagement/ApiBusinessErrorEventSubscriberSpec.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/ErrorManagement/ExtractBusinessErrorsFromApiResponseSpec.php
> API-1041: collect API business errors from source connections

- src/Akeneo/Connectivity/Connection/back/Infrastructure/ErrorManagement/ExtractBusinessErrorsFromApiResponse.php
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/ErrorManagement/CollectApiBusinessErrorsEndToEnd.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/ErrorManagement/ExtractBusinessErrorsFromApiResponseSpec.php
> API-1068: Collect business error when response has the errors field

- package.json
- yarn.lock
Add [reakit](https://reakit.io/) dependency for frontend.
This lib provides components,  composable with hooks.
This will provide us out of the box correct semantic and ally feature (especially good handling of focus).
The components are css free, so no weird overload to put our style.
| …
> RUL-122: Add reakit dep

- src/Akeneo/Connectivity/Connection/back/Domain/WrongCredentialsConnection/Persistence/Query/SelectConnectionCodeByClientIdQuery.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/ConnectionContext.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/EventSubscriber/ApiAuthenticationEventSubscriber.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/EventSubscriber/ConnectionContextEventSubscriber.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/EventSubscriber/ReadProductsEventSubscriber.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/Dbal/Query/DbalSelectConnectionCodeByClientIdQuery.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/event_subscribers.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/services.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/wrong_credentials_connection.yml
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/ConnectionContextSpec.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/EventSubscriber/ApiAuthenticationEventSubscriberSpec.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/EventSubscriber/ConnectionContextEventSubscriberSpec.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/EventSubscriber/ReadProductsEventSubscriberSpec.php
- src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/create-measurement-family/CreateMeasurementFamily.tsx
> API-1065: Create ConnectionContext service

- src/Akeneo/Connectivity/Connection/back/Infrastructure/EventSubscriber/ApiAuthenticationEventSubscriber.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/EventSubscriber/ApiAuthenticationEventSubscriberSpec.php
> Fix ConnectionContext

- config/bundles.php
- config/packages/akeneo_feature_flag.yml
- config/routes/routes.yml
- frontend/build/update-extensions.js
- src/Akeneo/Platform/Bundle/FeatureFlagBundle/AkeneoFeatureFlagBundle.php
- src/Akeneo/Platform/Bundle/FeatureFlagBundle/Configuration/EnvVarFeatureFlag.php
- src/Akeneo/Platform/Bundle/FeatureFlagBundle/DependencyInjection/AkeneoFeatureFlagExtension.php
- src/Akeneo/Platform/Bundle/FeatureFlagBundle/DependencyInjection/Configuration.php
- src/Akeneo/Platform/Bundle/FeatureFlagBundle/FeatureFlag.php
- src/Akeneo/Platform/Bundle/FeatureFlagBundle/FeatureFlags.php
- src/Akeneo/Platform/Bundle/FeatureFlagBundle/Internal/Controller.php
- src/Akeneo/Platform/Bundle/FeatureFlagBundle/Internal/FilterRoutesSubscriber.php
- src/Akeneo/Platform/Bundle/FeatureFlagBundle/Internal/Registry.php
- src/Akeneo/Platform/Bundle/FeatureFlagBundle/README.md
- src/Akeneo/Platform/Bundle/FeatureFlagBundle/Resources/config/routing.yml
- src/Akeneo/Platform/Bundle/FeatureFlagBundle/Resources/config/services.yml
- src/Akeneo/Platform/Bundle/FeatureFlagBundle/Service/Registry.php
- src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/feature-flags.ts
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/config-provider.js
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/pim-app.js
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/router.js
- tests/back/Platform/Specification/Bundle/FeatureFlagBundle/Configuration/EnvVarFeatureFlagSpec.php
- tests/back/Platform/Specification/Bundle/FeatureFlagBundle/FeatureFlagsSpec.php
- tests/back/Platform/Specification/Bundle/FeatureFlagBundle/Internal/RegistrySpec.php
- tests/back/Platform/Specification/Bundle/FeatureFlagBundle/Service/RegistrySpec.php
- tests/front/acceptance/cucumber/step-definitions/volume-monitoring/index.js
Please read the README https://github.com/akeneo/pim-community-dev/pull/11889/files#diff-d6aff3307a520a741d05e462f68397c8
Everything is explained inside.
> TIP-1403: Feature Flag system

- CHANGELOG-4.0.md
- src/Akeneo/Pim/Enrichment/.php_cd.php
- src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/Db/InitCompletenessDbSchemaSubscriber.php
- src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/Product/OnDelete/DeleteCompletenessSubscriber.php
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/event_subscribers.yml
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/removers.yml
- src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Completeness/SqlSaveProductCompletenesses.php
- src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ElasticsearchProjection/GetElasticsearchProductModelProjection.php
- src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Product/CompletenessRemover.php
- tests/back/Pim/Enrichment/Integration/Completeness/RemoveCompletenessWhenDeletingProductIntegration.php
- tests/parallel_api_calls/README.md
- tests/parallel_api_calls/parallel_api_calls.php
- upgrades/schema/Version_4_0_20200415194400_remove_product_foreign_key_pim_catalog_completeness.php
Backports deadlock fixes on product completeness from master to 4.0 branch.
| Added Specs                       | - 
> PIM-9190: Backports deadlock fixes on product completeness

- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/base/variables.less
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/Tag.less
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/index.less
Added colors and styles for tags
> RUL-79 Add colors and styles for tags

- CHANGELOG-4.0.md
- src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Model/ElasticsearchProductModelProjection.php
- tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Model/ElasticsearchProductModelProjectionSpec.php
> AOB-937: Include additional properties when indexing product models

- src/Akeneo/Connectivity/Connection/back/Domain/ErrorManagement/Model/Write/BusinessError.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/ErrorManagement/ApiBusinessErrorEventSubscriber.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/ErrorManagement/ExtractBusinessErrorsFromApiResponse.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/ErrorManagement/RoutesDictionary.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/Dbal/Repository/DbalApiBusinessErrorRepository.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/event_subscribers.yml
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Domain/ErrorManagement/Model/Write/BusinessErrorSpec.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/ErrorManagement/ApiBusinessErrorEventSubscriberSpec.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/ErrorManagement/ExtractBusinessErrorsFromApiResponseSpec.php
> API-1069: handle business errors from streamed response

- .env
- config/packages/akeneo_elasticsearch.yml
- config/services/pim_parameters.yml
- config/services/services.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/elasticsearch/connection_error_mapping.yml
- upgrades/schema/Version_5_0_20200427144538_create_connection_error_index.php
- upgrades/test_schema/Version_5_0_20200427144538_create_connection_error_index_Integration.php
> API-1094: Create connection error ES index

- CHANGELOG-4.0.md
- composer.json
- composer.lock
All is in the title
Composer install result:
```bash
Package operations: 192 installs, 0 updates, 0 removals
- Installing ass/xmlsecurity (v1.1.1): Loading from cache
- Installing psr/log (1.1.3): Loading from cache
- Installing symfony/polyfill-php73 (v1.15.0): Loading from cache
- Installing symfony/polyfill-ctype (v1.15.0): Loading from cache
- Installing symfony/polyfill-mbstring (v1.15.0): Loading from cache
- Installing symfony/polyfill-php72 (v1.15.0): Loading from cache
- Installing symfony/polyfill-intl-idn (v1.15.0): Loading from cache
- Installing symfony/mime (v4.4.7): Loading from cache
- Installing symfony/http-foundation (v4.4.7): Loading from cache
- Installing symfony/event-dispatcher-contracts (v1.1.7): Loading from cache
- Installing psr/container (1.0.0): Loading from …
```
> Limit Symfony version on 4.4.7 because of validation issues with 4.4.8

- CHANGELOG-3.2.md
- src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filters-column.ts
- yarn.lock
> GITHUB-11995: Fixes invalid Jquery generic type (#11995)

- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/mass-edit/form/product/associate.js
- tests/back/Pim/Enrichment/Integration/Product/Association/CreateTwoWayAssociationIntegration.php
- tests/back/Pim/Enrichment/Integration/Product/Association/CreateTwoWayAssociationProductModelIntegration.php
Bugs fixes that were discovered by the EE CI.
> MET-166: Fix issues in associations

- upgrades/test_schema/Version_5_0_20200320095430_add_is_two_way_col_to_associations_Integration.php
Only migration test
| Added integration tests           | Done
> MET-236: test: add test migration for is_two_way

- src/Akeneo/Connectivity/Connection/back/Application/ErrorManagement/Query/GetConnectionBusinessErrorsHandler.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/Elasticsearch/Query/ElasticsearchSelectLastConnectionBusinessErrorsQuery.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/queries.yml
- src/Akeneo/Connectivity/Connection/back/tests/Integration/Persistence/Elasticsearch/Query/ElasticsearchSelectLastConnectionBusinessErrorsQueryIntegration.php
- src/Akeneo/Tool/Bundle/ElasticsearchBundle/Client.php
> API-1097: Fetch errors from ES index for the GetConnectionBusinessErrors endpoint

- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/Tag.less
Fix tags CSS to respect BEM methodology
> RUL-79 Fix CSS to respect BEM methodology

- .env
- config/packages/akeneo_feature_flag.yml
- src/Akeneo/Pim/Structure/Bundle/DependencyInjection/AkeneoPimStructureExtension.php
- src/Akeneo/Pim/Structure/Bundle/Resources/config/feature_flag.yml
> MET-237: Add the feature flag FLAG_QUANTIFIED_ASSOCIATION_ENABLED

- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/doctrine/Product/Product.orm.yml
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/doctrine/Product/ProductModel.orm.yml
- src/Akeneo/Pim/Enrichment/Component/Product/Model/AbstractProduct.php
- src/Akeneo/Pim/Enrichment/Component/Product/Model/ProductModel.php
- upgrades/schema/Version_5_0_20200429094251_add_quantified_associations.php
- upgrades/test_schema/Version_4_0_20200116122239_remove_product_empty_raw_values_Integration.php
- upgrades/test_schema/Version_4_0_20200117080512_remove_product_model_empty_raw_values_Integration.php
- upgrades/test_schema/Version_4_0_20200117145507_remove_compute_model_descendant_jobs_Integration.php
- upgrades/test_schema/Version_5_0_20200429094251_add_quantified_associations_Integration.php
- Adds a new column in the product / product model DB tables
- Adds a new field in the product / product model entities named "quantified associations"
- Adds migration
> RAC-8: add quantified association field

- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/form_extensions.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/requirejs.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/routing.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/public/js/controller/audit.tsx
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/public/js/controller/error-management.tsx
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/public/js/controller/settings.tsx
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/public/js/menu/connection-params-provider.ts
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/public/js/menu/highlight-menu.ts
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/public/js/react/react-controller.ts
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
- src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/column.js
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/menu/column.js
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/menu/item.js
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/menu/navigation-back.ts
> API-1062: Add new Connection menu

- src/Akeneo/Connectivity/Connection/back/Infrastructure/Cli/PurgeConnectionErrorsCommand.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/Dbal/Query/SelectAllAuditableConnectionCodeQuery.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/Elasticsearch/Query/PurgeConnectionErrorsQuery.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/cli.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/queries.yml
- src/Akeneo/Connectivity/Connection/back/tests/Integration/Persistence/Dbal/Query/SelectAllAuditableConnectionCodeQueryIntegration.php
- src/Akeneo/Connectivity/Connection/back/tests/Integration/Persistence/Elasticsearch/Query/PurgeConnectionErrorsQueryIntegration.php
> API-1095: Purge connection errors over 100 and older than a week

- CHANGELOG-4.0.md
- config/services/test/test_services.yml
- src/Akeneo/Pim/Enrichment/Bundle/PdfGeneration/Renderer/ProductPdfRenderer.php
- src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Product/GetCategoryCodesByProductIdentifiers.php
- src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Product/SqlGetValuesOfSiblings.php
- src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductGrid/ProductModelImagesFromCodes.php
- src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/EntityWithFamilyVariantNormalizer.php
- src/Akeneo/Pim/Enrichment/Component/Product/ProductModel/Query/GetValuesOfSiblings.php
- src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/UniqueVariantAxisValidator.php
- src/Akeneo/Pim/Structure/Bundle/Query/PublicApi/AttributeOption/Cache/LRUCachedGetExistingAttributeOptions.php
- src/Akeneo/Pim/Structure/Bundle/Resources/config/queries.yml
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/edit-form.js
- src/Akeneo/Platform/CommunityVersion.php
- src/Akeneo/Tool/Bundle/VersioningBundle/Command/RefreshCommand.php
- src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filters-column.ts
- src/Oro/Bundle/PimDataGridBundle/spec/Extension/MassAction/MassActionDispatcherSpec.php
- tests/back/Integration/IntegrationTestsBundle/Query/PublicApi/AttributeOption/Cache/LRUClearableCachedGetExistingAttributeOptions.php
- tests/back/Pim/Enrichment/Integration/Product/LoadEntityWithValuesSubscriberIntegration.php
- tests/back/Pim/Enrichment/Integration/Storage/Sql/Product/SqlGetValuesOfSiblingsIntegration.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/UniqueVariantAxisValidatorSpec.php
- tests/back/Pim/Structure/Specification/Bundle/Query/PublicApi/AttributeOption/Cache/LRUCachedGetExistingAttributeOptionsSpec.php
- yarn.lock
> Merge 4.0 into master [pullup]

- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/pim-init.js
https://github.com/akeneo/pim-enterprise-dev/pull/8664
> RUL-152: Fix popin

- src/Akeneo/Connectivity/Connection/back/Infrastructure/Install/InstallSubscriber.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Install/Query/CreateConnectionAuditErrorTableQuery.php
- upgrades/schema/Version_5_0_20200506131741_create_connection_error_table.php
- upgrades/test_schema/Version_5_0_20200506131741_create_connection_error_table_Integration.php
> API-1108: Create connection audit error count table

- src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/EntityWithQuantifiedAssociations/LoadEntitySubscriber.php
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/normalizers.yml
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/serializers_standard.yml
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/StandardToFlat/Product.php
- src/Akeneo/Pim/Enrichment/Component/Product/Model/QuantifiedAssociation/EntityWithQuantifiedAssociationTrait.php
- src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/ProductModelNormalizer.php
- src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/ProductNormalizer.php
- src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Standard/Product/QuantifiedAssociationsNormalizer.php
- src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Standard/ProductModelNormalizer.php
- src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Standard/ProductNormalizer.php
- src/Akeneo/Pim/Enrichment/Component/Product/Updater/ProductModelUpdater.php
- src/Akeneo/Pim/Enrichment/Component/Product/Updater/ProductUpdater.php
- tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/CreateProductEndToEnd.php
- tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/PartialUpdateListProductEndToEnd.php
- tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/PartialUpdateProductEndToEnd.php
- tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/CreateProductModelEndToEnd.php
- tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/PartialUpdateListProductModelEndToEnd.php
- tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/PartialUpdateProductModelEndToEnd.php
- tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/ExternalApi/CreateVariantProductEndToEnd.php
- tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/ExternalApi/PartialUpdateListVariantProductEndToEnd.php
- tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/ExternalApi/PartialUpdateProductToVariantEndToEnd.php
- tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/ExternalApi/PartialUpdateVariantProductEndToEnd.php
- tests/back/Pim/Enrichment/Integration/Normalizer/Standard/ProductStandardIntegration.php
- tests/back/Pim/Enrichment/Integration/Normalizer/Standard/ProductStandardSortedCollectionIntegration.php
- tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/EntityWithQuantifiedAssociations/LoadEntitySubscriberSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/Standard/Product/QuantifiedAssociationsNormalizerSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/Standard/ProductModelNormalizerSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/Standard/ProductNormalizerSpec.php
> RAC-11: Add quantified associations to the InternalApi normalizer

- src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/ProductController.php
- src/Akeneo/Pim/Enrichment/Component/Product/Comparator/Filter/EntityWithValuesFilter.php
- src/Akeneo/Pim/Enrichment/Component/Product/Exception/UnknownAttributeException.php
- src/Akeneo/Pim/Enrichment/Component/Product/Updater/ProductUpdater.php
- tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/CreateProductEndToEnd.php
- tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/Media/CreateProductMediaFileEndToEnd.php
- tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/PartialUpdateProductEndToEnd.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Comparator/Filter/EntityWithValuesFilterSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Exception/UnknownAttributeExceptionSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Updater/ProductUpdaterSpec.php
Add an `UnknownAttributeException` (in place of `UnknownPropertyException`) to identify more precisely this kind of error.
```
Akeneo\Pim\Enrichment\Component\Product\Exception\UnknownAttributeException
```
> API-1090: Add an UnknownAttributeException

- CHANGELOG-3.2.md
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/index.less
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/pages/ProductExport.less
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/export/product/edit/content.html
This PR fixes 2 CSS bugs we have on the product export.
**Before :** 
**After :**
> PIM-9249: Fix channel and locale popin display on product export

- src/Akeneo/Connectivity/Connection/back/Infrastructure/Cli/PurgeAuditErrorCommand.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/Dbal/Query/PurgeAuditErrorQuery.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/cli.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/queries.yml
- src/Akeneo/Connectivity/Connection/back/tests/Integration/Fixtures/AuditErrorLoader.php
- src/Akeneo/Connectivity/Connection/back/tests/Integration/Persistence/Dbal/Query/DbalPurgeAuditErrorQueryIntegration.php
- src/Akeneo/Connectivity/Connection/back/tests/Integration/Resources/config/loaders.yml
> CXP-16: Be able to purge audit_error table by a command

- src/Akeneo/Connectivity/Connection/back/Application/ErrorManagement/Service/CollectApiError.php
- src/Akeneo/Connectivity/Connection/back/Application/ErrorManagement/Service/ExtractErrorsFromHttpExceptionInterface.php
- src/Akeneo/Connectivity/Connection/back/Domain/ErrorManagement/Model/Write/ApiError.php
- src/Akeneo/Connectivity/Connection/back/Domain/ErrorManagement/Model/Write/ApiErrorInterface.php
- src/Akeneo/Connectivity/Connection/back/Domain/ErrorManagement/Persistence/Repository/BusinessErrorRepository.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/ErrorManagement/ExtractErrorsFromHttpException.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/Elasticsearch/Repository/ElasticsearchBusinessErrorRepository.php
- src/Akeneo/Connectivity/Connection/back/tests/.php_cd.php
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/ErrorManagement/GetConnectionBusinessErrorsEndToEnd.php
- src/Akeneo/Connectivity/Connection/back/tests/Integration/Persistence/Elasticsearch/Repository/ElasticsearchBusinessErrorRepositoryIntegration.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/ErrorManagement/Service/CollectApiErrorSpec.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Domain/ErrorManagement/Model/Write/BusinessErrorSpec.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Domain/ErrorManagement/Model/Write/TechnicalErrorSpec.php
> Cxp 15 fixes

- src/Akeneo/Connectivity/Connection/back/Infrastructure/InternalApi/Controller/AuditController.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/controllers.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/routing/audit.yml
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Audit/ErrorCountPerConnectionEndToEnd.php
> CXP-55: Connection cards internal API

- src/Akeneo/Connectivity/Connection/back/Application/ErrorManagement/Service/CollectApiError.php
- src/Akeneo/Connectivity/Connection/back/Domain/ErrorManagement/Model/Write/ApiErrorCollection.php
- src/Akeneo/Connectivity/Connection/back/Domain/ErrorManagement/Persistence/Repository/BusinessErrorRepository.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Domain/ErrorManagement/Model/Write/ApiErrorCollectionSpec.php
> CXP-15: Add ApiErrorCollection

- src/Akeneo/Connectivity/Connection/tests/features/create_connection.feature
Skip an unstable behat test, awaiting a proper fix
> CXP-81: Skip unstable behat test

- src/Akeneo/Connectivity/Connection/back/Application/Audit/Query/GetPeriodEventCountPerConnectionHandler.php
- src/Akeneo/Connectivity/Connection/back/Application/Audit/Query/GetPeriodEventCountPerConnectionQuery.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/InternalApi/Controller/AuditController.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/controllers.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/handlers.yml
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Audit/Query/GetPeriodEventCountPerConnectionHandlerSpec.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Audit/Query/GetPeriodEventCountPerConnectionQuerySpec.php
> CXP-287: Fix naming inconsistencies

- src/Akeneo/Pim/Structure/Bundle/Datagrid/Attribute/FamilyFilter.php
- src/Akeneo/Pim/Structure/Bundle/Datagrid/Attribute/RegisterFamilyFilter.php
- src/Akeneo/Pim/Structure/Bundle/Resources/config/services.yml
- tests/back/Pim/Structure/Specification/Bundle/Datagrid/Attribute/FamilyFilterSpec.php
- tests/back/Pim/Structure/Specification/Bundle/Datagrid/Attribute/RegisterFamilyFilterSpec.php
> DAPI-1020: add a new family filter on attribute grid

- src/Akeneo/Tool/Bundle/MeasureBundle/Validation/CreateMeasurementFamily/CountValidator.php
> Fix a refacto typo in the CountValidator

- src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/ProductModelNormalizer.php
- src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/ProductNormalizer.php
- src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Standard/Product/QuantifiedAssociationsNormalizer.php
> RAC-63: Add parent quantified associations to the internal api meta

- src/Akeneo/Connectivity/Connection/back/Infrastructure/ErrorManagement/ExtractErrorsFromHttpException.php
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/ErrorManagement/CollectApiBusinessErrorsEndToEnd.php
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/ErrorManagement/CollectApiErrorsCountEndToEnd.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/ErrorManagement/ExtractErrorsFromHttpExceptionSpec.php
> CXP-291: Make UnknwnAttributeException a BusinessError

- src/Akeneo/Pim/Enrichment/Component/DocumentedExceptionInterface.php
- src/Akeneo/Pim/Enrichment/Component/Product/Exception/UnknownAttributeException.php
- tests/back/Pim/Enrichment/Integration/Product/Exception/DocumentedExceptionRouteExistsIntegration.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Exception/UnknownAttributeExceptionSpec.php
> CXP-293: Add documentation exception on UnknownAttributeException

- bin/check-pullup
Adds PAM-related files to the `check-pullup` script, see https://github.com/akeneo/pim-enterprise-dev/pull/8839
> Add PAM files to check-pullup

- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/form/form-tabs.html
> DAPI-1000: allow HTML tags in form tab labels

- .circleci/config.yml
Syncing CircleCI configuration for pim-enterprise-dev tests
> Sync pim-ee CI config

- src/Akeneo/Platform/Bundle/ImportExportBundle/Normalizer/StepExecutionNormalizer.php
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/job-execution/summary-table.html
- tests/back/Platform/Specification/Bundle/ImportExportBundle/Normalizer/StepExecutionNormalizerSpec.php
> RUL-202: Display step execution errors in job execution summary

- src/Akeneo/Connectivity/Connection/back/Infrastructure/ErrorManagement/ExtractErrorsFromHttpException.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Normalizer/ViolationNormalizer.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/AkeneoConnectivityConnectionBundle.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/DependencyInjection/AkeneoConnectivityConnectionExtension.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/normalizers.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/serializers.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/services.yml
- src/Akeneo/Connectivity/Connection/back/tests/.php_cd.php
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/ErrorManagement/CollectApiBusinessErrorsEndToEnd.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/ErrorManagement/ExtractErrorsFromHttpExceptionSpec.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Normalizer/ViolationNormalizerSpec.php
- src/Akeneo/Tool/Component/Api/Normalizer/Exception/ViolationNormalizer.php
> CXP-296: Store exception details inside Elasticsearch

- src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/ProductAndProductModel/GetFromIdentifiersAction.php
- src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Query/QuantifiedAssociation/GetIdMappingFromProductIdentifiersQuery.php
- src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Query/QuantifiedAssociation/GetIdMappingFromProductIdsQuery.php
- src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Query/QuantifiedAssociation/GetIdMappingFromProductModelCodesQuery.php
- src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Query/QuantifiedAssociation/GetIdMappingFromProductModelIdsQuery.php
- src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/EntityWithQuantifiedAssociations/LoadEntitySubscriber.php
- src/Akeneo/Pim/Enrichment/Component/Product/QuantifiedAssociation/QuantifiedAssociationsFromAncestorsFilter.php
- tests/back/Acceptance/spec/ProductModel/InMemoryProductModelRepositorySpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Model/QuantifiedAssociation/QuantifiedLinkSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/InternalApi/ProductModelNormalizerSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/InternalApi/ProductNormalizerSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/Standard/Product/QuantifiedAssociationsNormalizerSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/QuantifiedAssociation/QuantifiedAssociationsFromAncestorsFilterSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/QuantifiedAssociation/QuantifiedAssociationsMergerSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Updater/ProductModelUpdaterSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Updater/ProductUpdaterSpec.php
- tests/back/Pim/Structure/Specification/Component/ArrayConverter/FlatToStandard/AssociationTypeSpec.php
- tests/back/Pim/Structure/Specification/Component/ArrayConverter/StandardToFlat/AssociationTypeSpec.php
- tests/back/Pim/Structure/Specification/Component/Validator/Constraints/AssociationType/ShouldNotBeTwoWayAndQuantifiedValidatorSpec.php
phpspec tests were not launched anymore, see https://github.com/akeneo/pim-enterprise-dev/pull/8833
As a consequence, we broke some existing tests and also added a few incomplete/broken tests.
This PR fix all of this tests.
> RAC-64: Fix phpspec tests

- .circleci/config.yml
> Require the job deploy_upgrade_oldest_prod_environment for a PR

- src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/StandardToFlat/Product.php
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/StandardToFlat/ProductModel.php
- src/Akeneo/Pim/Enrichment/Component/Product/Model/QuantifiedAssociation/QuantifiedAssociations.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/StandardToFlat/ProductModelSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/StandardToFlat/ProductSpec.php
Add standard to flat quantified associations method
> RAC-43: Add standard to flat quantified associations method

- std-build/package.json
Adding the missing yarn workspaces in the standard `package.json` (`shared` and `legacy-bridge`)
> Add missing yarn workspaces to standard package.json

- src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/config/form_extensions/communication_channel.yml
- src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/config/requirejs.yml
- src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/public/bridge/react/react-element-helper.ts
- src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/public/bridge/react/react-view.ts
- src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/public/bridge/view/panel.tsx
- src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/public/components/panel/Panel.tsx
- src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/public/components/panel/index.ts
- src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/public/less/components/Menu.less
- src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/public/less/components/Panel.less
- src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/public/less/index.less
- src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/public/menu/communication-channel.html
- src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/public/menu/communication-channel.ts
- src/Akeneo/Platform/Bundle/CommunicationChannelBundle/Resources/translations/jsmessages.en_US.yml
- src/Akeneo/Platform/Bundle/CommunicationChannelBundle/tests/front/__mocks__/oro/mediator.ts
- src/Akeneo/Platform/Bundle/CommunicationChannelBundle/tests/front/__mocks__/oro/translator.ts
- src/Akeneo/Platform/Bundle/CommunicationChannelBundle/tests/front/unit/components/panel/Panel.unit.tsx
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/pim-app.js
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/base/variables.less
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/Overlay.less
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/index.less
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/app.html
- src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/legacy-bridge/src/bridge/react/index.ts
- src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/legacy-bridge/src/bridge/react/reactElementHelper.ts
- src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/legacy-bridge/src/bridge/react/reactView.ts
- src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/legacy-bridge/src/index.ts
Ticket : https://github.com/akeneo/actionable-product-data/issues/135
| Added Unit tests                      | OK
> GITHUB-APD-135: Open/Close the panel when I click on the update link button

- CHANGELOG-4.0.md
- src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
The placeholder "label" was not translated after fixing this translation issue => https://github.com/akeneo/pim-community-dev/pull/12156
So, I just added spaces around "label" to solve the problem. …
> PIM-9264: Make "search on..." translatable on Crowdin

- src/Akeneo/Connectivity/Connection/front/src/error-management/components/Documentation/DocumentationList.tsx
- src/Akeneo/Connectivity/Connection/front/src/error-management/components/Documentation/DocumentationMessage.tsx
- src/Akeneo/Connectivity/Connection/front/src/error-management/components/Documentation/RouteDocumentationMessageParameter.tsx
- src/Akeneo/Connectivity/Connection/front/src/error-management/components/ErrorList/ErrorList.tsx
- src/Akeneo/Connectivity/Connection/front/src/error-management/hooks/api/use-connection-errors.ts
- src/Akeneo/Connectivity/Connection/front/src/error-management/model/ConnectionError.ts
> CXP-297: Display documentation in connection monitoring

- src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
- src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/Index.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptionItem.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptions.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/Edit.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/List.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/ToggleButton.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/contexts/attributeContext.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/contexts/index.ts
- src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/fetchers/baseFetcher.ts
- src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/hooks/useAttributeOptions.ts
- src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/hooks/useLocales.ts
- src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/reducers/attributeOptionsReducer.ts
- src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/store/store.ts
- src/Akeneo/Pim/Structure/Bundle/Resources/public/less/attribute-option.less
- src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/attribute/form/choices.tsx
- tests/front/unit/structure/attribute-option/components/List.unit.tsx
- tests/front/unit/structure/attribute-option/reducers/attributeOptionsReducer.unit.ts
- tests/front/unit/structure/attribute-option/reducers/localesReducer.unit.ts
> DAPI-1033: display a dynamic attribute options list

- src/Akeneo/Connectivity/Connection/back/Infrastructure/Cli/UpdateAuditDataCommand.php
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Audit/UpdateAuditDataCommandEndToEnd.php
Fix the collect of product events by executing command for previous and current hourly interval
> CXP-306: Fix the collect of product events

- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/associations.js
- src/Akeneo/Tool/Component/Api/tests/integration/Normalizer/ProductNormalizerIntegration.php
Fixing product normalizer inte tests & front lint
> Fixing product normalizer inte tests & front lint

- src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptions.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/Edit.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/List.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/New.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/NewOptionPlaceholder.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/hooks/useCreateAttributeOption.ts
- src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/reducers/attributeOptionsReducer.ts
- src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/reducers/index.ts
- src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml
- tests/front/unit/structure/attribute-option/components/Edit.unit.tsx
- tests/front/unit/structure/attribute-option/components/List.unit.tsx
- tests/front/unit/structure/attribute-option/reducers/attributeOptionsReducer.unit.ts
> DAPI-1037: allow attribute options to be added

- src/Akeneo/Connectivity/Connection/back/Infrastructure/Normalizer/ProductDomainErrorNormalizer.php
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/ErrorManagement/CollectApiError/CollectDomainErrorFromProductEndpointEndToEnd.php
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/ErrorManagement/CollectApiError/CollectProductDomainErrorEndToEnd.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Normalizer/ProductDomainErrorNormalizerSpec.php
- src/Akeneo/Connectivity/Connection/front/src/error-management/components/Documentation/DocumentationMessage.tsx
- src/Akeneo/Connectivity/Connection/front/src/error-management/components/Documentation/RouteDocumentationMessageParameter.tsx
- src/Akeneo/Connectivity/Connection/front/src/error-management/model/ConnectionError.ts
- src/Akeneo/Pim/Enrichment/Component/Error/Documented/Documentation.php
- src/Akeneo/Pim/Enrichment/Component/Error/Documented/DocumentationCollection.php
- src/Akeneo/Pim/Enrichment/Component/Error/Documented/DocumentedErrorInterface.php
- src/Akeneo/Pim/Enrichment/Component/Error/Documented/HrefMessageParameter.php
- src/Akeneo/Pim/Enrichment/Component/Error/Documented/MessageParameterInterface.php
- src/Akeneo/Pim/Enrichment/Component/Error/Documented/MessageParameterTypes.php
- src/Akeneo/Pim/Enrichment/Component/Error/Documented/RouteMessageParameter.php
- src/Akeneo/Pim/Enrichment/Component/Product/Exception/UnknownAttributeException.php
- tests/back/Pim/Enrichment/Integration/Product/Exception/DocumentedExceptionRouteExistsIntegration.php
- tests/back/Pim/Enrichment/Specification/Component/Error/Documented/DocumentationCollectionSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Error/Documented/DocumentationSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Error/Documented/HrefMessageParameterSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Error/Documented/RouteMessageParameterSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Exception/UnknownAttributeExceptionSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Updater/ProductUpdaterSpec.php
> CXP-322: Create VO to structure DocumentedErrorInterface

- src/Akeneo/Platform/Bundle/UIBundle/tests/front/unit/components/QuantifiedAssociations.unit.tsx
Fixing QuantifiedAssociations coverage
> Fixing QuantifiedAssociations coverage

- src/Akeneo/Tool/Bundle/VersioningBundle/Command/PurgeCommand.php
> Fix purge command name

- src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/Elasticsearch/Query/PurgeConnectionErrorsQuery.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Persistence/Elasticsearch/Query/PurgeConnectionErrorsQuerySpec.php
> CXP-323: fix purge connection errors cmd

- src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptions.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/Edit.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/hooks/useCreateAttributeOption.ts
- src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/hooks/useDeleteAttributeOption.ts
- src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/hooks/useSaveAttributeOption.ts
- tests/front/unit/structure/attribute-option/components/Edit.unit.tsx
> DAPI-1034-1037: display basic validation errors on create and update

- src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/AttributeOptionsApp.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptions.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/List.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/ToggleButton.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/contexts/AttributeContext.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/hooks/useAttributeContextState.ts
- src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/index.ts
- src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/model/Events.ts
- src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/model/index.ts
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/attribute/form/choices.tsx
- tests/front/unit/structure/attribute-option/components/List.unit.tsx
> DAPI-1035: allow options to be sorted alphabetically

- CHANGELOG-4.0.md
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/lib/jquery.jstree.less
Fixed : https://akeneo.atlassian.net/browse/PIM-9250
Fixes worked on mac chrome / firefox (latest)
Tested on the filter category product grid, settings category and dashboard …
> PIM-9250: Fix artifact in jstree branches

- src/Akeneo/Platform/Bundle/AnalyticsBundle/DataCollector/DBDataCollector.php
- src/Akeneo/Platform/Bundle/AnalyticsBundle/Query/Sql/ApiConnectionCount.php
- src/Akeneo/Platform/Bundle/AnalyticsBundle/Resources/config/data_collectors.yml
- src/Akeneo/Platform/Bundle/AnalyticsBundle/Resources/config/queries.yml
- src/Akeneo/Tool/Component/Analytics/ApiConnectionCountQuery.php
- tests/back/Platform/Acceptance/Analytics/Query/Sql/ApiConnectionCountInMemory.php
- tests/back/Platform/Acceptance/Analytics/Resources/config/queries.yml
- tests/back/Platform/Integration/Analytics/Query/ApiConnectionCountIntegration.php
- tests/back/Platform/Specification/Bundle/AnalyticsBundle/DataCollector/DBDataCollectorSpec.php
Add information to know how many connections have a PIM and how many are tracked or not
> CXP-278: Add info about connections in the PIM tracker

- src/Akeneo/Connectivity/Connection/back/Application/ErrorManagement/Service/CollectApiError.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/EventSubscriber/ApiErrorEventSubscriber.php
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/ErrorManagement/CollectApiError/CollectProductDomainErrorEndToEnd.php
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/ErrorManagement/CollectApiErrorsCountEndToEnd.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/ErrorManagement/Service/CollectApiErrorSpec.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/EventSubscriber/ApiErrorEventSubscriberSpec.php
- src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/ProductController.php
- src/Akeneo/Pim/Enrichment/Component/Product/Comparator/Filter/EntityWithValuesFilter.php
- src/Akeneo/Pim/Enrichment/Component/Product/Event/ProductDomainErrorEvent.php
- src/Akeneo/Pim/Enrichment/Component/Product/Exception/UnknownAttributeException.php
- src/Akeneo/Pim/Enrichment/Component/Product/Exception/UnknownCategoryException.php
- src/Akeneo/Pim/Enrichment/Component/Product/Exception/UnknownProductException.php
- src/Akeneo/Pim/Enrichment/Component/Product/Updater/ProductUpdater.php
- src/Akeneo/Pim/Enrichment/Component/Product/Updater/Setter/CategoryFieldSetter.php
- src/Akeneo/Pim/Enrichment/Component/Product/Updater/Setter/FamilyFieldSetter.php
- tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/CreateProductEndToEnd.php
- tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/DeleteProductEndToEnd.php
- tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/Media/CreateProductMediaFileEndToEnd.php
- tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/PartialUpdateProductEndToEnd.php
- tests/back/Pim/Enrichment/Integration/Product/Exception/DocumentedExceptionRouteExistsIntegration.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Event/ProductDomainErrorEventSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Exception/UnknownAttributeExceptionSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Exception/UnknownCategoryExceptionSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Exception/UnknownProductExceptionSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Updater/Setter/CategoryFieldSetterSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Updater/Setter/FamilyFieldSetterSpec.php
- tests/legacy/features/platform/import/view_import_items_invalid_data.feature
- Category doesn’t exist
- Attribute doesn’t exist
- Family doesn’t exist
- Product doesn’t exist
> CXP-311: update error messages

- CHANGELOG-3.2.md
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/lib/jquery.jstree.less
Fix : https://akeneo.atlassian.net/browse/PIM-9203
Remove box shadow from active select 2 container
> PIM-9203: Fix category tree product grid box shadow 3.2 

- src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptions.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/EmptyAttributeOptionsList.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/List.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/public/less/attribute-option.less
- src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml
- tests/front/unit/structure/attribute-option/components/Edit.unit.tsx
- tests/front/unit/structure/attribute-option/components/List.unit.tsx
> DAPI: display a placeholder when there is no option

- src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/AttributeOptionsApp.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/DeleteConfirmationModal.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/Edit.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/List.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/ListItem.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/New.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/NewOptionPlaceholder.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/OverridePimStyles.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/public/less/attribute-option.less
- src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml
- tests/front/unit/structure/attribute-option/components/List.unit.tsx
> DAPI - revamp attribute options misc

- CHANGELOG-4.0.md
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/Dbal/Query/DbalExtractConnectionsProductEventCountQuery.php
> PIM-9301: Fix extractUpdatedProductsByConnection query group by issue

- src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/Edit.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/EmptyAttributeOptionsList.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/List.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/ToggleButton.tsx
- tests/legacy/features/Context/Page/Attribute/Creation.php
- tests/legacy/features/pim/structure/attribute/display_available_field_options.feature
- tests/legacy/features/pim/structure/attribute/option/create_attribute_options.feature
> DAPI-1039: update end to end tests for the new options screen

- src/Akeneo/Pim/Enrichment/Component/Category/Normalizer/InternalApi/CategoryNormalizer.php
> Fix unknown key in category normalizer

- tests/back/Acceptance/FamilyVariant/InMemoryFamilyVariantRepository.php
- tests/back/Acceptance/FamilyVariant/InMemoryFamilyVariantsByAttributeAxes.php
- tests/back/Acceptance/Product/InMemoryProductRepository.php
- tests/back/Acceptance/Resources/config/pim/queries.yml
- tests/back/Acceptance/spec/FamilyVariant/InMemoryFamilyVariantRepositorySpec.php
- tests/back/Acceptance/spec/Product/InMemoryProductRepositorySpec.php
> PIM-9298: Add missing implems for acceptance tests

- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/Subsection.less
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/Grid.less
- src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/cell/label-cell.js
https://github.com/akeneo/pim-enterprise-dev/pull/9005
> RUL-280: Fix style

- src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/Edit.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/ListItem.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/New.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/NewOptionPlaceholder.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/ToggleButton.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/public/less/attribute-option.less
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/images/icon-row-move.svg
> DAPI - revamp attribute options UI fixes

- .circleci/config.yml
> TIP-1412: Onboarder bundle is always registred in EE

- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/base/variables.less
> DAPI-1069: add yellow140 color as a Less variable

- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/updaters.yml
- src/Akeneo/Pim/Enrichment/Component/Product/Builder/ProductBuilder.php
- src/Akeneo/Pim/Enrichment/Component/Product/Model/AbstractProduct.php
- src/Akeneo/Pim/Enrichment/Component/Product/Model/ProductModel.php
- src/Akeneo/Pim/Enrichment/Component/Product/Model/QuantifiedAssociation/EntityWithQuantifiedAssociationTrait.php
- src/Akeneo/Pim/Enrichment/Component/Product/Model/QuantifiedAssociation/QuantifiedAssociations.php
- src/Akeneo/Pim/Enrichment/Component/Product/QuantifiedAssociation/QuantifiedAssociationsMerger.php
- src/Akeneo/Pim/Enrichment/Component/Product/Updater/Adder/QuantifiedAssociationFieldAdder.php
- src/Akeneo/Pim/Enrichment/Component/Product/Updater/Clearer/Field/QuantifiedAssociationFieldClearer.php
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/mass-edit/form/product/associate.js
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/associations.js
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/quantified-associations/components/QuantifiedAssociationRow.tsx
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/quantified-associations/components/QuantifiedAssociations.tsx
- src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/shared/src/components/SearchBar.tsx
- tests/back/Pim/Enrichment/Specification/Component/Product/Model/ProductModelSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Model/QuantifiedAssociation/QuantifiedAssociationsSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/QuantifiedAssociation/QuantifiedAssociationsMergerSpec.php
> RAC-32: First version of mass edit quantified associations

- src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/QuantifiedAssociationsValidator.php
- tests/features/pim/enrichment/entity-with-quantified-associations/validate_quantified_associations.feature
> RAC-104: change 9999 limit to 2147483647 (integer limit)

- src/Akeneo/Platform/VersionProvider.php
> Fix the version provider

- src/Akeneo/Connectivity/Connection/back/Infrastructure/ErrorManagement/DocumentationBuilder/DefaultAttributeValidation.php
- src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/IsString.php
- src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/IsStringValidator.php
- src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/NotDecimal.php
- src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/NotDecimalValidator.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/IsStringValidatorSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/NotDecimalValidatorSpec.php
> CXP-348 CXP-349: Add documented message about is string and not decimal

- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/common/default-template.html
> DAPI-997: add a new dropzone to be able to display the "back" button

- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/mass-edit/form/product/associate.js
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/quantified-associations/components/QuantifiedAssociationRow.tsx
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/quantified-associations/models/quantified-association.ts
- src/Akeneo/Platform/Bundle/UIBundle/tests/front/unit/components/QuantifiedAssociationRow.unit.tsx
> RAC-106: fix large number management in quantity field

- src/Akeneo/Pim/Structure/Component/Validator/Constraints/NotDecimalValidator.php
- tests/legacy/features/pim/enrichment/product/validation/validate_localized_date_attributes.feature
- tests/legacy/features/pim/enrichment/product/validation/validate_localized_number_attributes.feature
- tests/legacy/features/pim/enrichment/product/validation/validate_localized_price_attributes.feature
1. Fix a coupling issue by removing unused imports
```
Node /srv/pim/src/Akeneo/Pim/Structure/Component/Validator/Constraints/NotDecimalValidator.php does not respect the rule Akeneo\Pim\Structure\Component because of the tokens:
* Akeneo\Pim\Enrichment\Component\Product\Model\ProductPriceInterface
1 coupling issues found ✖😥🍆
```
2. Fix failing behat legacy with the right French translation
| …
> Remove unused imports

- src/Akeneo/Connectivity/Connection/back/Infrastructure/ErrorManagement/DocumentationBuilder/DefaultAttributeValidation.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/ErrorManagement/DocumentationBuilder/DefaultAttributeValidationSpec.php
- src/Akeneo/Pim/Enrichment/Component/Product/Validator/ConstraintGuesser/RegexGuesser.php
- src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/Regex.php
- src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/RegexValidator.php
- src/Akeneo/Pim/Structure/Component/Validator/Constraints/NotDecimalValidator.php
- tests/back/Pim/Enrichment/Integration/Validation/ProductIdentifierValidationIntegration.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Validator/ConstraintGuesser/RegexGuesserSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/RegexSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/RegexValidatorSpec.php
- tests/legacy/features/pim/enrichment/product/validation/validate_identifier_attribute.feature
- tests/legacy/features/pim/enrichment/product/validation/validate_localized_date_attributes.feature
- tests/legacy/features/pim/enrichment/product/validation/validate_localized_number_attributes.feature
- tests/legacy/features/pim/enrichment/product/validation/validate_localized_price_attributes.feature
- tests/legacy/features/pim/enrichment/product/validation/validate_text_attributes.feature
> CXP-355: create custom regex validation constraint

- src/Akeneo/Connectivity/Connection/back/Infrastructure/ErrorManagement/DocumentationBuilder/DefaultAttributeValidation.php
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/validation/product.yml
- src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/validators.en_US.yml
- src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/validators.fr_FR.yml
- src/Akeneo/Pim/Enrichment/Component/Product/Validator/ConstraintGuesser/LengthGuesser.php
- src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/Length.php
- src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/LengthValidator.php
- tests/back/Pim/Enrichment/Integration/Validation/ProductIdentifierValidationIntegration.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Validator/ConstraintGuesser/LengthGuesserSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/LengthSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/LengthValidatorSpec.php
- tests/legacy/features/pim/enrichment/product/mass-edit/validate/validate_editing_common_text_attributes.feature
- tests/legacy/features/pim/enrichment/product/validation/validate_identifier_attribute.feature
- tests/legacy/features/pim/enrichment/product/validation/validate_text_attributes.feature
- tests/legacy/features/pim/enrichment/product/validation/validate_textarea_attributes.feature
> CXP-338: update length error message

- .circleci/config.yml
- src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/validators.en_US.yml
Add missing translation string for RegEx validation error message
> CXP-355: add regex validation error translation string

- tests/legacy/features/pim/enrichment/product/pef/edit_product_with_localized_attributes.feature
- tests/legacy/features/user-management/user/edit_user.feature
Fixes 2 unstable legacy behats
> Fix unstable legacy behats

- src/Akeneo/Connectivity/Connection/back/Infrastructure/ErrorManagement/DocumentationBuilder/DefaultAttributeValidation.php
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/validation/product.yml
- src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/validators.en_US.yml
- src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/NotBlank.php
- src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/NotBlankValidator.php
- tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/CreateProductEndToEnd.php
- tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/PartialUpdateProductEndToEnd.php
- tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/ExternalApi/PartialUpdateVariantProductEndToEnd.php
- tests/back/Pim/Enrichment/Integration/Validation/ProductIdentifierValidationIntegration.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/NotBlankSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/NotBlankValidatorSpec.php
- tests/legacy/features/pim/enrichment/product-model/add_product_model_children.feature
Add NotBlank validation constraint with custom message.
> CXP-360: add custom notblank validation error

- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/FilterBox.less
> DAPI-1115 fix color impact

- make-file/connectivity-connection.mk
- make-file/test.mk
- phpstan.neon
- src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/tests/phpstan-infra.neon
- src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/tests/phpstan.neon
> CXP-333: Use same naming convention as EE

- src/Akeneo/Connectivity/Connection/back/tests/phpstan-infra.neon
- src/Akeneo/Connectivity/Connection/back/tests/phpstan.neon
- src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/tests/phpstan-infra.neon
- src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/tests/phpstan.neon
> CXP-333: Rollback wrongs deleted files

- CHANGELOG-4.0.md
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/factories.yml
This is a backport of https://github.com/akeneo/pim-community-dev/pull/12371
> PIM-9343: Backport PIM-9324

- src/Akeneo/Pim/Enrichment/Component/Product/QuantifiedAssociation/QuantifiedAssociationsMerger.php
- tests/back/Pim/Enrichment/Specification/Component/Product/QuantifiedAssociation/QuantifiedAssociationsMergerSpec.php
> RAC-243: fix product model inheritance

- src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/attribute/index.yml
- src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/attribute/form/grid.js
> DAPI-1191: Regression on attribute grid search

- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/Tag.less
Fixing tag height in rule grid
https://akeneo.atlassian.net/secure/RapidBoard.jspa?rapidView=209&projectKey=RUL&modal=detail&selectedIssue=RUL-369
> RUL-369: Fix tag height

- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/updaters.yml
https://github.com/akeneo/pim-enterprise-dev/pull/9091
> RUL-187: Add missing services

- src/Akeneo/Platform/Bundle/CommunicationChannelBundle/README.md
Ticket : https://github.com/akeneo/actionable-product-data/issues/193
> GITHUB-APD-193: Add README to explain useful commands on the BC

- tests/front/unit/jest/unit.jest.js
> Change coverage threshold to opt-in

- .env
- CHANGELOG.md
- src/Akeneo/Pim/Structure/Bundle/Resources/config/datagrid/association_type.yml
- src/Akeneo/Pim/Structure/Bundle/Resources/translations/messages.en_US.yml
Enabled for everyone possibility to create quantified association
| Review and 2 GTM                  | Done
| Micro Demo to the PO (Story only) | Done
> RAC-54: feat: enabled for everyone possibility to create quantified association

- .circleci/config.yml
- src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/grid/mass-actions.js
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/grid/mass-actions.html
https://github.com/akeneo/pim-enterprise-dev/pull/9208
> RUL-377: Add plural for datagrid selected items

- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/TitleContainer.less
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/button/ActionButton.less
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/FilterBox.less
> DAPI-1217: Fix pagination & configure columns button

- CHANGELOG-4.0.md
- src/Akeneo/Pim/Enrichment/Bundle/Resources/views/Product/renderPdf.html.twig
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/Grid.less
- src/Akeneo/Tool/Bundle/ElasticsearchBundle/IndexConfiguration/Loader.php
- src/Akeneo/Tool/Bundle/ElasticsearchBundle/spec/IndexConfiguration/LoaderSpec.php
- src/Akeneo/Tool/Bundle/ElasticsearchBundle/spec/IndexConfiguration/conf1.yml
- src/Akeneo/Tool/Bundle/ElasticsearchBundle/spec/IndexConfiguration/conf2.yml
- src/Akeneo/Tool/Bundle/ElasticsearchBundle/spec/IndexConfiguration/conf3.yml
- src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/select-filter.js
> PIM-9354: Merge 4.0 into master

- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/validation/product.yml
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/validation/productmodel.yml
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/validation/quantifiedassociations.yml
- src/Akeneo/Pim/Enrichment/Component/Product/Builder/ProductBuilder.php
- src/Akeneo/Pim/Enrichment/Component/Product/Model/AbstractProduct.php
- src/Akeneo/Pim/Enrichment/Component/Product/Model/EntityWithQuantifiedAssociationsInterface.php
- src/Akeneo/Pim/Enrichment/Component/Product/Model/ProductModel.php
- src/Akeneo/Pim/Enrichment/Component/Product/Model/QuantifiedAssociation/EntityWithQuantifiedAssociationTrait.php
- src/Akeneo/Pim/Enrichment/Component/Product/Model/QuantifiedAssociation/QuantifiedAssociationCollection.php
- src/Akeneo/Pim/Enrichment/Component/Product/QuantifiedAssociation/QuantifiedAssociationsMerger.php
- src/Akeneo/Pim/Enrichment/Component/Product/Updater/Adder/QuantifiedAssociationFieldAdder.php
- src/Akeneo/Pim/Enrichment/Component/Product/Updater/Clearer/Field/QuantifiedAssociationFieldClearer.php
- src/Akeneo/Pim/Enrichment/Component/Product/Updater/Setter/QuantifiedAssociationsFieldSetter.php
- src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/QuantifiedAssociationsValidator.php
- tests/back/Pim/Enrichment/Integration/Storage/Sql/Product/QuantifiedAssociation/GetProductModelQuantifiedAssociationsByProductIdentifiersIntegration.php
- tests/back/Pim/Enrichment/Integration/Storage/Sql/Product/QuantifiedAssociation/GetProductQuantifiedAssociationsByProductIdentifiersIntegration.php
- tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductModel/QuantifiedAssociation/GetProductModelQuantifiedAssociationsByProductModelCodesIntegration.php
- tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductModel/QuantifiedAssociation/GetProductQuantifiedAssociationsByProductModelCodesIntegration.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Processor/Denormalizer/ProductAssociationProcessorSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Processor/Denormalizer/ProductModelAssociationProcessorSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Model/ProductModelSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Model/QuantifiedAssociation/QuantifiedAssociationCollectionSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/Versioning/EntityWithQuantifiedAssociations/QuantifiedAssociationsNormalizerSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/QuantifiedAssociation/QuantifiedAssociationsMergerSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Updater/Adder/QuantifiedAssociationFieldAdderSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Updater/Setter/QuantifiedAssociationsFieldSetterSpec.php
In this PR:
- Rename quantifiedAssociations by QuantifiedAssociationCollection
- Do not rename all occurence of quantifiedAssociations by QuantifiedAssociationCollection => too much modification (https://github.com/akeneo/pim-community-dev/pull/12446/files)
| Tech Doc …
> RAC-120: refactor: Rename QuantifiedAssociations by QuantifiedAssociationCollection

- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/quantified-associations/components/QuantifiedAssociations.tsx
> RAC-108: change bouton look

- CHANGELOG.md
- src/Akeneo/Pim/Structure/Bundle/Doctrine/ORM/Repository/ExternalApi/AttributeRepository.php
- tests/back/Pim/Structure/EndToEnd/Attribute/ExternalApi/ListAttributeEndToEnd.php
> API-1237: Add filter on attribute types

- src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/JobParameters/ConstraintCollectionProvider/ProductAndProductModelQuickExport.php
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/JobParameters/ConstraintCollectionProvider/ProductCsvExport.php
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/JobParameters/ConstraintCollectionProvider/ProductModelCsvExport.php
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/JobParameters/ConstraintCollectionProvider/ProductQuickExport.php
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/JobParameters/ConstraintCollectionProvider/ProductXlsxExport.php
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/JobParameters/DefaultValueProvider/ProductCsvExport.php
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/JobParameters/DefaultValueProvider/ProductModelCsvExport.php
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/JobParameters/DefaultValueProvider/ProductQuickExport.php
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/JobParameters/DefaultValueProvider/ProductXlsxExport.php
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/product/edit/field/file-locale.js
> RAC-147: add new parameters to product and product model exports

- src/Akeneo/Pim/Structure/Bundle/Controller/ExternalApi/FamilyController.php
- src/Akeneo/Pim/Structure/Bundle/Doctrine/ORM/Repository/ExternalApi/FamilyRepository.php
- src/Akeneo/Pim/Structure/Bundle/Resources/config/repositories.yml
- src/Akeneo/Tool/Bundle/ApiBundle/Resources/config/repositories.yml
- tests/back/Pim/Structure/EndToEnd/Family/ExternalApi/ListFamilyEndToEnd.php
- tests/back/Pim/Structure/Integration/Doctrine/ORM/Repository/ExternalApi/FamilyRepositoryApiResourceIntegration.php
> API-1212: Add filters on family search

- src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/JobParameters/ConstraintCollectionProvider/ProductAndProductModelQuickExport.php
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/JobParameters/ConstraintCollectionProvider/ProductCsvExport.php
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/JobParameters/ConstraintCollectionProvider/ProductModelCsvExport.php
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/JobParameters/ConstraintCollectionProvider/ProductQuickExport.php
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/JobParameters/ConstraintCollectionProvider/ProductXlsxExport.php
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/JobParameters/DefaultValueProvider/ProductCsvExport.php
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/JobParameters/DefaultValueProvider/ProductModelCsvExport.php
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/JobParameters/DefaultValueProvider/ProductQuickExport.php
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/JobParameters/DefaultValueProvider/ProductXlsxExport.php
- src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/translations/jsmessages.en_US.yml
- src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_product_export_edit.yml
- src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_product_model_export_edit.yml
- src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_product_export_edit.yml
- src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_product_model_export_edit.yml
- src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/common/edit/field/decimal-separator.js
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/product/edit/field/file-locale.js
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/product/edit/field/header-with-label.js
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/product/edit/field/with-label.js
> RAC-146: add frontend for export with labels

- src/Akeneo/Pim/Enrichment/Bundle/DependencyInjection/AkeneoPimEnrichmentExtension.php
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/connector/flat_translators.yml
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/writers.yml
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/FlatTranslator/FlatTranslatorInterface.php
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/FlatTranslator/NullFlatTranslator.php
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/Writer/File/Csv/ProductWriter.php
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/Writer/File/Xlsx/ProductWriter.php
- src/Akeneo/Tool/Component/Connector/Writer/File/AbstractItemMediaWriter.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Writer/File/Csv/ProductWriterSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Writer/File/Xlsx/ProductWriterSpec.php
This PR contain only a new translation layer in Product/Product model/Published product export writers.
| Added Specs                       | DOne
> RAC-158: feat: Add translation layer in writer

- CHANGELOG-3.2.md
- src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/bootstrap-modal/bootstrap-modal.js
https://akeneo.atlassian.net/browse/PIM-9380
For EE: https://github.com/akeneo/pim-enterprise-dev/pull/9380
> PIM-9380 : missing translations

- package.json
- webpack.config.js
- yarn.lock
In our code we are defining styled components like that for example
With the react devtools, the display name looks like this
That is not the best dev xp we could have.
The plugins change the displayname in the devtools
There is some more options in the lib to try, and maybe try to minify some styled components in the prod env.
But it's not the purpose of this pr and could be poc later.
https://github.com/Igorbek/typescript-plugin-styled-components
Tell me what you think about it ;)  …
> Add typescript styled components plugins

- src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/CategoryController.php
- src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Repository/ExternalApi/CategoryRepository.php
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/repositories.yml
- src/Akeneo/Tool/Bundle/ApiBundle/Resources/config/repositories.yml
- tests/back/Pim/Enrichment/EndToEnd/Category/ExternalApi/ListCategoryEndToEnd.php
- tests/back/Pim/Enrichment/Integration/Doctrine/ORM/Repository/CategoryRepositoryApiResourceIntegration.php
> API-1247: Add filter on category codes

- src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/messages.en_US.yml
- src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/messages.fr_FR.yml
- src/Akeneo/Tool/Component/Localization/LanguageTranslator.php
- src/Akeneo/Tool/Component/Localization/spec/LanguageTranslatorSpec.php
Adding the country name in the Language translation & adding french translations for `pim_common` keys.
> RAC-128: Add country name in Language translation & add french translations

- src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/Consolidation/ConsolidateAxesRates.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/GetProductAxesRates.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/GetProductAxesRatesInterface.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/GetProductEvaluation.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/ProductEvaluation/AxisRegistryInterface.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/ProductEvaluation/CreateMissingCriteriaEvaluations.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/ProductEvaluation/CreateMissingCriteriaEvaluationsInterface.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/ProductEvaluation/EvaluatePendingCriteria.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/ProductEvaluation/SynchronousCriterionEvaluationsFilter.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/ProductEvaluation/SynchronousCriterionEvaluationsFilterInterface.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Connector/Tasklet/EvaluateProductsCriteriaTasklet.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Install/InitializeJobs.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetUpToDateProductEvaluationQuery.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/ProductGrid/FetchEnrichmentForProductRows.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Controller/GetProductAxesRatesController.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/jobs.yml
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/queries.yml
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/services.yml
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Application/GetProductEvaluationSpec.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Application/ProductEvaluation/EvaluatePendingCriteriaSpec.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Persistence/Query/ProductEvaluation/GetUpToDateProductEvaluationQuerySpec.php
> DAPI-1209: rename classes

- package.json
- yarn.lock
> PIM-9406: Merge 3.0 into 3.2

- src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
- yarn.lock
> PIM-9394: Merge 3.2 into 4.0

- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Command/ConsolidateDashboardRatesCommand.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Command/LaunchEvaluationsCommand.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Command/PurgeOutdatedDataCommand.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Command/SchedulePeriodicTasksCommand.php
> DAPI: change commands prefix to "pim" instead of "pimee"

- src/Oro/Bundle/PimDataGridBundle/tests/Integration/Query/Sql/ListProductGridAvailableColumnGroupsIntegration.php
- src/Oro/Bundle/PimDataGridBundle/tests/Integration/Query/Sql/ListProductGridAvailableColumnsIntegration.php
> Fix product grid integration tests with DQI new column

- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/connector/flat_translators/attribute_value_translators.yml
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/FlatTranslator/AttributeValue/BooleanTranslator.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/FlatTranslator/AttributeValue/BooleanTranslatorSpec.php
Add Boolean attribute value flat translator
> RAC-132: Add Boolean flat translator

- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/connector/flat_translators/property_value_translators.yml
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/FlatTranslator/PropertyValue/CategoryTranslator.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/FlatTranslator/PropertyValue/CategoryTranslatorSpec.php
Adding category value flat translator
> RAC-165: Add category value translator

- src/Akeneo/Pim/Enrichment/Component/Product/Connector/FlatTranslator/PropertyValue/EnabledTranslator.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/FlatTranslator/PropertyValue/EnabledTranslatorSpec.php
Add Enabled property flat translator
> RAC-171: Add Enabled property flat translator

- config/bundles.php
- src/Akeneo/Tool/Bundle/WebhookBundle/AkeneoWebhookBundle.php
- src/Akeneo/Tool/Bundle/WebhookBundle/Client/RequestFactory.php
- src/Akeneo/Tool/Bundle/WebhookBundle/DependencyInjection/AkeneoWebhookExtension.php
- src/Akeneo/Tool/Bundle/WebhookBundle/Resources/config/services.yml
- src/Akeneo/Tool/Bundle/WebhookBundle/Security/Signature.php
> API-1273: add webhook security helper

- config/bundles.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Install/Query/CreateConnectionTableQuery.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/MessageHandler/BusinessEventHandler.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/Dbal/Query/DbalSelectConnectionsWebhookQuery.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/DependencyInjection/AkeneoConnectivityConnectionExtension.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/message_handler.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/queries.yml
- src/Akeneo/Pim/Enrichment/Bundle/Doctrine/Common/Saver/ProductSaver.php
- src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/ProductEventSubscriber.php
- src/Akeneo/Pim/Enrichment/Bundle/Message/BusinessEvent.php
- src/Akeneo/Pim/Enrichment/Bundle/Message/BusinessEventNormalizer.php
- src/Akeneo/Pim/Enrichment/Bundle/Message/ProductCreated.php
- src/Akeneo/Pim/Enrichment/Bundle/Message/ProductUpdated.php
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/event_subscribers.yml
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/messenger.yml
> API-1207: poc business event queue + webhooks

- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/connector/flat_translators/attribute_value_translators.yml
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/FlatTranslator/AttributeValue/MultiSelectFlatTranslator.php
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/FlatTranslator/AttributeValue/SimpleSelectFlatTranslator.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/FlatTranslator/AttributeValue/MultiSelectFlatTranslatorSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/FlatTranslator/AttributeValue/SimpleSelectFlatTranslatorSpec.php
> RAC-133: Add Simple select attribute flat translator

- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/connector/flat_translators/property_value_translators.yml
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/FlatTranslator/PropertyValue/GroupTranslator.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/FlatTranslator/PropertyValue/GroupTranslatorSpec.php
Add group property flat translator
> RAC-168: Add group property flat translator

- src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Query/SqlGetProductModelLabels.php
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/connector/flat_translators/property_value_translators.yml
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/FlatTranslator/PropertyValue/ParentTranslator.php
- src/Akeneo/Pim/Enrichment/Component/Product/Query/GetProductModelLabelsInterface.php
- tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductModel/SqlGetProductModelLabelsIntegration.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/FlatTranslator/PropertyValue/ParentTranslatorSpec.php
Add parent property flat translator
> RAC-172: Add parent property flat translator

- tests/back/Pim/Structure/Integration/Doctrine/ORM/Repository/ExternalApi/AttributeGroupRepositoryApiResourceIntegration.php
> disable test_to_search_attribute_groups_by_codes

- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/connector/flat_translators/property_value_translators.yml
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/FlatTranslator/PropertyValue/FamilyTranslator.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/FlatTranslator/PropertyValue/FamilyTranslatorSpec.php
Add family property value flat translator
> RAC-166: Add family property value flat translator

- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/connector/flat_translators/property_value_translators.yml
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/FlatTranslator/PropertyValue/FamilyVariantTranslator.php
- src/Akeneo/Pim/Structure/Bundle/Query/PublicApi/FamilyVariant/Sql/SqlGetFamilyVariantTranslations.php
- src/Akeneo/Pim/Structure/Bundle/Resources/config/queries.yml
- src/Akeneo/Pim/Structure/Component/Query/PublicApi/FamilyVariant/GetFamilyVariantTranslations.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/FlatTranslator/PropertyValue/FamilyVariantTranslatorSpec.php
- tests/back/Pim/Structure/Integration/FamilyVariant/SqlGetFamilyVariantTranslationsIntegration.php
Add family variant property value flat translator
> RAC-167: Add family variant property value flat translator

- config/packages/liip_imagine.yml
See https://github.com/akeneo/pim-enterprise-dev/pull/9318
> PIM-9372: Add thumbnail_small filter for media-link thumbnails

- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/connector/flat_translators/attribute_value_translators.yml
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/FlatTranslator/AttributeValue/MetricTranslator.php
- src/Akeneo/Tool/Bundle/MeasureBundle/DependencyInjection/AkeneoMeasureExtension.php
- src/Akeneo/Tool/Bundle/MeasureBundle/PublicApi/SqlGetUnitTranslations.php
- src/Akeneo/Tool/Bundle/MeasureBundle/Resources/config/public_api.yml
- src/Akeneo/Tool/Bundle/MeasureBundle/tests/Integration/PublicApi/SqlGetUnitTranslationsIntegration.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/FlatTranslator/AttributeValue/MetricTranslatorSpec.php
Add metric attribute value flat translator
> RAC-131: Add metric attribute value flat translator

- src/Akeneo/Pim/Enrichment/Component/Product/Connector/FlatTranslator/AttributeValue/MetricTranslator.php
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/FlatTranslator/AttributeValuesFlatTranslator.php
- src/Akeneo/Tool/Component/Connector/Writer/File/AbstractItemMediaWriter.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/FlatTranslator/AttributeValue/MetricTranslatorSpec.php
> RAC-131: Fix quick export

- config/packages/messenger.yml
- config/packages/test/messenger.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/MessageHandler/BusinessEventHandler.php
- src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/ProductEventSubscriber.php
- src/Akeneo/Pim/Enrichment/Bundle/Message/ProductCreated.php
- src/Akeneo/Pim/Enrichment/Bundle/Message/ProductUpdated.php
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/event_subscribers.yml
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/messenger.yml
- src/Akeneo/Platform/Component/EventQueue/BusinessEvent.php
- src/Akeneo/Platform/Component/EventQueue/BusinessEventInterface.php
- src/Akeneo/Platform/Component/EventQueue/BusinessEventNormalizer.php
> API-1283: Prepare BusinessEvent message

- src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Query/SqlGetProductLabels.php
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/connector/flat_translators.yml
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/connector/flat_translators/property_value_translators.yml
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/FlatTranslator/ProductAndProductModelFlatTranslator.php
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/FlatTranslator/PropertyValue/AssociationTranslator.php
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/FlatTranslator/PropertyValue/FlatPropertyValueTranslatorInterface.php
- src/Akeneo/Pim/Enrichment/Component/Product/Query/GetProductLabelsInterface.php
- tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductModel/SqlGetProductLabelsIntegration.php
- tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductModel/SqlGetProductModelLabelsIntegration.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/FlatTranslator/ProductAndProductModelFlatTranslatorSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/FlatTranslator/PropertyValue/AssociationTranslatorSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/FlatTranslator/PropertyValue/GroupTranslatorSpec.php
> RAC-170: Adds association translator for groups, products/product models and association with quantity

- tests/back/Pim/Enrichment/Integration/Product/Export/AbstractExportTestCase.php
- tests/back/Pim/Enrichment/Integration/Product/Export/Product/ExportProductsWithLabelsIntegration.php
- tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductModel/SqlGetProductModelLabelsIntegration.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/FlatTranslator/AttributeValuesFlatTranslatorSpec.php
> RAC-170: Add End2End tests

- src/Akeneo/Tool/Bundle/MessengerBundle/Serialization/JsonSerializer.php
- src/Akeneo/Tool/Bundle/MessengerBundle/spec/Serialization/JsonSerializerSpec.php
- src/Akeneo/Tool/Bundle/MessengerBundle/spec/Transport/GooglePubSub/GpsReceiverSpec.php
- src/Akeneo/Tool/Bundle/MessengerBundle/spec/Transport/GooglePubSub/GpsSenderSpec.php
Add missing unit tests (phpspec) to `Akeneo\Tool\Bundle\MessengerBundle\Transport\GooglePubSub` :
- JsonSerializer
- GpsReceiver
- GpsSender
> API-1275: add unit tests

- phpspec.yml.dist
- src/Akeneo/Tool/Bundle/WebhookBundle/Client/RequestFactory.php
- src/Akeneo/Tool/Bundle/WebhookBundle/spec/Client/RequestFactorySpec.php
- src/Akeneo/Tool/Bundle/WebhookBundle/spec/Security/SignatureSpec.php
⇒ ok :ok_hand: 
Add unit tests to webhook helpers
> API-1276: add unit tests to webhook bundle

- .github/workflows/dsm-test.yml
- akeneo-design-system/.github/workflows/deploy.yml
> RAC-217: add deployment of staging env

- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/Tag.less
Fix style on tags  
https://akeneo.atlassian.net/browse/RUL-436
> RUL-436: fix tags style

- upgrades/schema/Version_5_0_20200901102010_add_connection_webhook_columns.php
- upgrades/test_schema/Version_5_0_20200901102010_add_connection_webhook_columns_Integration.php
> CXP-381: Add connection webhook migration script

- src/Akeneo/Platform/Component/EventQueue/BusinessEventNormalizer.php
- tests/back/Pim/Enrichment/Specification/Bundle/Message/ProductCreatedSpec.php
- tests/back/Pim/Enrichment/Specification/Bundle/Message/ProductUpdatedSpec.php
- tests/back/Platform/Specification/Component/EventQueue/BusinessEventNormalizerSpec.php
> API-1320: Add BusinessEvent unit tests

- src/Akeneo/Platform/Component/EventQueue/BusinessEventNormalizer.php
- tests/back/Platform/Specification/Component/EventQueue/BusinessEventNormalizerSpec.php
> API-1320: Fix BusinessEvent unit tests

- CHANGELOG-4.0.md
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/doctrine/Product/ProductModel.orm.yml
- src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductGrid/ProductModelImagesFromCodes.php
- src/Akeneo/Pim/Enrichment/Component/Product/Model/ProductModel.php
- src/Akeneo/Pim/Enrichment/Component/Product/ProductModel/ImageAsLabel.php
- tests/back/Pim/Enrichment/Specification/Component/Product/ProductModel/ImageAsLabelSpec.php
Backport from https://github.com/akeneo/pim-community-dev/pull/11677/
> PIM:9340: Avoid deadlock error when loading product and product models in parallel with the API

- akeneo-design-system/package.json
"akeneo-design-system" repository is already pusblished on NPM. So we deploy it as scoped package under my username
> RAC-204: Add scoped package

- akeneo-design-system/package.json
> RAC-204: Start builld

- akeneo-design-system/src/components/Checkbox/Checkbox.stories.mdx
> RAC-225: add possibility to update ArgsTable directly from the playground

- config/packages/dev/monolog.yml
- config/packages/monolog.yml
- config/packages/test/monolog.yml
- config/packages/test_fake/monolog.yml
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Connector/Tasklet/LogMetricsTasklet.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/jobs.yml
Blocks: https://github.com/akeneo/pim-enterprise-dev/pull/9584
> Dapi 1325 - Add a logger in order to graph in datadog size of product table, product model table and dqi tables

- src/Akeneo/Pim/Structure/Bundle/Doctrine/ORM/Repository/InternalApi/FamilyVariantSearchableRepository.php
- tests/back/Pim/Structure/Integration/Doctrine/ORM/Repository/InternalApi/FamilyVariantSearchableRepositoryIntegration.php
> RUL-456: Fix family variant search by identifiers

- akeneo-design-system/src/components/index.ts
> RAC-223: add badge and button to the lib

- akeneo-design-system/package.json
RAC-254: Export before commands
> RAC-254: Export before commands

- .circleci/config.yml
Cleanup and reajust CI configuration from the EE one.
> BH-44 Reajust CE CircleCI config from EE one

- akeneo-design-system/.eslintrc.json
- akeneo-design-system/jest.unit.config.js
- akeneo-design-system/src/components/Badge/Badge.tsx
- akeneo-design-system/src/components/Badge/Badge.unit.tsx
- akeneo-design-system/src/components/Button/Button.tsx
- akeneo-design-system/src/components/Button/Button.unit.tsx
- akeneo-design-system/src/components/Checkbox/Checkbox.tsx
- akeneo-design-system/src/components/Checkbox/Checkbox.unit.tsx
- akeneo-design-system/tsconfig.json
- akeneo-design-system/tsconfig.lint.json
RAC-258: Include src folder in tsconfig to be able to simplify imports
> RAC-258: Use absolute paths imports

- .github/workflows/dsm-extract.yml
- .github/workflows/dsm-test.yml
> RAC-266: Move to akeneo repo

- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/attribute/form/edit-form.js
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/controller/attribute/create.js
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/attributes/create-button.js
> RUL-449: option to open attribute creation modal and prefill edit form with code

- akeneo-design-system/jest.unit.config.js
- akeneo-design-system/jest.visual.config.js
- akeneo-design-system/src/all.visual.tsx
- akeneo-design-system/src/index.unit.ts
Add a test that imports everything from `src/index.ts` and compares it with every component found in `src/components` and `src/icons`
> RAC-261: Add test to check exports

- src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/jobs.yml
- src/Akeneo/Tool/Component/Batch/Job/JobRegistry.php
Allow the possibility to remove a registered job profile. It's needed for a feature flag checked at runtime.
> RAC-265: fix shared catalog fixture flag

- src/Akeneo/Connectivity/Connection/back/Application/Webhook/Command/SendBusinessEventToWebhooksHandler.php
- src/Akeneo/Connectivity/Connection/back/Domain/Webhook/WebhookEvent/WebhookEventBuildingFailedException.php
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/webhook.yml
- src/Akeneo/Pim/Enrichment/Component/Product/Webhook/ProductEventDataBuilder.php
> API-1282: send product updated & created webhooks (part 1)

- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/commands.yml
> DAPI-1250: adapt the preparation of catalog evaluation for Data Quality Insights

- CHANGELOG-3.2.md
- src/Akeneo/Pim/Enrichment/Bundle/Product/Query/Sql/GetProductIdentifiersByGroup.php
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/normalizers.yml
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/ComputeDataRelatedToFamilyProductsTasklet.php
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/ComputeDataRelatedToFamilyRootProductModelsTasklet.php
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/ComputeDataRelatedToFamilySubProductModelsTasklet.php
- src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/GroupNormalizer.php
- src/Akeneo/Pim/Enrichment/Component/Product/Query/GetProductIdentifiersByGroupInterface.php
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/Column.less
- tests/back/Pim/Enrichment/Integration/Product/Query/Sql/GetProductIdentifiersByGroupIntegration.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Job/ComputeDataRelatedToFamilyProductsTaskletSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Job/ComputeDataRelatedToFamilyRootProductModelsTaskletSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Job/ComputeDataRelatedToFamilySubProductModelsTaskletSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/InternalApi/GroupNormalizerSpec.php
- tests/front/unit/jest/unit.jest.js
> PIM-9459: Merge 3.2 into 4.0

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Connector/Writer/File/Flat/GenerateHeadersFromAttributeCodes.php
- src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Connector/Writer/File/Flat/GenerateHeadersFromFamilyCodes.php
See: https://github.com/akeneo/pim-enterprise-dev/pull/9629
> PIM-9460: Fix performance issue on export

- .circleci/config.yml
Adapt the fix of https://github.com/akeneo/pim-enterprise-dev/pull/9624 on CE.
> Fix the Onboarder tests on the CI

- CHANGELOG-3.2.md
- CHANGELOG-4.0.md
- src/Akeneo/Pim/Enrichment/Bundle/Filter/ProductEditDataFilter.php
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/ComputeDataRelatedToFamilyProductsTasklet.php
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/ComputeDataRelatedToFamilyRootProductModelsTasklet.php
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/ComputeDataRelatedToFamilySubProductModelsTasklet.php
- src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/GroupNormalizer.php
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/Column.less
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Job/ComputeDataRelatedToFamilyProductsTaskletSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Job/ComputeDataRelatedToFamilyRootProductModelsTaskletSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Job/ComputeDataRelatedToFamilySubProductModelsTaskletSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/InternalApi/GroupNormalizerSpec.php
- tests/front/unit/jest/unit.jest.js
> PIM-9462: Merge branch 4.0 into master

- akeneo-design-system/package.json
- akeneo-design-system/src/components/Checkbox/Checkbox.stories.mdx
- akeneo-design-system/src/components/Checkbox/Checkbox.tsx
- akeneo-design-system/src/components/Checkbox/Checkbox.unit.tsx
> RAC-256: change the checked property from a checkbox element

- src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Repository/AttributeGroupActivationRepositoryInterface.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Repository/AttributeGroupActivationRepository.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Subscriber/AttributeGroup/UpdateAttributeGroupActivationSubscriber.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/subscribers.yml
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/.php_cd.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Persistence/Repository/AttributeGroupActivationRepositoryIntegration.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Subscriber/UpdateAttributeGroupActivationSubscriberIntegration.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Subscriber/AttributeGroup/UpdateAttributeGroupActivationSubscriberSpec.php
To synchronize the attribute group activations.
> DAPI-1282: Add subscriber to update attribute group activation on create and remove

- src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Model/AttributeGroupActivation.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Query/Structure/GetAttributeGroupActivationQueryInterface.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Repository/AttributeGroupActivationRepositoryInterface.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/ValueObject/AttributeGroupCode.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Install/EventSubscriber/InitDataQualityInsightsDbSchemaSubscriber.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/Structure/GetAttributeGroupActivationQuery.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Repository/AttributeGroupActivationRepository.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Subscriber/AttributeGroup/UpdateAttributeGroupActivationSubscriber.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Controller/GetAttributeGroupActivationController.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Controller/UpdateAttributeGroupActivationController.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/controllers.yml
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/queries.yml
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/repositories.yml
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/routing.yml
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/subscribers.yml
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/.php_cd.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Persistence/Query/Structure/GetAttributeGroupActivationQueryIntegration.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Persistence/Repository/AttributeGroupActivationRepositoryIntegration.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Subscriber/UpdateAttributeGroupActivationSubscriberIntegration.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Subscriber/AttributeGroup/UpdateAttributeGroupActivationSubscriberSpec.php
- upgrades/schema/Version_5_0_20200921153252_dqi_create_table_attribute_group_activation.php
- upgrades/test_schema/Version_5_0_20200921153252_dqi_create_table_attribute_group_activation_Integration.php
Add table, query, repository and controllers to manage DQI activation on attribute groups.
> DAPI-1281: Attribute group - Back - Table, Repository, Controller

- .github/workflows/dsm-extract.yml
> fix: pim-community-dev cannot checkout akeneo-design-system because the repository is private

- CHANGELOG.md
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/grid/mass-actions.js
Fixes a regression introduced in the last pull up #12760 
> PIM-9466: Fix selection counter in datagrid

- src/Akeneo/Connectivity/Connection/back/Application/Webhook/Command/UpdateWebhookCommand.php
- src/Akeneo/Connectivity/Connection/back/Application/Webhook/Validation/EnabledWebhookRequiresAnUrlValidator.php
- src/Akeneo/Connectivity/Connection/back/Domain/Webhook/Model/Write/ConnectionWebhook.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Install/Query/CreateConnectionTableQuery.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/routing.yml
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Webhook/UpdateWebhookEndToEnd.php
- src/Akeneo/Connectivity/Connection/back/tests/Integration/Persistence/Dbal/Query/DbalGetAConnectionWebhookQueryIntegration.php
- src/Akeneo/Connectivity/Connection/back/tests/Integration/Persistence/Dbal/Repository/DbalConnectionWebhookRepositoryIntegration.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Webhook/Command/UpdateWebhookCommandSpec.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Webhook/Command/UpdateWebhookHandlerSpec.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Webhook/Validation/EnabledWebhookRequiresAnUrlSpec.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Webhook/Validation/EnabledWebhookRequiresAnUrlValidatorSpec.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Domain/Webhook/Exception/ConnectionWebhookNotFoundExceptionSpec.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Domain/Webhook/Model/Write/ConnectionWebhookSpec.php
- src/Akeneo/Connectivity/Connection/front/src/webhook/pages/Index.tsx
- upgrades/schema/Version_5_0_20200901102010_add_connection_webhook_columns.php
> CXP-383: Add test

- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/datagrid/product.yml
- src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
- src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/messages.en_US.yml
- src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/select-filter.js
- src/Oro/Bundle/PimFilterBundle/Filter/Product/ProductTypologyFilter.php
- src/Oro/Bundle/PimFilterBundle/Resources/config/filters.yml
- src/Oro/Bundle/PimFilterBundle/spec/Filter/Product/ProductTypologyFilterSpec.php
- tests/back/Pim/Enrichment/Integration/PQB/Filter/FamilyVariantFilterIntegration.php
- tests/legacy/features/pim/enrichment/product-model/create_product_model.feature
Adds a new filter in product grid
| Added Specs                       | :+1: 
| Added legacy Behats               | :-1: 
| Added acceptance tests            | :-1: 
| Added integration tests           | :-1: 
| Changelog updated                 | :-1: 
| Review and 2 GTM                  | :-1: 
| Micro Demo to the PO (Story only) | :-1: 
> PM2020-19: Add Product Typology Filter

- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/datagrid/product.yml
| Added Specs                       | :-1:
| Added legacy Behats               | :-1:
| Added acceptance tests            | :-1:
| Added integration tests           | :-1:
| Changelog updated                 | :-1:
| Review and 2 GTM                  | :-1:
| Micro Demo to the PO (Story only) | :-1:
> PM2020-16: Add Identifier filter

- .github/workflows/dsm-test.yml
- akeneo-design-system/package.json
- akeneo-design-system/rollup.config.js
> RAC-257: add lib build check

- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Controller/UpdateAttributeGroupActivationController.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/acl.yml
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/controllers.yml
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/translations/messages.en_US.yml
> DAPI-1243: Add ACL to edit attribute group activation

- CHANGELOG-4.0.md
- src/Akeneo/Pim/Structure/Bundle/Doctrine/ORM/Repository/ExternalApi/AttributeRepository.php
- tests/back/Pim/Structure/EndToEnd/Attribute/ExternalApi/ListAttributeEndToEnd.php
> PIM-9469: [Backport] API-1232: Be able to get list of attribute from the API

- CHANGELOG-4.0.md
- src/Akeneo/Pim/Structure/Bundle/Doctrine/ORM/Repository/ExternalApi/AttributeRepository.php
- tests/back/Pim/Structure/EndToEnd/Attribute/ExternalApi/ListAttributeEndToEnd.php
> API-1237: [Backport] Add filter on attribute types

- akeneo-design-system/src/index.unit.tsx
> RAC-260: add test on rest props

- config/packages/test/messenger.yml
> API-1323: Setup Symfony messenger config for test env

- src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_product_import_edit.yml
- src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_product_model_export_edit.yml
https://github.com/akeneo/pim-community-dev/issues/12704
> #12704 Remove duplicate YAML keys

- .github/actions/extract/README.md
> RAC-252: update extract to github readme

- akeneo-design-system/src/shared/PreviewGallery.tsx
- akeneo-design-system/src/theme/Colors.stories.mdx
> RAC-190: add split of colors

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Standard/Product/ProductValueNormalizer.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/Standard/Product/ProductValueNormalizerSpec.php
https://github.com/akeneo/pim-community-dev/issues/12578
> #12578 Fix trailing zeros

- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/datagrid/product.yml
- src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/TitleContainer.less
- src/Oro/Bundle/PimDataGridBundle/Resources/config/requirejs.yml
- src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/grouped-variant-filter.js
- src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/select-filter.js
- src/Oro/Bundle/PimDataGridBundle/Resources/public/templates/datagrid/display-selector.html
- src/Oro/Bundle/PimDataGridBundle/Resources/public/templates/filter/filter-grouped-variant.html
- src/Oro/Bundle/PimFilterBundle/Filter/Product/EntityTypeFilter.php
- src/Oro/Bundle/PimFilterBundle/Resources/config/filters.yml
- src/Oro/Bundle/PimFilterBundle/spec/Filter/Product/EntityTypeFilterSpec.php
> PM2020-18: Add Grouped/Ungrouped filter

- akeneo-design-system/.github/workflows/deploy.yml
> fix: use github_token instead

- akeneo-design-system/src/components/Badge/Badge.stories.mdx
- akeneo-design-system/src/components/Badge/Badge.unit.tsx
- akeneo-design-system/src/components/Button/Button.stories.mdx
- akeneo-design-system/src/components/Button/Button.unit.tsx
- akeneo-design-system/src/components/Checkbox/Checkbox.stories.mdx
- Remove commented code
- Use project render instead of call basic render method with theme provider
- Remove no needed json with type (this key is present something in code, it add confusion) 
- Remove no needed import
`Todo`: …
> Add more consistency on component test and component stories

- akeneo-design-system/.github/workflows/deploy.yml
Deployment on master doesn't work because the secrets "ACTIONS_DEPLOY_KEY" doesn't exist since we changed of repository (from https://github.com/samirboulil/dsm to https://github.com/akeneo/akeneo-design-system).
Instead of use specific deployment key (Personal Access Token related to one user), we use now the GITHUB_TOKEN automatically generated by github.
| Micro Demo …
> Fix DSM deployment

- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Controller/UpdateAttributeGroupActivationController.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/requirejs.yml
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/js/infrastructure/attribute-group/dqi-activation.tsx
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
- src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/AttributeGroup/AttributeGroupDQIActivation.tsx
- src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/AttributeGroup/HelperMessage.tsx
- src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/AttributeGroup/ToggleActivation.tsx
- src/Akeneo/Pim/Automation/DataQualityInsights/front/src/index.ts
- src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/fetcher/AttributeGroup/fetchAttributeGroupStatus.ts
- src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/hooks/AttributeGroup/useAttributeGroupState.ts
- src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/saver/AttributeGroup/saveAttributeGroupActivation.ts
- src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/attribute_group/edit.yml
With the DQI feature deactivated : 
With the feature flag activated but without the ACL : 
> DAPI-1280: attribute group activation / deactivation for DQI

- src/Akeneo/Connectivity/Connection/back/Application/Webhook/Command/GenerateWebhookSecretCommand.php
- src/Akeneo/Connectivity/Connection/back/Application/Webhook/Command/GenerateWebhookSecretHandler.php
- src/Akeneo/Connectivity/Connection/back/Application/Webhook/Command/UpdateWebhookHandler.php
- src/Akeneo/Connectivity/Connection/back/Application/Webhook/Service/GenerateSecretInterface.php
- src/Akeneo/Connectivity/Connection/back/Application/Webhook/Validation/ConnectionMustExist.php
- src/Akeneo/Connectivity/Connection/back/Application/Webhook/Validation/ConnectionMustExistValidator.php
- src/Akeneo/Connectivity/Connection/back/Domain/Webhook/Persistence/Query/SaveWebhookSecretQuery.php
- src/Akeneo/Connectivity/Connection/back/Domain/Webhook/Persistence/Query/SelectWebhookSecretQuery.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/InternalApi/Controller/WebhookController.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/Dbal/Query/DbalSaveWebhookSecretQuery.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/Dbal/Query/DbalSelectWebhookSecretQuery.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/handlers.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/queries.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/services.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/validation/WriteConnectionWebhook.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/validators.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/GenerateSecret.php
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Webhook/UpdateWebhookEndToEnd.php
- src/Akeneo/Connectivity/Connection/back/tests/Integration/Fixtures/WebhookLoader.php
- src/Akeneo/Connectivity/Connection/back/tests/Integration/Persistence/Dbal/Query/DbalGetAConnectionWebhookQueryIntegration.php
- src/Akeneo/Connectivity/Connection/back/tests/Integration/Persistence/Dbal/Query/DbalSaveWebhookSecretQueryIntegration.php
- src/Akeneo/Connectivity/Connection/back/tests/Integration/Persistence/Dbal/Query/DbalSelectConnectionsWebhookQueryIntegration.php
- src/Akeneo/Connectivity/Connection/back/tests/Integration/Persistence/Dbal/Query/DbalSelectWebhookSecretQueryIntegration.php
- src/Akeneo/Connectivity/Connection/back/tests/Integration/Resources/config/loaders.yml
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Webhook/Command/GenerateWebhookSecretCommandSpec.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Webhook/Command/GenerateWebhookSecretHandlerSpec.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Webhook/Command/UpdateWebhookHandlerSpec.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Webhook/Validation/ConnectionMustExistSpec.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Webhook/Validation/ConnectionMustExistValidatorSpec.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Webhook/GenerateSecretSpec.php
> CXP-400: Generate a webhook secret

- src/Akeneo/Connectivity/Connection/front/src/webhook/hooks/api/use-update-webhook.tsx
- src/Akeneo/Connectivity/Connection/front/src/webhook/pages/EditConnectionWebhook.tsx
> CXP-401: Generate secret when saving new webhook

- akeneo-design-system/src/components/Checkbox/Checkbox.stories.mdx
- akeneo-design-system/src/components/Checkbox/Checkbox.tsx
- akeneo-design-system/src/components/Checkbox/Checkbox.unit.tsx
Using `boolean | 'mixed'` as type for Checkbox value
> Checkbox type

- akeneo-design-system/src/components/Button/Button.tsx
> fix: do not change css when button is disabled on hover and active

- src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/datagrid/job_tracker.yml
> RAC-179: add user sorting and filtering

- composer.json
- composer.lock
Fix memory leak issue.
https://github.com/phpspec/prophecy/pull/420
> CXP-408: Bump prophecy version

- src/Akeneo/Connectivity/Connection/front/src/webhook/components/EditForm.tsx
- src/Akeneo/Connectivity/Connection/front/src/webhook/hooks/api/use-update-webhook.tsx
- src/Akeneo/Connectivity/Connection/front/src/webhook/pages/EditConnectionWebhook.tsx
- src/Akeneo/Connectivity/Connection/front/src/webhook/pages/RegenerateWebhookSecret.tsx
> CXP: Fix tests

- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Webhook/ConsumeBusinessEventEndToEnd.php
> API-1333: Consume business event end-to-end test

- src/Akeneo/Connectivity/Connection/back/Application/Webhook/Command/SendBusinessEventToWebhooksHandler.php
- src/Akeneo/Connectivity/Connection/back/Application/Webhook/WebhookEventBuilder.php
- src/Akeneo/Connectivity/Connection/back/Domain/Webhook/Client/WebhookRequest.php
- src/Akeneo/Connectivity/Connection/back/Domain/Webhook/Model/WebhookEvent.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/handlers.yml
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Webhook/Command/SendBusinessEventToWebhooksHandlerSpec.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Webhook/WebhookEventBuilderSpec.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Domain/Webhook/Client/WebhookRequestSpec.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Domain/Webhook/Model/WebhookEventSpec.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Webhook/Client/GuzzleWebhookClientSpec.php
TODO: add "**author**" and "**pim_source**".
```json
{
"action": "product.created",
"author": "julia",
"event_id": "6ad821d8-2468-4632-89d2-92e442c72313",
"event_date": "2020-01-01T00:00:00+00:00",
"pim_source": "staging.akeneo.com",
"data": {
"resource": {
"identifier": "blue_shirt"
}
}
}
```
> CXP-412: Update the webhook event format

- src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml
- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/attribute-groups/AttributeGroupsDataGrid.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/attribute-groups/NoSearchResult.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/shared/datagrids/DataGrid.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/shared/datagrids/DraggableRowWrapper.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/shared/datagrids/HeaderRow.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/shared/layouts/tables/TableCell.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/shared/layouts/tables/TableContainer.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/shared/layouts/tables/TableHeadCell.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/shared/providers/DataGridStateProvider.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/shared/useDataGridState.ts
- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/hooks/shared/useDataGridState.unit.tsx
- src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/shared/src/components/SearchBar.tsx
**Default render :**
**Render when searching for a group:**
> DAPI-1288: make attribute groups grid filterable

- src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Query/Structure/GetAllAttributeGroupsActivationQueryInterface.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/Structure/GetAllAttributeGroupsActivationQuery.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Controller/GetAllAttributeGroupsActivationController.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/controllers.yml
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/queries.yml
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/routing.yml
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/less/index.less
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/less/quality-badges.less
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
- src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml
- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/attribute-groups/AttributeGroupsDataGrid.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/attribute-groups/NoSearchResult.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/shared/datagrids/DataGrid.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/shared/datagrids/DraggableRowWrapper.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/shared/datagrids/HeaderRow.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/shared/layouts/tables/TableCell.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/shared/layouts/tables/TableContainer.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/shared/layouts/tables/TableHeadCell.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/shared/providers/DataGridStateProvider.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/attribute-groups/useAttributeGroupsDataGridState.ts
- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/shared/useDataGridState.ts
- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/infrastructure/fetchers/attributeGroupDqiStatusFetcher.ts
- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/infrastructure/fetchers/index.ts
- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/models/AttributeGroup.ts
- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/__mocks__/pim/feature-flags.ts
- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/hooks/attribute-groups/useAttributeGroupsDataGridState.unit.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/hooks/shared/useDataGridState.unit.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/utils/provideAttributeGroupHelper.ts
- src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/shared/src/components/SearchBar.tsx
**With the DQI feature :**
**Without the DQI feature :**
> DAPI-1287 / DAPI-1314: add DQI status badges on attribute groups grid

- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
- src/Akeneo/Connectivity/Connection/front/src/common/components/ToggleButton.tsx
- src/Akeneo/Connectivity/Connection/front/src/common/components/button/ApplyButton.tsx
- src/Akeneo/Connectivity/Connection/front/src/common/components/button/Button.tsx
- src/Akeneo/Connectivity/Connection/front/src/common/components/button/GhostButton.tsx
- src/Akeneo/Connectivity/Connection/front/src/common/components/button/GreyButton.tsx
- src/Akeneo/Connectivity/Connection/front/src/common/components/button/ImportantButton.tsx
- src/Akeneo/Connectivity/Connection/front/src/common/icons/LoaderIcon.tsx
- src/Akeneo/Connectivity/Connection/front/src/common/icons/index.ts
- src/Akeneo/Connectivity/Connection/front/src/webhook/components/EditForm.tsx
- src/Akeneo/Connectivity/Connection/front/src/webhook/components/TestUrlButton.tsx
- src/Akeneo/Connectivity/Connection/front/src/webhook/hooks/api/use-webhook.ts
- src/Akeneo/Connectivity/Connection/front/src/webhook/pages/EditConnectionWebhook.tsx
- Fixed page title
- Fixed display of URL form input errors
- Added loading spinner on test URL button + disabled button while checking
- Fixed "enable" webhook toggle button
> CXP-417: fix event-subscription form

- akeneo-design-system/src/hooks/useShortcut.unit.ts
Add useShortcut unit test with provided ref
> RAC-306: Add useShortcut unit test with provided ref

- yarn.lock
> Dsm update yarn lock

- .github/workflows/dsm-extract.yml
RAC-268: Use master branch instead of dsm
> RAC-268: Use master branch instead of dsm

- tests/back/Pim/Enrichment/Specification/Bundle/Doctrine/Common/Saver/ProductSaverSpec.php
> API-1332 : As Filips, I want to be notified when a product has been created (API-1289 spec tests)

- src/Akeneo/Connectivity/Connection/front/src/common/icons/LoaderIcon.tsx
- src/Akeneo/Connectivity/Connection/front/src/settings/components/credentials/CopiableCredential.tsx
- src/Akeneo/Connectivity/Connection/front/src/webhook/components/TestUrlButton.tsx
> CXP: Fix copy secret button & test url spinner css

- .github/actions/extract/README.md
- .github/workflows/dsm-extract.yml
- akeneo-design-system/src/storybook/test-util.tsx
> DSM: Fixing review comments

- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/acl.yml
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/acl_groups.yml
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/translations/messages.en_US.yml
> DAPI-1243 - Add the ACL in a dedicated dqi group

- Makefile
- akeneo-design-system/tsconfig.json
- frontend/webpack/requirejs-utils.js
- std-build/Makefile
> DSM: fix DSM circleci error

- .circleci/run_behat.sh
Remove the retry 'feature" on behat test.
> BH15: Remove Behat retry workaround

- .github/workflows/dsm-extract.yml
- akeneo-design-system/.github/workflows/deploy.yml
It should resolve the following problem: https://github.com/akeneo/pim-community-dev/actions/runs/291385909
> Fix: The workflow is not valid. .github/workflows/dsm-extract.yml (Line: 18, Col: 14): Unexpected value

- akeneo-design-system/.github/workflows/deploy.yml
- akeneo-design-system/.github/workflows/tag-and-publish-to-npm.yml
> Fix: akeneo-design-system: No such file or directory

- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Webhook/ConsumeBusinessProductModelEventEndToEnd.php
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Webhook/ProduceBusinessProductModelEventEndToEnd.php
- src/Akeneo/Connectivity/Connection/front/src/webhook/components/EditForm.tsx
- src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/ProductModelEventSubscriber.php
- tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/ProductModelEventSubscriberSpec.php
> API-1309: As Filips, I want to be notified when a product model has been created

- CHANGELOG-3.2.md
- src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Repository/GroupRepository.php
- src/Akeneo/Pim/Structure/Bundle/Doctrine/ORM/Repository/AttributeOptionRepository.php
see https://github.com/akeneo/pim-community-dev/pull/12944
> PIM-9501: [Backport] PIM-9494

- package.json
- yarn.lock
Apparently, when the symlink is explicitly relative, it does not work on EE.
> Fix dsm link with implicit relative directory

- src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/ProductModelEditFormApp.tsx
- src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/hooks/AttributeGroup/useProductEvaluatedAttributeGroups.ts
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/infrastructure/hooks/AttributeGroup/useProductEvaluatedAttributeGroups.unit.tsx
**Not displayed on a product model with a pending evaluation** :
**On a sub product model :**
> DAPI-1290: display attribute group helper also on product models

- src/Akeneo/Pim/Enrichment/Bundle/Doctrine/Common/Saver/ProductSaver.php
- src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/BusinessEvent/DispatchProductBusinessEventSubscriber.php
- src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/BusinessEvent/DispatchProductModelBusinessEventSubscriber.php
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/event_subscribers.yml
- tests/back/Pim/Enrichment/Specification/Bundle/Doctrine/Common/Saver/ProductSaverSpec.php
- tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/BusinessEvent/DispatchProductBusinessEventSubscriberSpec.php
- tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/BusinessEvent/DispatchProductModelBusinessEventSubscriberSpec.php
> CXP-426: Fix business event naming

- config/services/pim_parameters.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/webhook.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/Client/GuzzleWebhookClient.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Webhook/Client/GuzzleWebhookClientSpec.php
- Added config parameters for the webhook client options
- Shortened the request timeout to 500ms
> CXP-431: shorten the timeout while sending webhooks

- src/Akeneo/Platform/Bundle/UIBundle/Resources/config/locale_provider.yml
Autralian files are added in the following PR: https://github.com/akeneo/pim-community-dev/pull/13002
We can it to the interface
> Add locale en_AU (Australia)

- CHANGELOG-3.2.md
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/validators.yml
- src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/Product/UniqueProductModelEntityValidator.php
- src/Akeneo/Pim/Enrichment/Component/Product/Validator/UniqueValuesSet.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/Product/UniqueProductModelEntityValidatorSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/UniqueValueValidatorSpec.php
- tests/legacy/features/Behat/Context/Domain/Enrich/ProductModelContext.php
- tests/legacy/features/pim/enrichment/product-model/import/import_with_invalid_data.feature
Backport of https://github.com/akeneo/pim-community-dev/pull/12925
> GITHUB-12899: Fix error shown when importing product models with the same code

- src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/TabContent/DataQualityInsights/AttributesGroupsHelper.tsx
- src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/TabContent/DataQualityInsightsTabContent.tsx
- src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/hooks/AttributeGroup/useProductEvaluatedAttributeGroups.ts
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/infrastructure/hooks/AttributeGroup/useProductEvaluatedAttributeGroups.unit.tsx
> DAPI-1406: fix no attribute group message when a product evaluation has not been refreshed

- akeneo-design-system/example/src/__snapshots__/App.test.js.snap
In the following PR : https://github.com/akeneo/pim-community-dev/pull/12961
The Badge component have changed, but the related test was not modified. 
> fix: dsm tests does not pass

- .circleci/config.yml
- .circleci/detect_structure_changes.sh
- CHANGELOG.md
- Dockerfile.base
- Dockerfile.dev
- composer.json
- composer.lock
- docker-compose.yml
- docker/build/docker-php-entrypoint
- make-file/test.mk
- src/Akeneo/Pim/Enrichment/Component/Product/Comparator/Attribute/MetricComparator.php
- src/Akeneo/Pim/Enrichment/Component/Product/Comparator/Attribute/ScalarComparator.php
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/FlatToStandard/AttributeColumnInfoExtractor.php
- src/Akeneo/Pim/Enrichment/Component/Product/Updater/Copier/AttributeCopier.php
- src/Akeneo/Pim/Enrichment/Component/Product/Updater/Copier/MetricAttributeCopier.php
- src/Akeneo/Platform/PimRequirements.php
- src/Akeneo/Tool/Bundle/ElasticsearchBundle/spec/Cursor/CursorSpec.php
- src/Akeneo/Tool/Bundle/MeasureBundle/Convert/MeasureConverter.php
- symfony.lock
- tests/back/Integration/IntegrationTestsBundle/Loader/FixturesLoader.php
- tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/CursorSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Updater/Copier/AttributeCopierSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Updater/Copier/MetricAttributeCopierSpec.php
- tests/legacy/features/Context/Page/Attribute/Creation.php
Check https://github.com/akeneo/pim-enterprise-dev/pull/8092 for the description and to know how to merge it.
> TIP-1233: upgrade to PHP 7.4

- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/connector/processors.yml
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/job_constraints.yml
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/job_defaults.yml
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/jobs.yml
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/steps.yml
- src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
- src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/messages.en_US.yml
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/Processor/MassEdit/ConvertToSimpleProductProcessor.php
- src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev/jobs.yml
- src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/minimal/jobs.yml
- src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/mass_edit/product.yml
- src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/mass-edit/form/product/convert-to-simple-product.ts
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Processor/MassEdit/ConvertToSimpleProductProcessorSpec.php
- upgrades/schema/Version_5_0_20201013070505_add_convert_to_simple_product_job.php
- upgrades/schema/Version_5_0_20201013070505_add_convert_to_simple_products_job.php
- upgrades/test_schema/Version_5_0_20201013070505_add_convert_to_simple_products_job_Integration.php
> PM2020-11: As Julia, I would like to bulk convert variant products to simple products

- tests/legacy/features/Behat/Decorator/Export/Filter/Select2Decorator.php
- tests/legacy/features/Context/DataGridContext.php
- tests/legacy/features/Context/WebUser.php
- tests/legacy/features/user-management/role/create_edit_and_delete_role.feature
Trying to solve these issues :shrug: 
vendor/akeneo/pim-community-dev/tests/legacy/features/user-management/role/create_edit_and_delete_role.feature:11
tests/legacy/features/pim/work-organization/workflow/proposal/list_proposals.feature:71
vendor/akeneo/pim-community-dev/tests/legacy/features/platform/acl/ensure_acl_on_export_profile.feature:21
> Fix random behats

- CHANGELOG.md
- docker-compose.yml
- src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Field/AncestorIdFilter.php
- tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Filter/Field/AncestorIdFilterSpec.php
> TIP-1528 update ES to 7.9.2

- std-build/package.json
- tests/legacy/features/Context/Page/Attribute/Creation.php
- tests/legacy/features/user-management/role/create_edit_and_delete_role.feature
Adds a missing workspace for the standard edition's `package.json`
> Add missing workspace in std-build/package.json

- akeneo-design-system/bin/dsm
- akeneo-design-system/package.json
Small tool tool to gather informations around DSM usage
> RAC-OKR: small POC to gather DSM usage informations

- tests/legacy/features/Context/DataGridContext.php
- tests/legacy/features/user-management/role/create_edit_and_delete_role.feature
Another attempt to fix a randomly failing legacy scenario
> New attempt to fix a random failing legacy scenario

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/ProductController.php
- src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/ProductController.php
- src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/Product/OnSave/ReindexFormerAncestorsSubscriber.php
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/controllers.yml
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/event_subscribers.yml
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/Processor/MassEdit/ConvertToSimpleProductProcessor.php
- src/Akeneo/Pim/Enrichment/Component/Product/EntityWithFamilyVariant/RemoveParentInterface.php
- tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/ExternalApi/PartialUpdateVariantProductEndToEnd.php
- tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/ExternalApi/PartialUpdateVariantToSimpleEndToEnd.php
- tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/Product/OnSave/ReindexFormerAncestorsSubscriberSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Processor/MassEdit/ConvertToSimpleProductProcessorSpec.php
> PM2020-9: Convert variant products to simple ones via API

- src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/jobs.yml
- src/Akeneo/Tool/Component/Batch/Job/JobRegistry.php
see https://github.com/akeneo/pim-community-dev/pull/12771
> RAC-205: Backport shared catalog

- Dockerfile.dev
- composer.lock
- symfony.lock
Same than https://github.com/akeneo/pim-community-dev/pull/13110
> Use Composer v1 in Dockerfile

- tests/back/Pim/Enrichment/Specification/Component/Product/Webhook/Exception/NotGrantedCategoryExceptionSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Webhook/Exception/ProductModelNotFoundExceptionSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Webhook/Exception/ProductNotFoundExceptionSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Webhook/ProductCreatedAndUpdatedEventDataBuilderSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Webhook/ProductModelCreatedAndUpdatedEventDataBuilderSpec.php
> Add missing specs for Webhook EventData builders and their exceptions

- akeneo-design-system/src/components/ProgressBar/ProgressBar.tsx
- src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/translations/jsmessages.en_US.yml
- src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_execution.yml
- src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/intl-duration.ts
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/execution/progress.tsx
- src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_US.yml
- src/Akeneo/Platform/Bundle/UIBundle/tests/front/unit/components/JobExecutionProgress.unit.tsx
- src/Akeneo/Platform/Bundle/UIBundle/tests/front/unit/intl-duration.unit.ts
> RAC-214: Loading bar - Execution details header [WIP]

- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/steps.yml
- src/Akeneo/Pim/Structure/Bundle/Resources/config/jobs.yml
- src/Akeneo/Pim/Structure/Bundle/Resources/config/steps.yml
- src/Akeneo/Platform/Bundle/ImportExportBundle/Normalizer/JobExecutionNormalizer.php
- src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/normalizers.yml
- src/Akeneo/Platform/Bundle/InstallerBundle/Resources/config/jobs.yml
- src/Akeneo/Platform/Bundle/InstallerBundle/Resources/config/steps.yml
- src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_execution.yml
- src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/execution/StopJobAction.tsx
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/execution/auto-refresh.js
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/execution/stop-job.tsx
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/view/base-interface.ts
- src/Akeneo/Platform/Bundle/UIBundle/tests/front/unit/components/StopJobAction.unit.tsx
- src/Akeneo/Tool/Component/Batch/Job/Job.php
- src/Akeneo/Tool/Component/Batch/Step/ItemStep.php
- tests/back/Platform/Specification/Bundle/ImportExportBundle/Normalizer/JobExecutionNormalizerSpec.php
- tests/legacy/features/platform/dashboard/display_last_operations_widget.feature
> RAC-212: Add Stop button in job details

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/processors.yml
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/JobParameters/ConstraintCollectionProvider/ProductCsvImport.php
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/JobParameters/DefaultValueProvider/ProductCsvImport.php
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/Processor/Denormalizer/ProductProcessor.php
- src/Akeneo/Pim/Enrichment/Component/Product/ProductModel/Filter/ProductAttributeFilter.php
- src/Akeneo/Pim/Enrichment/Component/Product/Updater/Setter/ParentFieldSetter.php
- src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/translations/jsmessages.en_US.yml
- src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_product_import_edit.yml
- src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_product_import_edit.yml
- tests/back/Pim/Enrichment/Integration/Product/UpdateVariantProductIntegration.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Job/JobParameters/ConstraintCollectionProvider/ProductCsvImportSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Job/JobParameters/DefaultValueProvider/ProductCsvImportSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Processor/Denormalizer/ProductProcessorSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/ProductModel/Filter/ProductAttributeFilterSpec.php
- tests/legacy/features/Context/FixturesContext.php
- tests/legacy/features/pim/enrichment/product/import/import_variant_products.feature
- tests/legacy/features/platform/import/edit_an_import.feature
> CPM-39: convert variant products to simple ones via import

- src/Akeneo/Connectivity/Connection/back/Domain/Webhook/Exception/ConnectionWebhookNotFoundException.php
Fix phpstan static test https://app.circleci.com/pipelines/github/akeneo/pim-enterprise-dev/26558/workflows/1d4543f5-7eeb-43f8-ac3e-f36f3387aa74/jobs/84443  
The code was green in phpstan 0.12.53 but is red in 0.12.54
> Fix typehint

- src/Akeneo/Platform/Bundle/ImportExportBundle/Controller/Ui/JobTrackerController.php
- src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/acl.yml
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/execution/StopJobAction.tsx
- src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/messages.en_US.yml
> RAC-213: add job stop ACL

- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
> DAPI-1419: Change "missing image" recommendation text

- src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/GetKeyIndicators.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/services.yml
- src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/KeyIndicator.tsx
- src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/KeyIndicators.tsx
- src/Akeneo/Pim/Automation/DataQualityInsights/front/src/domain/KeyIndicator.ts
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Application/GetKeyIndicatorsSpec.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Application/component/Dashboard/KeyIndicators/KeyIndicator.unit.tsx
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Application/component/Dashboard/KeyIndicators/KeyIndicators.unit.tsx
Fix properties and naming to avoid any confusion.
> DAPI-1414: Fix Dashboard key indicators properties

- CHANGELOG.md
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/Completeness/GetRequiredAttributesMasksQuery.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Persistence/Query/Completeness/GetRequiredAttributesMasksQueryIntegration.php
> PIM-9542: Fix product creation when the family has a numeric code

- src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/widget.yml
- src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/public/templates/last-operations-widget.html
- src/Akeneo/Platform/Bundle/ImportExportBundle/Widget/LastOperationsFetcher.php
- tests/back/Platform/Specification/Bundle/ImportExportBundle/Widget/LastOperationsFetcherSpec.php
In this PR : 
- Add information of current step in dashboard 
- Remove badge arround warning count in dashboard
> RAC-216: add information of current step in dashboard

- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Elasticsearch/Filter/KeyIndicatorFilter.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/ProductGrid/KeyIndicatorFilter.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/ProductGrid/RegisterKeyIndicatorFilter.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/productgrid.yml
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
> DAPI-1417: register 2 new key indicator related filters on the product grid

- src/Akeneo/Connectivity/Connection/back/Application/Webhook/Command/SendBusinessEventToWebhooksHandler.php
- src/Akeneo/Connectivity/Connection/back/Application/Webhook/Log/WebhookEventBuildLog.php
- src/Akeneo/Connectivity/Connection/back/Application/Webhook/Log/WebhookEventDataBuilderErrorLog.php
- src/Akeneo/Connectivity/Connection/back/Application/Webhook/Log/WebhookRequestLog.php
- src/Akeneo/Connectivity/Connection/back/Domain/Webhook/Client/WebhookRequest.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/Client/GuzzleWebhookClient.php
- src/Akeneo/Connectivity/Connection/back/tests/.php_cd.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Webhook/Log/WebhookEventBuildLogSpec.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Webhook/Log/WebhookEventDataBuilderErrorLogSpec.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Webhook/Log/WebhookRequestLogSpec.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Domain/Webhook/Client/WebhookRequestSpec.php
> CXP-448: Add logs of event processing time

- src/Akeneo/Connectivity/Connection/back/Application/Webhook/Command/SendBusinessEventToWebhooksHandler.php
- src/Akeneo/Connectivity/Connection/back/Domain/Webhook/Client/WebhookClient.php
- src/Akeneo/Connectivity/Connection/back/Domain/Webhook/Persistence/Query/GetConnectionUserForFakeSubscription.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/Dbal/Query/DbalGetConnectionUserForFakeSubscription.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/handlers.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/queries.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/Client/GuzzleWebhookClient.php
- src/Akeneo/Connectivity/Connection/back/tests/.php_cd.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Webhook/Command/SendBusinessEventToWebhooksHandlerSpec.php
> Cxp-462 : Simulate tech stack based on real customer data

- src/Akeneo/Platform/Bundle/ImportExportBundle/Query/GetJobExecutionTracking.php
- src/Akeneo/Tool/Component/Batch/Job/Job.php
- src/Akeneo/Tool/Component/Batch/Job/JobWithStepsInterface.php
- tests/back/Platform/Integration/ImportExport/Repository/InternalApi/GetJobExecutionTrackingIntegration.php
What is in this PR ? 
- Handle case of job does not exist anymore (We create JobExecutionTracking and StepExecutionTracking from JobExecution and StepExecution and do not search if job is trackable) => before it throw an exception now data was filled
- Refactor tests to be more readable
- Add new interface because JobInterface does not have function getSteps
> RAC-321: handle possible exceptions 

- CHANGELOG.md
- src/Akeneo/Tool/Bundle/ElasticsearchBundle/Command/UpdateTotalFieldsLimitCommand.php
- src/Akeneo/Tool/Bundle/ElasticsearchBundle/GetTotalFieldsLimit.php
- src/Akeneo/Tool/Bundle/ElasticsearchBundle/Resources/config/commands.yml
- src/Akeneo/Tool/Bundle/ElasticsearchBundle/Resources/config/services.yml
> PIM-9452: Add a command to update the ElasticSearch indexes max fields limit

- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/js/infrastructure/dqi-dashboard/section.tsx
- src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/Dashboard.tsx
- src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/KeyIndicator.tsx
- src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/Overview/Filters/CategoryFilter.tsx
- src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/Overview/Filters/FamilyFilter.tsx
- src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/context/DashboardContext.tsx
- src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/ProductGridRouter.ts
- src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/hooks/useInitDashboardContextState.ts
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Application/component/Dashboard/KeyIndicators/KeyIndicator.unit.tsx
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Application/component/Dashboard/KeyIndicators/KeyIndicators.unit.tsx
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Dashboard/FilterOnCategory.unit.tsx
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Dashboard/FilterOnFamily.unit.tsx
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/__mocks__/pim/datagrid/state.ts
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/infrastructure/ProductGridRouter.unit.ts
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/utils/render/renderDashboardWithProvider.tsx
> DAPI-1417: redirect on filtered product grid when clicking on a key indicator

- .circleci/detect_structure_changes.sh
- Dockerfile.dev
- composer.json
- composer.lock
- symfony.lock
> BH-143: Upgrade to composer v2

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/Component/Product/Model/AbstractProduct.php
- src/Akeneo/Pim/Enrichment/Component/Product/Model/ProductInterface.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Builder/ProductBuilderSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Model/ProductSpec.php
Clean up product interface and its implementation
> Cleanup product interface

- src/Akeneo/Platform/Bundle/UIBundle/DependencyInjection/Compiler/RegisterFormExtensionsPass.php
Revise PHP doc to accurately describe the path it is fetching files from.
> Correct phpdoc

- CHANGELOG-3.2.md
- src/Oro/Bundle/PimDataGridBundle/Datasource/AssociatedProductModelDatasource.php
> Bugfix/fix association display 3.2

- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/ProductGrid/EnrichmentSorter.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/.php_cd.php
EE https://github.com/akeneo/pim-enterprise-dev/pull/9864
> DAPI-1427 - fix enrichment sort behavior

- src/Akeneo/Platform/Bundle/UIBundle/DependencyInjection/Compiler/RegisterFormExtensionsPass.php
> Correct phpdoc (#12492)

- src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/ProductGridRouter.ts
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/infrastructure/ProductGridRouter.unit.ts
> DAPI-1430 - land to the product grid with products ungrouped

- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/translations/messages.en_US.yml
EE https://github.com/akeneo/pim-enterprise-dev/pull/9884
> DAPI-1429 - add traduction for key indicators filters

- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
> DAPI-1431 - update 'more than x products' link

- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Elasticsearch/Query/GetProductKeyIndicatorsQuery.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/elasticsearch.yml
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/.php_cd.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Elasticsearch/Query/GetProductKeyIndicatorsQueryIntegration.php
The category children were not taking into account.
> DAPI-1414: Fix filter key indicators by category

- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/js/infrastructure/dqi-dashboard/base-dashboard.ts
> DAPI-1393: update default timelapse to weekly

- tests/back/Pim/Structure/Integration/Doctrine/ORM/Repository/ExternalApi/AttributeGroupRepositoryApiResourceIntegration.php
> CXP-519: Fix AttributeGroupRepository integration test to be determinist

- src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Model/LocaleCollection.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
- src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/KeyIndicator.tsx
- src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/KeyIndicators.tsx
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Application/component/Dashboard/KeyIndicators/KeyIndicators.unit.tsx
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Application/component/ProductEditForm/TabContent/DataQualityInsights/Criterion.unit.ts
> DAPI-1367: always display all key indicators

- src/Akeneo/Connectivity/Connection/back/Application/Webhook/Command/SendBusinessEventToWebhooksHandler.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Webhook/Command/SendBusinessEventToWebhooksHandlerSpec.php
> CXP-434: Do not send message to webhook if it is the author of the event

- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/KeyIndicator/ComputeProductsWithImageQuery.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Persistence/Query/KeyIndicator/ComputeProductsWithImageQuerySpec.php
> DAPI-1412 - fix key indicator missing image

- .github/workflows/dsm-test.yml
- akeneo-design-system/bin/dsm
- akeneo-design-system/example/src/__snapshots__/App.test.js.snap
> RAC-358: fix generate command for training

- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Webhook/Command/SendBusinessEventToWebhooksHandlerSpec.php
- src/Akeneo/Pim/Enrichment/.php_cd.php
> CXP-520: Fix phpcd

- src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/ProductEvaluation/Enrichment/EvaluateCompleteness.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Model/Write/CompletenessCalculationResult.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Enrichment/CalculateProductCompleteness.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/KeyIndicator/ComputeProductsEnrichmentStatusQuery.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Persistence/Query/KeyIndicator/ComputeProductsEnrichmentStatusQueryIntegration.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Application/ProductEvaluation/Enrichment/EvaluateCompletenessSpec.php
- upgrades/schema/Version_5_0_20201118150500_dqi_reset_enrichment_evaluations.php
> DAPI reduce queries key indicators

- src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/GetProductEvaluation.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Model/Read/ProductEvaluation.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Query/ProductEvaluation/GetLatestProductScoresQueryInterface.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetEmptyScoresQuery.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetLatestProductScoresQuery.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetUpToDateProductEvaluationQuery.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/queries.yml
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/services.yml
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/DataQualityInsightsTestCase.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Persistence/Query/ProductEvaluation/GetLatestProductScoresQueryIntegration.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Persistence/Repository/ProductScoreRepositoryIntegration.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Application/GetProductEvaluationSpec.php
Adaptations to return the unique score instead of the axes rates, and to regroup all the criteria evaluations.
> DAPI-1397: Adaptations to get product evaluation with unique score

- upgrades/schema/Version_5_0_20201117133700_add_dqi_unique_score_tables.php
- upgrades/schema/Version_5_0_20201118133700_migrate_product_axis_rate_to_unique_score.php
- upgrades/schema/Version_5_0_20201118133701_migrate_dashboard_rates_projection_to_unique_score_projection.php
- upgrades/test_schema/Version_5_0_20201117133700_add_dqi_unique_score_tables_Integration.php
- upgrades/test_schema/Version_5_0_20201118133700_migrate_product_axis_rate_to_unique_score_Integration.php
- upgrades/test_schema/Version_5_0_20201118133701_migrate_dashboard_rates_projection_to_unique_score_projection_Integration.php
Those migration script take into account CE and EE format (one axis vs two axes)
> Dapi 1439 - Migration script for already consolidated axis

- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/productgrid.yml
- src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/Dashboard.tsx
EE PR https://github.com/akeneo/pim-enterprise-dev/pull/9942
> DAPI-1436 - reactivate key indicators

- CHANGELOG-4.0.md
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/StandardToFlat/Product/ValueConverter/BooleanConverter.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/StandardToFlat/Product/ValueConverter/BooleanConverterSpec.php
> PIM-9565: Quick export modify empty Boolean value

- src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Attribute/BooleanFilter.php
- Add empty/not_empty in the rules engine
- Boolean Filter Integration Bugfix (if operator is empty)
> Cpm 79 Add empty/not_empty in the rules engine

- src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/ProductModelEditFormApp.tsx
- src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/TabContent/DataQualityInsights/Axis/AxisHeader.tsx
- src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/TabContent/DataQualityInsights/AxisEvaluation.tsx
- src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/TabContent/DataQualityInsightsTabContent.tsx
- src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/helper/EvaluationHelper.ts
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Application/helper/Dashboard/EvaluationHelper.unit.ts
> DAPI-1348: remove axis scores on DQI tab evaluation

- src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/ProductGridRouter.ts
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/infrastructure/ProductGridRouter.unit.ts
> Dapi 1437 - When coming from a KI, the product grid should display the Quality Score column

- upgrades/schema/Version_5_0_20201118133700_migrate_product_axis_rate_to_unique_score.php
- upgrades/schema/Version_5_0_20201118133701_migrate_dashboard_rates_projection_to_unique_score_projection.php
- upgrades/test_schema/Version_5_0_20201118133700_migrate_product_axis_rate_to_unique_score_Integration.php
- upgrades/test_schema/Version_5_0_20201118133701_migrate_dashboard_rates_projection_to_unique_score_projection_Integration.php
> Fix migration script to handle empty tables of evaluation/consolidation

- src/Akeneo/Pim/Enrichment/Component/Product/Connector/FlatTranslator/AttributeValue/MetricTranslator.php
- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/shared/layouts/tables/TableCell.tsx
- src/Akeneo/Tool/Bundle/MeasureBundle/PublicApi/GetUnitTranslations.php
- src/Akeneo/Tool/Bundle/MeasureBundle/PublicApi/SqlGetUnitTranslations.php
- tests/back/Acceptance/MeasurementFamily/InMemoryGetUnitTranslations.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/FlatTranslator/AttributeValue/MetricTranslatorSpec.php
Need an interface and an InMemory query for https://github.com/akeneo/pim-enterprise-dev/pull/9944
> CPM-91: add GetUnitTranslations interface and in memory query

- src/Akeneo/Pim/Structure/.php_cd.php
- src/Akeneo/Pim/Structure/Bundle/EventSubscriber/InitDeletedAttributeSchemaSubscriber.php
- src/Akeneo/Pim/Structure/Bundle/Resources/config/services.yml
- upgrades/schema/Version_5_0_20201123112748_add_attribute_blacklist_table.php
- upgrades/test_schema/Version_5_0_20201123112748_add_attribute_blacklist_table_Integration.php
> RAC-390: migration for attribute code blacklist table

- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Webhook/ConsumeBusinessProductModelEventEndToEnd.php
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/webhook.yml
- src/Akeneo/Pim/Enrichment/Component/Product/Webhook/ProductModelCreatedAndUpdatedEventDataBuilder.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Webhook/ProductModelCreatedAndUpdatedEventDataBuilderSpec.php
> CXP-559: Update the ProductModel EventDataBuilder to support BulkEvent

- .circleci/config.yml
Same than https://github.com/akeneo/pim-enterprise-dev/pull/9966
Validated on EE, needed on CE too
> Fix broken pipe in test_upgrade_from_last_release CI job

- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/Dashboard/GetAverageRanksQuery.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Controller/Dashboard/DashboardWidgetCategoriesController.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/less/dqi-dashboard.less
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/less/grid.less
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/less/index.less
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
- src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/Widgets/AddItem.tsx
- src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/Widgets/CategoryWidget.tsx
- src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/Widgets/FamilyWidget.tsx
- src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/Widgets/RemoveItem.tsx
- src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/Widgets/SeeInGrid.tsx
- src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/Widgets/Table.tsx
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Persistence/Query/Dashboard/GetAverageRanksQueryIntegration.php
- Display the Quality Score by families and categories in the dashboard widget
- Replace Rate badges by the new Quality score badge. (DAPI-1352)
> DAPI-1345: As a PM, in the dashboard, I want one column with Quality Score to replace E&C scores in the widgets (family and category)

- src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/Consolidation/ConsolidateDashboardRates.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/Consolidation/PurgeOutdatedData.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Query/Dashboard/GetDashboardScoresQueryInterface.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Repository/DashboardScoresProjectionRepositoryInterface.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Install/EventSubscriber/InitDataQualityInsightsDbSchemaSubscriber.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/Dashboard/GetAverageRanksQuery.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/Dashboard/GetDashboardScoresQuery.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Repository/DashboardScoresProjectionRepository.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Controller/Dashboard/DashboardOverviewController.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/controllers.yml
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/queries.yml
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/repositories.yml
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/services.yml
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Persistence/Query/Dashboard/GetAverageRanksQueryIntegration.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Persistence/Query/Dashboard/GetDashboardScoresQueryIntegration.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Persistence/Repository/DashboardScoresProjectionRepositoryIntegration.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Application/Consolidation/ConsolidateDashboardRatesSpec.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Application/Consolidation/PurgeOutdatedDataSpec.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Symfony/Controller/Dashboard/DashboardOverviewControllerSpec.php
> DAPI: use the new table to consolidate product scores

- src/Akeneo/Platform/Bundle/AnalyticsBundle/DataCollector/DBDataCollector.php
- src/Akeneo/Platform/Bundle/AnalyticsBundle/Query/Sql/IsDemoCatalog.php
- src/Akeneo/Platform/Bundle/AnalyticsBundle/Resources/config/data_collectors.yml
- src/Akeneo/Platform/Bundle/AnalyticsBundle/Resources/config/queries.yml
- src/Akeneo/Platform/Bundle/AnalyticsBundle/Resources/translations/messages.en_US.yml
- src/Akeneo/Tool/Component/Analytics/IsDemoCatalogQuery.php
- tests/back/Platform/Acceptance/Analytics/Query/InMemory/IsDemoCatalogInMemory.php
- tests/back/Platform/Acceptance/Analytics/Resources/config/queries.yml
- tests/back/Platform/Integration/Analytics/Query/IsDemoCatalogIntegration.php
- tests/back/Platform/Specification/Bundle/AnalyticsBundle/DataCollector/DBDataCollectorSpec.php
It's useful to know if the user is testing the PIM.
> GITHUB-APD-251: track if it's demo catalog which is installed

- src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/ScoreDistributionSection/Chart/ScoreDistributionChart.tsx
- src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/ScoreDistributionSection/Chart/ScoreDistributionChartByTimePeriod.tsx
- src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/ScoreDistributionSection/Header.tsx
- src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/ScoreDistributionSection/ScoreDistributionSection.tsx
> DAPI-1351: fix hidden filters issue when Score distribution is not valid

- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/js/infrastructure/product-edit-form/attribute-filter-all-missing-attributes.ts
> DAPI-1449: fix "display all missing attributes" filter

- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
- src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/TabContent/DataQualityInsights/Recommendation/Recommendation.tsx
> DAPI-1438: change the "not applicable" criterion message

- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Webhook/ProduceBusinessProductEventEndToEnd.php
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Webhook/ProduceBusinessProductModelEventEndToEnd.php
- src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/BusinessEvent/DispatchProductModelRemovedEventSubscriber.php
- src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/BusinessEvent/DispatchProductRemovedEventSubscriber.php
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/event_subscribers.yml
- tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/BusinessEvent/DispatchProductModelRemovedEventSubscriberSpec.php
- tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/BusinessEvent/DispatchProductRemovedEventSubscriberSpec.php
> CXP-565: Update tech event subscriber to support bulk event

- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Webhook/ConsumeBusinessProductEventEndToEnd.php
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Webhook/ConsumeBusinessProductModelEventEndToEnd.php
- src/Akeneo/Pim/Enrichment/Component/Product/Webhook/ProductModelRemovedEventDataBuilder.php
- src/Akeneo/Pim/Enrichment/Component/Product/Webhook/ProductRemovedEventDataBuilder.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Webhook/ProductModelRemovedEventDataBuilderSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Webhook/ProductRemovedEventDataBuilderSpec.php
> CXP-566: Update event data builder for product and product model

- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/productgrid.yml
> DAPI-1368: fix project creation with quality score
