.circleci/config.yml, .circleci/run_phpunit.sh
Try to remove the useless run_phpunit.sh file that is present on EE
=> TIP-1196: only one run_phpunit.sh

CHANGELOG-3.1.md, src/Oro/Bundle/PimDataGridBundle/Resources/public/templates/filter/filter-group.html
In the product-grid filters menu, the labels of the attributes usable as a filter are not fully displayed (they are shortened with an "ellipsis"). The goal of this PR is to display the full label when the mouse is hovering it.
=> PIM-8597: Fix display of long attribute names in the filter menu

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/attributes/create-button.js
We didn't go far enough when removing the asset-single attribute. I've put back the removal of the button in the UI so that customers do not see it.
We need to rework this part :/
`OK`: Done / …
=> PIM-8409: Remove asset single link attribute from list

CHANGELOG-3.1.md, src/Oro/Bundle/PimDataGridBundle/Query/Sql/ListProductGridAvailableColumns.php
Add a sort on attribute code to have a constant order even when all attributes order and attribute groups order are set to 0.
=> PIM-8603: Sort attribute columns by code if no order is defined

.circleci/config.yml, Makefile
This PR adds a comment to explain a little trick on the CI and it fixes makefile to run behat on the right env.
=> TIP-1193 Run behat on the right env using makefile

app/AppKernel.php, app/bundles.php, app/config/config.yml, app/config/config_dev.yml, app/config/routing_dev.yml, composer.json, composer.lock, tests/back/Integration/AppKernelTest.php
For more information, please read http://fabien.potencier.org/symfony4-directory-structure.html and https://symfony.com/doc/current/bundles.html.
This is another step forward SF4 (and maybe Flex).
Next move is to remove those `AppKernelTest` classes :)
=> TIP-1192 Make the symfony kernel compatible with SF4

CHANGELOG-3.1.md, src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/translations/jsmessages.en_US.yml, src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/translations/jsmessages.fr_FR.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_base_import_edit.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_product_import_edit.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_product_model_import_edit.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_base_import_edit.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_product_import_edit.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_product_model_import_edit.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/yml_base_import_edit.yml
Add a different translation key for filepath in import profile because it's not the same use case than export profile.
=> PIM-8600: Fix import filepath tooltip

app/config/config_behat.yml
The goal is still to make the enterprise edition (and our tests) closer to what we have in production.
I removed all the conf that was not necessary in our Behat env.
=> TIP-1196: make Behat env closer to prod's one

CHANGELOG-3.0.md, src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/NotEmptyVariantAxesValidator.php, tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/NotEmptyVariantAxesValidatorSpec.php
The PHP function `empty()` returns `true` for the value `'0'`, but it's a valid value for an option code, and so for an axis value.
=> PIM-8614: Fix empty variant axes validation

CHANGELOG-3.0.md, src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Repository/ProductMassActionRepository.php, src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Field/AncestorFilter.php, tests/back/Pim/Enrichment/Specification/Bundle/Doctrine/ORM/Repository/ProductMassActionRepositorySpec.php, tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Filter/Field/AncestorFilterSpec.php
There's a bug when a user selects all the products in a filtered product-grid to export them, but un-select manually one (or several) product-model (by clicking on the checkbox). 
The export will well exclude the product-model, but will add its variants.
It's because in this case, the ES query is built with the filters of the product-grid chosen by the user, and will add a filter to exclude the id of the products that have been unselected. In the case of a product-model, it results that the variants of the excluded product-model match the ES query, when they should be excluded.
To fix that I added a filter on the field "ancestor.id" to exclude the variants of the excluded product-models.
To do that I had to change the `AncestorFilter` application, to remove a clause on the existence of …
=> PIM-8611: Fix filters applied when a product model is excluded from a product-grid selection

CHANGELOG-2.3.md, src/Pim/Bundle/EnrichBundle/Resources/public/js/i18n.ts
The split wasn't working and break the grid.
Now:
=> PIM-7583: Allow user to import custom locales without '_'

CHANGELOG-2.3.md, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/product/edit.yml, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/product_model/edit.yml
=> PIM-8461: Do not display 'Compare/translate' if user has no permission to edit product attributes

upgrades/3.2-4.0/es_delete_unused_indexes.php
This PR adds a migration script to delete the alias + index associated with `akeneo_pim_product` and `akeneo_pim_product_model`. 
=> TIP-1185: Add migration script

CHANGELOG-3.0.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/field/wysiwyg-field.js
The originalEvent does not exist on Firefox but in Chrome.
This tricky allows to get the original Path in Firefox.
=> PIM-8623: Fix wysiwyg edit link modal on Firefox

CHANGELOG-3.0.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/filter/attribute/select.js
The filter was not rendered after the status change, so the right input was not hidden/showed after change.
=> PIM-8387: Fix product export builder on simple/multi select attribute filters

CHANGELOG-3.0.md, src/Akeneo/UserManagement/Bundle/Resources/public/js/fields/default-grid-views.ts, src/Akeneo/UserManagement/Bundle/Resources/public/js/fields/default-product-grid-view.ts, src/Oro/Bundle/PimDataGridBundle/Repository/DatagridViewRepository.php, tests/back/Oro/Integration/DatagridView/DatagridViewRepositoryIntegration.php, tests/legacy/features/Context/Page/Base/Form.php
The previous field was loading "all" the grid views before displaying it.
2 issues:
- it's not scalable (imagine 10000 views)
- the query automatically strip to the 20 firsts ones.
So I transformed it into an "ajax-way", to load them only when user click, and 20 by 20.
=> PIM-8624: Fix default product grid view selector in user profile when there is more than 20 views

CHANGELOG-3.0.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/properties/translation.js
By default, the translation module was not loading the locales without the permission "pim.internal_api.locale.view".
The correct behavior is to even display the locales in the configuration screens.
=> PIM-8628: Display label translations on configuration screens even you don't have 'Allowed to view information' permission on a locale

CHANGELOG-2.3.md, src/Pim/Component/Connector/ArrayConverter/FlatToStandard/ConvertedField.php, src/Pim/Component/Connector/spec/ArrayConverter/FlatToStandard/ConvertedFieldSpec.php
The issue happened on the `array_merge_recursive` of `['X_SELL' => [...]]` and `[1234 => [ ... ]]`.
This returned `['X_SELL' => [...], 0 => [...]]`.
=> PIM-8630: Fix revert action when it exists an association type with integer as code

CHANGELOG-3.2.md, src/Akeneo/Platform/Bundle/ImportExportBundle/Command/PurgeJobExecutionCommand.php, src/Akeneo/Tool/Bundle/BatchBundle/Persistence/Sql/DeleteJobExecution.php, tests/back/Tool/Integration/Batch/Persistence/Sql/DeleteJobExecutionIntegration.php
When you purge the job executions, some job execution are not purged because it failed.
The `end_time` is not set and the query does not delete jobs without `end_time`.
We could remove jobs without `end_time`, but it means that a job executed today that failed would be purged also, whatever the parameter of the command (older than X days).
The most simple thing is just to be based on the date of creation.
**Cons:**
As a job could be put in the queue and executed only some hours later, I forced to purge at a minimum of 1 day.
I don't think there is any usecase at allowing 0 day. 
It means also if a job last 24 hours you can have a problem if you execute the command with "older than 1 day".
But I don't think that's a good practice to …
=> PIM-8601: Fix purge of the job execution according to the date of creation and not deletion

CHANGELOG-3.0.md, src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductGrid/FetchProductRowsFromIdentifiers.php, tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductGrid/FetchProductRowsFromIdentifiersIntegration.php
In the case of
- a product model without any value
- a product variant of this PM with a value on it
The query will do a JSON_MERGE of `[]`, `{ sku: ... }`, which result in `[{}, { sku: ... }]`.
If I have to add a test, feel free to indicate what and where.
=> PIM-8632: Fix empty column in the product datagrid when product model doest not have any shared value

tests/legacy/features/pim/enrichment/product-model/navigate_product_and_product_model_edit_page.feature, tests/legacy/features/pim/enrichment/product/datagrid/datagrid_views.feature, tests/legacy/features/pim/enrichment/product/datagrid/filtering/filter_products_per_label_or_identifier.feature, tests/legacy/features/pim/enrichment/product/datagrid/multiple_page_selection.feature, tests/legacy/features/pim/enrichment/product/mass-action/quick-export/quick_export_grid_context.feature, tests/legacy/features/pim/enrichment/product/mass-action/quick-export/quick_export_products_and_product_models.feature, tests/legacy/features/pim/enrichment/product/mass-action/sequential-edit/sequential_edit_product_and_product_model.feature, tests/legacy/features/pim/enrichment/product/mass-edit/edit-common-attribute/mass_edit_products_and_product_models.feature, tests/legacy/features/pim/enrichment/product/mass-edit/mass_add_to_existing_product_model.feature, tests/legacy/features/pim/enrichment/product/mass-edit/mass_edit_products_and_product_models.feature, tests/legacy/features/pim/enrichment/product/pef/edit_and_display_all_attributes.feature, tests/legacy/features/pim/enrichment/product/pef/edit_boolean_value.feature, tests/legacy/features/pim/enrichment/product/pef/edit_product_and_filter_attributes.feature, tests/legacy/features/pim/enrichment/product/pef/edit_product_with_localized_attributes.feature, tests/legacy/features/pim/enrichment/reference-data/product/sorting/sort_products_per_reference_data.feature, tests/legacy/features/pim/structure/attribute/option/sort_attribute_options.feature
When does it fail?
- We display the datagrid
- We click on a row
- The datagrid should be refreshed
- Row is uncheck
- We click on bulk action => no row selected, **error**
When does it work?
- We display the datagrid
- The datagrid is refreshed
- We click on a row
- We click on bulk action
- etc (it's working)
**Solution** 
Switch to the method "display datagrid" which is almost the same, but a little bit more robust.
I also added a wait for a test, because I think it will stabilize it (same problem of partial loading, but on the PEF) …
=> Fix unstable in the CI due to the grid loaded two times, which lead to non-deterministic behavior when clicking on rows

CHANGELOG-2.3.md, src/Pim/Bundle/UIBundle/Resources/public/less/components/product-edit-form/TextField.less
The style was broken (and very crappy)
So we decided to put it back as the "browser way". No style.
This input is already nice in 3.0, so this commit will be reverted on merge.
=> PIM-7675: Fix file input

src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/common/menu.yml, src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/column.js, src/Pim/Bundle/UIBundle/Resources/public/less/components/Column.less
=> PIM-7483: fix activity navigation dropdown menu when the menu is collapsed

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/pim-attributeoptionview.js, tests/legacy/features/pim/structure/attribute/option/delete_attribute_options.feature
=> PIM-8442: Display flash messages instead of old popup when an error occurs in the attribute option edition

CHANGELOG-3.0.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/button/ButtonList.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/product/history.html
This PR fixes spacing between actions on the history grid
=> PIM-8357: Fix styling of actions on history grid

CHANGELOG-3.0.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/attribute/edit.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/attribute/form/save.js
=> PIM-8438: display a flash message with the real error when attribute saving fails

CHANGELOG-3.0.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_base_import_show.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_product_import_show.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_product_model_import_show.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_base_import_show.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_product_import_show.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_product_model_import_show.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/yml_base_import_show.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/import/switcher-item.js, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/import/switcher.js
Currently, the upload button on import profiles remains even if uploads are disabled in the import profile settings. This PR fixes this issue by filtering the import profile actions by the `uploadAllowed` property on the import profile configuration.  …
=> PIM-8629: Allow import profile actions to be filtered by allowed property

upgrades/schema/Version_4_0_20190801084247_remove_native_json_type.php
When migrating from 3.2 to master, we have the following error (introduced by https://github.com/akeneo/pim-community-dev/pull/10527 and https://github.com/akeneo/pim-enterprise-dev/pull/6659):
```
janvier:pcd$ docker-compose exec fpm bin/console doctrine:schema:update --env=prod                                                                              
10:33:50 ERROR     [console] Error thrown while running command "doctrine:schema:update --env=prod". Message: "Unknown column type "native_json" requested. Any Doctrine type that you use has to be registered with \Doctrine\DBAL\Types\Type::addType(). You can get a list of all the known types with \Doctrine\DBAL\Types\Type::getTypesMap(). If this error occurs during database introspection then you might have forgotten to register all …
```
=> TIP-901: database migration for native_json type removal

Makefile, docker-compose.yml, make-file/dev.mk
This goal of this PR is to simplify the `Makefile` to:
- find better name for targets,
- fix problems like avoiding PHP dependencies installation when you checkout a new  CE branch or asset installation,
- prepare the "advanced" env vars using.
`Todo`: …
=> TIP-1210 Make Makefile simpler

CHANGELOG-3.2.md, src/Akeneo/Pim/Enrichment/Bundle/Product/Query/Sql/GetValuesAndPropertiesFromProductIdentifiers.php, tests/back/Pim/Enrichment/Integration/Product/Query/Sql/GetValuesAndPropertiesFromProductIdentifiersIntegration.php
Empty values are stored as an empty JSON array in `raw_values` column, which used to conflict with the JSON_MERGE MySQL function, and return an array instead of an object. 
ex:
`SELECT JSON_MERGE('[]', '{"foo": "bar"}', '{"bar": "baz"}');` 
will return
`[{"foo": "bar"}, {"bar": "baz"}]`
whereas we expect 
`{"foo": "bar", "bar": "baz"}`
This PR ensures that we merge only objects in order to get the expected format for the results. …
=> PIM-8661: Fix merging values from a variant product when one of its ancestors has empty values

CHANGELOG-3.0.md, src/Oro/Bundle/PimDataGridBundle/Datagrid/Configuration/Product/FiltersConfigurator.php, src/Oro/Bundle/PimDataGridBundle/Datagrid/Configuration/Product/SelectedAttributesConfigurator.php, src/Oro/Bundle/PimDataGridBundle/Extension/Filter/FilterExtension.php, src/Oro/Bundle/PimDataGridBundle/spec/Datagrid/Configuration/Product/FiltersConfiguratorSpec.php
Fixes searching and applying filters for attributes with numeric codes in the grid. The issue was mostly due to bad string/int casting
=> PIM-8667: Fix grid filters for numeric attribute codes

CHANGELOG-3.0.md, src/Akeneo/Pim/Enrichment/Bundle/DependencyInjection/Compiler/ConfigureAxisValueLabelsNormalizerPass.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/normalizers.yml, src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/AxisValueLabelsNormalizer/BooleanNormalizer.php, src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/EntityWithFamilyVariantNormalizer.php, tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/InternalApi/AxisValueLabelsNormalizer/BooleanNormalizerSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/InternalApi/EntityWithFamilyVariantNormalizerSpec.php
This is a port of #10437 on the 3.0 branch
=> PIM-8615: Fix issue with boolean attribute used as variant axis

CHANGELOG-3.2.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/tree-manage.jstree.js
Fix the category tree selector.
(A category with an ID of `1` was always ignored because of the js operator `in` that operate on array/object keys and not values.)
=> PIM-8663: Fix category tree selector

CHANGELOG-3.2.md, src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/DateValueFactory.php, src/Akeneo/Tool/Component/StorageUtils/Exception/InvalidPropertyException.php, src/Akeneo/Tool/Component/StorageUtils/spec/Exception/InvalidPropertyExceptionSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Factory/Value/DateValueFactorySpec.php
When creating a DateValue, the validity of the provided date was not checked, so one could create a date value with invalid dates (e.g '0000-00-00' or '2019-02-31')  from the API, which resulted in invalid data stroed in the DB.
`-`: Not …
=> PIM-8674: Check provided date validity when creating a DateValue

CHANGELOG-3.2.md, src/Akeneo/Platform/Bundle/UIBundle/Imagine/FlysystemLoader.php, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/services.yml, src/Akeneo/Tool/Component/FileStorage/File/FileStorer.php, tests/back/Platform/Specification/Bundle/UIBundle/Imagine/FlysystemLoaderSpec.php
When using a cloud storage solution (AWS S3, Google Cloud Storage). You need to send the `Content-Type` metadata along with your file or it will be stored as `application/octet-stream`.
The goal of this PR is to:
- Set the metadata option required by each Flysystem adapter (dirty fix, but a rewrite to handle properly each adapter configuration would probably be too much).
- Fallback to load the mime-type of a file from the FileInfo repository if we get a `Content-Type` `application/octet-stream` when loading a file from the storage. …
=> PIM-8673: Add a fallback to get the mime-type of files loaded without metadata.

CHANGELOG-3.0.md, src/Akeneo/Pim/Enrichment/Bundle/Resources/views/CategoryTree/form.html.twig, src/Akeneo/Pim/Structure/Bundle/Resources/config/datagrid/family.yml
Fix the display of the remove button in family grid and category tree when the user does not have the permissions
=> PIM-6138: Fix display of remove button according to ACL

CHANGELOG-3.2.md, src/Akeneo/Pim/Enrichment/Bundle/Resources/views/CategoryTree/edit.html.twig
The categories settings page display a title of `Category tree {{ category.label }} | Edit` on the initial page load (`category.label` is not defined). 
The problem is that the `PageTitle` service is triggered by a routing change, but the script in `CategoryTree/edit.html.twig` that set the  `PageTitle` params is executed after the event happen. …
=> PIM-8655: Fix page title of the categories settings

CHANGELOG-3.2.md, src/Akeneo/Pim/Enrichment/Bundle/PdfGeneration/Renderer/ProductPdfRenderer.php, tests/back/Pim/Enrichment/Specification/Bundle/PdfGeneration/Renderer/ProductPdfRendererSpec.php
Fixes the display of attribute options in PDF in case of scopable and/or localizable simple/multi select attributes
=> PIM-8701: Fix PDF rendering for scopable/localizable simple or multi select attributes

CHANGELOG-3.0.md, src/Akeneo/Pim/Structure/Component/Model/FamilyInterface.php, tests/back/Pim/Structure/Specification/Component/Model/FamilySpec.php
This pull request aims to change the value of the updated property from the Family entity when the user updates the attribute requirements (SETTINGS > FAMILIES > ${FAMILY} > Attributes)
This is done "automatically" if the family implement the Timestampable interface. Interface methods already are implemented in the Family model, but the the interface was not declared.
| …
=> PIM-8678: Change the updated property value of the Family entity when the attribute requirements are updated

src/Akeneo/Pim/Structure/Bundle/Query/PublicApi/Family/Sql/SqlGetRequiredAttributesMasks.php
This PR fixes a problem where an integer couldn't be used as the code for `RequiredAttributesMaskForChannelAndLocale` and `RequiredAttributesMask`. This fixes the data generation step on the EE CI for performance tests.  …
=> Fix integer as codes for required attributes masks

CHANGELOG-2.3.md, src/Pim/Bundle/EnrichBundle/VersionStrategy/CacheBusterVersionStrategy.php, src/Pim/Bundle/EnrichBundle/spec/VersionStrategy/CacheBusterVersionStrategySpec.php
Hide the PIM version from the dev console when requesting CSS files
=> PIM-7127: Hide version from CSS call

CHANGELOG-3.0.md, src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/product_scope-filter.js
On the first loading of the product grid, the grid is loaded 2 times. Why ?
- It loads the datagrid with the default parameters
- When the datagrid is loaded, every filter call "datagrid_filters:rendered".
- The scope filter check that its value is filled, and if not, set the user catalog scope, which is already the scope used in the first step, so changed nothing.
The chosen solution is to keep the current behavior but do not ask for a datagrid refresh (i.e. send an event "onValueUpdated"). …
=> PIM-6978: Do not refresh datagrid on firstload

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/ProjectWidget.less
DAPI-26: https://akeneo.atlassian.net/browse/DAPI-26
This pull request updates the css rules for redering the enrichment progress in the widget's project dropdown. This part is used by the Entreprise Edition only. …
=> DAPI-26: Add the enrichment progress in the widget's project drop down

CHANGELOG-4.0.md, src/Akeneo/Pim/Enrichment/Bundle/Command/CalculateCompletenessCommand.php, src/Akeneo/Pim/Enrichment/Bundle/Command/IndexProductCommand.php, src/Akeneo/Pim/Enrichment/Bundle/Doctrine/Common/Saver/ProductModelDescendantsSaver.php, src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Indexer/ProductIndexer.php, src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Indexer/ProductModelDescendantsIndexer.php, src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/IndexProductModelsSubscriber.php, src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/IndexProductsSubscriber.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/elasticsearch.yml, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/event_subscribers.yml, src/Akeneo/Tool/Component/StorageUtils/Indexer/ProductIndexerInterface.php, tests/back/Integration/IntegrationTestsBundle/Loader/FixturesLoader.php, tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/DeleteProductEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/ExternalApi/DeleteVariantProductEndToEnd.php, tests/back/Pim/Enrichment/Integration/Completeness/CalculateCompletenessCommandIntegration.php, tests/back/Pim/Enrichment/Specification/Bundle/Command/IndexProductCommandSpec.php, tests/back/Pim/Enrichment/Specification/Bundle/Doctrine/Common/Saver/ProductModelDescendantsSaverSpec.php, tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Indexer/ProductIndexerSpec.php, tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Indexer/ProductModelDescendantsIndexerSpec.php, tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/IndexProductModelsSubscriberSpec.php, tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/IndexProductsSubscriberSpec.php
https://akeneo.atlassian.net/browse/TIP-1220  
Remove old interfaces from `Akeneo\Pim\Enrichment\Bundle\Elasticsearch\Indexer\ProductIndexer` and replace them by a single one new interface `ProductIndexerInterface`.  Public methods modification:
| Old methods | New methods
| index($object, ..) | indexFromProductIdentifier(string $productIdentifier, ..)
| indexAll($objects, ..) | indexFromProductIdentifiers(array $productIdentifiers, ..)
| remove($objectId, ..) | removeFromProductId(string $productId, ..)
| removeAll($objects, ..) | removeFromProductIds(array $productIds, ..)
Change and adapt in entire application and tests.  
Inject the ProductRepository in order to fetch and normalize product. This is a temporary solution, it will be replaced by …
=> TIP-1220: ProductIndexer as Interface

Dockerfile
This PR adds the ca-certificates package to the php image for composer to be able to install packages from source
=> Add ca-certificates package to php image

CHANGELOG-3.2.md, src/Akeneo/Platform/Bundle/ImportExportBundle/Command/PurgeJobExecutionCommand.php, src/Akeneo/Platform/Bundle/ImportExportBundle/Purge/PurgeJobExecution.php, src/Akeneo/Tool/Bundle/BatchBundle/Persistence/Sql/DeleteJobExecution.php, tests/back/Tool/Integration/Batch/Persistence/Sql/DeleteJobExecutionIntegration.php
Re-enable the 0 day purge for job executions.
The purge command was modified in #10485 but there is a use case for a 0 days purge.
It's more about tooling than daily use because it is used to clean the tracker and boards after an installation with job fixtures.
=> PIM-8677: Purge all job executions

CHANGELOG-3.2.md, src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/minimal/channels.csv
When a new client opens for the first time its PIM, some entities are created by default (a category tree, a channel, a locale) 
The existing channel code is "ecommerce" but its label is "Default". 
It can be a bit confusing for the customer, especially if the Used change the channel locale and keep en_US for its UI language. The label Default is then displayed, and the user does not understand where does it come from. 
Expected: change the label "Default" for "Ecommerce" to be compliant with the channel's code. …
=> PIM-8734: Change label for default channel in minimal catalog

CHANGELOG-3.2.md, src/Akeneo/Tool/Bundle/VersioningBundle/Command/PurgeCommand.php
When launching the command in `--no-interaction` mode, we didn't set the default value for the number. This PR just set the same default for every mode, interactive or not.
=> PIM-8753: Fix pim:versioning:purge command without parameter

tests/legacy/features/Context/WebUser.php
Fix behat `vendor/akeneo/pim-community-dev/tests/legacy/features/pim/enrichment/product/mass-edit/mass_add_to_existing_product_model.feature` which was failing because the mass action modal wouldn't show up after pressing the button.
See EE build https://github.com/akeneo/pim-enterprise-dev/pull/6877 …
=> FIX Nightly: Fix press button step

CHANGELOG-3.0.md, src/Akeneo/Pim/Enrichment/Component/Product/EntityWithFamily/IncompleteValueCollectionFactory.php, src/Akeneo/Pim/Enrichment/Component/Product/EntityWithFamily/RequiredValue.php, tests/back/Pim/Enrichment/Specification/Component/Product/EntityWithFamily/IncompleteValueCollectionFactorySpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/EntityWithFamily/RequiredValueCollectionFactorySpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/EntityWithFamily/RequiredValueSpec.php
Local specific attribute completeness is not correct because the RequiredValue didn't return the locale to compute the completeness on the locale.
It returned a required value key of `myattribute-<all_channels>-<all_locales>` when it should have return `myattribute-<all_channels>-en_US` for example. The completeness was then computed only on the last available locale.
| Added Specs                       | Updated
| Tech Doc …
=> PIM-8754: Fix completeness for locale specific attribute

CHANGELOG-2.3.md, src/Pim/Component/Connector/Archiver/FileWriterArchiver.php, src/Pim/Component/Connector/spec/Archiver/FileWriterArchiverSpec.php
When creating the archive for big export, we can crash the memory if we read the file at once. Using a stream fixes the memory consumption.
| Added Specs                       | updated
=> PIM-8757: Use a stream to create export archive

CHANGELOG-2.3.md, src/Pim/Bundle/ApiBundle/tests/integration/Controller/AttributeOption/CreateAttributeOptionIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/AttributeOption/PartialUpdateAttributeOptionIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/AttributeOption/PartialUpdateListAttributeOptionIntegration.php, src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Query/GetAttributeOptionsMaxSortOrder.php, src/Pim/Bundle/CatalogBundle/Entity/AttributeOption.php, src/Pim/Bundle/CatalogBundle/EventSubscriber/AttributeOption/SetAttributeOptionSortOrderSubscriber.php, src/Pim/Bundle/CatalogBundle/Resources/config/event_subscribers.yml, src/Pim/Bundle/CatalogBundle/Resources/config/queries.yml, src/Pim/Bundle/CatalogBundle/spec/Entity/AttributeOptionSpec.php, src/Pim/Bundle/CatalogBundle/spec/EventSubscriber/AttributeOption/SetAttributeOptionSortOrderSubscriberSpec.php, src/Pim/Bundle/CatalogBundle/tests/integration/Doctrine/ORM/Query/GetAttributeOptionsMaxSortOrderIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/EventSubscriber/SetAttributeOptionSortOrderSubscriberIntegration.php
When creating a new attribute option for a simple/multi select via the UI, the sort order was not set, so it defaulted to 1 (`Pim\Bundle\CatalogBundle\Entity\AttributeOption`'s default value for `$sortOrder` property), which caused inconsistencies in the 'History' tab (newly created option appeared in 2nd position in the options list, instead of last position).
This PR:
- removes the default value for `$sortOrder`
- adds a subscriber which computes and sets the sort order (if needed, i.e when it's `null`) when saving attribute options (or attributes with options)
| Added …
=> PIM-8751: Fix simple and multi select attributes history when creating a new option

.circleci/config.yml
Docker layer caching will be removed for the container plan and very expensive for the Performance Plan.
So we remove it and will work on an alternative solution.
=> TIP-1252 Removes deprecated docker layer caching

CHANGELOG-3.2.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/fields/simple-select-async.js
If you press tab on the identifier field to select the next field family (keyboard navigation) and you start typing to search for a family; then the select2 field misbehave and jump in the top-left corner of the screen:
Fix:
I fixed it by luck, as it seems to be a race condition between a re-render of the template and the select2 dynamic dropdown positioning.
Removing the re-render doesn't break/change everything on the behavior of the form/select2 on this page and it should not break anything elsewhere (but we never know).
(If someone with extensive knowledge of the frontend stack / select2 have a better explanation I'm interested)
| …
=> PIM-8750: Fix wrong re-render on simple-select-async

docker-compose.yml
Because on the non OSS package, xpack plugin is installed. It works 2 weeks for free and then you have to pay for it.
=> TIP-1250: use the OSS image for ES

tests/back/Pim/Enrichment/Upgrade/RemoveProductEmptyRawValuesIntegration.php, tests/back/Pim/Enrichment/Upgrade/RemoveProductModelEmptyRawValuesIntegration.php, upgrades/schema/Version_4_0_20190916122239_remove_empty_raw_values.php, upgrades/schema/Version_4_0_20190916122239_remove_product_empty_raw_values.php, upgrades/schema/Version_4_0_20190917080512_remove_product_model_empty_raw_values.php
We forbid the use of null values in the domain, as it does not make sense (the value object should not accept null values anymore). It was the cause of multiple bug.
So, we should not have any null value anymore in the storage, which was not the case.
The gaol of this script is to clean the database.
The completeness is not impacted, no need to relaculate it.
We will have to re-index only the impacted product. Do note that the indexation will be with sql queries as we are currently reworking it.
=> TIP-1160: Add migration

CHANGELOG-2.3.md, src/Akeneo/Bundle/BatchBundle/Command/PurgeJobExecutionCommand.php, src/Akeneo/Bundle/BatchBundle/Persistence/Sql/DeleteJobExecution.php, src/Akeneo/Bundle/BatchBundle/Resources/config/removers.yml, tests/back/Integration/integration/BatchBundle/Persistence/Sql/DeleteJobExecutionIntegration.php
Fix [PIM-8738](https://akeneo.atlassian.net/browse/PIM-8738)  
Replace doctrine ORM removing by SQL removing. This is a backport of #10198 
=> PIM-8738: fix memory leak on purge job execution

src/Akeneo/Platform/Bundle/InstallerBundle/Command/DatabaseCommand.php
I changed the method signature in my previous PR but this method is overrided in EE. This PR avoids this error:
```
Compile Error: Declaration of Akeneo\Platform\Bundle\InstallerBundle\Comman  
d\EnterpriseDatabaseCommand::launchCommands() must be compatible with Akene  
o\Platform\Bundle\InstallerBundle\Command\DatabaseCommand::launchCommands()  
: Akeneo\Platform\Bundle\InstallerBundle\Command\DatabaseCommand 
``` …
=> Fix EE installation

CHANGELOG-2.3.md, src/Pim/Bundle/EnrichBundle/EventListener/Storage/RemoveCategoryFilterInJobInstanceSubscriber.php, src/Pim/Bundle/EnrichBundle/Resources/config/event_listeners.yml, src/Pim/Bundle/EnrichBundle/spec/EventListener/Storage/RemoveCategoryFilterInJobInstanceSubscriberSpec.php, src/Pim/Bundle/EnrichBundle/tests/integration/EventListener/RemoveCategoryFilterInJobInstanceSubscriberIntegration.php
Fix [PIM-7890](https://akeneo.atlassian.net/browse/PIM-7890)  
When a category or parent category is removed, the filter stay in the job instance and there is no way to remove it.  
Now when we remove a category, we also remove the filter in job instances.  
| Tech Doc …
=> PIM-7890: fix non removed category filter in job instances

CHANGELOG-2.3.md, src/Akeneo/Component/StorageUtils/Exception/InvalidObjectException.php, src/Pim/Bundle/ApiBundle/Controller/ProductController.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/PartialUpdateProductIntegration.php, src/Pim/Component/Catalog/Comparator/Filter/EntityWithValuesFilter.php, src/Pim/Component/Catalog/Updater/EntityWithValuesUpdater.php, src/Pim/Component/Catalog/spec/Comparator/Filter/EntityWithValuesFilterSpec.php
[PIM-8778](https://akeneo.atlassian.net/browse/PIM-8778)  
- Add exception when values are bad formatted
- Returns 422 error code instead of 500, with explicit message
=> PIM-8778: replace 500 error code by 422 in product API

CHANGELOG-3.2.md, src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/ProductController.php, src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/ProductModelController.php
Fix missing search_scope query parameter in API first, next, previous, current pagination links
=> PIM-8787: Fix missing search_scope in API links

src/Oro/Bundle/DataGridBundle/Resources/config/actions.yml, src/Oro/Bundle/DataGridBundle/Resources/config/services.yml, src/Oro/Bundle/PimDataGridBundle/Resources/config/mass_actions.yml
Getting services from the container is deprecated since Symfony 3.2 and will fail in 4.0. It quite impossible to easily refactor the datagrid that is why we decided to make some services public like datagrid action. …
=> TIP-1262 Make datagrid actions public

src/Akeneo/Pim/Enrichment/Component/Product/ReferenceData/MethodNameGuesser.php
`\Symfony\Component\PropertyAccess\StringUtil` is deprecated since version 3.1 and will be removed in 4.0. It is replaced by `Symfony\Component\Inflector\Inflector`
=> TIP-1262 Use Inflector instead of StringUtils because it is deprecated

src/Akeneo/Tool/Component/Connector/Job/JobParameters/ConstraintCollectionProvider/SimpleCsvExport.php, src/Akeneo/Tool/Component/Connector/Job/JobParameters/ConstraintCollectionProvider/SimpleCsvImport.php
Not setting the strict option of the Choice constraint to true is deprecated since Symfony 3.4 and will throw an exception in 4.0
=> TIP-1262 Add strict mode to choice validation constraint

tests/back/Acceptance/Resources/config/behat/services.yml, tests/back/Pim/Enrichment/Acceptance/Resources/config/behat/services.yml, tests/back/Platform/Acceptance/CatalogVolumeMonitoring/Resources/config/behat/services.yml
In symfony 4.0 all services are private by default that means our Behat services are private too. Behat Symfony extension need to get those services that why we declare them as public.
`-`: Not …
=> TIP-1262 Make context services public to avoid failure in SF4.3

CHANGELOG-3.0.md, src/Oro/Bundle/PimDataGridBundle/Query/Sql/ListAttributesUseableInProductGrid.php
The SKU (identifier) filter is displayed as selected for filter but does not appear on the sidebar. You have to unselect it, then reselect it to see it appearing on the menu. This is because it was not fetched in the first page of filters. The fix add a special 'ORDER BY' to make the identifier the first to be returned by the filter list so that it will always be displayed.
| Tech Doc …
=> PIM-8769: Fix 'SKU' filter disappearing from the filter options

src/Akeneo/Tool/Bundle/ApiBundle/tests/integration/ApiTestCase.php, tests/back/Integration/IntegrationTestsBundle/Loader/DatabaseSchemaHandler.php, tests/back/Integration/IntegrationTestsBundle/Loader/FixturesLoader.php, tests/back/Integration/IntegrationTestsBundle/Resources/config/services.yml, tests/back/Integration/IntegrationTestsBundle/Security/SystemUserAuthenticator.php, tests/back/Integration/TestCase.php, tests/back/Pim/Enrichment/Integration/Classification/ClassifyProductModelIntegration.php, tests/back/Pim/Enrichment/Integration/Doctrine/Common/Saver/SavingProductModelDescendantsIntegration.php, tests/back/Pim/Enrichment/Integration/Fixture/EntityBuilder.php, tests/back/Pim/Enrichment/Integration/PQB/Filter/Field/ParentFilterIntegration.php, tests/back/Pim/Enrichment/Integration/Product/Query/Sql/GetCategoryCodesByProductIdentifiersIntegration.php, tests/back/Pim/Enrichment/Integration/Product/Query/Sql/GetGroupAssociationsByProductIdentifiersIntegration.php, tests/back/Pim/Enrichment/Integration/Product/Query/Sql/GetProductAssociationsByProductIdentifiersIntegration.php, tests/back/Pim/Enrichment/Integration/Product/Query/Sql/GetProductModelAssociationsByProductIdentifiersIntegration.php, tests/back/Pim/Enrichment/Integration/Product/Query/Sql/GetValuesAndPropertiesFromProductIdentifiersIntegration.php, tests/back/Pim/Enrichment/Integration/ProductModel/Query/Sql/GetCategoryCodesByProductModelCodesIntegration.php, tests/back/Pim/Enrichment/Integration/ProductModel/Query/Sql/GetGroupAssociationsByProductModelCodesIntegration.php, tests/back/Pim/Enrichment/Integration/ProductModel/Query/Sql/GetProductAssociationsByProductModelCodesIntegration.php, tests/back/Pim/Enrichment/Integration/ProductModel/Query/Sql/GetProductModelsAssociationsByProductModelCodesIntegration.php, tests/back/Pim/Enrichment/Integration/ProductModel/Query/Sql/GetValuesAndPropertiesFromProductModelCodesIntegration.php
When trying to upgrade to SF4, we face a problem: all services are now private by default. In the test, you can bypass that problem by setting `test: true` in the `framework` configuration.
In our PhpUnit tests, we have a weird "double kernel booted". We sometimes inject `@service_container` or `@kernel` to retrieve some services inside the test services. It seems, but we are not sure, that those injected containers are not built with the `test` configuration set to `true`.
Anyway, even if this PR doesn't fix our problem, it's better to properly inject only what we need.
=> TIP-1262: proper dependency injection in the test services

Makefile, src/Akeneo/Platform/Bundle/InstallerBundle/Command/CheckRequirementsCommand.php, src/Akeneo/Platform/Bundle/InstallerBundle/Resources/config/cli_command.yml, src/Akeneo/Platform/PimRequirements.php
This is kind of a hot/dirty fix just to be able to deploy a EE PIM with Ansible.
Ideally, the `check-requirements` command should not check the same thing between an onprem and a SaaS instance. I'll fix that with TIP-1295.
=> TIP-1263: fix check requirements

.circleci/config.yml
During the setup of the PIM all docker containers are up but we don't need that because all makfile targets run command thought docker instead of exec them.
The setup job has been renamed because we will need to build the pim to run tests on dev and prod docker images soon.
| Tech Doc …
=> Clean Circle-CI configuration

CHANGELOG-2.3.md, src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Query/GetChannelActiveLocaleCodes.php, src/Pim/Bundle/CatalogBundle/EventSubscriber/RemoveLocaleFilterInJobInstancesSubscriber.php, src/Pim/Bundle/CatalogBundle/Resources/config/event_subscribers.yml, src/Pim/Bundle/CatalogBundle/Resources/config/queries.yml, src/Pim/Bundle/CatalogBundle/tests/integration/Doctrine/ORM/Query/GetChannelActiveLocaleCodesIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/EventSubscriber/RemoveLocaleFilterInJobInstanceSubscriberIntegration.php
Product exports are now updated when a locale is removed of a channel : if the removed locale was used as a filter in an export, the locale filter is removed.
=> PIM-6424: update exports when a locale is removed from a channel

CHANGELOG-3.2.md, src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/grid.js
If you go to the product grid, then PEF, then product grid, it will register 2 times the events of the datagrid and refresh 2 times the grid on product deletion.
This PR removes the previous events before adding new ones.
=> PIM-8820: Avoid multiple refresh of the product grid on product delete

src/Akeneo/Platform/PimRequirements.php
OK... Well...
There is this [MySQL bug](https://bugs.mysql.com/bug.php?id=96823) in 8.0.17. The previous requirements were here to force us to install 8.0.16, and so, to avoid this bug.
It works well for the CI as we use Docker containers.
For our test features environments, we use the scripts Ansible scripts. Which themselves use the official MySQL repository. Which only provides MySQL 8.0.17. That means, currently we can't deploy a test dev environment. And yes, with this PR, that means we'll be able to deploy a test dev env, but it will have the MySQL bug... 
This is the less worse we can do. We have to wait for MySQL to release a 8.0.18 :crossed_fingers:   When they'll do, I'll update again the requirements.
=> TIP-1249: Update MySQL requirements

src/Akeneo/Pim/Enrichment/Component/Product/Completeness/MaskItemGenerator/DefaultMaskItemGenerator.php, src/Akeneo/Pim/Structure/Component/AttributeTypes.php
Fixes an error during the last 3.2 -> master pull-up (2 very similar constants were added).
Also, defaultMaskItemGenerator can now handle EE  refentity collections attributes
=> Fix MaskItemGenerator for EE attribute types

src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ElasticsearchProjection/GetElasticsearchProductModelProjection.php, tests/back/Pim/Enrichment/Integration/ProductModel/Query/Sql/GetElasticsearchProductModelProjectionIntegration.php
Fixes a `null` => 0 conversion while hydrating ElasticsearchProductModelProjection instances
=> TIP-1174: Fix elasticsearch product model projection for root product models

CHANGELOG-3.0.md, src/Akeneo/Pim/Enrichment/Component/Category/CategoryTree/UseCase/ListRootCategoriesWithCountHandler.php, src/Akeneo/UserManagement/Bundle/Context/UserContext.php
The called method was not aware of any permission to get the default catalog tree.
It implies a bug on front.
=> PIM-8331: Fix display of category tree in the product grid when user does not have access to its default tree

src/Akeneo/Pim/Enrichment/Bundle/Command/CalculateCompletenessCommand.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/cli_command.yml, tests/back/Pim/Enrichment/Integration/Completeness/CalculateCompletenessCommandIntegration.php
Refactor the `pim:completeness:calculate` command:
- recompute completeness for all products (not only the ones with missing completeness)
- do not hydrate products whereas only identifiers are needed
`OK`: …
=> TIP-1159: Refactor completeness calculation command

CHANGELOG-3.0.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/product/field/metric.html
=> PIM-8852: Fix display of locale specific metric attribute in PEF

CHANGELOG-3.2.md, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/datagrid/product.yml, src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/product-row.js, src/Oro/Bundle/PimDataGridBundle/Resources/public/templates/datagrid/row/product-thumbnail.html
It does not change the display of the standard grid because only the "values" are displayed.
It only always return the image and label "properties" in the product grid.
=> PIM-8838: Force display of label and image in gallery mode even if they are not in the column list

src/Pim/Bundle/EnrichBundle/Controller/FileController.php, src/Pim/Bundle/UIBundle/Resources/public/less/components/product-edit-form/MediaField.less
In Imagine (vendor/imagine/imagine/lib/Imagine/Gd/Imagine.php:187) when you try to create an image from TIFF, it throws a RuntimeException.
I added a catch to render the default image.
=> PIM-7644: Fix 500 error on thumbnail of TIFF images

tests/back/Integration/IntegrationTestsBundle/Loader/DatabaseSchemaHandler.php, tests/legacy/features/Behat/Context/DBALPurger.php
**Problem**
When renoving a product model, the delete cascade does not delete child product.
Not reproducible in a dedicated transaction, with the same queries.
**Cause**
When loading the dump, we reset the database. To reset it, we deactivate the foreign key check and then delete + truncate tables and then reactivate it.
In a same query:
`SET FOREIGN_KEY_CHECKS = 0; delete...; truncate ... ; SET FOREIGN_KEY_CHECKS = 1`
The problem is that we try to truncate EE tables, and the query silently fail until this instruction. Therefore, the `SET FOREIGN_KEY_CHECKS = 1` is never called (but not error raised).
**Solution**
Do not truncate EE tables (just to be clean). Isolate in a dedicated query the reactivation of the checks.
**Definition Of …
=> Reactivate foreign key after loading the dump

CHANGELOG-4.0.md, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml, src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Completeness/VariantProductRatio.php, src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Connector/SqlGetConnectorProductModels.php, src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Family/CountEntityWithFamilyVariant.php, src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Family/CountProductsWithFamily.php, src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Family/FindAttributesForFamily.php, src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Product/GetAssociatedProductCodesByProductFromDB.php, src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Product/SqlGetValuesOfSiblings.php, src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductGrid/ProductModelImagesFromCodes.php, src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductModel/CountProductModelsAndChildrenProductModels.php, src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductModel/GetCategoryCodesByProductModelCodes.php, src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductModel/GetGroupAssociationsByProductModelCodes.php, src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductModel/GetProductAssociationsByProductModelCodes.php, src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductModel/GetProductModelsAssociationsByProductModelCodes.php, src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductModel/GetValuesAndPropertiesFromProductModelCodes.php, tests/back/Pim/Enrichment/Integration/Storage/Sql/ElasticsearchProjection/GetElasticsearchProductModelProjectionIntegration.php, tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductModel/CountProductModelsAndChildrenProductModelsIntegration.php, tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductModel/GetCategoryCodesByProductModelCodesIntegration.php, tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductModel/GetGroupAssociationsByProductModelCodesIntegration.php, tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductModel/GetProductAssociationsByProductModelCodesIntegration.php, tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductModel/GetProductModelsAssociationsByProductModelCodesIntegration.php, tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductModel/GetValuesAndPropertiesFromProductModelCodesIntegration.php
- Move Enrichment queries from `ProductModel\Query\Sql` to `Storage\Sql`
- Update queries to use DBAL connection instead of Entity Manager when possible
=> TIP-1287: move product model queries

CHANGELOG-3.2.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/menu/user-navigation.js
In the user-navigation dropdown, the delegateEvents method was only called during initialize, not in the render. Click events on this menu items were not registered after a re-render.
=> PIM-8773: Add missing delegateEvents() in the render of the user-navigation dropdown

CHANGELOG-2.3.md, src/Pim/Bundle/CatalogBundle/EventSubscriber/RemoveAttributeFiltersInJobInstancesOnAttributeDeletion.php, src/Pim/Bundle/CatalogBundle/tests/integration/EventSubscriber/RemoveAttributeFiltersInJobInstancesOnAttributeDeletionIntegration.php, src/Pim/Bundle/EnrichBundle/Resources/config/event_listeners.yml
When an attribute is deleted in the PIM, product exports are now updated is the attribute was used as a filter
=> PIM-7891: update exports when an attribute is deleted

CHANGELOG-2.3.md, src/Pim/Bundle/CatalogBundle/Resources/translations/validators.en.yml, src/Pim/Component/Catalog/Validator/ConstraintGuesser/RangeGuesser.php, src/Pim/Component/Catalog/Validator/Constraints/ValidNumberRange.php, src/Pim/Component/Catalog/Validator/Constraints/ValidNumberRangeValidator.php, src/Pim/Component/Catalog/spec/Validator/ConstraintGuesser/RangeGuesserSpec.php, src/Pim/Component/Catalog/spec/Validator/Constraints/ValidNumberRangeValidatorSpec.php
It adds an error message when you edit a product and you try to put a number higher than PHP_INT_MAX.
It adds an error message when you edit an attribute and you try to put as the maximum a number higher than PHP_INT_MAX. (It was the case before but now you have an explicit error message) .
`Todo`: …
=> PIM-7332: show an error message when a number attribute field reaches the PHP_INT_MAX

CHANGELOG-2.3.md, src/Pim/Bundle/UserBundle/Form/Type/UserType.php, src/Pim/Bundle/UserBundle/Resources/config/form_types.yml, tests/legacy/features/user/edit_user.feature
Users without the permissions `Edit roles` or `Edit user groups` could escalate their own role from `User` to `Administrator`. The previous security check was only on the current route, if it was `oro_user_profile_update`, they were not allowed to change their own roles.
The problem was, this form was since accessible in other pages.
The solution is to use the SecurityFacade service to check if the logged user has the correct permissions.
| Added legacy Behats               | yes
| …
=> PIM-7691: Users were able to edit their own roles

Makefile, config/services/behat/parameters.yml, config/services/pim_parameters.yml, config/services/test/parameters.yml, config/services/test_fake/parameters.yml, src/Akeneo/Platform/Bundle/InstallerBundle/Command/DatabaseCommand.php, src/Akeneo/Platform/Bundle/InstallerBundle/FixtureLoader/FixtureJobLoader.php, src/Akeneo/Platform/Bundle/InstallerBundle/FixtureLoader/FixturePathProvider.php, src/Akeneo/Platform/Bundle/InstallerBundle/FixtureLoader/JobInstancesConfigurator.php, src/Akeneo/Platform/Bundle/InstallerBundle/Resources/config/cli_command.yml, src/Akeneo/Platform/Bundle/InstallerBundle/Resources/config/fixture_loader.yml, tests/back/Integration/IntegrationTestsBundle/Loader/FixturesLoader.php, tests/back/Platform/Specification/Bundle/InstallerBundle/FixtureLoader/FixturePathProviderSpec.php, tests/back/Platform/Specification/Bundle/InstallerBundle/FixtureLoader/JobInstancesConfiguratorSpec.php, tests/legacy/features/Context/CatalogConfigurationContext.php
The parameter `%installer_data%` has been removed in this PR and the installation command has been improved too. We want to install the minimal catalog by default except for the symfony dev environement `ice cat demo dev` will be installed.
To install `icecat demo dev` you need to run the following command:
```
$ O="--catalog src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev" make database
// OR
$ bin/console pim:install:db --catalog src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev
```
The options `catalog` is not mandatory, its default value is the path where is the minimal catalog. Don't worry, the target `pim-dev` will still install the `ice cat demo dev` catalog!
**Definition …
=> TIP-1278 Catalog installation

.eslintignore, tests/front/acceptance/cucumber/world.js
- Ignore jslint for asset manager tests
- bump the number of max listened request for puppeteer
=> PIM-8842: Fix js lint ignore

CHANGELOG-3.0.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/lib/select2.less, tests/legacy/features/pim/enrichment/product-model/create_product_model.feature
`display: flex` on `.select2-result-label` was breaking the rendering of highlighted matches when searching inside select2, the solution is to avoid using flex and only use line-height + ellipsis.
=> PIM-8369: Remove flex from families dropdown css

CHANGELOG-3.0.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/family/form/attributes/attributes.js, tests/legacy/features/pim/structure/family/remove_attribute_from_a_family.feature
`_.sortBy` does return the sorted collection, the previous version was not storing in a variable nor using it.
The attributes need to be sorted and then grouped to be displayed correctly.
=> PIM-8585: fix incorrect displayed order in attributes groups

CHANGELOG-2.3.md, src/Pim/Bundle/EnrichBundle/Controller/Rest/AttributeController.php
When editing a text or text-area attribute, removing the value in the `max_characters` field resulted in a bad request from the server, this was because the empty string value was not being treated as `null`.
`OK`: …
=> PIM-6976: fix max_characters attribute field not being nullable

src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filters-column.ts
=> Allow only default filters without calling a dynamic attributes query

src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/select2-rest-choice-filter.js
By default, we show always "in list", "empty", "not empty" operators for a choice filter. For some use case, it's a non sense. Allow to show only specific operators.
`-`: Not …
=> Allow to show only specific operators

CHANGELOG-2.3.md, src/Pim/Bundle/UIBundle/Resources/config/assets.yml, src/Pim/Bundle/UIBundle/Resources/public/less/lib/bootstrap.datepicker.less
The datepicker was not adapting its width when changing the month or the year, I added a lib customization to fix it.
=> PIM-7963: fix datepicker width not adapting to the dropdown

CHANGELOG-3.2.md, composer.json, composer.lock, src/Akeneo/Pim/Enrichment/.php_cd.php, src/Akeneo/Pim/Enrichment/Bundle/PdfGeneration/Builder/DompdfBuilder.php
We update dompdf because the pdf export fail on some products on a known error fixed in 0.8.3,
see https://github.com/dompdf/dompdf/issues/902
=> PIM-8893: update dompdf because the pdf export fail on some products

CHANGELOG-3.2.md, src/Akeneo/Pim/Enrichment/Bundle/Controller/Ui/FileController.php
We were not able to display thumbnails in the grid
=> PIM-8908: Fix default image always showing

CHANGELOG-4.0.md, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/validation/product.yml, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/validation/productmodel.yml, src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/validators.en_US.yml, tests/back/Acceptance/Catalog/Context/ProductCreation.php, tests/back/Acceptance/Catalog/Context/ProductValidation.php, tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/PartialUpdateListProductEndToEnd.php, tests/back/Pim/Enrichment/Integration/Validation/ProductIdentifierValidationIntegration.php, tests/features/pim/enrichment/product/value/product_identifier.feature, tests/legacy/features/Context/WebUser.php, tests/legacy/features/pim/enrichment/product/create_product.feature
All the characters except comma “,“ and semicolon “;“ are accepted for the product identifiers. If there is a space at the beginning or end of an identifier, it will be saved with it in the database.
The problem, in this case, is that the trailing spaces are ignored when we search a product by its identifier. It’s due to MySQL where all CHAR, VARCHAR, and TEXT values are compared without regard to any trailing spaces (it's according to the collation, and all the collations in MySQL 5.x have this behavior).
For instance, with an existing product with the identifier "foo". If a product is imported with the identifier " foo", a new product will be created, but with an identifier "foo ", the product "foo" will be updated. If there's a space at the beginning, the product repository doesn't …
=> PIM-8894: Change product identifier validation to forbid surrounding spaces

docker/wait_docker_up.sh
Since few day we have used `wait_docker_up.sh` in the MakeFile but some targets have been broken (pim-XXX, for example). This script checks that MySQL and Elasticsearch are alive. To know if ES is up we need to call an URL: `http://elasticsearch:9200/_cat/health` and find the word green. ES provides a better service: "http://elasticsearch:9200/_cluster/health?wait_for_status=green`. We don't need to use `grep` anymore. 
The main problem is that we use `docker-composer run` to call this URL instead  `docker-composer exec`. `docker-composer run` boots a container but  `docker-composer exec` uses the existing container.
| …
=> TIP-1327 Fix docker script (wait for elasticsearch)

tests/back/Integration/IntegrationTestsBundle/AkeneoIntegrationTestsBundle.php, tests/back/Integration/IntegrationTestsBundle/DependencyInjection/MakeServicesPublicForTestEnv.php
This PR simply put the compiler pass responsible to make the services public for in test env in Community Edition.
See https://github.com/akeneo/pim-community-dev/pull/10773
=> TIP-1262: make services public for test env

CHANGELOG-3.2.md, src/Akeneo/Pim/Enrichment/Bundle/PdfGeneration/Renderer/ProductPdfRenderer.php, tests/back/Pim/Enrichment/Specification/Bundle/PdfGeneration/Renderer/ProductPdfRendererSpec.php
A sanity check was missing on the option value before accessing its data : in some case, a simple or a multi select won't have any option for one or multiple locales.
`-`: Not …
=> PIM-8925: fix PDF export when there is no option for a given locale for a select attribute

CHANGELOG-3.0.md, src/Akeneo/Pim/Structure/Bundle/Controller/InternalApi/AttributeGroupController.php, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/attribute-group/form/list.js, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/attribute-group/list.html
Fix permission on attribute group sorting. Sort was always allowed even if the permission was uncheck.  
Backport of https://github.com/akeneo/pim-community-dev/pull/10277
=> PIM-8924: fix permission on attribute group sorting

src/Akeneo/Pim/Structure/Bundle/Resources/config/validators.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/generator/media-url-generator.js, tests/legacy/features/pim/enrichment/product/mass-action/quick-export/quick_export_products_and_product_models.feature, tests/legacy/features/pim/structure/family/import/import_families.feature
This PRs adds the support of Asset Manager **assets as main image for products**.
As Asset Manager **already provides direct url** for assets preview, we need to tweak the MediaUrlGenerator to display correct filepath.
=> PIM-8668: use an Asset Collection attribute as main image

CHANGELOG-3.0.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product-model/form/add-child/fields-container.js
Use catalog locale instead of UI locale. 
=> PIM-8927: fix translation on product model creation page

CHANGELOG-3.0.md, src/Akeneo/Pim/Structure/Bundle/Controller/InternalApi/AttributeGroupController.php, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/attribute_group/edit.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/attribute-group/form/tab/attribute.js, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/attribute-group/tab/attribute.html
A user that didn't have the permission to sort attributes could do it. This PR fix it.
=> PIM-8928: Fix permission of sorting attributes inside an attribute group

src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/AttributeOptionsExistValidator.php, tests/back/Acceptance/AttributeOption/InMemoryAttributeOptionRepository.php, tests/back/Acceptance/spec/AttributeOption/InMemoryAttributeOptionRepositorySpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/AttributeOptionsExistValidatorSpec.php, tests/features/pim/enrichment/product/validation/option_values.feature
Fixes a regression introduced in #10895: The validation of attribute option codes existence should be case insensitive
| Added acceptance tests            | OK
=> PIM-8879: Case insensitive validation of attribute option codes 

tests/front/WRITING-FRONT-TESTS.md
=> PIM-8836: fix extensions dump command in documentation

CHANGELOG-2.3.md, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/product-completeness.js
When we change locale on PEF and the ratio can not be calculated on this locale, completeness widget element was removed. So it can be display again when we change back to a locale with ratio. The element was removed to fix design issues. Here the solution is to hide it.
| Tech Doc …
=> PIM-7027: fix completeness visibility on PEF

.circleci/config.yml, Makefile, docker-compose.yml, make-file/apps.mk, make-file/channel.mk, make-file/dev.mk, make-file/enrichment.mk, make-file/structure.mk, make-file/test.mk, make-file/user-management.mk, src/Akeneo/Apps/back/tests/Acceptance/behat.yml
This PR introduces some new targets to run our tests, they are located in `make-file/test.mk`. At the end the purpose of this PR and the next ones is to be able to run tests the same way on the CI and locally. We won't rework the targets phpunit and behat-legacy in this PR. We want to keep it as simpler as possible for now.
For your information this new file contains the following targets:
* coupling: checks if the bounded context are well "de-coupled" (moved from `make-file/dev.mk`)
* check-pullup: checks is there are not mistake during the pull up
* lint-back and lint-front analyzes source code to flag programming errors, bugs, stylistic errors, and suspicious constructs. [Why this name?](https://en.wikipedia.org/wiki/Lint_(software))
* unit-back and unit-front: run all unit tests (back …
=> TIP-1327: Introduce new targets to run our tests (locally and on the CI)

.circleci/config.yml, .circleci/run_phpunit.sh, make-file/apps.mk, make-file/dev.mk, make-file/test.mk
Please have a look to this [PR](https://github.com/akeneo/pim-community-dev/pull/10984).
This PR adds two new target `integration-back` and `end-to-end-back` to run integration and end to end tests with phpunit.
`OK`: …
=> TIP-1327: Introduce new targets to run our tests (locally and on the CI) 

CHANGELOG-3.2.md, src/Akeneo/Pim/Structure/Bundle/Controller/InternalApi/FamilyController.php, src/Akeneo/Pim/Structure/Bundle/Resources/config/model/doctrine/Family.orm.yml, src/Akeneo/Pim/Structure/Component/Model/Family.php, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/properties/translation.js, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/form/properties/translation.html
Before, the back was sending validation errors in this format:
[
'translations[0].label': { message: 'Too long' },
]
And the front was expecting 
[
'translations': { en_US: { message; 'Too long' } }
]
After investigation, the [0] comes from the translation relation. Once validation are created, they does not include at all any information about the failing locale. So we choose to index the translations with the current locale (with indexBy).
From the front point of view, we transform "translations[en_US].label: { ... }" into "translations: { en_US : ... } }"
=> PIM-8943: Display validation messages on family translations

CHANGELOG-2.3.md, CHANGELOG-3.2.md, src/Akeneo/UserManagement/Bundle/Controller/Rest/UserController.php, tests/legacy/features/user-management/user/edit_user.feature
When you didn't have the permission to "list users", you didn't have the users list, but you could continue to access a user page with its path.
This PR forbid it.
=> PIM-8953: User without 'list users' permission can not access to other user pages

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/variant-navigation.js
The goal of this is to make the method `isCreationGranted` asynchronous as the Entreprise Edition need to do a call to the API to check some permissions.
See https://github.com/akeneo/pim-enterprise-dev/pull/7224 …
=> PIM-8944: Make variant navigation isCreationGranted method async

.circleci/config.yml, .circleci/run_behat.sh, make-file/apps.mk, make-file/channel.mk, make-file/dev.mk, make-file/enrichment.mk, make-file/structure.mk, make-file/test.mk, make-file/user-management.mk
Please have a look to this [PR](https://github.com/akeneo/pim-community-dev/pull/10984).
This PR adds a new target `end-to-end-legacy-back` to run behat legacy and end to end tests with behat. …
=> TIP-1327: Use make to run behat legacy tests

config/services/test_fake/services.yml
In 3.2, we experienced an issue on the asset manager BC regarding the integration tests of controllers. Every 404th+ tests would fail, but they would pass if run one by one.
We figured this issue happened because the SSO Repository had no InMemory implementation for the `test_fake` environment, so it would call the database anyway.
This repo was called for each HTTP request made to the PIM.
To fix this issue, we decided to close openned connection even on the for kernel built with the `test_fake` env.
On master, this service was not part of the `test_fake` env (_as it should_).
Today, we are currenlty blocked by this in the 3.2 -> master pull-up.
**Solution:**
Add the `akeneo_integration_tests.doctrine.connection.connection_closer` …
=> Pull-up: Fix Asset Manager integration tests

make-file/test.mk
Some builds have failed since a while because some weird characters (^@^@) appear in the output of some commands. For instance, the phpspec junit was not valid because at the beginning of the file we have "^@^@". Running command thought docker with the option -T prevent this errors. 
| Tech …
=> TIP-1290 Fix CI to avoid "^@^@" character

CHANGELOG-3.0.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/common/select2/family.js
This pull request aims to fix label translation on product family selection. The translation language of the family labels is the catalog locale.
=> PIM-8985: Fix label translation on family product selection

src/Akeneo/Apps/back/Infrastructure/Symfony/Resources/config/requirejs.yml
Restrict the access to the Apps settings for frontend routes.
=> API-719: Restrict Apps access

CHANGELOG-2.3.md, src/Pim/Bundle/EnrichBundle/Resources/public/templates/job-execution/summary-table.html
The following error message is thrown when the field "sku" in an import is submitted as "SKU." 
However, since the error message states "SKU" it is unclear where the error actually comes from (that case-sensitivity is not respected). The error message should reflect the error - that "sku" is missing from the imported file, not the caps lock "SKU." 
New error screen:
=> PIM-8965: Fix misleading error messages due to all-caps formatting

CHANGELOG-2.3.md, src/Pim/Bundle/UserBundle/Controller/UserRestController.php, src/Pim/Bundle/UserBundle/Resources/config/controllers.yml
Every user can access to the data of any other user with the end-point "pim_user_user_rest_get", even if the permission "List users" is not granted. 
It's a backport of https://github.com/akeneo/pim-community-dev/pull/11036 for the 2.3 with the difference that in 2.3, the user identifier of the end-point is not the integer id, but the user name or its email.
=>  PIM-8954: Forbid access to any user data when the permission 'list users' is not granted

CHANGELOG-2.3.md, src/Pim/Bundle/EnrichBundle/Doctrine/ORM/Repository/AttributeSearchableRepository.php, tests/legacy/features/attribute-group/display_attribute_group_history.feature
When listing a list of attributes, make sure they are sorted by:
- their attribute groups' sort_order
- their own sort_order
=> PIM-8989: fix attribute sort order in select

config/packages/liip_imagine.yml
Change `LiipImagine` conf to use `imagick` as driver, in order to be able to generate `tiff` and simple `psd` previews.
=> AST-11: Use imagick as liip_imagine driver

CHANGELOG-3.0.md, src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/validators.en_US.yml, src/Akeneo/Pim/Structure/Bundle/Resources/config/validation/attribute.yml
By the import, it's possible to create an attribute with a code with a line-feed as the last character.
The regex that validates an attribute code doesn't take account of that `/^[a-zA-Z0-9_]+$/` 
Per default, the trailing line-feeds are ignored after the `$` 
It could be fixed by adding the regex modifier `D` but I added another regex to be able to display a specific message, because the line-feeds are not displayed.
=> PIM-8992: Do not allow to import attribute code with line-feed characters

src/Akeneo/Platform/Bundle/InstallerBundle/Command/DumpRequirePathsCommand.php
With this PR, instead of generating absolute paths in the `require-paths.js`, we generate relative ones.
This resolve an issue with docker where the paths generated in a container does not match the paths on the host, preventing any yarn command to be run in the host.
This was a real handicap for debugging cucumber-js tests.
| …
=> Use relative paths instead of absolute ones in require-paths.js

src/Akeneo/Apps/back/Application/Validation/App/CodeMustBeUnique.php, src/Akeneo/Apps/back/Domain/Model/ValueObject/AppCode.php, src/Akeneo/Apps/back/Domain/Model/ValueObject/AppLabel.php, src/Akeneo/Apps/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml, src/Akeneo/Apps/back/tests/Acceptance/Context/AppContext.php, src/Akeneo/Apps/back/tests/Unit/spec/Application/Validation/App/CodeMustBeUniqueValidatorSpec.php, src/Akeneo/Apps/front/src/application/apps/actions/create-form-actions.ts, src/Akeneo/Apps/front/src/application/apps/components/AppCreateForm.tsx, src/Akeneo/Apps/front/src/application/apps/components/AppEditForm.tsx, src/Akeneo/Apps/front/src/application/apps/reducers/app-form-reducer.ts, src/Akeneo/Apps/front/src/application/apps/use-create-app.ts, src/Akeneo/Apps/front/tests/unit/application/apps/components/AppEditForm.spec.tsx
- Fix App code and label validation to not allow empty string
- Fix translation keys usage (missing `.app.`)
- Fix style lint (not runned in the CI, I will do a PR to enable it again)
- Remove unused code in create App form …
=> API-656: Fix App code and label validation

CHANGELOG-3.2.md, src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/FollowUp/GetCompletenessPerChannelAndLocale.php, tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/FollowUp/GetCompletenessPerChannelAndLocaleIntegration.php
When a channel would have no translations, the sql query responsible for generating the completeness widget read model would fail.
This was due to the fact when generating all the labels for the channels in a JSON object using JSON_OBJECTAGG with such a usecase, mysql would throw an error stating that it cannot build a JSON_OBJECT having a NULL key.
**Solution** (Found by alex)
Instead of creating the json object from the available translations, we now create them by starting with the activated locales in the PIM and try to find the labels for all the locales. In this case, it's possible to create a json object having a NULL value.
I've tried to improve the integration test, let me know if you dislike the style
**Definition Of Done (for …
=> PIM-8995: Adds the supports of the completeness widget for channels having no translations

CHANGELOG-3.0.md, src/Akeneo/Pim/Structure/Bundle/EventSubscriber/CreateAttributeRequirementSubscriber.php, tests/back/Pim/Structure/Specification/Bundle/EventSubscriber/CreateAttributeRequirementSubscriberSpec.php
When a channel is created, all the attribute requirements are created and persisted in the same process. So one line is inserted per attribute of each family.
For a catalog with a lot of families and a lot of attributes per family, the creation of a channel reaches the maximum time execution. (PS: it's not a memory leak. The process could run for hours if we don't limit it)
The proposed solution is simply to create only the attribute requirements for the identifier.
| Added integration …
=> PIM-8990: Fix channel creation taking too much time

CHANGELOG-3.0.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/field/wysiwyg-field.js
WYSIWYG editor use `<p><br></p>` as empty value (for [compatibility issue](https://github.com/summernote/summernote/pull/313)), to avoid saving this value we have to set empty value ourself on submit.
`OK`: Done / …
=> PIM-8997: Fix incorrect empty value stored for wysiwyg editor

.circleci/run_behat.sh, .circleci/run_phpunit.sh
Make sure phpunit and behat fails properly when failing on listing tests.
=> Makes script fails in case of failure to get tests list

CHANGELOG-3.2.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/lib/select2.less
For `records`, the height of a row in the select2 dropdown did not match the design.
=> PIM-8984: Fix css on records dropdowns

CHANGELOG-3.2.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/field/media-field.js
When uploading a file in the media field, a failure (file too big, for example) did not display an error in the UI.
Using `messenger.notify` instead of `messenger.enqueueMessage` will ensure the message is shown.
=> PIM-8996: Display an error when a file upload failed

CHANGELOG-2.3.md, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/variant-navigation.js
This PR fix a bug that can happen when selecting a newly created channel and choosing a variant product that has no completeness yet.
=> PIM-9003: fix product variant navigation when there is no completeness for a given channel

CHANGELOG-3.0.md, src/Akeneo/Pim/Enrichment/Bundle/Command/CleanRemovedAttributesFromProductAndProductModelCommand.php
=> PIM-9002: Allow command "pim:product:clean-removed-attributes" to work with --no-interaction parameter

src/Akeneo/Platform/PimRequirements.php
Add the `mbstring` extension as part of the requirements.
Already in the documentation: https://docs.akeneo.com/master/install_pim/manual/system_requirements/system_requirements.html
Already in the production docker image: https://github.com/akeneo/pim-community-dev/blob/master/Dockerfile#L31 …
=> DAPI-660 - add mbstring extension as official requirement

CHANGELOG-3.2.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/product/edit/content/structure/attributes-selector.js
We were displaying the "Remove" button when editing attributes to export on a product export profile edition:
(middle column should not have "Remove" button) 🠕
This PR fixes this behavior by displaying "Remove" button only when the item is in the "Selected" column:
| Tech Doc …
=> PIM-8988: Remove useless "Remove" button when editing exported attributes (in export profile)

.circleci/run_phpunit.sh
Some back integration tests fails because they endup with a segmentation fault (like this one https://circleci.com/gh/akeneo/pim-enterprise-dev/22764#tests/containers/3)
This PR attempts to print out the integration test file that failed directly after it failed.
`OK`: …
=> Fishing hook: print out failed integration tests

upgrades/schema/Version_4_0_20191031000000_modify_session_lifetime_type.php
Master broken in EE:
https://circleci.com/gh/akeneo/pim-community-dev/23012?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
```
Launch branch migrations...
PIM Migrations                    
WARNING! You have 1 previously executed migrations in the database that are not registered migrations.
>>  (_4_0_20191202144736_create_app_audit_table)
Migrating up to _4_0_20191031_modify_session_lifetime_type from _4_0_20191031124707_update_from_clients_to_apps
14:44:20 ERROR     [console] Error thrown while running command "doctrine:migrations:migrate --env=test --no-interaction". Message: "Could not find any migrations to execute." ["exception" => Doctrine\DBAL\Migrations\MigrationException]8;;file:///srv/pim/v …
```
=> Fix bad naming of migration script making migration failing

CHANGELOG-3.0.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/filter/product/category.js
This PR fix a bug on product export when cancelling a category selection. The chosen categories were synced by reference to the backbone "state" when the user selected / unselected a category, so the cancel operation didn't erase the user choices.
This fix is pretty simple : I send to the modal only a copy of the categories in the current backbone state, so the user clicks won't be synced. And only the modal validation button will sync the chosen categories.
| Added integration …
=> PIM-9007: [SLA] Cancelling category selection in export profile does not work

make-file/dev.mk, phpunit.xml.dist
… 
I broke the command `make phpunit` since this PR. Actually, you can't specify the environment on the fly because I removed this magic stuff:
```
$_SERVER += $_ENV;
$_SERVER['APP_ENV'] = $_ENV['APP_ENV'] = ($_SERVER['APP_ENV'] ?? $_ENV['APP_ENV'] ?? null) ?: 'dev';
$_SERVER['APP_DEBUG'] = $_SERVER['APP_DEBUG'] ?? $_ENV['APP_DEBUG'] ?? 'prod' !== $_SERVER['APP_ENV'];
$_SERVER['APP_DEBUG'] = $_ENV['APP_DEBUG'] = (int) $_SERVER['APP_DEBUG'] || filter_var($_SERVER['APP_DEBUG'], FILTER_VALIDATE_BOOLEAN) ? '1' : '0';
```
Now, you must specify the environment from the outside ot the `.env`: we use the makefile. It's the same as for the other commands, so it's simpler.
| Q …
=> Remove APP_ENV=test in the phpunit.xml to be specified outside of the process in the makefile

CHANGELOG-3.2.md, src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/Validator/ValidateSearchLocale.php, tests/back/Pim/Enrichment/Specification/Component/Product/Connector/UseCase/Validator/ValidateSearchLocaleSpec.php
The `locale` field of the completeness filter was forbidden but according to the API documentation, we should be able to use the `locale` filter for only one locale. But to filter on multiple locales, the `locales` filter must be used.
| Tech Doc                          | …
=> PIM-9008: Fix product models API when the filter "completenes" was used with a sub-filter "locale"

CHANGELOG-3.2.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/field/multi-select-field.js, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/select2/select2.css
Fix the display of very long option labels in the Product Edit Form (_truncate it with CSS, adds an ellipsis and a title on hover_).
**Before**:
**After**:
=> PIM-9005: Fix display of long option labels in the Product Edit Form

CHANGELOG-2.3.md, src/Pim/Bundle/EnrichBundle/Resources/public/js/family/form/attributes/toolbar/add-select/attribute-group/select.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/variant-navigation.js, tests/legacy/features/attribute-group/list_attribute_groups.feature, tests/legacy/features/family/add_attributes_to_family_by_group.feature
I just used the initial fix from Tamara (https://github.com/akeneo/pim-community-dev/pull/10866), wich was already good because Pierre's fix couldn't be backported as she suggested (his fix was for the attribute select, not the attribute group select).
| Tech Doc …
=> PIM-6437: Remove empty or already added attribute groups from family edit screen

CHANGELOG-3.2.md, src/Akeneo/Pim/Enrichment/Component/Category/CategoryTree/UseCase/ListRootCategoriesWithCountHandler.php, tests/back/Pim/Enrichment/Specification/Component/Category/CategoryTree/UseCase/ListRootCategoriesWithCountHandlerSpec.php
CF https://github.com/akeneo/pim-enterprise-dev/pull/7435
Also, this PR fix a spec that was not executed because of the a bad namespace.
=> PIM-8998: Avoid error 500 on asset list & product list when a user has no permission on categories & asset categories

config/packages/oneup_flysystem.yml, src/Akeneo/Tool/Bundle/FileStorageBundle/Resources/config/file_storage.yml, src/Akeneo/Tool/Component/FileStorage/File/FileFetcher.php, src/Akeneo/Tool/Component/FileStorage/spec/File/FileFetcherSpec.php, tests/back/Pim/Enrichment/Integration/Normalizer/Standard/FileIntegration.php
The tmpStorage filesystem cannot be something else than a local filesytem (otherwise the code will not work) and in the code was only used to get access to the `tmp_sotrage_dir` path.
This PR removes this filesystem and provide the `tmp_storage_dir` parameter directly to the FileFetch that needs it. …
=> Removes unused tmpStorage filesystem

src/Akeneo/Platform/Bundle/UIBundle/EventListener/AddContentSecurityPolicyListener.php
We will display a preview of uploading images using base64.
This PR add a rule in the CSP allowing `<img src="data:`
=> AST-40: Allows base64 images in CSP

src/Akeneo/Platform/Bundle/UIBundle/EventListener/ScriptNonceGenerator.php, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/services.yml, tests/back/Platform/Specification/Bundle/UIBundle/EventListener/AddContentSecurityPolicyListenerSpec.php, tests/back/Platform/Specification/Bundle/UIBundle/EventListener/ScriptNonceGeneratorSpec.php
The nonce used to authorize our inline scripts must not be regenerated on ajax calls.
We regenerate it on every first request and store it in session to retrieve it for ajax requests.
=> PIM-8950: Store script in session for ajax calls

CHANGELOG-3.2.md, src/Akeneo/Pim/Structure/Bundle/Resources/config/validation/attribute.yml, tests/back/Pim/Structure/EndToEnd/Attribute/ExternalApi/PartialUpdateListAttributeEndToEnd.php, tests/back/Pim/Structure/Integration/Attribute/Validation/GlobalConstraintsIntegration.php, tests/legacy/features/pim/structure/attribute/create_text_attribute.feature
I changed the translation key and not the message to not break every translation in every languages we have.
=> PIM-9016: Fix error message not translated for attribute code

CHANGELOG-3.2.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/attribute_group/create.yml
This PR fixes the validation error messages not displaying when trying to create an Attribute Group.
The module used to display the code field was not handling the errors correctly so I switched it for the same as in the Attribute form (`pim/form/common/fields/text`).
| Tech Doc …
=> PIM-9015: Fix validation message display on attribute group creation failure

CHANGELOG-2.3.md, src/Pim/Bundle/EnrichBundle/Resources/config/acl.yml
This PR removes the "Add an attribute to a product" ACL, as it was unable in the PIM.
=> PIM-9017: Remove "Add an attribute to a product" ACL

src/Akeneo/Platform/Bundle/UIBundle/Resources/config/services.yml
Deactivate the injection of Content Security Policy.
We need to rework the way we implement CSP and I deactivate it in the meantime.
=> PIM-8950: Deactivate CSP before reworking it

CHANGELOG-2.3.md, src/Pim/Bundle/CatalogBundle/Entity/AssociationType.php, src/Pim/Bundle/CatalogBundle/Entity/AttributeGroup.php, src/Pim/Bundle/CatalogBundle/Entity/Category.php, src/Pim/Bundle/CatalogBundle/Entity/Channel.php, src/Pim/Bundle/CatalogBundle/Entity/Family.php, src/Pim/Bundle/CatalogBundle/Entity/Group.php, src/Pim/Bundle/CatalogBundle/Entity/GroupType.php, src/Pim/Component/Catalog/Model/AbstractAttribute.php, src/Pim/Component/Catalog/Model/FamilyVariant.php
The comparison was not strict in the method that returns an attribute translation from a code. And because of that, if an attribute was updated using an array like `{"labels":["a_string"]}` instead of the standard format `{"labels":{"en_US": "a_string"}}` , the comparison always returned true because the locale code was 0 (instead of "en_US" for example), and in PHP `"en_US" == 0` is true. So the first locale was always updated because the script stopped after the first loop iteration.
After this fix, the API attribute patch method returns a 422 error with this type of request (`{"labels":["a_string"]}`), like every other API request of the PIM, instead of updating the label of the first locale of the PIM. 
**Definition Of Done (for …
=> PIM-6427: Wrong label update on attribute through the API

CHANGELOG-3.0.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/lib/jquery.jstree.less
This PR fixes the broken style on read-only categories, a specific template (with its specific CSS) was already used.
Before/After:
=> PIM-9011: Fix display issue on read-only categories

CHANGELOG-3.2.md, src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/validators.en_US.yml, src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/validators.fr_FR.yml
This PR adds the missing translation key for the Attribute group code validation message.
=> PIM-9020: Add missing attribute group code validation message translation key

config/services/test/test_services.yml, src/Akeneo/Tool/Bundle/ElasticsearchBundle/tests/integration/BulkIndexationIntegration.php, tests/back/Integration/IntegrationTestsBundle/Loader/FixturesLoader.php, tests/back/Pim/Enrichment/Integration/Elasticsearch/IndexConfiguration/AbstractPimCatalogProductModel.php
**Mysql dump optimization** 
It load the dumps through the connection instead of the mysql utility (a needed step if we want to wrap it in a transcation in the future).
I did some optimization of the dump also.
**Elasticsearch optimization**
We delete the documents (in one request) instead of resetting the indexes. In EE, we have 5 indexes. It can between 50 ms to 200 ms to reset an index. It's much faster to do it this way.
The only problem is the dynamic mapping. If a field (for example `image-media` in the PR` is of type "scalar" in a test and an object in another test, it will fail. This kind of coupling between the test worths the performance gain.
In EE: 
- before 19 min
- after 15 min
In CE:
- before 8m40
- after 7min40
Randomly, I looked at some tests: some test that last 1s30 …
=> Optimize loading of mysql dump and deletion of documents in ES for phpunit tests

config/packages/liip_imagine.yml
We add liip imagine configuration for Asset Manager PDF thumbnail & preview.
=> AST-152: Add liip imagine config for pdf on filesystem

src/Akeneo/Apps/back/Infrastructure/Symfony/Resources/public/js/dependencies.ts, src/Akeneo/Apps/front/src/application/shared/date-formatter/use-date-formatter.ts, src/Akeneo/Apps/front/src/application/shared/user/index.ts, src/Akeneo/Apps/front/src/application/shared/user/user-context.ts, src/Akeneo/Apps/front/src/application/shared/user/user.interface.ts, src/Akeneo/Apps/front/src/infrastructure/with-contexts.tsx
```
export const Dashboard = withContexts(() => {
const anyDate = '2004-12-02T22:00';
const formatDate = useDateFormatter();
const toto = formatDate(anyDate, {weekday: 'long', month: 'short', day: 'numeric'});
return (
<div>{toto}</div>
);
});
```
Displays the date: "Thursday, Dec 2" in terms of the user catalog locale.
| …
=> API-901: Add user context and date formatter to front

src/Akeneo/Platform/Bundle/UIBundle/EventListener/ScriptNonceGenerator.php, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/services.yml, tests/back/Platform/Specification/Bundle/UIBundle/EventListener/ScriptNonceGeneratorSpec.php
The PR to re-re-re-re-implement Content Security Policy.
**Previously on PIM Content Security Policy, season 4**
*To put a strong defense against the evil forces of XSS, the PIM team implemented the ultimate CSP weapon (similar to the Doom's BFG) in order to eradicate these little gremlins in one shot.*
But our heroes faced multiple obstacles in this fierce battle: they had to generate a incredibly complicated nonce (well... a UUID) to protect all our precious (but dirty) inline JS from the evil XSS forces and inject this antidote in every response before releasing it in the wild world
This was without counting on the forces of AJAX horde, firing request in every direction at every moment. The nonce was re-generated too many times and the great CSP weapon was completely screwed.
To regain …
=> PIM-8950: Use BAPID cookie to generate JS nonce

CHANGELOG-3.2.md, src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/select2-choice-filter.js
This PR fixes the Select2 input displaying when selecting an empty/not empty operator on a filter.
Before:
After:
=> PIM-9021: Fix input displaying when selecting empty/not empty filter

CHANGELOG-3.0.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/user/login-details.js, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/form/user/login-details.html, src/Akeneo/UserManagement/Bundle/Resources/config/form_extensions/edit.yml, src/Akeneo/UserManagement/Bundle/Resources/translations/jsmessages.en_US.yml, src/Akeneo/UserManagement/Component/Normalizer/UserNormalizer.php, tests/back/UserManagement/Specification/Component/Normalizer/UserNormalizerSpec.php
Since `v3.0`, user login details (created date, updated date, last login date and login count) were removed from the user profile page.
This PR adds them back using a simple backbone form and using the same style as in `v2.3`. …
=> PIM-9023: Add login details on user profile page

src/Akeneo/UserManagement/Bundle/Resources/config/datagrid/user-relation.yml, src/Akeneo/UserManagement/Bundle/Resources/config/datagrid/user.yml, tests/legacy/features/Context/DataGridContext.php, tests/legacy/features/Context/FixturesContext.php, tests/legacy/features/user-management/user/browse_users.feature
Hide API user from the user grids
=> API-837: Hide API users in the user grids of the PIM

src/Akeneo/Platform/Bundle/UIBundle/EventListener/AddContentSecurityPolicyListener.php
Add a CSP rules to allow youtube embedded as explained in: https://developers.google.com/web/fundamentals/security/csp (look for youtube.com)
=> AST-182: Add CSP rules to allow youtube embedded

CHANGELOG-3.0.md, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/serializers_versioning.yml, src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/DateValueFactory.php, src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Versioning/Product/DateTimeNormalizer.php, src/Akeneo/Tool/Bundle/VersioningBundle/tests/integration/Manager/VersionManagerIntegration.php, src/Akeneo/Tool/Bundle/VersioningBundle/tests/integration/Normalizer/Flat/ProductIntegration.php, tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/Versioning/Product/DateTimeNormalizerSpec.php
Date attributes values are stored in UTC format for the product raw_values.
Versioning was only storing `Y-m-d` dates and we could have a difference between history and the actual value of the attribute because of a difference timezone.
By storing dates versions in UTC format, we ensure to have the same value in history and current value. …
=> PIM-9030: Fix date formatting for non UTC values

CHANGELOG-2.3.md, composer.json, composer.lock
The Prophecy 1.10 release made last night introduced a bug and our tests can't pass.
This PR fixes the version at 1.9.* . We may revert it once Prophecy will be fixed.
=> Composer update to fix Prophecy version to 1.9.*

composer.json, composer.lock
The new release of `phpspec/prophecy` (1.10.0) is breaking tests on EE, so we lock to the previous version.
=> Lock phpspec/prophecy to 1.9

CHANGELOG-3.2.md, src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductGrid/ProductModelImagesFromCodes.php
In the fixed request, if `a_image.code` is numerical (ex: 001), it raises a MySQL error 
`Invalid JSON path expression. The error is around character position 5.`
It is because of the following request
```
SELECT JSON_EXTRACT(
raw_values,
'$.001."<all_channels>"."<all_locales>"'
)
FROM pim_catalog_product_model
where id=2;
```
It failed with the same error
If I replace 001 by "001", it will be executed without problems.
=> PIM-9028: Fix error on JSON_EXTRACT where a_image.code is numerical

config/packages/liip_imagine.yml
We are doing this to better support the "Other" preview without losing quality in rendering the rest of the media types.
=> AST-197: Generate jpg tumbnails instead of pngs for asset manager

composer.json, composer.lock, upgrades/schema/Version_4_0_20191223132437_data_quality_insights_add_dynamic_template.php, upgrades/test_schema/Version_4_0_20191223132437_data_quality_insights_add_dynamic_template_Integration.php
- Add Elasticsearch dynamic template migration script + migration integration test
- Upgrade elasticsearch php client to latest version which fix a bug i've encountered
`-`: …
=> Add elasticsearch migration script and integration test

CHANGELOG-3.2.md, src/Akeneo/Tool/Component/Connector/LogArchiver.php
The logs were not stored through JobArchiver, so logs cannot be downloaded.
=> PIM-9043: Archive every jobs in flysystem

CHANGELOG-3.0.md, src/Akeneo/Pim/Structure/Bundle/Controller/InternalApi/FamilyController.php
The mass edit action "Add to existing product model" is quite slow with a huge set of families.
The query is OK (very quick and not optimizable), but the normalization is still complex (it normalize all the family, attributes, requirements, etc).
It exists an option in the normalizer to only return code and labels, this PR use it.
With icecat, the previous query was 250ms ~, now it's 60ms ~.
=> PIM-9041: Fix performance issue on "Add to existing product model" mass action

CHANGELOG-2.3.md, src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filter/select-filter.js, src/Pim/Bundle/UIBundle/Resources/public/less/components/grid/FilterBox.less
It glitched a lot before, because the text was way too long.
Now:
=> PIM-7699: Fix multi-select filter design with a lot of filtered items

config/packages/liip_imagine.yml, src/Akeneo/Connectivity/Connection/front/src/audit/components/ConnectionSelect.tsx
=> API-917: Add liip_imagine filter for dropdown picture

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/attributes.js, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/column-tabs-navigation.js
Trigger dedicated events before and after the rendering of the Attributes Tab on the PEF.
=> DAPI - Add events on before and after the rendering of the PEF

src/Akeneo/Connectivity/Connection/back/Infrastructure/User/Internal/CreateUser.php, src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/User/Internal/CreateUserSpec.php, src/Akeneo/UserManagement/Component/Model/User.php, tests/back/Platform/Integration/CatalogVolumeMonitoring/Persistence/Query/CountUsersIntegration.php, tests/back/UserManagement/Specification/Component/Model/UserSpec.php
Rename :
- defineAsUserApp() to defineAsUserApi
- isAUserApp() to isUserApi()
- TYPE_APP to TYPE_API
=> API-926: Rename defineAsUserApp() and isAUserApp()

Makefile, composer.lock
**What happened on one of my CI builds**
- vendor is not checkout from the cache
- `composer.json` is more recent than `composer.lock`
- so, the makefile executes a `composer update`
- `composer.lock` is modified due to this update...
- it saves the cache with with the hash from the modified `composer.lock`
- the CI is run with dependencies that are not coming from the `composer.lock` of the PR...
If I re-run the build, the cache is still not warmep up, as the cache key is the hash of the `composer.lock` after update.
**Why the `composer.json` is more recent than the `composer.lock`?**
Because of a PR to rename namespace about `App`. The `composer.json` was modified but not the `composer.lock`. This is normal as it was modification about namespaces for the autoloading. 
The good way to …
=> Remove composer update from makefile and ensure sync between composer json and composer.lock

CHANGELOG-3.0.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/TitleContainer.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/AssetCollectionField.less
When the image was too small, the preview was incorrectly displayed.
=> PIM-9051: Avoid cropping on assets preview

CHANGELOG-2.3.md, src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/attribute.yml
There is an extension in EE where filters are dynamically removed on some criteria.
This `removeFiltersNotUsableInGrid` will prevent the attribute datagrid to be affected.
=> PIM-7971: Fix filters being incorrectly disabled in the attributes grid

upgrades/schema/Version_4_0_20191031124707_update_from_clients_to_apps.php
The migration cannot be executed because a wrong namespace is used `Connection` instead of `DbalConnection` in the rollback section. I deleted the rollback section, as we don't handle it in the PIM.
Note: and if you had to do a rollback in a other application, please use a transaction to wrap everything, it's one of purpose of a transaction and it avoids a lot of boilerplate code.
| Review and 2 …
=> API-720: fix amigration using a wrong namespace by removing rollback

CHANGELOG-4.0.md, src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ElasticsearchProjection/GetElasticsearchProductModelProjection.php
**Context**
When creating the ES projection of a product model, we need to know if all products are complete or incomplete for each channel.
**Problem description**
On a server with 800 000 products of the reference catalog, including variant products, the ES indexation was VERY slow (1000 products every 2/3 minutes). Even with ORM it was way faster.
The part of the query which is very slow is this the query to get the completeness of children products:
```
SELECT
product_model.code AS product_model_code,
completeness.locale_id,
completeness.channel_id,
SUM(completeness.missing_count) = 0 AS all_complete,
MIN(completeness.missing_count) <> 0 AS all_incomplete
FROM pim_catalog_product_model product_model
INNER JOIN pim_catalog_product product ON product.product_model_id = product_model.id …
```
=> TIP-1174 improve performance of the SQL query to get completeness of the products

CHANGELOG-3.2.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/label.js, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/product-label.js
1) The product label in the PEF was listening to the scope change, not the locale change for re-rendering.
2) The legacy label collection in the product meta is not scopable, only localizable. For retrieving the valid label, I load the asset family for retrieving attribute_as_label.
| Tech …
=> PIM-9053: Update product label when locale is changed

CHANGELOG-3.2.md, src/Akeneo/Pim/Structure/Bundle/Resources/config/validation/attribute.yml
As you can see in [AttributeOption.orm.yml#L19](https://github.com/akeneo/pim-community-dev/blob/3.2/src/Akeneo/Pim/Structure/Bundle/Resources/config/model/doctrine/AttributeOption.orm.yml#L19), an AttributeOption code has a column length of 100.
The validation constraint was 255 characters. …
=> PIM-9054: Fix the constraint on AttributeOption:code max length

src/Akeneo/Pim/Structure/Component/AttributeTypes.php
This PR adds legacy PAM class needed to run the migration, we'll need to remote it later.
=> Add legacy PAM asset collection attribute type

upgrades/schema/Version_4_0_20190801083247_remove_indexes.php, upgrades/schema/Version_4_0_20190916122239_remove_product_empty_raw_values.php, upgrades/schema/Version_4_0_20190917080512_remove_product_model_empty_raw_values.php, upgrades/schema/Version_4_0_20191004145507_remove_compute_model_descendant_jobs.php, upgrades/schema/Version_4_0_20191031124707_update_from_clients_to_apps.php, upgrades/test_schema/ExecuteMigrationTrait.php, upgrades/test_schema/Version_4_0_20191004145507_remove_compute_model_descendant_jobs_Integration.php
The goal of this migration is to delete the compute product model descendant job. Before doing that, we need to get all pending jobs to index product models.
We were using a search after after (key set pagination):
1. It cannot work as it is designed to search after a specific id. It means you have to fetch the whole product model table to apply the search after.
2. It cannot work as it does not filter on jobs that are pending (consumer is NULL in the queue). It filters on all jobs... 
So, it was taking too much time to be executed.
I tested the query on 800 000 jobs and it's pretty fast (4 seconds). It returns 120 000 product model codes (thanks to the DISTINCT), which is ok in term of memory. So, no need to have a search after …
=> Fix migration job execution

CHANGELOG-3.2.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/mass-edit/form.html
At the 'confirm' step of a product mass action, the 'Previous' button used to redirect at the bulk action selection step, instead of the configuration step
=> PIM-9022: Fix behaviour of the 'Previous' button in product bulk actions modal

.circleci/config.yml, Makefile, package.json, yarn.lock
They are a lot of thing we can do to improve the test speed, but we will force to build the PIM at first. So it's important to optimize the most we can this step. Afte this PR, we can't do much better without reworking docker images or inspecting the node dependencies and puppeter.
It takes 4 min to do this first step.
- Move `make javacript-test` only where it's needed (40 seconds gain)
- Pull docker images in a dedicated step (for clarity)
- Start docker in first step, then build front, to avoid to wait 30 seconds the Mysql+ Elaticsearch to be up (30 seconds gain)
- Do not force lodash dependency (gain 200 Mo on 860 in node_modules :tada: )
| …
=> Improve build time of the front

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/saver/base-saver.js
Set Content-Type on the AJAX requests to match the payload which is hardcoded to JSON.
This seems to fix the issue #11374 
=> Set content-type on save

CHANGELOG-3.0.md, src/Akeneo/Channel/Bundle/Controller/UI/CurrencyController.php, src/Akeneo/Channel/Bundle/Resources/config/datagrid/currency.yml, src/Akeneo/Channel/Bundle/Resources/translations/jsmessages.en_US.yml
The goal, here, is to:
- add a success flash message when you toggle a currency that isn't used in your Channel configuration.
- add an error flash message when you want to deactivate a currency that is used in your Channel configuration.
| Tech Doc …
=> PIM-8163 Show messages when toggle currency

Dockerfile.base
As PAPO uses a SSH connection to get the enterprise version, composer needs to be able to do SSH connection from the CLI.
=> Papo requirements

CHANGELOG-3.2.md, src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/ApplyProductSearchQueryParametersToPQB.php, src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/Validator/ValidateProperties.php, tests/back/Pim/Enrichment/Specification/Component/Product/Connector/UseCase/Validator/ValidatePropertiesSpec.php
=> PIM-9058: Fix search products API with filters on numeric attribute codes

tests/legacy/features/pim/enrichment/product/mass-edit/mass_add_to_existing_product_model.feature
Attempt to fix unstable legacy behats which often fail o the EE CI builds. I noticed that most of the other tests implying product bulk actions used the `I am on the products grid` step, which slightly differs from `I am on the products page`.
I ran an EE build (https://circleci.com/workflow-run/9db65ac7-b4fd-46f7-b21f-286b0322ed26) and it passes. This means nothing as the fails are random, but I think it can't hurt to try, we'll see in the next builds if the fix works. …
=> Attempt to fx unstable legacy behats

src/Akeneo/Connectivity/Connection/back/Infrastructure/InternalApi/Controller/AuditController.php, src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Audit/CountDailyEventsByConnectionEndToEnd.php, src/Akeneo/Connectivity/Connection/back/tests/Integration/Fixtures/AuditLoader.php
Add e2e on fetch Audit events
I had to add the end_date as http query parameter to be able to do those tests.
=> API-946: Add e2e on fetch Audit events

CHANGELOG-3.0.md, src/Akeneo/Pim/Structure/Component/Updater/AttributeUpdater.php, tests/back/Pim/Structure/Specification/Component/Updater/AttributeUpdaterSpec.php
Fix update of 'unique' property in attribute updater when updating both unique and type properties
In AttributeUpdater, when updating first the 'unique' property then the 'type' property (this can happen with imports), the 'unique' value is overridden by the attribute type's default `isUnique()` value.
This PR fixes that:
- if the attribute type must be unique (`AttributeType::isUnique()` is true, e.g identifier attribute type), then the attribute's `unique` property is forced to `true`
- else if the attribute's `unique` property is not set (attribute creation), the `unique` property is initialized with the attribute type's default value
- else we do not update the `unique` property
| …
=> PIM-6160: Fix update of 'unique' property in attribute updater

CHANGELOG-3.2.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/attribute-group/tab/attribute.html, src/Akeneo/UserManagement/Bundle/Resources/public/js/fields/category-tree.ts, src/Akeneo/UserManagement/Bundle/Resources/public/js/fields/channel.ts
Fix catalog locale on: 
1. the user edit page > Additional tab (Catalog scope / Default tree)
2. settings > attribute groups > open one > tab "attributes"
=> PIM-9059: Fix catalog locale - user panel + attribute groups attributes

src/Akeneo/Pim/Enrichment/Component/Product/Completeness/MaskItemGenerator/DefaultMaskItemGenerator.php
In the migration scripts, we have something that removes the job "compute product model descendants". In case, when you migrate, you have some instances of this job in the queue, we need to recalculate the completeness of products. Today it does not work in case you have PAM assets.
This PR fixes it.
=> TIP-1367: make the completeness calculation work with legacy assets

CHANGELOG-3.0.md, src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Standard/Product/ProductValueNormalizer.php, src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Versioning/Product/ValueNormalizer.php, src/Akeneo/Tool/Component/Localization/Localizer/NumberLocalizer.php, src/Akeneo/Tool/Component/Localization/Presenter/NumberPresenter.php, tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/CreateProductEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/GetProductEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/CreateProductModelEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/PartialUpdateListProductModelEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/PartialUpdateProductModelEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/ExternalApi/CreateVariantProductEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/ExternalApi/PartialUpdateListVariantProductEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/ExternalApi/PartialUpdateProductToVariantEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/ExternalApi/PartialUpdateVariantProductEndToEnd.php, tests/back/Pim/Enrichment/Integration/Doctrine/Common/Saver/ProductSaverIntegration.php, tests/back/Pim/Enrichment/Integration/Normalizer/Standard/ProductStandardIntegration.php, tests/back/Pim/Enrichment/Integration/Product/LoadEntityWithValuesSubscriberIntegration.php, tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/InternalApi/ProductModelNormalizerSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/InternalApi/ProductNormalizerSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/Standard/Product/ProductValueNormalizerSpec.php, tests/legacy/features/pim/enrichment/product/export/export_products_with_localized_decimal.feature
This PR changes the max fraction digits from 4 to 10, in the Number localizer & presenter and in the Product value normalizer, in order to be able to save values like `0.123456789` in a number type attribute. …
=> PIM-9065: Change the number decimal precision to 10

Dockerfile.base
Cannot be run on the CI, i have to merge it with admin rights.
See #11482
=> Re-activate php7.3-gd extension in Docker image

src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml, src/Akeneo/Connectivity/Connection/front/src/audit/pages/AuditErrorBoundary.tsx, src/Akeneo/Connectivity/Connection/front/src/audit/pages/Index.tsx, src/Akeneo/Connectivity/Connection/front/src/common/components/RuntimeError.tsx, src/Akeneo/Connectivity/Connection/front/src/common/components/index.ts, src/Akeneo/Connectivity/Connection/front/src/settings/pages/Index.tsx, src/Akeneo/Connectivity/Connection/front/src/settings/pages/SettingsErrorBoundary.tsx, src/Akeneo/Connectivity/Connection/front/tests/unit/common/__snapshots__/PageHeader.spec.tsx.snap, src/Akeneo/Connectivity/Connection/front/tests/unit/common/__snapshots__/Section.spec.tsx.snap, src/Akeneo/Connectivity/Connection/front/tests/unit/settings/components/__snapshots__/ConnectionGrid.spec.tsx.snap, src/Akeneo/Connectivity/Connection/front/tests/unit/settings/components/__snapshots__/NoConnection.spec.tsx.snap
=> API-936: Add React error boundaries

config/packages/liip_imagine.yml
Fixes the thumbnail background being black when media link is empty.
Before: 
After:
=> AST-381: Fix media link preview black background

CHANGELOG-3.2.md, src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Field/AncestorCodeFilter.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/query_builders.yml, src/Oro/Bundle/PimDataGridBundle/Extension/MassAction/MassActionDispatcher.php, src/Oro/Bundle/PimDataGridBundle/spec/Extension/MassAction/MassActionDispatcherSpec.php
On product grid when we filter on parent code and we select all rows, the variant product are not taken in account in bulk action.  
This is because we filter on a root product model and the parent of the variant products is the sub product model, not the root. So the products are not retrieved by the query.  
The selected solution is to use `ancestors.codes` (that contains all the parents) instead of `parent`.  
This will fix:
- number of products that are concerned by the bulk action bfore launch the job
- product fetching during the job
**Before**
No product number displayed  
**After**
| Added Specs …
=> PIM-9067: fix product filter on mass edit action

docker-compose.yml
Selenium container port can be configured with `DOCKER_PORT_HTTP` env. The problem is this env is also used to configure the http container.  
So if we set a `DOCKER_PORT_HTTP` we cannot up the containers because of a conflict between selenium and http port
=> Fix selenium public port

CHANGELOG-3.2.md, src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/translations/jsmessages.en_US.yml
**Description (for Contributor and Core Developer)** 
When running the rules job "calculate affected products", the job showed the key "pim_import_export.widget.last_operations.job_type.mass_edit_rule".
The goal, here, was to had a translation for the key "mass_edit_rule".
`Todo`: …
=> PIM-9075: Fix mass_edit_rule key translation

behat.yml, tests/legacy/features/pim/enrichment/product/validation/remove_validation_error_on_correction.feature
Fix some unstable:
(tests/legacy/features/pim/enrichment/product/datagrid/datagrid_views.feature:50)
https://github.com/akeneo/pim-community-dev/issues/11481
The method to assert that a text is in the page take  A LOT of time. So when it's spinning, it can reach the timeout that I reduced to 20 sec.
I reduced it because a lot of time we wait something does not happen during the time of the timeout (a text does not appear, during 20 seconds for example).
Let's try with 25...
| Added …
=> Stabilize behat again

CHANGELOG-3.2.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/menu/resizable.js
Fix the jQuery.resizable handle overlapping on the page title while scrolling on the page
=> PIM-9080: Fix overlapping jQuery.resizable handle

CHANGELOG-3.0.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/assets.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/Grid.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/pages/AttributeOptions.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/attribute-option/edit.html, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/attribute-option/index.html, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/attribute-option/show.html
=> PIM-8952: Freeze headers of the attribute options tab

tests/back/Pim/Enrichment/EndToEnd/Product/Product/InternalApi/DownloadProductPdfEndToEnd.php
Fix an issue on EE where the route/URL has `permissions` appended to it, so the test doesn't work if we hard-code the URI
=> PIM-9081: Fix Download PDF e2e

.circleci/detect_structure_changes.sh
Ignore the PIM version when comparing database migrations, same as https://github.com/akeneo/pim-community-dev/commit/52256711702ebbf9813413e7a67b03d5492b450c
=> Remove version from the index names when checking if missing migration

src/Akeneo/Platform/Bundle/AnalyticsBundle/Resources/views/Update/last_patch.html.twig
On the dashboard we display if a new version is available. To know that we do a request on this url for PIM in 4.0: https://updates.akeneo.com/CE-4.0.json  
The problem was we had "New patch available:" for a while (we should have "New patch available: 4.0.3" for example).  
It's not reproductible today, unless we simulate a PIM v5: the request becomes  https://updates.akeneo.com/CE-5.0.json (404 response) and the mention  "New patch available:" is displayed.  
To fix that, we hide the "New patch available:" by default and dispay it only if request succeeds
=> PIM-9082: remove last release sentence when info not available

CHANGELOG-3.2.md, src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Field/CategoryFilter.php, tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Filter/Field/CategoryFilterSpec.php
The execution of the rules failed with a PHP error when a category was not found (specially when we wanted to have the children of a category with the "IN CHILDREN" operator). No message was displayed to the user.  
For family filter, we always check the existence of the families. This PR does the same for categories. A propper exception is thrown when a category does not exist and a message is now displayed: …
=> PIM-9089: add exception when category is unknown in ES queries

CHANGELOG-3.2.md, src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/ComputeDataRelatedToFamilyProductsTasklet.php, tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Job/ComputeDataRelatedToFamilyProductsTaskletSpec.php
Fix https://akeneo.atlassian.net/browse/PIM-9095  
When no product is valid, the entity manager was never cleared.  
=> PIM-9095: fix memory leak during family import

CHANGELOG-3.2.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/edit-form.js, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/attributes.js, tests/legacy/features/pim/structure/family/remove_attribute_from_a_family.feature
This pull request aims to keep the vertical scroll position of the edit forms after saving modifications.
=> PIM-9098: Regression: Product Form / Attribute. The display-position move after clicking SAVE-button

src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml
Missing translation for the confirmation popup
=> Fix missing translation for family variant deletion

CHANGELOG.md, src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Completeness/SqlSaveProductCompletenesses.php
When loading with a parallelism of 7 threads to import products, Mysql dead lock issues can occur. As we don't handle it in our code (it triggers an uncatched exception), it's an error 500 returned by the API.
Do note that:
In any application, we can have deadlock: this is just a matter of probability. 
The bigger are you transaction, the bigger is your probability to have a dead lock.
The more you have concurrent transactions,  the bigger is your probability to have a dead lock.
Here, it happens when we DELETE then INSERT the rows for the completeness, because we batched things.
What _probably_  happens is:
```
TRANSACTION 1
DELETE FROM pim_catalog_completeness WHERE product_id IN ('1', '2', '3')
```
Exclusive locks on product_id 1 and 2.
```
TRANSACTION 2
INSERT INTO …
```
=> PIM-9110: avoid deadlock error when loading products in parallel with the API

CHANGELOG-3.2.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/jstree/jquery.jstree.tree_selector.js
The state of the Settings / Category form is managed in the legacy `pim/formupdatelistener` (which itself is called in a twig macro :roll_eyes: ). 
The form uses a custom jQuery.jstree plugin (tree_selector), which allows to choose the category tree in a select2. Problem is, when this select2 is updated, `pim/formupdatelistener` will consider that the form was updated, thus displaying a 'unsaved changes' message.
My solution is to add the `exclude` class to the tree selector, so it will not be taken into account by the listener, as per these lines: https://github.com/akeneo/pim-community-dev/blob/299dac85b55a68adaf8ab18568c04d2bad67e5e3/src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/pim-formupdatelistener.js#L20...L25
| Q …
=> PIM-9108: Fix wrong message appearing when switching category tree

CHANGELOG-4.0.md, std-build/Kernel.php
Fixes #11583
> the braces could be removed altogether, as they only list one variant. "/{packages}/" is equivalent to "/packages/" as there is only the variant "packages". It would be a different story if it was "/{packages,}/" (notice the empty variant) or "/{packages,routes}/".
=> #11583: Remove useless GLOB_BRACE flag from standard Kernel

src/Akeneo/Pim/Enrichment/Bundle/DependencyInjection/AkeneoPimEnrichmentExtension.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/connector/archivers.yml, src/Akeneo/Tool/Bundle/ConnectorBundle/Resources/config/archiving.yml
Those archivers rely on the services `pim_connector.job.job_parameters.default_values_provider.product_csv_export` and `pim_connector.job.job_parameters.default_values_provider.product_xlsx_export` that are defined in PimEnrichmentBundle.
It's a good thing that they are defined in PimEnrichmentBundle imo (as the AkeneoConnectorBundle should have no knowledge about products, attributes etc...), they should just be renamed (which I will not do in this PR).
=> Move services definitions to Enrichment

CHANGELOG-3.2.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/variant-navigation.js
How to reproduce:
- create a new channel with only one locale (eg: fr_FR)
- open a product model PEF
- switch to a channel with several locales
- switch to a locale not used in the new channel (eg: en_US)
- open the variant list (everything is ok)
- switch to the new channel (selected locale is still en_US)
- open the variant list 
There is a fatal js error in the dropdown because the dropdown tries to retrieve the completeness using the selected locale, see https://github.com/akeneo/pim-community-dev/blob/f2be06998b7477eccead072a6d016d774a9f52ef/src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/variant-navigation.js#L343
But this locale does not exists in this channel.
The proposed fix is to simply check if the …
=> PIM-9111: Fix the variant list when the channel does not support the selected locale

CHANGELOG.md, src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
How to reproduce in the datagrid:
- Set the Family filter to `Clothing`
- Set the Parent filter to `is empty`
- Select all products (they are only products model in that case)
- Start a mass edit on an attribute
Then, the query run in backend only count `Product` but all Products are excluded by the Parent filter. It returns `0`.
The job will still run properly.
The UI is broken because it didn't support the case where itemsCount is `0`, making all the labels empty.
The proposed fix is to handle the `0` case where we returns generic labels without the count in it.
Since this translation already exists, **this PR only fix it for `en_US`.**
| …
=> PIM-9119: Fix missing translation when itemsCount is 0 for mass edit

src/Akeneo/Tool/Bundle/MeasureBundle/Application/SaveMeasurementFamily/SaveMeasurementFamilyCommand.php, src/Akeneo/Tool/Bundle/MeasureBundle/Application/SaveMeasurementFamily/SaveMeasurementFamilyHandler.php, src/Akeneo/Tool/Bundle/MeasureBundle/Persistence/MeasurementFamilyRepository.php, src/Akeneo/Tool/Bundle/MeasureBundle/Persistence/MeasurementFamilyRepositoryInterface.php, src/Akeneo/Tool/Bundle/MeasureBundle/spec/Application/SaveMeasurementFamily/SaveMeasurementFamilyHandlerSpec.php, src/Akeneo/Tool/Bundle/MeasureBundle/tests/Integration/Persistence/MeasurementFamilyRepositoryIntegration.php, tests/back/Acceptance/MeasurementFamily/InMemoryMeasurementFamilyRepository.php
This PR:
- Adds a save method in `MeasurementFamilyRepository` which updates an existing family and creates it if it doesn't exist already
- Adds a `SaveMeasurementFamilyCommand` & `SaveMeasurementFamilyHandler`
`OK`: …
=> MET-48: Add create/update service to update measurements

akeneo-design-system/extend-jest.d.ts, akeneo-design-system/src/components/Buttons/CoreButton/CoreButton.test.tsx, akeneo-design-system/src/components/Buttons/PrimaryButton/PrimaryButton.test.tsx, akeneo-design-system/tsconfig.json
Adding some styled components / css oriented tests.
The jest-styled-components encounters some typescript [issues](https://github.com/styled-components/jest-styled-components/issues/264).
A file extend-jest.d.ts has been added to extend properly the jest types, with a new function "toHaveStyleRule".
Doc about jest-styled-components is [here](https://github.com/styled-components/jest-styled-components).
Also for now I encounter a problem with the setupTests.ts file to avoid importing "import 'jest-styled-components';" in all tests file. It will be fixed in an another pr. …
=> [akeneo-design-system]: Add styled components tests

src/Akeneo/Pim/Enrichment/.php_cd.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml, src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Completeness/SqlSaveProductCompletenesses.php
When loading data with the API with 30 threads, we had some deadlocks despite the retry strategy, during insertion of completeness.
We tried a lot of things to mitigate this risk of deadlock during insertion of the completeness:
- increasing the `sleep` drastically at each retry  (:red_circle: )
- increasing the number of retry drastically (20)  (worked with 10 thread, ? with 30 threads)
- to delete only unwanted row + INSERT (:red_circle: )
- SELECT id from rows and then only DELETE by id to know if it changes the locking strategy  (:red_circle: )
- DELETE index `locale_id` and `channel_id` in case of locking  (:red_circle: )
- use INSERT ON DUPLICATE KEY UPDATE (:heavy_check_mark: with 10 threads, :red_circle: with 30)
- use two …
=> PIM-9110: lock tables to insert completeness if we still have deadlocks after 5 attempts

CHANGELOG.md, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/doctrine/Product/ProductModel.orm.yml, src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductGrid/ProductModelImagesFromCodes.php, src/Akeneo/Pim/Enrichment/Component/Product/Model/ProductModel.php, src/Akeneo/Pim/Enrichment/Component/Product/Model/ProductModelInterface.php, src/Akeneo/Pim/Enrichment/Component/Product/ProductModel/ImageAsLabel.php, tests/back/Pim/Enrichment/Specification/Component/Product/ProductModel/ImageAsLabelSpec.php, upgrades/schema/Version_5_0_20200304140000_remove_nested_set_columns_product_model.php, upgrades/test_schema/Version_4_0_20200117080512_remove_product_model_empty_raw_values_Integration.php, upgrades/test_schema/Version_4_0_20200117145507_remove_compute_model_descendant_jobs_Integration.php
Fix performance issues when deleting product model and also deadlock when inserting product model with parallelism through the PAI
We have two issues:
- performance problem when deleting a product model (and I suppose when inserting product models also...). An index is missing on `left` `right` `root`.
- deadlock when inserting product model
All of this is due to the nested set pattern we introduced for the product models. It is never used. Let's drop that, this dead code is not really dead code as there are bugs due to that.
| Added legacy Behats               | …
=> Remove nested set pattern in product models

src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Completeness/SqlSaveProductCompletenesses.php
… 
It avoids to lock pim_catalog_product table when locking the completeness table.
=> PIM-9110: deactivate foreign keys check when locking the completeness table

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/field/metric-field.js, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/product/field/metric.html
In the metric field, the metric unit was translated using the catalog locale. It should use the UI locale.
=> MET-62: Use the uiLocale for translating the metric unit

.circleci/config.yml, akeneo-design-system/Makefile
Add a specific job `build_and_test_akeneo-design-system` inside the PIM circleci workflow.
_Why not a separate workflow?_
So that the user/developer doesn't have to trigger a second workflow by hand.
_Why not separate jobs for build and test?_
CI is expensive and our steps are relatively simple for now.
=> Add design system CI configuration for tests

src/Akeneo/Pim/Structure/Bundle/Query/PublicApi/Attribute/Sql/IsThereAtLeastOneAttributeConfiguredWithMeasurementFamily.php, src/Akeneo/Pim/Structure/Bundle/Resources/config/queries.yml, tests/back/Pim/Structure/Integration/Attribute/Query/IsThereAtLeastOneAttributeConfiguredWithMeasurementFamilyIntegration.php
Add query to find measurement families linked to product attributes in Enrichement/Structure public api.
=> MET-64: Add query to find measurement families linked to product attributes

akeneo-design-system/jest.config.js
Jest is launching test from the lib directory => exclude the directory lib
=> [akeneo-design-system]: fix jest config

src/Akeneo/Tool/Bundle/MeasureBundle/Persistence/MeasurementFamilyRepository.php, src/Akeneo/Tool/Bundle/MeasureBundle/Persistence/MeasurementFamilyRepositoryInterface.php, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/config/services.yml, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/config/validation.yml, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/translations/validators.en_US.yml, src/Akeneo/Tool/Bundle/MeasureBundle/Validation/Common/Code.php, src/Akeneo/Tool/Bundle/MeasureBundle/Validation/Common/CodeValidator.php, src/Akeneo/Tool/Bundle/MeasureBundle/Validation/Common/LabelCollection.php, src/Akeneo/Tool/Bundle/MeasureBundle/Validation/Common/LabelCollectionValidator.php, src/Akeneo/Tool/Bundle/MeasureBundle/Validation/MeasurementFamily/Count.php, src/Akeneo/Tool/Bundle/MeasureBundle/Validation/MeasurementFamily/CountValidator.php, src/Akeneo/Tool/Bundle/MeasureBundle/Validation/MeasurementFamily/OperationCount.php, src/Akeneo/Tool/Bundle/MeasureBundle/Validation/MeasurementFamily/OperationCountValidator.php, src/Akeneo/Tool/Bundle/MeasureBundle/Validation/MeasurementFamily/OperationValue.php, src/Akeneo/Tool/Bundle/MeasureBundle/Validation/MeasurementFamily/OperationValueValidator.php, src/Akeneo/Tool/Bundle/MeasureBundle/Validation/MeasurementFamily/StandardUnitCode.php, src/Akeneo/Tool/Bundle/MeasureBundle/Validation/MeasurementFamily/StandardUnitCodeValidator.php, src/Akeneo/Tool/Bundle/MeasureBundle/Validation/MeasurementFamily/UnitCount.php, src/Akeneo/Tool/Bundle/MeasureBundle/Validation/MeasurementFamily/UnitCountValidator.php, src/Akeneo/Tool/Bundle/MeasureBundle/tests/Acceptance/AcceptanceTestCase.php, src/Akeneo/Tool/Bundle/MeasureBundle/tests/Acceptance/SaveMeasurementFamilyTest.php, src/Akeneo/Tool/Bundle/MeasureBundle/tests/Integration/Persistence/MeasurementFamilyRepositoryIntegration.php, tests/back/Acceptance/MeasurementFamily/InMemoryMeasurementFamilyRepository.php, tests/back/Acceptance/Resources/config/pim/repositories.yml
The limits are:
- At least one mandatory operation per unit.
- 5 operations max per unit.
- The max number of measurement family is 100.
- The max number of units per measurement family is 50.
This limits are configurable with the following parameters:
```
parameters:
akeneo_measure.validation.measurement_family.operations_max: 5
akeneo_measure.validation.measurement_family.units_max: 50
akeneo_measure.validation.measurement_family.families_max: 100
```
| Added acceptance tests            | yes …
=> MET-58: Add validation for Measurement Families limits

upgrades/schema/Version_5_0_20200309165300_remove_product_foreign_key_pim_catalog_completeness.php
This PR makes the migration script able to guess the database name in order to retrieve the name of the foreign key to drop. 
| Migration script                  | OK
=> PIM-9110: remove completeness fk

src/Akeneo/Tool/Bundle/MeasureBundle/Controller/InternalApi/CreateMeasurementFamilyAction.php, src/Akeneo/Tool/Bundle/MeasureBundle/Controller/InternalApi/JsonSchema/MeasurementFamilyStructureValidator.php, src/Akeneo/Tool/Bundle/MeasureBundle/Controller/InternalApi/JsonSchemaErrorsFormatter.php, src/Akeneo/Tool/Bundle/MeasureBundle/DependencyInjection/AkeneoMeasureExtension.php, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/config/internal_api.yml, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/config/routing.yml, src/Akeneo/Tool/Bundle/MeasureBundle/tests/EndToEnd/InternalApi/CreateMeasurementFamilyEndToEnd.php
New endpoint for the internal API for creating a new MeasurementFamily:
`POST /rest/measurement-families`
| Added integration tests           | yes
=> MET-79: Add InternalApi endpoint for creating measurement families

CHANGELOG-5.0.md, src/Akeneo/Pim/Enrichment/Bundle/Filter/ProductEditDataFilter.php
This PR fixes a regression that can prevent a user from saving a product in a very specific usercase : 
Users `A` and `B` both open the same product page.
A user `A` update an attribute `A1` of an attribute group `Marketing` for example, and save a product. 
The user `B`, who still has the "old" version of the product, doesn't have edit rights on the attribute group `Marketing`, updates another attribute `A2` and try to save the product : there is an error.
This error occurs because the user send ALL the product data to the back when the form is sent, and the back doesn't filter the attributes the user can't edit. So for the backend point of view, the attribute `A1` that the user `A` sent to the back was updated. So in this PR, I now …
=> PIM-9133: Fix product save when the user has no permission on some attribute groups

CHANGELOG-3.0.md, src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/price-filter.js
On version 3.0.68 currency is not set by default on price filter on the datagrid.
Now the first currency is selected by default.
This is a cherry pick from [this](https://github.com/akeneo/pim-community-dev/commit/01a2a71a7943231d1436a6a7486668d6042fcf17#diff-61c9320a11738f809f9d1123c0a05a15) ans [this](https://github.com/akeneo/pim-community-dev/commit/a17ccb59337d833551e4ebac2e5d62ef2b18c3f4#diff-61c9320a11738f809f9d1123c0a05a15) prs.
| Added Specs                       |-
| Changelog …
=> PIM-9135: Currency is not set by default on price filter

CHANGELOG-3.0.md, src/Akeneo/Pim/Enrichment/Component/Product/Connector/Writer/File/Csv/ProductWriter.php, src/Akeneo/Pim/Enrichment/Component/Product/Connector/Writer/File/Xlsx/ProductWriter.php, tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Writer/File/Csv/ProductWriterSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Writer/File/Xlsx/ProductWriterSpec.php
This PR fixes a regression in 3.0 in a very specific use case : if a product export has no data and one or several attributes are used as filters, the expected behavior is to NOT export the headers (so the file should be empty). …
=> PIM-9137: do not export headers if no data to export and attribute used as filters

src/Akeneo/Connectivity/Connection/front/src/audit/components/Charts.tsx, src/Akeneo/Connectivity/Connection/front/src/audit/components/EventChart.tsx, src/Akeneo/Connectivity/Connection/front/src/audit/model/source-connection.ts, src/Akeneo/Connectivity/Connection/front/tests/src/audit/pages/Dashboard.test.tsx, src/Akeneo/Connectivity/Connection/front/tests/src/audit/reducers/dashboard-reducer.test.ts
=> API-1007: Update charts to display only connection with audit enabled

src/Akeneo/Pim/Structure/Bundle/Query/PublicApi/Attribute/Sql/IsThereAtLeastOneAttributeConfiguredWithMeasurementFamily.php, src/Akeneo/Tool/Bundle/MeasureBundle/Application/SaveMeasurementFamily/SaveMeasurementFamilyCommand.php, src/Akeneo/Tool/Bundle/MeasureBundle/Controller/ExternalApi/JsonSchema/MeasurementFamilyValidator.php, src/Akeneo/Tool/Bundle/MeasureBundle/Persistence/MeasurementFamilyRepository.php, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/config/services.yml, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/config/validation.yml, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/translations/validators.en_US.yml, src/Akeneo/Tool/Bundle/MeasureBundle/Validation/MeasurementFamily/CountValidator.php, src/Akeneo/Tool/Bundle/MeasureBundle/Validation/MeasurementFamily/OperationCountValidator.php, src/Akeneo/Tool/Bundle/MeasureBundle/Validation/MeasurementFamily/OperationValue.php, src/Akeneo/Tool/Bundle/MeasureBundle/Validation/MeasurementFamily/StandardUnitCodeShouldExist.php, src/Akeneo/Tool/Bundle/MeasureBundle/Validation/MeasurementFamily/StandardUnitCodeShouldExistValidator.php, src/Akeneo/Tool/Bundle/MeasureBundle/Validation/MeasurementFamily/WhenUsedInAProductAttributeShouldBeAbleToUpdateOnlyLabelsAndSymbolAndAddUnits.php, src/Akeneo/Tool/Bundle/MeasureBundle/Validation/MeasurementFamily/WhenUsedInAProductAttributeShouldBeAbleToUpdateOnlyLabelsAndSymbolAndAddUnitsValidator.php, src/Akeneo/Tool/Bundle/MeasureBundle/tests/Acceptance/SaveMeasurementFamilyTest.php, tests/back/Acceptance/Attribute/InMemoryIsThereAtLeastOneAttributeConfiguredWithMeasurementFamilyStub.php, tests/back/Acceptance/MeasurementFamily/InMemoryMeasurementFamilyRepository.php, tests/back/Acceptance/Resources/config/pim/queries.yml
Add update validation on update of a locked measurement family.
| Added acceptance tests            | Ok
=> MET-64: Add validation to prevent removing units when measurement family is locked

CHANGELOG-4.0.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/product-label.js, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/save.js
When a user saves a product with a label on which he have no view rights, two notifications shows up, a success one (200 from server) and an error.
The error one is trigger by two things :
-[here](https://github.com/akeneo/pim-community-dev/pull/11724/files#diff-e882e90a45781908d099227dfb7f540dR49), values is undefined so the find method crash.
-[here](https://github.com/akeneo/pim-community-dev/pull/11724/files#diff-0c84f61c4586733ded5138a47a03638cL86) the .fail from the ajax api is apply on all the transformation / side effect and not only on the http call.
Also this bug on EE rise some questions.
On the product grid user with no right can see the label
But the label is hidden in the product edit page
It seems that we have a …
=> FIX-PIM-9134: Remove error notif when a user saves a product and they have no view rights on the attribute used as label

CHANGELOG-3.2.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/lib/jquery.multiselect.less
=> PIM-9148: Fix UI attribute group display in association panel

src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/context/notify-context.ts, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/hooks/use-toggle-state.tsx, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/model/measurement-family.ts, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/model/validation-error.ts, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/create-measurement-family/CreateMeasurementFamily.tsx, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/create-measurement-family/form/create-measurement-family-form.ts, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/create-measurement-family/hooks/use-create-measurement-family-saver.ts, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/create-measurement-family/hooks/use-create-measurement-family-state.ts, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/list/List.tsx, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/Flag.tsx, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/FormGroup.tsx, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/InputErrors.tsx, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/Modal.tsx, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/PageContent.tsx, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/ResultCount.tsx, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/SearchBar.tsx, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/Subsection.tsx, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/SubsectionHelper.tsx, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/TextField.tsx, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/icons/CloseIcon.tsx, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/icons/SearchIcon.tsx, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/icons/WarningIcon.tsx, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/illustrations/MeasurementFamilyIllustration.tsx, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/translations/jsmessages.en_US.yml
Unifying coding style by using `export` only once at the end of each module.
Also boy-scout-adding Escape key shortcut to close the Create Measurement Family modal.
=> MET-102: Unify export use

src/Akeneo/Tool/Bundle/MeasureBundle/Application/CreateMeasurementFamily/CreateMeasurementFamilyCommand.php, src/Akeneo/Tool/Bundle/MeasureBundle/Application/CreateMeasurementFamily/CreateMeasurementFamilyHandler.php, src/Akeneo/Tool/Bundle/MeasureBundle/Controller/InternalApi/CreateMeasurementFamilyAction.php, src/Akeneo/Tool/Bundle/MeasureBundle/Model/MeasurementFamilyCode.php, src/Akeneo/Tool/Bundle/MeasureBundle/Model/UnitCode.php, src/Akeneo/Tool/Bundle/MeasureBundle/Persistence/MeasurementFamilyRepositoryInterface.php, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/config/internal_api.yml, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/config/services.yml, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/config/validation.yml, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/translations/validators.en_US.yml, src/Akeneo/Tool/Bundle/MeasureBundle/Validation/Common/CodeValidator.php, src/Akeneo/Tool/Bundle/MeasureBundle/Validation/CreateMeasurementFamily/CodeMustBeUnique.php, src/Akeneo/Tool/Bundle/MeasureBundle/Validation/CreateMeasurementFamily/CodeMustBeUniqueValidator.php, src/Akeneo/Tool/Bundle/MeasureBundle/Validation/CreateMeasurementFamily/Count.php, src/Akeneo/Tool/Bundle/MeasureBundle/Validation/CreateMeasurementFamily/CountValidator.php, src/Akeneo/Tool/Bundle/MeasureBundle/Validation/CreateMeasurementFamily/StandardUnitCodeShouldExist.php, src/Akeneo/Tool/Bundle/MeasureBundle/Validation/CreateMeasurementFamily/StandardUnitCodeShouldExistValidator.php, src/Akeneo/Tool/Bundle/MeasureBundle/tests/EndToEnd/InternalApi/CreateMeasurementFamilyEndToEnd.php, tests/back/Acceptance/MeasurementFamily/InMemoryMeasurementFamilyRepository.php
2 issues fixed:
- The constraints `NotBlank` and `Length(min=1)` on the code are doing the same thing, when the field is empty, 2 validation errors are returned. It was useless.
- the `Create` endpoint should not use the `SaveMeasurementFamilyCommand` because it's an upsert. I added a `CreateMeasurementFamilyCommand` with proper validation and the new `CodeMustBeUnique`. …
=> MET-105: Fix CreateMeasurementFamily validation

src/Akeneo/Tool/Bundle/MeasureBundle/tests/EndToEnd/InternalApi/CreateMeasurementFamilyEndToEnd.php, src/Akeneo/Tool/Bundle/MeasureBundle/tests/EndToEnd/WebTestCase.php
By mistake, I've used `Akeneo\Tool\Bundle\ApiBundle\tests\integration\ApiTestCase` for the End-to-End tests of this internal api endpoint. The tests are good when runned from a CE env but are failing on the auth when runned from EE.
This PR fix it by using the appropriate auth method.
| Tech …
=> MET-116: Fix the EE tests

CHANGELOG-3.0.md, src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/select2-choice-filter.js
Fix the data loading of the product grid select2 choice filter.
Only fetch the selected asset ids:
=> PIM-9146: Fix select2-choice-filter fetch for cached&missing data

src/Akeneo/Tool/Bundle/MeasureBundle/Application/DeleteMeasurementFamily/DeleteMeasurementFamilyCommand.php, src/Akeneo/Tool/Bundle/MeasureBundle/Application/DeleteMeasurementFamily/DeleteMeasurementFamilyHandler.php, src/Akeneo/Tool/Bundle/MeasureBundle/Controller/InternalApi/DeleteMeasurementFamilyAction.php, src/Akeneo/Tool/Bundle/MeasureBundle/Persistence/MeasurementFamilyRepository.php, src/Akeneo/Tool/Bundle/MeasureBundle/Persistence/MeasurementFamilyRepositoryInterface.php, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/config/internal_api.yml, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/config/routing.yml, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/config/services.yml, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/config/validation.yml, src/Akeneo/Tool/Bundle/MeasureBundle/Validation/DeleteMeasurementFamily/ShouldNotBeUsedByProductAttribute.php, src/Akeneo/Tool/Bundle/MeasureBundle/Validation/DeleteMeasurementFamily/ShouldNotBeUsedByProductAttributeValidator.php, src/Akeneo/Tool/Bundle/MeasureBundle/tests/EndToEnd/InternalApi/DeleteMeasurementFamilyEndToEnd.php, src/Akeneo/Tool/Bundle/MeasureBundle/tests/EndToEnd/WebTestCase.php, src/Akeneo/Tool/Bundle/MeasureBundle/tests/Integration/Persistence/MeasurementFamilyRepositoryIntegration.php, tests/back/Acceptance/MeasurementFamily/InMemoryMeasurementFamilyRepository.php
New internal endpoint:
```
DELETE /rest/measurement-families/{code}
```
3 responses possibles:
```
204 - Deleted
404 - Cannot be found
422 - Cannot be deleted
```
=> MET-90: Add DELETE endpoint for measurement families

CHANGELOG-3.0.md, src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/ProductModelController.php, src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Query/SqlGetProductCompletenessRatio.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/controllers.yml, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/normalizers.yml, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml, src/Akeneo/Pim/Enrichment/Component/Product/Completeness/Query/GetProductCompletenessRatio.php, src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/LightEntityWithFamilyVariantNormalizer.php, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/fetcher/product-model-fetcher.js, tests/back/Pim/Enrichment/Integration/Completeness/SqlGetProductCompletenessRatioIntegration.php, tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/InternalApi/LightEntityWithFamilyVariantNormalizerSpec.php, tests/legacy/features/Behat/Decorator/TabElement/ComparisonPanelDecorator.php
When a product model has a large number (several hundreds) of children, the variant navigation dropdown in the product model edit form can be really slow. This is especially true when children are variant products.
For other dropdown components we usually add an infinite scroll in this case, but it proves extremely complicated in this case: 
- the sorting system is quite complex and is performed frontend-side, on already normalized data
- the search is also performed on the frontend (the search is on normalized labels for the axes values). 
=> Implementing this search / sorting with an SQL query would be extremely hard, and probably unreadable
I noticed that most of the request time was due to the completeness normalization, whereas the …
=> PIM-9090: Optimize variant navigation dropdown

CHANGELOG.md, src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ElasticsearchProjection/GetElasticsearchProductModelProjection.php
This fix avoid loading all product model of the same families than the one being indexed in memory.
The previous SQL query was missing the filter on product model codes, so it was erroneously loading all product models from the same family than the ones identified by the provided product model codes. …
=> Filter on product model to avoid loading all of them from the DB

CHANGELOG-3.2.md, src/Akeneo/Tool/Bundle/VersioningBundle/Builder/VersionBuilder.php, src/Akeneo/Tool/Bundle/VersioningBundle/spec/Builder/VersionBuilderSpec.php
Fixes issues when products saved with 'date' are modified to 'datetime'. The PIM recognizes those fields as being updated (even if the date remains the same) and creates versions in the product history.
=> PIM-9152: Handle old versioning date format

src/Akeneo/Tool/Bundle/MeasureBundle/Application/ValidateUnit/ValidateUnitCommand.php, src/Akeneo/Tool/Bundle/MeasureBundle/Controller/InternalApi/ValidateUnitAction.php, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/config/internal_api.yml, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/config/routing.yml, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/config/services.yml, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/config/validation.yml, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/translations/validators.en_US.yml, src/Akeneo/Tool/Bundle/MeasureBundle/Validation/Unit/CodeMustBeUnique.php, src/Akeneo/Tool/Bundle/MeasureBundle/Validation/Unit/CodeMustBeUniqueValidator.php, src/Akeneo/Tool/Bundle/MeasureBundle/tests/EndToEnd/InternalApi/ValidateUnitActionEndToEnd.php
New internal endpoint:
```
POST /rest/measurement-families/{code}/validate-unit
```
3 responses possibles:
```
200 - Valid
404 - Measurement family cannot be found
422 - Not valid
```
=> MET-121: Add endpoint for validating a new unit

src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/model/direction.ts, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/model/label-collection.ts, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/model/measurement-family.ts, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/model/operation.ts, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/model/unit.ts, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/common/OperationCollection.tsx, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/create-measurement-family/form/create-measurement-family-form.ts, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/edit/PropertyTab.tsx, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/edit/UnitTab.tsx, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/list/List.tsx, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/list/MeasurementFamilyTable.tsx, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/Caret.tsx, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/TextField.tsx, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/translations/jsmessages.en_US.yml, src/Akeneo/Tool/Bundle/MeasureBundle/tests/front/unit/model/measurement-family.unit.ts
This PR:
- Splits model in dedicated files
- Add a `autofocus` prop in TextField component
- Disables the add operation button instead of hiding it
=> MET-124: Split models

.circleci/config.yml, Makefile, README.md, package.json, webpack.config.js
This is an attempt to improve webpack build times.
The **webpack build time is increasing** and the main culprit is `typescript` with its `ts-loader`, 
mostly on the **type-checking** part.
For a lot of daily tasks, when we are building the PIM, we don't need to run the type-checking. It should only be executed when needed and on the CI, as we already do for the back with `make lint-back`.
This PR introduces a new option for our webpack config: `--strict`. When enabled, webpack will run as before, with the type-checking.  When omitted, typescript will only transpile from `ts` to `js`.
For the benchmark, I've used a small script to cleanup the cache between builds, to check the performances on a "cold" webpack:
```
#!/bin/bash
rm -rf …
```
=> TIP-1395: Adds a webpack option to run typescript without type checking

src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml, src/Akeneo/Connectivity/Connection/front/src/audit/components/NoConnection.tsx
=> API-1009: Change Audit message when no connection exist

src/Akeneo/Platform/PimRequirements.php
When strict_type is enabled, passing null to trim triggers a TypeError, which causes a FatalError.
As shell_exec returns string|null, function result cannot be trimmed directly
When trying to install Akeneo 4.0, I faced a TypeError. This was related to Ghostscript version checking.
So currently, if GhostScript is not installed, you got a FatalError.
| …
=> Fixed TypeError when checking for GhostScript

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/variant-navigation.js
Trigger events before and after handling navigation in product model breadcrumb
=> DAPI-931: Keep the same tab when switching from a variant to a model (and vice versa)

CHANGELOG.md, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/normalizers.yml, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml, src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Group/SqlGetGroupProductIdentifiers.php, src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/GroupNormalizer.php, src/Akeneo/Pim/Enrichment/Component/Product/Query/GetGroupProductIdentifiers.php, tests/back/Pim/Enrichment/Integration/Storage/Sql/Group/SqlGetGroupProductIdentifiersIntegration.php, tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/InternalApi/GroupNormalizerSpec.php
There's a performance issue when displaying the edit page of a group that has a lot of products.
The problem comes from the `GroupNormalizer` that iterate on all the products of a group to retrieve the product identifiers. It makes Doctrine loads and hydrates all the products and it's very costly.
The list of product identifiers is necessary for the frontend, and it would be complicated to change that. So the simplest and cheapest solution to fix this problem is to add a SQL query to retrieve the product identifiers.
Execution time of the end-point that loads a group with 1000 products (on a PIM installed locally with dev env and Icecat catalog)
- before: ~900ms
- after: ~200ms (same time with only one product)
=> PIM-9157: Fix performance issue when loading the data of a product group

src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/hooks/use-measurement-family-remover.ts, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/edit/Edit.tsx, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/edit/UnitTab.tsx, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/translations/jsmessages.en_US.yml, src/Akeneo/Tool/Bundle/MeasureBundle/tests/front/unit/hooks/use-measurement-family-remover.unit.ts
This PR:
- Adds the remove measurement family hook
- Adds the remove measurement family modal
=> MET-91: Remove Measurement Family frontend (remover hook & confirm modal)

CHANGELOG-4.0.md, src/Akeneo/Pim/Enrichment/Component/Product/Localization/Localizer/AttributeConverter.php, tests/back/Pim/Enrichment/Specification/Component/Product/Localization/Localizer/AttributeConverterSpec.php
A client encountered this problem:
When attempting to save a product with a comma-separated decimal value (i.e 13,24) inside of a localized price attribute, the PIM fails leaving in a blank page. It should display an error message on the price field.
The blank page is due to a Javascript error because the locale is defined instead of the channel in the JSON response of the product edition.
The reason is that Backend side, the property path set in the validation constraint is malformed. It contains only the attribute code and the locale code separated by a dash. There is no channel because the attribute is not scopable, but it should replace the channel by "<all_channels>" to have the right format : "attribute-channel-locale". By having a property path like "attribute-locale", the …
=> PIM-9164: Fix build property path for localized attributes validation

.env, CHANGELOG.md, config/services/pim_parameters.yml, make-file/test.mk, src/Akeneo/Pim/Enrichment/Bundle/Resources/elasticsearch/settings.yml, src/Akeneo/Tool/Bundle/ElasticsearchBundle/DependencyInjection/AkeneoElasticsearchExtension.php, src/Akeneo/Tool/Bundle/ElasticsearchBundle/IndexConfiguration/Loader.php, src/Akeneo/Tool/Bundle/ElasticsearchBundle/spec/IndexConfiguration/LoaderSpec.php, src/Akeneo/Tool/Bundle/ElasticsearchBundle/spec/IndexConfiguration/conf4.yml
Total_fields limit of elasticsearch should be configurable on serenity instances
As per this documentation, this is something that can be needed by some clients:
https://docs.akeneo.com/4.0/maintain_pim/common_issues/index.html#the-limit-of-total-fields-is-reached-in-elasticsearch
=> PIM-9163: total_fields limit of elasticsearch should be configurable

src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/create-measurement-family/CreateMeasurementFamily.tsx, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/list/List.tsx
We now redirect to the newly created Measurement Family after creating it.
=> MET-171: Redirect to newly created Measurement Family after creation

src/Akeneo/Pim/Enrichment/Bundle/Resources/config/updaters.yml, src/Akeneo/Pim/Enrichment/Component/Product/Updater/Clearer/Field/AssociationFieldClearer.php, src/Akeneo/Pim/Enrichment/Component/Product/Updater/Clearer/Field/CategoryFieldClearer.php, src/Akeneo/Pim/Enrichment/Component/Product/Updater/Clearer/Field/GroupFieldClearer.php, tests/back/Pim/Enrichment/Integration/Updater/PropertyClearerIntegration.php, tests/back/Pim/Enrichment/Specification/Component/Product/Updater/Clearer/Field/AssociationFieldClearerSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Updater/Clearer/Field/CategoryFieldClearerSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Updater/Clearer/Field/GroupFieldClearerSpec.php
Add clearers to clear associations, categories and groups from a product / product model.  
=> RUL-89: add clearers for associations, categories and groups

src/Akeneo/Tool/Bundle/MeasureBundle/Controller/ExternalApi/GetMeasurementFamiliesAction.php
Harmonize the GET controller with the new method added in MET-137.
=> MET-172: reuse MeasurementFamily::normalizeWithIndexedUnits

src/Akeneo/Tool/Bundle/MeasureBundle/Controller/ExternalApi/JsonSchema/MeasurementFamilyValidator.php, src/Akeneo/Tool/Bundle/MeasureBundle/Controller/ExternalApi/SaveMeasurementFamiliesAction.php, src/Akeneo/Tool/Bundle/MeasureBundle/spec/Controller/ExternalApi/JsonSchema/MeasurementFamilyValidatorSpec.php, src/Akeneo/Tool/Bundle/MeasureBundle/tests/EndToEnd/ExternalApi/SaveMeasurementFamiliesActionEndToEnd.php
When creating a new Measurement Family, labels and symbols are not required.
=> MET-180: In Measurement Units, labels and symbol are not required

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/field/metric-field.js
The locale flag is displayed if either `locale` or `channel` is present in the context.
The UI locale was added a first time here (with a misleading variable name that triggered the bug):
https://github.com/akeneo/pim-community-dev/commit/f7bf1df71a044d09102de9d304b7986fda800798#diff-560f9f5174f27c976d1dc73643bcb030R40
and is now obsolete as the UI locale is injected there:
https://github.com/akeneo/pim-community-dev/commit/948c8fc90d2e250af7d08079c641a4859b605492#diff-560f9f5174f27c976d1dc73643bcb030R42 …
=> MET-179: Fix locale flag being displayed on measurement attributes

src/Akeneo/Tool/Bundle/MeasureBundle/Model/Operation.php, src/Akeneo/Tool/Bundle/MeasureBundle/Persistence/MeasurementFamilyRepository.php, src/Akeneo/Tool/Bundle/MeasureBundle/Validation/MeasurementFamily/OperationValueValidator.php, src/Akeneo/Tool/Bundle/MeasureBundle/spec/Model/OperationSpec.php, src/Akeneo/Tool/Bundle/MeasureBundle/spec/Validation/MeasurementFamily/OperationValueValidatorSpec.php
Currently the endpoint PATCH /api/rest/v1/measurement-families unit[convert_from_standard][value] field allow scientific annotation. To have consistency between UI (we allow only number in operation value) and API we decided to remove support of scientific notation in API and in Internal Controller (in case of UI validation is by passed) …
=> MET-176: fix: do not allow scientific notation

src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/create-measurement-family/CreateMeasurementFamily.tsx
The function `handleClose` has a new signature: 
`(createdMeasurementFamilyCode?: MeasurementFamilyCode) => void;`
but when called from `onClick`, a click event is given, redirecting the url to `/#/configuration/measurement/[object Object]`.
=> MET-195: Fix the close button of CreateMeasurementFamily modal

src/Akeneo/Pim/Enrichment/Component/Product/Updater/Adder/PriceCollectionAttributeAdder.php, tests/back/Acceptance/Channel/ChannelContext.php, tests/back/Pim/Enrichment/Specification/Component/Product/Updater/Adder/PriceCollectionAttributeAdderSpec.php
Prior to v4.0, the PriceCollectionValueFactory used to filter duplicate prices (with the same currency), only keeping the newest one (see https://github.com/akeneo/pim-community-dev/blob/f328bf1059babb2db6a14fa6f230e7679da21a2e/src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/PriceCollectionValueFactory.php#L237). This is not the case anymore, although the PriceCollectionAttributeAdder used to rely on this behavior.
I'll update the PriceCollectionValueFactory (to check that a currency is not used twice) in another PR.
I also took advantage of this PR to add allow to add a currency to a channel in acceptance context.
| …
=> RUL-60: Replace prices with same currency in PriceCollectionAttributeAdder

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/creation/field.js, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/fields/boolean.js
In one form, if you have a text field & boolean field:
If you want to reproduce locally, add the following lines:
```
extensions:
pim-association-type-properties-foo:
module: pim/form/common/fields/boolean
parent: pim-association-type-create-modal
targetZone: fields
position: 20
config:
fieldName: foo
label: foo
defaultValue: false
```
rebuild the front & try to create a new association type.
You can reproduce the bug with the following steps:
- fill the text field
- click directly on the boolean
The text field is emptied.
**Why ?**
In the creation field for the code, the input will update only on change (when the field lose the focus):
```js
// src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/creation/field.js …
```
=> Fix the boolean field cancelling other events

CHANGELOG-4.0.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/product/tab/attributes/validation-error.html
Before: A white space missed between the locale and the error message.
After: 
=> PIM-9164: Improve the display of the validation error message

tests/back/Acceptance/Channel/InMemoryChannelRepository.php
A method of in memory repository is not working because of bad typing object: the class was not imported.
=> RUL-84: fix missing use in in memory repository

CHANGELOG-3.2.md, src/Akeneo/Pim/Structure/Bundle/Controller/InternalApi/AttributeGroupController.php, src/Akeneo/Pim/Structure/Bundle/Query/InternalApi/AttributeGroup/Sql/FindAttributeCodesForAttributeGroup.php, src/Akeneo/Pim/Structure/Bundle/Resources/config/controllers.yml, src/Akeneo/Pim/Structure/Bundle/Resources/config/queries.yml, src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml, src/Akeneo/Pim/Structure/Component/Normalizer/InternalApi/AttributeGroupNormalizer.php, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/attribute-group/form/tab/attribute.js, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/attribute-group/tab/attribute.html, tests/back/Pim/Structure/Integration/AttributeGroup/Query/SqlFindAttributeCodesForAttributeGroupIntegration.php, tests/back/Pim/Structure/Specification/Component/Normalizer/InternalApi/AttributeGroupNormalizerSpec.php
When there is too many attributes within a group, and a user tries to list all the attributes for this group. The UI freezes.
Solution:
We only display the first 500 attributes of this group, when the number of attributes exceeds 500. We display a helper message at the end of the link and a link to the attribute list screen pre-filtered with the current attribute group code.
EDIT 10/04/2020:
In this new version, we filter the 500 attributes to show in the front-end (before we did this in the back-end). This way, we avoid updating the attribute with only 500 attributes instead of the whole attribute group entity.
I introduced a query function to speed things up during the update in the attribute group controller to avoid falling into a …
=> PIM-9177: Fix showing/updating attributes in attribute group when too many attributes

src/Akeneo/Connectivity/Connection/back/Application/Settings/Command/CreateConnectionHandler.php, src/Akeneo/Connectivity/Connection/back/Domain/Settings/Model/Write/Connection.php, src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/Dbal/Repository/DbalConnectionRepository.php, src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/InMemory/Repository/InMemoryConnectionRepository.php, src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Settings/Command/DeleteConnectionHandlerSpec.php, src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Settings/Command/RegenerateConnectionPasswordHandlerSpec.php, src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Settings/Command/RegenerateConnectionSecretHandlerSpec.php, src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Settings/Command/UpdateConnectionHandlerSpec.php, src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Settings/Validation/Connection/CodeMustBeUniqueValidatorSpec.php, src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Domain/Settings/Model/Write/ConnectionSpec.php
=> API-1075: Use int value for user id instead of value object

CHANGELOG-4.0.md, src/Oro/Bundle/PimDataGridBundle/Normalizer/ProductNormalizer.php, src/Oro/Bundle/PimDataGridBundle/spec/Normalizer/ProductNormalizerSpec.php
Fix https://akeneo.atlassian.net/browse/PIM-9160 
The association list on the PEF was broken because of missing channel. As the request is done with locale but without channel, we have to handle this case. The fix is done in the product normalizer (datagrid one).  
| Tech Doc …
=> PIM-9160: Fix product association display

CHANGELOG-4.0.md, src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/FlatToStandard/ColumnsMerger.php, tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/FlatToStandard/ColumnsMergerSpec.php
Imagine that you have activated but unused currencies on your PIM:
1- You export a product : the columns with the unused currencies are in the csv/xlsx file.
2- You complete the columns where the currencies that are interresting you (activated and used currencies)
3- You import your product on your PIM
Issue: The values completed in the csv/xlsx file didn't appear on the concerned PEF.
So, I fixed this issue by modifying the condition in the collectPriceData() function.
Now, all the values that you have completed on your csv/xlsx file appear on the concerned PEF, after importing it.
| Added Specs …
=> PIM-9175: Fix the import of all price values

CHANGELOG-3.0.md, src/Akeneo/Tool/Component/Localization/Presenter/DatePresenter.php, src/Akeneo/Tool/Component/Localization/spec/Presenter/DatePresenterSpec.php
So that the PEF is not broken if a weird date is in the version (among all other problems we could encounter in pages where the date presenter is used).
=> PIM-9193: DatePresenter presents null if date can not be formatted

CHANGELOG.md, tests/back/Acceptance/Attribute/InMemoryAttributeRepository.php, tests/back/Acceptance/Attribute/InMemoryGetAttributes.php, tests/back/Acceptance/spec/Attribute/InMemoryAttributeRepositorySpec.php, tests/back/Acceptance/spec/Attribute/InMemoryGetAttributesSpec.php
The SQL implementation of GetAttributes is case insensitive. To reflect this in our tests, we have to do the same in InMemory one.  
=> PIM-9197: make the InMemoryGetAttributes case insensitive

CHANGELOG-4.0.md, Dockerfile.base
This lib allows us to generate preview for SVG files
=> PIM-9195: Add extra ImageMagick library to handle SVG files

.circleci/config.yml, Makefile, std-build/Makefile
PIM-9208 Uses HTTP instead of Yarn buggy HTTPs server
=> PIM-9208 Uses HTTP instead of Yarn buggy HTTPs server

CHANGELOG-3.2.md, src/Akeneo/Pim/Enrichment/Bundle/PdfGeneration/Renderer/ProductPdfRenderer.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/renderers.yml
Issue: When exporting a Product as PDF, we only had the values from the product itself, not the ones inherited from the Product Model.
Solution: We added the productValuesFiller to the productPDFRenderer.
`OK`: Done / …
=> PIM-9205: PDF doesn't export Product Model values

CHANGELOG-3.2.md, src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/EntityWithFamilyVariantNormalizer.php
When the user does not have the right to view the attribute used as an axis on product model variant, the UI display a 500 error because the axis attribute cannot be normalized (since it has been excluded) in the API response.
There has been an error page designed for this specific error but I don't know how to link this error from the back to the front.
The proposed solution is to at least catch the error and let the front fallback on its default behavior without crashing.
On the product model common PEF:
When I select the variant color: …
=> PIM-9204: Avoid error with ACL restricitions on axis attribute

.eslintignore
Adding the Rule directory as ignore in eslintignore file.
We are using a yarn workspace and specific linter rules on our project.
The global yarn lint failed on our project due to a dependency on @typescript/parser.
Didn't find a way to fix it for now, this is a quicker solution for the moment. …
=> RULE-ENGINE: Add eslintignore for rule directory

CHANGELOG-4.0.md, src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/ProductController.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/controllers.yml
A deadlock can occurs during the completeness calculation, on the `postSave` event in partial update of products.
This produce the following output:
```
...
{"line":93,"identifier":"1111111204","status_code":204}
{"line":94,"identifier":"1111111205","status_code":204}
{"line":95,"identifier":"1111111206","status_code":204}
{"line":96,"identifier":"1111111207","status_code":204}
{"line":97,"identifier":"1111111208","status_code":204}
{"line":98,"identifier":"1111111209","status_code":204}
{"line":99,"identifier":"1111111210","status_code":204}
{"line":100,"identifier":"1111111211","status_code":204}{"code":500,"message":"Internal Server Error"}
```
The proposed solution is to log the error instead of breaking the API response because …
=> PIM-9192: Fix error being printed in the response of partial update of products API

CHANGELOG-3.2.md, src/Akeneo/Pim/Enrichment/Bundle/Product/Query/Sql/GetCategoryCodesByProductIdentifiers.php
If one category is assigned first to a variant, then to the product model, in the product external API, this category is returned twice.
Instead of trying to search and update the database for this case, we simply hide the duplicates from the product API response. The reasons are:
- checking/removing duplicate categories from children while saving a product model would induce a huge performance impact
- it’s not that important/bad to have a category for both the product and the parent product model in BDD, because functionally speaking the child does have the category (it inherits it from its parent)
| Added …
=> PIM-9219: Fix duplicated categories in the product API when present in both Product Model and Variant

CHANGELOG-3.2.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/edit-form.js
- Now saving the scroll position on the common edit form before re-rendering, all credit goes to @mmetayer https://github.com/akeneo/pim-community-dev/pull/11600.
=> PIM-9212: Keep vertical scroll position of the attribute form after editing values

frontend/webpack/requirejs-utils.js
This PR fixes a bug preventing the override of any requirejs module if the file path and the module name are identical.
For instance:
```yaml
config:
paths:
acme/controller/index: 'acme/controller/index'
```
That was never an issue until now as the real file path and the module name are different most of the time, so the override work in this case. But we recently had the issue on the Onboarder with an Asset Manager module which name and real file path are identical.
The root cause is that `frontend/webpack/requirejs-utils.js` is merging all requirejs module paths together, but real file paths were taking precedence over them.
| …
=> AOB-925: Fix front-end override capabilities

.circleci/config.yml, .circleci/detect_structure_changes.sh
JM reported me a problem. Imagine you have both a CE and an EE branch.
Currently, the CE build will install a master EE with your CE branch. But your EE branch is not taken into account. This PR fixes the problem.
It also lead me to :
- fix the wrong checkout of the EE branch in the `detect_structure_changes.sh` script. The URL was not accessible at all! And as we now always clone an EE, it's much easier to do a  `git checkout MYBRANCH || git checkout master`. And this exactly what we want. Checkout MYBRANCH if it exists, master otherwise.
- remove a useless hack of the `composer.json` in the `build_prod` job. This change is already performed in `checkout_ee`.
=> TIP-1456: require correct EE branch if it exists

CHANGELOG-3.2.md, src/Oro/Bundle/PimDataGridBundle/Extension/MassAction/MassActionDispatcher.php, src/Oro/Bundle/PimDataGridBundle/spec/Extension/MassAction/MassActionDispatcherSpec.php, tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Filter/Field/AncestorCodeFilterSpec.php
Backports fix from #11638 to 3.2 branch. It fixes errors on mass action when the parent filter is set to empty
=> PIM-9222: Error 500 when attempting bulk change with parent=empty filter

CHANGELOG-4.0.md, src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductGrid/ProductModelImagesFromCodes.php
Optimizes the SQL query fetching product model images at the product level for the product datagrid. MySQL could sometimes wrongly optimize it (maybe bacause of the COALESCE in the ON CLAUSE). On a duplicated env with ~1 million products (but only 2 product models and 5 variant products):
- former query: ~ 1min40s
- new query: ~10 ms …
=> PIM-9227: Fix performance issue on product grid for product model images

CHANGELOG-4.0.md, src/Akeneo/Tool/Bundle/VersioningBundle/Command/RefreshCommand.php
The refresh command was not working with the following error message : 
```
In RefreshCommand.php line 103:
Attempted to call an undefined method named "getObjectManager" of class 
"Akeneo\Tool\Bundle\VersioningBundle\Command\RefreshCommand". 
```
Checking on 3.2, that definition was properly done.
**Solution:** 
The RefreshCommand class doesn't extend ContainerAwareCommand class anymore.
So, the method getObjectManager must now be called via the entityManager object (EntityManagerInterface extends ObjectManager).
| Added …
=> PIM-9224: Refresh command broken in 4.0

CHANGELOG-3.2.md, src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Query/SqlGetValuesOfSiblings.php, src/Akeneo/Pim/Enrichment/Component/Product/ProductModel/Query/GetValuesOfSiblings.php, src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/UniqueVariantAxisValidator.php, src/Akeneo/Pim/Structure/Bundle/Query/PublicApi/AttributeOption/Cache/LRUCachedGetExistingAttributeOptions.php, src/Akeneo/Pim/Structure/Bundle/Resources/config/queries.yml, tests/back/Pim/Enrichment/Integration/Doctrine/Query/SqlGetValuesOfSiblingsIntegration.php, tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/UniqueVariantAxisValidatorSpec.php, tests/back/Pim/Structure/Specification/Bundle/Query/PublicApi/AttributeOption/Cache/LRUCachedGetExistingAttributeOptionsSpec.php
When saving a variant product or product model, the `Akeneo\Pim\Enrichment\Component\Product\Validator\Constraints\UniqueVariantAxisValidator` validates that its variant axes are unique. In order to do so, it fetches the values of the siblings of the saved entity from DB and creates a ValueCollection.
However, creating a ValueCollection is costly, as there are a lot of checks performed (e.g, check that the stored attribute options still exist...), so creating a ValueCollection for each sibling can prove **very** costly
This PR:
- only fetches values corresponding to the variant axes to compare them
- stores the existing/unexisting attribute options into an LRU cache in order to avoid performing the same SQL query for each entity …
=> PIM-9221: Performance issue on update product model through API

config/services/test/test_services.yml, src/Akeneo/UserManagement/Bundle/Resources/config/repositories.yml, src/Oro/Bundle/SecurityBundle/Resources/config/services.yml, upgrades/test_schema/ExecuteMigrationTrait.php
**What's done today**
When we launch the command `make migration-back` in the CI job `test_back_data_migrations`, all PhpUnit tests of the suite `PIM_Migration_Test` are launched.
Those PhpUnit are launched in `test` mode, which is what we want as a lot of services we use for those tests are defined only in `test` mode. Each of this tests launches a migration in a subprocess via the [command_launcher service](https://github.com/akeneo/pim-community-dev/blob/master/src/Akeneo/Pim/Enrichment/Bundle/Resources/config/console.yml#L4-L10). This service uses the current environment (in our case, `test`).
**The problem**
The migration [Version_4_1_20200127171059_unauthorized_view_all_jobs_permission](https://github.com/akeneo/pim-community-dev/blob/master/upgrades/schema/Version_4_1_20200127171059 …
=> TIP-1291: launch migrations in prod mode, as it will be done on Serenity

CHANGELOG-3.0.md, src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/ProductModelController.php, tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/ListUpdatedOrCreatedSinceNDaysProductModelEndToEnd.php
Basically the same fix as the one for the product : https://github.com/akeneo/pim-community-dev/pull/8885
There must not be no formatting on date filter for the operators SINCE_LAST_N_DAYS, since it's an integer …
=> PIM-9242: Fix API product model list when filtering with SINCE LAST N DAYS operator

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/family-variant/form/attribute-set.js
For the Onboarder needs, we have to update the `family_variant/form/attribute-set.js` in order to lock our `supplier` and `supplier_reference` attributes to the latest level of family variant.
This PR extracts the logic of locking attributes in a function so we can override it easily.
| …
=> AOB-683: Add an extension point in family variant attribute-set

CHANGELOG-3.2.md, frontend/build/compile-less.js, frontend/build/update-extensions.js
Seen here in action: https://regex101.com/r/4A6zOF/5 (you can open the substitution panel to see the result)
It respect and improve the two previous examples:
https://regex101.com/r/4A6zOF/2
https://regex101.com/r/vdDaWy/5
One big error was the use of `[^vendor]` instead of `(?!=vendor)`
Regex explanation of `^.+(?=vendor).*?(?=src)\/`
`^` : easy, the string start
`.+(?=vendor)` : everything that is not followed by "vendor". Greedy mode, will go the the last _vendor_ occurrence
`.*?(?=src)` : everything that is not followed by "src". Non greedy mode, will go to the first _src_ occurrence
`\/` : require a slash behind _src_, not needed IMHO but i wanted to stay in the same line than previous code.
To sum up:
> remove everything before the FIRST 'src/' that is after the LAST 'vendor' …
=> PIM-9245: Fix relative JS files path for less compilation

CHANGELOG-4.0.md, src/Akeneo/Channel/Bundle/Resources/config/validation/locale.yml, src/Akeneo/Channel/Bundle/Resources/config/validators.yml, src/Akeneo/Channel/Bundle/Resources/translations/validators.en_US.yml, src/Akeneo/Channel/Component/Validator/Constraint/LocaleCode.php, src/Akeneo/Channel/Component/Validator/Constraint/LocaleCodeValidator.php, tests/back/Channel/Specification/Component/Validator/Constraint/LocaleCodeValidatorSpec.php
This PR adds a validation rule on locale codes. A locale must at least start with 2 or 3 letters, followed by an underscore and at least 2 characters (numbers, letters or underscores).
So this means that locale codes with only 2 letters are now forbidden (for example `en`)
FYI This is all the locale code formats I found in the PIM : 
```
af_ZA
arn_CL
en_029
az_Cyrl_AZ
tzm_Latn_DZ
```
| Review and …
=> PIM-9246: Add a validation on locale codes

Makefile
Uses Google Chrome from Node Docker image instead of the one downloaded by Puppeteer.
This has for effect to never have to download a Chromium locally, as this often fails because of the servers used by Puppeteer often fails.
| Added legacy Behats               |- …
=> Uses Google Chrome from Node Docker image

behat.yml, src/Akeneo/Pim/Enrichment/Bundle/DependencyInjection/AkeneoPimEnrichmentExtension.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/quantified_associations.yml, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/serializers_standard.yml, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/updaters.yml, src/Akeneo/Pim/Enrichment/Component/Product/Model/EntityWithQuantifiedAssociationsInterface.php, src/Akeneo/Pim/Enrichment/Component/Product/Model/QuantifiedAssociation/EntityWithQuantifiedAssociationTrait.php, src/Akeneo/Pim/Enrichment/Component/Product/Model/QuantifiedAssociation/QuantifiedAssociations.php, src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Standard/Product/QuantifiedAssociationsNormalizer.php, src/Akeneo/Pim/Enrichment/Component/Product/QuantifiedAssociation/QuantifiedAssociationsFromAncestorsFilter.php, src/Akeneo/Pim/Enrichment/Component/Product/QuantifiedAssociation/QuantifiedAssociationsMerger.php, src/Akeneo/Pim/Enrichment/Component/Product/Updater/ProductModelUpdater.php, src/Akeneo/Pim/Enrichment/Component/Product/Updater/ProductUpdater.php, src/Akeneo/Pim/Enrichment/Component/Product/Updater/Setter/QuantifiedAssociationsFieldSetter.php, tests/back/Pim/Enrichment/Acceptance/Context/QuantifiedAssociationsContext.php, tests/back/Pim/Enrichment/Acceptance/Resources/config/behat/services.yml, tests/back/Pim/Enrichment/Specification/Component/Product/QuantifiedAssociation/QuantifiedAssociationMergerSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/QuantifiedAssociation/QuantifiedAssociationsFromAncestorsFilterSpec.php, tests/features/pim/enrichment/entity-with-quantified-associations/update_quantified_associations.feature
- Update ProductUpdater & ProductModelUpdater to filter quantified associations inherited from the parents
- Update ProductUpdater & ProductModelUpdater to call the property setter
- Update the Standard normalizer to call the quantified associations merger
- Acceptance tests  …
=> RAC-21: Add quantified associations updater and setter

CHANGELOG-3.2.md, app/config/pim_parameters.yml, src/Akeneo/Tool/Bundle/ElasticsearchBundle/Command/ResetIndexesCommand.php, src/Akeneo/Tool/Bundle/ElasticsearchBundle/spec/Command/ResetIndexesCommandSpec.php
PIM indexes were hardcoded and the message at the end of the command was wrong in EE.
=> PIM-9165: Improve message of akeneo:elasticsearch:reset-indexes command

CHANGELOG-3.2.md, src/Akeneo/Pim/Enrichment/Component/Product/Job/JobParameters/ConstraintCollectionProvider/ComputeFamilyVariantStructureChanges.php
This PR updates the `ComputeFamilyVariantStructureChanges` in order to allow several elements in the `family_variant_codes` array.
=> AOB-953: Fix `ComputeFamilyVariantStructureChanges` constraint

.circleci/config.yml, .circleci/run_behat.sh
Currently, a PR is merge-able if the step `back_behat_legacy` is green. This configuration must be identical for all PIM branches. 
As we want to have more flexibility on our master workflow (for instance, a PR can be merged if `back_behat_legacy` and `foo` are green), we introduce here a final step `pull_request_success`. This one should always be green. And we can put whatever we want before it.
Also, `deploy_upgrade_oldest_prod_environment` now is a requirement to merge a PR.
Finally, we display behats lauched on each container for debug purposes. Indeed, we have sometimes problems with the split of the behats by timing. We hope that displaying the output of circle's command will help us to debug when the problem will occur again.
=> Minor improvements on CI PR workflow

CHANGELOG.md, src/Akeneo/Platform/Bundle/FeatureFlagBundle/AkeneoFeatureFlagBundle.php, src/Akeneo/Platform/Bundle/FeatureFlagBundle/README.md, tests/back/Platform/Specification/Bundle/FeatureFlagBundle/AkeneoFeatureFlagBundleSpec.php
This introduces a new compiler pass along with a boot hook in the kernel.
The compiler pass replaces each service tagged `feature_flags.is_enabled`
by a synthetic service (i.e: a service that needs to be defined at runtime).
The original service is renamed to `$id.real` and an alternative service is provided using a tag attribute named `otherwise`.
The alternative service must be a drop-in replacement of the original service (by implementing the same interface for example).
If no alternative is proposed, the service is kept synthetic, and accessing it would blow up with a runtime exception.
All in all, no change has to be made in your code and/or service definitions, except for adding the tag on the services you want:
```yaml
services:
My\Service:
tags:
- { name: feature_flags.is_enabled, …
```
=> TIP-1406: Add a tag to configure a DIC service based on a feature flag

CHANGELOG-4.0.md, src/Akeneo/Tool/Component/Console/CommandLauncher.php
We should not fix the memory limit of a batch command FROM the web context because they may not have the same memory_limit setting.
=> PIM-9260: do not use FPM memory_limit for CommandLauncher

CHANGELOG-3.2.md, src/Akeneo/Platform/config/bundles/liip_imagine.yml
Keep the rotation on thumbnails generated images We do it using the liip filter "auto_rotate" which tells imagick to keep the rotation in place.
=>  PIM-9262: Keep exif rotations when generating thumbnails 

CHANGELOG-3.2.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/associations.js, src/Oro/Bundle/PimDataGridBundle/Datagrid/Configuration/Product/ContextConfigurator.php
**Issue:**
When the channel was changed on a product, the associated products grid was not reloaded.
The completeness value could be wrong.
**Solution:**
We have made the associated products reloaded when the user changes the channel in the association view.
Changelog updated                 | Yes …
=> PIM-9255: Reload completeness on associated product when channel is switched on association view

CHANGELOG-4.0.md, src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/messages.en_US.yml
_**Issue:**_
On the header, while creating a new category, the terms "Tree.create" were not translated and not translatable (unable to find it) on Crowdin.
_**Solution:**_ 
I added the key "tree.create" and its associated message on the translation file. …
=> PIM-9269: Add a key "tree.create" and its associated message in the translation file for Crowdin

CHANGELOG-4.0.md, src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
On 4.0 version, the "Oro" bundle was by purpose removed from Crowdin, so the "search on..." of the datagrid wasn't translated anymore.
So, I added the key "pim_datagrid.search" in a jsmessages.en_US.yml file. …
=> PIM-9264: Make "search on..." translatable on Crowdin

.circleci/config.yml, .circleci/detect_structure_changes.sh
The Onboarder bundle contains all its configuration, so there is no need anymore to copy anything. Activating the bundle and setting the correct environment variables (not needed for the tests) is enough.
=> AOB-956: No more Onboarder specific configuration

CHANGELOG-2.3.md, src/Pim/Bundle/EnrichBundle/Resources/public/js/menu/help.js, src/Pim/Bundle/EnrichBundle/Resources/public/templates/menu/help.html
Same things than the https://github.com/akeneo/pim-community-dev/pull/12155 PR but in 2.3.
Ticket : https://github.com/akeneo/actionable-product-data/issues/130 
=> GITHUB-APD-130: Update help menu link to redirect to the right version on the help center

CHANGELOG-4.0.md, src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ElasticsearchProjection/GetElasticsearchProductModelProjection.php, src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ElasticsearchProjection/GetElasticsearchProductProjection.php, tests/back/Pim/Enrichment/Integration/Product/Job/ComputeFamilyVariantStructureChangesTaskletIntegration.php
https://akeneo.atlassian.net/browse/PIM-9276  
A problem occurred when we change the level of an attribute in a family variant. A cron is launched to move the values from a product/product model to another product/product model, but during this operation there is a time where the value is at 2 levels (for example the value is in the root product model and the sub product model). That is because we cannot save product models and products at same time.  
In the indexation process, we merge all the values of root product model, sub product model and variant products, and this operation does not make it right because of the `JSON_MERGE_PRESERVE`.
For example a date value is present in the root PM and the sub PM. When we merge the value …
=> PIM-9276: fix values merge during indexation

CHANGELOG-4.0.md, src/Akeneo/Pim/Enrichment/Component/Product/Validator/ConstraintGuesser/RegexGuesser.php, tests/back/Pim/Enrichment/Integration/Validation/ProductIdentifierValidationIntegration.php, tests/legacy/features/pim/enrichment/product/validation/validate_identifier_attribute.feature, tests/legacy/features/pim/enrichment/product/validation/validate_text_attributes.feature
When you tried to edit an attribute (define with a regular expression) with a value not allowed you got a generic error message.
So, I modified this message in the RegexGuesser.php file.
=> PIM-9106: Improve error message when editing an attribute when it's due to a regular expression

CHANGELOG-4.0.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/product-label.js
The `getLabelFromAttribute` method tries to find  the `attributeAsLabelIdentifier` value in form values, on Onboarder side this value is not sent to the front,
so it throws an exception when trying to apply to find method on something `undefined`, 
in that case, we return false to display the product identifier.  …
=> AOB-968: fix product label rendering, return false if values are undefined

.circleci/config.yml, CHANGELOG-5.0.md, src/Akeneo/Tool/Component/Connector/Reader/File/Yaml/Reader.php, src/Akeneo/Tool/Component/Connector/spec/Reader/File/Yaml/ReaderSpec.php, src/Akeneo/Tool/Component/Connector/spec/fixtures/fake_incorrectly_formatted_yml_file.yml
Process tracker when incorrect file is read:
=> PIM-9274: Fix Yaml reader to display the number of lines read for incorrectly formatted files

src/Akeneo/Pim/Enrichment/Bundle/Resources/config/updaters.yml, src/Akeneo/Pim/Enrichment/Component/Product/Updater/ProductModelUpdater.php, src/Akeneo/Pim/Enrichment/Component/Product/Updater/ProductUpdater.php, src/Akeneo/Pim/Enrichment/Component/Product/Updater/Setter/QuantifiedAssociationsFieldSetter.php, src/Akeneo/Pim/Enrichment/Component/Product/Updater/Validator/QuantifiedAssociationsStructureValidator.php, src/Akeneo/Pim/Enrichment/Component/Product/Updater/Validator/QuantifiedAssociationsStructureValidatorInterface.php, tests/back/Pim/Enrichment/EndToEnd/Product/EntityWithQuantifiedAssociations/AbstractQuantifiedAssociationsTestCase.php, tests/back/Pim/Enrichment/EndToEnd/Product/EntityWithQuantifiedAssociations/QuantifiedAssociationsTestCaseTrait.php, tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/QuantifiedAssociations/AddQuantifiedAssociationsToProductEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/QuantifiedAssociations/DeleteQuantifiedAssociationsFromProductEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/QuantifiedAssociations/UpdateQuantifiedAssociationsInProductEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/QuantifiedAssociations/ValidateQuantifiedAssociationsInProductEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/Product/InternalApi/QuantifiedAssociations/RemoveQuantifiedAssociationsFromProductEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/AbstractProductModelTestCase.php, tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/QuantifiedAssociations/AddQuantifiedAssociationsToProductModelEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/QuantifiedAssociations/DeleteQuantifiedAssociationsFromProductEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/QuantifiedAssociations/DeleteQuantifiedAssociationsFromProductModelEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/QuantifiedAssociations/UpdateQuantifiedAssociationsInProductEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/QuantifiedAssociations/UpdateQuantifiedAssociationsInProductModelEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/QuantifiedAssociations/ValidateQuantifiedAssociationsInProductModelEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/InternalApi/QuantifiedAssociations/RemoveQuantifiedAssociationsFromProductModelEndToEnd.php, tests/back/Pim/Enrichment/Specification/Component/Product/Updater/ProductModelUpdaterSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Updater/ProductUpdaterSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Updater/Setter/QuantifiedAssociationsFieldSetterSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Updater/Validator/QuantifiedAssociationsStructureValidatorSpec.php
- Add a structure validator on quantified associations using the same method as we already do for the associations
- Change QuantifiedAssociationsFieldSetter to merge by keys (expected behavior for partial updates)
- End2End tests on the create/update/delete of quantified associations. (including validation) …
=> RAC-45: Create/update quantified associations in the External API

CHANGELOG-4.0.md, src/Akeneo/Channel/Bundle/DependencyInjection/AkeneoChannelExtension.php, src/Akeneo/Channel/Bundle/Query/Sql/SqlGetChannelCodeWithLocaleCodes.php, src/Akeneo/Channel/Bundle/Resources/config/queries.yml, src/Akeneo/Channel/Component/Query/GetChannelCodeWithLocaleCodesInterface.php, src/Akeneo/Channel/Component/Query/PublicApi/Cache/CachedChannelExistsWithLocale.php, src/Akeneo/Channel/Component/Query/PublicApi/ChannelExistsWithLocaleInterface.php, src/Akeneo/Pim/Enrichment/.php_cd.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/factories.yml, src/Akeneo/Pim/Enrichment/Component/Product/Factory/NonExistentValuesFilter/NonExistentChannelLocaleValuesFilter.php, tests/back/Acceptance/Channel/InMemoryGetChannelCodeWithLocaleCodes.php, tests/back/Acceptance/Resources/config/pim/queries.yml, tests/back/Acceptance/spec/Channel/InMemoryGetChannelCodeWithLocaleCodesSpec.php, tests/back/Channel/Integration/Channel/Query/Sql/SqlGetChannelCodeWithLocaleCodesIntegration.php, tests/back/Channel/Specification/Component/Query/PublicApi/Cache/CachedChannelExistsWithLocaleSpec.php, tests/back/Pim/Enrichment/Integration/PQB/AbstractProductQueryBuilderTestCase.php, tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/Boolean/LocalizableScopableFilterIntegration.php, tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/Date/LocalizableScopableFilterIntegration.php, tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/Media/LocalizableScopableFilterIntegration.php, tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/Metric/LocalizableScopableFilterIntegration.php, tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/Number/LocalizableScopableFilterIntegration.php, tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/Option/LocalizableScopableFilterIntegration.php, tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/Options/LocalizableScopableFilterIntegration.php, tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/Price/LocalizableScopableFilterIntegration.php, tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/Text/LocalizableScopableFilterIntegration.php, tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/TextArea/LocalizableScopableFilterIntegration.php, tests/back/Pim/Enrichment/Integration/PQB/ProductQueryBuilderIntegration.php, tests/back/Pim/Enrichment/Specification/Component/Product/Factory/NonExistentValuesFilter/NonExistentChannelLocaleValuesFilterSpec.php
Please focus your review on the second commit. The first commit has been backported from master
Since the 4.0, the validation of the product values is stricter. It's no more possible to update a value for a locale not activated for the given channel  (but activated for another channel). It's was possible in 3.2, but it was a mistake.
The side effect is that if a locale is deactivated for a channel, all the products that had a value on a scopable and localizable attribute for this locale cannot be updated anymore from the UI. It's because the values of the deactivated locale are still submitted and don't pass the validation.
The solution is to filter these values when they are fetched from the database, as it has been done for the other similar cases (e.g. deleted options or deleted …
=> PIM-9273: Allow to save product after locale deletion

.circleci/run_behat.sh
Pretty basic PR to fix a "random" problem on Behat execution when only one Behat scenario is selected by CircleCI to be run on a container.
With the previous code, if there was only one scenario, the `grep` command would fail, as there was no scenario separator (the space character).
This fix simplifies the code as well by removing the grep and the embedded command interpretation.
The -e added in the echo inside the loop was added in order for the "\n" to be interpreted...
| Added …
=> TIP-450 Fix breaking build when only one Behat is selected by CircleCi

CHANGELOG-4.0.md, src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Attribute/OptionFilter.php
An inconsistency has been detected into the API : the creation of attribute options via API is not case sensitive, while calling attribute options via API is case sensitive.
So, I make calling attribute options case insensitive. …
=> PIM-9282 : make calling attribute options via API case insensitive

src/Akeneo/Tool/Component/Connector/Exception/InvalidItemFromViolationsException.php, src/Akeneo/Tool/Component/Connector/spec/Exception/InvalidItemFromViolationsExceptionSpec.php
During an import, when the invalid value of a constraint violation is a collection of objects (without magic `__toString()` method), the instantiation of InvalidItemFromViolationsException of will fail with a `Catchable Fatal Error: Object of class Foo\Bar\Baz could not be converted to string`.
This PR fixes this issue.
| …
=> RUL-170: Fix InvalidItemFromViolationsException when invalid value is a collection of objects

CHANGELOG-4.0.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/categories.js, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/tree-associate.jstree.js
When a product has a lot of categories, the URI to load the categories tree of the PEF can be too long. All the categories of the product are added to the URI as "selected" categories.
I'm not totally comfortable with this solution, but it's the easiest. I added an optional parameter to "tree-associate" to be flexible on the HTTP method to use. I don't see another solution that would not need a big rework.
=> PIM-9290: Fix product categories loading

behat.yml, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/validation/product.yml, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/validation/productmodel.yml, src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/validators.en_US.yml, src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/validators.fr_FR.yml, src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/AssociationTypeIsNotQuantified.php, src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/AssociationTypeIsNotQuantifiedValidator.php, src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/QuantifiedAssociationsValidator.php, tests/back/Acceptance/Product/InMemoryProductRepository.php, tests/back/Acceptance/Resources/config/behat/services.yml, tests/back/Acceptance/User/UserContext.php, tests/back/Acceptance/spec/Product/InMemoryProductRepositorySpec.php, tests/back/Pim/Enrichment/Acceptance/Context/QuantifiedAssociationsContext.php, tests/back/Pim/Enrichment/EndToEnd/Product/Product/InternalApi/QuantifiedAssociations/AddQuantifiedAssociationsToProductEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/InternalApi/QuantifiedAssociations/AddQuantifiedAssociationsToProductModelEndToEnd.php, tests/features/pim/enrichment/entity-with-quantified-associations/validate_quantified_associations.feature
Add a validator to check that no quantified association type are used in `Product::associations`.
Also update the translations for `association_type_is_not_quantified` and `association_type_should_not_be_quantified` after feedback. …
=> RAC-59: Add validation to fordib quantified association type in associations

CHANGELOG-4.0.md, src/Akeneo/Pim/Enrichment/Component/Product/Builder/EntityWithValuesBuilder.php, tests/back/Pim/Enrichment/Specification/Component/Product/Builder/EntityWithValuesBuilderSpec.php
Updating a product with a text value made of spaces only generates a server error. So the product cannot be updated, and the error message displayed is only "The product could not be updated."  The user cannot know what's the problem and what attribute causes this problem. (it occurs for UI, API, and imports)
The error comes from the service `TextValueFactory` https://github.com/akeneo/pim-community-dev/blob/master/src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/TextValueFactory.php that doesn't accept empty strings and considers legitimately a string made of spaces only as empty.
There's surely a more global problem about trailing spaces, but I think that as an SLA fix, it's better to only focus on this precise problem: to not consider a string made of spaces only as a …
=> PIM-9291: Fix product updated with a text value made of spaces only

src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptions.tsx, src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/DeleteConfirmationModal.tsx, src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/Edit.tsx, src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/List.tsx, src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/ListItem.tsx, src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/NewOptionPlaceholder.tsx, src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/hooks/useCreateAttributeOption.ts, src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/hooks/useDeleteAttributeOption.ts, src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/hooks/useSaveAttributeOption.ts, src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/reducers/attributeOptionsReducer.ts, src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/reducers/index.ts, src/Akeneo/Pim/Structure/Bundle/Resources/public/less/attribute-option.less, tests/front/unit/structure/attribute-option/components/Edit.unit.tsx, tests/front/unit/structure/attribute-option/components/List.unit.tsx, tests/front/unit/structure/attribute-option/components/ListItem.unit.tsx, tests/front/unit/structure/attribute-option/reducers/attributeOptionsReducer.unit.ts
2 features in this PR: Attribute option deletion (with a confirmation modal) + new option cancellation.
=> DAPI-1038: Attribute options revamp - Remove an option

src/Akeneo/Pim/Structure/Component/Model/AttributeOptionInterface.php, src/Akeneo/Tool/Bundle/VersioningBundle/UpdateGuesser/AttributeOptionUpdateGuesser.php, src/Akeneo/Tool/Bundle/VersioningBundle/spec/UpdateGuesser/AttributeOptionUpdateGuesserSpec.php
As part of the Data-quality-insight features, we need to determine when an attribute option has been modified (to check the spelling). 
To do so, the chosen solution is to add versioning on the attribute options. It will be imperceptible for the users because the current history of the attributes will be unchanged. It will add entries in the versioning table when an option is created, deleted, sorted, and when a value is updated (for the entity `Akeneo\Pim\Structure\Component\Model\AttributeOption`)
=> DAPI-1008: Add versioning on attribute options

CHANGELOG-3.2.md, src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Attribute/OptionFilter.php
Same as https://github.com/akeneo/pim-community-dev/pull/12201 but for PIM 3.2.
=> PIM-9282 : make calling attribute options via API case unsensitive

src/Akeneo/Pim/Enrichment/Component/Product/Exception/ObjectNotFoundException.php
The phpDoc of [`ProductQueryBuilderInterface::addFilter()`](https://github.com/akeneo/pim-community-dev/blob/55841bceae131dbe475042f45fcf1d86ffb75745/src/Akeneo/Pim/Enrichment/Component/Product/Query/ProductQueryBuilderInterface.php#L30) states that it can only throw `\LogicException`, but some filters throw `ObjectNotFoundException`s, which directly extends the base `\Exception` …
=> RUL-276: ObjectNotFoundException extends \LogicException

CHANGELOG-5.0.md, CHANGELOG.md, src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
When deleting an association or a group linked to a published product, an error pop in is displayed but the message was the translation keys.
So, I added the translation keys in a jsmessages.en_US.yml file and associated them an error message. …
=> PIM-9289: Display a correct error message when deleting a group or an association 

CHANGELOG-4.0.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/lib/jquery.jstree.less
Fix : https://akeneo.atlassian.net/browse/PIM-9203
Remove box shadow from active select 2 container
=> PIM-9203: Fix box shadow category tree

src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptions.tsx, src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/List.tsx, src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/ListItem.tsx, src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/NewOptionPlaceholder.tsx, src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/contexts/LocalesContext.tsx, src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/hooks/index.ts, src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/hooks/useManualSortAttributeOptions.ts, src/Akeneo/Pim/Structure/Bundle/Resources/public/less/attribute-option.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/images/icon-row-move.svg, tests/front/unit/structure/attribute-option/components/List.unit.tsx, tests/front/unit/structure/attribute-option/components/ListItem.unit.tsx
=> DAPI-1036: allows attribute options to be manually reordered

src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/fetchers/baseFetcher.ts, src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/reducers/attributeOptionsReducer.ts, tests/front/unit/structure/attribute-option/reducers/attributeOptionsReducer.unit.ts
=> DAPI: fix options list when then backend returns an empty object where there is no option

src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/AttributeOptionsApp.tsx, src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/hooks/useAttributeOptions.ts, src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/reducers/attributeOptionsReducer.ts, src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/reducers/index.ts, tests/front/unit/structure/attribute-option/reducers/attributeOptionsReducer.unit.ts
This PR adds a fix to avoid a weird blinking effect when we display the options for an attribute AFTER having visited another one before : the options of the previous attribute were displayed, until the new options are loaded. Somehow the redux store is not resetted when we leave the page, so we have to clean it manually. …
=> DAPI-1076: ensure the redux store is resetted when unmounting the application

.circleci/config.yml, CHANGELOG.md, composer.json, composer.lock
The Phpstan `0.12.29` version seems to have introduced an issue and do not handle correctly this kind of forward/backward compatibilty tricks: https://github.com/symfony/event-dispatcher-contracts/blob/v1.1.7/Event.php with the `inteface_exists` condition.
Some tests fail whereas they don't have to.
I've decided to add the `psr/event-dispatcher` dependency to solve the error.
The `psr/event-dispatcher` will be used in upcoming version of symfony event dispatcher component https://github.com/symfony/event-dispatcher-contracts/blob/v2.1.2/Event.php#L14
PS: includes @rybus fixes regarding the terraform version used.
| --------------------------------- …
=> Add psr/event-dispatcher dependency

src/Akeneo/Pim/Enrichment/Component/Product/Updater/Adder/GroupFieldAdder.php, src/Akeneo/Pim/Enrichment/Component/Product/Updater/Clearer/Field/GroupFieldClearer.php, src/Akeneo/Pim/Enrichment/Component/Product/Updater/Remover/GroupFieldRemover.php, src/Akeneo/Pim/Enrichment/Component/Product/Updater/Setter/EnabledFieldSetter.php, src/Akeneo/Pim/Enrichment/Component/Product/Updater/Setter/GroupFieldSetter.php, tests/back/Pim/Enrichment/Specification/Component/Product/Updater/Adder/GroupFieldAdderSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Updater/Clearer/Field/GroupFieldClearerSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Updater/Remover/GroupFieldRemoverSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Updater/Setter/EnabledFieldSetterSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Updater/Setter/GroupFieldSetterSpec.php
When using `Akeneo\Pim\Enrichment\Component\Product\Updater` components for groups and status (enabled), we have to check that the target entity is a product
=> PIM-9295: Check that target is a product when adding, setting or removing groups

CHANGELOG-4.0.md, src/Akeneo/Pim/Structure/Bundle/Resources/config/validation/attribute.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/fields/select.js
Fixes an issue where an empty string was sent to the back when clearing the `Validation rule` simple select field, and was then rejected by the validation.
=> PIM-9294: Fix the removal of a validation rule in attribute edit form

CHANGELOG-4.0.md, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/normalizers.yml, src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/ProductNormalizer.php, tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/InternalApi/ProductNormalizerSpec.php
Fixes the "Missing attribute values" in the PEF when an attribute option/entity record/asset was deleted. The solution is to calculate the completeness of a product from its ValueCollection (from which the removed options were filtered at load) instead of its DB raw values.
This method is way slower, but as it's only used for one product (PEF display) I guess it's OK …
=> PIM-9279: Fix missing required attributes in PEF when an attribute option was deleted

CHANGELOG-4.0.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/grid/view-selector.js, src/Akeneo/UserManagement/Bundle/Resources/public/js/fields/default-product-grid-view.ts, src/Oro/Bundle/PimDataGridBundle/Controller/Rest/DatagridViewController.php
When fetching views from the view selector, it can happen that some views are filtered after the SQL query (for instance because of permissions, or because a category used in the filter was deleted...).
When that's the case, the number of results returned by the backend is less than the limit specified in the request, and the view selector considers that there are no more results (whereas there can be more), and the infinite scroll stops.
In order to solve this, I let the backend decide whether there are more results.
| Added …
=> PIM-9308: Fix infinite scroll in view selector when views are filtered

tests/front/unit/jest/unit.jest.js
Quick fix on the coverage unit front to skip the Image.tsx file. I can't test the logic in the onLoad.
=> GITHUB-APD-132: Fix coverage unit front

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/FieldContainer.less
Fix an issue on the icon size of multi-line validation error.
Before:
After:
=> CXP-347: fix validation error icon size

src/Akeneo/Tool/Component/Api/tests/integration/Normalizer/ProductNormalizerIntegration.php
Due to modification of technicalSql fixture those test does not pass.
This test was not launch in PR workflow (due to @group ce) only in nightly workflow
=> fix-nightly: fix missing nightly test

src/Akeneo/Connectivity/Connection/back/Infrastructure/ErrorManagement/DocumentationBuilder/AttributeValidation.php, src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/documentation.yml, src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/UniqueValue.php, src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/UniqueValueValidator.php, tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/UniqueValueValidatorSpec.php
Add default documentation for validation error on attributes
- enable it for UniqueValueValidator
=> CXP-365: add attribute validation documentation

tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/AbstractProductTestCase.php, tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/CreateProductEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/PartialUpdateListProductEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/PartialUpdateProductEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/CreateProductModelEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/PartialUpdateProductModelEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/QuantifiedAssociations/UpdateQuantifiedAssociationsInProductModelEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/ExternalApi/CreateVariantProductEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/ExternalApi/PartialUpdateListVariantProductEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/ExternalApi/PartialUpdateProductToVariantEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/ExternalApi/PartialUpdateVariantProductEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/ExternalApi/QuantifiedAssociations/AddQuantifiedAssociationsToVariantProductEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/ExternalApi/QuantifiedAssociations/DeleteQuantifiedAssociationsFromVariantProductEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/ExternalApi/QuantifiedAssociations/UpdateQuantifiedAssociationsInVariantProductEndToEnd.php, tests/back/Pim/Enrichment/Integration/Normalizer/Standard/ProductStandardSortedCollectionIntegration.php
This PR remove all @TODO MET-198 already done in https://github.com/akeneo/pim-community-dev/pull/12187 
This PR only add test on variant product
| Added acceptance tests            | Done
=> RAC-93: fix: remove @todo already done in previous tickets

src/Akeneo/Connectivity/Connection/back/Infrastructure/ErrorManagement/DocumentationBuilder/DefaultAttributeValidation.php, src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/documentation.yml, src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/ErrorManagement/DocumentationBuilder/DefaultAttributeValidationSpec.php, src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/IsNumeric.php, src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/IsNumericValidator.php, src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/Range.php, src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/RangeValidator.php, tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/IsNumericValidatorSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/RangeSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/RangeValidatorSpec.php
Add default documentation to:
13.6
13.11
13.12
13.16.1
13.16.2
=> CXP-366: add number validation documentation

.circleci/config.yml, .circleci/detect_structure_changes.sh, src/Akeneo/Platform/CommunityVersion.php, src/Akeneo/Tool/Bundle/ElasticsearchBundle/Client.php, tests/back/Platform/Specification/CommunityVersionSpec.php
https://github.com/akeneo/actionable-product-data/issues/158
It's currently not possible to know how many CE users installed master version.
Actually, it's mixed with 4.0.X, which is not good good for analytics.
So, the solution is to hardcode it. I added a test to avoid a mistake during a pull-up. 
*Note*: I changed the `detect_structure_changes.sh` script. Actually, changing the version name has an impact on this script, even if it's run only in EE.
It's because when we create an ES index, we prefix it with the version name from the CE. We were somehow "lucky" it worked.
It's totally useless to put the version name when creating an index. I did that when we switched from index to alias. It was to help at finding what was the previous …
=> GITHUB-APD-158: hardcode version name as master to allow correct analytics

CHANGELOG-3.2.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/attributes.js, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/edit-form.js, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/group-selector.js
**Issue:** When using the attribute group filter option on a product page, scrolling its attributes, and changing the attribute group, the PIM didn't display the top of the list, but the bottom. 
**Solution:** I added a reset function to set the scroll position to the top of the attribute list when selecting a new attribute group.
| …
=> PIM-9314: Reset scroll position when switching attribute group in the PEF

src/Akeneo/Pim/Structure/Bundle/Resources/config/validation/associationtype.yml, tests/back/Pim/Structure/Integration/AssociationType/Validation/AssociationTypeValidationIntegration.php
If the association type code is an integer, and since we use those association type codes as keys in associative arrays, when a json request is decoded, the code will be converted to the native type `integer` and the structure validation will fail.
The proposed solution is to forbid to have an integer only in association type code. …
=> RAC-95: Forbid association type code with integer only

CHANGELOG-4.0.md, src/Akeneo/Connectivity/Connection/front/src/audit/components/EventChart.tsx
**Issue** : In the Connection Dashboard, the dates were not correct for a user located in a timezone different than UTC.
_Example : 
In Boston, the dates displayed today (Friday, June 26) were the following:
Friday, Jun 19 / Saturday, Jun 20 / Sunday, Jun 21 / Monday, Jun 22 / Tuesday, Jun 23 / Wednesday, Jun 24 / Today_
The user timezone (set in the pim) was "crushed" by the browser timezone.
**Solution** : I added the timezone option 'UTC' to display correct dates.
_Now, today, with a browser's timezone set to 'EDT' (for example) the dates are:
Saturday, Jun 20 / Sunday, Jun 21 / Monday, Jun 22 / Tuesday, Jun 23 / Wednesday, Jun 24 / Thursday, Jun 24 / Today_
| Q …
=> PIM-9319: Fix date timezone for a correct display of the dates in the Connection Dashboard

CHANGELOG-3.2.md, src/Akeneo/Pim/Enrichment/Component/Product/Model/AbstractProduct.php
This pull request aims to fix the retrieving of used attributes for a product variant. It fixes the display of inherited attribute from model in PDF generation
=> PIM-9323: PDF doesn't export all Product Model values

CHANGELOG.md, src/Akeneo/Pim/Enrichment/Bundle/Resources/views/Product/renderPdf.html.twig
The product label is not showed when product attribute as name is localizable or scopable
=> PIM-9327: fix: the label value was not search by scope and locale in pdf export

CHANGELOG-4.0.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/locale_provider.yml
**Issue** : 
The en_GB UI language was no longer available in the local UI settings.
**Solution** : 
An "en_GB" translations file was already in the pim so I added the corresponding code (en_GB) in the locale_provider.yml file. …
=> PIM-9328: Add "en_GB" code to display the corresponding locale in the UI

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/Subsection.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/button/ActionButton.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/FilterBox.less
Fix also DAPI-1114 (grid)
Before products:
After products:
Before Grids:
After Grids:
=> DAPI-1115 fix filter label color and subsection font weight

src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Domain/Announcement/Model/Read/AnnouncementItem.php, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Infrastructure/CommunicationChannel/InMemory/InMemoryFindAnnouncementItems.php, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Infrastructure/CommunicationChannel/InMemory/serenity-updates.json, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/tests/Integration/Announcement/ListAnnouncementIntegration.php, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/tests/Unit/spec/Application/Announcement/Query/ListAnnouncementsHandlerSpec.php, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/tests/Unit/spec/Domain/Announcement/Model/Read/AnnouncementItemSpec.php, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/src/components/panel/announcement/Announcement.tsx, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/src/components/panel/announcement/Link.tsx, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/src/definitions/announcement.schema.json, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/tests/front/unit/__mocks__/dataProvider.ts, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/tests/front/unit/components/panel/Panel.unit.tsx
Ticket : https://github.com/akeneo/actionable-product-data/issues/172
It adds an id to know on which announcements users are clicking on (thanks to analytics). 
=> GITHUB-APD-172: I want to be able to track which announcements meet the most success in the communication panel 

src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Attribute/DateFilter.php, src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Field/DateTimeFilter.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/localization/presenters.yml, src/Akeneo/Pim/Enrichment/Component/Product/Query/Filter/FieldFilterHelper.php, tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/Date/DateFilterIntegration.php, tests/back/Pim/Enrichment/Integration/PQB/Filter/Field/DateTimeFilterIntegration.php, tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Filter/Attribute/DateFilterSpec.php, tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Filter/Field/DateTimeFilterSpec.php
Allows to use a relative datetime format in the ES' DateFilter and DateTimeFilter. 
The format is stricter than PHP allows, it must be: `now` or `+/-$count $unit` (`$count` is an integer and `$unit` is one of "day", "week", "month" or "year", with an optional final "s"; the DateTimeFilter also accepts "minute" and "hour")
| …
=> RUL-271: Allow relative dates for DateFilter and DateTimeFilter

src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Infrastructure/Framework/Symfony/Resources/public/bridge/view/panel.tsx, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Infrastructure/Framework/Symfony/Resources/public/less/components/Panel.less, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/src/components/panel/Header.tsx, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/src/components/panel/ListAnnouncement.tsx
Ticket : https://akeneo.atlassian.net/browse/DAPI-1085
Problem : It had a css bug triggered by Lucas when we opened a dropdown for the filter. It was displaying a part of the panel. Because of even when the panel was collapsed, it was considered as an element in the dom. It was just out of the screen.
Solution : Put a display none when the Panel is collapsed like that the element it's not considered as an element of the dom anymore.
| Changelog …
=> DAPI-1085: Fix css bug when collapsed panel

src/Akeneo/Connectivity/Connection/back/Infrastructure/ErrorManagement/DocumentationBuilder/DefaultAttributeValidation.php, src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/ErrorManagement/DocumentationBuilder/DefaultAttributeValidationSpec.php, src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/BooleanValueFactory.php, src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/Boolean.php, src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/BooleanValidator.php, tests/back/Pim/Enrichment/Specification/Component/Product/Factory/Value/BooleanValueFactorySpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/BooleanSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/BooleanValidatorSpec.php
- Change boolean validation error message and add it to the default documentation builder.
- Fix the `BooleanValueFactory.php` to only check that the attribute data is a scalar and let the validation stack check the boolean value
- and fixed the Boolean validator to do what the BooleanValueFactory was doing aka only check boolean value (and not 0|1)
| Micro Demo to the …
=> CXP-358: change boolean validation error message

.circleci/config.yml
This PR comes from a discussion we had with Juju. Sometimes the squads need to launch a regular CE build from a CE PR, just to ensure they didn't break some weird stuff in the Community Edition (probably due to a "sensitive" CE/EE override problem).
Currently, as I hope you know, a CE build actually checkouts the EE master and the proper CE branch. All EE tests are launched. And normally, EE tests also contains CE tests. A build is considered green when all EE tests are green. Which is really good, as our goal is to not break the SaaS offer when we merge a CE PR.
With this PR, you have a new approval step `ready_to_build_only_ce?`. This branch of the workflow will checkout the CE branch and launch only CE tests. **A PR is still considered mergeable when `pull_request_success` is green. …
=> TIP-1493: launch a "regular CE build" from the same PR workflow

src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Infrastructure/Framework/Symfony/DependencyInjection/AkeneoCommunicationChannelExtension.php, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Infrastructure/Framework/Symfony/Installer/InstallerSubscriber.php, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Infrastructure/Framework/Symfony/Installer/Query/CreateViewedAnnouncementsTableQuery.php, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Infrastructure/Framework/Symfony/Resources/config/installer.yml, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/tests/.php_cd.php, upgrades/schema/Version_5_0_20200630044018_create_communication_channel_viewed_announcements_table.php
Ticket : https://github.com/akeneo/actionable-product-data/issues/178
There will be notification if the user didn't see all announcements in the PIM. So, we need to track which announcements the user saw. It will be done in the created table. …
=> GITHUB-APD-178: Add akeneo_communication_channel_announcements_viewed table

src/Akeneo/Pim/Enrichment/Bundle/Resources/config/datagrid/association_group.yml
When displaying the associations with the mode `Display groups`, there was a `Filters` button floating.
Its only purpose was to open a panel with the same exact fitlers already visible: `label`, `is_associated`, `code`, `type`.
The solution suggested by our dear Stephane is to simply remove this button.
**before:**
**after:**
| …
=> RAC-51: Disable the manage filters button from associations group grid

src/Akeneo/Connectivity/Connection/back/tests/Integration/Persistence/Dbal/Repository/DbalEventCountRepositoryIntegration.php
Test on updated datetime was instable and not relevant is this case, I just deleted it
=> CXP-79: Remove instable datetime test

tests/back/Pim/Enrichment/Integration/Storage/Sql/Connector/SqlGetConnectorProductModelsIntegration.php
Since quantified associations of product model and variant products inherit quantified associations of parents those tests no longer pass
=> Fix quantified associations tests only launched on nightly

src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/attribute/index.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/attributes.js
When coming from the PEF, attribute labels should be in the locale selected in the PEF
To reproduce:
1. Set your locale in the product grid to FR
2. Go to attribute grid -> attribute labels are in French
3. Go to a product and click on the attribute labels with spelling mistakes linkExpected result: Attribute labels are in French - OK
4. Click on "back to products"
5. Change locale for EN
6. Click on the attribute labels with spelling mistakes link
Expected result: Attribute labels are in English - KO
Current result: Attribute labels are in French 
| Added legacy …
=> DAPI-1118: Preserve the selection of the catalogLocale when we navigate from the product edit form

config/services/test/test_services.yml, make-file/communication-channel.mk, make-file/test.mk, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Application/Announcement/Command/AddViewedAnnouncementsByUserCommand.php, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Application/Announcement/Command/AddViewedAnnouncementsByUserHandler.php, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Application/Announcement/Query/ListAnnouncementsHandler.php, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Domain/Announcement/Model/Read/AnnouncementItem.php, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Domain/Announcement/Model/Write/ViewedAnnouncement.php, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Domain/Announcement/Query/FindAnnouncementItemsInterface.php, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Domain/Announcement/Repository/ViewedAnnouncementRepositoryInterface.php, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Infrastructure/CommunicationChannel/InMemory/InMemoryFindAnnouncementItems.php, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Infrastructure/Delivery/InternalApi/Announcement/AddViewedAnnouncementsAction.php, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Infrastructure/Delivery/InternalApi/Announcement/ListAction.php, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Infrastructure/Framework/Symfony/DependencyInjection/AkeneoCommunicationChannelExtension.php, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Infrastructure/Framework/Symfony/Installer/Query/CreateViewedAnnouncementsTableQuery.php, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Infrastructure/Framework/Symfony/Resources/config/add_viewed_announcements.yml, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Infrastructure/Framework/Symfony/Resources/config/announcement_list.yml, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Infrastructure/Framework/Symfony/Resources/config/routing.yml, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Infrastructure/Persistence/Dbal/Repository/DbalViewedAnnouncementRepository.php, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Infrastructure/Persistence/InMemory/Repository/InMemoryViewedAnnouncementRepository.php, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/tests/.php_cd.php, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/tests/Integration/Delivery/InternalApi/Announcement/AddViewedAnnouncementsActionIntegration.php, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/tests/Integration/Delivery/InternalApi/Announcement/ListAnnouncementIntegration.php, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/tests/Integration/Persistence/Dbal/Repository/DbalViewedAnnouncementRepositoryIntegration.php, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/tests/Integration/Resources/config/in_memory.yml, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/tests/Unit/spec/Application/Announcement/Command/AddViewedAnnouncementsByUserHandlerSpec.php, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/tests/Unit/spec/Domain/Announcement/Model/Read/AnnouncementItemSpec.php, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/tests/phpstan-infra.neon, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/tests/phpstan.neon, upgrades/schema/Version_5_0_20200702232424_create_communication_channel_viewed_announcement_index.php
Ticket : https://github.com/akeneo/actionable-product-data/issues/179
There will be notification if the user didn't view all announcements in the PIM. So, we need to track which announcements the user saw. The table creation to track is done in the first commit (which is the PR https://github.com/akeneo/pim-community-dev/pull/12380).
But to flag an announcement as viewed, we need to expose it in a controller. That's the role of this PR: expose an HTTP endpoint to mark all the articles as viewed. …
=> GITHUB-APD-179: Add announcements viewed endpoint

.circleci/config.yml
The goal of the job `test_upgrade_from_serenity_to_master` is to install the latest Serenity and upgrade it to master. 
As it's stable, it is now integrated in the PR workflow.
=> TIP-1492: test_upgrade_from_serenity_to_master is stable now

src/Akeneo/Pim/Structure/Bundle/Resources/config/validation/associationtype.yml, tests/back/Pim/Structure/Integration/AssociationType/Validation/AssociationTypeValidationIntegration.php
This reverts commit 90bfe7bdb7be17ad768d6f2b2975a2c380a22d66.
We introduced a new constraint in RAC-95 which broke a customer environment, we are reverting the change.
This change was trying to prevent a bug which didn't happen yet.
This bug should be prevented by the work currently happening in https://akeneo.atlassian.net/browse/RAC-103 …
=> PIM-9348: Revert RAC-95

CHANGELOG-4.0.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/Grid.less
In the record list, when the image is not loading, it's 1px taller than expected, breaking the alignement of the list.
A simple overflow hidden enforce the image size.
=> PIM-9349: Fix record list alignment when images are loading indefinitely

src/Akeneo/Pim/Enrichment/Component/Product/Model/EntityWithQuantifiedAssociationsInterface.php, src/Akeneo/Pim/Enrichment/Component/Product/Model/QuantifiedAssociation/EntityWithQuantifiedAssociationTrait.php, src/Akeneo/Pim/Enrichment/Component/Product/Model/QuantifiedAssociation/QuantifiedAssociations.php, src/Akeneo/Pim/Enrichment/Component/Product/QuantifiedAssociation/QuantifiedAssociationsMerger.php, src/Akeneo/Pim/Enrichment/Component/Product/Updater/Adder/QuantifiedAssociationFieldAdder.php, tests/back/Pim/Enrichment/Specification/Component/Product/Model/QuantifiedAssociation/QuantifiedAssociationsSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/QuantifiedAssociation/QuantifiedAssociationsMergerSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Updater/Adder/QuantifiedAssociationFieldAdderSpec.php
This PR contain refactor of function merge in QuantifiedAssociations class. 
This function is now immutable. 
This use array_replace_recursive instead of using several loops 
=> RAC-118: refactor: make QuantifiedAssociations immutable

CHANGELOG-4.0.md, src/Akeneo/Pim/Enrichment/Bundle/Resources/views/Product/renderPdf.html.twig
The pdf renderer expect every attribute value to be an object with `__toString`.
In some cases, it does not work because the content is already a string (`pim_catalog_simpleselect` and `pim_catalog_multiselect` are already converted to string before that line).
A simple fix is to use `|trim` instead of `.__toString()` because the twig trim filter always cast the value to a string with `(string)$value` and it will work for both cases (objects implementing `__toString` and strings)
| Added …
=> PIM-9344:  Correctly convert variable to string in pdf renderer

CHANGELOG-4.0.md, src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/select-filter.js
The job and connector labels were not sorted by alphabetical order on associated menus on Imports and Exports pages.
So, I added 2 functions :
1 - to translate the label keys
2 - and then to sort them by alphabetical order …
=> PIM-9330: Sort jobs and connectors by alphabetical order on associated menus on Imports and Exports pages.

src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/src/components/panel/AnnouncementList.tsx, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/src/components/panel/Panel.tsx, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/src/hooks/useInfiniteScroll.ts, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/src/reducers/infiniteScrollReducer.ts, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/tests/front/unit/components/panel/AnnouncementList.unit.tsx, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/tests/front/unit/components/panel/Panel.unit.tsx, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/tests/front/unit/reducers/infiniteScrollReducer.unit.ts, tests/front/unit/jest/unit.jest.js
Ticket : https://github.com/akeneo/actionable-product-data/issues/188
- Optimise the fetch of the announcement list to do it when we open the panel instead of doing it when we mount the component. Moreover, we don't need to refresh the list when we close the panel anymore.
- Fix bug with the last append. In fact, I spotted a bug when we re-open the panel after we have already scrolled all the pages. We couldn't scroll the pages anymore.
- Update to scroll top when we close the panel. If we re-opened the panel after we have already scrolled some pages, the scroll would be at the end of the first page (because of the load of the first elements only). In order to have a better UX, we scroll top to the panel when we close it.
- Improve …
=> GITHUB-APD-188: Update to fetch announcements only when we open the panel

CHANGELOG.md, src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Product/QuantifiedAssociation/GetProductModelQuantifiedAssociationsByProductIdentifiers.php, src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Product/QuantifiedAssociation/GetProductQuantifiedAssociationsByProductIdentifiers.php, src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductModel/QuantifiedAssociation/GetProductModelQuantifiedAssociationsByProductModelCodes.php, src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductModel/QuantifiedAssociation/GetProductQuantifiedAssociationsByProductModelCodes.php, tests/back/Pim/Enrichment/Integration/Storage/Sql/Product/QuantifiedAssociation/GetProductModelQuantifiedAssociationsByProductIdentifiersIntegration.php, tests/back/Pim/Enrichment/Integration/Storage/Sql/Product/QuantifiedAssociation/GetProductQuantifiedAssociationsByProductIdentifiersIntegration.php, tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductModel/QuantifiedAssociation/GetProductModelQuantifiedAssociationsByProductModelCodesIntegration.php, tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductModel/QuantifiedAssociation/GetProductQuantifiedAssociationsByProductModelCodesIntegration.php
**Context:** the upcoming feature about quantified associations has been merged regularly on master during the development, with a feature flag disabling the UI.
Apparently, there was an earlier version saving `[]` in the json column instead of `NULL` when there was no quantified associations.
This is not happening anymore, we have a lot of validation before saving the quantified associations now.
Since the last release (2 days ago), the quantified associations are exposed in the external api endpoint for GET products (it's not documented yet). 
The query for returning the quantified associations:
```
SELECT
p.identifier,
JSON_MERGE_PRESERVE(COALESCE(pm2.quantified_associations, '{}'), COALESCE(pm1.quantified_associations, '{}'), …
```
=> PIM-9356: Fix external api endpoint for products with invalid quantified associations

CHANGELOG-4.0.md, src/Akeneo/Tool/Bundle/ElasticsearchBundle/IndexConfiguration/Loader.php, src/Akeneo/Tool/Bundle/ElasticsearchBundle/spec/IndexConfiguration/LoaderSpec.php, src/Akeneo/Tool/Bundle/ElasticsearchBundle/spec/IndexConfiguration/conf1.yml, src/Akeneo/Tool/Bundle/ElasticsearchBundle/spec/IndexConfiguration/conf2.yml, src/Akeneo/Tool/Bundle/ElasticsearchBundle/spec/IndexConfiguration/conf3.yml
Since 4.0 the ES configuration files doesn't include the index name anymore. However, the ES config loader has not been updated accordingly to that.
=> PIM-9359: Fix ES configuration override for dynamic templates

src/Akeneo/Pim/Enrichment/Component/Product/Model/EntityWithQuantifiedAssociationsInterface.php, src/Akeneo/Pim/Enrichment/Component/Product/Model/QuantifiedAssociation/EntityWithQuantifiedAssociationTrait.php, src/Akeneo/Pim/Enrichment/Component/Product/Model/QuantifiedAssociation/QuantifiedAssociations.php, src/Akeneo/Pim/Enrichment/Component/Product/Updater/Clearer/Field/QuantifiedAssociationFieldClearer.php, src/Akeneo/Pim/Enrichment/Component/Product/Updater/Setter/QuantifiedAssociationsFieldSetter.php, tests/back/Pim/Enrichment/Integration/Storage/Sql/Product/QuantifiedAssociation/GetProductModelQuantifiedAssociationsByProductIdentifiersIntegration.php, tests/back/Pim/Enrichment/Integration/Storage/Sql/Product/QuantifiedAssociation/GetProductQuantifiedAssociationsByProductIdentifiersIntegration.php, tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductModel/QuantifiedAssociation/GetProductModelQuantifiedAssociationsByProductModelCodesIntegration.php, tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductModel/QuantifiedAssociation/GetProductQuantifiedAssociationsByProductModelCodesIntegration.php, tests/back/Pim/Enrichment/Specification/Component/Product/Model/ProductModelSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Model/QuantifiedAssociation/QuantifiedAssociationsSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Updater/Setter/QuantifiedAssociationsFieldSetterSpec.php
Goals of this PR : 
- Remove all logic into EntityWithQuantifiedAssociationTrait this class should only be a "passe plat"
- Remove setQuantifiedAssociations from EntityWithQuantifiedAssociationTrait => business logic should be into domain not in services
| Tech Doc …
=> RAC-119: move business logic into QuantifiedAssociations class to remove setQuantifiedAssociations

CHANGELOG.md, src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Field/FamilyFilter.php, tests/back/Pim/Enrichment/Integration/PQB/Filter/Field/FamilyFilterIntegration.php, tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Filter/Field/FamilyFilterSpec.php
**Before:** 
The rules were case sensitive. Meaning if you used a family code for your rule with no uppercase while your family code actually started with an uppercase then the rule didn't recognize it and so didn't find any product to apply the rule to.
**Solution:** 
In the FamilyFilter class, I added a way to replace the value by its familyCode. …
=> PIM-9357: Make rules case-insensitive so it complies with family and attribute codes

composer.lock, phpstan.neon
The "ignoreErrors" are regular expressions in phpstan config file, so special chars should be escaped. This updates phpstan's version to v0.12.33 in composer.lock, as well as some other packages (symfony/flex, symfony/polyfill* , theseer/tokenizer and aws/aws-sdk-php)
| …
=> Fix regular expression in phpstan config file

CHANGELOG-4.0.md, src/Akeneo/Pim/Enrichment/Bundle/Resources/views/Product/renderPdf.html.twig
In the pdf renderer of products, for attribute of type `pim_catalog_image`, the twig was trying to access `content.media`.
`content` is the attribute value and it's an object with the class `Akeneo\Pim\Enrichment\Component\Product\Value\MediaValue`:
https://github.com/akeneo/pim-community-dev/blob/3a6cd4edb7e3182cd79cbfe9c4ae2aa3d01e6a45/src/Akeneo/Pim/Enrichment/Component/Product/Value/MediaValue.php#L9-L18
The problem is, this class do not have a property `media`, it's called `data`.
see https://github.com/akeneo/pim-community-dev/blob/3a6cd4edb7e3182cd79cbfe9c4ae2aa3d01e6a45/src/Akeneo/Pim/Enrichment/Component/Product/Value/MediaValue.php#L34-L37
Since it was not accessible, the fallback to `__toString` was used, returning the key of …
=> Fix pdf renderer for image attributes

CHANGELOG-3.0.md, src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Attribute/OptionFilter.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/elasticsearch/product_mapping.yml, src/Akeneo/Pim/Enrichment/Bundle/Resources/elasticsearch/settings.yml
Same as https://github.com/akeneo/pim-community-dev/pull/12201 but for PIM 3.0.
For 3.0, it will be necessary to reset indices before re-indexing
=> PIM-9282 : make calling attribute options via API case insensitive (PIM 3.0)

CHANGELOG.md, src/Akeneo/Platform/Bundle/AnalyticsBundle/Resources/views/SystemInfo/index.html.twig
In System Information page, pim_analytics.info_type.api_connection related information was not relevant 
(because of specific data format) :
_Array
Array
Array._
So, I adapt the twig file in order to display a list of number for each type of connection 
(tracked and untracked, to respect the format):
_Data Destination tracked : 12
Data Destination untracked : 3
Data Source tracked : 0
Data Source untracked : 2
Other tracked : 4
Other untracked : 1_
(I added the translations in the corresponding EE PR) …
=> PIM-9362: Adapt System Information twig file for API connections display

CHANGELOG.md, src/Akeneo/Pim/Structure/Bundle/Controller/ExternalApi/AttributeController.php, src/Akeneo/Pim/Structure/Bundle/Doctrine/ORM/Repository/ExternalApi/AttributeRepository.php, tests/back/Pim/Structure/EndToEnd/Attribute/ExternalApi/ListAttributeEndToEnd.php
Update the API endpoint `/api/rest/v1/attributes` to able to get all attributes given a list of attribute codes `/api/rest/v1/attributes?search={"code":[{"operator":"IN","value":["code1","code2"]}]}`.
| Added EndToEnd               | OK
`Todo`: …
=> API-1201: Be able get attributes searching by codes

src/Akeneo/Tool/Bundle/ElasticsearchBundle/Client.php, src/Akeneo/Tool/Bundle/ElasticsearchBundle/spec/ClientSpec.php
Elasticsearch has a parametrized maximum request body size when indexing. (http.max_content_length, 100MB by default). If the request body is exceeded it will throw a 413 error (Request Entity Too Large), leading to an uncaught exception in the PIM. When indexing a large amount of products with a lot of data (e.g when reindexing products via the pim:product:index command), this body size can be exceeded.
This PR set a size limite for the query (100 MB) and split the query into multiple calls if it is exceeded.
The responses are then merged before returning.
=> PIM-9361: Chunk large ES query

CHANGELOG.md, config/bootstrap.php
Environment variables declared outside of the PIM were not integrated in production mode when the .env file is compiled.
=> TIP-1513: Fixing env variables not available from outside

CHANGELOG-4.0.md, src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Product/GetValuesAndPropertiesFromProductIdentifiers.php
Trying to mitigate memory usage by breaking down the query with a CTE for the group codes, the combination of the JSON array aggregate & the JSON merge on the raw values was overflowing the `sort_buffer_size` which is set at 256Kb …
=> PIM-9358: Break down values & properties query with CTE to use less memory

src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Application/Announcement/Query/HasNewAnnouncementsHandler.php, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Application/Announcement/Query/HasNewAnnouncementsQuery.php, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Application/Announcement/Query/ListAnnouncementsHandler.php, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Application/Announcement/Query/ListAnnouncementsQuery.php, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Domain/Announcement/Query/FindAnnouncementItemsInterface.php, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Domain/Announcement/Query/FindNewAnnouncementIdsInterface.php, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Infrastructure/CommunicationChannel/Api/ApiFindAnnouncementItems.php, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Infrastructure/CommunicationChannel/Api/ApiFindNewAnnouncementIds.php, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Infrastructure/CommunicationChannel/LocalFilestorage/LocalFilestorageFindAnnouncementItems.php, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Infrastructure/CommunicationChannel/LocalFilestorage/LocalFilestorageFindNewAnnouncementIds.php, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Infrastructure/Delivery/InternalApi/Announcement/HasNewAnnouncementsAction.php, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Infrastructure/Delivery/InternalApi/Announcement/ListAnnouncementsAction.php, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/tests/Integration/CommunicationChannel/Api/ApiFindAnnouncementItemsIntegration.php, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/tests/Integration/CommunicationChannel/Api/ApiFindNewAnnouncementIdsIntegration.php, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/tests/Integration/CommunicationChannel/Api/Expectations/firstAnnoucements.json, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/tests/Integration/CommunicationChannel/Api/Expectations/newAnnouncements.json, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/tests/Integration/CommunicationChannel/Api/Expectations/nextAnnoucements.json, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/tests/Unit/spec/Application/Announcement/Query/HasNewAnnouncementsHandlerSpec.php, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/tests/Unit/spec/Application/Announcement/Query/ListAnnouncementsHandlerSpec.php
Add the locale in query parameters to translate the announcements in the user locale. 
For now, we don't translate announcements (only english is supported). This parameter is therefore useless *for now*.
But as this feature will be backported in previous version and people migrates the PIM to a next patch ~6 months, it's better to anticipate it (instead of adding it in another patch).
| Review …
=> GITHUB-APD-195: add locale to translate the announcements if it's needed in the future

CHANGELOG-4.0.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/attribute-group/form/tab/select.js
Fix https://akeneo.atlassian.net/browse/PIM-9379
The catralog locale was missing in the attribute search request. So the search by label could not working.
=> PIM-9379: fix attribute search by label in attribute group section

src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/actions-panel.js, src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/quickexport/component/Form.tsx, src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/quickexport/component/Option.tsx, src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/quickexport/component/QuickExportConfigurator.tsx, src/Oro/Bundle/PimDataGridBundle/tests/front/unit/QuickExportConfigurator.unit.tsx
Add a boolean prop to show the select for with-labels options
=> RAC-175: Rework QuickExportConfigurator to hide with-labels select

CHANGELOG-4.0.md, src/Akeneo/Pim/Enrichment/Component/Product/Factory/EmptyValuesCleaner.php, tests/back/Pim/Enrichment/Specification/Component/Product/Factory/EmptyValuesCleanerSpec.php
I was fooled by the API return example and was trying with prices, but the problem is only with metric attributes.
I greped the provided dump and found that we have raw values like that: 
```
"weight": {"<all_channels>": {"<all_locales>": {"unit": null, "amount": null, "family": "Weight", "base_data": null, "base_unit": "KILOGRAM"}}}
```
The EmptyCleaner consider them as filled because of not null values in `family` and `base_unit` values.
This is a quick fix for invalid data coming from previous migrations and we must set a migration for 4.0 -> 5.0 to really clean the data and not have to handle it at product load.
There is a PR for that: https://github.com/akeneo/pim-community-dev/pull/11628
=> PIM-9112: Fix publish product if metric with null values

src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/src/components/panel/AnnouncementList.tsx, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/src/components/panel/Panel.tsx, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/src/hooks/useInfiniteScroll.ts, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/tests/front/unit/components/panel/AnnouncementList.unit.tsx, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/tests/front/unit/components/panel/Panel.unit.tsx, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/tests/front/unit/hooks/useInfiniteScroll.unit.tsx
Two things:
- modify the threshold to fetch the next announcements (as it's search after), it was done too late when scrolling down
https://github.com/akeneo/actionable-product-data/issues/206
- it was hardcoded to fetch the announcements only in Serenity. This is not the case anymore. It asks both for Serenity and CE.
https://github.com/akeneo/actionable-product-data/issues/204
Note: there was an infinite loop when an error occured, because the AnnouncementList component listen on "state" in a `useEffect`. I extracted this logic as it was not correct to put it in `useEffect`.
Unfortunately, I can't reproduce it in unit test :/
It was completely blocking the browser.
| Q …
=> GITHUB-APD-206: modify the treshold to fetch next announcements in the panel

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/menu/help.ts
On CE master, it's currently a 404 when clicking on the helpcenter button. It redirects now to serenity as soons as the version is not a number version (master, v20201009180000).
`OK`: Done / …
=> GITHUB-APD-126: helpcenter link button redirects to serenity for CE master and Serenity

CHANGELOG-4.0.md, src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Attribute/AbstractAttributeFilter.php, src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Attribute/DateFilter.php, src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Attribute/MediaFilter.php, src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Attribute/MetricFilter.php, src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Attribute/NumberFilter.php, src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Attribute/OptionFilter.php, src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Attribute/PriceFilter.php, src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Attribute/ReferenceDataFilter.php, src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Attribute/TextAreaFilter.php, src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Attribute/TextFilter.php, src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/ProductAndProductModelSearchAggregator.php, tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/EmptyFilterWithProductsAndProductModelsIntegration.php, tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/Media/LocalizableFilterIntegration.php, tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/Media/ScopableFilterIntegration.php, tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/ReferenceData/ReferenceDataSimpleSelectFilterIntegration.php, tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Filter/Attribute/DateFilterSpec.php, tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Filter/Attribute/MediaFilterSpec.php, tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Filter/Attribute/MetricFilterSpec.php, tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Filter/Attribute/NumberFilterSpec.php, tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Filter/Attribute/OptionFilterSpec.php, tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Filter/Attribute/PriceFilterSpec.php, tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Filter/Attribute/ReferenceDataFilterSpec.php, tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Filter/Attribute/TextAreaFilterSpec.php, tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Filter/Attribute/TextFilterSpec.php, tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/ProductAndProductModelSearchAggregatorSpec.php
In #11518, the usage of attribute filters' EMPTY operator was fixed, adding a should clause testing that the target attribute had to be part of either the 'attributes_for_this_level' list or in the 'attributes_of_ancestors' one. Unfortunately the fix was only applied in ProductAndProductModelWithSearchAggregator (i.e the product grid's query builder). 
This leads ES queries with an EMPTY filter returning wrong results in other PQBs, especially when there are models and variants involved (see examples in #11518) => this can cause some mass actions (including mass delete) to affect more entities than desired.
In this PR I apply the should clause directly in the attribute filters, the final query being:
- the ES attribute path must must not exist
AND
- the 'attributes_for_this_level' must …
=> PIM-9401: Fix ES filters with EMPTY operator

src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/Domain/Announcement/Model/Read/AnnouncementItem.php
Not testable as we can't easily mock  "new \datetime" in PHP.
When end date of notifcation is 12/06 and we are the 12/06, the comparison of the date was "12-06-2020 16:01:10" <  "12-06-2020 00:00:00" because `new \Datetime` returns the date with the current hour/minute/second, which is not what we want.
Link to https://github.com/akeneo/actionable-product-data/issues/213 …
=> GITHUB-APD-213: fix display of new tag when current date equals start date

CHANGELOG.md, src/Akeneo/Pim/Enrichment/Component/Product/Builder/EntityWithValuesBuilder.php, tests/back/Pim/Enrichment/Specification/Component/Product/Builder/EntityWithValuesBuilderSpec.php
As of v4.0, empty values are not persisted anymore, and empty values are filtered. However the format of price and measurement attributes is a bit more complex than for other attributes (complex array), and the check performed to check if the value is empty did not take these formats into account.
In this PR we consider that a price or a measurement with a `null` amount is empty, and we filter these values.
| …
=> PIM-9391: Filter empty price and measurement values

CHANGELOG.md, src/Akeneo/Pim/Structure/Component/Model/AttributeGroupInterface.php
For entities persisted via doctrine ORM, if one need to have the "updated_at" field of this entity updated on save. This entity needs to implement the `TimestampableInterface` so that the subscriber https://github.com/akeneo/pim-community-dev/blob/master/src/Akeneo/Tool/Bundle/VersioningBundle/EventSubscriber/TimestampableSubscriber.php will catch this entity on preSave and automatically updates the updated_at field. …
=> PIM-9408: Fix attribute group's updated_at field udpate

src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Subscriber/Product/InitializeEvaluationOfAProductSubscriber.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/subscribers.yml, src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Subscriber/Product/InitializeEvaluationOfAProductSubscriberSpec.php
The problem occurs only when saving a single product (unitary update). The ES query that updates the rates can be in conflict with the ES query that re-index the product.
The solution is to not update the rates in ES anymore, and prioritize the evaluation to do it before the full indexation.
=> DAPI-1231: Fix possible ES conflicts when updating product rates

CHANGELOG-4.0.md, src/Akeneo/Tool/Component/Connector/Archiver/AbstractInvalidItemWriter.php
Fix incorrect use of `Akeneo\Tool\Component\Batch\Item\InvalidItemInterface`
=> PIM-9426: Fix incorrect interface use

CHANGELOG.md, src/Akeneo/Pim/Structure/Bundle/Resources/config/model/doctrine/Attribute.orm.yml, upgrades/schema/Version_5_0_20200827093636_increase_attribute_max_characters.php
The database field type was not good. We should support at least 65535 characters.
=> PIM-9425: Fix inaccurate attribute max characters

.circleci/config.yml, .circleci/run_behat.sh
Adds a log when retrying a Behat test. The log will be stored as an artifact on Circle CI side.
The main goal is to have Behat stable enough that the retry system is not needed anymore. First step is to get the current state of the retries by logging them and analyzing after one week of run. …
=> BH-7 Logs Behat tests retried

CHANGELOG.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/creation/modal/create-user.js, src/Akeneo/UserManagement/Bundle/Resources/config/form_extensions/create.yml, src/Akeneo/UserManagement/Bundle/Resources/config/validation.yml, tests/back/UserManagement/Integration/Component/Updater/UserUpdaterIntegration.php
- Disable save button when user creation form is not ready to submit by adding a custom modal form.
- Add `NotBlank` constraint on password field to have a proper validation error instead of a `500`.
`OK`: Done / …
=> PIM-9371: Disable save button when user creation form is not ready to submit

src/Akeneo/Pim/Enrichment/Component/Product/Connector/FlatTranslator/AttributeValue/MetricTranslator.php, tests/back/Pim/Enrichment/Specification/Component/Product/Connector/FlatTranslator/AttributeValue/MetricTranslatorSpec.php
When doing an export with label, values in metric column are translated. Problem is when the value is empty, the translation is not found => The value is transformed under bracket but value is empty
`OK`: Done / …
=> RAC-219: fix unit value translation is filled with '[]' when product does not have value on unit

CHANGELOG-3.2.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/grid/mass-actions.js
When selecting ALL entities with a label filter and then clearing the label filter, the results counter was displaying an erroneous value, this PR updates the counter to show the effective affected products when selecting ALL items. …
=> PIM-9427: Update datagrid selection count when clearing filter

CHANGELOG-3.2.md, src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Attribute/AbstractAttributeFilter.php, src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Attribute/IsEmpty/DateFilter.php, src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Attribute/IsEmpty/MediaFilter.php, src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Attribute/IsEmpty/MetricFilter.php, src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Attribute/IsEmpty/NumberFilter.php, src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Attribute/IsEmpty/OptionFilter.php, src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Attribute/IsEmpty/PriceFilter.php, src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Attribute/IsEmpty/ReferenceDataFilter.php, src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Attribute/IsEmpty/TextAreaFilter.php, src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Attribute/IsEmpty/TextFilter.php, src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/ProductAndProductModelSearchAggregator.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/query_builders.yml, tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/EmptyFilterWithProductsAndProductModelsIntegration.php, tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/ProductAndProductModelSearchAggregatorSpec.php
A fix (https://github.com/akeneo/pim-community-dev/pull/12567) about Elasticsearch filters with EMPTY operators was merged in `4.0` and used fields (`attributes_for_this_level` and `attributes_of_ancestors`) which are not present in all indexes that we had in `3.2`. This PR adds specific filters for the EMPTY operator to use only the index that has these fields.
Note: these specific filters are irrelevant in `4.0` and should be removed during the next pull-up …
=> PIM-9402: Add new ES filters for EMPTY operator

CHANGELOG-3.2.md, src/Akeneo/Pim/Structure/Bundle/Resources/config/routing.yml, src/Akeneo/Pim/Structure/Bundle/Resources/config/routing/front.yml, src/Akeneo/Pim/Structure/Bundle/Resources/config/routing/internal_api/associationtype.yml, src/Akeneo/Pim/Structure/Bundle/Resources/config/routing/internal_api/family.yml, src/Akeneo/Pim/Structure/Bundle/Resources/config/routing/internal_api/family_variant.yml, src/Akeneo/Pim/Structure/Bundle/Resources/config/routing/internal_api/grouptype.yml, tests/front/integration/pimenrich/fetcher/family-fetcher.integration.js
Given the right parameters, a number of routes can be mistaken for one another.
For instance, after creating a `rest` family from the UI, the modal redirects to the `pim_enrich_family_edit` (`/configuration/family/{code =  rest}/edit`), but the front router first matches the `pim_enrich_family_rest_get` route (`/configuration/family/rest/{identifier = edit}`), resulting in a 404
This PR aims at fixing these routes, only modifying paths for `internal_api` routes, as frontend ones may be bookmarked by users. Obviously I didn't update the `external_api` ones.
I couldn't think of any side effect, as I didn't change the route names or their parameters, feel free to point out my mistake if you find a counterexample though.
**Definition Of …
=> PIM-9101: Fix ambiguous internal_api route paths

upgrades/schema/Version_5_0_20200826153300_add_primary_key_connection.php
Fixes wrong order: constraints need to be remove before indexes. Also DROP CONSTRAINT doesn't exist for MySQL.
=> Fixes wrong order: constraints need to be remove before indexes

upgrades/schema/Version_5_0_20200826153300_add_primary_key_connection.php
Index from foreign key are automatically removed by foreign key dropped.
The current code generated problems as it registered the DROP of the foreign key and the drop of the index.
Then all the "added" SQL is executed sequentially and when it's time to remove fhe index from foreign key, the code goes into error as the index has already been removed by the drop of the FOREIGN KEY. …
=> Index from foreign key are automatically removed by foreign key dropped

akeneo-design-system/.github/workflows/npm-publish.yml
Github action executed on the read-only repository that published the package to npm.
=> RAC-204: Add publish to npm github action

CHANGELOG-4.0.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/column-tabs-navigation.js
The asset menu was duplicated when saving the PEF:
A fix has been done in the `master` branch in [this PR](https://github.com/akeneo/pim-community-dev/commit/89118a466118b2cdae6be911883e525405223f73#diff-23012730008abf6dd08375d900598d73).
On the Onboarder, we are still using the 4.0.x version of CE & EE so this PR backports the fix in `4.0`. …
=> AOB-1023: Fix duplicated assets menu in PEF

CHANGELOG-4.0.md, CHANGELOG.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/config-provider.js
We are loading extensions dynamically at page load and the `extensions.json` caused cache issues because it's "versioned" like other javascript assets.
By adding a random query string parameter, we will force it to be refreshed.
Note on perfs: with this query string, it is not cached anymore. But it's not a real problem because it's loaded only on HTML page refresh when the rest of the PIM is mainly a SPA. It will mainly be on login, so not very often for the same user.
=> PIM-9443: Do not cache extensions.json

CHANGELOG-4.0.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/bootstrap-switch/bootstrap.switch.js
On compare/translate page, bootstrapSwitch is called twice on switcher => this function add div on parent div of checkbox input. 
Here we do not add div when div already have "has-switch" class
`OK`: Done / …
=> PIM-9445: fix switch is broken on compare/translate when attribute is localisable or scopable

CHANGELOG-4.0.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/FieldContainer.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/product/field/multi-select.html, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/product/field/simple-select.html
On PEF, the attribute of type simple and multi select are handled by select2. On initilization, select2 create a div in specific height but before the div height :
- Is equal to 39px when the "+" is displayed
- Is equal to 0px when the user does not have access to edit attribute
On this PR :
Fix the size of simple/multi select container …
=> PIM-9439: fix PEF shakes on product with lot of simple/multi select

CHANGELOG-3.2.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/Column.less
=> AOB-1080: fix pim/onboarder logo submenu display under collapsed column

make-file/test.mk, upgrades/test_schema/ExecuteMigrationTrait.php
The rollback migrations are not implemented in the application. So we test that they fail with an error. But the error is displayed in the output of the test, which can be very confusing.
And the CommandLauncher service is not able to redirect the error output. So the trait doesn't use it anymore. 
The PR allows as well the possibility to run the migration tests locally through the makefile  …
=> BH-46 Avoid polluting test migration output

CHANGELOG-3.2.md, src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/ComputeDataRelatedToFamilyProductsTasklet.php, src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/ComputeDataRelatedToFamilyRootProductModelsTasklet.php, src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/ComputeDataRelatedToFamilySubProductModelsTasklet.php, tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Job/ComputeDataRelatedToFamilyProductsTaskletSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Job/ComputeDataRelatedToFamilyRootProductModelsTaskletSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Job/ComputeDataRelatedToFamilySubProductModelsTaskletSpec.php
Actually on ComputeDataRelatedToFamilyProductsTasklet, ComputeDataRelatedToFamilyRootProductModelsTasklet and ComputeDataRelatedToFamilySubProductModelsTasklet we call clear function on UnitOfWork when product to save is equal to the batch size. 
Problem is when product or product model is invalid. UnitOfWork clear and Cursor fetch data are desynchronized. When it the case, we have in cursor versionA of FamilyVariant and a versionB when we fetch Product/ProductModel on save (due to permission fullProduct). Those two versions are totally same but for Doctrine they are different due to clear function call.
| …
=> PIM-9450: Fix error during family import, compute products/product models doesn't work when products/product models are skipped

tests/front/unit/jest/unit.jest.js
Currenly, the 3.2 nightly does not pass. 
Reason ? yarn.lock is not versionned only in pim-enterprise 3.2. 
But this problem will arrived when we are going to update dependency on others versions
Reproduce in locale in pim-enterprise-dev 3.2: 
```
rm -rf yarn.lock
docker-compose run --rm node yarn install
docker-compose run --rm node yarn run unit src/Akeneo/ReferenceEntity/tests/front/unit/akeneoreferenceentity/domain/model/attribute/type/text/validation-rule.unit.ts
```
Why this error now ?
A new version of https://github.com/es-shims/String.prototype.trim have been released it require version es-abstract: 1.18.0. Due to conflict with other package that require es-abstract 1.17.*, yarn download es-abstract: 1.18.0 into node_modules of …
=> fix: Cannot find module 'es-abstract/2020/RequireObjectCoercible' from 'implementation.js'

.env, CHANGELOG-4.0.md, config/services/pim_parameters.yml, src/Akeneo/Pim/Enrichment/Bundle/Filter/ProductEditDataFilter.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/elasticsearch/settings.yml, src/Akeneo/Tool/Bundle/ElasticsearchBundle/DependencyInjection/AkeneoElasticsearchExtension.php, src/Akeneo/Tool/Bundle/ElasticsearchBundle/IndexConfiguration/Loader.php, src/Akeneo/Tool/Bundle/ElasticsearchBundle/spec/IndexConfiguration/LoaderSpec.php, src/Akeneo/Tool/Bundle/ElasticsearchBundle/spec/IndexConfiguration/conf4.yml
Total_fields limit of elasticsearch should be configurable on 4.0 instances.
PR done for master => https://github.com/akeneo/pim-community-dev/pull/11838
=> [Backport master => 4.0] PIM-9455: Make total_fields limit of elasticsearch configurable

CHANGELOG.md, src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Attribute/NumberFilter.php, src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Attribute/TextAreaFilter.php, src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Attribute/TextFilter.php, src/Akeneo/Pim/Enrichment/Component/Product/Query/Filter/FieldFilterHelper.php, tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/Media/MediaFilterIntegration.php, tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/Number/NumberFilterIntegration.php, tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/Text/TextFilterIntegration.php, tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/TextArea/TextAreaFilterIntegration.php, tests/back/Pim/Enrichment/Integration/PQB/Filter/Field/IdFilterIntegration.php, tests/back/Pim/Enrichment/Integration/PQB/Filter/Field/IdentifierFilterIntegration.php, tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Filter/Attribute/IdentifierFilterSpec.php, tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Filter/Attribute/MediaFilterSpec.php, tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Filter/Attribute/NumberFilterSpec.php, tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Filter/Attribute/TextAreaFilterSpec.php, tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Filter/Attribute/TextFilterSpec.php, tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Filter/Field/EntityTypeFilterSpec.php, tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Filter/Field/IdentifierFilterSpec.php
We currently accept null as "value" for some field/operator combinations in the PQB, though Elasticsearch does not accept such values for these fields, and throws a BadRequestException, (for instance ["a_text_attribute_value", "=", null])
This PR checks value types more strictly when applying filters (text fields only accept non null strings, numeric fields only accept numeric values)
Note: the error is quite rare because:
- sometimes this passed value is transformed (e.g with `sprintf`), and cast as string
- sometimes filters with `null` are not applied (e.g when coming from the product grid)
| Added Specs …
=> PIM-9454: Fix scalar values type check in PQB filters

CHANGELOG.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/FieldContainer.less
=> PIM-9461: Fix display of multiselect fields with a lot of selected options

src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/src/components/panel/announcement/Announcement.tsx, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/src/components/panel/announcement/Tag.tsx, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/src/definitions/announcement.schema.json, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/tests/front/unit/__mocks__/dataProvider.ts, src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/tests/front/unit/components/panel/AnnouncementList.unit.tsx
**Before**
In the communication panel, there is a link in each announcement. This link target a page in the helpcenter website. The link is  a "Read more" button in the PIM.
**After**
There are marketing announcements that will be written by the product marketing. These announcements will not necessary have a link. In that case, it should not display a Read more button.
Note: the color of the "tag" for the marketing announcements are coming from UX designer
| Added integration …
=> GITHUB-APD-224: don't display the Read more button in communication panel if there is no link in the announcement

CHANGELOG-4.0.md, src/Akeneo/Platform/Bundle/InstallerBundle/Command/DatabaseCommand.php, src/Akeneo/Platform/Bundle/InstallerBundle/Command/InstallCommand.php
This PR adds an option in the pim:installer:db command in order to allow the user not to drop an existing database, but rather empty it.
For PaaS hosts such as Platform.sh, the database is provided by the host and we cannot delete it.
=> PIM-9055: Allow not to drop an existing database during install

upgrades/schema/Version_5_0_20200921153252_dqi_create_table_attribute_group_activation.php, upgrades/test_schema/Version_5_0_20200921153252_dqi_create_table_attribute_group_activation_Integration.php
I used the attribute group creation date as activation update date.
=> DAPI-1285: populate attribute groups activation during migration

src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/Completeness/GetNonRequiredAttributesMasksQuery.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/Completeness/GetNonRequiredProductModelAttributesMaskQuery.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/Completeness/GetRequiredAttributesMasksQuery.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/Completeness/GetRequiredProductModelAttributesMaskQuery.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetEvaluableAttributesByProductModelQuery.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetEvaluableAttributesByProductQuery.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/queries.yml, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/services.yml, src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Persistence/Query/Completeness/CompletenessTestCase.php, src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Persistence/Query/Completeness/GetNonRequiredAttributesMasksQueryIntegration.php, src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Persistence/Query/Completeness/GetNonRequiredProductModelAttributesMaskQueryIntegration.php, src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Persistence/Query/Completeness/GetRequiredAttributesMasksQueryIntegration.php, src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Persistence/Query/Completeness/GetRequiredProductModelAttributesMaskQueryIntegration.php, src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Persistence/Query/ProductEvaluation/GetEvaluableAttributesByProductModelQueryIntegration.php, src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Persistence/Query/ProductEvaluation/GetEvaluableAttributesByProductQueryIntegration.php
The simplest solution is to exclude the deactivated attributes directly from the MySQL queries that fetch the "evaluable" attributes.
The same for the completeness calculations. And now we have to write our own query for the "required attributes mask" instead of using the one of the Enrichment bundle.
=> DAPI-1284: Do not evaluate attributes of deactivated attribute groups

CHANGELOG.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/locale-switcher.js
This PR fixes a bug on the locale selector on the product edit form when the user does not have the permission to edit attributes (i.e. the attributes tab is not visible). The locale switcher module relied on the attributes module (https://github.com/akeneo/pim-community-dev/blob/master/src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/attributes.js#L156) to actually update the displayed locale via an event, so if this module was not loaded, the locale was simply not updated. The event content was modified by reference in the event listener to update the selected locale code.
My PR changes this behavior. I still send the event to notify the PIM that the locales has changed (so my PR shouldn't break anything in the …
=> PIM-9476: Fix locale selector behavior on the product edit form when the user does not have permissions to edit attributes

CHANGELOG.md, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Connector/Tasklet/PrepareProductModelsCriteriaEvaluationTasklet.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Connector/Tasklet/PrepareProductsCriteriaEvaluationTasklet.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Connector/Tasklet/RemoveEvaluationsWithoutProductTasklet.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Repository/ProductCriterionEvaluationRepository.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Repository/ProductModelCriterionEvaluationRepository.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/jobs.yml
When a product (or product model) is deleted, their evaluations are not deleted. (no foreign key with "cascade delete"). 
The cleaning of these evaluations is done with a single `DELETE`  query. As there is a `JOIN` on the products table, this one is locked during all the query execution.  As the deletion can take a long time for big catalog, it's problematic.
Adding a foreign key with "cascade delete" would take too much time. We would have to find a way to perform this kind of migration without locks, but it's not an easy task.
in the meantime, we decided to split the query to not lock the products table. As there's still a slow query to execute, this one will done only once per day instead of every 30 min. To do so, I added a step to the job "DQI daily tasks".
=> PIM-9440: Fix locked MySQL tables during removing DQI evaluations without product

CHANGELOG.md, src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Product/SqlGetValuesOfSiblings.php
Previously :
The identifier could be properly updated on a simple product but not in a variant product.
Solution:
Now, I compare the id instead of the identifier (which can be updated).
`OK`: Done / …
=> PIM-9478: Allow the modification of the identifier on a variant product

CHANGELOG.md, src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Repository/ProductModelRepository.php, tests/back/Pim/Enrichment/Integration/Doctrine/ORM/Repository/ProductModelRepositoryIntegration.php
`root` and `level` are not used anymore in the product model table. I use parent instead.  
The order is not the same than before. To get the exactly same order, we need to make more a complex query that needs study in order to check performance is still good. So I propose this fix as a quick fix and if the order matters (I don't find any test on that so I presume it doesn't) we can re-work the query.
| Review …
=> PIM-9481: fix query to get product models by family variant

src/Akeneo/Pim/Structure/Bundle/Controller/InternalApi/AttributeController.php
Currently Attribute Remove Event Subscriber can't pass bubble exception message as exceptions are not handled in Controller for removeAction.
=> pass bubble exception for attribute remove action.

CHANGELOG.md, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/validators.yml, src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/Product/UniqueProductModelEntityValidator.php, src/Akeneo/Pim/Enrichment/Component/Product/Validator/UniqueValuesSet.php, tests/back/Pim/Enrichment/Integration/Product/Job/ComputeFamilyVariantStructureChangesTaskletIntegration.php, tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/Product/UniqueProductModelEntityValidatorSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/UniqueValueValidatorSpec.php, tests/legacy/features/Behat/Context/Domain/Enrich/ProductModelContext.php, tests/legacy/features/pim/enrichment/product-model/import/import_with_invalid_data.feature
Bug reported in https://github.com/akeneo/pim-community-dev/issues/12899
When importing product models, if there is 2 product models with the same code in one batch, the UniqueProductModelValidator was not catching the error.
**Before**
**After**
| Added legacy Behats               | yes
=> GITHUB-12899: Fix error shown when importing product models with the same code

src/Akeneo/Connectivity/Connection/front/src/common/components/SmallHelper.tsx, src/Akeneo/Connectivity/Connection/front/src/common/components/button/GhostButton.tsx, src/Akeneo/Connectivity/Connection/front/src/common/styled-with-theme.ts, src/Akeneo/Connectivity/Connection/front/src/webhook/components/EditForm.tsx, src/Akeneo/Connectivity/Connection/front/src/webhook/components/EventSubscriptionHelper.tsx, src/Akeneo/Connectivity/Connection/front/src/webhook/pages/EditConnectionWebhook.tsx
Url field
Style issue from the BEM ghost button ………..  
Helper
Secret field
=> CXP-423: fix webhook form style & behavior

.circleci/config.yml
**Issue(s) of the pull-up**
Bug fixes are pull-up from supported branches manually. For example, if a fix is done in `3.2` version, it's pulled-up in `4.0` by the maintenance team, when they can.
I's long, and sometimes painful when not done regularly.
It impacts the workflow of the support team in many ways:
- support team does not exactly which fixes are in which version. It's possible thanks to Github, but this is not their main tool. They rely mainly on the changelog. 
- pull-up are done by the maintenance team, but it could be a long task sometimes. That's why people don't necessary know which fix is in which version (see point above).
- some fixes are **maybe** done in the branch having the bug even if the bug is in older supported versions, because it's long to pull-up a fix. So, …
=> Automatically pull-up a merge in next branch version and notify the result in Slack

CHANGELOG.md, src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Repository/GroupRepository.php, src/Akeneo/Pim/Structure/Bundle/Doctrine/ORM/Repository/AttributeOptionRepository.php
When a filter of type "attribute select", that let you pick attribute options, is used in the datagrid, there was performances issues when there is a lot of attribute options (eg: 5000).
This is because the filter in front tries to be smart and only fetch the selected values:
https://github.com/akeneo/pim-community-dev/blob/162def2dabfa6f4b62ab5c9deee6a3a781c83bf1/src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/select2-choice-filter.js#L234-L245
For doing so, it launch a search limited to some `identifiers`.
It was working on most repositories, like `FamilySearchableRepository`:
https://github.com/akeneo/pim-community-dev/blob/162def2dabfa6f4b62ab5c9deee6a3a781c83bf1/src/Akeneo/Pim/Structure/Bundle/Doctrine/ORM/Rep …
=> PIM-9494: Fix the performances of attribute-select-filter on long lists of AttributeOptions

src/Akeneo/Connectivity/Connection/back/Domain/Audit/Model/Read/ErrorCountPerConnection.php, src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Domain/Audit/Model/Read/ErrorCountPerConnectionSpec.php
When no error are found on the connection, the `errorCounts` property was not initialized as an array. So we had the error `Invalid argument supplied for foreach() in...` and a 500.  
`-`: Not …
=> PIM-9184: Fix error count

CHANGELOG-4.0.md, src/Akeneo/Pim/Enrichment/Bundle/PdfGeneration/Renderer/ProductPdfRenderer.php, tests/back/Pim/Enrichment/EndToEnd/Product/Product/InternalApi/DownloadProductPdfEndToEnd.php, tests/back/Pim/Enrichment/Specification/Bundle/PdfGeneration/Renderer/ProductPdfRendererSpec.php
PR to render all product attributes in the PDF, even empty ones.
Before, empty attributes where part of the values, but since 4.0, empty values are not stored and we must retrieve all the attributes from the product family
=> PIM-9493: Attributes with no values are well rendered in PDF

src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Webhook/ConsumeProductModelEventEndToEnd.php, src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Webhook/ProduceProductModelEventEndToEnd.php, src/Akeneo/Connectivity/Connection/back/tests/Integration/Fixtures/Enrichment/FamilyVariantLoader.php, src/Akeneo/Connectivity/Connection/back/tests/Integration/Fixtures/Enrichment/ProductModelLoader.php, src/Akeneo/Connectivity/Connection/back/tests/Integration/Resources/config/loaders.yml, src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/ProductModelEventSubscriber.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/event_subscribers.yml, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/webhook.yml, src/Akeneo/Pim/Enrichment/Component/Product/Message/ProductModelRemoved.php, src/Akeneo/Pim/Enrichment/Component/Product/Webhook/ProductModelRemovedEventDataBuilder.php, tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/ProductEventSubscriberSpec.php, tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/ProductModelEventSubscriberSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Message/ProductModelRemovedSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Webhook/ProductModelRemovedEventDataBuilderSpec.php
Notify webhook when a product model has been deleted
=> API-1310: Create & dispatch ProductModelRemoved business event

docker-compose.yml
Description
This Docker image is used to emulate GCloud Pub/Sub. However, the latest release 313.0.0 seems to have a different behavior or to not work at all. Quick fix proposed in this PR is to set the Docker image version to the last working tag 312.0.0.
=> Fix google/cloud-sdk Docker image tag

src/Akeneo/Connectivity/Connection/back/Infrastructure/Cli/CreateConnectionCommand.php, src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Connection/CreateConnectionCommandEndToEnd.php
The auditable Connection parameter is currently set in hard, with this contribution it will be possible to pass a new option named --auditable in argument to specify that we want the connection to be auditable. …
=> Add auditable option in CreateConnectionCommand

CHANGELOG-4.0.md, src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductGrid/FetchProductModelRowsFromCodes.php
This query was really slow on the **first** execution due to mysql not being able to optimize it properly, because of the COALESCE.
(We have up to 4min30s for a customer with 800.000 products)
With a simple `OR`, we are down to ~ `0.01 sec`, even on first execution.
| Tech Doc …
=> PIM-9497: Improve performances of SQL query about product model children completeness

CHANGELOG.md, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/localization/factories.yml
Only a few locales (fr_FR & en_US) had a specified format when normalizing date values.
By default, IntlDateFormatter fallback to a short format like `10/10/99` and the year lack precision. (1999 ? 2099 ?)
With this fix, the italian date format is `dd/MM/yyyy` instead of `dd/MM/yy`
**Before:**
**After:** …
=> PIM-9496: Change date format in the locale it_IT from dd/MM/yy to dd/MM/yyyy

src/Akeneo/Connectivity/Connection/back/Infrastructure/Cli/CreateConnectionCommand.php, src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Connection/CreateConnectionCommandEndToEnd.php
From https://github.com/akeneo/pim-community-dev/pull/12956
The auditable Connection parameter is currently set in hard, with this contribution it will be possible to pass a new option named --auditable in argument to specify that we want the connection to be auditable.
| …
=> Add an "auditable" option to the create connection command

CHANGELOG.md, src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/ProductGridFilterController.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/datagrid/product.yml, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/product_grid_category_tree.yml, src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/messages.en_US.yml, src/Akeneo/UserManagement/Bundle/Resources/public/js/fields/product-grid-filters.ts
In the user additional settings page, in the product grid filters dropdown, the labels were not translated. 
(some were hardcoded since 2014 ! :older_man: )
**Before**
**After**
=> PIM-9491: Translate product grid filters in user additional settings

src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/widget/export-widget.js
After design review, we want the job execution to open in the same page the notification message is thrown in.
=> RAC-178: Prevent opening job execution in new tab

src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/BusinessEvent/DispatchProductBusinessEventSubscriber.php, src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/BusinessEvent/DispatchProductModelBusinessEventSubscriber.php, tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/BusinessEvent/DispatchProductBusinessEventSubscriberSpec.php, tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/BusinessEvent/DispatchProductModelBusinessEventSubscriberSpec.php
Removed product & product model data from the message sent to PubSub
Keeping only `identifier` and `categories` for permission check.
The goal is to avoid to put too much pressure on the PubSub stack for now, especially as we dont need the data.
=> CXP-428: remove unused data from business events

tests/legacy/features/Behat/Context/NavigationContext.php
Fixes the "I should (not? ) be able to access the page" step: if, for any reason, the pages takes more than 1 second to load, the spin() function returns false and tries to reload the requested page, which takes more than 1 second to load etc... (rinse and repeat...)
I'm not sure why the 403 page takes more than 1 second to load for the product grid though (seems to be quite recent)
| Review and 2 …
=> Fix failing legacy behat

CHANGELOG.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/messages.en_US.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/messages.fr_FR.yml
The ACL "Remove a product model" allows the customer to see the various delete buttons available to delete a product model. And when we click on those buttons, the expected behavior is to remove the whole product model (with its children).
The ACL naming can be confusing because the customer doesn't clearly know that even the children of the product model are going to be deleted.
**Improvement:**  
Change "Remove a product model" to: “Remove a product model (including children)”
| …
=> PIM-9485: Change ACL name “Remove a product model” to “Remove a product model (including children)”

src/Akeneo/Pim/Enrichment/Bundle/ProductQueryBuilder/ProductAndProductModelQueryBuilder.php, tests/back/Pim/Enrichment/Integration/PQB/Filter/LabelOrIdentifierFilterIntegration.php, tests/back/Pim/Enrichment/Integration/PQB/ProductAndProductModelQueryBuilderIntegration.php, tests/back/Pim/Enrichment/Specification/Bundle/ProductQueryBuilder/ProductAndProductModelQueryBuilderSpec.php
https://akeneo.atlassian.net/browse/PM2020-4
Actually the quick search grid (on identifier and label) returns simple product and root product model, not sub product models and variants.  
With this PR we display all products and PM.
When there is another filter on an attribute value, we use to "aggregate" results to display only the level where the attribute is defined (= the PM). If there is also a "label or identifier" filter, now we don't aggregate otherwise the product cannot be displayed (same behavior as the filter on id). …
=> PM2020-4: update PQB to display all documents with quick search

src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml, src/Oro/Bundle/PimDataGridBundle/Resources/translations/jsmessages.en_US.yml
Since files in ` src/Oro/Bundle/PimDataGridBundle` are not translated in crowding, we need to move those new translations to Enrichment.
=> RAC-319: Move the translations to the Enrichment bundle

src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetProductIdsImpactedByAttributeGroupActivationQuery.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetProductModelIdsImpactedByAttributeGroupActivationQuery.php, src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Persistence/Query/ProductEvaluation/GetProductIdsImpactedByAttributeGroupActivationQueryIntegration.php, src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Persistence/Query/ProductEvaluation/GetProductModelIdsImpactedByAttributeGroupActivationQueryIntegration.php
There was an error in the queries that retrieve the products to re-evaluate when an attribute-group is (de)activated.
I tried to exclude the products that have been evaluated after the (de)activation of the attribute-group, but I used the wrong date. To use the right date (the update date of the attribute-group) the request would be too complex and not efficient.
The best solution is to remove this optimization. It was overkill because the (de)activation of an attribute-group is a very rare action.
=> DAPI-1407: Fix get products to re-evaluate because attribute-group activation

CHANGELOG.md, src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/label_or_identifier-filter.js
With a UI in french, the search field displayed "Rechercher sur pim_common.Libellé ou identifiant"
In a previous PR, the label had been translated, so, we had to remove the "pim_common" key from the template.
Small modification: I added the _toLowerCase()_ function to the _label_ because the first letter was in upper case ( label is used in other places in the pim so I preferred to make this specific modification in this js file).
_Please feel free to tell me if there is a more suitable way to do this._
| Added acceptance …
=> PIM-9519: Fix translation key for datagrid search field

CHANGELOG.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/locale-switcher.js
It's a regression introduced by this PR of mine a few weeks ago : https://github.com/akeneo/pim-community-dev/pull/12835
As I explained in the previous PR, the way the locale was selected in the UI was strange : the value was retrieved from another module by using events to update an object by reference to get the locale, and I made a mistake by ignoring it (I didn't know there was a use case in the export builder where it was needed). So instead of ignoring the value selected by the event, I use it this time.
The problem is that the locale switcher module is used everywhere in the PIM and the selected value can be set by different event listeners. So the algorithme to select the right value is now a bit like a chain-of-responsibility …
=> PIM-9517: Fix locale selector default value on localizable attributes in product exports

CHANGELOG-3.2.md, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/config/measure.yml
The multiplicator for the millibar measure was wrong. The bar is 1, so the millibar should be 1000 and not 0.001.
=> PIM-9523: Fix pressure measure multiplicator error

src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/GetProductsKeyIndicators.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Query/Dashboard/GetProductsKeyIndicator.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Connector/Tasklet/EvaluateProductsAndProductModelsCriteriaTasklet.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Elasticsearch/GetDataQualityInsightsPropertiesForProductProjection.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Elasticsearch/UpdateProductsIndex.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/KeyIndicator/GetProductsEnrichmentStatusQuery.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/KeyIndicator/GetProductsWithAnImageQuery.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/elasticsearch.yml, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/jobs.yml, src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Persistence/Query/KeyIndicator/GetProductsEnrichmentStatusQueryIntegration.php, src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Application/GetProductsKeyIndicatorsSpec.php, src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Elasticsearch/GetDataQualityInsightsPropertiesForProductProjectionSpec.php, src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Elasticsearch/UpdateProductsIndexSpec.php
I did a dedicated PR for several tasks:
1. Rename two ES services to reflect that they we don't only save the rates in ES anymore, but also the key indicators
2. Add missing specs
3. Use an array of `ProductId` as parameter in `GetProductsKeyIndicators` and `GetProductsEnrichmentStatusQuery` to facilitate the calls and the tests
4. Remove EE copyrights
=> DAPI-1374: Key indicators - Renaming, specs, and fixes

CHANGELOG-4.0.md, src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductGrid/ProductModelImagesFromCodes.php
Fix https://akeneo.atlassian.net/browse/PIM-9518
- Add condition in sub query in order to have only needed variant products
- Fetch entire raw values is useless as we only need the images information
`OK`: Done / …
=> PIM-9518: improve query to fetch images from product model codes

CHANGELOG-4.0.md, src/Akeneo/Platform/Bundle/ImportExportBundle/Persistence/Filesystem/DeleteOrphanJobExecutionDirectories.php
Fix https://akeneo.atlassian.net/browse/PIM-9524
An out of memory error occurred when we have a lot of files to list. The error is thrown in the flysystem list function. Badly we cannot fix it efficiently because the `listContents` method builds and returns an array with all results: https://github.com/thephpleague/flysystem/blob/1.1.3/src/Adapter/Local.php#L288  
The flysystem v2 (not released yet) will return an iterator with a generator. So the problem will be fixed.  
For now, to try to fix the issue, instead of listing all files in the `.` directory recursively, I fetch all directories in level 1, then in level 2, finally in level 3 (no need to go further for this use case). And I use a generator to returns directories by group of …
=> PIM-9524: improve purge job command to avoid out of memory errors

CHANGELOG.md, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/jobs.yml, src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/ComputeCompletenessOfFamilyProductsTasklet.php, src/Akeneo/Pim/Structure/Bundle/Resources/config/jobs.yml, src/Akeneo/Pim/Structure/Bundle/Resources/config/steps.yml, src/Akeneo/Pim/Structure/Component/Reader/Database/MassEdit/FilteredFamilyReader.php, tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Job/ComputeCompletenessOfFamilyProductsTaskletSpec.php
You could have some completeness desynchronisation when you use the bulk action "set attribute requirements" on families. This PR fix the behavior to recalculate completeness after a bulk action on families.
=> PIM-9516: Recalculate completeness after a bulk set attribute requirements on families

CHANGELOG.md, src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/action/mass-action.js
When the user filters on a label in family grid, and selects "All" the results, the mass action should concern only the filtered families. Actually it's not the case, all the families are concerned.
`OK`: Done / …
=> PIM-9532: use grid filters in family mass action

src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/shared/layouts/tables/TableCell.tsx, src/Akeneo/Platform/Bundle/ImportExportBundle/Query/GetJobExecutionTracking.php, src/Akeneo/Platform/Bundle/ImportExportBundle/tests/front/unit/components/JobExecutionStatus.unit.tsx, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/intl-duration.ts, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/execution/progress.tsx, src/Akeneo/Platform/Bundle/UIBundle/tests/front/unit/components/JobExecutionProgress.unit.tsx, src/Akeneo/Platform/Bundle/UIBundle/tests/front/unit/intl-duration.unit.ts, tests/back/Platform/Integration/ImportExport/Repository/InternalApi/GetJobExecutionTrackingIntegration.php
Instead of mapping the batch status to a tracking status, we should reuse the batch status which is already translated and expected in the front.
It also support the cases expected by the badge (see https://github.com/akeneo/pim-community-dev/pull/13053)
```
const COMPLETED = 1;
const STARTING = 2;
const STARTED = 3;
const STOPPING = 4;
const STOPPED = 5;
const FAILED = 6;
const ABANDONED = 7;
const UNKNOWN = 8;
``` …
=> RAC-335: Re-use job execution status in tracking endpoint

CHANGELOG.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/locale-switcher.js
Fix regression introduced by https://github.com/akeneo/pim-community-dev/pull/13046 and https://github.com/akeneo/pim-community-dev/pull/12835.
Why we have a problem ? The switcher (visual element)[src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/locale-switcher.js] and the attribute filter (form data)[src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/filter/attribute/attribute.js] are desynchronized on first display. The locale-switcher doesn't provide a default locale to the attribute filter on event `pim_enrich:form:locale_switcher:pre_render`, if the user does not change the locale, the locale remains undefined in form data. 
| Q …
=> PIM-9535: fix localizable attribute are filled with locale undefined on export builder by default

src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/GetKeyIndicators.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/GetKeyIndicatorsInterface.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Model/Read/KeyIndicator.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Query/Dashboard/GetProductKeyIndicatorsQueryInterface.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/ValueObject/KeyIndicatorCode.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Elasticsearch/Query/GetProductKeyIndicatorsQuery.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Controller/Dashboard/DashboardKeyIndicatorsController.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/controllers.yml, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/elasticsearch.yml, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/services.yml, src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/.php_cd.php, src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/DataQualityInsightsTestCase.php, src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Elasticsearch/Query/GetProductKeyIndicatorsQueryIntegration.php
Controller, Application and ES query to retrieve the key indicators for the Dashboard.
The interface `GetKeyIndicatorsInterface` will allow to have an implementation in EE to add the key indicator on attributes. 
For the EE key indicators on products with perfect spelling, we will just have to add its code by decorating the service `akeneo.pim.automation.data_quality_insights.get_key_indicators`
=> DAPI-1414: Retrieve key indicators for the Dashboard

src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/ComputeProductsKeyIndicators.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/GetKeyIndicators.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/GetKeyIndicatorsInterface.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Model/KeyIndicator/ProductsWithGoodEnrichment.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Model/KeyIndicator/ProductsWithImage.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Model/Read/KeyIndicator.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Query/Dashboard/ComputeProductsKeyIndicator.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Query/Dashboard/GetProductKeyIndicatorsQueryInterface.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/ValueObject/KeyIndicatorCode.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Elasticsearch/GetDataQualityInsightsPropertiesForProductProjection.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Elasticsearch/Query/GetProductKeyIndicatorsQuery.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Elasticsearch/UpdateProductsIndex.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/KeyIndicator/ComputeProductsEnrichmentStatusQuery.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/KeyIndicator/ComputeProductsWithImageQuery.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Controller/Dashboard/DashboardKeyIndicatorsController.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/controllers.yml, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/elasticsearch.yml, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/queries.yml, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/services.yml, src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/.php_cd.php, src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/DataQualityInsightsTestCase.php, src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Elasticsearch/Query/GetProductKeyIndicatorsQueryIntegration.php, src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Persistence/Query/KeyIndicator/ComputeProductsEnrichmentStatusQueryIntegration.php, src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Application/ComputeProductsKeyIndicatorsSpec.php, src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Elasticsearch/GetDataQualityInsightsPropertiesForProductProjectionSpec.php, src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Elasticsearch/UpdateProductsIndexSpec.php, src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Persistence/Query/KeyIndicator/ComputeProductsWithImageQuerySpec.php
Renaming to clarify if the services and queries are for writing (compute the key indicators form MySQL or store them in ES) or for reading (from ES)
I added two minimal interfaces to hold the codes of the key indicators.
=> DAPI-1414: Renaming

src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/datagrid/last_executions.yml, src/Oro/Bundle/PimDataGridBundle/Resources/config/data_sources.yml
In this PR : 
- Add information of current step in last job execution grid
- Remove badge around warning count in last job execution grid
=> RAC-280: feat add current step and total step when job process is started or starting

CHANGELOG.md, src/Akeneo/Tool/Bundle/ConnectorBundle/Resources/translations/jsmessages.en_US.yml, tests/legacy/features/platform/acl/ensure_acl_on_export_profile.feature
_batch_jobs.default_steps.delete_products_and_product_models_ was not translated.
So, I added the translation in the correct file.
=> PIM-9498: Add translation for 'Mass delete products' job

CHANGELOG.md, src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/shared/layouts/tables/TableCell.tsx, src/Oro/Bundle/PimDataGridBundle/Resources/public/js/pageable-collection.js
Sorters are handled in 2 ways:
- sorter stored in session when user sorted the results in a previous usecase
- sorter stored in actual state, when user is selecting a new sorter
So we can have 2 sorters in the same time, that causes weird displays. And the sorter in the session cannot be removed (except a logout action) so the user is stucked.
In this PR, when a new sorter is detected, we remove the old sorter. …
=> PIM-9538: Fix sorting on rule engine list page

std-build/install-required-files.sh
Fix https://app.circleci.com/pipelines/github/akeneo/pim-community-standard/2519/workflows/51a40b5b-0181-4592-a12a-10a53d49cd2c/jobs/3322  
Missing `.env.dev` to define the PubSub emulator in dev environment
=> Add .env.dev to fix the standard build

tests/back/Acceptance/Channel/InMemoryChannelRepository.php, tests/back/Acceptance/spec/Channel/InMemoryChannelRepositorySpec.php
The `ChannelInterface` was not imported. As the method is not used in any acceptance tests, the error was never noticed. 
We need this method to work in some Onboarder acceptance tests.
`-`: …
=> Fix InMemoryChannelRepository::getChannelCodes()

src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Model/Read/KeyIndicator.php
These two new methods are indirectly tested by the spec of the service `GetKeyIndicators`
=> DAPI-1425: Add helper methods to key indicator model

package.json, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/view/base.ts, src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/column-selector.ts, yarn.lock
Version 4.0 only works with the `yarn.lock`. By deleting the `yarn.lock` we have a lot of issues of field declared two times, etc..
Fixing the version of typescript avoid that.
This way, we can update the dependencies and our integrators also in standard version.
| Tech Doc …
=> PIM-9549: Fix typescript version to be able to update yarn.lock

CHANGELOG.md, config/packages/behat/monolog.yml, config/packages/prod/monolog.yml, config/packages/prod_onprem_paas/monolog.yml
Our monolog config used to have the default value (0 =unlimited) for the `crossed_fingers` handlers `buffer_size` param, which means it stored every log message in a buffer until one had a level high enough to be flushed. 
This has almost always no consequence, except in large jobs, where the amount of logged messages can stack up and cause an out of memory error (e.g in product imports, an INFO message is logged each time a product is updated or created)
This PR limits the buffer_size to 1000, meaning that when a message is flushed, only the 1000 previous messages will be flushed alongside.
| Added Specs …
=> PIM-9545: Update monolog config to avoid possible memory leak

src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/TabContent/DataQualityInsights/Criterion.tsx, src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/AttributeGridRouter.ts, src/Akeneo/Pim/Structure/Bundle/Datagrid/Attribute/FamilyFilter.php, src/Akeneo/Pim/Structure/Bundle/Datagrid/Attribute/RegisterFamilyFilter.php, src/Akeneo/Pim/Structure/Bundle/Query/InternalApi/Family/GetAllFamiliesLabelByLocaleQuery.php, src/Akeneo/Pim/Structure/Bundle/Resources/config/queries.yml, src/Akeneo/Pim/Structure/Bundle/Resources/config/services.yml, src/Akeneo/Pim/Structure/Component/Query/InternalApi/GetAllFamiliesLabelByLocaleQueryInterface.php, tests/back/Pim/Structure/Integration/Family/GetAllFamiliesLabelByLocaleQueryIntegration.php
=> DAPI-1367: update family attribute grid filter to use code instead of ids

akeneo-design-system/src/components/ProgressBar/ProgressBar.tsx, src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/ComputeCompletenessOfFamilyProductsTasklet.php, src/Akeneo/Pim/Structure/Bundle/Resources/config/jobs.yml, src/Akeneo/Pim/Structure/Component/Reader/Database/MassEdit/FilteredFamilyReader.php, src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/datagrid/last_executions.yml, src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/public/templates/last-operations-widget.html, src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/translations/jsmessages.en_US.yml, src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/views/Property/warning.html.twig, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/execution/progress.tsx, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/execution/status.tsx, src/Akeneo/Platform/Bundle/UIBundle/tests/front/unit/components/JobExecutionProgress.unit.tsx, src/Akeneo/Tool/Component/Batch/Step/ItemStep.php, src/Akeneo/Tool/Component/Batch/spec/Step/ItemStepSpec.php, src/Akeneo/Tool/Component/Connector/Reader/File/Csv/Reader.php, src/Akeneo/Tool/Component/Connector/spec/Reader/File/Csv/ReaderSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Job/ComputeCompletenessOfFamilyProductsTaskletSpec.php
In this PR : 
**Back:**
- Remove file validation file step in XLSX attribute option export and XLSX attribute export job (user does not give the input file)
- The CSV reader do not used the defined separator in job instance, if file contain a comma and the separator is semicolon the count is false
- Make ComputeCompletenessOfFamilyProductsTasklet trackable
- Make FilteredFamilyReader trackable
- ItemStep do not update processedItem when processor return null
- ItemStep do not update jobExecution if Reader is not trackable
**Font:**
- Css problem on project calculation grid 
- When status is completed the progress bar should be at 100% we don’t have to pay attention to totalItems and processedItems even if the process is trackable
- …
=> RAC-343: Fix progress job errors

src/Akeneo/Tool/Component/Batch/Model/StepExecution.php
Doctrine hydrate entities by bypassing both constructor and setters.
The migration added the column tracking data with a default value to null.
When `$this->trackingData = null;`, fatal error.
With this PR, we ensure there is no error when those getter/setter are called.
| …
=> RAC-376: Fix step execution migration by handling the error in the getters

config/services/test/test_services.yml, src/Akeneo/Pim/Enrichment/Bundle/Command/CleanRemovedAttributesFromProductAndProductModelCommand.php, tests/back/Common/EntityWithValue/Builder/Product.php, tests/back/Pim/Enrichment/Integration/Fixture/ProductAndProductModelWithRemovedAttributeLoader.php, tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductAndProductModel/CountProductModelsWithRemovedAttributeIntegration.php, tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductAndProductModel/CountProductsAndProductModelsWithInheritedRemovedAttributeIntegration.php, tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductAndProductModel/CountProductsWithRemovedAttributeIntegration.php, tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductAndProductModel/GetProductIdentifiersWithRemovedAttributeIntegration.php, tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductAndProductModel/GetProductModelIdentifiersWithRemovedAttributeIntegration.php, tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductAndProductModel/WithRemovedAttributeTestCase.php, tests/back/Pim/Enrichment/Specification/Bundle/Product/CleanValuesOfRemovedAttributesSpec.php
This pull request aims to improve the previous pull request https://github.com/akeneo/pim-community-dev/pull/13242 with specifications and integration tests
=> PIM-9550: add integration tests on internal services used by the command "pim:product:clean-removed-attributes"

CHANGELOG.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/FamilyVariant.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/VerticalList.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/family-variant/attribute-group.html
Long attribute labels (or codes) were displayed on 2 lines (or more) and so hover over separation lines and attributes below them on the variant attributes page of Settings > Families, making it very difficult to read and sort out.
So, I worked on the concerned css files to add an ellipsis when an attribute label/code is too long for the display to be correct. …
=> PIM-9539: Fix the display of long attribute labels or codes on variant attributes page

CHANGELOG-4.0.md, src/Akeneo/Pim/Enrichment/Bundle/Doctrine/Common/Saver/GroupSaver.php, src/Akeneo/Pim/Enrichment/Component/Product/Updater/GroupUpdater.php, tests/back/Pim/Enrichment/Specification/Bundle/Doctrine/Common/Saver/GroupSaverSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Updater/GroupUpdaterSpec.php
This fix a performance issue when saving a group with a lot of products (whatever the change)
The group updater was removing all the products before re-adding them all, and the group saver was saving all the products for the versioning.
Now, it will only add, remove and save the products that need it.
It's not an ideal solution, and the problem will remain if too many products are added/removed in the same request. But better solutions will cause BC-breaks.
=> PIM-9568: Fix performance issue when saving a big product group

CHANGELOG-4.0.md, src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/action/navigate-action.js
This PRs adds a hash at the beginning of (not unset) URLs used in datagrid actions cells so that they can be opened in a new tab with the correct URL.
The `onClick` handler intercepts the link `href` anyway so it's really only useful when "right clicking -> open in a new tab" …
=> PIM-9575: Prepend hash to navigate actions URLs

CHANGELOG.md, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/steps.yml, src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/ComputeCompletenessOfFamilyProductsTasklet.php, src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/ComputeDataRelatedToFamilyProductsTasklet.php, src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/ComputeDataRelatedToFamilyRootProductModelsTasklet.php, src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/ComputeDataRelatedToFamilySubProductModelsTasklet.php, src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/EnsureConsistentAttributeGroupOrderTasklet.php, src/Akeneo/Pim/Enrichment/Component/Product/Job/DeleteProductsAndProductModelsTasklet.php, src/Akeneo/Pim/Structure/Component/Reader/Database/MassEdit/FilteredFamilyReader.php, src/Akeneo/Tool/Component/Batch/Item/RewindableItemReaderInterface.php, src/Akeneo/Tool/Component/Batch/Item/TrackableTaskletInterface.php, src/Akeneo/Tool/Component/Connector/Reader/File/Csv/Reader.php, src/Akeneo/Tool/Component/Connector/Reader/File/Xlsx/Reader.php, src/Akeneo/Tool/Component/Connector/Reader/File/Yaml/Reader.php, src/Akeneo/Tool/Component/Connector/Step/TaskletStep.php, src/Akeneo/Tool/Component/Connector/spec/Reader/File/Csv/ReaderSpec.php, src/Akeneo/Tool/Component/Connector/spec/Reader/File/Xlsx/ReaderSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Job/ComputeCompletenessOfFamilyProductsTaskletSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Job/ComputeDataRelatedToFamilyProductsTaskletSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Job/ComputeDataRelatedToFamilyRootProductModelsTaskletSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Job/ComputeDataRelatedToFamilySubProductModelsTaskletSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Job/EnsureConsistentAttributeGroupOrderTaskletSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Job/DeleteProductsAndProductModelsTaskletSpec.php
In this PR: 
- Refactor way of set the total item in Tasklets -> before the tasklet should return the total items not the tasklet is responsible to set the total items => it's more logic and avoid double call to Elasticsearch
- DeleteProductAndProductModelTasklet progress is not updated during execution => it pass from 0 to 100 on interface  …
=> RAC-339: refactor way of counting total items

CHANGELOG-3.2.md, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/config/measure.yml
Reverting this PR https://github.com/akeneo/pim-community-dev/pull/13064, as the doc says: `Operations are defined to convert from the unit to the standard unit`
`-`: Not …
=> PIM-9578: Revert change on millibar conversion operation

CHANGELOG.md, src/Akeneo/UserManagement/Component/Normalizer/UserNormalizer.php, src/Oro/Bundle/PimDataGridBundle/Controller/Rest/DatagridViewController.php, src/Oro/Bundle/PimDataGridBundle/DataTransformer/DefaultViewDataTransformer.php, src/Oro/Bundle/PimDataGridBundle/Repository/DatagridViewRepository.php, src/Oro/Bundle/PimDataGridBundle/Repository/DatagridViewRepositoryInterface.php, src/Oro/Bundle/PimDataGridBundle/spec/DataTransformer/DefaultViewDataTransformerSpec.php, src/Oro/Bundle/PimDataGridBundle/tests/Integration/Repository/DatagridViewRepositoryIntegration.php, tests/back/UserManagement/Specification/Component/Normalizer/UserNormalizerSpec.php
There was some issues between the `DatagridViewRepositoryInterface` and its implementation: `getDatagridViewTypeByUser` and `findDatagridViewBySearch` was defined to return ArrayCollection in interface but returned array in implementation.  
Some rework is done to fix that (and more):
- `getDatagridViewTypeByUser` is renamed as `getDatagridViewAliasesByUser`. Datagrid views has an alias and a type. To have a method `getDatagridViewTypeByUser` that return aliases is very confusing. Now the method return a flat array instead of unnecessary complex array
Before:
```
[["datagridAlias" => "alias1"], ["datagridAlias" => "alias2"], ...]
```
After:
```
["alias1", "alias2", ...]
```
- `findDatagridViewBySearch` now returns a Collection in the …
=> CPM-74: rework datagrid view repository

CHANGELOG-4.0.md, src/Akeneo/Pim/Enrichment/.php_cd.php, src/Akeneo/Pim/Enrichment/Bundle/Command/CleanRemovedAttributesFromProductAndProductModelCommand.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/command.yml, src/Akeneo/Pim/Structure/Bundle/Event/AttributeEvents.php
Setting methods as protected to be able to extend this command in EE
=> PIM-9559: Dispatch event when clean removed attributes command is over

src/Akeneo/Pim/Enrichment/Component/Product/Model/AbstractProduct.php
Following #13178, the `AbstractProduct::getValues()` method now returns a copy of its WriteValueCollection. (this was already the case before for variant products, but not for simple products)
Problem is, this method is used quite a lot in the PIM, and instantiating a WriteValueCollection is quite costly, as [it performs a number of checks and computations for each value](https://github.com/akeneo/pim-community-dev/blob/master/src/Akeneo/Pim/Enrichment/Component/Product/Model/WriteValueCollection.php#L233). 
To avoid this, I now return a mere clone of the original value collection, as all these checks and computations were already performed on the original collection, so they don't need to be run on the new one. 
Here are the Blackfire …
=> CXP-493: Clone ValueCollection instead of instantiating a new one

CHANGELOG.md, src/Akeneo/Pim/Enrichment/Component/Product/Model/AbstractProduct.php
There's a circular reference with the product groups that can reach to a memory usage issue under certain circumstances.
It occurred for a client that has a group with more than 5000 products when a new product with this group is imported. The import itself already uses a lot of memory, and when the group is added to the product the memory usage explodes.
It's because the method `AbstractProduct::addGroup` adds the product to the group by calling the method `Group::addProduct` , that calls `AbstractProduct::addGroup` again. The conditions  `if (!$this->groups->contains($group))` and `if (!$this->products->contains($product))` prevents an infinite loop, but it causes all the products of the group to be automatically loaded and hydrated by the ORM.
```
abstract class AbstractProduct …
```
=> PIM-9569: Fix memory usage issue when adding a group to a product

CHANGELOG-3.2.md, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/config/measure.yml
The conversion was in reverse for these units
=> PIM-9580: Fix conversion operation for ATM, PSI, TORR & MMHG

CHANGELOG.md, src/Akeneo/Tool/Bundle/ConnectorBundle/EventListener/InvalidItemsCollector.php, src/Akeneo/Tool/Bundle/ConnectorBundle/spec/EventListener/InvalidItemsCollectorSpec.php
When importing product models, if warnings were raised, we didn't retrieve all the problematic product models on the "invalid data file". 
It was because the invalid data file recovered the types of errors (regardless of the number of products impacted) and not each product in error.
So, I added a condition that gets the position of the item when invalidItem is an instance of FileInvalidItem class.
So I can build an array of invalid items which will all be picked up by the invalid data file. …
=> PIM-9571: Fix missing items on the invalid data file when importing product models

src/Akeneo/Platform/Bundle/AnalyticsBundle/DataCollector/DBDataCollector.php, src/Akeneo/Platform/Bundle/AnalyticsBundle/Query/Sql/ActiveEventSubscriptionCount.php, src/Akeneo/Platform/Bundle/AnalyticsBundle/Resources/config/data_collectors.yml, src/Akeneo/Platform/Bundle/AnalyticsBundle/Resources/config/queries.yml, src/Akeneo/Tool/Component/Analytics/ActiveEventSubscriptionCountQuery.php, tests/back/Platform/Acceptance/Analytics/Query/InMemory/ActiveEventSubscriptionCountInMemory.php, tests/back/Platform/Acceptance/Analytics/Resources/config/queries.yml, tests/back/Platform/Integration/Analytics/Query/ActiveEventSubscriptionCountIntegration.php, tests/back/Platform/Specification/Bundle/AnalyticsBundle/DataCollector/DBDataCollectorSpec.php
In order to follow-up the Events API activation, we add the number of activated event subscriptions into the PIM tracker. 
`nb_active_event_subscription : integer
`
=> CXP-503: Add the number of activated WH in the tracker

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/execution/StopJobAction.tsx, src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/widget/export-widget.js
The MessageBar sent by the quick export widget had a missing key error because we pass its children here as an array https://github.com/akeneo/pim-community-dev/blob/8972f7288473be719f0b39270f218552b66965fc/src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/widget/export-widget.js#L29, the children elements then need a `key` prop
| Micro Demo …
=> Fix missing key in MessageBar

src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/KeyIndicator/ComputeProductsEnrichmentStatusQuery.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetCriteriaEvaluationsByProductIdQuery.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetEvaluationRatesByProductsAndCriterionQuery.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Transformation/Channels.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Transformation/Locales.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Transformation/TransformCriterionEvaluationResultCodes.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Transformation/TransformCriterionEvaluationResultIds.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/queries.yml, src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Persistence/Transformation/TransformCriterionEvaluationResultCodesIntegration.php, src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Persistence/Transformation/TransformCriterionEvaluationResultIdsIntegration.php, src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Persistence/Transformation/TransformCriterionEvaluationResultCodesSpec.php, src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Persistence/Transformation/TransformCriterionEvaluationResultIdsSpec.php
The key-indicators calculation added MySQL queries on the table `pim_data_quality_insights_product_criteria_evaluation` that need adaptation to transform ids to codes.
=> DAPI-1377: Adaptations for key-indicators calculation

CHANGELOG-4.0.md, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/product_value_factories.yml, src/Akeneo/Pim/Enrichment/Component/Product/Factory/NonExistentValuesFilter/ChainedNonExistentValuesFilter.php, src/Akeneo/Pim/Enrichment/Component/Product/Factory/NonExistentValuesFilter/NonExistentFileValueFilter.php, src/Akeneo/Pim/Enrichment/Component/Product/Factory/NonExistentValuesFilter/NonExistentMultiSelectValuesFilter.php, src/Akeneo/Pim/Enrichment/Component/Product/Factory/NonExistentValuesFilter/NonExistentPriceCollectionValueFilter.php, src/Akeneo/Pim/Enrichment/Component/Product/Factory/NonExistentValuesFilter/NonExistentReferenceDataMultiSelectValuesFilter.php, src/Akeneo/Pim/Enrichment/Component/Product/Factory/NonExistentValuesFilter/NonExistentReferenceDataSimpleSelectValuesFilter.php, src/Akeneo/Pim/Enrichment/Component/Product/Factory/NonExistentValuesFilter/NonExistentSimpleSelectValuesFilter.php, src/Akeneo/Pim/Enrichment/Component/Product/Factory/ReadValueCollectionFactory.php, src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/BooleanValueFactory.php, src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/DateValueFactory.php, src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/FileValueFactory.php, src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/IdentifierValueFactory.php, src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/ImageValueFactory.php, src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/MetricValueFactory.php, src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/NumberValueFactory.php, src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/OptionValueFactory.php, src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/OptionsValueFactory.php, src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/PriceCollectionValueFactory.php, src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/ReferenceDataCollectionValueFactory.php, src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/ReferenceDataValueFactory.php, src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/TextAreaValueFactory.php, src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/TextValueFactory.php, tests/back/Pim/Enrichment/Integration/Product/ReadValueCollectionFactoryIntegration.php, tests/back/Pim/Enrichment/Specification/Component/Product/Factory/Value/FileValueFactorySpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Factory/Value/ImageValueFactorySpec.php
see https://github.com/akeneo/pim-community-dev/pull/13330 for the 3.2 version
Between 3.2 and 4.0, in `ReadValueCollectionFactory`, the implem of `createWithoutCheckingData` was added to improve the performances of the API.
Sadly, this allows fatal errors when an attribute is removed then re-created with the same code but another type.
After the benchmarks done by Steven and I, on a reference catalog (100 products with 120 attributes each), we found out that using `createByCheckingData` instead of `createWithoutCheckingData` effectively increase ReadValueCollectionFactory time by **+20%**.
This result in a time increase of **+8%** on the product API endpoint, when fetching 100 products.
Since most of those checks are done by calling a …
=> RAC-388: Fix fatal error when an attribute is removed then re-created with the same code but another type

CHANGELOG.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_base_import_edit.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/common/edit/properties.js
Actually, the General settings tab is empty on cloud environments on the following xlsx imports:
- attribute
- family
- family variant
- association type
- attribute option
- attribute group
- group type
This is due to the following lines :
https://github.com/akeneo/pim-community-dev/blob/97ef99631fc43e90d433acb90c8ec69e0d429c0f/src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/common/edit/field/allow-file-upload.ts#L6
https://github.com/akeneo/pim-community-dev/blob/97ef99631fc43e90d433acb90c8ec69e0d429c0f/src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/common/edit/field/file-path.ts#L6
In this PR, i added the possibility to hide an tab on cloud instance, and used it for simple xlsx import 
**Definition Of Done …
=> PIM-9577: Remove empty 'Global settings' tab on XLSX import

CHANGELOG-4.0.md, src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/ApplyProductSearchQueryParametersToPQB.php
If I used this filter, I got a 500 (the "2" isn't in quote) :
`{{url}}/api/rest/v1/products?search={"updated": [{"operator": "SINCE LAST N HOURS","value": 2}]`
When I used this filter, I got a 422, that is expected (the "2" is in quote) :
({{url}}/api/rest/v1/products?search={"updated": [{"operator": "SINCE LAST N HOURS","value": "2"}]}
_NOTE: using "SINCE LAST N DAYS" filter works both with an int or a string (2 or "2")_
**Solution:**
The 500 error was raised because the function createFromFormat() expects a parameter to be string, int was given.
So, I converted $value to string.
| Added Specs …
=> PIM-9513: Fix the use of an unexisting filter on the API so that it does not return an error 500

CHANGELOG-4.0.md, src/Akeneo/Tool/Bundle/ConnectorBundle/EventListener/InvalidItemsCollector.php, src/Akeneo/Tool/Bundle/ConnectorBundle/spec/EventListener/InvalidItemsCollectorSpec.php
PR master => https://github.com/akeneo/pim-community-dev/pull/13377
=> PIM-9586: [Backport PIM-9571] Fix missing items on the invalid data file when importing product models

CHANGELOG-4.0.md, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/config/measure.yml
Fix https://akeneo.atlassian.net/browse/PIM-9592
1 day = 60 * 60 * 24 = 86400 seconds
1 year = 86400 * 365 = 31536000 seconds
1 month = 31536000 / 12 = **2628000** seconds
=> PIM-9592: fix month to seconds conversion

src/Akeneo/Connectivity/Connection/back/Application/Webhook/Command/SendBusinessEventToWebhooksHandler.php, src/Akeneo/Connectivity/Connection/back/Application/Webhook/Service/CacheClearerInterface.php, src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/handlers.yml, src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/services.yml, src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/Service/CacheClearer.php, src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Webhook/Command/SendBusinessEventToWebhooksHandlerSpec.php, src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Webhook/Service/CacheClearerSpec.php
Currently the consumer daemon is restarted regularly to invalidate any cache on permissions or structure. This PR aims to clear cache from services that are used during the process of sending events to webhooks. …
=> CXP-546: Clear cache after sending event to webhooks

CHANGELOG.md, src/Akeneo/Pim/Enrichment/Bundle/Command/CleanRemovedAttributesFromProductAndProductModelCommand.php
Change the dependency from EventDispatcher to EventDispatcherInterface for fixing the following error in EE: 
```
It for Argument 6 passed to Akeneo\Pim\Enrichment\Bundle\Command\CleanRemovedAttributesFromProductAndProductModelCommand::__construct() must be an instance of Symfony\Component\EventDispatcher\EventDispatcher, instance of Symfony\Comp  
onent\HttpKernel\Debug\TraceableEventDispatcher given,
``` …
=> Fix CleanRemovedAttributesFromProductAndProductModelCommand  dependency with EventDispatcher

src/Akeneo/Pim/Enrichment/Component/Product/Model/ProductModel.php, src/Akeneo/Pim/Enrichment/Component/Product/Model/ProductModelInterface.php
... like other setters. Because it's annoying.
=> Make ProductModel::setCode() respect fluent interface

src/Akeneo/Channel/Bundle/Doctrine/Query/FindActivatedCurrencies.php, src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/services.yml, src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/Service/CacheClearer.php, src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Webhook/Service/CacheClearerSpec.php, src/Akeneo/Pim/Structure/Bundle/Query/PublicApi/Attribute/Cache/LRUCachedGetAttributes.php, tests/back/Pim/Structure/Specification/Bundle/Query/PublicApi/Attribute/Cache/LRUCachedGetAttributesSpec.php
Currently the consumer daemon is restarted regularly to invalidate any cache on permissions or structure. This PR aims to clear cache from services that are used during the process of sending events to webhooks. …
=> CXP-582: Clear cache after sending events to webhooks

CHANGELOG.md, src/Akeneo/Pim/Structure/Component/Manager/AttributeOptionsSorter.php, tests/back/Pim/Structure/Specification/Component/Manager/AttributeOptionsSorterSpec.php
A typo was introduced during a fix for PHP Stan that prevented the attribute options to be manually sorted. There was no unit test on this code so we didn't see the error. I added one in this PR. …
=> PIM-9596: Fix attribute options manual sorting

src/Akeneo/Connectivity/Connection/back/Infrastructure/Install/InstallSubscriber.php, src/Akeneo/Connectivity/Connection/back/Infrastructure/Install/Query/CreateConnectionEventsApiRequestCountTableQuery.php, upgrades/schema/Version_5_0_20201207171120_create_connection_events_api_request_count_table.php, upgrades/test_schema/Version_5_0_20201207171120_create_connection_events_api_request_count_table_Integration.php
We want to be able to implement a “rate limiting” on the Events API.
Rate limiting would be “per hour”.
- dbtable
- akeneo_connectivity_connection_events_api_request_count
- minute (int)
- count (int)
- updated (datetime)
- migration (+ migration test) + installer
| Tech Doc …
=> CXP-598: store count of events api request per minute

src/Akeneo/Pim/Structure/Bundle/EventSubscriber/InitDeletedAttributeSchemaSubscriber.php, src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev/jobs.yml, tests/legacy/features/Context/catalog/apparel/jobs.yml, tests/legacy/features/Context/catalog/default/jobs.yml, tests/legacy/features/Context/catalog/footwear/jobs.yml
- Removing the job db insert on the POST_LOAD_FIXTURES event and adding it instead in each catalog fixtures
=> RAC-394: Remove job insert from subscriber and add it in fixtures

tests/back/Acceptance/Channel/InMemoryChannelRepository.php
Without this missing `use`, there is no way `InMemoryChannelRepository::getChannelCodes()` can work.
I already did this fix 2 months ago, but on the 4.0 branch ><.
=> Fix "in memory" channel repository

akeneo-design-system/src/components/Image/Image.tsx
Alignment of image was wrong on Table component.
Before: 
Now:
=> Fix css alignement of image in Table row

CHANGELOG.md, src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml, src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.fr_FR.yml, src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/translations/jsmessages.en_US.yml, src/Akeneo/Tool/Component/Connector/Writer/File/AbstractItemMediaWriter.php, src/Oro/Bundle/PimDataGridBundle/Controller/ProductExportController.php, src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/actions-panel.js, src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/quickexport/component/QuickExportConfigurator.tsx, src/Oro/Bundle/PimDataGridBundle/tests/front/unit/QuickExportConfigurator.unit.tsx, tests/legacy/features/pim/enrichment/product/mass-action/quick-export/quick_export.feature, tests/legacy/features/pim/enrichment/product/mass-action/quick-export/quick_export_grid_context.feature, tests/legacy/features/pim/enrichment/product/mass-action/quick-export/quick_export_products_and_product_models.feature, tests/legacy/features/pim/enrichment/product/mass-action/quick-export/quick_export_with_localized_data.feature, tests/legacy/features/pim/enrichment/product/mass-action/quick-export/quick_export_with_media.feature
Change a little the behavior to handle asset files use case (https://github.com/akeneo/pim-enterprise-dev/pull/10009)
Not very proud of this but overriding this method in EE would be worse IMHO
When we export product/product model with asset files, we need to add all the files in the archive BUT we need to NOT replace the column values by the paths
=> CPM-54: handle multiple media files in product and product model export

.circleci/config.yml, CHANGELOG-3.2.md, package.json, yarn.lock
To avoid version bugs (appeared in EE)
=> PIM-9599: Fix @babel/types dependency to ~7.11.5

src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/validators.en_US.yml, src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/ConstraintViolationNormalizer.php, src/Akeneo/Pim/Structure/Bundle/Query/InternalApi/Attribute/GetBlacklistedAttributeJobExecutionId.php, src/Akeneo/Pim/Structure/Bundle/Resources/config/validators.yml, src/Akeneo/Pim/Structure/Component/Query/InternalApi/GetBlacklistedAttributeJobExecutionIdInterface.php, src/Akeneo/Pim/Structure/Component/Validator/Constraints/BlacklistedAttributeCode.php, src/Akeneo/Pim/Structure/Component/Validator/Constraints/BlacklistedAttributeCodeValidator.php, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/form/common/fields/field.html, tests/back/Pim/Structure/Integration/Attribute/Validation/BlacklistedAttributeCodeIntegration.php, tests/back/Pim/Structure/Specification/Component/Validator/Constraints/BlacklistedAttributeCodeValidatorSpec.php
In this PR, change the validation error to give the direct link to job only on internal API.
=> RAC-395: Validation error with direct link to job only on internal API

CHANGELOG.md, src/Akeneo/Channel/Bundle/Query/Sql/SqlGetChannelCodeWithLocaleCodes.php, src/Akeneo/Channel/Component/Query/PublicApi/Cache/CachedChannelExistsWithLocale.php, src/Akeneo/Channel/Component/Query/PublicApi/GetChannelCodeWithLocaleCodesInterface.php, src/Akeneo/Pim/Enrichment/.php_cd.php, src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/EntityWithValues/AddDefaultValuesSubscriber.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/event_subscribers.yml, tests/back/Acceptance/Channel/InMemoryGetChannelCodeWithLocaleCodes.php, tests/back/Acceptance/spec/Channel/InMemoryGetChannelCodeWithLocaleCodesSpec.php, tests/back/Channel/Specification/Component/Query/PublicApi/Cache/CachedChannelExistsWithLocaleSpec.php, tests/back/Pim/Enrichment/Integration/Product/CreateEntityWithDefaultValuesIntegration.php, tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/EntityWithValues/AddDefaultValuesSubscriberSpec.php
Given a boolean attribute with a `default_value`, this PR adds the default value at product / product model creation. Any existing value for this attribute will not be overridden.
I chose to implement it in a PRE_SAVE subscriber; this has pros and cons:
**pros**
- we are positive that the event is triggered when persisting a product or model, as the product(model)saver is the only mandatory service called (for instance we don't have to use the ProductUpdater, even if we do it 99% of the time)
- most entities related to the product (attributes, family...) are already loaded in the UnitOfWork at that point, so in a vast majority of the cases it should not trigger any additional SQL query
**cons**
- the product is updated after validation …
=> CPM-96: Set default values when creating a product or product model

CHANGELOG.md, src/Akeneo/Channel/Bundle/Doctrine/Query/FindActivatedCurrencies.php, src/Akeneo/Channel/Bundle/EventListener/ClearCacheSubscriber.php, src/Akeneo/Channel/Bundle/Resources/config/queries.yml, src/Akeneo/Channel/Component/Query/PublicApi/Cache/CachedChannelExistsWithLocale.php, src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/services.yml, src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/Service/CacheClearer.php, src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Webhook/Service/CacheClearerSpec.php, src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Query/FindQuantifiedAssociationTypeCodes.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml, src/Akeneo/Pim/Structure/Bundle/Query/PublicApi/Attribute/Cache/LRUCachedGetAttributes.php, src/Akeneo/Pim/Structure/Bundle/Resources/config/queries.yml, src/Akeneo/Tool/Bundle/StorageUtilsBundle/DependencyInjection/AkeneoStorageUtilsExtension.php, src/Akeneo/Tool/Bundle/StorageUtilsBundle/Resources/config/cache.yml, src/Akeneo/Tool/Component/StorageUtils/Cache/CachedQueriesClearer.php, src/Akeneo/Tool/Component/StorageUtils/Cache/CachedQueriesClearerInterface.php, src/Akeneo/Tool/Component/StorageUtils/Cache/CachedQueryInterface.php, src/Akeneo/Tool/Component/StorageUtils/spec/Cache/CachedQueriesClearerSpec.php, tests/back/Channel/Specification/Bundle/EventListener/ClearCacheSubscriberSpec.php, tests/back/Pim/Enrichment/Integration/Doctrine/Query/FindQuantifiedAssociationTypeCodesIntegration.php
In this PR we introduce:
- a dedicated interface for cachedQuery called CachedQueryInterface
- a tag for those queries that are automagically injected into a the "Connectivity/CacheClearer" class
- some queries directly injected in the "Connectivity/CacheClearer" were tagged with the new tag and removed from the CacheClearer constructor injection
- pim_channel.query.cache.channel_exists_with_locale
- pim_catalog.query.find_activated_currencies
- Akeneo\Pim\Structure\Bundle\Query\PublicApi\Attribute\Cache\LRUCachedGetAttributes
| …
=> RAC-436: Add cache to FindQuantifiedAssociationTypeCodes

CHANGELOG-4.0.md, src/Akeneo/Platform/Bundle/ImportExportBundle/Purge/PurgeJobExecution.php, src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/services.yml, src/Akeneo/Tool/Bundle/BatchBundle/Persistence/Sql/GetJobExecutionIds.php, src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/removers.yml, src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/services.yml, src/Akeneo/Tool/Bundle/BatchBundle/Storage/DeleteJobExecutionLogs.php, tests/back/Tool/Integration/Batch/Persistence/Sql/GetJobExecutionIdsIntegration.php
When calling the command `akeneo:batch:purge-job-execution`, we should also remove the logs of those deleted jobs.
Batch logs are logged like this:
```
batch/
24/
batch_5dfd97dbb66807705ce1bcf5c38c69c1cede36dc.log
```
In that case, the directory `24` is always the job execution id.
So the solution is a query to find the ids of the soon-to-be removed jobs, then removing this directories in the logs.
| Added integration tests           | yes
| Review …
=> PIM-9551: Add service for purging logs from job executions

akeneo-design-system/src/components/Input/TextInput/TextInput.tsx, src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/attribute/form/delete/DeleteModal.tsx, src/Akeneo/Platform/Bundle/UIBundle/tests/front/unit/attribute/form/delete/DeleteAction.unit.tsx, src/Akeneo/Platform/Bundle/UIBundle/tests/front/unit/attribute/form/delete/DeleteModal.unit.tsx, tests/legacy/features/Context/WebUser.php, tests/legacy/features/pim/enrichment/product/versioning/display_removed_value_history.feature, tests/legacy/features/pim/structure/attribute/delete_attribute.feature, tests/legacy/features/pim/structure/attribute/option/delete_attribute_options.feature
=> RAC-397: Add confirm attribute code field in delete modal

src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/BusinessEvent/DispatchProductCreatedAndUpdatedEventSubscriber.php, src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/BusinessEvent/DispatchProductModelCreatedAndUpdatedEventSubscriber.php, src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/BusinessEvent/DispatchProductModelRemovedEventSubscriber.php, src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/BusinessEvent/DispatchProductRemovedEventSubscriber.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/event_subscribers.yml, src/Akeneo/Tool/Bundle/MessengerBundle/Transport/GooglePubSub/GpsReceiver.php, src/Akeneo/Tool/Bundle/MessengerBundle/Transport/GooglePubSub/GpsSender.php, src/Akeneo/Tool/Bundle/MessengerBundle/spec/Transport/GooglePubSub/GpsReceiverSpec.php, src/Akeneo/Tool/Bundle/MessengerBundle/spec/Transport/GooglePubSub/GpsSenderSpec.php, tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/BusinessEvent/DispatchProductCreatedAndUpdatedEventSubscriberSpec.php, tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/BusinessEvent/DispatchProductModelCreatedAndUpdatedEventSubscriberSpec.php, tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/BusinessEvent/DispatchProductModelRemovedEventSubscriberSpec.php, tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/BusinessEvent/DispatchProductRemovedEventSubscriberSpec.php
Make event dispatching more resilient to infrastructure issues.
If there is an issue with Google PubSub (for example) then we should not necessarily break the PIM behavior and/or the UI. 
Instead the error is log as critical (still monitored by the SRE).
=> CXP-597 make event dispatching more resilient

CHANGELOG.md, src/Akeneo/Pim/Enrichment/Component/Product/Model/AbstractProduct.php, src/Akeneo/Pim/Enrichment/Component/Product/Model/ProductModel.php, src/Akeneo/Pim/Enrichment/Component/Product/Model/QuantifiedAssociation/QuantifiedAssociationCollection.php, tests/back/Pim/Enrichment/Specification/Component/Product/Model/ProductModelSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Model/ProductSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Model/QuantifiedAssociation/QuantifiedAssociationCollectionSpec.php
Last PR in the series of _**Do not save a product or product model if it was not actually updated**_ :slightly_smiling_face: 
Here we compare the quantified association collection before and after calling methods which potentially update it to compute the state of the product / model (aka `isDirty()`). In order to do so, I added the `QuantifiedAssociationCollection::equals()` public method …
=> Do not update products or models when quantified associations were not updated

CHANGELOG-4.0.md, src/Akeneo/Pim/Structure/Bundle/Doctrine/ORM/Repository/FamilyRepository.php, tests/back/Pim/Structure/Integration/Doctrine/ORM/Repository/FamilyRepositoryIntegration.php
Because the pagination feature was not implemented in the repository, the dropdown was not able to do the infinite scroll and if a family on another page than the first one is selected, it was not displayed. …
=> PIM-9602: Fix family dropdown on product model creation modal

CHANGELOG.md, src/Akeneo/Tool/Component/Localization/LanguageTranslator.php, src/Akeneo/Tool/Component/Localization/spec/LanguageTranslatorSpec.php
When the bs_Cyrl_BA locale is active on the exported channel, the quick export with labels fails if there are localizable attributes.
When translating the locale for the header Intl is not able to find a translation.
Updating to Intl 5.2.0 does not fix the problem.
I use the given fallback when the Exception is thrown.
| …
=> PIM-9598: Fix quick export when the bs_Cyrl_BA locale is used

src/Akeneo/Pim/Enrichment/Bundle/Product/ComputeAndPersistProductCompletenesses.php, src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Completeness/SqlGetCompletenessProductMasks.php
Completeness can takes a lots of space in memory due to masks, locales, etc.
This PR is a first step to reduce the required memory by processing the completeness by chunks.
Next step will be to use iterable generators which should not need any arbitrary chunk size.
=> PIM-9601: Fix completeness mask memory usage

CHANGELOG-4.0.md, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/normalizers.yml, src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/AxisValueLabelsNormalizer/MetricNormalizer.php, tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/InternalApi/AxisValueLabelsNormalizer/MetricNormalizerSpec.php
In the variant navigation component, display the label of the unit instead of its code for measurement attribute axes
**:warning: this PR cannot be pulled up as is into master** (the way to get unit labels has changed in master), it will need to be reworked during the next pull-up
| …
=> PIM-9605: Display unit label instead of code in variant navigation dropdown

CHANGELOG.md, src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/ProductAndProductModel/GetProductIdentifiersWithRemovedAttribute.php, src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/ProductAndProductModel/GetProductModelIdentifiersWithRemovedAttribute.php
**Summary:** 
The number of processed items in product clean is invalid when we remove an attribute from the PIM. On the icecat catalog when we remove the attribute name the number of processed item is invalid.
**Explanation**
Why this happened ? The last product on the last batch is "AKNSTK". To know if it's the last batch we use "AKNSTK" 
on search after field. In the pim the identifier are indexed by lowercase identifier. Elasticsearch loop randomly several time with the query `search_after: ["AKNSTK"]` (here 10 times). 
I think that this result, is returned while the product is really deleted on elasticsearch but I find nothing on documentation.
**Now**
Now search_after is filled with "aknstk" and we didn't have the problem now. …
=> RAC-449: search after does not work when identifier is in uppercase

akeneo-design-system/src/components/Modal/Modal.stories.mdx, akeneo-design-system/src/components/Modal/Modal.tsx, akeneo-design-system/src/components/Modal/Modal.unit.tsx, akeneo-design-system/src/patterns/Overlays.stories.mdx, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/attribute/form/delete/DeleteModal.tsx, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/execution/StopJobAction.tsx, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/create-measurement-family/CreateMeasurementFamily.tsx, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/create-unit/CreateUnit.tsx, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/ConfirmDeleteModal.tsx, src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/quickexport/component/QuickExportConfigurator.tsx
The DSM modal had a prop `isOpen` which does not really make sense.
Either you want to display a modal and you mount `<Modal/>`, or you want to display it conditionally and you do `{isModalOpen && <Modal/>`.
By always mounting it, we consume useless resources and we introduced a bug:
When mounted, the dom is injected and the `useShortcut(Key.Escape, onClose);` is immediatly registered, even if the modal is not visible !
The proposed solution is to remove this prop and fix usages around the PIM. …
=> RAC-453: Remove isOpen prop from the DSM modal

akeneo-design-system/src/hooks/useShortcut.ts
The current version of `useShortcut` automatically stop the propagation of the event.
IMHO, since this event is passed to the callback, it's the responsibility of the listener to decide whether the event should be stopped or not.
Enforcing such behavior in the DSM does not really allow flexibility when using it. …
=> RAC-454: useShortcut doesnt stop propagation by default

CHANGELOG.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/quantified-associations/hooks/useProductThumbnail.ts, src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/shared/tests/front/unit/utils.tsx, src/Akeneo/Platform/Bundle/UIBundle/tests/front/unit/hooks/useProductThumbnail.unit.tsx
When the image is coming from the Asset Manager, it is already a ready-to-use path so we can return it directly. Same workflow as here https://github.com/akeneo/pim-enterprise-dev/blob/master/src/Akeneo/AssetManager/front/domain/model/asset/data/media-file.ts#L4
| Tech Doc …
=> PIM-9612: Fix no image preview for Association with quantities when the image is an asset collection

CHANGELOG.md, src/Akeneo/Tool/Component/Localization/Factory/DateFactory.php, src/Akeneo/Tool/Component/Localization/spec/Factory/DateFactorySpec.php
A lot of locales have a short date representation with only 2 digits for the year. In the PIM such a format makes it really difficult for a user to define a date in the datepicker, and even impossible to set dates before 1970 or after 2069 (e.g: 1/1/69 represents the 1st of January, 2069 whereas 1/1/70 represents the 1st or January, 1970)
This PR forces a 4-digit representation of the year for every locale, unless an exception is explicitly added in the `pim_catalog.localization.factory.date.formats` and/or `pim_catalog.localization.factory.datetime.formats` parameters
(Note: there are currently 3 exceptions en_US, fr_FR and it_IT, and all of them actualmly replace the default 2-digit year by a 4-digit year...)
**Definition Of Done (for …
=> PIM-9610: Replace 2-digit year by 4-digit year in date patterns

src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/src/components/panel/announcement/Tag.tsx
The tag (in blue on the image below after fix) didn't have any style. This is the fix to add it.
It also fixes `updates` as `update` to be consistent, and add a default color for an unknown tag.
https://github.com/akeneo/actionable-product-data/issues/270
| Tech Doc …
=> Fix color of the tags for announcements in communication panel

CHANGELOG-3.2.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/pim-app.js, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/Overlay.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/index.less
- Adding Overlay less file (backported from `master`)
- Adding click behaviour & mediator event listener
=> PIM-9614: Fix missing overlay when the announcements panel is open

CHANGELOG-4.0.md, src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ElasticsearchProjection/GetElasticsearchProductProjection.php
The indexation command is very slow for a customer (30 hours for 680k products). The issue is the slow query to fetch the results from Mysql. It is not reproducible every time. Sometimes, after a restart, it's slow, Sometimes, it's fast, despite 5 restarts in a row...
The part to fetch the completeness is responsible of this slowness.
The query can be simplified this way:
```
EXPLAIN ANALYZE WITH product as (
SELECT
product.id, 
product.identifier
FROM 
pim_catalog_product product 
WHERE 
product.identifier IN (1000 products identifiers)
)
SELECT
product_id,
channel.code as channel_code
FROM
product
JOIN pim_catalog_completeness completeness ON completeness.product_id = product.id
JOIN pim_catalog_channel channel ON channel.id = completeness.channel_id
JOIN pim_catalog_locale locale ON …
```
=> PIM-9611: force the order of a join due to statistics bias for low cardinality

tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/Date/DateFilterIntegration.php
Test that failed:
```
AkeneoTest\Pim\Enrichment\Integration\PQB\Filter\Date\DateFilterIntegration::testRelativeDates
Failed asserting that two arrays are identical.
--- Expected
+++ Actual
@@ @@
-Array &0 (
-    0 => 'product_future'
-)
+Array &0 ()
/srv/pim/tests/back/Pim/Enrichment/Integration/PQB/AbstractProductQueryBuilderTestCase.php:164
/srv/pim/tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/Date/DateFilterIntegration.php:176
```
This fix simplify the tests to avoid to have comparison on an exact day. A better fix will done later.
=> Fix date filter integration test

CHANGELOG.md, src/Akeneo/Platform/Bundle/ImportExportBundle/Controller/InternalApi/JobInstanceController.php, src/Akeneo/Platform/Bundle/ImportExportBundle/Repository/InternalApi/JobExecutionRepository.php, src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/controllers.yml, src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/datagrid/last_executions.yml, src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/datagrid/last_export_executions.yml, src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/datagrid/last_import_executions.yml, src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/public/js/datagrid/Actions.tsx, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/common/edit/launch.js, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/common/edit/upload-launch.js, src/Oro/Bundle/PimDataGridBundle/EventListener/AddJobCodeToGridListener.php
A 403 error was served after dropping a valid product import file and clicking "Upload and import now" in the case the user has no permission to "View import report details".
Validating by Benjamin and Stéphane:
If no permission to view the import report details, we need to remove the action button "view" to avoid 403 errors
and we need to stay on the import profile page after launching an import.
So, when the user does not have the rights to view the import details:
- I made sure that we stay on the import profile page after launching the job execution by returning an empty URL to the upload-launch.js file
- I made the view button invisible using useSecurity ()
- I added a reload of the import profile page to see the last executions …
=> PIM-9595: Avoid 403 error when launching import with no view rights on import details

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/attribute/form/delete/DeleteModal.tsx, src/Akeneo/Platform/Bundle/UIBundle/tests/front/unit/attribute/form/delete/DeleteModal.unit.tsx
RAC-450: Handle confirm when hitting enter on the Delete Attribute modal, also rewriting the `fetch` call using `async/await`
=> RAC-450: Handle confirm when hitting enter on the Delete Attribute modal

CHANGELOG.md, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/KeyIndicator/ComputeProductsEnrichmentStatusQuery.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/queries.yml
The following query generates a MySQL memory allocation error for big catalogs:
```
SELECT product_id, JSON_OBJECTAGG(criterion_code, result) as results
FROM pim_data_quality_insights_product_criteria_evaluation
WHERE product_id IN(:productIds) AND criterion_code IN(:criterionCodes)
GROUP BY product_id
```
Due to  `GROUP BY`, MySQL performs a "filesort" on the table (it can be seen with an `EXPLAIN`). If the table is huge, the memory needed for this operation can exceed the allocated memory.
The solution is to execute two simple queries instead of this one. It needs some rework to regroup the results of the evaluations of the two completeness criteria, being careful to the PHP memory because all the results are fetched at once.
=> PIM-9622: Fix query that can generate a MySQL memory allocation error

akeneo-design-system/src/components/Checkbox/Checkbox.tsx, akeneo-design-system/src/components/Dropdown/Dropdown.stories.mdx, akeneo-design-system/src/components/Dropdown/Dropdown.tsx, akeneo-design-system/src/components/Dropdown/Header/Header.tsx, akeneo-design-system/src/components/Dropdown/Header/Title.tsx, akeneo-design-system/src/components/Dropdown/Item/Item.tsx, akeneo-design-system/src/components/Dropdown/ItemCollection/ItemCollection.tsx, akeneo-design-system/src/components/Dropdown/Overlay/Overlay.tsx
In this PR: 
- Add Dropdown sub components in the dropdown documentation page
- Remove Dropdown.ItemLabel because for the moment we don't need it, this component is used when we have string in Dropdown.Item component
- Remove Dropdown.Content because it's never used
- Move Dropdown.Tile and Dropdown.Header into function component because Storybook expose styled component props instead of children  …
=> RAC-375: add dropdown subcomponent documentation on storybook

CHANGELOG-4.0.md, src/Akeneo/Pim/Structure/Bundle/Doctrine/ORM/Repository/FamilyRepository.php, tests/back/Pim/Structure/Integration/Doctrine/ORM/Repository/FamilyRepositoryIntegration.php
When we select a family not present in the first page on create product model page, the family is not displayed.
**Why ?**
Because when we select the value an ajax call is made :
https://github.com/akeneo/pim-community-dev/blob/8a7f6f25553b5f4887a4e0918a4d7207dacb88a3/src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/fields/simple-select-async.js#L172
Currently the parameters identifiers is ignored, it does not make problem when identifier is in the twenty first result but it make problem when family is in the second page. In this PR, if the parameter identifier is given I also filter result by identifiers
| …
=> PIM-9627: fix empty family field when creating a product model with family not present in first page

src/Akeneo/Connectivity/Connection/back/Application/Webhook/Command/CheckWebhookReachabilityCommand.php, src/Akeneo/Connectivity/Connection/back/Application/Webhook/Command/CheckWebhookReachabilityHandler.php, src/Akeneo/Connectivity/Connection/back/Application/Webhook/Service/UrlReachabilityCheckerInterface.php, src/Akeneo/Connectivity/Connection/back/Infrastructure/InternalApi/Controller/WebhookController.php, src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml, src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/Client/GuzzleWebhookClient.php, src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/Client/Signature.php, src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/RequestHeaders.php, src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/Service/WebhookReachabilityChecker.php, src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Webhook/Command/CheckWebhookReachabilityCommandSpec.php, src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Webhook/Command/CheckWebhookReachabilityHandlerSpec.php, src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Webhook/Client/GuzzleWebhookClientSpec.php, src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Webhook/Client/SignatureSpec.php, src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Webhook/Service/WebhookReachabilityCheckerSpec.php, src/Akeneo/Connectivity/Connection/front/src/webhook/components/EditForm.tsx, src/Akeneo/Connectivity/Connection/front/src/webhook/hooks/api/use-webhook-check-reachability.ts
Two headers were missing from the request: `x-akeneo-request-timestamp` and `x-akeneo-request-signature`. We need it because when you develop your own app to receive webhook data without the headers there is no solution to know if the request really comes from Akeneo.
| Tech Doc …
=> CXP-616: Send akeneo headers when testing an URL during event subscriptions configuration

CHANGELOG-4.0.md, src/Akeneo/Pim/Structure/Bundle/Query/PublicApi/AttributeOption/Cache/LRUCachedGetExistingAttributeOptions.php, tests/back/Pim/Structure/Specification/Bundle/Query/PublicApi/AttributeOption/Cache/LRUCachedGetExistingAttributeOptionsSpec.php
When the product is updated with a simple option attribute, the validation uses the cache to validate the existence of the option code. There was an error when we used code with bad case.
For instance when the attribute code is `simple` and the option code is `yes`, and we update product with "YES" through API:
**Before this PR**
We make the query and put in cache:
```json
{"simple.YES": false, "simple.yes": true}
```
=> The validation is ok because there is ` "simple.yes": true`.
The second time, we don't make the query because we have the key `simple.YES` in cache, we use it so we have:
```json
{"simple.YES": false}
```
=> The validation fails. It misses the ` "simple.yes": true` part
**The fix**
To fix that I change the caching method. Now I cache:
- key: always in lower case (ex: …
=> PIM-9635: make the attribute option code insensitive in cache

CHANGELOG.md, src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product-model/form/add-child/header.js, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/product_model/add-child/header.html
In this PR:
- Add possibility to have plurial on add variant page depending on number of variant
**Why use an another key ?**
Because when axesCount is greater than 1 and the message is not plurialized, the translator display nothing when the translation does not have multiple translations.
By adding a new key, this force translator to create a new translation instead of having a bug on all languages ​​except English because they doesn't follow the convention of plurialized translation. …
=> PIM-9636: add posibility to contextualize translation when create a variant depending on number of axes

behat.yml
Before:
```
curl "https://circleci.com/api/v1.1/project/github/akeneo/pim-community-dev/71836/tests?circle-token=XXXXXX" | jq '.tests |= sort_by(.run_time) | .tests[].run_time' | awk '{sum+=$1} END{printf("%f\n",sum)}'  
12474.341000 (seconds)
```
After:
```
curl "https://circleci.com/api/v1.1/project/github/akeneo/pim-community-dev/71869/tests?circle-token=XXXXXXX" | jq '.tests |= sort_by(.run_time) | .tests[].run_time' | awk '{sum+=$1} END{printf("%f\n",sum)}'  
10187.043000 (seconds)
``` …
=>  ci: use headless chrome browser to speedup the time by ~15%

CHANGELOG.md, src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/FollowUp/GetCompletenessPerChannelAndLocale.php
Fixes SQL sort buffer size issue when the catalog has a very large number of categories
Remove the ordering on channel codes which it seems to be useless
=> PIM-9630: Dashboard completeness broken due to mysql buffer size

CHANGELOG-4.0.md, src/Oro/Bundle/PimDataGridBundle/Extension/MassAction/MassActionDispatcher.php, src/Oro/Bundle/PimDataGridBundle/spec/Extension/MassAction/MassActionDispatcherSpec.php
This PR fixes a bug in the sequential edit feature when selecting All (in the mass action toolbar) with a filter on parent. There was a rule in the code that transformed the parent filter in an Ancestor filter when all rows were selected. This was to fix a bug where we wanted to be sure to apply the action on ALL the variants. But in the sequential edit, we only want to apply the action on the selected products and not on the variants. 
So basically we want 2 opposite behaviors with the same code base. The fix was simply to apply the transformation I described before only when this is not a sequential edit. …
=> PIM-9639: Fix sequential edit when selecting All with a filter on parent

src/Akeneo/Tool/Bundle/MessengerBundle/Command/PurgeMessengerCommand.php, src/Akeneo/Tool/Bundle/MessengerBundle/DependencyInjection/AkeneoMessengerExtension.php, src/Akeneo/Tool/Bundle/MessengerBundle/Query/PurgeDoctrineQueueQuery.php, src/Akeneo/Tool/Bundle/MessengerBundle/Resources/config/purge.yml, src/Akeneo/Tool/Bundle/MessengerBundle/tests/integration/PurgeDoctrineQueueIntegration.php
When you install the PIM on OnPrem the queue is handle by doctrine which uses an SQL table to store messages.
Doctrine does not handle the purge of this table. This PR aims to add a purge command to cover this need. …
=> CXP-626: Add purge messenger command

.circleci/config.yml
EE is tested in a dedicated build each night and we don't need to retest it in this repo
=> Remove EE tests from nightly build

CHANGELOG.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/family/form/attributes/attributes.js
This PR fixes a JS error that prevented attribute groups to be displayed in the family edit form where there was more that 20 attribute groups in the family. The endpoints to get attribute groups accepts a `limit` option that has a default value to 20 if not set. The option was indeed not set so the returned attribute groups were capped to 20, and this triggered a JS error because we tried to access a group that didn't exist.
We don't want a limit in this particular use case and the only to do it is to set a limit to a negative number. …
=> PIM-9631: fix attribute groups not displayed in family due to JS error

src/Akeneo/Pim/Enrichment/Bundle/Resources/config/versions.yml, src/Akeneo/Tool/Bundle/ElasticsearchBundle/IndexConfiguration/UpdateIndexMappingWrapper.php, src/Akeneo/Tool/Bundle/ElasticsearchBundle/tests/integration/UpdateIndexMappingWrapperIntegration.php
From a migration we have access to public services only. Reindexing documents is not easy with this constraint.  
To faciliate the work, the `UpdateIndexMappingWrapper` class helps to handle this problem (see the [EE PR](https://github.com/akeneo/pim-enterprise-dev/pull/10251))
| Tech Doc …
=> PIM-9584: create public service to reindex documents from a migration

CHANGELOG-4.0.md, src/Oro/Bundle/PimFilterBundle/Filter/ProductValue/StringFilter.php
It has been decided that the IN_LIST string filter operator now accepts non-breaking spaces in values to mean actual spaces. This PRs modifies the value parsing to replace all non-breaking spaces with actual spaces. …
=> PIM-9623: String filter is now able to filter on codes with spaces

CHANGELOG-4.0.md, src/Akeneo/Pim/Enrichment/Bundle/Command/CleanRemovedAttributesFromProductAndProductModelCommand.php
Fixes `bin/console` list on 4.0
```
Argument 6 passed to Akeneo\Pim\Enrichment\Bundle\Command\CleanRemovedAttributesFromProductAndProduc  
tModelCommand::__construct() must be an instance of Symfony\Component\EventDispatcher\EventDispatche  
r or null, instance of Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher given, called in   
/var/www/var/cache/dev/ContainerYdVbSQO/getCleanRemovedAttributesFromProductAndProductModelCommandSe  
rvice.php on line 12
```
| Added …
=> PIM-9644: Now using interface in Clean removed attributes command constructor

src/Akeneo/Connectivity/Connection/back/Domain/Webhook/Model/Read/ConnectionWebhook.php, src/Akeneo/Connectivity/Connection/back/Domain/Webhook/Model/Read/EventSubscriptionFormData.php, src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/Dbal/Query/DbalGetAConnectionWebhookQuery.php, src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Webhook/GetEventSubscriptionFormDataEndToEnd.php, src/Akeneo/Connectivity/Connection/back/tests/Integration/Persistence/Dbal/Query/DbalGetAConnectionWebhookQueryIntegration.php, src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Domain/Webhook/Model/Read/ConnectionWebhookSpec.php, src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Domain/Webhook/Model/Read/EventSubscriptionFormDataSpec.php, src/Akeneo/Connectivity/Connection/front/src/webhook/components/EventSubscriptionHelper.tsx, src/Akeneo/Connectivity/Connection/front/src/webhook/hooks/api/use-fetch-connection.ts, src/Akeneo/Connectivity/Connection/front/src/webhook/hooks/api/use-fetch-event-subscription-form-data.ts, src/Akeneo/Connectivity/Connection/front/src/webhook/model/Webhook.ts, src/Akeneo/Connectivity/Connection/front/src/webhook/pages/EditConnectionWebhook.tsx
- Fix event subscription form to display the connection label as title (instead of the code)
- Fix the helper link
=> API-1414 fix event subscription edit form

.circleci/config.yml
Since few days,the CI step 'test_deploy' failed at a cleanup command.
The first hypothesis was a side effect on a non-consistent operation on GCS (link to the terraform backend).
But not!
We disabled the `-m` option in gsutil to disable the operation parallelism and show the real error. It's not clear in the gsutil documentation, but `-m` doesn't print errors, but catch all of them and print a generic message.
And the error is linked to a python issue, so a Gcloud SDK problem.
I upgrade the cloud-deployer version to use the last one, and the same as EE Circle CI workflow.
| Added Specs …
=> BH-350: update cloud-deployer

CHANGELOG.md, src/Akeneo/Pim/Enrichment/Bundle/PdfGeneration/Renderer/ProductPdfRenderer.php
Following https://github.com/akeneo/pim-community-dev/pull/12945, attributes from the family were added to the PDF render of the Product, but these are added after the values are filtered out based on permissions, so we need to check afterwards whether each attribute should be rendered.
See: https://github.com/akeneo/pim-enterprise-dev/pull/10277
| Micro …
=> PIM-9649: Fix PDF product renderer disregarding permissions on Attribute groups

akeneo-design-system/src/components/Checkbox/Checkbox.tsx, akeneo-design-system/src/hooks/useSelection.ts, akeneo-design-system/src/hooks/useSelection.unit.ts
In this PR, we expose the selection to be able to transform the selection mode into filters
=> RAC-477: expose selection to handle the mode on mass delete action

CHANGELOG.md, src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
When making a mass delete action, on the notification panel, instead of "Deletion", "pim_notification.types.mass_delete" was displayed.
So, I added the missing corresponding key in the jsmessages.en_US.yml file. …
=> PIM-9650: Add translation key for mass delete action and the corresponding word on the job page

CHANGELOG-3.2.md, src/Akeneo/Tool/Bundle/ApiBundle/DependencyInjection/PimApiExtension.php, src/Akeneo/Tool/Bundle/ApiBundle/EventListener/CheckApiRequestContentSizeListener.php, src/Akeneo/Tool/Bundle/ApiBundle/Resources/config/event_listeners.yml, src/Akeneo/Tool/Bundle/ApiBundle/tests/integration/Controller/Token/GetAccessTokenIntegration.php
Backporting https://github.com/akeneo/pim-community-dev/pull/13801
=> PIM-9648: [Backport] Mitigate DDoS risk on API auth endpoint by rejecting too large content

CHANGELOG.md, src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/ProductController.php, src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/ProductNormalizer.php, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/product/edit.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/fetcher/product-fetcher.js, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/main-image.js, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/product/product-main-image.ts
Adding a custom form extension for the PEF main image to refetch the normalized product with its localized or scoped image
=> PIM-9642: Refresh product image when switching channel or locale

src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml, src/Akeneo/Connectivity/Connection/front/src/webhook/components/EditForm.tsx
Fix documentation link on the helper displayed when the maximum number of enabled subscriptions is reached.
=> API fix event subscription documentation link

composer.json, composer.lock
There is an issue with aws/aws-sdk-php (aws/aws-sdk-php#2189) and we must fix the used version, at least temporary.
Thanks to @AymericPlanche for helping me fixing this one.
=> Fix aws/aws-sdk-php issue

CHANGELOG-4.0.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/lib/summernote.less
… to differentiate new paragraphs from mere line breaks
Backport of this fix => https://github.com/akeneo/pim-community-dev/pull/13236
=> PIM-9665: [Backport] PIM-9533: Update wysiwyg editor's style in order to differentiate new paragraphs from mere line breaks

tests/back/Integration/IntegrationTestsBundle/Messenger/AssertEventCountTrait.php, tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/PartialUpdateProductModelEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/ExternalApi/PartialUpdateVariantProductEndToEnd.php
This PR adds a more explicit error message during the assert event count.
It completes tests on product variant actions from API to be able to assert that all events are sent or not.
`OK`: Done / …
=> API-1432: Test that event are well handled during variant product actions

CHANGELOG.md, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/documentation.yml, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/validators.yml, src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/validators.en_US.yml, src/Akeneo/Pim/Enrichment/Component/Error/DocumentationBuilder/AttributeOptionValidation.php, src/Akeneo/Pim/Enrichment/Component/Product/Factory/NonExistentValuesFilter/NonExistentMultiSelectValuesFilter.php, src/Akeneo/Pim/Enrichment/Component/Product/Validator/ConstraintGuesser/OptionsGuesser.php, src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/DuplicateOptions.php, src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/DuplicateOptionsValidator.php, src/Akeneo/Pim/Enrichment/Component/Product/Value/OptionsValue.php, src/Akeneo/Pim/Enrichment/Component/Product/Value/OptionsValueInterface.php, src/Akeneo/Pim/Enrichment/Component/Product/Value/OptionsValueWithLinkedData.php, tests/back/Pim/Enrichment/Integration/Product/LoadEntityWithValuesSubscriberIntegration.php, tests/back/Pim/Enrichment/Specification/Component/Error/DocumentationBuilder/AttributeOptionValidationSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Factory/NonExistentValuesFilter/NonExistentMultiSelectValuesFilterSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Validator/ConstraintGuesser/OptionsGuesserSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/DuplicateOptionsValidatorSpec.php, tests/features/pim/enrichment/product/validation/option_values.feature
The PR validates that a multiselect value doesn't have duplicate options. It also deduplicates options when loading a product from the database, in case there already are duplicates in DB
| Added acceptance tests            | OK …
=> PIM-9667: Prevent import of duplicate options in multiselect attributes

tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/DeleteProductEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/PartialUpdateProductEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/CreateProductModelEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/PartialUpdateProductModelEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/ExternalApi/CreateVariantProductEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/ExternalApi/DeleteVariantProductEndToEnd.php
This PR adds a more explicit error message during the assert event count.
It completes tests on product variant actions from API to be able to assert that all events are sent or not.
=> API-1422: Test that event are well handled during variant product actions

CHANGELOG.md, src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/ProductController.php
Turn a 500 Exception into a formatted Exception when 
**"data": [null]**
In API update product
=> PIM-9672: Error 500 on the API when inputing [null] on an array

tests/back/Integration/IntegrationTestsBundle/Messenger/AssertEventCountTrait.php
=> API: Add a way to clear message bus observer

CHANGELOG.md, src/Akeneo/Pim/Structure/Bundle/Doctrine/ORM/Repository/InternalApi/AttributeGroupRepository.php
This pull request fixes the display of the filter groups in the attribute grid when there are several attribute groups with the same label.
=> PIM-9670: Fix attribute filter Group issue when several attribute groups have the same label

package.json, yarn.lock
In one the latest version of `@types/backbone` (1.4.9), a breaking change was introduced in the View interface.
see https://github.com/DefinitelyTyped/DefinitelyTyped/commit/01db383f12ef1c1499a6acc826fcfac01c9095e5#diff-d60bebcbc6b7b8fc4d481b68f93d350fe46e7c01dff65af9ab447dcd87eaf236R579-R580
I think that the newer interface is correct but it's clearly incompatible with a lot of our inherited classes.
Yes, we should update our code accordingly (I've looked into it, at least a dozen classes) but it's not something we should do in 3.2, which is in maintenance mode only.
This error does not directly happen in `pim-community-dev@3.2` because we have a yarn.lock, but it does appear in `pim-enterprise-standard@3.2` when using the onboarder …
=> AOB-1300: Fix Onboarder bundle front build

akeneo-design-system/src/components/Button/Button.tsx
Before:
After:
Also simplifying styled component Container using the builtin `as` prop
=> RAC-511: Fix DSM Button outline style

CHANGELOG-5.0.md, src/Akeneo/Pim/Structure/.php_cd.php, src/Akeneo/Pim/Structure/Bundle/Controller/ExternalApi/AttributeController.php, src/Akeneo/Pim/Structure/Bundle/EventSubscriber/ApiAggregatorForAttributePostSaveEventSubscriber.php, src/Akeneo/Pim/Structure/Bundle/Resources/config/controllers.yml, src/Akeneo/Pim/Structure/Bundle/Resources/config/event_subscribers.yml
There are a performance issue when updating attributes with the API end-point "PATCH attributes".
It's because an event POST_SAVE with the parameter `unitary` at `true` is dispatched for each attribute while it's a "batch" process. A subscriber of the DQI context listen to these events and launch computations that takes time.
The parameter `unitary` was designed for this kind of cases. It allows to distinct a single update from a multiple/batch update.
This kind of problem has already been spotted and fixed for the products. A subscriber has been added to put the parameter `unitary` to false and dispatch a POST_SAVE_ALL event.
dev/blob/master/src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/Product/OnSave/ApiAggregatorForProductPostSaveEventSubscriber.php
=> PIM-9620: Fix performance issue on API attributes partial update list

CHANGELOG.md, src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/ComputeCompletenessOfFamilyProductsTasklet.php, tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Job/ComputeCompletenessOfFamilyProductsTaskletSpec.php
Fix a memory leak caused by products fetch by the ORM in the tasklet `ComputeCompletenessOfFamilyProductsTasklet`
=> PIM-9686 fix memory issue of compute completeness task

CHANGELOG-5.0.md, src/Oro/Bundle/SecurityBundle/DependencyInjection/Compiler/AclConfigurationPass.php
Working on the PIM V5 compatibility on the Supplier Onboarder, we've found a nested ternary expression that prevents us from running our integration tests. This is deprecated [since PHP 7.4.](https://wiki.php.net/rfc/ternary_associativity)
Here a fix adding paranthesis to the second ternary. …
=> AOB-1317: Fix deprecated nested ternary expression

CHANGELOG.md, src/Akeneo/Tool/Bundle/BatchQueueBundle/Manager/JobExecutionManager.php, src/Akeneo/Tool/Bundle/BatchQueueBundle/spec/Manager/JobExecutionManagerSpec.php
The healthcheck system doesn't handle stopping status, now the status is also mark as failed when healthcheck is not up to date
=> PIM-9690: Fix HeathCheck system doesn't handle stopping status

tests/back/Integration/IntegrationTestsBundle/Messenger/AssertEventCountInTransportTrait.php, tests/back/Pim/Enrichment/EndToEnd/Product/MassEdit/AbstractMassEditEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/MassEdit/MassEditCategoriesOfEntitiesEndToEnd.php, tests/legacy/features/pim/enrichment/product-model/edit_product_model.feature
Add 2 legacy tests on variant products.
Add a way to easily create EndToEnd tests on bulk actions. 
=> API-1407: Add tests on variant products

CHANGELOG-4.0.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/categories.js, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/lib/jquery.jstree.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/jstree/jquery.jstree.js
In this PR: 
- Allow possibility to define category tab is read only => backport of https://github.com/akeneo/pim-community-dev/pull/13362
=> PIM-9696: Associations and categories display according to the ownership rights

CHANGELOG.md, src/Akeneo/Pim/Enrichment/Bundle/Command/IndexProductCommand.php, src/Akeneo/Pim/Enrichment/Bundle/Command/IndexProductModelCommand.php, src/Akeneo/Tool/Bundle/ElasticsearchBundle/Client.php
Add a new option to the product/product-models index command to choose the number of records to index per batch (batch-size).
The default batch-size value is 1000
Affected commands:
1 - "bin/console pim:product:index"
2 - "bin/console pim:product-model:index"
ex:
"bin/console pim:product:index --all"  >> batch-size is 1000
"bin/console pim:product:index --all --batch-size=100" >> batch-size is 100
"bin/console pim:product:index  identifier_1 identifier_2 ... --batch-size=100"  >> batch-size is 100
Tested on duplicated env:
https://stellamccartney-dev-sds-17219.dev.cloud.akeneo.com
| Added Specs …
=> PIM-9700: Add batch-size option in index products command and index product-models command

CHANGELOG.md, src/Akeneo/Platform/Bundle/ImportExportBundle/Controller/InternalApi/JobExecutionController.php, src/Akeneo/Platform/Bundle/ImportExportBundle/Datagrid/GridHelper.php, src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/controllers.yml, src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/datagrid/job_tracker.yml, src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/grid.yml, src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/public/js/last-operations-widget.js, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/execution/index.tsx, tests/back/Platform/Specification/Bundle/ImportExportBundle/Datagrid/GridHelperSpec.php
In this PR :
- Last operation dashboard redirect to job_tracker view
- Add permission check on process tracker view (user can view export/import detail only if the permission is given)
- Now user cannot click on export/import row in process tracker when user doesn't have permission to display import details
| …
=> PIM-9699: Fix clicking detail on last operation return 404 on import and export

CHANGELOG.md, src/Akeneo/Connectivity/Connection/front/src/webhook/components/EditForm.tsx, src/Akeneo/Connectivity/Connection/front/src/webhook/components/TestUrlButton.tsx
In the Event Subscription page, there is `test` button.
Problem is, it's a `<button>` inside a `<form>`, in certains conditions, the button submit a form with `GET`, breaking the URI.
=> API-1483: Fix the test button of the Event Subscription

src/Akeneo/Connectivity/Connection/back/Application/Webhook/Command/SendBusinessEventToWebhooksHandler.php, src/Akeneo/Connectivity/Connection/back/Application/Webhook/Service/EventsApiDebugLogger.php, src/Akeneo/Connectivity/Connection/back/Domain/Webhook/Persistence/Repository/EventsApiDebugRepository.php, src/Akeneo/Connectivity/Connection/back/Infrastructure/EventSubscriber/EventsApiRequestsLimitEventSubscriber.php, src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/Elasticsearch/Repository/ElasticsearchEventsApiDebugRepository.php, src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/event_subscribers.yml, src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/handlers.yml, src/Akeneo/Connectivity/Connection/back/tests/Integration/Persistence/Elasticsearch/Repository/ElasticsearchEventsApiDebugRepositoryIntegration.php, src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Webhook/Command/SendBusinessEventToWebhooksHandlerSpec.php, src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Webhook/Service/EventsApiDebugLoggerSpec.php, src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/EventSubscriber/EventsApiRequestsLimitEventSubscriberSpec.php
We buffer the log to optimise the indexation in elasticsearch.
This PR aime to decouple the buffering from the logger and add it to the persistence layer.
=> API-1471 move log buffer to repository

src/Akeneo/Connectivity/Connection/back/Application/Webhook/Command/SendBusinessEventToWebhooksHandler.php, src/Akeneo/Connectivity/Connection/back/Application/Webhook/Service/EventSubscriptionSkippedOwnEventLogger.php, src/Akeneo/Connectivity/Connection/back/Application/Webhook/Service/EventsApiDebugLogger.php, src/Akeneo/Connectivity/Connection/back/Application/Webhook/Service/LimitOfEventsApiRequestsReachedLogger.php, src/Akeneo/Connectivity/Connection/back/Infrastructure/EventSubscriber/EventsApiRequestsLimitEventSubscriber.php, src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Webhook/Command/SendBusinessEventToWebhooksHandlerSpec.php, src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Webhook/Service/EventsApiDebugLoggerSpec.php, src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/EventSubscriber/EventsApiRequestsLimitEventSubscriberSpec.php
Add two interfaces to the Events API logger:
- limit of events api request reached
- event subscription skipped own event
=> API-1471 add interfaces to events api debug logger

CHANGELOG.md, src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/grouped-variant-filter.js
On the product-grid, the "click" to switch the view between "group" and "ungrouped" variants was only on the word, and not the full line.
=> PLG-63: Fix product-grid grouped variant filter dropdown

.circleci/config.yml, .circleci/run_behat.sh
We are experiencing CI issues from unstable Behat Selenium tests.
While studying other test solution (fixing our Behats, stop using Selenium, etc) we can reactivate the retry feature to facilitate PR validation.
=> BH-420: reactivate Behat retry

CHANGELOG.md, src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Standard/Product/ProductValueNormalizer.php, tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/Standard/Product/ProductValueNormalizerSpec.php
When an attribute number allows the decimal values, the number of values saved on the product is limited to 5 digits if the number finished by one or several zeros. IE the PIM removes all zeros after 5 digits. 
Here is an example 
If I input 1234500 > 12345 is saved
If I input 123000 > 12300 is saved 
If I input 1234567 > 1234567 is saved  …
=> PIM-9718: Decimals attribute values with no separators are well formatted

src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/form_extensions.yml, src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/requirejs.yml, src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/routing.yml, src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/public/js/menu/connection-params-provider.ts, src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/public/js/menu/highlight-menu.ts, src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml, src/Akeneo/Connectivity/Connection/front/jest.config.js, src/Akeneo/Connectivity/Connection/front/src/audit/pages/AuditErrorBoundary.tsx, src/Akeneo/Connectivity/Connection/front/src/audit/pages/Dashboard.tsx, src/Akeneo/Connectivity/Connection/front/src/error-management/pages/ConnectionMonitoring.tsx, src/Akeneo/Connectivity/Connection/front/src/settings/pages/EditConnection.tsx, src/Akeneo/Connectivity/Connection/front/src/settings/pages/ListConnections.tsx, src/Akeneo/Connectivity/Connection/front/src/settings/pages/SettingsErrorBoundary.tsx, src/Akeneo/Connectivity/Connection/front/src/shared/user/UserButtons.tsx, src/Akeneo/Connectivity/Connection/front/src/shared/user/index.ts, src/Akeneo/Connectivity/Connection/front/src/webhook/components/EventLogList.tsx, src/Akeneo/Connectivity/Connection/front/src/webhook/components/EventSubscriptionDisabled.tsx, src/Akeneo/Connectivity/Connection/front/src/webhook/components/NoEventLogs.tsx, src/Akeneo/Connectivity/Connection/front/src/webhook/hooks/api/use-fetch-connection.ts, src/Akeneo/Connectivity/Connection/front/src/webhook/hooks/api/use-fetch-event-subscription.ts, src/Akeneo/Connectivity/Connection/front/src/webhook/pages/EditConnectionWebhook.tsx, src/Akeneo/Connectivity/Connection/front/src/webhook/pages/EventLogs.tsx, src/Akeneo/Connectivity/Connection/front/src/webhook/pages/Index.tsx, src/Akeneo/Connectivity/Connection/front/tests/src/webhook/pages/EventLogs.test.tsx
Add initial page and menu entry for displaying the logs of the Events API.
Also,
- display a message if the event subscription is disabled
- display a message if there is not logs
=> API-1490 add event logs page

CHANGELOG-4.0.md, src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Field/IdentifierFilter.php, src/Akeneo/Pim/Enrichment/Component/Product/Query/Filter/FieldFilterHelper.php, src/Akeneo/Tool/Component/StorageUtils/Exception/InvalidPropertyTypeException.php, tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Filter/Field/IdentifierFilterSpec.php
Filtering on invalid product identifiers during an API call triggers a 500 error with the right operators (IN and NOT IN). It's because the API query is not properly validated. We do validate that the identifiers are an array but not that it's an array of strings. The query is considered as valid and is transformed to an Elasticsearch query, and this is where the 500 error is triggered when we filter for example with a `null` value (because null is not a valid value for ES)
Example of query that triggered the problem : `/api/rest/v1/products?search={"identifier":[{"operator":"IN","value":["15554974",null]}]}`
With this fix, the API now returns a proper 422 error, like other malformed queries. …
=> PIM-9717: Fix 500 error when filtering with invalid product identifiers value during an API call

CHANGELOG.md, src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/ProductController.php, tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/SuccessListProductEndToEnd.php
=> PIM-9727 add missing query params to hatoas links

src/Akeneo/Pim/Enrichment/Bundle/Resources/config/console.yml
In the https://github.com/akeneo/pim-enterprise-dev/pull/10504 we launch asset re-indexation in a migration. To do that we have to make the service public
=> PIM-9721: make command launcher service public

CHANGELOG-4.0.md, tests/back/Acceptance/Attribute/InMemoryGetExistingReferenceDataCodes.php, tests/back/Acceptance/Resources/config/pim/queries.yml, tests/back/Acceptance/spec/Attribute/InMemoryGetExistingReferenceDataCodesSpec.php
We would like to add an acceptance test for an Onboarder use case but an in memory query is missing. The SQL implem is called instead and prevent us from testing as we'd like to. In this PR, we are adding this in memory query. …
=> AOB-1340: Add InMemory implem for GetExistingReferenceDataCodes query

CHANGELOG.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/categories.js
When switching out of and then back into the 'Categories' tab of the PEF, the category tree events were not listened to anymore, making it impossible to update the categories or even switch to a different category tree.
In this PR, the category trees are built and rendered only once (when the `render()` method is called for the first time), and the events are delegated ate each call of this method
| Review and …
=> PIM-9730: Fix PEF category tree initialization when switching tabs

CHANGELOG.md, src/Akeneo/Pim/Enrichment/Component/Product/Factory/CleanLineBreaksInTextAttributes.php, src/Akeneo/Pim/Enrichment/Component/Product/Factory/ReadValueCollectionFactory.php, tests/back/Pim/Enrichment/Specification/Component/Product/Factory/CleanLineBreaksInTextAttributesSpec.php
**PART 1** done by @nmarniesse => https://github.com/akeneo/pim-community-dev/pull/14001
**PART 2**
For existing line breaks, I added a function that replaces them with spaces when it comes to text attributes, at the product saving. …
=> PIM-9679: Clean existing text attribute values removing linebreaks.

src/Akeneo/Pim/Enrichment/Bundle/Resources/config/processors.yml, src/Akeneo/Pim/Enrichment/Component/Product/Connector/Processor/CleanLineBreaksInTextAttributes.php, src/Akeneo/Pim/Enrichment/Component/Product/Connector/Processor/Denormalizer/ProductModelProcessor.php, src/Akeneo/Pim/Enrichment/Component/Product/Connector/Processor/Denormalizer/ProductProcessor.php, src/Akeneo/Tool/Component/Batch/Item/NonBlockingWarningAggregatorInterface.php, src/Akeneo/Tool/Component/Batch/Step/ItemStep.php, tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Processor/CleanLineBreaksInTextAttributesSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Processor/Denormalizer/ProductModelProcessorSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Processor/Denormalizer/ProductProcessorSpec.php
https://akeneo.atlassian.net/browse/PIM-9679
During import we display a warning message when a value is fixed
Part1:
Part2: Done in another PR
=> PIM-9679: Clean line breaks in product and product model imports

src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/Elasticsearch/Repository/ElasticsearchEventsApiDebugRepository.php, src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/elasticsearch/events_api_debug_mapping.yml, src/Akeneo/Connectivity/Connection/back/tests/Integration/Persistence/Elasticsearch/Repository/ElasticsearchEventsApiDebugRepositoryIntegration.php
We need to flatten the context when storing it in ES.
2 different fields: the full context as `object`, a `text` with only the recursive values.
=> API-1512: Refactor storage of Events API logs

src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/components/DashboardIndex.tsx, src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/components/Widgets/LastOperationsWidget.tsx, src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/domain/index.ts, src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/domain/operation.ts, src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/hooks/index.ts, src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/hooks/useDashboardLastOperations.ts, tests/front/unit/jest/unit.jest.js, tests/legacy/features/Behat/Context/NavigationContext.php, tests/legacy/features/platform/dashboard/display_last_operations_widget.feature, tests/legacy/features/platform/security/login.feature
=> PLG-89: display the last operations widget on the dashboard

.circleci/config.yml
Following the merge of https://github.com/akeneo/pim-enterprise-dev/pull/10520 of env var is missing, needed by test-deploy step.
We need to have a green test_deploy using the Short image tag.
`OK`: …
=> BH-464: Add IMAGE_TAG_SHORTED var for the EE deployment test

CHANGELOG.md, src/Akeneo/Pim/Enrichment/Component/Product/Connector/Processor/CleanLineBreaksInTextAttributes.php, src/Akeneo/Pim/Enrichment/Component/Product/Factory/CleanLineBreaksInTextAttributes.php, tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Processor/CleanLineBreaksInTextAttributesSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Factory/CleanLineBreaksInTextAttributesSpec.php
Small mistake, big impact in PIM-9658.
I fix it in this PR without using a regex.
=> PIM-9758: Fix bad replacement for line breaks introduced in PIM-9658

CHANGELOG.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/creation/field.js
When creating a new product, after filling in the SKU/code by making a right-click / paste, then after selecting the family, the code disappeared.
A PR was done for fixing a bug with the boolean field => https://github.com/akeneo/pim-community-dev/pull/11906
It updated the model only on "keyup input" this is why the model wasn't updated anymore when pasting with the mouse.
So, I added the "change input" event on the field.js file to fix the issue. …
=> PIM-9743: Add the "change input" event so that the SKU/code doesn't disappear when doing copy/paste

src/Akeneo/Connectivity/Connection/front/src/shared/router/use-router.ts, src/Akeneo/Connectivity/Connection/front/src/webhook/components/DownloadLogsButton.tsx, src/Akeneo/Connectivity/Connection/front/src/webhook/components/EventLogList.tsx, src/Akeneo/Connectivity/Connection/front/src/webhook/hooks/api/use-fetch-event-subscription.ts, src/Akeneo/Connectivity/Connection/front/src/webhook/pages/EditConnectionWebhook.tsx, src/Akeneo/Connectivity/Connection/front/src/webhook/pages/EventLogs.tsx
The download logs button was on the event subscription configuration page.
This PR move it to the dedicated new screen for the logs.
=> API-1520: Move download logs button

CHANGELOG.md, package.json, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/init-layout.js, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/router.js, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/bootstrap/js/bootstrap.js, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/jstree/jquery.jstree.js, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/slimbox2/slimbox2.js, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/export/common/edit/upload.html, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/form/common/fields/media.html, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/grid/mass-actions.html, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/mass-edit/form.html, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/product/field/media.html, src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/text-filter.js, src/Oro/Bundle/PimDataGridBundle/Resources/public/lib/multiselect/jquery.multiselect.js, yarn.lock
This PR upgrades jQuery version following a XSS vulnerability that was fixed in version 3.5.0.
As this version introduces a breaking change on a specific method (see https://jquery.com/upgrade-guide/3.5/), this PR also updates all self-closing tags in HTML templates and in JS files using jQuery.
=> PIM-9748: Upgrade JQuery for security reasons

CHANGELOG-3.2.md, src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
Fix missing translation on move to categories mass edit action
=> PIM-9709: Fix missing translation on move to categories mass edit action

src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/Elasticsearch/Query/PurgeEventsApiErrorLogsQuery.php, src/Akeneo/Connectivity/Connection/back/tests/Integration/Persistence/Elasticsearch/Query/PurgeEventsApiErrorLogsQueryIntegration.php
The query purged the logs the wrong way. It purged the logs that were sooner than the DateTime and not older than.
Moreover, the test is more robust testing the timestamps.
=> API-1523: Fix es purge query

src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/Elasticsearch/Query/GetAllEventSubscriptionDebugLogsQuery.php, src/Akeneo/Connectivity/Connection/back/tests/Integration/Persistence/Elasticsearch/Query/GetEventSubscriptionLogsQueryIntegration.php
In the download logs feature,the 100 oldest NOTICE & INFO logs are retrieved.
It should be the newest logs and there must be something wrong in the tests.
+ Add EventsApiDebugLogLevels constants
=> API-1521: Fix order of NOTICE & INFO logs

Makefile, std-build/Makefile, std-build/install-required-files.sh, std-build/migration/prepare_40_to_50.sh
Kernel was not updated during the standard edition update
- Fix Kernel update
- Add upgrade-front in the makefile according to the documentation
- Fix copy statement in the prepare script
`OK`: Done …
=> PIM-9772: Fix V5 standard build

CHANGELOG-4.0.md, src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filters-column.ts
Adding a safeguard on the grid filters that sometimes are returned as an object, this will ensure the filters are always in an array.
=> PIM-9770: Fix proposal filters not loading when no permissions on attribute groups

CHANGELOG.md, src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/UniqueVariantAxisValidator.php, tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/UniqueVariantAxisValidatorSpec.php
Fix unique variant axis validator considering 01 and 1 as equal because `in_array('01', ['code' => '1'])` returns `true` without the `strict` option.
=> PIM-9773: Fix unique variant axis validator considering 01 and 1 as equal

CHANGELOG.md, config/packages/test/security.yml, src/Akeneo/UserManagement/Bundle/Controller/Rest/UserController.php, src/Akeneo/UserManagement/Bundle/Form/Type/ResetType.php, src/Akeneo/UserManagement/Bundle/Resources/translations/messages.en_US.yml, tests/back/UserManagement/Integration/Bundle/ControllerIntegrationTestCase.php, tests/back/UserManagement/Integration/Bundle/UserPasswordIntegration.php, tests/legacy/features/user-management/user/create_and_delete_user.feature
Setting new validation constraints on user password length, minimum of 8 characters and maximum of 4096 as it's the Symfony's encoder limit https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Security/Core/Encoder/BasePasswordEncoder.php#L27.
| Tech Doc …
=> PIM-9767: Fix minimum & maximum user password validation

Dockerfile.base, Dockerfile.dev
Docker build failed for 4.0 PHP image
Need to update ca certificate as soon as possible.
=> Pim-9772: Docker php image build for 4.0 are broken

CHANGELOG-4.0.md, src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/number-filter.js
Adding frontend input validation on grid Number filters, this will allow only number-like inputs (5, -4, 3e5, 6.2, etc)
=> PIM-9766: Prevent letter usage in grid Number filters

CHANGELOG.md, src/Akeneo/Platform/Bundle/ImportExportBundle/Factory/NotificationFactory.php
Fix completed import/export job notification broken link, now leading to the new job tracker
=> PIM-9780: Fix completed import/export job notification broken link

src/Akeneo/UserManagement/Bundle/Controller/Rest/UserController.php, tests/back/UserManagement/Integration/Bundle/UserPasswordIntegration.php
Uses `mb_strlen` to handle special characters correctly in password length computation. However, we still need to use `strlen` on the max length check because Symfony's BasePasswordEncore will compare its strict length when trying to encode it with salt.
See: https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Security/Core/Encoder/BasePasswordEncoder.php#L100 …
=> PIM-9792: Use mb_strlen to handle special chars

CHANGELOG-4.0.md, src/Akeneo/Pim/Enrichment/Component/Product/Model/AbstractMetric.php, tests/back/Pim/Enrichment/Specification/Component/Product/Model/MetricSpec.php
The MetricValue data type is not enforced by any type hinting.
I could have fix by a cast here: https://github.com/akeneo/pim-community-dev/blob/4.0/src/Akeneo/Pim/Enrichment/Component/Product/Model/AbstractMetric.php#L38 but the impacts could be important, so I chose to only fix the comparison in 4.0
=> PIM-9774: Fix variant axis 'metric' validation on import

CHANGELOG.md, src/Akeneo/Pim/Enrichment/Bundle/Product/ComputeAndPersistProductCompletenesses.php
Fix https://akeneo.atlassian.net/browse/PIM-9783
The query to calculate completeness fails with 8.084 product identifiers. The batch was 10.000, it is now 1.000.  
Tested on https://cora-prod-clone-sds-17727.dev.cloud.akeneo.com
FYI it works with a batch of 5.000. But as the query depends on the catalog structure (number of product models + number of product values), a  margin of error is considered and the batch is set to 1.000.
=> PIM-9783: decrease batch when calculate completeness

CHANGELOG.md, phpunit.xml.dist, src/Oro/Bundle/SecurityBundle/Acl/Dbal/MutableAclProvider.php, src/Oro/Bundle/SecurityBundle/Tests/Unit/Acl/Dbal/MutableAclProviderTest.php
Fix https://akeneo.atlassian.net/browse/PIM-9779  
On a very specific environment, we cannot add a specific ACL for a specific role. This behaviour is very strange, but we are not the only one to observe the problem. It's in the `symfony/security-acl` bundle, it's exactly the same as:  
https://github.com/symfony/security-acl/issues/5 
https://github.com/symfony/security-acl/issues/23 
https://github.com/symfony/security-acl/issues/24 
https://github.com/symfony/security-acl/issues/28 
To fix it a PR was opened https://github.com/symfony/security-acl/pull/29, approved by one person, but never merged.  
We had 2 choices:
- fix the problem by code by applying the patch described by the PR (or equivalent)
- fix by SQL query
We think the fix by SQL query is too risky to be executed on all …
=> PIM-9779: fix ACE orders after finding ACLs

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/attribute/form/delete/DeleteModal.tsx, src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/shared/src/components/DeleteModal.tsx, src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/shared/src/components/index.ts, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/edit/Edit.tsx, src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/edit/unit-tab/UnitDetails.tsx
Unifying modal usage with a simple DeleteModal, currently used in Measurements and in RefEntities/Asset Manager here akeneo/pim-enterprise-dev#10622
=> RAC: Add DeleteModal in shared

CHANGELOG-4.0.md, src/Akeneo/Pim/Enrichment/Bundle/DependencyInjection/AkeneoPimEnrichmentExtension.php, src/Akeneo/Pim/Enrichment/Bundle/Doctrine/Common/Saver/CategorySaver.php, src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Query/EnsureLockTableExistsQuery.php, src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/Db/InitLockDbSchemaSubscriber.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/event_subscribers.yml, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/lock.yml, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/savers.yml, src/Akeneo/Pim/Enrichment/Component/Lock/Query/EnsureLockTableExistsInterface.php, tests/back/Pim/Enrichment/Integration/Doctrine/Common/Saver/CategorySaverIntegration.php, tests/back/Pim/Enrichment/Integration/Doctrine/ORM/EnsureLockTableExistsIntegration.php, tests/back/Pim/Enrichment/Specification/Bundle/Doctrine/Common/Saver/CategorySaverSpec.php
=> PIM-9726: mitigate deadlock on categories (backport PIM-9548)

src/Akeneo/Connectivity/Connection/front/src/common/components/ExpandableTableRow.tsx
There is no `max-width: 100%` on the `<pre>` element, the behavior with max-width in % does not work as expected.
Without a width, `overflow: scroll` does not work.
Without wrapping of the content, the `<pre>` will take the width on its content, overflowing the table.
Hence the following:
(you can see that the row is wider than the table header)
The only solution I found, which will work on all browsers and most screen is to set a width to it.
The width is not random, it's the exact same one as the initial design.
| Added …
=> API-1534: Fix log context width

CHANGELOG.md, src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Completeness/SqlGetCompletenessProductMasks.php
See https://akeneo.atlassian.net/browse/PIM-9783
With the old version, MySQL don't use index range scan if a lot of product identifiers are given (+6000 in our tests).  
Old version: 1min12 for the query with 8084 idnetifiers
New version: less than 2s
Thanks @ahocquard
=> PIM-9783: optimize query for completeness

upgrades/schema/Version_5_0_20201112083948_add_lock_table.php
This is an ugly fix, but we have a conflict between this migration and the [InitLockDbSchemaSubscriber](https://github.com/akeneo/pim-community-dev/blob/5.0/src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/Db/InitLockDbSchemaSubscriber.php) backported from master. This migration can have been played and we can't delete it. That's why I chose to modify it by adding the "IF NOT EXISTS" clause.
If it has been played, nothing will change. If it has not been played, it will not crash because of the InitLockDB subscriber.
Not the smarter fix ever, but with no side effects.
=> Fix Version_5_0_20201112083948_add_lock_table migration

config/packages/twig.yml
As described in:
- https://github.com/symfony/symfony/blob/4.4/UPGRADE-4.4.md#twigbundle
- https://github.com/FriendsOfSymfony/FOSRestBundle/blob/2.8.6/UPGRADING-2.8.md
This parameter is deprecated. This change disable Twig ErrorHandler to use the HTTP Kernel one.
This will help have a better control over logging.
| Migration …
=> BH-477 Remove deprecated parameter

CHANGELOG.md, src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/ProductController.php, src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/BusinessEvent/DispatchProductCreatedAndUpdatedEventSubscriber.php, src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/BusinessEvent/DispatchProductModelCreatedAndUpdatedEventSubscriber.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/webhook.yml, src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Connector/SqlGetConnectorProductModels.php, src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Connector/SqlGetConnectorProducts.php, src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Connector/SqlGetConnectorProductsWithOptions.php, src/Akeneo/Pim/Enrichment/Component/Product/ProductModel/Query/GetConnectorProductModels.php, src/Akeneo/Pim/Enrichment/Component/Product/Query/GetConnectorProducts.php, src/Akeneo/Pim/Enrichment/Component/Product/Webhook/ProductCreatedAndUpdatedEventDataBuilder.php, src/Akeneo/Pim/Enrichment/Component/Product/Webhook/ProductModelCreatedAndUpdatedEventDataBuilder.php, tests/back/Pim/Enrichment/EndToEnd/Product/Product/InternalApi/ProductCreationEndToEnd.php, tests/back/Pim/Enrichment/Integration/Storage/Sql/Connector/SqlGetConnectorProductModelsIntegration.php, tests/back/Pim/Enrichment/Integration/Storage/Sql/Connector/SqlGetConnectorProductsIntegration.php, tests/back/Pim/Enrichment/Integration/Storage/Sql/Connector/SqlGetConnectorProductsWithOptionsIntegration.php, tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/BusinessEvent/DispatchProductCreatedAndUpdatedEventSubscriberSpec.php, tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/BusinessEvent/DispatchProductModelCreatedAndUpdatedEventSubscriberSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Webhook/ProductCreatedAndUpdatedEventDataBuilderSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Webhook/ProductModelCreatedAndUpdatedEventDataBuilderSpec.php
The webhooks workflow searches for products and indexes product models after they are created. Depending on the [refresh time of the Elasticsearch index](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-refresh.html#refresh-api-desc), the resource might not be retrieved.
To solve this problem, we base the retrieval of products and product models only on SQL queries.
| Review …
=> PIM-9800: Event not sent when creating products or product models

src/Akeneo/Connectivity/Connection/front/src/webhook/components/EventLogList.tsx, src/Akeneo/Connectivity/Connection/front/src/webhook/hooks/api/use-infinite-event-subscription-logs.ts, src/Akeneo/Connectivity/Connection/front/src/webhook/scroll/hooks/useInfiniteScroll.ts
In the current version, there is no "initial" loading screen, it jump directly to the table of logs.
Then, when the fetch is done, and there is no logs, the page is replaced by `<NoEventLogs />`.
This create a "flash" of the page content.
By adding isInitialized, we display nothing until the first fetch is done. …
=> API-1545: Adds isInitialized to useInfiniteScroll

CHANGELOG.md, src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/select-filter.js
With Firefox and for some UI locale, filters in the product grid disappeared + the filter 'Product image' had a different behavior from the others. 
Video before fixing the bug => https://www.screencast.com/t/G05lxhii1
In the console, I got this message `jQuery.Deferred exception: a.__translation.localeCompare is not a function`
Addind the toString() function resolves the issue.
Here is a gif, after adding the fix: …
=> PIM-9809: Fix missing filters in the product grid for few UI locales with Firefox

src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/BusinessEvent/DispatchBufferedPimEventSubscriberInterface.php, src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/BusinessEvent/DispatchProductCreatedAndUpdatedEventSubscriber.php, src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/BusinessEvent/DispatchProductModelCreatedAndUpdatedEventSubscriber.php, src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/BusinessEvent/DispatchProductModelRemovedEventSubscriber.php, src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/BusinessEvent/DispatchProductRemovedEventSubscriber.php, tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/BusinessEvent/DispatchProductCreatedAndUpdatedEventSubscriberSpec.php, tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/BusinessEvent/DispatchProductModelCreatedAndUpdatedEventSubscriberSpec.php, tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/BusinessEvent/DispatchProductModelRemovedEventSubscriberSpec.php, tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/BusinessEvent/DispatchProductRemovedEventSubscriberSpec.php
Currently, published products produce PIM events (which are sent to webhooks) but they mustn't.
This PR aims to change this behavior by decorating the subscribers and stopping the propagation of events from a published product.
In the CE PR, I add an interface to the subscribers in order to create a contract and be able to mock those final classes in EE spec. …
=> PIM-9804: Add an interface to Pim events dispatchers

src/Akeneo/Connectivity/Connection/front/src/common/components/PageHeader.tsx
When loading the page, there was a css jump when the DOM appears.
With a simple min-height, we can anticipate this element expected height.
=> API-1552: Add a min-height to the breadcrumb to avoid jump of the DOM

src/Akeneo/Platform/Bundle/UIBundle/EventListener/ScriptNonceGenerator.php
When launching ./bin/console debug:event-dispatcher it fails because an event dependency in the constructor assumes there is a session. This makes an exception to be thrown.
=> test if session exists

src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Repository/ExternalApi/CategoryRepository.php, src/Akeneo/Pim/Structure/Bundle/Doctrine/ORM/Repository/ExternalApi/AttributeGroupRepository.php, src/Akeneo/Pim/Structure/Bundle/Doctrine/ORM/Repository/ExternalApi/AttributeRepository.php, src/Akeneo/Pim/Structure/Bundle/Doctrine/ORM/Repository/ExternalApi/FamilyRepository.php
API concatenates error messages together without leaving a space character in between
This pull request threats only errors done by search filters validation for the following endpoints:
- family (is already fixed on master)
- category
- attribute
- attributeGroup
~~Updated namespaces from DateTime to DateTimeInterface as the former was removed since PHP 7.2~~
| Micro …
=> Api 1341 - Updated API error output format

src/Akeneo/Connectivity/Connection/front/src/webhook/scroll/hooks/useInfiniteScroll.ts, src/Akeneo/Connectivity/Connection/front/tests/src/webhook/hooks/api/use-infinite-event-subscription-logs.test.ts, src/Akeneo/Connectivity/Connection/front/tests/src/webhook/scroll/hooks/useInfiniteScroll.test.ts
2 parts:
- new generic test on `use-infinite-event-subscription-logs.ts`
- new test about amount of re-renders of `useInfiniteScroll.ts`
=> API-1564: Add tests & reduce amount of re-render in useInfiniteScroll

src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/validation/WriteConnectionWebhook.yml, src/Akeneo/Connectivity/Connection/back/tests/Integration/Validation/WriteConnectionWebhookValidationIntegration.php
Since the validation configuration is not something that can be spec'ed, I've added an integration test for it.
=> API-1544: Validate url length in event subscription form

CHANGELOG-5.0.md, Dockerfile.base
PIM 5.0 deployments are failing with the following error `Memcached not found`. It has been fixed in master [here](https://github.com/akeneo/pim-community-dev/pull/13979/files) but not in 5.0 The Onboarder team is using these branch to build the docker image with the bundle for PIM 5.0 deployment.
In this PR, we are just backporting the fix made in the master branch.
| …
=> OB-752: Fix php-memcached version
