CHANGELOG-3.2.md
src/Akeneo/Tool/Bundle/MeasureBundle/Resources/config/measure.yml

PIM-9581: Merge 3.2 into 4.0

---

Dockerfile.base
Dockerfile.dev

BH-229: Fix blackfire installation

---

Dockerfile.dev

Backporting https://github.com/akeneo/pim-community-dev/pull/13392

Fix blackfire install

---

src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Application/component/ProductEditForm/TabContent/DataQualityInsights/Criterion.unit.tsx
src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/ProductEvaluationTab/ClickOnAnAttributeWithRecommandation.unit.tsx
src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/ProductEvaluationTab/DisplayAxisEvaluation.unit.tsx
src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/utils/render/index.ts
src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/utils/render/renderAttribute.tsx
src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/utils/render/renderAttributesList.tsx
src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/utils/render/renderAxisEvaluation.tsx
src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/utils/render/renderCriterion.tsx
src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/utils/render/renderRecommendationWithAttributesList.tsx
src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/utils/render/renderTooManyAttributesLink.tsx
src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/utils/render/renderWithProductEditFormContextHelper.tsx

DAPI-1438: fix unit tests with not applicable recommendation

---

src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/validators.en_US.yml
src/Akeneo/Pim/Structure/Bundle/Query/InternalApi/Attribute/IsAttributeCodeBlacklisted.php
src/Akeneo/Pim/Structure/Bundle/Resources/config/queries.yml
src/Akeneo/Pim/Structure/Bundle/Resources/config/validation/attribute.yml
src/Akeneo/Pim/Structure/Bundle/Resources/config/validators.yml
src/Akeneo/Pim/Structure/Component/Query/InternalApi/IsAttributeCodeBlacklistedInterface.php
src/Akeneo/Pim/Structure/Component/Validator/Constraints/AttributeTypeForOptionValidator.php
src/Akeneo/Pim/Structure/Component/Validator/Constraints/BlacklistedAttributeCode.php
src/Akeneo/Pim/Structure/Component/Validator/Constraints/BlacklistedAttributeCodeValidator.php
src/Akeneo/Tool/Bundle/MeasureBundle/PublicApi/SqlGetUnitTranslations.php
tests/back/Pim/Structure/Integration/Attribute/Query/IsAttributeCodeBlacklistedIntegration.php
tests/back/Pim/Structure/Integration/Attribute/Validation/BlacklistedAttributeCodeIntegration.php

RAC-391: add is blacklisted query

---

src/Oro/Bundle/PimDataGridBundle/tests/Integration/Query/Sql/ListProductGridAvailableColumnsIntegration.php

DAPI: fix integration tests on unique score feature

---

CHANGELOG-3.2.md
CHANGELOG-4.0.md
CHANGELOG.md
src/Akeneo/Pim/Enrichment/.php_cd.php
src/Akeneo/Pim/Enrichment/Bundle/Command/CleanRemovedAttributesFromProductAndProductModelCommand.php
src/Akeneo/Pim/Enrichment/Bundle/Doctrine/Common/Saver/GroupSaver.php
src/Akeneo/Pim/Enrichment/Bundle/Resources/config/command.yml
src/Akeneo/Pim/Enrichment/Component/Product/Updater/GroupUpdater.php
src/Akeneo/Pim/Structure/Bundle/Event/AttributeEvents.php
src/Akeneo/Pim/Structure/Bundle/EventListener/RemoveNonExistingProductValuesSubscriber.php
src/Akeneo/Pim/Structure/Bundle/Resources/config/services.yml
src/Akeneo/Tool/Bundle/BatchBundle/Persistence/Sql/SqlCreateJobInstance.php
src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/removers.yml
src/Akeneo/Tool/Component/Batch/Query/CreateJobInstanceInterface.php
src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/action/navigate-action.js
tests/back/Pim/Enrichment/Specification/Bundle/Doctrine/Common/Saver/GroupSaverSpec.php
tests/back/Pim/Enrichment/Specification/Component/Product/Updater/GroupUpdaterSpec.php
tests/back/Pim/Structure/Specification/Bundle/EventListener/RemoveNonExistingProductValuesSubscriberSpec.php

PIM-9582: Merge 4.0 into master

---

src/Akeneo/Connectivity/Connection/back/Application/Webhook/Command/SendBusinessEventToWebhooksHandler.php

Remove `dump` function usage :bug:

CXP remove debug code

---

src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/productgrid.yml

DAPI - fix enrichment filter and image filter behavior with projects

---

CHANGELOG-3.2.md

Pull up 3.2 to 4.0

---

src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/less/data-quality-insights-attributes.less
src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/less/dqi-dashboard.less
src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/QualityScoreEvolutionSection/QualityScoreEvolutionSection.tsx
src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/ScoreDistributionSection/Header.tsx
src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/TabContent/DataQualityInsights/Recommendation/EnrichmentImageMessage.tsx
src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/TabContent/DataQualityInsights/Recommendation/Recommendation.tsx

- remove sticky headers for Score evolution and distribution graphs
- update style for recommendations and external links in it

DAPI: fix unique score feedbacks

---

CHANGELOG-3.2.md
CHANGELOG-4.0.md
src/Akeneo/Pim/Enrichment/Component/Product/Factory/NonExistentValuesFilter/NonExistentFileValueFilter.php
src/Akeneo/Pim/Enrichment/Component/Product/Factory/NonExistentValuesFilter/NonExistentMultiSelectValuesFilter.php
src/Akeneo/Pim/Enrichment/Component/Product/Factory/NonExistentValuesFilter/NonExistentReferenceDataMultiSelectValuesFilter.php
src/Akeneo/Pim/Enrichment/Component/Product/Factory/NonExistentValuesFilter/NonExistentReferenceDataSimpleSelectValuesFilter.php
src/Akeneo/Pim/Enrichment/Component/Product/Factory/NonExistentValuesFilter/NonExistentSimpleSelectValuesFilter.php
src/Akeneo/Pim/Enrichment/Component/Product/Factory/ReadValueCollectionFactory.php
src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/BooleanValueFactory.php
src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/DateValueFactory.php
src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/FileValueFactory.php
src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/IdentifierValueFactory.php
src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/ImageValueFactory.php
src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/MetricValueFactory.php
src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/NumberValueFactory.php
src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/OptionValueFactory.php
src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/OptionsValueFactory.php
src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/PriceCollectionValueFactory.php
src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/ReferenceDataCollectionValueFactory.php
src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/ReferenceDataValueFactory.php
src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/TextAreaValueFactory.php
src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/TextValueFactory.php
tests/back/Pim/Enrichment/Specification/Component/Product/Factory/Value/FileValueFactorySpec.php
tests/back/Pim/Enrichment/Specification/Component/Product/Factory/Value/ImageValueFactorySpec.php

This is a pull up of:
3.2 https://github.com/akeneo/pim-community-dev/pull/13330
4.0 https://github.com/akeneo/pim-community-dev/pull/13403
I've kept 2 fixes on `FileValueFactory.php` and `MediaValueFactory.php` because those are real fixes inside the `createByCheckingData` method.
I've also kept the prefix `\` to the php functions since we benchmarked a performance increase with it.
I've discarded the try/catch + logger since we are currently working on a better solution on master. …

Pull up 4.0 to master

---

src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Product/QuantifiedAssociation/GetProductModelQuantifiedAssociationsByProductIdentifiers.php
src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Product/QuantifiedAssociation/GetProductQuantifiedAssociationsByProductIdentifiers.php
src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductModel/QuantifiedAssociation/GetProductModelQuantifiedAssociationsByProductModelCodes.php
src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductModel/QuantifiedAssociation/GetProductQuantifiedAssociationsByProductModelCodes.php

In those 4 queries:
```
GetProductQuantifiedAssociationsByProductIdentifiers
GetProductModelQuantifiedAssociationsByProductIdentifiers
GetProductQuantifiedAssociationsByProductModelCodes
GetProductModelQuantifiedAssociationsByProductModelCodes
```
there is a validation step on association type codes because the quantified associations are stored in JSON format in the database, without foreign keys.
For each QuantifiedAssociation hydrated, we need to check that the corresponding QuantifiedAssociationTypeCode still exists in the database.
A simple cache was added, to avoid to run the query `SELECT code FROM pim_catalog_association_type WHERE is_quantified = true` hundred of times when validating.
Instead of having a statefull cache in the …

CXP-596: Remove statefull cache from quantified associations queries

---

src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Webhook/ConsumeBusinessProductModelEventEndToEnd.php

Since https://github.com/akeneo/pim-enterprise-dev/pull/10041, `src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Webhook/ConsumeBusinessProductModelEventEndToEnd.php` should be updated.

CXP-564 Apply permissions on product model removed events

---

src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Model/Read/CriterionEvaluationResult.php
src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Model/Write/CriterionEvaluationResult.php
src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/ValueObject/FamilyId.php
src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetCriteriaEvaluationsByProductIdQuery.php
src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Repository/CriterionEvaluationRepository.php

See https://github.com/akeneo/pim-enterprise-dev/pull/10029

DAPI-1446: Adaptations for family evaluation

---

src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/DataQualityInsightsTestCase.php

I don't know why it didn't crash before...

DAPI-1454: Fix product model creation in integration tests

---

.circleci/run_behat.sh

Backport the master run script to fix some Circle CI errors

Fix legacy Behats run scripts on Circle CI

---

src/Akeneo/Channel/Bundle/Resources/translations/jsmessages.en_US.yml
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/LocalesIndex.tsx

DAPI-1304: Add helper which explain that locales are activated in channels screen

---

src/Akeneo/Pim/Enrichment/.php_cd.php
src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/GetProductsWithQualityScores.php
src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/GetProductsWithQualityScoresInterface.php
src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/ListProductsQueryHandler.php
src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/ExternalApi/ConnectorProductNormalizer.php
tests/back/Pim/Enrichment/Specification/Component/Product/Connector/UseCase/GetProductsWithQualityScoresSpec.php
tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/ExternalApi/ConnectorProductNormalizerSpec.php

See feedbacks of https://akeneo.atlassian.net/browse/DAPI-1392?focusedCommentId=179748

DAPI-1392: Change format and filter by channel/locales

---

CHANGELOG.md
src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
src/Oro/Bundle/PimDataGridBundle/Controller/ProductExportController.php
src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/actions-panel.js
src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/quickexport/component/QuickExportConfigurator.tsx
src/Oro/Bundle/PimDataGridBundle/tests/front/unit/QuickExportConfigurator.unit.tsx
tests/legacy/features/pim/enrichment/product/mass-action/quick-export/quick_export.feature
tests/legacy/features/pim/enrichment/product/mass-action/quick-export/quick_export_grid_context.feature
tests/legacy/features/pim/enrichment/product/mass-action/quick-export/quick_export_products_and_product_models.feature
tests/legacy/features/pim/enrichment/product/mass-action/quick-export/quick_export_with_media.feature

Add "without media" / "with media" option

CPM-47: add "with media" option in quick exports

---

tests/back/Acceptance/Product/InMemoryProductRepository.php
tests/back/Acceptance/spec/Product/InMemoryProductRepositorySpec.php

We need this method for the Onboarder bundle acceptance tests.

AOB-1234: Implement InMemoryProductRepository::findAll()

---

src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/hooks/useInitDashboardContextState.ts

DAPI: fix family filter "All" on dashboard

---

src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Model/Read/KeyIndicator.php
src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/KeyIndicator.tsx
src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/KeyIndicators.tsx
src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/user-actions/followKeyIndicatorResult.ts
src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/user-actions/index.ts
src/Akeneo/Pim/Automation/DataQualityInsights/front/src/domain/KeyIndicator.ts
src/Akeneo/Pim/Automation/DataQualityInsights/front/src/domain/index.ts

DAPI-1462: fix redirect on attribute grid when dashboard is filtered on category

---

src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/KeyIndicator.tsx

DAPI: Fix linter issue on KeyIndicator component

---

CHANGELOG.md
src/Akeneo/Pim/Enrichment/Bundle/Resources/config/product_value_factories.yml
src/Akeneo/Pim/Enrichment/Component/Product/Factory/NonExistentValuesFilter/ChainedNonExistentValuesFilter.php
src/Akeneo/Pim/Enrichment/Component/Product/Factory/NonExistentValuesFilter/NonExistentPriceCollectionValueFilter.php
src/Akeneo/Pim/Enrichment/Component/Product/Factory/NonExistentValuesFilter/NonExistentReferenceDataMultiSelectValuesFilter.php
src/Akeneo/Pim/Enrichment/Component/Product/Factory/ReadValueCollectionFactory.php
tests/back/Pim/Enrichment/Integration/Product/ReadValueCollectionFactoryIntegration.php
tests/back/Pim/Enrichment/Specification/Component/Product/Factory/ReadValueCollectionFactorySpec.php

RAC-435: Fix fatal error for user that migrate from 4.0 with product values format that doesn't correspond to expected format

---

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/index.tsx
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/menu/item.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/legacy-bridge/src/provider/DependenciesProvider.type.ts
src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/bridge/controller/settings.tsx
src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/index.tsx

RAC-university: add measurement as a real react page

---

Dockerfile.dev

Remove Dockerfile obsolete entrypoint

---

akeneo-design-system/src/components/Modal/Modal.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/attribute/form/delete/DeleteModal.tsx
src/Akeneo/Platform/Bundle/UIBundle/tests/front/unit/attribute/form/delete/DeleteAction.unit.tsx
src/Akeneo/Platform/Bundle/UIBundle/tests/front/unit/attribute/form/delete/DeleteModal.unit.tsx

RAC-396: Add impacted items in attribute delete modal

---

src/Akeneo/Tool/Component/Batch/Step/ItemStep.php

RAC-406: Cleanup stop itemsteps

---

src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/form_extensions.yml
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/public/js/menu/connection-params-provider.ts
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/public/js/menu/highlight-menu.ts
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
src/Akeneo/Connectivity/Connection/front/src/webhook/components/EditForm.tsx

- Add menu entry
- Also, fix a regression on the test url input that displayed a success as an error. The issue is that the DSM doesn't provide (yet) the "success" style so I replaced "error" by "info"

[DO NOT MERGE] CXP-419 add event subscriptions menu

---

akeneo-design-system/package.json
akeneo-design-system/src/components/Button/Button.unit.tsx
akeneo-design-system/src/components/Modal/Modal.tsx
akeneo-design-system/src/components/ProgressBar/ProgressBar.tsx
akeneo-design-system/yarn.lock

RAC-typescript: upgrade typescript and storybook version on DSM

---

src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/BusinessEvent/DispatchProductCreatedAndUpdatedEventSubscriber.php
src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/BusinessEvent/DispatchProductModelCreatedAndUpdatedEventSubscriber.php
src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/BusinessEvent/DispatchProductModelRemovedEventSubscriber.php
src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/BusinessEvent/DispatchProductRemovedEventSubscriber.php
tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/BusinessEvent/DispatchProductCreatedAndUpdatedEventSubscriberSpec.php
tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/BusinessEvent/DispatchProductModelCreatedAndUpdatedEventSubscriberSpec.php
tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/BusinessEvent/DispatchProductModelRemovedEventSubscriberSpec.php
tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/BusinessEvent/DispatchProductRemovedEventSubscriberSpec.php

Cleanup for 5.0, remove the "user undefined" error handling.
Onboarder test isn't up-to-date yet and the error break the CI.

CXP-443 remove dead code

---

src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Elasticsearch/Filter/QualityScoreFilter.php
src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Elasticsearch/Sorter/QualityScoreSorter.php

DAPI-1444: remove fallback on quality score sorter and filter

---

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/pages/Login.less
src/Akeneo/UserManagement/Bundle/Resources/views/layout.html.twig

DAPI: fix homepage logo not displayed in firefox

---

src/Akeneo/Tool/Component/Batch/Job/JobRegistry.php

RAC-447: Remove SC feature flag

---

akeneo-design-system/bin/dsm

RAC-DSM: fix DSM usage metrics

---

CHANGELOG.md
src/Akeneo/Platform/Bundle/ImportExportBundle/Controller/Ui/JobTrackerController.php
src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/controllers.yml
src/Akeneo/Tool/Bundle/BatchBundle/EventListener/LoggerSubscriber.php

RAC-444: Improve job logs

---

src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Webhook/ConsumeProductEventEndToEnd.php
src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Webhook/ConsumeProductModelEventEndToEnd.php

- Add connection user group to have the correct permissions
- Remove metadata since there are not present on CE

CXP-615: Fix e2e tests

---

CHANGELOG.md
docker-compose.yml

update ES to 7.10.1

---

upgrades/schema/Version_5_0_20200702232424_create_communication_channel_viewed_announcement_index.php

In some upgrade path to 4.0, some customers already have the Announcement board in the PIM, but a migration doesn't test that before apply it

BH-287: Check indices update index migration

---

src/Akeneo/Pim/Enrichment/Bundle/Command/CleanRemovedAttributesFromProductAndProductModelCommand.php
src/Akeneo/Pim/Enrichment/Bundle/Resources/config/jobs.yml
src/Akeneo/Pim/Structure/Bundle/EventSubscriber/AttributeRemovalSubscriber.php
src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/translations/jsmessages.en_US.yml
src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev/jobs.yml
src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/minimal/jobs.yml
src/Akeneo/Tool/Bundle/ConnectorBundle/Resources/translations/jsmessages.en_US.yml
src/Oro/Bundle/PimDataGridBundle/Resources/translations/messages.en_US.yml
tests/back/Integration/catalog/technical/jobs.yml
tests/legacy/features/Context/catalog/apparel/jobs.yml
tests/legacy/features/Context/catalog/catalog_modeling/jobs.yml
tests/legacy/features/Context/catalog/default/jobs.yml
tests/legacy/features/Context/catalog/footwear/jobs.yml

After PO review, some changes in the labels have been made.

RAC-451: Fix labels for cleaning attribute values job

---

upgrades/schema/Version_5_0_20201127102539_fix_pressure_operations.php

check if there are pressure units to be updated

---

src/Akeneo/Pim/Enrichment/Bundle/Resources/config/normalizers.yml
src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/AxisValueLabelsNormalizer/MetricNormalizer.php

PIM-9608: Fetch unit translation

---

src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/src/components/panel/announcement/Tag.tsx

Same as https://github.com/akeneo/pim-community-dev/pull/13622
https://github.com/akeneo/actionable-product-data/issues/271

Fix color of the tags for announcements in communication panel

---

CHANGELOG-3.2.md
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/pim-app.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/Overlay.less
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/index.less

PIM-9616: Pullup 3.2 -> 4.0

---

CHANGELOG-3.2.md
CHANGELOG-4.0.md
src/Akeneo/Pim/Enrichment/Bundle/Product/ComputeAndPersistProductCompletenesses.php
src/Akeneo/Pim/Enrichment/Bundle/Resources/config/normalizers.yml
src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.it_IT.yml
src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.ja_JP.yml
src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.nl_NL.yml
src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.ru_RU.yml
src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/messages.ru_RU.yml
src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Completeness/SqlGetCompletenessProductMasks.php
src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/ApplyProductSearchQueryParametersToPQB.php
src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/AxisValueLabelsNormalizer/MetricNormalizer.php
src/Akeneo/Pim/Structure/Bundle/Doctrine/ORM/Repository/FamilyRepository.php
src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.it_IT.yml
src/Akeneo/Platform/Bundle/ImportExportBundle/Purge/PurgeJobExecution.php
src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/services.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.it_IT.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.ja_JP.yml
src/Akeneo/Tool/Bundle/BatchBundle/Persistence/Sql/GetJobExecutionIds.php
src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/removers.yml
src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/services.yml
src/Akeneo/Tool/Bundle/BatchBundle/Storage/DeleteJobExecutionLogs.php
src/Akeneo/Tool/Bundle/MeasureBundle/Resources/translations/jsmessages.nl_NL.yml
src/Akeneo/Tool/Bundle/MeasureBundle/Resources/translations/messages.nl_NL.yml
src/Akeneo/UserManagement/Bundle/Resources/translations/messages.nl_NL.yml
tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/InternalApi/AxisValueLabelsNormalizer/MetricNormalizerSpec.php
tests/back/Pim/Structure/Integration/Doctrine/ORM/Repository/FamilyRepositoryIntegration.php
tests/back/Tool/Integration/Batch/Persistence/Sql/GetJobExecutionIdsIntegration.php

PIM-9608: Merge 4.0 into master

---

src/Akeneo/Connectivity/Connection/back/Application/Webhook/Log/EventSubscriptionSendApiEventRequestLog.php
src/Akeneo/Connectivity/Connection/back/Domain/Webhook/Client/WebhookRequest.php
src/Akeneo/Connectivity/Connection/back/Domain/Webhook/Model/WebhookEvent.php
src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Webhook/ConsumeProductEventEndToEnd.php
src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Webhook/ConsumeProductModelEventEndToEnd.php
src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Webhook/Command/SendBusinessEventToWebhooksHandlerSpec.php
src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Domain/Webhook/Client/WebhookRequestSpec.php
src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Domain/Webhook/Model/WebhookEventSpec.php
src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Webhook/Client/GuzzleWebhookClientSpec.php

Rename event_date to event_datetime

API-1393: Rename event_date by event_datetime

---

std-build/Makefile

BH-294 - add missing target

---

src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/messages.en_US.yml
src/Akeneo/UserManagement/Bundle/Resources/views/layout.html.twig

Do not translate Akeneo baseline

---

.circleci/config.yml
CHANGELOG-5.0.md
src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/KeyIndicator/ComputeProductsEnrichmentStatusQuery.php
src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/queries.yml

Backport in 5.0 of the PR https://github.com/akeneo/pim-community-dev/pull/13667

PIM-9662: [Backport] Fix query that can generate a MySQL memory allocation error

---

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/execution/ExecutionDetail.tsx
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/execution/summary/SummaryTable.tsx
src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/edit/Edit.tsx
src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/list/List.tsx
src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/shared/components/PageContent.tsx
tests/legacy/features/Behat/Context/Domain/SecondaryActionsContext.php
tests/legacy/features/Behat/Decorator/Common/DropdownMenuDecorator.php
tests/legacy/features/Context/Page/Base/Base.php
tests/legacy/features/platform/export/export.feature
tests/legacy/features/platform/import/import.feature

RAC-463: Fixing behats

---

.circleci/config.yml
.circleci/detect_structure_changes.sh

BH-328: remove onboarder for the 5.0 LTS

---

.circleci/config.yml
make-file/test.mk

the integration test make target was wrong

---

src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/shared/src/hooks/useDebounce.ts

DAPI: fix useDebounceCallback typehinting to allow callbacks with several parameters

---

src/Akeneo/Pim/Enrichment/.php_cd.php
src/Akeneo/Pim/Enrichment/Bundle/Command/CleanRemovedAttributesFromProductAndProductModelCommand.php
src/Akeneo/Pim/Enrichment/Bundle/Resources/config/command.yml
src/Akeneo/Pim/Structure/Bundle/Query/InternalApi/Attribute/GetAllBlacklistedAttributeCodes.php
src/Akeneo/Pim/Structure/Bundle/Resources/config/queries.yml
src/Akeneo/Pim/Structure/Component/Query/InternalApi/GetAllBlacklistedAttributeCodesInterface.php
tests/back/Pim/Structure/Integration/Attribute/Query/GetAllBlacklistedAttributeCodesIntegration.php

RAC-461: add cleanup by blacklisted attribute codes

---

akeneo-design-system/.github/workflows/cleanup-staging.js
akeneo-design-system/.github/workflows/cleanup-staging.yml

RAC-222: cleanup staging envs of the DSM

---

src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/pim-app.ts
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/pim-onboarding.ts
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/router.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/views/index.html.twig
src/Akeneo/UserManagement/Bundle/Resources/views/layout.html.twig

PLG: improve tracking

---

CHANGELOG-5.0.md
src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/DataQualityInsightsTestCase.php
src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Persistence/Query/Completeness/CompletenessTestCase.php

This error often occurs during the CI integration tests:
```
PIM_CONTEXT=data-quality-insights make data-quality-insights-integration-back
├ SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'Akeneo\Channel\Component\Model\Locale' for key 'akeneo_structure_version_last_update.PRIMARY' …
```

DAPI-1477: Fix unstable DQI integration tests

---

src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml

API-1401: Beta is still displayed on some screens

---

CHANGELOG-5.0.md
src/Akeneo/Connectivity/Connection/back/Application/Webhook/Command/CheckWebhookReachabilityCommand.php
src/Akeneo/Connectivity/Connection/back/Application/Webhook/Command/CheckWebhookReachabilityHandler.php
src/Akeneo/Connectivity/Connection/back/Application/Webhook/Service/UrlReachabilityCheckerInterface.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/InternalApi/Controller/WebhookController.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_AU.yml
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_GB.yml
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/Client/GuzzleWebhookClient.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/Client/Signature.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/RequestHeaders.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/Service/WebhookReachabilityChecker.php
src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Webhook/Command/CheckWebhookReachabilityCommandSpec.php
src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Webhook/Command/CheckWebhookReachabilityHandlerSpec.php
src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Webhook/Client/GuzzleWebhookClientSpec.php
src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Webhook/Client/SignatureSpec.php
src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Webhook/Service/WebhookReachabilityCheckerSpec.php
src/Akeneo/Connectivity/Connection/front/src/webhook/components/EditForm.tsx
src/Akeneo/Connectivity/Connection/front/src/webhook/hooks/api/use-webhook-check-reachability.ts
src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/DataQualityInsightsTestCase.php
src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Persistence/Query/Completeness/CompletenessTestCase.php
src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.fr_FR.yml
src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/messages.fr_FR.yml
src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/translations/jsmessages.fr_FR.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/messages.fr_FR.yml

Pullup 5.0 master 20120119

---

akeneo-design-system/src/icons/DeleteIcon.tsx
akeneo-design-system/src/icons/DownloadIcon.tsx
akeneo-design-system/src/illustrations/ImportIllustration.tsx

[DO NOT MERGE] RAC-465: add possibility to export Animations on icons

---

akeneo-design-system/src/components/Badge/Badge.tsx
akeneo-design-system/src/components/Card/Card.stories.mdx
akeneo-design-system/src/components/Card/Card.tsx
akeneo-design-system/src/components/Card/Card.unit.tsx
src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/legacy-bridge/src/provider/DependenciesProvider.type.ts
src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/shared/src/hooks/index.ts
src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/shared/src/hooks/useSelection.ts
src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/shared/tests/front/unit/hooks/useSelection.unit.ts

RAC-467 Add possibility to have onCLick and on select on Card component

---

config/packages/security.yml

Require authentication for the `/media` endpoints

PIM-9656: Fix unauthenticated endpoint

---

std-build/Makefile

BH-357: set PUPPETEER_SKIP_CHROMIUM_DOWNLOAD for dsm

---

std-build/Makefile

BH-367: set PUPPETEER_SKIP_CHROMIUM_DOWNLOAD for dsm

---

composer.json
composer.lock

Backport of https://github.com/akeneo/pim-community-dev/pull/13856

Fix aws/aws-sdk-php issue

---

.circleci/config.yml

This PR allows to build the CE on demand.

BH-363 On demand build for CE

---

tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/PartialUpdateProductEndToEnd.php
tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/ExternalApi/PartialUpdateProductToVariantEndToEnd.php
tests/back/Pim/Structure/EndToEnd/Family/ExternalApi/PartialUpdateFamilyEndToEnd.php

It completes tests on product actions from API to be able to assert that all events are sent or not.

API-1432: Test that event are well handled during product API actions

---

CHANGELOG-4.0.md
composer.json
composer.lock
src/Akeneo/Pim/Enrichment/Bundle/PdfGeneration/Renderer/ProductPdfRenderer.php

Backport of https://github.com/akeneo/pim-community-dev/pull/13791

PIM-9663: Fix PDF product renderer disregarding permissions on attribute groups (backport of PIM-9649)

---

CHANGELOG.md
src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/GroupController.php
src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/ProductController.php
src/Akeneo/Pim/Structure/Bundle/Controller/InternalApi/AssociationTypeController.php
src/Akeneo/Pim/Structure/Bundle/Controller/InternalApi/FamilyController.php
src/Akeneo/Pim/Structure/Bundle/Controller/InternalApi/GroupTypeController.php
src/Akeneo/Platform/Bundle/ImportExportBundle/Controller/InternalApi/JobInstanceController.php
src/Akeneo/UserManagement/Bundle/Controller/Rest/UserController.php

Some backend permission checks were missing

PIM-9658: Add missing backend permission checks

---

CHANGELOG-4.0.md
src/Akeneo/Tool/Component/Localization/Factory/DateFactory.php
src/Akeneo/Tool/Component/Localization/spec/Factory/DateFactorySpec.php

Backport of https://github.com/akeneo/pim-community-dev/pull/13605

PIM-9669: [Backport] PIM-9610: Force displaying years with 4 digits in dates for every locale

---

src/Akeneo/Tool/Bundle/MessengerBundle/README.md

- Add Akeneo Messenger Bundle documentation

CXP-619 add messenger bundle documentation

---

src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/BusinessEvent/DispatchProductCreatedAndUpdatedEventSubscriber.php
src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/BusinessEvent/DispatchProductModelCreatedAndUpdatedEventSubscriber.php
tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/BusinessEvent/DispatchProductCreatedAndUpdatedEventSubscriberSpec.php
tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/BusinessEvent/DispatchProductModelCreatedAndUpdatedEventSubscriberSpec.php
tests/legacy/features/pim/enrichment/product-model/edit_product_model.feature
tests/legacy/features/pim/structure/family/remove_attribute_from_a_family.feature

API-1448: Add behat tests

---

tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/PartialUpdateProductModelEndToEnd.php

This PR adds missing end to end tests. We need those scenarios to check that the PIM event is well dispatched.

API-1448: Add missing end to end tests

---

tests/legacy/features/channel/locale/browse_locales.feature

DAPI-1260: update legacy behat regarding locales

---

CHANGELOG-5.0.md
src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/ProductGridRouter.ts
src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/infrastructure/ProductGridRouter.unit.ts

DAPI-1490: fix redirect to product grid from DQI dashboard when a default view is activated on the user profile

---

CHANGELOG.md
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/main-image.js
src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/cell/image-cell.js

PIM-9664: Add fallback URL for product images

---

src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/TabContent/DataQualityInsights/Criterion/Criterion.tsx
src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/user-actions/followCriterionRecommendation.ts
src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Application/component/ProductEditForm/TabContent/DataQualityInsights/Criterion.unit.tsx

DAPI-1491: pass locale to followCriterionRecommendation callback

---

src/Akeneo/UserManagement/Bundle/Controller/Rest/UserController.php
src/Akeneo/UserManagement/Bundle/Resources/config/routing/user_rest.yml
src/Akeneo/UserManagement/Component/Model/User.php
src/Akeneo/UserManagement/Component/Model/UserInterface.php
tests/back/UserManagement/Integration/Bundle/ControllerIntegrationTestCase.php
tests/back/UserManagement/Integration/Bundle/DuplicateUserIntegration.php
tests/back/UserManagement/Specification/Component/Model/UserSpec.php

CPM-137: duplicate a user (back)

---

CHANGELOG.md
src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/none-filter.js
src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/select2-choice-filter.js
src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/select2-rest-choice-filter.js
src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/text-filter.js

Rollback previous changes on the `outsideClickListener`

PIM-9681 fix criteria selector closing behavior

---

akeneo-design-system/src/components/Dropdown/Dropdown.stories.mdx
akeneo-design-system/src/components/Dropdown/Item/Item.tsx
akeneo-design-system/src/shared/array.ts
akeneo-design-system/src/shared/array.unit.ts

RAC-489: allow override of the Dropdown.Item colors

---

CHANGELOG-5.0.md
src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/ComputeCompletenessOfFamilyProductsTasklet.php
tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Job/ComputeCompletenessOfFamilyProductsTaskletSpec.php

Backport of https://github.com/akeneo/pim-community-dev/pull/13937

PIM-9686 fix memory issue of compute completeness task

---

src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev/jobs.yml
src/Akeneo/Tool/Bundle/ConnectorBundle/Resources/translations/jsmessages.en_US.yml
src/Akeneo/UserManagement/Bundle/DependencyInjection/PimUserExtension.php
src/Akeneo/UserManagement/Bundle/Resources/config/form_types.yml
src/Akeneo/UserManagement/Bundle/Resources/config/jobs.yml
src/Akeneo/UserManagement/Bundle/Resources/config/normalizers.yml
src/Akeneo/UserManagement/Bundle/Resources/config/processors.yml
src/Akeneo/UserManagement/Bundle/Resources/config/readers.yml
src/Akeneo/UserManagement/Bundle/Resources/config/steps.yml
src/Akeneo/UserManagement/Bundle/Resources/config/writers.yml
src/Akeneo/UserManagement/Component/Connector/ArrayConverter/StandardToFlat/User.php
src/Akeneo/UserManagement/Component/Normalizer/Standard/UserNormalizer.php
src/Akeneo/UserManagement/Component/Normalizer/UserNormalizer.php
tests/back/UserManagement/Integration/Bundle/Export/ExportUserIntegration.php
tests/back/UserManagement/Integration/Bundle/Export/ExportUserRoleIntegration.php
tests/back/UserManagement/Specification/Component/Connector/ArrayConverter/StandardToFlat/UserSpec.php
tests/back/UserManagement/Specification/Component/Normalizer/Standard/UserNormalizerSpec.php

User export. The avatar image is not exported yet, done in #13926 

CPM-132: User export via flat files

---

config/packages/dev/monolog.yml
config/packages/monolog.yml
config/packages/test/monolog.yml
src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/BusinessEvent/DispatchProductCreatedAndUpdatedEventSubscriber.php
src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/BusinessEvent/DispatchProductModelCreatedAndUpdatedEventSubscriber.php
src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/BusinessEvent/DispatchProductModelRemovedEventSubscriber.php
src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/BusinessEvent/DispatchProductRemovedEventSubscriber.php
src/Akeneo/Pim/Enrichment/Bundle/Resources/config/event_subscribers.yml
src/Akeneo/Platform/Component/EventQueue/Event.php
tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/BusinessEvent/DispatchProductCreatedAndUpdatedEventSubscriberSpec.php
tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/BusinessEvent/DispatchProductModelCreatedAndUpdatedEventSubscriberSpec.php
tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/BusinessEvent/DispatchProductModelRemovedEventSubscriberSpec.php
tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/BusinessEvent/DispatchProductRemovedEventSubscriberSpec.php

Log event for products just after they are sent in the queue

API-1446 log events for products

---

src/Akeneo/Platform/Bundle/InstallerBundle/Resources/config/services.yml
src/Akeneo/Platform/Bundle/InstallerBundle/Resources/config/steps.yml
src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev/jobs.yml
src/Akeneo/Tool/Bundle/ConnectorBundle/Resources/config/processors.yml
src/Akeneo/Tool/Bundle/ConnectorBundle/Resources/config/readers.yml
src/Akeneo/Tool/Bundle/ConnectorBundle/Resources/translations/jsmessages.en_US.yml
src/Akeneo/UserManagement/.php_cd.php
src/Akeneo/UserManagement/Bundle/Resources/config/form_types.yml
src/Akeneo/UserManagement/Bundle/Resources/config/jobs.yml
src/Akeneo/UserManagement/Bundle/Resources/config/processors.yml
src/Akeneo/UserManagement/Bundle/Resources/config/readers.yml
src/Akeneo/UserManagement/Bundle/Resources/config/steps.yml
src/Akeneo/UserManagement/Bundle/Resources/config/validation.yml
src/Akeneo/UserManagement/Bundle/Resources/config/validators.yml
src/Akeneo/UserManagement/Bundle/Validator/Constraints/UserOwnsDefaultGridViews.php
src/Akeneo/UserManagement/Bundle/Validator/Constraints/UserOwnsDefaultGridViewsValidator.php
src/Akeneo/UserManagement/Component/Connector/ArrayConverter/FlatToStandard/User.php
src/Akeneo/UserManagement/Component/Connector/Processor/Denormalization/UserProcessor.php
src/Akeneo/UserManagement/Component/Connector/Reader/File/CsvUserReader.php
src/Akeneo/UserManagement/Component/Connector/Reader/File/XlsxUserReader.php
src/Oro/Bundle/PimDataGridBundle/Repository/DatagridViewRepository.php
src/Oro/Bundle/PimDataGridBundle/Repository/DatagridViewRepositoryInterface.php
src/Oro/Bundle/PimDataGridBundle/tests/Integration/Repository/DatagridViewRepositoryIntegration.php
tests/back/UserManagement/Integration/Bundle/Import/ImportUserIntegration.php
tests/back/UserManagement/Specification/Bundle/Validator/Constraints/UserOwnsDefaultGridViewsValidatorSpec.php
tests/back/UserManagement/Specification/Component/Connector/ArrayConverter/FlatToStandard/UserSpec.php
tests/back/UserManagement/Specification/Component/Connector/Processor/Denormalization/UserProcessorSpec.php
tests/back/UserManagement/Specification/Component/Connector/Reader/File/CsvUserReaderSpec.php
tests/back/UserManagement/Specification/Component/Connector/Reader/File/XlsxUserReaderSpec.php

CPM-131: As Peter, I'd like to import users via flat files

---

tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/BusinessEvent/DispatchProductCreatedAndUpdatedEventSubscriberSpec.php
tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/BusinessEvent/DispatchProductModelCreatedAndUpdatedEventSubscriberSpec.php

This one should fix the 2 tests missed by the preceding merge.

API-1446 follow-up: fixing tests

---

src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev/jobs.yml
src/Akeneo/Tool/Bundle/ConnectorBundle/Resources/translations/jsmessages.en_US.yml
src/Akeneo/UserManagement/Bundle/Resources/config/array_converters.yml
src/Akeneo/UserManagement/Bundle/Resources/config/form_types.yml
src/Akeneo/UserManagement/Bundle/Resources/config/jobs.yml
src/Akeneo/UserManagement/Bundle/Resources/config/processors.yml
src/Akeneo/UserManagement/Bundle/Resources/config/readers.yml
src/Akeneo/UserManagement/Bundle/Resources/config/steps.yml
src/Akeneo/UserManagement/Bundle/Resources/config/validation.yml
src/Akeneo/UserManagement/Bundle/Resources/config/writers.yml
src/Akeneo/UserManagement/Bundle/Resources/translations/validators.en_US.yml
src/Akeneo/UserManagement/Component/Connector/ArrayConverter/FlatToStandard/Role.php
src/Akeneo/UserManagement/Component/Connector/Processor/Denormalization/RoleWithPermissionsProcessor.php
src/Akeneo/UserManagement/Component/Connector/RoleWithPermissions.php
src/Akeneo/UserManagement/Component/Connector/Writer/Database/RoleWithPermissionsWriter.php
src/Akeneo/UserManagement/Component/Normalizer/RoleNormalizer.php
tests/back/Acceptance/User/InMemoryRoleRepository.php
tests/back/UserManagement/Integration/Bundle/Export/ExportUserRoleIntegration.php
tests/back/UserManagement/Integration/Bundle/Import/ImportUserRoleIntegration.php
tests/back/UserManagement/Specification/Component/Connector/ArrayConverter/FlatToStandard/RoleSpec.php
tests/back/UserManagement/Specification/Component/Connector/ArrayConverter/StandardToFlat/RoleSpec.php
tests/back/UserManagement/Specification/Component/Connector/Processor/Denormalization/RoleWithPermissionsProcessorSpec.php
tests/back/UserManagement/Specification/Component/Connector/RoleWithPermissionsSpec.php
tests/back/UserManagement/Specification/Component/Connector/Writer/Database/RoleWithPermissionsWriterSpec.php
tests/back/UserManagement/Specification/Component/Normalizer/RoleNormalizerSpec.php

Add user roles import with permission.  
Also  update the export to add the `role` column

CPM-133: import user roles with permissions

---

tests/back/Pim/Enrichment/EndToEnd/Product/MassEdit/AbstractMassEditEndToEnd.php
tests/back/Pim/Enrichment/EndToEnd/Product/MassEdit/MassEditAttributeValueOfEntitiesEndToEnd.php
tests/back/Pim/Enrichment/EndToEnd/Product/MassEdit/MassEditCategoriesOfEntitiesEndToEnd.php
tests/back/Pim/Enrichment/EndToEnd/Product/MassEdit/MassEditStatusOfEntitiesEndToEnd.php

API-1407: Add test on mass edit

---

tests/back/Pim/Enrichment/Integration/Product/RemoveValuesFromProductsAndProductModelsIntegration.php
tests/legacy/features/Context/ConnectivityContext.php
tests/legacy/features/Context/FixturesContext.php
tests/legacy/features/pim/enrichment/product/mass-edit/add_products_and_variant_products_to_groups.feature
tests/legacy/features/pim/enrichment/product/mass-edit/change_status.feature
tests/legacy/features/pim/enrichment/product/mass-edit/classify_product_model.feature
tests/legacy/features/pim/enrichment/product/mass-edit/edit-common-attribute/edit_common_attributes.feature
tests/legacy/features/pim/enrichment/product/mass-edit/mass_associate.feature
tests/legacy/features/pim/enrichment/product/pef/edit_variant_product.feature

Adding more tests for non regression of the Events Api

API-1407: Add tests

---

tests/back/Pim/Enrichment/EndToEnd/InternalApiTestCase.php
tests/back/Pim/Enrichment/EndToEnd/Product/Product/InternalApi/DownloadProductPdfEndToEnd.php
tests/back/Pim/Enrichment/EndToEnd/Product/Product/InternalApi/QuantifiedAssociations/AbstractProductWithQuantifiedAssociationsTestCase.php
tests/back/Pim/Enrichment/EndToEnd/Product/Product/InternalApi/QuantifiedAssociations/AddQuantifiedAssociationsToProductEndToEnd.php
tests/back/Pim/Enrichment/EndToEnd/Product/Product/InternalApi/QuantifiedAssociations/RemoveQuantifiedAssociationsFromProductEndToEnd.php
tests/back/Pim/Enrichment/EndToEnd/Product/Product/InternalApi/QuantifiedAssociations/ValidateQuantifiedAssociationsInProductEndToEnd.php
tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/InternalApi/UpdateVariantProductEndToEnd.php

Add the test: test_removing_category_from_variant_product_produces_an_event
EE PR: https://github.com/akeneo/pim-enterprise-dev/pull/10457

Api 1407w3

---

config/packages/dev/monolog.yml
config/packages/monolog.yml

Remove events_api and business_event logs from console for dev

Fix event log for dev

---

src/Akeneo/Connectivity/Connection/back/Application/Webhook/Service/EventsApiDebugLogger.php
src/Akeneo/Connectivity/Connection/back/Application/Webhook/Service/EventsApiDebugResponseErrorLogger.php
src/Akeneo/Connectivity/Connection/back/Application/Webhook/WebhookEventBuilder.php
src/Akeneo/Connectivity/Connection/back/Domain/Webhook/Model/WebhookEvent.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/webhook.yml
src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/Client/GuzzleWebhookClient.php
src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Webhook/Command/SendBusinessEventToWebhooksHandlerSpec.php
src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Webhook/Log/EventSubscriptionSendApiEventRequestLogSpec.php
src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Webhook/Service/Logger/SendApiEventRequestLoggerSpec.php
src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Webhook/WebhookEventBuilderSpec.php
src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Domain/Webhook/Client/WebhookRequestSpec.php
src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Domain/Webhook/Model/WebhookEventSpec.php
src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Webhook/Client/GuzzleWebhookClientSpec.php

Add the debug log for EventsApi SendRequestError

API-1455: Add the debug log for EventsApi SendRequestError

---

CHANGELOG-3.2.md
CHANGELOG-4.0.md
composer.lock
package.json
src/Akeneo/Channel/Bundle/Resources/translations/validators.fi_FI.yml
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.fi_FI.yml
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/messages.fi_FI.yml
src/Akeneo/Connectivity/Connection/front/src/audit/components/Chart/WeeklyAuditChart.tsx
src/Akeneo/Pim/Enrichment/Bundle/PdfGeneration/Renderer/ProductPdfRenderer.php
src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.fi_FI.yml
src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/messages.fi_FI.yml
src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/validators.fi_FI.yml
src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.fi_FI.yml
src/Akeneo/Platform/Bundle/AnalyticsBundle/Resources/translations/messages.fi_FI.yml
src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/translations/jsmessages.fi_FI.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/categories.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/lib/jquery.jstree.less
src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.fi_FI.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/messages.fi_FI.yml
src/Akeneo/Tool/Bundle/ApiBundle/DependencyInjection/PimApiExtension.php
src/Akeneo/Tool/Bundle/ApiBundle/EventListener/CheckApiRequestContentSizeListener.php
src/Akeneo/Tool/Bundle/ApiBundle/Resources/config/event_listeners.yml
src/Akeneo/Tool/Bundle/ApiBundle/tests/integration/Controller/Token/GetAccessTokenIntegration.php
src/Akeneo/UserManagement/Bundle/Resources/translations/jsmessages.fi_FI.yml
yarn.lock

Pullup4to5

---

src/Akeneo/Connectivity/Connection/back/Application/Webhook/Service/Logger/SendApiEventRequestLogger.php
src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Webhook/Service/Logger/SendApiEventRequestLoggerSpec.php

API-1509: Add event count to sent logs

---

src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml

DAPI: update DQI labels in product export builder

---

CHANGELOG-5.0.md
src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/ProductController.php
tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/SuccessListProductEndToEnd.php

See https://github.com/akeneo/pim-community-dev/pull/14034

PIM-9727 add missing query params to hatoas links

---

bin/queue-daemon-wrapper.sh

add a wrapper to better catch signals in console jobs

PIM-9728: add missing daemon wrapper to CE

---

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/Column.less
src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_US.yml

RAC-542: add common translations

---

src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/shared/src/components/page/header/State.tsx

PLG-39: minor UI fix for PageHeader State component

---

akeneo-design-system/src/components/Input/MultiSelectInput/MultiSelectInput.tsx
akeneo-design-system/src/components/Input/MultiSelectInput/MultiSelectInput.unit.tsx
akeneo-design-system/src/components/Input/NumberInput/NumberInput.tsx
akeneo-design-system/src/components/Input/NumberInput/NumberInput.unit.tsx
akeneo-design-system/src/components/Input/TagInput/TagInput.tsx
akeneo-design-system/src/components/Input/TagInput/TagInput.unit.tsx
akeneo-design-system/src/components/Input/TextInput/TextInput.tsx
akeneo-design-system/src/components/Input/TextInput/TextInput.unit.tsx

RAC-541: add onSubmit on DSM inputs

---

src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_US.yml

PLG-86 - Update dashboard name to Activity dashboard

---

src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/common/menu.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_US.yml
src/Akeneo/Tool/Bundle/MeasureBundle/Resources/config/form_extensions.yml

EE PR (with screenshots): https://github.com/akeneo/pim-enterprise-dev/pull/10527

PLG-92 - Organize settings menu items

---

package.json
src/Akeneo/Platform/Bundle/DashboardBundle/Resources/config/routing.yml
src/Akeneo/Platform/Bundle/DashboardBundle/Resources/translations/jsmessages.en_US.yml
src/Akeneo/Platform/Bundle/DashboardBundle/Resources/views/Dashboard/index.html.twig
src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/translations/jsmessages.en_US.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/common/menu.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/controller/dashboard.tsx
src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/package.json
src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/components/DashboardIndex.tsx
src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/components/Header.tsx
src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/components/Widgets/CompletenessWidget.tsx
src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/components/Widgets/LastOperationsWidget.tsx
src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/components/index.ts
src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/index.ts
src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/shared/src/components/page/header/Illustration.tsx

PLG-104: reactify the activity/dashboard page (first iteration)

---

src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/ProductAndProductModel/ESGetProductAndProductModelIdentifiersWithValuesIgnoringLocaleAndScope.php
tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductAndProductModel/ESGetProductAndProductModelIdentifiersWithValuesIgnoringLocaleAndScopeIntegration.php

see https://github.com/akeneo/pim-enterprise-dev/pull/10531

PIM-9736: Search all products and models with non empty values for a given attribute

---

src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/shared/src/hooks/useImageUploader.ts
src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/shared/tests/front/unit/hooks/useImageUploader.unit.ts

RAC-483: Add useImageUploader unit test

---

src/Akeneo/Connectivity/Connection/back/Domain/Webhook/Persistence/Query/SearchEventSubscriptionDebugLogsQueryInterface.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/Elasticsearch/Query/SearchEventSubscriptionDebugLogsQuery.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/Elasticsearch/Repository/ElasticsearchEventsApiDebugRepository.php
src/Akeneo/Connectivity/Connection/back/tests/CatalogBuilder/EventSubscriptionLogLoader.php
src/Akeneo/Connectivity/Connection/back/tests/CatalogBuilder/Resources/config/loaders.yml
src/Akeneo/Connectivity/Connection/back/tests/Integration/Persistence/Elasticsearch/Query/SearchEventSubscriptionDebugLogsQueryIntegration.php
src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Persistence/Elasticsearch/Query/SearchEventSubscriptionDebugLogsQuerySpec.php

API-1498: Update query to search for a value in the log list of an event subscription

---

akeneo-design-system/src/components/Input/MediaFileInput/FullscreenPreview.tsx
akeneo-design-system/src/components/Input/MediaFileInput/MediaFileInput.stories.mdx
akeneo-design-system/src/components/Input/MediaFileInput/MediaFileInput.tsx
akeneo-design-system/src/components/Input/MediaFileInput/MediaFileInput.unit.tsx
akeneo-design-system/src/components/Input/MediaLinkInput/FullscreenPreview.tsx
akeneo-design-system/src/components/Input/MediaLinkInput/MediaLinkInput.stories.mdx
akeneo-design-system/src/components/Input/MediaLinkInput/MediaLinkInput.tsx
akeneo-design-system/src/components/Input/TextAreaInput/TextAreaInput.tsx
akeneo-design-system/src/components/Input/TextInput/TextInput.tsx
akeneo-design-system/src/storybook/hooks/useFakeMediaStorage.ts

RAC-483: refactor MediaFileInput to be like MediaLinkInput

---

src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
src/Akeneo/Connectivity/Connection/front/src/webhook/components/EventLogBadge.tsx
src/Akeneo/Connectivity/Connection/front/src/webhook/components/EventLogDatetime.tsx
src/Akeneo/Connectivity/Connection/front/src/webhook/components/EventLogList.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/webhook/components/EventLogBadge.test.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/webhook/components/EventLogDatetime.test.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/webhook/pages/EventLogList.test.tsx

API-1491: Display error logs in row

---

src/Akeneo/Platform/Bundle/DashboardBundle/Resources/translations/jsmessages.en_US.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/components/ChannelLocalesCompletenesses.tsx
src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/hooks/usePimVersion.ts
src/Oro/Bundle/ConfigBundle/Resources/public/js/form/system/tab/notification.js

PLG-99: display progress messages on completeness component (+CS)

---

akeneo-design-system/src/components/Button/Button.tsx
akeneo-design-system/src/components/Dropdown/Overlay/Overlay.tsx
akeneo-design-system/src/components/Input/MediaLinkInput/MediaLinkInput.tsx
akeneo-design-system/src/components/Input/MultiSelectInput/MultiSelectInput.tsx
akeneo-design-system/src/components/Input/MultiSelectInput/Overlay/Overlay.tsx
akeneo-design-system/src/components/Input/SelectInput/Overlay/Overlay.tsx
akeneo-design-system/src/components/Input/SelectInput/SelectInput.tsx
akeneo-design-system/src/components/Input/TextInput/TextInput.tsx
akeneo-design-system/src/components/Modal/Modal.stories.mdx
akeneo-design-system/src/components/Modal/Modal.tsx
akeneo-design-system/src/components/Modal/Modal.unit.tsx
akeneo-design-system/src/components/Modal/ModalContext.tsx
akeneo-design-system/src/components/SectionTitle/SectionTitle.tsx
akeneo-design-system/src/hooks/index.ts
akeneo-design-system/src/hooks/usePosition.ts
akeneo-design-system/src/hooks/usePosition.unit.ts
src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/shared/src/hooks/index.ts
src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/shared/src/hooks/useImageUploader.ts
src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/shared/src/hooks/useUploader.ts
src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/shared/tests/front/unit/hooks/useImageUploader.unit.ts
src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/shared/tests/front/unit/hooks/useUploader.unit.ts

RAC-483: prevent closing on media file input

---

CHANGELOG-4.0.md
src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Field/IdentifierFilter.php
src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/ProductAndProductModel/ESGetProductAndProductModelIdentifiersWithValuesIgnoringLocaleAndScope.php
src/Akeneo/Pim/Enrichment/Component/Product/Query/Filter/FieldFilterHelper.php
src/Akeneo/Tool/Component/StorageUtils/Exception/InvalidPropertyTypeException.php
tests/back/Acceptance/Attribute/InMemoryGetExistingReferenceDataCodes.php
tests/back/Acceptance/Resources/config/pim/queries.yml
tests/back/Acceptance/spec/Attribute/InMemoryGetExistingReferenceDataCodesSpec.php
tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductAndProductModel/ESGetProductAndProductModelIdentifiersWithValuesIgnoringLocaleAndScopeIntegration.php
tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Filter/Field/IdentifierFilterSpec.php

PIM-9737: Pull-up 4.0 => 5.0

---

CHANGELOG-4.0.md
src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/Db/InitCompletenessDbSchemaSubscriber.php

I unfortunately squash-merged the last pull up, so this pull request aims to fix the git history

PIM-9737: Pull-up 4.0 => 5.0 (fix squashed history)

---

CHANGELOG.md
src/Akeneo/Tool/Bundle/ConnectorBundle/Resources/translations/jsmessages.en_US.yml

PIM-9759: Fix step name translation for product models csv import

---

akeneo-design-system/src/components/Dropdown/Dropdown.stories.mdx
akeneo-design-system/src/components/Dropdown/Item/Item.tsx
akeneo-design-system/src/components/Dropdown/Item/Item.unit.tsx

RAC-562: fix on click on keyboard events

---

src/Akeneo/Connectivity/Connection/front/src/common/components/ExpandableTableRow.tsx

API-1524: Fix the preview of log payload css

---

std-build/migration/prepare_40_to_50.sh

PIM-9753: Fix Upgrade 40 to 50 script

---

CHANGELOG.md
akeneo-design-system/src/components/Card/Card.tsx
akeneo-design-system/src/components/Card/Card.unit.tsx
akeneo-design-system/src/components/Checkbox/Checkbox.tsx

This PR fixes the Card not displaying as a correct link

PIM-9764: Fix DSM Card component to handle links properly

---

src/Akeneo/UserManagement/Bundle/Resources/translations/jsmessages.en_US.yml
src/Akeneo/UserManagement/Bundle/Resources/workspaces/user-ui/src/components/CreateUserForm.tsx
src/Akeneo/UserManagement/Bundle/Validator/Constraints/CreateUserValidator.php
tests/back/UserManagement/Specification/Bundle/Validator/Constraints/CreateUserValidatorSpec.php

- Error message was not displayed when username contains space
- Add front validation: when username contain space or is too short
- Show validation message on blur
- Disable submit button when a validation error occurred

Fix duplicate user error

---

akeneo-design-system/src/hooks/usePosition.ts
akeneo-design-system/src/hooks/usePosition.unit.ts

RAC-562: use a more clever way to place dropdown

---

CHANGELOG-5.0.md
src/Akeneo/Channel/Bundle/Resources/translations/jsmessages.en_US.yml
src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/ProductGrid/RegisterKeyIndicatorFilter.php
src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/translations/messages.en_US.yml
tests/legacy/features/channel/locale/browse_locales.feature

- PLG-138 - Update translation
- PLG-139 - Update translation
- PLG-137 - Update dqi key indicator filter name and value to be more relevant without DQI context

PLG fix translations

---

Makefile
std-build/Makefile
std-build/install-required-files.sh
std-build/migration/prepare_40_to_50.sh

The kernel was not updated in some case

PIM-9772: Fix master standard build

---

.circleci/run_behat.sh
CHANGELOG-4.0.md
src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filters-column.ts

PIM-9784: Pull-up 4.0 => 5.0

---

src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/Elasticsearch/Query/SearchEventSubscriptionDebugLogsQuery.php
src/Akeneo/Connectivity/Connection/back/tests/Integration/Persistence/Elasticsearch/Query/SearchEventSubscriptionDebugLogsQueryIntegration.php

The query scores the MUST higher than the SHOULD, so when you add a MUST at the same level as a SHOULD, the should is almost ignored. 

API-1538: Fix Search events logs query when filtering

---

tests/legacy/features/Context/Page/Dashboard/Index.php

Proposals are an EE feature. I modified the Behat context in the EE to not need this dirty stuff anymore.

PLG-90: Fix end-to-end of dashboard proposals widget

---

CHANGELOG-5.0.md
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/form-tabs.js

In case where we want to update the label of a tab title, we re-rendered all the form. It causes HTTP calls duplication, that slow down a lot the UI on big catalog.

PIM-9799: Improve PEF performance by avoid a useless render

---

src/Akeneo/Pim/Enrichment/Bundle/Resources/config/routing/ui/categorytree.yml
src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
src/Akeneo/Pim/Structure/Bundle/Resources/public/js/controller/CategoriesSettings.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/apps/CategoriesApp.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/apps/index.ts
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/categories/EmptyCategoryTreeList.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/categories/index.ts
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/index.ts
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/categories/CategoriesIndex.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/categories/index.ts
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/index.ts
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml

PLG-168: Initialize the list of category trees page

---

src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/categories/CategoryTreeDataGrid.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/categories/index.ts
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/categories/useCategoryTreeList.ts
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/index.ts
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/models/Category.ts
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/models/index.ts
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/categories/CategoriesIndex.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/hooks/categories/useCategoryTreeList.unit.ts
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/utils/provideCategoryHelper.ts

PLG-169: Show the list of category trees

---

src/Akeneo/Pim/Enrichment/Bundle/Resources/config/routing/ui/categorytree.yml
src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
src/Akeneo/Pim/Structure/Bundle/Resources/public/js/controller/CategoriesSettings.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/apps/CategoriesApp.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/categories/CategoryTreeDataGrid.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/categories/index.ts
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/categories/useCategoryTree.ts
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/categories/useCategoryTreeList.ts
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/shared/index.ts
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/shared/useSetPageTitle.ts
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/models/Category.ts
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/categories/CategoriesTreePage.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/categories/index.ts
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/hooks/categories/useCategoryTree.unit.ts
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/hooks/categories/useCategoryTreeList.unit.ts
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/hooks/shared/useSetPageTitle.unit.ts
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/utils/provideCategoryHelper.ts
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_US.yml

PLG-187: Initialize the category tree page

---

src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/categories/CategoryTreeDataGrid.tsx

PLG-173: Follow a category tree from the category tree list

---

akeneo-design-system/src/icons/DeleteIcon.tsx
behat.yml
src/Akeneo/Pim/Structure/Bundle/Resources/public/js/controller/AssociationTypesSettings.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/apps/AssociationTypeApp.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/apps/AssociationTypesApp.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/apps/index.ts
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/association-types/AssociationTypesDataGrid.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/association-types/DeleteConfirmation.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/association-types/NoAssociationTypes.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/association-types/index.ts
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/index.ts
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/association-types/index.ts
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/association-types/useAssociationTypes.ts
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/index.ts
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/infrastructure/removers/associationTypeRemover.ts
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/models/AssociationType.ts
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/models/index.ts
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/AssociationTypesIndex.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/index.ts
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/association_type/index.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
tests/legacy/features/Behat/Context/Domain/Structure/AssociationTypeContext.php
tests/legacy/features/Context/DataGridContext.php
tests/legacy/features/Context/Page/AssociationType/Index.php
tests/legacy/features/pim/structure/association-type/browse_association_types.feature
tests/legacy/features/pim/structure/association-type/delete_association_type.feature

PLG-64: Revamp Association-types data-grid

---

src/Akeneo/Connectivity/Connection/front/src/webhook/components/EventLogList.tsx

API-1549: Event logs - filter refresh

---

src/Akeneo/Pim/Enrichment/Bundle/Resources/workspaces/enrichment/src/components/completeness/ProductCurrentCompleteness.tsx
src/Akeneo/Pim/Enrichment/Bundle/Resources/workspaces/enrichment/src/components/completeness/index.ts
src/Akeneo/Pim/Enrichment/Bundle/Resources/workspaces/enrichment/src/helpers/index.ts
src/Akeneo/Pim/Enrichment/Bundle/Resources/workspaces/enrichment/src/helpers/scrollToPefAttribute.ts
src/Akeneo/Pim/Enrichment/Bundle/Resources/workspaces/enrichment/src/hooks/index.ts
src/Akeneo/Pim/Enrichment/Bundle/Resources/workspaces/enrichment/src/hooks/useScrollToAttribute.ts
src/Akeneo/Pim/Enrichment/Bundle/Resources/workspaces/enrichment/src/index.ts
src/Akeneo/Pim/Enrichment/Bundle/Resources/workspaces/enrichment/src/models/Product.ts
src/Akeneo/Pim/Enrichment/Bundle/Resources/workspaces/enrichment/src/models/index.ts
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/product_model/edit.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product-model/form/completeness-follow-missing-attribute.tsx
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/completeness.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/product-completeness.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/legacy-bridge/src/provider/DependenciesProvider.type.ts

PLG-151: implement scroll to PEF attribute

---

src/Akeneo/Platform/Bundle/DashboardBundle/Resources/translations/jsmessages.en_US.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/components/Header.tsx

PLG-84: display a random welcome sentence as title

---

src/Akeneo/UserManagement/Component/Model/User.php
tests/back/UserManagement/Specification/Component/Model/UserSpec.php

Before, the fullname returned " Mary Smith " instead of "Mary Smith"
This is only used by proposals, and it badly displayed username in this page.

CPM-159: Fix username

---

composer.json
composer.lock
src/Akeneo/Tool/Component/FileStorage/Adapter/GoogleCloudStorageAdapter.php
src/Akeneo/Tool/Component/FileStorage/spec/Adapter/GoogleCloudStorageAdapterSpec.php
symfony.lock

This class is needed for the growth edition

PIM-9697: Move GoogleCloudStorageAdapter override to CE repository

---

src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/categories/CategoriesTreePage.tsx

PLG-186: Follow a category from the category tree

---

src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/common/menu.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_US.yml

PLG-215: rename settings navigation block labels

---

src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/SettingsIndex.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/index.ts
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/AttributeGroupsIndex.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/LocalesIndex.tsx
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/common/menu.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/routing.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/controller/settings.tsx
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/menu/column.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_US.yml
src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/edit/Edit.tsx
src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/list/List.tsx

PLG-195 : new settings index page

---

src/Akeneo/Pim/Enrichment/Bundle/Resources/workspaces/enrichment/src/components/completeness/ProductCurrentCompleteness.tsx

PLG-224: Fix the completeness for the channel and locale in the header of the PEF

---

src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/SettingsIndex.tsx

PLG-225: Fix Wrong display of the Settings landing page when all catalog entries are not available

---

.circleci/config.yml

Context : `helm3 not found`
change cloud-deployer:2.4 by 2.10
DOD : Helm3 works !

BH-524 - change cloud-deployer version

---

.circleci/config.yml

Enable pull-up 4.0

---

akeneo-design-system/src/components/Search/Search.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/categories/CategoryTreeDataGrid.tsx

**With search :**
**No search results :** 

PLG-172 - Search category trees on label or code

---

.github/workflows/dsm-extract.yml

Fix DSM extract

---

src/Akeneo/Pim/Enrichment/Bundle/Controller/Ui/CategoryTreeController.php
src/Akeneo/Pim/Enrichment/Bundle/Resources/config/controllers.yml
src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/categories/CategoryTreeDataGrid.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/infrastructure/savers/categoryTreeSaver.ts
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/infrastructure/savers/index.ts
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/categories/CategoriesIndex.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/categories/NewCategoryModal.tsx

**Create button :**
**With error :**
**Creation successful :** 
**Without permissions :**

PLG-165: create a category tree

---

.circleci/config.yml

Activation pr did not work. Pull-up is not taken into account.
However workflow appear on circleci
https://app.circleci.com/insights/github/akeneo/pim-community-dev?reporting-window=last-7-days
Maybe pull-up indentation pb.?
circleci config validate doesn't fail.
circleci config process .circleci/config.yml seems to fail without indentation... …

indent pull-up

---

src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/form_extensions.yml
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/requirejs.yml
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/public/js/menu/marketplace-item.js
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/public/templates/marketplace-item.html
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml

CXP-660: Add NEW badge on marketplace menu item

---

src/Akeneo/Connectivity/Connection/front/src/webhook/components/DateRangeFilter/DateTimeInput.tsx
src/Akeneo/Connectivity/Connection/front/src/webhook/components/DateRangeFilter/DateTimeRangeField.tsx
src/Akeneo/Connectivity/Connection/front/src/webhook/components/DateRangeFilter/EventLogDateTimeRangeFilter.tsx
src/Akeneo/Connectivity/Connection/front/src/webhook/components/EventLogList.tsx
src/Akeneo/Connectivity/Connection/front/src/webhook/components/EventLogListFilters.tsx
src/Akeneo/Connectivity/Connection/front/src/webhook/hooks/api/use-infinite-event-subscription-logs.ts
src/Akeneo/Connectivity/Connection/front/src/webhook/model/EventSubscriptionLogFilters.ts
src/Akeneo/Connectivity/Connection/front/tests/src/webhook/components/DateRangeFilter/DateTimeInput.test.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/webhook/components/DateRangeFilter/EventLogDateTimeRangeFilter.test.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/webhook/components/EventLogListFilters.test.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/webhook/hooks/api/use-infinite-event-subscription-logs.test.ts
src/Akeneo/Connectivity/Connection/front/tests/src/webhook/model/EventSubscriptionLogFilters.test.tsx

A lot of rework to simplify the component and support the logical default time for both fields.

API-1597-3/API-1546: Simplify the DateTimeInput component

---

src/Akeneo/Connectivity/Connection/back/Application/Marketplace/MarketplaceUrlGenerator.php
src/Akeneo/Connectivity/Connection/back/Domain/Marketplace/MarketplaceUrlGeneratorInterface.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/InternalApi/Controller/MarketplaceUrlController.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/DependencyInjection/AkeneoConnectivityConnectionExtension.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/controllers.yml
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/marketplace_url.yml
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/routing.yml
src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Marketplace/MarketplaceUrlGeneratorSpec.php
src/Akeneo/Connectivity/Connection/front/src/connect/hooks/use-fetch-marketing-url.ts
src/Akeneo/Connectivity/Connection/front/src/connect/pages/Marketplace.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/connect/hooks/use-fetch-marketplace-url.test.tsx
src/Akeneo/Connectivity/Connection/front/tests/test-utils.tsx

CXP-659: generate marketplace url

---

CHANGELOG.md
src/Akeneo/Pim/Enrichment/Component/Product/Model/AbstractProduct.php

This is a clone PR of the original PR done by a contributor => #12050
in order to launch the CI and to merge his code.

PIM-9833: #12049: fixed null pointer exception when a product do not have a parent

---

src/Akeneo/Pim/Enrichment/Bundle/Controller/Ui/CategoryTreeController.php
src/Akeneo/Pim/Enrichment/Bundle/Resources/config/controllers.yml
src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml
src/Akeneo/Pim/Enrichment/Bundle/Resources/config/routing/ui/categorytree.yml
src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Category/CountTreesChildren.php
src/Akeneo/Pim/Enrichment/Component/Category/Query/CountTreesChildrenInterface.php
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/categories/CategoryTreeDataGrid.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/categories/index.ts
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/categories/useCountCategoryTreesChildren.ts
tests/back/Pim/Enrichment/Integration/Category/CountTressChildrenIntegration.php

PLG-164: Display the number of categories in trees list

---

CHANGELOG-5.0.md
config/services/test_fake/services.yml
make-file/test.mk
phpunit.xml.dist
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/form-tabs.js
src/Akeneo/Tool/Bundle/MeasureBundle/Application/CreateMeasurementFamily/CreateMeasurementFamilyHandler.php
src/Akeneo/Tool/Bundle/MeasureBundle/Application/DeleteMeasurementFamily/DeleteMeasurementFamilyHandler.php
src/Akeneo/Tool/Bundle/MeasureBundle/Application/SaveMeasurementFamily/SaveMeasurementFamilyHandler.php
src/Akeneo/Tool/Bundle/MeasureBundle/Event/MeasurementFamilyCreated.php
src/Akeneo/Tool/Bundle/MeasureBundle/Event/MeasurementFamilyDeleted.php
src/Akeneo/Tool/Bundle/MeasureBundle/Event/MeasurementFamilyUpdated.php
src/Akeneo/Tool/Bundle/MeasureBundle/Model/MeasurementFamily.php
src/Akeneo/Tool/Bundle/MeasureBundle/Persistence/MeasurementFamilyRepository.php
src/Akeneo/Tool/Bundle/MeasureBundle/PublicApi/Onboarder/FindAllMeasurementFamilies.php
src/Akeneo/Tool/Bundle/MeasureBundle/PublicApi/Onboarder/MeasurementFamily.php
src/Akeneo/Tool/Bundle/MeasureBundle/Resources/config/public_api.yml
src/Akeneo/Tool/Bundle/MeasureBundle/Resources/config/services.yml
src/Akeneo/Tool/Bundle/MeasureBundle/Validation/Common/LabelCollectionValidator.php
src/Akeneo/Tool/Bundle/MeasureBundle/spec/Application/SaveMeasurementFamily/SaveMeasurementFamilyHandlerSpec.php
src/Akeneo/Tool/Bundle/MeasureBundle/spec/Event/MeasurementFamilyCreatedSpec.php
src/Akeneo/Tool/Bundle/MeasureBundle/spec/Event/MeasurementFamilyDeletedSpec.php
src/Akeneo/Tool/Bundle/MeasureBundle/spec/Event/MeasurementFamilyUpdatedSpec.php
src/Akeneo/Tool/Bundle/MeasureBundle/tests/Acceptance/CreateMeasurementFamilyTest.php
src/Akeneo/Tool/Bundle/MeasureBundle/tests/Acceptance/DeleteMeasurementFamilyTest.php
src/Akeneo/Tool/Bundle/MeasureBundle/tests/Acceptance/SaveMeasurementFamilyTest.php
src/Akeneo/Tool/Bundle/MeasureBundle/tests/EndToEnd/InternalApi/CreateMeasurementFamilyActionEndToEnd.php
src/Akeneo/Tool/Bundle/MeasureBundle/tests/EndToEnd/InternalApi/SaveMeasurementFamilyActionEndToEnd.php
src/Akeneo/Tool/Bundle/MeasureBundle/tests/Integration/PublicApi/Onboarder/FindAllMeasurementFamiliesIntegration.php
tests/back/Acceptance/EventDispatcher/EventDispatcherMock.php

PIM-9836: Pull-up 5.0 → master

---

src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/shared/tree/Tree.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/shared/tree/TreeActions.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/shared/tree/TreeRow.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/tree/categories/CategoryTree.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/tree/categories/Node.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/categories/CategoriesTreePage.tsx

PLG-116: Handle the display of create and delete actions in Category tree nodes

---

src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml

CXP-670: fix number of results

---

src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
src/Akeneo/Connectivity/Connection/front/src/settings/pages/ListConnections.tsx

CXP-667: Update the Connection settings info panel

---

src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/store/productEditFormStore.ts
src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/store/store.ts

RAC-600: fix dataquality insight test does not pass since redux have bumped from 4.0.5 to 4.1

---

CHANGELOG-5.0.md
src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/BusinessEvent/DispatchBufferedPimEventSubscriberInterface.php
src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/BusinessEvent/DispatchProductCreatedAndUpdatedEventSubscriber.php
src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/BusinessEvent/DispatchProductModelCreatedAndUpdatedEventSubscriber.php
src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/BusinessEvent/DispatchProductModelRemovedEventSubscriber.php
src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/BusinessEvent/DispatchProductRemovedEventSubscriber.php
tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/BusinessEvent/DispatchProductCreatedAndUpdatedEventSubscriberSpec.php
tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/BusinessEvent/DispatchProductModelCreatedAndUpdatedEventSubscriberSpec.php
tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/BusinessEvent/DispatchProductModelRemovedEventSubscriberSpec.php
tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/BusinessEvent/DispatchProductRemovedEventSubscriberSpec.php

PIM-9804: Add an interface to Pim events dispatchers

---

src/Akeneo/Pim/Enrichment/Bundle/Command/BackoffElasticSearchStateHandler.php
src/Akeneo/Pim/Enrichment/Bundle/Command/IndexProductModelCommand.php

PIM-9837 emergency

---

CHANGELOG-5.0.md

Pullup1557

---

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/view/base.ts

RAC-689: Use generic type for renderReact props

---

std-build/package.json

Fix standard edition build

---

front-packages/akeneo-design-system/CONTRIBUTING.md

RAC-DSM: fix DSM path in doc

---

src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/shared/tree/TreeRow.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/tree/categories/Node.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/categories/useCategoryTreeList.ts
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/categories/useCategoryTreeNode.ts
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/infrastructure/savers/moveCategory.ts
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/models/Category.ts
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/hooks/categories/useCategoryTree.unit.ts
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/hooks/categories/useCategoryTreeList.unit.ts
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/hooks/categories/useCategoryTreeNode.unit.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/hooks/shared/useDataGridState.unit.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/utils/provideCategoryHelper.ts
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/utils/provideTreeNodeHelper.ts

PLG-116: Handle move in parent category with preloading children

---

front-packages/shared/src/components/PimView.tsx
front-packages/shared/src/components/index.ts
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/SettingsIndex.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/buttons/AttributeGroupsCreateButton.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/AssociationTypesIndex.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/AttributeGroupsIndex.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/LocalesIndex.tsx
src/Akeneo/Platform/Bundle/AnalyticsBundle/Resources/public/js/SystemInfo.tsx
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/execution/ExecutionDetail.tsx
src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/components/Header.tsx
src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/legacy-bridge/src/index.ts
src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/edit/Edit.tsx
src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/list/List.tsx

Move PimView to shared

---

front-packages/shared/src/microfrontend/MicroFrontendDependenciesProvider.tsx

RAC-689: improve shared translator

---

src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/categories/CategoryTreeDataGrid.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/categories/NewCategoryModal.tsx

PLG-230: Fix wrong notification messages in Category trees page

---

front-packages/akeneo-design-system/src/components/Table/TableHeader/TableHeader.tsx

RAC-689: fix invalid layoud when thead is sticky and tr contain input

---

src/Akeneo/Pim/Enrichment/Bundle/Controller/Ui/CategoryTreeController.php
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/categories/useCountCategoryTreesChildren.ts

PLG-94: fix linter issues

---

src/Akeneo/Tool/Bundle/MeasureBundle/Resources/config/form_extensions.yml

PLG-232: fix place issue of the measurements entry in the settings sub navigation

---

.circleci/config.yml

Report EE circle CI config

---

CHANGELOG.md
front-packages/akeneo-design-system/src/components/SwitcherButton/SwitcherButton.tsx
src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/Filters/TimePeriodFilter.tsx
src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/QualityScoreEvolutionSection/QualityScoreEvolutionSection.tsx
src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/ScoreDistributionSection/Header.tsx
src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Dashboard/ChangeTimePeriod.unit.tsx

Using the DSM component to fix UI section title issue

PIM-9850: Fix broken section title in DQI dashboard

---

src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/providers/CategoryTreeProvider.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/shared/tree/TreeRow.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/tree/categories/Node.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/tree/categories/NodePreview.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/categories/useCategoryTreeNode.ts
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/infrastructure/savers/moveCategory.ts
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/categories/CategoryEditPage.tsx

PLG-200: Move Categories (SImple moves)

---

CHANGELOG-4.0.md
src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/FollowUp/GetCompletenessPerChannelAndLocale.php

Backporting https://github.com/akeneo/pim-community-dev/pull/13731

PIM-9862: [Backport] Fix SQL sort buffer size issue when the catalog has a very large number of categories

---

CHANGELOG.md
config/packages/security.yml
src/Akeneo/UserManagement/.php_cd.php
src/Akeneo/UserManagement/Bundle/Model/LockedAccountException.php
src/Akeneo/UserManagement/Bundle/Provider/CustomDaoAuthenticationProvider.php
src/Akeneo/UserManagement/Bundle/Resources/config/model/doctrine/User.orm.yml
src/Akeneo/UserManagement/Bundle/Resources/config/services.yml
src/Akeneo/UserManagement/Component/Model/User.php
src/Akeneo/UserManagement/Component/Model/UserInterface.php
tests/back/Pim/Enrichment/Specification/Bundle/Command/BackoffElasticSearchStateHandlerSpec.php
tests/back/UserManagement/Specification/Bundle/Provider/CustomDaoAuthenticationProviderSpec.php
upgrades/schema/Version_6_0_20210427163307_add_user_account_locking_after_too_many_attempts.php

Purpose is to provide a temporary user login lock mechanism to protect agains brute force attack.

PIM-9806: Brute-force attack protection

---

front-packages/akeneo-design-system/src/components/TabBar/TabBar.stories.mdx
front-packages/akeneo-design-system/src/components/TabBar/TabBar.tsx
front-packages/akeneo-design-system/src/components/TabBar/TabBar.unit.tsx
front-packages/akeneo-design-system/src/hooks/index.ts
front-packages/akeneo-design-system/src/hooks/useTabBar.ts
front-packages/akeneo-design-system/src/hooks/useTabBar.unit.ts

RAC-715: add overflow management

---

front-packages/akeneo-design-system/src/components/Table/TableBody/useDrop.ts
front-packages/akeneo-design-system/src/components/Table/TableBody/useDrop.unit.tsx
front-packages/akeneo-design-system/src/components/Table/TableRow/TableRow.tsx

RAC-601: Fix Drag & Drop

---

.circleci/config.yml

remove useless step

---

.circleci/config.yml
make-file/test.mk

**Add test-database-structure**

BH-556: Add test-database-structure

---

front-packages/akeneo-design-system/src/components/Table/TableCell/TableCell.tsx

Fix DSM Table Cell props override

Fix DSM Table Cell props override

---

front-packages/akeneo-design-system/src/components/TabBar/TabBar.tsx

Fix performances issues on TabBar component

---

src/Akeneo/Pim/Structure/Bundle/Resources/config/form_extensions/category/edit.yml
src/Akeneo/Pim/Structure/Bundle/Resources/config/requirejs.yml
src/Akeneo/Pim/Structure/Bundle/Resources/public/js/category/history.ts
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/categories/CategoryEditPage.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/categories/HistoryPimView.tsx

PLG-132: display the category history in a dedicated tab

---

src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/AssociationTypesIndex.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/categories/CategoriesIndex.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/categories/CategoriesTreePage.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/categories/CategoryEditPage.tsx

PLG-253: fix settings first breadcrumb item link

---

CHANGELOG.md
src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptions.tsx

PIM-9777: Fix behat for EE PR

---

src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/common/menu.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_US.yml

PLG-237: fix collapsed settings menu label

---

.eslintignore

https://github.com/akeneo/pim-enterprise-dev/pull/10889

CPM-173: Add lint ignore

---

CHANGELOG-4.0.md
src/Akeneo/Tool/Bundle/BatchQueueBundle/Resources/config/services.yml
src/Akeneo/Tool/Component/BatchQueue/Queue/PublishJobToQueue.php
src/Akeneo/Tool/Component/BatchQueue/spec/Queue/PublishJobToQueueSpec.php

PIM-9724: Fix duplicated log files for some job executions

---

CHANGELOG-5.0.md
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/AttributeGroupsIndex.tsx

PIM-9878: Fix breadcrumb link in Settings > Attribute Groups

---

src/Akeneo/Connectivity/Connection/back/Application/Marketplace/MarketplaceUrlGenerator.php
src/Akeneo/Connectivity/Connection/back/Domain/Marketplace/GetUserProfileQueryInterface.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/InternalApi/Controller/MarketplaceUrlController.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/Dbal/Query/DbalGetUserProfileQuery.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/DependencyInjection/AkeneoConnectivityConnectionExtension.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/controllers.yml
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/marketplace.yml
src/Akeneo/Connectivity/Connection/back/tests/Integration/Marketplace/GetUserProfileQueryIntegration.php
src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Marketplace/MarketplaceUrlGeneratorSpec.php
src/Akeneo/Connectivity/Connection/front/src/connect/hooks/use-fetch-marketing-url.ts

CXP-681: Track user profile in marketplace url

---

src/Akeneo/Connectivity/Connection/front/src/connect/components/UserProfileSelector.tsx
src/Akeneo/Connectivity/Connection/front/src/connect/hooks/use-fetch-marketing-url.ts
src/Akeneo/Connectivity/Connection/front/src/connect/hooks/use-fetch-marketplace-url.ts
src/Akeneo/Connectivity/Connection/front/src/connect/hooks/use-fetch-user-profiles.ts
src/Akeneo/Connectivity/Connection/front/src/connect/hooks/use-save-user.ts
src/Akeneo/Connectivity/Connection/front/src/connect/pages/Marketplace.tsx
src/Akeneo/Connectivity/Connection/front/src/error-management/components/ErrorList/ErrorList.tsx
src/Akeneo/Connectivity/Connection/front/src/shared/formatter/use-date-formatter.ts
src/Akeneo/Connectivity/Connection/front/src/shared/formatter/use-number-formatter.ts
src/Akeneo/Connectivity/Connection/front/src/shared/user/useUser.ts
src/Akeneo/Connectivity/Connection/front/src/shared/user/user-context.ts
src/Akeneo/Connectivity/Connection/front/src/shared/user/user.interface.ts
src/Akeneo/Connectivity/Connection/front/tests/src/audit/components/DataDestinationCharts.test.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/audit/components/DataSourceCharts.test.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/connect/hooks/use-fetch-marketplace-url.test.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/settings/pages/EditConnection.test.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/shared/user/useUser.test.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/webhook/components/DateRangeFilter/DateTimeInput.test.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/webhook/components/DateRangeFilter/EventLogDateTimeRangeFilter.test.tsx
src/Akeneo/Connectivity/Connection/front/tests/test-utils.tsx
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/user-context.js
src/Akeneo/UserManagement/Bundle/Resources/translations/jsmessages.en_US.yml

If the user profile is empty display a select to choose it before redirecting to the marketplace

CXP-680: New marketplace page display if the user profile is empty

---

src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/categories/NewCategoryModal.tsx

PLG-259: Auto focus on code field when the category creation form is open

---

config/packages/akeneo_feature_flag.yml
src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/config/requirejs.yml
src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/public/js/onboarding/appcues-agent.ts
src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/public/js/onboarding/appcues-onboarding.ts
src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/public/js/onboarding/appcuses-onboarding.ts
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/onboarding/index.ts
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/onboarding/pim-onboarding.ts
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/pim-app.ts

PLG-243: Enable Appcues onboarding for the FT

---

front-packages/akeneo-design-system/src/components/TabBar/TabBar.tsx
front-packages/akeneo-design-system/src/hooks/useTabBar.ts
front-packages/shared/src/models/channel.ts
front-packages/shared/src/models/channel.unit.ts
src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_US.yml

RAC-602: add methods to channel model

---

CHANGELOG-4.0.md
config/packages/liip_imagine.yml
src/Akeneo/Tool/Bundle/BatchQueueBundle/Resources/config/services.yml
src/Akeneo/Tool/Component/BatchQueue/Queue/PublishJobToQueue.php
src/Akeneo/Tool/Component/BatchQueue/spec/Queue/PublishJobToQueueSpec.php
src/Oro/Bundle/PimDataGridBundle/Resources/public/templates/datagrid/row/product-thumbnail.html

PIM-9888: Merge 4.0 into 5.0

---

CHANGELOG-4.0.md
CHANGELOG-5.0.md
config/packages/liip_imagine.yml
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/AttributeGroupsIndex.tsx
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/grid/grid_view_selector.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/grid/view-selector-secondary-actions.ts
src/Akeneo/Tool/Bundle/BatchQueueBundle/Resources/config/services.yml
src/Akeneo/Tool/Component/BatchQueue/Queue/PublishJobToQueue.php
src/Akeneo/Tool/Component/BatchQueue/spec/Queue/PublishJobToQueueSpec.php
src/Oro/Bundle/PimDataGridBundle/Resources/public/templates/datagrid/row/product-thumbnail.html

PIM-9889: Merge 5.0 into master

---

src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
src/Oro/Bundle/PimDataGridBundle/Resources/translations/jsmessages.en_US.yml

Product grid: move translation key

---

CHANGELOG.md
src/Akeneo/Pim/Enrichment/.php_cd.php
src/Akeneo/Pim/Enrichment/Bundle/Command/BackoffElasticSearchStateHandler.php
src/Akeneo/Pim/Enrichment/Bundle/Command/BulkEsHandlerInterface.php
src/Akeneo/Pim/Enrichment/Bundle/Command/IndexProductModelCommand.php
tests/back/Pim/Enrichment/Specification/Bundle/Command/BackoffElasticSearchStateHandlerSpec.php

When ES undergoes heavy BO office due to node synchronisation. it sends a 429 error answer.
I first try to introduce increasing retry temporisation. Which was of no effect.
I tried then to iterativel reduce batch size, which solved the problem on the customer side.
It was then decided to remove the temporisation since it is of no effect (although it is what is hinted by a 429 response).

PIM-9863 Improve ES backoff pressure handling algorithm.

---

src/Akeneo/Pim/Enrichment/Bundle/Controller/Ui/CategoryTreeController.php
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/helpers/index.ts
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/helpers/permissionsHelper.ts
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/categories/useCategoryTree.ts
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/categories/useEditCategoryForm.ts
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/helpers/permissionsHelper.unit.ts

PLG-263: auto apply permissions on upper and lower levels

---

src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml

PLG-287 : Fix Wrong flash messages in categories

---

src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/categories/EditPermissionsForm.tsx

PLG-285: Improve permissions page helpers

---

src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/categories/DeleteCategoryModal.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/categories/CategoryEditPage.tsx
tests/legacy/features/Behat/Context/Domain/Structure/CategoryContext.php
tests/legacy/features/pim/enrichment/category/remove_a_category.feature

[WIP] PLG-170: update category/tree deletion end to end tests

---

src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/categories/useEditCategoryForm.ts
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/infrastructure/savers/saveEditCategoryForm.ts
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/categories/CategoryEditPage.tsx
tests/legacy/features/pim/enrichment/category/edit_a_category.feature

This PR also fix a bug : the title of the page was not updated after the category saving.

PLG-170: update category edit end to end tests

---

tests/legacy/features/Behat/Context/Domain/Structure/CategoryContext.php
tests/legacy/features/Context/NavigationContext.php
tests/legacy/features/Context/Page/Category/Tree.php
tests/legacy/features/pim/enrichment/category/create_a_category.feature

PLG-170: Cover creation of categories by e2e tests

---

CHANGELOG-5.0.md
src/Akeneo/Pim/Enrichment/Bundle/Command/IndexProductCommand.php
src/Akeneo/Pim/Enrichment/Bundle/Command/IndexProductModelCommand.php
src/Akeneo/Tool/Bundle/ElasticsearchBundle/Client.php

Here is the original PR (done in master) => https://github.com/akeneo/pim-community-dev/pull/13967

PIM-9894: [Backport] PIM-9700: Add batch-size option in index products command and index product-models command

---

CHANGELOG-4.0.md
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/fetcher/attribute-fetcher.js

See https://github.com/akeneo/pim-enterprise-dev/pull/10956

PIM-9892: Add possibility to define options when fetching attributes by type

---

tests/back/Acceptance/Attribute/AttributeContext.php
tests/back/Acceptance/Catalog/Context/ProductValidation.php
tests/back/Acceptance/User/UserContext.php
tests/features/pim/enrichment/product/validation/localizable_values.feature
tests/features/pim/enrichment/product/validation/option_values.feature
tests/features/pim/enrichment/product/validation/scopable_values.feature
tests/features/pim/enrichment/product/value/product_identifier.feature

https://github.com/akeneo/pim-enterprise-dev/pull/10958/files

CPM-230: Update acceptance contexts

---

src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/categories/NewCategoryModal.tsx

PLG-292: New category tree overlay wrong text

---

front-packages/akeneo-design-system/src/components/Dropdown/Dropdown.tsx
front-packages/akeneo-design-system/src/components/Input/SelectInput/SelectInput.tsx
front-packages/akeneo-design-system/src/components/TabBar/TabBar.tsx
src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/messages.en_US.yml

RAC-602: Fix TabBar hidden behaviour & Section dropdown margin

---

src/Akeneo/Tool/Bundle/MeasureBundle/Persistence/MeasurementFamilyRepository.php
src/Akeneo/Tool/Bundle/MeasureBundle/spec/Controller/ExternalApi/JsonSchema/MeasurementFamilyCommonStructureValidatorSpec.php
src/Akeneo/Tool/Bundle/MeasureBundle/spec/Controller/ExternalApi/JsonSchema/MeasurementFamilyValidatorSpec.php
src/Akeneo/Tool/Bundle/MeasureBundle/tests/Integration/Persistence/MeasurementFamilyRepositoryIntegration.php

Here the original PR: https://github.com/akeneo/pim-community-dev/pull/14629

OB-759: [Backport] Fix missing measurements in cache

---

src/Akeneo/Connectivity/Connection/front/src/connect/pages/Marketplace.tsx
src/Akeneo/UserManagement/Bundle/Resources/config/form_extensions/edit.yml
src/Akeneo/UserManagement/Bundle/Resources/config/requirejs.yml
src/Akeneo/UserManagement/Bundle/Resources/public/js/form/edit-form.js

Add refreshUser into pim-user-edit-form

CXP-716: UserContext must be updated when user form is saved

---

CHANGELOG-4.0.md
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/fetcher/attribute-fetcher.js

PIM-9905: Merge 4.0 into 5.0

---

front-packages/akeneo-design-system/src/components/TabBar/TabBar.stories.mdx
front-packages/akeneo-design-system/src/components/TabBar/TabBar.tsx
front-packages/akeneo-design-system/src/components/TabBar/TabBar.unit.tsx

RAC-741: Handle keydown on Tabs

---

front-packages/akeneo-design-system/src/components/Collapse/Collapse.stories.mdx
front-packages/akeneo-design-system/src/components/Collapse/Collapse.tsx
front-packages/akeneo-design-system/src/components/Collapse/Collapse.unit.tsx

RAC-627: Fix Collapse dynamic height

---

src/Akeneo/Connectivity/Connection/back/Application/ErrorManagement/Service/CollectApiError.php
src/Akeneo/Connectivity/Connection/back/tests/.php_cd.php

CXP-686: Fix coupling about Enrich\DomainErrorInterface

---

CHANGELOG-4.0.md
src/Akeneo/Pim/Enrichment/Component/Product/ValuesFiller/FillMissingProductModelValues.php
src/Akeneo/Pim/Enrichment/Component/Product/ValuesFiller/FillMissingProductValues.php
tests/back/Common/Structure/Attribute/Builder.php
tests/back/Pim/Enrichment/Specification/Component/Product/ValuesFiller/FillMissingProductModelValuesSpec.php
tests/back/Pim/Enrichment/Specification/Component/Product/ValuesFiller/FillMissingProductValuesSpec.php

PIM-9902: fix specific local attribute export in model and product model

---

src/Akeneo/Pim/Structure/Bundle/Resources/public/js/controller/CategoriesSettings.tsx

PLG-294: fix category app loaded several times

---

CHANGELOG-4.0.md
src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Repository/ProductModelRepository.php
src/Akeneo/Pim/Enrichment/Component/Product/ProductModel/ImageAsLabel.php
src/Akeneo/Pim/Enrichment/Component/Product/Repository/ProductModelRepositoryInterface.php
tests/back/Acceptance/ProductModel/InMemoryProductModelRepository.php
tests/back/Acceptance/spec/ProductModel/InMemoryProductModelRepositorySpec.php
tests/back/Pim/Enrichment/Integration/Doctrine/ORM/Repository/ProductModelRepositoryIntegration.php
tests/back/Pim/Enrichment/Specification/Component/Product/ProductModel/ImageAsLabelSpec.php

See https://github.com/akeneo/pim-enterprise-dev/pull/11021

PIM-9901: Error 403 on a 2-levels product variant when displaying a variant product without having permission on product model

---

src/Akeneo/Pim/Enrichment/Bundle/Controller/Ui/CategoryTreeController.php
src/Akeneo/Pim/Enrichment/Bundle/DependencyInjection/AkeneoPimEnrichmentExtension.php
src/Akeneo/Pim/Enrichment/Bundle/Form/CategoryFormViewNormalizer.php
src/Akeneo/Pim/Enrichment/Bundle/Resources/config/forms.yml
src/Akeneo/Pim/Enrichment/Component/Category/Form/CategoryFormViewNormalizerInterface.php
src/Akeneo/Pim/Structure/Bundle/Resources/public/js/controller/CategoriesSettings.tsx

PLG-313 - Extract and test Category edition form formatting

---

CHANGELOG-4.0.md
src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Repository/ProductModelRepository.php
src/Akeneo/Pim/Enrichment/Component/Product/ProductModel/ImageAsLabel.php
src/Akeneo/Pim/Enrichment/Component/Product/Repository/ProductModelRepositoryInterface.php
src/Akeneo/Pim/Enrichment/Component/Product/ValuesFiller/FillMissingProductModelValues.php
src/Akeneo/Pim/Enrichment/Component/Product/ValuesFiller/FillMissingProductValues.php
tests/back/Acceptance/ProductModel/InMemoryProductModelRepository.php
tests/back/Acceptance/spec/ProductModel/InMemoryProductModelRepositorySpec.php
tests/back/Common/Structure/Attribute/Builder.php
tests/back/Pim/Enrichment/Integration/Doctrine/ORM/Repository/ProductModelRepositoryIntegration.php
tests/back/Pim/Enrichment/Specification/Component/Product/ProductModel/ImageAsLabelSpec.php
tests/back/Pim/Enrichment/Specification/Component/Product/ValuesFiller/FillMissingProductModelValuesSpec.php
tests/back/Pim/Enrichment/Specification/Component/Product/ValuesFiller/FillMissingProductValuesSpec.php

PIM-9910: Merge 4.0 into 5.0

---

src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/providers/CategoryTreeProvider.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/categories/useCategoryTree.ts

PLG-94: Fix refresh issue of tree when the category id is changed in the url

---

front-packages/akeneo-design-system/src/components/Collapse/Collapse.tsx
front-packages/akeneo-design-system/src/components/Collapse/Collapse.unit.tsx
front-packages/akeneo-design-system/src/components/Pill/Pill.tsx

Add min-width due to border-radius: 50%. In case of long source name the Pill width is reduced

RAC-628: Cleanup function in collapse & fix Pill min-width

---

front-packages/akeneo-design-system/src/components/Field/Field.tsx

RAC-727: fix Field child props

---

src/Akeneo/Pim/Enrichment/Component/Error/DocumentationBuilder/NotScopableAttribute.php
src/Akeneo/Pim/Enrichment/Component/Error/DocumentationBuilder/ScopableAttribute.php
src/Akeneo/Pim/Enrichment/Component/Product/Exception/NotScopableAttributeException.php
src/Akeneo/Pim/Enrichment/Component/Product/Exception/ScopableAttributeException.php
src/Akeneo/Pim/Enrichment/Component/Product/Validator/AttributeValidatorHelper.php
tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/ErrorListProductEndToEnd.php
tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/Boolean/LocalizableScopableFilterIntegration.php
tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/Boolean/ScopableFilterIntegration.php
tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/Date/LocalizableScopableFilterIntegration.php
tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/Date/ScopableFilterIntegration.php
tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/Media/LocalizableScopableFilterIntegration.php
tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/Metric/LocalizableScopableFilterIntegration.php
tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/Metric/ScopableFilterIntegration.php
tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/Number/LocalizableScopableFilterIntegration.php
tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/Number/ScopableFilterIntegration.php
tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/Option/LocalizableScopableFilterIntegration.php
tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/Option/ScopableFilterIntegration.php
tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/Options/LocalizableScopableFilterIntegration.php
tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/Options/ScopableFilterIntegration.php
tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/Price/LocalizableScopableFilterIntegration.php
tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/Price/ScopableFilterIntegration.php
tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/Text/ScopableFilterIntegration.php
tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/TextArea/ScopableFilterIntegration.php
tests/back/Pim/Enrichment/Specification/Component/Error/DocumentationBuilder/NotScopableAttributeSpec.php
tests/back/Pim/Enrichment/Specification/Component/Error/DocumentationBuilder/ScopableAttributeSpec.php
tests/back/Pim/Enrichment/Specification/Component/Product/Exception/NotScopableAttributeExceptionSpec.php
tests/back/Pim/Enrichment/Specification/Component/Product/Exception/ScopableAttributeExceptionSpec.php
tests/back/Pim/Enrichment/Specification/Component/Product/Updater/Copier/AttributeCopierSpec.php
tests/back/Pim/Enrichment/Specification/Component/Product/Validator/AttributeValidatorHelperSpec.php

CXP-346: fix scopable attribute error message

---

front-packages/akeneo-design-system/src/components/Navigation/SubNavigationPanel/SubNavigationPanel.stories.mdx
front-packages/akeneo-design-system/src/components/Navigation/SubNavigationPanel/SubNavigationPanel.tsx
front-packages/akeneo-design-system/src/components/Navigation/SubNavigationPanel/SubNavigationPanel.unit.tsx

Add CSS transition to the SubNavigationPanel

CXP-715: add transition to SubNavigationPanel

---

CODEOWNERS

fix codeowners file for blackhawks

BH-611 - fix codeowners file for blackhawks

---

CHANGELOG.md
src/Akeneo/UserManagement/Bundle/Resources/config/validation.yml
src/Akeneo/UserManagement/Bundle/Resources/translations/validators.en_US.yml
tests/back/UserManagement/Integration/Bundle/Import/ImportUserRoleIntegration.php

PIM-9925: Fix roles that could not contain dashes in their codes

---

CHANGELOG-4.0.md
src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.ja_JP.yml
src/Akeneo/Tool/Component/Connector/Writer/File/FlatItemBufferFlusher.php
src/Akeneo/Tool/Component/Connector/Writer/GlobalFunctionsHelper.php
src/Akeneo/Tool/Component/Connector/Writer/WriterFactory.php
tests/back/Pim/Enrichment/Integration/Product/Export/Product/ExportProductsIntegration.php
tests/legacy/features/Behat/Context/Domain/Collect/ImportProfilesContext.php

PIM-9922: Merge 4.0 into 5.0

---

CHANGELOG-4.0.md
src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/messages.en_US.yml

PIM-9921: Add a translation for the title of category creation form

---

CHANGELOG-4.0.md
CHANGELOG-5.0.md
src/Akeneo/Channel/Bundle/Resources/translations/jsmessages.ja_JP.yml
src/Akeneo/Channel/Bundle/Resources/translations/validators.ja_JP.yml
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.ja_JP.yml
src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.ja_JP.yml
src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/messages.ja_JP.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/product/edit/content/data.js
src/Akeneo/Tool/Component/Connector/Writer/File/FlatItemBufferFlusher.php
src/Akeneo/Tool/Component/Connector/Writer/GlobalFunctionsHelper.php
src/Akeneo/Tool/Component/Connector/Writer/WriterFactory.php
tests/back/Pim/Enrichment/Integration/Product/Export/Product/ExportProductsIntegration.php
tests/back/Pim/Structure/Integration/Family/ImportFamilyIntegration.php
tests/back/UserManagement/Integration/Bundle/Import/ImportUserGroupIntegration.php
tests/back/UserManagement/Integration/Bundle/Import/ImportUserIntegration.php
tests/back/UserManagement/Integration/Bundle/Import/ImportUserRoleIntegration.php
tests/legacy/features/Behat/Context/Domain/Collect/ImportProfilesContext.php

/!\ The lib upgrade will be done in another PR.

PIM-9923: Merge 5.0 into Master

---

src/Akeneo/Pim/Enrichment/Bundle/Resources/config/documentation.yml
src/Akeneo/Pim/Enrichment/Component/Error/DocumentationBuilder/LocalizableScopableAttribute.php
src/Akeneo/Pim/Enrichment/Component/Product/Exception/LocalizableAndNotScopableAttributeException.php
src/Akeneo/Pim/Enrichment/Component/Product/Exception/LocalizableAndScopableAttributeException.php
src/Akeneo/Pim/Enrichment/Component/Product/Exception/NotLocalizableAndNotScopableAttributeException.php
src/Akeneo/Pim/Enrichment/Component/Product/Exception/NotLocalizableAndScopableAttributeException.php
src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/ValidateAttribute.php
tests/back/Pim/Enrichment/Specification/Component/Error/DocumentationBuilder/LocalizableScopableAttributeSpec.php
tests/back/Pim/Enrichment/Specification/Component/Product/Exception/LocalizableAndNotScopableAttributeExceptionSpec.php
tests/back/Pim/Enrichment/Specification/Component/Product/Exception/LocalizableAndScopableAttributeExceptionSpec.php
tests/back/Pim/Enrichment/Specification/Component/Product/Exception/NotLocalizableAndNotScopableAttributeExceptionSpec.php
tests/back/Pim/Enrichment/Specification/Component/Product/Exception/NotLocalizableAndScopableAttributeExceptionSpec.php
tests/back/Pim/Enrichment/Specification/Component/Product/Factory/Value/ValidateAttributeSpec.php
tests/back/Pim/Enrichment/Specification/Component/Product/Factory/ValueFactorySpec.php

CXP-342: Update error messages

---

.circleci/config.yml
cypress/support/commands.js
tests/front/e2e/product/edit.js

We will use the admin user to avoid authentication and/or permissions issues on customers env

BH-620: Use 'adminekeneo' user for front e2e tests

---

CHANGELOG-5.0.md
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/execution/progress.tsx

Here is the PR done in master by Thomas G. => https://github.com/akeneo/pim-community-dev/pull/13914

PIM-9931: [Backport] PIM-9678: The time counter is still running despite the job failed

---

front-packages/invite-user/src/feature/InviteUserApp.tsx

PLG-349: The size of the illustration is wrong

---

CHANGELOG-5.0.md
src/Akeneo/Channel/Bundle/Resources/config/validation/channel.yml
tests/back/Channel/EndToEnd/Channel/ExternalApi/PartialUpdateListChannelEndToEnd.php
tests/back/Channel/Integration/Channel/Validation/ChannelValidationIntegration.php

Here is the PR done in master by Thomas G. => https://github.com/akeneo/pim-community-dev/pull/14652

PIM-9935: [Backport] PIM-9890: Creating Channels with numeric code breaks the PIM

---

src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/validators.fr_FR.yml
src/Akeneo/Tool/Bundle/MessengerBundle/Transport/GooglePubSub/Client.php
src/Akeneo/Tool/Bundle/MessengerBundle/spec/Transport/GooglePubSub/ClientSpec.php
tests/legacy/features/pim/enrichment/product/validation/validate_localized_metric_attributes.feature
tests/legacy/features/pim/enrichment/product/validation/validate_localized_number_attributes.feature
tests/legacy/features/pim/enrichment/product/validation/validate_localized_price_attributes.feature

Fix create subscription

---

src/Akeneo/Tool/Bundle/BatchBundle/EventListener/LoggerSubscriber.php
src/Akeneo/Tool/Bundle/BatchQueueBundle/MessageHandler/JobExecutionMessageHandler.php
src/Akeneo/Tool/Component/Batch/Event/StepExecutionEvent.php
src/Akeneo/Tool/Component/Batch/Step/AbstractStep.php

BH-509: Cleanup job datadog logs

---

.circleci/config.yml

PIM-9934: Stop 3.2 nightly builds

---

src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/validators.fr_FR.yml

Fix ci 28 06 2021

---

src/Akeneo/Connectivity/Connection/docs/marketplace/api.yaml

CXP-777: marketplace specs for Discover

---

src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/validators.fr_FR.yml

fix: translations from nelson

---

src/Akeneo/Connectivity/Connection/docs/marketplace/api.yaml

After discussion, we added an id to `Extension` model spec.

CXP-777: Add id to marketplace extension spec

---

src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/fixtures/marketplace-data-extensions.json

I would like to define mocked extensions data for marketplace API

CXP-787 Define mocked extensions data for marketplace API

---

src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/validators.en_US.yml
src/Akeneo/Pim/Enrichment/Component/Error/DocumentationBuilder/DefaultAttributeValidation.php
src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/File.php
src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/FileValidator.php
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/datagrid/history.yml
tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/FileSpec.php
tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/FileValidatorSpec.php
tests/legacy/features/pim/enrichment/product/import/import_products_with_media.feature
tests/legacy/features/pim/enrichment/product/validation/validate_file_attributes.feature
tests/legacy/features/pim/enrichment/product/validation/validate_image_attributes.feature

PLG-290: English - History several pages  - Logged at

---

src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/public/js/invite-user/controller.tsx

PLG-350: The navigation stay active when I am on the Invite user page

---

CHANGELOG-4.0.md

PIM-9939: Merge 4.0 into 5.0

---

src/Akeneo/Pim/Enrichment/Bundle/Resources/config/documentation.yml
src/Akeneo/Pim/Enrichment/Bundle/Resources/config/validation/product.yml
src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/validators.en_US.yml
src/Akeneo/Pim/Enrichment/Component/Error/DocumentationBuilder/UniqueProductIdentifier.php
src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/Product/UniqueProductEntity.php
src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/Product/UniqueProductEntityValidator.php
tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/CreateProductEndToEnd.php
tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/PartialUpdateProductEndToEnd.php
tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/ExternalApi/CreateVariantProductEndToEnd.php
tests/back/Pim/Enrichment/Integration/Validation/ProductIdentifierValidationIntegration.php
tests/back/Pim/Enrichment/Specification/Component/Error/DocumentationBuilder/UniqueProductIdentifierSpec.php
tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/Product/UniqueProductEntityValidatorSpec.php
tests/features/pim/enrichment/product/value/product_identifier.feature
tests/legacy/features/pim/enrichment/product/import/import_products_with_invalid_data.feature

CXP-319 Improved error message on unique product identifier
Improved Rest API error message
Improved Error monitoring message with documentation
Improved PEF error message

CXP-319 Improved error message on unique product identifier

---

CHANGELOG-4.0.md
CHANGELOG-5.0.md
src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/messages.en_US.yml

PIM-9940: Merge 5.0 into master

---

src/Akeneo/FreeTrial/back/Domain/Model/InvitedUser.php
src/Akeneo/FreeTrial/back/Domain/Query/GetInvitedUserQuery.php
src/Akeneo/FreeTrial/back/Infrastructure/MySql/MySqlGetInvitedUserQuery.php
src/Akeneo/FreeTrial/back/Infrastructure/MySql/MySqlInvitedUserRepository.php
src/Akeneo/FreeTrial/back/Infrastructure/Subscriber/UserFirstConnectionSubscriber.php
src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/config/mysql.yml
src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/config/subscribers.yml
src/Akeneo/FreeTrial/tests/back/Integration/MySql/MySqlGetInvitedUserQueryIntegration.php
src/Akeneo/FreeTrial/tests/back/Integration/MySql/MySqlInvitedUserRepositoryIntegration.php

PLG-278: Activate user when he logs in for the first time in the Free Trial

---

src/Akeneo/Connectivity/Connection/back/Domain/Marketplace/GetAllExtensionsQueryInterface.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/InternalApi/Controller/Marketplace/GetAllExtensions.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Marketplace/GetAllExtensionsQuery.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/controllers.yml
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/marketplace.yml
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/routing.yml
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/routing/marketplace.yml
src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Marketplace/GetAllExtensionsEndToEnd.php

- Internal API endpoint to fetch extensions.
- E2e test, but fixture aren't properly loaded yet since the query doesn't exist.

CXP-791: add internal API to fetch extensions

---

CHANGELOG-5.0.md
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/attribute-groups/AttributeGroupsDataGrid.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/locales/LocalesDataGrid.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/AttributeGroupsIndex.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/LocalesIndex.tsx
src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/list/List.tsx

PIM-9945: Fix number of displayed items in attribute group, locale and measurement family grids

---

src/Akeneo/Connectivity/Connection/back/Infrastructure/ContentSecurityPolicy/MarketplaceContentSecurityPolicy.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/services.yml

CXP-782: add CSP for the marketplace images

---

front-packages/shared/src/components/DeleteModal.tsx
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/product/edit/content/data.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/export/product/edit/content/data.html

RAC-758: Add label overrides in DeleteModal

---

CHANGELOG-5.0.md
src/Akeneo/Pim/Structure/Component/Remover/FamilyRemover.php
src/Akeneo/Tool/Bundle/StorageUtilsBundle/Doctrine/Common/Remover/BaseRemover.php
src/Akeneo/Tool/Bundle/VersioningBundle/EventSubscriber/AddRemoveVersionSubscriber.php
src/Akeneo/Tool/Bundle/VersioningBundle/spec/EventSubscriber/AddRemoveVersionSubscriberSpec.php
tests/back/Pim/Structure/Specification/Component/Remover/FamilyRemoverSpec.php

Backport of : https://github.com/akeneo/pim-community-dev/pull/14530

PIM-9956: [Backport] PIM-9852: Fix exception during PRE_REMOVE on removeAll cause ES desynchronisation

---

src/Akeneo/Pim/Structure/Bundle/Controller/ExternalApi/AttributeController.php

See https://github.com/akeneo/pim-enterprise-dev/pull/11201
The getNormalizationContext method is override in EE

CPM-256: update controller to pass params in normalizer

---

.circleci/config.yml

Fix Onboarder tests dependencies

---

front-packages/shared/src/components/DeleteModal.tsx
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/product/edit/content/data.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/export/product/edit/content/data.html

[feature branch] Tailored export foundations 2

---

src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/messages.en_US.yml

RAC-769: Rename scope by channel

---

CHANGELOG.md
src/Akeneo/Pim/Enrichment/Component/Product/Validator/UniqueValuesSet.php
tests/back/Pim/Enrichment/Specification/Component/Product/Validator/UniqueValuesSetSpec.php

PIM-9946: forbid import with identical identifier

---

src/Akeneo/Connectivity/Connection/front/src/connect/components/MarketplaceIsLoading.tsx
src/Akeneo/Connectivity/Connection/front/src/connect/pages/MarketplacePage.tsx

CXP-785: add skeleton

---

.circleci/config.yml

Fixes Growth Edition dependency on CE.

BH-663 Fixes composer.json for GRTH

---

CHANGELOG.md
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/index.ts
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/index.ts

Do not export the main Settings component in the `components` export file to prevent circular references

PIM-9966: Fix Settings page crashing when coming from the PEF

---

front-packages/akeneo-design-system/src/components/Input/SelectInput/Overlay/Overlay.tsx
front-packages/akeneo-design-system/src/components/Input/SelectInput/SelectInput.tsx

This PR fixes the Overlay of the Select, to use the same behavior than the Dropdown component.
We use a Portal to put the overlay as fixed in the <body>, to be able to use this component anywhere.

CPM-250: Fix select overlay

---

.circleci/config.yml

Remove MySQL port translation that fails intermittently during the CI.

BH-664 Remove MySQL port translation in CI

---

src/Akeneo/Connectivity/Connection/front/src/connect/pages/SelectUserProfilePage.tsx

CXP-779 Removed top margin on marketplace profile selector page

CXP-779 Removed top margin on marketplace profile selector page

---

src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml

CXP-707 Updated translation message

---

src/Akeneo/Connectivity/Connection/docs/marketplace/api.yaml

If you want to check live the spec, go https://editor.swagger.io/, `File` -> `Import url` and paste `https://github.com/akeneo/pim-community-dev/blob/CXP-766/src/Akeneo/Connectivity/Connection/docs/marketplace/api.yaml`

CXP-766: Specs for the Apps endpoint

---

front-packages/akeneo-design-system/src/components/Input/SelectInput/SelectInput.tsx
front-packages/akeneo-design-system/src/components/Input/SelectInput/SelectInput.unit.tsx

CPM-244: Handle keyboard navigation for Select Input

---

front-packages/akeneo-design-system/src/components/Table/TableBody/TableBody.tsx
front-packages/akeneo-design-system/src/components/Table/TableBody/TableBody.unit.tsx

This PR, fix blank page on tailored export when the user exceeded the limit of column

RAC-793: Fix error thrown when tbody contain a conditionnal node

---

front-packages/akeneo-design-system/src/theme/connector/index.ts
front-packages/akeneo-design-system/src/theme/themes.ts

BCAPP-58: Add DSM connector theme

---

front-packages/akeneo-design-system/src/index.ts

BCAPP-58: Fix missing export

---

src/Akeneo/Connectivity/Connection/back/Infrastructure/EventSubscriber/AclPrivilegesEventSubscriber.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/acl.yml
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/event_subscribers.yml
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/messages.en_US.yml
src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/EventSubscriber/AclPrivilegesEventSubscriberSpec.php
src/Oro/Bundle/ConfigBundle/Resources/config/acl.yml
src/Oro/Bundle/SecurityBundle/Acl/Event/EventDispatcherAware.php
src/Oro/Bundle/SecurityBundle/Acl/Event/PrivilegesPostLoadEvent.php
src/Oro/Bundle/SecurityBundle/Acl/Extension/AclClassInfo.php
src/Oro/Bundle/SecurityBundle/Acl/Persistence/AclManager.php
src/Oro/Bundle/SecurityBundle/Acl/Persistence/AclPrivilegeRepository.php
src/Oro/Bundle/SecurityBundle/Annotation/Acl.php
src/Oro/Bundle/SecurityBundle/Metadata/ActionMetadata.php
src/Oro/Bundle/SecurityBundle/Metadata/ActionMetadataProvider.php
src/Oro/Bundle/SecurityBundle/Model/AclPrivilege.php
src/Oro/Bundle/SecurityBundle/Resources/config/services.yml

CXP-725: Be able to authorize a user to manage apps

---

config/bundles.php
src/Akeneo/FreeTrial/back/Infrastructure/Symfony/AkeneoCommunityFreeTrialBundle.php
src/Akeneo/FreeTrial/back/Infrastructure/Symfony/DependencyInjection/AkeneoCommunityFreeTrialExtension.php
src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/config/requirejs.yml

Rename the Free-Trial bundle to be able to add the main bundle in `EE/tria/`

PLG-212: Free trial - Invite user

---

front-packages/akeneo-design-system/src/components/Navigation/MainNavigationItem/MainNavigationItem.tsx
src/Akeneo/FreeTrial/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/KeyIndicators.tsx
src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/SectionTitle.tsx
src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/components/DashboardIndex.tsx

PLG-210 / PLG-209 : display fake widget and helpers on the dashboards of the FT

---

src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/fixtures/marketplace-data-apps.json
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
src/Akeneo/Connectivity/Connection/front/src/connect/components/ActivateAppButton.tsx
src/Akeneo/Connectivity/Connection/front/src/connect/components/Marketplace.tsx
src/Akeneo/Connectivity/Connection/front/src/connect/components/MarketplaceCard.tsx
src/Akeneo/Connectivity/Connection/front/src/connect/components/Section.tsx
src/Akeneo/Connectivity/Connection/front/src/connect/hooks/use-fetch-apps.ts
src/Akeneo/Connectivity/Connection/front/src/connect/pages/MarketplacePage.tsx
src/Akeneo/Connectivity/Connection/front/src/model/app.ts
src/Akeneo/Connectivity/Connection/front/tests/src/connect/hooks/use-fetch-apps.test.tsx

CXP-795: display apps in marketplace

---

front-packages/akeneo-design-system/src/components/Dropdown/Dropdown.stories.mdx
front-packages/akeneo-design-system/src/components/Dropdown/Overlay/Overlay.tsx
front-packages/akeneo-design-system/src/components/Input/TableInput/TableInputBoolean/TableInputBoolean.tsx
front-packages/akeneo-design-system/src/components/Input/TableInput/TableInputSelect/TableInputSelect.tsx
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/attributes.js

Cpm 275 fix horizontal position for dropdown overlay

---

front-packages/akeneo-design-system/src/components/Search/Search.tsx

RAC-800: Add inputRef prop to Search component

---

tests/back/Integration/IntegrationTestsBundle/Launcher/JobLauncher.php
tests/back/UserManagement/Integration/Bundle/Import/ImportUserRoleIntegration.php

CPM-187: Allow warning return for job launcher

---

front-packages/akeneo-design-system/example/src/__snapshots__/App.test.js.snap
front-packages/akeneo-design-system/src/components/Collapse/Collapse.tsx
front-packages/akeneo-design-system/src/components/Collapse/Collapse.unit.tsx
front-packages/akeneo-design-system/src/theme/common.ts

RAC: Improve Collapse component animation

---

tests/back/Acceptance/Catalog/Context/ProductValidation.php

CPM-278: update validation context

---

front-packages/akeneo-design-system/src/components/Table/Table.tsx
front-packages/akeneo-design-system/src/components/Table/TableBody/TableBody.tsx
front-packages/akeneo-design-system/src/components/Table/TableBody/useDragElementIndex.tsx
front-packages/akeneo-design-system/src/components/Table/TableRow/TableRow.tsx
front-packages/akeneo-design-system/src/components/Table/TableRow/usePlaceholderPosition.ts
front-packages/shared/src/microfrontend/MicroFrontendDependenciesProvider.tsx

RAC-807: Memoize Table handlers to improve performance

---

docker-compose.yml

There was an update of the selenium image yesterday and it is buggy.

fix: freeze selenium version due to a bug in the next version

---

front-packages/akeneo-design-system/src/components/Search/Search.tsx
front-packages/akeneo-design-system/src/components/SectionTitle/SectionTitle.tsx
front-packages/measurement/src/feature/pages/edit/unit-tab/UnitTab.tsx
front-packages/measurement/src/feature/pages/list/List.tsx
src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/categories/CategoryTreeDataGrid.tsx
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/quantified-associations/components/QuantifiedAssociations.tsx
src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_US.yml
src/Akeneo/Tool/Bundle/MeasureBundle/Resources/translations/jsmessages.en_US.yml

RAC-615: Add sticky prop to Search component

---

src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptionTable.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/NewOptionPlaceholder.tsx

PLG-302: Add Label column

---

src/Akeneo/Channel/Bundle/Query/Sql/SqlGetAllViewableLocalesForUser.php
src/Akeneo/Channel/Bundle/Resources/config/queries.yml
src/Akeneo/Channel/Component/Query/PublicApi/Permission/GetAllViewableLocalesForUserInterface.php
src/Akeneo/Pim/Structure/Bundle/Resources/config/queries.yml
src/Akeneo/Pim/Structure/Component/Query/PublicApi/Permission/GetAllViewableLocalesForUser.php
src/Akeneo/Pim/Structure/Component/Query/PublicApi/Permission/GetViewableAttributeCodesForUser.php
src/Akeneo/Pim/Structure/Component/Query/PublicApi/Permission/GetViewableAttributeCodesForUserInterface.php
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/redirect.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/common/edit/launch.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/export/common/edit/launch.html
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/form/redirect.html

RAC-751: move permission interfaces in CE

---

front-packages/akeneo-design-system/src/components/Input/TableInput/TableInputBoolean/TableInputBoolean.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/attributes/useAttributeCodeInput.tsx
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/attribute/form/delete/DeleteModal.tsx
src/Akeneo/Platform/Bundle/UIBundle/tests/front/unit/attribute/form/delete/DeleteModal.unit.tsx

CPM-332: Prevent duplicate code in attribute creation popin

---

src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptionTable.tsx
tests/front/unit/structure/attribute-option/components/AttributeOptionTable.unit.tsx

PLG-306-bis: Replace role by data-testid

---

src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
src/Akeneo/Connectivity/Connection/front/src/connect/components/Marketplace.tsx
src/Akeneo/Connectivity/Connection/front/src/connect/components/MarketplaceHelper.tsx
src/Akeneo/Connectivity/Connection/front/src/connect/pages/MarketplacePage.tsx

The list of available Apps must be behind the feature flag.
**Feature flag disabled**
**Feature flag enabled**

CXP-800: Marketplace Apps behind a feature flag

---

src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml

Adjusted translation message for marketplace helper

CXP-829 Adjusted translation message

---

src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/List.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/ListItem.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/public/less/attribute-option.less
tests/front/unit/structure/attribute-option/components/List.unit.tsx

PLG-308: Add Label column in 5.0

---

src/Akeneo/UserManagement/Bundle/Resources/config/repositories.yml
src/Akeneo/UserManagement/Bundle/Resources/config/savers.yml
upgrades/schema/Version_6_0_20210715082931_add_product_web_api_acl.php
upgrades/test_schema/Version_6_0_20210715082931_add_product_web_api_acl_Integration.php

Migration introduced in https://github.com/akeneo/pim-community-dev/pull/15082
The migration was incorrect and the tests were passing because the migration used a service marked as `private` in prod, `public` in test.
Rollback'ed in https://github.com/akeneo/pim-community-dev/pull/15109

CXP-811: Restore migration

---

src/Akeneo/Channel/Bundle/Resources/config/datagrid/currency.yml
src/Oro/Bundle/PimDataGridBundle/Resources/views/Property/activated.html.twig

PLG-456: Currencies - English improvements

---

src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/product/edit.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/product_model/edit.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/sub-navigation.ts

This PR adds this behavior for all the PIM

PLG-452: Auto-collapse left-column when starting compare/translate

---

src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_AU.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_GB.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_NZ.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_US.yml

PLG-454: Change the 404 page English message

---

src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_AU.yml
src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_GB.yml
src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_NZ.yml
src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml

PLG-460: Families bulk actions - English improvements

---

src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_AU.yml
src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_GB.yml
src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_NZ.yml
src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
src/Akeneo/Pim/Structure/Bundle/Resources/config/datagrid/attribute.yml
src/Oro/Bundle/PimDataGridBundle/Resources/translations/jsmessages.en_US.yml

PLG-459: Attribute main screen - English improvements

---

src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/Resources/translations/jsmessages.en_AU.yml
src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/Resources/translations/jsmessages.en_GB.yml
src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/Resources/translations/jsmessages.en_NZ.yml
src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/Resources/translations/jsmessages.en_US.yml

PLG-455: CVM page - English improvements

---

src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/providers/CategoryTreeProvider.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/helpers/treeHelper.ts
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/categories/useCategoryTree.ts
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/categories/useCategoryTreeNode.ts
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/categories/CategoriesIndex.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/categories/CategoriesTreePage.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/categories/CategoryEditPage.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/helpers/treeHelper.unit.ts
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/hooks/categories/useCategoryTree.unit.ts
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/utils/provideCategoryHelper.ts

PLG-401: Open the category tree to the last selected category, if any

---

src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptionTable.tsx

PLG-476: "Add option" button size to small

---

src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptionTable.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/New.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/public/less/attribute-option.less
tests/legacy/features/Context/Page/Attribute/Creation.php

PLG-477: Focus border on options labels field + DSM input field on new attribute option

---

CHANGELOG.md
src/Akeneo/Tool/Bundle/ElasticsearchBundle/Application/MigrateIndexWithoutDowntimeHandler.php
src/Akeneo/Tool/Bundle/ElasticsearchBundle/Client.php
src/Akeneo/Tool/Bundle/ElasticsearchBundle/Domain/Model/IndexMigration.php
src/Akeneo/Tool/Bundle/ElasticsearchBundle/Domain/Query/IndexMigrationRepositoryInterface.php
src/Akeneo/Tool/Bundle/ElasticsearchBundle/IndexConfiguration/IndexConfiguration.php
src/Akeneo/Tool/Bundle/ElasticsearchBundle/IndexConfiguration/UpdateIndexMappingWithoutDowntime.php
src/Akeneo/Tool/Bundle/ElasticsearchBundle/Infrastructure/Client/ClientMigration.php
src/Akeneo/Tool/Bundle/ElasticsearchBundle/Infrastructure/Client/ClientMigrationInterface.php
src/Akeneo/Tool/Bundle/ElasticsearchBundle/Infrastructure/Clock/SystemClock.php
src/Akeneo/Tool/Bundle/ElasticsearchBundle/Infrastructure/Install/InstallSubscriber.php
src/Akeneo/Tool/Bundle/ElasticsearchBundle/Infrastructure/PublicApi/IndexMigrationIsDone.php
src/Akeneo/Tool/Bundle/ElasticsearchBundle/Infrastructure/Repository/IndexMigrationRepository.php
src/Akeneo/Tool/Bundle/ElasticsearchBundle/Resources/config/services.yml
src/Akeneo/Tool/Bundle/ElasticsearchBundle/spec/IndexConfiguration/LoaderSpec.php
src/Akeneo/Tool/Bundle/ElasticsearchBundle/spec/IndexConfiguration/UpdateIndexMappingWithoutDowntimeSpec.php
src/Akeneo/Tool/Bundle/ElasticsearchBundle/tests/integration/Infrastructure/PublicApi/IndexMigrationIsDoneIntegration.php
src/Akeneo/Tool/Bundle/ElasticsearchBundle/tests/integration/UpdateIndexMappingWithoutDowntimeIntegration.php
src/Akeneo/Tool/Component/Elasticsearch/ClockInterface.php
src/Akeneo/Tool/Component/Elasticsearch/PublicApi/Read/IndexMigrationIsDoneInterface.php
src/Akeneo/Tool/Component/Elasticsearch/PublicApi/Write/MigrateIndexWithoutDowntime.php
src/Akeneo/Tool/Component/Elasticsearch/PublicApi/Write/MigrateIndexWithoutDowntimeHandlerInterface.php
upgrades/schema/Version_6_0_20210816123500_add_index_migration_table.php
upgrades/test_schema/Version_6_0_20210816123500_add_index_migration_table_Integration.php

See https://github.com/akeneo/pim-enterprise-dev/pull/11423

PIM-9989: Add possibility to clone a client with another index

---

src/Akeneo/Pim/Structure/Bundle/Query/PublicApi/Group/Sql/SqlGetGroupTranslations.php

RAC-851: Fix group label is not fallbacked when group label is empty

---

front-packages/akeneo-design-system/src/icons/UserIcon.tsx
front-packages/akeneo-design-system/src/icons/index.ts
package.json
src/Akeneo/Platform/Bundle/AnalyticsBundle/Resources/public/js/SystemInfo.tsx
src/Akeneo/Platform/Bundle/UIBundle/Controller/SystemController.php
src/Akeneo/Platform/Bundle/UIBundle/Query/CountSystemEntitiesQueryInterface.php
src/Akeneo/Platform/Bundle/UIBundle/Query/Sql/CountSystemEntitiesQuery.php
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/controllers.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/common/menu.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/queries.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/routing.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/controller/system-index.tsx
src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_US.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/system/package.json
src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/system/src/components/SystemIndex.tsx
src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/system/src/components/index.ts
src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/system/src/hooks/index.ts
src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/system/src/hooks/useCountEntities.ts
src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/system/src/index.ts
tests/back/Platform/Integration/UI/Query/CountSystemEntitiesQueryIntegration.php

PLG-260: Create a menu page for System

---

src/Akeneo/Pim/Structure/Bundle/Query/PublicApi/Group/Sql/SqlGetGroupTranslations.php

[Feature branch] Tailored export

---

std-build/package.json

Add system workspace in std's package.json

---

front-packages/shared/src/components/Navigation/PimNavigation.tsx

In this PR, we re added the possibility to open in another tab item in main menu

RAC: Fix main navigation is not anymore a href cannot open in another tab

---

tests/back/Integration/IntegrationTestsBundle/Helper/AuthenticatorHelper.php
tests/back/Integration/IntegrationTestsBundle/Helper/WebClientHelper.php

Move Integration tests helper classes to Community Edition so all editions can benefit from them.

BH-651 Provides Integration tests helpers for all edition

---

front-packages/shared/src/index.ts
front-packages/shared/src/tools/index.ts
front-packages/shared/src/tools/sanitize.ts
front-packages/shared/src/tools/sanitize.unit.ts
src/Akeneo/Platform/Bundle/ImportExportBundle/Controller/InternalApi/JobInstanceController.php
src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/routing/internal_api/job_instance.yml
src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/translations/jsmessages.en_US.yml
src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/translations/validators.en_US.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_base_export_edit.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_base_import_edit.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_product_export_edit.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_product_import_edit.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_product_model_export_edit.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_product_model_import_edit.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_base_export_edit.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_base_import_edit.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_product_export_edit.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_product_import_edit.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_product_model_export_edit.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_product_model_import_edit.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/yml_base_export_edit.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/yml_base_import_edit.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/common/duplicate/DuplicateJob.tsx
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/common/duplicate/duplicate.ts
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/product/edit/field/with-label.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_US.yml
src/Akeneo/Platform/Bundle/UIBundle/tests/front/unit/job/common/duplicate/DuplicateJob.unit.tsx
src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/validation/jobinstance.yml

RAC-768: Add duplicate job profile button&modal

---

src/Akeneo/Connectivity/Connection/front/src/connect/components/MarketplaceCard.tsx

CXP-833: fix CSS glitch about marketplace app cards

---

src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptionRow.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptionTable.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptions.tsx

[WIP] Attribute options - Fix perfs on click

---

front-packages/akeneo-design-system/src/components/Collapse/Collapse.tsx

RAC-845: fix outline on overflow

---

CHANGELOG.md
src/Akeneo/Platform/Bundle/UIBundle/Resources/views/macros.html.twig
src/Akeneo/UserManagement/Bundle/Resources/views/Group/update.html.twig

Reusing the same macro as for the user and role pages to prevent page freezing and removing an old twig macro in the meantime

PIM-9997: Fix page freezing after deleting a user group

---

CHANGELOG.md
config/services/pim_parameters.yml
src/Akeneo/Tool/Bundle/ElasticsearchBundle/Resources/config/commands.yml

PIM-10041: change index field limit  for reference entities and assets

---

src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_base_export_show.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_base_import_show.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_product_export_show.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_product_import_show.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_product_model_export_show.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_product_model_import_show.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_base_export_show.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_base_import_show.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_product_export_show.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_product_import_show.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_product_model_export_show.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_product_model_import_show.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/yml_base_export_show.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/yml_base_import_show.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/common/edit-button.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/export/edit/edit.js

RAC-858: move job edit button to CE

---

.circleci/config.yml

**Issue:**
PIM EE Dockerfile try to run the `COPY tmp tmp` instruction.
This `tmp` directory is not present in the CE CI context
**Fix:**
Add the CI step to checkout BigCommerce repository in the correct folder in order to build the EE image correctly.

Checkout big commerce connector repository in CE workflow

---

composer.json
composer.lock

Hotfix: Use Phpstan Symfony 0.12.44

---

front-packages/akeneo-design-system/src/components/Input/TableInput/TableInput.unit.tsx
front-packages/akeneo-design-system/src/components/Input/TableInput/TableInputBody/TableInputBody.tsx
front-packages/akeneo-design-system/src/components/Input/TableInput/TableInputBoolean/TableInputBoolean.tsx
front-packages/akeneo-design-system/src/components/Input/TableInput/TableInputRow/TableInputRow.tsx
front-packages/akeneo-design-system/src/components/Input/TableInput/TableInputSelect/TableInputSelect.tsx

CPM-298: Fix drag and drop

---

front-packages/akeneo-design-system/src/components/Input/SelectInput/SelectInput.tsx

To fix this issue we had to change a callback we use on the component selectInput from the akeneo design system.
We make the callback call when the onChange is modified.

CPM-339 fix select Input callback on keyboard navigation

---

src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
src/Akeneo/Connectivity/Connection/front/src/connect/components/AppWizardWithSteps/AppWizardWithSteps.tsx
src/Akeneo/Connectivity/Connection/front/src/connect/components/AppWizardWithSteps/PermissionsSummary.tsx
src/Akeneo/Connectivity/Connection/front/src/shared/permission-form-registry/permission-form-registry.interface.ts
src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/AppWizardWithSteps/AppWizardWithSteps.test.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/AppWizardWithSteps/Permissions.test.tsx
src/Akeneo/Connectivity/Connection/workspaces/permission-form/src/component/PermissionSectionSummary.test.tsx
src/Akeneo/Connectivity/Connection/workspaces/permission-form/src/component/PermissionSectionSummary.tsx
src/Akeneo/Connectivity/Connection/workspaces/permission-form/src/index.ts
src/Akeneo/Connectivity/Connection/workspaces/permission-form/src/registry/PermissionFormRegistry.ts

CXP-724: implements Summary steps in app wizard

---

src/Akeneo/Pim/Enrichment/Component/Product/Completeness/MissingRequiredAttributesCalculator.php
src/Akeneo/Pim/Enrichment/Component/Product/Completeness/MissingRequiredAttributesCalculatorInterface.php
src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/ProductModelNormalizer.php
src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/ProductNormalizer.php
tests/back/Pim/Enrichment/Integration/Completeness/AbstractCompletenessTestCase.php
tests/back/Pim/Enrichment/Specification/Component/Product/Completeness/MissingRequiredAttributesCalculatorSpec.php

See https://github.com/akeneo/pim-enterprise-dev/pull/11697  
An interface is added to ease the override of the service in EE

PIM-10059: Fix completeness display when user does not have permission on attribute group(s)

---

src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/CreateAttributeModal.tsx
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/attribute/form/CreateAttributeButtonApp.tsx

https://github.com/akeneo/pim-enterprise-dev/pull/11719

CPM-358: Add previous button

---

upgrades/schema/Version_6_0_20210908142400_add_product_web_api_acl.php
upgrades/test_schema/Version_6_0_20210908142400_add_product_web_api_acl_Integration.php

The original migration had mixed results observed in production.
Some environments did not have the new ACLs on all roles.
This was slightly expected, due to unpredictability of the legacy ACL system & its cache.
Worst, when the original migration was run a second time on those broken environments, the ACLs were fixed.
Since it's unthinkable to go "let's execute the migration until it's working", I'm going for a new migration, SQL-only this time.
To compare the results between the migrations, I did this small script to compare the after state of both migrations.
Since I know the original is working locally, with a fresh PIM without cache, I'm quit confident in the results.
```
#/bin/bash
APP_ENV=test make database
APP_ENV=test …
```

CXP-811: Add API ACLs to existing roles in pure SQL

---

config/packages/monolog.yml
config/packages/test/monolog.yml
src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/ProductController.php
src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/ProductModelController.php
src/Akeneo/Pim/Enrichment/Bundle/Resources/config/controllers.yml
src/Akeneo/Tool/Bundle/ApiBundle/tests/integration/ApiTestCase.php
tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/CreateProductEndToEnd.php
tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/DeleteProductEndToEnd.php
tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/GetProductEndToEnd.php
tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/SuccessListProductEndToEnd.php
tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/PartialUpdateListProductEndToEnd.php
tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/PartialUpdateProductEndToEnd.php
tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/CreateProductModelEndToEnd.php
tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/GetProductModelEndToEnd.php
tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/ListOffsetProductModelEndToEnd.php
tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/PartialUpdateListProductModelEndToEnd.php
tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/PartialUpdateProductModelEndToEnd.php

We don't have the guarantee that the recently introduced ACLs are correctly configured on existing roles.
To avoid unwanted access denied errors, we will log instead, to monitor on production environments.

CXP-811: Check ACL on Product external API & log results

---

src/Akeneo/Connectivity/Connection/front/src/connect/components/AppWizard/AppWizard.tsx
src/Akeneo/Connectivity/Connection/workspaces/permission-form/src/component/PermissionFormWidget.test.tsx
src/Akeneo/Connectivity/Connection/workspaces/permission-form/src/component/PermissionFormWidget.tsx
tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/InternalApi/QuantifiedAssociations/AbstractProductModelWithQuantifiedAssociationsTestCase.php

CXP-868: read only mode on form if not granted

---

src/Akeneo/Connectivity/Connection/front/src/connect/components/AppWizard/AppWizard.tsx
src/Akeneo/Connectivity/Connection/workspaces/permission-form/src/component/MultiSelectInputWithDynamicOptions.test.tsx
src/Akeneo/Connectivity/Connection/workspaces/permission-form/src/component/MultiSelectInputWithDynamicOptions.tsx
src/Akeneo/Connectivity/Connection/workspaces/permission-form/src/component/PermissionFormWidget.tsx
src/Akeneo/Connectivity/Connection/workspaces/permission-form/src/index.ts

This is needed for the EE PR : https://github.com/akeneo/pim-enterprise-dev/pull/11764

CXP-842: add support for select2 QueryParamsBuilder

---

CHANGELOG.md
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/bootstrap-datetimepicker/js/bootstrap-datetimepicker.js

PIM-10067: Date value in calendar not set when none is selected

---

src/Akeneo/Pim/Enrichment/Bundle/PdfGeneration/Renderer/ProductPdfRenderer.php
src/Akeneo/Pim/Enrichment/Bundle/PdfGeneration/Renderer/ProductValueRenderer/BooleanProductValueRenderer.php
src/Akeneo/Pim/Enrichment/Bundle/PdfGeneration/Renderer/ProductValueRenderer/DefaultProductValueRenderer.php
src/Akeneo/Pim/Enrichment/Bundle/PdfGeneration/Renderer/ProductValueRenderer/ImageProductValueRenderer.php
src/Akeneo/Pim/Enrichment/Bundle/PdfGeneration/Renderer/ProductValueRenderer/MultiSelectProductValueRenderer.php
src/Akeneo/Pim/Enrichment/Bundle/PdfGeneration/Renderer/ProductValueRenderer/ProductValueRenderer.php
src/Akeneo/Pim/Enrichment/Bundle/PdfGeneration/Renderer/ProductValueRenderer/ProductValueRendererExtension.php
src/Akeneo/Pim/Enrichment/Bundle/PdfGeneration/Renderer/ProductValueRenderer/ProductValueRendererRegistry.php
src/Akeneo/Pim/Enrichment/Bundle/PdfGeneration/Renderer/ProductValueRenderer/SimpleSelectProductValueRenderer.php
src/Akeneo/Pim/Enrichment/Bundle/PdfGeneration/Renderer/ProductValueRenderer/TextareaProductValueRenderer.php
src/Akeneo/Pim/Enrichment/Bundle/Resources/config/renderers.yml
src/Akeneo/Pim/Enrichment/Bundle/Resources/config/twig.yml
src/Akeneo/Pim/Enrichment/Bundle/Resources/views/Product/renderPdf.html.twig
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/CreateAttributeModal.tsx
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/attribute/form/CreateAttributeButtonApp.tsx
tests/back/Pim/Enrichment/Specification/Bundle/PdfGeneration/Renderer/ProductPdfRendererSpec.php
tests/back/Pim/Enrichment/Specification/Bundle/PdfGeneration/Renderer/ProductValueRenderer/BooleanProductValueRendererSpec.php
tests/back/Pim/Enrichment/Specification/Bundle/PdfGeneration/Renderer/ProductValueRenderer/DefaultProductValueRendererSpec.php
tests/back/Pim/Enrichment/Specification/Bundle/PdfGeneration/Renderer/ProductValueRenderer/ImageProductValueRendererSpec.php
tests/back/Pim/Enrichment/Specification/Bundle/PdfGeneration/Renderer/ProductValueRenderer/MultiSelectProductValueRendererSpec.php
tests/back/Pim/Enrichment/Specification/Bundle/PdfGeneration/Renderer/ProductValueRenderer/ProductValueRendererExtensionSpec.php
tests/back/Pim/Enrichment/Specification/Bundle/PdfGeneration/Renderer/ProductValueRenderer/ProductValueRendererRegistrySpec.php
tests/back/Pim/Enrichment/Specification/Bundle/PdfGeneration/Renderer/ProductValueRenderer/SimpleSelectProductValueRendererSpec.php
tests/back/Pim/Enrichment/Specification/Bundle/PdfGeneration/Renderer/ProductValueRenderer/TextareaProductValueRendererSpec.php

The current PDF renderer does not allow any extensibility for another attribute type
So now, we have a Registry to find how to display product values in a PDF.

CPM-357: Refactor PDF renderer

---

src/Akeneo/Connectivity/Connection/front/src/connect/components/AppWizardWithSteps/AppWizardWithSteps.tsx
src/Akeneo/Connectivity/Connection/front/src/connect/components/AppWizardWithSteps/Permissions.tsx

Adds the scroll bar in the form container.
Fixes a glitch about the logo. The logo was not scaled but stretched in the box.
EE: https://github.com/akeneo/pim-enterprise-dev/pull/11801

CXP-746: Be able to choose attribute groups permissions during App activation

---

docker-compose.yml

The latest Minio docker image crashes on our CI

Hotfix: Minio docker image version

---

CHANGELOG.md
src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/contexts/AttributeOptionsContextProvider.tsx

PIM-10078: Add sanity check on DQI attribute option evaluation

---

docker-compose.yml

Hotfix: Minio docker image version (4.0)

---

docker-compose.yml

Hotfix: Minio docker image version (5.0)

---

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/locale-switcher.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/start-copy.js

PLG-531: Track application events to complete the checklist #3 (Localize your catalog for new markets)

---

src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/SettingsIndex.tsx
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/attributes/create-button.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/fields/field.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/properties/translation.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/save-form.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/grid/mass-actions.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/mass-edit/form/family/set-requirements.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/locale-switcher.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/start-copy.js

PLG-532: Track application events to complete the checklist #4 (Get ready to sell on any channel)

---

src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/SettingsIndex.tsx
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/attributes/create-button.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/edit-form.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/fields/field.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/properties/translation.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/save-form.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/grid/mass-actions.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/common/edit/launch.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/common/edit/save.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/product/edit/content.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/product/edit/content/structure/attributes-selector.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/mass-edit/form/family/set-requirements.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/locale-switcher.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/start-copy.js
src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/grid.js

PLG-533: Track application events to complete the checklist #5 (Tailor your exports for your business partners)

---

src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/SettingsIndex.tsx
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/family-variant/form/attribute-set.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/family/form/family-variant.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/attributes/create-button.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/edit-form.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/fields/field.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/properties/translation.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/save-form.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/grid/mass-actions.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/common/edit/launch.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/common/edit/save.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/product/edit/content.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/product/edit/content/structure/attributes-selector.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/mass-edit/form/family/set-requirements.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product-model/form/save.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/locale-switcher.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/start-copy.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/variant-navigation.js
src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/grid.js

PLG-534: Track application events to complete the checklist #6 (Easily model the most complex catalogs)

---

docker-compose.yml
src/Akeneo/Platform/Bundle/InstallerBundle/Event/Subscriber/AssetsInstaller.php

CPM-262: Move table attribute in GE

---

front-packages/shared/src/microfrontend/MicroFrontendDependenciesProvider.tsx
front-packages/shared/src/microfrontend/useNotifications.ts

Microfrontend dependencies were not memoized, which had unintended side effects, such as re-rendering the whole component tree when adding/removing a notification for instance.

RAC: Memoize microfrontend dependencies to prevent unwanted renders

---

src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Controller/InternalApi/GetAllConnectedAppsAction.php

removed semicolon

---

src/Akeneo/Connectivity/Connection/front/src/connect/components/AppWizardWithSteps/PermissionsSummary.tsx
src/Akeneo/Connectivity/Connection/workspaces/permission-form/src/component/MultiSelectInputWithDynamicOptions.test.tsx
src/Akeneo/Connectivity/Connection/workspaces/permission-form/src/component/MultiSelectInputWithDynamicOptions.tsx

https://github.com/akeneo/pim-enterprise-dev/pull/11827

CXP-880: make the summary scrollable

---

src/Akeneo/UserManagement/Component/Model/Group.php
src/Akeneo/UserManagement/Component/Model/GroupInterface.php
tests/back/UserManagement/Specification/Component/Model/GroupSpec.php

see https://github.com/akeneo/pim-enterprise-dev/pull/11846

CXP-841: Category Permissions Saver

---

front-packages/akeneo-design-system/README.md

- Use introduction from Notion design system: https://www.notion.so/akeneo/DSM-Introduction-87947631b1e84c5d827021f9f3ee0bf2
- Quick fix english

DSM: Improve DSM homepage

---

src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Product/GetAssociatedProductCodesByProductFromDB.php

Fix coding style after upgrade of friendsofphp/php-cs-fixer

---

src/Akeneo/Connectivity/Connection/back/Application/Apps/Command/CreateAppWithAuthorizationHandler.php
src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/Command/CreateAppWithAuthorizationHandlerIntegration.php
src/Akeneo/UserManagement/Component/Model/User.php

When creating a App dedicated user:
Updated first and last name to use App name

CXP-750 Changed app user first and last name

---

src/Akeneo/Connectivity/Connection/back/tests/Integration/Persistence/Elasticsearch/Query/PurgeEventsApiSuccessLogsQueryIntegration.php

In the test, there is no guarantee that ES will index the documents in the correct order and that we retain 4 of each type (notice & info)

Fix a random test using ES

---

tests/legacy/features/pim/enrichment/product/pef/edit_product.feature

Sometimes the wrong field was updated in this test because the PEF was not fully loaded yet when updating the field:

Fix unstable legacy behat

---

CHANGELOG-5.0.md
src/Akeneo/Channel/Bundle/Doctrine/Remover/ChannelRemover.php
src/Akeneo/Channel/Bundle/Query/Sql/IsChannelUsedInProductProductExportJob.php
src/Akeneo/Channel/Bundle/Resources/config/queries.yml
src/Akeneo/Channel/Bundle/Resources/config/services.yml
src/Akeneo/Channel/Bundle/Resources/translations/messages.en_US.yml
src/Akeneo/Channel/Component/Query/IsChannelUsedInProductExportJobInterface.php
tests/back/Channel/Integration/Channel/Query/Sql/IsChannelUsedInProductProductExportJobIntegration.php
tests/back/Channel/Specification/Bundle/Doctrine/Remover/ChannelRemoverSpec.php
tests/legacy/features/channel/delete_channel.feature

Backport #14122 into 5.0. I had to refacto a little bit to avoid BC breaks, so we will have to make sure we keep the master version during the next pull-up

PIM-10131: [Backport PIM-9740]: Prevent to delete a channel used in a product export job

---

CHANGELOG.md

PIM-10139: Fix missing translation key in Italian locale with "change family" mass action

---

CHANGELOG-5.0.md
src/Akeneo/Channel/Bundle/Resources/config/queries.yml
tests/back/Channel/Integration/Channel/Query/Sql/IsChannelUsedInProductProductExportJobIntegration.php
tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/ExternalApi/PartialUpdateVariantToSimpleEndToEnd.php

- Backport of https://github.com/akeneo/pim-community-dev/pull/15472  
- prevent deletion of a channel used in a published product export

PIM-10133 - PIM-10134: Prevent deletion of a channel used in a published product/shared catalog export job

---

tests/legacy/features/pim/enrichment/product/mass-edit/edit-common-attribute/edit_common_localized_attributes.feature

These tests used to be flaky, but it seems #15568 fixed them (executed 100 times in a row on a local environment)

CPM-399: Unskip formerly flaky tests

---

CHANGELOG.md
src/Akeneo/UserManagement/Bundle/Controller/ResetController.php

PIM-10145: fix template twig name on reset password page

---

CHANGELOG-5.0.md
src/Akeneo/Pim/Enrichment/Bundle/Resources/config/event_subscribers.yml
tests/back/Pim/Enrichment/Integration/Category/ConfigureCategoryTreeForExportJobsAfterChangingTheChannelCategoryTreeIntegration.php

PIM-10132: Update SC export profile when the channel's category is changed

---

src/Akeneo/Connectivity/Connection/front/src/connect/components/AuthorizeClientError.tsx

CXP-937: Missing translation on the Authorize screen

---

front-packages/akeneo-design-system/yarn.lock
yarn.lock

See: https://github.com/akeneo/pim-enterprise-dev/pull/12256

 RAC: Upgrade @types/styled-components to resolve tria build error 

---

.prettierignore
front-packages/akeneo-design-system/src/components/Input/TextAreaInput/RichTextEditor.tsx
front-packages/akeneo-design-system/yarn.lock
src/Akeneo/Connectivity/Connection/front/src/settings/use-image-uploader.ts
src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptionTable.tsx
src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/legacy-bridge/src/bridge/react/reactView.ts
src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filters-column.ts
tests/front/unit/structure/attribute-option/components/NewOptionPlaceholder.unit.tsx
yarn.lock

RAC-977: upgrade frontend dependencies

---

config/services/test/test_services.yml
config/services/test_fake/services.yml
src/Akeneo/Platform/Job/back/Application/SearchJobExecution/SearchJobExecutionQuery.php
src/Akeneo/Platform/Job/back/Domain/Query/FindJobTypesInterface.php
src/Akeneo/Platform/Job/back/Infrastructure/Controller/GetJobTypesAction.php
src/Akeneo/Platform/Job/back/Infrastructure/Controller/IndexAction.php
src/Akeneo/Platform/Job/back/Infrastructure/Query/CountJobExecution.php
src/Akeneo/Platform/Job/back/Infrastructure/Query/FindJobTypes.php
src/Akeneo/Platform/Job/back/Infrastructure/Query/SearchJobExecution.php
src/Akeneo/Platform/Job/back/Infrastructure/Registry/NotVisibleJobsRegistry.php
src/Akeneo/Platform/Job/back/Infrastructure/Symfony/DependencyInjection/AkeneoJobExtension.php
src/Akeneo/Platform/Job/back/Infrastructure/Symfony/Resources/config/controllers.yml
src/Akeneo/Platform/Job/back/Infrastructure/Symfony/Resources/config/queries.yml
src/Akeneo/Platform/Job/back/Infrastructure/Symfony/Resources/config/registries.yml
src/Akeneo/Platform/Job/back/Infrastructure/Symfony/Resources/config/routing.yml
src/Akeneo/Platform/Job/back/tests/Integration/FakeServices/Job.php
src/Akeneo/Platform/Job/back/tests/Integration/Infrastructure/Controller/GetJobTypesActionTest.php
src/Akeneo/Platform/Job/back/tests/Integration/Infrastructure/Query/CountJobExecutionTest.php
src/Akeneo/Platform/Job/back/tests/Integration/Infrastructure/Query/FindJobTypesTest.php
src/Akeneo/Platform/Job/back/tests/Integration/Infrastructure/Query/SearchJobExecutionTest.php
src/Akeneo/Platform/Job/back/tests/Integration/Infrastructure/Registry/NotVisibleJobsRegistryTest.php
src/Akeneo/Platform/Job/back/tests/Integration/Loader/FixturesLoader.php
src/Akeneo/Platform/Job/back/tests/Integration/Resources/config/services.yml

- Add a controller to fetch job types (only job types of visible jobs in database are fetched)
- Handle "type" filter in SearchJobExecution

RAC-955: Add endpoint to fetch job types + filter job by type

---

front-packages/akeneo-design-system/src/components/Input/SelectInput/SelectInput.tsx
front-packages/akeneo-design-system/src/components/Input/SelectInput/SelectInput.unit.tsx
front-packages/akeneo-design-system/src/components/Input/TableInput/TableInputRow/TableInputRow.tsx
front-packages/akeneo-design-system/src/components/Input/TableInput/TableInputSelect/TableInputSelect.tsx
front-packages/akeneo-design-system/src/shared/key.ts

These PRs disappears during one of our rebase, I put them back

CPM-306 - Fix deleted old PRs

---

src/Akeneo/Platform/Job/back/Application/SearchJobExecution/SearchJobExecutionQuery.php
src/Akeneo/Platform/Job/back/Infrastructure/Controller/IndexAction.php
src/Akeneo/Platform/Job/back/Infrastructure/Query/SearchJobExecution.php
src/Akeneo/Platform/Job/back/tests/Acceptance/Application/SearchJobExecution/SearchJobExecutionHandlerTest.php
src/Akeneo/Platform/Job/back/tests/Integration/Infrastructure/Controller/IndexActionTest.php
src/Akeneo/Platform/Job/back/tests/Integration/Infrastructure/Query/SearchJobExecutionTest.php
src/Akeneo/Platform/Job/front/process-tracker/src/feature/pages/JobExecutionList.tsx

RAC-958: Add job status filter in query

---

.circleci/config.yml

The deployment job was failing because of the changing source from github to GCP bucket
The modification done in the EE was not applied in the CE for too long...
Resynch the deployment process from the EE to the CE

BH-871 - Use the same deployment process in the CE and EE

---

src/Akeneo/Pim/Enrichment/Component/Product/Completeness/MissingRequiredAttributesCalculator.php
src/Akeneo/Pim/Enrichment/Component/Product/Completeness/MissingRequiredAttributesCalculatorInterface.php
src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/ProductModelNormalizer.php
src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/ProductNormalizer.php
tests/back/Pim/Enrichment/Integration/Completeness/AbstractCompletenessTestCase.php
tests/back/Pim/Enrichment/Specification/Component/Product/Completeness/MissingRequiredAttributesCalculatorSpec.php

Backport from (#15259)
See https://akeneo.atlassian.net/browse/PIM-10059 to have a full description of the bug.

PIM-10150: Fix completeness display when user does not have permission on attribute group(s)

---

src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/requirejs.yml
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/routing.yml
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApp/ConnectedAppContainer.tsx
src/Akeneo/Connectivity/Connection/front/src/connect/hooks/use-delete-app.ts
src/Akeneo/Connectivity/Connection/front/src/connect/pages/ConnectedAppDeletePage.tsx
src/Akeneo/Connectivity/Connection/front/src/infrastructure/ConnectedApps.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/connect/hooks/use-delete-app.test.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/connect/pages/ConnectedAppDeletePage.test.tsx
src/Akeneo/Connectivity/Connection/workspaces/permission-form/src/registry/PermissionFormRegistry.ts

CXP-966: Add button & modal for deleting an App

---

src/Akeneo/UserManagement/Bundle/Resources/config/model/doctrine/Group.orm.yml
src/Akeneo/UserManagement/Component/Model/Group.php
src/Akeneo/UserManagement/Component/Model/GroupInterface.php
tests/back/UserManagement/Specification/Component/Model/GroupSpec.php
upgrades/schema/Version_6_0_20211115143942_add_user_group_type_column.php
upgrades/test_schema/Version_6_0_20211115143942_add_user_group_type_column_Integration.php

CXP-751: Add type to the user Group entity

---

.circleci/find_non_executed_phpspec.sh
src/Akeneo/Pim/Structure/Bundle/Resources/config/queries.yml

Adds missing service declaration as well as spec check on a the new EE components/ directory (to come).

BH-651 Tailored Export to GRTH fixes

---

src/Akeneo/Platform/Job/back/Infrastructure/Query/SearchJobExecution.php
src/Akeneo/Platform/Job/back/tests/Integration/Infrastructure/Query/SearchJobExecutionTest.php
src/Akeneo/Platform/Job/front/process-tracker/src/feature/components/JobExecutionList/JobExecutionTable.tsx

Remove sorting from warnings column in front and back.
See https://github.com/akeneo/pim-community-dev/pull/15695#discussion_r749256282

RAC-1033: Remove sorting on warnings column

---

src/Akeneo/Platform/Job/back/Infrastructure/Controller/IndexAction.php
src/Akeneo/Platform/Job/back/Infrastructure/Query/SearchJobExecution.php
src/Akeneo/Platform/Job/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
src/Akeneo/Platform/Job/back/tests/Integration/Infrastructure/Query/SearchJobExecutionTest.php
src/Akeneo/Platform/Job/front/process-tracker/src/feature/components/JobExecutionList/JobExecutionTable.test.tsx
src/Akeneo/Platform/Job/front/process-tracker/src/feature/components/JobExecutionList/JobExecutionTable.tsx
src/Akeneo/Platform/Job/front/process-tracker/src/feature/hooks/useJobExecutionTable.ts
src/Akeneo/Platform/Job/front/process-tracker/src/feature/models/JobExecutionFilter.test.ts
src/Akeneo/Platform/Job/front/process-tracker/src/feature/models/JobExecutionFilter.ts
src/Akeneo/Platform/Job/front/process-tracker/src/feature/pages/JobExecutionList.test.tsx
src/Akeneo/Platform/Job/front/process-tracker/src/feature/pages/JobExecutionList.tsx

Make job execution table columns sortable.

RAC-1028: Job execution sort [front]

---

front-packages/akeneo-design-system/src/components/Tiles/Tiles.tsx
front-packages/akeneo-design-system/src/components/Tiles/Tiles.unit.tsx

CPM-366: Allow tab and enter navigation on Tiles DSM Component

---

tests/legacy/features/pim/enrichment/product/export/export_products_by_text.feature

Skip random test
For example here is a failing CI: https://app.circleci.com/pipelines/github/akeneo/pim-community-dev/28450/workflows/c7843336-96e2-4da3-ac6e-3c4ca2d0d860/jobs/131352

Skip export_products_by_text.feature

---

front-packages/akeneo-design-system/src/components/Modal/Modal.stories.mdx
front-packages/akeneo-design-system/src/components/Modal/Modal.tsx
front-packages/akeneo-design-system/src/components/Modal/Modal.unit.tsx
src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/CreateAttributeModal.tsx

We Add a new Container for top left buttons inside Modal component

CPM-422:Add TopLeftButton in modal DSM

---

src/Akeneo/Platform/Job/front/process-tracker/src/feature/components/JobExecutionList/JobExecutionTable.test.tsx
src/Akeneo/Platform/Job/front/process-tracker/src/feature/components/JobExecutionList/JobExecutionTable.tsx

RAC-1030: disable click on table row when user doesn't have ACL

---

src/Akeneo/Platform/Job/front/process-tracker/src/feature/components/JobExecutionList/JobExecutionTable.test.tsx
src/Akeneo/Platform/Job/front/process-tracker/src/feature/components/JobExecutionList/JobExecutionTable.tsx
src/Akeneo/Platform/Job/front/process-tracker/src/feature/hooks/useJobExecutionTable.test.ts
src/Akeneo/Platform/Job/front/process-tracker/src/feature/hooks/useJobExecutionTable.ts
src/Akeneo/Platform/Job/front/process-tracker/src/feature/models/JobExecutionTable.test.ts
src/Akeneo/Platform/Job/front/process-tracker/src/feature/models/JobExecutionTable.ts
src/Akeneo/Platform/Job/front/process-tracker/src/feature/pages/JobExecutionList.test.tsx
src/Akeneo/Platform/Job/front/process-tracker/src/feature/pages/JobExecutionList.tsx

RAC-1047: Add stop button on front

---

src/Akeneo/Platform/Job/back/Infrastructure/Query/SearchJobExecution.php
src/Akeneo/Platform/Job/back/Infrastructure/Symfony/Resources/config/queries.yml
src/Akeneo/Platform/Job/back/tests/Acceptance/FakeServices/InMemorySearchJobExecution.php
src/Akeneo/Platform/Job/back/tests/Integration/Infrastructure/Query/SearchJobExecutionTest.php

* The blacklisted job executions do not appear in the process tracker
* The count of job execution does not take the blacklisted job name into account

RAC-993: Remove not visible job

---

src/Akeneo/Platform/Job/back/Infrastructure/Symfony/Resources/config/test/services.yml
src/Akeneo/Platform/Job/back/tests/Integration/ControllerIntegrationTestCase.php
src/Akeneo/Platform/Job/back/tests/Integration/Infrastructure/Controller/GetJobTypesActionTest.php
src/Akeneo/Platform/Job/back/tests/Integration/Infrastructure/Controller/IndexActionTest.php
src/Akeneo/Platform/Job/back/tests/Integration/Infrastructure/Query/CountJobExecutionTest.php
src/Akeneo/Platform/Job/back/tests/Integration/Infrastructure/Query/FindJobTypesTest.php
src/Akeneo/Platform/Job/back/tests/Integration/Infrastructure/Query/SearchJobExecutionTest.php
src/Akeneo/Platform/Job/back/tests/Integration/IntegrationTestCase.php
src/Akeneo/Platform/Job/back/tests/Integration/Loader/FixturesJobHelper.php
src/Akeneo/Platform/Job/back/tests/Integration/Loader/FixturesLoader.php
src/Akeneo/Platform/Job/back/tests/Integration/Loader/FixturesUserHelper.php

In this PR we reworked the loading of fixture in job bundle : 
- We splitted the JobLoader => now we have a job loader fixture and a job loader helper.
- We added the role and user management because we are going to need her to check permission. Now we have 3 personna : 
- Peter : Can see the job of all users, can see the process tracker and the job executions
- Mary: Can see process tracker and the job executions
- Betty: cannot see process tracker and the job executions

RAC-Rework-ACL: Improve tests fixtures

---

src/Akeneo/Platform/Job/back/Infrastructure/Controller/GetJobTypesAction.php
src/Akeneo/Platform/Job/back/Infrastructure/Controller/IndexAction.php
src/Akeneo/Platform/Job/back/Infrastructure/Symfony/Resources/config/controllers.yml
src/Akeneo/Platform/Job/back/tests/Integration/Infrastructure/Controller/GetJobTypesActionTest.php
src/Akeneo/Platform/Job/back/tests/Integration/Infrastructure/Controller/IndexActionTest.php

RAC-1064: Add ACL on process tracker controller

---

src/Akeneo/Platform/Job/back/Application/SearchJobExecution/SearchJobExecutionQuery.php
src/Akeneo/Platform/Job/back/Domain/Query/FindJobUsersInterface.php
src/Akeneo/Platform/Job/back/Infrastructure/Controller/GetJobTypesAction.php
src/Akeneo/Platform/Job/back/Infrastructure/Controller/GetJobUsersAction.php
src/Akeneo/Platform/Job/back/Infrastructure/Controller/IndexAction.php
src/Akeneo/Platform/Job/back/Infrastructure/Query/FindJobTypes.php
src/Akeneo/Platform/Job/back/Infrastructure/Query/FindJobUsers.php
src/Akeneo/Platform/Job/back/Infrastructure/Query/SearchJobExecution.php
src/Akeneo/Platform/Job/back/Infrastructure/Symfony/Resources/config/controllers.yml
src/Akeneo/Platform/Job/back/Infrastructure/Symfony/Resources/config/queries.yml
src/Akeneo/Platform/Job/back/Infrastructure/Symfony/Resources/config/routing.yml
src/Akeneo/Platform/Job/back/tests/Integration/Infrastructure/Controller/GetJobTypesActionTest.php
src/Akeneo/Platform/Job/back/tests/Integration/Infrastructure/Controller/GetJobUsersActionTest.php
src/Akeneo/Platform/Job/back/tests/Integration/Infrastructure/Controller/IndexActionTest.php
src/Akeneo/Platform/Job/back/tests/Integration/Infrastructure/Query/CountJobExecutionTest.php
src/Akeneo/Platform/Job/back/tests/Integration/Infrastructure/Query/FindJobUsersTest.php
src/Akeneo/Platform/Job/back/tests/Integration/Loader/FixturesLoader.php

RAC-989: Revamp user filter (back)

---

CHANGELOG-5.0.md
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/bootstrap/js/bootstrap.js

[PULLUP] 5.0 to master

---

CHANGELOG.md
src/Akeneo/UserManagement/Bundle/Resources/views/Group/update.html.twig

Prefix breadcrumb groups link with a # char.

PIM-10163: Prefix groups breadcrumb link to avoid 404

---

src/Akeneo/Platform/Job/back/Infrastructure/Query/SearchJobExecution.php
src/Akeneo/Platform/Job/back/tests/Integration/Loader/FixturesJobHelper.php
src/Akeneo/Tool/Bundle/BatchBundle/Job/DoctrineJobRepository.php
src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/model/doctrine/JobExecution.orm.yml
src/Akeneo/Tool/Component/Batch/Model/JobExecution.php
src/Akeneo/Tool/Component/Batch/spec/Model/JobExecutionSpec.php
tests/back/Tool/Integration/Batch/Command/BatchCommandIntegration.php
upgrades/schema/Version_6_0_20211122154203_add_step_count_in_job_execution.php
upgrades/test_schema/Version_6_0_20211122154203_add_step_count_in_job_execution_Integration.php

RAC-1042: Add step count in job execution table

---

CHANGELOG.md
src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/FlatToStandard/ColumnsMerger.php
src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/translations/messages.en_US.yml
tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/FlatToStandard/ColumnsMergerSpec.php

Throw an exception when the value of price attribute is interpreted as DateTime in import.

PIM-10167: Import file - datetime in price attribute break the import

---

src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml

Update description and confirmation messages in bulk action edit popin.

CPM-418 update the description in the bulk edit popin + confirmation

---

CHANGELOG.md
src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/components/Widgets/LastOperationsWidget.tsx
src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/domain/operation.ts

https://akeneo.atlassian.net/browse/PIM-10177?atlOrigin=eyJpIjoiYmQ3NWI1NmFhMjY2NDc5Yzg0YjYyNmRiYmYwYjk0ZDYiLCJwIjoiaiJ9
Use tracking data to choose the badge level.

PIM-10177: Fix warning level for status badge on last operations

---

tests/legacy/features/pim/enrichment/product/mass-edit/edit-common-attribute/edit_common_attributes.feature

Thanks to #15786, this test should not be unstable anymore

Unskip formerly flaky test

---

src/Akeneo/Pim/Structure/Bundle/Resources/config/services.yml
src/Akeneo/Pim/Structure/Component/Security/AssociationTypeScopeMapper.php
tests/back/Pim/Structure/Specification/Component/Security/AssociationTypeScopeMapperSpec.php

CXP-947: Create a Scope provider for AssociationType

---

src/Akeneo/Pim/Structure/Bundle/Resources/config/services.yml
src/Akeneo/Pim/Structure/Component/Security/AttributeOptionsScopeMapper.php
tests/back/Pim/Structure/Specification/Component/Security/AttributeOptionsScopeMapperSpec.php

CXP-944: Create a Scope provider for Attribute Options

---

src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Security/ScopeMapperInterface.php
src/Akeneo/Pim/Structure/Bundle/Resources/config/services.yml
src/Akeneo/Pim/Structure/Component/Security/CatalogStructureScopeMapper.php
tests/back/Pim/Structure/Specification/Component/Security/CatalogStructureScopeMapperSpec.php

CXP-943: Add catalog structure Scope Mapper

---

src/Akeneo/Pim/Enrichment/Bundle/DependencyInjection/AkeneoPimEnrichmentExtension.php
src/Akeneo/Pim/Enrichment/Bundle/Resources/config/scope_mappers.yml
src/Akeneo/Pim/Enrichment/Component/Product/Security/ProductScopeMapper.php
tests/back/Pim/Enrichment/Specification/Component/Product/Security/ProductScopeMapperSpec.php

CXP-948: Add Product Scope Mapper

---

.circleci/config.yml
Dockerfile
composer.json
composer.lock
docker-compose.yml
docker/cypress/Dockerfile
src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Model/Write/CriterionEvaluation.php
src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Domain/Model/Write/CriterionEvaluationSpec.php
src/Akeneo/Pim/Enrichment/Component/Product/Validator/ConstraintGuesser/FileGuesser.php
src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/NotDecimalValidator.php
src/Akeneo/Pim/Structure/Component/Validator/Constraints/NotDecimalValidator.php
src/Akeneo/Tool/Component/Batch/Job/ExitStatus.php
src/Akeneo/Tool/Component/Batch/Step/ItemStep.php
src/Akeneo/Tool/Component/Batch/spec/Job/ExitStatusSpec.php
src/Akeneo/Tool/Component/Batch/spec/Model/JobExecutionSpec.php
src/Akeneo/Tool/Component/Batch/spec/Model/StepExecutionSpec.php
src/Akeneo/Tool/Component/Batch/spec/Step/ItemStepSpec.php
src/Akeneo/Tool/Component/Localization/Validator/Constraints/DateFormatValidator.php
src/Oro/Bundle/PimDataGridBundle/Normalizer/FamilyVariantNormalizer.php
tests/legacy/features/pim/enrichment/product/validation/validate_localized_price_attributes.feature
tests/legacy/features/pim/enrichment/product/validation/validate_price_attributes.feature

BH-859: Use PHP 8.0

---

front-packages/akeneo-design-system/src/components/Dropdown/Dropdown.tsx
front-packages/akeneo-design-system/src/components/Dropdown/ItemCollection/ItemCollection.tsx
src/Akeneo/Platform/Job/back/Infrastructure/Installer/JobInstaller.php
src/Akeneo/Platform/Job/back/tests/.php_cd.php
src/Akeneo/Platform/Job/front/process-tracker/src/feature/components/JobExecutionList/JobExecutionTable.test.tsx
src/Akeneo/Platform/Job/front/process-tracker/src/feature/components/JobExecutionList/JobExecutionTable.tsx
src/Akeneo/Platform/Job/front/process-tracker/src/feature/pages/JobExecutionList.test.tsx
upgrades/schema/Version_6_0_20211124163100_add_index_to_improve_search_on_job_execution.php
upgrades/test_schema/Version_6_0_20211124163100_add_index_to_improve_search_on_job_execution_Integration.php

In this PR: 
- I fixed CI that does not pass 
- I added a role into the component Dropdown.ItemCollection in order to getByText only on the dropdown (else the translation key is present twice in the screen (in the table and in the filter))
- I temporary removed started_time_idx because doctrine throw an exception on index function

RAC: Fix CI on process tracker feature branch

---

.circleci/config.yml

Switch from Scheduled workflow to Scheduled pipelines. It will allow us to use dynamic config from Circle CI (and to split the config in different files).
See https://discuss.circleci.com/t/scheduled-pipelines-are-here/41684 for the announcement of scheduled pipelines.
See for the doc https://github.com/CircleCI-Public/api-preview-docs/blob/master/docs/scheduled-pipelines.md
I discovered the UI is ready to configure scheduled pipelines.
See https://app.circleci.com/settings/project/github/akeneo/pim-community-dev/triggers

TIP-1546: configure schedule pipelines for existing workflow

---

src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/front/src/feature/hooks/useCatalogVolumeByAxis.test.ts

PLG-646: Add hook test

---

src/Akeneo/Connectivity/Connection/front/src/connect/components/AppWizardWithSteps/Permissions.tsx
src/Akeneo/Connectivity/Connection/front/src/connect/components/AppWizardWithSteps/PermissionsSummary.tsx
src/Akeneo/Connectivity/Connection/front/src/connect/components/MarketplaceIsLoading.tsx
src/Akeneo/Connectivity/Connection/front/src/connect/components/PermissionsForm.tsx
src/Akeneo/Connectivity/Connection/workspaces/permission-form/src/component/PermissionFormWidget.tsx

1. Marketplace Skeleton :
The loading skeleton is now aligned with the loaded version.
2. Wizard permissions :
The container height is 545px to highlight the next section.
3. Manage Connected Apps permissions :
The FormContainer max-width is set to 460px.

CXP-967 Polish Marketplace & Activate UI

---

src/Akeneo/Platform/Job/front/process-tracker/src/feature/components/JobExecutionList/JobExecutionSearchBar.tsx
src/Akeneo/Platform/Job/front/process-tracker/src/feature/hooks/useStoredJobExecutionFilter.test.ts
src/Akeneo/Platform/Job/front/process-tracker/src/feature/hooks/useStoredJobExecutionFilter.ts
src/Akeneo/Platform/Job/front/process-tracker/src/feature/pages/JobExecutionList.tsx

To avoid blank page due to a error occurred when a new filter is not in local stored filter value, we need to merge default filter value with stored filter value.

RAC-1096: Merge filter default value and local stored value

---

bin/check-services-instantiability

Fixes constraints handling by service insatiability checker.

BH-651 Fixes constraints handling by service insantiability checker

---

src/Akeneo/Pim/Structure/Bundle/Resources/config/queries.yml

Remove hotfix done here https://github.com/akeneo/pim-community-dev/pull/15793

CPM-331: remove table attribute from default

---

.circleci/config.yml

BH-924 - Split deploy and commit instance

---

src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApps/ConnectedAppCard.tsx
src/Akeneo/Connectivity/Connection/front/src/connect/hooks/use-connected-apps.ts
src/Akeneo/Connectivity/Connection/front/src/connect/hooks/use-fetch-apps.ts
src/Akeneo/Connectivity/Connection/front/src/connect/pages/ConnectedAppsListPage.tsx
src/Akeneo/Connectivity/Connection/front/src/model/Apps/connected-app.ts
src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApps/ConnectedAppsCard.test.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/connect/hooks/use-connected-apps.test.ts

CXP-1013 DO NOT MERGE

---

.circleci/config.yml

BH-758 - readd test_database

---

src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
src/Akeneo/Connectivity/Connection/front/src/connect/components/ScopeList.tsx

CXP-914: Add new scopes for AssetManager & Reference Entities

---

src/Akeneo/Connectivity/Connection/back/Application/Apps/Command/RequestAppAuthorizationCommand.php
src/Akeneo/Connectivity/Connection/back/Application/Apps/Command/RequestAppAuthorizationHandler.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Controller/AuthorizeAction.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/apps.yml
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/validation/RequestAppAuthorizationCommand.yml
src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Apps/AuthorizeEndToEnd.php
src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/Session/AppAuthorizationSessionIntegration.php
src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Apps/Session/AppAuthorizationSessionSpec.php

CXP-983: Ignores redirect_uri in Authorize request, uses Callback url from the marketplace

---

CHANGELOG.md
src/Akeneo/Pim/Enrichment/Bundle/Command/IndexProductCommand.php
src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Indexer/ProductAndAncestorsIndexer.php
src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Indexer/ProductIndexer.php
src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Indexer/ProductModelDescendantsAndAncestorsIndexer.php
src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Indexer/ProductModelIndexer.php
src/Akeneo/Pim/Enrichment/Bundle/Resources/config/factories.yml
src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ElasticsearchProjection/GetElasticsearchProductModelProjection.php
src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ElasticsearchProjection/GetElasticsearchProductProjection.php
src/Akeneo/Pim/Enrichment/Component/Product/Factory/NonExistentValuesFilter/ChainedNonExistentValuesFilter.php
tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Indexer/ProductIndexerSpec.php
tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Indexer/ProductModelIndexerSpec.php
tests/back/Pim/Enrichment/Specification/Component/Product/Factory/EmptyValuesCleanerSpec.php
tests/back/Pim/Enrichment/Specification/Component/Product/Factory/NonExistentValuesFilter/ChainedNonExistentValuesFilterSpec.php

Decrease the batch size during product/model indexation in order to mitigate the risk of getting a memory overflow when the batch has a lot of "big" values, plus some minor improvements

PIM-10155: Decrease batch size during indexation of products and product models

---

.circleci/find_non_executed_phpspec.sh

Fixes wrong sorting for list of classes.

BH-651 Fixes component path

---

.circleci/config.yml
front-packages/shared/src/components/Navigation/SubNavigation.tsx
src/Akeneo/Channel/.php_cd.php
src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/Persistence/DbalConnectedAppRepositoryIntegration.php
src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/AppWizard/AppWizard.test.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/AppWizardWithSteps/AppWizardWithSteps.test.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/AppWizardWithSteps/Authorizations.test.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApp/ConnectedAppContainer.test.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApp/ConnectedAppSettings.test.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApps/ConnectedAppsCard.test.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApps/ConnectedAppsContainer.test.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApps/ConnectedAppsContainerHelper.test.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApps/NoConnectedApps.test.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/PermissionsForm.test.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/connect/pages/AppAuthorizePage.test.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/connect/pages/ConnectedAppPage.test.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/connect/pages/ConnectedAppsListPage.test.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/settings/pages/EditConnection.test.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/settings/pages/ListConnections.test.tsx
src/Akeneo/Connectivity/Connection/tests/Context/AppActivateContext.php
src/Akeneo/Pim/Enrichment/.php_cd.php
src/Akeneo/Pim/Structure/.php_cd.php
upgrades/schema/Version_6_0_20210917103700_add_user_group_default_permissions.php

CXP-1011: Prepare activate-feature-branch for merge in master

---

src/Akeneo/Platform/Job/front/process-tracker/src/feature/components/JobExecutionList/JobExecutionTable.tsx
src/Akeneo/Platform/Job/front/process-tracker/src/feature/components/LastExecutionTable.tsx
src/Akeneo/Platform/Job/front/process-tracker/src/feature/components/common/ProgressCell.test.tsx
src/Akeneo/Platform/Job/front/process-tracker/src/feature/hooks/useJobExecutionTable.test.ts
src/Akeneo/Platform/Job/front/process-tracker/src/feature/hooks/useJobExecutionTable.ts

- Hide progress cell
- Disable autorefresh

RAC-916: Hide progress cell & disable autorefresh

---

CHANGELOG.md
config/packages/liip_imagine.yml
src/Akeneo/Platform/Bundle/UIBundle/Imagine/IccStripFilter.php
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/services.yml

See full description in https://github.com/akeneo/pim-enterprise-dev/pull/12298. (The fix in Asset Manager was extended for all thumbnails)

PIM-10199: Fix occasional segmentation fault when generating thumbnails

---

src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/OAuth/CreateAccessToken.php

Return all scopes, but persist only authorization ones in pim_api_access_token table

---

src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Controller/AuthorizeAction.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Controller/ConfirmAuthenticationAction.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/controllers.yml
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/requirejs.yml
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/routing.yml
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/routing/apps.yml
src/Akeneo/Connectivity/Connection/front/src/connect/components/AppWizard/AuthenticationModal.tsx
src/Akeneo/Connectivity/Connection/front/src/connect/components/AppWizard/steps/Authentication/Authentication.tsx
src/Akeneo/Connectivity/Connection/front/src/connect/components/AppWizard/steps/Authentication/ConsentList.tsx
src/Akeneo/Connectivity/Connection/front/src/connect/hooks/use-confirm-authentication.ts
src/Akeneo/Connectivity/Connection/front/src/connect/hooks/use-fetch-app-wizard-data.ts
src/Akeneo/Connectivity/Connection/front/src/connect/pages/AppAuthenticatePage.tsx
src/Akeneo/Connectivity/Connection/front/src/infrastructure/Apps.tsx
src/Akeneo/Connectivity/Connection/front/src/model/Apps/wizard-data.ts

Cxp 1028 standalone consent

---

src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/OAuth/CreateAccessToken.php

increase readibility of the id_token footprint

---

src/Akeneo/Connectivity/Connection/tests/features/activate_an_app.feature

see https://github.com/akeneo/yell-extension/pull/10

fix activate behat

---

src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/OAuth/AuthorizationCodeGenerator.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/OAuth/AuthorizationCodeGeneratorInterface.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/OAuth/CreateAccessToken.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/OAuth/RedirectUriWithAuthorizationCodeGenerator.php

Do not add scopes to autorization code table

---

tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/SuccessListProductEndToEnd.php

Add an e2e test to check the particular use case fixed in #15880 

PIM-10194: Add e2e API test with uppercase identifier

---

src/Akeneo/Connectivity/Connection/back/Application/Apps/Command/RequestAppAuthenticationCommand.php
src/Akeneo/Connectivity/Connection/back/Application/Apps/Command/RequestAppAuthenticationHandler.php
src/Akeneo/Connectivity/Connection/back/Domain/Apps/Exception/UserConsentRequiredException.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Controller/AuthorizeAction.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/apps.yml
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/controllers.yml
src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Apps/OAuth/AuthorizationCodeGeneratorSpec.php
src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Apps/OAuth/CreateAccessTokenSpec.php
src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Apps/OAuth/RedirectUriWithAuthorizationCodeGeneratorSpec.php

- Keep user consented scopes in sync with what the app request
- Fixed phpspec after the removal of the scope in the AuthCode object

CXP-989: Sync user consent

---

src/Akeneo/Connectivity/Connection/back/Domain/Apps/DTO/AppAuthenticationUser.php
src/Akeneo/Connectivity/Connection/back/Domain/Apps/Persistence/Query/GetUserConsentedAuthenticationUuidQueryInterface.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Persistence/Query/GetUserConsentedAuthenticationUuidQuery.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Security/AppAuthenticationUserProvider.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/apps.yml
src/Akeneo/Connectivity/Connection/back/tests/CatalogBuilder/Resources/config/loaders.yml
src/Akeneo/Connectivity/Connection/back/tests/CatalogBuilder/UserConsentLoader.php
src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/Persistence/Query/GetUserConsentedAuthenticationUuidQueryIntegration.php

CXP-1029: Use PPID from the user_consent table to build the JWToken

---

src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Controller/InternalApi/GetConnectedAppMonitoringSettingsAction.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Apps/InternalApi/GetConnectedAppMonitoringSettingsActionEndToEnd.php
src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApp/ConnectedAppContainer.tsx
src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApp/ErrorMonitoring/ConnectedAppErrorMonitoring.tsx
src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApp/ErrorMonitoring/ErrorMonitoringError.tsx
src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApp/ErrorMonitoring/NotAuditableConnectedApp.tsx
src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApp/ErrorMonitoring/NotDataSourceConnectedApp.tsx
src/Akeneo/Connectivity/Connection/front/src/error-management/components/ConnectionErrors.tsx
src/Akeneo/Connectivity/Connection/front/src/error-management/components/ErrorsHelper.tsx
src/Akeneo/Connectivity/Connection/front/src/error-management/pages/ConnectionMonitoring.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApp/ConnectedAppContainer.test.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApp/ErrorMonitoring/ConnectAppErrorMonitoring.test.tsx

CXP-760: Adds error monitoring feature in Apps

---

frontend/webpack/requirejs-utils.js
package.json
webpack.config.js
yarn.lock

Remove dependencies

---

src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml

CXP-756: replace word connection by data in the dataflow dashboard

---

src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml

CXP-1017: change the translation on the no scope title label

---

src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml

CXP-910: Rename Monitoring tab in Error monitoring on connections

---

src/Akeneo/Platform/Job/front/process-tracker/src/feature/components/JobExecutionList/JobExecutionTable.tsx
src/Akeneo/Platform/Job/front/process-tracker/src/feature/components/LastExecutionTable.tsx
src/Akeneo/Platform/Job/front/process-tracker/src/feature/hooks/useJobExecutionTable.test.ts
src/Akeneo/Platform/Job/front/process-tracker/src/feature/hooks/useJobExecutionTable.ts

- Enabling auto-refresh every 5 seconds
- Re-adding progress cells in tables

RAC-1109: Enable process tracker improvements

---

src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Controller/AuthorizeAction.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/controllers.yml
src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Apps/AuthorizeEndToEnd.php

CXP-988: add a condition to throw an error if missing ACL

---

src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Controller/InternalApi/GetAllConnectedAppsAction.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/controllers.yml
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/form_extensions.yml
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/requirejs.yml
src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApps/ConnectedAppCard.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApps/ConnectedAppsCard.test.tsx

- Disable ACLs to access connected apps page
- Add an 'open_apps' ACL check on the "Open app" button

CXP-1007: disable acl to access connected apps page

---

akeneo-design-system/example/package.json
tests/front/unit/jest/fileMock.js
tests/front/unit/jest/unit.jest.js

In this PR i just added in the moduleNameMapper an entry for svg in order to pass the CI

Rac fix shared catalog review

---

src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/less/data-quality-insights-attributes.less
src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/TabContent/DataQualityInsights/Criterion/Criterion.tsx

Fix the following behaviour : display data quality message in several lines if needed for a product and a product model.
see : https://akeneo.atlassian.net/jira/software/projects/PLG/boards/252?selectedIssue=PLG-682 to the result after fixing the issue.

Plg 682 fix product dqi message

---

src/Akeneo/Platform/Job/back/Infrastructure/Installer/JobInstaller.php

When we merged the following PR https://github.com/akeneo/pim-community-dev/pull/15908 we didn't added it in the installer. In this PR I added this migration in the installer

RAC: Fix new instance does not have indexes on job execution table

---

front-packages/akeneo-design-system/src/components/Input/TableInput/TableInputSelect/TableInputSelect.tsx

This PR adds a props to check from the outside when the component opens/closes

CPM-438: Add handler for open/close on TableInputSelect

---

src/Akeneo/Tool/Bundle/MeasureBundle/Model/Unit.php
src/Akeneo/Tool/Bundle/MeasureBundle/PublicApi/GetUnit.php
src/Akeneo/Tool/Bundle/MeasureBundle/PublicApi/SqlGetUnit.php
src/Akeneo/Tool/Bundle/MeasureBundle/PublicApi/Unit.php
src/Akeneo/Tool/Bundle/MeasureBundle/Resources/config/public_api.yml
src/Akeneo/Tool/Bundle/MeasureBundle/tests/Integration/PublicApi/SqlGetUnitIntegration.php

In order to get unit from external bounded context we need to add a new public API

RAC-1006: Add measurement public API

---

src/Akeneo/Platform/Bundle/UIBundle/Imagine/FlattenLayersFilter.php
src/Akeneo/Platform/Bundle/UIBundle/Imagine/GifFilter.php
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/services.yml

This PR add a LiipImagine filter to merge and flatten images layers.

PIM-10211: Flatten image layers during thumbnail and preview transformations in AM

---

config/packages/akeneo_feature_flag.yml

RAC-1111: Add new branding page on shared catalog

---

src/Akeneo/Connectivity/Connection/back/Domain/Settings/Model/Read/Connection.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/Dbal/Query/DbalSelectConnectionsQuery.php
src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Connection/ListConnectionEndToEnd.php
src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Domain/Settings/Model/Read/ConnectionSpec.php
src/Akeneo/Connectivity/Connection/front/src/audit/components/ErrorManagement/BusinessErrorCard.tsx
src/Akeneo/Connectivity/Connection/front/src/audit/components/ErrorManagement/BusinessErrorCountWidget.tsx
src/Akeneo/Connectivity/Connection/front/src/model/connection.ts

In the dataflow dashboard, you can click on the Connections to check individual errors.
When you click on an App, you should be redirected to the App Monitoring Tab.

CXP-753: fix click on Error Business shortcut

---

src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/ProductAndProductModel/CountProductModelsWithRemovedAttribute.php
src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/ProductAndProductModel/CountProductsWithRemovedAttribute.php
src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/ProductAndProductModel/GetProductIdentifiersWithRemovedAttribute.php
src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/ProductAndProductModel/GetProductModelIdentifiersWithRemovedAttribute.php
src/Akeneo/Pim/Enrichment/Component/Product/Query/CountProductModelsWithRemovedAttributeInterface.php
src/Akeneo/Pim/Enrichment/Component/Product/Query/CountProductsWithRemovedAttributeInterface.php
src/Akeneo/Pim/Enrichment/Component/Product/Query/GetProductIdentifiersWithRemovedAttributeInterface.php
src/Akeneo/Pim/Enrichment/Component/Product/Query/GetProductModelIdentifiersWithRemovedAttributeInterface.php
tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductAndProductModel/GetProductIdentifiersWithRemovedAttributeIntegration.php

Refactor `get/countProduct[Model]WithRemovedAttributes` queries used in the cleaning removed attribute values job, in order to allow decorating theme

CPM-448: Refactor and prepare queries for decoration

---

config/packages/behat/monolog.yml
config/packages/monolog.yml
config/packages/prod/monolog.yml
config/packages/test/monolog.yml
src/Akeneo/Tool/Bundle/ApiBundle/EventSubscriber/ApiRequestLogSubscriber.php
src/Akeneo/Tool/Bundle/ApiBundle/Resources/config/event_subscribers.yml
src/Akeneo/Tool/Bundle/ApiBundle/tests/integration/EventSubscriber/ApiRequestLogSubscriberIntegration.php

see https://github.com/akeneo/pim-enterprise-dev/pull/12607

CXP-1050: log all api requests

---

src/Akeneo/Platform/Bundle/ImportExportBundle/Repository/InternalApi/JobInstanceRepository.php
src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/repositories.yml

Do not load deactivated jobs in the job profile datagrid (import/export)

---

src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filters-selector.ts

CPM-413: Add method to read which datagrid is used in filterModules

---

CHANGELOG.md
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/grid/view-selector.js
src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/product_scope-filter.js

https://akeneo.atlassian.net/browse/PIM-10218?atlOrigin=eyJpIjoiMGY4NzNhMTE1ZTkyNDgwNGE2YWYwZmZmOWNkYjllYTAiLCJwIjoiaiJ9

PIM-10218: Fix channel filter added to the product grid each time you switch from published products to products if you were on a projet

---

src/Akeneo/Connectivity/Connection/front/src/connect/components/DeveloperModeTag.tsx

I've merged the PR https://github.com/akeneo/pim-community-dev/pull/16086 without pushing the fix on the style of the badge, sorry for the mistake.

CXP-1037: replace Badge by Tag

---

frontend/webpack/config-loader.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/config-registry.ts

See https://github.com/akeneo/pim-enterprise-dev/pull/12605

RAC-1019: Add config-registry component in order to to not inject anymore the __moduleConfig in all files

---

CHANGELOG.md
config/packages/framework.yml
config/packages/security.yml

PIM-10229: Enforce strict samesite policy for session cookies

---

src/Akeneo/Connectivity/Connection/back/Domain/Marketplace/GetAllTestAppsQueryInterface.php
src/Akeneo/Connectivity/Connection/back/Domain/Marketplace/Model/App.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/InternalApi/Controller/Marketplace/GetAllTestAppsAction.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Marketplace/GetAllTestAppsQuery.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/controllers.yml
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/routing/marketplace.yml
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Marketplace/GetAllTestAppsActionEndToEnd.php
src/Akeneo/Connectivity/Connection/back/tests/Integration/Resources/config/services.yml
src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Domain/Marketplace/Model/AppSpec.php
src/Akeneo/Connectivity/Connection/front/src/connect/components/Marketplace.tsx
src/Akeneo/Connectivity/Connection/front/src/connect/components/MarketplaceCard.tsx
src/Akeneo/Connectivity/Connection/front/src/connect/components/TestApp/TestAppCard.tsx
src/Akeneo/Connectivity/Connection/front/src/connect/components/TestApp/TestAppList.tsx
src/Akeneo/Connectivity/Connection/front/src/connect/hooks/use-fetch-test-apps.ts
src/Akeneo/Connectivity/Connection/front/src/connect/pages/MarketplacePage.tsx
src/Akeneo/Connectivity/Connection/front/src/model/app.ts
src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/TestApp/TestAppCard.test.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/TestApp/TestAppList.test.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/connect/hooks/use-fetch-test-apps.test.ts
src/Akeneo/UserManagement/Bundle/Resources/translations/jsmessages.en_US.yml

CXP-1041 Display test apps

---

src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml

CXP 1041 Conflicting translations fix

CXP 1041 Conflicting translations fix

---

front-packages/shared/src/components/Navigation/PimNavigation.tsx

Reverts akeneo/pim-community-dev#16091

Revert "PLG-670: Zoom problem on the resolution on several users screens"

---

.circleci/jobs/features/connectivity.yml
make-file/connectivity-connection.mk
src/Akeneo/Connectivity/Connection/back/tests/phpinsights.php
src/Akeneo/Connectivity/Connection/back/tests/psalm.xml

CXP: configure php insights

---

.circleci/jobs/build_and_deploy.yml

BH-1046 - Fix remove env kubernetes

---

src/Akeneo/Connectivity/Connection/back/Infrastructure/Install/Query/CreateAppTableQuery.php
upgrades/schema/Version_6_0_20220111160750_update_logo_to_be_nullable.php
upgrades/schema/Version_6_0_20220111161207_update_author_to_be_nullable.php
upgrades/test_schema/Version_6_0_20220111160750_update_logo_to_be_nullable_Integration.php
upgrades/test_schema/Version_6_0_20220111161207_update_author_to_be_nullable_Integration.php

CXP-1060: add migration to nullable logo and author

---

src/Akeneo/Tool/Bundle/StorageUtilsBundle/Doctrine/DBAL/Types/UTCDateTimeType.php

Backport of #16121 on the 6.0 branch

[BACKPORT] Fix UTCDateTimeType::convertToPHPValue() to handle datetime arguments

---

src/Akeneo/Connectivity/Connection/back/Application/Apps/Command/CreateAppWithAuthorizationHandler.php
src/Akeneo/Connectivity/Connection/back/Application/Apps/Command/RequestAppAuthorizationHandler.php
src/Akeneo/Connectivity/Connection/back/Domain/Apps/Exception/InvalidAppAuthorizationRequestException.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Controller/AuthorizeAction.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Controller/ConfirmAuthenticationAction.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Controller/ConfirmAuthorizationAction.php
src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/Command/CreateAppWithAuthorizationHandlerIntegration.php
src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/Command/RequestAppAuthorizationHandlerIntegration.php
src/Akeneo/Connectivity/Connection/back/tests/PhpStan/Rule/SuffixExceptionRule.php
src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Apps/Command/CreateAppWithAuthorizationHandlerSpec.php
src/Akeneo/Connectivity/Connection/back/tests/phpstan.neon

CXP-956: [rule] Each backend exception should have the Exception suffix

---

src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/validation/CreateTestAppCommand.yml
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
src/Akeneo/Connectivity/Connection/back/tests/Integration/Marketplace/TestApps/Validation/CreateTestAppCommandValidationIntegration.php
src/Akeneo/Connectivity/Connection/front/src/connect/components/TestApp/CreateTestAppCredentials.tsx
src/Akeneo/Connectivity/Connection/front/src/connect/components/TestApp/CreateTestAppForm.tsx
src/Akeneo/Connectivity/Connection/front/src/connect/hooks/use-create-test-app.ts
src/Akeneo/Connectivity/Connection/front/src/connect/pages/TestAppCreatePage.tsx
src/Akeneo/Connectivity/Connection/front/src/settings/components/credentials/CopiableCredential.tsx
src/Akeneo/Connectivity/Connection/front/src/settings/components/credentials/Credential.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/TestApp/CreateTestAppCredentials.test.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/TestApp/CreateTestAppForm.test.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/connect/hooks/use-create-test-app.test.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/connect/pages/TestAppCreatePage.test.tsx

CXP-1049: Show credentials

---

front-packages/akeneo-design-system/src/components/Input/TableInput/TableInputCellContent/TableInputCellContent.tsx
front-packages/akeneo-design-system/src/components/Input/TableInput/TableInputHeaderCell/TableInputHeaderCell.tsx
src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/legacy-bridge/src/__mocks__/dependencies.ts

Fix Cell input's style for long texts

Cpm 444: Fix styles for cells

---

src/Akeneo/Connectivity/Connection/back/tests/PhpStan/Rule/SuffixTraitRule.php
src/Akeneo/Connectivity/Connection/back/tests/phpstan.neon

CXP-957: [rule] Each backend trait should have the Trait suffix

---

src/Akeneo/Connectivity/Connection/back/Infrastructure/EventSubscriber/AclPrivilegesEventSubscriber.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Marketplace/TestApps/Controller/InternalApi/CreateTestAppsAction.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/acl.yml
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/event_subscribers.yml
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/marketplace.yml
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/messages.en_US.yml
src/Akeneo/Connectivity/Connection/back/tests/.php_cd.php
src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Marketplace/TestApps/CreateTestAppsActionEndToEnd.php
src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/EventSubscriber/AclPrivilegesEventSubscriberSpec.php
src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Marketplace/TestApps/Controller/InternalApi/CreateTestAppsActionSpec.php
src/Akeneo/Connectivity/Connection/front/src/connect/components/ActivateAppButton.tsx
src/Akeneo/Connectivity/Connection/front/src/connect/components/Marketplace.tsx
src/Akeneo/Connectivity/Connection/front/src/connect/components/TestApp/TestAppList.tsx
src/Akeneo/Connectivity/Connection/front/src/connect/hooks/use-developer-mode.ts
src/Akeneo/Connectivity/Connection/front/src/connect/pages/ConnectedAppsListPage.tsx
src/Akeneo/Connectivity/Connection/front/src/connect/pages/MarketplacePage.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ActiveAppButton.test.tsx
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/acl_groups.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/messages.en_US.yml

CXP-1044: Add acl on manage test apps

---

src/Akeneo/Connectivity/Connection/back/Application/Marketplace/TestApps/Command/DeleteTestAppCommand.php
src/Akeneo/Connectivity/Connection/back/Application/Marketplace/TestApps/Command/DeleteTestAppHandler.php
src/Akeneo/Connectivity/Connection/back/Domain/Marketplace/TestApps/Persistence/DeleteTestAppQueryInterface.php
src/Akeneo/Connectivity/Connection/back/Domain/Marketplace/TestApps/Persistence/GetTestAppQueryInterface.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Marketplace/GetTestAppQuery.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Marketplace/TestApps/Controller/InternalApi/DeleteTestAppAction.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Marketplace/TestApps/Persistence/DeleteTestAppQuery.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/marketplace.yml
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/requirejs.yml
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/routing.yml
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/routing/marketplace.yml
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
src/Akeneo/Connectivity/Connection/back/tests/.php_cd.php
src/Akeneo/Connectivity/Connection/front/src/connect/components/TestApp/TestAppCard.tsx
src/Akeneo/Connectivity/Connection/front/src/connect/hooks/use-delete-test-app.ts
src/Akeneo/Connectivity/Connection/front/src/connect/pages/DeleteTestAppPromptPage.tsx
src/Akeneo/Connectivity/Connection/front/src/infrastructure/Marketplace.tsx

Implemented test app deletion:
Missing tests but will be done in the next  PR

CXP-1038 Test App deletion

---

src/Akeneo/Connectivity/Connection/back/Infrastructure/Marketplace/GetAllTestAppsQuery.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Marketplace/GetTestAppQuery.php

The join was useless and returning inconsistent results.

CXP-1067: fix GetAllTestAppsQuery

---

src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/TestApp/CreateTestAppCredentials.test.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/connect/hooks/use-create-test-app.test.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/connect/pages/TestAppCreatePage.test.tsx

CXP-1036: add some tests

---

src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Persistence/DbalConnectedAppRepository.php
src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/Persistence/DbalConnectedAppRepositoryIntegration.php
src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApp/ConnectedAppContainer.tsx
src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApps/ConnectedTestAppList.tsx
src/Akeneo/Connectivity/Connection/front/src/connect/components/TestApp/TestAppCard.tsx
src/Akeneo/Connectivity/Connection/front/src/connect/components/TestApp/TestAppList.tsx
src/Akeneo/Connectivity/Connection/front/src/connect/hooks/use-connected-apps.ts
src/Akeneo/Connectivity/Connection/front/src/connect/hooks/use-fetch-test-apps.ts
src/Akeneo/Connectivity/Connection/front/src/connect/hooks/use-test-apps.ts
src/Akeneo/Connectivity/Connection/front/src/connect/pages/MarketplacePage.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/connect/hooks/use-connected-apps.test.ts
src/Akeneo/Connectivity/Connection/front/tests/src/connect/hooks/use-fetch-test-apps.test.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/connect/hooks/use-test-apps.test.ts

CXP-1015: Fixes after review

---

.circleci/jobs/build_and_deploy.yml
.circleci/workflows/pull_request.yml

BH-986: CI for v6.0

---

CHANGELOG.md
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/field/wysiwyg-field.js

PIM-10234: Fix the saved value by an empty wysiwyg

---

src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/InMemory/Query/IsConnectionsNumberLimitReachedQuery.php
src/Akeneo/Connectivity/Connection/back/tests/Acceptance/Resources/config/queries.yml

Added missing InMemory query to fix failling acceptance test

CXP-928: Added missing InMemory query

---

.circleci/jobs/features/connectivity.yml

CXP-1081: Added acceptance back as step for test_back_connectivity job

CXP-1081: Added acceptance back as step for test_back_connectivity job

---

tests/back/Acceptance/MeasurementFamily/InMemoryGetUnit.php
tests/back/Acceptance/Resources/config/pim/repositories.yml
tests/back/Acceptance/spec/MeasurementFamily/InMemoryGetUnitSpec.php

CPM-458: add in memory service to get measurement unit

---

.circleci/detect_structure_changes.sh
.circleci/jobs/build_and_deploy.yml
.circleci/jobs/features/connectivity.yml
.circleci/jobs/features/other.yml
tests/legacy/features/channel/edit_channel.feature

fix circleci uid

---

.circleci/detect_structure_changes.sh
.circleci/jobs/build_and_deploy.yml
.circleci/jobs/features/connectivity.yml
.circleci/jobs/features/other.yml
src/Akeneo/Tool/Bundle/MeasureBundle/Convert/MeasureConverter.php
src/Akeneo/Tool/Bundle/MeasureBundle/spec/Convert/MeasureConverterSpec.php
tests/legacy/features/channel/edit_channel.feature

CPM-461: make the MeasureConverter case insensitive

---

src/Akeneo/Connectivity/Connection/back/Domain/Marketplace/TestApps/Persistence/GetTestAppQueryInterface.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Validation/CodeChallengeMustBeValidValidator.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Marketplace/GetTestAppQuery.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/validators.yml
src/Akeneo/Connectivity/Connection/back/tests/Integration/Marketplace/GetTestAppQueryIntegration.php
src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Apps/Validation/CodeChallengeMustBeValidValidatorSpec.php

When connecting a test App, the code challenge should be handled PIM-side, we shoudn't call the marketplace API.

OCT-4: Do not call the marketplace API when validating a test app

---

CHANGELOG.md
src/Akeneo/UserManagement/Bundle/Provider/CustomUserChecker.php
src/Akeneo/UserManagement/Bundle/Resources/config/services.yml
src/Akeneo/UserManagement/Component/Model/User.php
tests/back/UserManagement/Specification/Bundle/Provider/CustomUserCheckerSpec.php
tests/back/UserManagement/Specification/Component/Model/UserSpec.php

An emergency  fix... Please note added code is injected in CustomDaoAuthenticationProvider which is based on a deprecated class since Symfony 5.3

PIM-10241: fix user account disabled can connect regression

---

src/Akeneo/Pim/Structure/Bundle/Query/PublicApi/AttributeOption/Sql/SqlGetAttributeOptions.php
src/Akeneo/Pim/Structure/Bundle/Resources/config/queries.yml
src/Akeneo/Pim/Structure/Component/Query/PublicApi/AttributeOption/GetAttributeOptions.php
tests/back/Pim/Structure/Integration/AttributeOption/SqlGetAttributeOptionsIntegration.php

CPM-455: Add query to retrieve AttributeOptions

---

front-packages/akeneo-design-system/src/components/Input/TableInput/TableInputMeasurement/TableInputMeasurement.tsx

Add props highlighted and inError to TableInputMeasurement component

CPM-364: Add props highlighted and inError to TableInputMeasurement component

---

composer.json
phpspec.yml.dist
phpstan.neon
phpunit.xml.dist
src/Akeneo/Pim/Enrichment/Bundle/DependencyInjection/AkeneoPimEnrichmentExtension.php
src/Akeneo/Pim/Enrichment/Bundle/Resources/config/handlers.yml
src/Akeneo/Pim/Enrichment/Product/back/Api/Command/Exception/LegacyViolationsException.php
src/Akeneo/Pim/Enrichment/Product/back/Api/Command/Exception/ViolationsException.php
src/Akeneo/Pim/Enrichment/Product/back/Api/Command/UpsertProductCommand.php
src/Akeneo/Pim/Enrichment/Product/back/Api/Command/UserIntent/SetTextValue.php
src/Akeneo/Pim/Enrichment/Product/back/Api/Command/UserIntent/UserIntent.php
src/Akeneo/Pim/Enrichment/Product/back/Api/Command/UserIntent/ValueUserIntent.php
src/Akeneo/Pim/Enrichment/Product/back/Application/UpsertProductHandler.php
src/Akeneo/Pim/Enrichment/Product/tests/back/Integration/Handler/UpsertProductIntegration.php
src/Akeneo/Pim/Enrichment/Product/tests/back/Specification/Api/Command/UpsertProductCommandSpec.php
src/Akeneo/Pim/Enrichment/Product/tests/back/Specification/Api/Command/UserIntent/SetTextValueSpec.php
src/Akeneo/Pim/Enrichment/Product/tests/back/Specification/Application/UpsertProductHandlerSpec.php

No permission handled for now -> do not use for now.
Only "SetTextValue" is possible now.
Test configs are plugged on the current tests. In CPM-499 we certainly will refactor this.

CPM-491: First brick of product service API (experimental)

---

CHANGELOG-5.0.md

PIM-10254: Pull up 5.0 into master

---

make-file/connectivity-connection.mk
tests/back/Pim/Structure/Specification/Component/Security/AttributeOptionsScopeMapperSpec.php

We broke a test with https://github.com/akeneo/pim-community-dev/pull/16228
Those tests were not launched by our custom CI, because they are in other contexts.
But since they are really relevant to our work and feature, I've added them in our custom CI.

OCT-6: fix spec

---

make-file/job.mk
src/Akeneo/Platform/Job/back/Infrastructure/Controller/GetJobExecutionAction.php
src/Akeneo/Platform/Job/back/Infrastructure/Controller/GetJobTypeAction.php
src/Akeneo/Platform/Job/back/Infrastructure/Controller/GetJobUserAction.php
src/Akeneo/Platform/Job/back/Infrastructure/Hydrator/StepExecutionTrackingHydrator.php
src/Akeneo/Platform/Job/back/Infrastructure/Query/SearchJobExecution.php
src/Akeneo/Platform/Job/back/Infrastructure/Query/SearchJobUser.php
src/Akeneo/Platform/Job/back/Infrastructure/Symfony/DependencyInjection/AkeneoJobExtension.php
src/Akeneo/Platform/Job/back/tests/.php_cs.php
src/Akeneo/Platform/Job/back/tests/Integration/Infrastructure/Query/SearchJobExecutionTest.php
src/Akeneo/Platform/Job/back/tests/Integration/Loader/FixturesJobHelper.php
src/Akeneo/Platform/Job/back/tests/Integration/Loader/FixturesLoader.php
src/Akeneo/Platform/Job/back/tests/Integration/Loader/FixturesUserHelper.php

In this PR :
We added temporary rector in composer.json (while it was not valided with backend guild)
```
"rector/rector": "^0.11.5"
```
We launched rector on job bundle :
```bash
docker-compose run -u www-data fpm vendor/bin/rector process
```
With the following configuration `rector.php`:
```php
<?php
declare(strict_types=1);
use Rector\Core\Configuration\Option;
use Rector\Php74\Rector\Property\TypedPropertyRector;
use Rector\Php73\Rector\FuncCall\JsonThrowOnErrorRector;
use Rector\Set\ValueObject\SetList;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;
return static function (ContainerConfigurator $containerConfigurator): void {
$parameters = $containerConfigurator->parameters();
// Find rules here …
```

RAC-UNIVERSITY: Launch rector on job bundle and add phpcsfixer configuration more specific

---

src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/QualityScoreProductHeader.tsx
src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/QualityScoreLoader.tsx
src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/listener/ProductEditForm/ProductContextListener.tsx
src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/state/PageContextState.ts
src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/hooks/ProductEditForm/useFetchProductQualityScore.tsx
src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/hooks/ProductEditForm/useProductEvaluation.ts
src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/reducer/ProductEditForm/pageContextReducer.ts
src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/reducer/index.ts

**Description (for Contributor and Core De
veloper)**
---------------

PLG-718 : Display quality score skeleton when product is evaluating only on save action 

---

CHANGELOG-6.0.md

BH-986: Rename CHANGELOG

---

src/Akeneo/Platform/Bundle/NotificationBundle/Resources/views/Email/notification.html.twig
src/Akeneo/Platform/Bundle/NotificationBundle/Resources/views/Email/notification.txt.twig
src/Akeneo/Tool/Bundle/BatchBundle/Resources/views/Email/notification.txt.twig
src/Akeneo/UserManagement/Bundle/Resources/views/Mail/reset.txt.twig

/!\ The 'shared catalog' notion has been deleted in this [PR](https://github.com/akeneo/pim-community-dev/pull/16156/files) regarding the email password which is already merged.
Fix : On plain text message add footer. 

PLG-239 : add footer on plain text batch email

---

CHANGELOG-5.0.md
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/select2/select2.js

PIM-10257: Fix content Security Policy error log

---

upgrades/schema/Version_5_0_20220201155016_add_user_account_locking_after_too_many_attempts.php
upgrades/schema/Version_6_0_20210427163307_add_user_account_locking_after_too_many_attempts.php

FIX-CI: fix migrations

---

CHANGELOG-5.0.md
src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Product/Association/GetGroupAssociationsByProductIdentifiers.php
src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Product/Association/GetProductAssociationsByProductIdentifiers.php
src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Product/Association/GetProductModelAssociationsByProductIdentifiers.php
src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductModel/GetGroupAssociationsByProductModelCodes.php
src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductModel/GetProductAssociationsByProductModelCodes.php
src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductModel/GetProductModelsAssociationsByProductModelCodes.php

https://akeneo.atlassian.net/browse/PIM-10258?atlOrigin=eyJpIjoiOTcyNGFjZWRiYzVjNDAzZGExMGM2ZTUyM2I1YzE5NzYiLCJwIjoiaiJ9

PIM-10258: Increase buffer size to avoid memory size issue for product associations query

---

CHANGELOG.md
src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Completeness/VariantProductRatio.php

Description of the issue and the fix here : https://akeneo.atlassian.net/browse/PIM-10264?atlOrigin=eyJpIjoiYjdlNzVkOWJmMjU4NGJmNTgwMzE0N2M3ZDMwYWM0YTYiLCJwIjoiaiJ9

PIM-10264: Optimize variant product ratio query

---

CHANGELOG-5.0.md
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/fetcher/attribute-group-fetcher.js

PIM-10270: Fix insufficient limit when fetching a lot of attribute groups in families settings

---

CHANGELOG.md
composer.json
composer.lock
src/Akeneo/Pim/Enrichment/.php_cd.php
src/Akeneo/Pim/Enrichment/Bundle/DependencyInjection/AkeneoPimEnrichmentExtension.php
src/Akeneo/Pim/Enrichment/Bundle/PdfGeneration/Builder/DompdfBuilder.php
src/Akeneo/Pim/Enrichment/Bundle/PdfGeneration/HtmlFormatter/ArabicHtmlFormatter.php
src/Akeneo/Pim/Enrichment/Bundle/PdfGeneration/HtmlFormatter/HtmlFormatter.php
src/Akeneo/Pim/Enrichment/Bundle/Resources/config/builders.yml
src/Akeneo/Pim/Enrichment/Bundle/Resources/config/html_formatter.yml
symfony.lock
tests/back/Pim/Enrichment/Specification/Bundle/PdfGeneration/HtmlFormatter/ArabicHtmlFormatterSpec.php

PIM-10259: Add ArPHP library and fix Arabic RTL in PDF Exports

---

.circleci/workflows/squads/octopus.yml

Added OCT prefixed PR to use octopus workflow

OCT Added OCT prefixed PR to use octopus workflow

---

CHANGELOG-5.0.md
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/fetcher/attribute-group-fetcher.js

Pullupwilly

---

make-file/connectivity-connection.mk
src/Akeneo/Connectivity/Connection/back/Infrastructure/Marketplace/TestApps/Controller/InternalApi/CreateTestAppsAction.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/marketplace.yml
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Marketplace/TestApps/Controller/InternalApi/CreateTestAppsActionSpec.php
src/Akeneo/Connectivity/Connection/front/src/connect/pages/TestAppCreatePage.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/connect/pages/TestAppCreatePage.test.tsx

CXP-1093: Send 404 on cerate test app form if feature flag are disabled

---

src/Akeneo/Pim/Enrichment/Product/back/Api/Command/UserIntent/SetNumberValue.php
src/Akeneo/Pim/Enrichment/Product/back/Api/Command/UserIntent/SetTextValue.php
src/Akeneo/Pim/Enrichment/Product/back/Application/UpsertProductHandler.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductIntegration.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Api/Command/UpsertProductCommandSpec.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Api/Command/UserIntent/SetNumberValueSpec.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Api/Command/UserIntent/SetTextValueSpec.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Infrastructure/Validation/LocaleAndChannelShouldBeConsistentValidatorSpec.php

Add SetNumberValue as a UserIntent to use for UpsertProductCommand

CPM-515: Add SetNumberValue as a UserIntent to use for UpsertProductCommand

---

src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductIntegration.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductWithPermissionIntegration.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Infrastructure/Validation/LocaleShouldBeEditableByUserValidatorSpec.php

CPM-515: Replace upsertProductHandler with messagebus in tests

---

src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApps/ConnectedAppCard.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApps/ConnectedAppCard.test.tsx

OCT-14: fix ACLs to open a test app

---

CODEOWNERS

See https://github.com/akeneo/pim-enterprise-dev/pull/13013 for full description

DPE: Remove BlackHawk code owner for migrations

---

src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/GetProductModelScores.php
src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/ProductEvaluation/GetUpToDateProductModelScoresQuery.php
src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Query/ProductEvaluation/GetProductModelScoresQueryInterface.php
src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Query/ProductEvaluation/HasUpToDateEvaluationQueryInterface.php
src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetProductModelScoresQuery.php
src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetUpToDateLatestProductScoresQuery.php
src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/HasUpToDateProductEvaluationQuery.php
src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/HasUpToDateProductModelEvaluationQuery.php
src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Controller/GetProductModelQualityScoreController.php
src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/controllers.yml
src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/queries.yml
src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/services.yml
src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Infrastructure/Persistence/Query/ProductEvaluation/GetProductModelScoresQueryIntegration.php
src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Infrastructure/Persistence/Query/ProductEvaluation/HasUpToDateProductEvaluationQueryIntegration.php
src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Application/GetProductModelScoresSpec.php
src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Application/ProductEvaluation/GetUpToDateProductModelScoresQuerySpec.php
src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Persistence/Query/ProductEvaluation/GetUpToDateLatestProductScoresQuerySpec.php

PLG-745 :  product model fetch quality score

---

src/Akeneo/Pim/Enrichment/Product/back/API/Command/UserIntent/ClearValue.php
src/Akeneo/Pim/Enrichment/Product/back/API/Command/UserIntent/ValueUserIntent.php
src/Akeneo/Pim/Enrichment/Product/back/Application/UpsertProductHandler.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductIntegration.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/API/Command/UpsertProductCommandSpec.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/API/Command/UserIntent/ClearValueSpec.php

Add ClearValue UserIntent for UpsertProductCommand

CPM-520 ClearValue UserIntent

---

src/Akeneo/Pim/Enrichment/Product/back/Application/UpsertProductHandler.php
src/Akeneo/Pim/Enrichment/Product/back/Domain/Event/ProductWasCreated.php
src/Akeneo/Pim/Enrichment/Product/back/Domain/Event/ProductWasUpdated.php
src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Symfony/Resources/config/handlers.yml
src/Akeneo/Pim/Enrichment/Product/back/Test/.php_cd.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Application/UpsertProductHandlerSpec.php

Add `ProductWasCreated` and `ProductWasUpdated` events to dispatch on UpsertProductHandler

CPM-521: Add Events when product was updated with UpsertProductCommand

---

.circleci/workflows/editions/community.yml

Fix automatic pullup script

---

CHANGELOG-5.0.md
src/Akeneo/Pim/Enrichment/Component/Product/Localization/Presenter/MetricPresenter.php
tests/back/Pim/Enrichment/Specification/Component/Product/Localization/Presenter/MetricPresenterSpec.php

Improve array_filter in product grid present function to keep zero values

Pim 10296: Fix display of zero value in Product grid

---

src/Akeneo/Pim/Enrichment/Product/back/API/Command/UserIntent/SetMetricValue.php
src/Akeneo/Pim/Enrichment/Product/back/Application/UpsertProductHandler.php
src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Symfony/Resources/config/validation/product_commands.yml
src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductIntegration.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/API/Command/UpsertProductCommandSpec.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/API/Command/UserIntent/SetMetricValueSpec.php

CPM-519: SetMetricValue UserIntent

---

src/Akeneo/Pim/Enrichment/Bundle/Command/MigrateToUuid/MigrateToUuidFillJson.php
src/Akeneo/Pim/Enrichment/Bundle/Command/MigrateToUuid/MigrateToUuidFillProductUuid.php
src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/Product/OnSave/AddUuidSubscriber.php

Before we did a select query, then a "insert on duplicate key update". The problem is some items can be removed between this 2 statements. In this case the 2nd query will insert bad rows. Even if the case would probably never happen, we could not ensure it will not happen.
To prevent this, we now use update

CPM-539: use update instead of "insert on duplicate key update"

---

CHANGELOG-5.0.md

Fix 5.0 CHANGELOG

---

CHANGELOG-6.0.md
src/Akeneo/UserManagement/Bundle/Security/UserApiProvider.php
src/Akeneo/UserManagement/Bundle/Security/UserProvider.php
tests/back/UserManagement/Specification/Bundle/Security/UserApiProviderSpec.php

[Backport V6] PIM-10305 Refuse disabled users 

---

src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Controller/AuthorizeAction.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Controller/InternalApi/ConfirmAuthenticationAction.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/controllers.yml
src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Apps/InternalApi/ConfirmAuthenticationEndToEnd.php
src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Apps/Controller/AuthorizeActionSpec.php
src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Apps/Controller/InternalApi/ConfirmAuthenticationActionSpec.php

OCT-20: ACLs : (re)connect a test app : only manage_test_apps is needed

---

src/Akeneo/Pim/Enrichment/Product/back/API/Command/UserIntent/SetBooleanValue.php
src/Akeneo/Pim/Enrichment/Product/back/Application/UpsertProductHandler.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductIntegration.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/API/Command/UpsertProductCommandSpec.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/API/Command/UserIntent/SetBooleanValueSpec.php

Add SetBooleanValue UserIntent

CPM-514: Add SetBooleanValue UserIntent

---

src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Symfony/Resources/config/validation/product_commands.yml
src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Symfony/Resources/config/validators.yml
src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Symfony/Resources/translations/validators.en_US.yml
src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Validation/UserIntentsShouldBeUnique.php
src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Validation/UserIntentsShouldBeUniqueValidator.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductIntegration.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Infrastructure/Validation/UserIntentsShouldBeUniqueValidatorSpec.php

CPM-501: Validate valueIntents to avoid two edits on the same value

---

src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
src/Akeneo/Connectivity/Connection/front/src/connect/components/AppWizard/steps/Authentication/ConsentList.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/AppWizard/steps/Authentication/ConsentList.test.tsx

OCT-15: highlight firstname, lasname and email in the consent list

---

src/Akeneo/Pim/Enrichment/Product/back/Test/Helper/FeatureHelper.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductIntegration.php

Add integration test for assets and refEntities for UpsertProductCommand

CPM-523: Add integration test for assets and refEntities for UpsertProductCommand

---

src/Akeneo/Pim/Enrichment/Product/back/API/Command/UserIntent/SetMultiSelectValue.php
src/Akeneo/Pim/Enrichment/Product/back/API/Command/UserIntent/SetSimpleSelectValue.php
src/Akeneo/Pim/Enrichment/Product/back/Application/UpsertProductHandler.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductIntegration.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/API/Command/UserIntent/SetMultiSelectValueSpec.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/API/Command/UserIntent/SetSimpleSelectValueSpec.php

CPM-530: Add SetSimpleSelectValue and SetMultiSelectValue user intents

---

src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml

CXP-1119: Rename Apps into Cnnected Apps

---

make-file/connectivity-connection.mk
src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/Security/ScopeMapperRegistryIntegration.php
src/Akeneo/Pim/Structure/Component/Security/AttributeOptionsScopeMapper.php
tests/back/Pim/Structure/Specification/Component/Security/AttributeOptionsScopeMapperSpec.php

OCT-6: Fix wrong ACL mapping for attribute options

---

src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/routing.yml
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
src/Akeneo/Connectivity/Connection/front/src/connect/components/AppWizard/AppWizard.tsx
src/Akeneo/Connectivity/Connection/front/src/connect/components/AppWizard/AppWizardWithPermissions.tsx
src/Akeneo/Connectivity/Connection/front/src/connect/pages/AppAuthenticatePage.tsx
src/Akeneo/Connectivity/Connection/front/src/connect/pages/AppAuthorizePage.tsx
src/Akeneo/Connectivity/Connection/front/src/connect/pages/MarketplacePage.tsx
src/Akeneo/Connectivity/Connection/front/src/connect/pages/SelectUserProfilePage.tsx
src/Akeneo/Connectivity/Connection/front/src/infrastructure/Marketplace.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/AppWizard/AppWizard.test.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/AppWizard/AppWizardWithPermissions.test.tsx
src/Akeneo/UserManagement/Bundle/Resources/translations/jsmessages.en_US.yml
tests/legacy/features/Context/Page/Marketplace/Index.php

CXP-1118: Rename marketplace by App Store

---

src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/js/infrastructure/datagrid/cell/quality-score-badge-cell.tsx
src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/ScoreDistributionSection/Chart/Summary.tsx
src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/ScoreDistributionSection/Chart/Tooltip.tsx
src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/QualityScoreProductHeader.tsx
src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/QualityScore.tsx
src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/QualityScoreBar.tsx
src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/QualityScoreLoader.tsx
src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/QualityScorePending.tsx
src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/index.ts
src/Akeneo/Pim/Automation/DataQualityInsights/front/src/domain/QualityScore.ts
src/Akeneo/Pim/Automation/DataQualityInsights/front/src/domain/QualityScoreModel.ts
src/Akeneo/Pim/Automation/DataQualityInsights/front/src/domain/index.ts
src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/hooks/Dashboard/useFetchQualityScoreEvolution.ts
src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/hooks/ProductEditForm/useFetchQualityScore.tsx
src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Application/component/ProductEditForm/QualityScoreProductHeader.unit.tsx
src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Application/component/QualityScore.unit.tsx
src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Application/component/QualityScoreBar.unit.tsx

PLG-754-pending-status-UX-in-grid-and-PEF

---

docker-compose.yml
src/Akeneo/Pim/Enrichment/Bundle/Command/MigrateToUuid/MigrateToUuidAddTriggers.php
src/Akeneo/Pim/Enrichment/Bundle/Command/MigrateToUuid/MigrateToUuidCommand.php
src/Akeneo/Pim/Enrichment/Bundle/Command/MigrateToUuid/MigrateToUuidTrait.php
src/Akeneo/Pim/Enrichment/Bundle/Resources/config/cli_command.yml
tests/back/Pim/Enrichment/Integration/Product/AbstractMigrateToUuidTestCase.php
tests/back/Pim/Enrichment/Integration/Product/MigrateToUuidCommandIntegration.php
tests/back/Pim/Enrichment/Integration/Product/UuidMigration/AbstractMigrateToUuidTestCase.php
tests/back/Pim/Enrichment/Integration/Product/UuidMigration/AddUuidSubscriberIntegration.php

CPM-541: Add triggers

---

src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/routing.yml
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
src/Akeneo/Connectivity/Connection/front/src/connect/components/AppWizard/AppWizard.tsx
src/Akeneo/Connectivity/Connection/front/src/connect/components/AppWizard/AppWizardWithPermissions.tsx
src/Akeneo/Connectivity/Connection/front/src/connect/pages/AppAuthenticatePage.tsx
src/Akeneo/Connectivity/Connection/front/src/connect/pages/AppAuthorizePage.tsx
src/Akeneo/Connectivity/Connection/front/src/connect/pages/MarketplacePage.tsx
src/Akeneo/Connectivity/Connection/front/src/connect/pages/SelectUserProfilePage.tsx
src/Akeneo/Connectivity/Connection/front/src/infrastructure/Marketplace.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/AppWizard/AppWizard.test.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/AppWizard/AppWizardWithPermissions.test.tsx
src/Akeneo/UserManagement/Bundle/Resources/translations/jsmessages.en_US.yml
tests/legacy/features/Context/Page/Marketplace/Index.php

Pull-up 6.0 into master

---

src/Akeneo/Pim/Enrichment/Product/back/API/Command/UserIntent/SetDateValue.php
src/Akeneo/Pim/Enrichment/Product/back/Application/UpsertProductHandler.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductIntegration.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/API/Command/UpsertProductCommandSpec.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/API/Command/UserIntent/SetDateValueSpec.php

CPM-529: Add SetDateValue UserIntent

---

src/Akeneo/Pim/Enrichment/Product/back/API/Command/UserIntent/AddMultiSelectValue.php
src/Akeneo/Pim/Enrichment/Product/back/Application/UpsertProductHandler.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductIntegration.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/API/Command/UpsertProductCommandSpec.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/API/Command/UserIntent/AddMultiSelectValueSpec.php

Add AddMultiSelectProductValue UserIntent

CPM-531: Add AddMultiSelectProductValue UserIntent

---

src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/routing.yml
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
src/Akeneo/Connectivity/Connection/front/src/infrastructure/Marketplace.tsx

CXP-1118: Rename marketplace into App Store

---

tests/legacy/features/channel/edit_channel.feature

[BACKPORT] Skip flaky test on updating a channel conversion units

---

.circleci/jobs/build_and_deploy.yml
.circleci/jobs/features/connectivity.yml

In this PR, I fixed the fact that we cannot restore the cache (https://app.circleci.com/pipelines/github/akeneo/pim-community-dev/32474/workflows/f59ba3b5-746c-4bf1-b66b-c8ddabdd8c4d/jobs/157778).
Why we have this error ?
Because when we tried to restore the cache the project owner is ubuntu and not circleci

Fix error on cache permission

---

CHANGELOG-6.0.md
upgrades/schema/Version_6_0_20210531152335_dqi_launch_recompute_products_scores.php
upgrades/test_schema/Version_6_0_20210531152335_dqi_launch_recompute_products_scores_Integration.php

Fix migration task related to calculating product quality scores to be independent of the JobExecution implementation

PLG-781: Fix migration task related to calculating product quality scores

---

CHANGELOG.md
src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Versioning/EntityWithQuantifiedAssociations/QuantifiedAssociationsNormalizer.php
src/Akeneo/Pim/Enrichment/Component/Product/Updater/Validator/QuantifiedAssociationsStructureValidator.php
tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/QuantifiedAssociations/UpdateQuantifiedAssociationsInProductEndToEnd.php
tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/QuantifiedAssociations/ValidateQuantifiedAssociationsInProductEndToEnd.php
tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/QuantifiedAssociations/ValidateQuantifiedAssociationsInProductModelEndToEnd.php
tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/Versioning/EntityWithQuantifiedAssociations/QuantifiedAssociationsNormalizerSpec.php
tests/back/Pim/Enrichment/Specification/Component/Product/Updater/Validator/QuantifiedAssociationsStructureValidatorSpec.php

https://akeneo.atlassian.net/browse/PIM-10331

PIM-10331: Fix error when using an association with quantities having an numeric code

---

.circleci/jobs/features/connectivity.yml
.circleci/workflows/squads/octopus.yml
make-file/connectivity-connection.mk

Every sunday night, we have a workflow on Circleci computing the code quality of Connectivity.
I'm adding a step that will post these results on our slack channel:

CXP-1137: octopus quality on slack

---

.circleci/workflows/editions/community.yml
CHANGELOG-6.0.md
src/Akeneo/Pim/Enrichment/Bundle/Command/CalculateCompletenessCommand.php

Backport of https://github.com/akeneo/pim-community-dev/pull/16364/files 
See https://akeneo.atlassian.net/browse/PIM-10307

PIM-10307: backport add batch-size option to pim:completness:calculate command

---

CHANGELOG.md
src/Akeneo/Pim/Enrichment/Bundle/Resources/config/array_converter.yml
src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/validators.en_US.yml
src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/FlatToStandard/ValueConverter/BooleanConverter.php
src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/Boolean.php
tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/FlatToStandard/ValueConverter/BooleanConverterSpec.php
tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/BooleanSpec.php

https://akeneo.atlassian.net/browse/PIM-10330
- The message is used for import and API. So we can't fix it directly. Instead I do the check in the converter to return the expected message for import only.
- The message in the validator is translated

PIM-10330: [SLA] Fix validation message for import

---

CHANGELOG-6.0.md
src/Akeneo/Platform/Bundle/UIBundle/Resources/views/Form/pim-fields.html.twig

Backport of  https://github.com/akeneo/pim-community-dev/pull/16370/files
See https://akeneo.atlassian.net/browse/PIM-10292

PIM-10308: Backport PIM-10292

---

CHANGELOG-6.0.md
src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Completeness/VariantProductRatio.php

Backport of https://github.com/akeneo/pim-community-dev/pull/16264/files
See https://akeneo.atlassian.net/browse/PIM-10264

PIM-10315: backport Optimize variant product ratio query

---

src/Akeneo/Pim/Enrichment/Product/back/API/Command/UpsertProductCommand.php
src/Akeneo/Pim/Enrichment/Product/back/API/Command/UserIntent/FamilyUserIntent.php
src/Akeneo/Pim/Enrichment/Product/back/API/Command/UserIntent/RemoveFamily.php
src/Akeneo/Pim/Enrichment/Product/back/API/Command/UserIntent/SetFamily.php
src/Akeneo/Pim/Enrichment/Product/back/Application/UpsertProductHandler.php
src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Symfony/Resources/config/validation/product_commands.yml
src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Symfony/Resources/translations/validators.en_US.yml
src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductIntegration.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/API/Command/UpsertProductCommandSpec.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/API/Command/UserIntent/SetFamilySpec.php

Add user intents about families:
- SetFamily
- RemoveFamily

CPM-532: add Family user intent

---

CHANGELOG-6.0.md
composer.json
composer.lock
src/Akeneo/Pim/Enrichment/.php_cd.php
src/Akeneo/Pim/Enrichment/Bundle/DependencyInjection/AkeneoPimEnrichmentExtension.php
src/Akeneo/Pim/Enrichment/Bundle/PdfGeneration/Builder/DompdfBuilder.php
src/Akeneo/Pim/Enrichment/Bundle/PdfGeneration/HtmlFormatter/ArabicHtmlFormatter.php
src/Akeneo/Pim/Enrichment/Bundle/PdfGeneration/HtmlFormatter/HtmlFormatter.php
src/Akeneo/Pim/Enrichment/Bundle/Resources/config/builders.yml
src/Akeneo/Pim/Enrichment/Bundle/Resources/config/html_formatter.yml
symfony.lock
tests/back/Pim/Enrichment/Specification/Bundle/PdfGeneration/HtmlFormatter/ArabicHtmlFormatterSpec.php

Backport of https://github.com/akeneo/pim-community-dev/pull/16269/files
See https://akeneo.atlassian.net/browse/PIM-10259

PIM-10318: [Backport PIM-10259] Add ArPHP library and fix Arabic RTL in PDF Exports

---

upgrades/schema/Version_7_0_20220314113925_add_has_outdated_scopes_to_connected_app_table.php
upgrades/test_schema/Version_7_0_20220314113925_add_has_outdated_scopes_to_connected_app_table_Integration.php

Added `hasOutdatedScopes` to `akeneo_connectivity_connected_app` table as TINYINT boolean that default to false

CXP-1143: hasOutdatedScopes migration

---

src/Akeneo/Pim/Enrichment/Product/back/API/Command/UserIntent/SetNumberValue.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductIntegration.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/API/Command/UpsertProductCommandSpec.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/API/Command/UserIntent/SetNumberValueSpec.php

CPM-561 set string as type of value property of setNumberValue

---

src/Akeneo/Tool/Bundle/StorageUtilsBundle/Doctrine/Common/Remover/BaseRemover.php

See https://github.com/akeneo/pim-community-dev/pull/16576

Fix duplicated PRE_REMOVE event

---

src/Akeneo/Connectivity/Connection/back/Domain/Apps/Model/ConnectedApp.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Install/CreateAppTableQuery.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Persistence/DenormalizeConnectedAppTrait.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Persistence/FindAllConnectedAppsQuery.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Persistence/FindOneConnectedAppByConnectionCodeQuery.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Persistence/FindOneConnectedAppByIdQuery.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Apps/Internal/GetAllConnectedAppsActionEndToEnd.php
src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Apps/Internal/GetConnectedAppActionEndToEnd.php
src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/Persistence/CreateConnectedAppQueryIntegration.php
src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Domain/Apps/Model/ConnectedAppSpec.php
src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApps/ConnectedAppCard.tsx
src/Akeneo/Connectivity/Connection/front/src/model/Apps/connected-app.ts
src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApp/ConnectedAppAuthorizations.test.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApp/ConnectedAppContainer.test.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApp/ConnectedAppSettings.test.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApp/ErrorMonitoring/ConnectAppErrorMonitoring.test.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApps/ConnectedAppCard.test.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApps/ConnectedAppsContainer.test.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApps/ConnectedTestAppList.test.tsx

CXP-1128: add a visual indicator in Connected Apps

---

src/Akeneo/Pim/Structure/Bundle/Resources/config/updaters.yml
src/Akeneo/Pim/Structure/Component/Updater/AttributeUpdater.php
tests/back/Pim/Structure/Specification/Component/Updater/AttributeUpdaterSpec.php

https://akeneo.atlassian.net/browse/API-1597

API-1597: Attribute endpoints issue with group_labels

---

src/Akeneo/Pim/Enrichment/Bundle/Resources/config/array_converter.yml
src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/StandardToFlat/Product.php
src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/StandardToFlat/Product/QualityScoreConverter.php
src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/StandardToFlat/ProductModel.php
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/filters.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_product_model_export_edit.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_product_model_export_edit.yml
tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/StandardToFlat/Product/QualityScoreConverterSpec.php
tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/StandardToFlat/ProductModelSpec.php
tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/StandardToFlat/ProductSpec.php

Add export filter for product model

[PLG-727] display export product model filter

---

src/Akeneo/Pim/Enrichment/Bundle/Resources/config/array_converter.yml
src/Akeneo/Pim/Enrichment/Bundle/Resources/config/processors.yml
src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/StandardToFlat/Product.php
src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/StandardToFlat/Product/QualityScoreConverter.php
src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/StandardToFlat/ProductModel.php
src/Akeneo/Pim/Enrichment/Component/Product/Connector/Processor/Normalization/GetNormalizedProductModelQualityScores.php
src/Akeneo/Pim/Enrichment/Component/Product/Connector/Processor/Normalization/GetNormalizedProductQualityScores.php
src/Akeneo/Pim/Enrichment/Component/Product/Connector/Processor/Normalization/GetNormalizedQualityScoresInterface.php
src/Akeneo/Pim/Enrichment/Component/Product/Connector/Processor/Normalization/ProductProcessor.php
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/filters.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_product_model_export_edit.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_product_model_export_edit.yml
tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/StandardToFlat/Product/QualityScoreConverterSpec.php
tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/StandardToFlat/ProductModelSpec.php
tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/StandardToFlat/ProductSpec.php
tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Processor/Normalization/GetNormalizedProductModelQualityScoresSpec.php
tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Processor/Normalization/GetNormalizedProductQualityScoresSpec.php
tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Processor/Normalization/ProductProcessorSpec.php

PLG-727: Expose product models scores in exports

---

src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Install/InitializeJobs.php
upgrades/schema/Version_6_0_20210531152335_dqi_launch_recompute_products_scores.php
upgrades/test_schema/Version_6_0_20210531152335_dqi_launch_recompute_products_scores_Integration.php

PIM-10344: The migration fails when upgrading the PIM v5 to PIM v6

---

src/Akeneo/Pim/Enrichment/Product/back/Application/Applier/SetEnabledApplier.php
src/Akeneo/Pim/Enrichment/Product/back/Application/Applier/UserIntentApplier.php
src/Akeneo/Pim/Enrichment/Product/back/Application/Applier/UserIntentApplierRegistry.php
src/Akeneo/Pim/Enrichment/Product/back/Application/UpsertProductHandler.php
src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Symfony/DependencyInjection/AkeneoPimEnrichmentProductExtension.php
src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Symfony/Resources/config/appliers.yml
src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Symfony/Resources/config/handlers.yml
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Application/Applier/UserIntentApplierRegistrySpec.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Application/UpsertProductHandlerSpec.php

CPM-500 add user intent applier registry

---

.circleci/jobs/build_and_deploy.yml
.circleci/workflows/editions/community.yml
CHANGELOG-6.0.md
docker-compose.yml
src/Akeneo/Pim/Enrichment/Bundle/PdfGeneration/Builder/DompdfBuilder.php
src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Completeness/VariantProductRatio.php
src/Akeneo/Pim/Structure/Bundle/Query/PublicApi/AttributeOption/Sql/SqlSearchAttributeOptions.php
upgrades/.php_cd.php
upgrades/schema/Version_6_0_20210531152335_dqi_launch_recompute_products_scores.php
upgrades/test_schema/Version_6_0_20210531152335_dqi_launch_recompute_products_scores_Integration.php

PIM-10343: Pull-up 6.0=> master

---

src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/AttributeMessageBuilder.tsx
src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/KeyIndicatorAboutAttributes.tsx
src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/KeyIndicatorAboutProducts.tsx
src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/KeyIndicators.tsx
src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/ProductMessageBuilder.tsx
src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/keyIndicatorDescriptorsCE.tsx
src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/user-actions/followKeyIndicatorResult.ts
src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Application/component/Dashboard/KeyIndicators/KeyIndicatorAboutAttributes.unit.tsx
src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/Application/component/Dashboard/KeyIndicators/KeyIndicatorAboutProducts.unit.tsx

Requested modifications following code review on previous eponymous PR.

PLG-770 post-merge CR fixes

---

composer.json
composer.lock

https://akeneo.atlassian.net/browse/API-1679
Newer version than #15899 BH-1009

API-1679: Upgrade google/cloud-pubsub to ^1.35.0

---

src/Akeneo/Connectivity/Connection/back/Domain/Apps/Persistence/GetAllConnectedAppsPublicIdsInterface.php
src/Akeneo/Connectivity/Connection/back/Domain/Apps/Persistence/GetAllPendingAppsPublicIdsQueryInterface.php
src/Akeneo/Connectivity/Connection/back/Domain/Marketplace/Model/App.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Persistence/GetAllConnectedAppsPublicIdsQuery.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Persistence/GetAllPendingAppsPublicIdsQuery.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Marketplace/Persistence/GetAllAppsQuery.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Apps/queries.yml
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Marketplace/queries.yml
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Marketplace/Controller/Internal/GetAllAppsEndToEnd.php
src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Marketplace/Controller/Internal/GetAllTestAppsActionEndToEnd.php
src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/Persistence/GetAllConnectedAppsPublicIdsQueryIntegration.php
src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/Persistence/GetAllPendingAppsPublicIdsQueryIntegration.php
src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Domain/Marketplace/Model/AppSpec.php
src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Marketplace/Persistence/GetAllAppsQuerySpec.php
src/Akeneo/Connectivity/Connection/front/src/connect/components/ActivateAppButton.tsx
src/Akeneo/Connectivity/Connection/front/src/connect/components/Marketplace.tsx
src/Akeneo/Connectivity/Connection/front/src/connect/components/TestApp/TestAppList.tsx
src/Akeneo/Connectivity/Connection/front/src/model/app.ts
src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ActiveAppButton.test.tsx

CXP-1140: Displays pending Apps in the App Store

---

CHANGELOG-5.0.md
src/Akeneo/Pim/Enrichment/Bundle/Resources/config/array_converter.yml
src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductGrid/ProductModelImagesFromCodes.php
src/Akeneo/Pim/Enrichment/Component/Category/Connector/ArrayConverter/FlatToStandard/Category.php
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/filter/attribute/attribute.js
tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductGrid/ProductModelImagesFromCodesIntegration.php
tests/back/Pim/Enrichment/Specification/Component/Category/Connector/ArrayConverter/FlatToStandard/CategorySpec.php
tests/legacy/features/pim/enrichment/product-model/classify_product_model.feature
tests/legacy/features/pim/enrichment/product/mass-edit/mass_edit_products_and_product_models.feature

Pim 10356: Pullup 5.0=>6.0

---

src/Akeneo/Pim/Enrichment/Product/back/API/Command/UserIntent/AddAssetValue.php
src/Akeneo/Pim/Enrichment/Product/back/API/Command/UserIntent/RemoveAssetValue.php
src/Akeneo/Pim/Enrichment/Product/back/API/Command/UserIntent/SetAssetValue.php
src/Akeneo/Pim/Enrichment/Product/back/Application/Applier/AddAssetValueApplier.php
src/Akeneo/Pim/Enrichment/Product/back/Application/Applier/RemoveAssetValueApplier.php
src/Akeneo/Pim/Enrichment/Product/back/Application/Applier/SetAssetValueApplier.php
src/Akeneo/Pim/Enrichment/Product/back/Application/UpsertProductHandler.php
src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Symfony/Resources/config/appliers.yml
src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductIntegration.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/API/Command/UpsertProductCommandSpec.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/API/Command/UserIntent/AddAssetValueSpec.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/API/Command/UserIntent/RemoveAssetValueSpec.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/API/Command/UserIntent/SetAssetValueSpec.php

Add: 
- SetAssetValue
- AddAssetValue
- RemoveAssetValue

CPM-553: Add Asset related UserIntents

---

src/Akeneo/Pim/Enrichment/Product/back/Application/Applier/AddMultipleValuesApplier.php
src/Akeneo/Pim/Enrichment/Product/back/Application/Applier/ClearValueApplier.php
src/Akeneo/Pim/Enrichment/Product/back/Application/Applier/RemoveFamilyApplier.php
src/Akeneo/Pim/Enrichment/Product/back/Application/Applier/SetDateValueApplier.php
src/Akeneo/Pim/Enrichment/Product/back/Application/Applier/SetFamilyApplier.php
src/Akeneo/Pim/Enrichment/Product/back/Application/Applier/SetMetricValueApplier.php
src/Akeneo/Pim/Enrichment/Product/back/Application/Applier/SetMultipleValuesApplier.php
src/Akeneo/Pim/Enrichment/Product/back/Application/Applier/SetSingleValueApplier.php
src/Akeneo/Pim/Enrichment/Product/back/Application/UpsertProductHandler.php
src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Symfony/Resources/config/appliers.yml
src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Symfony/Resources/config/handlers.yml
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Application/Applier/AddMultipleValuesApplierSpec.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Application/Applier/ClearValueApplierSpec.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Application/Applier/RemoveFamilyApplierSpec.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Application/Applier/SetDateValueApplierSpec.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Application/Applier/SetFamilyApplierSpec.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Application/Applier/SetMetricValueApplierSpec.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Application/Applier/SetMultipleValuesApplierSpec.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Application/Applier/SetSingleValueApplierSpec.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Application/UpsertProductHandlerSpec.php

Add :
- AddMultipleValuesApplier
- ClearValueApplier
- RemoveFamilyApplier
- SetDateValueApplier
- SetFamilyApplier
- SetMetricValueApplier
- SetMultipleValuesApplier
- SetSingleValueApplier

CPM-564: Add UserIntents appliers for the registry

---

front-packages/akeneo-design-system/src/components/Input/MediaFileInput/MediaFileInput.tsx

In this PR we changed how the image fit in the div 
**Before**
**After**

RAC-1214: [Shared Catalogs] Displayed logo not resized

---

src/Akeneo/Connectivity/Connection/back/Application/Apps/Command/DeleteAppHandler.php
src/Akeneo/Connectivity/Connection/back/Domain/Apps/Persistence/IsAccessTokenRevokedQueryInterface.php
src/Akeneo/Connectivity/Connection/back/Domain/Apps/Persistence/SaveRevokedAccessTokensOfDisconnectedAppQueryInterface.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/EventSubscriber/AccessDeniedForRevokedAppTokenEventSubscriber.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Install/CreateRevokedAppTokenTableQuery.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Install/InstallSubscriber.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Persistence/IsAccessTokenRevokedQuery.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Persistence/SaveRevokedAccessTokensOfDisconnectedAppQuery.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/EventSubscriber/ApiAuthenticationEventSubscriber.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/EventSubscriber/ConnectionContextEventSubscriber.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/DependencyInjection/AkeneoConnectivityConnectionExtension.php
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Apps/event_subscribers.yml
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Apps/handlers.yml
src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Apps/queries.yml
src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/Command/DeleteAppHandlerIntegration.php
src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/EventSubscriber/AccessDeniedForRevokedAppTokenEventSubscriberIntegration.php
src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/Persistence/IsAccessTokenRevokedQueryIntegration.php
src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/Persistence/SaveRevokedAccessTokensOfDisconnectedAppQueryIntegration.php
src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Apps/Command/DeleteAppHandlerSpec.php
src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/EventSubscriber/ApiAuthenticationEventSubscriberSpec.php
src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/EventSubscriber/ConnectionContextEventSubscriberSpec.php
src/Akeneo/Tool/Bundle/ApiBundle/Security/OAuth2.php
src/Akeneo/Tool/Bundle/ApiBundle/spec/Security/OAuth2Spec.php
src/Akeneo/Tool/Component/Api/Event/ApiAuthenticationEvent.php
src/Akeneo/Tool/Component/Api/Event/ApiAuthenticationFailedEvent.php
src/Akeneo/Tool/Component/Api/spec/Event/ApiAuthenticationEventSpec.php
upgrades/schema/Version_7_0_20220318150000_add_revoked_app_token_table.php
upgrades/test_schema/Version_7_0_20220318150000_add_revoked_app_token_table_Integration.php

This PR is easy to review, commit by commit.
Before
After

CXP-1125: Better error message when the App Access Token has been revoked

---

src/Akeneo/Pim/Enrichment/Bundle/Command/MigrateToUuid/MigrateToUuidAddTriggers.php

The previous version of the trigger automatically added the UUID of foreign columns, when
- the INSERT query inserts lines from product ids
- the product has a filled uuid in the pim_catalog_product table
This ensure that the foreign uuid column is always filled, because the current version of the PIM only do INSERT queries with product ids.
We are currently working on moving the code to update the queries to do INSERT queries with product uuids instead of product ids. But, as there are still constraints (on primary keys, on foreign constraints...), we need the foreign product id columns to be filled.
So, we updated the trigger to automatically add the ID of foreign columns, when
- the INSERT query inserts lines from product uuids,
- the product has a filled uuid in the …

CPM-573: Fix triggers

---

src/Akeneo/Pim/Enrichment/Product/back/API/Command/UserIntent/AddCategories.php
src/Akeneo/Pim/Enrichment/Product/back/API/Command/UserIntent/RemoveCategories.php
src/Akeneo/Pim/Enrichment/Product/back/Application/Applier/AddCategoriesApplier.php
src/Akeneo/Pim/Enrichment/Product/back/Application/Applier/RemoveCategoriesApplier.php
src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Symfony/Resources/config/appliers.yml
src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Symfony/Resources/config/validators.yml
src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Validation/ShouldStayOwnerOfTheProductValidator.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductIntegration.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductWithPermissionIntegration.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/API/Command/UserIntent/AddCategoriesSpec.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/API/Command/UserIntent/RemoveCategoriesSpec.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Application/Applier/AddCategoriesApplierSpec.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Application/Applier/RemoveCategoriesApplierSpec.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Infrastructure/Validation/ShouldStayOwnerOfTheProductValidatorSpec.php

CPM-551: AddCategories and RemoveCategories user intents

---

CHANGELOG-6.0.md
src/Akeneo/UserManagement/Bundle/Provider/CustomUserChecker.php
src/Akeneo/UserManagement/Bundle/Resources/config/services.yml
src/Akeneo/UserManagement/Component/Model/User.php
tests/back/UserManagement/Specification/Bundle/Provider/CustomUserCheckerSpec.php
tests/back/UserManagement/Specification/Component/Model/UserSpec.php

backport of https://github.com/akeneo/pim-community-dev/pull/16199

PIM-10321: [Backport PIM-10241] Fix user account disabled can connect regression

---

src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Elasticsearch/Query/GetProductKeyIndicatorsQuery.php

DQI : Ignore submodels in ES queries for key indicators concerning product models.

PLG-821 fix(DQI) keyindicator ES queries for product models : ignoring submodels

---

src/Akeneo/Pim/Enrichment/Product/back/API/Command/UserIntent/SetSimpleReferenceEntityValue.php
src/Akeneo/Pim/Enrichment/Product/back/Application/Applier/SetSimpleReferenceEntityValueApplier.php
src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Symfony/Resources/config/appliers.yml
src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductIntegration.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/API/Command/UpsertProductCommandSpec.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/API/Command/UserIntent/SetSimpleReferenceEntityValueSpec.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Application/Applier/SetSimpleReferenceEntityValueApplierSpec.php

CPM-554 create setSimpleReferenceEntityValue user intent

---

CHANGELOG-6.0.md
config/packages/framework.yml
config/packages/security.yml

Backport of https://github.com/akeneo/pim-community-dev/pull/16099/files
See https://akeneo.atlassian.net/browse/PIM-10229

PIM-10325: [Backport PIM-10229] [CE] Enforce strict samesite policy for session cookies

---

src/Akeneo/Pim/Enrichment/Product/back/API/Command/UserIntent/AddMultiReferenceEntityValue.php
src/Akeneo/Pim/Enrichment/Product/back/API/Command/UserIntent/RemoveMultiReferenceEntityValue.php
src/Akeneo/Pim/Enrichment/Product/back/API/Command/UserIntent/SetMultiReferenceEntityValue.php
src/Akeneo/Pim/Enrichment/Product/back/Application/Applier/AddMultiReferenceEntityValueApplier.php
src/Akeneo/Pim/Enrichment/Product/back/Application/Applier/RemoveMultiReferenceEntityValueApplier.php
src/Akeneo/Pim/Enrichment/Product/back/Application/Applier/SetMultiReferenceEntityValueApplier.php
src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Symfony/Resources/config/appliers.yml
src/Akeneo/Pim/Enrichment/Product/back/Test/Helper/FeatureHelper.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductIntegration.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/API/Command/UserIntent/AddMultiReferenceEntityValueSpec.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/API/Command/UserIntent/RemoveMultiReferenceEntityValueSpec.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/API/Command/UserIntent/SetMultiReferenceEntityValueSpec.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Application/Applier/AddMultiReferenceEntityValueApplierSpec.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Application/Applier/RemoveMultiReferenceEntityValueApplierSpec.php

CPM-555 create userIntent to set, add and remove multi reference entity values

---

CHANGELOG-6.0.md
std-build/migration/prepare_50_to_60.sh

See https://github.com/akeneo/pim-enterprise-dev/pull/13279

PIM-10369: Update upgrade 5.0 to 6.0 preparation steps

---

src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApps/ConnectedAppCard.tsx
src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApps/ConnectedAppCardDescription.tsx
src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApps/ConnectedAppsContainer.tsx
src/Akeneo/Connectivity/Connection/front/src/connect/hooks/use-connected-apps.ts
src/Akeneo/Connectivity/Connection/front/src/model/Apps/connected-app.ts
src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApps/ConnectedAppCard.test.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApps/ConnectedAppsContainer.test.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/connect/hooks/use-connected-apps.test.ts

This is a copy of https://github.com/akeneo/pim-community-dev/pull/16602 but this time, on master because the feature branch used is not ready.

CXP-1138: display warning when the connected app is not listed

---

src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApps/ConnectedAppCardDescription.tsx

The change introduced in https://github.com/akeneo/pim-community-dev/pull/16672 was affecting test Apps.
This PR fix it.

CXP-1138: fix NotListed on the App Store for test apps

---

src/Akeneo/Pim/Enrichment/Bundle/Command/MigrateToUuid/MigrateToUuidCreateColumns.php
src/Akeneo/Pim/Enrichment/Bundle/Command/MigrateToUuid/MigrateToUuidFillForeignUuid.php
src/Akeneo/Pim/Enrichment/Bundle/Command/MigrateToUuid/MigrateToUuidReindexElasticsearch.php
src/Akeneo/Pim/Enrichment/Bundle/Command/MigrateToUuid/MigrateToUuidStep.php
src/Akeneo/Tool/Bundle/ElasticsearchBundle/Client.php
src/Akeneo/Tool/Bundle/ElasticsearchBundle/spec/ClientSpec.php
tests/back/Pim/Enrichment/Integration/Product/MigrateToUuidCommandIntegration.php
tests/back/Pim/Enrichment/Integration/Product/UuidMigration/AbstractMigrateToUuidTestCase.php

CPM-549: Migration fixes

---

src/Akeneo/Pim/Enrichment/Product/back/API/Command/UserIntent/SetIdentifierValue.php
src/Akeneo/Pim/Enrichment/Product/back/Application/Applier/SetSingleValueApplier.php
src/Akeneo/Pim/Enrichment/Product/back/Application/Applier/UserIntentApplier.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductIntegration.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/API/Command/UserIntent/SetIdentifierValueSpec.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Application/Applier/SetSingleValueApplierSpec.php

CPM-552: Add SetIdentifierValue user intent

---

.circleci/config.yml
.circleci/jobs/build_and_deploy.yml

In this PR: 
- I used clone shallow like in EE (https://github.com/akeneo/pim-enterprise-dev/pull/13024) in order to improve CI performance
- I used dynamic key for cache like in EE: https://github.com/akeneo/pim-enterprise-dev/pull/12350

Use shallow clone in order to improve CI

---

CHANGELOG-6.0.md
src/Akeneo/Pim/Enrichment/Bundle/Cursor/SequentialEditProduct.php
src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/AbstractCursor.php
src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Cursor.php
src/Akeneo/Tool/Bundle/ElasticsearchBundle/Cursor/AbstractCursor.php
src/Akeneo/Tool/Bundle/ElasticsearchBundle/Cursor/Cursor.php
src/Akeneo/Tool/Bundle/ElasticsearchBundle/Cursor/SearchAfterSizeCursor.php
src/Akeneo/Tool/Bundle/ElasticsearchBundle/spec/Cursor/CursorSpec.php
src/Akeneo/Tool/Bundle/ElasticsearchBundle/spec/Cursor/SearchAfterSizeCursorSpec.php
tests/back/Pim/Enrichment/Integration/PQB/UpdateProductsWhenElasticsearchIsDesynchronisedIntegration.php
tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/CursorSpec.php

Backport of https://github.com/akeneo/pim-community-dev/pull/16189
See https://akeneo.atlassian.net/browse/PIM-10324

PIM-10324: Backport PIM-10232 fix on the "Error a new entity was found in the relationship..." error during jobs

---

src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductIntegration.php

TIP-1557: enable reference entity feature flags

---

src/Akeneo/Pim/Enrichment/Product/back/Application/Applier/AssociationUserIntentCollectionApplier.php
src/Akeneo/Pim/Enrichment/Product/back/Domain/Query/GetNonViewableProducts.php
src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Query/GetNonViewableProducts.php
src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Symfony/Resources/config/appliers.yml
src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Symfony/Resources/config/queries.yml
src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/EnrichmentProductTestCase.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductAssociationsIntegration.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductVariantIntegration.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductWithPermissionIntegration.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Application/Applier/AssociationUserIntentCollectionApplierSpec.php

CPM-558: Add query to fetch non viewable products in list

---

src/Akeneo/Pim/Enrichment/Product/back/Application/Applier/AssociationUserIntentCollectionApplier.php
src/Akeneo/Pim/Enrichment/Product/back/Domain/Query/GetViewableProducts.php
src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Query/GetViewableProducts.php
src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Symfony/Resources/config/appliers.yml
src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Symfony/Resources/config/queries.yml
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Application/Applier/AssociationUserIntentCollectionApplierSpec.php

Rename GetNonViewableProducts into GetViewableProducts

CPM-558: Rename GetNonViewableProducts into GetViewableProducts

---

src/Akeneo/Pim/Structure/Component/Query/PublicApi/Family/RequiredAttributesMask.php

PLG-792: add getFamilyCode for RequiredAttributeMask

---

src/Akeneo/Pim/Enrichment/Bundle/Command/MigrateToUuid/MigrateToUuidCommand.php
src/Akeneo/Pim/Enrichment/Bundle/Command/MigrateToUuid/MigrateToUuidCreateIndexes.php
src/Akeneo/Pim/Enrichment/Bundle/Command/MigrateToUuid/MigrateToUuidFillForeignUuid.php
src/Akeneo/Pim/Enrichment/Bundle/Command/MigrateToUuid/MigrateToUuidFillProductUuid.php
src/Akeneo/Pim/Enrichment/Bundle/Command/MigrateToUuid/MigrateToUuidReindexElasticsearch.php

- Add more information in log messages during migration
- Get the products to reindex by batches of 10000 to avoid having to refresh the index at each loop

Add information in log messages

---

src/Akeneo/Pim/Enrichment/Bundle/Command/MigrateToUuid/MigrateToUuidSetNotNullableUuidColumns.php
tests/back/Pim/Enrichment/Integration/Product/MigrateToUuidCommandIntegration.php

TODO: delete EE branch after merguez

Cpm 597 Update the migration to set nullable pim_versioning_version.resource_id

---

src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Command/LaunchEvaluationsCommand.php
src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/commands.yml
src/Akeneo/Pim/Enrichment/.php_cd.php
src/Akeneo/Pim/Enrichment/Bundle/Command/MigrateToUuid/MigrateToUuidCommand.php
src/Akeneo/Pim/Enrichment/Bundle/Command/MigrateToUuid/MigrateToUuidStep.php
src/Akeneo/Pim/Enrichment/Bundle/Command/MigrateToUuid/Utils/StatusAwareTrait.php
src/Akeneo/Pim/Enrichment/Bundle/Resources/config/cli_command.yml

This PR do 2 things:
- Prevent running the migration if there is a DQI evaluation job in progress
- Prevent running DQI evaluation job if migration in progress

CPM-572: Don't run DQI and migration in the same time

---

src/Akeneo/Pim/Enrichment/Bundle/Command/MigrateToUuid/MigrateToUuidCreateIndexes.php
src/Akeneo/Pim/Enrichment/Bundle/Command/MigrateToUuid/MigrateToUuidFillForeignUuid.php

CPM-581: Delete temporary index on pim_versioning_version

---

CHANGELOG-6.0.md
src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/hooks/usePimVersion.ts
src/Akeneo/Platform/Bundle/UIBundle/tests/front/unit/components/PimVersion.unit.tsx

PIM-10400: Pull up 6.0 => master

---

src/Akeneo/Pim/Enrichment/Product/back/API/Command/UserIntent/SetMeasurementValue.php
src/Akeneo/Pim/Enrichment/Product/back/Application/Applier/SetMeasurementValueApplier.php
src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Symfony/Resources/config/appliers.yml
src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Symfony/Resources/config/validation/product_commands.yml
src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductIntegration.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/API/Command/UpsertProductCommandSpec.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/API/Command/UserIntent/SetMeasurementValueSpec.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Application/Applier/SetMeasurementValueApplierSpec.php

Rename classes and tests names but kept DB attribute 'a_metric' and 'metric' in exception's message to avoid breaking another BC.
TODO: delete EE branch after mergez

CPM-598 rename setMetricValue intent to setMeasurementValue

---

.circleci/workflows/pull_request.yml
tests/legacy/features/Behat/Decorator/Page/GridCapableDecorator.php

Add two methods to tests the visibility of the view switcher.

TIP-1560: twa feature flag

---

CHANGELOG-6.0.md
src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Versioning/EntityWithQuantifiedAssociations/QuantifiedAssociationsNormalizer.php
src/Akeneo/Pim/Enrichment/Component/Product/Updater/Validator/QuantifiedAssociationsStructureValidator.php
tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/QuantifiedAssociations/UpdateQuantifiedAssociationsInProductEndToEnd.php
tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/QuantifiedAssociations/ValidateQuantifiedAssociationsInProductEndToEnd.php
tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/QuantifiedAssociations/ValidateQuantifiedAssociationsInProductModelEndToEnd.php
tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/Versioning/EntityWithQuantifiedAssociations/QuantifiedAssociationsNormalizerSpec.php
tests/back/Pim/Enrichment/Specification/Component/Product/Updater/Validator/QuantifiedAssociationsStructureValidatorSpec.php

https://akeneo.atlassian.net/browse/PIM-10332
Backport of https://github.com/akeneo/pim-community-dev/pull/16521

[Backport] PIM-10332: Fix error when using an association with quantities having an numeric code

---

src/Akeneo/Pim/Enrichment/Product/back/API/Command/UserIntent/Association/AssociateGroups.php
src/Akeneo/Pim/Enrichment/Product/back/API/Command/UserIntent/Association/DissociateGroups.php
src/Akeneo/Pim/Enrichment/Product/back/API/Command/UserIntent/Association/ReplaceAssociatedGroups.php
src/Akeneo/Pim/Enrichment/Product/back/Application/Applier/AssociationUserIntentCollectionApplier.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductAssociationsIntegration.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/API/Command/UserIntent/Association/AssociateGroupsSpec.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/API/Command/UserIntent/Association/DissociateGroupsSpec.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/API/Command/UserIntent/Association/ReplaceAssociatedGroups.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/API/Command/UserIntent/Association/ReplaceAssociatedGroupsSpec.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Application/Applier/AssociationUserIntentCollectionApplierSpec.php

Add following user intents:
- AssociateGroups
- DissociateGroups
- ReplaceGroups

CPM-560: Add group associations user intents

---

src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/form_extensions.yml

CXP-1171: Remove the new tag on the Connected apps submenu

---

src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Service/UpdateConnectedAppRoleWithScopes.php

When the app requests less scopes, we need to **explicitly** remove related ACLs from the role associated with this app.

CXP-1062: fix app role acls update when scopes are removed

---

src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Settings/Client/Fos/CreateClientSpec.php
src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Settings/Client/Fos/DeleteClientSpec.php
src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Settings/Client/Fos/FosRegenerateClientSecretSpec.php

These specs were not executed, because they have a wrong namespace

Fix spec namespace

---

src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/Db/AddUuidColumnsSubscriber.php
upgrades/schema/Version_7_0_20220415090329_add_uuid_column_for_comment.php

CPM-607: add pim_comment_comment.resource_uuid column

---

src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Webhook/routing.yml

OCT-38: fix missing routes

---

make-file/connectivity-connection.mk

After a refacto some specs had not been moved correctly and the master CI failed. Here is a fix to ensure specs are all run and there is no diff between the total number of specs and the number of ran specs.
Here is what it looks like in the CI when it fails:

Cxp ci spec

---

src/Akeneo/Pim/Enrichment/Bundle/Command/MigrateToUuid/MigrateToUuidCreateIndexes.php
src/Akeneo/Pim/Enrichment/Bundle/Command/MigrateToUuid/MigrateToUuidFillForeignUuid.php
src/Akeneo/Pim/Enrichment/Bundle/Command/MigrateToUuid/MigrateToUuidSetNotNullableUuidColumns.php
src/Akeneo/Pim/Enrichment/Bundle/Command/MigrateToUuid/MigrateToUuidStep.php
tests/back/Pim/Enrichment/Integration/Product/MigrateToUuidCommandIntegration.php

To make the CI pass, we need to merge CPM-607 on master and rebase adr-uuid (and this PR) from master

CPM-608: add pim_comment_comment in the migration

---

src/Akeneo/Tool/Bundle/MessengerBundle/Transport/GooglePubSub/PubSubClientFactory.php

Use rest api instead of grpc for pubsub

PIM-10278: try fixing `DEADLINE_EXCEEDED` (#16308)

---

CHANGELOG.md
src/Akeneo/UserManagement/Bundle/EventListener/LocaleSubscriber.php

Fix the locale when calls are made by API : en_US always.

PIM-10251: fix locale on API call

---

src/Akeneo/Pim/Structure/Bundle/Resources/config/normalizers.yml
src/Akeneo/Pim/Structure/Component/Normalizer/Standard/AttributeNormalizer.php
tests/back/Pim/Structure/Specification/Component/Normalizer/Standard/AttributeNormalizerSpec.php

Read only attribute prevent any edit of an attribute in the UI.
It's still editable in import, API, etc (no security on backend side).

TIP-1563: add feature flag on product read only attribute

---

front-packages/shared/src/components/page/PageHeader.tsx
front-packages/shared/src/components/page/header/Title.tsx

See https://github.com/akeneo/pim-enterprise-dev/pull/13625

PIM-10422: add option to not transform text in title

---

src/Akeneo/Pim/Enrichment/Bundle/Command/MigrateToUuid/MigrateToUuidCleanCompletenessTable.php
src/Akeneo/Pim/Enrichment/Bundle/Command/MigrateToUuid/MigrateToUuidCommand.php
src/Akeneo/Pim/Enrichment/Bundle/Command/MigrateToUuid/MigrateToUuidCreateIndexes.php
src/Akeneo/Pim/Enrichment/Bundle/Command/MigrateToUuid/MigrateToUuidFillForeignUuid.php
src/Akeneo/Pim/Enrichment/Bundle/Command/MigrateToUuid/MigrateToUuidStep.php
src/Akeneo/Pim/Enrichment/Bundle/Resources/config/cli_command.yml
src/Akeneo/Tool/Bundle/ElasticsearchBundle/Client.php
tests/back/Pim/Enrichment/Integration/Product/MigrateToUuidCommandIntegration.php

Some final fixes for the feature branch:
- Add (and keep) temporary indexes which are only useful for the migration (they will be removed once every client is migrated)
- Clean pim_catalog_completeness table
- Prioritize the migration command over DQI-related jobs

Migration cron

---

src/Akeneo/Pim/Enrichment/Product/back/API/Command/UserIntent/SetImageValue.php
src/Akeneo/Pim/Enrichment/Product/back/Application/Applier/SetSingleValueApplier.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductIntegration.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/API/Command/UserIntent/SetFileValueSpec.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/API/Command/UserIntent/SetImageValueSpec.php

CPM-616 Add setImageValue UserIntent

---

tests/back/Acceptance/Product/InMemoryProductRepository.php
tests/back/Acceptance/spec/Product/InMemoryProductRepositorySpec.php

Needed for https://github.com/akeneo/pim-onboarder/pull/943

Implement InMemoryProductRepository's findOneBy

---

CHANGELOG-5.0.md
src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/ProductGridFilterController.php
src/Akeneo/UserManagement/Bundle/Resources/public/js/fields/product-grid-filters.ts

PIM-10424 [Backport] Increase product grid filters limit display in user settings

---

src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/system/src/components/SystemIndex.tsx

SSO should not be displayed and configurable in Serenity.
See https://github.com/akeneo/pim-enterprise-dev/pull/13658

TIP-1568: sso configuration depending of feature flags

---

.circleci/jobs/build_and_deploy.yml
.circleci/jobs/features/connectivity.yml
.circleci/jobs/features/other.yml

See https://github.com/akeneo/pim-enterprise-dev/pull/13669

Try to stabilize docker pull by updating Circle CI VM image

---

src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/ProductCommentController.php
src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Repository/CommentRepository.php
src/Akeneo/Pim/Enrichment/Bundle/Resources/config/doctrine/Comment/Comment.orm.yml
src/Akeneo/Pim/Enrichment/Component/Comment/Builder/CommentBuilder.php
src/Akeneo/Pim/Enrichment/Component/Comment/Model/Comment.php
src/Akeneo/Pim/Enrichment/Component/Comment/Model/CommentInterface.php
src/Akeneo/Pim/Enrichment/Component/Comment/Normalizer/Standard/CommentNormalizer.php
src/Akeneo/Pim/Enrichment/Component/Comment/Repository/CommentRepositoryInterface.php
tests/back/Pim/Enrichment/Specification/Component/Comment/Normalizer/Standard/CommentNormalizerSpec.php
tests/legacy/features/Context/FixturesContext.php
tests/legacy/features/Context/SecurityContext.php

Cpm 609 update pim_comment_comment table creation and fix code to use uuid

---

src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/ProductCommentController.php
src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Repository/CommentRepository.php
src/Akeneo/Pim/Enrichment/Bundle/Resources/config/doctrine/Comment/Comment.orm.yml
src/Akeneo/Pim/Enrichment/Component/Comment/Builder/CommentBuilder.php
src/Akeneo/Pim/Enrichment/Component/Comment/Model/Comment.php
src/Akeneo/Pim/Enrichment/Component/Comment/Model/CommentInterface.php
src/Akeneo/Pim/Enrichment/Component/Comment/Normalizer/Standard/CommentNormalizer.php
src/Akeneo/Pim/Enrichment/Component/Comment/Repository/CommentRepositoryInterface.php
tests/back/Pim/Enrichment/Specification/Component/Comment/Normalizer/Standard/CommentNormalizerSpec.php
tests/legacy/features/Context/FixturesContext.php
tests/legacy/features/Context/SecurityContext.php

CPM-609: Update pim_comment_comment table creation and fix code to use uuid

---

src/Akeneo/Pim/Enrichment/.php_cd.php
src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Repository/ExternalApi/CategoryRepository.php
src/Akeneo/Pim/Enrichment/Bundle/Resources/config/repositories.yml
src/Akeneo/Pim/Enrichment/Component/Validator/Constraints/Type.php
src/Akeneo/Pim/Enrichment/Component/Validator/Constraints/TypeValidator.php
src/Akeneo/Pim/Structure/Bundle/Doctrine/ORM/Repository/ExternalApi/AttributeGroupRepository.php
src/Akeneo/Pim/Structure/Bundle/Doctrine/ORM/Repository/ExternalApi/AttributeRepository.php
src/Akeneo/Pim/Structure/Bundle/Doctrine/ORM/Repository/ExternalApi/FamilyRepository.php
src/Akeneo/Pim/Structure/Bundle/Resources/config/repositories.yml
src/Akeneo/Pim/Structure/Bundle/Resources/config/validators.yml
src/Akeneo/Pim/Structure/Component/Validator/Constraints/Type.php
src/Akeneo/Pim/Structure/Component/Validator/Constraints/TypeValidator.php
tests/back/Pim/Enrichment/EndToEnd/Category/ExternalApi/GetCategoryEndToEnd.php
tests/back/Pim/Enrichment/Specification/Bundle/Doctrine/ORM/Repository/ExternalApi/CategoryRepositorySpec.php

fix(api-1586): update violation error message

---

src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApp/ConnectedAppAuthorizations.tsx
src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApp/ConnectedAppContainer.tsx
src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApp/ConnectedAppPermissions.tsx
src/Akeneo/Connectivity/Connection/front/src/connect/is-granted-on-product.ts
src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApp/ConnectedAppAuthorizations.test.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApp/ConnectedAppContainer.test.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApp/ConnectedAppPermissions.test.tsx
src/Akeneo/Connectivity/Connection/front/tests/src/connect/is-granted-on-product.test.tsx

CXP-1166: Adapt the level of permissions to the connected app scopes

---

.circleci/jobs/build_and_deploy.yml
.circleci/workflows/editions/community.yml
docker/Dockerfile_node

Bacjkport of https://github.com/akeneo/pim-community-dev/pull/16959
It builds pim-php-dev:6.0 and akeneo/node:14 every night

Improvement: Build Akeneo Docker images every night

---

src/Akeneo/Pim/Enrichment/Product/back/API/Command/UserIntent/PriceValue.php
src/Akeneo/Pim/Enrichment/Product/back/API/Command/UserIntent/SetPriceCollectionValue.php
src/Akeneo/Pim/Enrichment/Product/back/Application/Applier/SetPriceCollectionValueApplier.php
src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Symfony/Resources/config/appliers.yml
src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductIntegration.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/API/Command/UserIntent/PriceValueSpec.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/API/Command/UserIntent/SetPriceCollectionValueSpec.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Application/Applier/SetPriceCollectionValueApplierSpec.php

Not sure about the naming of the intents, maybe something else would be clearer

CPM-617: Implement SetPriceCollectionValue user intent for products

---

.github/CODEOWNERS

Add Chipmunks as migrations code owners to validate changes on products

Add Chipmunks as migrations code owners

---

src/Akeneo/Pim/Enrichment/Bundle/Resources/config/connector/use_cases.yml
src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/Validator/ListProductsQueryValidator.php
src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/Validator/ValidateIdentifiersLimit.php
tests/back/Pim/Enrichment/Specification/Component/Product/Connector/UseCase/Validator/ListProductsQueryValidatorSpec.php
tests/back/Pim/Enrichment/Specification/Component/Product/Connector/UseCase/Validator/ValidateIdentifiersLimitSpec.php

chore(api-1784): add limitation on IN filter for products

---

CHANGELOG.md
src/Akeneo/Pim/Enrichment/Bundle/Resources/config/normalizers.yml
src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/AxisValueLabelsNormalizer/BooleanNormalizer.php
tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/InternalApi/AxisValueLabelsNormalizer/BooleanNormalizerSpec.php

PIM-10427 Fix display of boolean value in variant axis

---

CHANGELOG-5.0.md
src/Akeneo/Pim/Enrichment/Component/Product/Comparator/Attribute/OptionComparator.php
src/Akeneo/Pim/Enrichment/Component/Product/Comparator/Attribute/OptionsComparator.php
src/Akeneo/Pim/Enrichment/Component/Product/Factory/NonExistentValuesFilter/NonExistentMultiSelectValuesFilter.php
src/Akeneo/Pim/Enrichment/Component/Product/Factory/NonExistentValuesFilter/NonExistentSimpleSelectValuesFilter.php
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/field/multi-select-field.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/field/simple-select-field.js
tests/back/Pim/Enrichment/Specification/Component/Product/Comparator/Attribute/OptionComparatorSpec.php
tests/back/Pim/Enrichment/Specification/Component/Product/Comparator/Attribute/OptionsComparatorSpec.php
tests/back/Pim/Enrichment/Specification/Component/Product/Factory/NonExistentValuesFilter/NonExistentMultiSelectValuesFilterSpec.php
tests/back/Pim/Enrichment/Specification/Component/Product/Factory/NonExistentValuesFilter/NonExistentSimpleSelectValuesFilterSpec.php

Backoprt of https://github.com/akeneo/pim-community-dev/pull/16751 and https://github.com/akeneo/pim-community-dev/pull/16899

PIM-10419: [Backport] PIM-10350: Fix simple and multi select filtering and comparison

---

CHANGELOG-5.0.md
config/packages/liip_imagine.yml
src/Akeneo/Platform/Bundle/UIBundle/Imagine/IccStripFilter.php
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/services.yml

Backport of https://github.com/akeneo/pim-enterprise-dev/pull/12298 & https://github.com/akeneo/pim-community-dev/pull/15888

PIM-10428: [Backport PIM-10049] Add custom strip filter to avoid segmentation fault

---

src/Akeneo/Pim/Enrichment/Product/back/API/Command/UserIntent/SetTableValue.php
src/Akeneo/Pim/Enrichment/Product/back/Application/Applier/SetTableValueApplier.php
src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Symfony/Resources/config/appliers.yml
src/Akeneo/Pim/Enrichment/Product/back/Test/Helper/FeatureHelper.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductIntegration.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/API/Command/UserIntent/SetTableValueSpec.php
src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Application/Applier/SetTableValueApplierSpec.php

CPM-624 add SetTableValue user intent

---

CHANGELOG.md
src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/ListProductModelsQueryHandler.php
src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/ListProductsQueryHandler.php
tests/back/Pim/Enrichment/Specification/Component/Product/Connector/UseCase/ListProductModelsQueryHandlerSpec.php

PIM-10435: Fix strtolower on search_after with accents

---

src/Akeneo/Connectivity/Connection/front/src/connect/components/AppWizard/AppWizard.tsx
src/Akeneo/Connectivity/Connection/front/src/connect/components/AppWizard/steps/Permissions.tsx
src/Akeneo/Connectivity/Connection/front/src/connect/components/AppWizard/steps/PermissionsSummary.tsx
src/Akeneo/Connectivity/Connection/front/src/shared/permission-form-registry/permission-form-registry.interface.ts
src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/AppWizard/steps/Permissions.test.tsx
src/Akeneo/Connectivity/Connection/workspaces/permission-form/src/registry/PermissionFormRegistry.ts

CXP-1146: handle only display view permission during render summary

---

src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Query/ProductEvaluation/GetEvaluationResultsByProductsAndCriterionQueryInterface.php
src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/ValueObject/ProductIdCollection.php
src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/ValueObject/ProductModelIdCollection.php
src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetEvaluationResultsByProductModelsAndCriterionQuery.php
src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetEvaluationResultsByProductsAndCriterionQuery.php
src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetPendingCriteriaEvaluationsByProductIdsQuery.php
src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/queries.yml

Fix dqi phpstan tests

---

src/Akeneo/Pim/Enrichment/Component/Product/Comparator/Attribute/OptionComparator.php
src/Akeneo/Pim/Enrichment/Component/Product/Comparator/Attribute/OptionsComparator.php
tests/back/Pim/Enrichment/Specification/Component/Product/Comparator/Attribute/OptionComparatorSpec.php
tests/back/Pim/Enrichment/Specification/Component/Product/Comparator/Attribute/OptionsComparatorSpec.php

CPM-628: Fix error when partial update of a multiselect attribute with a string value

---

src/Akeneo/Pim/Enrichment/Bundle/Command/MigrateToUuid/MigrateToUuidCleanCompletenessTable.php

With the former implementation, the delete request used to lock tables for a long time, because the CTE took a really long time if the pim_catalog_product and pim_catalog_completeness had a lot of records (e.g several million each), thus possibly causing deadlocks.
With the new implementation, the DELETE query is distinct from the select query. (the select query is still quite long, but does not write lock tables), plus a search_after was added so that the query does not traverse the whole completeness table at each iteration, but rather starts over where it stopped at the last iteration 

Avoid deadlocks while cleaning completeness table

---

src/Akeneo/Channel/back/API/Query/FindAllEditableLocalesForUser.php
src/Akeneo/Channel/back/Infrastructure/Query/Cache/CachedFindAllEditableLocalesForUser.php
src/Akeneo/Channel/back/Infrastructure/Query/Cache/CachedFindAllViewableLocalesForUser.php
src/Akeneo/Channel/back/Infrastructure/Query/Sql/SqlFindAllEditableLocalesForUser.php
src/Akeneo/Channel/back/Infrastructure/Symfony/Resources/config/queries.yml
src/Akeneo/Channel/back/tests/Integration/Query/Sql/SqlFindAllEditableLocalesForUserIntegration.php
src/Akeneo/Channel/back/tests/Specification/Infrastructure/Query/Cache/CachedFindAllEditableLocalesForUserSpec.php

Add service API to retrieve all editable locales for given user

RAB-617: Retrieve all editable locales for user

---

.circleci/jobs/features/connectivity.yml
make-file/connectivity-connection.mk
src/Akeneo/Connectivity/Connection/tests/Context/Page/Connections/Index.php
src/Akeneo/Connectivity/Connection/tests/Context/SettingsContext.php
src/Akeneo/Connectivity/Connection/tests/Decorator/Settings/EditForm.php
src/Akeneo/Connectivity/Connection/tests/features/edit_connection.feature

Added a new Behat test to cover connection edit

CXP-1175: Added edit connection end to end behat test

---

src/Akeneo/Pim/Enrichment/Bundle/Command/MigrateToUuid/DummyMigrationAuthorization.php
src/Akeneo/Pim/Enrichment/Bundle/Command/MigrateToUuid/MigrateToUuidCommand.php
src/Akeneo/Pim/Enrichment/Bundle/Command/MigrateToUuid/MigrationAuthorization.php
src/Akeneo/Pim/Enrichment/Bundle/Resources/config/cli_command.yml

CPM-644: add MigrationAuthorization

---

CHANGELOG.md
src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/ProductGridFilterController.php

PIM-10443: Search for system product grid filters in System > Users > Additional is now case insensitive

---

src/Akeneo/Pim/Enrichment/Bundle/Command/MigrateToUuid/MigrateToUuidCommand.php

CPM-644: fix message

---

src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Infrastructure/Persistence/Repository/ProductScoreRepositoryIntegration.php

The tests on the "latest" scores and the purges are always good on a dev env, but are flaky on the CI.
As these two tests will become irrelevant with the PR https://github.com/akeneo/pim-community-dev/pull/16974 that will be merged soon, I decided to simply remove them now.

WSL-13: Fix flaky integration test (bis)
