akeneo/pim-community-dev

- .circleci/docker-compose.override.yml.dist
- docker-compose.yml
3.7 format is the latest compatible with our current requirements:
Akeneo doc: https://docs.akeneo.com/master/install_pim/docker/installation_docker.html
docker-compose compatibility table: https://docs.docker.com/compose/compose-file/compose-file-v3/
> BH-518: Upgrade docker-compose format to 3.7

- src/Akeneo/Connectivity/Connection/back/Domain/Webhook/Exception/ConnectionWebhookNotFoundException.php
- src/Akeneo/Connectivity/Connection/back/tests/.php_cd.php
Split Connectivity/Connection coupling detection by sub-context to highlight unnecessary dependencies.
> Improve coupling detector config for connectivity contexts

- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/AssociationTypesIndex.tsx
The Pagination component crash when the search returns no results because it's called with `currentPage=1` and `totalItems=0` 
As the current page is piloted by the search itself and always start at page 1 (no page 0) the simple solution is to not call the Pagination component if there are no results.
> PLG-64: Prevent pagination crash when empty search result

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/Bundle/PdfGeneration/Builder/DompdfBuilder.php
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/builders.yml
When exporting to PDF, no image was exported.
I added the chroot option to point to the correct directory.
> PIM-9771: Fix the image preview when exporting a product as pdf

- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/SettingsIndex.tsx
- src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/common/menu.yml
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/menu/menu.js
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/menu/tab.js
> PLG-226: Settings entry should not be displayed when a user has no right on Settings items

- CHANGELOG.md
- src/Oro/Bundle/PimFilterBundle/Filter/ProductValue/AbstractDateFilter.php
- src/Oro/Bundle/PimFilterBundle/spec/Filter/ProductValue/DateRangeFilterSpec.php
Here is the description of the error:
On the product grid, on the filter "Created at", select "less than", 
then set a date and save the filter.
Reopen the filter, select "more than" > the date "disappears".
If you don't input a new date and save the filter > error 500 
I tested this case, too:
On the product grid, on the filter "Created at", select "more than", 
then set a date and save the filter.
Reopen the filter, select "less than" > the date "disappears".
If you don't input a new date and save the filter > error 500, also.
So, I fixed the issue returning false in isValidData() function when 
-> $data['type'] is "more than" and if $data['value']['start'] is null
-> $data['type'] is "less than" and if $data['value']['end'] is null …
> PIM-9820: Fix the Error 500 on the product grid with the date filter

- CHANGELOG-4.0.md
- src/Akeneo/Pim/Enrichment/Bundle/Controller/Ui/FileController.php
Adding a special case for SVG images to return them as file response in the File controller in order to display them correctly as thumbnails, refactoring the whole image caching process for Ref entities would be a bit much for a released version patch
| Tech Doc …
> PIM-9818: Handle SVG image show action in file input

- CHANGELOG.md
- src/Oro/Bundle/PimFilterBundle/Filter/Product/FamilyFilter.php
- src/Oro/Bundle/PimFilterBundle/spec/Filter/Product/FamilyFilterSpec.php
PIM-9829: Fix product grid crash when using a family filter on a deleted family by ignoring the filter when the specified family is not found
> PIM-9829: Fix product grid crash when using a family filter on a deleted family

- config/packages/dev/monolog.yml
Currently all the logs output in the monolog channel `event_api` or `business_event` are silenced and not visible.
- Not in the log file
- Not in the `messenger:consume` command output (even with `--verbose` flag)
This make it really difficult to debug the Events API.
This is because the configuration is setup to ignore those logs for the `main` output (log file) and the `console` output.
The goal of this PR is to stop ignoring these monolog channels and use the default behaviors like other channels.
- For the `main` configuration, all the logs at the level `debug` and above will be sent to the log file
- For the `console` configuration (for the `messenger:consume` command) all the logs will be output directly according to  verbosity …
> Fix Events API logs output on dev env

- config/services/test_fake/services.yml
- make-file/test.mk
- phpunit.xml.dist
- src/Akeneo/Tool/Bundle/MeasureBundle/Application/CreateMeasurementFamily/CreateMeasurementFamilyHandler.php
- src/Akeneo/Tool/Bundle/MeasureBundle/Application/DeleteMeasurementFamily/DeleteMeasurementFamilyHandler.php
- src/Akeneo/Tool/Bundle/MeasureBundle/Application/SaveMeasurementFamily/SaveMeasurementFamilyHandler.php
- src/Akeneo/Tool/Bundle/MeasureBundle/Event/MeasurementFamilyCreated.php
- src/Akeneo/Tool/Bundle/MeasureBundle/Event/MeasurementFamilyDeleted.php
- src/Akeneo/Tool/Bundle/MeasureBundle/Event/MeasurementFamilyUpdated.php
- src/Akeneo/Tool/Bundle/MeasureBundle/Model/MeasurementFamily.php
- src/Akeneo/Tool/Bundle/MeasureBundle/Persistence/MeasurementFamilyRepository.php
- src/Akeneo/Tool/Bundle/MeasureBundle/Resources/config/services.yml
- src/Akeneo/Tool/Bundle/MeasureBundle/Validation/Common/LabelCollectionValidator.php
- src/Akeneo/Tool/Bundle/MeasureBundle/spec/Event/MeasurementFamilyCreatedSpec.php
- src/Akeneo/Tool/Bundle/MeasureBundle/spec/Event/MeasurementFamilyDeletedSpec.php
- src/Akeneo/Tool/Bundle/MeasureBundle/spec/Event/MeasurementFamilyUpdatedSpec.php
- src/Akeneo/Tool/Bundle/MeasureBundle/spec/Model/MeasurementFamilySpec.php
- src/Akeneo/Tool/Bundle/MeasureBundle/tests/Acceptance/CreateMeasurementFamilyTest.php
- src/Akeneo/Tool/Bundle/MeasureBundle/tests/Acceptance/DeleteMeasurementFamilyTest.php
- src/Akeneo/Tool/Bundle/MeasureBundle/tests/Acceptance/SaveMeasurementFamilyTest.php
- src/Akeneo/Tool/Bundle/MeasureBundle/tests/EndToEnd/InternalApi/CreateMeasurementFamilyActionEndToEnd.php
- src/Akeneo/Tool/Bundle/MeasureBundle/tests/EndToEnd/InternalApi/SaveMeasurementFamilyActionEndToEnd.php
- tests/back/Acceptance/EventDispatcher/EventDispatcherMock.php
Introduces Domain events for measurement families
- MeasurementFamilyCreated
- MeasurementFamilyUpdated
- MeasurementFamilyDeleted
Events are created & dispatched by the dedicated application services (ideally, they would have been created by the aggregate and dispatched by the repository, that was too much work).
⚠️ Acceptance & EndToEnd tests were not run by the CI, hence I added them in the phpunit config.
> RAC-575: Add Measurement family domain events + Fix CI configuration

- src/Akeneo/Tool/Bundle/MeasureBundle/PublicApi/Onboarder/FindAllMeasurementFamilies.php
- src/Akeneo/Tool/Bundle/MeasureBundle/PublicApi/Onboarder/MeasurementFamily.php
- src/Akeneo/Tool/Bundle/MeasureBundle/Resources/config/public_api.yml
- src/Akeneo/Tool/Bundle/MeasureBundle/tests/Integration/PublicApi/Onboarder/FindAllMeasurementFamiliesIntegration.php
- New read model dedicated to onboarder representing the measurement family (lives in PHP publicAPI)
- New query dedicated to onboarder to fetch all measurement families in the form of the onboarder read model
> RAC-576: Introduce MF read model & public API for onboarder

- CHANGELOG-4.0.md
- src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductGrid/ProductModelImagesFromCodes.php
Extracting the `JSON_EXTRACT` part of the query in a dedicated CTE to avoid sorting on all JSON raw values, thanks @ahocquard for the tips
Tested on the ref env with the problematic dataset and it creates no Out of sort memory errors.
> PIM-9832: Fix variant product images query by extracting image values before sorting

- docker-compose.yml
Do you hate when you start a consumer with docker-compose and you cannot stop it ?
~Have you tried turning your computer off and on again?~
---
Now, with this PR, it will work.
**How**
I'm simply proposing to use the option `init: true` see https://docs.docker.com/compose/compose-file/compose-file-v3/#init
It's only possible since https://github.com/akeneo/pim-community-dev/pull/14303, thanks to our dear @jmleroux  …
> Allows ctrl-c for stopping the php process in docker-compose

- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/categories/CategoryTreeDataGrid.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/categories/useCountCategoryTreesChildren.ts
Make `countTreesChildren` nullable to to distinct when the number of children are loaded or not.
Display `0 category` by default to handle new created tree.
> PLG-231: Fix to display number of categories of new trees

- src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Repository/ExternalApi/CategoryRepository.php
- tests/back/Pim/Enrichment/Integration/Doctrine/ORM/Repository/ExternalApi/CategoryRepositoryApiResourceIntegration.php
Add a "is_root" search filter to the Rest API for get categories.
Supports searching for root categories only or non-root categories only.
> API-1565: rest api search category without parent

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/Component/Product/Updater/ProductUpdater.php
Copy of Thomas' PR.
His description: _Throw BadRequestHttpException when bad parameters are passed to ProductUpdater->filterData()_
> PIM-9827: Fix HTTP 500 when using POST/PATCH with incorrect format

- src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/pages/create-unit/CreateUnit.tsx
This PR fix a glitch introduced when we use DSM component. It only append when user create unit on measurement family already used by an attribute
Before:
After:
> Fix measurement glitch

- CHANGELOG-5.0.md
- upgrades/schema/Version_5_0_20210507154610_update_pim_catalog_completeness_id.php
- upgrades/test_schema/Version_5_0_20210507154610_update_pim_catalog_completeness_id_Integration.php
A migration has been forgot in this [PR ](https://github.com/akeneo/pim-community-dev/pull/14115) , it make the Onboarder test on migration failing, this PR add the missing migration on `pim_catalog_completeness` table
> OB-806: Add missing migration on `pim_catalog_completeness` table

- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/providers/CategoryTreeProvider.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/tree/categories/Node.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/tree/categories/NodePreview.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/categories/useCategoryTreeNode.ts
Wrap the reset of the states `draggedCategory`, `hoveredCategory` and `moveTarget` to be sure that it will be called when a category has been moved.
They were called in `onDrop` and `onDragEnd` but because of the previews, they were not called for some cases.
> PLG-200: Fix states reset after moving a category

- CHANGELOG.md
- src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/choice-filter.js
Forcing the select2 container to be closed when hiding filter choice criteria
> PIM-9741: Fix choice filter mask not closing when selecting with keyboard

- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/providers/CategoryTreeProvider.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/tree/categories/Node.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/tree/categories/NodePreview.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/categories/useCategoryTreeNode.ts
The reset of the "drag" states must also be done when a move is invalid (in itself, outside the tree, etc...) or when an error occurred during the move.
> PLG-200: Reset states when invalid move

- tests/back/Integration/IntegrationTestsBundle/Loader/FixturesLoader.php
**TL;DR** mysqldump bad; always specify the columns when inserting data.
**What happened ?**
While working on #14443,
first, we added a new column to the entity `Category`.
see https://github.com/akeneo/pim-community-dev/pull/14443/commits/1e879a806abfe50c9c5e9d2ed565ebcbe3d9ddfb#diff-8d43e73c3b47b8dbbf8f530d66a4a8c96790f2f3bae7396afe36b7bfa1c8934aR33-R41
then, we added the corresponding migration.
see https://github.com/akeneo/pim-community-dev/pull/14443/commits/1e879a806abfe50c9c5e9d2ed565ebcbe3d9ddfb#diff-47b029001315fb1029e5bd63811e76285fe629ff49ea622e7be77382cbca9fccR16-R20
Everything was working as expected, the CI was green.
Then, another unrelated migration has been merged earlier today, and after rebasing, this migration was …
> FixturesLoader cache fixtures with column names

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductGrid/FetchProductModelRowsFromCodes.php
Splitting the `OR` in `JOIN` predicate into two queries with a `UNION` to be able to perform an index seek
> PIM-9856: Fix children completeness query being too long

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Field/DateTimeFilter.php
- tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Filter/Field/DateTimeFilterSpec.php
Replacing the `is_numeric` by a `is_int` as the filter only accepts integers.
> PIM-9864: Fix 500 error when using DateTime filter with invalid value

- src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/ApplyProductSearchQueryParametersToPQB.php
- tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/SuccessListProductEndToEnd.php
- tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/ListOffsetProductModelEndToEnd.php
Prior to this PR, in the API, the use of the `parent` filter was restricted to the products endpoint (where it was internally replaced by the 'ancestor.code' filter), and only accepted the '=' operator, which was inconsistent with the rest of the PIM (where `parent` can be used to filter on both products and models, and accepts the `IN`, `EMPTY` and `NOT EMPTY` operators)
This PR allows the use of the `parent` filter for both the product and product model endpoints, while keeping the former behavior when filter is 'parent' and operator is '=', in order to avoid a functional BC break
Note: this feature is implemented on 5.0, but will only be documented (and supported) as of v6.0/Saas editions …
> API: allow the use of the 'parent' filter in product models endpoint

- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/shared/tree/Tree.tsx
1. Display a leaf as a node when another category is over (to be dropped in)
2. Hide the actions (`Create` and `Delete`) when a category is dragged
3. Do not open a node when it's dragged
> PLG-248: Fix move category in another ones

- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/shared/tree/Tree.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/tree/categories/Node.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/categories/useCategoryTreeNode.ts
I moved the boolean state `isOpen` in the hook to be able to change it when a category is created.
> PLG-240: Open node when a new category is created inside

- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/categories/CategoryTreeDataGrid.tsx
Hide the button `Delete` on the new category trees data-grid when the user hasn't the permission to remove a category.
> PLG-250: Apply permission on delete category tree

- CHANGELOG-5.0.md
- src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/EntityWithAssociations/PersistTwoWayAssociationSubscriber.php
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/event_subscribers.yml
Calling reindexation on impacted products & product models when persisting 2-way associations.
> PIM-9839: Fix indexation issue on the 2-way associations

- front-packages/akeneo-design-system/.github/workflows/deploy.yml
Since we moved react to peer dependencies the dsm is not deployed on github.io after merge cf: https://github.com/akeneo/akeneo-design-system/runs/2611873575.
This PR fix this by adding fixed peer dependencies while we found a better way to do this
> RAC-717: Fix dsm deployment in https://akeneo.github.io/akeneo-design-system/

- CHANGELOG-4.0.md
- src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/action/delete-action.js
When trying to delete an attribute - linked to a specific entity - in the attribute grid, the message displayed in the flash message was `error.removing.attribute`
As decided with Charlélie and Steven, I made the message displayed to be the same as the one displayed when trying to remove an attribute directly from the attribute page.
I had to add a condition so that when `response = ""`, we don't pass in the `if` and the exception is thrown correctly.
> PIM-9777: Fix error message when trying to delete an attribute linked to an entity

- tests/back/Pim/Enrichment/Integration/Doctrine/Common/Saver/CategorySaverIntegration.php
The changes done on https://github.com/akeneo/pim-community-dev/pull/14466 made this test random, due to the randomness of the datetime used.
> API-1598: Fix random test not detected earlier

- CHANGELOG.md
- src/Akeneo/Platform/Bundle/ImportExportBundle/Controller/InternalApi/JobExecutionController.php
- src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/controllers.yml
- src/Akeneo/Tool/Component/Connector/LogKey.php
- src/Akeneo/Tool/Component/Connector/spec/LogKeySpec.php
- tests/back/Platform/EndToEnd/ImportExport/InternalApi/GetJobExecutionEndToEnd.php
The download log is not present in cloud version because we called file_exist function. 
The file does not exist because the file generated is present in the pim-daemon-server not in the fpm-server. Now we use the filesystem dedicated to the log and check if the file exist.
We only check if there is a logFile related to the JobExecution because when the job is not started the jobFile is empty.
I remove the `is_file($jobExecution->getLogFile()` statement because it required that the file is located in the same server. The \Akeneo\Tool\Component\Connector\LogArchiver already check this.
> PIM-9869: Fix download log in job tracker is only available when log is located in the fpm server

- src/Akeneo/Connectivity/Connection/back/Application/Webhook/Command/SendBusinessEventToWebhooksHandler.php
- src/Akeneo/Connectivity/Connection/back/Domain/Webhook/Event/EventsApiRequestFailedEvent.php
- src/Akeneo/Connectivity/Connection/back/Domain/Webhook/Event/EventsApiRequestSucceededEvent.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/EventSubscriber/EventsApiRequestsLimitIncrementSubscriber.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/event_subscribers.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/handlers.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/webhook.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/Client/GuzzleWebhookClient.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Webhook/Command/SendBusinessEventToWebhooksHandlerSpec.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/EventSubscriber/EventsApiRequestsLimitIncrementSubscriberSpec.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Webhook/Client/GuzzleWebhookClientSpec.php
Decouple the incrementation of the Events API rate limit from the main command handler.
> CXP-628: decouple events api limit increment

- CHANGELOG.md
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/filter/product/updated.js
Since [PIM-9864](https://akeneo.atlassian.net/browse/PIM-9864), SINCE_LAST_N_DAYS operator is more restrictive on the value type given.  In this PR, given the right value in case of the filter operator is SINCE LAST N DAYS
> PIM-9873: Fix since last n day filter in product export

- CHANGELOG.md
- src/Akeneo/Pim/Structure/Component/Remover/FamilyRemover.php
- src/Akeneo/Tool/Bundle/StorageUtilsBundle/Doctrine/Common/Remover/BaseRemover.php
- src/Akeneo/Tool/Bundle/VersioningBundle/EventSubscriber/AddRemoveVersionSubscriber.php
- src/Akeneo/Tool/Bundle/VersioningBundle/spec/EventSubscriber/AddRemoveVersionSubscriberSpec.php
When we remove multiple objects we dispatch event PRE_REMOVE, handlers can throw exception in this case the remove process is stopped but the entity are always in the the unit of work so when we flushed the unit of work (for example when we save the JobExecution) the product are remove but the POST_REMOVE is not triggered.
In this PR, I also changed the event listened by the AddRemoveVersionSubscriber because it create a version while the product is not really removed.
> PIM-9852: Fix exception during PRE_REMOVE on removeAll cause ES desynchronisation

- CHANGELOG-4.0.md
- config/packages/liip_imagine.yml
- src/Oro/Bundle/PimDataGridBundle/Resources/public/templates/datagrid/row/product-thumbnail.html
When an asset attribute was defined as the main image of a product, the thumbnail display was broken in the product grid on gallery mode.
Adding `background-size` and `background-repeat` css properties fixes the issue.
The thumbnail display was broken too when adding an image as attribute "picture" (thumbnail broken in the product form, in the product grid - list and gallery mode).
So, I fixed the liip_imagine config by replacing outbound mode with inset mode for thumbnail and thumbnail small.
> PIM-9692: Standardize the thumbnail display on the product grid

- .gitignore
- front-packages/akeneo-design-system/.gitignore
Fix DSM extraction. The lib folder was not sent to the library private repository.
> Fix DSM extraction by not ignoring the lib folder

- front-packages/akeneo-design-system/src/components/Table/TableRow/TableRow.tsx
https://github.com/akeneo/pim-enterprise-dev/pull/10890
When there is only 1 column, the drag and drop cell takes ~ 200px width.
This PR fixes it and hardcode the width of this cell.
> CPM-176: Fix DSM for drag and drop cell width

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/Component/Product/Builder/EntityWithValuesBuilder.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Builder/EntityWithValuesBuilderSpec.php
Since https://github.com/akeneo/pim-community-dev/pull/13338 we do not save products or product models that were not actually updated anymore. One thing we missed is, when trying to update a value with the same data, we successively call `$entity->removeValue()` then `$entity->addValue()`, which makes the entity *believe* it was updated, whereas the data is the same. This leads to saving the entity and possibly triggering an "Entity update" webhook event, which we do not want.
For most use cases it's not an issue, as identical data is filtered _a priori_ (External API, UI, Mass actions), but the behavior still happens when 
- executing a rule
- running an import with the "Compare values" flag disabled …
> PIM-9881: Do not update a value which was not modified

- CHANGELOG-5.0.md
- src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/grid/grid_view_selector.yml
- src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/grid/view-selector-secondary-actions.ts
Under certain circumstances (Italian, German or Dutch UI locale, a selected grid view with a short label, ..), the "secondary actions" dropdown of the grid view selector is partially hidden, and no horizontal scrollbar appears, making it hardly readable:
This PR fixes this behavior:
Due to the column layout I wasn't able to fix it in pure CSS, I had to manually set the position: fixed in js
> PIM-9882: Fix display of grid selector secondary actions dropdown

- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/Column.less
The small line-height was incompatible with the label included recently, creating differences in the height of the sub navigation elements, see:
> CXP-711: fix sub navigation link css

- src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/legacy-bridge/src/bridge/react/reactController.ts
- src/Akeneo/Tool/Bundle/MeasureBundle/Resources/public/bridge/controller/settings.tsx
This PR goal is to provide a way to fix a kind of memory leak when a single controller is used for a react application that uses multiple internal routes, without breaking anything in the PIM. The current behavior of the react controller creates a new container each time a react route is rendered, without unmounted the previous one, so react apps keeps piling up.
Each backbone controller that renders a React routed app will have to provide a static reference to a HTML element wherein the app will be mounted. To demonstrate the fix, I applied this fix in a dedicated commit in the Measurements. For now, it's the only place where we have this issue in the CE.
> Fix container react router

- config/packages/behat/messenger.yml
- config/packages/test/messenger.yml
- config/packages/test_fake/messenger.yml
- config/services/test_fake/services.yml
- phpunit.xml.dist
- src/Akeneo/Tool/Bundle/BatchQueueBundle/EventListener/AckMessageEventListener.php
- src/Akeneo/Tool/Bundle/BatchQueueBundle/README.md
- src/Akeneo/Tool/Bundle/BatchQueueBundle/Resources/config/services.yml
- src/Akeneo/Tool/Bundle/BatchQueueBundle/spec/EventListener/AckMessageEventListenerSpec.php
- src/Akeneo/Tool/Bundle/BatchQueueBundle/tests/Acceptance/AckMessageEventListenerTest.php
- src/Akeneo/Tool/Bundle/MessengerBundle/README.md
- src/Akeneo/Tool/Bundle/MessengerBundle/Transport/GooglePubSub/Client.php
- src/Akeneo/Tool/Bundle/MessengerBundle/Transport/GooglePubSub/GpsReceiver.php
- src/Akeneo/Tool/Bundle/MessengerBundle/Transport/GooglePubSub/GpsTransportFactory.php
- src/Akeneo/Tool/Bundle/MessengerBundle/spec/Transport/GooglePubSub/GpsReceiverSpec.php
- tests/back/Acceptance/Messenger/InMemorySpyTransport.php
- tests/back/Acceptance/Messenger/InMemorySpyTransportFactory.php
- tests/back/Acceptance/Resources/config/pim/messenger.yml
Previously we set a machanism to ack the message after pulling it only if the transport was pubsub (please see the ADR to know the reason).  
Now we ack the message in all cases thanks to an event subscriber.
Issue:
The event subscriber allows to ack the message before handling it. But after handling it, a new ack is requested. I don't figure out how to disable this second ack: it's hardcoded in the Worker https://github.com/symfony/messenger/blob/4.4/Worker.php#L150  
It seems there is no problem to ack the same message twice, but it would be better to ack once.  
> POC: ack job message after pull in all cases

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/Bundle/Resources/workspaces/enrichment/src/components/completeness/ProductCurrentCompleteness.tsx
This fix prevent a javascript error that block the display of the PEF when the selected locale has been deactivated. 
As on 5.0, the completeness badge and selector will not be displayed at all.
> PIM-9886: Fix display of completeness in the PEF when the selected locale is deactivated

- src/Akeneo/Tool/Bundle/MeasureBundle/Persistence/MeasurementFamilyRepository.php
- src/Akeneo/Tool/Bundle/MeasureBundle/spec/Controller/ExternalApi/JsonSchema/MeasurementFamilyCommonStructureValidatorSpec.php
- src/Akeneo/Tool/Bundle/MeasureBundle/spec/Controller/ExternalApi/JsonSchema/MeasurementFamilyValidatorSpec.php
- src/Akeneo/Tool/Bundle/MeasureBundle/tests/Integration/Persistence/MeasurementFamilyRepositoryIntegration.php
After creating a measurement, the cache contains only one measurement so the `FindAllMeasurementFamilies` query returns only one measurements instead of all. 
I also found some forgotten copy/paste from asset context and fixed them.
> OB-759: Fix missing measurements in cache

- CHANGELOG.md
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/KeyIndicator/ComputeProductsEnrichmentStatusQuery.php
`$this->channels->getIdByCode($channel);` and `$localeId = $this->locales->getIdByCode($locale);` can return `null`, but this case was not handled and it can cause a fatal error.
Because we're loading channels/locales codes and ids in two distinct queries. And because we put the results in cache to avoid to repeat those queries. It can happen that the id of a channel or locale cannot be found from its code.
I added sanity checks to avoid any error, and rework the code for more readability.
> PIM-9891: Fix missing sanity checks when computing enrichment status

- CHANGELOG.md
- src/Akeneo/Channel/Bundle/Resources/config/validation/channel.yml
- tests/back/Channel/EndToEnd/Channel/ExternalApi/PartialUpdateListChannelEndToEnd.php
- tests/back/Channel/Integration/Channel/Validation/ChannelValidationIntegration.php
For solving the issue, it has been decided that the channel should contain at least one letter.
> PIM-9890: Creating Channels with numeric code breaks the PIM

- src/Akeneo/Connectivity/Connection/back/Infrastructure/EventSubscriber/EventsApiRequestsLimitEventSubscriber.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/EventSubscriber/EventsApiRequestsLimitEventSubscriberSpec.php
In `EventsApiRequestsLimitEventSubscriber.php`, replace `WorkerRunningEvent` by `MessageProcessedEvent` in `getSubscribedEvents()`
> API-1608: Update EventsApiRequestLimitSubscriber to use MessageProcessedEvent

- src/Akeneo/Connectivity/Connection/back/Application/ErrorManagement/Service/CollectApiError.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/EventSubscriber/ApiErrorEventSubscriber.php
- src/Akeneo/Connectivity/Connection/back/tests/.php_cd.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/ErrorManagement/Service/CollectApiErrorSpec.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/EventSubscriber/ApiErrorEventSubscriberSpec.php
Pass Context instead of Product in `Akeneo\Connectivity\Connection\Application\ErrorManagement\Service\CollectApiError::collectFromProductDomainError:collectFromProductDomainError() `and `Akeneo\Connectivity\Connection\Application\ErrorManagement\Service\CollectApiError::collectFromProductDomainError:collectFromProductValidationError()`
> CXP-687: remove Akeneo\Pim\Enrichment\Component\Product\Model\ProductInterface coupling

- src/Akeneo/Connectivity/Connection/back/Application/Webhook/Service/DnsLookupInterface.php
- src/Akeneo/Connectivity/Connection/back/Application/Webhook/Service/IpMatcherInterface.php
- src/Akeneo/Connectivity/Connection/back/Application/Webhook/Validation/ExternalUrl.php
- src/Akeneo/Connectivity/Connection/back/Application/Webhook/Validation/ExternalUrlValidator.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Service/DnsLookup.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Service/IpMatcher.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/services.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/validation/WriteConnectionWebhook.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/validators.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/Service/WebhookReachabilityChecker.php
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Webhook/UpdateEventSubscriptionEndToEnd.php
- src/Akeneo/Connectivity/Connection/back/tests/Integration/Mock/FakeDnsLookup.php
- src/Akeneo/Connectivity/Connection/back/tests/Integration/Resources/config/services.yml
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Webhook/Validation/ExternalUrlValidatorSpec.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Service/IpMatcherSpec.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Webhook/Service/WebhookReachabilityCheckerSpec.php
**Rules**
Blacklist of the domains:
- localhost
- elasticsearch
- memcached 
Check URL for use of IP addresses instead of FQDN's and blacklist all RFC 1918 IPs
Set a new env variable to allow a coma separated list of specific network. For example: `ALLOWED_NETWORK_WHITELIST=10.0.2.0/24,172.19.8`
In the Event Subscription endpoint field, we want to check 2 things:
First, only urls are allowed (http & https), not other protocols.
Second, urls resolving to internal ips are forbidden.
**Documentation's PR:** https://github.com/akeneo/pim-docs/pull/1643
> API-1602: dns lookup for event subscription url

- .circleci/config.yml
Some developper alert us that CE build_dev CI does not work anymore due to the following error: 
Watch plugin jest-watch-typeahead/filename cannot be found. Make sure the watchPlugins configuration option points to an existing node module. (https://app.circleci.com/pipelines/github/akeneo/pim-community-dev/23719/workflows/053cc1cc-5a6a-4c69-8137-99214fb44f5d/jobs/101618)
This PR remove will remove the front-packages cache **temporarily** in order to do not block anymore the others developers. We will in another PR, investigate about the error, add more check on cache and make sure it doesn't happen again.
> Fix corrupted front-packages

- .circleci/config.yml
- Makefile
- package.json
Related to : https://github.com/akeneo/pim-community-dev/pull/14732
We decided to cache only the DSM, this packages take time to be installed. For now we don't need to add each front-packages in cache.
We decided to do this in first time, when we will migrate to yarn 2 we will cache the compressed node_module of each front-packages.
> Only cache design system

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Model/ElasticsearchProductModelProjection.php
- src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Model/ElasticsearchProductProjection.php
- src/Akeneo/Pim/Enrichment/Bundle/Resources/elasticsearch/product_mapping.yml
- src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ElasticsearchProjection/GetElasticsearchProductModelProjection.php
- src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ElasticsearchProjection/GetElasticsearchProductProjection.php
- tests/back/Pim/Enrichment/Integration/Storage/Sql/ElasticsearchProjection/GetElasticsearchProductModelProjectionIntegration.php
- tests/back/Pim/Enrichment/Integration/Storage/Sql/ElasticsearchProjection/GetElasticsearchProductProjectionIntegration.php
- tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Indexer/ProductIndexerSpec.php
- tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Indexer/ProductModelIndexerSpec.php
- tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Model/ElasticsearchProductModelProjectionSpec.php
- tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Model/ElasticsearchProductProjectionSpec.php
- upgrades/schema/Version_6_0_20210615084255_add_entity_updated_in_product_mapping.php
- upgrades/test_schema/Version_6_0_20210615084255_add_entity_updated_in_product_mapping_Integration.php
https://akeneo.atlassian.net/browse/PIM-9719
To spot the desynchronization between a product in DB and in ES, we should have the `updated` information in ES (see the ticket for more info). 
But in ES the `updated` info is updated each time the parent product model or the root is updated. For instance for a product:
```sql
GREATEST(product.updated, COALESCE(sub_product_model.updated, 0), COALESCE(root_product_model.updated, 0)) AS updated_date
```
We can't change the behavior of this updated field as it is used for API.  
In this PR we add the `entity_updated` information that matches the real updated information in DB for a product/product model.
- add the information in the ES projections
- add the mapping for new installs
- add a …
> PIM-9719: add entity updated info in indexation

- CHANGELOG-4.0.md
- src/Akeneo/Tool/Component/Connector/Writer/File/FlatItemBufferFlusher.php
- src/Akeneo/Tool/Component/Connector/Writer/GlobalFunctionsHelper.php
- src/Akeneo/Tool/Component/Connector/Writer/WriterFactory.php
- symfony.lock
- tests/back/Pim/Enrichment/Integration/Product/Export/Product/ExportProductsIntegration.php
- tests/legacy/features/Behat/Context/Domain/Collect/ImportProfilesContext.php
* The backslash \ should not be considered as a an escape character where today the PIM says it is an escape character
* The quote ” should always be doubled when it is set as a value (which is today’s behavior except when there are backslashes)
> PIM-9914: Fix backslash incorrectly considered as an escape character in exports

- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/categories/CategoryEditPage.tsx
There was a bug when the translation of the language used for the UI was empty. A sanity check was incomplete.
Before :
After :
> PLG: fix category edit form display when the current translation is null

- CHANGELOG-5.0.md
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/product/edit/content/data.js
When a text, a simple select or a date attribute was used as a filter for a product export profile, update of values on each filter after the first saved value was never applied even after clicking the Save button.
The same filter was applied twice, so, we created a condition to avoid this issue.
> PIM-9916: Fix value updating for text, simple select and date attribute used as product export filter not saved

- front-packages/akeneo-design-system/src/components/Input/MultiSelectInput/MultiSelectInput.stories.mdx
- front-packages/akeneo-design-system/src/components/Input/MultiSelectInput/MultiSelectInput.tsx
- front-packages/akeneo-design-system/src/components/Input/MultiSelectInput/MultiSelectInput.unit.tsx
This PR fixes an issue occuring on the multi select input when one of the codes of the options given for the multi select does not exist as an Option in the Children
> RAC-609: Fix multi-select-input bug when codes don't have associated children

- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/documentation.yml
- src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/validators.en_US.yml
- src/Akeneo/Pim/Enrichment/Component/Error/DocumentationBuilder/LocalizableAttribute.php
- src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/LocalizableValues.php
- src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/LocalizableValuesValidator.php
- tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/Media/CreateProductModelMediaFileEndToEnd.php
- tests/back/Pim/Enrichment/Specification/Component/Error/DocumentationBuilder/LocalizableAttributeSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/LocalizableValuesValidatorSpec.php
- tests/features/pim/enrichment/product/validation/localizable_values.feature
Update the following error message from `Attribute "%attribute_code%" expects an existing and activated locale, "%invalid_locale%" given.` to `The %attribute_code% attribute requires a valid locale. The %invalid_locale% locale does not exist.` for inactive or non-existent locales.
API Response
Error Monitoring UI
> CXP-344: enrich "non active locale" error

- src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/validators.en_US.yml
- src/Akeneo/Pim/Enrichment/Component/Error/DocumentationBuilder/LocalizableAttribute.php
- src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/LocalizableValues.php
- src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/LocalizableValuesValidator.php
- tests/back/Pim/Enrichment/Specification/Component/Error/DocumentationBuilder/LocalizableAttributeSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/LocalizableValuesValidatorSpec.php
- tests/features/pim/enrichment/product/validation/localizable_values.feature
Improve error message and error monitoring
(screenshots not up-to-date with the last error message change)
> CXP-345: enrich error on invalid locale for channel

- CHANGELOG.md
- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/categories/CategoryEditPage.tsx
> PIM-9933: Fix delete category menu that stays displayed on screen

- config/services/behat/services.yml
- config/services/test/test_services.yml
- src/Akeneo/Tool/Bundle/BatchQueueBundle/tests/integration/Queue/ConsumeJobMessageIntegration.php
- src/Akeneo/Tool/Bundle/MessengerBundle/Transport/GooglePubSub/Client.php
- src/Akeneo/Tool/Bundle/MessengerBundle/spec/Transport/GooglePubSub/ClientSpec.php
- tests/back/Integration/IntegrationTestsBundle/Launcher/JobLauncher.php
- tests/back/Integration/IntegrationTestsBundle/Launcher/PubSubQueueStatus.php
- tests/back/Integration/IntegrationTestsBundle/Loader/FixturesLoader.php
- tests/legacy/features/Behat/Context/HookContext.php
- tests/legacy/features/Behat/Context/ImportExportFileContext.php
The phpunit/behat tests failed randomly. When the jobs were in the database we just had to clear the database, now we the jobs are in the pubsub emulator and we had to flush the queues between each tests (otherwise a test can create several jobs and pollute the next tests).
- Flush the queues between each behat tests
- Fix creation of subscription by "reload" the data (bypass the cache): sometimes the daemon failed because it tried to create a subscription that already exist, or try to use a subscription that didn't exist. Random tests that are very hard to debug
- Clear doctrine repo cache before fetching the job execution object
> CPM-156 stabilize job tests

- src/Akeneo/Tool/Bundle/MeasureBundle/Persistence/MeasurementFamilyRepository.php
Following this [PR](https://github.com/akeneo/pim-community-dev/pull/14629)
We need to initialize the cache by calling `all` method but we don't want to override caches values return by `all` method,
`all` method return `array_values` of measurmentFamilies (removing measurmentFamilies codes as key), and the cache need measurmentFamilies code as key to work properly
> OB-848: Fix cache initialization

- src/Akeneo/Tool/Bundle/MeasureBundle/Persistence/MeasurementFamilyRepository.php
Following this PR
We need to initialize the cache by calling all method but we don't want to override caches values return by all method,
all method return array_values of measurmentFamilies (removing measurmentFamilies codes as key), and the cache need measurmentFamilies code as key to work properly
> OB-848: Fix cache initialization (cherry-pick from 5.0)

- CHANGELOG-4.0.md
- src/Akeneo/Tool/Bundle/MeasureBundle/Resources/config/measure.yml
On the measure yml file, the bar symbol was written Bar. Same for millibar -> mBar.
The convention is 
Bar : the symbol should be bar
Millibar: the symbol should be mbar
> PIM-9941: Metrics: Change Bar symbol for bar

- CHANGELOG-5.0.md
- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/attribute-groups/useFilteredAttributeGroups.ts
Fix the search on the attribute group datagrid:
- the search should be performed based on the catalog locale instead of the UI locale
- if no label is defined for the given locale, search on the code
> PIM-9944: Fix attribute group grid search

- src/Akeneo/Connectivity/Connection/back/Infrastructure/InternalApi/Controller/Marketplace/GetWebMarketplaceUrl.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/controllers.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/routing.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/routing/marketplace.yml
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Marketplace/GetWebMarketplaceUrlEndToEnd.php
- src/Akeneo/Connectivity/Connection/front/src/connect/hooks/use-fetch-marketplace-url.ts
- src/Akeneo/Connectivity/Connection/front/tests/src/connect/hooks/use-fetch-marketplace-url.test.tsx
Following https://github.com/akeneo/pim-community-dev/pull/14885
The goal is to regroup marketplace action/controller
> CXP-791: refactor 'get web marketplace url' endpoint

- front-packages/shared/src/components/CategoryTree/CategoryTree.tsx
- front-packages/shared/src/components/CategoryTree/CategoryTrees.tsx
- front-packages/shared/src/components/CategoryTree/RecursiveCategoryTree.tsx
- src/Akeneo/Platform/Bundle/ImportExportBundle/Controller/Ui/CategoryTreeController.php
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/filter/product/category/Selector.tsx
_Those new features have been implemented in the context of the following PR. https://github.com/akeneo/pim-enterprise-dev/pull/11165. In this PR, the display of each category might depend on the state of their parent category._
This PRs extends a bit more the possibilities of the CategoryTree (and recursive categorytrees) by:
- Modifying the isCategorySelected callback signature to take into account an additonnal (optional) argument that is an object representing the parent category of the current category.
- introducing a new callback that checks for each node if the node should be displayed read-only or not (just like the isCategorySelected callback works.
- this callbacks takes the current displayed category as well as it's parent.
> RAC-739: update CategoryTree component to allow display depending on parents

- CHANGELOG.md
- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/categories/CategoryEditPage.tsx
Fix edit category page to display the breadcrumb & title value with the catalog locale (en_US) and not the UI locale (fr_FR)
> PIM-9949: Fix category edit page to use catalog locale

- CHANGELOG-5.0.md
- src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/listener/ProductEditForm/CatalogContextListener.tsx
When using the compare/translate feature on a product, the spell-check is applied according to the locale of the comparison instead of the catalog context.
The locale and channel on DQI features must be changed only when the change is done on the product base context.
> PIM-9951: Fix wrong locale used by spellcheck when comparing product attributes

- src/Akeneo/Connectivity/Connection/back/Application/Webhook/WebhookEventBuilder.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Webhook/WebhookEventBuilderSpec.php
- src/Akeneo/Pim/Enrichment/Component/Product/Webhook/ProductCreatedAndUpdatedEventDataBuilder.php
- src/Akeneo/Pim/Enrichment/Component/Product/Webhook/ProductModelCreatedAndUpdatedEventDataBuilder.php
- src/Akeneo/Pim/Enrichment/Component/Product/Webhook/ProductModelRemovedEventDataBuilder.php
- src/Akeneo/Pim/Enrichment/Component/Product/Webhook/ProductRemovedEventDataBuilder.php
- src/Akeneo/Platform/Component/Webhook/Context.php
- src/Akeneo/Platform/Component/Webhook/EventDataBuilderInterface.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Webhook/ProductCreatedAndUpdatedEventDataBuilderSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Webhook/ProductModelCreatedAndUpdatedEventDataBuilderSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Webhook/ProductModelRemovedEventDataBuilderSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Webhook/ProductRemovedEventDataBuilderSpec.php
- tests/back/Platform/Specification/Component/Webhook/ContextSpec.php
The goal of this PR is to remove the dependency on the *UserManagement* bounded context from the "EventDataBuilder" interfaces used by the *Enrichment* bounded context to build its own events data sent by the Events API.
From the
```php
namespace Akeneo\Platform\Component\Webhook;
interface EventDataBuilderInterface
```
Before, with the coupling to UserManagement
```php
public function build(BulkEventInterface $event, Akeneo\UserManagement\Component\Model\UserInterface $user): EventDataCollection;
```
After, the interface is not coupled to UserManagement but use a simple DTO with only its required data (user id & username)
```php
public function build(BulkEventInterface $event, Context $context): EventDataCollection;
```
> Fix coupling between Connectivity and UserManagement

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductModel/GetDescendantVariantProductIdentifiers.php
By adding a where clause on the join, mysql isn't using a join buffer anymore and can rely on indexes.
`EXPLAIN` of old & new query:
Old `EXPLAIN ANALYZE`:
New `EXPLAIN ANALYZE`:
> PIM-9948: Fix performance issue on product model import

- CHANGELOG-5.0.md
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/ProductGrid/QualityScoreFilter.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/ProductGrid/QualityScoreFilterSpec.php
Under some conditions, filtering the products on their quality score with the choice "all" could lead to empty list.
The choice "All" should not apply the filter on quality score at all.
> PIM-9943: Fix product-grid quality score filter all

- bin/queue-daemon-wrapper.sh
Exits queue daemon wrapper after signal handling
> BH-665 Exits queue daemon wrapper after signal handling

- .circleci/config.yml
Makes composer cache dir writable for Onboarder test
> BH-666 Makes composer cache dir writable for Onboarder test

- CHANGELOG.md
- src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/choice-filter.js
Providing Select2 choice filter a custom tokenizer that selects the last element of a pasted list (separated by `,`, `;` or ` `)
Before:
After:
> PIM-9716: Autoselect last element of pasted list in choice filter

- upgrades/schema/Version_6_0_20210713134208_create_table_invited_users.php
- upgrades/test_schema/Version_6_0_20210713134208_create_table_invited_users_Integration.php
The migration script to create the table to persist the invited users is mandatory to pass the CI.
> PLG-212: Add migration script

- .circleci/config.yml
This PR replaces the usage of composer to change requirements by a sed in order to reduce the API calls to Github and avoid reaching API limits.
Indeed, doing a composer require, even without the --no-update option, will validate that the requirement can work, and go through all dependencies again, including the private repositories hosted on Github.
This validation is not necessary as a bit later in the process we launch a full composer install, which will do the validation again.
> BH-669 Reduces Github API calls by avoiding using composer to change requirements

- .circleci/config.yml
- cypress/support/commands.js
- docker/cypress/Dockerfile
- tests/front/e2e/product/edit.js
The e2e suite is used to make sanity checks on real customers that don't always have a "name" text attribute and we must adapt the test to use the first available text filed in the PeF
> BH-589: Use first text filed in PEF for sanity checks

- CHANGELOG.md
- front-packages/akeneo-design-system/src/components/Input/SelectInput/Overlay/Overlay.tsx
Rerendering the content with the visible prop to trigger the ref being mounted and get its actual position and size
> PIM-9973: Fix Asset attribute media type dropdown being hidden

- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/translator.js
Oro translator is removing placeholders when translating a message, so when translating a second time, the placeholders are missing...
See: https://github.com/oroinc/platform/commit/bafde8ad778f4659420c4c500a4e2cde2a57f228
> RAC-795: Fix placeholders are removed on second translation

- CHANGELOG.md
- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/categories/useDeleteCategory.ts
- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/infrastructure/removers/deleteCategory.ts
When we updated the category UI, we forgot to use the error message returned by the backend when an error occurs while deleting a category. This PR fixes this behavior so we display a proper error message instead of a generic message, for example when in EE we try to delete a category that has published product in it :
> PIM-9986: Fix error message returned by the backend not displayed when an error occured while deleting a category

- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/public/js/dependencies.ts
- src/Akeneo/Connectivity/Connection/front/src/audit/pages/Dashboard.tsx
- src/Akeneo/Connectivity/Connection/front/src/error-management/components/ConnectionErrors.tsx
- src/Akeneo/Connectivity/Connection/front/src/infrastructure/dependencies-provider.tsx
- src/Akeneo/Connectivity/Connection/front/src/shared/feature-flags/feature-flags-context.ts
- src/Akeneo/Connectivity/Connection/front/src/shared/feature-flags/feature-flags.interface.ts
- src/Akeneo/Connectivity/Connection/front/src/shared/feature-flags/index.ts
- src/Akeneo/Connectivity/Connection/front/src/shared/feature-flags/use-feature-flags.ts
The goal is to remove the helper messages in the Connectivity pages on the Free-Trial. There will be a dedicated helpers for the Free-Trial.
> PLG-362: Remove helper messages in Connectivity for Free-Trial

- front-packages/measurement/src/feature/pages/list/List.tsx
- front-packages/shared/src/DependenciesContext.tsx
- front-packages/shared/src/DependenciesProvider.type.ts
- front-packages/shared/src/hooks/index.ts
- front-packages/shared/src/hooks/useFeatureFlags.ts
- src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/legacy-bridge/src/__mocks__/dependencies.ts
- src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/legacy-bridge/src/dependencies.ts
The goal is to remove the helper message in the Measurements page on the Free-Trial. There will be a dedicated helper for the Free-Trial.
To do so, it was necessary to add a new dependency `FeatureFlags` in `akeneo-pim-community/shared`
> PLG-364: Remove helper message  in Measurement page for Free-Trial

- CHANGELOG.md
- src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/product/index.yml
- src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/grid/mass-actions.js
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/grid/mass-actions.ts
This PR fixes an issue with the product selection count in the product grid in a specific use case. For example if you selected 2 products, then searched for a specific SKU and added the product to the selection, the count was reset to 1, where the correct number should have been 3. Furthermore, the number of selected products was not coherent with the real number of products impacted by the mass action, because the mass action had the real number of selected products (3 in my example). Since it's difficult to explain, I added 2 gifs of the before / after behaviors at the end.
Technically, for a reason I can't understand, the number displayed in the mass action bar was only the number of currently selected products, and not the total …
> PIM-9987: Fix product grid count not accurate after specific SKU selection

- CHANGELOG.md
- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/SettingsIndex.tsx
- src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_US.yml
- src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.fr_FR.yml
In the settings menu, when you had only one channel, the sentence displayed was "You have 1 channels".
I tried to write a conditional translation like this:
`channels: '{1}You have 1 channel|]1, Inf[You have {{ count }} channels'`
but it doesn't work 
so I created a second key and added the condition in the SettingsIndex.tsx file.
Do not hesitate to offer me a better solution ;-)
(Will be fixed in Crowdin too, for the French translation)
> PIM-9985: Improve channels sentence display in the settings menu

- CHANGELOG-4.0.md
- src/Akeneo/Pim/Enrichment/Component/Product/ValuesFiller/FillMissingProductModelValues.php
- src/Akeneo/Pim/Enrichment/Component/Product/ValuesFiller/FillMissingProductValues.php
- tests/back/Pim/Enrichment/Specification/Component/Product/ValuesFiller/FillMissingProductModelValuesSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/ValuesFiller/FillMissingProductValuesSpec.php
This PR fixes a bug with quick exports containing products that have scopable & localizable & locale specific attributes : in this particular use case, we must not export all the locales of the channel, but only the locales of the attribute. Scopable & localizable attributes work fine, but this use case was simply forgotten.
The side effect of this bug was that we couldn't reimport the generated file because it contained columns with locales that were not part of the locale specific attribute.
> PIM-9988: Fix quick export with attributes that are scopable, localizable and locale specific

- src/Akeneo/Pim/Enrichment/Component/Product/Model/EntityWithValuesInterface.php
PHPStan failed in EE because of the bad doc block. The various implementations say we can have null return, not the interface.
> CPM-283: fix docblock

- .circleci/config.yml
Following the tag of the Onboarder this morning, we have broken the `test_onboarder_bundle` job in the PIM CI. 
Issue was that we were starting the docker containers too early (because we do [some changes](https://github.com/akeneo/pim-onboarder/pull/736/files#diff-64053cf08d8acec719799250b6691a8eee37b542e033c703002cb4523d4b1100R158) in `docker-compose.yml` through the `onboarder.mk`)
> Fix test_onboarder_bundle CircleCI job following flysystem upgrade

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/ProductModelController.php
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/controllers.yml
Like https://github.com/akeneo/pim-enterprise-dev/pull/8611 and https://github.com/akeneo/pim-community-dev/pull/11972. A deadlock can occurs during the completeness calculation, on the postSave event in partial update of product models.
This produce the following output:
```
{"line":98,"code":"CPLAL9","status_code":204}
{"line":99,"code":"CPLAA9","status_code":204}
{"line":100,"code":"CPLAN9","status_code":204}<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8" />
<meta name="robots" content="noindex,nofollow,noarchive" />
<title>An Error Occurred: Internal Server Error</title>
<style>body { background-color: #fff; color: #222; font: 16px/1.5 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; …
```
> PIM-10009: Fix error being printed in the response of partial update of product models API

- front-packages/akeneo-design-system/src/components/Dropdown/ItemCollection/ItemCollection.tsx
- front-packages/akeneo-design-system/src/components/TabBar/TabBar.tsx
Tab bar detection of hidden tab does not work in chrome because entries length is higher than 1, we should only take care of the last entry in case of there is multiple entries
> RAC-834: Fix tabbar detection of hidden tab

- cypress/support/commands.js
- tests/front/e2e/product/edit.js
Cypress tests have stability issue when saving a product attribute and reloading. This PR add a new cypress command "reloadProduct" and use it with tests 
> BH-691: Cypress save product stabilization

- src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/GetElasticsearchProductModelProjectionInterface.php
- src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/GetElasticsearchProductProjectionInterface.php
- src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Indexer/ProductIndexer.php
- src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Indexer/ProductModelIndexer.php
- src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ElasticsearchProjection/GetElasticsearchProductModelProjection.php
- src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ElasticsearchProjection/GetElasticsearchProductProjection.php
- src/Akeneo/Tool/Bundle/ElasticsearchBundle/Client.php
- tests/back/Pim/Enrichment/Integration/Storage/Sql/ElasticsearchProjection/GetElasticsearchProductModelProjectionIntegration.php
- tests/back/Pim/Enrichment/Integration/Storage/Sql/ElasticsearchProjection/GetElasticsearchProductProjectionIntegration.php
- tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Indexer/ProductIndexerSpec.php
- tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Indexer/ProductModelIndexerSpec.php
Since #10831 the indexation of products and product models only uses plain DBAL queries (the ORM is not used anymore). This  has allowed improved performances and a better management of the used memory during indexation. 
However, when trying to index a batch of really "big" products (with lots of values), the memory can still be pretty full during the process. 
This PR tries to take advantage of PHP's generators in order to load/instantiate indexation-related objects only when they are needed, thus reducing the peak memory usage of the script. 
I don't have a real benchmark, but on a real use case, the peak memory usage of an API request to patch 100 root product models (with 480 sub product models and ~3000 variant products) was …
> PIM-10013: Decrease memory consumption when indexing products / product models

- upgrades/schema/Version_6_0_20210715082931_add_product_web_api_acl.php
- upgrades/test_schema/Version_6_0_20210715082931_add_product_web_api_acl_Integration.php
In the PR https://github.com/akeneo/pim-community-dev/pull/14978 that was introducing new ACLs, the lack of migration created inconsistencies between roles in production.
complete technical analysis on notion: https://www.notion.so/akeneo/Technical-analysis-a2a4188bac60430b8e77af655f64ad58
This PR introduce the missing migration.
My only regret is to not be able to write a pure sql migration, I've tried and some OroAcl behavior is completely unexpected.
For example, I was not able to properly manage the `ace_order` value in the `acl_entries` table.
Any mistake in the inserted data will completely corrupt the ACLs when you try to save the same role from the UI with updated permissions, which is unacceptable.
**Edit**
Following …
> CXP-811: add a migration for product acls

- src/Oro/Bundle/PimDataGridBundle/Extension/MassAction/MassActionDispatcher.php
The MassActionDispatcher used to add the "dataLocale" parameter to the grid's query builder only for the family datagrid, but it is also needed for the EE rules datagrid mass actions. (Note: currently only the family and the rules grids have mass actions - besides product and published product grids of course)
> PIM-10012: Add dataLocale parameter to qb in mass action context

- front-packages/akeneo-design-system/src/components/Table/TableRow/TableRow.tsx
The handle cell width should not been calculated by the navigator it should be always the same width 
> RAC-763: Fix handle cell width

- src/Akeneo/Pim/Enrichment/Bundle/Controller/Ui/AbstractListCategoryController.php
- src/Akeneo/Pim/Enrichment/Bundle/Controller/Ui/CategoryTreeController.php
- src/Akeneo/Platform/Bundle/ImportExportBundle/Controller/Ui/JobTrackerController.php
- src/Akeneo/UserManagement/Bundle/Controller/GroupController.php
- src/Akeneo/UserManagement/Bundle/Controller/ResetController.php
- src/Akeneo/UserManagement/Bundle/Controller/RoleController.php
- src/Akeneo/UserManagement/Bundle/Controller/SecurityController.php
- src/Oro/Bundle/DataGridBundle/Controller/GridController.php
See https://symfony.com/blog/new-in-symfony-4-2-important-deprecations#deprecated-the-base-controller-class
> BH-681: Use AbstractController instead of the deprecated base Controller

- config/packages/security.yml
> BH-681: Remove deprecated firewall option `logout_on_user_change`

- CHANGELOG.md
- src/Akeneo/UserManagement/.php_cd.php
- src/Akeneo/UserManagement/Bundle/Context/UserContext.php
- src/Akeneo/UserManagement/Bundle/EventListener/LocaleSubscriber.php
- src/Akeneo/UserManagement/Bundle/Resources/config/context.yml
- src/Akeneo/UserManagement/Bundle/Resources/config/event_subscribers.yml
- tests/back/UserManagement/Specification/Bundle/Context/UserContextSpec.php
- tests/back/UserManagement/Specification/Bundle/EventListener/LocaleSubscriberSpec.php
During API calls, the session is initialized because we access it on UserContext and LocaleSubscriber.
We don't have to create and save sessions during API calls.
The proposed solution is to check if the current firewall is stateless.
Since the API is of course stateless, it doesn't start a session anymore.
see https://github.com/akeneo/pim-community-dev/blob/master/config/packages/security.yml#L43-L48
> PIM-10026: fix session being stored during stateless calls

- src/Akeneo/Pim/Structure/Bundle/DependencyInjection/Configuration.php
- src/Akeneo/Platform/Bundle/AnalyticsBundle/DependencyInjection/Configuration.php
- src/Akeneo/Platform/Bundle/ImportExportBundle/DependencyInjection/Configuration.php
- src/Akeneo/Platform/Bundle/UIBundle/DependencyInjection/Configuration.php
- src/Akeneo/Tool/Bundle/ApiBundle/DependencyInjection/Configuration.php
- src/Akeneo/Tool/Bundle/BatchBundle/DependencyInjection/Configuration.php
- src/Akeneo/Tool/Bundle/ElasticsearchBundle/DependencyInjection/Configuration.php
- src/Akeneo/Tool/Bundle/StorageUtilsBundle/DependencyInjection/Configuration.php
- src/Oro/Bundle/ConfigBundle/DependencyInjection/Configuration.php
- src/Oro/Bundle/ConfigBundle/DependencyInjection/SettingsBuilder.php
- src/Oro/Bundle/DataGridBundle/Datasource/Orm/QueryConverter/QueryConfiguration.php
- src/Oro/Bundle/DataGridBundle/DependencyInjection/Configuration.php
- src/Oro/Bundle/DataGridBundle/Extension/Sorter/Configuration.php
- src/Oro/Bundle/DataGridBundle/Extension/Toolbar/Configuration.php
- src/Oro/Bundle/FilterBundle/DependencyInjection/Configuration.php
- src/Oro/Bundle/FilterBundle/Grid/Extension/Configuration.php
- src/Oro/Bundle/PimDataGridBundle/Extension/Sorter/Configuration.php
- src/Oro/Bundle/SecurityBundle/DependencyInjection/Configuration.php
- src/Oro/Bundle/TranslationBundle/DependencyInjection/Configuration.php
The tree builder configuration used in the PIM is deprecated.
Fix done with Rector rule `RootNodeTreeBuilderRector`
> BH-681: RootNode Tree Builder Rector

- cypress/support/commands.js
Cypress tests have stability issue when switching from "grouped" to "ungrouped" view in product list page because we try to access to the first element of the product list without waiting for DOM ready
> BH-691 : [cypress] wait for DOM to be ready when switching view in product list

- cypress/support/commands.js
[Cypress] Add a check when reloading products : 
1. Check for loading mask appearence
2. Wait for xhr completion
3. Check for loading mask deletion (the DOM should be reloaded before mask deletion)
> BH-691: [Cypress] Add check when reloading products

- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/product/edit/field/with-label.js
Actually the export with label is available for published product when code is not the default one, in this PR I create a JobInstanceFormProvider dedicated for published product and i remove ugly fix
> RAC-613: Fix export with label is not available for published product we cannot check it by it's code

- src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/AppRoleWithScopesFactory.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/apps.yml
- src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/AppRoleWithScopesFactoryIntegration.php
- src/Akeneo/UserManagement/Bundle/Resources/config/model/doctrine/Role.orm.yml
- src/Akeneo/UserManagement/Component/Model/Role.php
- src/Akeneo/UserManagement/Component/Model/RoleInterface.php
- upgrades/schema/Version_6_0_20210817135301_add_role_type_column.php
For activating an App, and for creating the underlying Connection, we need a dedicated User Role with the ACLs corresponding to the requested scopes.
To be able to distinguish this new role type from other roles, we've added a new discriminator column in the `oro_access_role` table.
> CXP-812: create an App Role for OAuth scopes

- front-packages/akeneo-design-system/src/components/Preview/Preview.stories.mdx
- front-packages/akeneo-design-system/src/components/Preview/Preview.tsx
- src/Akeneo/Tool/Bundle/MeasureBundle/Manager/MeasureManager.php
- src/Akeneo/Tool/Bundle/MeasureBundle/spec/Manager/MeasureManagerSpec.php
- Add familyExists method in Measure manager
- Fix white space rendering on Preview component
Before:
After:
> RAC-755: Add familyExists method in Measure manager

- .circleci/config.yml
In this PR, we are commenting the `test_database` step. This step is only useful for GA versions and it prevents us (the Onboarder team) from validating Onboarder bundle tags.
The same PR has been merged on the EE.
> OB-969: Comment test_database step until next GA

- CHANGELOG.md
- src/Akeneo/Pim/Structure/Bundle/Doctrine/ORM/Repository/FamilyRepository.php
- tests/back/Pim/Structure/Integration/Doctrine/ORM/Repository/FamilyRepositoryIntegration.php
Fix the get families with variant query to select distinct results in order for the limit parameter to work as intended.
Before, with a limit of 20, the query would return multiple times the same family, as the select was not distinct:
After the DISTINCT, we have the correct number of results:
> PIM-10037: Fix family variant query to return correct number of results

- .php_cs_symfony.dist
- make-file/dev.mk
**Note:** ~The 2 last commits are simple examples of what the new rules are, and are not meant to be merged in this PR~ the commits were removed
This PR is an attempt to homogenize the code style in the pim's codebase. The goal is to apply the `@Symfony` php-cs-fixer ruleset on updated / new files, but not change the CI's config (with more permissive rules) in order not to have a failing build if some files were not updated according to the new rules. This will allow migrating the codebase progressively, and avoid a big PR with all the code base updated at once, which would cause a lot of file conflicts, and tedious PR rebases.
In order to do so, I added a new makefile target, which can be used at will or in the following pre-commit …
> Symfony codestyle

- front-packages/akeneo-design-system/src/components/Dropdown/ItemCollection/ItemCollection.unit.tsx
- front-packages/akeneo-design-system/src/hooks/useAutoFocus.ts
- front-packages/akeneo-design-system/src/hooks/useAutoFocus.unit.ts
The Dropdown Component was not working with autofocus, because it is displayed "after" the call of focus()
The timeout fix this.
> CPM-356: Fix useAutoFocus

- upgrades/schema/Version_4_1_20200127171059_unauthorized_view_all_jobs_permission.php
This migration is failing when testing for 4.0 upgrade to master
https://app.circleci.com/pipelines/gh/akeneo/pim-community-standard/3898/workflows/f26b907f-11c2-4708-90b2-d72972052742/jobs/5516
We try to fetch the Roles with Doctrine ORM and the Role entity is not compatible with a 4.0 database because of the `type` column not existing in 4.0: https://github.com/akeneo/pim-community-dev/blob/master/src/Akeneo/UserManagement/Bundle/Resources/config/model/doctrine/Role.orm.yml#L20
By fetching only the role column, we are sure this migration will be compatible with both databases.
> CXP-812: fix migration

- .circleci/config.yml
- docker-compose.yml
Gain: ~2m30 for building PIM dev
The front and back cache layers were removed during the rework of the CI to launch the EE edition. It was existing in 4.0.
It was a different approach: node_modules and vendor were cached directly.
Such approach is not recommended with `yarn`, and same for composer. Instead, it's recommended to store in cache the global cache dependency directory and let the package manager to do its stuff. It is `.composer` for PHP and `.cache/.yarn` for JS.
Also, there is another cache: Cypress. It is very costly to build the package both in **local** and in the **CI**, because this cache is not mount in docker (and also not persisted as cache on the CI). 
**Note 1**: the cache key `package.json` is not necessary …
> TIP-1541: add a front and back cache layer on dependencies

- src/Akeneo/Pim/Enrichment/Component/Product/Query/AbstractEntityWithValuesQueryBuilder.php
- src/Akeneo/Pim/Structure/Bundle/Resources/config/validation/attribute.yml
- tests/back/Pim/Enrichment/Integration/PQB/ProductQueryBuilderIntegration.php
- tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/ProductAndProductModelQueryBuilderFactorySpec.php
- tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/ProductQueryBuilderFactorySpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Query/ProductModelQueryBuilderSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Query/ProductQueryBuilderSpec.php
- tests/back/Pim/Structure/Integration/Attribute/Validation/NonAvailableAttributeCodeIntegration.php
Before the query builder was case sensitive . That means if the attribute code is `test` we cannot filter on `TEST`.  
It was like that because we can create some attribute with code like `CATEGORIES`, `FAMILIES`, ... So when a filter is added on `categories` we cannot know if this refers to the system filter or the attribute filter.  
Having the PQB case sensitive provides some bad UX, as the PIM is case insensitive almost everywhere, and not here.  
Now the PQB is case insensitive. To do that:
- now we forbid the creation of attribute with `CATEGORIES` code. So the conflict could not happen
- Our SAAS environments does not have attribute like that, so there is no conflict with the existent attribute
- the PQB is now simplified, and we …
> PIM-10063: make query builder case insensitive for attribute filter

- CHANGELOG.md
- front-packages/shared/src/components/Navigation/SubNavigation.tsx
Added explicit container so that legacy modules can contextually add content into sub-navigation panel.
This is useful for filters that are inject through jQuery
> PIM-10029 Added named container to sub-navigation panel

- front-packages/akeneo-design-system/src/components/Input/NumberInput/NumberInput.tsx
The increment and decrement callbacks are not updated if the value is updated from outside. It can lead to very weird bugs. As it's related to external model, I don't really know if it's relevant to add a test to this
> RAC-fix-number: fix number input on increment/decrement

- src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/Consolidation/ConsolidateProductScores.php
Check if the list of product scores is not empty before saving it
> SDS-20187: fix wrong check before saving consolidated product scores

- src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/Consolidation/ConsolidateProductScores.php
Check if the list of product scores is not empty before saving it
> SDS-20187: backport in 5.0, fix wrong check before saving consolidated product scores

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Cursor.php
This PR fix the following error: 
`Typed property Akeneo\Pim\Enrichment\Bundle\Elasticsearch\Cursor::$result must not be accessed before initialization./srv/pim/src/Akeneo/Pim/Automation/RuleEngine/Bundle/Controller/InternalApi/GetImpactedProductCountController.php:70,/srv/pim/vendor/symfony/http-kernel/HttpKernel.php:158,/srv/pim/vendor/symfony/http-kernel/HttpKernel.php:80,/srv/pim/vendor/symfony/http-kernel/Kernel.php:201,/srv/pim/public/index.php:20{/code}`
When does this error happen ?
- Only on production because in production we call getResult without initialized $result. Before https://github.com/akeneo/pim-enterprise-dev/pull/11662. The cursor was initialized when counting `count($subjectSet->getSubjectsCursor())`  but now in …
> PIM-10071: Fix fatal error in case of Cursor::getResults is called without been initialized

- .circleci/config.yml
**Put front packages in cache to speed up compilation time**
DSM was rebuilt during `make front-packages`, even if a cache of the DSM already exists. Indeed, only the `lib` directory was put in the cache. `yarn` was not able to detect that the build is up to date with the source.
A solution would be to have a different behavior between `make front-packages` in the CI and in local. But it defeats the purpose of why we used `make` initially (reproducibility). 
The best option is to put in cache the whole front package. Indeed, yarn does not rebuild the package if it's already built thanks to the file `tsconfig.build.tsbuildinfo`. 
It can be applied for every front packages.
**Put dockerfile in cache**
PHP Docker image is rebuilt in each PR, even if the Dockerfile or `docker/` didn't change …
> TIP-1542: add cache on Dockerfile and front package dependencies

- CHANGELOG.md
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
YAML: Keys like "yes" or "no" evaluate to true and false by Crowdin.
In order to use the strings 'yes' and 'no' as keys, I needed to wrap them with quotes.
> - PIM-10077: Fix the "product image" filter display (untranslatable values on languages other than english)

- CHANGELOG-5.0.md
- src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/context/AttributeGroupsStatusContext.tsx
- src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/context/index.ts
- src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/index.ts
- src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/hooks/AttributeGroup/index.ts
- src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/hooks/AttributeGroup/useFetchAllAttributeGroupsStatus.ts
- src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/hooks/index.ts
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/infrastructure/hooks/AttributeGroup/useFetchAllAttributeGroupsStatus.unit.ts
Backport of PIM-9671: 
https://github.com/akeneo/pim-enterprise-dev/pull/10360
https://github.com/akeneo/pim-community-dev/pull/13888
> PIM-10073: [Backport] DQI de-activation on attribute group is not fully taken into account

- CHANGELOG.md
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/mass-edit/form/form.js
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/mass-edit/form.html
- src/Oro/Bundle/PimDataGridBundle/Resources/translations/jsmessages.en_US.yml
Add a translation key for the former hardcoded "Select action" label on the mass action selection screen
> PIM-10074: Add translation key for mass action selection

- Makefile
- std-build/Makefile
The correct spelling of the `--remove-orphans` flag is plural, see: https://docs.docker.com/compose/reference/down/
On docker-compose v2, using it without the `s` will not work:
> RAC: Fix --remove-orphans typo

- src/Akeneo/Channel/.php_cd.php
- src/Akeneo/Channel/Bundle/Twig/LocaleExtension.php
- src/Akeneo/Pim/Enrichment/.php_cd.php
- src/Akeneo/Pim/Enrichment/Bundle/Twig/AttributeExtension.php
- src/Akeneo/Pim/Enrichment/Bundle/Twig/CategoryExtension.php
- src/Akeneo/Platform/Bundle/AnalyticsBundle/Twig/UpdateExtension.php
- src/Akeneo/Platform/Bundle/NotificationBundle/Twig/NotificationExtension.php
- src/Akeneo/Platform/Bundle/UIBundle/Twig/AttributeExtension.php
- src/Akeneo/Platform/Bundle/UIBundle/Twig/ContentSecurityPolicyExtension.php
- src/Akeneo/Platform/Bundle/UIBundle/Twig/ExternalJavascriptDependenciesExtension.php
- src/Akeneo/Platform/Bundle/UIBundle/Twig/LocaleExtension.php
- src/Akeneo/Platform/Bundle/UIBundle/Twig/Node/PlaceholderNode.php
- src/Akeneo/Platform/Bundle/UIBundle/Twig/ObjectClassExtension.php
- src/Akeneo/Platform/Bundle/UIBundle/Twig/StyleExtension.php
- src/Akeneo/Platform/Bundle/UIBundle/Twig/TranslationsExtension.php
- src/Akeneo/Platform/Bundle/UIBundle/Twig/UiExtension.php
- src/Akeneo/Platform/Bundle/UIBundle/Twig/VersionExtension.php
- src/Akeneo/Platform/Bundle/UIBundle/Twig/ViewElementExtension.php
- src/Akeneo/Tool/Bundle/BatchBundle/Notification/MailNotifier.php
- src/Akeneo/UserManagement/.php_cd.php
- src/Akeneo/UserManagement/Bundle/Twig/AclGroupsExtension.php
- src/Oro/Bundle/ConfigBundle/Twig/ConfigExtension.php
- src/Oro/Bundle/DataGridBundle/Twig/MetadataExtension.php
- src/Oro/Bundle/FilterBundle/Twig/AbstractExtension.php
- src/Oro/Bundle/FilterBundle/Twig/RenderHeaderExtension.php
- src/Oro/Bundle/FilterBundle/Twig/RenderLayoutExtension.php
- src/Oro/Bundle/PimDataGridBundle/Twig/FilterExtension.php
- src/Oro/Bundle/SecurityBundle/Twig/OroSecurityExtension.php
- tests/back/Channel/Specification/Bundle/Twig/LocaleExtensionSpec.php
- tests/back/Platform/Specification/Bundle/UIBundle/Twig/ViewElementExtensionSpec.php
Twig_* classes will be deprecated in Twig v3 that we will use with Symfony 5.
> BH-681: Fixes Twig deprecated classes

- src/Akeneo/UserManagement/Bundle/Resources/config/model/doctrine/Group.orm.yml
- src/Akeneo/UserManagement/Component/Model/Group.php
- src/Akeneo/UserManagement/Component/Model/GroupInterface.php
- tests/back/UserManagement/Integration/Bundle/Export/ExportUserGroupIntegration.php
- upgrades/schema/Version_6_0_20210917103700_add_user_group_default_permissions.php
For the Activate App feature, we want to be able to configure default permissions to an user group (since each app will have a dedicated user group).
Basically, we add a new JSON column, `{[key: string]: boolean}` where different features in EE are able to add dynamically setup default values for their permissions.
Example:
```
{"attribute_group_view": true, "asset_familly_view": true}
```
See the PR in EE for examples: https://github.com/akeneo/pim-enterprise-dev/pull/11815/files
> CXP-872: Add a default_permissions column to the user group table

- src/Akeneo/Connectivity/Connection/front/src/connect/hooks/use-fetch-apps.ts
- src/Akeneo/Connectivity/Connection/front/src/connect/hooks/use-fetch-extensions.ts
- src/Akeneo/Connectivity/Connection/front/src/connect/pages/MarketplacePage.tsx
When the marketplace is not available, like this afternoon, an expected error is thrown when trying to retrieve extensions.
Sadly, it was not correctly handled in the front.
In the following snippet, the setExtensions is only called when the Promise is rejected.
The exception we were throwing was thrown before the Promise of `response.json` was started so, it was not catched.
```
fetchExtensions()
.then(setExtensions)
.catch(() => setExtensions(false));
```
> CXP-871: fix how we catch marketplace errors in the front

- tests/back/Integration/IntegrationTestsBundle/Loader/FixturesLoader.php
The catalog parameter is required for trial edition when installer events are triggered. We define the catalog name during the installation of the required jobs during the initialization of integration tests
> PIM-464: the catalog parameter is required for enterprise edition when the post_load_fixture

- CHANGELOG.md
- src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/text-filter.js
This PR fixes a bug in the product grid for all filters that can be partially hidden due to the content (cf screenshot) and theirs position at the bottom at the filters list. This is the case for simple select, multi select, reference entities and assets attributes. To fix that, I called an already existing method to recalculate the position of the filter popin every time an item is added (or deleted) to the selected items.
The same method is already used when we scroll in the product grid's filters list, to recalculate the popin position.
> PIM-10085: Fix product grid filters with multiple selectable values going out of screen when too many values are selected

- .circleci/config.yml
Running Cypress over a PIM in dev has two drawbacks:
- the app is slower
- we can have issues with selector because of the debug bar when targeting buttons for example
> Run cypress in prod mode

- front-packages/akeneo-design-system/src/components/Badge/Badge.stories.mdx
- front-packages/akeneo-design-system/src/components/Button/Button.stories.mdx
- front-packages/akeneo-design-system/src/components/Checkbox/Checkbox.stories.mdx
- front-packages/akeneo-design-system/src/components/Helper/Helper.stories.mdx
- front-packages/akeneo-design-system/src/components/IconButton/IconButton.stories.mdx
- front-packages/akeneo-design-system/src/components/IconCard/IconCard.stories.mdx
- front-packages/akeneo-design-system/src/components/Information/Information.stories.mdx
- front-packages/akeneo-design-system/src/components/Input/BooleanInput/BooleanInput.stories.mdx
- front-packages/akeneo-design-system/src/components/Link/Link.stories.mdx
- front-packages/akeneo-design-system/src/components/MessageBar/MessageBar.stories.mdx
- front-packages/akeneo-design-system/src/components/Modal/Modal.stories.mdx
- front-packages/akeneo-design-system/src/components/Navigation/MainNavigationItem/MainNavigationItem.stories.mdx
- front-packages/akeneo-design-system/src/components/Pill/Pill.stories.mdx
- front-packages/akeneo-design-system/src/components/Tiles/Tiles.stories.mdx
- front-packages/akeneo-design-system/src/guidelines/Iconography.stories.mdx
- front-packages/akeneo-design-system/src/guidelines/Illustration.stories.mdx
In this PR :
- Remove the following warning deprecation on storybook :
Link to the deprecation: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-controloptions 
> RAC-898: Fix DSM deprecation warning

- front-packages/akeneo-design-system/.github/workflows/deploy.yml
Actually the gh-pages are not cleaned after merge: https://github.com/akeneo/akeneo-design-system/tree/gh-pages
In this PR : 
Fix the github action called "Cleanup unused staging envs" (https://github.com/akeneo/akeneo-design-system/runs/3642544224?check_suite_focus=true) the cleanup-staging.js script is not present in the branche gh-pages branch
> RAC-897: Fix cleanup-staging.js is not present in gh-pages the github action cannot be executed successfully

- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
- src/Akeneo/Connectivity/Connection/front/src/connect/components/AppWizardWithSteps/AppWizardWithSteps.tsx
- src/Akeneo/Connectivity/Connection/front/src/connect/hooks/use-confirm-authorization.ts
- src/Akeneo/Connectivity/Connection/front/src/shared/notify/notify.interface.ts
- src/Akeneo/Connectivity/Connection/front/src/shared/permission-form-registry/permission-form-registry.interface.ts
- src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/AppWizardWithSteps/AppWizardWithSteps.test.tsx
- src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/AppWizardWithSteps/Permissions.test.tsx
- src/Akeneo/Connectivity/Connection/workspaces/permission-form/src/registry/PermissionFormRegistry.ts
Added confirm handling for App Wizard with steps
Sends confirm App request then sequentially saves each form provider
> CXP-840 Confirm App Wizard with steps

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/SequentialEditController.php
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/controllers.yml
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/routing/internal_api/sequential_edit.yml
- src/Oro/Bundle/DataGridBundle/Extension/MassAction/MassActionParametersParser.php
- src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/action/sequential-edit-action.js
a proactive correction on a error log received in datadog. 
probably du to get url above 2048 char with query string param.
> PIM-10062: compute default value for missing filter in sequential edit

- src/Akeneo/Connectivity/Connection/back/Domain/Apps/Persistence/Query/GetConnectedAppIdAndUserGroupQueryInterface.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Controller/ConfirmAuthorizationAction.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Persistence/Query/GetConnectedAppIdAndUserGroupQuery.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/apps.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/controllers.yml
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Apps/ConfirmAuthorizationEndToEnd.php
- src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/Persistence/Query/GetConnectedAppIdAndUserGroupQueryIntegration.php
Updated confirm authorization endpoint
The App Wizard requires a user group name to save permissions via form providers
So these changes updates Confirm authorization endpoint to return an id as well as user group name (that was created for the app)
> CXP-891 Updated confirm authorization endpoint

- CHANGELOG.md
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/main-image.ts
When the main image of a product is on an attribute of type asset collection, the image can be different for the current locale and channel.
The problem has been fixed for the locale switching here https://github.com/akeneo/pim-community-dev/pull/14202/
But not for the channel switching
> PIM-10096: Reload PEF main image on channel switching

- CHANGELOG.md
- src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/family/index.yml
- src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/family/grid/mass-actions.ts
- src/Oro/Bundle/PimDataGridBundle/Adapter/OroToPimGridFilterAdapter.php
- src/Oro/Bundle/PimDataGridBundle/spec/Adapter/OroToPimGridFilterAdapterSpec.php
This PR fixes 2 issues in the family datagrid when we add families to the selection in multiple steps. For example add the first family, then search for a second one, add it to the selection (first issue : the counter at the bottom of the screen displayed 1 selected family) and then launch the bulk action (second issue : only one family was displayed as selected in the bulk action modal. 
The first issue was a frontend issue, already fixed for the product grid in this PR : https://github.com/akeneo/pim-community-dev/pull/15032. I fixed it the same way for the families.
The second issue was on the backend side : the selected families were used as filters to retrieve the family entities, but the search filter was too, so the 2 filters …
> PIM-10101: Fix incorrect count of families selection in the family grid

- front-packages/shared/src/components/page/PageHeader.tsx
- tests/legacy/features/pim/enrichment/product/mass-action/quick-export/quick_export_with_localized_data.feature
Sometimes on behat test the page is not correctly displayed. For instance the right side is truncated and we can't access the notification button/menu on the right.
It's because the text is too long:
Now with the fix the text is truncated:
> CPM-400: fix notification check for behat

- src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Controller/AuthorizeAction.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/OAuth/CreateAccessToken.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Validation/CodeChallengeMustBeValidValidator.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/apps.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/controllers.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/routing.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/validators.yml
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Apps/AuthorizeEndToEnd.php
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Apps/RequestAccessTokenActionEndToEnd.php
- src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/Validation/AccessTokenRequestValidationIntegration.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Apps/OAuth/CreateAccessTokenSpec.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Apps/Validation/CodeChallengeMustBeValidValidatorSpec.php
- src/Akeneo/Connectivity/Connection/tests/Context/AppActivateContext.php
- src/Akeneo/Connectivity/Connection/tests/features/activate_an_app.feature
**Issues:**
- With the previous version, an expiration date was attributed to the token with `time() + null`, which mean that the token was expiring immediately ...
- When using fake apps, don't check the code challenge in the marketplace
- When validating a token request, don't call the marketplace if any of `code_challenge` & `code_identifier` are empty, it will fail anyway on the `NotBlank`.
- the endpoint for requesting a token should be `POST`, not `GET`
**Bonus:**
- I've implemented the last step of the behat scenario
- When an app is already authorized, skip the wizard and redirect directly with the Authorization Code. *This is a workaround waiting for the proper re-activation feature*.
> CXP-938: Fix issues with Activate OAuth

- src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Model/Read/KeyIndicator.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Domain/Model/Read/KeyIndicatorSpec.php
Round ratio extremities to avoid having 100% while there's at least one entity to improve and to avoid having 0% while there's at least one good entity.
> PLG-472: Improve rounding key indicators extremities

- tests/legacy/features/Context/Page/Base/Base.php
This PR should fix the following flaky tests : 
- tests/legacy/features/pim/structure/read-only-attribute/attribute.feature:32
- tests/legacy/features/pim/permission/product-model/edit_product_model.feature:15
Now we spin while the field is found. Tested locally 200x without error
> RAC-966: Get field before clicking it

- tests/legacy/features/Context/Page/Base/ProductEditForm.php
- tests/legacy/features/Context/WebUser.php
- tests/legacy/features/pim/enrichment/reference-data/product/display_history.feature
With a test like this:
```
Given I change the "Weather conditions" to "Hot, Cold, Dry, Wet"
And I save the product
```
The select2 component is updated by triggering js events.
Sadly, the save button is then clicked before all the changes are propagated to the form state stored in backbone.
That's why only a part of the selected values are saved and we randomly have the following error: `Expected product field "Weather conditions" to contain "cold, dry, hot, wet", but got "dry, hot, wet".`
I'm proposing that each time we fill a field in the PEF, we spin until the value is as expected.
It should prevent this race condition.
> Assert that the value is correctly set in the field

- src/Akeneo/UserManagement/Bundle/Resources/views/Reset/reset.html.twig
The reset form page was in 500 again because of the duplicate renderer of the `_token` field:
```log
An exception has been thrown during the rendering of a template ("Field "_token" has already been rendered, save the result of previous render call to a variable and output that instead.") in "@PimUI/Form/pim-fields.html.twig".
```
The changelog was already updated in this [PR](https://github.com/akeneo/pim-community-dev/pull/15642)
> PIM-10145: Fix duplicate form token

- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Command/ConsolidateDashboardRatesCommand.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Command/InitializeProductsEvaluationsCommand.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Command/LaunchEvaluationsCommand.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Command/MigrateProductCriterionEvaluationCommand.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Command/PrepareEvaluationsCommand.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Command/PurgeOutdatedDataCommand.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Command/RecomputeProductsScores.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Command/SchedulePeriodicTasksCommand.php
- src/Akeneo/Platform/Bundle/InstallerBundle/Command/DatabaseCommand.php
- src/Akeneo/Tool/Bundle/ApiBundle/Command/ListClientsCommand.php
There are several avantages to use lazy commands. From a performance point of vue, I've traced **a lot** of services instanciated just to regsiter commands.
I create this PR because I've run into an issue when warming up the application without a database container up. One of the instantiated commands triggered a listener trying to make a database call and then resulting in an error when I had no use of this call (only seen in APP_DEBUG=1 mode).
From https://symfony.com/blog/new-in-symfony-3-4-lazy-commands:
> the Symfony Console suffered a shortcoming since day one: you must instantiate all commands to register them in the console application. The reason is that even the command name itself is defined inside a method called configure(), so you must instantiate the command class to …
> BH-859: Use lazy commands

- upgrades/schema/Version_6_0_20210331105730_remove_datagrid_view_unique_label_constraint.php
The constraint is already remove by a backport in https://github.com/akeneo/pim-community-dev/pull/15580 and can therefore not exists in 5.0. We must add a condition to remove it only if exists.
> Fix Version_6_0_20210331105730

- src/Akeneo/Platform/Job/front/process-tracker/src/feature/hooks/useJobExecutionTable.test.ts
- src/Akeneo/Platform/Job/front/process-tracker/src/feature/hooks/useJobExecutionTable.ts
- src/Akeneo/Platform/Job/front/process-tracker/src/feature/models/JobExecutionFilter.test.ts
- src/Akeneo/Platform/Job/front/process-tracker/src/feature/models/JobExecutionFilter.ts
- src/Akeneo/Platform/Job/front/process-tracker/src/feature/models/index.ts
- src/Akeneo/Platform/Job/front/process-tracker/src/feature/pages/JobExecutionList.test.tsx
- src/Akeneo/Platform/Job/front/process-tracker/src/feature/pages/JobExecutionList.tsx
- Adding a `JobExecutionFilter` model to better represent the filters used to query job executions
- Display placeholders when no results and no search result
> RAC-1025: Add JobExecution filter model

- src/Akeneo/Platform/Job/back/Application/SearchJobExecution/SearchJobExecutionQuery.php
- src/Akeneo/Platform/Job/back/Infrastructure/Controller/IndexAction.php
- src/Akeneo/Platform/Job/back/Infrastructure/Query/SearchJobExecution.php
- src/Akeneo/Platform/Job/back/tests/.php_cd.php
- src/Akeneo/Platform/Job/back/tests/Integration/Infrastructure/Query/SearchJobExecutionTest.php
Handle sort column and directions in query to be able to sort all columns of job execution table.
> RAC-975: Backend service to query job executions should support sorting on each columns

- front-packages/shared/src/components/LocaleSelector.tsx
- front-packages/shared/src/components/LocaleSelector.unit.tsx
- front-packages/shared/src/models/locale.ts
Using the singular label on the Locale Selector to be more consistent
> RAC-1010: Use common label on LocaleSelector

- src/Akeneo/Platform/Job/front/process-tracker/src/feature/pages/JobExecutionList.tsx
Filter state are now persisted in browser local storage.
The page is not keep cause search bar debounce useEffect but it better because it will avoid failure when job are purged between filter appliance and page reload.
> RAC-973: Process tracker filters should be persisted in the local storage

- src/Akeneo/Connectivity/Connection/back/Application/Apps/Service/CreateConnection.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/Dbal/Repository/DbalConnectionRepository.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Persistence/InMemory/Repository/InMemoryConnectionRepository.php
- src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/Command/CreateAppWithAuthorizationHandlerIntegration.php
A Connection has a column `type`. Its `default` by default.
When creating an App, the underlying Connection should have the type `type` to be distinguishable from the others.
> CXP-765: fix type of connection created for an app

- CHANGELOG.md
- src/Akeneo/Tool/Component/FileStorage/PathGenerator.php
- src/Akeneo/Tool/Component/FileStorage/spec/PathGeneratorSpec.php
On the Asset manager, when uploading a file with a filename longer than 100 characters, the thumbnail generation would fail. This was because the path generator used to store the file would try to use the `$file->getExtension()` function but this would return an empty string on AM files as it using a different filename than the original filename of the actual file. Using the `UploadedFile::getClientOriginalExtension` method fixes this issue.
> PIM-10160: Fix AM thumbnail generation when filename is longer than 100 characters

- CHANGELOG-5.0.md
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/bootstrap/js/bootstrap.js
https://akeneo.atlassian.net/browse/PIM-10162
When dropdown will overlap the bottom page, we added the top position so the list was displayed to the top. But we didn't test if the list will overlap the top. Now if the list overlaps the bottom and the top, we let the bottom position.  
> PIM-10162: Fix dropdown vertical position

- tests/legacy/features/Behat/Decorator/Field/Select2Decorator.php
Previously, we used PHP click method to click on a item in a Select2 box.
This "click", sometimes, was instable :shrug: 
I replaced it by a pure JS method to use "mouseup" method, because select2 lib only uses "onMouseUp" event to trigger selection.
After 2 hours in my computer, this raises no errors, let's try this method.
> [CI] Fix multiselect fill value

- src/Akeneo/Platform/Job/back/Infrastructure/Installer/JobInstaller.php
- src/Akeneo/Platform/Job/back/Infrastructure/Symfony/Resources/config/services.yml
- src/Akeneo/Platform/Job/front/process-tracker/src/feature/components/JobExecutionList/JobExecutionTable.tsx
- src/Akeneo/Platform/Job/front/process-tracker/src/feature/pages/JobExecutionList.tsx
- upgrades/schema/Version_6_0_20211124163100_add_index_to_improve_search_on_job_execution.php
- upgrades/test_schema/Version_6_0_20211124163100_add_index_to_improve_search_on_job_execution_Integration.php
In this PR : 
- I added indexes on job execution in order to improve performance of the new process tracker.  
- I used the same translation key that the filter (Some job type are not translated with the previous translation key)
- I reset now the page when sorting another column (there is no sense to keep the actual page) 
> RAC-1078: Add indexes on job execution to fix search performances

- tests/legacy/features/pim/enrichment/product/export/export_products_by_text.feature
In this PR i fixed the following behat: `tests/legacy/features/pim/enrichment/product/export/export_products_by_text.feature`
Why we have the error ?
Since https://github.com/akeneo/pim-community-dev/pull/15693 we passed from : symfony/css-selector: "v3.4.47" to "v5.3.4",
Now CssSelectorConverter (used to convert css path to xpath) use a cache. Problem is that the path have change between the time where user add the filter and user change the locale. 
> RAC-1063: Fix instable test due to CssSelectorConverter cache

- src/Akeneo/Pim/Structure/Bundle/Resources/config/queries.yml
Since #15776 was merged, the completeness calculation does not take table attributes into account. This is a temporary fix to reinstate the former behavior, this change will be reverted when https://github.com/akeneo/pim-enterprise-dev/pull/12290 is merged
> CPM-331: Default behavior for completeness calculation of table attribute values

- composer.json
- composer.lock
`symfony/cache` was installed but version was not described in our composer.json. The version 6.0 was picked in EE (no composer.lock) and build failures happened https://app.circleci.com/pipelines/github/akeneo/pim-enterprise-dev/52832/workflows/d1f8c8f3-390f-42e6-99aa-0a87599d67c4/jobs/277307
Now the version is fixed
> Fix symfony/cache to 5.4

- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/fields/field.js
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/form-tabs.js
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/common/edit/properties.js
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/product/edit/content.js
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/form/form-tabs.html
There was some glitches with the previous way of computing errors on form tabs
Sometimes, a red badge stays in the tab, even if the error was fixed.
The previous way was too "random", so we refactor it to register errors and not doing some increment/decrement weird counting.
> CPM-318: Refactor tabs errors

- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
- src/Akeneo/Connectivity/Connection/front/src/common/components/PageHeader.tsx
- src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApp/ConnectedAppContainer.tsx
We prefixed the introduction sentence by "App".
With an App called `App prototype`, it does `App App prototype needs to`.
I'm proposing to remove the word `App` from the sentence.
**Before**
**After**
----
The image in App Settings was not displayed, now it's working:
> CXP-984: Quick fixes on App display

- CHANGELOG-5.0.md
- src/Akeneo/UserManagement/Bundle/Controller/ResetController.php
- src/Akeneo/UserManagement/Bundle/Form/Handler/ResetHandler.php
Fixes: [PIM-10128](https://akeneo.atlassian.net/browse/PIM-10128)
Fixes security a breach where password reset enables user even if  the said user were previously disabled. 
Withdraws ability to reset the password as a inactive account:
- no reset password email send
- for existing emails : link will redirect to an error (just like when email expires)
> PIM-10128 Fixed disabled user activation after password reset

- front-packages/akeneo-design-system/src/components/Modal/Modal.tsx
- front-packages/akeneo-design-system/src/components/Modal/Modal.unit.tsx
Actually in the new process tracker the user is redirected to the job execution detail when the user stop it.
Why: 
As describe here the portal redirect event to the parent : https://fr.reactjs.org/docs/portals.html#event-bubbling-through-portals.
The parent have a onClick so the onClick is called no matter where the user clicks in the modal
Why it doesn't appear in the current grid:
Because the page is reloaded to reload the datagrid
> RAC-1091: Fix user is redirected to the job execution when user stop a job

- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
- src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApps/ConnectedAppCard.tsx
- src/Akeneo/Connectivity/Connection/front/src/connect/hooks/use-connected-apps.ts
- src/Akeneo/Connectivity/Connection/front/src/connect/hooks/use-fetch-apps.ts
- src/Akeneo/Connectivity/Connection/front/src/connect/pages/ConnectedAppsListPage.tsx
- src/Akeneo/Connectivity/Connection/front/src/model/Apps/connected-app.ts
- src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApps/ConnectedAppsCard.test.tsx
- src/Akeneo/Connectivity/Connection/front/tests/src/connect/hooks/use-connected-apps.test.ts
Here is the strategy.
- First, we fetch connected apps from the internal API.
- we render the view (the open app button is disabled)
- Then, we immediatly fetch all marketplace Apps from the marketplace API.
- If the marketplace API fails, nothing happens, the Open App stays disabled.
- If we successfully retrieved the marketplace Apps, we merge both responses and re-render.
Benefits:
- The Connected Apps UI is never slowed down by the marketplace
- The Connected Apps UI still works if the marketplace is down.
- Only 2 API calls are done, even with a lot of Connected Apps.
> CXP-1013: Add an Open App button to Connected Apps

- src/Akeneo/Connectivity/Connection/tests/Context/AppActivateContext.php
- src/Akeneo/Connectivity/Connection/tests/features/activate_an_app.feature
With this PR, in the behat scenario for activating an App, we are replacing:
`And it has an authorization code` which was only checking if there was an authorization code in the database
to 
`And it can exchange the authorization code for a token` which calls the Create Access Token endpoint, exchanging the Authorization code for a token.
> CXP-1010: update behat scenario

- src/Akeneo/Tool/Bundle/BatchBundle/Job/DoctrineJobRepository.php
On the revamped process tracker, we're reading the warning_count column in job_execution but it is never incremented.
> RAC-1079: Increment warning_count when adding warning

- src/Akeneo/Platform/Job/back/Application/SearchJobExecution/SearchJobExecutionHandler.php
- src/Akeneo/Platform/Job/back/Application/SearchJobExecution/SearchJobExecutionQuery.php
- src/Akeneo/Platform/Job/back/Infrastructure/Controller/IndexAction.php
- src/Akeneo/Platform/Job/back/Infrastructure/Query/SearchJobExecution.php
- src/Akeneo/Platform/Job/back/tests/Acceptance/Application/SearchJobExecution/SearchJobExecutionHandlerTest.php
- src/Akeneo/Platform/Job/back/tests/Integration/Infrastructure/Query/SearchJobExecutionTest.php
- src/Akeneo/Platform/Job/front/process-tracker/src/feature/models/JobExecutionFilter.test.ts
As we discuss [here](https://akeneo.slack.com/archives/C02CZHWASM6/p1638525168027500), it is better for code sense and readability to validate query at the beginning of handler instead of inside the search job execution.
> RAC-1101: Move query validation into handler

- CHANGELOG.md
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/ColumnConfigurator.less
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/VerticalList.less
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/export/product/edit/content/structure/attribute-list.html
- src/Oro/Bundle/PimDataGridBundle/Resources/public/templates/datagrid/column-selector/columns.html
- src/Oro/Bundle/PimDataGridBundle/Resources/public/templates/datagrid/column-selector/modal.html
- src/Oro/Bundle/PimDataGridBundle/Resources/public/templates/datagrid/column-selector/selected.html
In this PR I fixed the drag and drop in the column datagrid selector. 
Why we have the problem ?
Because the column does not have the same width depending on the length of label. When the attribute group label is too long the column does not take 30% the other take less. When we try to drag and drop we cannot drop in the right column because the width of the column is more than the column so the pointer is blocked.
Now the column are not anymore a flex-basic => it's a width so we need to handle the overflow
> PIM-10187: Fix impossible to configure the columns of the product grid if attribute labels are too long

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/Component/Product/Validator/AttributeValidatorHelper.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Validator/AttributeValidatorHelperSpec.php
- tests/legacy/features/Context/WebUser.php
Since PHP 8.0 implode throw an TypeError when separator is in the second parameter
> PIM-10193: fix TypeError(implode(): Argument #2 () must be of type ?array, string given)

- src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Controller/InternalApi/GetConnectedAppMonitoringSettingsAction.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/controllers.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/routing/apps.yml
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Apps/InternalApi/GetConnectedAppMonitoringSettingsActionEndToEnd.php
- src/Akeneo/Connectivity/Connection/front/src/connect/hooks/use-fetch-connected-app-monitoring-settings.ts
- src/Akeneo/Connectivity/Connection/front/src/model/Apps/monitor-settings.ts
- src/Akeneo/Connectivity/Connection/front/src/model/Apps/monitoring-settings.ts
- src/Akeneo/Connectivity/Connection/front/tests/src/connect/hooks/use-fetch-connected-app-monitoring-settings.test.ts
Prerequisite query for App monitoring feature:
- new endpoint to fetch Monitor settings for a connected app (flow type and auditable flag)
- associated hook
> CXP-758 monitoring settings query

- std-build/package.json
With this PR https://github.com/akeneo/pim-community-dev/pull/15258, a new workspace have been added but it not have been added in the standard
> BH-953: Fix pim-enterprise-standard by adding the new workspace

- src/Akeneo/Platform/Job/back/Infrastructure/Symfony/Resources/config/routing.yml
As we cannot modify the onboarder (https://github.com/akeneo/pim-onboarder/pull/879) for compatibility reason, i added the url used by onboarder
> RAC: Fix compatibility with onboarder

- upgrades/schema/Version_6_0_20211213191300_add_index_to_improve_process_tracker_count_query.php
- upgrades/test_schema/Version_6_0_20211213191300_add_index_to_improve_process_tracker_count_query_Integration.php
Depending on filters applied, the count query used to print the total result on top of process tracker page can take 2s. This index optimizes that query by putting the join column and filters column in the index.
Before : 
After :
These tests was done on the madeira cloned env.
> RAC-1106: add index to optimize count query

- CHANGELOG-5.0.md
- src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/ListItem.tsx
> PIM-10204: Use catalog locale for option labels in simple/multi select attributes

- src/Akeneo/Pim/Enrichment/Component/Product/Connector/Reader/Database/MassEdit/ProductAndProductModelReader.php
- src/Akeneo/Pim/Enrichment/Component/Product/Model/ProductModel.php
- src/Akeneo/Pim/Enrichment/Component/Product/Model/ProductModelInterface.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Model/ProductModelSpec.php
See https://github.com/akeneo/pim-enterprise-dev/pull/12541  
To fix the issue, we want to know which are the categories for the current level, and not have the categories of the parent.
> PIM-10203: add getCategoriesForThisLevel on product model interface

- src/Akeneo/Connectivity/Connection/back/Application/Apps/Command/RequestAppAuthenticationHandler.php
If the openid scope is not in the scope requested, empty the user consent scope column.
Catch those cases:
- from a connected app and a user who consented "openid profile email" to "profile email" -> remove consented scopes (was already catched by the condition)
- from a disconnected app (removed) and a user who consented "openid profile email" to "no openid requested anymore" -> remove consented scopes (this PR catch this case)
implies that all app users even from apps without openid requested, we create a consent line with empty scopes
other solution:
keep the if requested scope > 0 as is, but add another if which try to find the user in the user consent table to empty its scope column if needed. …
> reset user consent scope

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/factories.yml
- src/Akeneo/Pim/Enrichment/Component/Product/Factory/NonExistentValuesFilter/ChainedNonExistentValuesFilter.php
- src/Akeneo/Pim/Enrichment/Component/Product/Factory/NonExistentValuesFilter/NonExistentChannelLocaleValuesFilter.php
- src/Akeneo/Pim/Enrichment/Component/Product/Factory/NonExistentValuesFilter/OnGoingFilteredRawValues.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Factory/NonExistentValuesFilter/ChainedNonExistentValuesFilterSpec.php
https://akeneo.atlassian.net/browse/PIM-10206
When a product is loaded, the non existent values are cleaned. The ChainedNonExistentValuesFilter cleans the values by running several filters. Each filter handles a particular attribute type, and once the filter is ran the values are put in a "filtered values" list. So we know these values are already filtered and we don't touch them anymore.
The problem is there was a NonExistentChannelLocaleValuesFilter that is ran at the end to remove the values that are not attached to an existent locale/scope, and this filter does not handle already filtered values. So some values are not cleaned. It should filter ALL the values.  
The fix is to remove the NonExistentChannelLocaleValuesFilter in the …
> PIM-10206: Fix product and product model save when they had values for a deleted channel

- CHANGELOG.md
- src/Akeneo/Channel/Bundle/Twig/LocaleExtension.php
- src/Oro/Bundle/PimDataGridBundle/Resources/views/Property/currency_label.html.twig
- tests/back/Channel/Specification/Bundle/Twig/LocaleExtensionSpec.php
Fixing the currency settings crashing when the currency label for an unknown currency code was not found (because we are using Symfony\Component\Intl to retrieve currency labels)
> PIM-10208: Fix currency settings page crashing when label is not found

- CHANGELOG.md
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/family-variant/form/save.js
Fixes : [PIM-10198](https://akeneo.atlassian.net/browse/PIM-10198)
Initially the task was to update error message to display a user-friendlier message when saving family variant with wrong attributes.
However it appears that such [messages are already in place](https://github.com/akeneo/pim-community-dev/blob/master/src/Akeneo/Pim/Structure/Component/Validator/Constraints/FamilyVariant.php) and returned to the front end .
On the front side, [Family variant saver  handles saving](https://github.com/akeneo/pim-community-dev/blob/master/src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/family-variant/form/save.js)
Family variant saver does not personally handles errors but delegates it to [parent saver ](https://github.com/akeneo/pim-community-dev/blob/58a1d2b503d473426f95d5e213a10f5ff3 …
> PIM-10198 customised error notifications on family variant save

- .circleci/workflows/squads/octopus.yml
When introducing a new database migration, `test_back_data_migrations` is not enough to check that everything is good.
When we do, we need to launch the full CI.
So, this is useless to launch it everytime we change Connectivity code.
> CXP-1033: remove database migrations tests from octopus workflow

- make-file/connectivity-connection.mk
We are running phpunit integration with `CI=false` because it's ~3 times faster without parallelization in our case.
But we are not logging the tests results anymore and circleci cannot exploit them anymore.
This is a quick workaround.
> Cxp 1033 log phpunit

- src/Akeneo/Connectivity/Connection/back/Application/Apps/Command/ConsentAppAuthenticationHandler.php
- src/Akeneo/Connectivity/Connection/back/Application/Apps/Command/RequestAppAuthenticationHandler.php
- src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/Command/RequestAppAuthenticationHandlerIntegration.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Apps/Command/RequestAppAuthenticationHandlerSpec.php
Fix a regression where the consent modal was displayed to the user when only the openid scope was requested, instead of automatically consenting to it.
> Cxp 989 fix openid consent

- CHANGELOG.md
- upgrades/schema/Version_6_0_20211217145100_use_the_new_process_tracker_route.php
- upgrades/test_schema/Version_6_0_20211217145100_use_the_new_process_tracker_route_Integration.php
In this PR, i fixed the following error : 
`Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "pim_enrich_job_tracker_show" as such route does not exist.")." at /srv/pim/vendor/akeneo/pim-community-dev/src/Akeneo/Platform/Bundle/NotificationBundle/Resources/views/Notification/list.json.twig line 6`
Why we have this error ? 
Because when we deployed the process tracker revamp we have renamed the route name. 
Because notification redirect url is stored in database we forget it
> PIM-10210: Fix notifications can't be displayed

- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/form_extensions.yml
The `feature` option hides form_extensions, see https://github.com/akeneo/pim-community-dev/blob/417d8b3a0d2d29425a9b8422be1281476fc5cc9a/src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/config-provider.js#L22-L23
> CXP-1035: hide connected apps menu

- front-packages/shared/src/components/page/header/Illustration.tsx
- Use DSM Image component and accept other component to put in place of the illustration in the PageHeader
> RAC-1192: Accept components as Illustration in PageHeader

- .circleci/jobs/features/other.yml
See https://github.com/sebastianbergmann/phpunit/issues/4847. 
**This fix should be reverted as soon as either PHPUnit 9.5.11 or composer 2.2.2 is released.**
> Temporary CI fix: use phpunit's executable instead of composer one for onboarder tests

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/Processor/QuickExport/ProductAndProductModelProcessor.php
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/Writer/File/Csv/ProductModelWriter.php
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/Writer/File/Xlsx/ProductModelWriter.php
When a user launch a quick export of a product model with a grid context without id (code), the job fails because the `ProductModelWriter` does not have the code to retrieve media file. 
This PR uses the same way as the product quick export and set a `identifier` (which will not be added into exported file) property that will be use to fallback if code is not exported.
I'm not thrilled about this solution, feel free to suggest me a cleaner one.
> PIM-10217: Fix cannot quick export product model when id is not present in grid context

- CHANGELOG.md
- src/Akeneo/Pim/Structure/Bundle/Resources/config/model/doctrine/Attribute.orm.yml
- src/Akeneo/Tool/Bundle/MeasureBundle/Validation/Common/CodeValidator.php
- src/Akeneo/Tool/Bundle/MeasureBundle/tests/Acceptance/CreateMeasurementFamilyTest.php
- src/Akeneo/Tool/Bundle/MeasureBundle/tests/Acceptance/SaveMeasurementFamilyTest.php
- upgrades/schema/Version_6_0_20211221170000_modify_metric_family_and_default_metric_unit.php
- upgrades/test_schema/Version_6_0_20211221170000_modify_metric_family_and_default_metric_unit_Integration.php
Actually, we cannot create measurement attribute if measurement family or unit code is too long, a limit is set to 30 chars max in database datatype of `metric_family` and `default_metric_unit` columns. This PR set this limit to 100 chars max (same as `code` and `standard_unit` columns in `akeneo_measurement`).
> PIM-10214: Fix cannot create a measurement attribute if measurement family or unit code is too long

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Standard/Product/AssociationsNormalizer.php
Fixes : [PIM-10220](https://akeneo.atlassian.net/browse/PIM-10220)
AssociationsNormalizer filters code duplicates for associations products. However in some cases array is not indexed using integers as keys but strings producing following results:
This leads to a front end issues where an array is expected but object is given
This fix addresses this issue:
> PIM-10220 Fixed array indexed keys for AssociationsNormalizer

- make-file/test.mk
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/GetProductEvaluation.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/ProductEvaluation/CompleteEvaluationWithImprovableAttributes.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/ProductEvaluation/Enrichment/EvaluateCompleteness.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Model/Write/CriterionEvaluation.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/KeyIndicator/ComputeProductsEnrichmentStatusQuery.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Transformation/TransformCriterionEvaluationResultCodes.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Transformation/TransformCriterionEvaluationResultIds.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/services.yml
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/.php_cd.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Infrastructure/Persistence/Transformation/TransformCriterionEvaluationResultCodesIntegration.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Infrastructure/Persistence/Transformation/TransformCriterionEvaluationResultIdsIntegration.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Application/GetProductEvaluationSpec.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Application/ProductEvaluation/CompleteEvaluationWithImprovableAttributesSpec.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Application/ProductEvaluation/Enrichment/EvaluateCompletenessSpec.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Persistence/Transformation/TransformCriterionEvaluationResultCodesSpec.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Persistence/Transformation/TransformCriterionEvaluationResultIdsSpec.php
For the completeness criteria, we store in database the list of the codes of the attributes without value for each product, channel and locale. The problem is it can reach a huge volume of data.
To avoid that, these lists will not be persisted anymore, but re-calculated when needed (to display the recommendations in the PEF DQI tab)
We still need to persist the number of these attributes to calculate the key indicators. So we calculate and persist it in a new entry in the evaluation resust data.
> PLG-468: DQI - Optimize product evaluations storage

- make-file/test.mk
- upgrades/.php_cd.php
We want to avoid having schema migrations relying on services.
This PR starts to enforce it but includes exceptions for all existing dependencies.
This should prevent having new migrations relying on more services than what's currently allowed.
> CXP-1051: add php_cd on schema upgrades

- .circleci/jobs/features/other.yml
This reverts commit 6087c18e3afc365f3112153540d5d4605b7d8605.
This temporary fix is not needed anymore now that PHPUnit v9.5.11 is released
> Revert "Temporary CI fix: use phpunit's executable instead of composer one for onboarder tests"

- src/Akeneo/Connectivity/Connection/back/Infrastructure/Install/InstallSubscriber.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Install/Query/CreateTestAppTableQuery.php
- upgrades/schema/Version_6_0_20220103100000_add_test_app_table.php
I've left `user_id` nullable with `ON DELETE SET NULL` because if we have a `DELETE CASCADE` on it, and the related user is deleted, it would delete his test apps, not the related connected apps.
I think it's better that users are required to use our Command+Handler through the UI to delete a test app, it will take care of side effects instead of leaving the database in a unexpected state.
It's easy to display in the UI that the creator of the test app was deleted, if the value is null.
> CXP-1047: Add test app table

- src/Akeneo/Platform/Bundle/DashboardBundle/Resources/translations/messages.en_US.yml
- src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/translations/jsmessages.en_US.yml
- src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/components/Widgets/LastOperationsWidget.tsx
- src/Oro/Bundle/PimDataGridBundle/Resources/translations/messages.en_US.yml
The following translation are not used anymore since we have released the process tracker revamp, we need to cleanup it:
```
pim_dashboard.widget.last_operations.job_type.* (CE and EE)
pim_datagrid.cells.type.*
```
> RAC-1199: Remove unused translations

- src/Akeneo/Connectivity/Connection/back/Domain/Apps/Model/ConnectedApp.php
- src/Akeneo/Connectivity/Connection/back/Domain/Marketplace/DTO/GetAllTestAppsResult.php
- src/Akeneo/Connectivity/Connection/back/Domain/Marketplace/Model/App.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Marketplace/GetAllTestAppsQuery.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Marketplace/GetAppQuery.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Marketplace/GetTestAppQuery.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/marketplace.yml
- src/Akeneo/Connectivity/Connection/back/tests/Integration/Marketplace/GetAllTestAppsQueryIntegration.php
- src/Akeneo/Connectivity/Connection/back/tests/Integration/Marketplace/GetTestAppQueryIntegration.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Domain/Marketplace/Model/AppSpec.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Marketplace/GetAppQuerySpec.php
The `GetAppQuery` is at the center of our Wizard.
It is called before the connect and during the Wizard.
By hooking into it, we can check if there is a test App matching the id of the App being connected.
We can also reuse our `App` DTO by adding a new named constructor.
This way, there is no need to rewrite other parts of the Wizard process.
Also, the WebMarketplaceApi service stays unchanged.
> CXP-1039: returns a test app in GetAppQuery when necessary

- composer.json
- composer.lock
- symfony.lock
In doctrine/doctrine-bundle v2.5.4, an issue prevented the Doctrine\Bundle\DoctrineBundle\Controller\ProfilerController from being instantiated if the twig or profiler services had not been priorly initialized in the service container. This made our check-service-instantiability check fail.
It did not impact the CE version thanks to the committed composer.lock, but we had to fix doctrine-bundle version in EE. The issue was fixed in doctrine-bundle v2.5.5, so we can upgrade now
> PIM-10225: Upgrade doctrine-bundle to v 2.5.5

- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
- src/Akeneo/Connectivity/Connection/front/src/connect/components/TestApp/CreateTestAppCredentials.tsx
- src/Akeneo/Connectivity/Connection/front/src/connect/components/TestApp/CreateTestAppForm.tsx
- src/Akeneo/Connectivity/Connection/front/src/connect/pages/MarketplacePage.tsx
- src/Akeneo/Connectivity/Connection/front/src/connect/pages/TestAppCreatePage.tsx
- src/Akeneo/Connectivity/Connection/front/src/model/Apps/test-app-credentials.ts
- src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/TestApp/CreateTestAppCredentials.test.tsx
- src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/TestApp/CreateTestAppForm.test.tsx
- src/Akeneo/Connectivity/Connection/front/tests/src/connect/pages/MarketplacePage.test.tsx
- src/Akeneo/Connectivity/Connection/front/tests/src/connect/pages/TestAppCreatePage.test.tsx
- Display the form
- Display errors on required fields
- Redirect to credentials screen when the form is submitted
- Close modal when the "cancel" button is clicked
This will be done in the [CXP-1049: [Front] Display generated credentials](https://akeneo.atlassian.net/browse/CXP-1049) : 
- Call "create test app" API endpoint
- Display API errors
> CXP-1046: Add form Create a test app

- src/Akeneo/Platform/Job/front/process-tracker/src/feature/components/common/JobExecutionStatus.tsx
- src/Akeneo/Platform/Job/front/process-tracker/src/feature/models/JobExecutionDetail/JobExecution.test.ts
- src/Akeneo/Platform/Job/front/process-tracker/src/feature/models/JobExecutionDetail/JobExecution.ts
- src/Akeneo/Platform/Job/front/process-tracker/src/feature/pages/JobExecutionDetail.test.tsx
- src/Akeneo/Tool/Component/Batch/Job/BatchStatus.php
- src/Akeneo/Tool/Component/Batch/spec/Job/BatchStatusSpec.php
- tests/back/Platform/Integration/ImportExport/Repository/InternalApi/GetJobExecutionTrackingIntegration.php
In this PR: 
- I fixed a regression made when we have modified STARTED by IN_PROGRESS, in the process detail we didn't display anymore the estimated time we display the time spent (cf screenshoot)
With this fix i fixed the status label used to know what to display to the user. 
> RAC-1203: Job detail page display 'Time spent' instead of displaying the estimated time when job status is 'IN PROGRESS'

- src/Akeneo/Tool/Bundle/StorageUtilsBundle/Doctrine/DBAL/Types/UTCDateTimeType.php
`UTCDateTimeType::convertToPHPValue()` can be passed a \DateTime as first argument, (cf https://github.com/doctrine-extensions/DoctrineExtensions/blob/a9fd83ad6e908e7180a719f174ded0b27aec2556/src/Timestampable/Mapping/Event/Adapter/ORM.php#L35), we need to handle that case
(NB: [UTCDateTimeImmutableType](https://github.com/akeneo/pim-community-dev/blob/master/src/Akeneo/Tool/Bundle/StorageUtilsBundle/Doctrine/DBAL/Types/UTCDateTimeImmutableType.php) already handles it)
> Fix UTCDateTimeType::convertToPHPValue() to handle datetime argument

- src/Akeneo/Tool/Bundle/MeasureBundle/Convert/MeasureConverter.php
- src/Akeneo/Tool/Bundle/MeasureBundle/spec/Convert/MeasureConverterSpec.php
When converting a small number, it's cast to '1.0E-7' (scientific notation) which was not compatible with bc math functions.
> CPM-467: Fix MeasureConverter for small numbers

- src/Akeneo/Connectivity/Connection/back/Domain/Apps/Model/ConnectedApp.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Persistence/DbalConnectedAppRepository.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Apps/InternalApi/GetAllConnectedAppsActionEndToEnd.php
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Apps/InternalApi/GetConnectedAppActionEndToEnd.php
- src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/Persistence/DbalConnectedAppRepositoryIntegration.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Domain/Apps/Model/ConnectedAppSpec.php
- src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApp/ConnectedAppContainer.tsx
- src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApps/ConnectedAppCard.tsx
- src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApps/ConnectedAppsContainer.tsx
- src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApps/ConnectedTestAppList.tsx
- src/Akeneo/Connectivity/Connection/front/src/connect/pages/ConnectedAppsListPage.tsx
- src/Akeneo/Connectivity/Connection/front/src/model/Apps/connected-app.ts
- src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApp/ConnectedAppAuthorizations.test.tsx
- src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApp/ConnectedAppContainer.test.tsx
- src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApp/ConnectedAppSettings.test.tsx
- src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApp/ErrorMonitoring/ConnectAppErrorMonitoring.test.tsx
- src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApps/ConnectedAppsCard.test.tsx
- src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApps/ConnectedAppsContainer.test.tsx
- src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApps/ConnectedTestAppList.test.tsx
- src/Akeneo/Connectivity/Connection/front/tests/src/connect/pages/ConnectedAppsListPage.test.tsx
CXP 1042 Display test apps in the Apps submenu
- Added `test` property to API response for GetAllConnectedApps
- Added display for connected test apps in a dedicated section
- Refactored front test suite
- Updated connected card to handle empty author and logo
> CXP 1042 Display test apps in the Apps submenu

- src/Akeneo/Connectivity/Connection/front/src/common/components/PageHeader.tsx
- src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApp/ConnectedAppContainer.tsx
Test  apps have no logo image,  we should display AppIllustration  instead. 
Since `PageHeader` is used to display connected (Test) App settings, it should be able to display Illustration if logo path is not provided
> CXP 1040 Handle no app logo for the PageHeader

- src/Akeneo/Platform/Bundle/UIBundle/Resources/config/acl_groups.yml
- src/Akeneo/UserManagement/Bundle/Resources/config/twig.yml
- src/Akeneo/UserManagement/Bundle/Twig/AclGroupsExtension.php
- tests/back/UserManagement/Integration/Bundle/ApplyFeatureFlagOnAclGroupsIntegration.php
- tests/back/UserManagement/Integration/Fixtures/FeatureFlagOnAclGroupsTestBundle/FeatureFlagOnAclGroupsTestBundle.php
- tests/back/UserManagement/Integration/Fixtures/FeatureFlagOnAclGroupsTestBundle/Resources/config/acl_groups.yml
We added added a new ACL Group, but when you don't have the flag `FLAG_APP_DEVELOPER_MODE_ENABLED`, it look like this:
(it's visible but empty)
With the solution present in this PR, an ACL group can be hidden, based on a feature flag.
After, it's back to normal:
> CXP-1044: hide ACL groups based on feature flag

- tests/back/Acceptance/Product/InMemoryProductRepository.php
- tests/back/Acceptance/spec/Product/InMemoryProductRepositorySpec.php
In pim-onboarder we use productRepository->findBy but him is not implemented in findby so some integration-test of pim was on error so i implemente in memory to correct integration test and change spec
> AOB-1445 : Implement findBy in memory and change spec

- CHANGELOG-5.0.md
- src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/ProductController.php
- src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/ProductModelController.php
- src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/ProductController.php
- src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/ProductModelController.php
- tests/back/Pim/Enrichment/EndToEnd/Product/Product/InternalApi/ProductCreationEndToEnd.php
Refresh ES index after creating a product from the UI and the API in order to well send product and product model created/updated event to event subscriptions.
> PIM-10233: Refresh ES index after creating a product from the UI in order to well send product created event to event subscriptions

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/Bundle/Cursor/SequentialEditProduct.php
- src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/AbstractCursor.php
- src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Cursor.php
- src/Akeneo/Tool/Bundle/ElasticsearchBundle/Cursor/AbstractCursor.php
- src/Akeneo/Tool/Bundle/ElasticsearchBundle/Cursor/Cursor.php
- src/Akeneo/Tool/Bundle/ElasticsearchBundle/Cursor/SearchAfterSizeCursor.php
- src/Akeneo/Tool/Bundle/ElasticsearchBundle/spec/Cursor/CursorSpec.php
- src/Akeneo/Tool/Bundle/ElasticsearchBundle/spec/Cursor/SearchAfterSizeCursorSpec.php
- tests/back/Pim/Enrichment/Integration/PQB/UpdateProductsWhenElasticsearchIsDesynchronisedIntegration.php
- tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/CursorSpec.php
https://akeneo.atlassian.net/browse/PIM-10232
**What's happening?**
Given a job that needs to iterate on products to make some product updates, it generally uses a PQB that hydrates products per batch of 100, and returns them one by one.
When 100 products are hydrated with doctrine ORM, they are also in the doctrine's Unit of Work.
The job treat them also per batch of 100, and clears the Doctrine UoW after each batch of 100.
So now what's happening if there is a desynchro between ES and MySQL, for example a product is returned by ES but unknown in MySQL?
The ES query returns 100 products, but MySQL returns 99 products. The cursor have 99 products in memory. So when the job ask for the 100th product, the cursor do a new ES query to ask …
> PIM-10232: Quick fix on the "Error a new entity was found in the relationship..." error during jobs

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/ProductController.php
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/controllers.yml
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/validators.yml
- src/Akeneo/Pim/Enrichment/Component/Product/Validator/ExternalApi/PayloadFormat.php
- src/Akeneo/Pim/Enrichment/Component/Product/Validator/ExternalApi/PayloadFormatValidator.php
- tests/back/Pim/Enrichment/Integration/Validation/PayloadFormatValidatorIntegration.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Validator/ExternalApi/PayloadFormatValidatorSpec.php
https://akeneo.atlassian.net/browse/PIM-10240
When giving null for a price value data, we have a 500 error, because we expect an array. In this PR we now return a 422 error and a good message. 
In our API we don't validate the payload directly. We catch exceptions to return a 422 error when:
- we check duplicate values
- we filter values
- we try to update the product with the values
- we validate the product before saving it
So the validation of the payload format is checked in different places, and some validations are clearly missing.
To handle that I start a PayloadFormatValidator that is responsible to validate the format.
Using a json-schema was a possibility but we cannot specify the error message we want for each case. …
> PIM-10240: Fix 500 error to a proper 422 error message

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/ApplyProductSearchQueryParametersToPQB.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/UseCase/ApplyProductSearchQueryParametersToPQBSpec.php
In this PR: 
I added the possibility to filter by updated and created NOT BETWEEN two dates. This fix contains a commit from your dear @Thijzer (thanks to her) https://github.com/akeneo/pim-community-dev/pull/16211. 
It should not be merged while Thijzer does not sign the Contributor Agreement
> PIM-10248: Fix NOT BETWEEN filter does not work on products and product models (created and updated property)

- .circleci/detect_structure_changes.sh
- .circleci/jobs/build_and_deploy.yml
- .circleci/jobs/features/connectivity.yml
- .circleci/jobs/features/other.yml
- Rollback https://github.com/akeneo/pim-community-dev/pull/16209
- Fix chown 1001
The uid of circleci user appears to be random. We thought it was changed to 1000, that's why we removed the chown.  
In this PR the chown are back, and the "chown 1001:1001" (1001 was the supposed uid of circleci) are fixed in "chown circleci:circleci"
> Fix circleci permissions

- .circleci/config.yml
- CHANGELOG-5.0.md
- Makefile
- std-build/Makefile
Fix issue on the Makefile from the 5.0 that is missing an s in the "remove-orphans" option.
> PIM-10223: Add missing "s" on "remove-orphans" option

- src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/Security/ScopeMapperRegistryIntegration.php
- src/Akeneo/Pim/Structure/Component/Security/AttributeOptionsScopeMapper.php
Fix a typo in attribute options ACLs scope mapper.
> OCT-6: Fix Attribute Options Scope mapping

- upgrades/schema/Version_5_0_20220201155016_add_user_account_locking_after_too_many_attempts.php
- upgrades/test_schema/Version_5_0_20220201155016_add_user_account_locking_after_too_many_attempts_Integration.php
In this PR, I modify Version_5_0_20220201155016_add_user_account_locking_after_too_many_attempts to make it idempotent and add test as in master we pulled up this with an error.
> Fix make Version_5_0_20220201155016_add_user_account_locking_after_too_many_attempts idempotent

- .circleci/config.yml
Now 6.0 is tagged we can automatically have pull up into 6.0
> Fix automatic pull up in order to target 6.0 now

- src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Completeness/VariantProductRatio.php
Following this discussion : https://github.com/akeneo/pim-community-dev/pull/16264#discussion_r800809073
Removing this condition does not occurs 500 error. The error log reported by me is a warning that have been thrown before querying the variant product ratio and have any relation with the query.
> RAC-1213: Remove useless condition in VariantProductRatio query

- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/handlers.yml
- src/Akeneo/Pim/Enrichment/Product/back/Application/UpsertProductHandler.php
- src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Application/UpsertProductHandlerSpec.php
We tried to set an regex validation on an attribute, then enrich it with the new service API => we didn't have exception (no violation).
We tried to resave the product without changing any data and we have an error. There is a product validator, with weird Guesser that check those things so we used this validator. (same than the used in the ProductController)
> RAB: Fix service API does not return ContraintValidation when attribute regex is not satisfied

- front-packages/akeneo-design-system/src/components/Input/TableInput/TableInputMeasurement/TableInputMeasurement.tsx
Fix Measurement display by removing uppercase
Exemple : mHz and MHz... which are not the same units, are displayed both MHZ
Exemple 2 : are (a) and acre (A) are displayed both A
> CPM-512: Fix Measurement display by removing uppercase

- .circleci/jobs/build_and_deploy.yml
- .circleci/jobs/features/connectivity.yml
- .circleci/jobs/features/other.yml
CircleCI’s Ubuntu 14.04 and 16.04 images will be permanently unavailable as of May 31, 2022. Migrate to a newer image today.
https://circleci.com/blog/ubuntu-14-16-image-deprecation/
--- EDIT ---
After review from teammates (thank you @StevenVAIDIE ), I rewrote the Circle CI config to change the machine executor to make it easier to change in the following PR.
I'd love to have only one occurence of the alias array to not repeat it in several files, but it is not supported by the `yq` merge operation
> PIM-10281: Update Circle CI machine executors

- CHANGELOG-6.0.md
- src/Akeneo/Platform/Bundle/AnalyticsBundle/Command/Style/SystemInfoStyle.php
PIM-10287: Fix deprecated methods for Symfony\Component\Console\Helper\TableStyle
The kind of deprecation we should have detected before: https://github.com/symfony/console/blob/4.4/Helper/TableStyle.php#L273
> PIM-10287: Fix deprecated methods for Symfony table style

- src/Akeneo/Pim/Structure/Bundle/Query/PublicApi/Attribute/Cache/LRUCachedGetAttributes.php
- src/Akeneo/Pim/Structure/Bundle/Query/PublicApi/Attribute/Sql/SqlGetAttributeTranslations.php
- src/Akeneo/Pim/Structure/Bundle/Query/PublicApi/Attribute/Sql/SqlGetAttributes.php
- src/Akeneo/Pim/Structure/Component/Query/PublicApi/Attribute/GetAttributeTranslations.php
- src/Akeneo/Pim/Structure/Component/Query/PublicApi/AttributeType/Attribute.php
- src/Akeneo/Pim/Structure/Component/Query/PublicApi/AttributeType/GetAttributes.php
- tests/back/Acceptance/Attribute/InMemoryGetAttributes.php
- tests/back/Pim/Structure/Integration/Attribute/Query/SqlGetAttributeTranslationsIntegration.php
- tests/back/Pim/Structure/Integration/Attribute/Query/SqlGetAttributesIntegration.php
Currently to list the linked product attribute on an asset edit form, we fetch the list of asset collection attributes from the structure REST endpoint.
As this is not a specialized endpoint, we fetch the first 20 asset collection attributes and then we filter the one corresponding to the current asset family.
Remove this direct call to an external endpoint and create a dedicated one in our bounded context.
> RAC-1202: Create endpoint to get product attributes for an Asset Family

- src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/LightEntityWithFamilyVariantNormalizer.php
LightEntityWithFamilyVariantNormalizer normalize method raises errors, `Akeneo\Pim\Enrichment\ReferenceEntity\Component\Normalizer\ReferenceEntityAxisLabelNormalizer::normalize(): Argument #1 ($value) must be of type Akeneo\Pim\Enrichment\Component\Product\Model\ValueInterface, null given` so in order to get more informations about the payload creating this error, we add an assert with current values.
> CPM-517: Add Assert notNull in LightEntityWithFamilyVariantNormalizer

- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/attributes.js
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/scope-switcher.js
When there is an error on a field (localizable or scopable), the attribute are correctly updated on the errored locale or the errored scope. But the locale switcher and scope switcher remained on the previous value.
This PR fixes that behaviour by adding mediator events when an error occured on a field.
> CPM-390: Fix channel and locale change on save error

- CHANGELOG-5.0.md
- src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Product/Association/GetGroupAssociationsByProductIdentifiers.php
- src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Product/Association/GetProductAssociationsByProductIdentifiers.php
- src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Product/Association/GetProductModelAssociationsByProductIdentifiers.php
- src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductModel/GetGroupAssociationsByProductModelCodes.php
- src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductModel/GetProductAssociationsByProductModelCodes.php
- src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductModel/GetProductModelsAssociationsByProductModelCodes.php
- tests/back/Pim/Enrichment/Integration/Storage/Sql/Product/Association/GetGroupAssociationsByProductIdentifiersIntegration.php
- tests/back/Pim/Enrichment/Integration/Storage/Sql/Product/Association/GetProductAssociationsByProductIdentifiersIntegration.php
- tests/back/Pim/Enrichment/Integration/Storage/Sql/Product/Association/GetProductModelAssociationsByProductIdentifiersIntegration.php
- tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductModel/GetGroupAssociationsByProductModelCodesIntegration.php
- tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductModel/GetProductAssociationsByProductModelCodesIntegration.php
- tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductModel/GetProductModelsAssociationsByProductModelCodesIntegration.php
When you add an association on a product model and its variant the associations come up twice in the API. This PR attempt to fix this behavior
> PIM-10288: Fix product associations came duplicated in API

- .gitignore
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Elasticsearch/Filter/QualityScoreFilter.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/js/infrastructure/datagrid/cell/quality-score-badge-cell.tsx
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Elasticsearch/Filter/QualityScoreFilterSpec.php
- src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/SearchQueryBuilder.php
make product grid ignore DQI score for product models (temporary) before the second release of the DQI for product models integrates master.
> PLG-761-no-impact-on-ui-when-productmodels-scores-will-be-computed

- CHANGELOG.md
- src/Akeneo/Platform/Bundle/UIBundle/Resources/views/Form/pim-fields.html.twig
In this PR, 
I fixed the group page when a validation error occured, since we bump to 5.4 of Symfony we have this error, it's due to the fact that transChoice have been removed (cf: https://github.com/symfony/twig-bridge/blob/5.4/CHANGELOG.md#500)
> PIM-10292: Fix error 500 when role page contain a validation errors

- CHANGELOG-5.0.md
- src/Akeneo/Pim/Structure/Bundle/Resources/config/datagrid/association_type.yml
In this PR: 
- I fixed the invalid entityHint in order to use the existing error key when an error occured on association type deletion
- This entityHint is only used for confirmation modal and error notification message 
> PIM-10275: Missing translation key when error occured during association deletion

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/.php_cd.php
- src/Akeneo/Pim/Enrichment/Bundle/Extension/RegisterIdentifierFilters.php
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/datagrid_actions.yml
- src/Oro/Bundle/PimDataGridBundle/Datagrid/Configuration/Product/FiltersConfigurator.php
- src/Oro/Bundle/PimDataGridBundle/spec/Datagrid/Configuration/Product/FiltersConfiguratorSpec.php
- tests/back/Pim/Enrichment/Specification/Bundle/Extension/RegisterIdentifierFiltersSpec.php
In this PR: 
- I removed the fact that the identifier is always displayed
- I added a listener in order to add the filter into the default list of filters (as the identifier can be other than sku we cannot add it manually in the grid config) 
> PIM-10268: Fix identifier filter should not be displayed if user doesn't choose to display it

- src/Akeneo/Pim/Enrichment/Bundle/Command/MigrateToUuid/MigrateToUuidFillJson.php
Add a condition for the `shouldBeExecuted` method inside the `MigrateToUuidFillJson` step in order to avoid a long request by checking if any quantified association type exists.
> CPM-537: Add condition on quantifiedAssociationsType for MigrateToFillUuidFillJson step

- tests/back/Platform/Integration/Analytics/Query/GetConnectedAppsIdentifiersQueryIntegration.php
This test recently failed on EE because when you don't specify fixtures, the database is not cleared.
> CXP-1103: prevent inte test from failing randomly

- src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/Product/OnSave/AddUuidSubscriber.php
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/event_subscribers.yml
- tests/back/Pim/Enrichment/Integration/Product/UuidMigration/AddUuidSubscriberIntegration.php
The POST_SAVE subscription is changed into Doctrine's postPersist subscription. So now:
- the creation of the product with the uuid is now atomic
- it allows to make the triggers work (as a reminder, we will add trigger on other tables, like product's association table, in order to recopy the product's uuid into it)
**Before**
- flush doctrine during a product save
- open transaction
- insert product without uuid (doctrine)
- insert product's association -> **here the trigger can not work because product does not have uuid**
- commit transaction
- POST_SAVE event -> update uuid on product
**After**
- flush doctrine during a product save
- open transaction
- insert product without uuid (doctrine)
- postPersist event on product -> update uuid on product
- insert product's association -> …
> CPM-541: Change uuid subsriber to make it work with triggers

- src/Akeneo/Pim/Enrichment/Bundle/Command/MigrateToUuid/MigrateToUuidFillForeignUuid.php
- src/Akeneo/Pim/Enrichment/Bundle/Command/MigrateToUuid/MigrateToUuidFillJson.php
- src/Akeneo/Pim/Enrichment/Bundle/Command/MigrateToUuid/UuidNotFoundException.php
- tests/back/Pim/Enrichment/Integration/Product/MigrateToUuidCommandIntegration.php
- Fix: when a product is deleted the related pim_versioning_version column is not cleared so we added a join on the count and update methods used in MigrateToUuidFillForeignUuid step
- in the MigrateToUuidFillJson, we clear JSON when the related product inside association does not exist anymore
> CPM-538: Remove the id of the product association when product does not exist

- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/KeyIndicator/ComputeProductsEnrichmentStatusQuery.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetCriteriaEvaluationsByProductIdQuery.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetEvaluationRatesByProductModelsAndCriterionQuery.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetEvaluationRatesByProductsAndCriterionQuery.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Transformation/Attributes/AttributesInterface.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Transformation/Attributes/InMemoryAttributes.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Transformation/Attributes/SqlAttributes.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Transformation/Channels/ChannelsInterface.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Transformation/Channels/InMemoryChannels.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Transformation/Channels/SqlChannels.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Transformation/CriterionEvaluationResultData/TransformCommonCriterionResultDataIds.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Transformation/CriterionEvaluationResultData/TransformCompletenessResultDataIds.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Transformation/CriterionEvaluationResultData/TransformResultDataIdsInterface.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Transformation/Locales/InMemoryLocales.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Transformation/Locales/LocalesInterface.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Transformation/Locales/SqlLocales.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Transformation/TransformChannelLocaleDataIds.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Transformation/TransformCriterionEvaluationResultCodes.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Transformation/TransformCriterionEvaluationResultIds.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/queries.yml
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/transformation.yml
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Infrastructure/Persistence/Transformation/TransformCriterionEvaluationResultIdsIntegration.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Persistence/Transformation/Attributes/InMemoryAttributesSpec.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Persistence/Transformation/Channels/InMemoryChannelsSpec.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Persistence/Transformation/CriterionEvaluationResultData/TransformCommonCriterionResultDataIdsSpec.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Persistence/Transformation/CriterionEvaluationResultData/TransformCompletenessResultDataIdsSpec.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Persistence/Transformation/Locales/InMemoryLocalesSpec.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Persistence/Transformation/TransformChannelLocaleDataIdsSpec.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Persistence/Transformation/TransformCriterionEvaluationResultCodesSpec.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Persistence/Transformation/TransformCriterionEvaluationResultIdsSpec.php
The goal is multiple:
1. Split the responsibilities of the main service to facilitate testing, readability and maintainability.
2. Handle the specificity of the two completeness criteria, that can have been persisted with a deprecated format (see PLG-468)
3. Make the service usable in the service that compute the Key-indicator on the completeness
I added "in memory" implementations for the queries on attributes, channels and locales to facilitate the tests. It allows to avoid using mocks for these queries in the specs.
> PLG-782: Rework criterion results transformation from ids to codes

- docker-compose.yml
We don't need a 2.5GB docker image for the pubsub emulator.
It's time for a **diet** :tada: 
**1) Image size**
Before:
```console
tseho@akeneo ~/work/pim-community-dev $ docker-compose images | grep pubsub
pim-community-dev_pubsub-emulator_1   google/cloud-sdk    331.0.0    55ef8753037e   2.508 GB
```
After:
```console
tseho@akeneo ~/work/pim-community-dev $ docker-compose images | grep pubsub
pim-community-dev_pubsub-emulator_1   google/cloud-sdk     375.0.0-emulators    2a6c0a154d60   865.8 MB
```
**2) CI speed**
Before:
After:
_note:_ This will save precious seconds on the following steps:
- `test_back_phpunit`
- `test_back_behat_legacy`
- `test_back_performance`
- `test_back_missing_structure_migrations`
- …
> OCT-28: replace pubsub image with a light one

- src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Query/Dashboard/ComputeProductsKeyIndicator.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Query/ProductEvaluation/GetEvaluationResultsByProductsAndCriterionQueryInterface.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Enrichment/CalculateProductModelCompleteness.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/KeyIndicator/ComputeProductsEnrichmentStatusQuery.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetEvaluationResultsByProductModelsAndCriterionQuery.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetEvaluationResultsByProductsAndCriterionQuery.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/elasticsearch.yml
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/queries.yml
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Infrastructure/Enrichment/CalculateProductModelCompletenessIntegration.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Infrastructure/Persistence/Query/KeyIndicator/ComputeProductModelsEnrichmentStatusQueryIntegration.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Infrastructure/Persistence/Query/ProductEvaluation/GetEvaluationResultsByProductModelsAndCriterionQueryIntegration.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Infrastructure/Persistence/Query/ProductEvaluation/GetEvaluationResultsByProductsAndCriterionQueryIntegration.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Persistence/Query/KeyIndicator/ComputeProductsEnrichmentStatusQuerySpec.php
Rework the service that compute the Key-Indicator on the enrichment status to be able to use it for the product models.
- Extract the MySQL query
- Use the "transformer" service to manipulate a object `CriterionEvaluationResult` instead of an array of raw data
- Add a unit test
> PLG-782: Rework compute products enrichment status KI

- CHANGELOG-6.0.md
- src/Akeneo/Pim/Structure/Bundle/Query/PublicApi/AttributeOption/Sql/SqlSearchAttributeOptions.php
- tests/back/Pim/Structure/Integration/AttributeOption/SqlSearchAttributeOptionsIntegration.php
Cherry picked from commit 1e291ffa1a0bacf174708416e7f44b5b450a460d)
> RAC-1223: [Backport] RAC-1215: fix error when attributeOption doesn't have label

- upgrades/schema/Version_6_0_20210531152335_dqi_launch_recompute_products_scores.php
Publish the `data_quality_insights_recompute_product_scores` job to the queue using dedicated public cli command instead of using the internal service
Migrations are run in `prod` environment so the use of the `akeneo_batch_queue.queue.job_execution_queue` internal service is not possible
> PLG-810: Fix publishing the data_quality_insights_recompute_product_scores job during migration

- .circleci/config.yml
Ubuntu 16.04 machine executor are deprecated
See https://circleci.com/blog/ubuntu-14-16-image-deprecation/
> Fix CI machine machine executor for 5.0

- src/Akeneo/Tool/Bundle/StorageUtilsBundle/Doctrine/Common/Remover/BaseRemover.php
Due to conflict in a pull-up, we sent the PRE_REMOVE twice in the base remover.  
The bad commit is [here](https://github.com/akeneo/pim-community-dev/commit/c7d614472b1067f4b28ed0c848d0506204233f54#diff-d22771992fec043d501faf9cf4eddd75183214dc1d6eb66895d125e51cb43abbR84)
> Fix duplicated PRE_REMOVE event

- src/Akeneo/Pim/Enrichment/.php_cd.php
- src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/ProductModelController.php
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/connector/use_cases.yml
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/controllers.yml
- src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Connector/SqlGetConnectorProductModels.php
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/ReadModel/ConnectorProduct.php
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/ReadModel/ConnectorProductModel.php
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/GetProductModelsWithQualityScores.php
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/GetProductModelsWithQualityScoresInterface.php
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/GetProductsWithQualityScores.php
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/GetProductsWithQualityScoresInterface.php
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/ListProductModelsQuery.php
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/ListProductModelsQueryHandler.php
- src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/ExternalApi/ConnectorProductModelNormalizer.php
- src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/ExternalApi/ConnectorProductNormalizer.php
- tests/back/Pim/Enrichment/Integration/Storage/Sql/Connector/SqlGetConnectorProductModelsIntegration.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ReadModel/ConnectorProductModelListSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ReadModel/ConnectorProductModelSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/UseCase/GetProductModelsWithQualityScoresSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/UseCase/GetProductsWithQualityScoresSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/UseCase/ListProductModelsQueryHandlerSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/ExternalApi/ConnectorProductModelNormalizerSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/ExternalApi/ConnectorProductNormalizerSpec.php
Rework to avoid coupling on `Akeneo\Pim\Automation\DataQualityInsights\Domain` in `Enrichment` 
We use `Akeneo\Pim\Automation\DataQualityInsights`PublicApi` instead, when DQI is needed in another BC
> PLG-728: Use DQI public API to fetch quality scores

- CHANGELOG-5.0.md
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/filter/attribute/attribute.js
When adding a localizable boolean attribute as a product export filter, the locale was not correctly initialized in the state.
> PIM-10335: Fix locale not saved for localizable attribute in product exports

- src/Akeneo/Pim/Enrichment/Bundle/Command/MigrateToUuid/MigrateToUuidCommand.php
- src/Akeneo/Pim/Enrichment/Bundle/Command/MigrateToUuid/MigrateToUuidReindexElasticsearch.php
- src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Indexer/ProductAndAncestorsIndexer.php
- src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Indexer/ProductIndexer.php
- src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Model/ElasticsearchProductProjection.php
- src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/Product/OnDelete/ComputeProductsAndAncestorsSubscriber.php
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/cli_command.yml
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/event_subscribers.yml
- src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ElasticsearchProjection/GetElasticsearchProductProjection.php
- src/Akeneo/Pim/Enrichment/Component/Product/Storage/Indexer/ProductIndexerInterface.php
- src/Akeneo/Tool/Bundle/ElasticsearchBundle/Client.php
- src/Akeneo/Tool/Bundle/ElasticsearchBundle/Domain/Model/AffectedByMigrationProjection.php
- tests/back/Pim/Enrichment/Integration/Product/MigrateToUuidCommandIntegration.php
- tests/back/Pim/Enrichment/Integration/Product/UuidMigration/AddUuidSubscriberIntegration.php
- tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductAndProductModel/ReindexAffectedByMigrationProductIntegration.php
- tests/back/Pim/Enrichment/Integration/Storage/Sql/ElasticsearchProjection/GetElasticsearchProductProjectionIntegration.php
- tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Indexer/ProductAndAncestorsIndexerSpec.php
- tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Indexer/ProductIndexerSpec.php
- tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Model/ElasticsearchProductProjectionSpec.php
- tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/Product/OnDelete/ComputeProductsAndAncestorsSubscriberSpec.php
The goal is to:
- add a migration step to reindex all products
- each time a product is saved, we have to reindex it
The "original" products are indexed under "_id" and "id" fields (which are the same in the PIM) with mysql id like "product_1234"
When the product have a uuid, we have to index their "_id" and "id" fields with the uuid, like "product_1e40-4c55-a415-89c7958b270d"
The idea is to remove the previous one, then add the new one, in the same query.
> CPM-504: Add ES reindexation

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/FlatToStandard/ProductModel.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/FlatToStandard/ProductModelSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/FlatToStandard/ProductSpec.php
In this PR: 
I fixed the following error : When user import a product with a numeric only attribute name, we have a fatal error with the following message: `preg_match(): #2 ($subject) must be of type string, int given.`
**Why we didn't have this error message in product import ?** 
Because src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/FlatToStandard/Product.php doesn't have `declare(strict_types=1);` so the cast is automatically done by PHP.
Current PHPStan level is 2 on enrichment, only level 5 can catch this error. 
Instead of removing the `declare(strict_types=1);` i manually casted the variable
> PIM-10345: Having a full numerical attribute code cause an error on product model import

- CHANGELOG.md
- src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/contexts/AttributeOptionsContextProvider.tsx
In a previous bug, labels of attribute options have been persisted in the spellcheck evaluations instead of their code. This bug has been fixed since, but the spellcheck evaluations have not been well cleaned. It remains some codes with different sensitive case.
This will be fixed by a new cleaning (command launched from CRON in EE) https://github.com/akeneo/pim-enterprise-dev/pull/13255
I didn't find any test on `AttributeOptionsContextProvider.tsx` and I think that it would be too complex and heavy to do it for a SLA
> PIM-10346: Fix spellcheck badge not displayed on attribute options

- CHANGELOG-5.0.md
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/quantified-associations/components/QuantifiedAssociationRow.tsx
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/quantified-associations/components/QuantifiedAssociations.tsx
- src/Akeneo/Platform/Bundle/UIBundle/tests/front/unit/components/QuantifiedAssociationRow.unit.tsx
Now permission are take into account when user cannot add or remove an association
> PIM-10364: Fix broken permissions on Associations with Quantity

- src/Akeneo/Connectivity/Connection/back/tests/.php_cd.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/.php_cd.php
- src/Akeneo/Pim/Enrichment/.php_cd.php
- src/Akeneo/Pim/Enrichment/Product/back/Test/.php_cd.php
- src/Akeneo/Pim/Structure/.php_cd.php
- src/Akeneo/Platform/Job/back/tests/.php_cd.php
- src/Akeneo/UserManagement/.php_cd.php
In this PR, I removed all dependencies declared in the php_cd but not effective with the command `list-unused-requirements` of php coupling detector
**Why I do that ?**
In order to read more easily the php_cd file and have a graph dependency closer to reality.
**Why I didn't add the `list-unused-requirements` in all bounded context testing suite ?**
I should be the choice of each squad to check it at each time => can be annoying for people
> Fix unused requirements in php_cd

- src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/GetKeyIndicators.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Model/Read/KeyIndicator.php
- src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/KeyIndicatorAboutProducts.tsx
- src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/KeyIndicators/ProductMessageBuilder.tsx
- src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/QualityScoreEvolutionSection/QualityScoreEvolutionSection.tsx
- src/Akeneo/Pim/Automation/DataQualityInsights/front/src/domain/KeyIndicator.ts
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Application/GetKeyIndicatorsSpec.php
Key indicator component crashed when backend service missed product_models key in the response (meaning nothing was returned by ES query).
Front is now ready for this.
> PLG-822 fix (Data quality insights) Key indicator component must be ready when key product_models is missing.

- src/Akeneo/Connectivity/Connection/back/Application/Apps/Command/RefreshConnectedAppCommand.php
- src/Akeneo/Connectivity/Connection/back/Application/Apps/Command/RefreshConnectedAppHandler.php
- src/Akeneo/Connectivity/Connection/back/Domain/Apps/Model/ConnectedApp.php
- src/Akeneo/Connectivity/Connection/back/Domain/Apps/Persistence/UpdateConnectedAppDescriptionQueryInterface.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Controller/Internal/RefreshConnectedAppAction.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Persistence/UpdateConnectedAppDescriptionQuery.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Apps/controllers.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Apps/handlers.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Apps/queries.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Apps/routing.yml
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Apps/Internal/RefreshConnectedAppActionEndToEnd.php
- src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/Command/RefreshConnectedAppHandlerIntegration.php
- src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/Persistence/UpdateConnectedAppDescriptionQueryIntegration.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Domain/Apps/Model/ConnectedAppSpec.php
- src/Akeneo/Connectivity/Connection/front/src/connect/hooks/use-connected-apps.ts
- src/Akeneo/Connectivity/Connection/front/src/connect/hooks/use-trigger-connected-app-refresh.ts
- src/Akeneo/Connectivity/Connection/front/tests/src/connect/hooks/use-connected-apps.test.ts
When cached information from the App Store changes (name, logo), we need to update it in the ConnectedApp for consistency.
This is triggered when both versions are reconciled in the front.
> CXP-1124: Refresh the name & logo of a Connected App when different

- src/Akeneo/Tool/Bundle/MeasureBundle/PublicApi/FindUnit.php
- src/Akeneo/Tool/Bundle/MeasureBundle/PublicApi/SqlFindUnit.php
- src/Akeneo/Tool/Bundle/MeasureBundle/Resources/config/public_api.yml
- src/Akeneo/Tool/Bundle/MeasureBundle/tests/Integration/PublicApi/SqlFindUnitIntegration.php
In the measurement bundle: 
- adds a new `\Akeneo\Tool\Bundle\MeasureBundle\PublicApi\FindUnit` query in the public api to allow **finding** unit instead of **getting** it (returns `null` instead of throwing exception)
- this PR keeps the the existing `\Akeneo\Tool\Bundle\MeasureBundle\PublicApi\GetUnit`
> Add new FindUnit query in the public API of MeasurementBundle

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Versioning/Product/ValueNormalizer.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/Versioning/Product/ValueNormalizerSpec.php
When importing a "number" attribute through XLS, it was cast to an int and we don't normalize it as a float because we never check the attribute configuration.
> PIM-10362: Fix attribute type "number" gets modified in history when import with same value

- CHANGELOG-5.0.md
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/array_converter.yml
- src/Akeneo/Pim/Enrichment/Component/Category/Connector/ArrayConverter/FlatToStandard/Category.php
- src/Akeneo/Pim/Enrichment/Component/Category/Model/Category.php
- tests/back/Pim/Enrichment/Specification/Component/Category/Connector/ArrayConverter/FlatToStandard/CategorySpec.php
- tests/legacy/features/channel/edit_channel.feature
- tests/legacy/features/pim/enrichment/product-model/classify_product_model.feature
- tests/legacy/features/pim/enrichment/product/export/export_products_by_categories.feature
- tests/legacy/features/pim/enrichment/product/mass-edit/mass_edit_products_and_product_models.feature
https://akeneo.atlassian.net/jira/software/c/projects/PIM/boards/9?modal=detail&selectedIssue=PIM-10374
- Revert PIM-10333 changes
- Modify the locale comparison to be case insensitive for Category translation
> PIM-10374: Revert PIM-10333 + Fix category translations are not displayed in the category tree when locale is not xx_XX

- CHANGELOG.md
- src/Akeneo/Channel/Component/Updater/ChannelUpdater.php
- tests/back/Channel/Specification/Component/Updater/ChannelUpdaterSpec.php
- tests/back/Integration/TestCase.php
- upgrades/schema/Version_7_0_20220330095652_ensure_locale_codes_for_labels_in_channels_have_correct_case.php
- upgrades/test_schema/Version_7_0_20220330095652_ensure_locale_codes_for_labels_in_channels_have_correct_case_integration.php
When Setting/Importing channels labels are localized using a [localeCode => label] map.
The locale codes must refer to locales known by the PIM, and case must be correct to prevent issue frontside.
The proposed modification ensures that when a locale is known, its case is correct in the channel data.
> PIM-10372 make sure labels are saved with know locale codes correctly spelled regarding letter cases

- src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/Db/AddUuidColumnsSubscriber.php
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/event_subscribers.yml
- tests/back/Integration/catalog/technical_sql/200_products.sql
- upgrades/schema/Version_7_0_20220404075823_add_uuid_columns.php
This PR prepares the migration from product id to product uuid
The first step is to add columns for product table and for every foreign table.
This can be done in a simple Symfony migration
We tested this migration on a real environment with tens of millions of lines and it takes less than 1 second per table.
> CPM-587: Add uuid columns

- src/Akeneo/Connectivity/Connection/tests/features/activate_an_app.feature
The changes related to the feature flags introduced by @ahocquard in https://github.com/akeneo/pim-community-dev/pull/16657 broke our 2 behat tests for the App Activation.
It's not his fault, these 2 tests are not executed in the complete CI, only ours.
> OCT-37: Fix feature flag in App Activate behat tests

- src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/Db/AddUuidColumnsSubscriber.php
- upgrades/schema/Version_7_0_20220404075823_add_uuid_columns.php
The previous queries were too long and lead to a timeout (+20min)
This version should be a lot quicker, but will add a lock on the tables.
> CPM-587: Fix ALGORITHM and LOCK on uuid columns migration

- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Command/OneTimeTask/CleanCompletenessEvaluationResultsCommand.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Command/OneTimeTask/OneTimeTaskCommandTrait.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/commands.yml
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Infrastructure/Symfony/Command/OneTimeTask/CleanCompletenessEvaluationResultsCommandIntegration.php
Since PLG-468 we store the number of improvable attributes instead of the list of their id for the two completeness criteria. 
This command aims to clean the criteria results data where there are still this list of attributes id
In the process, we browses all the results of the completeness criteria. When a result has the deprecated format, it's replaced by the new one (counting the attributes). 
We could add a condition to fetch only the deprecated results, but it would generate slow queries on big catalogs
> PLG-696: Add command to clean deprecated data in completeness results

- config/packages/akeneo_feature_flag.yml
- src/Akeneo/Platform/Bundle/FeatureFlagBundle/Configuration/OnlyFlexibilityOnPremiseFeatureFlag.php
- src/Akeneo/Platform/Bundle/FeatureFlagBundle/Resources/config/services.yml
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/attribute/form/SelectAttributeType.tsx
- tests/legacy/features/pim/enrichment/reference-data/attribute/add_attribute.feature
- tests/legacy/features/pim/enrichment/reference-data/attribute/display_attribute_history.feature
In this PR, I introduced a new feature flag configuration `OnlyFlexibilityOnPremiseFeatureFlag`. Its purpose is to have the possibility to enabled some feature only on Flexibility and OnPremise environment. It will be very useful to hide any feature from SaaS.
Also I added a reference_data feature and I added a check into the SelectAttributeType.tsx to remove reference data attribute type from the create options. That will hide reference data creation from the SaaS UI.
**/!\ This PR just hides reference data, don't disable it.**
I created a card to completly disable it. At this time, it is a quickwin to just hide it and it is ok for our PM.
> RAC-1208: Hide "reference data" attributes from SaaS users

- src/Akeneo/Connectivity/Connection/back/Application/Apps/Command/UpdateConnectedAppScopesWithAuthorizationHandler.php
- src/Akeneo/Connectivity/Connection/back/Application/Apps/Service/UpdateConnectedAppRoleWithScopesInterface.php
- src/Akeneo/Connectivity/Connection/back/Domain/Apps/Persistence/GetConnectedAppRoleIdentifierQueryInterface.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Persistence/FindAllUsernamesWithAclQuery.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Persistence/GetConnectedAppRoleIdentifierQuery.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Service/UpdateConnectedAppRoleWithScopes.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Apps/handlers.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Apps/queries.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Apps/services.yml
- src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/Command/UpdateConnectedAppScopesWithAuthorizationHandlerIntegration.php
- src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/Persistence/FindAllUsernamesWithAclQueryIntegration.php
- src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/Persistence/GetConnectedAppRoleIdentifierQueryIntegration.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Apps/Command/UpdateConnectedAppScopesWithAuthorizationHandlerSpec.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Apps/Service/UpdateConnectedAppRoleWithScopesSpec.php
When an app requests a different scopes list for an already connected app, its scope list is persisted. However, the role associated with the hidden user created for the said app remains unchanged. Meaning underlying ACLs are not updated with new scope changes
This PR creates a new service to update the connected app role ACLs based on provided scopes.
Much of its code is taken from [`AppRoleWithScopesFactory`](https://github.com/akeneo/pim-community-dev/blob/d826b9f3dbc465ec2b677f351e45b4803dafe7c6/src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/AppRoleWithScopesFactory.php). I didn't feel the need in extracting (yet) this chunk of code even if it is repeated
> CXP-1130 ACL Update

- src/Akeneo/Connectivity/Connection/back/tests/.php_cd.php
New PHP CD rules for Connectivity :
- Domain of {x} should use only classes from the same Domain
- Application of {x} should use only classes from the same Domain or same Application
- Infrastructure can use anything
> CXP-1154: rewrite phpcd rules

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/validation/category.yml
Fix category validator on import to prevent break-lines
> PIM-10398: Fix category validator on import to prevent break-lines

- src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/ProductController.php
- src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/ProductModelController.php
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/controllers.yml
- tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/CreateProductEndToEnd.php
- tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/DeleteProductEndToEnd.php
- tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/GetProductEndToEnd.php
- tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/SuccessListProductEndToEnd.php
- tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/PartialUpdateListProductEndToEnd.php
- tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/PartialUpdateProductEndToEnd.php
- tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/CreateProductModelEndToEnd.php
- tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/GetProductModelEndToEnd.php
- tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/ListOffsetProductModelEndToEnd.php
- tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/PartialUpdateListProductModelEndToEnd.php
- tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/PartialUpdateProductModelEndToEnd.php
A long time ago, we were logging errors due to the introduced ACLs on this REST API endpoints.
We don't need those logs anymore.
> CXP-916: remove warning logs of live ACLs

- src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApps/ConnectedAppCard.tsx
- src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApp/Settings/Authentication.test.tsx
- src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApps/ConnectedAppCard.test.tsx
When an app has outdated scopes, the open app button displays in yellow. When clicking on this button, the outdated scopes flag must be removed and the button must come back to its default color.
> CXP-1062: open app button must reset outdated scopes flag when clicking on it

- src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/Consolidation/ComputeScores.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/GetProductEvaluation.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/ProductEvaluation/CreateCriteriaEvaluations.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/ProductEvaluation/CriteriaByFeatureRegistry.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/ProductEvaluation/CriteriaEvaluationRegistry.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/FeatureFlag/AllCriteriaFeature.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/AkeneoDataQualityInsightsBundle.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Command/InitializeProductsEvaluationsCommand.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/DependencyInjection/Compiler/CriteriaByFeatureRegistryPass.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/commands.yml
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/feature_flags.yml
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/services.yml
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Application/Consolidation/ComputeScoresSpec.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Application/GetProductEvaluationSpec.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Application/ProductEvaluation/CreateCriteriaEvaluationsSpec.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Application/ProductEvaluation/CriteriaByFeatureRegistrySpec.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Application/ProductEvaluation/CriteriaEvaluationRegistrySpec.php
- Add a registry that will have the responsibility to list criteria codes according to the feature.
- Remove the responsibility to list criteria codes from the historic registry
The new registry will be used to be able to compute the double scores.
I choose to have an instance for the products and another for the product-models to be consistent with how the criteria are declared (with two tags), even if in practice the criteria are the same (it could change in the future)
See criteria declaration in EE: https://github.com/akeneo/pim-enterprise-dev/pull/13477/files
> PLG-834: Register criteria according to feature flag

- src/Akeneo/Pim/Enrichment/Bundle/Command/IndexProductCommand.php
- src/Akeneo/Pim/Enrichment/Bundle/Command/IndexProductModelCommand.php
The count(*) query can be very long and quite ineffective for big tables, and was only used to init the ProgressBar
> PIM-10410: Do not count the total number of products/models when doing a full reindex

- src/Akeneo/Channel/back/API/Query/FindLocales.php
- src/Akeneo/Channel/back/API/Query/Locale.php
- src/Akeneo/Channel/back/Infrastructure/Query/Sql/SqlFindLocales.php
- src/Akeneo/Channel/back/Infrastructure/Symfony/Resources/config/queries.yml
- src/Akeneo/Channel/back/tests/Integration/Query/Sql/SqlFindLocalesIntegration.php
- src/Akeneo/Channel/back/tests/Specification/API/Query/LocaleSpec.php
- src/Akeneo/Channel/back/tests/Specification/Infrastructure/Query/Sql/SqlFindLocalesSpec.php
- Add a query in Channel's API to retrieve all activated locales & find a locale by its code
- Add related read model `Locale`
- Query is cached
> RAB-614: Retrieve all locales information (Query)

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/Component/Product/Factory/MetricFactory.php
- src/Akeneo/Tool/Bundle/MeasureBundle/Manager/MeasureManager.php
- src/Akeneo/Tool/Bundle/MeasureBundle/spec/Manager/MeasureManagerSpec.php
- tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/CreateProductEndToEnd.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Factory/MetricFactorySpec.php
When trying to create a metric with a unit code which does not match the measurement family's unit code case (e.g: Gram instead of GRAM), the [ValidMetricValidator](https://github.com/akeneo/pim-community-dev/blob/master/src/Akeneo/Pim/Structure/Component/Validator/Constraints/ValidMetricValidator.php) would create a violation stating that the unit code is invalid
I could have simply fixed the validator, but this would cause an entry to be wrongly created in the product's history if e.g, updating a value from "200 GRAM" to "200 gram". Instead, the metric factory now gets the right unit code (with the right case) when creating a metric
> PIM-10409: Allow creating a measurement value with case insensitive unit code

- src/Akeneo/Connectivity/Connection/back/tests/.php_cd.php
The following rules have unused rules in our phpcd configuration file
Rule Akeneo\Connectivity\Connection\Application\User  have:
`Akeneo\Connectivity\Connection\Domain\User`
Rule Akeneo\Connectivity\Connection\Application\Webhook have:
`Akeneo\Platform\Bundle\UIBundle\Provider\ContentSecurityPolicy\ContentSecurityPolicyProviderInterface`
> CXP-fixunused-phpcd-rules: Removed unsused rules

- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/Dashboard/GetRanksDistributionFromProductScoresQuery.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/queries.yml
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Infrastructure/Persistence/Query/Dashboard/GetRanksDistributionFromProductScoresQueryIntegration.php
The data used in the Dashboard for evolution graphs and for the category/family widgets are computed from scores stored in ES.
So we just need to adapt the ES query to do the aggregations on the right scores property
> PLG-837: Adapt ranks distribution for double scores

- src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Query/ProductEvaluation/GetProductModelScoresByCodesQueryInterface.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Query/ProductEvaluation/GetProductScoresByIdentifiersQueryInterface.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Elasticsearch/Filter/QualityScoreFilter.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Elasticsearch/Filter/QualityScoreMultiLocalesFilter.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Elasticsearch/GetScoresPropertyStrategy.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Elasticsearch/Sorter/QualityScoreSorter.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/Dashboard/GetRanksDistributionFromProductScoresQuery.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetProductModelScoresByCodesQuery.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetProductScoresByIdentifiersQuery.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/elasticsearch.yml
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/productgrid.yml
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/public_api/queries.yml
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/queries.yml
- src/Akeneo/Pim/Automation/DataQualityInsights/back/PublicApi/Query/ProductEvaluation/GetProductModelScoresQuery.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/PublicApi/Query/ProductEvaluation/GetProductScoresQuery.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Infrastructure/Persistence/Query/Dashboard/GetRanksDistributionFromProductScoresQueryIntegration.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Infrastructure/Persistence/Query/ProductEvaluation/GetProductModelScoresByCodesQueryIntegration.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Infrastructure/Persistence/Query/ProductEvaluation/GetProductScoresByIdentifiersQueryIntegration.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/PublicApi/Query/ProductEvaluation/GetProductModelScoresQueryIntegration.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/PublicApi/Query/ProductEvaluation/GetProductScoresQueryIntegration.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Elasticsearch/Filter/QualityScoreFilterSpec.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Elasticsearch/Filter/QualityScoreMultiLocalesFilterSpec.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Elasticsearch/GetScoresPropertyStrategySpec.php
- Adapt MySQL queries used for the exports and the API
- Adapt ES queries to filter and sort on the scores according to the feature flag
> PLG-830: Adapt double scores for exports and API

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/Component/Product/Model/AbstractMetric.php
- src/Akeneo/Tool/Bundle/MeasureBundle/Convert/MeasureConverter.php
- src/Akeneo/Tool/Bundle/MeasureBundle/spec/Convert/MeasureConverterSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Model/MetricSpec.php
When importing "1.900.000" as metric value, there is an error on bcomp
> PIM-10411: Fix non numeric metric value in imports

- src/Akeneo/Pim/Enrichment/Product/back/API/Command/UpsertProductCommand.php
- src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/EnrichmentProductTestCase.php
- src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductAssociationsIntegration.php
- src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/API/Command/UpsertProductCommandSpec.php
Add two way association tests for the UpsertProductCommand
> CPM-600 and CPM-601: Add two-way associations integration tests for UpsertProduct Command

- CHANGELOG.md
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/routing.yml
patch connections routing order : 
this front route must be at the end, always.
```
akeneo_connectivity_connection_settings_any:
path: '/connect/connection-settings/{any}'
requirements:
any: .*
```
> PIM-10413: patch connections routing order

- src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/GetProductEvaluation.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/ProductEvaluation/EvaluateOutdatedProductModel.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Controller/EvaluateProductModelController.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Controller/GetProductModelEvaluationController.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Application/GetProductEvaluationSpec.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Application/ProductEvaluation/EvaluateOutdatedProductModelSpec.php
Fetching and launching evaluation of product models were broken because the dedicated controllers used `ProductId` instead of `ProductModelId`
> PLG-853: Fix fetching and launching product models evaluation

- src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/KeyIndicator/ComputeProductsKeyIndicators.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/KeyIndicator/GetKeyIndicators.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/KeyIndicator/GetKeyIndicatorsInterface.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/KeyIndicator/ProductKeyIndicatorsByFeatureRegistry.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Query/Dashboard/ComputeProductsKeyIndicator.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Elasticsearch/BulkUpdateProductQualityScoresIndex.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Elasticsearch/GetDataQualityInsightsPropertiesForProductModelProjection.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Elasticsearch/GetDataQualityInsightsPropertiesForProductProjection.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/KeyIndicator/ComputeProductsEnrichmentStatusQuery.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/KeyIndicator/ComputeProductsWithImageQuery.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/ProductGrid/RegisterKeyIndicatorFilter.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/AkeneoDataQualityInsightsBundle.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Controller/Dashboard/DashboardKeyIndicatorsController.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/DependencyInjection/Compiler/ProductKeyIndicatorsByFeatureRegistryPass.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/queries.yml
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/services.yml
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Application/KeyIndicator/ComputeProductsKeyIndicatorsSpec.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Application/KeyIndicator/GetKeyIndicatorsSpec.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Application/KeyIndicator/ProductKeyIndicatorsByFeatureRegistrySpec.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Elasticsearch/BulkUpdateProductQualityScoresIndexSpec.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Elasticsearch/GetDataQualityInsightsPropertiesForProductModelProjectionSpec.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Elasticsearch/GetDataQualityInsightsPropertiesForProductProjectionSpec.php
The key-indicators specific to the EE were declared directly from Symfony DI by passing their code. This PR add a registry that allows to provide the key-indicators according to the enabled feature.
See EE PR: https://github.com/akeneo/pim-enterprise-dev/pull/13607
> PLG-831: Adapt key indicators for GE in EE

- src/Akeneo/Tool/Bundle/ElasticsearchBundle/IndexConfiguration/UpdateIndexMappingWithoutDowntime.php
- src/Akeneo/Tool/Bundle/ElasticsearchBundle/Infrastructure/Client/ClientMigration.php
- src/Akeneo/Tool/Bundle/ElasticsearchBundle/Infrastructure/Client/ClientMigrationInterface.php
- src/Akeneo/Tool/Bundle/ElasticsearchBundle/spec/IndexConfiguration/UpdateIndexMappingWithoutDowntimeSpec.php
**In this PR:** 
I handle the fact that index to migrate is not an alias. 
Some client have directly the index instead of having the alias that pointing to index, this lead to an error in production when we tried to reindex.
Another solution have been tested here : https://github.com/akeneo/pim-enterprise-dev/pull/13587. Problem is that the migration have an downtime, it's not what we wanted. Some impacted client (listed in Jira) have more than 250000 documents to reindex it could take time. Another problem is that we have not guaranty about that the problem will not exist anymore. So best choice is to handle it directly on the handler 
> RAC-1227: Handle index does not have alias when we migrate index mapping

- src/Akeneo/Pim/Structure/Bundle/Query/PublicApi/Attribute/Sql/SqlGetAttributeTranslations.php
- src/Akeneo/Pim/Structure/Component/Query/PublicApi/Attribute/GetAttributeTranslations.php
- tests/back/Pim/Structure/Integration/Attribute/Query/SqlGetAttributeTranslationsIntegration.php
In this PR: 
I fixed the following error in datadog : 
```
An exception occurred while executing '    SELECT
code,
JSON_OBJECTAGG(attribute_translation.locale, attribute_translation.label) as labels
FROM pim_catalog_attribute attribute
LEFT JOIN pim_catalog_attribute_translation attribute_translation ON attribute.id = attribute_translation.foreign_key
WHERE attribute.code IN (?)
GROUP BY attribute.code;' with params ["images"]:
```
> We cannot use result from left join as JSON_OBJECTAGG key. Solution is to do not left join anymore => we didn't care about there is not translation and there is no attribute in this query
> RAC-1234: Fix SQLSTATE[22032]: <<Unknown error>>: 3158 JSON documents may not contain NULL member names.

- src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/TabContent/DataQualityInsights/AxisEvaluation.tsx
When GE will be merged in the EE code base, the criteria of the axis Consistency will be evaluated but must not be displayed. 
On a GE, the Backend will not return the Consistency recommendations, but the axis compenent (with its title) is still display.
We previously choose to let the Backend have the responsibility to decide what are the recommendations according to the feature flags. So the simplest way to fix the problem is to not display an axis if it has no recommendations.
> PLG-832: Display DQI axis only if there are recommencations

- src/Akeneo/Connectivity/Connection/back/Application/Apps/Command/CreateConnectedAppWithAuthorizationHandler.php
- src/Akeneo/Connectivity/Connection/back/Application/Apps/Service/CreateUserInterface.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/EventSubscriber/GroupAllIsRemovedFromUsersUsedByAppsOnUpdateEventSubscriber.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/User/CreateUser.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Apps/event_subscribers.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Apps/handlers.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Apps/services.yml
- src/Akeneo/Connectivity/Connection/back/tests/.php_cd.php
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Apps/Internal/ConfirmAuthenticationEndToEnd.php
- src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/Command/ConsentAppAuthenticationHandlerIntegration.php
- src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/Command/CreateConnectedAppWithAuthorizationHandlerIntegration.php
- src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/Persistence/GetAppConfirmationQueryIntegration.php
- src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/User/CreateUserIntegration.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Apps/Command/CreateConnectedAppWithAuthorizationHandlerSpec.php
- src/Akeneo/UserManagement/Bundle/Manager/UserManager.php
- src/Akeneo/UserManagement/Bundle/Resources/config/services.yml
- upgrades/schema/Version_7_0_20220405000000_remove_group_all_from_apps.php
- upgrades/test_schema/Version_7_0_20220405000000_remove_group_all_from_apps_Integration.php
When an App is connected, we create a hidden user for the Connection.
By default, this user had the group "All" which was provoking inconsistencies with the permissions configured in the App settings.
In this PR, I stopped using the service `CreateUser` for Connections, to use a new one dedicated to Apps.
In this new `CreateUser` service, I remove the group "All".
> CXP-1145: App's user is not in the "All" default group

- .circleci/jobs/build_and_deploy.yml
- .circleci/jobs/features/connectivity.yml
- .circleci/workflows/squads/octopus.yml
- make-file/connectivity-connection.mk
- make-file/test.mk
- src/Akeneo/Connectivity/Connection/front/tsconfig.json
- src/Akeneo/Connectivity/Connection/workspaces/permission-form/tsconfig.json
**Before**
_From start to finish: 16-17min_
**After**
_From start to finish: 9-10min_
---
**The trick**
By installing the dependencies before building the PIM, we can already execute a lot of tests (unit, integration) while compiling the JS for example.
The `build_ce` is still the same and still tries to install the dependencies, but since they are already there or were cached, it has no impact.
**What about persistence of the files?**
Persisting the same workspace in parallelized jobs is possible.
https://circleci.com/blog/deep-diving-into-circleci-workspaces/
Thanks @ahocquard for the tips
By persisting only subdirectories when installing the dependencies:
```
-   persist_to_workspace:
root: ~/
paths:
- project/vendor
```
```
-   persist_to_workspace:
root: ~/
paths:
- …
```
> CXP-1174: Faster CXP CI

- tests/back/Acceptance/Product/InMemoryProductRepository.php
- tests/back/Acceptance/spec/Product/InMemoryProductRepositorySpec.php
The CI of the CE is red because it is not configured to change the pim-onboarder dependency (still ^7.0).  
Instead please check the CI of the EE that can run tests with the `migration-adr-uuid` branch of pim-onboarder: https://app.circleci.com/pipelines/github/akeneo/pim-enterprise-dev?branch=migration-adr-uuid&filter=all
> Implement InMemoryProductRepository's findOneBy

- CHANGELOG.md
- src/Akeneo/Tool/Bundle/MeasureBundle/Controller/ExternalApi/GetMeasurementFamiliesAction.php
- src/Akeneo/Tool/Bundle/MeasureBundle/Normalizer/ExternalMeasurementFamilyNormalizer.php
- src/Akeneo/Tool/Bundle/MeasureBundle/Resources/config/api.yml
- src/Akeneo/Tool/Bundle/MeasureBundle/spec/Normalizer/ExternalMeasurementFamilyNormalizerSpec.php
- src/Akeneo/Tool/Bundle/MeasureBundle/tests/EndToEnd/ExternalApi/GetMeasurementFamiliesActionEndToEnd.php
- src/Akeneo/Tool/Bundle/MeasureBundle/tests/EndToEnd/ExternalApi/Responses/measurement-families.json
Fixes https://akeneo.atlassian.net/browse/PIM-10426?atlOrigin=eyJpIjoiMGRiN2JkY2U2NjUwNGZlMzllMjAyZWQwNzA3NTEyZDIiLCJwIjoiaiJ9
If we want to have a empty JSON object, we need to pass an empty ArrayObject to JsonResponse as the Symfony JSON Encoder will encode empty array into JSON empty array and empty object into JSON empty object.
cf https://github.com/symfony/symfony/issues/23019
> PIM-10426: Fix empty array should be normalized as empty JSON object in Measurement Family API

- src/Akeneo/Channel/back/Infrastructure/Query/Sql/SqlFindChannels.php
Functionnally, a **Channel MUST have at least one locale and one currency**.
**Therefore**, in a lot of our test fixtures, we simply create channel without related entities (which is bad), this PR adapts the Query to handle those cases to be iso-functional with before.
This avoids error of type:
```
Error in query (3158): JSON documents may not contain NULL member names. 
```
> Handle case where channel has no currency nor locale

- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/cursors.yml
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/query_builders.yml
and use it in counter
CountImpactedProducts used the product and product model factory PQB. So to have a count, the PQB hydrated the first 100 products/product models. It was useless because we just want the count of the query result.
Now this class uses the product and product model *identifier* PQB => **no more hydration!**
> CPM-488: create product and product model identifier PQB factory

- composer.json
The nightlies are blocked because of composer https://app.circleci.com/pipelines/github/akeneo/pim-community-dev/35133/workflows/3c462c14-200e-48e1-b4fd-f7594bc9d520/jobs/176385  
He now asks if we want to add the plugins.  
Until now the current behavior were it added the plugins by default, see https://getcomposer.org/doc/06-config.md#allow-plugins
We also could allow all plugins, but we prefered to allow them one by one explicitely
> Fix composer allow plugins

- CHANGELOG-6.0.md
- upgrades/schema/Version_6_0_20220509143200_use_the_new_process_tracker_route.php
- upgrades/test_schema/Version_6_0_20220509143200_use_the_new_process_tracker_route_Integration.php
In this PR, i fixed the following error :
`Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "pim_importexport_export_execution_show" as such route does not exist.")." at /home/akeneo/pim/vendor/akeneo/pim-community-dev/src/Akeneo/Platform/Bundle/NotificationBundle/Resources/views/Notification/list.json.twig line 6`
Why we have this error ?
Because when we deployed the process tracker revamp we have renamed the route name (see https://github.com/akeneo/pim-community-dev/pull/15795 )
Because notification redirect url is stored in database we forget it.
> PIM-10425: Fix notifications can't be displayed because of removed routes

- CHANGELOG.md
- src/Akeneo/Platform/Job/back/Application/SearchJobExecution/Model/JobExecutionHealthCheck.php
- src/Akeneo/Platform/Job/back/Application/SearchJobExecution/Model/JobExecutionRow.php
- src/Akeneo/Platform/Job/back/Infrastructure/Clock/ClockInterface.php
- src/Akeneo/Platform/Job/back/Infrastructure/Clock/SystemClock.php
- src/Akeneo/Platform/Job/back/Infrastructure/Hydrator/JobExecutionHealthCheckHydrator.php
- src/Akeneo/Platform/Job/back/Infrastructure/Hydrator/JobExecutionRowHydrator.php
- src/Akeneo/Platform/Job/back/Infrastructure/Query/SearchJobExecution.php
- src/Akeneo/Platform/Job/back/Infrastructure/Symfony/Resources/config/hydrators.yml
- src/Akeneo/Platform/Job/back/tests/Acceptance/Application/SearchJobExecution/SearchJobExecutionHandlerTest.php
- src/Akeneo/Platform/Job/back/tests/Integration/Infrastructure/Query/SearchJobExecutionTest.php
- src/Akeneo/Platform/Job/back/tests/Specification/Application/SearchJobExecution/Model/JobExecutionHealthCheckSpec.php
- src/Akeneo/Platform/Job/back/tests/Specification/Application/SearchJobExecution/Model/JobExecutionRowSpec.php
- src/Akeneo/Platform/Job/back/tests/Specification/Application/SearchJobExecution/Model/JobExecutionTableSpec.php
**What's going wrong ?**
We forgot to handle the recalculation of the status based on the health time check : this will cause some bugs when jobs fails due to external down like a mysql pod crash. Now, users can seen that their jobs are failed.
> PIM-10420: Handle status computed by health check time on process tracker

- .circleci/detect_structure_changes.sh
- .circleci/jobs/features/other.yml
- .circleci/run_phpunit.sh
- Makefile
- docker-compose.yml
- make-file/communication-channel.mk
- make-file/connectivity-connection.mk
- make-file/test.mk
Setting the user for `php` container in the docker-compose file will avoid the need to always add it in the command line.
This should avoid annoying side effects like when you forget to use `-u www-data` with a `composer update` command and you find yourself with your composer cache file permissions spoiled by root user.
```bash
$ docker-compose run --rm php id
Creating ee-master_php_run ... done
uid=0(root) gid=0(root) groups=0(root)
$ docker-compose run --rm -u www-data php id
Creating ee-master_php_run ... done
uid=1000(www-data) gid=1000(www-data) groups=1000(www-data)
```
```bash
$ docker-compose run --rm php id
Creating ee-master_php_run ... done
uid=1000(www-data) gid=1000(www-data) groups=1000(www-data)
$ docker-compose run --rm -u www-data php id
Creating ee-master_php_run ... …
```
> DPE: Use www-data user for Docker Compose php container

- composer.json
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Query/ProductEnrichment/GetDescendantVariantProductUuidsQueryInterface.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Infrastructure/Persistence/Query/KeyIndicator/ComputeProductsEnrichmentStatusQueryIntegration.php
- src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/ProductController.php
- src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Category/AscendantCategories.php
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/Processor/MassEdit/AddAttributeValueProcessor.php
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/Writer/Database/MassEdit/ProductAndProductModelWriter.php
- src/Akeneo/Pim/Enrichment/Component/Product/Model/AbstractProduct.php
- src/Akeneo/Pim/Enrichment/Component/Product/Model/EntityWithValuesInterface.php
- src/Akeneo/Pim/Enrichment/Component/Product/Model/ProductInterface.php
- src/Akeneo/Pim/Enrichment/Component/Product/Model/ProductModel.php
- src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/EntityWithFamilyVariantNormalizer.php
- src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/Product/UniqueProductEntityValidator.php
- src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/Product/UniqueProductModelEntityValidator.php
- src/Akeneo/Tool/Bundle/ClassificationBundle/Doctrine/ORM/Repository/AbstractItemCategoryRepository.php
- src/Akeneo/Tool/Component/Batch/Model/StepExecution.php
- src/Oro/Bundle/PimDataGridBundle/Datasource/ProductDatasource.php
- src/Oro/Bundle/PimDataGridBundle/spec/Datasource/ProductDatasourceSpec.php
- src/Oro/Bundle/SecurityBundle/Acl/Domain/ObjectIdAccessor.php
- tests/back/Pim/Enrichment/Integration/Normalizer/Standard/ProductStandardSortedCollectionIntegration.php
- tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/Product/OnSave/ApiAggregatorForProductPostSaveEventSubscriberSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Writer/Database/MassEdit/ProductAndProductModelWriterSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/InternalApi/EntityWithFamilyVariantNormalizerSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/Product/UniqueProductEntityValidatorSpec.php
- tests/legacy/features/Context/SecurityContext.php
Remove all remaining usages of getId/setId on Product. 
- setId is removed
- getId is kept because the shared interfaces (EntityWithValuesInterface, ...) but it throws an exception now
- a new `isNew` method is added (before we checked the id is null or not)
> CPM: clean product's getId() and setId()

- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Command/LaunchEvaluationsCommand.php
- src/Akeneo/Pim/Enrichment/Bundle/Command/MigrateToUuid/MigrateToUuidCommand.php
Before this PR, we have to check if every state was already done
The issue is that our biggest client takes a very long time to compute.
With this solution, we store the success of the migration, and only check for it when we run the cmd.
> [adr-uuid] Store success on db

- src/Akeneo/Connectivity/Connection/back/Infrastructure/Marketplace/TestApps/Controller/External/DeleteTestAppAction.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Marketplace/TestApps/Controller/External/DeleteTestAppActionSpec.php
CXP-1163: Fixed linting error for DeleteTestAppAction
```
------ ----------------------------------------------------------------------- 
Line   Marketplace/TestApps/Controller/External/DeleteTestAppAction.php       
------ ----------------------------------------------------------------------- 
53     Offset 'connected' on array{id: string, secret: string, name: string,  
author: string|null, activate_url: string, callback_url: string,       
connected: bool} on left side of ?? always exists and is not           
nullable.                                                              
------ ----------------------------------------------------------------------- 
```
> CXP-1163: Fixed linting error for DeleteTestAppAction

- .circleci/jobs/features/other.yml
- Dockerfile
Using the COMPOSER_MEMORY_LIMIT directly inside our PHP container allows us to not have to define this limit anywhere when using the container.
This can still be overridden in CLI if more memory is needed.
It has no impact on the overall PHP memory limit and is used only by Composer
> DPE: COMPOSER_MEMORY_LIMIT env var in php container

- .circleci/jobs/features/other.yml
- Dockerfile
Using the COMPOSER_MEMORY_LIMIT directly inside our PHP container allows us to not have to define this limit anywhere when using the container.
This can still be overridden in CLI if more memory is needed.
It has no impact on the overall PHP memory limit and is used only by Composer
> Improvement: COMPOSER_MEMORY_LIMIT is set in PHP container

- front-packages/akeneo-design-system/src/components/Block/Block.unit.tsx
- front-packages/akeneo-design-system/src/components/Input/TagInput/TagInput.stories.mdx
- front-packages/akeneo-design-system/src/components/Input/TagInput/TagInput.tsx
- front-packages/akeneo-design-system/src/components/Input/TagInput/TagInput.unit.tsx
- Create a tag when submitting (hitting Enter) with a non-empty input
- Add ellipsis when having a very long tag
Before: 
After:
Also fixing warning in Block.unit.tsx
> RAB-723: Create tag before submitting with non-empty input

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/validators.yml
- src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/Product/UniqueProductEntityValidator.php
- src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/Product/UniqueProductModelEntityValidator.php
- tests/back/Acceptance/Product/InMemoryFindProductId.php
- tests/back/Acceptance/ProductModel/InMemoryFindProductModelId.php
- tests/back/Acceptance/Resources/config/pim/queries.yml
- tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/Product/UniqueProductEntityValidatorSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/Product/UniqueProductModelEntityValidatorSpec.php
The UniqueEntityValidator used a repository to check for existence in db, but it only needed to get the id. I replaced it with the FindId query, which avoids to hydrate the whole product/product model (filter/check values, and in EE apply permissions on locales/categories/attribute groups, etc.)
> PIM-10447: Do not use repositories to check for product existence

- front-packages/akeneo-design-system/src/components/Checkbox/Checkbox.tsx
If the checkbox is constrained by its container element size, the checkbox will shrink in size.
> DSM Fix checkbox to not shrink when constrained by container size

- CHANGELOG.md
- src/Akeneo/Tool/Bundle/BatchBundle/Command/BatchCommand.php
- src/Akeneo/Tool/Bundle/BatchBundle/spec/Launcher/SimpleJobLauncherSpec.php
- src/Akeneo/Tool/Bundle/BatchQueueBundle/spec/Launcher/QueueJobLauncherSpec.php
- src/Akeneo/Tool/Component/Batch/Job/Job.php
- src/Akeneo/Tool/Component/Batch/Job/JobInterface.php
- tests/back/Pim/Enrichment/Integration/Category/ConfigureCategoryTreeForExportJobsAfterChangingTheChannelCategoryTreeIntegration.php
Rework the BatchCommand to make it ignore the batch `code` parameter when an execution ID (`execution` parameter`) is already provided. Indeed, the batch code is part of the execution parameter.
This would allow us to launch some batches by knowing only the execution ID.
If the execution ID is not provided, the batch code is still used as before.
Also added a `getJobRepository` in the interface because it was internally required and was using polymorphic calls.
> BH-1159: Rework BatchCommand to use execution ID without batch code

- src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/DependencyInjection/Compiler/VolumeQueryPass.php
- src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/PimCatalogVolumeMonitoringBundle.php
- src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/Resources/config/normalizers.yml
- src/Akeneo/Platform/Component/CatalogVolumeMonitoring/Volume/Normalizer/Volumes.php
- tests/back/Platform/Specification/Bundle/CatalogVolumeMonitoringBundle/Controller/VolumeMonitoringControllerSpec.php
- tests/back/Platform/Specification/Component/CatalogVolumeMonitoring/Volume/Normalizer/VolumesSpec.php
Allow to enable/disable display of values in catalog volume monitoring screen, depending on the activation of the feature or not (needed for asset/ref entities)
> TIP-1579: hide catalog volume from disabled features

- CHANGELOG-6.0.md
- src/Akeneo/Platform/Job/back/Infrastructure/Installer/JobInstaller.php
- upgrades/schema/Version_6_0_20220520114800_add_start_time_index_on_job_execution.php
- upgrades/test_schema/Version_6_0_20220520114800_add_start_time_index_on_job_execution_Integration.php
See : [PIM-10451](https://akeneo.atlassian.net/jira/software/c/projects/PIM/boards/9?modal=detail&selectedIssue=PIM-10451)
Updating JobInstaller.php to add an index on start_time
Add migration to add an index on start_time on the job_execution table  for client that started on 6.0
> PIM-10451: Add start_time index on JobInstaller

- CHANGELOG-6.0.md
- upgrades/schema/Version_6_0_20220524122443_oro_user_field_consecutive_authentication_failure_counter_is_not_nullable.php
Some customers migrating from Flexibility v6 to serenity have failed diff on table oro_user because of the definition of the column consecutive_authentication_failure_counter.
This PR proposes a migration to ensure all descriptions of this column correspond to : unsigned int not null default 0.
> PIM-10457 Fixed inconsistency with column oro_user.consecutive_authentication_failure_counter when migrating from v6 to serenity

- .circleci/config.yml
4.0 is not supported anymore and the nightly build is not monitored
> Remove nightly build for 4.0

- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Connector/JobLauncher/RunUniqueProcessJob.php
- src/Akeneo/Tool/Bundle/BatchQueueBundle/Command/JobExecutionWatchdogCommand.php
- src/Akeneo/Tool/Bundle/BatchQueueBundle/Manager/JobExecutionManager.php
- src/Akeneo/Tool/Bundle/BatchQueueBundle/MessageHandler/JobExecutionMessageHandler.php
- src/Akeneo/Tool/Bundle/BatchQueueBundle/Resources/config/services.yml
- src/Akeneo/Tool/Bundle/BatchQueueBundle/spec/Manager/JobExecutionManagerSpec.php
- src/Akeneo/Tool/Bundle/BatchQueueBundle/tests/integration/Queue/ConsumeJobMessageIntegration.php
Split the Job consumer with a dedicated job execution watchdog.
This allow us to have a mutualized, context agnostic message consumer launching a watchdog responsible for initiating the context and running the health check.
> BH-1160: Job execution watchdog

- src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/BooleanValueFactory.php
- src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/Boolean.php
- src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/BooleanValidator.php
- src/Akeneo/Pim/Enrichment/Component/Product/Validator/ExternalApi/PayloadFormatValidator.php
- tests/back/Pim/Enrichment/Integration/Validation/PayloadFormatValidatorIntegration.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Factory/Value/BooleanValueFactorySpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Validator/ExternalApi/PayloadFormatValidatorSpec.php
Forbids the instantiation of a boolean value with non-boolean data. 
In case of a wrong data in the DB (e.g '1' instead of true), the corresponding values will be ignored, this allows to
- not pass a wrong data to the API
- not index wrong data 
Regarding API, an additional payload validation was added in order to keep the same behavior as before
> Fix boolean value factory for non-boolean data

- .circleci/jobs/build_and_deploy.yml
- .circleci/workflows/editions/community.yml
- Dockerfile
- docker/Dockerfile_node
Build Node v16 instead of v18 because we are not ready for v18
Move the docker builds in a specific nightly workflow
> DPE: Build Akeneo Node v16 docker image

- front-packages/akeneo-design-system/src/all.visual.tsx
The goal of this PR is to speed up the CI of the DSM.
The "Launch visual tests" step of the CI is currently taking ~ 4 min 30 sec.
This step is running the following npm script: `yarn test:visual:run` that finally runs `sb extract storybook-static stories.json && jest --config ./jest.visual.config.js`.
The `sb extract storybook-static stories.json` part is extracting all the stories from the `stories.mdx` files, see: [main.js](https://github.com/akeneo/pim-community-dev/blob/master/front-packages/akeneo-design-system/.storybook/main.js#L7) 
This way the stories are extracted in a `stories.json` file. Then, we are using jest to execute the [all.visual.tsx](https://github.com/akeneo/pim-community-dev/blob/master/front-packages/akeneo-design-system/src/all.visual.tsx) file. This file takes a …
> OBS-157: Remove the 500ms waiting between the screenshot of each story

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/AttributeOptionsExistValidator.php
- src/Akeneo/Pim/Structure/Bundle/Query/PublicApi/AttributeOption/Cache/LRUCachedGetExistingAttributeOptions.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/AttributeOptionsExistValidatorSpec.php
- tests/back/Pim/Structure/Specification/Bundle/Query/PublicApi/AttributeOption/Cache/LRUCachedGetExistingAttributeOptionsSpec.php
This PR fixes two related issues, which used to cause issues when validating the existence of options with numeric codes:
- The LRU cached get existing options used to return wrong results when querying the existence of option codes containing a dot
- The OptionsExistValidator returned false positives when comparing a numeric (integerish) option code and a numeric (floatish) option code (from user input, as an option code cannot contain a non alphanumeric char), e.g: "3.00" and "3"
> PIM-10475: Fix option existence validation for numeric option codes

- CHANGELOG.md
- src/Akeneo/Tool/Component/Connector/Writer/File/FlatItemBufferFlusher.php
- src/Akeneo/Tool/Component/Connector/spec/Writer/File/FlatItemBufferFlusherSpec.php
- tests/back/Integration/IntegrationTestsBundle/Launcher/JobLauncher.php
- tests/legacy/features/pim/enrichment/product/mass-action/quick-export/quick_export.feature
- tests/legacy/features/pim/enrichment/product/mass-action/quick-export/quick_export_grid_context.feature
- tests/legacy/features/pim/enrichment/product/mass-action/quick-export/quick_export_products_and_product_models.feature
- tests/legacy/features/pim/enrichment/product/mass-action/quick-export/quick_export_with_localized_data.feature
- tests/legacy/features/pim/enrichment/product/mass-action/quick-export/quick_export_with_media.feature
In this PR we change the behavior of the export writter to flush only if the buffer count at least 1 item
> PIM-10471: Do not generate 2 files when making a quick export of 1 type of products

- CHANGELOG-5.0.md
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/family/form/attributes/attributes.js
PHP configuration does not allow more than 1000 parameters.
We split the front query to split calls 200 by 200, then merge the attributes.
> PIM-10472: Fix attributes list limit in the family mass edit

- CHANGELOG-6.0.md
- src/Akeneo/Platform/Job/front/process-tracker/src/feature/ProcessTrackerApp.tsx
- src/Akeneo/Platform/Job/front/process-tracker/src/feature/pages/JobExecutionDetail.test.tsx
- src/Akeneo/Platform/Job/front/process-tracker/src/feature/pages/JobExecutionDetail.tsx
When we are on a job execution detail page and the job execution id changes (manually or through a click on notification), the job execution detail component is not correctly rerendered. It is now thanks to the params id used as key. Also, the component now receives a prop for job execution id.
> PIM-10470: Refresh process tracker job detail page when job execution id param changes

- tests/legacy/features/Behat/Decorator/Field/Select2Decorator.php
Fixes open() method when the select2 field is not fully rendered yet (see https://app.circleci.com/pipelines/github/akeneo/pim-enterprise-dev/68341/workflows/c150c905-2f7f-4c88-98cf-9b25f0ef2e22/jobs/415833)
> CPM-654: Fix behat Select2Decorator::open() method

- src/Akeneo/Pim/Structure/Bundle/EventSubscriber/ComputeFamilyVariantStructureChangesSubscriber.php
- src/Akeneo/Pim/Structure/Bundle/EventSubscriber/SaveFamilyVariantOnFamilyUpdateSubscriber.php
- src/Akeneo/Pim/Structure/Bundle/Resources/config/event_subscribers.yml
- src/Akeneo/Pim/Structure/Component/Model/FamilyVariant.php
- src/Akeneo/Pim/Structure/Component/Model/FamilyVariantInterface.php
- src/Akeneo/Pim/Structure/Component/Updater/FamilyVariantUpdater.php
- tests/back/Pim/Enrichment/Integration/EntityWithFamilyVariant/ChangeVariantFamilyStructureIntegration.php
- tests/back/Pim/Structure/Specification/Bundle/EventSubscriber/ComputeFamilyVariantStructureChangesSubscriberSpec.php
- tests/back/Pim/Structure/Specification/Bundle/EventSubscriber/SaveFamilyVariantOnFamilyUpdateSubscriberSpec.php
- tests/back/Pim/Structure/Specification/Component/Model/FamilyVariantSpec.php
- tests/back/Pim/Structure/Specification/Component/Updater/FamilyVariantUpdaterSpec.php
The subscriber did not listen the POST_SAVE_ALL events and only triggered the job on unitary POST_SAVE event.
Now we listen the POST_SAVE_ALL events, but this PR improves the decision if the job should be launched or not (before we always launch the job, even for a change on a label!)
So we avoid to launch job on a family variant if:
- the family variant is new
- the attributes or the axes of a level are updated (there is a validator to check the axes are not changed, but this part of code is ready just in case)
- another job containing this family variant is in "starting" status (!= started!)
When we update a family, before the `compute_family_variant_structure_changes` was always launched. We keep this behaviour by force it to be launched. 
When we update several families, we are in an …
> PIM-10462: Fix ComputeFamilyVariantStructureChanges job not launched after import

- src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Category/SqlFindCategoryTrees.php
- src/Akeneo/Pim/Enrichment/Component/Category/Query/PublicApi/CategoryTree.php
- tests/back/Pim/Enrichment/Integration/Category/SqlFindCategoryTreesIntegration.php
Add id field on `CategoryTree`, in order to avoid another fetch to retrieve it.
`id` is mainly used to retrieve children categories.
> RAB-761: Add id field on CategoryTree

- src/Akeneo/Platform/Bundle/ImportExportBundle/Controller/InternalApi/JobInstanceController.php
- src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/EventSubscriber/DownloadFileFromStorageBeforeImportSubscriber.php
- src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/EventSubscriber/ExportFileToStorageAfterExportSubscriber.php
- src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/EventSubscriber/UpdateJobExecutionStorageSummarySubscriber.php
In this PR, I made the job failed when the storage is not available instead of just add a error message in the page
> RAB-791: Make the job fail when the storage is not available

- components/catalogs/Makefile
- make-file/connectivity-connection.mk
I caught that there was a service definition error in CXP-1197 but the CI did not catch it because all tests were passing anyway.
Adding `bin/console lint:container` will catch those small errors.
> OCT-67: Add symfony container lint check

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductGrid/ProductModelImagesFromCodes.php
Quick fix: increase sort_buffer_size to display product datagrid
> PIM-10495: Fix product datagrid by increasing sort_buffer_size

- src/Akeneo/Connectivity/Connection/back/Application/Webhook/Command/SendBusinessEventToWebhooksHandler.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/DependencyInjection/AkeneoConnectivityConnectionExtension.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Webhook/commands.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Webhook/message_handlers.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Webhook/services_test.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/Command/SendBusinessEventToWebhooks.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/MessageHandler/BusinessEventHandler.php
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/GuzzleJsonHistory.php
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/GuzzleMockHandlerStack.php
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/WebTestCase.php
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Webhook/ConsumeProductEventEndToEnd.php
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Webhook/ConsumeProductModelEventEndToEnd.php
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Webhook/IncrementEventsApiRequestCountEndToEnd.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Webhook/MessageHandler/BusinessEventHandlerSpec.php
- src/Akeneo/Platform/Component/EventQueue/BulkEvent.php
- src/Akeneo/Platform/Component/EventQueue/BulkEventInterface.php
- src/Akeneo/Platform/Component/EventQueue/BulkEventNormalizer.php
- src/Akeneo/Platform/Component/EventQueue/EventNormalizer.php
- src/Akeneo/Tool/Bundle/ApiBundle/tests/integration/ApiTestCase.php
- src/Akeneo/Tool/Bundle/MessengerBundle/Middleware/UcsMiddleware.php
- src/Akeneo/Tool/Component/Messenger/Tenant/TenantAwareInterface.php
I had another solution in mind when starting the PR but it's  not possible for now to use the enveloppe in handler.
See this issue and conversation: https://github.com/symfony/symfony/issues/31075
> BH-1176: UCS - Webhooks

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/FlatToStandard/ColumnsMerger.php
- src/Akeneo/Tool/Bundle/MeasureBundle/Convert/MeasureConverter.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/FlatToStandard/ColumnsMergerSpec.php
When Excel cell is formatted as number, the file reader gives us a float.
Problem comes with very small values (0.000075) that comes with scientific notation (7.5E-5), because we merge it with its metric unit : "7.5E-5 GRAM".
So now, we enforce decimal notation.
> PIM-10487: Fix import of very tiny measurement values (e.g. 0.000075 GRAM)

- components/catalogs/Makefile
- components/catalogs/back/infection.json
- components/catalogs/back/phpunit.xml.dist
- components/catalogs/back/tests/Unit/Infrastructure/Validation/MaxNumberOfCatalogsPerUserValidatorTest.php
3 new makefile targets:
```
make catalogs-mutation-back
make catalogs-mutation-unit-back
make catalogs-mutation-integration-back
```
Since `catalogs-mutation-unit-back` is fast enough for the moment, I've added it to `catalogs-tests`.
On the contrary, `catalogs-mutation-integration-back` is quit slow (~7min) but can be useful, for example, it discovered that all tests are passing when you remove the following line, which is yet already covered by tests:
> OCT-71: Add infection for mutation testing

- src/Akeneo/Channel/back/tests/phpstan.neon.dist
- src/Akeneo/Tool/Bundle/BatchQueueBundle/MessageHandler/JobExecutionMessageHandler.php
- src/Akeneo/Tool/Bundle/BatchQueueBundle/tests/integration/Factory/JobExecutionMessageFactoryIntegration.php
- src/Akeneo/Tool/Bundle/MessengerBundle/Middleware/UcsMiddleware.php
- src/Akeneo/Tool/Component/BatchQueue/Factory/JobExecutionMessageFactory.php
- src/Akeneo/Tool/Component/BatchQueue/Normalizer/JobExecutionMessageNormalizer.php
- src/Akeneo/Tool/Component/BatchQueue/Queue/JobExecutionMessage.php
- src/Akeneo/Tool/Component/BatchQueue/Queue/JobExecutionMessageInterface.php
- src/Akeneo/Tool/Component/BatchQueue/spec/Factory/JobExecutionMessageFactorySpec.php
- src/Akeneo/Tool/Component/BatchQueue/spec/Normalizer/JobExecutionMessageNormalizerSpec.php
Tenant ID information is transported by the Doctrine transport and injected in messages at runtime.
> PH-20: UCS - Do not persist tenant ID in JobMessage

- src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/product/index.yml
- src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/column-selector.ts
Allow using column-selector for different grids
> PIM-10491: add gridName in column-selector configuration

- src/Akeneo/Connectivity/Connection/back/Domain/Webhook/EventNormalizer/ProductEventNormalizer.php
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Webhook/ConsumeProductEventEndToEnd.php
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Webhook/IncrementEventsApiRequestCountEndToEnd.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Domain/Webhook/EventNormalizer/ProductEventNormalizerSpec.php
- src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/BusinessEvent/DispatchProductCreatedAndUpdatedEventSubscriber.php
- src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/BusinessEvent/DispatchProductRemovedEventSubscriber.php
- src/Akeneo/Pim/Enrichment/Component/Product/Message/ProductCreated.php
- src/Akeneo/Pim/Enrichment/Component/Product/Message/ProductRemoved.php
- src/Akeneo/Pim/Enrichment/Component/Product/Message/ProductUpdated.php
- src/Akeneo/Pim/Enrichment/Component/Product/Webhook/Exception/ProductNotFoundException.php
- src/Akeneo/Pim/Enrichment/Component/Product/Webhook/ProductCreatedAndUpdatedEventDataBuilder.php
- src/Akeneo/Pim/Enrichment/Component/Product/Webhook/ProductRemovedEventDataBuilder.php
- src/Akeneo/Platform/Component/EventQueue/EventNormalizer.php
- tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/BusinessEvent/DispatchProductCreatedAndUpdatedEventSubscriberSpec.php
- tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/BusinessEvent/DispatchProductRemovedEventSubscriberSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Message/ProductCreatedSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Message/ProductRemovedSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Message/ProductUpdatedSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Webhook/Exception/ProductNotFoundExceptionSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Webhook/ProductCreatedAndUpdatedEventDataBuilderSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Webhook/ProductModelRemovedEventDataBuilderSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Webhook/ProductRemovedEventDataBuilderSpec.php
As identifier will be optional, we need to create webhook messages with uuid instead of identifiers.
> CPM-674: Add uuid on webhook messages

- src/Akeneo/Tool/Bundle/BatchBundle/Launcher/JobLauncherInterface.php
- src/Akeneo/Tool/Bundle/BatchBundle/Launcher/SimpleJobLauncher.php
- src/Akeneo/Tool/Bundle/BatchBundle/Launcher/SynchronousJobLauncher.php
- src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/services.yml
- src/Akeneo/Tool/Bundle/BatchBundle/tests/Integration/Launcher/SynchronousJobLauncherIntegration.php
- src/Akeneo/Tool/Bundle/BatchQueueBundle/Launcher/QueueJobLauncher.php
- src/Akeneo/Tool/Bundle/ConnectorBundle/Launcher/AuthenticatedJobLauncher.php
In this PR: 
- I added a new JobLauncher called SynchronousJobLauncher this launcher will not queue job but instead directly run the job. In order to sure that process killed is managed, the launcher run job in another process and the master process update the health_check_time during the process. 
- I made the user nullable because rule are actually launched without user
> PIM-10504: Add possibility to launch rule without passing throught queue

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/jobs.yml
- src/Akeneo/Pim/Enrichment/Component/Product/Job/RemoveCompletenessForChannelAndLocaleTasklet.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Job/RemoveCompletenessForChannelAndLocaleTaskletSpec.php
When removing a locale from a channel, and re-adding it before the remove_completeness_for_channel_and_locale, the job would re-remove it, possibly deactivating the locale if it's not bound to another channel
This PR:
- ensures the job does nothing if the provided locales are still in the channel
- and moreover, ensures the job DOES NOT update the locales, as it's not its role (it's only here to clean product values, recompute completeness and reindex products)
> PIM-10516: Do not run the remove completeness job when there is no need

- CHANGELOG.md
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/controller/attribute/create.js
Fixes the attribute creation form when the label from the creation modal contains an `&`
```javascript
decodeURI('%26')
'%26'
decodeURIComponent('%26')
'&'
```
> PIM-10508: Fix attribute creation form when label contains an '&' character

- components/catalogs/Makefile
- components/catalogs/front/.eslintrc.json
- components/catalogs/front/dependency-cruiser.js
- components/catalogs/front/package.json
- components/catalogs/front/src/components/CatalogEdit/hooks/useCatalogForm.test.ts
- components/catalogs/front/src/components/CatalogEdit/reducers/CatalogFormReducer.test.ts
- components/catalogs/front/src/components/ProductSelection/index.ts
- package.json
- yarn.lock
`depcruise` does static analysis of dependencies & support custom rules.
It comes with default rules like
- `no-non-package-json` => you cannot uses dependencies not declared in package.json
- `not-to-deprecated` => warning when using a deprecated dependency
You can also write custom rules.
For example, the following one forbid to use internal files from other major components, it can only use modules exported in the `index.ts` of others.
```
{
name: 'no-to-other-components-internals',
severity: 'error',
from: {
path: '^src/components/([^/]+)/.+',
},
to: {
path: '^src/components/([^/]+)/(?!index).+',
pathNot: '^src/components/$1',
},
},
```
:warning: This PR, as it is, still have 50 dependency errors to be fixed before having a green …
> OCT-80: dependency cruiser

- components/catalogs/Makefile
- components/catalogs/back/src/Infrastructure/Controller/Internal/GetFamiliesAction.php
- components/catalogs/back/src/Infrastructure/Persistence/GetFamiliesByCodeQuery.php
- components/catalogs/back/src/Infrastructure/Symfony/Resources/config/services.yml
- components/catalogs/back/tests/Integration/Infrastructure/Controller/Internal/GetFamiliesActionTest.php
- components/catalogs/back/tests/Unit/Infrastructure/Controller/Internal/GetFamiliesActionTest.php
The frontend needs to be able to find families by code.
When the multi select is rendered, if there is values in it, we need to fetch the families of those codes to display the label.
We cannot wait for the infinite scroll to find them.
> CXP-1240: add support to find families by code

- composer.json
Do not use v.3.9.1 of php-cs-fixer (see https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/6470)
Note: This PR should be reverted when a fix comes for the mentioned issue
> Do not use v3.9.1 of friendsofphp/php-cs-fixer

- CHANGELOG.md
- src/Oro/Bundle/PimDataGridBundle/EventListener/AddParametersToGridListener.php
This used to throw a type error if $value was an array (e.g assiciatedIds in `association-group-grid`)
> PIM-10527: Fix associated groups grid

- CHANGELOG.md
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/mass-edit/form/product/associate.js
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/associations.js
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/quantified-associations/components/QuantifiedAssociationRow.tsx
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/quantified-associations/components/QuantifiedAssociations.tsx
- src/Akeneo/Platform/Bundle/UIBundle/tests/front/unit/components/QuantifiedAssociationRow.unit.tsx
- src/Akeneo/Platform/Bundle/UIBundle/tests/front/unit/components/QuantifiedAssociations.unit.tsx
There was a behavior mismatch concerning the "Add associations" button visibility for simple associations and quantified associations.
This button should be displayed if: (see [here](https://github.com/akeneo/pim-enterprise-dev/blob/8c2201079b376273c501d6c04e395a2c3a186b05/src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/associations.js#L19-L18))
1. The user is owner of the product
2. The user has the permission to add associations (ACL)
The problem comes from the fact that there was a missing check for rule #1 when displaying the quantified association grid.
The fix consists in drilling down the "isOwner" information (from backbone getFormData().meta.is_user_owner) through a new optional React prop "isUserOwner" …
> PIM-10515: Fix 'add associations' button visibility for quantified associations & category permissions

- CHANGELOG.md
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/controller/association-type.js
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/controller/attribute-group/edit.js
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/controller/attribute/edit.js
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/controller/channel/edit.js
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/controller/family.js
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/controller/group-type.js
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/controller/group.js
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/controller/job-instance.js
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/controller/mass-edit.js
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/controller/product/index.js
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/controller/system.js
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/controller/user.js
Page titles are set through the [pim/page-title](https://github.com/akeneo/pim-community-dev/blob/master/src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/page-title.js) component in javascript, we don't need to escape special characters here (as opposite as if they were included in a HTML template)
Also, in some pages, labels were escaped twice (eg `&` would become `&amp;amp;`)
before:
after:
> PIM-10528: Fix escaped special characters in page titles

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Versioning/Product/ValueNormalizer.php
https://akeneo.atlassian.net/browse/PIM-10518?atlOrigin=eyJpIjoiYmIxNmY4YTgwZDA1NDJhZmE5MTE5OWRmOTNjNjI3MGEiLCJwIjoiaiJ9
**What's the issue ?**
The normalization behavior for simple and multi select option is not the same. For multi, the normalizer gets the saved attribute code. For simple, the normalizer gets the saved product value. We want to have the same behavior for simple and multi.
After a product import with these values : 
Versioning before fix : 
Versioning after fix : 
> PIM-10518: Normalize simple select option value like multi select

- components/catalogs/front/tsconfig.build.json
Recent changes in catalogs broke how it's imported in Connectivity. Fixing the tsconfig resolve the issue.
What happened?
We changed the extensions of our frontend tests from `.test.ts` to `.unit.ts` and `.integration.ts` to better differentiate them.
We didn't notice that the tests were no longer ignored by tsconfig and were exported in the `lib` directory, changing its directory structure and making it unusable outside catalogs.
The CI for catalogs was green when we did that change and this is something that we need to prevent from happening again.
> OCT-81: fix tsconfig

- src/Akeneo/Pim/Enrichment/Bundle/Command/MigrateToUuid/MigrateToUuidReindexElasticsearch.php
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/cli_command.yml
Now that we don't delete legacy product documents (with mysql id) during indexation anymore, we need to manually delete them during the migration reindexation step to avoid an infinite loop.
> CPM-682: Fix reindexation step

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/Product/back/Domain/UserIntent/Factory/ValueUserIntentFactoryRegistry.php
- src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Domain/UserIntent/Factory/ValueUserIntentFactoryRegistrySpec.php
Attribute codes containing only numeric chars are typed as int by PHP, we need to cast them to string.
> PIM-10542: Fix int attribute code breaks ValueUserIntentFactoryRegistry

- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Marketplace/routing.yml
Endpoints for Test App creation and deletion are listed when fetching the list of available endpoints using `/api/rest/v1/`
This fix effectively removes these two endpoints from the list
> OCT-93: Hide test app internal endpoints from the public endpoint list

- upgrades/schema/Version_7_0_20220704141138_update_job_instance_parameter_path.php
- upgrades/test_schema/Version_7_0_20220704141138_update_job_instance_parameter_path_Integration.php
- In this PR, we **don't migrate quick export** job instances as they have a dedicated type (`quick_export`).
**Performances impact on customers** :zap:  
This query only updates job instances filtered by `types` and `connector`. 
The maximum in production is **243** (`srnt-alfuttain`), so this won't be a problem.
**Remaining work:**
> RAB-873: Migrate existing job instances (JobConfiguration[storage][file_path] and JobConfiguration[filePath])

- src/Akeneo/Platform/Bundle/ImportExportBundle/Application/TransferFilesToStorage/FileToTransfer.php
- src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/Hydrator/LocalStorageHydrator.php
- src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/Step/UploadStep.php
- src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/StorageClient/TransferFilesToStorage.php
- src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/controllers.yml
- src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/hydrators.yml
- src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev/jobs.yml
- src/Akeneo/Tool/Component/Connector/Writer/File/AbstractFileWriter.php
- src/Akeneo/Tool/Component/Connector/Writer/File/AbstractItemMediaWriter.php
- src/Oro/Bundle/PimDataGridBundle/Controller/ProductExportController.php
- src/Oro/Bundle/PimDataGridBundle/Resources/config/controllers.yml
- tests/back/Platform/Acceptance/ImportExport/TransferFilesToLocalStorageTest.php
- tests/back/Platform/Acceptance/ImportExport/TransferFilesToNoneStorageTest.php
- tests/back/Platform/Specification/Bundle/ImportExportBundle/Infrastructure/Hydrator/LocalStorageHydratorSpec.php
- tests/back/Platform/Specification/Bundle/ImportExportBundle/Infrastructure/StorageClient/StorageClientProviderSpec.php
- tests/legacy/features/pim/enrichment/product/export/configure_export_products_with_media.feature
In this PR: 
- We fixed some behat tests than does not pass only in CE (non SAAS) =>
- Quick export is local or none depending on version in order to make the tests/legacy/features/pim/enrichment/product/mass-action/quick-export/quick_export_with_media.feature:29 pass
- We now only exclude local file on local storage instead of do not export the whole files on locale storage because media are not in locale => it break the tests
- We made icecat fixture by default to none storage in order to not have the import now
> RAB: Fix remote storage bug of break session

- front-packages/akeneo-design-system/src/components/Input/TagInput/TagInput.tsx
> RAB-837: Add min-width on remove tag icon

- src/Akeneo/Tool/Bundle/BatchQueueBundle/Launcher/QueueJobLauncher.php
- upgrades/schema/Version_7_0_20220722090828_remove_old_file_path_on_product_and_product_model_quick_export_job.php
- upgrades/test_schema/Version_7_0_20220722090828_remove_old_file_path_on_product_and_product_model_quick_export_job_Integration.php
In this PR: 
- We remove ugly hack that we done when we migrate to storage : Some client have a filePath into here product and product model quick export. In this migration we removed this key in order to clean some code (this key is not used anymore).
Performance impact: 
Only 4 lines will be selected and updated by the migration on all instances => this kind of job cannot be created by clients
> RAB-924: Add migration to remove old filePath on product and product model quick export

- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Command/OneTimeTask/CleanCompletenessEvaluationResultsCommand.php
Use `sort_buffer_size` to avoid MYSQL error during the calculation of the completeness of required and non-required attributes
> GRF-207: Fix MYSQL error during the calculation of the completeness

- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Audit/Command/UpdateAuditDataCommandEndToEnd.php
- src/Akeneo/Connectivity/Connection/back/tests/Integration/Audit/Persistence/DbalExtractConnectionsProductEventCountQueryIntegration.php
- src/Akeneo/Connectivity/Connection/back/tests/Integration/Marketplace/Persistence/GetUserProfileQueryIntegration.php
- src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/tests/Integration/CommunicationChannel/Api/ApiFindAnnouncementItemsIntegration.php
- src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/tests/Integration/CommunicationChannel/Api/ApiFindNewAnnouncementIdsIntegration.php
- src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/tests/Integration/WebTestCase.php
- src/Akeneo/Tool/Bundle/BatchQueueBundle/tests/Acceptance/AckMessageEventListenerTest.php
- src/Akeneo/Tool/Bundle/MeasureBundle/tests/Acceptance/AcceptanceTestCase.php
- src/Akeneo/Tool/Bundle/MeasureBundle/tests/EndToEnd/WebTestCase.php
- src/Akeneo/Tool/Bundle/MeasureBundle/tests/Integration/SqlIntegrationTestCase.php
- src/Akeneo/Tool/Bundle/MessengerBundle/tests/integration/OrderingKeySolverIntegration.php
- src/Oro/Bundle/PimDataGridBundle/tests/Integration/Controller/ControllerIntegrationTestCase.php
- tests/back/Pim/Enrichment/EndToEnd/InternalApiTestCase.php
- tests/back/Pim/Enrichment/EndToEnd/Product/EntityWithQuantifiedAssociations/AbstractQuantifiedAssociationsTestCase.php
- tests/back/Pim/Enrichment/EndToEnd/Product/MassEdit/AbstractMassEditEndToEnd.php
- tests/back/Pim/Enrichment/EndToEnd/Product/Product/InternalApi/DownloadProductPdfEndToEnd.php
- tests/back/Pim/Enrichment/EndToEnd/Product/Product/InternalApi/ProductCreationEndToEnd.php
- tests/back/Pim/Enrichment/EndToEnd/Product/Product/InternalApi/QuantifiedAssociations/AbstractProductWithQuantifiedAssociationsTestCase.php
- tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/InternalApi/QuantifiedAssociations/AbstractProductModelWithQuantifiedAssociationsTestCase.php
- tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/InternalApi/UpdateVariantProductEndToEnd.php
- tests/back/Pim/Enrichment/EndToEnd/RemoveLocaleFromChannelEndToEnd.php
- tests/back/Platform/EndToEnd/InternalApiTestCase.php
- tests/back/Platform/Integration/ImportExport/Repository/InternalApi/GetJobExecutionTrackingIntegration.php
- tests/back/UserManagement/Integration/Bundle/ControllerIntegrationTestCase.php
Since Symfony 5.3 usage of self::$container is deprecated we should use now self::getContainer(). 
In this PR, I manage this deprecation
> RAB: Fix deprecated self::$container of symfony

- components/catalogs/back/src/Infrastructure/TemporaryEnrichmentBridge/SearchAfterSizeUuidResultCursorFactory.php
- src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Cursor.php
- src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/CursorFactory.php
- src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/FromSizeCursor.php
- src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/FromSizeCursorFactory.php
- src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/FromSizeIdentifierResultCursorFactory.php
- src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/IdentifierCursor.php
- src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/IdentifierCursorFactory.php
- src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/IdentifierResult.php
- src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/IdentifierResults.php
- src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/SearchAfterSizeIdentifierResultCursorFactory.php
- tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/CursorSpec.php
- tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/FromSizeCursorSpec.php
- tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/FromSizeIdentifierResultCursorFactorySpec.php
- tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/IdentifierCursorFactorySpec.php
- tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/IdentifierResultSpec.php
- tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/IdentifierResultsSpec.php
- tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/SearchAfterSizeIdentifierResultCursorFactorySpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Job/ComputeDataRelatedToFamilyProductsTaskletSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Job/ComputeCompletenessOfProductsFamilyTaskletSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Job/RemoveCompletenessForChannelAndLocaleTaskletSpec.php
When done, notify octopus team about updating components/catalogs/back/src/Infrastructure/TemporaryEnrichmentBridge/SearchAfterSizeUuidResultCursorFactory.php#L57 to also add the id in _source of the esQuery
> CPM-634: Add Uuids in IdentifierResult from PQB

- CHANGELOG-6.0.md
- config/packages/framework.yml
- config/packages/security.yml
`strict` mode samesite cookies was implemented [here](https://github.com/akeneo/pim-community-dev/pull/16099/files) and backport to v6 [here](https://github.com/akeneo/pim-community-dev/pull/16520).
It was the [rollback](https://github.com/akeneo/pim-enterprise-dev/pull/12679) and [change to](https://github.com/akeneo/pim-enterprise-dev/pull/12684) `lax` mode but only on EE.
In this PR we correct it on CE. It cannot be in `strict` mode for SSO and Apps oAuth2 workflows.
**Note**: we cannot test it with behat because Cookie creation in `friendsofbehat/mink` only manages `name` and `value`: https://github.com/FriendsOfBehat/Mink/blob/master/src/Driver/DriverInterface.php#L203
> OCT-76: On CE v6, when you connect an App and you are redirected to the PIM, you lose your authentication

- src/Akeneo/Pim/Structure/Bundle/EventSubscriber/SaveFamilyVariantOnFamilyUpdateSubscriber.php
- src/Akeneo/Pim/Structure/Component/Model/Family.php
- src/Akeneo/Pim/Structure/Component/Model/FamilyInterface.php
- src/Akeneo/Pim/Structure/Component/Model/FamilyVariantInterface.php
- src/Akeneo/Pim/Structure/Component/Updater/FamilyUpdater.php
- tests/back/Pim/Structure/Specification/Bundle/EventSubscriber/SaveFamilyVariantOnFamilyUpdateSubscriberSpec.php
- tests/back/Pim/Structure/Specification/Component/Model/FamilySpec.php
- tests/back/Pim/Structure/Specification/Component/Updater/FamilyUpdaterSpec.php
- tests/legacy/features/pim/structure/family/remove_attribute_from_a_family.feature
Disable `compute_family_variant_structure_changes` launch on simple and bulk family save subscriber because it is already done in the `ComputeCompletenessOfProductsFamilyTasklet` with the `saveAll` function.
> PIM-10478: Disable compute_family_variant_structure_changes on familySave

- src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/ListProductsByUuidController.php
- src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Sorter/Field/IdSorter.php
- src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Sorter/Field/UuidSorter.php
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/connector/use_cases.yml
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/controllers.yml
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/query_builders.yml
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/routing/external_api/product.yml
- src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Connector/SqlGetConnectorProducts.php
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/ListProductsByUuidQueryHandler.php
- src/Akeneo/Pim/Enrichment/Component/Product/Query/AbstractEntityWithValuesQueryBuilder.php
- src/Akeneo/Tool/Component/Api/Pagination/SearchAfterHalPaginator.php
- tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/AbstractProductTestCase.php
- tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/SuccessListProductsWithUuidEndToEnd.php
- tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/product_china.json
- tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/product_localizable.json
- tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/product_localizable_and_scopable.json
- tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/product_scopable.json
- tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/product_simple.json
- tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/product_with_parent.json
- tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/product_without_category.json
- tests/back/Pim/Enrichment/Specification/Component/Product/Query/ProductModelQueryBuilderSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Query/ProductQueryBuilderSpec.php
This PR adds LIST product endpoint by UUID
It only includes Success EndToEnd tests
It miss ErrorListProductEndToEnd, ListProductWithCompletenessEndToEnd, SuccessListVariantProductDeltaEndToEnd to be 100% coverage in test, but this will be done in another PR.
> CPM-638: Add route for listing products with uuid

- src/Akeneo/Tool/Bundle/BatchBundle/Command/BatchCommand.php
- src/Akeneo/Tool/Bundle/BatchBundle/JobExecution/CreateJobExecutionHandler.php
- src/Akeneo/Tool/Bundle/BatchBundle/JobExecution/ExecuteJobExecutionHandler.php
- src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/cli_commands.yml
- src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/services.yml
- src/Akeneo/Tool/Bundle/BatchBundle/tests/Integration/JobExecution/CreateJobExecutionHandlerIntegration.php
Extract services from the BatchCommand:
- `CreateJobExecutionHandler` for creating the JobExecution when only batch code is provided
- `ExecuteJobExecutionHandler` for effectively executiong the JobExecution
No code changed in the services, I just decoupled them from the Console Input/Ouput interfaces.
This will allow us to reuse these services without being tied to the command, which I will need for UCS.
The BatchCommand main proces is now way simpler:
```
if (null === $executionId) {
$jobExecution = $this->jobExecutionFactory->createFromBatchCode($code, $config, $username);
$executionId = $jobExecution->getId();
}
$jobExecution = $this->jobExecutionRunner->executeFromJobExecutionId((int)$executionId);
```
And these services can be reused more or less the same way.
> PH-13: Extract services from BatchCommand

- src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/Validation/FilePathValidator.php
- tests/back/Platform/Acceptance/ImportExport/Infrastructure/Validation/Storage/ValidateLocalStorageTest.php
- tests/back/Platform/Acceptance/ImportExport/Infrastructure/Validation/Storage/ValidateNoneStorageTest.php
- tests/back/Platform/Acceptance/ImportExport/Infrastructure/Validation/ValidateFilePathTest.php
Actually, import jobs have an null filePath problem is that it throw an error 500 on save. In this PR, we fixed that.
Now we early return when value is null. 
```
Uncaught PHP Exception TypeError: "Akeneo\Platform\Bundle\ImportExportBundle\Infrastructure\Validation\FilePathValidator::validateFileExtension(): Argument #1 ($filePath) must be of type string, null given, called in /srv/pim/vendor/akeneo/pim-community-dev/src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/Validation/FilePathValidator.php on line 19" at /srv/pim/vendor/akeneo/pim-community-dev/src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/Validation/FilePathValidator.php line 22
```
We tried to use validation groups in order to check that the …
> Do not throw an exception when filepath is null

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/Product/back/Domain/UserIntent/Factory/AssociationsUserIntentFactory.php
- src/Akeneo/Pim/Enrichment/Product/back/Domain/UserIntent/Factory/QuantifiedAssociationUserIntentFactory.php
- src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Domain/UserIntent/Factory/AssociationsUserIntentFactorySpec.php
- src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Domain/UserIntent/Factory/QuantifiedAssociationUserIntentFactorySpec.php
Associations codes can come as an int value whearas the userIntent expects a string, so we cast it in the factory
> PIM-10561: Fix associationUserIntentFactory to cast in to string

- .circleci/configure_docker_mirrors.sh
- .circleci/jobs/features/other.yml
- docker-compose.yml
Add a Docker image registry cache mirror to increase CI stability
see https://cloud.google.com/container-registry/docs/pulling-cached-images#configure
I chose to apply it mainly on parallel runs because they are the most error prone, but we may add this Docker configuration on other jobs if needed.
Note for debug on the CI: you can activate the debug log for docker daemon by using this configuration:
```json
{
"registry-mirrors": ["https://mirror.gcr.io"],
"debug": true
}
```
The log will then be available in `var/log/syslog` or in the journal with `sudo journalctl -fu docker.service`
You can then check which mirror is used, like in this extract:
```
Aug  3 15:47:40 ip-172-28-21-188 dockerd[4341]: time="2022-08-03T15:47:40.684988496Z" level=debug msg="hostDir: …
```
> Use Google mirror cache registry to pull Docker images

- src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/FlatToStandard/ColumnsMerger.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/FlatToStandard/ColumnsMergerSpec.php
add blanck thousand separator to avoid issue with large number containing decimal like 80,000.75
> RAC-1264: Using number_format whitout toushand separator specified will add one has comma in the value

- src/Akeneo/Category/front/src/configuration/ConfigurationProvider.tsx
- src/Akeneo/Category/front/src/feature/CategoriesApp.tsx
- src/Akeneo/Category/front/src/feature/legacy/README.md
- src/Akeneo/Category/front/src/feature/legacy/components/EditPermissionsForm.tsx
- src/Akeneo/Category/front/src/feature/legacy/components/EditPropertiesForm.tsx
- src/Akeneo/Category/front/src/feature/legacy/components/Style.tsx
- src/Akeneo/Category/front/src/feature/legacy/components/datagrids/DeleteCategoryModal.tsx
- src/Akeneo/Category/front/src/feature/legacy/components/index.ts
- src/Akeneo/Category/front/src/feature/legacy/components/providers/EditCategoryProvider.tsx
- src/Akeneo/Category/front/src/feature/legacy/components/providers/index.ts
- src/Akeneo/Category/front/src/feature/legacy/helpers/index.ts
- src/Akeneo/Category/front/src/feature/legacy/helpers/permissionsHelper.test.ts
- src/Akeneo/Category/front/src/feature/legacy/helpers/permissionsHelper.ts
- src/Akeneo/Category/front/src/feature/legacy/hooks/index.ts
- src/Akeneo/Category/front/src/feature/legacy/hooks/useCategory.ts
- src/Akeneo/Category/front/src/feature/legacy/hooks/useCountProductsBeforeDeleteCategory.ts
- src/Akeneo/Category/front/src/feature/legacy/hooks/useCountProductsByCategory.ts
- src/Akeneo/Category/front/src/feature/legacy/hooks/useDeleteCategory.ts
- src/Akeneo/Category/front/src/feature/legacy/hooks/useEditCategoryForm.ts
- src/Akeneo/Category/front/src/feature/legacy/infrastructure/index.ts
- src/Akeneo/Category/front/src/feature/legacy/infrastructure/removers/deleteCategory.ts
- src/Akeneo/Category/front/src/feature/legacy/infrastructure/removers/index.ts
- src/Akeneo/Category/front/src/feature/legacy/infrastructure/savers/index.ts
- src/Akeneo/Category/front/src/feature/legacy/infrastructure/savers/saveEditCategoryForm.ts
- src/Akeneo/Category/front/src/feature/legacy/models/Category.ts
- src/Akeneo/Category/front/src/feature/legacy/models/Tree.ts
- src/Akeneo/Category/front/src/feature/legacy/models/index.ts
- src/Akeneo/Category/front/src/feature/legacy/pages/HistoryPimView.tsx
- src/Akeneo/Category/front/src/feature/legacy/pages/LegacyCategoryEditPage.tsx
- src/Akeneo/Category/front/src/index.tsx
Created a legacy folder in front in the category bounded context, so that the edition of a category before the enriched category project is stable and untouched. The main legacy component is LegacyCategoryEditPage, all its local dependencies are copied into legacy so that we can freely modify the new CategoryEditPage.
the index.tsx does the switch between the two using the _enriched_category_ feature flag in the CategoryApp component.
> GRF-228 separated legacy category UI code from the enriched category stream and refactarization

- CHANGELOG-5.0.md
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/associations.js
The associations grid was not correctly initialized when the currently selected association type was quantified (meta was empty, thus preventing from correctly computing permissions in EE)
> PIM-10553: Fix initialization of the associations grid in product edit form

- CHANGELOG-5.0.md
- src/Akeneo/Pim/Structure/Bundle/Resources/config/model/doctrine/Attribute.orm.yml
- src/Akeneo/Tool/Bundle/MeasureBundle/Validation/Common/CodeValidator.php
- src/Akeneo/Tool/Bundle/MeasureBundle/tests/Acceptance/CreateMeasurementFamilyTest.php
- src/Akeneo/Tool/Bundle/MeasureBundle/tests/Acceptance/SaveMeasurementFamilyTest.php
- upgrades/schema/Version_5_0_20220801160000_modify_metric_family_and_default_metric_unit.php
- upgrades/test_schema/Version_5_0_20220801160000_modify_metric_family_and_default_metric_unit_Integration.php
Backport of [https://github.com/akeneo/pim-community-dev/pull/16052](https://github.com/akeneo/pim-community-dev/pull/16052).
[Issue](https://akeneo.atlassian.net/jira/software/c/projects/PIM/boards/9?modal=detail&selectedIssue=PIM-10556&quickFilter=651).
We cannot create measurement attribute if measurement family or unit code is too long, a limit is set to 30 chars max in database datatype of metric_family and default_metric_unit columns. This PR set this limit to 100 chars max (same as code and standard_unit columns in akeneo_measurement).
> PIM-10556: Fix cannot create a measurement attribute if measurement family or unit code is too long

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/ReadModel/ConnectorProduct.php
- tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/GetProductEndToEnd.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ReadModel/ConnectorProductSpec.php
Fixes an issue where attribute option labels were not displayed in the Get/List products endpoints, when the value in DB does not have the same case as the option code
TODO:
> PIM-10530: Fix case issue when querying products with attribute options

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/EntityWithAssociations/PersistTwoWayAssociationSubscriber.php
When publishing a product 2-way associated with a published product, we don't want the reverse association to be published (i.e we don't want the target published product to be updated)
> PIM-10572: Fix product publishing when associated to a published product with a 2-way association

- CHANGELOG.md
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/mass-edit/form/product/associate.js
Fixes a small regression introduced by #17416 : in the associate mass action screen there is no form data, and anyway we don't need to check that the user is owner (it's the job's role to check that)
> PIM-10569: Fix associate bulk action screen for quantified associations

- tests/back/Acceptance/User/InMemoryUserRepository.php
- tests/back/Acceptance/spec/User/InMemoryUserRepositorySpec.php
The [InMemory implem of this repository](https://github.com/akeneo/pim-community-dev/blob/master/tests/back/Acceptance/User/InMemoryUserRepository.php#L81-L84) does not implement the `findAll()` method but we need it in order to be able to test a subscriber.
> SP-223: Implement findAll method in InMemoryUserRepository

- src/Akeneo/Category/back/Infrastructure/EventSubscriber/InitCategoryDbSchemaSubscriber.php
- src/Akeneo/Category/back/Infrastructure/Symfony/DependencyInjection/AkeneoCategoryExtension.php
- src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/subscribers.yml
- upgrades/schema/Version_7_0_20220808143128_add_value_collection_to_category.php
Migration which add a column `value_collection` (json) in the table `pim_catalog_category`.
Tested in a Corabelux env (20,777 categories) : took 2783ms.
> GRF-122: Add JSON value collection field for the category in the database

- CHANGELOG.md
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/quantified-associations/components/QuantifiedAssociationRow.tsx
Fixes the parameter to use uuid for products.
> PIM-10574: Fix link to product page in quantified association row

- CHANGELOG.md
- src/Akeneo/Tool/Bundle/ConnectorBundle/Resources/config/readers.yml
- src/Akeneo/Tool/Component/Connector/Exception/InvalidYamlFileException.php
- src/Akeneo/Tool/Component/Connector/Reader/File/Yaml/Reader.php
- src/Akeneo/Tool/Component/Connector/spec/Reader/File/Yaml/ReaderSpec.php
In this PR: 
- I added a validation about the root level in YAML file. Before wet retrieve the first root level, now we search the expected root level. By doing it we can display an understandable error message to the user if root level is not found.
I also added the following check in order to do not having an SLA on this error :
- An error when the file is not found (like the other readers)
- An error if the row is not a row (an array)
> PIM-10548: Fix yaml reader does not display an error message when imported file does not contain the root level

- CHANGELOG.md
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/family/form/attributes/toolbar/add-select/attribute-group/select.js
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/add-select/select.js
Before fix, not all attribute groups were shown in the infinite scroll of attribute group selector in family edit form because empty family groups were not returned by the item fetcher, thus not returning as many options as results per page, which made the function think there were no more options. At the end, this caused the "more" condition to not be triggered.
The fix allows to filter the loaded items while preserving all the items found before filtering, making it possible for the function to know that there still are options to look for.
> PIM-10571: Fix infinite scroll of attribute group selector in family edit form

- CHANGELOG-5.0.md
- src/Akeneo/Pim/Structure/Component/Normalizer/ExternalApi/AttributeNormalizer.php
- tests/back/Pim/Structure/EndToEnd/AttributeGroup/ExternalApi/CreateAttributeGroupEndToEnd.php
- tests/back/Pim/Structure/Specification/Component/Normalizer/ExternalApi/AttributeNormalizerSpec.php
Fix attribute normalizer returning an empty array for empty group labels when it should return an empty object. 
> PIM-10512: Fix empty group labels format for attribute endpoints

- src/Akeneo/Platform/Bundle/ImportExportBundle/Normalizer/StepExecutionNormalizer.php
- tests/back/Platform/EndToEnd/ImportExport/InternalApi/GetJobExecutionEndToEnd.php
- tests/back/Platform/Specification/Bundle/ImportExportBundle/Normalizer/StepExecutionNormalizerSpec.php
**In this PR, I fixed the following error :** 
By checking the data before translate it
**When we have this error ?** 
When the user display a data_quality_insights_evaluations job this job is not visible in the process tracker but can be displayed through the URL
**Why we have this error ?** 
Because in this job the tasklet add as summary an array (https://github.com/akeneo/pim-community-dev/blob/d77dab1/src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Connector/Tasklet/EvaluateProductsAndProductModelsCriteriaTasklet.php#L59)
> RAC-1265: Fix error when user display the data_quality_insights_evaluations job

- src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/OptionsValueFactory.php
- src/Akeneo/Pim/Enrichment/Component/Product/Factory/ValueFactory.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Factory/Value/OptionsValueFactorySpec.php
The global value factory now accepts any array containing data (even an empty string); it's the role of each specific Value factory to check the data structure
> CPM-704: Fix Error 500 when trying to update multiselect value with an array containing empty string

- CHANGELOG-5.0.md
- src/Akeneo/Pim/Structure/Bundle/EventSubscriber/SaveFamilyVariantOnFamilyUpdateSubscriber.php
- src/Akeneo/Pim/Structure/Component/Model/Family.php
- src/Akeneo/Pim/Structure/Component/Model/FamilyInterface.php
- src/Akeneo/Pim/Structure/Component/Model/FamilyVariantInterface.php
- src/Akeneo/Pim/Structure/Component/Updater/FamilyUpdater.php
- tests/back/Pim/Structure/Specification/Bundle/EventSubscriber/SaveFamilyVariantOnFamilyUpdateSubscriberSpec.php
- tests/back/Pim/Structure/Specification/Component/Model/FamilySpec.php
- tests/back/Pim/Structure/Specification/Component/Updater/FamilyUpdaterSpec.php
- tests/legacy/features/pim/structure/family/remove_attribute_from_a_family.feature
Backport of this PR: https://github.com/akeneo/pim-community-dev/pull/17298
> PIM-10559: [Backport PIM-10478]: Disable compute_family_variant_structure_changes on familySave

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/datagrid/product.yml
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/datagrid/action/toggle-product-action.js
- src/Oro/Bundle/DataGridBundle/Extension/Action/Actions/AjaxAction.php
- src/Oro/Bundle/DataGridBundle/Extension/Action/Actions/DeleteAction.php
The delete and toggle status actions are only related to products but were both calculated in the datagrid for products and product models.
The two endpoints were excepting a correct uuids passed with the technical id so we had an error for product models.
The actions are now just overrided with the getLink function in order to handle uuids and ids
> PIM-10529: Fix links on product grid

- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/doctrine/Product/Product.orm.yml
- upgrades/schema/Version_7_0_20221808143128_remove_zdd_setidentifiernullable_from_pim_one_time_task_table.php
- upgrades/test_schema/Version_7_0_20220802151250_add_automation_column_in_job_instance_Integration.php
- upgrades/test_schema/Version_7_0_20221808143128_remove_zdd_setidentifiernullable_from_pim_one_time_task_table_Integration.php
We introduce:
- doctrine migration to remove the "zdd_SetProductIdentifierNullable" from the "pim_one_time_task" table
- Change the doctrine mapping to set the identifier nullable
Why ?
See [JIRA ticket](https://akeneo.atlassian.net/browse/CPM-692)
Consequences ?
The ZDD migration will be replayed on all SaaS instances which:
- should be fast for already migrated instances (not much to do anyway)
- should be fast for new instances (and if it's not it's ok since it's a ZDD migration)
> CPM-692: sf migration to force replaying ZDD migration

- components/catalogs/back/src/Infrastructure/Validation/ProductSelection/AttributeCriterionContainsValidLocaleValidator.php
- components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSelection/AttributeCriterion/AbstractAttributeCriterionTest.php
- components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSelection/AttributeCriterion/AttributeTextCriterionTest.php
It's not anymore an all-layers integration test.
Nonetheless, the test content is the same.
```
/**
* @dataProvider validDataProvider
*/
public function testItReturnsNoViolation(array $attribute, array $criterion): void
{
$this->createAttribute($attribute);
$violations = $this->validator->validate($criterion, new AttributeTextCriterion());
$this->assertEmpty($violations);
}
```
The symfony validator is still called, we are still testing that our bricks are behaving as expected.
The big difference is that queries called by the validators are mocked.
If I submit a valid criterion, everything's green, if I submit an invalid one, everything's red and the test proves it.
The main benefit is, of course, performances. (measured on my machine, …
> CXP-1245: rewrite validation test with mocks on queries

- composer.json
- composer.lock
In lcobucci/jwt 4.2.0, SHA256 with 1024bits keys are not supported anymore and throws an exception.
By fixing the lib version to 4.1.5, our current implementation is still working and will give us time to upgrade correctly to newer versions.
> OCT-107: downgrade to lcobucci 4.1.5

- components/catalogs/front/src/index.tsx
- front-packages/shared/src/microfrontend/DangerousMicrofrontendAutomaticAuthenticator.ts
- front-packages/shared/src/microfrontend/index.ts
In our microfrontends, the PIM API is proxied.
If you don't have an active session with the correct cookies on the PIM (localhost:8080), the microfronted calls to the PIM API are rejected.
This PR introduce a dirty solution to automatically authenticate and reload the page when this error is detected, that can be enabled with 2 lines in the `index.ts` of a create-react-app microfrontend.
```
import {DangerousMicrofrontendAutomaticAuthenticator} from '@akeneo-pim-community/shared';
DangerousMicrofrontendAutomaticAuthenticator.enable('admin', 'admin');
```
https://user-images.githubusercontent.com/1421130/185653409-e92ed2f3-b290-45d6-91a0-44c29412b897.mp4
> OCT-89: Authenticate automatically in a microfrontend

- src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/UserManagement/UpsertRunningUser.php
- src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/services.yml
- src/Akeneo/Platform/Bundle/ImportExportBundle/Test/.php_cd.php
- src/Akeneo/Platform/Bundle/InstallerBundle/Resources/config/fixture_loader.yml
- src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/model/doctrine/JobInstance.orm.yml
- src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/updaters.yml
- src/Akeneo/Tool/Bundle/ConnectorBundle/Resources/config/security.yml
- src/Akeneo/Tool/Component/Batch/Model/JobInstance.php
- src/Akeneo/Tool/Component/Batch/Updater/JobInstanceUpdater.php
- src/Akeneo/Tool/Component/Batch/spec/Updater/JobInstanceUpdaterSpec.php
- src/Akeneo/UserManagement/Bundle/Resources/config/providers.yml
- src/Akeneo/UserManagement/Bundle/Resources/translations/validators.en_US.yml
- src/Akeneo/UserManagement/Bundle/Security/JobUserProvider.php
- src/Akeneo/UserManagement/Bundle/Security/UserApiProvider.php
- src/Akeneo/UserManagement/Bundle/Security/UserProvider.php
- src/Akeneo/UserManagement/Bundle/Validator/Constraints/CreateUser.php
- src/Akeneo/UserManagement/Bundle/Validator/Constraints/CreateUserValidator.php
- src/Akeneo/UserManagement/Component/Repository/RoleRepositoryInterface.php
- tests/back/Platform/Specification/Bundle/ImportExportBundle/Infrastructure/UserManagement/UpsertRunningUserSpec.php
- tests/back/UserManagement/Specification/Bundle/Security/JobUserProviderSpec.php
- tests/back/UserManagement/Specification/Bundle/Security/UserProviderSpec.php
- tests/back/UserManagement/Specification/Bundle/Validator/Constraints/CreateUserValidatorSpec.php
Why we added `changeTrackingPolicy: DEFERRED_EXPLICIT ` ? 
Because when we persist the user then flush, the job instance is saved. Problem is that the job instance is not validated yet. As by default the changeTrackingPolicy is DEFERRED_IMPLICIT doctrine save the entity as he detect that there is a change in the entity. 
> RAB-927: Upsert running user on job save

- components/catalogs/front/src/FakeCatalogEditContainer.tsx
- components/catalogs/front/src/components/CatalogEdit/hooks/useCatalogForm.ts
- components/catalogs/front/src/components/CatalogEdit/hooks/useCatalogForm.unit.ts
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
- src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApp/Catalog/ConnectedAppCatalogContainer.tsx
- src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApp/Catalog/ConnectAppCatalogContainer.test.tsx
- Catalog save returns a boolean that indicates save success
- Added notification inside connectivity to notify when the catalog is saved
- Updated the fake catalog edit container to have some feedback on save
Need feedback on: If catalogs cannot be saved due to user error notification is a warning
> CXP-1253: Added notifications to user when  catalog is saved

- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/view/base-interface.ts
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/view/base.ts
- src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/legacy-bridge/src/tools/validator.ts
In this PR, I fixed some error that typescript detect when we check the backbone bridge.
- triggerExtensions has now two parameters instead of none and using the magic argument `argument`
- position is now initialized as typescript detect it as not used
> RAB-974: Fix typescript error

- CHANGELOG.md
- src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/src/components/panel/AnnouncementList.tsx
- src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/src/components/panel/Panel.tsx
- src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/tests/front/unit/components/panel/AnnouncementList.unit.tsx
- src/Akeneo/Platform/Bundle/CommunicationChannelBundle/front/tests/front/unit/components/panel/Panel.unit.tsx
The component `AnnouncementList` was always mounted, even when the panel is never opened.
It was automatically fetching the list of announcements, which is actually quit slow (~3s).
I've deferred its mount only when opened.
I've moved the `handleHasNewAnnouncements` to the parent component to still have the visual indicator if there is new annoucements.
> PIM-10607: Only request /announcements when the panel is open

- components/catalogs/back/tests/Integration/IntegrationTestCase.php
- tests/back/Integration/IntegrationTestsBundle/Loader/FixturesLoaderInterface.php
FixturesLoader has the method `purge()` that we started using in a test only since this morning.
It was not in the interface, so it broke the EE implementation of FixturesLoaderInterface.
This PR is there to remedy this problem.
Also, when attributes are created without the group "other" in EE, we have errors with permissions.
> OCT-114: adds purge() to FixturesLoaderInterface

- src/Akeneo/UserManagement/Bundle/Controller/Rest/UserController.php
- src/Akeneo/UserManagement/Bundle/Doctrine/ORM/Repository/GroupRepository.php
- src/Akeneo/UserManagement/Component/Normalizer/UserNormalizer.php
- src/Akeneo/UserManagement/Component/Repository/GroupRepositoryInterface.php
- src/Akeneo/UserManagement/Component/Updater/UserUpdater.php
- src/Akeneo/UserManagement/back/Application/Handler/UpsertUserHandler.php
- src/Akeneo/UserManagement/back/ServiceApi/User/UpsertUserCommand.php
- src/Akeneo/UserManagement/back/tests/Integration/ServiceApi/User/UpsertUserHandlerIntegration.php
- tests/back/Acceptance/User/InMemoryGroupRepository.php
- tests/back/UserManagement/Specification/Component/Normalizer/UserNormalizerSpec.php
- tests/back/UserManagement/Specification/Component/Updater/UserUpdaterSpec.php
- add a way to retrieve all visible user groups (all groups but the system "All" group)
- change the way we upsert user, it's now possible to give `group_ids` instead of group labels (as user group label can be modified later on)
> RAB-1003: Save ids instead of username & labels in automation parameters

- CHANGELOG.md
- src/Akeneo/Pim/Structure/Bundle/EventSubscriber/ComputeFamilyVariantStructureChangesSubscriber.php
- src/Akeneo/Pim/Structure/Bundle/EventSubscriber/SaveFamilyVariantOnFamilyUpdateSubscriber.php
- src/Akeneo/Pim/Structure/Component/Model/Family.php
- src/Akeneo/Pim/Structure/Component/Model/FamilyVariant.php
- tests/back/Pim/Structure/Specification/Bundle/EventSubscriber/SaveFamilyVariantOnFamilyUpdateSubscriberSpec.php
The job computeFamilyVariantStructureChange was not launched when an attribute was removed on the family level.
The job is created only when there has been changed on the family variant attributes or axes. We now add one event when an attribute is removed from the family
> PIM-10606: Fix computeFamilyVariantStructureChange on attribute removal

- src/Akeneo/Tool/Bundle/VersioningBundle/Builder/VersionBuilder.php
In the error logs, there are null bytes in $old property, so we replace null bytes by empty string to prevent errors on `DateTimeImmutable::createFromFormat`
[Related logs](https://app.datadoghq.eu/logs?query=project%3Aakecld-saas-prod%20%40context.akeneo_context%3A%28Enrichment%20OR%20Structure%20OR%20Permissions%20OR%20%22Rule%20Engine%22%29%20status%3A%28error%20OR%20critical%29%20-%40context.exception.message%3A%2AHY000%2A%20-%40context.exception.message%3A%2Ano_shard_available_action_exception%2A&agg_q=%40context.exception.message&agg_t=count&cols=host%2Cservice&index=%2A&messageDisplay=inline&panel=%7B%22timeRange%22%3A%7B%22from%22%3A1661267574801%2C%22to%22%3A1661872374801%2C%22live%22%3Atrue%7D%2C%22queryString%22%3A%22%28projec …
> CPM-717: Replace null bytes by empty strings in VersionBuilder

- CHANGELOG-5.0.md
- src/Akeneo/Platform/Bundle/ImportExportBundle/Controller/InternalApi/JobExecutionController.php
- src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/controllers.yml
Following this [ticket](https://akeneo.atlassian.net/browse/PIM-10591?atlOrigin=eyJpIjoiNGFhOTIzYTViMWY3NGY1NWIwY2M4MGYyY2VhNGY0YmIiLCJwIjoiaiJ9) and this [discussion](https://akeneo.slack.com/archives/GQ839T8QM/p1661332863893139), we decided to disable download log action when a job is running (same behavior on 6.0/master).
> PIM-10591: Fix download log should not be possible when job is running

- src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/CreateProductByUuidController.php
- src/Akeneo/Pim/Enrichment/Product/back/API/Command/UpsertProductCommand.php
- src/Akeneo/Pim/Enrichment/Product/back/API/ValueObject/ProductIdentifier.php
- src/Akeneo/Pim/Enrichment/Product/back/API/ValueObject/ProductUuid.php
- src/Akeneo/Pim/Enrichment/Product/back/Application/UpsertProductHandler.php
- src/Akeneo/Pim/Enrichment/Product/back/Domain/Query/GetCategoryCodes.php
- src/Akeneo/Pim/Enrichment/Product/back/Domain/Query/GetNonViewableCategoryCodes.php
- src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Query/GetNonViewableCategoryCodes.php
- src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Query/SqlGetCategoryCodes.php
- src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Symfony/Resources/config/validation/product_commands.yml
- src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Symfony/Resources/config/validators.yml
- src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Validation/IsUserOwnerOfTheProductValidator.php
- src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Validation/ShouldStayOwnerOfTheProductValidator.php
- src/Akeneo/Pim/Enrichment/Product/back/Test/Acceptance/InMemory/InMemoryGetCategoryCodes.php
- src/Akeneo/Pim/Enrichment/Product/back/Test/Acceptance/InMemory/InMemoryGetProductUuids.php
- src/Akeneo/Pim/Enrichment/Product/back/Test/Acceptance/Resources/config/services.yml
- src/Akeneo/Pim/Enrichment/Product/back/Test/Acceptance/Specification/InMemory/InMemoryGetCategoryCodesSpec.php
- src/Akeneo/Pim/Enrichment/Product/back/Test/Acceptance/Specification/InMemory/InMemoryGetProductUuidsSpec.php
- src/Akeneo/Pim/Enrichment/Product/back/Test/Feature/upsert.feature
- src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/EnrichmentProductTestCase.php
- src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductIntegration.php
- src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductWithPermissionIntegration.php
- src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Query/SqlGetCategoryCodesIntegration.php
- src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/API/Command/UpsertProductCommandSpec.php
- src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Application/Applier/SetCategoriesApplierSpec.php
- src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Application/UpsertProductHandlerSpec.php
- src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Infrastructure/Query/GetNonViewableCategoryCodesSpec.php
- src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Infrastructure/Validation/IsUserOwnerOfTheProductValidatorSpec.php
- src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Infrastructure/Validation/ShouldStayOwnerOfTheProductValidatorSpec.php
- UpsertProductCommand constructor is now private
- Methods to create a command:
-> createFromCollection (legacy, now deprecated, kept to minimize BC break)
-> createWithUuid
-> createWithIdentifier
-> createWithoutUuidNorIdentifier
> CPM-698: Add uuid in UpsertProductCommand

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml
- src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ElasticsearchProjection/GetElasticsearchProductModelProjection.php
- src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ElasticsearchProjection/GetElasticsearchProductProjection.php
- tests/back/Pim/Enrichment/Integration/Storage/Sql/ElasticsearchProjection/GetElasticsearchProductProjectionIntegration.php
When a user launch a product/product model mass delete and an attribute delete in a same time, the "Cleaning removed attribute values" will fail due to an exception thrown inside queries used to fetch ES product/product model projection.
The fix is simply to make those queries more safe and replace the throw by a logged warning. We don't need to throw an exception in those queries.
> PIM-10598: Fix "Cleaning removed attribute values" job failing if attribute is deleted during mass deletion of products

- src/Akeneo/Pim/Enrichment/Product/back/Domain/Query/GetProductUuids.php
- src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Query/Cache/LRUCacheGetProductUuids.php
- src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Query/SqlGetProductUuids.php
- src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Validation/ShouldStayOwnerOfTheProductValidator.php
- src/Akeneo/Pim/Enrichment/Product/back/Test/Acceptance/InMemory/InMemoryGetProductUuids.php
- src/Akeneo/Pim/Enrichment/Product/back/Test/Acceptance/Specification/InMemory/InMemoryGetProductUuidsSpec.php
- src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/EnrichmentProductTestCase.php
- src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductWithPermissionIntegration.php
- src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Query/GetProductUuidsIntegration.php
- src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Infrastructure/Validation/ShouldStayOwnerOfTheProductValidatorSpec.php
Allow creating a product without owning it via the service API. It essentially fixes this test: https://github.com/akeneo/pim-community-dev/pull/17847/files#diff-40fbe65847c0b0ff6966625232a49b54d2d8e03a6f343ce1f18d571bd421dbf8
> CPM-716: Fix UpsertProductCommand validation on permissions

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/FlatTranslator/AttributeValue/MultiSelectTranslator.php
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/FlatTranslator/AttributeValue/SimpleSelectTranslator.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/FlatTranslator/AttributeValue/MultiSelectTranslatorSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/FlatTranslator/AttributeValue/SimpleSelectTranslatorSpec.php
- be case insensitive when retrieving option labels to mimic MySQL behavior
> PIM-10620: Fix export product options values with label to be case insensitive with codes

- .circleci/config.yml
- .circleci/config/parameters.yml
- .circleci/jobs/features/catalogs/test_back_catalogs_ce.yml
- .circleci/jobs/features/catalogs/test_back_catalogs_ee.yml
**Introduction**
Running all integration tests on the existing migrations adds around **5min** to the CI workflow.
When we initially configured our workflow, we decided that we were going to run those tests only on demand.
It worked well for some time, but last week, I merged a broken migration without running those tests because I forgot to launch them. :boom: 
We need to prevent it from happening again.
But instead of running those tests in all workflows, we agreed it was time to implement `path-filtering`.
When using `path-filtering`, we can rely on the `git diff` between the latest commit and **master** to find which files are affected by the PR.
With the following mapping:
```
upgrades/.* run-database-tests true
```
Any PR …
> OCT-117: Automatically launch database tests only when a migration is added

- components/catalogs/Makefile
- components/catalogs/back/.php_cd.php
- composer.json
- composer.lock
- make-file/category.mk
- make-file/channel.mk
- make-file/communication-channel.mk
- make-file/connectivity-connection.mk
- make-file/data-quality-insights.mk
- make-file/enrichment-product.mk
- make-file/enrichment.mk
- make-file/import-export.mk
- make-file/job.mk
- make-file/structure.mk
- make-file/test.mk
- make-file/user-management.mk
- src/Akeneo/Connectivity/Connection/back/tests/.php_cd.php
- src/Akeneo/Pim/Enrichment/.php_cd.php
- src/Akeneo/Pim/Enrichment/Product/back/Test/.php_cd.php
- src/Akeneo/Platform/Bundle/ImportExportBundle/Test/.php_cd.php
- src/Akeneo/Platform/Job/back/tests/.php_cd.php
- src/Akeneo/UserManagement/.php_cd.php
- upgrades/.php_cd.php
**Unused coupling ?**
When a developer adds a dependency in a namespace, he have to add it in a dependency list.
A big job was done to plan how to remove (or decrease) these dependencies.
The issue is that the already-fixed dependencies are not always removed from the dependency list.
Having this dependency add some dirt and does not help us on focusing on a removal of a dependency.
This PR adds a step in the coupling detector step, to ensure there are no unused dependency on any context.
This PR
- Avoid to list all directories except "Test" one on Enrichment one
- Adds a step to check unused coupling
- Removes unused coupling
> CPM-522: Fix coupling detector

- src/Akeneo/Pim/Structure/Bundle/Query/InternalApi/Family/DefaultSqlGetRequiredAttributesMasks.php
- src/Akeneo/Pim/Structure/Bundle/Resources/config/validators.yml
- src/Akeneo/Pim/Structure/Component/Normalizer/InternalApi/FamilyNormalizer.php
- src/Akeneo/Pim/Structure/Component/Updater/FamilyUpdater.php
- src/Akeneo/Pim/Structure/Component/Validator/Constraints/FamilyRequirementsValidator.php
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/family/form/attributes/attributes.js
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/family/tab/attributes/attributes.html
- tests/back/Pim/Structure/EndToEnd/Family/ExternalApi/PartialUpdateFamilyEndToEnd.php
- tests/back/Pim/Structure/Integration/Family/ImportFamilyIntegration.php
- tests/back/Pim/Structure/Integration/Query/InternalApi/Family/DefaultSqlGetRequiredAttributesMasksIntegration.php
- tests/back/Pim/Structure/Specification/Component/Updater/FamilyUpdaterSpec.php
- tests/back/Pim/Structure/Specification/Component/Validator/Constraints/FamilyRequirementsValidatorSpec.php
This PR aims to enable the configuration of sku for family attribute requirements.
It can now be enabled or disabled for completeness
> CPM-633: Enable identifier configuration for family attribute requirements

- src/Akeneo/Category/front/src/FakePIM.tsx
- src/Akeneo/Category/front/src/index.tsx
When developping for enriched category on the standalone microfrontend, the configuration panel had to be displayed before feature flags are correclty taken in account. 
This was annoying and now fixed.
> GRF-328 fix DX issue within category microfrontend in dev mode

- src/Akeneo/UserManagement/Component/Normalizer/UserNormalizer.php
The scheduling form was crashing due to the fact that the User Normalizer was keeping indices when filtering and then sending the value as an object.
Before:
After:
> RAB-1039: Fix user normalizer sending visible groups ids as object

- CHANGELOG.md
- upgrades/schema/Version_7_0_20220921104755_update_job_instance_parameter_user_to_notify_for_jobs.php
- upgrades/test_schema/Version_7_0_20220921104755_update_job_instance_parameter_user_to_notify_for_jobs_Integration.php
I added a db migration to migrate user_to_notify job parameter.
ZDD compliancy : 
As we can see on this screenshot, the maximum lines for job instances table is 1780. We fetch them to update a value inside each lines so it should be quick and ZDD compliant.
> PIM-10648: Migrate all job conf which contains old user_to_notify param

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/FlatTranslator/AttributeValue/MultiSelectTranslator.php
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/FlatTranslator/AttributeValue/SimpleSelectTranslator.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/FlatTranslator/AttributeValue/MultiSelectTranslatorSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/FlatTranslator/AttributeValue/SimpleSelectTranslatorSpec.php
In this PR, I fixed the fact that code is returned when there is an uppercase in the attribute code when exporting with label. The option key generated is always in lowercase that why we can't find the option label
> PIM-10646: Fix export with label from a select attribute containing uppercase in its code exports code and not labels

- src/Akeneo/Tool/Bundle/ElasticsearchBundle/Client.php
- upgrades/schema/Version_7_0_20220920000000_deduplicate_elasticsearch_indices.php
- upgrades/test_schema/Version_7_0_20220920000000_deduplicate_elasticsearch_indices_Integration.php
`Client::createIndex` did not prevent the PIM from creating multiple indices with the same alias.
We have, on some customers environments, the following error:
```
{"type":"illegal_argument_exception","reason":"no write index is defined for alias [akeneo_connectivity_connection_events_api_debug]. The write index may be explicitly disabled using is_write_index=false or the alias points to multiple indices without one being designated as a write index"}
```
In this PR:
1) I prevent createIndex to duplicate indices
2) I add a migration that will remove duplicated indices
> OCT-128: deduplicate ES indices

- src/Akeneo/Pim/Enrichment/Bundle/Command/MigrateToUuid/Context.php
- src/Akeneo/Pim/Enrichment/Bundle/Command/MigrateToUuid/MigrateToUuidAddConstraints.php
- src/Akeneo/Pim/Enrichment/Bundle/Command/MigrateToUuid/MigrateToUuidCommand.php
- src/Akeneo/Pim/Enrichment/Bundle/Command/MigrateToUuid/MigrateToUuidCreateIndexes.php
- src/Akeneo/Pim/Enrichment/Bundle/Command/MigrateToUuid/MigrateToUuidSetNotNullableUuidColumns.php
- upgrades/schema/Version_7_0_20220429131804_execute_uuid_migration.php
The UUID migration was designed to be SAAS-compliant, so every ALTER TABLE methods use ALGORITHM INPLACE and LOCK NONE.
Today, some users want to run this migration with the server down.
We hope to speed up the migration by removing this inplace algorithm.
We added a new option '--lock-tables', set to true on the doctrine migrations.
> [migration uuid] Add option to remove the algorithm inplace

- CHANGELOG.md
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/fetcher/attribute-fetcher.js
Actually when the user have move than 1000 attribute in the product export attribute selector the filtering does not work correctly => attribute are not part of the requested attribute group for example
**Why we have this problem ?** 
Because there is a FPM configuration named `max_input_vars` filled with the environment variable PHP_CONF_MAX_INPUT_VARS. In production the value of this configuration is 1000. So FPM silently truncate the inputs to 1000.
**How we resolve it ?**
Instead of updating the `max_input_vars` and having another problem after I decided to send search query into json content, to do this we need to use `$.ajax` instead of `$.post`.
> PIM-10649: Fix wrong attributes displayed when selecting attribute group in export profile filter when there is too much attribute selected

- src/Akeneo/Connectivity/Connection/back/tests/CatalogBuilder/Enrichment/ProductLoader.php
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Webhook/ConsumeProductEventEndToEnd.php
- src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/ProductController.php
- src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/ExternalApi/ConnectorProductNormalizer.php
- tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/AbstractProductTestCase.php
- tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/GetProductEndToEnd.php
- tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/ListProductWithCompletenessEndToEnd.php
- tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/SuccessListProductEndToEnd.php
- tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/SuccessListVariantProductDeltaEndToEnd.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/ExternalApi/ConnectorProductNormalizerSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Webhook/ProductCreatedAndUpdatedEventDataBuilderSpec.php
Add uuid to the response of `api/rest/v1/products` endpoints
> CPM-695: Add uuid to old product endpoints

- src/Akeneo/Platform/Bundle/ImportExportBundle/Command/PurgeJobExecutionCommand.php
- src/Akeneo/Platform/Bundle/ImportExportBundle/Job/PurgeJobExecutions.php
- src/Akeneo/Platform/Bundle/ImportExportBundle/Purge/PurgeJobExecution.php
- src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/services.yml
- src/Akeneo/Tool/Bundle/BatchBundle/Persistence/Sql/DeleteJobExecution.php
- src/Akeneo/Tool/Bundle/BatchBundle/Persistence/Sql/GetJobExecutionIds.php
- src/Akeneo/Tool/Bundle/BatchBundle/Storage/DeleteJobExecutionLogs.php
When running the purge job execution, we first create a job execution.
If we set the purge limit to 0, all executions are purged, included the purge itself.
At the end of the job, we try to update the execution status of this purge, but the execution does not exist anymore.
When running the purge as a job, we will have a new hard limit to one hour and we will not purge job executions of the last hour.
But we  will keep the possibility to purge all with a CLI command. Do do that, the CLI command will not launch a job anymore, but use the purger directly.
> PH-268: Allow to purge  job executions older than 1 hour

- components/catalogs/back/.php_cd.php
In back Infrastructure, we would like to have a clear view of what is coupled for a necessity (Anti Corruption Layer) vs. what is coupled because we can't do some other way for now.
The PHP coupling detector is a simple tool and does not allow to have complex rules (e.g. override by sub-directories). So as a quick win, we re-organized the coupling and add some comments on which ones should be removed when ServiceApi of other contexts will be available.
> OCT-116: reorganize coupling in Infrastructure to have a better view

- src/Akeneo/Platform/Bundle/NotificationBundle/EventSubscriber/JobExecutionNotifier.php
- tests/back/Platform/Specification/Bundle/NotificationBundle/EventSubscriber/JobExecutionNotifierSpec.php
Following, `user_to_notify` migration, we add this falback for pending jobs. We can remove it now because migration is done and pending jobs are completed.
> RAB-1046: Remove fallback to user_to_notify

- src/Akeneo/Pim/Enrichment/Bundle/Controller/Ui/FileController.php
Fix a datadog error log
The exception is 
```
The mime type of file 4/0/6/6/xxxx.eps must be image/xxx or application/pdf, got application/postscript.
```
The entry point is used to show image. As there is an exception on the filter, we added a new catch.
> [fix-datadog] Fix FileController Exception

- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Marketplace/services.yml
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Marketplace/Controller/Internal/GetWebMarketplaceUrlEndToEnd.php
There are now 2 separated hosts for the app store:
- website: https://apps.akeneo.com
- api: https://api.apps.akeneo.cloud
> OCT-126: Broken link to the marketplace in the PIM app store

- src/Akeneo/Tool/Bundle/BatchBundle/JobExecution/CreateJobExecutionHandler.php
- src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/services.yml
- src/Akeneo/Tool/Bundle/BatchQueueBundle/Resources/config/services.yml
- src/Akeneo/Tool/Component/Batch/Exception/InvalidJobException.php
- src/Akeneo/Tool/Component/BatchQueue/Queue/PublishJobToQueue.php
- src/Akeneo/Tool/Component/BatchQueue/spec/Queue/PublishJobToQueueSpec.php
In this PR, I edited `CreateJobExecutionHandler` to be able to call it with a `JobInstance` already fetched and I added job validation inside it. I removed all logic from `PublishJobToQueue` which is duplicated in `CreateJobExecutionHandler`.
> RAB-1016: Use CreateJobExecutionHandler in PublishJobToQueue

- components/catalogs/back/.php_cd.php
- components/catalogs/back/src/Infrastructure/Symfony/Resources/meta-schemas/product-0.0.1.json
- components/catalogs/back/src/Infrastructure/Symfony/Resources/schemas/product-0.0.1.json
- components/catalogs/back/src/Infrastructure/Validation/ProductSchema.php
- components/catalogs/back/src/Infrastructure/Validation/ProductSchemaValidator.php
- components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchemaValidatorTest.php
- composer.json
- composer.lock
- src/Akeneo/Channel/back/Infrastructure/Component/Repository/CurrencyRepositoryInterface.php
**Why a new dependency ?**
The current JSON Schema library we use in the PIM stopped updating the spec at the Draft-4. It does not support all the features we have in the meta schema.
https://github.com/justinrainbow/json-schema/issues/658 :tada: 
2 new alternatives emerged in the community, and after trying both, I went with `opis/json-schema` because the API is similar and it supports `draft-2020-12, draft-2019-09, draft-07 and draft-06`.
**yes**, we need an ADR.
> CXP-1300: Adds first product meta schema

- upgrades/test_schema/ExecuteMigrationTrait.php
When an error occurred during a migration test the error displayed do not show the error message it display 
(https://app.circleci.com/pipelines/github/akeneo/pim-enterprise-dev/80249/workflows/2df6ab9d-145b-4b77-ac5e-ce0937432d93/jobs/515176) :
```
This migration is irreversible and cannot be reverted .....
```
Because the output is not cleared after the migration down test. In this PR, i just clear the output before launching migration up
> Fix error during migration test does not display revelant message

- tests/back/Integration/TestCase.php
This PR allows you to run integration tests without using the cache container.
It can be useful when working on services DI definition by launching the integration test. Without this PR, you have to clear the cache each time you modify the DI, which is a real pain... :cry: 
You can activate the debug several ways:
By adding the env var in the Docker command line:
```bash
APP_ENV=test docker-compose run --rm -e APP_DEBUG=1 php vendor/bin/phpunit src/Akeneo/..../MyTestIntegration.php
```
Or by adding the APP_DEBUG in a local test env file named `.env.test.local`
> Use APP_DEBUG env var for test Kernel

- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Webhook/commands.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/Command/SendBusinessEventToWebhooks.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/EventsApiDebug/Command/PurgeEventsApiLogsCommand.php
This 2 commands are launched by kubes before the database & ES are ready.
I'm downgrading the error level from critical to warning.
Then, in datadog, we will dedicate a new monitoring that will notify us if the amount of warnings is too high. (we will basically ignore it if this error happens less than 10 times a day, for example)
> OCT-149: catch unavailable mysql or ES errors and log warnings

- components/catalogs/back/src/Application/Persistence/Catalog/GetCatalogQueryInterface.php
- components/catalogs/back/src/Domain/Catalog.php
- components/catalogs/back/src/Infrastructure/Persistence/Catalog/GetCatalogQuery.php
- components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/GetCatalogQueryTest.php
Having query interfaces in Domain is a reasonable option.
But I think this is not the way to go for us.
- We already have all persistence interfaces in Application/Persistence. => As usual, if we put similar patterns in different directories without an obvious explanation on the case-by-case situation, it doesn't scale well. How do you guess which query belong to Domain and the other to Application ? How do you trace the line ?
- We cannot autowire interfaces that are in Domain. The Domain directory is excluded on purpose https://github.com/akeneo/pim-community-dev/blob/master/components/catalogs/back/src/Infrastructure/Symfony/Resources/config/services.yml#L17 => Why ? If you don't, Symfony tries to convert all classes in it into …
> CXP-1313: Move Catalog DTO & QueryInterface

- CHANGELOG-6.0.md
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/FlatTranslator/AttributeValue/MultiSelectTranslator.php
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/FlatTranslator/AttributeValue/SimpleSelectTranslator.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/FlatTranslator/AttributeValue/MultiSelectTranslatorSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/FlatTranslator/AttributeValue/SimpleSelectTranslatorSpec.php
Backport https://github.com/akeneo/pim-community-dev/pull/17972
> PIM-10652: [Backport PIM-10646] Fix export with label from a select attribute containing uppercase in its code exports code and not labels

- src/Akeneo/Pim/Structure/Component/Model/AttributeOption.php
- src/Akeneo/Pim/Structure/Component/Model/AttributeOptionInterface.php
- tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/AttributeOption/SetAttributeOptionSortOrderSubscriberSpec.php
- tests/back/Pim/Structure/Specification/Component/Manager/AttributeOptionsSorterSpec.php
- tests/back/Pim/Structure/Specification/Component/Normalizer/Standard/AttributeOptionNormalizerSpec.php
Started to fix this incorrect test: https://github.com/akeneo/pim-community-dev/blob/master/src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/AttributeOption/SetAttributeOptionSortOrderSubscriber.php#L88
`AttributeOptionInterface::getSortOrder()` was typed `int` strict [in phpDoc](https://github.com/akeneo/pim-community-dev/blob/master/src/Akeneo/Pim/Structure/Component/Model/AttributeOptionInterface.php#L84) when it is in fact nullable
I'm typing all the stuff by the way...
> PH-276: Fix AttributeOptionInterface typing

- src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Field/UuidFilter.php
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/query_builders.yml
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/Validator/ValidateProperties.php
- tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/SuccessListProductEndToEnd.php
- tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/SuccessListProductsWithUuidEndToEnd.php
- tests/back/Pim/Enrichment/Integration/PQB/Filter/Field/Product/UuidFilterIntegration.php
- tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Filter/Field/UuidFilterSpec.php
Adds a filter on product uuids, usable in the external API. The filter only accepts the "IN" operator
> CPM-754: Add Uuid filter in list products endpoints

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/ExternalApi/ConnectorProductNormalizer.php
- src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/ExternalApi/ConnectorProductWithUuidNormalizer.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/ExternalApi/ConnectorProductNormalizerSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/ExternalApi/ConnectorProductWithUuidNormalizerSpec.php
Fixes the format of empty completenesses (for a product without family) in the external API (it is actually an array, and not an object)
> PIM-10655: Fix format of empty completeness in external API

- src/Akeneo/Tool/Bundle/MeasureBundle/Controller/ExternalApi/JsonSchema/MeasurementFamilyCommonStructureValidator.php
- src/Akeneo/Tool/Bundle/MeasureBundle/Controller/ExternalApi/JsonSchema/MeasurementFamilyListValidator.php
- src/Akeneo/Tool/Bundle/MeasureBundle/Controller/ExternalApi/JsonSchema/MeasurementFamilyValidator.php
- src/Akeneo/Tool/Bundle/MeasureBundle/Controller/ExternalApi/JsonSchemaErrorsFormatter.php
- src/Akeneo/Tool/Bundle/MeasureBundle/spec/Controller/ExternalApi/JsonSchema/MeasurementFamilyListValidatorSpec.php
- src/Akeneo/Tool/Bundle/MeasureBundle/spec/Controller/ExternalApi/JsonSchema/MeasurementFamilyValidatorSpec.php
- src/Akeneo/Tool/Bundle/MeasureBundle/spec/Controller/ExternalApi/JsonSchemaErrorsFormatterSpec.php
- src/Akeneo/Tool/Bundle/MeasureBundle/tests/EndToEnd/ExternalApi/SaveMeasurementFamiliesActionEndToEnd.php
We added the new `opis/json-schema` library to validate JSON-schema because `justinrainbow/json-schema` is nor up-to-date neither maintained anymore.
This PR aims to migrate the use of the old one to the new one in `MeasureBundle`. 
There are some changes about error formatting but to minimize them and avoid BC breaks in the external API, we convert `opis` property path syntax to the `justinrainbow` one.
> OCT-136: Migrate from `justinrainbow/json-schema` to `opis/json-schema` the MeasureBundle

- composer.json
`Akeneo\\Test\\Pim\\Automation\\IdentifierGenerator\\` is duplicated in composer.json's autoload-dev, this PR removes it
> Remove duplicated entry in composer.json's autoload-dev

- components/catalogs/back/src/Infrastructure/Persistence/Catalog/Product/GetProductIdentifiersQuery.php
- components/catalogs/back/src/Infrastructure/Persistence/Catalog/Product/GetProductUuidsQuery.php
- components/catalogs/back/src/Infrastructure/TemporaryEnrichmentBridge/SearchAfterSizeUuidResultCursorFactory.php
- components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/GetProductsActionTest.php
- components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/Product/GetProductUuidsQueryTest.php
- components/catalogs/back/tests/Integration/IntegrationTestCase.php
In EE, the order of product UUIDs is not preserved by the query `FetchUserRightsOnProduct`. We had a list ordered by identifier that was suddenly ordered by UUID and the search_after was broken.
see https://github.com/akeneo/pim-enterprise-dev/pull/15212 for the fix on the query.
On top of fixing the issue in EE, I've also changed our ordering from `identifier` to `UUID` since `identifier` will change in the future.
To make tests on this easier, I've added the possibility to create products with UUIDs in the integration tests.
I've updated some of our tests to be more resilient.
> OCT-155: order catalog products by uuid

- src/Akeneo/Connectivity/Connection/back/Application/Webhook/WebhookEventBuilder.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/EventSubscriber/AccessDeniedForRevokedAppTokenEventSubscriber.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/EventSubscriber/GroupAllIsRemovedFromUsersUsedByAppsOnUpdateEventSubscriber.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Install/InstallSubscriber.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Normalizer/ViolationListNormalizer.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Audit/Install/InstallSubscriber.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Marketplace/Controller/Internal/GetAllAppsAction.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Marketplace/Controller/Internal/GetAllExtensionsAction.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Marketplace/Controller/Internal/GetWebMarketplaceUrlAction.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Marketplace/Install/InstallSubscriber.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/EventsApiDebug/Job/PurgeEventsApiLogs.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/Install/InstallSubscriber.php
- src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/Command/CreateConnectedAppWithAuthorizationHandlerIntegration.php
- src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/Install/AddAclToRolesIntegration.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Webhook/WebhookEventBuilderSpec.php
In this PR, we upgraded the octopus maintenance domain to Symfony 6. For V7 release we should make your code compliant with Symfony6. In order to keep ownership to user we migrate code by maintenance domain. All change have been made by rector (committed for now).
TLDR:
- Symfony make her code more strict (return type)
- getUsername have been replaced by getUserIdentifier => https://github.com/symfony/symfony/blob/6.0/UPGRADE-6.0.md?plain=1#L353-L354
> RAB-1115: Launch Symfony upgrade on octopus bounded context

- CHANGELOG.md
- src/Akeneo/Tool/Bundle/ApiBundle/Stream/StreamResourceResponse.php
- tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/PartialUpdateListProductEndToEnd.php
- tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/PartialUpdateListProductWithUuidEndToEnd.php
- tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/PartialUpdateListProductModelEndToEnd.php
When value from identifierCode was not a string, an error 500 was thrown. Now we throw 2.. type error
> PIM-10644: Fix identifier format check on multiple product update

- src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/ProductController.php
- src/Akeneo/Pim/Enrichment/Component/Product/Model/AbstractProduct.php
- tests/back/Pim/Enrichment/EndToEnd/Product/Product/InternalApi/ProductCreationEndToEnd.php
When saving a product without data, it is still marked as "not dirty", so it's not saved.
By forcing the save, the product is saved.
> CPM-771: Fix product creation without sku

- CHANGELOG.md
- src/Akeneo/Platform/Bundle/FrameworkBundle/PimFrameworkBundle.php
Events API generates a normalized product for the event subscription to send
Naturally, if a product contains media it is normalized, and a [HAL link is generated](https://github.com/akeneo/pim-community-dev/blob/4c20b1011c3cd091f4d00ed8fe36689ff7519dab/src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/ExternalApi/ValuesNormalizer.php#L60)
Issue here is that  events API is taking place as part of a CLI command thus Request Context is using `AKENEO_PIM_URL` environment variable to populate itself (instead of $_REQUEST). If `AKENEO_PIM_URL` have no explicit port, the port extracted from it becomes `0` (because of the cast to integer). When [the router generate an absolute URL it appends  the port `0`](https://github.com/symfony/symfony/blob/6.2/src/Symfony/Component/Routing/Generator/Ur …
> PIM-10673: Added default port to router request context

- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/creation/identifier.js
If we didn't send anything to the backend, it fails because it needs a value (null or "").
I have no idea how to add a test for this part @cemorin
> CPM-766: Fix duplicate to allow empty identifier

- components/identifier-generator/front/src/feature/IdentifierGeneratorApp.tsx
- components/identifier-generator/front/src/feature/hooks/useIdentifierAttributes.ts
- components/identifier-generator/front/src/feature/hooks/useUiLocales.ts
Using react-query, the queries should not be retrieved multiple times with the same props.
Before: the queryClient was not well configured to have that behavior because staleTime is set to 0 minutes as default value.
Now: staleTime is infinite, so that the queryClient keeps infinitly the cached queries
+ adding global settings inside QueryClient initialization
> CPM-735: Fix react-query cache config

- components/catalogs/back/src/Application/Handler/DeleteProductMappingSchemaHandler.php
- components/catalogs/back/src/Application/Handler/GetProductMappingSchemaHandler.php
- components/catalogs/back/src/Application/Handler/UpdateProductMappingSchemaHandler.php
- components/catalogs/back/src/Infrastructure/Controller/Public/GetProductMappingSchemaAction.php
- components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/GetProductMappingSchemaActionTest.php
- components/catalogs/back/tests/Integration/IntegrationTestCase.php
Fixes:
- GET product mapping schema returns a 404 instead of 500 when there is no product schema
- product schema file name on filesystem (every files had the same name because we casted `uuid string` into `int` in `sprintf`)
- reset catalog mapping file storage between each tests
> CXP-1338: Product mapping schema - 404 not found error instead of 500

- src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/FlatToStandard/FieldConverter.php
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/Processor/Denormalizer/ProductProcessor.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Processor/Denormalizer/ProductProcessorSpec.php
Instead of converting imported string to uuid, check it in the product processor and skip it when not valid
> CPM-760: Add uuid validation in ProductProcessor

- src/Akeneo/Connectivity/Connection/back/Infrastructure/Audit/Command/UpdateAuditDataCommand.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Audit/UpdateAuditData.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/DependencyInjection/AkeneoConnectivityConnectionExtension.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Audit/commands.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Audit/services.yml
Extract `akeneo:connectivity-audit:update-data` logic into a dedicated service.
This will allow to reuse this logic easilly, like in scheduled jobs for UCS.
I also add a few logs for observability.
> PH-269: Extract `akeneo:connectivity-audit:update-data` logic

- src/Akeneo/Platform/Job/back/Infrastructure/Query/SqlFindJobInstance.php
- src/Akeneo/Platform/Job/back/ServiceApi/JobInstance/JobInstanceQuery.php
- src/Akeneo/Platform/Job/back/tests/Integration/Infrastructure/Query/SqlFindJobInstanceTest.php
- Return JobInstance read model in FindJobIntance query
- Use job name instead of type in API
> RAB-1163: Return JobInstance read model in FindJobInstance query

- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/routing/external_api/product.yml
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/routing/internal_api/product.yml
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/routing/ui/product.yml
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/ListProductsByUuidQueryHandler.php
- src/Akeneo/Tool/Bundle/ApiBundle/Stream/StreamResourceResponse.php
- tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/CreateProductWithUuidEndToEnd.php
- tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/DeleteProductWithUuidEndToEnd.php
- tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/GetProductWithUuidEndToEnd.php
- tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/SuccessListProductsWithUuidEndToEnd.php
- tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/PartialUpdateListProductWithUuidEndToEnd.php
- tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/PartialUpdateProductWithUuidEndToEnd.php
- tests/back/Pim/Enrichment/EndToEnd/Product/Product/InternalApi/DownloadProductPdfEndToEnd.php
The RFC [RFC 4122: A Universally Unique IDentifier (UUID) URN Namespace](https://www.rfc-editor.org/rfc/rfc4122#section-3)
says that a uuid should be displayed with lowercase only.
But each input should accept uuid with 1 or more letter with uppercase, like “B9146fca-5456-433a-9360-27273258fcbC”
> CPM-779: Allow uppercase in uuid inputs

- front-packages/akeneo-design-system/src/components/Card/Card.tsx
- front-packages/akeneo-design-system/src/components/Card/Card.unit.tsx
In this PR I modified the Card component in order to :
- Have the possibility to give a ref, for example to detect if the component is in the user screen
- Add a props called `loading` that indicates how the browser should load the card image
In order to ease the review you can `Hide whitespace`
> PIM-10674: Add possibility to send a loading method on Card component

- CHANGELOG.md
- src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/helpers/convertBackendDashboardCompletenessData.ts
- src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/tests/front/unit/helpers/convertBackendDashboardCompletenessData.unit.ts
In this PR, i have a round to the inferior in order to not display 100% when completeness is 99,99%. By doing it we continue to do not display decimal on the dashboard.
> PIM-10686: Fix percentage of inaccurate completeness in the activity dashboard

- CHANGELOG-6.0.md
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/OAuth/CreateAccessToken.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Persistence/Query/IncreaseScopeLengthQuery.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/apps.yml
- src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/Persistence/Query/IncreaseScopeLengthQueryIntegration.php
When an app ask too many scopes (like all available scopes in EE), the database columns from FOS Oauth lib where these scopes are stored are too small.
We fixed this issue on master by doing a migration but on 6.0 we need to update the column structure on runtime as creating new migrations is forbidden.
We only use scopes in the app authorization process so we add the sql query right before creating the access token.
> PIM-10631: increase the FOS OAuth scope column to VARCHAR(1000)

- src/Akeneo/Platform/Job/back/Infrastructure/Query/SqlFindJobInstance.php
- src/Akeneo/Platform/Job/back/tests/Integration/Infrastructure/Query/SqlFindJobInstanceTest.php
In this PR, I've added the possibility to have a null Pagination object in SqlFindJobInstances.
> RAB-1171: Handle null Pagination object in SqlFindJobInstances

- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/product/edit/content/structure/attributes.js
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/common/modal-centered.html
- Adding the possiblity to specify a header Helper with an optional link in the export attributes modal
> RAB-1136: Add helper in Shared Catalogs export attribute modal

- src/Akeneo/Connectivity/Connection/back/Domain/ErrorManagement/Model/Write/ApiError.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/elasticsearch/connection_error_mapping.yml
- src/Akeneo/Connectivity/Connection/back/tests/.php_cd.php
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/ErrorManagement/CollectApiError/CollectDomainErrorFromProductEndpointEndToEnd.php
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/ErrorManagement/CollectApiError/CollectProductDomainErrorEndToEnd.php
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/ErrorManagement/CollectApiError/CollectProductValidationErrorEndToEnd.php
- src/Akeneo/Connectivity/Connection/back/tests/Integration/ErrorManagement/Persistence/ElasticsearchBusinessErrorRepositoryIntegration.php
- src/Akeneo/Connectivity/Connection/back/tests/Integration/ErrorManagement/Persistence/ElasticsearchSelectLastConnectionBusinessErrorsQueryIntegration.php
- src/Akeneo/Connectivity/Connection/back/tests/Integration/ErrorManagement/Persistence/PurgeConnectionErrorsQueryIntegration.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Domain/ErrorManagement/Model/Write/BusinessErrorSpec.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Domain/ErrorManagement/Model/Write/TechnicalErrorSpec.php
- upgrades/schema/Version_7_0_20221027152057_add_id_field_to_connection_error_index_mapping.php
- upgrades/test_schema/Version_7_0_20221027152057_add_id_field_to_connection_error_index_mapping_Integration.php
Currently, our logs are polluted with deprecation messages such as:
```
Loading the fielddata on the _id field is deprecated and will be removed in future versions. If you require sorting or aggregating on this field you should also include the id in the body of your documents, and map this field as a keyword field that has [doc_values] enabled
```
In order to mitigate it, another mapped field is required to be used instead of `_id`
This PR only adds the new field to the list of mapped fields
[Another PR](https://github.com/akeneo/pim-community-dev/pull/18266) will update queries that use `_id` on the `connection_error` index
> OCT-164: Add 'id' to connection_error ES index

- src/Akeneo/Connectivity/Connection/back/Application/Webhook/Service/EventsApiDebugLogger.php
- src/Akeneo/Connectivity/Connection/back/Domain/Webhook/Persistence/Repository/EventsApiDebugRepositoryInterface.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/elasticsearch/events_api_debug_mapping.yml
- src/Akeneo/Connectivity/Connection/back/tests/.php_cd.php
- src/Akeneo/Connectivity/Connection/back/tests/Integration/Webhook/EventsApiDebug/Persistence/ElasticsearchEventsApiDebugRepositoryIntegration.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Webhook/Service/EventsApiDebugLoggerSpec.php
- upgrades/schema/Version_7_0_20221026154157_add_id_to_events_api_debug_index_mapping.php
- upgrades/test_schema/Version_7_0_20221026154157_add_id_to_events_api_debug_index_mapping_Integration.php
Currently, our logs are polluted with deprecation messages such as:
```
Loading the fielddata on the _id field is deprecated and will be removed in future versions. If you require sorting or aggregating on this field you should also include the id in the body of your documents, and map this field as a keyword field that has [doc_values] enabled
```
In order to mitigate it, another mapped field is required to be used instead of _id
This PR only adds the new field to the list of mapped fields
[Another PR](https://github.com/akeneo/pim-community-dev/pull/18268) will update queries that use _id on the events_api_debug index
> OCT-165: Add 'id' to events_api_debug index

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/Processor/QuickExport/ProductAndProductModelProcessor.php
- src/Oro/Bundle/PimDataGridBundle/Datasource/AssociatedProductDatasource.php
- src/Oro/Bundle/PimDataGridBundle/spec/Datasource/AssociatedProductDatasourceSpec.php
Currently, associations in the grid are not properly sorted, this PR adds a sort on the ElasticSearch field ID to make sure products are sorted using their uuids.
> PIM-10689: Add sorting on ES id for product associations grid

- CHANGELOG-6.0.md
- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/providers/CategoryTreeProvider.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/categories/useCategoryTreeNode.ts
State managing nodes list was not well synchronized with user actions (adding new categories in the tree for instance).
When updating the state, some of the newly created nodes lost the information of having children, resulting in not visible "child categories".
Fix give the setNodes function the previous state to make sure the synchronisation is well done.
> PIM-10664 Hidden sub-categories from the sub category trees unless page is refreshed

- .circleci/jobs/build_and_deploy.yml
- Dockerfile
- composer.json
- composer.lock
- docker-compose.yml
In this PR, 
I upgraded the PHP version used by the PIM to 8.1. 
akeneo/pim-php-dev have been tagged to 8.1 (https://hub.docker.com/layers/akeneo/pim-php-dev/8.1/images/sha256-ce7ec077b50a358347f8fdcf6e7ba0aff4e193a974697d2f1ddfc1a93eef35e7?context=explore), there is no more master tag but just tag version related to the PHP version, let's use it now !
> RAB-1127: [php 8.0 => 8.1] update image

- CHANGELOG-5.0.md
- src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/associations/product.yml
Use the product grid category tree route in the association picker, which is way faster than the former route (and is for enrichment anyway). This allows rendering the category picker much faster if there are a lot of categories
> PIM-10671: Fix slowness on product association page with a lot of categories

- upgrades/.php_cd.php
- upgrades/schema/Version_7_0_20221026154157_add_id_to_events_api_debug_index_mapping.php
- upgrades/schema/Version_7_0_20221027152057_add_id_field_to_connection_error_index_mapping.php
- upgrades/test_schema/Version_7_0_20221026154157_add_id_to_events_api_debug_index_mapping_Integration.php
- upgrades/test_schema/Version_7_0_20221027152057_add_id_field_to_connection_error_index_mapping_Integration.php
**Context**
The migration is executed asynchronously. 
Before the doctrine migration was executed, the webhook consumer started indexing new documents in the index `akeneo_connectivity_connection_events_api_debug`, with a new property `id`.
Because you can index documents without configuring a mapping beforehand, the new property has been automatically created by ES with the type `text` instead of `keyword`.
In ES, you cannot directly change the type of a property. (see https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-put-mapping.html#updating-field-mappings)
The migration is failing for customers having sent webhooks between the deployment and the doctrine migration execution.
**The dirty solution**
Since we cannot rename a property, cannot change the type of a …
> OCT-169: fix migration of ES index

- CHANGELOG-5.0.md
- src/Akeneo/Tool/Component/Connector/Archiver/AbstractInvalidItemWriter.php
Sometimes it happens that an invalid value (= a row) has at least one empty value at the end. FileIterator returns nothing for these values and then when we try to `array_combine` headers and row, both array length does not match and makes the invalid items files generation failing.
Basically, the fix is to pad the row by empty values to match the headers length.
> PIM-10711: Fix AbstractInvalidItemWriter does not pad empty values for trailing empty column

- CHANGELOG.md
- src/Akeneo/Category/back/Domain/ValueObject/LabelCollection.php
Labels are not mandatory in the PIM, we can have a LabelCollection like this : 
```
[
'en_US' => null,
'de_DE' => null,
'fr_FR' => null,
]
```
We can remove assert validation in the constructor of LabelCollection.
> PIM-10718: Categories with empty labels throw 500 error

- src/Akeneo/Tool/Bundle/BatchBundle/Notification/MailNotifier.php
- src/Akeneo/Tool/Bundle/BatchBundle/Resources/views/Email/notification.html.twig
- src/Akeneo/Tool/Bundle/BatchBundle/Resources/views/Email/notification.txt.twig
- src/Akeneo/Tool/Bundle/BatchBundle/spec/Notification/MailNotifierSpec.php
Export type was hardcoded in the mail subject, it is now using the job instance label in the received event.
I also updated the subject and message inside mail template.
> RAC-1283: Fix email subject of a job notification

- src/Akeneo/Category/back/Infrastructure/Builder/TemplateBuilder.php
- src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
- src/Akeneo/Category/back/tests/Specification/Infrastructure/Builder/TemplateBuilderSpec.php
- src/Akeneo/Category/front/src/feature/components/EditAttributesForm.tsx
- src/Akeneo/Category/front/src/feature/components/datagrids/CategoryTreeDataGrid.tsx
- src/Akeneo/Category/front/src/feature/components/templates/EditTemplateAttributesForm.tsx
- src/Akeneo/Category/front/src/feature/components/templates/createTemplate.tsx
Type 1, 4 and 5 weren't the good ones, and I created labels for corresping attribute types and the Image code.
Beyond the fix, I used this subject to discover the pim and experiment dynamic variables to handle attributes sorting.
My idea was based on usual dynamic database.
> Grf 562 : Order attributes in Template structure page same as in the static template itself

- docker-compose.yml
In this PR, I changed the elasticsearch version to 7.17.7 in order to prepare upgrade to 8. As recommended in the official doc we should upgrade at the last version of v7 in order to have all deprecation message
> RAB-1170: Upgrade elasticsearch version to 7.17.7 in order to prepare upgrade to 8

- src/Akeneo/Platform/CommunityVersion.php
The version name for 6.0 is wrong, maybe overrided by a previous pull-up from 5.0.
> Fix version name

- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Apps/Public/GetOpenIdPublicKeyEndToEnd.php
Following the phpseclib migration from v2 to v3 here https://github.com/akeneo/pim-community-dev/pull/17101 we found a bug by testing manually the PR. The new public key was not readable by the openssl standard function of PHP.
This PR aims to add an automatic test to ensure the public key delivered by our open id endpoint is still readable by openssl. 
> OCT-158: add test on open id public key

- front-packages/akeneo-design-system/src/icons/HelpIcon.tsx
The HelpIcon on the DSM has the ? not in the center of the circle. So I updated it to be correct.
> Update Help Icon for DSM

- src/Akeneo/Category/front/src/feature/components/EditAttributesForm.tsx
- src/Akeneo/Category/front/src/feature/components/attributes/buildRichTextFieldAttribute.tsx
Define a key for rich text editor which will include the composite key for better identifiate the component
Remove useless check which prevented to display the attribute image label that is no localizable for now
> GRF-595: Charge attributes values per channel dynamicaly

- front-packages/akeneo-design-system/src/components/Collapse/Collapse.tsx
Seen with the designers, the font size for the collapse label is too small.
We need to move it from 11px to 13px.
> DSM: Update font size label collapse

- src/Akeneo/Category/front/src/feature/components/EditAttributesForm.tsx
- src/Akeneo/Category/front/src/feature/components/channel/ChannelSelector.test.tsx
- src/Akeneo/Category/front/src/feature/components/channel/ChannelSelector.tsx
When the PIM is build and launched for the 1st time, or when we delete the project's cache, the ChannelSelector component receives an empty list of channels. It try to access the "code" property of every channel of this empty list which resulted in an error and a blank page.
Now we do not display the component if the channels list is empty
> GRF-599 fix blank page on categories when manipulating channels list before it is fetched

- components/identifier-generator/front/src/feature/pages/CreateGeneratorPage.tsx
- components/identifier-generator/front/src/feature/pages/CreateOrEditGeneratorPage.tsx
- components/identifier-generator/front/src/feature/pages/__tests__/CreateGeneratorPage.test.tsx
- components/identifier-generator/front/src/feature/pages/__tests__/CreateOrEditGeneratorPage.test.tsx
We invalidate the getGenerator query on create in order to refetch the generator in all the app.
> CPM-828: Invalidate getGenerator on create to refresh datas

- CHANGELOG-6.0.md
- src/Akeneo/Tool/Component/Connector/Archiver/FileWriterArchiver.php
- src/Akeneo/Tool/Component/Connector/spec/Archiver/FileWriterArchiverSpec.php
In this PR, 
I fixed a fatal error due to the fact that we call a function on an array instead of calling the function on the object
> PIM-10735: Assets export fails because of a failed warning messages

- src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/jobs.yml
**Before:** 
https://blackfire.io/profiles/bd61eb60-95f7-46e1-b1d2-6e22b1c5d49b/graph?settings%5Bdimension%5D=timeline&settings%5Bdisplay%5D=landscape&settings%5BtabPane%5D=metrics&selected=&callname=main()&constraintDoc=
---
**After:**
https://blackfire.io/profiles/462590cd-2c14-4cf7-b59e-3d828bb4fbb4/graph?settings%5Bdimension%5D=timeline&settings%5Bdisplay%5D=landscape&settings%5BtabPane%5D=metrics&selected=&callname=main()&constraintDoc=
---
**Why?**
I've noticed on the initial graph that a lot of time is spent on DI when the `Akeneo\Pim\Enrichment\Bundle\Elasticsearch\ProductQueryBuilderFactory` is loaded from the Symfony container.
I was able to pinpoint it to this class: …
> OCT-175: lazy load 2 job repositories

- components/catalogs/front/src/components/ProductSelection/ProductSelection.integration.tsx
- components/catalogs/front/src/components/ProductSelection/hooks/useAttributeOptionsByCodes.unit.ts
- components/catalogs/front/src/exports.ts
In order to reuse Catalog Product Selection in other context, in this PR we export the front component.
We also complete integration tests to cover all use cases. Thus, this integration test can be used as documentation.
> CXP: export catalog product selection

- components/identifier-generator/back/src/Infrastructure/Symfony/Install/InstallerSubscriber.php
- upgrades/schema/Version_7_0_20221129093347_add_cascade_on_prefixes.php
- upgrades/schema/Version_7_0_20221130130031_update_identifier_generator_prefix_number_type.php
- upgrades/test_schema/Version_7_0_20221130130031_update_identifier_generator_prefix_number_type_Integration.php
Previous max number was INT(8) -> -2147483648 to 2147483647
Now it can have INT(16) UNSIGNED -> 0 to 2^64 - 1
https://dev.mysql.com/doc/refman/8.0/en/integer-types.html#:~:text=MySQL%20supports%20the%20SQL%20standard,TINYINT%20%2C%20MEDIUMINT%20%2C%20and%20BIGINT%20.
> CPM-817: Add migration for column type

- src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Attribute/IdentifierFilter.php
- src/Akeneo/Pim/Enrichment/Bundle/Extension/RegisterIdentifierFilters.php
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/datagrid/product.yml
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/query_builders.yml
- src/Oro/Bundle/PimDataGridBundle/Resources/config/attribute_types.yml
- src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/identifier-filter.js
- tests/back/Pim/Enrichment/Integration/PQB/Filter/Field/IdentifierFilterIntegration.php
- tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Filter/Attribute/IdentifierFilterSpec.php
- tests/back/Pim/Enrichment/Specification/Bundle/Extension/RegisterIdentifierFiltersSpec.php
> CPM-824: Add empty/not empty operator on identifier filter in product grid

- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/WebTestCase.php
- src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/AppRoleWithScopesFactoryIntegration.php
- src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/Command/UpdateConnectedAppScopesWithAuthorizationHandlerIntegration.php
- src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/Install/AddAclToRolesIntegration.php
- src/Akeneo/Connectivity/Connection/tests/Context/AppActivateContext.php
- src/Akeneo/Pim/Enrichment/Product/back/Test/Acceptance/Context/UserContext.php
- src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/tests/Integration/WebTestCase.php
- tests/back/Acceptance/User/UserContext.php
- tests/back/Pim/Enrichment/EndToEnd/InternalApiTestCase.php
- tests/back/Platform/EndToEnd/InternalApiTestCase.php
- upgrades/test_schema/Version_6_0_20210908142400_add_product_web_api_acl_Integration.php
Following the merge of this [PR](https://github.com/akeneo/pim-community-dev/pull/18434), I fixed minors depreciations :
- UsernamePasswordToken does not accept anymore $credentials in his constructor so I removed from every new clauses
> RAB-1149: Fix minors depreciations

- src/Akeneo/Category/back/Infrastructure/Builder/TemplateBuilder.php
- src/Akeneo/Category/back/Infrastructure/Storage/InMemory/GetAttributeInMemory.php
- src/Akeneo/Category/back/tests/Integration/Helper/CategoryTestCase.php
- src/Akeneo/Category/back/tests/Integration/Infrastructure/FileSystem/PreviewGenerator/BinaryImageGeneratorIntegration.php
- src/Akeneo/Category/back/tests/Specification/Domain/Model/Enrichment/TemplateSpec.php
- src/Akeneo/Category/back/tests/Specification/Domain/UserIntent/Factory/ValueUserIntentFactorySpec.php
- src/Akeneo/Category/front/src/feature/components/attributes/buildImageFieldAttribute.tsx
> GRF-347 : Allow image attribute fields to be also locale (and channel)-specific

- src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/EventsApiDebug/Persistence/GetAllEventSubscriptionDebugLogsQuery.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/EventsApiDebug/Persistence/PurgeEventsApiSuccessLogsQuery.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/EventsApiDebug/Persistence/SearchEventSubscriptionDebugLogsQuery.php
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Webhook/EventsApiDebug/Controller/Internal/DownloadEventSubscriptionLogsEndToEnd.php
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Webhook/EventsApiDebug/Controller/Internal/SearchEventSubscriptionLogsEndToEnd.php
- src/Akeneo/Connectivity/Connection/back/tests/Integration/Webhook/EventsApiDebug/Persistence/GetAllEventSubscriptionDebugLogsQueryIntegration.php
- src/Akeneo/Connectivity/Connection/back/tests/Integration/Webhook/EventsApiDebug/Persistence/PurgeEventsApiSuccessLogsQueryIntegration.php
- src/Akeneo/Connectivity/Connection/back/tests/Integration/Webhook/EventsApiDebug/Persistence/SearchEventSubscriptionDebugLogsQueryIntegration.php
This PR updates queries that use `_id` field to use the mapped field `id` created by [OCT-165](https://github.com/akeneo/pim-community-dev/pull/18267)
> OCT-167: Updated queries to use mapped field id instead of ES _id

- composer.json
- composer.lock
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Webhook/services_test.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/Client/GuzzleWebhookClient.php
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/GuzzleJsonHistoryContainer.php
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/GuzzleMockHandlerStackFactory.php
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Webhook/ConsumeProductEventEndToEnd.php
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Webhook/ConsumeProductModelEventEndToEnd.php
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Webhook/IncrementEventsApiRequestCountEndToEnd.php
I upgraded `guzzlehttp/guzzle` to v7.
I had to refactor a bit a mock used in Connectivity 2e2. Basically, `HandlerStack` is now final, so we can't extends it. I removed the extension and injected the history container in tests to query it.
> RAB-1124: Update guzzlehttp/guzzle

- .circleci/jobs/features/connectivity.yml
- .circleci/workflows/squads/octopus/octopus_connectivity_pull_request.yml
This is a slow step but it guarantee that we didn't break the build (it happened a few days ago because imports paths were valid only in tests, so the CI was green)
> OCT-185: Add javascript-dev-strict command to CXP CI

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/MetricValueFactory.php
- src/Akeneo/Tool/Component/StorageUtils/Exception/InvalidPropertyTypeException.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Factory/Value/MetricValueFactorySpec.php
We have to invalidate value in hexadecimal or power exponent format. Actually, there is no function to do that in php (`ctype_digit` only works with integer and we can receive float here), so we have have to invalidate it with a regex.
see https://akeneo.atlassian.net/browse/PIM-10753
> PIM-10753: Fix 500 error in the API when patching a product metric with a mathematical notation

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/validators.en_US.yml
- src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/IsNumeric.php
- src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/IsNumericValidator.php
- src/Akeneo/Tool/Bundle/MeasureBundle/Convert/MeasureConverter.php
- src/Akeneo/Tool/Bundle/MeasureBundle/spec/Convert/MeasureConverterSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Validator/ConstraintGuesser/MetricGuesserSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Validator/ConstraintGuesser/NumericGuesserSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/IsNumericSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/IsNumericValidatorSpec.php
When a user try to save a measurement value with a space, it encounters a 500 error.
I fixed the MeasureConverter to ignore the value and added a check in IsNumeric constraint to be able to unvalidate the product and print a message to the user.
see https://akeneo.atlassian.net/browse/PIM-10751
> PIM-10751: Avoid 500 error and print a violation when user try to save measurement value with space

- src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/StorageClient/DownloadFileFromStorage.php
- src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/StorageClient/TransferFile.php
- src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/StorageClient/TransferFilesToStorage.php
- src/Akeneo/Platform/Bundle/ImportExportBundle/Query/GetJobExecutionTracking.php
- src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/AmazonS3StorageConfigurator.tsx
- src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/SftpStorageConfigurator.tsx
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/common/file-path.js
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/import/file-path.html
- tests/back/Platform/EndToEnd/ImportExport/InternalApi/GetJobExecutionEndToEnd.php
- tests/back/Platform/Integration/ImportExport/Repository/InternalApi/GetJobExecutionTrackingIntegration.php
- User-friendly error message when we cannot upload file (we cannot use exception message as they are formatted differently for each provider)
- Remove dirty hack that skipped upload/download steps for old jobs, as the feature is now released for more than 90 days
- Add placeholders on password & secret inputs
- Add storage type badge next to file path & import button when having a remote storage configured
> RAB-1235: Add storage type badge & better error message

- src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Controller/Public/RedirectToEditConnectedAppAction.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Apps/controllers.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Apps/routing.yml
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Apps/Public/RedirectToEditConnectedAppActionEndToEnd.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Apps/Controller/Public/RedirectToEditConnectedAppActionSpec.php
To be able to modify the Go to PIM link in demo app to directly reach the connected app edit page, we need the connection code.
So, this new public route allows to do this.
> CXP-1363: Add route to reach connected app edit page by id with redirection

- composer.json
- composer.lock
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/OAuth/CreateJsonWebToken.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Apps/OAuth/CreateJsonWebTokenSpec.php
Around 22 August, `lcobucci/jwt` released a new minor 4.2.0 that introduces a BC break due to security reason: https://github.com/lcobucci/jwt/issues/877
This new version did not allow SHA256 with private key of 1024 bits, which is the default length used by phpseclib : https://lcobucci-jwt.readthedocs.io/en/4.2.1/supported-algorithms/#deprecated-items_1
As there is no `composer.lock` on EE and in our `composer.json` we set `"lcobucci/jwt": "^4.1"`, we have automatically upgraded and it broke some tests in the CI.
To quickly fix this behavior, we locked the vendor to the last working version and planned an update: https://github.com/akeneo/pim-community-dev/pull/17696
Since this day we made an update of phpseclib from version 2 to 3 : …
> OCT-108: Upgrade lcobucci/jwt to ^4.2

- std-build/migration/prepare_60_to_70.sh
In this PR, I added the missing prepare script used when a PIM is migrated from v6 to v7. This file is the same than the v6 for now, let's see if we need to change it after merging it and test a migration
> RAB-1243: Add prepare_60_to_70.sh into std-build directories

- .circleci/workflows/pull_request.yml
EE: https://github.com/akeneo/pim-enterprise-dev/pull/15913
> OCT-194: Remove slack notifications when `test_catalogs` fails on a PR but keep it for the nightly

- src/Akeneo/Tool/Bundle/ApiBundle/DependencyInjection/Compiler/ContentTypeNegotiatorPass.php
We use a service of FOSRestBundle which was removed in the last version.
see https://github.com/FriendsOfSymfony/FOSRestBundle/pull/2377
> Fix compiler pass broken due to FOSRestBundle upgrade

- components/catalogs/Makefile
> OCT-207: limit catalogs coverage to unit & inte, not perfs

- CHANGELOG-6.0.md
- src/Akeneo/Pim/Enrichment/.php_cd.php
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/jobs.yml
- src/Akeneo/Pim/Enrichment/Component/Product/Job/RemoveCompletenessForChannelAndLocaleTasklet.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Job/RemoveCompletenessForChannelAndLocaleTaskletSpec.php
[[BACKPORT PIM-10516]](https://github.com/akeneo/pim-community-dev/pull/17366)
When removing a locale from a channel, and re-adding it before the remove_completeness_for_channel_and_locale, the job would re-remove it, possibly deactivating the locale if it's not bound to another channel
This PR:
- ensures the job does nothing if the provided locales are still in the channel
- and moreover, ensures the job DOES NOT update the locales, as it's not its role (it's only here to clean product values, recompute completeness and reindex products)
> PIM-10787: Do not run the remove completeness job when there is no need

- components/identifier-generator/front/src/feature/pages/__tests__/CreateGeneratorPage.test.tsx
- components/identifier-generator/front/src/feature/tabs/StructureTab.tsx
- components/identifier-generator/front/src/feature/validators/__tests__/validateDelimiter.test.ts
- components/identifier-generator/front/src/feature/validators/__tests__/validateFreeText.test.ts
- components/identifier-generator/front/src/feature/validators/validateDelimiter.ts
- components/identifier-generator/front/src/feature/validators/validateFreeText.ts
User cannot create/save a generator which has a delimiter with the following values: ` spaceBefore`, `spaceAfter `, `,`, `;`
> CPM-898: Add validation on delimiter value

- config/services/services.yml
- src/Akeneo/Platform/Bundle/PimVersionBundle/Resources/config/services.yml
I introduced a new param for VersionProvider : `version_file_folder_location`.
Using kernel.project_dir does not work for standard edition, we have to search version.txt in the CE project path.
I used a new param instead of `pim_ce_dev_src_folder_location` because the location will change in EE.
> RAB-1266: Introduce a new param for VersionProvider

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Completeness/SqlGetProductCompletenesses.php
Mysql statistics are very simple. It is possible to calculate a cardinality of 8000 channels in the table `pim_catalog_completeness`, even if there are maximum 20 channels in the PIM.
This is due to its way it calculate it with sampling. It fetches completeness by filtering on completeness instead of product uuids. We forced to filter on product uuids thanks to CTE + DISTINCT as barrier optimization.
It's exactly the same issue as here: https://github.com/akeneo/pim-community-dev/pull/13648/files
> SDS-27322: Optimize get completeness SQL query

- components/catalogs/back/src/Application/Handler/GetMappedProductsHandler.php
- components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/GetMappedProductsActionTest.php
- components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/GetProductsActionTest.php
- components/catalogs/back/tests/Integration/IntegrationTestCase.php
- added safeguards to prevent errors when catalog product selection is invalid on mapped products endpoint
- added a test case to check that a removed attribute does not break the mapping endpoint
> CXP-1356: GetProductMappedHandler : Catch exception from PQB like in GetProductsHandler

- .circleci/config/commands.yml
- components/catalogs/back/src/Application/Handler/GetProductHandler.php
- components/catalogs/back/src/Infrastructure/Controller/Public/GetProductAction.php
- components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/GetProductActionTest.php
The catalog's GetProduct endpoint throws an error if the catalog product selection is invalid
This PR adds similar error handling to what was done on other endpoints to prevent the endpoint from crashing
> OCT-199 Add catalog disable event on error for GetProduct endpoint

- components/catalogs/front/src/components/CatalogEdit/hooks/useCatalogErrors.ts
I corrected the possibility to have an error message while all errors were already corrected :
The only change is the deactivation of the cache (cacheTime: 0).
> OCT-188 : AttributeMapping: Error is shown one more time after correction.

- composer.json
- composer.lock
justinrainbow/json-schema is removed in the composer.json, it have been replace by opis/json-schema.
It is always present in the composer.lock because it's used by nunomaduro/phpinsights vendor
```docker-compose run --rm php php -d memory_limit=4G /usr/local/bin/composer why justinrainbow/json-schema```
> OCT-139: [CE] remove justinrainbow/json-schema in composer.json

- src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/model.test.ts
- src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/model.ts
- src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/model.test.ts
- src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/model.ts
In this PR,
I added the fact that microsoft azure, google cloud storage and amazon s3 are not displayed in CE. To do it I added a check of the feature flag in CE and I only added the implementation of this flag in EE. By doing it microsoft azure, google cloud storage and amazon s3 are not displayed in CE.
> RAB-1138: Do not display the additional storage in CE

- components/identifier-generator/back/src/Infrastructure/Repository/SqlIdentifierGeneratorRepository.php
How it works
- Our code is deployed
- PHP container are restarted
- Migration are started.
During the little gap between "PHP new code is active" and "migration are not finished", we can have the scenario of a user saves a product. It implies a SELECT from the "pim_catalog_identifier_generator" table. These queries are looking for a "target_id" column, which will not be migrated and not existing.
In this case, we fallback in the previous query using "target".
> CPM-924: Be able to work with previous database version

- CHANGELOG.md
- front-packages/shared/src/components/TextField.tsx
- src/Akeneo/Platform/Bundle/ImportExportBundle/Controller/InternalApi/JobInstanceController.php
- src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/Security/CredentialsEncrypter.php
- src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/Security/CredentialsEncrypterRegistry.php
- src/Akeneo/Platform/Bundle/ImportExportBundle/Normalizer/Versioning/JobInstanceNormalizer.php
- src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/normalizers.yml
- src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/public/js/job/common/edit/storage-form.ts
- src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/AmazonS3StorageConfigurator.test.tsx
- src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/AmazonS3StorageConfigurator.tsx
- src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/LocalStorageConfigurator.test.tsx
- src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/MicrosoftAzureStorageConfigurator.test.tsx
- src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/MicrosoftAzureStorageConfigurator.tsx
- src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/SftpStorageConfigurator.test.tsx
- src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/SftpStorageConfigurator.tsx
- src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/model.ts
- src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageForm.test.tsx
- src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageForm.tsx
- src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/model.ts
- src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/hooks/useCheckStorageConnection.test.ts
- src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/hooks/useCheckStorageConnection.ts
- tests/back/Platform/Specification/Bundle/ImportExportBundle/Infrastructure/Security/CredentialsEncrypterRegistrySpec.php
- tests/back/Platform/Specification/Bundle/ImportExportBundle/Normalizer/Versioning/JobInstanceNormalizerSpec.php
In this PR: 
- I removed the fact that the secret are displayed in the UI. The secret/password are not directly displayed to the user (the input type is password) but is available in network and in the DOM. Now the password is never returned to user, the secret key is not returned to the front. By doing this we can distinguish when the secret is empty because the user give an empty secret or because the secret is obfuscated. 
The used can edit the password without having the previous password displayed by clicking on edit
- I removed the fact that the hashed password is displayed into the history
> PIM-10789: Do not return and show encrypted password

- CHANGELOG.md
- src/Akeneo/Tool/Bundle/ApiBundle/Stream/StreamResourceResponse.php
- tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/PartialUpdateListProductWithUuidEndToEnd.php
param $this->uriParamName has been created in order to work with both 'uuid' and 'code' but meaning the code or uuid as set in the url calling.
Here it's the 'code' of the response, so it will always be 'code'
> PIM-10768: Fix update list status_code response

- src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/ProductAndProductModel/GetProductUuidsNotSynchronisedBetweenEsAndMysql.php
- tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductAndProductModel/GetProductUuidsNotSynchronisedBetweenEsAndMysqlIntegration.php
Improve Product & Product model indexing command
The error is the following:
`Uncaught Exception TypeError: "DateTimeImmutable::__construct(): Argument #1 ($datetime) must be of type string, null given" at /srv/pim/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/ProductAndProductModel/GetProductUuidsNotSynchronisedBetweenEsAndMysql.php line 79
`
This error happens when a product is completely absent from the ES index
> CPM-917: Fix product indexation command with "--diff" option

- components/identifier-generator/back/src/Domain/Model/Condition/Conditions.php
- components/identifier-generator/back/src/Domain/Model/Condition/EmptyIdentifier.php
- components/identifier-generator/back/src/Domain/Model/IdentifierGenerator.php
- components/identifier-generator/back/src/Domain/Model/ProductProjection.php
- components/identifier-generator/back/src/Domain/Model/Property/AutoNumber.php
- components/identifier-generator/back/src/Domain/Model/Property/FamilyProperty.php
- components/identifier-generator/back/src/Domain/Model/Property/FreeText.php
- components/identifier-generator/back/src/Domain/Model/Property/PropertyInterface.php
- components/identifier-generator/back/src/Domain/Model/Structure.php
- components/identifier-generator/back/src/Infrastructure/Subscriber/SetIdentifiersSubscriber.php
- components/identifier-generator/back/tests/Specification/Application/Generate/GenerateIdentifierHandlerSpec.php
- components/identifier-generator/back/tests/Specification/Application/Generate/Property/GenerateAutoNumberHandlerSpec.php
- components/identifier-generator/back/tests/Specification/Application/Generate/Property/GenerateFamilyHandlerSpec.php
- components/identifier-generator/back/tests/Specification/Application/Generate/Property/GenerateFreeTextHandlerSpec.php
- components/identifier-generator/back/tests/Specification/Domain/Model/Condition/ConditionsSpec.php
- components/identifier-generator/back/tests/Specification/Domain/Model/Condition/EmptyIdentifierSpec.php
- components/identifier-generator/back/tests/Specification/Domain/Model/Condition/EnabledSpec.php
- components/identifier-generator/back/tests/Specification/Domain/Model/Condition/FamilySpec.php
- components/identifier-generator/back/tests/Specification/Domain/Model/Condition/SimpleSelectSpec.php
- components/identifier-generator/back/tests/Specification/Domain/Model/IdentifierGeneratorSpec.php
- components/identifier-generator/back/tests/Specification/Domain/Model/Property/FamilyPropertySpec.php
- components/identifier-generator/back/tests/Specification/Domain/Model/StructureSpec.php
- components/identifier-generator/back/tests/Specification/Infrastructure/Subscriber/SetIdentifiersSubscriberSpec.php
When adding structure properties, some of them have implicit conditions.
For example, when you want to generate a code with a Family, you need the product to have a family.
> CPM-909: Add implicit conditions

- components/identifier-generator/front/src/feature/models/properties/autoNumber.ts
- components/identifier-generator/front/src/feature/tabs/structure/edit/AutoNumberEdit.tsx
- components/identifier-generator/front/src/feature/tabs/structure/edit/__tests__/AutoNumberEdit.test.tsx
- components/identifier-generator/front/src/feature/tabs/structure/preview/AutoNumberPreview.tsx
- components/identifier-generator/front/src/feature/validators/__tests__/validateAutoNumber.test.ts
- components/identifier-generator/front/src/feature/validators/__tests__/validateStructure.test.ts
- components/identifier-generator/front/src/feature/validators/validateAutoNumber.ts
- components/identifier-generator/front/src/feature/validators/validateStructure.ts
Set the AutoNumber nullable in order to erase data. 
Validation will add violation on null digitsMin or numberMin
> CPM-842 : Erase the default number of digits for the auto number

- CHANGELOG.md
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/field/wysiwyg-field.js
Event name changed after navigator update (from chrome 108 to 109)
> PIM-10802: Fix wysiwyg-field add link event

- src/Akeneo/UserManagement/Bundle/EventListener/LoginRateLimitListener.php
- tests/back/UserManagement/Specification/Bundle/EventListener/LoginRateLimitListenerSpec.php
An 500 error has been detected on demo cluster (all region) and prod cluster (only Australia/Asia) and the deployment in production has been suspended.
We found that, in some login failure case we were not able to identify clearly, the new Symfony authentication system threw an exception, resulting in an empty "User Passport" and then manipulation of an empty object.
This fix manage this case and consider this as a failed login attempt.
> Fix error 500 on login page when username length > 4096 characters

- src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/Security/ScopeMapperRegistryIntegration.php
- src/Akeneo/Pim/Enrichment/Bundle/Command/ZddMigrations/V20220516171405SetProductIdentifierNullableZddMigration.php
- src/Akeneo/Pim/Enrichment/Bundle/Command/ZddMigrations/V20220729171405DropProductIdColumnsAndCleanVersioningResourceUuidColumns.php
- src/Akeneo/Platform/Bundle/InstallerBundle/Command/ZddMigration.php
- upgrades/.php_cd.php
- upgrades/schema/Version_7_0_20230201143400_drop_product_id_columns_and_clean_versioning_resource_uuid_columns.php
- upgrades/schema/Version_7_0_20230201143500_set_product_identifier_nullable.php
- upgrades/test_schema/Version_7_0_20230201143400_drop_product_id_columns_and_clean_versioning_resource_uuid_columns_Integration.php
- upgrades/test_schema/Version_7_0_20230201143500_set_product_identifier_nullable_Integration.php
Some migrations are not launched out of Saas env because they are ZDD.
I created not ZDD equivalents for them in this PR.
> RAB-1310: Add not ZDD migrations equivalent of ZDD migrations

- components/identifier-generator/back/src/Application/Update/UpdateGeneratorHandler.php
- components/identifier-generator/back/src/Domain/Model/IdentifierGenerator.php
- components/identifier-generator/back/tests/Specification/Domain/Model/IdentifierGeneratorSpec.php
Remove setters to make IdentifierGenerator immutable
> CPM-928: Transform IdentifierGenerator into an Immutable Object

- components/catalogs/back/src/Application/Mapping/TargetTypeConverter.php
- components/catalogs/back/tests/Acceptance/ApiContext.php
- components/catalogs/back/tests/Unit/Application/Mapping/TargetTypeConverterTest.php
In the above API response, I mapped the PIM attribute "optical zoom" which is a number to the targets "zoom" and "description":
> CXP-1431: Map number attributes (string)

- components/identifier-generator/front/package.json
- front-packages/akeneo-design-system/package.json
- front-packages/measurement/package.json
- front-packages/shared/package.json
- src/Akeneo/Category/front/package.json
- src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/front/package.json
- src/Akeneo/Platform/Bundle/ImportExportBundle/front/package.json
- src/Akeneo/Platform/Job/front/process-tracker/package.json
- src/Oro/Bundle/ConfigBundle/front/package.json
In this PR, 
I fixed the memory leak that random fail CI, as --workerIdleMemoryLimit=300MB is only available on jest 29 and we are in jest 26, first we try to bump the jest version (https://akeneo.atlassian.net/browse/RAB-1311) but we didn't succeeded (dependency hell) since 1 week so we decided to use the node parameter.
> Fix workerIdleMemoryLimit only work on jest 29, as we did not success to upgrade jest we used max_old_space_size

- CHANGELOG.md
- src/Akeneo/Platform/Bundle/AnalyticsBundle/Controller/ExternalApi/GetSystemInformationController.php
- src/Akeneo/Platform/Bundle/AnalyticsBundle/Resources/config/controllers.yml
- src/Akeneo/Platform/Bundle/PimVersionBundle/Version/GrowthVersion.php
- tests/back/Platform/EndToEnd/ExternalApi/GetSystemInformationEndToEnd.php
- tests/back/Platform/Specification/Bundle/AnalyticsBundle/Controller/ExternalApi/GetSystemInformationControllerSpec.php
As per the https://api.akeneo.com/api-reference.html#System: 
In a Saas env, do a GET {{url}}/api/rest/v1/system-information call, the edition returned should be 'Serenity'
In a GE env, do a GET {{url}}/api/rest/v1/system-information call, the edition returned should be 'GE'
In an EE env, do a GET {{url}}/api/rest/v1/system-information call, the edition returned should be 'EE'
In a CE env,do a GET {{url}}/api/rest/v1/system-information call, the edition returned should be 'CE'
> PIM-10796: Fix system-information endpoint with wrong answers

- src/Akeneo/Connectivity/Connection/back/Infrastructure/Marketplace/WebMarketplaceAliases.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Marketplace/services.yml
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Marketplace/WebMarketplaceAliasesSpec.php
- src/Akeneo/Pim/Enrichment/Component/Product/Localization/Presenter/MetricPresenter.php
- tests/legacy/features/pim/enrichment/product/mass-action/quick-export/quick_export_with_localized_data.feature
Apps displayed in the app store of a free trial edition should be the same as for the Growth edition. As there is no "free-trial-edition" option in app store API (see https://github.com/akeneo/marketplace-store-api/blob/master/docs/openapi.yaml#L69), we use "growth-edition"
> OCT-182: [Free trial] Displayed apps are not the right ones

- src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Controller/Internal/GetWizardDataAction.php
- src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Apps/Internal/GetWizardDataActionEndToEnd.php
- src/Akeneo/Connectivity/Connection/front/src/connect/components/AppWizard/AppWizard.tsx
- src/Akeneo/Connectivity/Connection/front/src/connect/components/AppWizard/AuthenticationModal.tsx
- src/Akeneo/Connectivity/Connection/front/src/connect/components/AppWizard/steps/Authentication/Authentication.tsx
- src/Akeneo/Connectivity/Connection/front/src/connect/components/AppWizard/steps/Authentication/ConsentCheckbox.tsx
- src/Akeneo/Connectivity/Connection/front/src/connect/components/AppWizard/steps/Authorizations.tsx
- src/Akeneo/Connectivity/Connection/front/src/connect/hooks/use-fetch-app-wizard-data.ts
- src/Akeneo/Connectivity/Connection/front/src/model/Apps/wizard-data.ts
- src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/AppWizard/AppWizard.test.tsx
- src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/AppWizard/AuthenticationModal.test.tsx
- src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/AppWizard/steps/Authentication/Authentication.test.tsx
- src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/AppWizard/steps/Authentication/ConsentCheckbox.test.tsx
- src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/AppWizard/steps/Authorizations.test.tsx
- src/Akeneo/Connectivity/Connection/front/tests/src/connect/hooks/use-fetch-app-wizard-data.test.ts
Today users agree with the app privacy when connecting an app that requests authentication scopes. 
When these scopes are updated, we re-display the authentication step to warn our users that the app needs more information. They shouldn’t have to agree to the app privacy policy again. 
This is why, when the app updates its authentication scopes, we hide the agreement checkbox and only display the existing subtext as in the screenshot
> CXP-1177: Update legal text in the authentication step

- src/Akeneo/Category/back/Domain/ValueObject/Version/CategoryVersion.php
- src/Akeneo/Category/back/Infrastructure/Builder/CategoryVersionBuilder.php
- src/Akeneo/Category/back/tests/Integration/Infrastructure/Builder/CategoryVersionBuilderIntegration.php
Update the parent snapshot when the category is root. 
Means that when the category is root the snapshot parent has to be null and not an empty string. 
> GRF-728 Update snapshot parent when the category is root

- CHANGELOG-6.0.md
- src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Completeness/SqlSaveProductCompletenesses.php
- tests/back/Pim/Enrichment/EndToEnd/RemoveLocaleFromChannelEndToEnd.php
- tests/back/Pim/Enrichment/Integration/Storage/Sql/Completeness/SaveProductCompletenessesIntegration.php
Fixes database lock issues that occur when multiple parallel processing changes a lot of completeness rows.
This can happen especially when a lot of completeness records have to be updated at once (for instance, when the catalog contains a lot of channels/locales)
This fix tries to mitigate this issue by upserting rows in the completeness table, rather than deleting every row and re-inserting them. Identical rows are not updated anymore, thus resulting in less pressure on MySQL.
- without fix
- 33 deadlock
- 93 lock times
- 1 locking (Table lock)
- 37 lockwait dbal exception (DB lock timeout)
- with fix
- 115 deadlock
- 0 lock time
- 3 locking (Table lock) 
- 0 lockwait dbal exception (DB lock timeout) …
> Pim 10810: Optimize completeness saving

- CHANGELOG-6.0.md
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/Validator/ValidateProperties.php
- tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/SuccessListProductEndToEnd.php
Fixes a regression that prevented from searching on the "parent" property in the "list products" endpoints
> PIM-10834: Fix regression on parent filter in LIST products endpoint

- components/catalogs/front/jest.config.js
- front-packages/shared/jest.config.js
- src/Akeneo/Connectivity/Connection/front/jest.config.js
- src/Akeneo/Connectivity/Connection/workspaces/permission-form/jest.config.js
- src/Akeneo/Platform/Bundle/ImportExportBundle/front/jest.config.json
I removed an option we added few weeks ago to mitigate a memory leak inside jest. This option was unused due to incorrect jest version and we found another way to mitigate the memory leak.
> Revert "RAB-1124-divers: Add --workerIdleMemoryLimit=300MB"

- components/catalogs/front/src/components/ProductMapping/components/RequirementsCollapse.tsx
- components/catalogs/front/src/components/ProductMapping/components/SourcePanel.tsx
- components/catalogs/front/src/components/ProductMapping/models/Target.d.ts
First, really useful link when you are struggling with weird typescript stuff: https://www.typescriptlang.org/docs/handbook/utility-types.html
Then, instead of going into `[key: string]: any;` territory...
I'm proposing another version, which is more strict and will prevent us to have errors due to `any`.
I've commented the code in the PR because it's not obvious at first sight.
> CXP-1390: avoid 'any' in typescript

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/FlatToStandard/ColumnsMerger.php
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/FlatToStandard/Product.php
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/FlatToStandard/ProductModel.php
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/FlatToStandard/Value.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/FlatToStandard/ColumnsMergerSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/FlatToStandard/ProductModelSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/FlatToStandard/ProductSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/FlatToStandard/ValueSpec.php
In this PR, 
I fixed the fact that the product import standard does not work when the decimal separator is not `.` and the measurement/price value is a number in excel. We have this problem because in basic import we have to merge multiple column. When we do it we cast the number to string by default the cast contain a dot, now we cast with the decimal separator
> PIM-10823: Cannot import price and measurement with comma as decimal separator with value not saved as string in import file

- src/Akeneo/Platform/Bundle/InstallerBundle/Command/DatabaseCommand.php
- src/Akeneo/Platform/Bundle/InstallerBundle/Resources/config/cli_command.yml
We should use the logger instead of direct console output.
Console output is always detected as error on Datadog.
Advantages for using the logger:
- more correct log levels
- real logs with all the context information
- possibility to not ingest if not needed
- etc.
Cons:
- not displayed by default in the dev console, but it can be easily displayed by using a higher verbosity with the -vv parameter
In brief, more log control (and in the end maybe a lower billing :wink: )
> DatabaseCommand should not write on output

- CHANGELOG.md
- src/Akeneo/Tool/Bundle/BatchQueueBundle/Command/PublishJobToQueueCommand.php
- src/Akeneo/Tool/Component/BatchQueue/Queue/PublishJobToQueue.php
In this PR, I fixed the `akeneo:batch:publish-job-to-queue` that does not work anymore since email is an email
> PIM-10835: Fix command publish-job-to-queue does not work

- src/Akeneo/Platform/Bundle/InstallerBundle/Command/DatabaseCommand.php
- src/Akeneo/Tool/Component/Console/CommandExecutor.php
The CommandExecutor should only run a _Command_ and not a full _Application_.
With this PR, we find the command into the application and run it without having to trick exception handler or autoexit.
Also, I come to this PR while working on upper stack and having issues with logger, because the logger is kind of _reset_ when using Application::run. I didn't manage to find the exact inner reason, but just running the command canceled this side effect.
Last but not least, using the find method is the recommended way in the docs: https://symfony.com/doc/current/console/calling_commands.html
> PH-430: Use Application::find() to run the command in CommandExecutor

- src/Akeneo/Pim/Enrichment/Bundle/Command/MigrateToUuid/MigrateToUuidCommand.php
- src/Akeneo/Pim/Enrichment/Bundle/Command/MigrateToUuid/MigrateToUuidCompletenessTable.php
- src/Akeneo/Pim/Enrichment/Bundle/Command/MigrateToUuid/MigrateToUuidStep.php
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/cli_command.yml
- upgrades/test_schema/Version_7_0_20220429131804_execute_uuid_migration_Integration.php
Full process documentation : https://www.notion.so/akeneo/Accelerate-UUID-Migration-2de3f82092984c7cab713723531da46d#261a915eafef438fa0226565e8eed3e9
Short version : When upgrading database from v6 to v7, the process can take a very long time. One of the longest steps in a big database is the copy of product uuids to the pim_catalog_completeness table.
This PR changes how this table is populated, instead of inserting the uuid into the table, we create an empty copy of the table, in order to be able to insert the data without indexes/foreign keys to speed up the process.
> Improve performance completeness table's UUID Migration

- components/identifier-generator/front/src/feature/tabs/StructureTab.tsx
- components/identifier-generator/front/src/feature/tabs/structure/AddPropertyButton.tsx
- components/identifier-generator/front/src/feature/tabs/structure/__tests__/AddPropertyButton.test.tsx
Auto number can now only be added once in the structure
> CPM-881: Forbid auto number properties to be added twice

- CHANGELOG-6.0.md
- src/Akeneo/Platform/Bundle/AnalyticsBundle/Controller/ExternalApi/GetSystemInformationController.php
- tests/back/Platform/EndToEnd/ExternalApi/GetSystemInformationEndToEnd.php
- tests/back/Platform/Specification/Bundle/AnalyticsBundle/Controller/ExternalApi/GetSystemInformationControllerSpec.php
Backport of https://github.com/akeneo/pim-community-dev/pull/18980
As described in the [6.0 documentation](https://api.akeneo.com/api-reference-60.html#System):
- In a PaaS EE env, do a GET {{url}}/api/rest/v1/system-information call, the edition returned should be 'EE'
- In a PaaS CE env, do a GET {{url}}/api/rest/v1/system-information call, the edition returned should be 'CE'
related EE PR: https://github.com/akeneo/pim-enterprise-dev/pull/16389
> PIM-10826: Fix GET system-information endpoint with wrong answers

- CHANGELOG.md
- src/Akeneo/Pim/Structure/Bundle/Query/PublicApi/Association/Sql/SqlGetAssociationTypes.php
- tests/back/Pim/Structure/Integration/AssociationType/Query/SqlGetAssociationTypesIntegration.php
In this PR I reworked the SqlGetAssociationTypes query to avoid the GROUP_CONCAT limit
> PIM-10843: Rework query to avoid issue with group concat max lenght limit

- CHANGELOG.md
- src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/abstract-filter.js
- src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/search-filter.js
Add a `\` before special characters.
> PIM-10828: Search bars don't take into account special characters

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Connector/SqlGetConnectorProductsWithOptions.php
- src/Akeneo/Pim/Structure/Bundle/Form/Type/AttributeOptionType.php
- src/Akeneo/Pim/Structure/Component/Normalizer/Standard/AttributeOptionNormalizer.php
- tests/back/Pim/Enrichment/Integration/Storage/Sql/Connector/SqlGetConnectorProductsWithOptionsIntegration.php
- tests/back/Pim/Structure/EndToEnd/AttributeOption/ExternalApi/GetAttributeOptionEndToEnd.php
- tests/back/Pim/Structure/Specification/Bundle/Form/Type/AttributeOptionTypeSpec.php
When updating an attribute option from the attribute edit form UI, empty labels were inserted anyway in the `pim_catalog_attribute_option_value` table (with value = NULL). This happened only in the UI, because it still uses a Symfony form, as opposed to import and API (which use the repo/factory/updater/saver stack)
This led to inconsistencies in the API, because such null labels were returned, unlike for other PIM entities
In this PR:
- I make sure null attribute option labels are not returned anymore
- and that null labels are not inserted anymore when using the UI
> PIM-10844: Filter empty attribute option labels

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Sorter/Field/CompletenessSorter.php
- tests/back/Pim/Enrichment/Integration/PQB/Sorter/CompletenessSorterIntegration.php
- tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Sorter/Field/CompletenessSorterSpec.php
Adds an `unmapped_type`  parameter in the completeness sort clause, in order to avoid the "No mapping found for [completeness.channel.locale] in order to sort on" Elasticsearch error
> PIM-10849: Fix sorting datagrid on completeness when the selected locale is not supported by the channel

- CHANGELOG.md
- src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/SftpStorageConfigurator.test.tsx
- src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/SftpStorageConfigurator.tsx
- src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/models/Storage.ts
see https://akeneo.atlassian.net/browse/PIM-10858
We don't remove password property from a storage when we pass from a password type storage to a private key storage. That leads to validation error in back and disallow user to save a valid form.
> PIM-10858: Fix password is set on sftp storage using private key

- CHANGELOG-6.0.md
- src/Akeneo/Platform/Bundle/FrameworkBundle/Command/CheckUpdateRequirementsCommand.php
- src/Akeneo/Platform/Bundle/FrameworkBundle/Resources/config/services.yml
- src/Akeneo/Tool/Bundle/ElasticsearchBundle/Command/UpdateIndexVersionCommand.php
- src/Akeneo/Tool/Bundle/ElasticsearchBundle/Infrastructure/Client/IndexUpdaterClient.php
- src/Akeneo/Tool/Bundle/ElasticsearchBundle/Resources/config/commands.yml
- src/Akeneo/Tool/Bundle/ElasticsearchBundle/Resources/config/services.yml
- src/Akeneo/Tool/Bundle/ElasticsearchBundle/tests/integration/UpdateIndexVersionIntegration.php
In this PR, I added a command in order to check elasticsearch index creation version. 
**Why ?** 
Because in flex v7 the elasticsearch version have been bump to 8.4 before updating the elasticsearch version we need to check that all elasticsearch version have been created with at least elasticsearch 7.
This command will display the elasticsearch indexes to migrate if there is some index have been created with Elasticsearch 6
**Example of display (Error)**
**Example of display (Success)**
> RAB-1353: Add script to check elasticsearch index have been created with Elasticsearch 7

- CHANGELOG.md
- src/Akeneo/Pim/Structure/Bundle/EventSubscriber/SaveFamilyVariantOnFamilyUpdateSubscriber.php
- tests/back/Pim/Structure/Specification/Bundle/EventSubscriber/SaveFamilyVariantOnFamilyUpdateSubscriberSpec.php
- tests/legacy/features/pim/structure/family/mass_edit_families.feature
When unique attributes are added through the Mass Action workflow, the family variant were not updated.
It was due to the fact that the subject in `onBulkSave` was considered to be a FamilyInterface but was really an array of FamilyInterface.
> PIM-10853: Fix type checking in SaveFamilyVariantOnFamilyUpdate bulk action

- Makefile
- bin/benchmark_products_api.sh
- src/Akeneo/Platform/Bundle/InstallerBundle/Command/DatabaseCommand.php
- std-build/Makefile
- tests/back/Pim/Enrichment/Integration/Product/V20220729171405DropProductIdColumnsAndCleanVersioningResourceUuidColumnsIntegration.php
- upgrades/test_schema/Version_7_0_20220429131804_execute_uuid_migration_Integration.php
- upgrades/test_schema/Version_7_0_20220927080024_add_identifier_generator_table_Integration.php
- upgrades/test_schema/Version_7_0_20230201143400_drop_product_id_columns_and_clean_versioning_resource_uuid_columns_Integration.php
When launching PIM installation, the default behavior is to drop the whole existing database.
:warning: **_It can be very dangerous if launched on client data._**
There is a `doNotDropDatabase` option, but this option will also drop the schema (not the database). 
:warning: **_It is still very dangerous, not less than previous one in fact._**
Dropping database and/or schema is a developer need, and we can remove the dangerous SQL commands from the PIM installer command and move them in Makefile used by developers.
> PIM-10846: PIM installer does not drop database/schema

- CHANGELOG.md
- src/Akeneo/Pim/Structure/Bundle/EventSubscriber/TimestampableAttributeSubscriber.php
- src/Akeneo/Pim/Structure/Bundle/Resources/config/event_subscribers.yml
- tests/back/Pim/Structure/Integration/Attribute/UpdateAttributeDateIntegration.php
**Current behavior**:
The `update` column for the attribute is updated thanks to the `AddVersionSubscriber`.
The old version and new versions are compared and if there is a difference, a version is created and the column `update` is updated. But in the attribute options normalizer used for the AddVersionSubscriber, only the 10000 first options are retrieved.
**Problem**:
When an option is added to an attribute already having 10000 options, there is no change detected and the update column is not updated.
**Solution**:
We add a Subscriber on `preSave and `preRemove` for the AttributeOptionInterface. So that its attribute `update` property is updated every time an option is added/removed.
> PIM-10840: Fix attribute update date on attribute options change above 10000 options

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/.php_cd.php
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/jobs.yml
- src/Akeneo/Pim/Enrichment/Component/Product/Job/ComputeCompletenessOfProductsFamilyTasklet.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Job/ComputeCompletenessOfProductsFamilyTaskletSpec.php
When removing an attribute from a family, two jobs are launched : 
- compute_completeness_of_products_family
- compute_family_variant_structure_changes
in some cases the former could override the changes performed by the latter because it would force save the concerned products.  
In this fix, the product are not saved anymore, we only recompute the completeness and reindex them.
> PIM-10832: Fix compute completeness job

- src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetCategoriesSql.php
- src/Akeneo/Category/back/tests/Integration/Helper/CategoryTestCase.php
- src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetCategoriesSqlIntegration.php
Update the API REST end point to get enriched categories **category tree and their child with enriched values**  if the template is not deactivated.
(/api/rest/v1/categories?with_position=true&page=1&with_enriched_attributes=true&search={"code":[{"operator":"IN","value":["print", "print_accessories", "print_clothing", "print_shoes"]}]})
(/api/rest/v1/categories/print_accessories?with_enriched_attributes=true)
> GRF-771 : Update get categories SQL

- CHANGELOG-6.0.md
- src/Akeneo/Channel/.php_cd.php
- src/Akeneo/Channel/Component/Query/PublicApi/Cache/CachedChannelExistsWithLocale.php
- src/Akeneo/Channel/Component/Query/PublicApi/GetCaseSensitiveChannelCodeInterface.php
- src/Akeneo/Channel/Component/Query/PublicApi/GetCaseSensitiveLocaleCodeInterface.php
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/factories.yml
- src/Akeneo/Pim/Enrichment/Component/Product/Factory/NonExistentValuesFilter/NonExistentChannelLocaleValuesFilter.php
- tests/back/Channel/Specification/Component/Query/PublicApi/Cache/CachedChannelExistsWithLocaleSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Factory/NonExistentValuesFilter/NonExistentChannelLocaleValuesFilterSpec.php
How to reproduce this bug ?
Simple put this kind of values in a product:
```
"localizablescopableprice": {"ecommerCe": {"en_us": [{"amount": "12.00", "currency": "EUR"}, {"amount": "37.00", "currency": "USD"}]}}}
```
The case of ecommerce and en_US is not the right one and values are filtered before normalization, so do not appear on PEF. This PR fixes it
> Fix PEF display for localizable and scopable values with wrong case

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/CountItemsWithAttributeValueAction.php
- src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/ProductAndProductModel/CountProductModelsWithRemovedAttribute.php
- src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/ProductAndProductModel/CountProductsWithRemovedAttribute.php
- src/Akeneo/Pim/Enrichment/Component/Product/Query/CountProductModelsWithRemovedAttributeInterface.php
- src/Akeneo/Pim/Enrichment/Component/Product/Query/CountProductsWithRemovedAttributeInterface.php
- src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/attribute/form/delete/DeleteModal.tsx
- tests/back/Pim/Enrichment/Integration/Fixture/ProductAndProductModelWithRemovedAttributeLoader.php
- tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductAndProductModel/CountProductModelsWithRemovedAttributeIntegration.php
- tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductAndProductModel/CountProductsWithRemovedAttributeIntegration.php
- tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductAndProductModel/GetAllProductIntegration.php
- tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductAndProductModel/GetProductExistingAmongIntegration.php
- tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductAndProductModel/GetProductIdentifiersWithRemovedAttributeIntegration.php
- tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductAndProductModel/GetProductModelIdentifiersWithRemovedAttributeIntegration.php
- tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductAndProductModel/GetProductNotSynchronisedBetweenEsAndMysqlIntegration.php
I fixed a regression introduced by a previous fix on completeness calculation. This query should be able to count products with or without values for attribute codes passed in params.
see https://akeneo.atlassian.net/browse/PIM-10791
> PIM-10855: Fix products and models with empty attribute values are counted by CountItemsWithAttributeValueAction

- src/Akeneo/Pim/Structure/Bundle/Controller/InternalApi/MassDeleteAttributeController.php
- src/Akeneo/Pim/Structure/Bundle/Resources/config/controllers.yml
- src/Akeneo/Pim/Structure/Bundle/Resources/config/routing/internal_api/attribute.yml
- src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/action/attribute-mass-delete-action.ts
In this PR, 
I just a factorization, now we used a dedicated controller to launch a attribute mass delete job instead of using the MassEdit controller of Enrichment. By this way we decouple your self to enrichment when we are going to work on ACL we can do the necessary checks.
Email and notification already work perfectly
> RAB-1263: Create a dedicated controller for mass delete attributes instead of using enrichment one

- components/identifier-generator/front/src/feature/hooks/useGetFamilies.ts
There is a cache on queries with react-query
When we did a call for having the families from another component, then wanted to have the same call but updating the "limit", the cache was telling is that we already having this result, which is not the case.
We added the limit to the parameters able to change and calling a new call.
> CPM-986: Fix cache on get families

- front-packages/shared/src/components/DoubleCheckDeleteModal.tsx
- src/Akeneo/Pim/Structure/Bundle/Controller/InternalApi/AttributeGroupController.php
- src/Akeneo/Pim/Structure/Bundle/EventSubscriber/CheckAttributeGroupOtherCannotBeRemovedSubscriber.php
- src/Akeneo/Pim/Structure/Bundle/EventSubscriber/CheckAttributeGroupWithAttributeCannotBeRemovedSubscriber.php
- src/Akeneo/Pim/Structure/Bundle/Resources/config/controllers.yml
- src/Akeneo/Pim/Structure/Bundle/Resources/config/event_subscribers.yml
- src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml
- src/Akeneo/Pim/Structure/Bundle/Resources/translations/messages.en_US.yml
- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/attribute-groups/MassDeleteAttributeGroupsModal.tsx
- src/Akeneo/Pim/Structure/Component/Exception/AttributeGroupOtherCannotBeRemoved.php
- src/Akeneo/Pim/Structure/Component/Exception/AttributeGroupWithAttributeCannotBeRemoved.php
- src/Akeneo/Pim/Structure/Component/Exception/UserFacingError.php
- tests/back/Pim/Structure/Integration/AttributeGroup/EventSubscriber/CheckAttributeGroupOtherCannotBeRemovedSubscriberIntegration.php
- tests/back/Pim/Structure/Integration/AttributeGroup/EventSubscriber/CheckAttributeGroupWithAttributeCannotBeRemovedSubscriberIntegration.php
In this PR, 
- I move all check before deletion into a dedicated subscriber, by this way we will have those check in mass delete 
- I also call on confirm on DoubleCheckModalDeletion when user hit Enter on confirmation input
- I fixed some translations that are not plurialized
> RAB-1287: Move delete attribute groups error into a dedicated subscriber 

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/VersioningController.php
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/localization/presenters.yml
- src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Product/SqlFindProductIdentifier.php
- src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/VersionNormalizer.php
- src/Akeneo/Pim/Enrichment/Component/Product/Query/FindIdentifier.php
- src/Akeneo/Tool/Component/Localization/Presenter/ProductQuantifiedAssociationPresenter.php
- src/Akeneo/Tool/Component/Localization/spec/Presenter/ProductQuantifiedAssociationPresenterSpec.php
- tests/back/Pim/Enrichment/Integration/Storage/Sql/Product/SqlFindProductIdentifierIntegration.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/InternalApi/VersionNormalizerSpec.php
If associations with quantities are used with products that all have SKUs, UUID are displayed in the history.
Identifiers shall be displayed in product history.
**Example with associated products** (one with identifier, one without identifier)
> PIM-10745: Fix history display for product's quantified association

- src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml
- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/attribute-groups/AttributeGroupsDataGrid.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/attribute-groups/MassDeleteAttributeGroupsModal.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/attribute-groups/index.ts
- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/models/AttributeGroup.ts
- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/AttributeGroupsIndex.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/components/shared/datagrids/attribute-groups/MassDeleteAttributeGroupsModal.unit.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/models/AttributeGroup.unit.ts
- Disable Drag n Drop when search value is not empty
- Add link to edit attribute group page on row click
- Change Attribute group name header to Label
- Set Attribute group label to brand100 (row title to true)
- Fix attribute children count when select all then unselect one attribute group & Fix target attribute group list when select all then unselect one attribute group with custom utility hook
> RAB-1358: Fixes after breakit on bulk delete attribute groups

- src/Akeneo/Category/back/tests/Integration/ServiceApi/CategoryQueryIntegration.php
Passing a Generator for the parameter corresponding to the haystack in the `assertCount` method is deprecated and will be removed in PHPUnit 10, we have to convert it to array.
> Fix integration test on Category BC

- CHANGELOG.md
- src/Akeneo/Category/back/ServiceApi/ExternalApiCategory.php
- src/Akeneo/Category/back/tests/Integration/ServiceApi/ExternalApiCategoryIntegration.php
Empty labels for categories are given by the API as an array while the [documentation mentions an object](https://api.akeneo.com/api-reference.html#get_categories__code_):
After fix :
> PIM-10874 : fix labels api type consistency

- components/identifier-generator/front/src/feature/components/NomenclatureEdit.tsx
Disables the "Edit nomenclature button" in Structure tab when the user has only view permissions on identifier generators
> CPM-989: Disable the edit nomenclature button in read-only mode

- front-packages/akeneo-design-system/src/components/Input/DateInput/DateInput.tsx
Fix the style conflicts when the InputDate is used in the PIM. The icon size is collapsed and the icon is not visible. The fix sets the a wrapper container around the icon to apply the background and hide the native datepicker icon for Firefox.
Expected in the storybook
Integration in the PIM
> Fix box-sizing reset issue with the svg icons

- front-packages/akeneo-design-system/src/components/IconCard/IconCard.tsx
When an IconCardGrid has only one child IconCard, it takes up the whole grid width, which feels a little weird. This PR makes sure IconCards have a maximum width
Before:
After:
> CPM-985: Fix maximum width for IconCardGrid

- src/Akeneo/Pim/Enrichment/Product/back/API/Query/GetProductCategoryCodesQuery.php
- src/Akeneo/Pim/Enrichment/Product/back/Application/Applier/AddCategoriesApplier.php
- src/Akeneo/Pim/Enrichment/Product/back/Application/Applier/RemoveCategoriesApplier.php
- src/Akeneo/Pim/Enrichment/Product/back/Application/Category/GetProductCategoryCodesHandler.php
- src/Akeneo/Pim/Enrichment/Product/back/Domain/Query/GetCategoryCodes.php
- src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Query/SqlGetCategoryCodes.php
- src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Symfony/Resources/config/handlers.yml
- src/Akeneo/Pim/Enrichment/Product/back/Test/Acceptance/InMemory/InMemoryGetCategoryCodes.php
- src/Akeneo/Pim/Enrichment/Product/back/Test/Acceptance/Specification/InMemory/InMemoryGetCategoryCodesSpec.php
- src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/EnrichmentProductTestCase.php
- src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/Category/GetProductCategoryCodesHandlerIntegration.php
- src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Query/SqlGetCategoryCodesIntegration.php
- src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Application/Applier/AddCategoriesApplierSpec.php
- src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Application/Applier/RemoveCategoriesApplierSpec.php
- tests/back/Category/Integration/Query/SqlGetCategoryCodesIntegration.php
Expose the GetCategoryCodes query in Enrichment service API, so it can be used by external contexts. I also removed the deprecated `fromProductIdentifiers()` method.
> CPM-998: Expose GetCategoryCodes query in Enrichment service API

- components/identifier-generator/back/src/Domain/Model/Property/SimpleSelectProperty.php
- components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/CreateIdentifierGeneratorWithSimpleSelectEndToEnd.php
- components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/GetIdentifierGeneratorControllerEndToEnd.php
- components/identifier-generator/back/tests/Specification/Domain/Model/Property/SimpleSelectPropertySpec.php
- components/identifier-generator/front/src/feature/hooks/useGetAttributeByCode.ts
SimpleSelectProperty 's `normalize` function used to retrieve scope and locale even if value is null.
But in the UpdateIdentifierGenerator validators, we require scope and locale not to be passed if not needed
> CPM-1002: Fix SimpleSelectProperty normalize to not retrieve scope and locale if not needed

- make-file/user-management.mk
- phpspec.yml.dist
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Apps/commands.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Audit/commands.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Connections/command.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/ErrorManagement/commands.yml
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Webhook/commands.yml
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/cli_command.yml
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/command.yml
- src/Akeneo/Pim/Structure/Bundle/Resources/config/commands.yml
- src/Akeneo/Platform/Bundle/AnalyticsBundle/Resources/config/commands.yml
- src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/services.yml
- src/Akeneo/Platform/Bundle/InstallerBundle/Resources/config/cli_command.yml
- src/Akeneo/Tool/Bundle/ApiBundle/Resources/config/cli_commands.yml
- src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/cli_commands.yml
- src/Akeneo/Tool/Bundle/BatchQueueBundle/Resources/config/services.yml
- src/Akeneo/Tool/Bundle/ElasticsearchBundle/Resources/config/commands.yml
- src/Akeneo/Tool/Bundle/FileStorageBundle/Resources/config/cli_commands.yml
- src/Akeneo/Tool/Bundle/VersioningBundle/Resources/config/cli_commands.yml
- src/Akeneo/UserManagement/Bundle/DependencyInjection/Compiler/RegisterCommandsThatNeedUserSystemPass.php
- src/Akeneo/UserManagement/Bundle/PimUserBundle.php
- src/Akeneo/UserManagement/Bundle/Resources/config/commands.yml
- src/Akeneo/UserManagement/Bundle/Resources/config/event_subscribers.yml
- src/Akeneo/UserManagement/back/Infrastructure/Cli/EventListener/AuthenticateCommandAsAdminUser.php
- src/Akeneo/UserManagement/back/Infrastructure/Cli/EventListener/AuthenticateCommandAsAdminUserListener.php
- src/Akeneo/UserManagement/back/Infrastructure/Cli/Registry/AuthenticatedAsAdminCommandRegistry.php
- src/Akeneo/UserManagement/back/tests/Integration/Infrastructure/Cli/EventListener/AuthenticateCommandAsAdminUserIntegration.php
- src/Akeneo/UserManagement/back/tests/Integration/Infrastructure/Cli/EventListener/AuthenticateCommandAsAdminUserListenerIntegration.php
- src/Akeneo/UserManagement/back/tests/Specification/Infrastructure/Cli/Registry/AuthenticatedAsAdminCommandRegistrySpec.php
While benchmarking a simple Symfony command execution in the PIM, we detected that a significant number of undesirable services (as Doctrine ORM) were called and took a significant amount of time. At the origin of this is a legacy listener that automatically authenticate an admin system user to every Akeneo/PIM Symfony commands (command names that started by `pim` or `akeneo`)  https://github.com/akeneo/pim-community-dev/blob/master/src/Akeneo/UserManagement/Bundle/EventListener/CreateUserSystemListener.php
In our case we need to be able to run a command as fast as possible, so we don't want to trigger this listener. And in a more global case, this authentication is useless for most of the PIM commands. It's mandatory only for process that involve permissions.
So we decided to trigger …
> JEL-239: Create User System for tagged commands

- components/identifier-generator/back/src/Infrastructure/Query/SqlGetSequencedNextIdentifierQuery.php
- components/identifier-generator/back/src/Infrastructure/Query/SqlUpdateIdentifierPrefixesQuery.php
- components/identifier-generator/back/src/Infrastructure/Repository/SqlIdentifierGeneratorRepository.php
We had to be sure that queries can be executed with or without migrations.
As every migration is done on prod, we can remove them.
> fix-performance-tests

- front-packages/shared/src/components/DoubleCheckDeleteModal.tsx
- front-packages/shared/src/components/DoubleCheckDeleteModal.unit.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/attribute-groups/MassDeleteAttributeGroupsModal.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/components/shared/datagrids/attribute-groups/MassDeleteAttributeGroupsModal.unit.tsx
In this PR, I tried to fix 2 UI glitchs : 
- We need to reset `MassDeleteAttributeGroupsModal` state to avoid having the replacement attribute group kept between different selection
- We need to override the `onChange` props of `DeleteModal` to avoid user bypassing double check (the modal still closes when user hints `Enter` : I don't know if I can disallow that and if there is a real interest as the job is not launched anymore)
> RAB-1365: Bug fix on mass delete attribute group

- components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/Product/IsProductBelongingToCatalogQueryTest.php
- src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Field/CategoryFilter.php
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/query_builders.yml
- tests/back/Pim/Enrichment/Integration/PQB/Filter/Field/CategoryFilterIntegration.php
- tests/back/Pim/Enrichment/Integration/ProductQueryBuilder/Filter/CategoryFilterIntegration.php
- tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Filter/Field/CategoryFilterSpec.php
Add the "IS NOT EMPTY" filter for Category in order to use it with the ProductQueryBuilder
> CXP-1415: Add IS NOT EMPTY to CategoryFilter to use it on the ProductQueryBuilder

- src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/FollowUp/GetCompletenessPerChannelAndLocale.php
- src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/helpers/convertBackendDashboardCompletenessData.ts
- src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/tests/front/unit/helpers/convertBackendDashboardCompletenessData.unit.ts
- tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/FollowUp/GetCompletenessPerChannelAndLocaleIntegration.php
The completeness ratio of a channel on the Activity dashboard is not well calculated. It should be the percent of products that have 100% completeness on all locales on that channel.
I reworked the ES query to do the calculation with aggregations.
Example for 4 products, with 2 products fully enriched on all locales
Before:
After:
> PIM-10861: Fix calcuation of completeness channel ratio on Activity Dashboard

- src/Akeneo/Channel/back/API/Query/Channel.php
- src/Akeneo/Channel/back/API/Query/ConversionUnitCollection.php
- src/Akeneo/Channel/back/Infrastructure/Query/Sql/SqlFindChannels.php
- src/Akeneo/Channel/back/tests/Integration/Query/Sql/SqlFindChannelsIntegration.php
- src/Akeneo/Channel/back/tests/Specification/API/Query/ChannelSpec.php
- src/Akeneo/Channel/back/tests/Specification/API/Query/ConversionUnitCollectionSpec.php
- src/Akeneo/Channel/back/tests/Specification/Infrastructure/Query/Cache/CachedFindChannelsSpec.php
- src/Akeneo/Pim/Structure/.php_cd.php
- src/Akeneo/Pim/Structure/Bundle/EventSubscriber/CheckAttributeIsNotUsedAsChannelConversionUnitOnDeletionSubscriber.php
- src/Akeneo/Pim/Structure/Bundle/Resources/config/event_subscribers.yml
I extended the Channel read model exposed by the Channel Service API to add it the conversion units. That's allow us to use it inside Structure domain for checking attribute deletion.
> RAB-1357: Update and use cached channels query in attribute deletion check

- src/Akeneo/Pim/Structure/Bundle/Query/PublicApi/Family/Sql/SqlGetFamilies.php
- src/Akeneo/Pim/Structure/Bundle/Resources/config/queries.yml
- src/Akeneo/Pim/Structure/Component/Query/PublicApi/Family/Family.php
- src/Akeneo/Pim/Structure/Component/Query/PublicApi/Family/GetFamilies.php
- tests/back/Pim/Structure/Integration/Family/SqlGetFamilyIntegration.php
This PR adds a new public service API in the structure context to get a list of families (or a single one too), that returns basic generic Family read models. We needed this service API for Supplier Portal needs. For now the read model only has what we needed in our side (code and labels), but it should be easy to add new properties if needed.
As discussed with Mathias, there is not LRU cache implementation for now, we thought it would not be needed at this point.
> SP-490: add a service API to retrieve a list of families or a single Family

- src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/OAuth/CreateJsonWebToken.php
- src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Apps/OAuth/CreateJsonWebTokenSpec.php
Added email_verified claim to JWT token when App requests email OpenId scope and set it to false as PIM does not verify its emails and PIM users are free to put anything as email
> OCT-233: Added email_verified claim to JWT token

- front-packages/akeneo-design-system/src/components/Input/SelectInput/SelectInput.tsx
According to the Dashlane doc, setting `data-form-type` to "other" prevents the autocomplete.
https://support.dashlane.com/hc/en-us/articles/4420122792594-Optimize-your-web-forms-for-Dashlane-Autofill
> CPM-978: Prevent Dashlane from triggering on select inputs

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/VersionNormalizer.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/InternalApi/VersionNormalizerSpec.php
PHP convert type to int when key is numeric.
`strpos` and `substr` use only string
So we need to cast before calling this functions
> PIM-10915: fix dynamic typing to cast to string

- front-packages/shared/src/components/Navigation/PimNavigation.tsx
- front-packages/shared/src/components/Navigation/PimNavigation.unit.tsx
- src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_US.yml
Previous PR was reverted because a useless menu was added and broke Onboarder.
Then, a regression was detected on trial because there is a chatbot button on the bottom left of the screen.
The solution is to add the new menu entries next to the menu, and add a very high z-index to be higher than the one used for the tria chatbot.
> CPM-951: Add sub entries to help menu

- components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductMapping/ProductMappingRespectsSchemaTest.php
The first goal was to add :
- One case where the source does not match the target type + format
- One case where a required target has no source
- One required field in the valid schema test case.
I took advantage of this development to refactor. Now we have :
- Only one place to run `createAttribute` method. 
- Only one schema (versus three)
- A assert on the number of violations to consolidate the tests
- Data providers to simplify the adding of new tests
We can imagine in the future to make optional the check the number of violations.
> OCT-232: add tests and refacto

- CHANGELOG.md
- src/Akeneo/Tool/Bundle/FileStorageBundle/Command/V20230324153137AddIndexOnFileInfoZddMigration.php
- src/Akeneo/Tool/Bundle/FileStorageBundle/Resources/config/cli_commands.yml
- src/Akeneo/Tool/Bundle/FileStorageBundle/Resources/config/model/doctrine/FileInfo.orm.yml
- tests/back/Tool/Integration/FileStorage/Command/V20230324153137AddIndexOnFileInfoZddMigrationIntegration.php
Some instance could have a lot of files (several millions). That leads to performance issues when we want to query the file info table to retrieve if a file is already stored. To resolve this issue, I added a ZDD migration which add an index on `original_name`, `hash` and `storage` columns of `akeneo_file_storage_file_info` table.
On the impacted instance, the query pass from more of 1m to less than 1s.
> PIM-10908: Add zdd migration to add an index on akeneo_file_storage_file_info

- components/catalogs/back/src/Application/Handler/GetMappedProductsHandler.php
- components/catalogs/back/src/Application/Persistence/WarmupAwareQueryInterface.php
- components/catalogs/back/src/Application/Persistence/WarmupableQueryInterface.php
- components/catalogs/back/src/Infrastructure/Persistence/Category/GetProductCategoriesLabelsQuery.php
- components/catalogs/back/src/Infrastructure/Symfony/DependencyInjection/AkeneoCatalogsExtension.php
- components/catalogs/back/src/Infrastructure/Symfony/Resources/config/buses.yml
- components/catalogs/back/src/Infrastructure/Symfony/Resources/config/event_subscribers.yml
- components/catalogs/back/src/Infrastructure/Symfony/Resources/config/queries.yml
- components/catalogs/back/src/Infrastructure/Symfony/Resources/config/services.yml
- components/catalogs/back/src/Infrastructure/Symfony/Resources/config/validation.yml
In this PR, I introduce 2 improvements:
- split services.yml in multiple files to add clarity
- remove the use of `method_exists()` by adding an interface
> OCT-code-improvements: use interface instead of method_exists, split services.yml

- src/Akeneo/Pim/Structure/Bundle/Query/PublicApi/Attribute/Sql/SqlGetAttributes.php
- src/Akeneo/Pim/Structure/Component/Query/PublicApi/AttributeType/Attribute.php
- tests/back/Pim/Structure/Integration/Attribute/Query/SqlGetAttributesIntegration.php
We needed to enrich the GetAttributes public API by adding labels for Supplier Portal needs. It has been decided with @akeneo/squad-chipmunks to only return the available labels (if any) and not the labels of all the locales with a null value if there is no label.
> SP-463: add labels in GetAttributes public API

- src/Akeneo/Pim/Structure/Bundle/Query/PublicApi/Family/Sql/SqlGetFamilies.php
- src/Akeneo/Pim/Structure/Component/Query/PublicApi/Family/Family.php
- tests/back/Pim/Structure/Integration/Family/SqlGetFamilyIntegration.php
Update existing public service API introduce by https://github.com/akeneo/pim-community-dev/pull/19438
Add a flat array of family attribute codes
> SP-489: Add attribute codes in `SqlGetFamilies` query of `Structure` context public Api

- CHANGELOG.md
- src/Akeneo/Pim/Structure/.php_cd.php
- src/Akeneo/Pim/Structure/Bundle/Datagrid/Attribute/AttributeFilter.php
- src/Akeneo/Pim/Structure/Bundle/Resources/config/datagrid/attribute.yml
- src/Akeneo/Pim/Structure/Bundle/Resources/config/services.yml
- src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_US.yml
- src/Oro/Bundle/FilterBundle/Datasource/ExpressionBuilderInterface.php
- src/Oro/Bundle/FilterBundle/Datasource/Orm/OrmExpressionBuilder.php
- src/Oro/Bundle/PimDataGridBundle/Resources/config/requirejs.yml
- tests/legacy/features/pim/structure/attribute/browse/filter.feature
When attribute mass delete have been release we removed the search by code filter have we believed that we can search by code on attribute group page. 
In this PR, I added the possibility to search by attribute code and attribute label, to do it I added a new oro filter that handle it
> PIM-10925: The search by code is missing on the attribute page

- CHANGELOG.md
- src/Akeneo/Channel/back/Infrastructure/Component/Model/Channel.php
- src/Akeneo/Channel/back/Infrastructure/Component/Model/Locale.php
- src/Akeneo/Channel/back/Infrastructure/Component/Model/LocaleInterface.php
- src/Akeneo/Channel/back/Infrastructure/Component/Updater/ChannelUpdater.php
- src/Akeneo/Channel/back/Infrastructure/EventListener/ChannelLocaleSubscriber.php
- src/Akeneo/Channel/back/Infrastructure/EventListener/RemoveLocalesFromChannelSubscriber.php
- src/Akeneo/Channel/back/Infrastructure/Processor/Denormalization/ChannelProcessor.php
- src/Akeneo/Channel/back/Infrastructure/Symfony/Resources/config/doctrine/model/Locale.orm.yml
- src/Akeneo/Channel/back/Infrastructure/Symfony/Resources/config/processors.yml
- src/Akeneo/Channel/back/Infrastructure/Symfony/Resources/config/services.yml
- src/Akeneo/Channel/back/tests/Integration/ChannelTestCase.php
- src/Akeneo/Channel/back/tests/Specification/Infrastructure/Processor/Denormalization/ChannelProcessorSpec.php
- tests/back/Acceptance/Channel/ChannelContext.php
- tests/back/Acceptance/Locale/LocaleContext.php
- tests/back/Channel/Specification/Infrastructure/Component/Updater/ChannelUpdaterSpec.php
- tests/back/Channel/Specification/Infrastructure/EventListener/ChannelLocaleSubscriberSpec.php
- tests/back/Channel/Specification/Infrastructure/EventListener/RemoveLocalesFromChannelSubscriberSpec.php
- tests/back/Pim/Enrichment/EndToEnd/RemoveLocaleFromChannelEndToEnd.php
- tests/features/channel/locale/locale_status.feature
Prevent channel creation on validation error during import
- Create channel processor from generic to remove association between channels and locales on new channels
- Update `ChannelLocaleSubscriber` in order to save locale updates only on **POST** events 
- Remove cascade persist between from Locale To channels
- Update acceptance test to check activation/deactivation of locale
> PIM-10887 :  Prevent channel creation on validation error during import

- CHANGELOG.md
- src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetCategoriesSql.php
Temporary rollback of a fix that cause performance issue on the categories Rest API.
> PIM-10955: rollback PIM-10916 to fix perf issue on categories API

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/NumberValueFactory.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Factory/Value/NumberValueFactorySpec.php
If data has been corrupted and contains a white space, the user cannot save the product anymore.
So we make sure to trim the number data if it's a string
> PIM-10932: Fix data in NumberValueFactory if data contains a white space

- CHANGELOG.md
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/pim-wysiwyg.js
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/field/wysiwyg-field.js
Add "dir" option to "auto" for textarea Wysiwyg in order to support rtl and ltr languages.
> PIM-10814: Wysiwyg now supports languages that use rtl

- CHANGELOG.md
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/ProductEvaluation/CompleteEvaluationWithImprovableAttributes.php
- src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Application/ProductEvaluation/CompleteEvaluationWithImprovableAttributesSpec.php
In some cases the rates of the persisted result are different from the one just calculated. It can happen when the required attributes list of a family has been changed, but the impacted products have not been re-evaluated yet (by the cron job)
The simplest solution is to replace the rates to be always accurate with the list of improvable attributes
> PIM-10967: Fix inconsistency on DQI completeness recommendation

- CHANGELOG.md
- src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/contexts/AttributeOptionsContextProvider.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/components/AttributeOptionTable.unit.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/components/Edit.unit.tsx
For a multi-select attribute, client notices that by adding a label option and clicking "done", an option that has been dragged at the top of the list just beforehand, goes back to the previous position. 
> PIM-10958: Fix attribute option position after clicking on "done"

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Completeness/VariantProductRatio.php
- src/Akeneo/Pim/Enrichment/Component/Product/ProductModel/Query/CompleteVariantProducts.php
- tests/back/Pim/Enrichment/Integration/Storage/Sql/Completeness/VariantProductRatioIntegration.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/InternalApi/LightEntityWithFamilyVariantNormalizerSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/ProductModel/Query/CompleteVariantProductsSpec.php
The variant counter used to be wrong if several variant products had an empty identifier:
> PIM-10976: Fix variant product counter on Product Model Edit Form for variant products without identifier

- CHANGELOG-6.0.md
- src/Akeneo/Platform/Bundle/FrameworkBundle/Command/CheckUpdateRequirementsCommand.php
- src/Akeneo/Tool/Bundle/ElasticsearchBundle/Command/UpdateIndexVersionCommand.php
- src/Akeneo/Tool/Bundle/ElasticsearchBundle/Infrastructure/Client/IndexUpdaterClient.php
- src/Akeneo/Tool/Bundle/ElasticsearchBundle/tests/integration/UpdateIndexVersionIntegration.php
In this PR:
- We fixed the `pim:update:check-requirements` command: this command check the index version and check if the index is used by the PIM, problem is that it compare an alias name with an index name. We fixed it, now it compare the alias names.
- We fixed the `akeneo:elasticsearch:update-index-version`: this command reindex into another index the alias given. Problem it can lead to the deletion of the alias used by the PIM if the user send the index name instead of the alias. We now return an error when the parameter is an index with an alias (we continue to accept index without alias because some client does not have an index `akeneo_pim_product_and_product_model` without alias
> PIM-10928: pim:update:check-requirements can create indexes which are unreachable from the PIM

- src/Akeneo/Connectivity/Connection/back/tests/Integration/Mock/FakeFeatureFlag.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/FeatureFlag/AllCriteriaFeature.php
- src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/FeatureFlag/DataQualityInsightsFeature.php
- src/Akeneo/Platform/Bundle/FeatureFlagBundle/Configuration/EnvVarFeatureFlag.php
- src/Akeneo/Platform/Bundle/FeatureFlagBundle/Configuration/FakeFeatureFlag.php
- src/Akeneo/Platform/Bundle/FeatureFlagBundle/Configuration/OnlyEnterpriseEditionFeatureFlag.php
- src/Akeneo/Platform/Bundle/FeatureFlagBundle/Configuration/OnlyFlexibilityOnPremiseFeatureFlag.php
- src/Akeneo/Platform/Bundle/FeatureFlagBundle/Configuration/OnlyFreeTrialFeatureFlag.php
- src/Akeneo/Platform/Bundle/FeatureFlagBundle/Configuration/OnlyGrowthAndSerenityFeatureFlag.php
- src/Akeneo/Platform/Bundle/FeatureFlagBundle/Configuration/OnlyGrowthAndSerenitySandboxFeatureFlag.php
- src/Akeneo/Platform/Bundle/FeatureFlagBundle/Configuration/OnlySaasFeatureFlag.php
- src/Akeneo/Platform/Bundle/FeatureFlagBundle/Configuration/OnlySerenityFeatureFlag.php
- src/Akeneo/Platform/Bundle/FeatureFlagBundle/FeatureFlag.php
- src/Akeneo/Platform/Bundle/FeatureFlagBundle/Internal/ImmutableFeatureFlags.php
- src/Akeneo/Platform/Bundle/FeatureFlagBundle/Internal/Registry.php
- src/Akeneo/Platform/Bundle/FeatureFlagBundle/README.md
- src/Akeneo/Tool/Bundle/BatchBundle/tests/Integration/Job/DoctrineJobRepositoryIntegration.php
- tests/back/Platform/Integration/FeatureFlag/FilePersistedFeatureFlagsIntegration.php
- tests/back/Platform/Specification/Bundle/FeatureFlagBundle/Internal/ImmutableFeatureFlagsSpec.php
- tests/back/Platform/Specification/Bundle/FeatureFlagBundle/Internal/RegistrySpec.php
- tests/back/Platform/Specification/Bundle/FeatureFlagBundle/Internal/Test/InMemoryFeatureFlagsSpec.php
Allows implementation of a service that uses an external solution for resolving the flags.
If the flag is unknown we need to declare a different service for every flag just to pass a parameter, which is very inefficient.
> GROWTH-76: Update FeatureFlag interface to allow passing the flag being evaluated

- CHANGELOG.md
- src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/model/doctrine/JobInstance.orm.yml
- src/Akeneo/UserManagement/Bundle/Resources/config/model/doctrine/Group.orm.yml
- src/Akeneo/UserManagement/Bundle/Resources/config/model/doctrine/Role.orm.yml
- upgrades/schema/Version_8_0_20230511113912_fix_oro_access_tables_columns_length.php
- upgrades/test_schema/Version_8_0_20230511113912_fix_oro_access_tables_columns_length_Integration.php
In some old PIMs, the `label` column of `oro_access_role` table was set to `varchar(30)` and during the migration from PaaS to SaaS was not updated to `varchar(255)` due to some typo in configuration.
This PR fixes the typo and add a simple migration to fix the column size.
> PIM-10983: Error HTTP 500 when adding a custom app

- src/Akeneo/Tool/Bundle/BatchQueueBundle/Command/JobExecutionWatchdogCommand.php
- src/Akeneo/Tool/Bundle/BatchQueueBundle/tests/integration/Command/PurgeVersioningWatchdogIntegration.php
The watchdog command was not able to transfer custom options to the `akeneo:batch:job` command.
We fix this by creating the job execution with the provided configuration, so the right parameters will be stored in the database job_execution.
**Workflow:**
- Launch watchdog command with custom config
```bash
bin/console akeneo:batch:watchdog --job_code=versioning_purge --config='{"more-than-days": 15, "less-than-days": 5}'
```
- The watchdog creates a job_execution with the custom parameters
- The batch command is launched by the watchdog with the created job execution ID
> PH-1028: :bug: Handle custom job config in watchdog

- CHANGELOG.md
- src/Oro/Bundle/PimDataGridBundle/Datasource/AssociatedProductDatasource.php
- src/Oro/Bundle/PimDataGridBundle/Datasource/AssociatedProductModelDatasource.php
- src/Oro/Bundle/PimDataGridBundle/spec/Datasource/AssociatedProductDatasourceSpec.php
In the association grid, the pagination was always calculated based on the total number of associated entities, and was not taking filters into account
> PIM-10980: Fix pagination update when applying filters on product association grid

- src/Akeneo/Platform/Bundle/InstallerBundle/InstallStatusManager/InstallStatusManager.php
- tests/back/Platform/Integration/Installer/InstallStatusManagerIntegration.php
InstallStatusManager must crash on any exception but TableNotFound exception to not produce false negative.
> PH-1034: InstallStatusManager catches only TableNotFound exception

- src/Akeneo/Tool/Bundle/MessengerBundle/Middleware/UcsMiddleware.php
- src/Akeneo/Tool/Bundle/MessengerBundle/Resources/config/transport.yml
- tests/back/Tool/Integration/Batch/Command/BatchCommandIntegration.php
In the previous version of `UcsMiddleware`, the property `$this->pimTenantId`, from `APP_TENANT_ID` env var, was used for adding the tenant id into messages.
In long running processes, this variable was supposed to stay null after each envelope.
That was not the case because after the first message is consumed, it becomes stateful because of the line
```
$this->pimTenantId = $stamp->pimTenantId();
```
With the new version, the middleware never become stateful in long-running processes and always use the stamp as a source of truth.
Since the webhook feature has no visible impact on the PIM (it's a background process that does not change PIM data), it took a lot of time to be noticed.
> fix stateful UcsMiddleware injecting wrong tenant id in messages

- CHANGELOG.md
- src/Akeneo/Tool/Component/Connector/Reader/File/Xlsx/Reader.php
- src/Akeneo/Tool/Component/Connector/spec/Reader/File/Xlsx/ReaderSpec.php
see https://akeneo.atlassian.net/browse/PIM-10972
In the case of an imported file with a large amount of columns, the file iterator removes empty values which leads to have data shifted. The fix is to rebuilt the row with empty values.
> PIM-10972: change the way incomplete row are filled

- Makefile
In some case the `akeneo_pim` database does not exist when we launch `make database` command. 
When it's the case we have the following error 
```
Can't drop database 'akeneo_pim'; database doesn't exist
```
In order to not have to create manually the database and relaunch the command I added to the drop database an if exist check.
> Fix database akeneo_pim does not exist when launching make database

- src/Akeneo/Pim/Structure/Bundle/EventSubscriber/AttributeRemovalSubscriber.php
- src/Akeneo/Pim/Structure/Bundle/Resources/config/event_subscribers.yml
In this PR, we modified the AttributeRemovalSubscriber in order to listen to the KernelEvents::TERMINATE and ConsoleEvents::TERMINATE only when an attribute is removed.
Why ?
Because actually the service is called each time a console/http request is finished. It's not really a problem in most cases because there is an early return but instantiating the AttributeRemovalSubscriber and her services is costly for the new job stack and it's incompatible with handle multiple job per second. 
> RAB-1395: Register onTerminate only when an attribute is added to the aggregator

- CHANGELOG.md
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/router.js
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/pages/Default.less
The classname used as root for React pages was the same as the classname used as a container for attributes.
From now on, the class used as root for React pages will be `view-global`
> PIM-11003: Fix scrolling on Product edit form attributes

- src/Akeneo/Tool/Bundle/BatchBundle/EventListener/PauseJobOnSigtermSubscriber.php
- src/Akeneo/Tool/Bundle/BatchQueueBundle/Command/JobExecutionWatchdogCommand.php
- src/Akeneo/Tool/Bundle/BatchQueueBundle/MessageHandler/JobMessageHandler.php
- src/Akeneo/Tool/Bundle/BatchQueueBundle/Resources/config/services.yml
I added SIGTERM signal handler to forward the signal across consumer, watchdog and batch command processes.
> RAB-1411: Forward SIGTERM across daemon and watchdog command

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/Bundle/Command/CleanRemovedAttributesFromProductAndProductModelCommand.php
The option `all-blacklisted-attributes` is set to null by default.
So we have to remove `InputOption::VALUE_OPTIONAL` to ignore this parameter if it is not set.
> PIM-11016: Improve the clean-removed-attributes command

- src/Akeneo/Pim/Enrichment/Component/Product/Job/ComputeFamilyVariantStructureChangesTasklet.php
- tests/back/Pim/Enrichment/Integration/Product/Job/ComputeFamilyVariantStructureChangesTaskletIntegration.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Job/ComputeFamilyVariantStructureChangesTaskletSpec.php
The `compute_family_variant_structure_changes` job used to stop as soon as it encountered an invalid product or model, thus leaving other entities of the family variant in an invalid state.
We now simply skip the invalid entities and keep on with the job execution so that the other entities are properly updated 
> PIM-11005: Skip invalid entities during compute_family_variant_structure_changes job

- src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_US.yml
- src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/system/src/components/reset-pim/ResetButton.tsx
- src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/system/src/components/reset-pim/ResetButton.unit.tsx
- src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/system/src/hooks/index.ts
- src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/system/src/hooks/useCheckInstanceCanBeReset.ts
- src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/system/src/hooks/useCheckInstanceCanBeReset.unit.ts
- src/Akeneo/Platform/Installer/back/src/Infrastructure/Controller/CheckInstanceCanBeResetAction.php
- src/Akeneo/Platform/Installer/back/src/Infrastructure/Symfony/Resources/config/controllers.yml
- src/Akeneo/Platform/Installer/back/src/Infrastructure/Symfony/Resources/config/routing.yml
- src/Akeneo/Platform/Installer/back/tests/.php_cd.php
- src/Akeneo/Platform/Installer/back/tests/Integration/Controller/CheckInstanceCanBeResetActionTest.php
- src/Akeneo/Platform/Installer/back/tests/Integration/ControllerIntegrationTestCase.php
- src/Akeneo/Platform/Job/back/Infrastructure/Symfony/Resources/config/queries.yml
- src/Akeneo/Platform/Job/back/ServiceApi/JobExecution/FindQueuedAndRunningJobExecution.php
- src/Akeneo/Platform/Job/back/ServiceApi/JobExecution/FindQueuedAndRunningJobExecutionInterface.php
- Add ServiceApi to count queued or running job execution (→ count method only for now, open to add a search method later on)
- Display error in message bar when trying to reset instance with queued or running jobs
> RAB-1329: Validate no job running before resetting PIM

- src/Akeneo/Tool/Bundle/BatchQueueBundle/EventListener/AckMessageEventListener.php
- src/Akeneo/Tool/Bundle/BatchQueueBundle/spec/EventListener/AckMessageEventListenerSpec.php
Scheduled jobs are not acknowledged immediately after consumption. It leads to multiple retries when a scheduled exceeds a duration of 10 minutes.
See https://github.com/akeneo/pim-community-dev/pull/14606/files
Unackownledged messages could probably be observed with [subscription/delivery_latency_health_score](https://cloud.google.com/monitoring/api/metrics_gcp#pubsub/subscription/delivery_latency_health_score)
> PH-1106: immediatly acknowledge schedules job messages

- src/Akeneo/Tool/Bundle/BatchQueueBundle/Command/JobExecutionWatchdogCommand.php
When the `job_execution_id` is provided to the watchdog, the `job_code` can be null
We must fetch it to have more explicit and usable logs
> PH-1104: :bug: Fix job_code empty in watchdog logs

- src/Akeneo/Pim/Structure/Bundle/Query/PublicApi/Attribute/Sql/SqlGetAttributes.php
- src/Akeneo/Pim/Structure/Component/Query/PublicApi/AttributeType/Attribute.php
- tests/back/Acceptance/Attribute/InMemoryGetAttributes.php
- tests/back/Pim/Structure/Integration/Attribute/Query/SqlGetAttributesIntegration.php
In this PR we added the ability to get the "main_identifier" property for GetAttribute service API
> RAB-1407: Add main identifier in GetAttribute service api

- src/Akeneo/Tool/Bundle/MessengerBundle/Command/BenchmarkDumbCommand.php
- src/Akeneo/Tool/Bundle/MessengerBundle/Resources/config/command.yml
- src/Akeneo/UserManagement/Bundle/Resources/config/event_subscribers.yml
- src/Akeneo/UserManagement/back/Infrastructure/Cli/AuthenticateAdminUser.php
- src/Akeneo/UserManagement/back/Infrastructure/Cli/EventListener/AuthenticateCommandAsAdminUserListener.php
To avoid performance issue, the services in dependency in `AuthenticateCommandAsAdminUserListener` need to be lazy (implemented only when called).
As it cannot be done directly with the DI attribute `lazy` for one of them, the process done in the listener are extracted in a dedicated lazy service.
> JEL-358: Fix performance issue when running Symfony console

- make-file/test.mk
`PIM_CONTEXT=test make pim-integration-back` and `end-to-end-back` in a non CI environment trigger an negligible error:
```
/bin/sh: 1: Syntax error: "(" unexpected
make: *** [make-file/test.mk:105: pim-integration-back] Error 2
```
> fix(): Makefile echo error

- CHANGELOG.md
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/product/locale-switcher.html
On DQI locale filter the display was not the same on the other locale filter in the PIM
i fixed by changing the locale language to the locale label in the locale switcher template
> PIM-11050: On "locale" DIV, missing the indication of the country

- CHANGELOG-7.0.md
- config/packages/behat/oneup_flysystem.yml
- config/packages/dev/oneup_flysystem.yml
- config/packages/prod/oneup_flysystem.yml
- config/packages/test/oneup_flysystem.yml
- config/services/pim_parameters.yml
- src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/Step/DownloadStep.php
- src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/step.yml
I extracted the root location of local storage in a container param.
This param is now used to rebuild the absolute local file path in the download step.
Resolves #19688
> PIM-11047: Be able to customize local storage root without breaking import/export

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/Component/Product/Value/ScalarValue.php
- tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/ExternalApi/CreateVariantProductEndToEnd.php
- tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/ExternalApi/CreateVariantProductWithUuidEndToEnd.php
- tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/ExternalApi/PartialUpdateVariantProductEndToEnd.php
- tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/ExternalApi/PartialUpdateVariantProductWithUuidEndToEnd.php
- tests/back/Pim/Enrichment/Integration/Storage/Sql/Product/SqlGetValuesOfSiblingsIntegration.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/UniqueVariantAxisValidatorSpec.php
The UniqueVariantAxisValidator does not invalidate a duplicated variant on a boolean axis because the ScalarValue does not cast wrapped boolean value to string correctly.
> PIM-11057: Fix ScalarValue::__toString does not cast wrapped boolean value correctly

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/Writer/TranslatedColumnPresenter.php
- src/Akeneo/Tool/Component/Connector/Writer/File/FlatItemBufferFlusher.php
- src/Akeneo/Tool/Component/Connector/Writer/File/SimpleColumnPresenter.php
- tests/back/Pim/Enrichment/Integration/Product/Export/Product/ExportProductsWithLabelsIntegration.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Writer/TranslatedColumnPresenterSpec.php
When exporting products or models with labels, the column presenter was used to generate column names for both the header row and "data" rows, which in some cases could lead to some inconsistencies, because "data" rows don't necessarily have values for each column. As a result, some values could be "out of bounds" (at the end of the row, in a column without header)
Now the column presenter returns a mapping `[original_column_name => translated_column_name]`, which is then used to prepare proper data rows
> PIM-11039: Fix export with duplicated labels

- CHANGELOG.md
- components/identifier-generator/back/src/Infrastructure/Subscriber/SetIdentifiersSubscriber.php
- components/identifier-generator/back/tests/Specification/Infrastructure/Subscriber/SetIdentifiersSubscriberSpec.php
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/validation/product.yml
Fixes the validation of a generated identifier:
In some cases, some constraints returned by the MetadataFactory would apply to the product itself, instead of its properties (here, the `identifier` property). It's the case of the Regex validator, which would validate the `$product->__toSttring()` (i.e the value of the attribute as label) instead of the product identifier.
Here, we simply add a validation group and validate the product only on this validation group, letting the validator decide which constraints to apply on which properties of the product
> PIM-11063: Fix generated identifier validation

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/Component/Product/ValuesFiller/FillMissingProductModelValues.php
- src/Akeneo/Pim/Enrichment/Component/Product/ValuesFiller/FillMissingProductValues.php
- tests/back/Common/Structure/Attribute/Builder.php
- tests/back/Pim/Enrichment/Specification/Component/Product/ValuesFiller/FillMissingProductModelValuesSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/ValuesFiller/FillMissingProductValuesSpec.php
In the MissingValuesAdder, when an attribute was locale-specific but the locale did not belong to the channel, the empty value was still generated, causing issues when trying to save the product from the PEF.
> PIM-11066: Fix Missing Values Adder for scopable + localizable + locale specific attributes

- src/Akeneo/Pim/Structure/Bundle/Doctrine/ORM/Repository/ExternalApi/AttributeRepository.php
- tests/back/Pim/Structure/EndToEnd/Attribute/ExternalApi/ListAttributeEndToEnd.php
Add `is_main_identifier` in search params for getAttributes API endpoint
> CPM-1074: Add is_main_identifier on get attributes search params

- upgrades/.php_cd.php
- upgrades/schema/Version_8_0_20230628104642_fill_new_completeness_table.php
- upgrades/test_schema/Version_8_0_20230628104642_fill_new_completeness_table_Integration.php
Non-ZDD migration for https://github.com/akeneo/pim-community-dev/blob/master/src/Akeneo/Pim/Enrichment/Bundle/Command/ZddMigrations/V20230512143522FillNewCompletenessTableZddMigration.php
It is not executed when the new completeness table already has some records
> CPM-1112: Add doctrine migration to fill the new completeness table

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ElasticsearchProjection/GetElasticsearchProductProjection.php
We suspect that with the former completeness tables (`pim_catalog_completeness`), it was possible to have a zero as value for `required` (number of required attributes).
With the new table (`pim_catalog_product_completeness`), we don't store the data for channels that don't have any required attributes.
But if there were some products with zero required attributes in `pim_catalog_completeness`, then the migration has inserted them in the new table (`pim_catalog_product_completeness`), then this error could happen.
> PIM-11071: Fix potential divided by zero in completeness calculation

- CHANGELOG.md
- src/Oro/Bundle/FilterBundle/Filter/StringFilter.php
- src/Oro/Bundle/FilterBundle/spec/Filter/StringFilterSpec.php
- src/Oro/Bundle/PimFilterBundle/Filter/ProductValue/StringFilter.php
We want to escape underscores only when having `%` so LIKE ot NOT LIKE operators.
> PIM-11073: Fix search with underscore on attribute grid

- src/Akeneo/Pim/Enrichment/Product/back/API/Command/UpsertProductCommand.php
- src/Akeneo/Pim/Enrichment/Product/back/Application/UpsertProductHandler.php
- src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductIntegration.php
In some cases, we want to validate a product and don't save it.
This is why we are adding a `dryRun` version of the UpsertProductCommand so that the product is not saved at the end.
> Add dryRun on UpsertProductCommand

- CHANGELOG-6.0.md
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/AppRoleWithScopesFactory.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Persistence/Query/IncreaseLabelLengthQuery.php
- src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/apps.yml
- src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/Persistence/Query/IncreaseLabelLengthQueryIntegration.php
- src/Akeneo/UserManagement/Bundle/Resources/config/model/doctrine/Role.orm.yml
Backport from https://akeneo.atlassian.net/browse/PIM-10983
In some old PIMs, the label column of oro_access_role table was set to varchar(30) and during the migration from PaaS to SaaS was not updated to varchar(255) due to some typo in configuration.
This PR fixes the typo and add a simple migration to fix the column size.
> PIM-11070: [SLA] [Backport] PIM-10983 - Error HTTP 500 when adding a custom app

- front-packages/shared/src/components/Navigation/PimNavigation.tsx
- front-packages/shared/src/components/Navigation/PimNavigation.unit.tsx
- src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/fetcher/Dashboard/fetchKeyIndicators.ts
- src/Akeneo/Platform/Bundle/AnalyticsBundle/Resources/public/js/patch-fetcher.js
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/menu/help.ts
- src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/activity/src/hooks/useDashboardCompleteness.ts
When Elasticsearch is down, `/analytics/collect_data` return a **500 internal server error**.
And Navigation bar is not shown
PHP ElasticSearch Client throw _NoNodesAvailableException_
> PIM-11088: Catch ElasticSearch exception

- src/Akeneo/Tool/Bundle/StorageUtilsBundle/Resources/config/doctrine.yml
- src/Akeneo/Tool/Bundle/StorageUtilsBundle/tests/integration/TableWithOldInstantColsCannotHaveNewColumnUntilUcsMigrationTest.php
- src/Akeneo/Tool/Component/StorageUtils/Migration/V20230622175500OptimizeTableWithInstantColsMigration.php
- upgrades/.php_cd.php
- upgrades/schema/Version_8_0_20230627173000_remove_instant_cols.php
- upgrades/test_schema/Version_8_0_20230627173000_remove_instant_cols_Integration.php
In this PR, 
I added a new migration in order to launch OPTIMIZE operation on table that have instant_col > 0 in order to rebuilt those table in order to avoid having table corruption like we had in production (cf  https://www.notion.so/akeneo/2023-06-01-MySQL-crash-loop-6796c8a1656c49daaa986aa53274bc71, https://akeneo.slack.com/archives/C05A8TT1UCW/p1686739172807109)
As some table have more than 1 million lines we decided to do not launch OPTIMIZE TABLE because it throw an error due to the fact that it required too much memory. As UCS coming, I added a test in order to validate that there is no new column on those table until UCS migration is finished.
Tested on multiple clone: 
- srnt-cto-pim: 127s
- srnt-madeira-production: 116s
- …
> RAB-1445: Add ZDDmigration in order to remove the old instant cols on mysql server in order to avoid having index corruption

- src/Akeneo/Pim/Structure/Component/Validator/Constraints/IdentifierAttributeCreationLimitValidator.php
- tests/back/Pim/Structure/Specification/Component/Validator/Constraints/IdentifierAttributeCreationLimitValidatorSpec.php
The validation was triggered for every attribute type, so you couldn't create any attribute once the limit was reached
> CPM-1160: Fix identifier attribute creation limit validation

- CHANGELOG-6.0.md
- src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Cursor.php
- src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/FromSizeCursor.php
- src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/FromSizeIdentifierResultCursorFactory.php
- src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/SearchAfterSizeIdentifierResultCursorFactory.php
- src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/ProductAndProductModel/ESGetProductAndProductModelIdentifiersWithValuesIgnoringLocaleAndScope.php
- tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/CursorFactorySpec.php
- tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/CursorSpec.php
- tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/FromSizeCursorFactorySpec.php
- tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/FromSizeCursorSpec.php
- tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/FromSizeIdentifierResultCursorFactorySpec.php
- tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/SearchAfterSizeIdentifierResultCursorFactorySpec.php
Backport [CPM-653](https://github.com/akeneo/pim-community-dev/pull/17783)
[CPM-653]: https://akeneo.atlassian.net/browse/CPM-653?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[OCT-167]: https://akeneo.atlassian.net/browse/OCT-167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PIM-11083: [backport] CPM-653: do not sort on _id in ES cursors

- CHANGELOG.md
- src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Field/IdentifierFilter.php
- tests/back/Pim/Enrichment/Integration/PQB/Filter/Field/IdentifierFilterIntegration.php
- tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Filter/Field/IdentifierFilterSpec.php
We remove the Query String escaping on Identifier filter when the equals or not equal operators are used
> PIM-11099: Fix regression on filtering products and product models on Identifier containing a dash character

- src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/AbstractCursor.php
- src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Cursor.php
- src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/FromSizeCursor.php
- tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/CursorSpec.php
- tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/FromSizeCursorSpec.php
**Orignal issue**
When trying to count products for a Supplier Portal use case, we noticed that the product repo injected in ES cursors is called to hydrate found entities even just for counting.
In EE, the repo is decorated and also [applies permissions by side effect](https://github.com/akeneo/pim-enterprise-dev/blob/master/src/Akeneo/Pim/Permission/Bundle/Persistence/ORM/EntityWithValue/ProductRepository.php#L248).
**Why it's useless**
- Permissions are [already applied in the ES query by the PQB](https://github.com/akeneo/pim-enterprise-dev/blob/master/src/Akeneo/Pim/Permission/Bundle/Persistence/ORM/EntityWithValue/ProductQueryBuilderFactory.php#L68-L70).
- Other operations done when calling `rewind()` from `count()` concern only pagination and sorting, which are irrelevant when …
> Avoid hydrating entities when counting from ES cursors

- front-packages/shared/src/components/DeleteModal.tsx
- src/Akeneo/Pim/Structure/Bundle/Application/SwitchMainIdentifier/CanNotSwitchMainIdentifierException.php
- src/Akeneo/Pim/Structure/Bundle/Application/SwitchMainIdentifier/CanNotSwitchMainIndentifierWithPublishedProductException.php
- src/Akeneo/Pim/Structure/Bundle/Application/SwitchMainIdentifier/CommunityPublishedProductExists.php
- src/Akeneo/Pim/Structure/Bundle/Application/SwitchMainIdentifier/PublishedProductExists.php
- src/Akeneo/Pim/Structure/Bundle/Application/SwitchMainIdentifier/SwitchMainIdentifierValidator.php
- src/Akeneo/Pim/Structure/Bundle/Controller/InternalApi/SwitchMainIdentifierController.php
- src/Akeneo/Pim/Structure/Bundle/Resources/config/validators.yml
- src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute/form/AttributeSetupApp.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute/form/attribute-setup.tsx
- src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml
This PR adds a button in the Danger Zone to update the main identifier.
It is only allowed
- If the attribute is an identifier
- If the attribute is not the main identifier
- If onBoarder is not activated (in this case, a warning is displayed and the button is not available)
- If there is no published products (in this case, the user has to fill the modal, then the backend will return a dedicated error message displayed in the front)
> CPM-1149: Add button to switch main identifier

- src/Akeneo/Platform/Job/back/Application/LaunchJobInstance/LaunchJobInstanceHandler.php
- src/Akeneo/Platform/Job/back/ServiceApi/JobInstance/LaunchJobInstanceCommand.php
In this PR, 
I made the File parameter on LaunchJobInstanceCommand not required in order to work with export job type. This parameters is only required when job is import
> RAB-1541: Do not make the File required on LaunchJobInstanceCommand ServiceApi

- src/Akeneo/Pim/Enrichment/Component/Product/Model/AbstractProduct.php
- src/Akeneo/Pim/Enrichment/Component/Product/Model/QuantifiedAssociation/QuantifiedAssociationCollection.php
- src/Akeneo/Pim/Enrichment/Component/Product/Model/QuantifiedAssociation/UuidMapping.php
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/associated-product-row.js
- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/product-and-product-model-picker.js
- tests/back/Pim/Enrichment/Specification/Component/Product/Model/ProductSpec.php
In the association screens (association grid and associated product picker), Display product uuid as fallback when neither the label or main identifier is filled:
> CPM-1165: Visualize main identifier in associations

- .circleci/jobs/build_and_deploy.yml
Actually the node image of Akeneo is 18 (https://github.com/akeneo/pim-community-dev/blob/cf8e24b6eda65ea2123a0822800ee095bc2c42b4/docker/Dockerfile_node) but we tag the image as akeneo/node:16 in Dockerhub, in this PR, i fixed it by taging this image as akeneo/node:18.
> Fix the node docker image generated by CI is the wrong version as CE master is now in 18

- CHANGELOG-7.0.md
- src/Akeneo/Tool/Bundle/VersioningBundle/Builder/VersionBuilder.php
- src/Akeneo/Tool/Bundle/VersioningBundle/spec/Builder/VersionBuilderSpec.php
How to reproduce the bug
- Create a product with a table attribute
- Save a table value in this product, with the order coming from the UI (still the same)
- Update this product table value through API, by changing the column order
- Update this product again in any other value
- A new version is created, including the table value
The issue comes from the VersionBuilder. This VersionBuilder creates "changeset" (the changes of the new product regarding the previous version of the product.
For each value, we compare strings to strings (for attributes and properties). If `old !== new`, then the value is considered as updated.
As the string `"[{a: "a", b:"b"}]"` differs from `"[{b:"b", a: "a"}]"`, a new version is created.
We use 
- `\json_decode` to decode the string. If the string was …
> PIM-11200: Fix versinoning on table attributes

- CHANGELOG-7.0.md
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/readers.yml
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/steps.yml
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/Processor/MassEdit/AddProductValueProcessor.php
- src/Akeneo/Pim/Enrichment/Component/Product/Connector/Reader/Database/MassEdit/ProductAndProductModelReader.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Reader/Database/MassEdit/ProductAndProductModelReaderSpec.php
Before this PR, there was an issue when trying to associate products via the mass associate action, for 2-way association types: when trying to associate a product/model to itself, a non-caught `Akeneo\Pim\Enrichment\Component\Product\Exception\TwoWayAssociationWithTheSameProductException` was thrown, and the job immediately failed, without skipping the wrong data.
Catching this exception and trying to skip the row would also result in an error (the infamous `A new entity was found through the relationship...`, because of the way the associations are designed (associated entities are fully hydrated when updating associations).
Let's say you want to associate products B and C to products A, B and B
- 1st step:
- the PQB hydrates the 3 products (see …
> PIM-11212: Fix error handling in mass associate bulk action

- CHANGELOG-7.0.md
- src/Akeneo/Pim/Enrichment/Component/Product/Comparator/Attribute/OptionComparator.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Comparator/Attribute/OptionComparatorSpec.php
In this PR we fixed an issue with the option comparator used to tell if a value is different when importing. When the value read was null the comparator automatically returned a difference even if the value was already null in the product
> PIM-11251: Fix option comparator when data is null

- front-packages/akeneo-design-system/src/components/Table/Table.stories.mdx
- front-packages/akeneo-design-system/src/components/Table/TableRow/TableRow.tsx
- front-packages/akeneo-design-system/src/components/Table/TableRow/TableRow.unit.tsx
Following [this ticket](https://akeneo.atlassian.net/browse/SCT-87), we (Shared Catalogs team) need to use the "mixed" checkbox within the "Table" component.
This PR adds this possiblity by allowing the `isSelected` prop to be "mixed" (in addition to true/false)
> [DSM] Add mixed capability to checkbox in TableRow component

- CHANGELOG-7.0.md
- src/Akeneo/Tool/Component/Connector/Writer/File/FlatItemBufferFlusher.php
In this PR, 
I replaced FormulaCell by StringCell: we didn't want that value in PIM are interpreted as formula when opening it in Excel, it also remove the possibility to made formula injection through the PIM (https://akeneo.atlassian.net/browse/PIM-10640)
> PIM-11266: Fix value starting with "=<" causes error when exporting in Excel

- CHANGELOG-7.0.md
- src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/action/mass-delete-action.js
Too big grid filters (e.g: in list with a lot of entries) used to cause 414 errors because they were sent as a query string
> PIM-11265: Fix mass delete action when using big grid filters

- CHANGELOG-7.0.md
- src/Akeneo/Pim/Enrichment/Bundle/Command/ZddMigrations/V20220729171405DropProductIdColumnsAndCleanVersioningResourceUuidColumns.php
- upgrades/schema/Version_7_0_20220429131804_execute_uuid_migration.php
During `doctrine:migration:migrate`, if the `pim:product:migrate-to-uuid` command lasts more than 8 hours (which can happen with big catalogs), MySQL will close the Doctrine migration's connection, causing the migration to fail. ("MySQL server has gone away...")
Also, some SQL queries (make product_id columns nullable) used to be executed even if they didn't need to (already done in a previous attempt).
> PIM-11269: Fix potential lost connection during 6.0 -> 7.0 migration

- CHANGELOG-7.0.md
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/doctrine/Product/Product.orm.yml
- src/Akeneo/Pim/Enrichment/Component/Product/Model/Group.php
This issue appeared following [PIM-10149](https://github.com/akeneo/pim-community-dev/pull/15725).  This mapping has been removed to avoid using it because it can leads to OOM. We decided to fix this warning by removing the inversedBy clause in the Product.orm.yml because we don’t use it anymore.
[PIM-10149]: https://akeneo.atlassian.net/browse/PIM-10149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PIM-10903: Fix Doctrine warning related to Product and Group

- CHANGELOG-7.0.md
- src/Akeneo/Pim/Enrichment/Component/Product/Validator/UniqueAxesCombinationSet.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Validator/UniqueAxesCombinationSetSpec.php
There is a case sensitivity issue when we try to compare a variant product with an uppercased identifier because we store cached identifier into lowercase and we do the check without lowercasing variant identifier.
Note for the pull-up into master: Don't pull-up those changes as this class has been already reworked and fixed.
> PIM-11289: Fix case-sensitive check in UniqueAxesCombinationSet

- CHANGELOG-7.0.md
- src/Akeneo/Pim/Enrichment/Component/Product/Updater/ExternalApi/ProductModelUpdater.php
- src/Akeneo/Pim/Enrichment/Component/Product/Updater/ProductModelUpdater.php
- tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/PartialUpdateListProductModelEndToEnd.php
- tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/PartialUpdateProductModelEndToEnd.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Updater/ExternalApi/ProductModelUpdaterSpec.php
- tests/back/Pim/Enrichment/Specification/Component/Product/Updater/ProductModelUpdaterSpec.php
Backport https://github.com/akeneo/pim-enterprise-dev/pull/21494
Previously, the tested query returned
```
+'{"code":422,"message":"Property \"family\" cannot be modified, \"FaMiLyA\" given. Check the expected format on the API documentation.","_links":{"documentation":{"href":"http:\/\/api.akeneo.com\/api-reference.html#patch_product_models__code_"}}}'
```
Now, it accepts the query.
> [backport PIM-11406] PIM-11418: Fix API Product Model endpoint when trying to update family with wrong case

- CHANGELOG-7.0.md
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/validation/product.yml
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/validation/productmodel.yml
- tests/back/Pim/Enrichment/Integration/Validation/ProductIdentifierValidationIntegration.php
https://akeneo.atlassian.net/browse/PIM-11452
Backport of https://github.com/akeneo/pim-enterprise-dev/pull/22243
> PIM-11452: Forbid the usage of non-breakable space in product identifier and product model code

- .circleci/config.yml
- .circleci/docker-compose.override.yml.dist
- .circleci/jobs/build_and_deploy.yml
- .circleci/jobs/features/catalogs/test_back_catalogs_ce.yml
- .circleci/jobs/features/catalogs/test_back_catalogs_ee.yml
- .circleci/jobs/features/catalogs/test_front_catalogs_ce.yml
- .circleci/jobs/features/catalogs/test_front_catalogs_ee.yml
- .circleci/jobs/features/catalogs/test_performance_catalogs_ce.yml
- .circleci/jobs/features/connectivity.yml
- .circleci/jobs/features/other.yml
- .circleci/jobs/install_back_dependencies.yml
- .circleci/jobs/install_front_dependencies.yml
- .circleci/settings.yml
- docker-compose-cypress.yml
- docker-compose.override-osx.yml
- docker-compose.yml
- Update config for circle CI to remove image `ubuntu-2004:2022.04.1` (unavailable).
- Remove warning for docker compose version
> Fix CI 7.0

- src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/TitleContainer.less
- src/Oro/Bundle/PimDataGridBundle/EventListener/AddParametersToProductGridListener.php
Backport the components related to the CE from the fix AST-551](https://akeneo.atlassian.net/browse/AST-551)
Here are the related PRs:
- https://github.com/akeneo/pim-enterprise-dev/pull/24860
- https://github.com/akeneo/pim-enterprise-dev/pull/24930
Linked to the EE pul request: https://github.com/akeneo/pim-enterprise-dev/pull/24990
> AST-551: backport fix for Product thumbnail using localizable scopable Asset Collection as main image

- src/Akeneo/Pim/Enrichment/Bundle/Command/ZeroDowntimeRecreateProductAndProductModelIndexCommand.php
- src/Akeneo/Pim/Enrichment/Bundle/Resources/config/command.yml
- src/Akeneo/Tool/Bundle/ElasticsearchBundle/IndexConfiguration/UpdateIndexMappingWithoutDowntime.php
- src/Akeneo/Tool/Bundle/ElasticsearchBundle/Infrastructure/Client/ClientMigration.php
- src/Akeneo/Tool/Bundle/ElasticsearchBundle/Infrastructure/Client/ClientMigrationInterface.php
- src/Akeneo/Tool/Bundle/ElasticsearchBundle/spec/IndexConfiguration/UpdateIndexMappingWithoutDowntimeSpec.php
Backport of command akeneo:pim:zero-downtime-recreate-product-and-product-model-index to remap without downtime product and product model indexes for Flex
> SQUD 215 Backport 'akeneo:pim:zero-downtime-recreate-product-and-product-model-index' command in 7.0
