akeneo/pim-community-dev

src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductIntegration.php, tests/back/Pim/Enrichment/EndToEnd/InternalApiTestCase.php, tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/AbstractProductTestCase.php, tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/CreateProductEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/GetProductEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/ListProductWithCompletenessEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/SuccessListProductEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/SuccessListVariantProductDeltaEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/Media/CreateProductMediaFileEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/PartialUpdateProductEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/Product/InternalApi/DownloadProductPdfEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/Product/InternalApi/QuantifiedAssociations/AbstractProductWithQuantifiedAssociationsTestCase.php, tests/back/Pim/Enrichment/EndToEnd/Product/Product/InternalApi/QuantifiedAssociations/AddQuantifiedAssociationsToProductEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/Product/InternalApi/QuantifiedAssociations/RemoveQuantifiedAssociationsFromProductEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/Product/InternalApi/QuantifiedAssociations/ValidateQuantifiedAssociationsInProductEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/CreateProductModelEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/ListProductModelWithCompletenessEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/PartialUpdateListProductModelEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/PartialUpdateProductModelEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/ExternalApi/CreateVariantProductEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/ExternalApi/PartialUpdateListVariantProductEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/ExternalApi/PartialUpdateProductToVariantEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/ExternalApi/PartialUpdateVariantProductEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/ExternalApi/PartialUpdateVariantToSimpleEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/ExternalApi/QuantifiedAssociations/DeleteQuantifiedAssociationsFromVariantProductEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/ExternalApi/QuantifiedAssociations/UpdateQuantifiedAssociationsInVariantProductEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/InternalApi/UpdateVariantProductEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/RemoveLocaleFromChannelEndToEnd.php, tests/back/Pim/Structure/Integration/Family/FamilyAttributeAsLabelChangedSubscriberIntegration.php
Use UpsertProductCommand in Enrichment E2E tests and its related user intents
=> CPM-603: Use UpsertProductCommand in Enrichment E2E tests

CHANGELOG.md, src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Field/IdFilter.php, src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Field/SelfAndAncestorFilter.php, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/sequential-edit.js
=> PIM-10459: Fix IdFilter for null uuids

src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/ProductController.php, tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/ErrorListProductEndToEnd.php
https://akeneo.atlassian.net/browse/API-1806
Quick & dirty fix. Hopefully we're going to do an ADR for the whole API
=> API-1806: Validate 'search' and 'pagination_type' query types

src/Akeneo/Pim/Enrichment/Bundle/Command/MigrateToUuid/MigrateToUuidCommand.php
=> Fix query to check DQI process is running

.circleci/jobs/features/connectivity.yml, .circleci/workflows/squads/octopus.yml, src/Akeneo/Connectivity/Connection/back/tests/.php_cd.php
Removing unused coupling rule:
```
Rule Akeneo\Connectivity\Connection\Application\Apps has unused requirements:
* <warning>Akeneo\Connectivity\Connection\Application\Settings\Service\CreateUserInterface</warning>
```
=> OCT-44: Removed unused coupling rule

src/Akeneo/Pim/Enrichment/.php_cd.php, src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/ProductController.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/controllers.yml, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml, src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Product/SqlFindProductIdentifier.php, src/Akeneo/Pim/Enrichment/Component/Product/Query/FindIdentifier.php, src/Akeneo/Pim/Enrichment/Product/back/Domain/Model/ViolationCode.php, src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Validation/AttributeGroupShouldBeEditableValidator.php, src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Validation/IsUserOwnerOfTheProductValidator.php, src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Validation/LocaleShouldBeEditableByUserValidator.php, src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Validation/ShouldStayOwnerOfTheProductValidator.php, src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Validation/UserShouldExistValidator.php, src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Infrastructure/Validation/AttributeGroupShouldBeEditableValidatorSpec.php, src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Infrastructure/Validation/IsUserOwnerOfTheProductValidatorSpec.php, src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Infrastructure/Validation/LocaleShouldBeEditableByUserValidatorSpec.php, src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Infrastructure/Validation/ShouldStayOwnerOfTheProductValidatorSpec.php, src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Infrastructure/Validation/UserShouldExistValidatorSpec.php, tests/back/Pim/Enrichment/Integration/Storage/Sql/Product/SqlFindProductIdentifierIntegration.php
Use new UpsertProductCommand in the InternalAPI for convertToSimpleProductAction method
=> CPM-604: Use UpsertProductCommand for convertToSimpleProductAction

src/Akeneo/Pim/Enrichment/Bundle/Command/MigrateToUuid/MigrateToUuidFillForeignUuid.php
=> Improve fill foreign uuids by removing shouldContinue query

src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Controller/Public/RequestAccessTokenAction.php, src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Validation/AuthorizationCodeMustBeValid.php, src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Validation/AuthorizationCodeMustBeValidValidator.php, src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Validation/AuthorizationCodeMustNotBeExpired.php, src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Validation/AuthorizationCodeMustNotBeExpiredValidator.php, src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Apps/validators.yml, src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/validation/AccessTokenRequest.yml, src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/Validation/AccessTokenRequestValidationIntegration.php, src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Apps/Controller/Public/RequestAccessTokenActionSpec.php, src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Apps/Validation/AuthorizationCodeMustBeValidValidatorSpec.php, src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Apps/Validation/AuthorizationCodeMustNotBeExpiredValidatorSpec.php
Expected behavior:
At least a more explicit message around the [problem](https://akeneo.atlassian.net/jira/software/projects/OCT/boards/289?selectedIssue=OCT-10).
=> OCT-10: add a more explicit violation message when the authorization code has expired

CHANGELOG-5.0.md, src/Akeneo/Pim/Enrichment/Bundle/Command/Category/CheckCategoryTrees/CategoriesPool.php, src/Akeneo/Pim/Enrichment/Bundle/Command/Category/CheckCategoryTrees/Category.php, src/Akeneo/Pim/Enrichment/Bundle/Command/Category/CheckCategoryTrees/CheckCategoryTrees.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/command.yml, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/doctrine/Category/Category.orm.yml, tests/back/Pim/Enrichment/Integration/Command/Category/CheckCategoryTrees/CheckCategoryTreesIntegration.php, tests/back/Pim/Enrichment/Specification/Bundle/Command/Category/CheckCategoryTrees/CategorySpec.php
=> PIM-10465: Pull-up 5.0 => 6.0

src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
=> OCT-54: Fixed typo

.circleci/workflows/squads/octopus.yml
3 differents workflows:
- octopus catalogs
- octopus connectivity
- octopus deploy pull request
:warning: With this new version, there is an approval step before launching any workflow. No more auto launch.
And the dedicated workflow to deploy an env for Megane will automatically publish the link in our slack channel.
=> OCT-56: rewamp octopus workflow

src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/ProductController.php, src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Product/SqlFindProductIdentifier.php, src/Akeneo/Pim/Enrichment/Component/Product/Query/FindIdentifier.php, src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/Product/UniqueProductEntityValidator.php
- Rename fromId to fromUuid for SqlFindProductIdentifier
- Fix condition in validator to due bad rebase
=> CPM-647: Rename fromId to fromUuid for SqlFindProductIdentifier

config/bootstrap.php
We were still using the old bootstrap code while we can now use a much more simple one.
=> BH-1159: Bootstrap refactoring

make-file/connectivity-connection.mk, src/Akeneo/Connectivity/Connection/back/Application/Apps/Command/CreateConnectedAppWithAuthorizationHandler.php, src/Akeneo/Connectivity/Connection/back/Domain/Apps/Event/UserGroupCreatedWithAllPermissionsByDefaultEvent.php, src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Apps/handlers.yml, src/Akeneo/Connectivity/Connection/back/tests/.php_cd.php, src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Apps/Command/CreateConnectedAppWithAuthorizationHandlerSpec.php
=> OCT-57: Dispatch event on connected app creation

components/catalogs/back/src/Application/Handler/CreateCatalogHandler.php, components/catalogs/back/src/Infrastructure/Installer/InstallerSubscriber.php, components/catalogs/back/src/Infrastructure/Normalizer/CatalogNormalizer.php, components/catalogs/back/src/Infrastructure/Persistence/FindOneCatalogByIdQuery.php, components/catalogs/back/src/Infrastructure/Persistence/GetCatalogsByOwnerIdQuery.php, components/catalogs/back/src/Infrastructure/Persistence/UpsertCatalogQuery.php, components/catalogs/back/src/ServiceAPI/Model/Catalog.php, components/catalogs/back/tests/Acceptance/ApiContext.php, components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/DeleteCatalogActionTest.php, components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/GetCatalogActionTest.php, components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/GetCatalogsActionTest.php, components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/UpdateCatalogActionTest.php, components/catalogs/back/tests/Integration/Infrastructure/Persistence/FindOneCatalogByIdQueryTest.php, components/catalogs/back/tests/Integration/Infrastructure/Persistence/GetCatalogsByOwnerIdQueryTest.php, components/catalogs/back/tests/Integration/Infrastructure/Persistence/UpsertCatalogQueryTest.php, upgrades/schema/Version_7_0_20220524134005_add_is_enabled_column_to_catalog.php, upgrades/test_schema/Version_7_0_20220524134005_add_is_enabled_column_to_catalog_Integration.php
=> CXP-1209: Add state column to the catalog table

components/catalogs/back/src/Application/Persistence/GetCatalogsByOwnerUsernameQueryInterface.php, components/catalogs/back/src/Infrastructure/Controller/Internal/GetAllCatalogsByOwnerAction.php, components/catalogs/back/src/Infrastructure/Controller/Public/CreateCatalogAction.php, components/catalogs/back/src/Infrastructure/Controller/Public/GetCatalogAction.php, components/catalogs/back/src/Infrastructure/Controller/Public/GetCatalogsAction.php, components/catalogs/back/src/Infrastructure/Controller/Public/UpdateCatalogAction.php, components/catalogs/back/src/Infrastructure/Normalizer/Internal/CatalogNormalizer.php, components/catalogs/back/src/Infrastructure/Normalizer/Public/CatalogNormalizer.php, components/catalogs/back/src/Infrastructure/Persistence/GetCatalogsByOwnerUsernameQuery.php, components/catalogs/back/src/Infrastructure/Security/DenyAccessUnlessGrantedTrait.php, components/catalogs/back/src/Infrastructure/Symfony/Resources/config/routing/internal.yml, components/catalogs/back/tests/Integration/Infrastructure/Controller/Internal/GetCatalogsByOwnerActionTest.php, components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/CreateCatalogActionTest.php, components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/DeleteCatalogActionTest.php, components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/GetCatalogActionTest.php, components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/GetCatalogsActionTest.php, components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/UpdateCatalogActionTest.php, components/catalogs/back/tests/Integration/Infrastructure/Persistence/GetCatalogsByOwnerUsernameQueryTest.php, components/catalogs/back/tests/Integration/IntegrationTestCase.php
=> CXP-1211: Create internal endpoint in Catalog component

src/Akeneo/Connectivity/Connection/back/Application/Apps/Command/CreateConnectedAppWithAuthorizationHandler.php, src/Akeneo/Connectivity/Connection/back/Domain/Apps/Event/AppUserGroupCreated.php, src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Apps/handlers.yml, src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Apps/Command/CreateConnectedAppWithAuthorizationHandlerSpec.php
Rename event to be more agnostic and do not depend of permission.
=> TIP-1575: dispatch an event when an app is created

src/Akeneo/Pim/Enrichment/Bundle/Command/MigrateToUuid/MigrateToUuidCommand.php, src/Akeneo/Tool/Component/Batch/Model/StepExecution.php, src/Oro/Bundle/PimDataGridBundle/Datasource/ProductDatasource.php, tests/back/Acceptance/Product/InMemoryFindProductId.php
=> adr-uuid-doctrine Fix InMemory to use uuids

make-file/test.mk, src/Akeneo/Platform/Bundle/ImportExportBundle/Command/PurgeJobExecutionCommand.php, src/Akeneo/Platform/Bundle/ImportExportBundle/Controller/InternalApi/JobExecutionController.php, src/Akeneo/Platform/Bundle/ImportExportBundle/Controller/InternalApi/JobInstanceController.php, src/Akeneo/Platform/Bundle/ImportExportBundle/Controller/Ui/JobTrackerController.php, src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/EventSubscriber/ExportFileToStorageAfterExportSubscriber.php, src/Akeneo/Platform/Bundle/ImportExportBundle/Normalizer/JobExecutionNormalizer.php, src/Akeneo/Platform/Bundle/ImportExportBundle/Query/GetJobExecutionTracking.php, src/Akeneo/Platform/Bundle/ImportExportBundle/Widget/LastOperationsFetcher.php, src/Akeneo/Tool/Component/Batch/Job/JobRegistry.php, src/Akeneo/Tool/Component/Batch/Model/StepExecution.php, tests/back/Platform/Specification/Bundle/ImportExportBundle/Normalizer/JobExecutionNormalizerSpec.php
In this PR,
- We launched phpstan on ImportExportBundle at level 5
- We added phpstan verification in CI
=> RAB: Fix phpstan issues on ImportExportBundle

CHANGELOG-5.0.md, src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Standard/Product/AssociationsNormalizer.php
Backport of https://github.com/akeneo/pim-community-dev/pull/16071
Fixes https://akeneo.atlassian.net/browse/PIM-10477?atlOrigin=eyJpIjoiNDIzYTY2ZmIwYzI1NDFmYWI2MjY4ZGI4OTliYmVlYjEiLCJwIjoiaiJ9
=> PIM-10477: [Backport PIM-10220] Fixed issues where association has NaN error

CHANGELOG.md, composer.json, config/packages/messenger.yml, config/services/pim.yml, src/Akeneo/Platform/Bundle/FrameworkBundle/Resources/config/services.yml, src/Akeneo/Tool/Bundle/BatchQueueBundle/MessageHandler/JobExecutionMessageHandler.php, src/Akeneo/Tool/Bundle/BatchQueueBundle/Resources/config/services.yml, src/Akeneo/Tool/Bundle/BatchQueueBundle/tests/integration/Factory/JobExecutionMessageFactoryIntegration.php, src/Akeneo/Tool/Bundle/MessengerBundle/Middleware/UcsMiddleware.php, src/Akeneo/Tool/Bundle/MessengerBundle/Resources/config/transport.yml, src/Akeneo/Tool/Bundle/MessengerBundle/Serialization/JsonSerializer.php, src/Akeneo/Tool/Bundle/MessengerBundle/Stamp/TenantIdStamp.php, src/Akeneo/Tool/Bundle/MessengerBundle/Transport/GooglePubSub/Client.php, src/Akeneo/Tool/Bundle/MessengerBundle/Transport/GooglePubSub/GpsReceiver.php, src/Akeneo/Tool/Bundle/MessengerBundle/Transport/GooglePubSub/GpsSender.php, src/Akeneo/Tool/Bundle/MessengerBundle/Transport/GooglePubSub/GpsTransport.php, src/Akeneo/Tool/Bundle/MessengerBundle/Transport/GooglePubSub/GpsTransportFactory.php, src/Akeneo/Tool/Bundle/MessengerBundle/spec/Serialization/JsonSerializerSpec.php, src/Akeneo/Tool/Bundle/MessengerBundle/spec/Transport/GooglePubSub/GpsReceiverSpec.php, src/Akeneo/Tool/Bundle/MessengerBundle/spec/Transport/GooglePubSub/GpsSenderSpec.php, src/Akeneo/Tool/Component/BatchQueue/Factory/JobExecutionMessageFactory.php, src/Akeneo/Tool/Component/BatchQueue/Normalizer/JobExecutionMessageNormalizer.php, src/Akeneo/Tool/Component/BatchQueue/Queue/JobExecutionMessage.php, src/Akeneo/Tool/Component/BatchQueue/Queue/JobExecutionMessageInterface.php, src/Akeneo/Tool/Component/BatchQueue/spec/Factory/JobExecutionMessageFactorySpec.php, src/Akeneo/Tool/Component/BatchQueue/spec/Normalizer/JobExecutionMessageNormalizerSpec.php
Add the tenant ID parameter to handle batch job for several tenants
=> BH-1159: UCS - Tenant ID for job messages

.circleci/jobs/features/catalogs.yml, .circleci/workflows/pull_request.yml, components/catalogs/back/tests/Integration/IntegrationTestCase.php, components/catalogs/front/package.json
=> OCT: fix prettier version conflict in catalogs

CHANGELOG.md, src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductGrid/FetchProductModelRowsFromCodes.php
=> PIM-10483: Fix slow loading products when filtering by variants

components/catalogs/front/src/FakeCatalogEditContainer.tsx
=> CXP-1232: Add save button in FakeCatalogEditContainer

components/catalogs/back/src/Infrastructure/Installer/InstallerSubscriber.php, upgrades/schema/Version_7_0_20220616074214_add_product_selection_criteria_field_to_catalogs.php
Added product selection criteria field to catalogs:
- migration (no test since it is a new field)
- updated installer subscriber
=> CXP-1226: Added product selection criteria field to catalogs

components/catalogs/back/src/Application/Handler/CreateCatalogHandler.php, components/catalogs/back/src/Application/Persistence/UpdateCatalogProductSelectionCriteriaQueryInterface.php, components/catalogs/back/src/Infrastructure/Persistence/UpdateCatalogProductSelectionCriteriaQuery.php, components/catalogs/back/src/ServiceAPI/Command/CreateCatalogCommand.php, components/catalogs/back/src/ServiceAPI/Command/DeleteCatalogCommand.php, components/catalogs/back/src/ServiceAPI/Command/UpdateCatalogCommand.php, components/catalogs/back/src/ServiceAPI/Model/Catalog.php, components/catalogs/back/src/ServiceAPI/Query/GetCatalogQuery.php, components/catalogs/back/src/ServiceAPI/Query/GetCatalogsByOwnerUsernameQuery.php, components/catalogs/back/tests/Integration/Infrastructure/Controller/Internal/GetCatalogActionTest.php, components/catalogs/back/tests/Integration/Infrastructure/Controller/Internal/GetCatalogsByOwnerActionTest.php, components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/CreateCatalogActionTest.php, components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/DeleteCatalogActionTest.php, components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/GetCatalogActionTest.php, components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/GetCatalogsActionTest.php, components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/UpdateCatalogActionTest.php, components/catalogs/back/tests/Integration/Infrastructure/Persistence/DeleteCatalogQueryTest.php, components/catalogs/back/tests/Integration/Infrastructure/Persistence/FindOneCatalogByIdQueryTest.php, components/catalogs/back/tests/Integration/Infrastructure/Persistence/GetCatalogsByOwnerUsernameQueryTest.php, components/catalogs/back/tests/Integration/Infrastructure/Persistence/UpdateCatalogProductSelectionCriteriaQueryTest.php, components/catalogs/back/tests/Integration/Infrastructure/Persistence/UpsertCatalogQueryTest.php, components/catalogs/back/tests/Integration/IntegrationTestCase.php, components/catalogs/back/tests/Unit/Application/Handler/CreateCatalogHandlerTest.php
I've also added some annotations to have phpunit coverage to correctly reflect what is tested.
=> CXP-1227: Add default criteria when a catalog is created

src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/StorageClient/DownloadFileFromStorage.php, src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/Validation/FilePath.php, src/Akeneo/Tool/Component/Connector/Reader/File/FlatFileIterator.php, tests/back/Platform/Acceptance/ImportExport/Infrastructure/Validation/ValidateFilePathTest.php
=> RAB-796: Display proper error message when cannot open file

components/catalogs/back/.php_cd.php, components/catalogs/back/phpstan.neon, components/catalogs/back/psalm.xml, components/catalogs/back/src/Application/Handler/GetProductIdentifiersHandler.php, components/catalogs/back/src/Application/Persistence/GetProductIdentifiersQueryInterface.php, components/catalogs/back/src/Infrastructure/Controller/Public/GetProductIdentifiersAction.php, components/catalogs/back/src/Infrastructure/Persistence/GetProductIdentifiersQuery.php, components/catalogs/back/src/Infrastructure/Persistence/GetProductUuidFromIdentifierQuery.php, components/catalogs/back/src/Infrastructure/Security/DenyAccessUnlessGrantedTrait.php, components/catalogs/back/src/Infrastructure/Symfony/Resources/config/routing/public.yml, components/catalogs/back/src/Infrastructure/Symfony/Resources/config/services.yml, components/catalogs/back/src/Infrastructure/TemporaryEnrichmentBridge/SearchAfterSizeUuidResultCursorFactory.php, components/catalogs/back/src/ServiceAPI/Query/GetProductIdentifiersQuery.php, components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/DeleteCatalogActionTest.php, components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/GetCatalogActionTest.php, components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/GetCatalogsActionTest.php, components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/GetProductIdentifiersActionTest.php, components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/UpdateCatalogActionTest.php, components/catalogs/back/tests/Integration/Infrastructure/Persistence/GetProductIdentifiersQueryTest.php, components/catalogs/back/tests/Integration/Infrastructure/Persistence/GetProductUuidFromIdentifierQueryTest.php, components/catalogs/back/tests/Integration/IntegrationTestCase.php, components/catalogs/back/tests/Integration/ServiceAPI/Query/GetProductIdentifiersQueryValidationTest.php, components/catalogs/front/src/components/ProductSelection/components/AddCriterionDropdown.test.tsx, components/catalogs/front/src/components/ProductSelection/criteria/StatusCriterion/StatusCriterion.test.tsx, components/catalogs/front/src/components/ProductSelection/criteria/StatusCriterion/index.test.ts, components/catalogs/front/src/components/ProductSelection/criteria/StatusCriterion/index.ts, components/catalogs/front/src/components/ProductSelection/criteria/StatusCriterion/types.d.ts
You can checkout the code commit by commit, they are independent.
- The correct value for the status criterion is "enabled", not "status".
- I've cleanup some left-over in controller tests
- I've added the new controller for product identifiers
=> CXP-1235: GET /catalogs/id/product-identifiers

composer.json, composer.lock
This should fix something like 7 dependabot alerts... :smiley:
=> Guzzle version update to ^6.5.8

composer.json, composer.lock
Fixes remote code injection in dompdf/dompdf
CVE-2022-28368
=> DomPDF version update to ^1.2.2

.github/CODEOWNERS
=> declare ownership of Connectivity to the octo team

front-packages/akeneo-design-system/src/components/Input/TagInput/TagInput.tsx
In this PR, 
We fixed the following bug :
Why we have this bug ? Because we didn't have createTags in onChangeCreateTags dependency list. I decided to remove all useCallback because we didn't really need it (early optimization) 
=> RAB-852: Fix Tag input does not take into account onClick change

components/catalogs/back/src/Infrastructure/Command/CatalogFixtureCommand.php
Add transaction to the akeneo:catalogs:fixtures command
=> OCT-61: Add transaction to the akeneo:catalogs:fixtures command

CHANGELOG.md, src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Connector/SqlGetConnectorProductModels.php, src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Connector/SqlGetConnectorProducts.php, src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Product/QuantifiedAssociation/GetProductModelQuantifiedAssociationsByProductIdentifiers.php, src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Product/QuantifiedAssociation/GetProductQuantifiedAssociationsByProductIdentifiers.php, tests/back/Pim/Enrichment/Integration/Storage/Sql/Connector/SqlGetConnectorProductsIntegration.php
=> PIM-10500: Fix API not returning quantified associations for products where association type code is numeric

components/catalogs/front/jest.config.js, components/catalogs/front/package.json, components/catalogs/front/src/components/CatalogEdit/components/Edit.test.tsx, components/catalogs/front/src/components/CatalogList/components/List.test.tsx, components/catalogs/front/src/components/ProductSelection/ProductSelection.test.tsx
Easier to write & more readable.
=> OCT-74: use mocked() in catalogs tests

src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/ProductController.php, src/Akeneo/Tool/Bundle/ApiBundle/EventSubscriber/ApiRequestLogSubscriber.php, src/Akeneo/Tool/Bundle/ApiBundle/EventSubscriber/ValidateApiRequestQueryParametersSubscriber.php, src/Akeneo/Tool/Bundle/ApiBundle/Resources/config/event_subscribers.yml, src/Akeneo/Tool/Bundle/ApiBundle/Resources/config/security.yml, src/Akeneo/Tool/Bundle/ApiBundle/Security/Firewall.php, src/Akeneo/Tool/Bundle/ApiBundle/tests/integration/EventSubscriber/ValidateApiRequestQueryParametersSubscriberIntegration.php, tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/ErrorListProductEndToEnd.php
https://akeneo.atlassian.net/browse/API-1824
=> API-1824: (ADR) API array query parameter validation

src/Akeneo/UserManagement/Bundle/Context/UserContext.php, src/Akeneo/UserManagement/Bundle/EventListener/LocaleSubscriber.php, src/Akeneo/UserManagement/Bundle/Provider/CustomDaoAuthenticationProvider.php, tests/back/UserManagement/Specification/Bundle/Context/UserContextSpec.php
=> OBS-127: add sanity checks to make onboarder serenity authentication possible

composer.json, composer.lock, tests/legacy/features/Context/DataGridContext.php, tests/legacy/features/Context/FeatureContext.php
Should fix a few dependabot alerts.
=> Update Composer dependencies for 5.0

CHANGELOG.md, src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Standard/Product/AssociationsNormalizer.php
=> PIM-10514: Fix associations normalization for published products

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/common/file-path.js
- Display host when storage is SFTP
=> RAB-668: Display host when storage is SFTP

src/Akeneo/Pim/Enrichment/Product/back/API/Command/UserIntent/SetMultiReferenceDataValue.php, src/Akeneo/Pim/Enrichment/Product/back/API/Command/UserIntent/SetSimpleReferenceDataValue.php, src/Akeneo/Pim/Enrichment/Product/back/Application/Applier/SetMultiReferenceDataValueApplier.php, src/Akeneo/Pim/Enrichment/Product/back/Application/Applier/SetSimpleReferenceDataValueApplier.php, src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Symfony/Resources/config/appliers.yml, src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductIntegration.php, src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/API/Command/UserIntent/SetMultiReferenceDataValueSpec.php, src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/API/Command/UserIntent/SetSimpleReferenceDataValueSpec.php, src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Application/Applier/SetMultiReferenceDataValueApplierSpec.php, src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Application/Applier/SetSimpleReferenceDataValueApplierSpec.php, tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/ReferenceData/ReferenceDataMultiSelectFilterIntegration.php, tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/ReferenceData/ReferenceDataSimpleSelectFilterIntegration.php
=> CPM-673: add set simple/multi reference data user intents

CHANGELOG-5.0.md, src/Akeneo/Tool/Component/StorageUtils/Exception/UnknownPropertyException.php
PR #17319 mistakenly merged. Reverting changes.
=> Revert #17319

CHANGELOG-6.0.md
EE : https://github.com/akeneo/pim-enterprise-dev/pull/14220
=> OCT-82: PULL UP 6.0

src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/translations/jsmessages.en_US.yml, src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/SftpStorageConfigurator.test.tsx, src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/SftpStorageConfigurator.tsx, src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/hooks/useCheckStorageConnection.test.ts, src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/hooks/useCheckStorageConnection.ts
- Update check storage button label
- Disable check storage button when required fields are missing
- Change Tailored Imports doc link
=> RAB-877: Disable check storage button when required fields are missing

CHANGELOG.md, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/validation/product.yml, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/validation/productmodel.yml, src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/validators.en_US.yml, tests/back/Pim/Enrichment/Integration/Validation/ProductIdentifierValidationIntegration.php
=> PIM-10501: Fix line break validation in product/product models identifiers in imports

src/Akeneo/Pim/Enrichment/Product/back/API/Query/GetProductUuidsQuery.php, src/Akeneo/Pim/Enrichment/Product/back/Application/PQB/GetProductUuidsHandler.php, src/Akeneo/Pim/Enrichment/Product/back/Domain/PQB/ProductQueryBuilderInterface.php, src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Query/Elasticsearch/ProductQueryBuilderAdapter.php, src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/PQB/GetProductUuidsHandlerIntegration.php, src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Application/PQB/GetProductUuidsHandlerSpec.php, src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Infrastructure/Query/Elasticsearch/ProductQueryBuilderAdapterSpec.php
See https://github.com/akeneo/pim-enterprise-dev/pull/14260
=> CPM-678: add search_after capability in PQB service API

composer.json, composer.lock
#17401 was not included in the last 5.0 -> 6.0 pull-up
=> PIM-10520: Upgrade Guzzle bundle

src/Akeneo/Pim/Enrichment/Bundle/Command/IndexProductCommand.php
=> BH-1075-1:Add a check between MySQL and Elasticsearch

src/Akeneo/Pim/Enrichment/Bundle/Command/IndexProductModelCommand.php
Add diff to resolve differences between MySQL and Elasticsearch on ProductModelCommand
=> BH-1199 : Add diff to resolve differences between MySQL and Elasticsearch

src/Akeneo/Platform/Bundle/ImportExportBundle/Controller/InternalApi/JobInstanceController.php
=> RAB-914: fix SFTP credentials encryption for GROWTH & TRIAL

src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/controllers.yml
In this PR, I replaced the SimpleJobLauncher definition by the AuthenticatedJobLauncher one.
This change allows to have a better history in CE & GE.
Before :
After:
Also, it fixes Tailored Import in GE because we need to get the userId of the launching user to pass it to Product Service API.
=> RAC-1254: Use the AuthenticatedJobLauncher in every edition

src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Completeness/SqlSaveProductCompletenesses.php
The previous fix of the completeness save was done to prevent database locks during migration.
But it introduce performance issues.
Now that the instances are all migrated, we can revert it to put it back to origin.
=> [adr-uuid] Revert previous completeness save

src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Connector/SqlGetConnectorProducts.php, src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Connector/SqlGetConnectorProductsWithOptions.php, src/Akeneo/Pim/Enrichment/Component/Product/Connector/ReadModel/ConnectorProductList.php, src/Akeneo/Pim/Enrichment/Component/Product/Query/GetConnectorProducts.php, src/Akeneo/Pim/Enrichment/Component/Product/Webhook/ProductCreatedAndUpdatedEventDataBuilder.php, tests/back/Pim/Enrichment/Integration/Storage/Sql/Connector/SqlGetConnectorProductsIntegration.php, tests/back/Pim/Enrichment/Integration/Storage/Sql/Connector/SqlGetConnectorProductsWithOptionsIntegration.php, tests/back/Pim/Enrichment/Specification/Component/Product/Webhook/ProductCreatedAndUpdatedEventDataBuilderSpec.php
=> CPM-634: Add Connector Product creation through Uuids

CHANGELOG.md, src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Versioning/Product/ValueNormalizer.php
Seen in discussion with [Alex in dedicated slack channel](https://akeneo.slack.com/archives/C03PPGC075X/p1658155083750279).
=> PIM-10518: Revert ValueNormalizer.php

src/Akeneo/Tool/Bundle/BatchQueueBundle/Launcher/QueueJobLauncher.php, src/Akeneo/Tool/Bundle/BatchQueueBundle/spec/Launcher/QueueJobLauncherSpec.php, src/Oro/Bundle/PimDataGridBundle/Controller/ProductExportController.php
=> RAB-FIX: RAB: Quick fix product export does not work on srnt-pim-pce due to filePath presence on configuration

src/Akeneo/Pim/Enrichment/Bundle/Command/IndexProductCommand.php
I did a mistake during a rebase, we both touched the same file and I didn't check the command.
This PR fixes it
=> Fix indexation rebase

CHANGELOG.md, src/Akeneo/Pim/Enrichment/Bundle/Controller/Ui/AbstractListCategoryController.php, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/TreeAssociate.tsx
Fix selected categories sent to listCategories
=> PIM-10543: Fix selected categories sent to listCategories

src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/DeleteProductByUuidController.php, src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/GetProductByUuidController.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/controllers.yml, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/normalizers.yml, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/routing/external_api/product.yml, src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/ExternalApi/ConnectorProductWithUuidNormalizer.php, src/Akeneo/Pim/Enrichment/Component/Product/Webhook/ProductCreatedAndUpdatedEventDataBuilder.php, tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/DeleteProductWithUuidEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/GetProductWithUuidEndToEnd.php, tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/ExternalApi/ConnectorProductWithUuidNormalizerSpec.php
Add a new API endpoint to access products through their UUID.
=> CPM-634: Add Get Product endpoint

components/catalogs/Makefile, components/catalogs/back/tests/Integration/Infrastructure/Persistence/GetProductIdentifiersQueryTest.php, components/catalogs/back/tests/Integration/Infrastructure/Persistence/GetProductUuidFromIdentifierQueryTest.php, components/catalogs/back/tests/Integration/IntegrationTestCase.php
=> PIM-10545: catalogs fix

src/Akeneo/Tool/Bundle/BatchBundle/DependencyInjection/AkeneoBatchExtension.php, src/Akeneo/Tool/Bundle/BatchBundle/Job/DoctrineJobRepository.php, src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/jobs.yml, src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/test/jobs.yml, src/Akeneo/Tool/Bundle/BatchBundle/tests/Integration/Job/DoctrineJobRepositoryIntegration.php, src/Akeneo/Tool/Bundle/BatchBundle/tests/Integration/Job/DumbStep.php, src/Akeneo/Tool/Component/Batch/Job/JobRegistry.php, src/Akeneo/Tool/Component/Batch/spec/Job/JobRegistrySpec.php
If a feature is not enabled yet, it should not be visible in the process tracker. For example, with GE with feature flags, there is a bug for the rule job:  it is visible because the rule cronjob is executed (same infra as serenity). 
Also, confirmed with PM: if a feature is enabled due to an upgrade, you should see the new jobs executed **since** the upgrade, but not the old one when the feature was deactivated.
We could either:
1. prevent the execution of the job in the command itself (execute rule for example),  which impact every commands
2. or make it invisible when executing the job
As a reminder, executing a job of a deactivated feature is not necessary useless. It can help to prepare data in case of an upgrade for example, etc …
=> TIP-1597: do not display jobs of features that are not activated yet

src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Elasticsearch/BulkUpdateProductQualityScoresIndex.php, src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Infrastructure/Elasticsearch/Query/GetProductKeyIndicatorsQueryIntegration.php, src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Elasticsearch/BulkUpdateProductQualityScoresIndexSpec.php, src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/Category/OnDelete/UpdateIndexesOnCategoryDeletion.php, src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/Family/FamilyAttributeAsLabelChangedSubscriber.php, tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/Family/FamilyAttributeAsLabelChangedSubscriberSpec.php
=> GRF-209: Fix deprecation on ES

tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/ErrorListProductWithUuidEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/ListProductWithUuidAndCompletenessEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/SuccessListVariantProductWithUuidDeltaEndToEnd.php
Add tests for https://github.com/akeneo/pim-community-dev/pull/17494
=> CPM-638: Add tests for LIST endpoint

src/Akeneo/Tool/Bundle/VersioningBundle/Doctrine/Query/SqlGetAllButLastVersionIdsByIdsQuery.php
The query is very slow, due to the OR condition.
```
| -> Nested loop semijoin  (cost=1539.49 rows=556) (actual time=98017.088..98017.088 rows=0 loops=1)
-> Filter: (`current`.id in (884307,884306))  (cost=2.05 rows=2) (actual time=0.038..1.241 rows=2 loops=1)
-> Index range scan on current using PRIMARY  (cost=2.05 rows=2) (actual time=0.037..1.235 rows=2 loops=1)
-> Filter: ((latest.resource_id = `current`.resource_id) or (`current`.resource_id is null))  (cost=194222.98 rows=278) (actual time=49007.921..49007.921 rows=0 loops=2)
-> Index lookup on latest using resource_name_resource_uuid_version_idx (resource_name=`current`.resource_name), with index condition: (((latest.resource_uuid = `current`.resource_uuid) or …
```
=> CPM-696: fix performance issue on versioning purge that last several days even on small catalogs

src/Akeneo/Tool/Bundle/ApiBundle/tests/integration/ApiTestCase.php, tests/back/Integration/Configuration.php, tests/back/Integration/IntegrationTestsBundle/Configuration/Catalog.php, tests/back/Integration/TestCase.php, tests/back/Pim/Enrichment/Integration/Product/DeleteUniqueValueInDatabaseIntegration.php
See https://github.com/akeneo/pim-enterprise-dev/pull/14428
=> fix: allow to configure feature flag before loading catalog

src/Akeneo/Tool/Component/Api/Normalizer/Exception/ViolationNormalizer.php
See https://github.com/akeneo/pim-enterprise-dev/pull/14450
=> Update phpstan version on asset manager, the normalizer need to say that returned value is array

CHANGELOG-5.0.md, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/factories.yml, src/Akeneo/Pim/Enrichment/Component/Product/Factory/NonExistentValuesFilter/NonExistentChannelLocaleValuesFilter.php, tests/back/Pim/Enrichment/Integration/PQB/ProductQueryBuilderIntegration.php, tests/back/Pim/Enrichment/Specification/Component/Product/Factory/NonExistentValuesFilter/NonExistentChannelLocaleValuesFilterSpec.php
=> PIM-10551: Add filtering on locale specific attributes when fetching values

std-build/package.json
Some front contexts have been created in CE, but there were not replicated into std-build/package.json file.
=> PIM-10558 add new contexts to std build

src/Akeneo/Category/front/src/configuration/ConfigurationProvider.tsx, src/Akeneo/Category/front/src/index.tsx
Category microfrontend configuration persisting in localstorage, for DX
=> GRF-229 categories microfrontend configuration now persisting in localstorage

front-packages/akeneo-design-system/src/components/Field/Field.tsx, front-packages/akeneo-design-system/src/components/Input/MediaFileInput/MediaFileInput.tsx, src/Akeneo/Category/front/src/FakePIM.tsx, src/Akeneo/Category/front/src/feature/components/EditAttributesForm.tsx, src/Akeneo/Category/front/src/feature/components/EditPermissionsForm.tsx, src/Akeneo/Category/front/src/feature/components/EditPropertiesForm.tsx, src/Akeneo/Category/front/src/feature/components/Style.tsx, src/Akeneo/Category/front/src/feature/components/index.ts, src/Akeneo/Category/front/src/feature/pages/CategoryEditPage.tsx
Enriched categories : new tab "attributes" to allow attribute edition.
Minor changes in design system in Field component and File Input requested by UX team.
=> GRF-108 tab 'attributes' in category edition component

src/Akeneo/Category/front/src/configuration/ConfigurationProvider.tsx, src/Akeneo/Category/front/src/configuration/Page.tsx
When we select community edition, the feature flag enrich category must be checked
Remove checkbox for Growth edition
=> GRF-230: Update configuration page in microfrontend

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/router.js
Display this message (in red) to user who don't have permission to access the product.
=> GRF-72: Fix message on 403

src/Akeneo/Category/front/src/feature/legacy/components/EditPermissionsForm.tsx, src/Akeneo/Category/front/src/feature/legacy/components/EditPropertiesForm.tsx, src/Akeneo/Category/front/src/feature/legacy/components/StyleLegacy.tsx
=> GRF-236: Fix FT and GE build issue

src/Akeneo/Category/back/Api/Command/UpsertCategoryCommand.php, src/Akeneo/Category/back/Infrastructure/Controller/InternalAPI/UpdateCategoryController.php
Update the categroy command identifier with the unique category code. This allow us to use command for update AND insert a category and using the code as unique identifier for import and export features.
=> GRF - Command : Update category identifier by category code

CHANGELOG-5.0.md, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/factories.yml, src/Akeneo/Pim/Enrichment/Component/Product/Factory/NonExistentValuesFilter/NonExistentChannelLocaleValuesFilter.php, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/associations.js, src/Akeneo/Tool/Bundle/MeasureBundle/Validation/Common/CodeValidator.php, tests/back/Pim/Enrichment/Specification/Component/Product/Factory/NonExistentValuesFilter/NonExistentChannelLocaleValuesFilterSpec.php, upgrades/schema/Version_5_0_20220801160000_modify_metric_family_and_default_metric_unit.php, upgrades/test_schema/Version_5_0_20220801160000_modify_metric_family_and_default_metric_unit_Integration.php
=> Pull up 60 into master

src/Akeneo/Category/back/Infrastructure/Controller/InternalApi/UpdateCategoryController.php, src/Akeneo/Category/back/Infrastructure/Storage/Sql/SqlFindOneByIdentifier.php, src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/controllers.yml, src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/queries.yml
As per discussion, minor refactoring regarding the camel case rule.
=> GRF Refactoring according CamelCase rule

src/Akeneo/Platform/Job/back/Infrastructure/Installer/JobInstaller.php, src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/model/doctrine/JobInstance.orm.yml, src/Akeneo/Tool/Component/Batch/Model/JobInstance.php, upgrades/schema/Version_7_0_20220802151250_add_automation_column_in_job_instance.php, upgrades/test_schema/Version_7_0_20220802151250_add_automation_column_in_job_instance_integration.php
add a new column to store automation configuration in job_instance table, and an indexed column to check if a job_instance is automated or not. Since we have client with more than 1000+ entry in the table scheduled boolean column is indexed.
=> RAB-945: migration DB

src/Akeneo/Tool/Component/Batch/Normalizer/Standard/JobInstanceNormalizer.php, src/Akeneo/Tool/Component/Batch/Updater/JobInstanceUpdater.php, src/Akeneo/Tool/Component/Batch/spec/Normalizer/Standard/JobInstanceNormalizerSpec.php, tests/back/Platform/EndToEnd/ImportExport/InternalApi/GetJobExecutionEndToEnd.php
change updater add scheduled and automation support
=> RAB-946: Migration code

make-file/category.mk, src/Akeneo/Category/back/tests/.php_cd.php
=> GRF : Fix make file acceptance test and coupling test

docker-compose.override-osx.yml
Remove the docker-compose.override.yml configuration from notion and add it to the PIM.
=> Versionnize OS X configuration for docker

src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml, src/Akeneo/Connectivity/Connection/front/src/connect/components/Marketplace.tsx, src/Akeneo/Connectivity/Connection/front/src/connect/components/MarketplaceHelper.tsx, src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/Marketplace.test.tsx
=> CXP-1169: Add a search bar on the PIM App Store page

src/Akeneo/Pim/Enrichment/Bundle/Command/ZddMigrations/V20220729171405CleanVersioningResourceUuidColumnForNonProductVersions.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/cli_command.yml, src/Akeneo/Platform/Bundle/InstallerBundle/Command/MigrateZddCommand.php, tests/back/Pim/Enrichment/Integration/Product/V20220729171405CleanVersioningResourceUuidColumnForNonProductVersionsIntegration.php, upgrades/schema/Version_7_0_20220728121643_remove_uuid_triggers.php, upgrades/test_schema/Version_7_0_20220722090828_remove_old_file_path_on_product_and_product_model_quick_export_job_Integration.php, upgrades/test_schema/Version_7_0_20220728121643_remove_uuid_triggers_Integration.php
Introduced first in this PR https://github.com/akeneo/pim-community-dev/pull/17544. Created a new PR because of the CI deployment failing.
=> CPM-691: Remove triggers introduced during UUID migration + Clean versioning #17544 

src/Akeneo/Connectivity/Connection/back/Application/Settings/Command/CreateConnectionCommand.php, src/Akeneo/Connectivity/Connection/back/Application/Settings/Command/CreateConnectionHandler.php, src/Akeneo/Connectivity/Connection/back/Application/Settings/Validation/Connection/UserGroupMustExist.php, src/Akeneo/Connectivity/Connection/back/Application/Settings/Validation/Connection/UserGroupMustExistValidator.php, src/Akeneo/Connectivity/Connection/back/Infrastructure/Connections/Command/CreateConnectionCommand.php, src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Connections/command.yml, src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Settings/validators.yml, src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/validation/CreateConnectionCommand.yml, src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml, src/Akeneo/Connectivity/Connection/back/tests/.php_cd.php, src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Connection/Command/CreateConnectionCommandEndToEnd.php, src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Application/Settings/Command/CreateConnectionHandlerSpec.php
=> OCT-98: add an user-group option to the akeneo:connectivity-connection:create command

CHANGELOG-5.0.md, src/Akeneo/Pim/Structure/Bundle/EventSubscriber/ComputeFamilyVariantStructureChangesSubscriber.php, src/Akeneo/Pim/Structure/Bundle/EventSubscriber/SaveFamilyVariantOnFamilyUpdateSubscriber.php, src/Akeneo/Pim/Structure/Bundle/Resources/config/event_subscribers.yml, src/Akeneo/Pim/Structure/Component/Model/Family.php, src/Akeneo/Pim/Structure/Component/Model/FamilyInterface.php, src/Akeneo/Pim/Structure/Component/Model/FamilyVariant.php, src/Akeneo/Pim/Structure/Component/Model/FamilyVariantInterface.php, src/Akeneo/Pim/Structure/Component/Normalizer/ExternalApi/AttributeNormalizer.php, src/Akeneo/Pim/Structure/Component/Updater/FamilyUpdater.php, src/Akeneo/Pim/Structure/Component/Updater/FamilyVariantUpdater.php, tests/back/Pim/Enrichment/Integration/EntityWithFamilyVariant/ChangeVariantFamilyStructureIntegration.php, tests/back/Pim/Structure/EndToEnd/AttributeGroup/ExternalApi/CreateAttributeGroupEndToEnd.php, tests/back/Pim/Structure/Specification/Bundle/EventSubscriber/ComputeFamilyVariantStructureChangesSubscriberSpec.php, tests/back/Pim/Structure/Specification/Bundle/EventSubscriber/SaveFamilyVariantOnFamilyUpdateSubscriberSpec.php, tests/back/Pim/Structure/Specification/Component/Model/FamilySpec.php, tests/back/Pim/Structure/Specification/Component/Model/FamilyVariantSpec.php, tests/back/Pim/Structure/Specification/Component/Normalizer/ExternalApi/AttributeNormalizerSpec.php, tests/back/Pim/Structure/Specification/Component/Updater/FamilyUpdaterSpec.php, tests/back/Pim/Structure/Specification/Component/Updater/FamilyVariantUpdaterSpec.php, tests/legacy/features/pim/structure/family/remove_attribute_from_a_family.feature
=> Pim 10582 : Pullup 5.0 into 6.0

CHANGELOG.md, src/Akeneo/Pim/Enrichment/Component/Product/Connector/ReadModel/ConnectorProduct.php, tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ReadModel/ConnectorProductSpec.php
=> PIM-10581: Fix attribute option code in linked data returned as an integer instead of a string

src/Akeneo/UserManagement/Bundle/Resources/config/service_api/queries.yml, src/Akeneo/UserManagement/Component/Model/User.php, src/Akeneo/UserManagement/Component/Model/UserInterface.php, src/Akeneo/UserManagement/back/Application/Handler/UpsertUserHandler.php, src/Akeneo/UserManagement/back/ServiceApi/User/UpsertUserCommand.php, src/Akeneo/UserManagement/back/ServiceApi/User/UpsertUserHandlerInterface.php, src/Akeneo/UserManagement/back/ServiceApi/ViolationsException.php, src/Akeneo/UserManagement/back/tests/Integration/ServiceApi/User/UpsertUserHandlerIntegration.php
In this PR, we added the a new PublicAPI to create a user. For now we only need it for job user type
=> RAB-935: Add UpsertUser ServiceAPI 

src/Akeneo/Pim/Enrichment/Component/Product/Builder/ProductBuilder.php, src/Akeneo/Pim/Enrichment/Component/Product/Builder/ProductBuilderInterface.php, src/Akeneo/Pim/Enrichment/Component/Product/Model/AbstractProduct.php, tests/back/Pim/Enrichment/Specification/Component/Product/Builder/ProductBuilderSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Model/ProductSpec.php
Allow defining a new product's uuid at instantiation time
=> CPM-708: Define uuid during product instantiation

CHANGELOG-5.0.md, src/Akeneo/Platform/Bundle/ImportExportBundle/Query/GetWarningCount.php
=> PIM-10587: Fix warnings count in process tracker

src/Akeneo/Pim/Enrichment/Product/back/API/Command/UserIntent/SetPriceValue.php, src/Akeneo/Pim/Enrichment/Product/back/Application/Applier/SetPriceCollectionValueApplier.php, src/Akeneo/Pim/Enrichment/Product/back/Application/Applier/SetPriceValueApplier.php, src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Symfony/Resources/config/appliers.yml, src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Validation/UserIntentsShouldBeUniqueValidator.php, src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductIntegration.php, src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/API/Command/UserIntent/SetPriceValueSpec.php, src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Application/Applier/SetPriceValueApplierSpec.php, src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Infrastructure/Validation/UserIntentsShouldBeUniqueValidatorSpec.php
This PR add a product user intent to set a price for one currency
=> RAB-955: Add SetPriceValue service API

components/catalogs/back/src/Infrastructure/Persistence/GetProductIdentifiersQuery.php
`IdentifierResult::getIdentifier()` is nullable since https://github.com/akeneo/pim-community-dev/pull/17619
We are not using the Service API yet and the current query `GetProductIdentifiersQuery` is destined to be removed soon.
As a consequence, we introduce this small fix instead of handling it differently.
=> OCT-109: fallback to product UUID when identifier is null

CHANGELOG.md, src/Akeneo/Pim/Enrichment/Product/back/API/Command/UserIntent/SetSimpleReferenceEntityValue.php, src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/API/Command/UserIntent/SetSimpleReferenceEntityValueSpec.php
=> PIM-10595: Fix not being able to add record with code 0 on a product

src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Install/CreateAppTableQuery.php, src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Persistence/SaveConnectedAppOutdatedScopesFlagQuery.php, src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Persistence/UpdateConnectedAppDescriptionQuery.php, src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Persistence/UpdateConnectedAppScopesQuery.php, src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/Persistence/CreateConnectedAppQueryIntegration.php, src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/Persistence/UpdateConnectedAppScopesQueryIntegration.php, upgrades/schema/Version_7_0_20220803111111_add_created_and_updated_date_to_connected_app_table.php
=> CXP-1268: Add created_at & updated_at on connected apps

CHANGELOG-5.0.md
=> PIM-10597: Pull-up 5.0 => 6.0

src/Akeneo/Pim/Enrichment/Product/back/Domain/Query/GetProductUuids.php, src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Query/Cache/LRUCacheGetProductUuids.php, src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Query/SqlGetProductUuids.php, src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Symfony/Resources/config/queries.yml, src/Akeneo/Pim/Enrichment/Product/back/Test/.php_cd.php, src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Infrastructure/Query/Cache/LRUCacheGetProductUuidsSpec.php, tests/back/Category/Integration/Query/SqlGetProductUuidsIntegration.php
Add GetProductUuids sql query and cached query
=> CPM-710: Add GetProductUuids sql query and cached query

src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetCategorySql.php, src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetCategorySqlIntegration.php
=> GRF-273: Fix query not returning anything when a category has no associated translations

upgrades/schema/Version_7_0_20220818143128_remove_zdd_setidentifiernullable_from_pim_one_time_task_table.php, upgrades/test_schema/Version_7_0_20220818143128_remove_zdd_setidentifiernullable_from_pim_one_time_task_table_Integration.php
Thanks JM [for spotting this issue](https://akeneo.slack.com/archives/C031QDW61/p1661244500766949)
=> CPM-692: Fix migration name

src/Akeneo/Pim/Enrichment/Bundle/Command/ZddMigrations/V20220729171405CleanVersioningResourceUuidColumnForNonProductVersions.php, upgrades/schema/Version_7_0_20220728121643_remove_uuid_triggers.php, upgrades/test_schema/Version_7_0_20220728121643_remove_uuid_triggers_Integration.php
Remove only the uuid triggers related to versionning.
=> CPM-691: Fix remove uuid triggers migration

src/Akeneo/Pim/Enrichment/Product/back/Test/Acceptance/Context/ProductContext.php, src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductAssociationsIntegration.php, src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductIntegration.php, src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductVariantIntegration.php, src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductWithPermissionIntegration.php, src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertQuantifiedAssociationsIntegration.php, src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/API/CommandMessageBusSpec.php, src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Application/UpsertProductHandlerSpec.php, src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Infrastructure/Validation/AttributeGroupShouldBeEditableValidatorSpec.php, src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Infrastructure/Validation/CategoriesShouldBeViewableValidatorSpec.php, src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Infrastructure/Validation/IsUserOwnerOfTheProductValidatorSpec.php, src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Infrastructure/Validation/LocaleShouldBeEditableByUserValidatorSpec.php, src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Infrastructure/Validation/ShouldStayOwnerOfTheProductValidatorSpec.php
=> CPM-698: Use createFromCollection for UpsertProductCommand

.circleci/jobs/build_and_deploy.yml
Details of changes: https://github.com/akeneo/cloud-tools/blob/master/cloud-deployer/CHANGELOG.md
=> SDO-223-pimc - Upgrade cloud-deployer image

components/catalogs/front/src/components/ProductSelection/hooks/useCategories.unit.ts, components/catalogs/front/tests/ReactQueryWrapper.tsx
=> CXP-1237: fix react query retry handling

src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_base_export_edit.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_base_import_edit.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_product_export_edit.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_product_import_edit.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_product_model_export_edit.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_product_model_import_edit.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_base_export_edit.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_base_import_edit.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_product_export_edit.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_product_import_edit.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_product_model_export_edit.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_product_model_import_edit.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/yml_base_export_edit.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/yml_base_import_edit.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/export/common/edit/properties.html
Add additional properties drop zone to be outside of the `.AknFormContainer` and its restrictive layout options
=> RAB-979: Add additional properties drop zone

CHANGELOG-5.0.md, src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Standard/Product/ProductValueNormalizer.php, tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/Standard/Product/ProductValueNormalizerSpec.php
=> PIM-10601: Backport PIM-9718 on 5.0 branch

CHANGELOG-6.0.md, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/less/data-quality-insights-attributes.less
=> PIM-10590: Fix capitalizing every first letter of attribute label in Data Quality Insights tab

CHANGELOG-5.0.md, frontend/webpack/requirejs-utils.js, package.json, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/button/Button.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/summernote/summernote.js, webpack.config.js, yarn.lock
https://akeneo.atlassian.net/browse/PIM-10577
The real fix is here
https://github.com/akeneo/pim-community-dev/pull/17725/commits/0d8b04dfc1a7c8a25d2334437f5758d562ac42f2#diff-6b14d7bcd3fff89dd544dd8bb464001218d12aa07409fb2dbb77c4e867c195a1R5258
=> PIM-10577: Fix PASTE event for summernote

CHANGELOG-5.0.md, src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Repository/ProductModelRepository.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/doctrine/Product/ProductModel.orm.yml
=> PIM-10580: Backport PIM-10499 on 5.0 branch

src/Akeneo/Pim/Enrichment/Product/back/API/Command/UserIntent/ClearPriceValue.php, src/Akeneo/Pim/Enrichment/Product/back/Application/Applier/ClearPriceValueApplier.php, src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Symfony/Resources/config/appliers.yml, src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Validation/UserIntentsShouldBeUniqueValidator.php, src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductIntegration.php, src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/API/Command/UserIntent/ClearPriceValueSpec.php, src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/API/Command/UserIntent/SetPriceCollectionValueSpec.php, src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Application/Applier/ClearPriceValueApplierSpec.php, src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Application/Applier/ClearValueApplierSpec.php, src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Infrastructure/Validation/UserIntentsShouldBeUniqueValidatorSpec.php
=> RAB-956: Add clear price value user intent 

src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev/jobs.yml, src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/minimal/jobs.yml, src/Akeneo/Tool/Bundle/VersioningBundle/Command/PurgeCommand.php, src/Akeneo/Tool/Bundle/VersioningBundle/Job/JobParameters/PurgeVersioning.php, src/Akeneo/Tool/Bundle/VersioningBundle/Job/PurgeVersioning.php, src/Akeneo/Tool/Bundle/VersioningBundle/Purger/VersionPurger.php, src/Akeneo/Tool/Bundle/VersioningBundle/Purger/VersionPurgerInterface.php, src/Akeneo/Tool/Bundle/VersioningBundle/Resources/config/cli_commands.yml, src/Akeneo/Tool/Bundle/VersioningBundle/Resources/config/jobs.yml, src/Akeneo/Tool/Bundle/VersioningBundle/Resources/config/purgers.yml, src/Akeneo/Tool/Bundle/VersioningBundle/tests/integration/Command/PurgeVersioningCommandIntegration.php, tests/back/Integration/catalog/technical/jobs.yml, upgrades/schema/Version_7_0_20220823094700_add_scheduled_jobs.php, upgrades/test_schema/Version_7_0_20220822173400_add_scheduled_jobs_Integration.php
Add a new job to purge versioning and refactor the command to launch this new job.
=> PH-172: Purge versioning batch job

CHANGELOG-5.0.md, frontend/webpack/requirejs-utils.js, package.json, src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Repository/ProductModelRepository.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/doctrine/Product/ProductModel.orm.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/button/Button.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/summernote/summernote.js, webpack.config.js, yarn.lock
=> PIM-10604: Pull-up 5.0 into 6.0

CHANGELOG.md, upgrades/schema/Version_7_0_20220824134638_add_missing_remove_completeness_for_channel_and_locale_job_instance.php, upgrades/test_schema/Version_7_0_20220824134638_add_missing_remove_completeness_for_channel_and_locale_job_instance_Integration.php
=> PIM-10588: Add migration to create potentially missing job instance

src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/UserManagement/UpsertRunningUser.php, src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/services.yml, src/Akeneo/Platform/Bundle/ImportExportBundle/Test/.php_cd.php, src/Akeneo/UserManagement/Bundle/Resources/config/queries.yml, src/Akeneo/UserManagement/Bundle/Resources/config/service_api/handler.yml, src/Akeneo/UserManagement/back/Application/Handler/ListUserRoleHandler.php, src/Akeneo/UserManagement/back/Domain/Model/UserRole.php, src/Akeneo/UserManagement/back/Domain/Storage/FindAllUserRoles.php, src/Akeneo/UserManagement/back/Infrastructure/Storage/SqlFindAllUserRoles.php, src/Akeneo/UserManagement/back/ServiceApi/UserRole/ListUserRoleInterface.php, src/Akeneo/UserManagement/back/ServiceApi/UserRole/UserRole.php, src/Akeneo/UserManagement/back/tests/Integration/Infrastructure/Storage/SqlFindAllUserRolesIntegration.php, src/Akeneo/UserManagement/back/tests/Integration/ServiceApi/UserRole/ListUserRoleQueryIntegration.php, tests/back/Platform/Specification/Bundle/ImportExportBundle/Infrastructure/UserManagement/UpsertRunningUserSpec.php
- Service API to list all user roles
=> RAB-981: Add ListUserRole service API

src/Akeneo/Tool/Bundle/StorageUtilsBundle/Doctrine/Common/Saver/BaseSaver.php, src/Akeneo/Tool/Bundle/StorageUtilsBundle/spec/Doctrine/Common/Saver/BaseSaverSpec.php, src/Akeneo/Tool/Component/FileStorage/Exception/FileAlreadyExistsException.php, src/Akeneo/Tool/Component/FileStorage/File/FileStorer.php, src/Akeneo/Tool/Component/FileStorage/File/FileStorerInterface.php, src/Akeneo/Tool/Component/StorageUtils/Exception/DuplicateObjectException.php, src/Akeneo/Tool/Component/StorageUtils/Saver/SaverInterface.php
=> RAC-1241: Throw business exception in BaseSaver & FileStorer

front-packages/shared/src/microfrontend/DangerousMicrofrontendAutomaticAuthenticator.ts
`?` added
https://akeneo.atlassian.net/jira/software/projects/OCT/boards/289?selectedIssue=OCT-113
=> OCT-113: fix DangerousMicrofrontendAutomaticAuthenticator

src/Akeneo/Pim/Enrichment/.php_cd.php, src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/CreateProductByUuidController.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/controllers.yml, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/routing/external_api/product.yml, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/updaters.yml, src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/validators.en_US.yml, src/Akeneo/Pim/Enrichment/Component/Product/Model/AbstractProduct.php, src/Akeneo/Pim/Enrichment/Component/Product/ProductModel/Filter/ProductAttributeFilter.php, src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/QuantifiedAssociations.php, src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/QuantifiedAssociationsValidator.php, src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/VariantProductParentValidator.php, src/Akeneo/Pim/Enrichment/Component/Product/Validator/ExternalApi/PayloadFormatValidator.php, tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/CreateProductWithUuidEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/QuantifiedAssociations/AddQuantifiedAssociationsToProductWithUuidEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/ExternalApi/CreateVariantProductEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/ExternalApi/CreateVariantProductWithUuidEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/ExternalApi/PartialUpdateProductToVariantEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/ExternalApi/QuantifiedAssociations/AddQuantifiedAssociationsToVariantProductWithUuidEndToEnd.php, tests/back/Pim/Enrichment/Integration/Product/CreateVariantProductIntegration.php, tests/back/Pim/Enrichment/Specification/Component/Product/Model/ProductSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/ProductModel/Filter/ProductAttributeFilterSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/VariantProductParentValidatorSpec.php, tests/legacy/features/pim/enrichment/product/import/import_variant_products_check_business_rules.feature
Add POST api endpoint with uuid
=> CPM-636: CREATE product external API

make-file/job.mk, make-file/measurement.mk, make-file/test.mk, src/Akeneo/Platform/Job/back/Application/SearchJobExecution/Model/JobExecutionTracking.php, src/Akeneo/Platform/Job/back/tests/Acceptance/Application/FindJobType/FindJobTypeHandlerTest.php, src/Akeneo/Platform/Job/back/tests/Acceptance/Application/SearchJobExecution/SearchJobExecutionHandlerTest.php, src/Akeneo/Platform/Job/back/tests/Acceptance/Application/SearchJobUser/SearchJobUserHandlerTest.php, src/Akeneo/Platform/Job/back/tests/Integration/Infrastructure/Query/FindJobTypeTest.php, src/Akeneo/Platform/Job/back/tests/Integration/Infrastructure/Query/SearchJobExecutionTest.php, src/Akeneo/Platform/Job/back/tests/Integration/Infrastructure/Query/SearchJobUserTest.php, src/Akeneo/Platform/Job/back/tests/Integration/IntegrationTestCase.php, src/Akeneo/Platform/Job/back/tests/rector.php, src/Akeneo/Tool/Bundle/MeasureBundle/Convert/MeasureConverter.php, src/Akeneo/Tool/Bundle/MeasureBundle/spec/Model/MeasurementFamilyCodeSpec.php, src/Akeneo/Tool/Bundle/MeasureBundle/spec/Model/UnitCodeSpec.php, src/Akeneo/Tool/Bundle/MeasureBundle/tests/Acceptance/CreateMeasurementFamilyTest.php, src/Akeneo/Tool/Bundle/MeasureBundle/tests/Acceptance/SaveMeasurementFamilyTest.php, src/Akeneo/Tool/Bundle/MeasureBundle/tests/EndToEnd/ExternalApi/Legacy/ListMeasureFamilyEndToEnd.php, src/Akeneo/Tool/Bundle/MeasureBundle/tests/Integration/Installer/MeasurementInstallerIntegration.php, src/Akeneo/Tool/Bundle/MeasureBundle/tests/rector.php
In this PR: 
- I commited the rector files already launched on the job and measurement bundle. By doing it we have now the history of rector and we can now have a better overview of the code state
- I added the rector process into the CI
- I fixed some rector error due to the fact that we didn't launch version at same version before (new rules)
=> RAC: Commit rector config file

CHANGELOG-6.0.md, src/Akeneo/Connectivity/Connection/back/Infrastructure/Marketplace/WebMarketplaceApi.php, src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/marketplace.yml, src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Marketplace/GetWebMarketplaceUrlEndToEnd.php, src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Marketplace/WebMarketplaceApiSpec.php
https://akeneo.atlassian.net/browse/MW-370
=> MW-370: PIM App store integration of the app-store-api service in the PIM

CHANGELOG-6.0.md, src/Akeneo/Connectivity/Connection/back/Infrastructure/Marketplace/WebMarketplaceApi.php, src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Marketplace/services.yml, src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Marketplace/Controller/Internal/GetWebMarketplaceUrlEndToEnd.php, src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Marketplace/WebMarketplaceApiSpec.php, src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/translations/messages.fi_FI.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/messages.fi_FI.yml
Pull up for https://akeneo.atlassian.net/browse/MW-370
=> Pull up 6.0 into master (MW-370)

.circleci/config.yml, .circleci/configure_docker_mirrors.sh, .circleci/jobs/build_and_deploy.yml, .circleci/jobs/features/other.yml
=> Try to fix CI

src/Akeneo/Platform/Bundle/ImportExportBundle/Controller/InternalApi/JobInstanceController.php
This PR fixes the sftp storage password badly validated : blank password should not be valid.
The issue is located inside the controller because we encrypt the password before validate his raw vaue. If we send a blank raw password, then it is encrypted so is it not blank anymore, then the encrypted value is send to the validator.
I fixes this issue by validating the raw value instead of encrypted value.
=> RAB-1010: Fix storage configuration are badly validated because of CredentialsEncryption

src/Akeneo/Pim/Enrichment/Component/Product/Updater/Setter/AssociationFieldSetter.php, tests/back/Pim/Enrichment/Specification/Component/Product/Updater/Setter/AssociationFieldSetterSpec.php
Handle uuids in AssociationFieldSetter
=> CPM-703: Handle uuids in AssociationFieldSetter

src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/validation/jobinstance.yml, src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/validators.yml, src/Akeneo/Tool/Bundle/BatchBundle/Resources/translations/validators.en_US.yml, src/Akeneo/Tool/Bundle/BatchBundle/Validator/Constraints/DummySchedulingValidator.php, src/Akeneo/Tool/Bundle/BatchBundle/Validator/Constraints/Scheduling.php, src/Akeneo/Tool/Bundle/BatchBundle/spec/Validator/Constraints/SchedulingSpec.php
Add validation to prevent save if Storage is None and Scheluding is enabled
=> RAB-952: Add validation on scheduled job

components/catalogs/back/src/Infrastructure/Persistence/SearchAttributesQuery.php, components/catalogs/back/src/Infrastructure/Validation/CatalogUpdatePayloadValidator.php, components/catalogs/back/src/Infrastructure/Validation/ProductSelection/AttributeCriterion/AttributeMultiSelectCriterion.php, components/catalogs/back/tests/Integration/Infrastructure/Persistence/SearchAttributesQueryTest.php, components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSelection/AttributeCriterion/AttributeMultiSelectCriterionTest.php, components/catalogs/front/src/components/ProductSelection/criteria/AttributeMultiSelectCriterion/AttributeMultiSelectCriterion.integration.tsx, components/catalogs/front/src/components/ProductSelection/criteria/AttributeMultiSelectCriterion/AttributeMultiSelectCriterion.tsx, components/catalogs/front/src/components/ProductSelection/criteria/AttributeMultiSelectCriterion/AttributeMultiSelectOperatorInput.tsx, components/catalogs/front/src/components/ProductSelection/criteria/AttributeMultiSelectCriterion/AttributeMultiSelectValueInput.tsx, components/catalogs/front/src/components/ProductSelection/criteria/AttributeMultiSelectCriterion/factory.ts, components/catalogs/front/src/components/ProductSelection/criteria/AttributeMultiSelectCriterion/factory.unit.ts, components/catalogs/front/src/components/ProductSelection/criteria/AttributeMultiSelectCriterion/index.ts, components/catalogs/front/src/components/ProductSelection/criteria/AttributeMultiSelectCriterion/types.d.ts, components/catalogs/front/src/components/ProductSelection/criteria/AttributeNumberCriterion/factory.ts, components/catalogs/front/src/components/ProductSelection/criteria/AttributeTextCriterion/factory.ts, components/catalogs/front/src/components/ProductSelection/hooks/useFindAttributeCriterionByType.ts, components/catalogs/front/src/components/ProductSelection/hooks/useFindAttributeCriterionByType.unit.ts
https://user-images.githubusercontent.com/1421130/187211913-72e53e68-4b4b-4e96-8d1c-ea96e30fe38b.mp4
=> CXP-1248: Adds AttributeMultiSelectCriterion

src/Akeneo/UserManagement/Bundle/Resources/config/service_api/handler.yml, src/Akeneo/UserManagement/back/Application/Handler/DeleteUserHandler.php, src/Akeneo/UserManagement/back/ServiceApi/User/DeleteUserCommand.php, src/Akeneo/UserManagement/back/ServiceApi/User/DeleteUserHandlerInterface.php, src/Akeneo/UserManagement/back/tests/Integration/ServiceApi/User/DeleteUserHandlerIntegration.php
In this PR I added a new service API to delete an user
=> RAB-998: Add service API to delete user

components/catalogs/back/src/Infrastructure/Persistence/SearchAttributesQuery.php, components/catalogs/back/src/Infrastructure/Validation/CatalogUpdatePayloadValidator.php, components/catalogs/back/src/Infrastructure/Validation/ProductSelection/AttributeCriterion/AttributeTextareaCriterion.php, components/catalogs/back/tests/Integration/Infrastructure/Persistence/SearchAttributesQueryTest.php, components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSelection/AttributeCriterion/AttributeTextareaCriterionTest.php, components/catalogs/back/tests/Integration/IntegrationTestCase.php, components/catalogs/front/src/components/ProductSelection/criteria/AttributeTextareaCriterion/AttributeTextareaCriterion.integration.tsx, components/catalogs/front/src/components/ProductSelection/criteria/AttributeTextareaCriterion/AttributeTextareaCriterion.tsx, components/catalogs/front/src/components/ProductSelection/criteria/AttributeTextareaCriterion/AttributeTextareaOperatorInput.tsx, components/catalogs/front/src/components/ProductSelection/criteria/AttributeTextareaCriterion/AttributeTextareaValueInput.tsx, components/catalogs/front/src/components/ProductSelection/criteria/AttributeTextareaCriterion/factory.ts, components/catalogs/front/src/components/ProductSelection/criteria/AttributeTextareaCriterion/factory.unit.ts, components/catalogs/front/src/components/ProductSelection/criteria/AttributeTextareaCriterion/index.ts, components/catalogs/front/src/components/ProductSelection/criteria/AttributeTextareaCriterion/types.d.ts, components/catalogs/front/src/components/ProductSelection/hooks/useFindAttributeCriterionByType.ts, components/catalogs/front/src/components/ProductSelection/hooks/useFindAttributeCriterionByType.unit.ts
https://user-images.githubusercontent.com/1421130/187690282-d629ffc0-d8d8-43e4-8ae8-b4ed7bbd7cda.mp4
=> CXP-1250: AttributeTextareaCriterion

components/catalogs/back/.php_cd.php, components/catalogs/back/.php_cs.php, components/catalogs/back/src/Application/Persistence/GetProductUuidsQueryInterface.php, components/catalogs/back/src/Application/Persistence/GetProductsQueryInterface.php, components/catalogs/back/src/Infrastructure/Installer/InstallerSubscriber.php, components/catalogs/back/src/Infrastructure/Persistence/GetProductUuidsQuery.php, components/catalogs/back/src/Infrastructure/Persistence/GetProductsQuery.php, components/catalogs/back/src/Infrastructure/Symfony/Resources/config/services.yml, components/catalogs/back/tests/Integration/Fakes/Clock.php, components/catalogs/back/tests/Integration/Fakes/TimestampableSubscriber.php, components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/GetProductIdentifiersActionTest.php, components/catalogs/back/tests/Integration/Infrastructure/Persistence/GetProductIdentifiersQueryTest.php, components/catalogs/back/tests/Integration/Infrastructure/Persistence/GetProductUuidFromIdentifierQueryTest.php, components/catalogs/back/tests/Integration/Infrastructure/Persistence/GetProductUuidsQueryTest.php, components/catalogs/back/tests/Integration/Infrastructure/Persistence/GetProductsQueryTest.php, components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSelection/AttributeCriterion/AbstractAttributeCriterionTest.php, components/catalogs/back/tests/Integration/IntegrationTestCase.php, upgrades/schema/Version_7_0_20220830000000_add_catalog_product_values_filters.php
The new query GetProductsQuery takes a catalog id, a search after, and a limit and returns normalized products where values are already filtered depending on the channels, locales & currencies also configured in your catalog.
=> CXP-1271: GetProductsQuery

src/Akeneo/Platform/Job/back/Infrastructure/Query/SearchJobUser.php, src/Akeneo/Platform/Job/back/tests/Integration/Infrastructure/Query/SearchJobUserTest.php, src/Akeneo/Platform/Job/back/tests/Integration/Loader/FixturesUserHelper.php
Rework query to only include simple users (and not API & job users)
=> RAB-1009: Fetch only simple users in process tracker user filter

components/catalogs/back/src/Infrastructure/Persistence/GetProductsQuery.php
In EE, products have metadatas. We don't want those so I added a whitelist of properties.
=> CXP-1271: whistelist properties of normalized products

src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/Product/UpdateProductController.php
Use uuid to update a product from the UI
=> CPM-632: Update product with uuid from PEF

CHANGELOG-5.0.md, src/Akeneo/Tool/Bundle/BatchBundle/Launcher/JobLauncherInterface.php, src/Akeneo/Tool/Bundle/BatchBundle/Launcher/SimpleJobLauncher.php, src/Akeneo/Tool/Bundle/BatchBundle/Launcher/SynchronousJobLauncher.php, src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/services.yml, src/Akeneo/Tool/Bundle/BatchQueueBundle/Launcher/QueueJobLauncher.php, src/Akeneo/Tool/Bundle/ConnectorBundle/Launcher/AuthenticatedJobLauncher.php
Fix Job execution stuck in status in progress or stopping
=> PIM-10610: backport PIM-10504

upgrades/schema/Version_7_0_20220830000000_add_catalog_product_values_filters.php, upgrades/test_schema/Version_7_0_20220830000000_add_catalog_product_values_filters_Integration.php
I did not test correctly the migration. No excuses here.
The deployment process is not happy about it.
Since the migration is not applied anywhere, we can change it, in my opinion.
=> OCT-120: fix migration

config/services/test_fake/services.yml, src/Akeneo/Platform/Bundle/NotificationBundle/Email/MailNotifier.php, src/Akeneo/Platform/Bundle/NotificationBundle/Email/MailNotifierInterface.php, src/Akeneo/Tool/Component/BatchQueue/Exception/InvalidJobException.php, tests/back/Platform/Acceptance/NotificationBundle/FakeService/FakeMailNotifier.php, tests/back/Platform/Acceptance/NotificationBundle/Resources/config/services.yml
In this PR, 
I mocked the MailerService into acceptance test. By doing this we are now able to assert that email have been sent
=> RAB-1011: Add fake mailer service

src/Akeneo/Platform/Job/back/ServiceApi/JobInstance/File.php, src/Akeneo/Platform/Job/back/ServiceApi/JobInstance/FindJobInstances.php, src/Akeneo/Platform/Job/back/ServiceApi/JobInstance/JobInstance.php, src/Akeneo/Platform/Job/back/ServiceApi/JobInstance/JobInstanceQuery.php, src/Akeneo/Platform/Job/back/ServiceApi/JobInstance/JobInstanceQueryPagination.php, src/Akeneo/Platform/Job/back/ServiceApi/JobInstance/LaunchJobInstanceCommand.php, src/Akeneo/Platform/Job/back/ServiceApi/JobInstance/LaunchJobInstanceHandlerInterface.php, src/Akeneo/Platform/Job/back/ServiceApi/JobInstance/LaunchJobInstanceResult.php
Add serviceApi for launching a job instance
Add serviceApi for retrieving job instances
=> RAB-1008: Add Job ServiceApi

src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/CreateProductByUuidController.php, src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/ProductController.php, src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/UpdateProductByUuidController.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/controllers.yml, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/routing/external_api/product.yml, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/updaters.yml, src/Akeneo/Pim/Enrichment/Component/Product/Updater/ProductUpdater.php, tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/PartialUpdateProductEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/PartialUpdateProductWithUuidEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/QuantifiedAssociations/UpdateQuantifiedAssociationsInProductWithUuidEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/ExternalApi/PartialUpdateProductToVariantWithUuidEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/ExternalApi/PartialUpdateVariantProductWithUuidEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/ExternalApi/PartialUpdateVariantToSimpleWithUuidEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/ExternalApi/QuantifiedAssociations/UpdateQuantifiedAssociationsInVariantProductWithUuidEndToEnd.php
=> CPM-637: Add PATCH endpoint api with uuid

components/catalogs/back/src/Infrastructure/Persistence/SearchAttributesQuery.php, components/catalogs/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml, components/catalogs/back/src/Infrastructure/Validation/CatalogUpdatePayloadValidator.php, components/catalogs/back/src/Infrastructure/Validation/ProductSelection/AttributeCriterion/AttributeIdentifierCriterion.php, components/catalogs/back/src/Infrastructure/Validation/ProductSelection/CriterionOperatorsRequireValueConstraints.php, components/catalogs/back/src/Infrastructure/Validation/ProductSelection/CriterionOperatorsRequireValueConstraintsValidator.php, components/catalogs/back/tests/Integration/Infrastructure/Controller/Internal/GetAttributesActionTest.php, components/catalogs/back/tests/Integration/Infrastructure/Persistence/SearchAttributesQueryTest.php, components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSelection/AttributeCriterion/AttributeIdentifierCriterionTest.php, components/catalogs/front/src/components/ProductSelection/components/Criterion.tsx, components/catalogs/front/src/components/ProductSelection/components/UnknownCriterion.tsx, components/catalogs/front/src/components/ProductSelection/criteria/AttributeBooleanCriterion/factory.ts, components/catalogs/front/src/components/ProductSelection/criteria/AttributeIdentifierCriterion/AttributeIdentifierCriterion.integration.tsx, components/catalogs/front/src/components/ProductSelection/criteria/AttributeIdentifierCriterion/AttributeIdentifierCriterion.tsx, components/catalogs/front/src/components/ProductSelection/criteria/AttributeIdentifierCriterion/AttributeIdentifierOperatorInput.tsx, components/catalogs/front/src/components/ProductSelection/criteria/AttributeIdentifierCriterion/AttributeIdentifierValueMultiInput.tsx, components/catalogs/front/src/components/ProductSelection/criteria/AttributeIdentifierCriterion/AttributeIdentifierValueSingleInput.tsx, components/catalogs/front/src/components/ProductSelection/criteria/AttributeIdentifierCriterion/factory.ts, components/catalogs/front/src/components/ProductSelection/criteria/AttributeIdentifierCriterion/factory.unit.ts, components/catalogs/front/src/components/ProductSelection/criteria/AttributeIdentifierCriterion/index.ts, components/catalogs/front/src/components/ProductSelection/criteria/AttributeIdentifierCriterion/types.d.ts, components/catalogs/front/src/components/ProductSelection/criteria/AttributeMeasurementCriterion/factory.ts, components/catalogs/front/src/components/ProductSelection/criteria/AttributeTextareaCriterion/factory.ts, components/catalogs/front/src/components/ProductSelection/hooks/useFindAttributeCriterionByType.ts, components/catalogs/front/src/components/ProductSelection/hooks/useFindAttributeCriterionByType.unit.ts, components/catalogs/front/src/components/ProductSelection/models/Criterion.d.ts
Commits are clean, you can review them one by one for easy reading.
https://user-images.githubusercontent.com/1421130/187902631-a72b035e-58d9-443f-b109-3727f02e3337.mp4
=> CXP-1252: AttributeIdentifierCriterion

src/Akeneo/Platform/Bundle/NotificationBundle/Email/MailNotifier.php, src/Akeneo/Platform/Bundle/NotificationBundle/Email/MailNotifierInterface.php, src/Akeneo/Platform/Bundle/NotificationBundle/Resources/views/Email/notification.txt.twig, src/Akeneo/Tool/Bundle/BatchBundle/Notification/MailNotifier.php, src/Akeneo/Tool/Bundle/BatchBundle/Resources/views/Email/notification.html.twig, src/Akeneo/Tool/Bundle/BatchBundle/spec/Notification/MailNotifierSpec.php, src/Akeneo/UserManagement/Bundle/Notification/MailResetNotifier.php, tests/back/Platform/Acceptance/NotificationBundle/FakeService/FakeMailNotifier.php, tests/back/UserManagement/Specification/Bundle/Notification/MailResetNotifierSpec.php
In this PR, I changed the way we sent emails in order to send it to multiple recipients as BCC and also modified the email templates accordingly.
=> RAB-1019: Rework email template and send one for all recipients

config/packages/akeneo_api.yml, src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/PartialUpdateListProductsByUuidController.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/controllers.yml, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/routing/external_api/product.yml, src/Akeneo/Tool/Bundle/ApiBundle/Resources/config/stream.yml, src/Akeneo/Tool/Bundle/ApiBundle/Stream/StreamResourceResponse.php, tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/PartialUpdateListProductWithUuidEndToEnd.php
New API endpoint: "PatchProductsByUUID
=> CPM-645: New API endpoint: "PatchProductsByUUID"

src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/appliers.yml
=> GRF-318 : Add applier services

src/Akeneo/Category/back/Api/Command/UserIntents/SetImage.php, src/Akeneo/Category/back/Application/Applier/SetImageApplier.php, src/Akeneo/Category/back/Application/Applier/SetLabelApplier.php, src/Akeneo/Category/back/Application/Applier/SetRichTextApplier.php, src/Akeneo/Category/back/Application/Applier/SetTextApplier.php, src/Akeneo/Category/back/Application/Applier/SetTextAreaApplier.php, src/Akeneo/Category/back/Domain/UserIntent/Factory/ValueUserIntentFactory.php, src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/appliers.yml, src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/validation/category_commands.yml, src/Akeneo/Category/back/tests/Specification/Application/Applier/SetImageApplierSpec.php, src/Akeneo/Category/back/tests/Specification/Application/Applier/SetRichTextApplierSpec.php, src/Akeneo/Category/back/tests/Specification/Application/Applier/SetTextApplierSpec.php, src/Akeneo/Category/back/tests/Specification/Application/Applier/SetTextAreaApplierSpec.php, src/Akeneo/Category/back/tests/Specification/Domain/UserIntent/Factory/ValueUserIntentFactorySpec.php
=> GRF-276: Implement SetImage user intent

components/catalogs/back/src/Infrastructure/Persistence/SearchAttributesQuery.php, components/catalogs/back/src/Infrastructure/Symfony/Resources/translations/validators.en_US.yml, components/catalogs/back/src/Infrastructure/Validation/CatalogUpdatePayloadValidator.php, components/catalogs/back/src/Infrastructure/Validation/ProductSelection/AttributeCriterion/AttributeDateCriterion.php, components/catalogs/back/tests/Integration/Infrastructure/Persistence/SearchAttributesQueryTest.php, components/catalogs/back/tests/Integration/Infrastructure/Validation/CatalogUpdatePayloadTest.php, components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSelection/AttributeCriterion/AttributeDateCriterionTest.php, components/catalogs/front/src/components/ProductSelection/criteria/AttributeDateCriterion/AttributeDateCriterion.integration.tsx, components/catalogs/front/src/components/ProductSelection/criteria/AttributeDateCriterion/AttributeDateCriterion.tsx, components/catalogs/front/src/components/ProductSelection/criteria/AttributeDateCriterion/AttributeDateOperatorInput.tsx, components/catalogs/front/src/components/ProductSelection/criteria/AttributeDateCriterion/AttributeDateValueMultiInput.tsx, components/catalogs/front/src/components/ProductSelection/criteria/AttributeDateCriterion/AttributeDateValueSingleInput.tsx, components/catalogs/front/src/components/ProductSelection/criteria/AttributeDateCriterion/DateInput.tsx, components/catalogs/front/src/components/ProductSelection/criteria/AttributeDateCriterion/factory.ts, components/catalogs/front/src/components/ProductSelection/criteria/AttributeDateCriterion/factory.unit.ts, components/catalogs/front/src/components/ProductSelection/criteria/AttributeDateCriterion/index.ts, components/catalogs/front/src/components/ProductSelection/criteria/AttributeDateCriterion/types.d.ts, components/catalogs/front/src/components/ProductSelection/hooks/useFindAttributeCriterionByType.ts, components/catalogs/front/src/components/ProductSelection/hooks/useFindAttributeCriterionByType.unit.ts
https://user-images.githubusercontent.com/1421130/188907723-ab8042d5-0e7d-41da-a004-80f6e7047773.mp4
=> CXP-1251: AttributeDateCriterion

.circleci/jobs/features/catalogs/test_back_catalogs_ce.yml, .circleci/jobs/features/catalogs/test_back_catalogs_ee.yml, .circleci/jobs/features/connectivity.yml, components/catalogs/Makefile, components/catalogs/back/tests/Integration/Infrastructure/Controller/Internal/GetFamiliesActionTest.php, components/catalogs/back/tests/Integration/Infrastructure/Validation/CatalogUpdatePayloadTest.php, components/catalogs/back/tests/Integration/IntegrationTestCase.php, config/services/behat/services.yml, config/services/test/test_services.yml, docker-compose.yml, src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/Command/GenerateAsymmetricKeysHandlerIntegration.php, src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/Persistence/GetAsymmetricKeysQueryIntegration.php, src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/Persistence/SaveAsymmetricKeysQueryIntegration.php, tests/back/Integration/IntegrationTestsBundle/Helper/ExperimentalTransactionHelper.php, tests/back/Integration/IntegrationTestsBundle/Loader/FixturesLoader.php, tests/back/Integration/TestCase.php
**CI Catalogs before:**
**CI Catalogs after:**
**Akeneo laptop + Catalogs before:**
**Akeneo laptop + Catalogs after:**
**Akeneo laptop + Connectivity before:**
**Akeneo laptop + Connectivity after:**
=> OCT-63: Accelerate integration tests with transactions⚡

src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Controller/Internal/GetAppActivateUrlAction.php, src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Controller/Public/AuthorizeAction.php, src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Apps/controllers.yml, src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Apps/Controller/Internal/GetAppActivateUrlActionSpec.php, src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Apps/Controller/Public/AuthorizeActionSpec.php
https://user-images.githubusercontent.com/4290650/188183690-3997b21e-500b-4700-87b4-3c649b7002c1.mp4
=> OCT-101: Trigger the connect app wizard externally

components/catalogs/back/.php_cd.php, components/catalogs/back/src/Application/Persistence/GetCurrenciesQueryInterface.php, components/catalogs/back/src/Application/Persistence/IsCurrencyActivatedQueryInterface.php, components/catalogs/back/src/Infrastructure/Controller/Internal/GetCurrenciesAction.php, components/catalogs/back/src/Infrastructure/Persistence/GetCurrenciesQuery.php, components/catalogs/back/src/Infrastructure/Persistence/IsCurrencyActivatedQuery.php, components/catalogs/back/src/Infrastructure/Symfony/Resources/config/routing/internal.yml, components/catalogs/back/src/Infrastructure/Symfony/Resources/config/services.yml, components/catalogs/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml, components/catalogs/back/src/Infrastructure/Symfony/Resources/translations/validators.en_US.yml, components/catalogs/back/src/Infrastructure/Validation/CatalogUpdatePayloadValidator.php, components/catalogs/back/src/Infrastructure/Validation/ProductValueFilters/FilterContainsActivatedCurrency.php, components/catalogs/back/src/Infrastructure/Validation/ProductValueFilters/FilterContainsActivatedCurrencyValidator.php, components/catalogs/back/tests/Integration/Infrastructure/Controller/Internal/GetCurrenciesActionTest.php, components/catalogs/back/tests/Integration/Infrastructure/Persistence/GetCurrenciesQueryTest.php, components/catalogs/back/tests/Integration/Infrastructure/Persistence/IsCurrencyActivatedQueryTest.php, components/catalogs/back/tests/Integration/Infrastructure/Validation/CatalogUpdatePayloadTest.php, components/catalogs/front/src/components/CatalogEdit/reducers/CatalogFormReducer.unit.ts, components/catalogs/front/src/components/CatalogEdit/utils/mapProductValueFiltersErrors.ts, components/catalogs/front/src/components/ProductValueFilters/ProductValueFilters.tsx, components/catalogs/front/src/components/ProductValueFilters/components/FilterCurrencies.integration.tsx, components/catalogs/front/src/components/ProductValueFilters/components/FilterCurrencies.tsx, components/catalogs/front/src/components/ProductValueFilters/hooks/useCurrencies.ts, components/catalogs/front/src/components/ProductValueFilters/hooks/useCurrencies.unit.ts, components/catalogs/front/src/components/ProductValueFilters/models/ProductValueFiltersValues.d.ts
=> CXP-1256: Be abe to filter product value by currencies

components/catalogs/front/src/hooks/useChannelsByCodes.ts, components/catalogs/front/src/hooks/useChannelsByCodes.unit.ts
https://user-images.githubusercontent.com/93598018/189611000-87e214a4-2ddf-4105-b28c-544247ad4ba5.mp4
=> CXP-1254: format removed channel in the filter

src/Akeneo/Platform/Job/back/Application/SearchJobExecution/SearchJobExecutionQuery.php, src/Akeneo/Platform/Job/back/Infrastructure/Controller/GetJobExecutionAction.php, src/Akeneo/Platform/Job/back/Infrastructure/Query/SearchJobExecution.php, src/Akeneo/Platform/Job/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml, src/Akeneo/Platform/Job/back/tests/Integration/Infrastructure/Query/SearchJobExecutionTest.php, src/Akeneo/Platform/Job/front/process-tracker/src/feature/components/JobExecutionList/AutomationFilter.test.tsx, src/Akeneo/Platform/Job/front/process-tracker/src/feature/components/JobExecutionList/AutomationFilter.tsx, src/Akeneo/Platform/Job/front/process-tracker/src/feature/components/JobExecutionList/JobExecutionSearchBar.tsx, src/Akeneo/Platform/Job/front/process-tracker/src/feature/components/JobExecutionList/index.ts, src/Akeneo/Platform/Job/front/process-tracker/src/feature/hooks/useJobExecutionTable.ts, src/Akeneo/Platform/Job/front/process-tracker/src/feature/models/JobExecutionFilter.ts, src/Akeneo/Platform/Job/front/process-tracker/src/feature/models/JobExecutionTable.ts, src/Akeneo/Platform/Job/front/process-tracker/src/feature/pages/JobExecutionList.test.tsx, src/Akeneo/Platform/Job/front/process-tracker/src/feature/pages/JobExecutionList.tsx, src/Akeneo/Platform/Job/front/process-tracker/src/feature/pages/JobInstanceDetail.tsx
add filter for automated job in process tracker
=> RAB-1035: Add a filter on process tracker

components/catalogs/back/.php_cd.php, components/catalogs/back/src/Application/Handler/GetProductUuidsHandler.php, components/catalogs/back/src/Application/Persistence/GetProductUuidsQueryInterface.php, components/catalogs/back/src/Infrastructure/Controller/Public/GetProductIdentifiersAction.php, components/catalogs/back/src/Infrastructure/Controller/Public/GetProductUuidsAction.php, components/catalogs/back/src/Infrastructure/Persistence/GetProductUuidsQuery.php, components/catalogs/back/src/Infrastructure/Symfony/Resources/config/routing/public.yml, components/catalogs/back/src/ServiceAPI/Query/GetProductUuidsQuery.php, components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/GetProductIdentifiersActionTest.php, components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/GetProductUuidsActionTest.php, components/catalogs/back/tests/Integration/Infrastructure/Persistence/GetProductUuidsQueryTest.php, components/catalogs/back/tests/Integration/ServiceAPI/Query/GetProductUuidsQueryValidationTest.php
=> CXP-1186: catalogs/{id}/product-uuids

components/catalogs/back/src/Application/Handler/GetProductsHandler.php, components/catalogs/back/src/Application/Persistence/GetProductsQueryInterface.php, components/catalogs/back/src/Infrastructure/Controller/Public/GetProductsAction.php, components/catalogs/back/src/Infrastructure/Persistence/GetProductsQuery.php, components/catalogs/back/src/Infrastructure/Symfony/Resources/config/routing/public.yml, components/catalogs/back/src/ServiceAPI/Query/GetProductsQuery.php, components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/GetProductIdentifiersActionTest.php, components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/GetProductsActionTest.php, components/catalogs/back/tests/Integration/Infrastructure/Persistence/GetProductsQueryTest.php
=> CXP-1270: GET /catalogs/{id}/products

CHANGELOG.md, src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductModel/CountVariantProducts.php
=> PIM-10624: Fix very slow query when counting variants for mass delete

components/catalogs/back/.php_cs.php, components/catalogs/back/tests/Integration/Infrastructure/Controller/Internal/GetChannelActionTest.php, components/catalogs/back/tests/Integration/Infrastructure/Controller/Internal/GetChannelsActionTest.php, components/catalogs/front/src/components/ProductSelection/criteria/AttributeDateCriterion/AttributeDateCriterion.integration.tsx
=> OCT-124: updates phpcs rules

src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/UpdateProductByUuidController.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/controllers.yml, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml, src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Product/SqlFindProduct.php, src/Akeneo/Pim/Enrichment/Component/Product/Query/FindProduct.php
Introduce a query to retrieve a product with its uuid, see https://github.com/akeneo/pim-enterprise-dev/pull/14856
=> CPM-637: Handle drafts in PATCH endpoint

src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/UserManagement/DeleteRunningUser.php, src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/services.yml, src/Akeneo/Tool/Bundle/BatchBundle/Remover/JobInstanceRemover.php, src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/removers.yml, src/Akeneo/Tool/Bundle/BatchBundle/spec/Remover/JobInstanceRemoverSpec.php, tests/back/Platform/Specification/Bundle/ImportExportBundle/Infrastructure/UserManagement/DeleteRunningUserSpec.php
In this PR I added the deletion of a running user when a scheduled job is deleted
=> RAB-997: Remove running user on delete scheduled job

src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/ProductController.php, src/Akeneo/Pim/Enrichment/Product/back/Test/Acceptance/Context/ProductContext.php, src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/PQB/GetProductUuidsHandlerIntegration.php, src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductAssociationsIntegration.php, src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductIntegration.php, src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductVariantIntegration.php, src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductWithPermissionIntegration.php, src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertQuantifiedAssociationsIntegration.php, src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/API/CommandMessageBusSpec.php, src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Application/UpsertProductHandlerSpec.php, src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Infrastructure/Validation/AttributeGroupShouldBeEditableValidatorSpec.php, src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Infrastructure/Validation/CategoriesShouldBeViewableValidatorSpec.php, src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/Infrastructure/Validation/LocaleShouldBeEditableByUserValidatorSpec.php
Remove use of deprecated createFromCollection
=> CPM-720 : Remove use of deprecated createFromCollection

CHANGELOG.md, upgrades/schema/Version_7_0_20220912132436_update_namespace_in_resource_name_for_category_history.php, upgrades/test_schema/Version_7_0_20220912132436_update_namespace_in_resource_name_for_category_history_Integration.php
SQL Query of the migration was tested on a cloned instance of an impacted client and took 4.80s 
=> PIM-10566: migration script for updating resource_name with correct namespace of categories

src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/JobParameters/ConstraintCollectionProvider/ProductMassEdit.php, src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/JobParameters/ConstraintCollectionProvider/SimpleMassEdit.php, src/Akeneo/Tool/Component/Connector/Job/JobParameters/ConstraintCollectionProvider/SimpleCsvExport.php, src/Akeneo/Tool/Component/Connector/Job/JobParameters/ConstraintCollectionProvider/SimpleCsvImport.php, src/Akeneo/Tool/Component/Connector/Job/JobParameters/ConstraintCollectionProvider/SimpleXlsxExport.php, src/Akeneo/Tool/Component/Connector/Job/JobParameters/ConstraintCollectionProvider/SimpleXlsxImport.php, src/Akeneo/Tool/Component/Connector/Job/JobParameters/ConstraintCollectionProvider/SimpleYamlExport.php, src/Akeneo/Tool/Component/Connector/Job/JobParameters/ConstraintCollectionProvider/SimpleYamlImport.php, src/Akeneo/Tool/Component/Connector/spec/Job/JobParameters/ConstraintCollectionProvider/SimpleCsvExportSpec.php, src/Akeneo/Tool/Component/Connector/spec/Job/JobParameters/ConstraintCollectionProvider/SimpleCsvImportSpec.php, src/Akeneo/Tool/Component/Connector/spec/Job/JobParameters/ConstraintCollectionProvider/SimpleXlsxExportSpec.php, src/Akeneo/Tool/Component/Connector/spec/Job/JobParameters/ConstraintCollectionProvider/SimpleXlsxImportSpec.php, src/Akeneo/Tool/Component/Connector/spec/Job/JobParameters/ConstraintCollectionProvider/SimpleYamlExportSpec.php, src/Akeneo/Tool/Component/Connector/spec/Job/JobParameters/ConstraintCollectionProvider/SimpleYamlImportSpec.php
Following this [PR](https://github.com/akeneo/pim-community-dev/pull/17858), the migration has not updated some jobs (seems to be only related to quick export, maybe it is not due to the db migration) instance correctly, this quickfix allow jobs working with the old conf.
This PR will be reverted when the issue will be found and fixed.
=> Quickfix job validation following flaky migration

tests/back/Platform/Acceptance/NotificationBundle/FakeService/FakeNotifier.php, tests/back/Platform/Acceptance/NotificationBundle/Resources/config/services.yml
=> RAB-943: Handle invalid job notifications before a job is launched

src/Akeneo/Pim/Enrichment/Component/Product/Connector/Writer/Database/MassEdit/ProductAndProductModelWriter.php, src/Akeneo/Pim/Enrichment/Component/Product/Connector/Writer/Database/ProductModelDescendantsWriter.php, src/Akeneo/Pim/Enrichment/Component/Product/Connector/Writer/Database/ProductWriter.php, src/Akeneo/Pim/Structure/Component/Writer/Database/AttributeGroupWriter.php, src/Akeneo/Tool/Bundle/ConnectorBundle/Resources/translations/messages.en_US.yml, src/Akeneo/Tool/Component/Connector/Writer/Database/JobInstanceWriter.php, src/Akeneo/Tool/Component/Connector/Writer/Database/Writer.php, src/Akeneo/Tool/Component/Connector/spec/Writer/Database/JobInstanceWriterSpec.php, src/Akeneo/Tool/Component/Connector/spec/Writer/Database/WriterSpec.php, src/Akeneo/UserManagement/Component/Connector/Writer/Database/RoleWithPermissionsWriter.php, tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Writer/Database/MassEdit/ProductAndProductModelWriterSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Writer/Database/ProductModelDescendantsWriterSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Writer/Database/ProductWriterSpec.php, tests/back/Pim/Structure/Specification/Component/Writer/Database/AttributeGroupWriterSpec.php, tests/back/UserManagement/Specification/Component/Connector/Writer/Database/RoleWithPermissionsWriterSpec.php, tests/legacy/features/pim/enrichment/product/import/import_products_with_media.feature, tests/legacy/features/pim/enrichment/product/mass-edit/edit-common-attribute/edit_common_attributes_product_model.feature, tests/legacy/features/pim/enrichment/product/mass-edit/mass_add_to_existing_product_model.feature, tests/legacy/features/pim/enrichment/product/mass-edit/mass_edit_products_and_product_models.feature, tests/legacy/features/pim/structure/attribute/import/import_attributes.feature, tests/legacy/features/pim/structure/family/family-variant/import/xlsx/update_family_variant.feature, tests/legacy/features/pim/structure/product-group/import_groups.feature, tests/legacy/features/pim/structure/product-group/import_groups_xlsx.feature
=> RAB-720: Replace "processed" by "updated" in PT for some jobs

src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Field/IdentifierFilter.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/query_builders.yml, src/Akeneo/Pim/Enrichment/Component/Product/Connector/ReadModel/ConnectorProduct.php, src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/ListProductsQueryHandler.php, tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/AbstractProductTestCase.php, tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/SuccessListProductEndToEnd.php, tests/back/Pim/Enrichment/Integration/PQB/AbstractProductQueryBuilderTestCase.php, tests/back/Pim/Enrichment/Integration/PQB/Filter/Field/IdentifierFilterIntegration.php, tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Filter/Field/IdentifierFilterSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Connector/UseCase/ListProductsQueryHandlerSpec.php
=> CPM-632: Implement empty/not empty filter on attribute and use it on product list REST API

components/catalogs/back/tests/Acceptance/ApiContext.php, components/catalogs/back/tests/Acceptance/AuthenticationContext.php, components/catalogs/features/api.feature
=> OCT-125: Add acceptance test for /products, /product-identifiers and /product-uuids catalog endpoints

src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/JobParameters/ConstraintCollectionProvider/ProductMassEdit.php, src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/JobParameters/ConstraintCollectionProvider/SimpleMassEdit.php, src/Akeneo/Tool/Component/Connector/Job/JobParameters/ConstraintCollectionProvider/SimpleCsvExport.php, src/Akeneo/Tool/Component/Connector/Job/JobParameters/ConstraintCollectionProvider/SimpleCsvImport.php, src/Akeneo/Tool/Component/Connector/Job/JobParameters/ConstraintCollectionProvider/SimpleXlsxExport.php, src/Akeneo/Tool/Component/Connector/Job/JobParameters/ConstraintCollectionProvider/SimpleXlsxImport.php, src/Akeneo/Tool/Component/Connector/Job/JobParameters/ConstraintCollectionProvider/SimpleYamlExport.php, src/Akeneo/Tool/Component/Connector/Job/JobParameters/ConstraintCollectionProvider/SimpleYamlImport.php, src/Akeneo/Tool/Component/Connector/spec/Job/JobParameters/ConstraintCollectionProvider/SimpleCsvExportSpec.php, src/Akeneo/Tool/Component/Connector/spec/Job/JobParameters/ConstraintCollectionProvider/SimpleCsvImportSpec.php, src/Akeneo/Tool/Component/Connector/spec/Job/JobParameters/ConstraintCollectionProvider/SimpleXlsxExportSpec.php, src/Akeneo/Tool/Component/Connector/spec/Job/JobParameters/ConstraintCollectionProvider/SimpleXlsxImportSpec.php, src/Akeneo/Tool/Component/Connector/spec/Job/JobParameters/ConstraintCollectionProvider/SimpleYamlExportSpec.php, src/Akeneo/Tool/Component/Connector/spec/Job/JobParameters/ConstraintCollectionProvider/SimpleYamlImportSpec.php, upgrades/schema/Version_7_0_20220914143410_update_job_instance_parameter_user_to_notify_for_quick_export.php, upgrades/test_schema/Version_7_0_20220914143410_update_job_instance_parameter_user_to_notify_for_quick_export_Integration.php
In this PR, I added a new migration to migrate quick_export which I've forgot in the first migration. I also reverted my morning quickfix.
=> RAB: migrate user_to_notify for quick_export jobs

src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/quantified-associations/components/QuantifiedAssociationRow.tsx, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/quantified-associations/components/QuantifiedAssociations.tsx
In this PR, i made the quantified association page compatible with the DSM.
Before:
After:
=> RAB-1031: Use DSM into quantified associations

.circleci/jobs/features/other.yml, composer.json, composer.lock
=> PIM-10635: update dompdf/dompdf package

CHANGELOG-6.0.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/FieldContainer.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/product/field/field-guidelines.html
Add line break support for attribute guidelines
=> CPM-721: Add line break support for attribute guidelines

components/catalogs/Makefile, components/catalogs/back/.php_cd.php, components/catalogs/back/src/Infrastructure/Exception/FilesystemException.php, components/catalogs/back/src/Infrastructure/Storage/CatalogsMappingStorage.php, components/catalogs/back/src/Infrastructure/Symfony/Resources/config/services.yml, components/catalogs/back/tests/Integration/Infrastructure/Storage/CatalogsMappingStorageTest.php, components/catalogs/back/tests/Integration/Infrastructure/Validation/CatalogUpdatePayloadTest.php, config/packages/behat/oneup_flysystem.yml, config/packages/dev/oneup_flysystem.yml, config/packages/oneup_flysystem.yml, config/packages/prod/oneup_flysystem.yml, config/packages/test/oneup_flysystem.yml, config/packages/test_fake/oneup_flysystem.yml, docker-compose.yml, tests/back/Integration/IntegrationTestsBundle/Loader/FixturesLoader.php
=> CXP-1283: New bucket for catalogs mapping

src/Akeneo/Platform/Bundle/ImportExportBundle/Command/PurgeJobExecutionCommand.php, src/Akeneo/Platform/Bundle/ImportExportBundle/DependencyInjection/PimImportExportExtension.php, src/Akeneo/Platform/Bundle/ImportExportBundle/Job/JobParameters/PurgeJobExecutions.php, src/Akeneo/Platform/Bundle/ImportExportBundle/Job/PurgeJobExecutions.php, src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/jobs.yml, src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/services.yml, src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev/jobs.yml, src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/minimal/jobs.yml, upgrades/schema/Version_7_0_20220919145300_add_scheduled_jobs.php, upgrades/test_schema/Version_7_0_20220919145300_add_scheduled_jobs_Integration.php
Refactoring of the command purging job executions to use a scheduled job
=> PH-268: Create `job_executions_purge` scheduled job

.circleci/workflows/editions/community.yml
This automatic pullup workflow is not really used
=> DPE: Remove auto pullup

components/identifier-generator/back/.php_cs.php, components/identifier-generator/back/src/Domain/Model/Condition/Conditions.php, components/identifier-generator/back/src/Domain/Model/Delimiter.php, components/identifier-generator/back/src/Domain/Model/IdentifierGenerator.php, components/identifier-generator/back/src/Domain/Model/IdentifierGeneratorCode.php, components/identifier-generator/back/src/Domain/Model/LabelCollection.php, components/identifier-generator/back/src/Domain/Model/Property/AutoNumber.php, components/identifier-generator/back/src/Domain/Model/Property/FreeText.php, components/identifier-generator/back/src/Domain/Model/Structure.php, components/identifier-generator/back/src/Domain/Model/Target.php, components/identifier-generator/back/tests/Specification/Domain/Model/Condition/ConditionsSpec.php, components/identifier-generator/back/tests/Specification/Domain/Model/DelimiterSpec.php, components/identifier-generator/back/tests/Specification/Domain/Model/IdentifierGeneratorCodeSpec.php, components/identifier-generator/back/tests/Specification/Domain/Model/IdentifierGeneratorSpec.php, components/identifier-generator/back/tests/Specification/Domain/Model/LabelCollectionSpec.php, components/identifier-generator/back/tests/Specification/Domain/Model/Property/AutoNumberSpec.php, components/identifier-generator/back/tests/Specification/Domain/Model/Property/FreeTextSpec.php, components/identifier-generator/back/tests/Specification/Domain/Model/StructureSpec.php, components/identifier-generator/back/tests/Specification/Domain/Model/TargetSpec.php, make-file/identifier-generator.mk, phpspec.yml.dist
=> CPM-727: Add domain validation for identifier generator

CHANGELOG.md, src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptionForm.tsx, src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/Edit.tsx, src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/contexts/AttributeOptionsContextProvider.tsx
=> PIM-10622: Fix save options labels when using the automatic correction in Firefox

components/catalogs/back/tests/Integration/Infrastructure/Controller/Internal/UpdateCatalogActionTest.php, components/catalogs/back/tests/Integration/Infrastructure/Job/DisableCatalogsOnAttributeOptionRemovalTaskletTest.php, components/catalogs/back/tests/Integration/Infrastructure/Persistence/DisableCatalogsQueryTest.php, components/catalogs/back/tests/Integration/IntegrationTestCase.php, tests/back/Integration/IntegrationTestsBundle/Helper/ExperimentalTransactionHelper.php
=> CXP-1299: fix experimental transaction in job test

.circleci/jobs/features/catalogs/test_back_catalogs_ce.yml, make-file/test.mk, upgrades/.php_cd.php
=> OCT-130: fix phpcd from OCT-128

components/identifier-generator/back/.php_cs.php, components/identifier-generator/back/src/Domain/Model/Condition/ConditionInterface.php, components/identifier-generator/back/src/Domain/Model/Condition/Conditions.php, components/identifier-generator/back/src/Domain/Model/Delimiter.php, components/identifier-generator/back/src/Domain/Model/IdentifierGenerator.php, components/identifier-generator/back/src/Domain/Model/IdentifierGeneratorCode.php, components/identifier-generator/back/src/Domain/Model/LabelCollection.php, components/identifier-generator/back/src/Domain/Model/Property/AutoNumber.php, components/identifier-generator/back/src/Domain/Model/Property/FreeText.php, components/identifier-generator/back/src/Domain/Model/Property/PropertyInterface.php, components/identifier-generator/back/src/Domain/Model/Structure.php, components/identifier-generator/back/src/Domain/Model/Target.php, components/identifier-generator/back/tests/Specification/Domain/Model/Condition/ConditionsSpec.php, components/identifier-generator/back/tests/Specification/Domain/Model/DelimiterSpec.php, components/identifier-generator/back/tests/Specification/Domain/Model/IdentifierGeneratorCodeSpec.php, components/identifier-generator/back/tests/Specification/Domain/Model/IdentifierGeneratorSpec.php, components/identifier-generator/back/tests/Specification/Domain/Model/LabelCollectionSpec.php, components/identifier-generator/back/tests/Specification/Domain/Model/Property/AutoNumberSpec.php, components/identifier-generator/back/tests/Specification/Domain/Model/Property/FreeTextSpec.php, components/identifier-generator/back/tests/Specification/Domain/Model/StructureSpec.php, components/identifier-generator/back/tests/Specification/Domain/Model/TargetSpec.php, make-file/identifier-generator.mk, phpspec.yml.dist
=> CPM-726: Create Domain Objects

components/catalogs/back/tests/Integration/IntegrationTestCase.php
=> OCT-121: catch cold boot of the kernel

components/catalogs/back/.php_cd.php, components/catalogs/back/src/Infrastructure/Persistence/Measurement/GetMeasurementsFamilyQuery.php, components/catalogs/back/src/Infrastructure/Symfony/Resources/config/services.yml, components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/GetCatalogProductValueFiltersQueryTest.php, components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/UpdateCatalogProductValueFiltersQueryTest.php, components/catalogs/back/tests/Integration/Infrastructure/Persistence/Channel/GetChannelsByCodeQueryTest.php, components/catalogs/back/tests/Integration/Infrastructure/Persistence/Currency/GetCurrenciesQueryTest.php, components/catalogs/back/tests/Integration/Infrastructure/Persistence/Currency/IsCurrencyActivatedQueryTest.php, components/catalogs/back/tests/Integration/Infrastructure/Persistence/Locale/GetLocalesByCodeQueryTest.php
=> OCT-115: Use Measurement ServiceAPI

src/Akeneo/Category/back/Application/Converter/Checker/AttributeApiRequirementChecker.php, src/Akeneo/Category/back/Application/Converter/Checker/ValueCollectionRequirementChecker.php, src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/validation/category_commands.yml, src/Akeneo/Category/back/tests/Specification/Application/Converter/Checker/AttributeApiRequirementCheckerSpec.php, src/Akeneo/Category/back/tests/Specification/Application/Converter/Checker/ValueCollectionRequirementCheckerSpec.php, src/Akeneo/Category/front/src/FakePIM.tsx, src/Akeneo/Category/front/src/feature/components/EditAttributesForm.tsx, src/Akeneo/Category/front/src/feature/components/attributes/buildImageFieldAttribute.tsx, src/Akeneo/Category/front/src/feature/components/file/preview/media-preview.tsx, src/Akeneo/Category/front/src/feature/helpers/categoryHelper.ts, src/Akeneo/Category/front/src/feature/hooks/useCategory.ts, src/Akeneo/Category/front/src/feature/hooks/useEditCategoryForm.test.ts, src/Akeneo/Category/front/src/feature/hooks/useEditCategoryForm.ts, src/Akeneo/Category/front/src/feature/hooks/useTemplate.ts, src/Akeneo/Category/front/src/feature/infrastructure/savers/saveEditCategoryForm.ts, src/Akeneo/Category/front/src/feature/models/Category.ts, src/Akeneo/Category/front/src/feature/pages/CategoryEditPage.tsx
=> GRF-342 category attributes handle issue in front related to the "unsaved changes" warning

components/catalogs/front/src/components/ProductSelection/components/CriterionFields.tsx, components/catalogs/front/src/components/ProductSelection/criteria/AttributeBooleanCriterion/AttributeBooleanCriterion.tsx, components/catalogs/front/src/components/ProductSelection/criteria/AttributeDateCriterion/AttributeDateCriterion.tsx, components/catalogs/front/src/components/ProductSelection/criteria/AttributeDateCriterion/AttributeDateValueMultiInput.tsx, components/catalogs/front/src/components/ProductSelection/criteria/AttributeIdentifierCriterion/AttributeIdentifierCriterion.tsx, components/catalogs/front/src/components/ProductSelection/criteria/AttributeMeasurementCriterion/AttributeMeasurementCriterion.tsx, components/catalogs/front/src/components/ProductSelection/criteria/AttributeMeasurementCriterion/AttributeMeasurementValueInput.tsx, components/catalogs/front/src/components/ProductSelection/criteria/AttributeMultiSelectCriterion/AttributeMultiSelectCriterion.tsx, components/catalogs/front/src/components/ProductSelection/criteria/AttributeNumberCriterion/AttributeNumberCriterion.tsx, components/catalogs/front/src/components/ProductSelection/criteria/AttributeSimpleSelectCriterion/AttributeSimpleSelectCriterion.tsx, components/catalogs/front/src/components/ProductSelection/criteria/AttributeTextCriterion/AttributeTextCriterion.tsx, components/catalogs/front/src/components/ProductSelection/criteria/AttributeTextareaCriterion/AttributeTextareaCriterion.tsx, components/catalogs/front/src/components/ProductSelection/criteria/CategoryCriterion/CategoryCriterion.tsx, components/catalogs/front/src/components/ProductSelection/criteria/CompletenessCriterion/CompletenessCriterion.tsx, components/catalogs/front/src/components/ProductSelection/criteria/FamilyCriterion/FamilyCriterion.tsx, components/catalogs/front/src/components/ProductSelection/criteria/StatusCriterion/StatusCriterion.tsx
=> OCT-118: the Product selection UI consistency pass

src/Akeneo/Tool/Bundle/BatchBundle/Notification/MailNotifier.php, src/Akeneo/Tool/Bundle/BatchBundle/Resources/views/Email/notification.html.twig, src/Akeneo/Tool/Bundle/BatchBundle/Resources/views/Email/notification.txt.twig, src/Akeneo/Tool/Bundle/BatchBundle/spec/Notification/MailNotifierSpec.php
This PR allow the user to know directly from email subject the status of the job execution
=> RAB-1068: Update legacy mail when job failed

CHANGELOG.md, src/Akeneo/Pim/Enrichment/.php_cd.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/steps.yml, src/Akeneo/Pim/Enrichment/Component/Product/Job/DeleteProductsAndProductModelsTasklet.php, tests/back/Pim/Enrichment/Specification/Component/Product/Job/DeleteProductsAndProductModelsTaskletSpec.php
Add an error in product and product model deletion when product model deletion is not granted
=> PIM-10576: Fix product model mass edit acl check

components/identifier-generator/back/tests/.php_cd.php, make-file/identifier-generator.mk, make-file/test.mk
Add phpCD for identifier generator components
=> CPM-729: Add phpCD for identifier generator components

src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/DependencyInjection/AkeneoConnectivityConnectionExtension.php, src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Webhook/jobs.yml, src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/EventsApiDebug/Command/PurgeEventsApiLogsCommand.php, src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/EventsApiDebug/Job/PurgeEventsApiLogs.php, src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev/jobs.yml, src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/minimal/jobs.yml, src/Akeneo/Tool/Component/Batch/Job/JobParameters/EmptyConstraintAndDefaultValuesProvider.php, src/Akeneo/Tool/Component/Batch/Job/JobParameters/EmptyDefaultValuesProvider.php, upgrades/schema/Version_7_0_20220926115200_add_scheduled_jobs.php, upgrades/test_schema/Version_7_0_20220926115200_add_scheduled_jobs_Integration.php
Add a scheduled job to purge API event logs.
Use the same services than the existing CRON command.
=> PH-277: Add a job to purge API events logs

components/identifier-generator/back/src/Application/CreateGeneratorCommand.php, components/identifier-generator/back/src/Application/CreateGeneratorHandler.php, components/identifier-generator/back/src/Domain/Model/IdentifierGenerator.php, components/identifier-generator/back/src/Domain/Repository/IdentifierGeneratorRepository.php, components/identifier-generator/back/src/Infrastructure/Repository/InMemoryIdentifierGeneratorRepository.php, components/identifier-generator/back/src/Infrastructure/Symfony/DependencyInjection/AkeneoIdentifierGeneratorExtension.php, components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/command_handlers.yml, components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/persistence.yml, components/identifier-generator/back/tests/.php_cd.php, components/identifier-generator/back/tests/.php_cs.php, components/identifier-generator/back/tests/Acceptance/Context/CreateIdentifierGeneratorContext.php, components/identifier-generator/back/tests/Acceptance/Resources/config/contexts.yml, components/identifier-generator/back/tests/Specification/Application/CreateGeneratorHandlerSpec.php, components/identifier-generator/back/tests/Specification/Domain/Model/IdentifierGeneratorSpec.php, components/identifier-generator/back/tests/Specification/Infrastructure/Repository/InMemoryIdentifierGeneratorRepositorySpec.php, components/identifier-generator/back/tests/behat.yml, components/identifier-generator/back/tests/features/createIdentifierGenerator.feature, composer.json, config/services/test_fake/services.yml, make-file/identifier-generator.mk, make-file/test.mk
Simple identifier generator creation use case. For now, the repository only has an in-memory implementation; no functional validation yet
=> CPM-728: Create IdentifierGenerator InMemory Repository

src/Akeneo/Platform/Bundle/ImportExportBundle/Domain/ResolveScheduledJobRunningUsername.php, src/Akeneo/Tool/Component/BatchQueue/Queue/PublishJobToQueue.php, src/Akeneo/Tool/Component/BatchQueue/Queue/PublishJobToQueueInterface.php
refactorisation of the publish job command
=> RAB-1073: refacto publish job command 

components/identifier-generator/back/src/Domain/Model/Condition/Conditions.php, components/identifier-generator/back/src/Domain/Model/Delimiter.php, components/identifier-generator/back/src/Domain/Model/IdentifierGeneratorCode.php, components/identifier-generator/back/src/Domain/Model/LabelCollection.php, components/identifier-generator/back/src/Domain/Model/Property/AutoNumber.php, components/identifier-generator/back/src/Domain/Model/Property/FreeText.php, components/identifier-generator/back/src/Domain/Model/Structure.php, components/identifier-generator/back/src/Domain/Model/Target.php
=> CPM-742: Add a short description for domain objects

CHANGELOG-5.0.md, src/Akeneo/Channel/Bundle/Resources/translations/jsmessages.pt_BR.yml, src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.pt_BR.yml, src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/messages.pt_BR.yml, src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/validators.pt_BR.yml, src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.pt_BR.yml, src/Akeneo/Platform/Bundle/AnalyticsBundle/Resources/translations/messages.pt_BR.yml, src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/translations/jsmessages.pt_BR.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.pt_BR.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/messages.pt_BR.yml, src/Akeneo/Tool/Bundle/BatchBundle/Launcher/JobLauncherInterface.php, src/Akeneo/Tool/Bundle/BatchBundle/Launcher/SimpleJobLauncher.php, src/Akeneo/Tool/Bundle/BatchBundle/Launcher/SynchronousJobLauncher.php, src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/services.yml, src/Akeneo/Tool/Bundle/BatchQueueBundle/Launcher/QueueJobLauncher.php, src/Akeneo/Tool/Bundle/ConnectorBundle/Launcher/AuthenticatedJobLauncher.php, src/Akeneo/Tool/Bundle/ConnectorBundle/Resources/translations/jsmessages.sv_SE.yml, src/Akeneo/UserManagement/Bundle/Resources/translations/jsmessages.pt_BR.yml
=> Pull up 5.0 to 6.0

.circleci/find_non_executed_phpspec.sh
=> Remove feature from non executed phpspecs script

components/catalogs/front/src/components/CatalogEdit/CatalogEdit.integration.tsx, components/catalogs/front/src/components/ProductValueFilters/components/FilterChannel.integration.tsx, components/catalogs/front/src/components/ProductValueFilters/components/FilterLocale.integration.tsx
Added missing mocks to integration tests that triggered console warning messages
=> OCT: Fixed console warning on front integration tests

src/Akeneo/Tool/Component/Api/Normalizer/Exception/ViolationNormalizer.php
=> [fix-datadog] Fix ViolationNormalizer ProductPrice

src/Akeneo/Pim/Enrichment/Bundle/Resources/config/normalizers.yml, src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/GroupNormalizer.php, tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/InternalApi/GroupNormalizerSpec.php
=> Perf groupnormalizer

CHANGELOG.md, src/Akeneo/Pim/Enrichment/Component/Product/Connector/Reader/Database/ProductReader.php
=> PIM-10658: Fix database product reader

composer.json, src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/Command/AggregateVolumesCommand.php, src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/DependencyInjection/PimCatalogVolumeMonitoringExtension.php, src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/Job/AggregateVolumeQueries.php, src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/Resources/config/jobs.yml, src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/Resources/config/services.yml, src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev/jobs.yml, src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/minimal/jobs.yml, src/Akeneo/Platform/Component/CatalogVolumeMonitoring/Volume/Service/VolumeAggregation.php, tests/back/Platform/Specification/Component/CatalogVolumeMonitoring/Volume/Service/VolumeAggregationSpec.php, upgrades/schema/Version_7_0_20221004093900_add_scheduled_jobs.php, upgrades/test_schema/Version_7_0_20221004093900_add_scheduled_jobs_Integration.php
Add a job to aggregate the result of all the volume queries that should not be executed live
=> PH-272: Add a job to aggregate volume queries

composer.lock, src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/AttributeOption/SetAttributeOptionSortOrderSubscriber.php, src/Akeneo/Tool/Bundle/MessengerBundle/Command/PurgeMessengerCommand.php
Remove a deprecated exception.
And update Composer dependencies by the way.
=> PH-276: Update Composer dependencies

components/catalogs/back/src/Application/Persistence/Catalog/GetCatalogProductValueFiltersQueryInterface.php, components/catalogs/back/src/Application/Persistence/Catalog/UpdateCatalogProductValueFiltersQueryInterface.php, components/catalogs/back/src/Domain/Catalog.php, components/catalogs/back/src/Domain/Catalog/Catalog.php, components/catalogs/back/src/Domain/Catalog/GetCatalogQueryInterface.php, components/catalogs/back/src/Infrastructure/Persistence/Catalog/GetCatalogProductValueFiltersQuery.php, components/catalogs/back/src/Infrastructure/Persistence/Catalog/GetCatalogQuery.php, components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/GetCatalogQueryTest.php
Added Catalog aggregate for internal uses with its own query that hydrates it
=> CXP-1307: Catalog aggregate

components/identifier-generator/back/src/Infrastructure/Controller/GetIdentifierAttributesController.php, components/identifier-generator/back/src/Infrastructure/Symfony/DependencyInjection/AkeneoIdentifierGeneratorExtension.php, components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/controllers.yml, components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/routing.yml, components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml, components/identifier-generator/back/tests/.php_cd.php, components/identifier-generator/back/tests/EndToEnd/ControllerEndToEndTestCase.php, components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/GetIdentifierAttributesControllerEndToEnd.php, composer.json, make-file/identifier-generator.mk, make-file/test.mk, phpunit.xml.dist
Add GetIdentifierAttributes controller and route
=> CPM-732: Add GetIdentifierAttributes controller and route

src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/acl.yml, src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/acl_groups.yml, src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/messages.en_US.yml, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/acl.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/acl_groups.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/messages.en_US.yml
Migrate category permission to Category bounded context. See dedicated [US](https://akeneo.atlassian.net/jira/software/projects/GRF/boards/301?selectedIssue=GRF-92) and [Subtask](https://akeneo.atlassian.net/jira/software/projects/GRF/boards/301?selectedIssue=GRF-496).
=> GRF-496 : Migrate ACL category configuration

components/catalogs/back/src/Application/Exception/CatalogNotFoundException.php, components/catalogs/back/src/Application/Persistence/Catalog/GetCatalogQueryInterface.php, components/catalogs/back/src/Domain/Catalog.php, components/catalogs/back/src/Infrastructure/Controller/Internal/GetCatalogAction.php, components/catalogs/back/src/Infrastructure/Persistence/Catalog/GetCatalogQuery.php, components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/GetCatalogQueryTest.php
=> CXP-1317: Update Internal/GetCatalogAction

components/catalogs/back/src/Application/Persistence/Catalog/Product/IsProductBelongingToCatalogQueryInterface.php, components/catalogs/back/src/Infrastructure/Persistence/Catalog/Product/IsProductBelongingToCatalogQuery.php, components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/Product/IsProductBelongingToCatalogQueryTest.php
=> CXP-1318: IsProductBelongToCatalogQuery

src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/acl.yml, src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/messages.en_US.yml
* Without feature flag :
* With feature flag :
=> GRF-497 : Add manage category template permission

components/catalogs/back/src/Infrastructure/Persistence/Catalog/Product/IsProductBelongingToCatalogQuery.php, components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/Product/IsProductBelongingToCatalogQueryTest.php
=> CXP-1318: Fix integration test

components/catalogs/back/src/Infrastructure/Controller/Public/GetProductIdentifiersAction.php, components/catalogs/back/src/Infrastructure/Controller/Public/GetProductUuidsAction.php, components/catalogs/back/src/Infrastructure/Controller/Public/GetProductsAction.php, components/catalogs/back/src/Infrastructure/Security/DenyAccessUnlessGrantedTrait.php
Updated DenyAccessUnlessGrantedTrait to use domain Catalog object
=> CXP-1324: Updated DenyAccessUnlessGrantedTrait

src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/acl.yml, src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/messages.en_US.yml
Without feature flag :
With feature flag :
=> GRF-500 : Add new category order trees permission

components/catalogs/back/.php_cd.php, components/catalogs/back/src/Infrastructure/Persistence/User/GetUserIdFromUsernameQuery.php
=> CXP-1327: Fix GetUserIdByUsernameQuery

components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml, components/identifier-generator/front/jest.unit.js, components/identifier-generator/front/package.json, components/identifier-generator/front/src/feature/IdentifierGeneratorApp.tsx, components/identifier-generator/front/src/feature/__tests__/IdentifierGeneratorApp.test.tsx, components/identifier-generator/front/src/feature/components/IdentifierAttributeSelector.tsx, components/identifier-generator/front/src/feature/components/__tests__/IdentifierAttributeSelector.test.tsx, components/identifier-generator/front/src/feature/components/index.ts, components/identifier-generator/front/src/feature/hooks/__tests__/useIdentifierAttributes.test.tsx, components/identifier-generator/front/src/feature/hooks/useIdentifierAttributes.ts, components/identifier-generator/front/src/feature/models/flatten-attribute.d.ts, components/identifier-generator/front/src/feature/tests/hooks/config/createWrapper.tsx, components/identifier-generator/front/src/feature/tests/test-utils.tsx, components/identifier-generator/front/src/index.tsx
Add IdentifierAttributeSelector component and call to backend
=> CPM-732: Add IdentifierAttributeSelector

components/catalogs/back/.php_cd.php, components/catalogs/back/src/Application/Handler/GetProductsHandler.php, components/catalogs/back/src/Application/Persistence/Catalog/Product/GetProductsQueryInterface.php, components/catalogs/back/src/Infrastructure/Controller/Public/GetProductIdentifiersAction.php, components/catalogs/back/src/Infrastructure/Controller/Public/GetProductUuidsAction.php, components/catalogs/back/src/Infrastructure/Controller/Public/GetProductsAction.php, components/catalogs/back/src/Infrastructure/Persistence/Catalog/Product/GetProductsQuery.php, components/catalogs/back/src/Infrastructure/Security/DenyAccessUnlessGrantedTrait.php, components/catalogs/back/src/ServiceAPI/Exception/CatalogNotFoundException.php, components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/GetProductsActionTest.php, components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/Product/GetProductsQueryTest.php
=> CXP-1321: Use Catalog Agg in GetProductsQuery

components/catalogs/back/src/Application/Handler/GetProductUuidsHandler.php, components/catalogs/back/src/Application/Handler/GetProductsHandler.php, components/catalogs/back/src/Application/Persistence/Catalog/Product/GetProductUuidsQueryInterface.php, components/catalogs/back/src/Infrastructure/Persistence/Catalog/Product/GetProductUuidsQuery.php, components/catalogs/back/src/Infrastructure/Persistence/Catalog/Product/GetProductsQuery.php, components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/Product/GetProductUuidsQueryTest.php
=> CXP-1322: Use Catalog Agg in GetProductUuidsQuery

CHANGELOG.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/product/edit/content/structure/attributes-selector.js
update attribute if needed when selecting attribute in import
=> PIM-10669: The next 20 attributes are not displayed if you do not scroll the list

src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Infrastructure/Persistence/Query/ProductEvaluation/GetProductIdsImpactedByAttributeGroupActivationQueryIntegration.php, src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Infrastructure/Persistence/Query/ProductEvaluation/GetProductModelIdsImpactedByAttributeGroupActivationQueryIntegration.php, src/Akeneo/Pim/Structure/Bundle/Resources/config/validation/attribute.yml, tests/back/Pim/Structure/Integration/Attribute/Validation/GlobalConstraintsIntegration.php
Forbid creation or update of an attribute called "uuid"
- add "uuid" to reserved code list
=> CPM-761 : Forbid creation or update of an attribute called "uuid"

CHANGELOG-5.0.md, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/documentation.yml, src/Akeneo/Pim/Enrichment/Component/Error/DocumentationBuilder/InvalidAssociationProductIdentifier.php, src/Akeneo/Pim/Enrichment/Component/Product/Exception/InvalidAssociationProductIdentifierException.php, src/Akeneo/Pim/Enrichment/Component/Product/Updater/Setter/AssociationFieldSetter.php, tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/CreateProductModelEndToEnd.php, tests/back/Pim/Enrichment/Specification/Component/Error/DocumentationBuilder/InvalidAssociationProductIdentifierSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Exception/InvalidAssociationProductIdentifierExceptionSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Updater/Setter/AssociationFieldSetterSpec.php, tests/legacy/features/pim/enrichment/product/import/import_products_with_associations.feature, tests/legacy/features/pim/enrichment/product/import/xlsx/import_products_with_associations.feature
Pull up for [PIM-10651](https://github.com/akeneo/pim-community-dev/pull/18091)
=> PIM-10680: pull up 5.0->6.0

tests/back/Pim/Enrichment/Integration/PQB/Filter/Field/Product/UuidFilterIntegration.php
=> PIM-10678: fix not working test

CHANGELOG-6.0.md, src/Akeneo/Pim/Enrichment/Component/Product/Completeness/MaskItemGenerator/PriceCollectionMaskItemGenerator.php, tests/back/Pim/Enrichment/Specification/Component/Product/Completeness/MaskItemGenerator/PriceCollectionMaskItemGeneratorSpec.php
=> PIM-10670: Fix memory leak on creating combinations for currencies

src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Versioning/EntityWithQuantifiedAssociations/QuantifiedAssociationsNormalizer.php, tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/Versioning/EntityWithQuantifiedAssociations/QuantifiedAssociationsNormalizerSpec.php
fix versioning when using external API with UUID, 
https://github.com/akeneo/pim-community-dev/pull/18058 will avoid unnecessary versioning identifier/uuid
=> CPM-755: [New API endpoints] Product versioning

components/identifier-generator/back/src/Application/Exception/ViolationsException.php, components/identifier-generator/back/src/Application/Validation/Error.php, components/identifier-generator/back/src/Application/Validation/ErrorList.php, components/identifier-generator/back/src/Infrastructure/Validation/CreateGeneratorCommandValidator.php, components/identifier-generator/back/tests/Acceptance/Context/CreateIdentifierGeneratorContext.php, components/identifier-generator/back/tests/Specification/Domain/Model/IdentifierGeneratorSpec.php
~~Fix coupling in Application namespace :~~
~~- remove coupling with Symfony in Application~~
~~- use interface for command validation~~
~~- move ValidationException in Application~~
~~- create our own Error and ErrorList to replace ConstraintViolation from Symfony~~
- Update with Pierre's comments
[https://github.com/akeneo/pim-community-dev/pull/18119](
https://github.com/akeneo/pim-community-dev/pull/18119)
=> CPM-756 (bis) : update after review

components/identifier-generator/back/src/Application/Create/CreateGeneratorCommand.php, components/identifier-generator/back/src/Application/Validation/Error.php, components/identifier-generator/back/src/Application/Validation/ErrorList.php, components/identifier-generator/back/src/Domain/Model/Condition/ConditionInterface.php, components/identifier-generator/back/src/Domain/Model/Condition/Conditions.php, components/identifier-generator/back/src/Domain/Model/Delimiter.php, components/identifier-generator/back/src/Domain/Model/Property/AutoNumber.php, components/identifier-generator/back/src/Domain/Model/Property/FreeText.php, components/identifier-generator/back/src/Domain/Model/Property/PropertyInterface.php, components/identifier-generator/back/src/Domain/Model/Structure.php, components/identifier-generator/back/src/Domain/Repository/IdentifierGeneratorRepository.php, components/identifier-generator/back/src/Infrastructure/Repository/SqlIdentifierGeneratorRepository.php, components/identifier-generator/back/src/Infrastructure/Validation/CreateGeneratorCommandValidator.php, components/identifier-generator/back/src/Infrastructure/Validation/IdentifierGeneratorCreationLimit.php, components/identifier-generator/back/src/Infrastructure/Validation/IdentifierGeneratorCreationLimitValidator.php, components/identifier-generator/back/src/Infrastructure/Validation/TargetAttributeShouldBeAnIdentifierValidator.php, components/identifier-generator/back/src/Infrastructure/Validation/TargetAttributeShouldExistValidator.php, components/identifier-generator/back/tests/.php_cs.php, components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/GetIdentifierAttributesControllerEndToEnd.php, components/identifier-generator/back/tests/Specification/Infrastructure/Validation/IdentifierGeneratorCreationLimitValidatorSpec.php, components/identifier-generator/back/tests/Specification/Infrastructure/Validation/TargetAttributeShouldExistValidatorSpec.php, components/identifier-generator/back/tests/phpstan.neon, make-file/identifier-generator.mk
- Add PHPStan
- Add rule for strict type declaration in PHP-CS-Fixer
- Update make file recipes
=> CPM-746 : Add PHPStan

src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/SequentialEditController.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/cursors.yml, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/query_builders.yml, src/Akeneo/Tool/Bundle/ElasticsearchBundle/Resources/config/cursors.yml
=> CPM-632: Use Enrichment cursors

components/catalogs/back/src/Application/Handler/CreateCatalogHandler.php, components/catalogs/back/src/Application/Handler/DeleteProductMappingSchemaHandler.php, components/catalogs/back/src/Application/Handler/GetProductMappingSchemaHandler.php, components/catalogs/back/src/Domain/Catalog.php, components/catalogs/back/src/Infrastructure/Controller/Internal/UpdateCatalogAction.php, components/catalogs/back/src/Infrastructure/Controller/Public/DeleteProductMappingSchemaAction.php, components/catalogs/back/src/Infrastructure/Persistence/Catalog/GetCatalogQuery.php, components/catalogs/back/src/Infrastructure/Persistence/Catalog/UpsertCatalogQuery.php, components/catalogs/back/src/Infrastructure/Symfony/Resources/config/routing/public.yml, components/catalogs/back/src/ServiceAPI/Command/DeleteProductMappingSchemaCommand.php, components/catalogs/back/src/ServiceAPI/Exception/ProductSchemaMappingNotFoundException.php, components/catalogs/back/tests/Acceptance/ApiContext.php, components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/DeleteProductMappingSchemaActionTest.php, components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/GetCatalogQueryTest.php, components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/IsCatalogsNumberLimitReachedQueryTest.php, components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/UpsertCatalogQueryTest.php, components/catalogs/back/tests/Integration/IntegrationTestCase.php, components/catalogs/back/tests/Unit/Application/Handler/CreateCatalogHandlerTest.php, components/catalogs/features/api.feature
=> CXP-1286: Endpoint DELETE product mapping schema

tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/PartialUpdateListProductWithUuidEndToEnd.php
=> CPM-736 : Patch multiple : UUID is mandatory

src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/Resources/config/jobs.yml
We injected the wrong service in the step
=> PH-428: Fix pim_volume_monitoring.step.aggregate_volume_queries definition

src/Akeneo/Tool/Bundle/BatchQueueBundle/Command/JobExecutionWatchdogCommand.php, src/Akeneo/Tool/Bundle/BatchQueueBundle/Manager/JobExecutionManager.php, src/Akeneo/Tool/Bundle/BatchQueueBundle/Resources/config/services.yml
We create a lock for unique jobs in https://github.com/akeneo/pim-community-dev/blob/master/src/Akeneo/Tool/Component/Connector/Step/CheckJobUniqueStep.php and we must release it in the watchdog wrapper.
=> PH-419: Release job lock in watchdog

src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/less/data-quality-insights-attributes.less, src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/Dashboard/CategoryModal/CategoryModal.tsx, src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/MessageBox.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/mass-edit/form.html, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/product/create-helper.html
=> CPM-773: Update MessageBox BEM to DSM style

src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/ProductController.php
=> Cpm 776: Fix converting variant product into simple

src/Akeneo/Category/back/Domain/Model/Category.php, src/Akeneo/Category/back/Domain/Model/CategoryTree.php, src/Akeneo/Category/back/Domain/Query/GetCategoryTreesInterface.php, src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetCategorySql.php, src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetCategoryTreesSql.php, src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/queries.yml, src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetCategoryTreesSqlIntegration.php
=> GRF-289: Create model CategoryTree and service GetCategoryTreesSql

src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/product_model/add_child.yml, tests/legacy/features/pim/enrichment/product-model/add_product_model_children.feature
=> CPM-775: Product Variant - Don't display the SKU as required

front-packages/akeneo-design-system/src/components/Table/TableActionCell/TableActionCell.tsx
=> Add HTMLTableCellElement on ActionCell Component

src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetCategorySqlIntegration.php
=> CPM-594 fix category tests

src/Akeneo/Platform/Bundle/InstallerBundle/Command/AssetsCommand.php, src/Akeneo/Platform/Bundle/InstallerBundle/Command/DatabaseCommand.php, src/Akeneo/Platform/Bundle/InstallerBundle/Command/InstallCommand.php, src/Akeneo/Platform/Bundle/InstallerBundle/Event/InstallerEvent.php, src/Akeneo/Tool/Component/Console/CommandExecutor.php, tests/back/Platform/Specification/Bundle/InstallerBundle/Event/InstallerEventSpec.php
See https://akeneo.atlassian.net/browse/TIP-977
=> TIP-977: Move CommandExecutor to Tool

src/Akeneo/UserManagement/Bundle/Resources/config/commands.yml, src/Akeneo/UserManagement/Bundle/Resources/config/services.yml, src/Akeneo/UserManagement/Component/Connector/RoleWithPermissions.php, src/Akeneo/UserManagement/Component/Updater/RoleWithPermissionsUpdater.php, src/Akeneo/UserManagement/back/Application/Exception/UnknownUserRole.php, src/Akeneo/UserManagement/back/Application/RestoreAdminRolePermissions.php, src/Akeneo/UserManagement/back/Infrastructure/Cli/RestoreAdminRolePermissionsCommand.php, src/Akeneo/UserManagement/back/tests/Integration/Application/RestoreAdminRolePermissionsIntegration.php
Add a CLI command to restore all permissions to the Administrator role and recreate the role if it does not exist.
=> PIM-10672: Command to create/add roles with all existing permissions

src/Akeneo/Pim/Enrichment/Component/Product/Connector/ReadModel/ConnectorProduct.php, tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ReadModel/ConnectorProductSpec.php
=> CPM-767: Fix Product Connector for associations without sku

components/identifier-generator/back/src/Domain/Repository/IdentifierGeneratorRepository.php, components/identifier-generator/back/src/Infrastructure/Controller/ListIdentifierGeneratorController.php, components/identifier-generator/back/src/Infrastructure/Repository/InMemoryIdentifierGeneratorRepository.php, components/identifier-generator/back/src/Infrastructure/Repository/SqlIdentifierGeneratorRepository.php, components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/controllers.yml, components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/routing.yml, components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/ListIdentifierGeneratorControllerEndToEnd.php, components/identifier-generator/back/tests/Integration/Repository/SqlIdentifierGeneratorRepositoryIntegration.php, components/identifier-generator/back/tests/Specification/Infrastructure/Repository/InMemoryIdentifierGeneratorRepositorySpec.php
=> CPM-780: Controller to list Identifier Generators

src/Akeneo/Category/back/Application/ActivateTemplate.php, src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/storage/template.yml, src/Akeneo/Category/back/tests/Integration/Application/ActivateTemplateIntegration.php
=> GRF-539 plug template attribute saver to activateTemplate process

src/Akeneo/Category/front/src/feature/components/datagrids/CategoryTreeDataGrid.tsx, src/Akeneo/Pim/Enrichment/Bundle/Controller/Ui/CategoryTreeController.php
=> GRF-358: Add view template button

src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/EventSubscriber/NotifyOnDisabledCatalogEventSubscriberIntegration.php
=> CXP-1282: fix test for EE

components/catalogs/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml, components/catalogs/front/src/components/ProductMapping/components/SourcePlaceholder.tsx
Completed source placeholder using DSM components
=> CXP-1288: Completed placeholder with an illustration and text

src/Akeneo/Pim/Structure/Component/Updater/AttributeOptionUpdater.php, tests/back/Pim/Structure/EndToEnd/AttributeOption/ExternalApi/CreateAttributeOptionEndToEnd.php, tests/back/Pim/Structure/EndToEnd/AttributeOption/ExternalApi/PartialUpdateAttributeOptionEndToEnd.php, tests/back/Pim/Structure/Specification/Component/Updater/AttributeOptionUpdaterSpec.php
=> CPM-787: Check type of sort_order in attribute option updater

src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/routing.yml
=> GRF-358 : Fix routing declaration

front-packages/akeneo-design-system/src/components/Table/Table.stories.mdx, front-packages/akeneo-design-system/src/components/Table/TableActionCell/TableActionCell.tsx, src/Akeneo/Category/front/src/feature/components/datagrids/CategoryTreeDataGrid.tsx
=> Grf 289 fix event propagation after changing style applying

src/Akeneo/Category/front/src/feature/components/templates/EditTemplateAttributesForm.tsx
=> GRF-551 : Replace local selection by the catalog local on template page

src/Akeneo/Category/front/src/feature/components/templates/EditTemplateAttributesForm.tsx
=> GRF-552 : Hide the description settings panel on view template

src/Akeneo/Category/front/src/feature/components/datagrids/CategoryTreeDataGrid.tsx, src/Akeneo/Category/front/src/feature/pages/CategoriesTreePage.tsx
=> Grf 559 : Delete Activate template button on category tree page

components/identifier-generator/back/src/Infrastructure/Controller/GetIdentifierGeneratorController.php, components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/controllers.yml, components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/routing.yml, components/identifier-generator/back/tests/EndToEnd/ControllerEndToEndTestCase.php, components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/GetIdentifierGeneratorControllerEndToEnd.php
=> CPM-782: Create controller and rest route to GET an identifier generator

components/identifier-generator/back/src/Application/Update/UpdateGeneratorCommand.php, components/identifier-generator/back/src/Application/Update/UpdateGeneratorHandler.php, components/identifier-generator/back/src/Domain/Exception/UnableToUpdateIdentifierGeneratorException.php, components/identifier-generator/back/src/Domain/Model/IdentifierGenerator.php, components/identifier-generator/back/src/Domain/Repository/IdentifierGeneratorRepository.php, components/identifier-generator/back/src/Infrastructure/Controller/UpdateIdentifierGeneratorController.php, components/identifier-generator/back/src/Infrastructure/Repository/InMemoryIdentifierGeneratorRepository.php, components/identifier-generator/back/src/Infrastructure/Repository/SqlIdentifierGeneratorRepository.php, components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/command_handlers.yml, components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/controllers.yml, components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/routing.yml, components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/validation/create_generator_command.yml, components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/validators.yml, components/identifier-generator/back/src/Infrastructure/Validation/UpdateGeneratorCommandValidator.php, components/identifier-generator/back/tests/Acceptance/Context/UpdateIdentifierGeneratorContext.php, components/identifier-generator/back/tests/Acceptance/Resources/config/services.yml, components/identifier-generator/back/tests/EndToEnd/ControllerEndToEndTestCase.php, components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/UpdateIdentifierGeneratorControllerEndToEnd.php, components/identifier-generator/back/tests/Integration/Repository/SqlIdentifierGeneratorRepositoryIntegration.php, components/identifier-generator/back/tests/Specification/Domain/Model/IdentifierGeneratorSpec.php, components/identifier-generator/back/tests/Specification/Infrastructure/Repository/InMemoryIdentifierGeneratorRepositorySpec.php, components/identifier-generator/back/tests/behat.yml, components/identifier-generator/back/tests/features/updateIdentifierGenerator.feature
=> CPM-781: Controller to SAVE an existing identifier generator

.circleci/jobs/features/catalogs/test_back_catalogs_ce.yml, .circleci/jobs/features/catalogs/test_performance_catalogs_ce.yml, .circleci/workflows/squads/octopus/octopus_catalogs_pull_request.yml, components/catalogs/Makefile, components/catalogs/back/phpunit.xml.dist, components/catalogs/back/rector.php, components/catalogs/back/tests/Performance/GetCatalogProductsPerformance.php, components/catalogs/back/tests/Performance/PerformanceTestCase.php, composer.json, composer.lock
Using blackfire,
This new CI step checks wall time, peak memory, number of SQL queries and number of ES queries when the endpoint is called.
You can also check the graph to see where the time is spent.
https://blackfire.io/profiles/0e2b495a-327c-4bac-92e8-8b38dc0cc976/graph
=> enable blackfire in catalogs

tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/SuccessListProductEndToEnd.php, tests/back/Pim/Enrichment/Integration/PQB/Filter/Field/IdentifierFilterIntegration.php
Update API test using uuid as product identifier
=> CPM-737: Fix brittle test

tests/back/Integration/TestCase.php, tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/PartialUpdateProductWithUuidEndToEnd.php, tests/back/Pim/Enrichment/Integration/Storage/Sql/ElasticsearchProjection/GetElasticsearchProductProjectionIntegration.php, tests/back/Pim/Enrichment/Integration/Storage/Sql/Product/Association/GetGroupAssociationsByProductUuidsIntegration.php, tests/back/Pim/Enrichment/Integration/Storage/Sql/Product/Association/GetProductAssociationsByProductUuidsIntegration.php, tests/back/Pim/Enrichment/Integration/Storage/Sql/Product/Association/GetProductModelAssociationsByProductUuidsIntegration.php, tests/back/Pim/Enrichment/Integration/Storage/Sql/Product/GetAncestorProductModelCodesIntegration.php, tests/back/Pim/Enrichment/Integration/Storage/Sql/Product/GetCategoryCodesByProductUuidsIntegration.php, tests/back/Pim/Enrichment/Integration/Storage/Sql/Product/GetValuesAndPropertiesFromProductUuidsIntegration.php, tests/back/Pim/Enrichment/Integration/Storage/Sql/Product/QuantifiedAssociation/GetProductModelQuantifiedAssociationsByProductUuidsIntegration.php, tests/back/Pim/Enrichment/Integration/Storage/Sql/Product/QuantifiedAssociation/GetProductQuantifiedAssociationsByProductUuidsIntegration.php
Refactor **getProductUuidFromIdentifier** in the integration tests
=> CPM-789 : refactor getProductUuidFromIdentifier

src/Akeneo/Category/front/src/feature/components/EditAttributesForm.tsx
=> GRF-560: Sync category edition page locale with Products pages

components/catalogs/back/src/Infrastructure/Controller/Public/GetProductAction.php, components/catalogs/back/src/Infrastructure/Controller/Public/GetProductIdentifiersAction.php, components/catalogs/back/src/Infrastructure/Controller/Public/GetProductUuidsAction.php, components/catalogs/back/src/Infrastructure/Controller/Public/GetProductsAction.php, components/catalogs/back/tests/Acceptance/ApiContext.php, components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/GetProductActionTest.php, components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/GetProductIdentifiersActionTest.php, components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/GetProductUuidsActionTest.php, components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/GetProductsActionTest.php
=> CXP-1341: Update 200 OK - error message catalog disabled

front-packages/measurement/package.json, front-packages/measurement/src/index.tsx, src/Akeneo/Platform/Job/front/process-tracker/package.json, src/Akeneo/Platform/Job/front/process-tracker/src/index.tsx
See https://github.com/akeneo/pim-community-dev/pull/18033
=> RAB-301: Use shared translator in Job&Measurements

tests/legacy/features/Behat/Decorator/Field/Select2Decorator.php
https://app.circleci.com/pipelines/github/akeneo/pim-enterprise-dev/84301/workflows/88d2cc0e-775c-4f9d-aa88-f9d87a90781b/jobs/551854
=> Fix random behat

components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml, components/identifier-generator/front/src/feature/IdentifierGeneratorApp.tsx, components/identifier-generator/front/src/feature/components/Common.tsx, components/identifier-generator/front/src/feature/components/Header.tsx, components/identifier-generator/front/src/feature/components/ListSkeleton.tsx, components/identifier-generator/front/src/feature/components/Styled.tsx, components/identifier-generator/front/src/feature/controllers/List.tsx, components/identifier-generator/front/src/feature/controllers/__tests__/List.test.tsx, components/identifier-generator/front/src/feature/hooks/__mocks__/useIdentifierAttributes.ts, components/identifier-generator/front/src/feature/hooks/__tests__/useGetGenerators.test.tsx, components/identifier-generator/front/src/feature/hooks/__tests__/useIdentifierAttributes.test.tsx, components/identifier-generator/front/src/feature/hooks/index.ts, components/identifier-generator/front/src/feature/hooks/useGetGenerators.ts, components/identifier-generator/front/src/feature/hooks/useIdentifierAttributes.ts, components/identifier-generator/front/src/feature/pages/CreateGeneratorModal.tsx, components/identifier-generator/front/src/feature/pages/CreateOrEditGeneratorPage.tsx, components/identifier-generator/front/src/feature/pages/ListPage.tsx, components/identifier-generator/front/src/feature/pages/__tests__/ListPage.test.tsx, components/identifier-generator/front/src/feature/pages/styles/ListPageStyled.ts, components/identifier-generator/front/src/feature/tests/hooks/config/createWrapper.tsx
Screen when there are no generator created yet
Screen when there is one generator
=> CPM-751: Add generator list page

src/Akeneo/Category/back/Domain/Model/Enrichment/Category.php, src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetCategorySql.php, src/Akeneo/Category/back/ServiceApi/ExternalApiCategory.php
=> GRF-381: Create a read model / DTO to adapt the categories data for the External API format

CHANGELOG-6.0.md, src/Akeneo/Category/front/src/feature/components/providers/CategoryTreeProvider.tsx, src/Akeneo/Category/front/src/feature/hooks/useCategoryTreeNode.ts
=> pull-up 6.0 master

src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml, src/Akeneo/Category/front/src/feature/components/EditAttributesForm.tsx, src/Akeneo/Category/front/src/feature/components/TemplateTitle.tsx, src/Akeneo/Category/front/src/feature/components/index.ts, src/Akeneo/Category/front/src/feature/components/templates/EditTemplateAttributesForm.tsx, src/Akeneo/Category/front/src/feature/hooks/useTemplateByTemplateUuid.ts, src/Akeneo/Category/front/src/feature/pages/CategoryEditPage.tsx
With a locale : 
Without a locale : 
=> GRF-544 : Display template label for enriched category

src/Akeneo/Category/back/Application/Query/GetCategoriesInterface.php, src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetCategoriesSql.php, src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/queries.yml, src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetCategoriesSqlIntegration.php
=> Grf 375 Create a Query (CQRS) to retrieve a list of categories

CHANGELOG-5.0.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/associations/product.yml
=> PIM-10708: Pull-up 5.0 into 6.0

components/identifier-generator/front/src/feature/components/Styled.tsx, components/identifier-generator/front/src/feature/components/index.ts, components/identifier-generator/front/src/feature/controllers/Edit.tsx, components/identifier-generator/front/src/feature/pages/CreateGeneratorModal.tsx, components/identifier-generator/front/src/feature/tabs/GeneralPropertiesTab.tsx, components/identifier-generator/front/src/feature/tabs/Structure.tsx
=> SCM-103: Fix identifier-generator front build

components/catalogs/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
=> OCT-150: Update value filters translations

components/identifier-generator/front/src/feature/components/Styled.tsx
=> Fix non used Styled creating errors

tests/back/Pim/Enrichment/Specification/Component/Product/Job/RemoveCompletenessForChannelAndLocaleTaskletSpec.php
Fixes a flaky test (see https://app.circleci.com/pipelines/github/akeneo/pim-enterprise-dev/84989/workflows/1ac6f598-24a9-43a5-898a-76a6a86bc36f/jobs/558448)
=> Fix flaky spec

CHANGELOG-6.0.md, src/Akeneo/UserManagement/Component/Normalizer/Standard/UserNormalizer.php, tests/back/UserManagement/Integration/Bundle/Export/ExportUserIntegration.php
=> PIM-10699: [SLA] "All" is exported allong with the user groups on the user export

CHANGELOG-5.0.md, CHANGELOG-6.0.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/associations/product.yml, src/Akeneo/UserManagement/Component/Normalizer/Standard/UserNormalizer.php, tests/back/UserManagement/Integration/Bundle/Export/ExportUserIntegration.php
=> PIM-10719: Pull-up 6.0 => master

components/catalogs/front/src/components/CatalogEdit/hooks/useCatalogForm.ts, components/catalogs/front/src/components/CatalogEdit/hooks/useCatalogForm.unit.ts
=> OCT-168: Delete errors when a cirteria is removed from the product selection

docker-compose.yml
=> RAB-1122: Update MySQL

composer.json, composer.lock, src/Akeneo/Category/back/tests/Specification/Infrastructure/Doctrine/ORM/Repository/CategoryRepositorySpec.php, src/Akeneo/Pim/Enrichment/Product/back/API/Command/UpsertProductCommand.php, src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Validation/LocaleAndChannelShouldBeConsistentValidator.php, src/Akeneo/Pim/Structure/Component/Query/PublicApi/AttributeType/GetAttributes.php, tests/back/Pim/Enrichment/Specification/Bundle/Doctrine/ORM/Repository/InternalApi/CategoryRepositorySpec.php
Fixes CVE-2022-41343 Remote file inclusion: https://github.com/advisories/GHSA-6x28-7h8c-chx4
Update all Composer dependencies by the way.
=> Hotfix: Fixes dompdf/dompdf CVE and update Composer dependencies

src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Controller/Dashboard/FindFamiliesController.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/controllers.yml, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/routing.yml, src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/fetcher/Dashboard/fetchFamiliesByCodes.ts, src/Akeneo/Pim/Automation/DataQualityInsights/front/src/infrastructure/hooks/Dashboard/useFetchFamiliesByCodes.ts, src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/.php_cd.php, src/Akeneo/Pim/Automation/DataQualityInsights/tests/front/unit/unit.jest.js
Add dedicated controller to fetch families for DQI dashboard needs
Force to use family codes in lowercase for PIM-10633 issue
=> Add dedicated controller to fetch families for DQI dashboard needs

CHANGELOG.md, src/Akeneo/Pim/Structure/Bundle/Controller/ExternalApi/FamilyVariantController.php, tests/back/Pim/Structure/EndToEnd/FamilyVariant/ExternalApi/GetFamilyVariantEndToEnd.php
=> PIM-10725: Fix get family variant case sensitive

CHANGELOG.md, src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Versioning/Product/PriceNormalizer.php, tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/Versioning/Product/PriceNormalizerSpec.php
Round up prices for versionning
=> PIM-10720: Fix price versioning normalizer to round numbers

components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml, components/identifier-generator/front/src/feature/hooks/__tests__/useSaveGenerator.test.tsx, components/identifier-generator/front/src/feature/hooks/useCreateIdentifierGenerator.ts, components/identifier-generator/front/src/feature/hooks/useGetIdentifierGenerators.ts, components/identifier-generator/front/src/feature/hooks/useSaveGenerator.ts, components/identifier-generator/front/src/feature/pages/CreateGeneratorPage.tsx, components/identifier-generator/front/src/feature/pages/CreateOrEditGeneratorPage.tsx, components/identifier-generator/front/src/feature/pages/EditGeneratorPage.tsx, components/identifier-generator/front/src/feature/pages/__tests__/CreateGeneratorPage.test.tsx, components/identifier-generator/front/src/feature/pages/__tests__/CreateOrEditGeneratorPage.test.tsx, components/identifier-generator/front/src/feature/pages/__tests__/EditGeneratorPage.test.tsx, components/identifier-generator/front/src/feature/tabs/structure/AddPropertyButton.tsx, components/identifier-generator/front/src/feature/tests/hooks/config/createWrapper.tsx
=> CPM-784: Add useSaveGenerator hook

src/Akeneo/Category/back/Application/Query/GetCategoriesInterface.php, src/Akeneo/Category/back/Domain/Model/Enrichment/Category.php, src/Akeneo/Category/back/Infrastructure/Controller/ExternalApi/ListCategoriesController.php, src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetCategoriesSql.php, src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetCategorySql.php, src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/controllers.yml, src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/queries.yml, src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/routing/external_api/category.yml, src/Akeneo/Category/back/ServiceApi/ExternalApiCategory.php, src/Akeneo/Category/back/tests/Integration/Helper/CategoryTestCase.php, src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetCategoriesSqlIntegration.php, src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetCategorySqlIntegration.php
* GRF-374: Create a new controller to list the categories on the REST API
* GRF-374: prepare get count
* GRF-374: Forward response
* GRF-374: Forward response to old controller if feature flag is disabled
* GRF-374: Remove dependence on category repository
* GRF-374: Fix return response
=> GRF-200: As Sarah, I want to export enriched categories (attribute values) via the API

upgrades/schema/Version_5_0_20220830143500_fix_volume_flow_conversion.php
fix undetected migration namespace
=> PIM-10728: fix namespace

components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml, components/identifier-generator/front/src/feature/pages/ListPage.tsx, components/identifier-generator/front/src/feature/pages/__tests__/ListPage.test.tsx
=> CPM-806: Add placeholder when 1st generator has been created

components/identifier-generator/back/src/Infrastructure/Symfony/Install/InstallerSubscriber.php, upgrades/schema/Version_7_0_20221116131232_add_prefixes_identifier_generator_table.php, upgrades/test_schema/Version_7_0_20221116131232_add_prefixes_identifier_generator_table_Integration.php
=> CPM-816: Identifier Generator Create table to store prefixes

CHANGELOG.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/mass-edit/form/product/associate.js
=> PIM-10730: Fix mass actions for quantified associations rendering

CHANGELOG-6.0.md, composer.json, composer.lock, src/Akeneo/Pim/Structure/Bundle/Resources/public/js/attribute-option/components/AttributeOptionTable.tsx
=> PIM-10688: Fix error on toLocaleLowerCase for select attribute options

CHANGELOG-5.0.md, src/Akeneo/Tool/Component/Connector/Archiver/AbstractInvalidItemWriter.php, upgrades/schema/Version_5_0_20220830143500_fix_volume_flow_conversion.php
=> Pull-up 5.0 to 6.0

src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/product/edit.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/meta/uuid.js, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/meta/uuid.js, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/form/meta/uuid.html, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/product/meta/uuid.html
=> CPM-805: Improve UUID accessibility for the user

src/Akeneo/Category/front/src/feature/components/providers/EditCategoryProvider.tsx, src/Akeneo/Category/front/src/feature/helpers/categoryHelper.ts, src/Akeneo/Category/front/src/feature/hooks/useCategory.ts, src/Akeneo/Category/front/src/feature/hooks/useEditCategoryForm.ts, src/Akeneo/Category/front/src/feature/models/Attribute.ts, src/Akeneo/Category/front/src/feature/models/CompositeKey.ts
Fetch channels, build the composite key and add the channel code in data values to have a payload like this:
=> GRF-591: Use is scopable info in POST

components/identifier-generator/front/src/feature/tabs/structure/Preview.tsx
=> Fix case sensitive import

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/history.js, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/product/history.html
=> CPM-335: history version toggle only with icon

src/Akeneo/Category/front/src/feature/components/EditAttributesForm.tsx, src/Akeneo/Category/front/src/feature/components/attributes/buildImageFieldAttribute.tsx, src/Akeneo/Category/front/src/feature/components/attributes/buildRichTextFieldAttribute.tsx, src/Akeneo/Category/front/src/feature/components/attributes/buildTextAreaFieldAttribute.tsx, src/Akeneo/Category/front/src/feature/components/attributes/buildTextFieldAttribute.tsx, src/Akeneo/Category/front/src/feature/components/attributes/templateAttributesFactory.tsx, src/Akeneo/Category/front/src/feature/components/attributes/types.ts
=> GRF-596 Add channel on scopable attributes in Category edit form

components/identifier-generator/front/src/feature/components/LabelTranslations.tsx, components/identifier-generator/front/src/feature/components/LabelTranslationsSkeleton.tsx, components/identifier-generator/front/src/feature/components/Styled.tsx, components/identifier-generator/front/src/feature/components/index.ts
[Identifier Generator.webm](https://user-images.githubusercontent.com/2642040/203560261-e460a79a-3568-47c8-a87a-6b118de1b5dd.webm)
=> CPM-796: Add Skeleton for labels on edit/create page

components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml, components/identifier-generator/front/src/feature/controllers/Edit.tsx, components/identifier-generator/front/src/feature/pages/CreateOrEditGeneratorPage.tsx, components/identifier-generator/front/src/feature/tabs/StructureTab.tsx, components/identifier-generator/front/src/feature/tabs/__tests__/StructureTab.test.tsx, components/identifier-generator/front/src/feature/tabs/structure/PropertyEdit.tsx
Prevent adding another property on the structure when limit is reached
=> CPM-820: Add helper and disable button when properties limit is reached

public/index.php
=> RAB-1203: Remove Request::HEADER_X_FORWARDED_ALL deprecation

src/Akeneo/Category/back/Infrastructure/Storage/Save/Query/UpsertCategoryTranslationsSql.php, src/Akeneo/Category/back/tests/Integration/Helper/CategoryTestCase.php, src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Save/Query/UpsertCategoryTranslationsSqlIntegration.php
=> GRF-570 : Add a non regression test on managing LabelCollection

CHANGELOG.md, src/Akeneo/Pim/Enrichment/Bundle/Command/IndexProductModelCommand.php
Fix product model indexation command when using the `--diff` option
=> PIM:10741: Fix diff indexation of product models

src/Akeneo/Pim/Enrichment/Bundle/Command/ZddMigrations/V20220729171405DropProductIdColumnsAndCleanVersioningResourceUuidColumns.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/cli_command.yml, tests/back/Pim/Enrichment/Integration/Product/V20220729171405DropProductIdColumnsAndCleanVersioningResourceUuidColumnsIntegration.php
- Removes DB triggers introduced during the uuid migration
- Removes the DB column that references `pim_catalog_product.id` columns
- Cleans up the versioning table from `resource_uuid` information for non product related versions.
Regarding the DB structure changes, here is an example of what is going to be executed on the environments
```
-- Version Pim\Upgrade\Schema\Version_7_0_20220823121643_remove_uuid_triggers
DROP TRIGGER IF EXISTS pim_catalog_association_uuid_insert;
DROP TRIGGER IF EXISTS pim_catalog_association_uuid_update;
DROP TRIGGER IF EXISTS pim_catalog_association_product_uuid_insert;
DROP TRIGGER IF EXISTS pim_catalog_association_product_uuid_update;
DROP TRIGGER IF EXISTS pim_catalog_association_product_model_to_product_uuid_insert;
DROP TRIGGER IF EXISTS …
```
=> CPM-691: with column removal deploy env

config/packages/framework.yml, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Controller/LiveblocksController.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/controllers.yml, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/routing.yml, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/js/infrastructure/liveblocks/Liveblocks.tsx, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/js/infrastructure/liveblocks/LiveblocksApp.tsx, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/js/infrastructure/liveblocks/components/Avatar.tsx, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/js/infrastructure/liveblocks/liveblocks.config.ts, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/public/js/infrastructure/liveblocks/view.ts
=> GRF-577: [POC] Integrate the live avatar component in the PEF

src/Akeneo/Category/back/Application/Handler/GetPositionInterface.php, src/Akeneo/Category/back/Application/Query/GetDirectChildrenCategoryCodesInterface.php, src/Akeneo/Category/back/Infrastructure/Component/Manager/PositionResolver.php, src/Akeneo/Category/back/Infrastructure/Component/Manager/PositionResolverInterface.php, src/Akeneo/Category/back/Infrastructure/Controller/ExternalApi/ListCategoriesController.php, src/Akeneo/Category/back/Infrastructure/Handler/GetPositionHandler.php, src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetDirectChildrenCategoryCodes.php, src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/controllers.yml, src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/handlers.yml, src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/queries.yml, src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetDirectChildrenCategoryCodesIntegration.php, src/Akeneo/Category/back/tests/Specification/Infrastructure/Component/Manager/PositionResolverSpec.php, src/Akeneo/Category/back/tests/Specification/Infrastructure/Handler/GetPositionHandlerSpec.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/managers.yml
=> GRF-379: Create a position handler to decouple legacy

components/identifier-generator/front/src/feature/hooks/index.ts, components/identifier-generator/front/src/feature/hooks/useStructureTabs.ts, components/identifier-generator/front/src/feature/models/generatorTab.ts, components/identifier-generator/front/src/feature/models/index.ts, components/identifier-generator/front/src/feature/models/structureTabs.ts, components/identifier-generator/front/src/feature/pages/CreateOrEditGeneratorPage.tsx, components/identifier-generator/front/src/feature/pages/ListPage.tsx
Add state to history location in order to stay on the same tab after redirect on create
=> CPM-830: Add currentTab to location state to stay on same tab after create

src/Akeneo/Pim/Enrichment/Bundle/ProductQueryBuilder/ProductAndProductModelQueryBuilder.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/datagrid/product.yml, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/query_builders.yml, src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/messages.en_US.yml, src/Oro/Bundle/PimDataGridBundle/Resources/config/requirejs.yml, src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/uuid-filter.js, src/Oro/Bundle/PimDataGridBundle/Resources/translations/jsmessages.en_US.yml
=> CPM-788: Add the ability to filter the product grid using Uuids

CHANGELOG.md, src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/FlatToStandard/ColumnsMerger.php, src/Akeneo/Pim/Enrichment/Component/Product/Model/QuantifiedAssociation/QuantifiedAssociationCollection.php, tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/FlatToStandard/ColumnsMergerSpec.php
=> PIM-10716: Fix uuids in quantified association revert version

CHANGELOG-6.0.md, src/Akeneo/Tool/Component/Connector/Archiver/FileWriterArchiver.php, src/Akeneo/Tool/Component/Connector/spec/Archiver/FileWriterArchiverSpec.php
=> Pull-up 6.0 => master

src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Field/LabelIdentifierOrUuidFilter.php, src/Akeneo/Pim/Enrichment/Bundle/ProductQueryBuilder/ProductAndProductModelQueryBuilder.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/datagrid/product.yml, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/query_builders.yml, src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/messages.en_US.yml, src/Oro/Bundle/PimDataGridBundle/Resources/config/requirejs.yml, src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/label_identifier_or_uuid-filter.js, src/Oro/Bundle/PimFilterBundle/Filter/Product/LabelIdentifierOrUuidFilter.php, src/Oro/Bundle/PimFilterBundle/Resources/config/filters.yml, src/Oro/Bundle/PimFilterBundle/spec/Filter/Product/LabelIdentifierOrUuidFilterSpec.php, tests/back/Pim/Enrichment/Integration/PQB/AbstractProductAndProductModelQueryBuilderTestCase.php, tests/back/Pim/Enrichment/Integration/PQB/Filter/LabelIdentifierOrUuidFilterIntegration.php, tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Filter/Field/LabelIdentifierOrUuidFilterSpec.php, tests/legacy/features/Context/Page/Base/Grid.php, tests/legacy/features/pim/enrichment/product/datagrid/filtering/filter_products_per_label_or_identifier.feature
=> CPM-791: Be able to search by UUID in the searchbar

src/Akeneo/Pim/Enrichment/Bundle/Command/IndexProductCommand.php
=> CPM-836: Fix diff indexation of product

components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml, components/identifier-generator/front/src/feature/pages/CreateOrEditGeneratorPage.tsx, components/identifier-generator/front/src/feature/pages/__tests__/CreateOrEditGeneratorPage.test.tsx, components/identifier-generator/front/src/feature/tabs/StructureTab.tsx, components/identifier-generator/front/src/feature/tabs/__mocks__/StructureTab.tsx, components/identifier-generator/front/src/feature/tabs/__tests__/DelimiterEdit.test.tsx, components/identifier-generator/front/src/feature/tabs/__tests__/StructureTab.test.tsx, components/identifier-generator/front/src/feature/tabs/structure/DelimiterEdit.tsx, components/identifier-generator/front/src/feature/tabs/structure/__mocks__/DelimiterEdit.tsx, components/identifier-generator/front/src/feature/tabs/structure/index.ts, components/identifier-generator/front/src/feature/tests/fixtures/initialGenerator.ts, components/identifier-generator/front/src/feature/validators/__tests__/validateDelimiter.test.ts, components/identifier-generator/front/src/feature/validators/validateDelimiter.ts
- Adds the UI to set a custom delimiter in the identifier generator
=> CPM-793: Add Delimiters in strucutre tab

components/catalogs/back/src/Infrastructure/Symfony/Resources/translations/validators.en_US.yml, components/catalogs/back/src/Infrastructure/Validation/CatalogUpdatePayloadValidator.php, components/catalogs/back/tests/Integration/Infrastructure/Validation/CatalogUpdatePayloadTest.php, components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductMapping/AttributeSource/AttributeTextSourceTest.php, components/catalogs/front/src/components/CatalogEdit/hooks/useCatalogForm.ts, components/catalogs/front/src/components/CatalogEdit/hooks/useCatalogForm.unit.ts, components/catalogs/front/src/components/ProductMapping/components/SelectAttributeDropdown.tsx, components/catalogs/front/src/components/ProductMapping/components/SelectChannelDropdown.tsx, components/catalogs/front/src/components/ProductMapping/components/SelectChannelLocaleDropdown.tsx, components/catalogs/front/src/components/ProductMapping/components/SelectLocaleDropdown.tsx, components/catalogs/front/src/components/ProductSelection/components/UnknownCriterion.tsx, components/catalogs/front/src/hooks/useLocalesByCodes.ts
=> CXP-1354: Display errors messages

src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/product/index.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/GridToolbar.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/product/index.html
=> CPM-826: Add pagination at the bottom of the product grid

src/Akeneo/Category/back/Domain/Model/Enrichment/Category.php, src/Akeneo/Category/back/Domain/ValueObject/PermissionCollection.php
=> Grf 340 bis Change Permission model to add user group names

src/Akeneo/Category/back/Domain/Model/Enrichment/Category.php, src/Akeneo/Category/back/Infrastructure/Builder/TemplateBuilder.php, src/Akeneo/Category/back/Infrastructure/Controller/ExternalApi/ListCategoriesController.php, src/Akeneo/Category/back/ServiceApi/ExternalApiCategory.php, src/Akeneo/Category/back/tests/EndToEnd/ExternalApi/ApiCategoryTestCase.php, src/Akeneo/Category/back/tests/EndToEnd/ExternalApi/ListCategoryEndToEnd.php, src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetCategorySqlIntegration.php
=> GRF-448 : Update end to end tests to cover the with enriched values use case

src/Akeneo/Pim/Enrichment/Bundle/Product/ComputeAndPersistProductCompletenesses.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/completeness.yml, tests/back/Pim/Enrichment/Specification/Bundle/Product/ComputeAndPersistProductCompletenessesSpec.php
The goal is to prevent any possible errors in the performance analytics on the critical path (here the product update)
We saw that, even if we have the best tests in our context, we still can have issues due to
- platform configuration
- external service down
- ....
Here we catch every errors and log them
=> JEL-123: add additional defensive measure on time-to-enrich feature

src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml, src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApp/ConnectedAppContainer.tsx, src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApp/ConnectedAppContainer.test.tsx
=> CXP-1326: Add the open app button in the app header

src/Akeneo/Pim/Enrichment/Bundle/Command/IndexProductCommand.php, src/Akeneo/Pim/Enrichment/Bundle/Command/IndexProductModelCommand.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/cli_command.yml, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml, src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/ProductAndProductModel/GetAllProductUuids.php, src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/ProductAndProductModel/GetAllRootProductModelCodes.php, src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/ProductAndProductModel/GetExistingProductModelCodes.php, src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/ProductAndProductModel/GetExistingProductUuids.php, src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/ProductAndProductModel/GetProductModelCodesNotSynchronisedBetweenEsAndMysql.php, src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/ProductAndProductModel/GetProductUuidsNotSynchronisedBetweenEsAndMysql.php, tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductAndProductModel/GetAllProductIntegration.php, tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductAndProductModel/GetAllRootProductModelIntegration.php, tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductAndProductModel/GetProductExistingAmongIntegration.php, tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductAndProductModel/GetProductModelExistingAmongIntegration.php, tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductAndProductModel/GetProductModelNotSynchronisedBetweenEsAndMysqlIntegration.php, tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductAndProductModel/GetProductNotSynchronisedBetweenEsAndMysqlIntegration.php
=> CPM-834: Refacto index product and product model

components/catalogs/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml, components/catalogs/front/src/components/ProductSelection/ProductSelection.tsx, components/catalogs/front/src/components/ProductSelection/components/CountSelectedProductsByCriteria.tsx, components/catalogs/front/src/components/ProductSelection/hooks/useCountProductsInSelectionCriteria.ts, components/catalogs/front/src/components/ProductSelection/hooks/useCountProductsInSelectionCriteria.unit.ts
=> CXP-1333: Be able to count the number of products in the selection criteria

CHANGELOG.md, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/controllers.yml
See [issue](https://akeneo.atlassian.net/jira/software/c/projects/PIM/boards/9?modal=detail&selectedIssue=PIM-10739&quickFilter=650). 
=> PIM-10739 : Data Quality Insights dashboard: get family grades for EE

components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
=> CPM-823: Add translation for identifier generator edit page

src/Akeneo/Connectivity/Connection/back/Infrastructure/Audit/Command/UpdateAuditDataCommand.php, src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/Command/SendBusinessEventToWebhooks.php
=> OCT-183: add 2 try catch to log TableNotFound and ConnectionLost exceptions

src/Akeneo/Connectivity/Connection/back/Infrastructure/ErrorManagement/Persistence/PurgeConnectionErrorsQuery.php
This PR updates queries that use `_id` field to use the mapped field  `id` created by [OCT-164](https://github.com/akeneo/pim-community-dev/pull/18263)
=> OCT-166 Use mapped id field for connection_error index

src/Akeneo/Pim/Structure/Bundle/Resources/config/validation/attribute.yml, tests/back/Pim/Structure/Integration/Attribute/Validation/GlobalConstraintsIntegration.php
=> CPM-871: Forbid attribute creation named "identifier"

components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/form_extensions.yml, components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/requirejs.yml, components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/routing.yml, components/identifier-generator/back/tests/EndToEnd/ControllerEndToEndTestCase.php, components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/CreateIdentifierGeneratorControllerEndToEnd.php, components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/DeleteIdentifierGeneratorControllerEndToEnd.php, components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/GetIdentifierAttributesControllerEndToEnd.php, components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/GetIdentifierGeneratorControllerEndToEnd.php, components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/ListIdentifierGeneratorControllerEndToEnd.php, components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/UpdateIdentifierGeneratorControllerEndToEnd.php, components/identifier-generator/back/tests/EndToEnd/Infrastructure/Subscriber/SetIdentifiersSubscriberEndToEnd.php, components/identifier-generator/back/tests/Integration/Repository/SqlIdentifierGeneratorRepositoryIntegration.php, config/packages/akeneo_feature_flag.yml, src/Akeneo/Platform/Bundle/FeatureFlagBundle/Configuration/OnlySaasFeatureFlag.php, src/Akeneo/Platform/Bundle/FeatureFlagBundle/Resources/config/services.yml
Only enable identifier generator features for Saas editions for the time being
=> CPM-865: Identifier generator feature flag

src/Akeneo/Category/back/Application/UpsertCategoryCommandHandler.php, src/Akeneo/Category/back/tests/Specification/Application/UpsertCategoryCommandHandlerSpec.php, src/Akeneo/Category/back/tests/phpstan.neon.dist
=> GRF-655: Create make category-ci on EE + phpstan & lint fix

docker-compose.yml
=> RAB-1204: upgrade elastic search image

components/catalogs/back/src/Infrastructure/Controller/Internal/CountProductsSelectedByCriteriaAction.php, components/catalogs/back/src/Infrastructure/Persistence/Catalog/Product/GetProductQuery.php, components/catalogs/back/src/Infrastructure/Persistence/Catalog/Product/GetProductsWithFilteredValuesQuery.php, components/catalogs/back/src/Infrastructure/Validation/ProductMapping/AttributeSourceContainsValidLocaleValidator.php, components/catalogs/back/src/Infrastructure/Validation/ProductMapping/AttributeSourceContainsValidScopeValidator.php, components/catalogs/back/src/Infrastructure/Validation/ProductSelection/AttributeCriterionContainsValidLocaleValidator.php, components/catalogs/back/src/Infrastructure/Validation/ProductSelection/AttributeCriterionContainsValidScopeValidator.php
Psalm was updated to 5.1 (https://github.com/akeneo/pim-community-dev/pull/18621/files) and broke our lint step in CI
=> OCT-190: CI master : fix lint due to Psalm update

components/identifier-generator/back/src/API/Presenter/UnableToSetIdentifierExceptionPresenterInterface.php, components/identifier-generator/back/src/API/Subscriber/UnableToSetIdentifiersSubscriberInterface.php, components/identifier-generator/back/src/Application/Exception/UnableToSetIdentifierException.php, components/identifier-generator/back/src/Application/Validation/ErrorList.php, components/identifier-generator/back/src/Infrastructure/Presenter/UnableToSetIdentifierExceptionPresenter.php, components/identifier-generator/back/src/Infrastructure/Subscriber/UnableToSetIdentifiersSubscriber.php, components/identifier-generator/back/src/Infrastructure/Symfony/DependencyInjection/AkeneoIdentifierGeneratorExtension.php, components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/presenters.yml, components/identifier-generator/back/tests/.php_cd.php, src/Akeneo/Pim/Enrichment/.php_cd.php, src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/Product/UpdateProductController.php, src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/ProductController.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/controllers.yml, src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/product/create.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/creation/modal.js, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/creation/modal.js, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/save.js, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/variant-navigation.js
=> CPM-808: Add warnings on PEF create/update

src/Akeneo/Platform/Bundle/InstallerBundle/Command/CheckRequirementsCommand.php, src/Akeneo/Platform/Bundle/InstallerBundle/Resources/config/cli_command.yml, src/Akeneo/Platform/PimRequirements.php, src/Akeneo/Platform/Requirements.php
Small fix of a method returning now string OR int OR null.
Plus some cleaning
=> Fix PIM requirements check

src/Akeneo/Category/front/src/feature/components/EditAttributesForm.tsx, src/Akeneo/Category/front/src/feature/components/EditPropertiesForm.tsx, src/Akeneo/Category/front/src/feature/components/templates/EditTemplateAttributesForm.tsx, src/Akeneo/Category/front/src/feature/components/templates/EditTemplatePropertiesForm.tsx, src/Akeneo/Category/front/src/feature/pages/CategoryEditPage.tsx, src/Akeneo/Category/front/src/feature/pages/TemplatePage.tsx
=> GRF-583 fix sticky tab and section in template edit page

src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Apps/Public/RedirectToEditConnectedAppActionEndToEnd.php
=> OCT-191: properly declare connection property

CHANGELOG-6.0.md, src/Akeneo/UserManagement/Bundle/Resources/config/commands.yml, src/Akeneo/UserManagement/Bundle/Resources/config/services.yml, src/Akeneo/UserManagement/Component/Connector/RoleWithPermissions.php, src/Akeneo/UserManagement/Component/Updater/RoleWithPermissionsUpdater.php, src/Akeneo/UserManagement/back/Application/Exception/UnknownUserRole.php, src/Akeneo/UserManagement/back/Application/RestoreAdminRolePermissions.php, src/Akeneo/UserManagement/back/Infrastructure/Cli/RestoreAdminRolePermissionsCommand.php, src/Akeneo/UserManagement/back/tests/Integration/Application/RestoreAdminRolePermissionsIntegration.php
Backport from https://github.com/akeneo/pim-community-dev/pull/18191
=> PIM-10690: [Backport] Command to create/add roles with all existing permission

README.md
=> Removing Scrutinizer from the readme

components/catalogs/back/src/Application/Persistence/Catalog/GetCatalogIdsUsingChannelsAsFilterQueryInterface.php, components/catalogs/back/src/Application/Persistence/Catalog/GetCatalogIdsUsingCurrenciesAsFilterQueryInterface.php, components/catalogs/back/src/Infrastructure/EventSubscriber/ChannelRemovalSubscriber.php, components/catalogs/back/src/Infrastructure/Job/DisableCatalogsOnChannelRemovalConstraint.php, components/catalogs/back/src/Infrastructure/Job/DisableCatalogsOnChannelRemovalTasklet.php, components/catalogs/back/src/Infrastructure/Persistence/Catalog/GetCatalogIdsUsingChannelsAsFilterQuery.php, components/catalogs/back/src/Infrastructure/Persistence/Catalog/GetCatalogIdsUsingCurrenciesAsFilterQuery.php, components/catalogs/back/src/Infrastructure/Symfony/Resources/config/jobs.yml, components/catalogs/back/src/Infrastructure/Symfony/Resources/config/services.yml, components/catalogs/back/tests/Integration/Infrastructure/Job/DisableCatalogsOnChannelRemovalConstraintTest.php, components/catalogs/back/tests/Integration/Infrastructure/Job/DisableCatalogsOnChannelRemovalTaskletTest.php, components/catalogs/back/tests/Integration/Infrastructure/Job/DisableCatalogsOnCurrencyDeactivationConstraintTest.php, components/catalogs/back/tests/Integration/Infrastructure/Job/DisableCatalogsOnCurrencyDeactivationTaskletTest.php, components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/GetCatalogIdsUsingChannelsAsFilterQueryTest.php, components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/GetCatalogIdsUsingCurrenciesAsFilterQueryTest.php, components/catalogs/back/tests/Integration/IntegrationTestCase.php, components/catalogs/back/tests/Performance/GetMappedProductsPerformance.php, src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev/jobs.yml, src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/minimal/jobs.yml, upgrades/schema/Version_7_0_20221213091400_add_disable_catalogs_on_channel_removal_job_instance.php, upgrades/test_schema/Version_7_0_20221213091400_add_disable_catalogs_on_channel_removal_job_instance_Integration.php
=> CXP-1360: Channel : Disable catalog if at least 1 FILTER becomes invalid

components/identifier-generator/back/src/Infrastructure/Controller/GetFamiliesController.php, components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/controllers.yml, components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/routing.yml, components/identifier-generator/back/tests/.php_cd.php, components/identifier-generator/back/tests/EndToEnd/ControllerEndToEndTestCase.php, components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/GetFamiliesControllerEndToEnd.php
=> CPM-858: Create a Controller to get the families list

.circleci/workflows/squads/octopus/octopus_catalogs_pull_request.yml
=> OCT-193: Make the test_performance_catalogs_ce step required in the CI

components/catalogs/Makefile, components/catalogs/back/src/Application/Persistence/Catalog/Product/CountProductsSelectedByCriteriaQueryInterface.php, components/catalogs/back/src/Domain/Catalog.php, components/catalogs/back/src/Infrastructure/Controller/Internal/CountProductsSelectedByCriteriaAction.php, components/catalogs/back/src/Infrastructure/Persistence/Catalog/GetCatalogQuery.php, components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/GetCatalogIdsUsingChannelsAsFilterQueryTest.php, components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/GetCatalogIdsUsingCurrenciesAsFilterQueryTest.php, components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/GetCatalogIdsUsingLocalesAsFilterQueryTest.php, components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/Product/GetProductQueryTest.php, components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/UpsertCatalogQueryTest.php, components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductMapping/AttributeSource/AbstractAttributeSourceTest.php, components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSelection/AttributeCriterion/AbstractAttributeCriterionTest.php, components/catalogs/back/tests/Integration/IntegrationTestCase.php, components/catalogs/back/tests/Integration/ServiceAPI/Command/CreateCatalogCommandValidationTest.php, components/catalogs/back/tests/Unit/Application/Handler/CreateCatalogHandlerTest.php, components/catalogs/back/tests/Unit/Infrastructure/Controller/Internal/GetCategoriesActionTest.php, components/catalogs/back/tests/Unit/Infrastructure/Controller/Internal/GetCategoryChildrenActionTest.php, components/catalogs/back/tests/Unit/Infrastructure/Controller/Internal/GetChannelActionTest.php, components/catalogs/back/tests/Unit/Infrastructure/Controller/Internal/GetChannelLocalesActionTest.php, components/catalogs/back/tests/Unit/Infrastructure/Controller/Internal/GetChannelsActionTest.php, components/catalogs/back/tests/Unit/Infrastructure/Controller/Internal/GetFamiliesActionTest.php, components/catalogs/back/tests/Unit/Infrastructure/Controller/Internal/GetLocalesActionTest.php, components/catalogs/back/tests/Unit/Infrastructure/Validation/MaxNumberOfCatalogsPerUserValidatorTest.php
You can check commit by per commit to see the changeset required by phpstan at each level.
I've not been up to level 8 because level 6 has 180 errors.
It detected issues like this one where we passed an array instead of an array of arrays.
=> OCT-192: apply phpstan to the tests directory

.circleci/jobs/features/catalogs/test_back_catalogs_ee.yml, .circleci/workflows/pull_request.yml
=> OCT-195: CI: improve catalog steps in pull_request pipeline

components/identifier-generator/front/src/feature/pages/SimpleDeleteModal.tsx, components/identifier-generator/front/src/feature/pages/__mocks__/DeletePropertyModal.tsx, components/identifier-generator/front/src/feature/pages/__mocks__/SimpleDeleteModal.tsx, components/identifier-generator/front/src/feature/pages/index.ts, components/identifier-generator/front/src/feature/tabs/SelectionTab.tsx, components/identifier-generator/front/src/feature/tabs/__tests__/SelectionTab.test.tsx, components/identifier-generator/front/src/feature/tabs/conditions/EnabledLine.tsx, components/identifier-generator/front/src/feature/tabs/conditions/__mocks__/EnabledLine.tsx, components/identifier-generator/front/src/feature/tabs/conditions/__tests__/EnabledLine.test.tsx, components/identifier-generator/front/src/feature/tabs/structure/PropertiesList.tsx
=> CPM-856: Remove a condition

std-build/package.json
=> RAB-1245: Fix 7.0 for flex team

CHANGELOG-6.0.md, docker/cypress/Dockerfile, src/Akeneo/Channel/Bundle/Doctrine/Query/FindActivatedCurrencies.php, src/Akeneo/Channel/Component/Query/PublicApi/FindActivatedCurrenciesInterface.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/completeness_mask_generators.yml, src/Akeneo/Pim/Enrichment/Component/Product/Completeness/MaskItemGenerator/PriceCollectionMaskItemGenerator.php, tests/back/Acceptance/Channel/InMemoryFindActivatedCurrencies.php, tests/back/Acceptance/Resources/config/pim/queries.yml, tests/back/Acceptance/spec/Channel/InMemoryFindActivatedCurrenciesSpec.php, tests/back/Pim/Enrichment/Integration/Storage/Sql/Completeness/SqlGetCompletenessProductMasksIntegration.php, tests/back/Pim/Enrichment/Integration/Storage/Sql/FindActivatedCurrenciesIntegration.php, tests/back/Pim/Enrichment/Specification/Component/Product/Completeness/MaskItemGenerator/PriceCollectionMaskItemGeneratorSpec.php
=> PIM-10687: Fix high memory consumption when computing completeness for prices with inactive currencies

src/Akeneo/Category/back/Infrastructure/Migration/V20221214GiveNewCategoryAclToUserWithOldCategoryAclZddMigration.php, src/Akeneo/Category/back/Infrastructure/Symfony/DependencyInjection/AkeneoCategoryExtension.php, src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/migration.yml, src/Akeneo/Category/back/tests/Integration/Helper/CategoryTestCase.php, src/Akeneo/Category/back/tests/Integration/Infrastructure/Migration/V20221214GiveNewCategoryAclToUserWithOldCategoryAclZddMigrationIntegration.php
=> GRF-642 give users with category ACLs the new enriched category ACLs

front-packages/akeneo-design-system/src/components/IconCard/IconCard.tsx, front-packages/shared/src/components/Navigation/SubNavigation.tsx, src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml, src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/SettingsIndex.tsx
=> GRF-546: Label can be of Type JSX.Element to be able to add Tag

components/identifier-generator/front/src/feature/components/Styled.tsx, components/identifier-generator/front/src/feature/tabs/SelectionTab.tsx, components/identifier-generator/front/src/feature/tabs/__tests__/SelectionTab.test.tsx, components/identifier-generator/front/src/feature/tabs/conditions/EnabledLine.tsx, components/identifier-generator/front/src/feature/tabs/conditions/FamilyLine.tsx
=> CPM-863: Be able to reorder conditions

components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml, components/identifier-generator/front/src/feature/IdentifierGeneratorApp.tsx, components/identifier-generator/front/src/feature/components/Styled.tsx, components/identifier-generator/front/src/feature/tabs/SelectionTab.tsx, components/identifier-generator/front/src/feature/tabs/StructureTab.tsx, components/identifier-generator/front/src/feature/tabs/__tests__/SelectionTab.test.tsx
=> CPM-857: Add placeholder when there are no conditions

src/Akeneo/Category/back/tests/Integration/Infrastructure/Migration/V20221214GiveNewCategoryAclToUserWithOldCategoryAclZddMigrationIntegration.php
=> fix-migration-integration-test fix test and linter + phpstan errors

tests/legacy/features/Context/Page/Base/ProductEditForm.php
=> CPM-902: Fix findValidationTooltip breaking behat tests

src/Akeneo/Category/back/Infrastructure/Migration/V20221214GiveNewCategoryAclToUserWithOldCategoryAclZddMigration.php, src/Akeneo/Category/back/tests/Integration/Infrastructure/Migration/V20221214GiveNewCategoryAclToUserWithOldCategoryAclZddMigrationIntegration.php, tests/legacy/features/Context/Page/Base/ProductEditForm.php
=> Enriched Category : Fix CI

src/Akeneo/Category/front/src/feature/components/TemplateTitle.tsx, src/Akeneo/Category/front/src/feature/pages/CategoryEditPage.tsx
=> Grf 630 : Fix of non-synchronised header translations when changing the locale in select

.circleci/jobs/build_and_deploy.yml
=> Feature enriched merge master

components/identifier-generator/front/src/feature/components/ScopeSelector.tsx, components/identifier-generator/front/src/feature/components/__tests__/ScopeSelector.test.tsx, components/identifier-generator/front/src/feature/components/index.ts, components/identifier-generator/front/src/feature/controllers/__tests__/Edit.test.tsx, components/identifier-generator/front/src/feature/hooks/__tests__/useGetScopes.test.tsx, components/identifier-generator/front/src/feature/hooks/index.ts, components/identifier-generator/front/src/feature/hooks/useGetScopes.ts, components/identifier-generator/front/src/feature/pages/__tests__/CreateGeneratorPage.test.tsx, components/identifier-generator/front/src/feature/pages/__tests__/CreateOrEditGeneratorPage.test.tsx, components/identifier-generator/front/src/feature/pages/__tests__/EditGeneratorPage.test.tsx, components/identifier-generator/front/src/feature/tabs/SelectionTab.tsx, components/identifier-generator/front/src/feature/tabs/__mocks__/StructureTab.tsx, components/identifier-generator/front/src/feature/tabs/__tests__/StructureTab.test.tsx, components/identifier-generator/front/src/feature/tests/fixtures/initialGenerator.ts, components/identifier-generator/front/src/feature/tests/fixtures/scopes.ts
Scope selector will be used in the simple select condition line
=> CPM-890: Add ScopeSelector and its hook

.circleci/jobs/build_and_deploy.yml, CHANGELOG-6.0.md, src/Akeneo/Channel/back/Infrastructure/Component/Query/PublicApi/FindActivatedCurrenciesInterface.php, src/Akeneo/Channel/back/Infrastructure/Doctrine/Query/FindActivatedCurrencies.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/completeness_mask_generators.yml, src/Akeneo/Pim/Enrichment/Component/Product/Completeness/MaskItemGenerator/PriceCollectionMaskItemGenerator.php, src/Akeneo/Tool/Bundle/ApiBundle/DependencyInjection/Compiler/ContentTypeNegotiatorPass.php, tests/back/Acceptance/Channel/InMemoryFindActivatedCurrencies.php, tests/back/Acceptance/Resources/config/pim/queries.yml, tests/back/Acceptance/spec/Channel/InMemoryFindActivatedCurrenciesSpec.php, tests/back/Pim/Enrichment/Integration/Storage/Sql/Completeness/SqlGetCompletenessProductMasksIntegration.php, tests/back/Pim/Enrichment/Integration/Storage/Sql/FindActivatedCurrenciesIntegration.php, tests/back/Pim/Enrichment/Specification/Component/Product/Completeness/MaskItemGenerator/PriceCollectionMaskItemGeneratorSpec.php, tests/legacy/features/Context/Page/Base/ProductEditForm.php
Pull-up from 6.0 to 7.0.
Chipmunks just merged a fix for Behat in 6.0, I need it in 7.0.
=> Pull-up 6.0 to 7.0

src/Akeneo/Pim/Structure/Family/back/Infrastructure/Query/Sql/SqlFindFamiliesWithLabels.php, src/Akeneo/Pim/Structure/Family/back/Test/Integration/Query/Sql/SqlFindFamiliesWithLabelsIntegration.php
=> CPM-905: Fix get families with family code is a number

src/Akeneo/Category/front/src/feature/components/attributes/buildImageFieldAttribute.tsx, src/Akeneo/Category/front/src/feature/components/file/preview/fullscreen-preview.tsx, src/Akeneo/Category/front/src/feature/components/file/preview/media-preview.tsx, src/Akeneo/Category/front/src/feature/helpers/categoryHelper.ts
Replace the type `Thumbnail` by `Preview` when we call the `getMediaPreviewUrl` in `fullscreen-preview.tsx` component.
=> GRF-652: Fix Image resolution and size when previewing uploaded image in Category Edit Form

.circleci/jobs/build_and_deploy.yml
[[BACKPORT FROM PH-682](https://github.com/akeneo/pim-community-dev/pull/18836)]
The ssh key has been rotated
So the fingerprint changed
Apply the fingerprint changed for the ssh key akeneo-circleci service account
=> [Backport PH-682]: Change ssh key fingerprint for akeneo-circleci

components/identifier-generator/back/src/Infrastructure/Controller/GetAvailableConditionsController.php, components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/controllers.yml, components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/routing.yml, components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/messages.en_US.yml, components/identifier-generator/back/tests/EndToEnd/ControllerEndToEndTestCase.php, components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/GetAvailableConditionsControllerEndToEnd.php, src/Akeneo/Pim/Structure/Component/Query/PublicApi/Attribute/GetGroupedAttributes.php
Create Controller to get the available Conditions
=> CPM 894 : Create Controller to get the available Conditions

components/identifier-generator/front/src/feature/components/Styled.tsx, components/identifier-generator/front/src/feature/components/TabValidationErrors.tsx, components/identifier-generator/front/src/feature/components/__tests__/TabValidationErrors.test.tsx, components/identifier-generator/front/src/feature/components/index.ts, components/identifier-generator/front/src/feature/pages/CreateOrEditGeneratorPage.tsx, components/identifier-generator/front/src/feature/tabs/GeneralPropertiesTab.tsx, components/identifier-generator/front/src/feature/tabs/SelectionTab.tsx, components/identifier-generator/front/src/feature/tabs/StructureTab.tsx, components/identifier-generator/front/src/feature/tabs/__tests__/GeneralProperties.test.tsx, components/identifier-generator/front/src/feature/tabs/__tests__/SelectionTab.test.tsx, components/identifier-generator/front/src/feature/tabs/__tests__/StructureTab.test.tsx, components/identifier-generator/front/src/feature/tabs/conditions/__tests__/EnabledLine.test.tsx
When there is a validation error,
The error message as well as a pill must be displayed in the correct tab.
=> CPM 901 : Add pills on tabs

components/identifier-generator/front/src/feature/components/Styled.tsx, components/identifier-generator/front/src/feature/components/TabValidationErrors.tsx, components/identifier-generator/front/src/feature/components/__tests__/TabValidationErrors.test.tsx, components/identifier-generator/front/src/feature/components/index.ts, components/identifier-generator/front/src/feature/pages/CreateGeneratorPage.tsx, components/identifier-generator/front/src/feature/pages/CreateOrEditGeneratorPage.tsx, components/identifier-generator/front/src/feature/pages/EditGeneratorPage.tsx, components/identifier-generator/front/src/feature/pages/__tests__/CreateGeneratorPage.test.tsx, components/identifier-generator/front/src/feature/pages/__tests__/CreateOrEditGeneratorPage.test.tsx, components/identifier-generator/front/src/feature/pages/__tests__/EditGeneratorPage.test.tsx, components/identifier-generator/front/src/feature/tabs/GeneralPropertiesTab.tsx, components/identifier-generator/front/src/feature/tabs/SelectionTab.tsx, components/identifier-generator/front/src/feature/tabs/StructureTab.tsx, components/identifier-generator/front/src/feature/tabs/__mocks__/StructureTab.tsx, components/identifier-generator/front/src/feature/tabs/__tests__/GeneralProperties.test.tsx, components/identifier-generator/front/src/feature/tabs/__tests__/SelectionTab.test.tsx, components/identifier-generator/front/src/feature/tabs/__tests__/StructureTab.test.tsx, components/identifier-generator/front/src/feature/tabs/conditions/__tests__/EnabledLine.test.tsx, components/identifier-generator/front/src/feature/tabs/structure/PropertiesList.tsx, components/identifier-generator/front/src/feature/tabs/structure/__tests__/PropertiesList.test.tsx, components/identifier-generator/front/src/feature/tabs/structure/edit/FreeTextEdit.tsx, components/identifier-generator/front/src/feature/validators/__tests__/validateDelimiter.test.ts, components/identifier-generator/front/src/feature/validators/__tests__/validateStructure.test.ts, components/identifier-generator/front/src/feature/validators/validateDelimiter.ts, components/identifier-generator/front/src/feature/validators/validateFreeText.ts, components/identifier-generator/front/src/feature/validators/validateIdentifierGenerator.ts, components/identifier-generator/front/src/feature/validators/validateStructure.ts
=> CPM-825: Display errors on structure on save and create

.circleci/detect_structure_changes.sh, .circleci/jobs/build_and_deploy.yml, .circleci/workflows/pull_request.yml, composer.json, composer.lock
We need to do it for CE 7.0 due to pim-community-standard which does not have a composer.lock.
see https://github.com/akeneo/pim-enterprise-dev/pull/16102
=> Fix version of ramsey/uuid

components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml, components/identifier-generator/front/src/feature/components/SimpleSelectOptionsSelector.tsx, components/identifier-generator/front/src/feature/components/__tests__/SimpleSelectOptionsSelector.test.tsx, components/identifier-generator/front/src/feature/hooks/__tests__/useGetSelectOptions.test.tsx, components/identifier-generator/front/src/feature/hooks/useGetFamilies.ts, components/identifier-generator/front/src/feature/hooks/useGetSelectOptions.ts, components/identifier-generator/front/src/feature/models/conditions/simpleSelectOptionCondition.ts, components/identifier-generator/front/src/feature/models/option.ts
This component will be used to filter product selection in the identifier generator
=> CPM-889: Add SimpleSelectOptionsSelector for Simple Select filter

upgrades/schema/Version_7_0_20230110161438_initialize_identifier_generator_acl.php, upgrades/test_schema/Version_7_0_20230110161438_initialize_identifier_generator_acl_Integration.php
=> CPM-832: Create migration to initialize Identifier Generator ACLs

src/Akeneo/Pim/Automation/DataQualityInsights/front/src/application/component/ProductEditForm/TabContent/DataQualityInsights/AttributesGroupsHelper.tsx, src/Akeneo/Pim/Automation/DataQualityInsights/front/src/domain/AttributeGroup.interface.ts, src/Akeneo/Pim/Automation/DataQualityInsights/front/src/domain/index.ts, src/Akeneo/Pim/Structure/Bundle/Controller/InternalApi/AttributeGroupController.php, src/Akeneo/Pim/Structure/Bundle/Query/InternalApi/AttributeGroup/Sql/GetAttributeGroups.php, src/Akeneo/Pim/Structure/Bundle/Resources/config/controllers.yml, src/Akeneo/Pim/Structure/Bundle/Resources/config/queries.yml, src/Akeneo/Pim/Structure/Bundle/Resources/config/routing/internal_api/attribute_group.yml, src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/attribute-groups/AttributeGroupsDataGrid.tsx, src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/attribute-groups/useAttributeGroupsIndexState.ts, src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/models/AttributeGroup.ts
Follows https://github.com/akeneo/pim-community-dev/pull/18901
=> RAB-1273: Refactor attribute group index

components/catalogs/back/src/Application/Handler/GetMappedProductHandler.php, components/catalogs/back/src/Application/Handler/GetMappedProductsHandler.php, components/catalogs/back/src/Application/Persistence/Catalog/Product/GetRawProductQueryInterface.php, components/catalogs/back/src/Application/Persistence/Catalog/Product/GetRawProductsQueryInterface.php, components/catalogs/back/src/Application/Persistence/ProductMappingSchema/GetProductMappingSchemaQueryInterface.php, components/catalogs/back/src/Application/Service/MapProductsInterface.php, components/catalogs/back/src/Application/Service/ProductMapperInterface.php, components/catalogs/back/src/Infrastructure/Controller/Public/GetMappedProductAction.php, components/catalogs/back/src/Infrastructure/Controller/Public/GetProductAction.php, components/catalogs/back/src/Infrastructure/Persistence/Catalog/Product/GetRawProductQuery.php, components/catalogs/back/src/Infrastructure/Persistence/Catalog/Product/GetRawProductsQuery.php, components/catalogs/back/src/Infrastructure/Persistence/ProductMappingSchema/GetProductMappingSchemaQuery.php, components/catalogs/back/src/Infrastructure/Service/MapProducts.php, components/catalogs/back/src/Infrastructure/Service/ProductMapper.php, components/catalogs/back/src/Infrastructure/Symfony/Resources/config/routing/public.yml, components/catalogs/back/src/ServiceAPI/Query/GetMappedProductQuery.php, components/catalogs/back/tests/Acceptance/ApiContext.php, components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/GetMappedProductActionTest.php, components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/GetMappedProductsActionTest.php, components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/GetProductActionTest.php, components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/GetProductsActionTest.php, components/catalogs/features/api.feature
=> CXP-1348: Endpoint GET mapped-product/uuid

components/catalogs/back/src/Application/Persistence/Catalog/GetCatalogIdsUsingLocalesInMappingQueryInterface.php, components/catalogs/back/src/Infrastructure/Job/DisableCatalogsOnLocaleDeactivationTasklet.php, components/catalogs/back/src/Infrastructure/Persistence/Catalog/GetCatalogIdsUsingLocalesInMappingQuery.php, components/catalogs/back/tests/Integration/Infrastructure/Job/DisableCatalogsOnLocaleDeactivationConstraintTest.php, components/catalogs/back/tests/Integration/Infrastructure/Job/DisableCatalogsOnLocaleDeactivationTaskletTest.php, components/catalogs/back/tests/Integration/Infrastructure/Persistence/Catalog/GetCatalogIdsUsingLocalesInMappingQueryTest.php, src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/messages.en_US.yml
=> CXP-1355: Disable Catalogs when Locales are removed

components/catalogs/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml, components/catalogs/front/src/FakePIM.tsx, components/catalogs/front/src/components/ProductMapping/components/SourcePanel.integration.tsx, components/catalogs/front/src/components/ProductMapping/components/SourcePanel.tsx
=> OCT-189 : Show message in parameters section of mapping configuration

components/catalogs/back/src/Infrastructure/Controller/Public/GetMappedProductsAction.php, components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/GetMappedProductsActionTest.php
Update error payload format to be consistent with other catalog product endpoints
=> OCT-200: updated error payload for consitency

src/Akeneo/Pim/Structure/Bundle/Doctrine/ORM/Repository/InternalApi/AttributeRepository.php, src/Akeneo/Pim/Structure/Bundle/Resources/config/datagrid/attribute.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml, src/Oro/Bundle/PimDataGridBundle/Datasource/AttributeDatasource.php, src/Oro/Bundle/PimDataGridBundle/Resources/config/data_sources.yml, src/Oro/Bundle/PimDataGridBundle/Resources/config/mass_actions.yml
=> RAB-1254: Bulk delete attributes

src/Akeneo/Pim/Structure/Bundle/Doctrine/ORM/Repository/InternalApi/AttributeRepository.php, src/Akeneo/Pim/Structure/Bundle/Resources/config/datagrid/attribute.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml, src/Oro/Bundle/PimDataGridBundle/Datasource/AttributeDatasource.php, src/Oro/Bundle/PimDataGridBundle/Resources/config/data_sources.yml, src/Oro/Bundle/PimDataGridBundle/Resources/config/mass_actions.yml
=> RAB-1254: Init mass action

CHANGELOG.md, src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Completeness/SqlGetProductCompletenesses.php
=> Feature enriched categories merge master

components/catalogs/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml, components/catalogs/front/src/components/ProductMapping/components/SelectAttributeDropdown.tsx, components/catalogs/front/src/components/ProductMapping/components/SourcePanel.tsx
=> OCT-202: add placeholder on the source selector in mapping

components/catalogs/back/src/Application/Persistence/Catalog/GetAttributeTypeByCodesQueryInterface.php, components/catalogs/back/src/Application/Service/AttributeValueExtractor/AttributeValueExtractorInterface.php, components/catalogs/back/src/Application/Service/AttributeValueExtractor/AttributeValueExtractorNotFoundException.php, components/catalogs/back/src/Application/Service/AttributeValueExtractor/AttributeValueExtractorRegistry.php, components/catalogs/back/src/Application/Service/AttributeValueExtractor/SelectExtractor.php, components/catalogs/back/src/Application/Service/AttributeValueExtractor/TextExtractor.php, components/catalogs/back/src/Domain/Catalog.php, components/catalogs/back/src/Infrastructure/Persistence/Catalog/GetAttributeTypeByCodesQuery.php, components/catalogs/back/src/Infrastructure/Service/ProductMapper.php, components/catalogs/back/src/Infrastructure/Symfony/Resources/config/services.yml, components/catalogs/back/src/Infrastructure/Validation/ProductMapping/IsValidLocale.php, components/catalogs/back/src/Infrastructure/Validation/ProductMapping/IsValidLocaleValidator.php, components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/GetMappedProductActionTest.php, components/catalogs/back/tests/Integration/Infrastructure/Controller/Public/GetMappedProductsActionTest.php, components/catalogs/back/tests/Integration/Infrastructure/Service/AttributeValueExtractor/SelectExtractorTest.php, components/catalogs/back/tests/Integration/Infrastructure/Service/AttributeValueExtractor/TextExtractorTest.php
=> CXP-1373: Add a registry to handle the attribute value extraction

CHANGELOG.md, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/Structure/GetAllAttributeGroupsActivationQuery.php, src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/attribute-groups/useAttributeGroupsIndexState.ts
=> PIM-10779: Lowercase on get attribute group code for dqi activation

src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/Category/OnDelete/RemoveCategoryFilterInJobInstanceSubscriber.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/event_subscribers.yml
=> PIM-10759: Tailored exports fail after the deletion of a category tree

src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/Client/GuzzleWebhookClient.php
=> OCT-198: fix GuzzleWebhookClient

src/Akeneo/Category/front/src/feature/components/datagrids/CategoryTreeDataGrid.tsx
=> GRF-676: Category Tree linked to 100+ products notification changed from INFO to ERROR

CHANGELOG.md, src/Akeneo/Pim/Enrichment/Component/Product/Updater/ProductModelUpdater.php, tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/PartialUpdateProductModelEndToEnd.php
=> PIM-10785: Fix case-insensitive patch product model

components/identifier-generator/back/src/Application/Exception/UnableToGenerateAutoNumberException.php, components/identifier-generator/back/src/Application/Generate/GenerateIdentifierCommand.php, components/identifier-generator/back/src/Application/Generate/GenerateIdentifierHandler.php, components/identifier-generator/back/src/Application/Generate/Property/GenerateAutoNumberHandler.php, components/identifier-generator/back/src/Application/Generate/Property/GenerateFreeTextHandler.php, components/identifier-generator/back/src/Application/Generate/Property/GeneratePropertyHandlerInterface.php, components/identifier-generator/back/src/Application/Validation/Error.php, components/identifier-generator/back/src/Domain/Model/IdentifierGeneratorId.php, components/identifier-generator/back/src/Domain/Query/GetNextIdentifierQuery.php, components/identifier-generator/back/src/Infrastructure/Query/SqlGetNextIdentifierQuery.php, components/identifier-generator/back/src/Infrastructure/Query/SqlGetSequencedNextIdentifierQuery.php, components/identifier-generator/back/src/Infrastructure/Symfony/Install/InstallerSubscriber.php, components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/persistence.yml, components/identifier-generator/back/tests/EndToEnd/Infrastructure/EndToEndTestCase.php, components/identifier-generator/back/tests/EndToEnd/Infrastructure/Subscriber/SetIdentifiersSubscriberEndToEnd.php, components/identifier-generator/back/tests/Specification/Application/Generate/GenerateIdentifierHandlerSpec.php, components/identifier-generator/back/tests/Specification/Application/Generate/Property/GenerateAutoNumberHandlerSpec.php, components/identifier-generator/back/tests/Specification/Application/Generate/Property/GenerateFreeTextHandlerSpec.php, upgrades/schema/Version_8_0_20230110131126_update_target_column_for_identifier_generators.php, upgrades/schema/Version_8_0_20230120154546_add_identifier_generator_sequence_table.php, upgrades/test_schema/Version_7_0_20220927080024_add_identifier_generator_table_Integration.php, upgrades/test_schema/Version_8_0_20230110131126_update_target_column_for_identifier_generators_Integration.php, upgrades/test_schema/Version_8_0_20230120154546_add_identifier_generator_sequence_table_Integration.php
=> CPM-926: Add Sequence

components/catalogs/back/src/Infrastructure/Symfony/Resources/meta-schemas/product-0.0.4.json
=> OCT-fix-meta-schema-version: fix a typo

components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml, components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/validators.en_US.yml, components/identifier-generator/back/tests/features/createIdentifierGenerator.feature, components/identifier-generator/back/tests/features/updateIdentifierGenerator.feature, components/identifier-generator/front/src/feature/components/Styled.tsx, components/identifier-generator/front/src/feature/tabs/structure/DelimiterEdit.tsx, components/identifier-generator/front/src/feature/tabs/structure/line/FreeTextLine.tsx, components/identifier-generator/front/src/feature/tabs/structure/preview/AutoNumberPreview.tsx
Please read it commit by commit, the name of the commit is the matching card.
=> CPM-900 + CPM-919 + CPM-903 + CPM-872 + CPM-906 = CPM-4500

components/identifier-generator/back/src/Domain/Model/Property/AutoNumber.php, components/identifier-generator/back/src/Domain/Model/Property/FamilyProperty.php, components/identifier-generator/back/src/Domain/Model/Property/FreeText.php, components/identifier-generator/back/src/Domain/Model/Property/Process.php, components/identifier-generator/back/src/Domain/Model/Property/PropertyInterface.php, components/identifier-generator/back/src/Domain/Model/Structure.php, components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/validation/create_generator_command.yml, components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/validation/update_generator_command.yml, components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/validators.yml, components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/validators.en_US.yml, components/identifier-generator/back/src/Infrastructure/Validation/FamilyPropertyShouldBeValid.php, components/identifier-generator/back/src/Infrastructure/Validation/FamilyPropertyShouldBeValidValidator.php, components/identifier-generator/back/tests/Acceptance/Context/CreateIdentifierGeneratorContext.php, components/identifier-generator/back/tests/Acceptance/Context/UpdateIdentifierGeneratorContext.php, components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/CreateIdentifierGeneratorControllerEndToEnd.php, components/identifier-generator/back/tests/Specification/Domain/Model/Property/FamilyPropertySpec.php, components/identifier-generator/back/tests/Specification/Domain/Model/Property/ProcessSpec.php, components/identifier-generator/back/tests/Specification/Domain/Model/StructureSpec.php, components/identifier-generator/back/tests/Specification/Infrastructure/Validation/FamilyPropertyShouldBeValidValidatorSpec.php, components/identifier-generator/back/tests/features/createIdentifierGenerator.feature, components/identifier-generator/back/tests/features/updateIdentifierGenerator.feature
Allow create/update with Family Generation
- Add validation for structure property
- Add tests
=> CPM-907 : Allow create/update with Family Generation

src/Akeneo/Pim/Enrichment/Product/back/API/Command/UserIntent/SetTableValue.php, src/Akeneo/Pim/Enrichment/Product/back/Test/Specification/API/Command/UserIntent/SetTableValueSpec.php
=> CPM-874: Fix case where table column code is an int

components/identifier-generator/back/src/Infrastructure/Controller/CreateIdentifierGeneratorController.php, components/identifier-generator/back/src/Infrastructure/Controller/DeleteIdentifierGeneratorController.php, components/identifier-generator/back/src/Infrastructure/Controller/GetAttributeOptionsController.php, components/identifier-generator/back/src/Infrastructure/Controller/GetAvailableConditionsController.php, components/identifier-generator/back/src/Infrastructure/Controller/GetFamiliesController.php, components/identifier-generator/back/src/Infrastructure/Controller/GetIdentifierAttributesController.php, components/identifier-generator/back/src/Infrastructure/Controller/GetIdentifierGeneratorController.php, components/identifier-generator/back/src/Infrastructure/Controller/ListIdentifierGeneratorController.php, components/identifier-generator/back/src/Infrastructure/Controller/UpdateIdentifierGeneratorController.php, components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/controllers.yml, components/identifier-generator/back/tests/EndToEnd/ControllerEndToEndTestCase.php, components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/CreateIdentifierGeneratorControllerEndToEnd.php, components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/DeleteIdentifierGeneratorControllerEndToEnd.php, components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/GetAttributeOptionsControllerEndToEnd.php, components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/GetAvailableConditionsControllerEndToEnd.php, components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/GetFamiliesControllerEndToEnd.php, components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/GetIdentifierAttributesControllerEndToEnd.php, components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/GetIdentifierGeneratorControllerEndToEnd.php, components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/ListIdentifierGeneratorControllerEndToEnd.php, components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/UpdateIdentifierGeneratorControllerEndToEnd.php
=> CPM-930: Apply permissions on backend endpoints

components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml, components/identifier-generator/front/src/feature/pages/ListPage.tsx
update wording for identifier generator information page
=> CPM-866: update wording

components/catalogs/back/src/Infrastructure/Symfony/Resources/config/routing/internal.yml, components/catalogs/back/tests/Integration/Infrastructure/Controller/Internal/GetAttributesByTargetTypeAndTargetFormatActionTest.php, components/catalogs/front/src/components/ProductMapping/ProductMapping.integration.tsx, components/catalogs/front/src/components/ProductMapping/components/SourcePanel.integration.tsx, components/catalogs/front/src/components/ProductMapping/hooks/useInfiniteSourceAttributes.unit.ts
=> OCT: rename internal endpoint to be more consistent

components/catalogs/back/src/Application/Mapping/TargetTypeConverter.php, components/catalogs/back/src/Application/Mapping/ValueExtractor/Extractor/Boolean/BooleanFromBooleanAttributeValueExtractor.php, components/catalogs/back/src/Application/Mapping/ValueExtractor/Extractor/BooleanValueExtractorInterface.php, components/catalogs/back/src/Application/Mapping/ValueExtractor/Extractor/ValueExtractorInterface.php, components/catalogs/back/src/Infrastructure/Command/CatalogFixtureCommand.php, components/catalogs/back/src/Infrastructure/Controller/Internal/GetAttributesByTargetTypeAndTargetFormatAction.php, components/catalogs/back/src/Infrastructure/Symfony/Resources/config/services.yml, components/catalogs/back/src/Infrastructure/Validation/CatalogProductMappingValidator.php, components/catalogs/back/src/Infrastructure/Validation/ProductMapping/AttributeSource/AttributeBooleanSource.php, components/catalogs/back/src/Infrastructure/Validation/ProductMapping/ProductMappingRespectsSchemaValidator.php, components/catalogs/back/tests/Acceptance/ApiContext.php, components/catalogs/back/tests/Integration/Application/Mapping/ValueExtractor/Extractor/Boolean/BooleanFromBooleanAttributeValueExtractorTest.php, components/catalogs/back/tests/Integration/Application/Mapping/ValueExtractor/Extractor/Number/NumberFromNumberAttributeValueExtractorTest.php, components/catalogs/back/tests/Integration/Application/Mapping/ValueExtractor/Extractor/String/StringFromNumberAttributeValueExtractorTest.php, components/catalogs/back/tests/Integration/Application/Mapping/ValueExtractor/Extractor/String/StringFromSimpleSelectAttributeValueExtractorTest.php, components/catalogs/back/tests/Integration/Application/Mapping/ValueExtractor/Extractor/String/StringFromTextAttributeValueExtractorTest.php, components/catalogs/back/tests/Integration/Application/Mapping/ValueExtractor/Extractor/String/StringFromTextareaAttributeValueExtractorTest.php, components/catalogs/back/tests/Integration/Application/Mapping/ValueExtractor/Extractor/ValueExtractorTestCase.php, components/catalogs/back/tests/Integration/Application/Mapping/ValueExtractor/Registry/ValueExtractorRegistryTest.php, components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductMapping/AttributeSource/AttributeBooleanSourceTest.php, components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductMapping/ProductMappingRespectsSchemaTest.php, components/catalogs/back/tests/Unit/Application/Mapping/TargetTypeConverterTest.php, components/catalogs/back/tests/Unit/Service/TargetTypeConverterTest.php
=> CXP-1375: Map boolean attributes (boolean)

src/Akeneo/Category/back/Infrastructure/EventSubscriber/InitCategoryDbSchemaSubscriber.php, upgrades/schema/Version_8_0_20230131155436_add_column_is_deactivated_on_template.php, upgrades/test_schema/Version_8_0_20230131155436_add_column_is_deactivated_on_template_Integration.php
No data for now in the client instances in this table, no risk to add a column.
=> GRF-700: Migration with new is_deactivated field on template table

CHANGELOG.md, src/Akeneo/Pim/Structure/Component/Validator/Constraints/FamilyRequirementsValidator.php, tests/back/Pim/Structure/Specification/Component/Validator/Constraints/FamilyRequirementsValidatorSpec.php
Add filter on required for family's attributeRequirements
=> PIM-10808: Fix Error message on the family modification when an attribute is as required=0

components/catalogs/back/src/Application/Mapping/TargetTypeConverter.php, components/catalogs/back/src/Application/Mapping/ValueExtractor/Extractor/String/StringFromIdentifierAttributeValueExtractor.php, components/catalogs/back/src/Application/Mapping/ValueExtractor/Extractor/ValueExtractorInterface.php, components/catalogs/back/src/Infrastructure/Symfony/Resources/config/services.yml, components/catalogs/back/src/Infrastructure/Validation/CatalogProductMappingValidator.php, components/catalogs/back/src/Infrastructure/Validation/ProductMapping/AttributeSource/AttributeIdentifierSource.php, components/catalogs/back/tests/Acceptance/ApiContext.php, components/catalogs/back/tests/Integration/Application/Mapping/ValueExtractor/Extractor/String/StringFromIdentifierAttributeValueExtractorTest.php, components/catalogs/back/tests/Integration/Application/Mapping/ValueExtractor/Registry/ValueExtractorRegistryTest.php, components/catalogs/back/tests/Integration/Infrastructure/Controller/Internal/GetAttributesByTargetTypeAndTargetFormatActionTest.php, components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductMapping/AttributeSource/AttributeIdentifierSourceTest.php, components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductMapping/ProductMappingRespectsSchemaTest.php, components/catalogs/back/tests/Unit/Application/Mapping/TargetTypeConverterTest.php, components/catalogs/front/src/components/ProductMapping/ProductMapping.integration.tsx, components/catalogs/front/src/components/ProductMapping/hooks/useInfiniteSourceAttributes.ts
=> CXP-1372: Mapping - Accept an identifier as a source for a string attribute

src/Akeneo/Category/front/src/feature/hooks/useEditCategoryForm.ts
Create locale code json key when it doesn't exist.
=> GRF-696: Fix Edit the Category label of a Category with the default label doesn't work

CHANGELOG-6.0.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/field/wysiwyg-field.js
=> PIM-10818: Backport PIM-10802 on 6.0

src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/save.js, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/save.js, src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_US.yml
=> PIM-10786 : Create error message when session expire

components/catalogs/back/src/Application/Mapping/TargetTypeConverter.php, components/catalogs/back/src/Application/Mapping/ValueExtractor/Extractor/StringDateTime/StringDateTimeFromDateAttributeValueExtractor.php, components/catalogs/back/src/Infrastructure/Command/CatalogFixtureCommand.php, components/catalogs/back/src/Infrastructure/Validation/CatalogProductMappingValidator.php, components/catalogs/back/src/Infrastructure/Validation/ProductMapping/AttributeSource/AttributeDateSource.php, components/catalogs/back/tests/Integration/Application/Mapping/ValueExtractor/Extractor/StringDateTime/StringDateTimeFromDateAttributeValueExtractorTest.php, components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductMapping/AttributeSource/AttributeDateSourceTest.php, components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductMapping/ProductMappingRespectsSchemaTest.php, components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductSchema/valid/0.0.4.json, components/catalogs/back/tests/Unit/Application/Mapping/TargetTypeConverterTest.php
=> CXP-1402: mapping - accept date as source for string-datetime target

components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/validation/create_generator_command.yml, components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/validation/update_generator_command.yml, components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/validators.yml, components/identifier-generator/back/src/Infrastructure/Validation/AttributeShouldHaveTypes.php, components/identifier-generator/back/src/Infrastructure/Validation/AttributeShouldHaveTypesValidator.php, components/identifier-generator/back/src/Infrastructure/Validation/SimpleOrMultiSelectShouldBeValid.php, components/identifier-generator/back/src/Infrastructure/Validation/SimpleOrMultiSelectShouldBeValidValidator.php, components/identifier-generator/back/tests/Acceptance/Context/CreateIdentifierGeneratorContext.php, components/identifier-generator/back/tests/Acceptance/Context/UpdateIdentifierGeneratorContext.php, components/identifier-generator/back/tests/Specification/Infrastructure/Validation/AttributeShouldHaveTypesValidatorSpec.php, components/identifier-generator/back/tests/Specification/Infrastructure/Validation/SimpleOrMultiSelectShouldBeValidValidatorSpec.php, components/identifier-generator/back/tests/features/createIdentifierGenerator.feature, components/identifier-generator/back/tests/features/updateIdentifierGenerator.feature
Be able to create/update a selection by MultiSelectOption
- Update validator
- Update AttributeShouldHaveType to make it compatible with a list of types
- add tests
=> CPM-938: update validator to be compatible with multi_select type

components/catalogs/back/src/Application/Mapping/TargetTypeConverter.php, components/catalogs/back/src/Application/Mapping/ValueExtractor/Extractor/Number/NumberFromNumberAttributeValueExtractor.php, components/catalogs/back/src/Infrastructure/Command/CatalogFixtureCommand.php, components/catalogs/back/src/Infrastructure/Validation/CatalogProductMappingValidator.php, components/catalogs/back/src/Infrastructure/Validation/ProductMapping/AttributeSource/AttributeNumberSource.php, components/catalogs/back/tests/Integration/Application/Mapping/ValueExtractor/Extractor/Number/NumberFromNumberAttributeValueExtractorTest.php, components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductMapping/AttributeSource/AttributeNumberSourceTest.php, components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductMapping/ProductMappingRespectsSchemaTest.php, components/catalogs/back/tests/Unit/Application/Mapping/TargetTypeConverterTest.php
=> CXP-1376: mapping - accept number as target with number source

components/identifier-generator/back/src/Infrastructure/Controller/GetAvailableConditionsController.php, components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/GetAvailableConditionsControllerEndToEnd.php, components/identifier-generator/front/src/feature/models/conditions/conditions.ts, components/identifier-generator/front/src/feature/models/conditions/simpleOrMultiSelectCondition.ts, components/identifier-generator/front/src/feature/models/index.ts, components/identifier-generator/front/src/feature/tabs/SelectionTab.tsx, components/identifier-generator/front/src/feature/tabs/__tests__/SelectionTab.test.tsx, components/identifier-generator/front/src/feature/tabs/conditions/SimpleOrMultiSelectLine.tsx, components/identifier-generator/front/src/feature/tabs/conditions/__mocks__/SimpleOrMultiSelectLine.tsx, components/identifier-generator/front/src/feature/tabs/conditions/__mocks__/SimpleSelectLine.tsx, components/identifier-generator/front/src/feature/tabs/conditions/__tests__/SimpleSelectLine.test.tsx, components/identifier-generator/front/src/feature/validators/__tests__/validateConditions.test.ts, components/identifier-generator/front/src/feature/validators/__tests__/validateSimpleSelect.test.ts, components/identifier-generator/front/src/feature/validators/validateConditions.ts, components/identifier-generator/front/src/feature/validators/validateSimpleOrMultiSelect.ts
Update SimpleSelectLine to SimpleOrMultiSelectLine
=> CPM-941: front multiselect line

components/catalogs/back/src/Application/Mapping/ValueExtractor/Extractor/Boolean/BooleanFromBooleanAttributeValueExtractor.php, components/catalogs/back/src/Infrastructure/Validation/ProductMapping/AttributeSource/AttributeSimpleSelectSource.php, components/catalogs/back/src/Infrastructure/Validation/ProductMapping/AttributeSource/AttributeTextSource.php, components/catalogs/back/src/Infrastructure/Validation/ProductMapping/AttributeSource/AttributeTextareaSource.php, components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductMapping/AttributeSource/AttributeBooleanSourceTest.php, components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductMapping/AttributeSource/AttributeDateSourceTest.php, components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductMapping/AttributeSource/AttributeNumberSourceTest.php, components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductMapping/AttributeSource/AttributeSimpleSelectSourceTest.php, components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductMapping/AttributeSource/AttributeTextSourceTest.php, components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductMapping/AttributeSource/AttributeTextareaSourceTest.php
=> CXP-improve-tests: make validation integration tests more complete

src/Akeneo/Pim/Enrichment/Component/Product/Localization/Presenter/MetricPresenter.php
see https://akeneo.atlassian.net/browse/RAC-1287
=> RAC-1287: Improve logging in MetricPresenter

tests/legacy/features/pim/enrichment/product/mass-action/quick-export/quick_export_with_localized_data.feature
Translations have been updated (https://github.com/akeneo/pim-community-dev/commit/92d5b5e09f6bff173e310accb284225a9b62cdd0)
We have to fix e2e tests.
=> CPM-953: fix fr_FR label for UUID

front-packages/akeneo-design-system/src/components/Input/ColorInput/ColorInput.tsx
=> RAB-1270: Fix content box for color input error

components/identifier-generator/back/src/Infrastructure/Controller/GetAvailableConditionsController.php, components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/controllers.yml, components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml, components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/GetAvailableConditionsControllerEndToEnd.php, components/identifier-generator/front/src/feature/tabs/conditions/SimpleSelectLine.tsx, components/identifier-generator/front/src/feature/tabs/conditions/__tests__/SimpleSelectLine.test.tsx, components/identifier-generator/front/src/setupTests.tsx
=> CPM-934: Do not display attributes if user has no permissions to list attributes

src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/save.js, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/save.js, src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_US.yml
=> [Pullup master] PIM-10786: Create error message when session expire

src/Akeneo/Category/back/Api/Command/UserIntents/SetRichText.php, src/Akeneo/Category/back/Api/Command/UserIntents/SetText.php, src/Akeneo/Category/back/Api/Command/UserIntents/SetTextArea.php, src/Akeneo/Category/back/Api/Command/UserIntents/ValueUserIntent.php, src/Akeneo/Category/back/Domain/UserIntent/Factory/ValueUserIntentFactory.php, src/Akeneo/Category/back/Domain/ValueObject/Attribute/Value/TextAreaValue.php, src/Akeneo/Category/back/Domain/ValueObject/Attribute/Value/TextValue.php, src/Akeneo/Category/back/Infrastructure/Storage/Save/Query/UpsertCategoryBaseSql.php, src/Akeneo/Category/back/Infrastructure/Validation/ValueUserIntentsShouldBeUniqueValidator.php, src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Save/Query/UpsertCategoryBaseSqlIntegration.php, src/Akeneo/Category/back/tests/Specification/Domain/UserIntent/Factory/ValueUserIntentFactorySpec.php, src/Akeneo/Category/back/tests/Specification/Domain/ValueObject/Attribute/Value/TextAreaValueSpec.php, src/Akeneo/Category/back/tests/Specification/Domain/ValueObject/Attribute/Value/TextValueSpec.php
- Fix REST API to not return empty attribute values
=> GRF-724: Fix attribute value to be clearable & remove persistence of null value

src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Controller/Internal/GetAppActivateUrlAction.php, src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Controller/Internal/GetOpenAppUrlAction.php, src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Controller/Public/RedirectToEditConnectedAppAction.php, src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/acl.yml, src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml, src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/messages.en_US.yml, src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Apps/Controller/Internal/GetAppActivateUrlActionSpec.php, src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Apps/Controller/Internal/GetOpenAppUrlActionSpec.php, src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Apps/Controller/Public/RedirectToEditConnectedAppActionSpec.php, src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApps/ConnectedAppCard.tsx, src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApps/ConnectedTestAppList.tsx, src/Akeneo/Connectivity/Connection/front/src/connect/components/Marketplace.tsx, src/Akeneo/Connectivity/Connection/front/src/connect/components/TestApp/TestAppCard.tsx, src/Akeneo/Connectivity/Connection/front/src/connect/components/TestApp/TestAppList.tsx, src/Akeneo/Connectivity/Connection/front/src/connect/hooks/use-fetch-test-apps.ts, src/Akeneo/Connectivity/Connection/front/src/connect/pages/MarketplacePage.tsx, src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApps/ConnectedAppCard.test.tsx, src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApps/ConnectedTestAppList.test.tsx, src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/TestApp/TestAppCard.test.tsx, src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/TestApp/TestAppList.test.tsx, src/Akeneo/Connectivity/Connection/front/tests/src/connect/pages/MarketplacePage.test.tsx, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/acl_groups.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/messages.en_US.yml
=> CXP-1424: Add the custom apps ACLs

components/identifier-generator/back/src/Infrastructure/Symfony/Install/InstallerSubscriber.php, upgrades/schema/Version_8_0_20230131125133_create_identifier_generator_family_nomenclature_tables.php, upgrades/test_schema/Version_8_0_20230131125133_create_identifier_generator_family_nomenclature_tables_Integration.php
Already GTMed, fausse manip
https://github.com/akeneo/pim-community-dev/pull/19006
=> CPM-942: Add tables for family nomenclature

components/identifier-generator/back/src/Application/Get/GetNomenclatureCommand.php, components/identifier-generator/back/src/Application/Get/GetNomenclatureHandler.php, components/identifier-generator/back/src/Domain/Model/NomenclatureDefinition.php, components/identifier-generator/back/src/Domain/Repository/NomenclatureRepository.php, components/identifier-generator/back/src/Infrastructure/Controller/GetNomenclatureController.php, components/identifier-generator/back/src/Infrastructure/Repository/InMemoryNomenclatureRepository.php, components/identifier-generator/back/src/Infrastructure/Repository/SqlNomenclatureRepository.php, components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/command_handlers.yml, components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/controllers.yml, components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/routing.yml, components/identifier-generator/back/tests/Acceptance/Context/UpdateFamilyNomenclatureContext.php, components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/GetFamilyNomenclatureControllerEndToEnd.php, components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/UpdateFamilyNomenclatureControllerEndToEnd.php
Add GetFamilyNomenclatureController
=> CPM-943: Add get family nomenclature controller and handler

components/identifier-generator/back/src/Application/Generate/GenerateIdentifierHandler.php, components/identifier-generator/back/src/Domain/Model/IdentifierGenerator.php, components/identifier-generator/back/src/Infrastructure/Repository/SqlIdentifierGeneratorRepository.php, components/identifier-generator/back/tests/Specification/Domain/Model/IdentifierGeneratorSpec.php
=> CPM 929: Set delimiter not nullable

components/identifier-generator/back/src/Infrastructure/ZddMigrations/V20221205153905FillIdentifierPrefixesZddMigration.php
=> Fix unknown method from ZDD migration

composer.json, composer.lock
=> Fix php-http/discovery version in order to avoid error about post-install script

src/Akeneo/Category/back/Infrastructure/Migration/V20221214GiveNewCategoryAclToUserWithOldCategoryAclZddMigration.php, src/Akeneo/Category/back/tests/.php_cd.php
- added coupling exclusion rule
- fixed zdd migration to match updated interface
=> GRF: fix feature branch

src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Controller/Internal/GetConnectedAppAction.php, src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Apps/Controller/Internal/GetConnectedAppActionSpec.php, src/Akeneo/Connectivity/Connection/front/src/connect/pages/MarketplacePage.tsx
=> CXP-1424: fix acls

src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/AmazonS3StorageConfigurator.test.tsx, src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/AmazonS3StorageConfigurator.tsx, src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/CheckStorageConnection.test.tsx, src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/CheckStorageConnection.tsx, src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/GoogleCloudStorageConfigurator.test.tsx, src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/GoogleCloudStorageConfigurator.tsx, src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/LocalStorageConfigurator.test.tsx, src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/LocalStorageConfigurator.tsx, src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/MicrosoftAzureStorageConfigurator.test.tsx, src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/MicrosoftAzureStorageConfigurator.tsx, src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/SftpStorageConfigurator.test.tsx, src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/SftpStorageConfigurator.tsx, src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/model.test.ts, src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageConfigurator/model.ts, src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageForm.test.tsx, src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/StorageForm.tsx, src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/components/index.ts, src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/hooks/index.ts, src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/hooks/useCheckStorageConnection.test.ts, src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/hooks/useCheckStorageConnection.ts, src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/index.ts, src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/models/Storage.test.ts, src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/models/Storage.ts, src/Akeneo/Platform/Bundle/ImportExportBundle/front/src/models/index.ts, src/Akeneo/Platform/Job/front/process-tracker/src/feature/components/JobExecutionDetail/summary/SummaryTable.tsx
- Mutualize CheckStorageConnection component
- Add title on step name in process tracker
- Refactor tests, mock hooks instead of fetch
- Move Storage model in models directory instead of components
=> RAB-1236: Create CheckStorage component & refactor tests

src/Akeneo/Category/back/ServiceApi/ExternalApiCategory.php, src/Akeneo/Category/back/tests/Integration/ServiceApi/ExternalApiCategoryIntegration.php
=> GRF-736: Incorrect API return format when no enriched attribute values exist

src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml, src/Akeneo/Category/front/src/feature/components/DiscoverEnrichedCategoriesInformationHelper.tsx
Add Help center link to the Enriched Category helper.
:warning: Link temporarely redirect to the Help center homepage.
=> GRF-638: add helpcenter link

src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
=> GRF-638: fix helper wording

CHANGELOG.md, src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/EventSubscriber/UpdateJobExecutionStorageSummarySubscriber.php, src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/StorageClient/TransferFilesToStorage.php
In this PR, I added more user friendly message to the user when an error occurred during transfer file to remote storage
=> PIM-10825: Improve message to the end user when remote storage does not work

CHANGELOG-6.0.md, src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/ProductController.php, src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/ProductModelController.php, src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Completeness/SqlSaveProductCompletenesses.php, src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/Validator/ValidateProperties.php, src/Akeneo/Pim/Enrichment/Component/Product/Job/RemoveCompletenessForChannelAndLocaleTasklet.php, tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/ErrorListProductEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/ErrorListProductWithUuidEndToEnd.php, tests/back/Pim/Enrichment/Integration/Storage/Sql/Completeness/SaveProductCompletenessesIntegration.php
=> PIM-10824: Pull up 6.0 into 7.0

src/Akeneo/Connectivity/Connection/front/src/connect/components/Marketplace.tsx, src/Akeneo/Connectivity/Connection/front/src/connect/components/TestApp/TestAppList.tsx, src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/Marketplace.test.tsx, src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/TestApp/TestAppList.test.tsx
=> CXP-1420: Limit the number of custom apps (connected)

src/Akeneo/Pim/Structure/Bundle/Query/InternalApi/Attribute/SqlCountAttributes.php, src/Akeneo/Pim/Structure/Bundle/Resources/config/queries.yml, src/Akeneo/Pim/Structure/Component/Query/InternalApi/CountAttributes.php, src/Oro/Bundle/PimDataGridBundle/Adapter/ItemsCounter.php, src/Oro/Bundle/PimDataGridBundle/Resources/config/adapters.yml, src/Oro/Bundle/PimDataGridBundle/spec/Adapter/ItemsCounterSpec.php, tests/back/Pim/Structure/Integration/Attribute/Query/SqlCountAttributesIntegration.php
I created a query to count attribute by filters built by the mass edit controller.
=> RAB-1260: Implement items count in backend

CHANGELOG-6.0.md, CHANGELOG-7.0.md, components/catalogs/front/jest.config.js, front-packages/shared/jest.config.js, src/Akeneo/Connectivity/Connection/front/jest.config.js, src/Akeneo/Connectivity/Connection/workspaces/permission-form/jest.config.js, src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/ProductController.php, src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/ProductModelController.php, src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Completeness/SqlSaveProductCompletenesses.php, src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/Validator/ValidateProperties.php, src/Akeneo/Pim/Enrichment/Component/Product/Job/RemoveCompletenessForChannelAndLocaleTasklet.php, src/Akeneo/Platform/Bundle/ImportExportBundle/front/jest.config.json, tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/ErrorListProductEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/ErrorListProductWithUuidEndToEnd.php, tests/back/Pim/Enrichment/Integration/Storage/Sql/Completeness/SaveProductCompletenessesIntegration.php
=> PIM-10824: Pull up 7.0 into master

src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/requirejs.yml, src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml, src/Akeneo/Connectivity/Connection/front/src/connect/hooks/use-delete-custom-app.ts, src/Akeneo/Connectivity/Connection/front/src/connect/pages/DeleteCustomAppPromptPage.tsx, src/Akeneo/Connectivity/Connection/front/src/connect/pages/DeleteTestAppPromptPage.tsx, src/Akeneo/Connectivity/Connection/front/src/infrastructure/CustomApps.tsx, src/Akeneo/Connectivity/Connection/front/tests/src/connect/hooks/use-delete-custom-app.test.tsx, src/Akeneo/Connectivity/Connection/front/tests/src/connect/pages/DeleteCustomAppPromptPage.test.tsx
Updated and tested custom app deletion prompt
=> CXP-1419 Delete custom app

src/Akeneo/Category/back/Application/Registry/FindCategoryAdditionalProperties.php, src/Akeneo/Category/back/Domain/Query/GetCategoryByIds.php, src/Akeneo/Category/back/Domain/ValueObject/Version/CategoryVersion.php, src/Akeneo/Category/back/Infrastructure/Registry/FindCategoryAdditionalPropertiesRegistry.php, src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetCategoryByIdsSql.php, src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/queries.yml, src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetCategoryByIdsSqlIntegration.php, src/Akeneo/Category/back/tests/Specification/Infrastructure/Registry/FindCategoryAdditionalPropertiesRegistrySpec.php
=> GRF-727 : Get a list of category by their ids

components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml, components/identifier-generator/front/src/feature/pages/ListPage.tsx, components/identifier-generator/front/src/feature/pages/__tests__/ListPage.test.tsx
=> CPM-910: Display a specific error message for identifier generator list if readonly

src/Akeneo/Pim/Enrichment/Bundle/Command/MigrateToUuid/MigrateToUuidSetNotNullableUuidColumns.php, src/Akeneo/Tool/Component/Batch/Event/ErrorHandlerConfigurationListener.php, src/Akeneo/Tool/Component/Connector/Encoder/CsvEncoder.php, upgrades/schema/Version_7_0_20220404075823_add_uuid_columns.php, upgrades/schema/Version_7_0_20220415090329_add_uuid_column_for_comment.php, upgrades/schema/Version_7_0_20230213153500_remove_index_on_product_uuid.php, upgrades/test_schema/Version_7_0_20230213153500_remove_index_on_product_uuid_Integration.php
In this PR, I fixed the fact that a fresh install does not have the same database structure than a migrated instance 6.0 => 7.0. 
- The following table and column does not have a COMMENT '(DC2Type:uuid_binary)' on migrated instance but have it on fresh instance. This fix is only for 7.0. We will create a ZDD migration to fix it on SaaS production
| Table name                                                                   | Column name  |
|------------------------------------------------------------------------|------------------------------------------------|
| pim_catalog_association                                              |  owner_uuid                                     |
| pim_catalog_association_product …
=> RAB-1317: Fix difference between a fresh install and a migrated install 6.0 => 7.0

src/Akeneo/Connectivity/Connection/front/src/connect/hooks/use-regenerate-custom-app-secret.ts, src/Akeneo/Connectivity/Connection/front/src/connect/pages/RegenerateSecretPage.tsx, src/Akeneo/Connectivity/Connection/front/tests/src/connect/hooks/use-regenerate-custom-app-secret.test.tsx
=> CXP-1418: Added test for custom app secret regeneration hook

components/identifier-generator/back/src/Infrastructure/Controller/GetAvailablePropertiesController.php, components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/controllers.yml, components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/routing.yml, components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/messages.en_US.yml, components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/GetAvailablePropertiesControllerEndToEnd.php
Get list of available system fields and attribute of type select for properties tab
=> CPM-961: Add GetAvailableProperties endpoint

components/catalogs/front/src/FakeCatalogEditContainer.tsx, components/catalogs/front/src/components/CatalogEdit/CatalogEdit.integration.tsx, components/catalogs/front/src/components/ProductMapping/ProductMapping.integration.tsx, components/catalogs/front/src/components/ProductMapping/ProductMapping.tsx, components/catalogs/front/src/components/ProductMapping/utils/createTargetsFromProductMapping.ts, components/catalogs/front/src/components/ProductMapping/utils/createTargetsFromProductMapping.unit.ts, components/catalogs/front/src/components/ProductMapping/utils/sourceHasError.ts, components/catalogs/front/src/components/ProductMapping/utils/sourceHasError.unit.ts, components/catalogs/front/src/components/ProductSelection/ProductSelection.integration.tsx
I've fixed some warnings in old tests and refactored/rewrited `ProductMapping.integration.tsx` to reduce drastically the number of tests & lines in it.
:face_with_thermometer: Since I rewrote the full file, the diff is hard to read. You can check the new version of the file here: https://github.com/akeneo/pim-community-dev/blob/OCT-209/components/catalogs/front/src/components/ProductMapping/ProductMapping.integration.tsx
The coverage on the underlaying components is not perfect but it's for another ticket.
=> OCT-209: update tests

src/Akeneo/Category/back/Infrastructure/Migration/V20221214GiveNewCategoryAclToUserWithOldCategoryAclZddMigration.php
=> Fix zdd migration

src/Akeneo/Connectivity/Connection/front/src/connect/components/CustomApps/CustomAppList.tsx, src/Akeneo/Connectivity/Connection/front/src/connect/components/Marketplace.tsx, src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/CustomApp/CustomAppList.test.tsx, src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/Marketplace.test.tsx
=> CXP-1418: Display an empty custom app section when no custom apps found 

CHANGELOG.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/common/item-picker.js, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/mass-edit/form/product/associate.js, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/associations.js, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/product-and-product-model-picker.js
***Previous behavior of the product and product model picker:***
There were several flaws with the current product picker in the association grid:
- each time a product/model is selected, a request was sent to the backend to get the product information (in order to render the items in the basket), BUT the request included ALL the basket items, not only the one you just selected)
- so, for instance, when selecting all the elements of a page (25), 25 requests would be sent to the backend:
- get products?ids=my_first_product
- get products?ids=my_first_product,my_second_product
- get products?ids=my_first_product,my_second_product,my_third_product
- etc...
- Moreover the event listeners were not unregistered, so each time you opened the …
=> PIM-10831: Prevent association picker from sending too many requests

src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApps/ConnectedAppsContainer.tsx, src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApps/ConnectedCustomAppList.tsx, src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApps/ConnectedCustomAppList.test.tsx
=> CXP-1418: custom app pending msg

src/Akeneo/Connectivity/Connection/back/Infrastructure/CustomApps/Controller/Internal/GetCustomAppSecretAction.php, src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/CustomApps/controllers.yml, src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApp/ConnectedAppSettings.tsx, src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApp/Settings/ConnectedAppCredentials.tsx, src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApps/ConnectedAppsContainer.tsx, src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApps/ConnectedCustomAppList.tsx, src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApp/ConnectedAppCredentials.test.tsx, src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApp/ConnectedAppSettings.test.tsx, src/Akeneo/Connectivity/Connection/front/tests/src/connect/components/ConnectedApps/ConnectedCustomAppList.test.tsx
=> Cxp 1418 custom app regenerate button acl

CHANGELOG-6.0.md, src/Akeneo/Platform/Bundle/AnalyticsBundle/Controller/ExternalApi/GetSystemInformationController.php, src/Akeneo/Platform/Bundle/AnalyticsBundle/Resources/config/controllers.yml, tests/back/Platform/EndToEnd/ExternalApi/GetSystemInformationEndToEnd.php, tests/back/Platform/Specification/Bundle/AnalyticsBundle/Controller/ExternalApi/GetSystemInformationControllerSpec.php
=> PIM-10852: Pull up 6.0 into 7.0

components/catalogs/back/src/Application/Mapping/TargetTypeConverter.php, components/catalogs/back/src/Application/Mapping/ValueExtractor/Extractor/String/StringFromMultiSelectAttributeValueExtractor.php, components/catalogs/back/src/Application/Mapping/ValueExtractor/Extractor/ValueExtractorInterface.php, components/catalogs/back/src/Infrastructure/Symfony/Resources/config/services.yml, components/catalogs/back/src/Infrastructure/Validation/CatalogProductMappingValidator.php, components/catalogs/back/src/Infrastructure/Validation/ProductMapping/AttributeSource/AttributeMultiSelectSource.php, components/catalogs/back/tests/Acceptance/ApiContext.php, components/catalogs/back/tests/Integration/Application/Mapping/ValueExtractor/Extractor/String/StringFromMultiSelectAttributeValueExtractorTest.php, components/catalogs/back/tests/Integration/Infrastructure/Validation/CatalogProductMappingTest.php, components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductMapping/AttributeSource/AttributeMultiSelectSourceTest.php, components/catalogs/back/tests/Unit/Application/Mapping/TargetTypeConverterTest.php, components/catalogs/front/src/components/ProductMapping/components/SourcePanel.tsx
=> CXP-1377: Map multi-select attributes (string)

CHANGELOG.md, src/Akeneo/Category/back/Infrastructure/Component/Model/Category.php, src/Akeneo/Category/back/tests/Specification/Infrastructure/Component/Model/CategorySpec.php, src/Akeneo/Channel/back/Infrastructure/Component/Model/Channel.php, src/Akeneo/Channel/back/tests/Specification/Infrastructure/Component/Model/ChannelSpec.php, src/Akeneo/Pim/Enrichment/Component/Product/Model/Group.php, src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Standard/TranslationNormalizer.php, src/Akeneo/Pim/Structure/Component/Model/AbstractAttribute.php, src/Akeneo/Pim/Structure/Component/Model/AssociationType.php, src/Akeneo/Pim/Structure/Component/Model/AttributeGroup.php, src/Akeneo/Pim/Structure/Component/Model/Family.php, src/Akeneo/Pim/Structure/Component/Model/FamilyVariant.php, src/Akeneo/Pim/Structure/Component/Model/GroupType.php, tests/back/Pim/Enrichment/Specification/Component/Product/Model/GroupSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/Standard/TranslationNormalizerSpec.php, tests/back/Pim/Structure/Specification/Component/Model/AssociationTypeSpec.php, tests/back/Pim/Structure/Specification/Component/Model/AttributeGroupSpec.php, tests/back/Pim/Structure/Specification/Component/Model/AttributeSpec.php, tests/back/Pim/Structure/Specification/Component/Model/FamilySpec.php, tests/back/Pim/Structure/Specification/Component/Model/FamilyVariantSpec.php, tests/back/Pim/Structure/Specification/Component/Model/GroupTypeSpec.php
Fix case-sensitive locale on translatable business objects
=> PIM-10829: Inconsistent behavior when importing label with 'wrong' locale case

src/Akeneo/Category/back/Domain/Model/Classification/CategoryTree.php, src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetCategoryTreesSql.php, src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetCategoryTreesSqlIntegration.php
=> GRF-701 : Update all queries to ignore deleted template

upgrades/test_schema/Version_7_0_20230201143400_drop_product_id_columns_and_clean_versioning_resource_uuid_columns_Integration.php
=> Fix flaky migration test

src/Akeneo/Category/back/Infrastructure/Validation/ValueUserIntentsShouldHaveAnActivatedTemplateValidator.php, src/Akeneo/Category/back/tests/Specification/Infrastructure/Validation/ValueUserIntentsShouldHaveAnActivatedTemplateValidatorSpec.php
=> GRF-755: Missing check on empty value user intents

src/Akeneo/Category/back/Domain/UserIntent/Factory/LabelUserIntentFactory.php, src/Akeneo/Category/back/tests/Specification/Domain/UserIntent/Factory/LabelUserIntentFactorySpec.php
=> GRF-755: Missing check on string label

src/Akeneo/Category/front/src/feature/hooks/useTemplateByTemplateUuid.ts
=> GRF-755: Add check on undefined value

src/Akeneo/Category/back/Infrastructure/Controller/ExternalApi/CategoryController.php, src/Akeneo/Category/back/Infrastructure/Controller/ExternalApi/DownloadCategoryMediaFileController.php, src/Akeneo/Category/back/Infrastructure/Controller/ExternalApi/GetCategoryController.php, src/Akeneo/Category/back/Infrastructure/Controller/ExternalApi/ListCategoriesController.php, src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/controllers.yml, src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/routing/external_api/category.yml, src/Akeneo/Category/back/tests/.php_cd.php
=> GRF-760: export API enriched category media file

src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml, src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/attribute-groups/AttributeGroupsDataGrid.tsx, src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/attribute-groups/MassDeleteAttributeGroupsModal.tsx, src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/hooks/attribute-groups/useAttributeGroupsIndexState.ts, src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/models/AttributeGroup.ts, src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/AttributeGroupsIndex.tsx, src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/components/shared/datagrids/attribute-groups/MassDeleteAttributeGroupsModal.unit.tsx
=> RAB-1294: [Front] Display number of attributes in the grid

src/Akeneo/Platform/PimRequirements.php
In this PR, I updated the check used when the user launch the following command: 
```
bin/console pim:installer:check-requirements
```
=> Flex v7: update system requirements check

src/Akeneo/Platform/Bundle/UIBundle/Controller/AjaxOptionController.php, tests/back/Platform/Specification/Bundle/UIBundle/Controller/AjaxOptionControllerSpec.php
see https://github.com/akeneo/pim-enterprise-dev/pull/16536
=> PIM-10862: Fix attribute options fetch fails in Rule Engine cause of URI Too Long

src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml, src/Akeneo/Category/front/src/feature/hooks/useEditCategoryForm.test.ts, src/Akeneo/Category/front/src/feature/hooks/useTemplateByTemplateUuid.ts, src/Akeneo/Category/front/src/feature/pages/TemplatePage.tsx
=> GRF-692: Redirect to category trees page when user try to view a deactivated tempate

front-packages/akeneo-design-system/src/components/Tooltip/Tooltip.tsx
fixing margin issue in the tooltip 
=> JEL-76: add Tooltip in DSM

CHANGELOG-6.0.md, src/Akeneo/Platform/Bundle/FrameworkBundle/Command/CheckUpdateRequirementsCommand.php, src/Akeneo/Platform/Bundle/FrameworkBundle/Resources/config/services.yml, src/Akeneo/Platform/Bundle/UIBundle/Controller/AjaxOptionController.php, src/Akeneo/Tool/Bundle/ElasticsearchBundle/Command/UpdateIndexVersionCommand.php, src/Akeneo/Tool/Bundle/ElasticsearchBundle/Infrastructure/Client/IndexUpdaterClient.php, src/Akeneo/Tool/Bundle/ElasticsearchBundle/Resources/config/commands.yml, src/Akeneo/Tool/Bundle/ElasticsearchBundle/Resources/config/services.yml, src/Akeneo/Tool/Bundle/ElasticsearchBundle/tests/integration/UpdateIndexVersionIntegration.php, tests/back/Platform/Specification/Bundle/UIBundle/Controller/AjaxOptionControllerSpec.php
=> Pull up 6.0 => 7.0

components/catalogs/front/src/components/ProductMapping/components/SourcePanel.tsx, components/catalogs/front/src/components/ProductMapping/components/SourceParameters/SelectChannelCurrenciesDropdown.tsx, components/catalogs/front/src/components/ProductMapping/components/SourceParameters/SelectCurrencyDropdown.tsx, components/catalogs/front/src/components/ProductMapping/components/SourceParameters/SelectLabelLocaleDropdown.tsx, components/catalogs/front/src/components/ProductMapping/components/SourceParameters/SourceParameters.tsx, components/catalogs/front/src/components/ProductMapping/components/SourceSectionTitle.tsx, components/catalogs/front/src/components/ProductMapping/components/SourceSelection/SelectChannelDropdown.tsx, components/catalogs/front/src/components/ProductMapping/components/SourceSelection/SelectChannelLocaleDropdown.tsx, components/catalogs/front/src/components/ProductMapping/components/SourceSelection/SelectLocaleDropdown.tsx, components/catalogs/front/src/components/ProductMapping/components/SourceSelection/SelectSourceAttributeDropdown.tsx, components/catalogs/front/src/components/ProductMapping/components/SourceSelection/SourceSelection.tsx, components/catalogs/front/src/components/ProductMapping/components/SourceSelection/SourceSettings.tsx, components/catalogs/front/src/components/ProductMapping/models/Source.d.ts, components/catalogs/front/src/components/ProductMapping/utils/createSourceFromAttribute.ts, components/catalogs/front/src/components/ProductMapping/utils/createSourceFromAttribute.unit.ts
Refactoring of Source Panel into 3 main components: Requirements, Source Selection, and Source Parameters
=> CXP-1439: 3 component split of Source Panel

CHANGELOG-6.0.md, src/Akeneo/Pim/Structure/Bundle/EventSubscriber/ComputeFamilyVariantStructureChangesSubscriber.php, src/Akeneo/Pim/Structure/Bundle/EventSubscriber/SaveFamilyVariantOnFamilyUpdateSubscriber.php, src/Akeneo/Pim/Structure/Component/Model/Family.php, src/Akeneo/Pim/Structure/Component/Model/FamilyVariant.php, tests/back/Pim/Structure/Specification/Bundle/EventSubscriber/SaveFamilyVariantOnFamilyUpdateSubscriberSpec.php
=> PIM-10865: Backport PIM-10606 on 6.0

CHANGELOG-6.0.md
=> Pull up 6.0 into 7.0

src/Akeneo/Connectivity/Connection/back/Infrastructure/Audit/Command/UpdateAuditDataCommand.php, src/Akeneo/Connectivity/Connection/back/Infrastructure/ErrorManagement/Command/PurgeConnectionErrorsCommand.php, src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/Command/SendBusinessEventToWebhooks.php
=> OCT-226: add a try catch to make silent exceptions

components/identifier-generator/front/src/feature/hooks/__mocks__/useGetConditionItems.ts, components/identifier-generator/front/src/feature/hooks/__tests__/useGetPropertyItems.test.tsx, components/identifier-generator/front/src/feature/hooks/index.ts, components/identifier-generator/front/src/feature/hooks/useGetAttributeByCode.ts, components/identifier-generator/front/src/feature/hooks/useGetConditionItems.ts, components/identifier-generator/front/src/feature/hooks/useGetPropertyItems.ts, components/identifier-generator/front/src/feature/models/attribute.ts, components/identifier-generator/front/src/feature/models/index.ts, components/identifier-generator/front/src/feature/models/itemsGroup.ts, components/identifier-generator/front/src/feature/models/properties/propertyItem.ts, components/identifier-generator/front/src/feature/models/structure.ts, components/identifier-generator/front/src/feature/tabs/structure/AddPropertyButton.tsx, components/identifier-generator/front/src/feature/tabs/structure/PropertyEdit.tsx, components/identifier-generator/front/src/feature/tabs/structure/__tests__/AddPropertyButton.test.tsx
=> CPM-962: Add simple selects to AddButtonProperty 

front-packages/shared/src/components/DoubleCheckDeleteModal.tsx, src/Akeneo/Pim/Structure/Bundle/Controller/InternalApi/MassDeleteAttributeController.php, src/Akeneo/Pim/Structure/Bundle/EventSubscriber/CheckAttributeIsNotUsedAsLabelOnDeletionSubscriber.php, src/Akeneo/Pim/Structure/Bundle/Resources/config/jobs.yml, src/Akeneo/Pim/Structure/Bundle/Resources/translations/messages.en_US.yml, src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/services.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/Notification.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/messages.en_US.yml
- I added an icon on mass delete notification
- I fixed the mass delete notification message
- I added email send at the end of attribute mass delete
- I added the fact to submit on confirmation input when hitting Enter key on attribute delete modal
=> RAB-1264: Fix breakit and UX review

src/Akeneo/Pim/Enrichment/Bundle/Resources/config/array_converter.yml, src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/FlatToStandard/Product.php, src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/FlatToStandard/ProductAssociation.php, src/Akeneo/Pim/Enrichment/Component/Product/Connector/Processor/Denormalizer/ProductAssociationProcessor.php, src/Akeneo/Pim/Enrichment/Component/Product/Connector/Processor/Denormalizer/ProductProcessor.php, src/Akeneo/Pim/Enrichment/Component/Product/Repository/ProductRepositoryInterface.php, tests/back/Pim/Enrichment/Integration/Product/Import/ImportProductsIntegration.php, tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/FlatToStandard/ProductSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Processor/Denormalizer/ProductAssociationProcessorSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Processor/Denormalizer/ProductProcessorSpec.php
=> PIM-10863: Fix import product without sku column

components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/messages.en_US.yml, components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/GetAvailableConditionsControllerEndToEnd.php
=> CPM-970: Update get available conditions

src/Akeneo/Category/back/tests/Integration/ServiceApi/CategoryQueryIntegration.php
Fix ci test error https://app.circleci.com/pipelines/github/akeneo/pim-community-dev/49606/workflows/01394507-33db-4e16-af12-f46d8fdbb98c/jobs/292181
```
AkeneoTestEnterprise\Pim\Permission\Performance\ImportVariantProductsWithApiPerformance::test_that_importing_products_with_api_is_performant
Failed asserting that Blackfire tests pass.
1 tests failures out of 6.
failed: Memory
- main.peak_memory < 45mb
More information at https://blackfire.io/profiles/900b3922-cd6e-4789-a96c-9e256df35e04/graph?settings%5BtabPane%5D=assertions.
/srv/pim/vendor/blackfire/php-sdk/src/Blackfire/Bridge/PhpUnit/TestConstraint.php:60
/srv/pim/vendor/blackfire/php-sdk/src/Blackfire/Bridge/PhpUnit/TestConstraint71.php:19
/srv/pim/vendor/blackfire/php-sdk/src/Blackfire/Bridge/PhpUnit/TestCaseTrait.php:53 …
```
=> JEL-213: load categories by codes / Ids

components/identifier-generator/back/src/Domain/Model/Property/PropertyInterface.php, components/identifier-generator/back/src/Domain/Model/Property/SimpleSelectProperty.php, components/identifier-generator/back/src/Domain/Model/Structure.php, components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/validation/create_generator_command.yml, components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/validation/update_generator_command.yml, components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/validators.yml, components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/validators.en_US.yml, components/identifier-generator/back/src/Infrastructure/Validation/FamilyPropertyShouldBeValidValidator.php, components/identifier-generator/back/src/Infrastructure/Validation/PropertyProcessShouldBeValid.php, components/identifier-generator/back/src/Infrastructure/Validation/PropertyProcessShouldBeValidValidator.php, components/identifier-generator/back/src/Infrastructure/Validation/SimpleSelectPropertyShouldBeValid.php, components/identifier-generator/back/src/Infrastructure/Validation/SimpleSelectPropertyShouldBeValidValidator.php, components/identifier-generator/back/tests/Acceptance/Context/CreateIdentifierGeneratorContext.php, components/identifier-generator/back/tests/Acceptance/Context/UpdateIdentifierGeneratorContext.php, components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/CreateIdentifierGeneratorControllerEndToEnd.php, components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/CreateIdentifierGeneratorWithSimpleSelectEndToEnd.php, components/identifier-generator/back/tests/Specification/Domain/Model/Property/SimpleSelectPropertySpec.php, components/identifier-generator/back/tests/Specification/Infrastructure/Validation/FamilyPropertyShouldBeValidValidatorSpec.php, components/identifier-generator/back/tests/Specification/Infrastructure/Validation/PropertyProcessShouldBeValidValidatorSpec.php, components/identifier-generator/back/tests/Specification/Infrastructure/Validation/SimpleSelectPropertyShouldBeValidValidatorSpec.php, components/identifier-generator/back/tests/features/createIdentifierGenerator.feature, components/identifier-generator/back/tests/features/updateIdentifierGenerator.feature
=> CPM-959: Add Classes and validation to create simple select properties in identifier generators

src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Field/UuidFilter.php, tests/back/Pim/Enrichment/Integration/PQB/Filter/Field/Product/UuidFilterIntegration.php, tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Filter/Field/UuidFilterSpec.php
=> CPM-990: Case insensitive UUID filter

CHANGELOG-6.0.md, src/Akeneo/Pim/Enrichment/Bundle/ProductQueryBuilder/ProductAndProductModelQueryBuilder.php, tests/back/Pim/Enrichment/Specification/Bundle/ProductQueryBuilder/ProductAndProductModelQueryBuilderSpec.php
=> PIM-10878: Fix filtering products with identifiers would not display some product models

components/identifier-generator/front/src/feature/components/NomenclatureEdit.tsx, components/identifier-generator/front/src/feature/components/Styled.tsx
=> CPM-987: Fix scroll on nomenclature

src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/attribute-groups/AttributeGroupsDataGrid.tsx
=> RAB-1362: make attribute groups unselectable for prod

CHANGELOG.md, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/productgrid.yml
=> PIM-10877: Sequential edit is not working if grid is sorted by quality score

components/identifier-generator/back/src/Application/Generate/Property/GenerateSimpleSelectHandler.php, components/identifier-generator/back/src/Domain/Model/Property/SimpleSelectProperty.php, components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/command_handlers.yml, components/identifier-generator/back/tests/EndToEnd/Infrastructure/EndToEndTestCase.php, components/identifier-generator/back/tests/EndToEnd/Infrastructure/Subscriber/SetIdentifiersSubscriberEndToEnd.php, components/identifier-generator/back/tests/Specification/Application/Generate/Property/GenerateSimpleSelectHandlerSpec.php, components/identifier-generator/back/tests/Specification/Domain/Model/Property/SimpleSelectPropertySpec.php
=> CPM-960: Add GenerateSimpleSelectHandler

src/Akeneo/Pim/Enrichment/Component/Product/Localization/Presenter/MetricPresenter.php
=> RAC-1288: Handle exceptions triggering logs in MetricPresenter

front-packages/shared/src/components/DoubleCheckDeleteModal.tsx, front-packages/shared/src/components/DoubleCheckDeleteModal.unit.tsx
Same as https://github.com/akeneo/pim-community-dev/pull/19388
=> RAB-1365: Fix UI glitch

front-packages/akeneo-design-system/src/components/Input/DateInput/DateInput.tsx, front-packages/akeneo-design-system/src/components/Input/DateInput/DateInput.unit.tsx
Ensure the right reference of the onChange handler is called when the DateInput is rerendered.
=> AST-527: Fix memoize callback issue with DateInput component

src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/common/menu.yml
=> Remove useless menu

src/Akeneo/Pim/Structure/.php_cd.php, src/Akeneo/Pim/Structure/Bundle/Controller/InternalApi/MassDeleteAttributeController.php, src/Akeneo/Pim/Structure/Bundle/Resources/config/acl.yml, src/Akeneo/Pim/Structure/Bundle/Resources/config/controllers.yml, src/Akeneo/Pim/Structure/Bundle/Resources/config/datagrid/attribute.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/messages.en_US.yml, upgrades/schema/Version_8_0_20230308152730_disable_attributes_mass_delete_acl.php, upgrades/test_schema/Version_8_0_20230308152730_disable_attributes_mass_delete_acl_Integration.php
I added an ACL to disallow users to bulk remove attributes.
=> RAB-1255: Add ACL for bulk remove attributes

src/Akeneo/Pim/Structure/Bundle/Infrastructure/Controller/MassDeleteAttributeGroupsController.php, src/Akeneo/Pim/Structure/Bundle/Resources/config/acl.yml, src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/attribute-groups/AttributeGroupsDataGrid.tsx, src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/messages.en_US.yml, upgrades/schema/Version_8_0_20230308113214_disable_attribute_groups_mass_delete_acl.php, upgrades/test_schema/Version_8_0_20230308113214_disable_attribute_groups_mass_delete_acl_Integration.php
I added an ACL to disallow users to bulk remove attribute groups.
=> RAB-1281: Add ACL for Bulk remove attribute groups

components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml, components/identifier-generator/front/src/feature/pages/ListPage.tsx, components/identifier-generator/front/src/feature/pages/__tests__/ListPage.test.tsx
[front] 
- Update limit from 1 to 20
- update placeholders
=> CPM-994: update limit from 1 to 20

front-packages/shared/src/components/Navigation/PimNavigation.tsx, front-packages/shared/src/components/Navigation/PimNavigation.unit.tsx, src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_US.yml
Reverts akeneo/pim-community-dev#19165
=> Revert "CPM-951: Add sub entries links for Help menu button"

src/Akeneo/Category/back/Domain/Model/Enrichment/Category.php, src/Akeneo/Category/back/Infrastructure/Controller/InternalApi/GetCategoryController.php, src/Akeneo/Category/back/ServiceApi/InternalApiCategory.php, src/Akeneo/Category/back/tests/.php_cd.php, src/Akeneo/Category/back/tests/Integration/ServiceApi/InternalApiCategoryIntegration.php
=> CPM-1003: Fix CategoryQueryHandler::byCodes() type error

components/identifier-generator/front/src/feature/pages/ListPage.tsx, components/identifier-generator/front/src/feature/pages/__tests__/ListPage.test.tsx
Add search bar on identifier generators list
=> CPM-996 : add search bar

src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
=> CPM-1001: change wording

components/identifier-generator/back/src/Domain/Model/Condition/Category.php, components/identifier-generator/back/src/Domain/Model/Condition/CategoryOperator.php, components/identifier-generator/back/src/Domain/Model/Condition/ConditionInterface.php, components/identifier-generator/back/src/Domain/Model/Condition/Conditions.php, components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/validation/create_generator_command.yml, components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/validation/update_generator_command.yml, components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/validators.yml, components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/validators.en_US.yml, components/identifier-generator/back/src/Infrastructure/Validation/CategoryCodesShouldExist.php, components/identifier-generator/back/src/Infrastructure/Validation/CategoryCodesShouldExistValidator.php, components/identifier-generator/back/src/Infrastructure/Validation/CategoryShouldBeValid.php, components/identifier-generator/back/src/Infrastructure/Validation/CategoryShouldBeValidValidator.php, components/identifier-generator/back/tests/Acceptance/Context/CreateIdentifierGeneratorContext.php, components/identifier-generator/back/tests/Acceptance/Context/UpdateIdentifierGeneratorContext.php, components/identifier-generator/back/tests/Specification/Domain/Model/Condition/CategorySpec.php, components/identifier-generator/back/tests/Specification/Infrastructure/Validation/CategoryCodesShouldExistValidatorSpec.php, components/identifier-generator/back/tests/Specification/Infrastructure/Validation/CategoryShouldBeValidValidatorSpec.php, components/identifier-generator/back/tests/features/createIdentifierGenerator.feature, components/identifier-generator/back/tests/features/updateIdentifierGenerator.feature
=> CPM-968: Create Category condition

components/identifier-generator/back/src/Application/Generate/Property/GenerateSimpleSelectHandler.php, components/identifier-generator/back/src/Infrastructure/Controller/GetAvailableConditionsController.php, components/identifier-generator/back/src/Infrastructure/Controller/GetAvailablePropertiesController.php, components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/GetAvailablePropertiesControllerEndToEnd.php, components/identifier-generator/back/tests/Specification/Domain/Model/Property/SimpleSelectPropertySpec.php, components/identifier-generator/front/src/feature/components/ScopeAndLocaleSelector.tsx, components/identifier-generator/front/src/feature/components/Styled.tsx, components/identifier-generator/front/src/feature/tabs/structure/PropertyEdit.tsx, components/identifier-generator/front/src/feature/validators/__tests__/validateSimpleSelectProperty.test.ts, components/identifier-generator/front/src/feature/validators/validateSimpleSelectProperty.tsx
- Fix validation when process value is empty
- Add labels for locale and channel in this screen (they should not appear in the selection)
=> CPM-882: Add validation for simple select property and add labels

components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml, components/identifier-generator/front/src/feature/components/NomenclatureEdit.tsx, components/identifier-generator/front/src/feature/components/__tests__/NomenclatureEdit.test.tsx
- Move filter line
- Add helper
=> CPM-975: Move filter line and add Helper

components/identifier-generator/back/src/Infrastructure/Symfony/Install/InstallerSubscriber.php, upgrades/schema/Version_8_0_20230315132124_create_identifier_generator_simple_select_nomenclature_tables.php, upgrades/test_schema/Version_8_0_20230315132124_create_identifier_generator_simple_select_nomenclature_tables_Integration.php
Add tables and migration for simple select nomenclature
=> CPM-1004: Add tables and migration for simple select nomenclature

components/identifier-generator/back/tests/Acceptance/Context/CreateIdentifierGeneratorContext.php, components/identifier-generator/back/tests/Acceptance/Resources/config/services.yml, components/identifier-generator/back/tests/features/createIdentifierGenerator.feature, components/identifier-generator/back/tests/features/updateIdentifierGenerator.feature, src/Akeneo/Category/back/Infrastructure/Storage/InMemory/GetCategoryInMemory.php, tests/back/Acceptance/Resources/config/pim/repositories.yml
Fix errors on acceptance tests
=> CPM-968: fix acceptance tests

components/identifier-generator/back/src/Infrastructure/Subscriber/SetIdentifiersSubscriber.php, components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/event_subscribers.yml, components/identifier-generator/back/tests/Specification/Infrastructure/Subscriber/SetIdentifiersSubscriberSpec.php
=> CPM-991: Add logs to track generated identifier values

components/identifier-generator/back/src/Application/Update/ReorderGeneratorsCommand.php, components/identifier-generator/back/src/Application/Update/ReorderGeneratorsHandler.php, components/identifier-generator/back/src/Domain/Query/ReorderIdentifierGenerators.php, components/identifier-generator/back/src/Infrastructure/Controller/ReorderIdentifierGeneratorsController.php, components/identifier-generator/back/src/Infrastructure/Query/InMemoryReorderIdentifierGenerators.php, components/identifier-generator/back/src/Infrastructure/Query/SqlReorderIdentifierGenerators.php, components/identifier-generator/back/src/Infrastructure/Repository/InMemoryIdentifierGeneratorRepository.php, components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/command_handlers.yml, components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/controllers.yml, components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/persistence.yml, components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/routing.yml, components/identifier-generator/back/tests/Acceptance/Context/UpdateIdentifierGeneratorContext.php, components/identifier-generator/back/tests/Acceptance/Resources/config/services.yml, components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/ReorderIdentifierGeneratorsControllerEndToEnd.php, components/identifier-generator/back/tests/Integration/Query/ReorderIdentifierGeneratorsIntegration.php, components/identifier-generator/back/tests/Specification/Infrastructure/Repository/InMemoryIdentifierGeneratorRepositorySpec.php, components/identifier-generator/back/tests/features/updateIdentifierGenerator.feature, components/identifier-generator/front/src/feature/hooks/useGetIdentifierGenerator.ts, components/identifier-generator/front/src/feature/pages/ListPage.tsx, components/identifier-generator/front/src/feature/pages/__tests__/ListPage.test.tsx, components/identifier-generator/front/src/feature/tests/test-utils.tsx
=> CPM-995: Reorder identifier generators

src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml, src/Akeneo/Category/front/src/configuration/Page.tsx, src/Akeneo/Category/front/src/feature/components/templates/AddTemplateAttributeModal.tsx, src/Akeneo/Category/front/src/feature/hooks/useCreateAttribute.ts, src/Akeneo/Category/front/src/feature/pages/TemplatePage.tsx
This PR only contains:
- add button to open modal
- modal opens and display. Cancel button works, create button simulate a success call to add attribute
- template customization feature flag is taken into account
=> GRF-775 create add template attribute modal

components/catalogs/back/src/Domain/Catalog.php, components/catalogs/back/src/Infrastructure/Validation/CatalogProductMappingValidator.php, components/catalogs/back/src/Infrastructure/Validation/ProductMapping/AttributeSource/AttributeBooleanSource.php, components/catalogs/back/src/Infrastructure/Validation/ProductMapping/NullSource/NullBooleanSource.php, components/catalogs/back/src/Infrastructure/Validation/ProductMapping/ProductMappingRespectsSchemaValidator.php, components/catalogs/back/tests/Integration/Application/Mapping/ValueExtractor/Extractor/StringUri/StringUriFromImageAttributeValueExtractorTest.php, components/catalogs/back/tests/Integration/Infrastructure/Persistence/Currency/GetChannelCurrenciesQueryTest.php, components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductMapping/AttributeSource/AttributeBooleanSourceTest.php, components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductMapping/NullSource/NullBooleanSourceTest.php, components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductMapping/ProductMappingRespectsSchemaTest.php, components/catalogs/front/src/components/ProductMapping/ProductMapping.tsx, components/catalogs/front/src/components/ProductMapping/components/SourcePanel.integration.tsx, components/catalogs/front/src/components/ProductMapping/components/SourcePanel.tsx, components/catalogs/front/src/components/ProductMapping/components/SourceParameters/DefaultValue.integration.tsx, components/catalogs/front/src/components/ProductMapping/components/SourceParameters/DefaultValue.tsx, components/catalogs/front/src/components/ProductMapping/components/SourceParameters/SourceParameters.tsx, components/catalogs/front/src/components/ProductMapping/models/Source.d.ts, components/catalogs/front/src/components/ProductMapping/utils/createTargetFromProductMappingSchema.ts
=> CXP-1417: add the boolean default value

src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml, src/Akeneo/Category/front/src/configuration/Page.tsx, src/Akeneo/Category/front/src/feature/components/templates/AddTemplateAttributeModal.test.tsx, src/Akeneo/Category/front/src/feature/components/templates/AddTemplateAttributeModal.tsx, src/Akeneo/Category/front/src/feature/components/templates/EditTemplateAttributesForm.test.tsx, src/Akeneo/Category/front/src/feature/components/templates/EditTemplateAttributesForm.tsx, src/Akeneo/Category/front/src/feature/hooks/useCreateAttribute.ts, src/Akeneo/Category/front/src/feature/hooks/useTemplateByTemplateUuid.ts, src/Akeneo/Category/front/src/feature/pages/TemplatePage.tsx
=> GRF-764 send add attribute's modal content and manage response

.circleci/config/commands.yml, .circleci/jobs/build_and_deploy.yml, .circleci/jobs/features/connectivity.yml, .circleci/jobs/features/other.yml, .circleci/run_behat.sh, Dockerfile, Makefile, bin/benchmark_products_api.sh, docker-compose.override-osx.yml, docker-compose.yml, docker/httpd.conf, docker/supervisord.conf
See the corresponding EE PR for explanations: https://github.com/akeneo/pim-enterprise-dev/pull/15607
=> Merge fpm and php containers

src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/attribute-groups/MassDeleteAttributeGroupsModal.tsx, src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/models/AttributeGroup.ts, src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/models/AttributeGroup.unit.ts
- Always display other in replacement attribute groups
=> RAB-1360: Always display other in replacement attribute groups

src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Query/ProductEvaluation/GetOutdatedProductModelIdsByDateAndCriteriaQueryInterface.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Query/ProductEvaluation/GetOutdatedProductUuidsByDateAndCriteriaQueryInterface.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/ValueObject/ProductModelIdCollection.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Clock/SystemClock.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Messenger/LaunchProductAndProductModelEvaluationsHandler.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Messenger/LaunchProductAndProductModelEvaluationsMessage.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetOutdatedProductModelIdsByDateAndCriteriaQuery.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetOutdatedProductUuidsByDateAndCriteriaQuery.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/messenger_handlers.yml, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Resources/config/queries.yml, src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Infrastructure/Messenger/LaunchProductAndProductModelEvaluationsHandlerIntegration.php, src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Infrastructure/Persistence/Query/ProductEvaluation/GetOutdatedProductModelIdsByDateAndCriteriaQueryIntegration.php, src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Integration/Infrastructure/Persistence/Query/ProductEvaluation/GetOutdatedProductUuidsByDateAndCriteriaQueryIntegration.php, src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Messenger/LaunchProductAndProductModelEvaluationsHandlerSpec.php, src/Akeneo/Pim/Automation/DataQualityInsights/tests/back/Specification/Infrastructure/Messenger/LaunchProductAndProductModelEvaluationsMessageSpec.php
See https://github.com/akeneo/pim-enterprise-dev/pull/16748
=> JEL-231: Add command to prepare and launch evaluations instead of jobs

components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/validation/create_generator_command.yml, components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/validators.yml, components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/validators.en_US.yml, components/identifier-generator/back/src/Infrastructure/Validation/UniqueIdentifierGeneratorCode.php, components/identifier-generator/back/src/Infrastructure/Validation/UniqueIdentifierGeneratorCodeValidator.php, components/identifier-generator/back/tests/Specification/Infrastructure/Validation/UniqueIdentifierGeneratorCodeValidatorSpec.php, components/identifier-generator/back/tests/features/createIdentifierGenerator.feature, components/identifier-generator/front/src/feature/pages/CreateGeneratorModal.tsx, components/identifier-generator/front/src/feature/pages/CreateOrEditGeneratorPage.tsx, components/identifier-generator/front/src/feature/pages/__tests__/CreateGeneratorModal.test.tsx
=> CPM-1013: Check identifier generator code unicity

components/catalogs/back/src/Application/Mapping/TargetTypeConverter.php, components/catalogs/back/src/Application/Mapping/ValueExtractor/Extractor/ArrayOfStrings/ArrayOfStringsFromCategoriesValueExtractor.php, components/catalogs/back/src/Infrastructure/Command/CatalogFixtureCommand.php, components/catalogs/back/src/Infrastructure/Symfony/Resources/config/services.yml, components/catalogs/back/tests/Acceptance/ApiContext.php, components/catalogs/back/tests/Integration/Application/Mapping/ValueExtractor/Extractor/ArrayOfStrings/ArrayOfStringsFromCategoriesValueExtractorTest.php, components/catalogs/back/tests/Integration/Application/Mapping/ValueExtractor/Registry/ValueExtractorRegistryTest.php, components/catalogs/back/tests/Integration/Infrastructure/Persistence/Category/GetProductCategoriesLabelsQueryTest.php, components/catalogs/back/tests/Unit/Application/Mapping/TargetTypeConverterTest.php, components/catalogs/front/src/components/ProductMapping/components/SourceSelection/SelectSourceAttributeDropdown.integration.tsx, components/catalogs/front/src/components/ProductMapping/components/SourceSelection/SelectSourceAttributeDropdown.tsx
=> CXP-1412: Map categories (string[])

src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml, src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/datagrids/attribute-groups/AttributeGroupList.tsx, src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/models/AttributeGroup.ts, src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/AttributeGroupsIndex.tsx, src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/models/AttributeGroup.unit.ts, src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev/jobs.yml, src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/minimal/jobs.yml, src/Akeneo/Platform/Job/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
- Select all attribute groups only selects filtered results
- Fix visual glitch of checkbox visible behind search bar
- 
- Rename mass delete -> bulk delete
- Rename child attributes -> related attributes
=> RAB-1366: Select all attribute groups only selects filtered results

src/Akeneo/Pim/Enrichment/Bundle/Command/CalculateCompletenessCommand.php, src/Akeneo/Pim/Enrichment/Bundle/Command/CleanRemovedAttributesFromProductAndProductModelCommand.php, src/Akeneo/Pim/Enrichment/Bundle/Command/CleanRemovedProductsCommand.php, src/Akeneo/Pim/Enrichment/Bundle/Command/IndexProductCommand.php, src/Akeneo/Pim/Enrichment/Bundle/Command/IndexProductModelCommand.php, src/Akeneo/Tool/Bundle/ElasticsearchBundle/Command/ResetIndexesCommand.php
=> GH-19430: Command shortcut cannot be a boolean

src/Akeneo/Platform/Bundle/FeatureFlagBundle/Configuration/OnlyGrowthAndSerenitySandboxFeatureFlag.php, src/Akeneo/Platform/Bundle/FeatureFlagBundle/Resources/config/services.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_US.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/system/src/components/SystemIndex.tsx
See [EE PR](https://github.com/akeneo/pim-enterprise-dev/pull/16917) for details.
=> RAB-1322: Add a feature flag for reset pim feature

CHANGELOG-6.0.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/controller/attribute/create.js
=> PIM-10913: Fix attribute creation form when a label contains a question mark

src/Akeneo/Category/front/src/feature/components/templates/EditTemplateAttributesForm.tsx
=> fix remove unnecessary useRef and useCallback

components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml, components/identifier-generator/front/src/feature/components/NomenclatureEdit.tsx, components/identifier-generator/front/src/feature/components/Styled.tsx, components/identifier-generator/front/src/feature/components/__tests__/NomenclatureEdit.test.tsx, components/identifier-generator/front/src/feature/hooks/index.ts, components/identifier-generator/front/src/feature/hooks/useGetFamilies.ts, components/identifier-generator/front/src/feature/hooks/useGetNomenclatureValues.ts, components/identifier-generator/front/src/feature/hooks/useGetSelectOptions.ts, components/identifier-generator/front/src/feature/hooks/useNomenclatureDisplay.ts, components/identifier-generator/front/src/feature/models/index.ts, components/identifier-generator/front/src/feature/models/nomenclature.ts, components/identifier-generator/front/src/feature/models/nomenclatureLineEditProps.ts, components/identifier-generator/front/src/feature/models/properties/canUseNomenclatureProperty.ts, components/identifier-generator/front/src/feature/models/properties/index.ts, components/identifier-generator/front/src/feature/models/properties/simpleSelectProperty.ts, components/identifier-generator/front/src/feature/models/simpleSelect.ts, components/identifier-generator/front/src/feature/tabs/structure/ProcessablePropertyEdit.tsx, components/identifier-generator/front/src/feature/tabs/structure/__tests__/ProcessablePropertyEdit.test.tsx, components/identifier-generator/front/src/feature/tabs/structure/edit/FamilyPropertyEdit.tsx, components/identifier-generator/front/src/feature/tabs/structure/edit/SimpleSelectPropertyEdit.tsx, src/Akeneo/Pim/Structure/Bundle/Query/InternalApi/AttributeOption/SqlFindAttributeOptions.php, src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml, tests/back/Pim/Structure/Integration/Query/InternalApi/AttributeOption/SqlFindAttributeOptionsIntegration.php
=> CPM-1009: Allow user to select nomenclature in the process list

components/catalogs/front/package.json
=> OCT-237: reverse wrong change in package.json

src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml, src/Akeneo/Category/front/src/feature/components/DiscoverEnrichedCategoriesInformationHelper.tsx
=> GRF-788: Update Enriched Category helper message

CHANGELOG.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/datagrid/history.yml, tests/legacy/features/pim/enrichment/reference-data/attribute/display_attribute_history.feature
=> PIM-10906: Use user timezone to display dates in history grid

components/identifier-generator/back/src/Infrastructure/Controller/GetAvailablePropertiesController.php, components/identifier-generator/back/tests/EndToEnd/ControllerEndToEndTestCase.php, components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/GetAvailablePropertiesControllerEndToEnd.php, components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/GetIdentifierGeneratorControllerEndToEnd.php, src/Akeneo/Pim/Enrichment/Product/back/Test/Helper/FeatureHelper.php
Add ref entities in properties list
=> CPM-1019: Add ref entities in GetAvailablePropertiesController

.php_cs.php, composer.json, config/bundles.php, config/services/test_fake/services.yml, make-file/installer.mk, make-file/test.mk, phpspec.yml.dist, src/Akeneo/Platform/Installer/back/src/Application/InstallPim/InstallFixtures.php, src/Akeneo/Platform/Installer/back/src/Application/InstallPim/InstallPimHandler.php, src/Akeneo/Platform/Installer/back/src/Infrastructure/Fixtures/FixturesInstaller.php, src/Akeneo/Platform/Installer/back/src/Infrastructure/Symfony/AkeneoInstallerBundle.php, src/Akeneo/Platform/Installer/back/src/Infrastructure/Symfony/DependencyInjection/AkeneoInstallerExtension.php, src/Akeneo/Platform/Installer/back/src/Infrastructure/Symfony/Resources/config/fixtures.yml, src/Akeneo/Platform/Installer/back/src/Infrastructure/Symfony/Resources/config/handlers.yml, src/Akeneo/Platform/Installer/back/tests/.php_cd.php, src/Akeneo/Platform/Installer/back/tests/.php_cs.src.php, src/Akeneo/Platform/Installer/back/tests/.php_cs.tests.php, src/Akeneo/Platform/Installer/back/tests/Acceptance/FakeServices/InMemoryFixturesInstaller.php, src/Akeneo/Platform/Installer/back/tests/Acceptance/Resources/config/fake_services.yml, src/Akeneo/Platform/Installer/back/tests/Acceptance/UseCases/InstallPim/InstallPimTest.php, src/Akeneo/Platform/Installer/back/tests/Integration/DummyTest.php, src/Akeneo/Platform/Installer/back/tests/Specification/Application/InstallPim/InstallPimHandlerSpec.php, src/Akeneo/Platform/Installer/back/tests/phpstan.neon, src/Akeneo/Platform/Installer/back/tests/phpunit.xml, src/Akeneo/Platform/Installer/back/tests/rector.php, src/Akeneo/Tool/Bundle/BatchQueueBundle/Command/PublishJobToQueueCommand.php
I initialized a new Bundle in Platform context : `AkeneoInstallerBundle`
I created directory structure according to clean architecture and I added dummy classes to be able to set up a runnable test suite.
=> RAB-1369: Initialize AkeneoInstallerBundle

src/Akeneo/Pim/Enrichment/Component/Product/Value/ScalarValue.php, tests/back/Pim/Enrichment/Specification/Component/Product/Value/ScalarValueSpec.php
=> CPM-702: Improves number comparison

components/identifier-generator/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
=> CPM-1035: Several identifiers - update wording helper for deployment

src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/AttributeGroupSecondaryActions.tsx, src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/DeleteAttributeGroupModal.tsx, src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/components/index.ts, src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/models/AttributeGroup.ts, src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/components/AttributeGroupSecondaryActions.unit.tsx, src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/tests/front/unit/components/DeleteAttributeGroupModal.unit.tsx, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/attribute_group/edit.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/attribute-group/form/secondary-actions.tsx, tests/legacy/features/Behat/Decorator/Common/DropdownMenuDecorator.php
- Disable delete button on the attribute group “Other”
- Fix spacing issue
=> RAB-1378: Attribute group unitary delete

src/Akeneo/Pim/Structure/Bundle/Resources/config/job_constraints.yml, src/Akeneo/Pim/Structure/Bundle/Resources/workspaces/settings-ui/src/pages/AttributeGroupsIndex.tsx
- Declare dedicated constraint collection provider for bulk delete attributes jobs
- Hide toolbar when having no filtered results in Attribute groups grid
=> RAB: Fix constraints for bulk delete attributes

src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml, src/Akeneo/Category/front/src/feature/components/DiscoverEnrichedCategoriesInformationHelper.tsx, src/Akeneo/Category/front/src/feature/components/templates/AttributeList.tsx, src/Akeneo/Category/front/src/feature/components/templates/AttributeSettings.tsx, src/Akeneo/Category/front/src/feature/components/templates/EditTemplateAttributesForm.tsx, src/Akeneo/Category/front/src/feature/components/templates/EditTemplatePropertiesForm.tsx, src/Akeneo/Category/front/src/feature/components/templates/NoTemplateAttribute.tsx, src/Akeneo/Category/front/src/feature/components/templates/NoTemplateAttributeOnTemplatePage.tsx, src/Akeneo/Category/front/src/feature/pages/CategoryEditPage.tsx, src/Akeneo/Category/front/src/feature/pages/TemplatePage.tsx
=> GRF-793 Add attribute settings panel in edit template page

components/identifier-generator/back/src/Application/Generate/Property/GenerateReferenceEntityHandler.php, components/identifier-generator/back/src/Application/Match/Condition/MatchReferenceEntityHandler.php, components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/command_handlers.yml, components/identifier-generator/back/tests/EndToEnd/Infrastructure/EndToEndTestCase.php, components/identifier-generator/back/tests/EndToEnd/Infrastructure/Subscriber/SetIdentifiersSubscriberEndToEnd.php, components/identifier-generator/back/tests/Specification/Application/Generate/Property/GenerateReferenceEntityHandlerSpec.php
=> CPM-1020: Create GenerateReferenceEntitySingleLinkHandler

components/catalogs/back/src/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml, components/catalogs/front/src/components/CatalogList/CatalogList.integration.tsx, components/catalogs/front/src/components/CatalogList/components/Empty.tsx, components/catalogs/front/src/components/ProductSelection/components/Empty.tsx
=> OCT-240: Link to fix - There is no catalog

CHANGELOG-6.0.md, composer.json, composer.lock
=> PIM-10922: Update dompdf library

src/Akeneo/Connectivity/Connection/front/src/connect/components/CustomApps/CreateCustomAppForm.tsx
=> OCT-238: Link to fix - create an app screen

components/identifier-generator/back/src/Infrastructure/Repository/InMemoryFamilyNomenclatureRepository.php, components/identifier-generator/back/src/Infrastructure/Repository/InMemoryIdentifierGeneratorRepository.php, components/identifier-generator/back/src/Infrastructure/Repository/InMemorySimpleSelectNomenclatureRepository.php, components/identifier-generator/back/tests/Acceptance/Context/SimpleSelectNomenclatureContext.php, components/identifier-generator/back/tests/Acceptance/Context/UpdateFamilyNomenclatureContext.php, components/identifier-generator/back/tests/Integration/Repository/SqlIdentifierGeneratorRepositoryIntegration.php, components/identifier-generator/back/tests/Integration/Repository/SqlSimpleSelectNomenclatureRepositoryIntegration.php, components/identifier-generator/back/tests/Specification/Infrastructure/Repository/InMemoryFamilyNomenclatureRepositorySpec.php, components/identifier-generator/back/tests/Specification/Infrastructure/Repository/InMemoryIdentifierGeneratorRepositorySpec.php, components/identifier-generator/back/tests/Specification/Infrastructure/Repository/InMemorySimpleSelectNomenclatureRepositorySpec.php, components/identifier-generator/back/tests/features/updateFamilyNomenclature.feature, components/identifier-generator/back/tests/features/updateSimpleSelectNomenclature.feature
No test on InMemoryFamilyNomenclatureRepository because the implem is being changed in another PR, so it will be added separately
=> CPM-1015: Fix SimpleSelect Nomenclature InMemory repository and add case tests

.circleci/jobs/build_and_deploy.yml
Upgrade cloud-deployer to 7.14
To merge synchronously with : 
https://github.com/akeneo/pim-enterprise-dev/pull/15528
=> SDO-338-pimce Upgrade cloud-deployer to 7.14

.circleci/find_non_executed_phpspec.sh
=> GROWTH-71: Remove feature from non executed phpspecs script

src/Akeneo/Platform/Bundle/InstallerBundle/Command/DatabaseCommand.php
=> Add the --complete to DatabaseCommand

CHANGELOG.md, src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Webhook/services.yml, src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/Client/GuzzleWebhookClient.php, src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/RequestHeaders.php, src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/Service/WebhookReachabilityChecker.php, src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Webhook/Client/GuzzleWebhookClientSpec.php, src/Akeneo/Connectivity/Connection/back/tests/Unit/spec/Infrastructure/Webhook/Service/WebhookReachabilityCheckerSpec.php
=> PIM-10911: Add user-agent when sending an event

src/Akeneo/Pim/Enrichment/Component/Product/Value/ScalarValue.php, tests/back/Pim/Enrichment/Specification/Component/Product/Value/ScalarValueSpec.php
=> CPM-1052: Fix number comparison with \is_numeric

components/catalogs/back/src/Infrastructure/Validation/ProductMapping/AttributeSource/SystemAttributeCategoriesSource.php, components/catalogs/back/src/Infrastructure/Validation/ProductMapping/AttributeSource/SystemAttributeFamilySource.php, components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductMapping/AttributeSource/SystemAttributeCategoriesSourceTest.php, components/catalogs/back/tests/Integration/Infrastructure/Validation/ProductMapping/AttributeSource/SystemAttributeFamilySourceTest.php
=> OCT-243: Error when we select a property source and fill a Default value 

components/identifier-generator/back/src/Domain/Repository/ReferenceEntityNomenclatureRepository.php, components/identifier-generator/back/src/Infrastructure/Repository/InMemoryReferenceEntityNomenclatureRepository.php, components/identifier-generator/back/src/Infrastructure/Repository/SqlReferenceEntityNomenclatureRepository.php, components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/persistence.yml, components/identifier-generator/back/tests/Acceptance/Resources/config/services.yml, components/identifier-generator/back/tests/Integration/Repository/SqlReferenceEntityNomenclatureRepositoryIntegration.php, components/identifier-generator/back/tests/Specification/Infrastructure/Repository/InMemoryReferenceEntityNomenclatureRepositorySpec.php
Add SQL and InMemory repositories for ref entities
=> CPM-1024: Add ref entity nomenclature repositories

CHANGELOG.md, src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/VersioningController.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/controllers.yml, src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/history.js, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/product/history.html, src/Akeneo/Tool/Bundle/VersioningBundle/Doctrine/ORM/VersionRepository.php, src/Akeneo/Tool/Bundle/VersioningBundle/Repository/VersionRepositoryInterface.php, tests/back/Pim/Enrichment/Integration/Controller/VersioningControllerIntegration.php
=> PIM-10929: Add limit on get product history

CHANGELOG.md, src/Akeneo/Pim/Structure/Bundle/Controller/InternalApi/AttributeGroupController.php
=> PIM-10941: Fix unitary attribute group deletion

CHANGELOG-6.0.md, src/Akeneo/Channel/Bundle/EventListener/ChannelLocaleSubscriber.php, src/Akeneo/Channel/Bundle/EventListener/RemoveLocalesFromChannelSubscriber.php, src/Akeneo/Channel/Bundle/Processor/Denormalization/ChannelProcessor.php, src/Akeneo/Channel/Bundle/Resources/config/doctrine/model/Locale.orm.yml, src/Akeneo/Channel/Bundle/Resources/config/processors.yml, src/Akeneo/Channel/Bundle/Resources/config/services.yml, src/Akeneo/Channel/Component/Model/Channel.php, src/Akeneo/Channel/Component/Model/Locale.php, src/Akeneo/Channel/Component/Model/LocaleInterface.php, src/Akeneo/Channel/Component/Updater/ChannelUpdater.php, tests/back/Acceptance/Channel/ChannelContext.php, tests/back/Acceptance/Locale/LocaleContext.php, tests/back/Channel/Integration/Channel/ChannelTestCase.php, tests/back/Channel/Specification/Bundle/EventListener/ChannelLocaleSubscriberSpec.php, tests/back/Channel/Specification/Bundle/EventListener/RemoveLocalesFromChannelSubscriberSpec.php, tests/back/Channel/Specification/Bundle/Processor/Denormalization/ChannelProcessorSpec.php, tests/back/Channel/Specification/Component/Updater/ChannelUpdaterSpec.php, tests/back/Pim/Enrichment/EndToEnd/RemoveLocaleFromChannelEndToEnd.php, tests/features/channel/locale/locale_status.feature
=> PIM-10937: backport PIM-10887

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/Notification.less
=> OCT-245: fixed namespace

CHANGELOG.md, src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/NumberValueFactory.php, src/Akeneo/Pim/Enrichment/Component/Product/Value/NumberValue.php, src/Akeneo/Pim/Enrichment/Component/Product/Value/ScalarValue.php, src/Akeneo/Pim/Enrichment/Product/back/Test/Integration/Handler/UpsertProductIntegration.php, tests/back/Pim/Enrichment/Integration/Storage/Sql/Connector/SqlGetConnectorProductModelsIntegration.php, tests/back/Pim/Enrichment/Integration/Storage/Sql/Connector/SqlGetConnectorProductsIntegration.php, tests/back/Pim/Enrichment/Integration/Storage/Sql/Connector/SqlGetConnectorProductsWithOptionsIntegration.php, tests/back/Pim/Enrichment/Specification/Component/Product/Factory/Value/NumberValueFactorySpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Value/NumberValueSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Value/ScalarValueSpec.php
Introduces a new Value type: NumberValue. This helps compare values for number attribute types, as the comparison is different from other scalar values 
=> PIM-10948: Fix number value comparison

src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_US.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/system/src/components/SystemIndex.tsx, src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/system/src/components/reset-pim/ResetButton.tsx, src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/system/src/components/reset-pim/ResetButton.unit.tsx, src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/system/src/components/reset-pim/ResetModal.tsx, src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/system/src/components/reset-pim/ResetModal.unit.tsx, src/Akeneo/Platform/Bundle/UIBundle/Resources/workspaces/system/src/components/reset-pim/index.ts
=> RAB-1326: Add Reset PIM confirmation modal

CHANGELOG.md, src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/ProductModelController.php, src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/Product/UpdateProductController.php, src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/ProductModelController.php, src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Updater/TwoWayAssociationUpdater.php, src/Akeneo/Pim/Enrichment/Component/Product/Exception/TwoWayAssociationWithTheSameProductException.php, tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/PartialUpdateProductModelEndToEnd.php
=> PIM-10959: Fix API response when trying to associate a product model to itself in a 2-way association

src/Akeneo/Connectivity/Connection/back/Infrastructure/ErrorManagement/Persistence/PurgeConnectionErrorsQuery.php
=> OCT-251: prevent elasticsearch error

src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/ProductCommentController.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/controllers.yml
=> CPM-1057: Fix user timezone on comments

CHANGELOG.md, src/Akeneo/Pim/Structure/Bundle/Doctrine/ORM/Repository/InternalApi/AttributeSearchableRepository.php, src/Akeneo/Pim/Structure/Bundle/Resources/config/datagrid/attribute.yml, src/Oro/Bundle/PimDataGridBundle/Adapter/OroToPimGridFilterAdapter.php
=> PIM-10950: bring back code filter

src/Akeneo/Category/front/src/feature/components/templates/AttributeSettings.tsx
=> Remove a debug console.log

CHANGELOG.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/lib/select2.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/form/add-select/line.html, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/product/form/add-select/attribute/line.html
=> PIM-10914: Add title and ellipsis for long labels on attribute select

src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml, src/Akeneo/Category/front/src/feature/components/DiscoverEnrichedCategoriesInformationHelper.tsx
=> GRF-834: update category helper

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/app.html, src/Akeneo/Platform/Bundle/UIBundle/Resources/views/index.html.twig, src/Akeneo/UserManagement/Bundle/Resources/views/layout.html.twig
=> GROWTH-127: Implements div elements for login & pim cookie consent

components/identifier-generator/back/src/Application/Exception/UndefinedAttributeException.php, components/identifier-generator/back/src/Application/Exception/UnexpectedAttributeTypeException.php, components/identifier-generator/back/src/Application/Get/GetNomenclatureHandler.php, components/identifier-generator/back/src/Application/Update/UpdateNomenclatureHandler.php, components/identifier-generator/back/src/Infrastructure/Controller/GetNomenclatureController.php, components/identifier-generator/back/src/Infrastructure/Controller/UpdateNomenclatureController.php, components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/command_handlers.yml, components/identifier-generator/back/tests/.php_cd.php, components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/GetNomenclatureControllerEndToEnd.php, components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/UpdateFamilyNomenclatureControllerEndToEnd.php, components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/UpdateReferenceEntityNomenclatureControllerEndToEnd.php, components/identifier-generator/back/tests/EndToEnd/Infrastructure/Controller/UpdateSimpleSelectNomenclatureControllerEndToEnd.php
Handle ref entities in GetNomenclatureController and UpdateNomenclatureController
=> CPM-1027: Get and Update Ref entities nomenclatures

src/Akeneo/Category/front/src/feature/components/templates/AttributeList.tsx
=> GRF-831 : Change back wording to textArea for rich text

src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Product/SqlGetValuesOfSiblings.php, src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/UniqueVariantAxisValidator.php, src/Akeneo/Pim/Enrichment/Component/Product/Validator/UniqueAxesCombinationSet.php, tests/back/Pim/Enrichment/Integration/Product/Import/ImportProductsIntegration.php, tests/back/Pim/Enrichment/Integration/Storage/Sql/Product/SqlGetValuesOfSiblingsIntegration.php, tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/UniqueVariantAxisValidatorSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Validator/UniqueAxesCombinationSetSpec.php
=> PIM-10949: Fix import duplicate variant products without identifier

src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/Db/InitProductCompletenessDbSchemaSubscriber.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/event_subscribers.yml, upgrades/schema/Version_8_0_20230509160000_new_table_completeness.php, upgrades/test_schema/Version_8_0_20230509160000_new_table_completeness_Integration.php
=> CPM-1039: Create new table for completeness

.circleci/config.yml
=> Remove nightly builds on 5.0

src/Akeneo/Tool/Bundle/BatchQueueBundle/Resources/config/services.yml, src/Akeneo/Tool/Bundle/MessengerBundle/tests/integration/JsonSerializerIntegration.php, src/Akeneo/Tool/Component/BatchQueue/Normalizer/ScheduledJobMessageNormalizer.php
Add the missing ScheduledJobMessageNormalizer
Also add integration tests for JsonSerializer to test all the serializer stack. Specs were not enough to detect the missing part about scheduled jobs.
=> PH-1021: Add ScheduledJobMessageNormalizer

std-build/install-required-files.sh, std-build/package.json
=> Fix standard that does not pass since fpm and httpd have been merged and catalog have been moved to EE

config/services/pim_parameters.yml, src/Akeneo/Tool/Bundle/VersioningBundle/Command/PurgeCommand.php, src/Akeneo/Tool/Bundle/VersioningBundle/Resources/config/cli_commands.yml, src/Akeneo/Tool/Bundle/VersioningBundle/tests/integration/Command/PurgeVersioningCommandIntegration.php
=> CPM-839: Add env parameter for Product Version retention

CHANGELOG.md, src/Akeneo/UserManagement/Component/Model/User.php, src/Akeneo/UserManagement/Component/Model/UserInterface.php
We add a method to the User model to check if it is of type 'user' (UI user).
The real fix happen in EE: https://github.com/akeneo/pim-enterprise-dev/pull/17401
=> PIM-10977 make control on user type more strict during log in

components/identifier-generator/back/src/Application/Generate/Property/PropertyProcessApplier.php, components/identifier-generator/back/src/Infrastructure/Symfony/Resources/config/command_handlers.yml, components/identifier-generator/back/tests/EndToEnd/Infrastructure/Subscriber/SetIdentifiersSubscriberEndToEnd.php, components/identifier-generator/back/tests/Specification/Application/Generate/Property/PropertyProcessApplierSpec.php
=> CPM-1025: Handle ref entity nomenclature in PropertyProcessApplier

components/identifier-generator/back/src/Application/Get/GetGeneratorHandler.php, components/identifier-generator/back/src/Application/Get/GetGeneratorQuery.php, components/identifier-generator/back/src/Application/Get/GetGeneratorsHandler.php, components/identifier-generator/back/src/Application/Get/GetGeneratorsQuery.php, components/identifier-generator/back/src/Application/Get/GetNomenclatureHandler.php, components/identifier-generator/back/src/Application/Get/GetNomenclatureQuery.php, components/identifier-generator/back/src/Infrastructure/Controller/CreateIdentifierGeneratorController.php, components/identifier-generator/back/src/Infrastructure/Controller/GetIdentifierGeneratorController.php, components/identifier-generator/back/src/Infrastructure/Controller/GetNomenclatureController.php, components/identifier-generator/back/src/Infrastructure/Controller/ListIdentifierGeneratorController.php, components/identifier-generator/back/src/Infrastructure/Controller/UpdateIdentifierGeneratorController.php
=> CPM-1058: Rename commands retrieving data to queries

tests/back/Pim/Enrichment/Integration/Controller/VersioningControllerIntegration.php
=> CPM-1062: Remove Category coupling

src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml, src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Completeness/DoubleStorageCompletenesses.php, src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Completeness/SqlSaveCompletenesses.php, tests/back/Pim/Enrichment/Integration/Storage/Sql/Completeness/SqlSaveCompletenessesIntegration.php, tests/back/Pim/Enrichment/Specification/Bundle/Storage/Sql/Completeness/DoubleStorageCompletenessesSpec.php
=> CPM-1045: On product save, update/fill the new completeness table

CHANGELOG-6.0.md, src/Akeneo/UserManagement/Bundle/EventListener/RemoveRoleSubscriber.php, tests/back/UserManagement/Integration/Bundle/RemoveRoleIntegration.php
=> Pim 10997 Update error message on role deletion

src/Akeneo/Pim/Enrichment/Bundle/Command/ZddMigrations/V20230512143522FillNewCompletenessTableZddMigration.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/cli_command.yml, tests/back/Pim/Enrichment/Integration/Product/V20230512143522FillNewCompletenessTableZddMigrationIntegration.php, tests/back/Pim/Enrichment/Integration/Storage/Sql/Completeness/SqlSaveCompletenessesIntegration.php, tests/back/Pim/Enrichment/Specification/Bundle/Storage/Sql/Completeness/DoubleStorageCompletenessesSpec.php
=> CPM-1046: Migration to fill with current completeness data

CHANGELOG.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/form/form-tabs.html
=> PIM-10966: Fix JS error on toggling tabs on an export profile editing page

src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Completeness/SqlSaveCompletenesses.php
=> PIM-1045-bis: fix number of queries to save completeness

CHANGELOG-7.0.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/common/file-path.js
=> Pullup 7.0 => master

src/Akeneo/Connectivity/Connection/back/Infrastructure/Webhook/EventsApiDebug/Controller/Internal/SearchEventSubscriptionLogsAction.php
=> OCT-262: Error on event API search subscription logs due tu bad json_decode exception

src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Query/SqlGetProductCompletenessRatio.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml, src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Completeness/SqlGetCompletenesses.php, src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Completeness/SwitchSqlGetCompleteness.php, src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductGrid/FetchProductRowsFromUuids.php, tests/back/Pim/Enrichment/Integration/Completeness/SqlGetProductCompletenessRatioIntegration.php, tests/back/Pim/Enrichment/Integration/Storage/Sql/Completeness/GetProductCompletenessesIntegration.php, tests/back/Pim/Enrichment/Specification/Bundle/Storage/Sql/Completeness/SwitchSqlGetCompletenessSpec.php
=> CPM-1041: Get Completenesses from new table

.circleci/jobs/build_and_deploy.yml
Upgrade cloud-deployer to latest version for PIM CE CI.
Details here : https://github.com/akeneo/cloud-tools/blob/master/cloud-deployer/CHANGELOG.md
=> SAAS-754-pim-ce Upgrade cloud-deployer

.circleci/jobs/features/other.yml, docker-compose.yml
Start gcs-emulator container for **test_back_phpunit**
=> fix-ci-gcs

src/Akeneo/Tool/Bundle/BatchQueueBundle/Command/JobExecutionWatchdogCommand.php
Add job information in Watchdog logs to better track and debug
=> PIM-11025: :chart_with_upwards_trend: Enrich watchdog logs

src/Akeneo/Category/back/Application/Command/AddAttributeCommandHandler.php, src/Akeneo/Category/back/Domain/Query/UpdateCategoryTemplateAttributesOrder.php, src/Akeneo/Category/back/Domain/ValueObject/Attribute/AttributeCollection.php, src/Akeneo/Category/back/Infrastructure/EventSubscriber/ReorderTemplateAttributesOnAttributeDeactivatedSubscriber.php, src/Akeneo/Category/back/Infrastructure/Storage/Sql/UpdateCategoryTemplateAttributesOrderSql.php, src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/queries.yml, src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/subscribers.yml, src/Akeneo/Category/back/tests/EndToEnd/InternalApi/DeactivateAttributeControllerEndToEnd.php, src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/UpdateCategoryTemplateAttributesOrderSqlIntegration.php, src/Akeneo/Category/back/tests/Specification/Domain/ValueObject/Attribute/AttributeCollectionSpec.php
=> GRF-830 reindex template attribute order after add/delete attribute

src/Akeneo/Pim/Enrichment/Component/Product/Connector/Writer/Database/ProductAssociationWriter.php, src/Akeneo/Pim/Enrichment/Component/Product/Connector/Writer/Database/ProductModelWriter.php, src/Akeneo/Pim/Enrichment/Component/Product/Connector/Writer/Database/ProductWriter.php, src/Akeneo/Pim/Structure/Component/Writer/Database/AttributeGroupWriter.php, src/Akeneo/Tool/Component/Connector/Reader/File/Csv/Reader.php, src/Akeneo/Tool/Component/Connector/Reader/File/Xlsx/Reader.php, src/Akeneo/Tool/Component/Connector/Reader/File/Yaml/Reader.php, src/Akeneo/UserManagement/Component/Connector/Writer/Database/RoleWithPermissionsWriter.php
=> RAB-1414: paused import

src/Akeneo/Connectivity/Connection/front/src/common/components/PageContent.tsx, src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApp/Catalog/ConnectedAppCatalogContainer.tsx, src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApp/ConnectedAppContainer.tsx
EE: https://github.com/akeneo/pim-enterprise-dev/pull/17662
=> CXP-1499: Add scroll bars on the target list and the source panel

CHANGELOG.md, src/Oro/Bundle/PimFilterBundle/Filter/Product/LabelOrIdentifierFilter.php, src/Oro/Bundle/PimFilterBundle/spec/Filter/Product/LabelOrIdentifierFilterSpec.php, src/Oro/Bundle/PimFilterBundle/spec/Filter/ProductValue/StringFilterSpec.php, tests/back/Pim/Enrichment/Integration/PQB/AbstractProductAndProductModelQueryBuilderTestCase.php, tests/back/Pim/Enrichment/Integration/PQB/Filter/LabelOrIdentifierFilterIntegration.php
Fix product search containing underscores
=> PIM-11023 : Fix product search containing underscores

src/Akeneo/UserManagement/Bundle/Resources/public/js/form/unsupported-ui-locale-warning.tsx, src/Akeneo/UserManagement/Bundle/Resources/translations/jsmessages.en_US.yml
=> GRF-859 : Add link to crowdin on unsuported UI local warning

src/Akeneo/Pim/Structure/Bundle/Doctrine/ORM/Repository/AttributeRepository.php
Fix performance using cache for identifier code
=> Add cache for identifierCode

src/Akeneo/Category/front/src/feature/components/attributes/templateAttributesFactory.tsx
=> GRF-850 : Fix empty label not replaced by [code]

src/Akeneo/Platform/Bundle/ImportExportBundle/Repository/InternalApi/JobExecutionRepository.php, src/Akeneo/Tool/Bundle/VersioningBundle/tests/integration/Command/PurgeVersioningCommandIntegration.php, tests/back/Platform/Integration/ImportExport/Repository/InternalApi/JobExecutionRepositoryIntegration.php
We need to add a condition on the `health_check_time` to avoid being blocked by a crashed job execution
=> PH-1086: :ambulance: Improve job uniqueness check

src/Akeneo/Tool/Bundle/BatchQueueBundle/MessageHandler/JobMessageHandler.php
=> PH-1087: :loud_sound: Add tenant ID in log record context when possible

CHANGELOG.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/creation/identifier.js, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/form/creation/field.html
Add permissions check on attribute group & attribute "read_only" property
=> PIM-11040: Sku is disabled according to the rights

src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Product/SqlUpdateIdentifierValuesQuery.php
Migration and the use of the table were shiped inside the same release, so we check whether the table exists before using it.
Link to this ticket: https://akeneo.atlassian.net/browse/PIM-11045
=> PIM-11045: Check whether the table exists before using it

src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
=> GRF-844: change deactivate template naming

src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Query/ProductEvaluation/GetEntityIdsToEvaluateQueryInterface.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetProductModelIdsToEvaluateQuery.php, src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetProductUuidsToEvaluateQuery.php, src/Akeneo/Platform/Bundle/InstallerBundle/Command/MigrateZddCommand.php, src/Akeneo/Platform/Bundle/InstallerBundle/Exception/UcsOnlyMigrationException.php
The goal is to be able to launch a ZddMigration only on pim that are on the UCS platform
=> JEL-357: Add Exception to ignore Zdd migration on non-UCS platform

CHANGELOG.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/group-selector.js
=> PIM-11041: Fix null has attribute group code broke the pef

CHANGELOG.md, src/Akeneo/Platform/Bundle/ImportExportBundle/Command/PurgeJobExecutionCommand.php, src/Akeneo/Platform/Bundle/ImportExportBundle/Job/JobParameters/PurgeJobExecutions.php, src/Akeneo/Platform/Bundle/ImportExportBundle/Job/PurgeJobExecutions.php, src/Akeneo/Platform/Bundle/ImportExportBundle/Purge/PurgeJobExecution.php, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/group-selector.js, src/Akeneo/Tool/Bundle/BatchBundle/Persistence/Sql/DeleteJobExecution.php, src/Akeneo/Tool/Bundle/BatchBundle/Persistence/Sql/GetJobExecutionIds.php, src/Akeneo/Tool/Bundle/BatchBundle/Storage/DeleteJobExecutionLogs.php, tests/back/Tool/Integration/Batch/Persistence/Sql/DeleteJobExecutionIntegration.php, tests/back/Tool/Integration/Batch/Persistence/Sql/GetJobExecutionIdsIntegration.php
=> PIM-10931: Add possibility to filter job execution to purge by status and job_instance_code

components/identifier-generator/back/src/Infrastructure/Subscriber/SetIdentifiersSubscriber.php, components/identifier-generator/back/tests/.php_cd.php, components/identifier-generator/back/tests/Specification/Infrastructure/Subscriber/SetIdentifiersSubscriberSpec.php
=> CPM-1083: Use IdentifierValue in SetIdentifierSubscriber

.circleci/jobs/build_and_deploy.yml
Remove old CI workflow step used by the V1 of the BigCommerce connector.
=> BC: rm bigcommerce step from ci workflow

src/Akeneo/Connectivity/Connection/back/Application/Apps/Command/RequestAppAuthorizationCommand.php, src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/validation/RequestAppAuthorizationCommand.yml, src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml
=> OCT-270: fix validation for the scope variable

src/Akeneo/Platform/Bundle/FeatureFlagBundle/Configuration/OnlySaasSandboxFeatureFlag.php
see https://github.com/akeneo/pim-enterprise-dev/pull/17868
=> PIM-11051: Add OnlySaasSandboxFeatureFlag

src/Akeneo/Category/back/Application/Command/LoadAttributeSet/LoadAttributeSetCommand.php, src/Akeneo/Category/back/Application/Command/LoadAttributeSet/LoadAttributeSetCommandHandler.php, src/Akeneo/Category/back/Domain/AttributeSetFactory.php, src/Akeneo/Category/back/Infrastructure/Controller/InternalApi/LoadAttributeSetController.php, src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/controllers.yml, src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/factories.yml, src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/handlers.yml, src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/routing/internal_api/category_template.yml, src/Akeneo/Category/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml, src/Akeneo/Category/back/tests/EndToEnd/InternalApi/LoadAttributeSetControllerEndToEnd.php, src/Akeneo/Category/front/src/feature/components/templates/EditTemplateAttributesForm/InitializeTemplateChoice.tsx, src/Akeneo/Category/front/src/feature/components/templates/EditTemplateAttributesForm/LoadAttributeSetModal.tsx
=> GRF-873: add load attribute set command

src/Akeneo/Category/front/src/feature/components/templates/AddTemplateAttributeModal.tsx, src/Akeneo/Category/front/src/feature/components/templates/EditTemplateAttributesForm/InitializeTemplateChoice.tsx, src/Akeneo/Category/front/src/feature/components/templates/EditTemplateAttributesForm/LoadAttributeSetModal.tsx, src/Akeneo/Category/front/src/feature/hooks/useTrackUsageOfLoadPredefinedAttributes.ts
=> GRF-843: add tracking of template init

config/services/pim_parameters.yml, src/Akeneo/Tool/Bundle/VersioningBundle/Resources/config/cli_commands.yml
=> Fix PIM_VERSIONING_RETENTION_IN_DAYS

CHANGELOG.md, src/Akeneo/Connectivity/Connection/front/src/connect/components/ConnectedApp/ConnectedAppContainer.tsx
Addition of a condition in the view to show the permissions panel in a connected app's settings only if permissions are manageable.
=> PIM-11018: The App section displays the Permission screen on GE/CE PIM.

src/Akeneo/Tool/Bundle/FileStorageBundle/Validator/Constraints/UploadedFile.php, src/Akeneo/Tool/Bundle/FileStorageBundle/Validator/Constraints/UploadedFileValidator.php, src/Akeneo/Tool/Bundle/FileStorageBundle/spec/Validator/Constraints/UploadedFileValidatorSpec.php
Story https://akeneo.atlassian.net/browse/PIM-10869  
First PR https://github.com/akeneo/pim-community-dev/pull/19857
=> PIM-10869: Change image upload error messages to give less information

CHANGELOG-7.0.md, make-file/user-management.mk, src/Akeneo/UserManagement/Bundle/Resources/config/normalizers.yml, src/Akeneo/UserManagement/Bundle/Resources/config/processors.yml, src/Akeneo/UserManagement/Bundle/Resources/config/writers.yml, src/Akeneo/UserManagement/Component/Connector/Processor/Denormalization/UserProcessor.php, src/Akeneo/UserManagement/Component/Normalizer/DateTimeNormalizer.php, src/Akeneo/UserManagement/Component/Normalizer/Standard/UserNormalizer.php, src/Akeneo/UserManagement/Component/Updater/UserUpdater.php, tests/back/UserManagement/Integration/Bundle/Export/ExportUserIntegration.php, tests/back/UserManagement/Integration/Bundle/Import/ImportUserIntegration.php, tests/back/UserManagement/Specification/Component/Connector/Processor/Denormalization/UserProcessorSpec.php, tests/back/UserManagement/Specification/Component/Normalizer/DateTimeNormalizerSpec.php, tests/back/UserManagement/Specification/Component/Normalizer/Standard/UserNormalizerSpec.php
=> GRF-872: [Backport GRF-669] Add 4 field columns (properties) to the user export job profile

src/Akeneo/Channel/back/Infrastructure/Symfony/Resources/config/jobs.yml, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/jobs.yml, src/Akeneo/Pim/Structure/Bundle/Resources/config/jobs.yml, src/Akeneo/Tool/Bundle/BatchBundle/EventListener/PauseJobOnSigtermSubscriber.php, src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/services.yml, src/Akeneo/Tool/Bundle/BatchBundle/Resources/config/test/jobs.yml, src/Akeneo/Tool/Bundle/BatchBundle/tests/Integration/EventListener/PauseJobOnSigtermSubscriberIntegration.php, src/Akeneo/Tool/Component/Batch/Job/Job.php, src/Akeneo/Tool/Component/Batch/Job/PausableJobInterface.php, src/Akeneo/UserManagement/Bundle/Resources/config/jobs.yml
=> RAB-1415: Pause Jobs only when they are actually Pausable

src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Attribute/IdentifierFilter.php, src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Field/IdentifierFilter.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/query_builders.yml, src/Akeneo/Pim/Structure/Bundle/Query/PublicApi/Attribute/Cache/CachedGetMainIdentifierAttributeCode.php, src/Akeneo/Pim/Structure/Bundle/Query/PublicApi/Attribute/Sql/SqlGetMainIdentifierAttributeCode.php, src/Akeneo/Pim/Structure/Bundle/Resources/config/queries.yml, src/Akeneo/Pim/Structure/Component/Query/PublicApi/Attribute/GetMainIdentifierAttributeCode.php, tests/back/Pim/Enrichment/Integration/PQB/AbstractProductAndProductModelQueryBuilderTestCase.php, tests/back/Pim/Enrichment/Integration/PQB/AbstractProductQueryBuilderTestCase.php, tests/back/Pim/Enrichment/Integration/PQB/Filter/Field/ProductAndProductModelIdentifierFilterIntegration.php, tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Filter/Attribute/IdentifierFilterSpec.php, tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Filter/Field/IdentifierFilterSpec.php
=> CPM-1084: Update ES Identifier filters to use main identifier attribute

src/Akeneo/Tool/Component/Batch/Job/Job.php, src/Akeneo/Tool/Component/Batch/Step/AbstractStep.php, src/Akeneo/Tool/Component/Batch/spec/Step/ItemStepSpec.php
=> RAB-1446: Fix Job and Step execution start time when a job resume

src/Akeneo/Tool/Bundle/FileStorageBundle/Resources/config/internal_api.yml
https://akeneo.atlassian.net/browse/PIM-11077
=> PIM-11077: Add missing supported image types

CHANGELOG-6.0.md, src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/UniqueVariantAxisValidator.php, src/Akeneo/Pim/Enrichment/Component/Product/Validator/UniqueAxesCombinationSet.php, tests/back/Pim/Enrichment/Specification/Component/Product/Validator/Constraints/UniqueVariantAxisValidatorSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Validator/UniqueAxesCombinationSetSpec.php
=> PIM-11008: Pull up 6.0 to 7.0

CHANGELOG.md, src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml, src/Akeneo/Pim/Structure/Bundle/Resources/config/datagrid/attribute.yml, src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/search-filter.js
=> PIM-11072: Fix missing translation key

src/Akeneo/Category/front/src/feature/components/DiscoverEnrichedCategoriesInformationHelper.tsx
=> GRF: add survey monkey link on enrich category

src/Akeneo/Tool/Component/Connector/Reader/File/Csv/Reader.php, src/Akeneo/Tool/Component/Connector/Reader/File/Xlsx/Reader.php, src/Akeneo/Tool/Component/Connector/spec/Reader/File/Xlsx/ReaderSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Reader/File/Xlsx/ProductModelReaderSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Reader/File/Xlsx/ProductReaderSpec.php, tests/back/UserManagement/Specification/Component/Connector/Reader/File/XlsxUserReaderSpec.php
=> RAB-1463: fix iterator pointer on resume

.circleci/jobs/features/other.yml, .circleci/workflows/pull_request.yml
see https://github.com/akeneo/pim-enterprise-dev/pull/17237
=> RAC-1302: Add test job declaration step to CI

CHANGELOG.md, src/Akeneo/Platform/Job/back/Infrastructure/Symfony/Resources/translations/jsmessages.en_US.yml, src/Akeneo/Tool/Bundle/ConnectorBundle/Resources/translations/jsmessages.en_US.yml
see https://github.com/akeneo/pim-enterprise-dev/pull/18073
=> PIM-11090: Add missing translations for Process Tracker

CHANGELOG.md, src/Akeneo/Tool/Bundle/FileStorageBundle/Validator/Constraints/UploadedFileValidator.php, src/Akeneo/Tool/Bundle/FileStorageBundle/spec/Validator/Constraints/UploadedFileValidatorSpec.php
https://akeneo.atlassian.net/browse/PIM-11095
=> PIM-11095: Make image extension check case insensitive

src/Akeneo/Connectivity/Connection/back/tests/EndToEnd/Webhook/ConsumeProductEventEndToEnd.php, src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/ExternalApi/ConnectorProductNormalizer.php, tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/GetProductEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/ListProductWithCompletenessEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/SuccessListProductEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/SuccessListVariantProductDeltaEndToEnd.php, tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/ExternalApi/ConnectorProductNormalizerSpec.php
In this PR, we remove the filtering of the main identifier value in the GET and LIST product API endpoints
=> CPM-1075: Display main identifier value in GET and LIST product endpoints

tests/back/Pim/Structure/Integration/Attribute/UpdateAttributeDateIntegration.php
=> CPM-1133: Add tests on date update after main identifier update

src/Akeneo/Pim/Structure/Bundle/Application/SwitchMainIdentifier/SwitchMainIdentifierCommand.php, src/Akeneo/Pim/Structure/Bundle/Application/SwitchMainIdentifier/SwitchMainIdentifierHandler.php, src/Akeneo/Pim/Structure/Bundle/Application/SwitchMainIdentifier/SwitchMainIdentifierValidator.php, src/Akeneo/Pim/Structure/Bundle/Controller/InternalApi/SwitchMainIdentifierController.php, src/Akeneo/Pim/Structure/Bundle/Resources/config/controllers.yml, src/Akeneo/Pim/Structure/Bundle/Resources/config/handlers.yml, src/Akeneo/Pim/Structure/Bundle/Resources/config/routing/internal_api/attribute.yml, src/Akeneo/Pim/Structure/Bundle/Resources/config/validators.yml, tests/back/Pim/Structure/EndToEnd/Attribute/InternalApi/SwitchMainIdentifierControllerEndToEnd.php, tests/back/Pim/Structure/Integration/Attribute/SwitchMainIdentifierIntegration.php, tests/back/Pim/Structure/Integration/Attribute/UpdateAttributeDateIntegration.php
This PR introduce
- A new endpoint for the end users
- A Command to switch main identifier
- A Handler to execute the Query
- A Validator to be sure the command is executable
=> CPM-1067: Add endpoint to switch main identifier

CHANGELOG-6.0.md, src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/AppRoleWithScopesFactory.php, src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Persistence/Query/IncreaseLabelLengthQuery.php, src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Apps/persistence.yml, src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/Resources/config/Apps/services.yml, src/Akeneo/Connectivity/Connection/back/tests/Integration/Apps/Persistence/Query/IncreaseLabelLengthQueryIntegration.php, src/Akeneo/UserManagement/Bundle/Resources/config/model/doctrine/Role.orm.yml
Pull up of [PIM-11070](https://github.com/akeneo/pim-community-dev/pull/19950)
[PIM-11070]: https://akeneo.atlassian.net/browse/PIM-11070?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PIM-11070: Pull-up 6.0 to 7.0

src/Akeneo/Category/back/tests/Integration/Application/Command/DeleteCategoryCommand/DeleteCategoryCommandHandlerIntegration.php
Test is randomly failing so it has been decided to increase it for now.
=> Fix category id to delete in test

CHANGELOG.md, src/Akeneo/Category/back/Application/Command/CleanCategoryTemplateAttributeAndEnrichedValues/CleanCategoryTemplateAttributeAndEnrichedValuesCommandHandler.php, src/Akeneo/Category/back/Application/Query/GetDeactivatedAttribute.php, src/Akeneo/Category/back/Infrastructure/Storage/Sql/GetDeactivatedCategoryTemplateAttributeSql.php, src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/handlers.yml, src/Akeneo/Category/back/Infrastructure/Symfony/Resources/config/queries.yml, src/Akeneo/Category/back/tests/Integration/Application/Command/CleanCategoryTemplateAttributeAndEnrichedValues/CleanCategoryTemplateAttributeAndEnrichedValuesCommandHandlerIntegration.php, src/Akeneo/Category/back/tests/Integration/Infrastructure/Storage/Sql/GetDeactivatedCategoryTemplateAttributeSqlIntegration.php
=> PIM-11103: Fix deletion of enriched category attribute when deleting attribute

src/Akeneo/Pim/Enrichment/.php_cd.php, src/Akeneo/Pim/Enrichment/Bundle/Controller/Ui/FileController.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/controllers.yml, src/Akeneo/Tool/Component/FileStorage/spec/File/FileStorerSpec.php
=> PIM-11078: Double check file Mime Type before upload

tests/back/Pim/Structure/Integration/AttributeGroup/Query/SqlFindAttributeCodesForAttributeGroupIntegration.php
This test started to fail with EE fixtures because we already have an attribute with `id: 1`, resulting in a conflict.
I removed the ids from the test to make it more stable.
=> Fix unstable test in community

src/Akeneo/Pim/Structure/Bundle/Resources/config/datagrid/attribute.yml, src/Oro/Bundle/PimDataGridBundle/Resources/config/requirejs.yml, src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/cell/attribute-type-cell.js, src/Oro/Bundle/PimDataGridBundle/Resources/translations/jsmessages.en_US.yml
=> CPM-1164: Add is main identifier information to attribute datagrid

src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Messenger/LaunchProductAndProductModelEvaluationsHandler.php, src/Akeneo/Tool/Bundle/MessengerBundle/Process/RunMessageProcess.php, src/Akeneo/Tool/Bundle/MessengerBundle/Serialization/JsonSerializer.php, src/Akeneo/Tool/Bundle/MessengerBundle/spec/Serialization/JsonSerializerSpec.php
Fix message logs from the sub process. They were not redirect to stdin/stderr of the main process.
Also fix the retry process because message headers should be strings
=> JEL fix messaging logs

CHANGELOG-6.0.md
=> PIM-11117: Pull-up from 6.0 to 7.0

CHANGELOG-6.0.md, src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Connector/SqlGetConnectorProductsWithOptions.php, src/Akeneo/Pim/Structure/Bundle/Form/Type/AttributeOptionType.php, src/Akeneo/Pim/Structure/Component/Normalizer/Standard/AttributeOptionNormalizer.php, tests/back/Pim/Enrichment/Integration/Storage/Sql/Connector/SqlGetConnectorProductsWithOptionsIntegration.php, tests/back/Pim/Structure/EndToEnd/AttributeOption/ExternalApi/GetAttributeOptionEndToEnd.php, tests/back/Pim/Structure/Specification/Bundle/Form/Type/AttributeOptionTypeSpec.php
Backport of : https://akeneo.atlassian.net/browse/PIM-10844
=> PIM-11106: Filter empty attribute option labels

CHANGELOG-6.0.md, front-packages/shared/src/components/CategoryTree/CategoryTree.tsx, front-packages/shared/src/components/CategoryTree/RecursiveCategoryTree.tsx, src/Akeneo/Platform/Bundle/UIBundle/tests/front/unit/components/CategoryTree/RecursiveCategoryTree.unit.tsx
Fix checkboxes on category trees
=> [Backport PIM-10868] PIM-11123: Fix checkboxes on category trees

composer.json, composer.lock
See https://github.com/akeneo/pim-enterprise-dev/pull/18645
=> RAB: Fix Spout to 4.15 version for now

CHANGELOG-6.0.md, src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/column-selector.ts
Backport of https://github.com/akeneo/pim-enterprise-dev/pull/18739
=> [Backport PIM-11155]

.circleci/workflows/editions/community.yml
=> Removes nightly ci

.circleci/jobs/features/other.yml, .circleci/workflows/pull_request.yml, tests/back/Integration/IntegrationTestsBundle/Loader/FixturesLoader.php, upgrades/test_schema/Version_6_0_20210527144217_dqi_init_recompute_products_scores_Integration.php
In this PR, I launched the `InstallerEvents::PRE_LOAD_FIXTURES` when we load the catalog in test in order to have the `data_quality_insights_evaluations` job installed
=> PIM-10589: Launch event in order to have all job installed

.circleci/workflows/editions/community.yml
=> RAB-FIX: Fix nightly docker is no more built

CHANGELOG-6.0.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/lib/bootstrap.switch.less
=> PIM-11192: Fix boolean switch for Japan locale

src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/yml_base_export_edit.yml
=> RAB-1598: [7.0] Remove global settings tab from YML export profile

src/Akeneo/Pim/Structure/Component/AttributeTypes.php, src/Akeneo/Platform/Bundle/InstallerBundle/Command/CheckAttributesCompatibilityWithSaasCommand.php, src/Akeneo/Platform/Bundle/InstallerBundle/Resources/config/cli_command.yml, tests/back/Platform/Integration/Installer/CheckAttributesCompatibilityWithSaasCommandIntegration.php
In order to check compatibility of the PIM with future versions, this command will check whether the database contains unknown attribute types/backend types, and fail if any is found.
=> PIM-11163: Create command to verify attribute types in the database

src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Repository/ProductModelRepository.php
=> [Backport] - PIM-11318: Fix out of memory

CHANGELOG-7.0.md
=> PIM-11318: Add changelog

CHANGELOG-7.0.md, src/Oro/Bundle/PimDataGridBundle/Controller/Rest/DatagridViewController.php
Backport https://github.com/akeneo/pim-enterprise-dev/pull/20555
=> PIM-11354: Backport PIM-11345 into 7.0

CHANGELOG-7.0.md, src/Akeneo/Pim/Enrichment/.php_cd.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/jobs.yml, src/Akeneo/Pim/Enrichment/Component/Product/Job/ComputeCompletenessOfProductsFamilyTasklet.php, tests/back/Pim/Enrichment/Specification/Component/Product/Job/ComputeCompletenessOfProductsFamilyTaskletSpec.php
Backport of
https://github.com/akeneo/pim-community-dev/pull/19280/commits/0bcc84d0b2452e9866868c3d666a7ebf7d6aae1e
=> PIM-11388: Backport PIM-10832 into 7.0

CHANGELOG-7.0.md, src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/StorageClient/Local/LocalStorageClientProvider.php
**Description (for contributor and lead developer)**
In this PR, I resolved an access rights issue on folders occurring during an export in order to allow other users and groups to read the folder
=> PIM-11405: Fix permission on created files on local storage

CHANGELOG-7.0.md, src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Sorter/Field/FamilySorter.php, tests/back/Pim/Enrichment/Integration/PQB/Sorter/FamilySorterIntegration.php, tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Sorter/Field/FamilySorterSpec.php
Backport : https://github.com/akeneo/pim-enterprise-dev/pull/21570
=> PIM-11407 [backport] Fix Family sorting on product grid

CHANGELOG-7.0.md, src/Akeneo/Platform/Bundle/ImportExportBundle/Infrastructure/StorageClient/Local/LocalStorageClientProvider.php
Improvement of https://github.com/akeneo/pim-community-dev/pull/20409 asked by Support
=> PIM-11405: Permissions should be 655 and 755

CHANGELOG-7.0.md, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/array_converter.yml, src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/FlatToStandard/Product.php, src/Akeneo/Pim/Enrichment/Component/Product/Connector/ArrayConverter/FlatToStandard/ProductAssociation.php, src/Akeneo/Pim/Enrichment/Component/Product/Connector/Processor/Denormalizer/ProductAssociationProcessor.php, src/Akeneo/Pim/Enrichment/Component/Product/Connector/Processor/Denormalizer/ProductProcessor.php, tests/back/Pim/Enrichment/Integration/Product/Import/ImportProductsIntegration.php, tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ArrayConverter/FlatToStandard/ProductSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Processor/Denormalizer/ProductAssociationProcessorSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Processor/Denormalizer/ProductProcessorSpec.php
=> PIM-11496: fix import in v7 without SKU

CHANGELOG-7.0.md, src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/CountItemsWithAttributeValueAction.php, src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/ProductAndProductModel/CountProductModelsWithRemovedAttribute.php, src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/ProductAndProductModel/CountProductsWithRemovedAttribute.php, src/Akeneo/Pim/Enrichment/Component/Product/Query/CountProductModelsWithRemovedAttributeInterface.php, src/Akeneo/Pim/Enrichment/Component/Product/Query/CountProductsWithRemovedAttributeInterface.php, src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/attribute/form/delete/DeleteModal.tsx, tests/back/Pim/Enrichment/Integration/Fixture/ProductAndProductModelWithRemovedAttributeLoader.php, tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductAndProductModel/CountProductModelsWithRemovedAttributeIntegration.php, tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductAndProductModel/CountProductsWithRemovedAttributeIntegration.php, tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductAndProductModel/GetAllProductIntegration.php, tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductAndProductModel/GetProductExistingAmongIntegration.php, tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductAndProductModel/GetProductIdentifiersWithRemovedAttributeIntegration.php, tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductAndProductModel/GetProductModelIdentifiersWithRemovedAttributeIntegration.php, tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductAndProductModel/GetProductNotSynchronisedBetweenEsAndMysqlIntegration.php
=> PIM-11576 - Backport PIM-10855

CHANGELOG-7.0.md, src/Akeneo/Platform/Bundle/UIBundle/DependencyInjection/Compiler/RegisterGenericProvidersPass.php, src/Akeneo/Tool/Component/FileStorage/File/OutputFileFetcher.php, src/Akeneo/Tool/Component/FileStorage/spec/File/OutputFileFetcherSpec.php, tests/back/Acceptance/Channel/InMemoryFindActivatedCurrencies.php
=> PIM-11673: backport 11670 ce side

.circleci/jobs/features/other.yml, CHANGELOG-7.0.md, src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Versioning/Product/MetricNormalizer.php, src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Versioning/Product/ValueNormalizer.php, tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/Versioning/Product/MetricNormalizerSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/Versioning/Product/ValueNormalizerSpec.php
see https://github.com/akeneo/pim-enterprise-dev/pull/18359
=> PIM-11738 [Backport PIM-11108]: Fix number precision in history

src/Akeneo/Platform/Bundle/CommunicationChannelBundle/back/tests/Integration/CommunicationChannel/Api/ApiFindAnnouncementItemsIntegration.php, src/Akeneo/Tool/Bundle/FileStorageBundle/Adapter/MicrosoftAzureBlobStorageAdapter.php, src/Akeneo/Tool/Bundle/FileStorageBundle/Auth/StorageSharedKeyCredential.php, src/Akeneo/Tool/Bundle/FileStorageBundle/Client/Azure/MicrosoftAzureBlobClient.php, src/Akeneo/Tool/Bundle/FileStorageBundle/Client/Azure/MicrosoftAzureBlobContainerClient.php, src/Akeneo/Tool/Bundle/FileStorageBundle/Client/Azure/MicrosoftAzureBlobServiceClient.php, src/Akeneo/Tool/Bundle/FileStorageBundle/Domain/Model/Azure/ApiVersion.php, src/Akeneo/Tool/Bundle/FileStorageBundle/Domain/Model/Azure/Blob/Blob.php, src/Akeneo/Tool/Bundle/FileStorageBundle/Domain/Model/Azure/Blob/BlobContainerProperties.php, src/Akeneo/Tool/Bundle/FileStorageBundle/Domain/Model/Azure/Blob/BlobDownloadStreamingResult.php, src/Akeneo/Tool/Bundle/FileStorageBundle/Domain/Model/Azure/Blob/BlobPrefix.php, src/Akeneo/Tool/Bundle/FileStorageBundle/Domain/Model/Azure/Blob/BlobProperties.php, src/Akeneo/Tool/Bundle/FileStorageBundle/Domain/Model/Azure/Blob/GetBlobsOptions.php, src/Akeneo/Tool/Bundle/FileStorageBundle/Domain/Model/Azure/Blob/Requests/Block.php, src/Akeneo/Tool/Bundle/FileStorageBundle/Domain/Model/Azure/Blob/Requests/BlockType.php, src/Akeneo/Tool/Bundle/FileStorageBundle/Domain/Model/Azure/Blob/Requests/PutBlockRequestBody.php, src/Akeneo/Tool/Bundle/FileStorageBundle/Domain/Model/Azure/Blob/Response/ListBlobsResponseBody.php, src/Akeneo/Tool/Bundle/FileStorageBundle/Domain/Model/Azure/Blob/TaggedBlob.php, src/Akeneo/Tool/Bundle/FileStorageBundle/Domain/Model/Azure/Blob/UploadBlobOptions.php, src/Akeneo/Tool/Bundle/FileStorageBundle/Helpers/Azure/ConnectionStringHelper.php, src/Akeneo/Tool/Bundle/FileStorageBundle/Helpers/Azure/MetadataHelper.php, src/Akeneo/Tool/Bundle/FileStorageBundle/Middleware/AddAuthorizationHeaderMiddleware.php, src/Akeneo/Tool/Bundle/FileStorageBundle/Middleware/AddDefaultQueryParamsMiddleware.php, src/Akeneo/Tool/Bundle/FileStorageBundle/Middleware/AddXMsDateHeaderMiddleware.php, src/Akeneo/Tool/Bundle/FileStorageBundle/Middleware/AddXMsVersionMiddleware.php, src/Akeneo/Tool/Bundle/FileStorageBundle/Middleware/ClientFactory.php, src/Akeneo/Tool/Bundle/FileStorageBundle/tests/Integration/Client/Azure/MicrosoftAzureBlobClientTest.php, src/Akeneo/Tool/Bundle/FileStorageBundle/tests/Integration/Client/Azure/MicrosoftAzureBlobContainerClientTest.php, src/Akeneo/Tool/Bundle/FileStorageBundle/tests/Integration/MockGuzzle.php
=> PIM-11831: backport Azure storage adapter

composer.json, composer.lock, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/validators.yml, src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/JobParameters/ConstraintCollectionProvider/ProductCsvExport.php, src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/JobParameters/ConstraintCollectionProvider/ProductXlsxExport.php, src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/Export/ProductFilters.php, src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/Export/ProductFiltersValidator.php, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/filter/attribute/select.js, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/filter/filter.js, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/product/edit/content/data.js, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/FieldContainer.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/filter/filter.html
See: https://github.com/akeneo/pim-enterprise-dev/pull/27664
=> [Backport] PIM-11936: Add reference entity collection filter validator and limit
