akeneo/pim-community-dev

CHANGELOG.md
spec/Pim/Bundle/BaseConnectorBundle/Validator/Import/ProductImportValidatorSpec.php
spec/Pim/Bundle/EnrichBundle/MassEditAction/Operation/AddToGroupsSpec.php
src/Pim/Bundle/BaseConnectorBundle/Validator/Import/ProductImportValidator.php
src/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/ProductRepository.php
src/Pim/Bundle/CatalogBundle/Doctrine/ORM/ProductRepository.php
src/Pim/Bundle/CatalogBundle/Entity/Repository/GroupRepository.php
src/Pim/Bundle/CatalogBundle/Resources/config/validation/product.yml
src/Pim/Bundle/CatalogBundle/Resources/config/validators.yml
src/Pim/Bundle/CatalogBundle/Validator/Constraints/UniqueVariantAxisValidator.php
src/Pim/Bundle/CatalogBundle/Validator/Constraints/UniqueVariantGroup.php
src/Pim/Bundle/CatalogBundle/Validator/Constraints/UniqueVariantGroupValidator.php
src/Pim/Bundle/EnrichBundle/DependencyInjection/PimEnrichExtension.php
src/Pim/Bundle/EnrichBundle/Form/Type/MassEditAction/AddToVariantGroupType.php
src/Pim/Bundle/EnrichBundle/MassEditAction/Operation/AddToVariantGroup.php
src/Pim/Bundle/EnrichBundle/Resources/config/acl.yml
src/Pim/Bundle/EnrichBundle/Resources/config/form_types.yml
src/Pim/Bundle/EnrichBundle/Resources/config/mass_actions.yml
src/Pim/Bundle/EnrichBundle/Resources/config/view_elements/mass_edit.yml
src/Pim/Bundle/EnrichBundle/Resources/translations/messages.en.yml
src/Pim/Bundle/EnrichBundle/Resources/views/MassEditAction/configure/add-to-variant-group.html.twig
src/Pim/Bundle/EnrichBundle/Resources/views/MassEditAction/configure/edit-common-attributes.html.twig
src/Pim/Bundle/EnrichBundle/Resources/views/MassEditAction/warning.html.twig

| New feature?         | Y
| Fixed tickets        | PIM-2458
| DB schema updated?   | N
This pull request intend to remove the ability to add a product to multiple variant groups. I split add to groups and add to variant group in two seperate operations.
Todo :

PIM-2458: handle variant group in mass edit

---

CHANGELOG.md
src/Pim/Bundle/BaseConnectorBundle/Writer/File/CsvProductWriter.php

Fix product media stacktrace regression on missing media on filesystem during an export
| Bug fix?             | Yes
| Tests pass?          | Yes
| Scenarios pass?      | Yes also green on EE
| Checkstyle issues?*  | No
| PMD issues?**        | No
| Changelog updated?   | Yes
| Fixed tickets        | PIM-3664

PIM-3664: Fix product media stacktrace regression on missing media on filesystem

---

features/Context/AssertionContext.php
features/variant-group/remove_attributes_from_variant_group.feature

| Bug fix?             | No
| Tests pass?          | Running
| Scenarios pass?      | Running
| Checkstyle issues?*  | No
| PMD issues?**        | No
| Changelog updated?   | No
| Fixed tickets        | PIM-3693
| DB schema updated?   | No

PIM-3697: Add behat when remove attribute from a variant group

---

CHANGELOG.md
composer.json

| Scenarios pass?      | Y
| Fixed tickets        | PIM-3712

PIM-3712: freeze gedmo/doctrine-extensions to v2.3.10

---

CHANGELOG.md
UPGRADE-1.3.md
app/config/pim_parameters.yml
build.xml
features/Context/FeatureContext.php
src/Akeneo/Bundle/StorageUtilsBundle/AkeneoStorageUtilsBundle.php
src/Akeneo/Bundle/StorageUtilsBundle/DependencyInjection/AkeneoStorageUtilsExtension.php
src/Akeneo/Bundle/StorageUtilsBundle/DependencyInjection/Configuration.php
src/Pim/Bundle/BaseConnectorBundle/DependencyInjection/PimBaseConnectorExtension.php
src/Pim/Bundle/CatalogBundle/DependencyInjection/PimCatalogExtension.php
src/Pim/Bundle/CatalogBundle/PimCatalogBundle.php
src/Pim/Bundle/DataGridBundle/DependencyInjection/Compiler/ResolverPass.php
src/Pim/Bundle/DataGridBundle/DependencyInjection/PimDataGridExtension.php
src/Pim/Bundle/DataGridBundle/Resources/config/data_sources.yml
src/Pim/Bundle/DataGridBundle/Resources/config/extensions.yml
src/Pim/Bundle/EnrichBundle/Resources/config/pim.yml
src/Pim/Bundle/InstallerBundle/Command/DatabaseCommand.php
src/Pim/Bundle/InstallerBundle/DataFixtures/MongoDB/LoadFixturesData.php
src/Pim/Bundle/InstallerBundle/DataFixtures/ORM/LoadFixturesData.php
src/Pim/Bundle/TransformBundle/DependencyInjection/PimTransformExtension.php
src/Pim/Bundle/VersioningBundle/DependencyInjection/PimVersioningExtension.php
src/Pim/Bundle/VersioningBundle/Tests/Unit/DependencyInjection/PimVersioningExtensionTest.php
upgrades/1.2-1.3/common/remove_multiple_variant_groups.php

This PR is transitional. 
Its aim is to rename the **user parameter** `akeneo_storage_utils_storage_driver` to `pim_catalog_product_storage_driver`. Please also note that the **container parameter** `akeneo_storage_utils.storage_driver` has been deleted.  From 1.2 branch, that means the **container parameter** `pim_catalog.storage_driver` has been deleted. This container parameter should be handled directly by AkeneoStorageUtils, which we are not able to do right now.
| New feature?         | N 
| BC breaks?           | Y
| Scenarios pass?      | Y
| …

PIM-3733: rename parameter akeneo_storage_utils_storage_driver 

---

CHANGELOG.md
src/Pim/Bundle/EnrichBundle/Resources/public/js/pim-init.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/pim-scopable.js

| Scenarios pass?      | Y (Build 1867)
| Fixed tickets        | PIM-3632
| DB schema updated?   | N

PIM-3632 : Correctly show scopable attribute icons on scope change

---

CHANGELOG.md
src/Pim/Bundle/UIBundle/Resources/public/css/pim.less

| Bug fix?             | yes
| New feature?         | no
| BC breaks?           | no
| Tests pass?          | yes
| Scenarios pass?      | Yes
| Checkstyle issues?*  | no
| PMD issues?**        | no
| Changelog updated?   | yes
| Fixed tickets        | PIM-3068
| DB schema updated?   | no
| Migration script?    | no
| Doc PR               | no

PIM-3068: Darken navigation arrows in product grid

---

src/Pim/Bundle/DataGridBundle/Resources/translations/jsmessages.en.yml

Missing translation message in users grid
| Checkstyle issues?*  |
| PMD issues?**        |
| Fixed tickets        | PIM-3812
| DB schema updated?   |n
| Migration script?    |n
| Doc PR               |n

PIM-3812 : add translation message

---

CHANGELOG.md
features/acl/assert_acl.feature
src/Pim/Bundle/EnrichBundle/Resources/views/Product/index.html.twig

| Bug fix?             | Yes
| Tests pass?          | Yes
| Scenarios pass?      | Yes
| Checkstyle issues?*  | No
| PMD issues?**        | No
| Changelog updated?   | Yes
| Fixed tickets        | PIM-3758
| DB schema updated?   | No

PIM-3758: hide the caterory tree on products grid if user do not have the right to list categories

---

src/Pim/Bundle/InstallerBundle/DataFixtures/AbstractLoadFixturesData.php

With the `0.4` version of the BatchBundle, we should use  the `--no-log` option to hide all logs during installation.

PIM-3825: Use the new --no-log batch option

---

CHANGELOG.md
spec/Pim/Bundle/BaseConnectorBundle/Processor/CategoryProcessorSpec.php
src/Pim/Bundle/BaseConnectorBundle/Processor/CategoryProcessor.php

| Bug fix?             | y
| CI currently passes? | yes
| Scenarios pass?      |
| Changelog updated?   | y
| Fixed tickets        | PIM-3929
| Migration script?    | n

PIM-3929: Categories with circular references are skipped in processor

---

CHANGELOG.md
src/Pim/Bundle/CatalogBundle/Manager/MediaManager.php

| Bug fix?             | YES
| CI currently passes? | 
| Scenarios pass?      | 
| Changelog updated?   | y
| Fixed tickets        | PIM-4017
| Migration script?    | n

PIM-4017: Fix bug with variant group when saving an empty media attribute

---

CHANGELOG.md
src/Pim/Bundle/EnrichBundle/Resources/public/js/pim-attributeoptionview.js

| Bug fix?             | y
| CI currently passes? | 
| Scenarios pass?      | y
| Changelog updated?   | y
| Fixed tickets        | PIM-4019
| Migration script?    | n

PIM-4019: option code is properly displayed during option deletion

---

phpspec.yml

We have too many specs now. Displaying all of them is useless...

Use default phpspec formatter

---

CHANGELOG.md
src/Pim/Bundle/CatalogBundle/Resources/translations/validators.en.yml

| Bug fix?             | y
| CI currently passes? | /
| Scenarios pass?      | y
| Changelog updated?   | y
| Fixed tickets        | PIM-4047

PIM-4047: Missing translation key for a number value which should not be decimal

---

CHANGELOG.md
spec/Akeneo/Bundle/StorageUtilsBundle/Doctrine/MongoDBODM/Cursor/CursorFactorySpec.php
spec/Akeneo/Bundle/StorageUtilsBundle/Doctrine/MongoDBODM/Cursor/CursorSpec.php
spec/Akeneo/Bundle/StorageUtilsBundle/Doctrine/ORM/Cursor/CursorFactorySpec.php
spec/Akeneo/Bundle/StorageUtilsBundle/Doctrine/ORM/Cursor/CursorSpec.php
src/Akeneo/Bundle/StorageUtilsBundle/Doctrine/MongoDBODM/Cursor/Cursor.php
src/Akeneo/Bundle/StorageUtilsBundle/Doctrine/ORM/Cursor/Cursor.php

| Scenarios pass?      | running
| Fixed tickets        | PIM-4113
Imagine the following code:
```php
$products = $pqb->execute(); // returns the products 12468511, 13675186, 13851841
$first = $products->current();
if (null !== $first) {
echo "FIRST=" . $first->getIdentifier()  . "\n";
} else {
echo "FIRST IS NULL\n";
}
$i = 1;
foreach ($products as $product) {
echo "$i    " .  $product->getIdentifier() . "\n";
$i++;
}
```
Result before:
```
FIRST …
```

[TR] PIM-4113: initialize cursors on first item during creation

---

spec/Pim/Bundle/ReferenceDataBundle/Doctrine/ORM/Repository/ReferenceDataRepositorySpec.php
src/Pim/Bundle/CatalogBundle/Repository/ChannelRepositoryInterface.php
src/Pim/Bundle/ReferenceDataBundle/Doctrine/ORM/Repository/ReferenceDataRepository.php
src/Pim/Bundle/ReferenceDataBundle/Resources/config/datagrid/sorters.yml

Only the *code* field is required for a *reference data* entity. The purpose of this fix is to sort reference data only if they have a field *sortOrder* (like what we have for custom entities)
| Bug fix?             | Y (on master only)
| CI currently passes? | Y 
| Scenarios pass?      | running
| Changelog updated?   |

[TR] Fix reference data repository

---

spec/Pim/Bundle/CatalogBundle/Manager/MediaManagerSpec.php
src/Pim/Bundle/CatalogBundle/Manager/MediaManager.php

| Bug fix?             |  yes
| New feature?         | 
| BC breaks?           |
| CI currently passes? |
| Tests pass?          |  yes
| Scenarios pass?      |
| Checkstyle issues?*  |
| PMD issues?**        |
| Changelog updated?   |
It prevents error like `ProductValue` can not be used like an array when your identifier has special characters.

Urlizer::urlize works with a string

---

CHANGELOG.md
src/Pim/Bundle/FilterBundle/Resources/public/js/datafilter/filter/select2-choice-filter.js

Pressing Enter on a Product grid filter makes the page "unclickable"
| Changelog updated?   |y
| Fixed tickets        |PIM-4044

[TR] PIM-4044 : "Enter" and Product grid filter

---

src/Pim/Bundle/DataGridBundle/Resources/translations/jsmessages.en.yml
src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml

To prepare the 1.3 tagging (keys are synchronized from master)

PIM-4146: add missing translation keys

---

CHANGELOG.md
features/family/mass_edit_families.feature
src/Pim/Bundle/CatalogBundle/Entity/Repository/FamilyRepository.php
src/Pim/Bundle/EnrichBundle/MassEditAction/Operation/AbstractMassEditAction.php

| Scenarios pass?      | Y
| Fixed tickets        | PIM-4203
| DB schema updated?   | N
| Migration script?    | N
See : http://doctrine-orm.readthedocs.org/en/latest/reference/dql-doctrine-query-language.html#pure-and-mixed-results

[TR] PIM-4203: fix mass edit of families after sorting by label

---

src/Pim/Bundle/InstallerBundle/Command/DatabaseCommand.php

fix an error about sess_lifetime not having a default value.
Reminder : this field is not used before SF 2.6

default value 0 for sess_lifetime

---

.travis.yml

Executing CS fixer only on PHP 5.6 speed up Travis build by a 50%+ ratio

[TR] Travis settings : execute CS fixer only for PHP 5.6

---

CHANGELOG.md
src/Pim/Bundle/EnrichBundle/Resources/public/js/pim-attributeoptionview.js

| Bug fix?             | Yes
| Tests pass?          | Yes
| Scenarios pass?      | Yes
| Checkstyle issues?*  | No
| PMD issues?**        | No
| Changelog updated?   | Yes
| Fixed tickets        | PIM-4032
| DB schema updated?   | No
| Migration script?    | No
| Doc PR               | No

[TR] PIM-4032: Wrong error message when deleting used attribute option by a published product

---

CHANGELOG.md
app/config/pim_parameters.yml
spec/Pim/Bundle/PdfGeneratorBundle/Renderer/ProductPdfRendererSpec.php
src/Pim/Bundle/PdfGeneratorBundle/DependencyInjection/PimPdfGeneratorExtension.php
src/Pim/Bundle/PdfGeneratorBundle/Renderer/ProductPdfRenderer.php
src/Pim/Bundle/PdfGeneratorBundle/Resources/config/renderers.yml
src/Pim/Bundle/PdfGeneratorBundle/Resources/views/Product/renderPdf.html.twig

| Fixed tickets        | PIM-4535

[TR] PIM-4535: Fix font problems on pdf generation: you can now set a custom font by setting the %pim_pdf_font% parameter

---

src/Pim/Bundle/EnrichBundle/Resources/translations/messages.en.yml

PIM-4660 : missing translation key for pim_enrich.acl.job_tracker.index

---

spec/Pim/Bundle/TransformBundle/Normalizer/Flat/CategoryNormalizerSpec.php
spec/Pim/Bundle/TransformBundle/Normalizer/Structured/CategoryNormalizerSpec.php
src/Pim/Bundle/TransformBundle/Normalizer/Structured/CategoryNormalizer.php

Interfaces has changed in order to also use the assets categories
| Behats             | yes
| Specs & Static     | yes
| Changelog updated  | yes
http://core-ci.akeneo.com/job/pim-pr-behat/3042/console

[TR][PAM]PIM-4690: Changed interfaces

---

Gruntfile.js

Thanks to @filipsalpe and based on the solution given here https://github.com/cloudchen/grunt-template-jasmine-requirejs/issues/72

[TR] Fix jasmine spec by giving the .bind() polyfill as vendor

---

CHANGELOG.md
src/Pim/Bundle/UIBundle/Resources/public/css/form.less

| Migration script?  | Y
| Behats             | No regression

[TR] PIM-4803: Drag & Drop is too long when I filter on attribute group

---

src/Pim/Bundle/CatalogBundle/Resources/translations/validators.en.yml
src/Pim/Bundle/UIBundle/Resources/translations/jsmessages.en.yml

restore these keys to avoid regression on 1.2 and 1.3

PIM-4518: Restore removed translation keys

---

app/Resources/jenkins/behat/run_behat.sh

This PR allows to run Behat features wherever they are.
Main changes for CE pull request:
- separator is now "," instead of ":"
- paths has to be relative to the application root and not to the features directory anymore
This PR will introduce changes that will allow for EE:
- only one execution of run_behat (so no more yellow CI, it will be either red or blue)
- the feature list will be entered in only one spot (no separation between EE and CE), allowing easier control on what will be executed as well as easier interaction with existing CI errors analysis tools

Generic features directory, can be anywhere

---

CHANGELOG-1.4.md
src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/panel/history.html

| Behats             | N (this PR fix existing behats)

PIM-4911: fix escaping of property with locale and scope

---

src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/tab/attributes/validation-error.html

In some systems, underscore.js throw an "Uncaught SyntaxError: Unexpected identifier" in product view.
Issue : Underscore.js bug on product view #3383
URL : https://github.com/akeneo/pim-community-dev/issues/3383

Fix for undescore.js :

---

features/Context/FixturesContext.php

Use product & family savers instead of DB queries in FixturesContext to launch the events properly
| Added Specs       | Not needed
| Added Behats      | Not needed
| Travis CI is ok   | OK
| Changelog updated | Not needed

ESB-40: Use savers instead of DB queries in FixturesContext

---

behat.yml.dist
features/Context/AssertionContext.php
features/Context/DataGridContext.php
features/Context/FeatureContext.php
features/Context/NavigationContext.php
features/Context/Page/Attribute/Creation.php
features/Context/Page/AttributeGroup/Edit.php
features/Context/Page/Base/Base.php
features/Context/Page/Base/Form.php
features/Context/Page/Batch/Classify.php
features/Context/Page/Category/CategoryView.php
features/Context/Page/Family/Edit.php
features/Context/Page/Product/Edit.php
features/Context/Spin/SpinCapableTrait.php
features/Context/WebUser.php
features/datagrid/datagrid_views.feature
features/user/edit_my_account.feature
features/user/edit_user_group_and_role_assignations.feature

| Changelog updated | -
| Review and 2 GTM  | -
The aim of this PR is to make a first step on the stabilization on our CI. Our first tests on the new CI system reveal a lot of unstable Behat due to timeouts. Our current CI is super fast thanks to RAMFS and we will not have this on our future CI; ie: **each Behat will surely be slower and more subject to timeouts on the future CI than what we have currently**.
We'll test this branch on the new CI to find which timeout suit the best.
What's done here?

[TR] PIM-5071: CI stabilization

---

CHANGELOG-1.4.md
features/Context/Page/Base/Form.php
features/Context/Page/Product/Edit.php
src/Pim/Bundle/DataGridBundle/Extension/Filter/FilterExtension.php
src/Pim/Bundle/EnrichBundle/Controller/Rest/AttributeController.php
src/Pim/Bundle/EnrichBundle/Resources/config/requirejs.yml
src/Pim/Bundle/EnrichBundle/Resources/public/js/fetcher/attribute-fetcher.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/fetcher/base-fetcher.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/manager/attribute-manager.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/manager/product-manager.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/associations.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/attributes/add-attribute.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/form-tabs.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/meta/groups.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/panel/history.js
src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/tab/attributes/add-attribute.html

https://akeneo.atlassian.net/browse/PIM-5008
What this PR does ?
- Each time we used to fetch all attributes, fetch only needed attributes by codes instead.
- Rework the "add attributes" extension (the last one that really needs all attributes) so that the attributes choices are fetched only when the user opens the multiselect.
- Load the associations grid only when the user opens the associations tab.
- Fix the way identifier attribute is fetched.

[TR] PIM-5008: Optimize PEF when dealing with lots of attributes

---

CHANGELOG-1.4.md
src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/field/boolean.html

[SLA] PIM-5039: Fix missing translation key for boolean attribute switch

---

CHANGELOG-1.4.md
features/Context/WebUser.php
spec/Pim/Bundle/BaseConnectorBundle/Writer/File/CsvProductWriterSpec.php
src/Pim/Bundle/BaseConnectorBundle/Writer/File/CsvProductWriter.php

https://akeneo.atlassian.net/browse/PIM-5127
Overrides `flush()` of CsvWriter to be able to read products from a buffer.
To be reworked on master.

[TR] PIM-5127: Improve products export memory usage

---

CHANGELOG-1.4.md
features/product/associate_product.feature
spec/Pim/Bundle/DataGridBundle/Datasource/ResultRecord/MongoDbOdm/AssociatedProductHydratorSpec.php
src/Pim/Bundle/DataGridBundle/Datasource/ResultRecord/MongoDbOdm/AssociatedProductHydrator.php

The is_associated sort does not work anymore on the MongoDB association grid due to https://github.com/akeneo/pim-community-dev/pull/3540...

[TR] PIM-5161: fix the is_associated sort on MongoDB association grid

---

CHANGELOG-1.4.md
spec/Pim/Bundle/DataGridBundle/Datagrid/Configuration/Product/FiltersConfiguratorSpec.php
spec/Pim/Bundle/FilterBundle/Filter/ProductValue/BooleanFilterSpec.php
spec/Pim/Bundle/FilterBundle/Filter/ProductValue/DateRangeFilterSpec.php
src/Pim/Bundle/DataGridBundle/Datagrid/Configuration/ConfiguratorInterface.php
src/Pim/Bundle/DataGridBundle/Datagrid/Configuration/Product/FiltersConfigurator.php

> This is a part of improvement for the product grid loading speed. (The main part is in the platform: https://github.com/akeneo/platform/pull/39)
The `configure()` method is called X times when the grid is loaded.
X being the number of attributes usable as grid filter.
`offsetGetByPath` and `offsetSetByPath` are very time consuming (property accessor that handles a lot of cases), but those cases are pretty simple and can be managed by `offsetGet` and `offsetSet`.
| Added Specs       | Y

[TR] PIM-5150: Grid is very slow to load with a lot of attributes

---

app/Resources/jenkins/behat/run_behat.sh
behat.yml.dist
features/Context/FeatureContext.php
features/Context/NavigationContext.php
features/Context/Page/Base/Base.php
features/Context/Page/Base/Form.php
features/Context/Spin/SpinCapableTrait.php
features/Context/WebUser.php

| Specs             |n
| Behats            |y
| Changelog updated |n
| Review and 2 GTM  |y
| Micro Demo (PO)   |n
| Migration script  |n
| Tech Doc          |n
What's new : 
- timeout is only fixed in behat config file and accessed statically to avoid the redundant constant
- spinning is now "time based" and no more based on a number of iterations. Necessary because we are not really able to catch Timeout exceptions in nested spins

PIM-5071 : refactor spin method

---

CHANGELOG-1.4.md
src/Pim/Bundle/VersioningBundle/Doctrine/MongoDBODM/VersionRepository.php

This fix **can't be tested by behat scenarios**, as they reload pages each time.
This bug is only reproducible with the normal navigation (single page application).

PIM-5163: Fix the VersionRepository on MongoDB to take the most recent entry for product resources

---

CHANGELOG-1.3.md
features/product/completeness.feature
src/Pim/Bundle/CatalogBundle/Command/PurgeCompletenessCommand.php
src/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/CompletenessGenerator.php
src/Pim/Bundle/CatalogBundle/MongoDB/Normalizer/MediaNormalizer.php

Imagine a family `F` with a media attribute `M` which is required for a channel.
When you create a product with this family `F`, the normalized data contains the empty media (it's an array with the keys `filename` and `originalFilename`) .
During the completeness calculation, as the media normalzed data exists, the generator thinks the media is filled in, so the calculation is wrong.
To fix this:
* for new products, we don't normalize the empty medias anymore in the normalized data
* for old products: we don't take into account empty medias in the calculation and we'll ask customers to purge their completeness with the new command `pim:completeness:purge` and to recalculate it  with`pim:completeness:calculate`
| …

[TR] PIM-5190: Fix calculation error for MongoDB completeness with empty media attributes

---

features/Context/WebUser.php
spec/Pim/Bundle/BaseConnectorBundle/Writer/File/CsvProductWriterSpec.php
src/Pim/Bundle/BaseConnectorBundle/Writer/File/CsvProductWriter.php

Tested with 10K products. Memory stays stable at 88MB.

[TR] PIM-5197: Improve products export memory usage (backport PIM-5127 into 1.3)

---

CHANGELOG-1.4.md
src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/FamilyRepository.php
src/Pim/Bundle/CatalogBundle/Repository/FamilyRepositoryInterface.php
src/Pim/Bundle/EnrichBundle/Controller/Rest/FamilyController.php

Reverts akeneo/pim-community-dev#3583
We have identifiied a new bug with this patch. The permissions are not applied correctly on Enterprise Edition (ie: attributes are not filtered by permissions). 
The Behat _Compare and copy localized fields from different sources // Successfully copy value from my draft_ fails.

Revert "[SLA][TR]PIM-5194: fix perf on json family generation"

---

src/Pim/Bundle/EnrichBundle/Resources/public/js/product/edit-form.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form.js

Actually in the BaseForm we are trying to reach this.model in the `getFormData` but this.model is not instantiated by the BaseForm. The goal of this PR is to make the BaseForm standealone.

[TR] PIM-4347: Moved model initialization from PEF to BaseForm

---

CHANGELOG-1.4.md
spec/Pim/Component/Connector/Processor/Denormalization/ProductAssociationProcessorSpec.php
spec/Pim/Component/Connector/Processor/Denormalization/ProductProcessorSpec.php
src/Akeneo/Bundle/StorageUtilsBundle/Doctrine/Common/Detacher/ObjectDetacher.php
src/Pim/Bundle/ConnectorBundle/Resources/config/batch_jobs.yml
src/Pim/Bundle/ConnectorBundle/Resources/config/processors.yml
src/Pim/Component/Connector/Processor/Denormalization/ProductAssociationProcessor.php
src/Pim/Component/Connector/Processor/Denormalization/ProductProcessor.php

This PR fixes two problems:
- missing `detach()` calls on ProductProcessor and ProductAssociationProcessor
- buggy `cascadeDetach()` on our MongoDB ODM version (see https://github.com/doctrine/mongodb-odm/pull/979/ ) by reimplementing a proper `cascadeDetach()` on our ObjectDetacher()
This second fix must be not ported on master. We must switch to a stable version of MongoDB ODM . (See PIM-4981).
| Added Specs       | No
| Added Behats      | No
| Travis CI is ok   | In progress

[TR] PIM-5170 - Fixes MongoDB memory leak at import time.

---

CHANGELOG-1.4.md
features/Context/Page/UserRole/Edit.php
spec/Pim/Bundle/TransformBundle/Normalizer/Flat/AttributeGroupNormalizerSpec.php
spec/Pim/Bundle/TransformBundle/Normalizer/Structured/AttributeGroupNormalizerSpec.php
spec/Pim/Bundle/VersioningBundle/EventSubscriber/AddVersionSubscriberSpec.php
src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/AttributeRepository.php
src/Pim/Bundle/TransformBundle/Normalizer/Flat/AttributeGroupNormalizer.php
src/Pim/Bundle/TransformBundle/Normalizer/Structured/AttributeGroupNormalizer.php
src/Pim/Bundle/TransformBundle/Resources/config/serializer/flat.yml
src/Pim/Bundle/TransformBundle/Resources/config/serializer/structured.yml
src/Pim/Bundle/VersioningBundle/EventSubscriber/AddVersionSubscriber.php
src/Pim/Bundle/VersioningBundle/Resources/config/event_subscribers.yml
src/Pim/Bundle/VersioningBundle/Resources/config/serializer/flat.yml

The goal of this PR is to reduce the memory footprint and request time of whatever uses the `AttributeGroupNormalizer`. Actually `Rest\AttributegroupController` and `VersionManager` are using this normalizers so it should fix some performance issues in the product edit form ans during the versioning management.
Note: To make this PR 1.4 compatible and avoid BC Break, the injection of AttributeRepository is optional in this version. We will remove this compatibility layer during the merge on master branch.
| Behats            | Running
| Micro Demo (PO)   | todo

[TR] PIM-5209: Optimized AttributeGroupNormalizer in order to serialize attributes codes in one request.

---

CHANGELOG-1.3.md
features/filter/option.feature
features/filter/options.feature
spec/Pim/Bundle/CatalogBundle/Doctrine/Common/Filter/ObjectIdResolverSpec.php
src/Pim/Bundle/CatalogBundle/Doctrine/Common/Filter/ObjectIdResolver.php
src/Pim/Bundle/CatalogBundle/Doctrine/Common/Filter/ObjectIdResolverInterface.php
src/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/Filter/OptionFilter.php
src/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/Filter/OptionsFilter.php
src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Filter/OptionFilter.php
src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Filter/OptionsFilter.php

Imagine you have 2 attributes: `attr1` and `attr2` (multi or simple select). Each attribute has the following options: `red`, `blue`, `purple`.
Let's say you want to filter the products with `attr2 IN purple`. 
Currently, the `purple` option that is returned by the filters is ALWAYS the one that belongs to `attr1` because the attribute is not taken into account.

[TR] PIM-5224: Fix first matching option on selects during filtering via the pqb

---

src/Pim/Bundle/EnrichBundle/Resources/public/js/fetcher/base-fetcher.js

The getObjects method here is usefull in other contexts than the BaseFetcher. Actually we need to use it in the EnterpriseEdition in the ProductDraftFetcher.
| Review and 2 GTM  |  todo

[TR] PIM-4347: Change visibility of function getObjects in the BaseFetcher

---

CHANGELOG-1.4.md
spec/Pim/Bundle/TransformBundle/Normalizer/MongoDB/ProductNormalizerSpec.php
src/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/Filter/FamilyFilter.php
src/Pim/Bundle/TransformBundle/Normalizer/MongoDB/ProductNormalizer.php

Impossible to create a behat as this wrong normalization is only used by the DirectToDb Mongo writer.
| Blue CI           | CE Y, EE running

PIM-5240: Fix Mongo normalization that creates a nullable family field

---

CHANGELOG-1.4.md
features/Context/DataGridContext.php
features/Context/Page/Base/Grid.php
features/attribute/edit_identifier_attribute.feature
features/product/date.feature
features/product/display_attributes_in_the_grid.feature
features/product/filtering/filter_products.feature
features/variant-group/add_attributes_to_a_variant_group.feature
src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/AttributeRepository.php
src/Pim/Bundle/DataGridBundle/Datagrid/Configuration/Product/ContextConfigurator.php
src/Pim/Bundle/DataGridBundle/Resources/config/configurators.yml
src/Pim/Bundle/EnrichBundle/Resources/translations/messages.en.yml

TEST PROTOCOL:
* no xdebug, done on local machine
* database with 10k attributes
* 1 variant group,  1 product that belongs to that variant group
* calculate mean time of  25 curl calls
BEFORE PATCH:
* refresh product grid: 9.278s
* refresh variant product grid: 9.235s
AFTER PATCH:
* refresh product grid: 0.439s
* refresh variant product grid: 0.453s
| Blue CI           | CE Y, EE running

[SLA][TR] PIM-5208: patch for grid performance with large amount of attributes

---

CHANGELOG-1.4.md
src/Pim/Bundle/PdfGeneratorBundle/Resources/views/Product/renderPdf.html.twig

Dev Notes:
* We can't use a simple table here: it breaks with big cells (it does a page break before the cell and let a huge blank space). This was the original implementation of this feature and was reviewed by @damien-carcel to fix this case.
* Floats are not well implemented in DOMPDF (its an experimental feature that you can enable with a flag), and breaks everything if a floating element have to be displayed on multiple pages (which happens in our case).
With that said I came to the conclusion that only absolute boxing model is possible and, to be able to compute the height of the boxes, I have to set …

[SLA] PIM-5268: Fixed PDF display to be able to display long attribute name

---

CHANGELOG-1.4.md
spec/Pim/Component/Connector/Processor/Denormalization/ProductAssociationProcessorSpec.php
spec/Pim/Component/Connector/Processor/Denormalization/ProductProcessorSpec.php
src/Akeneo/Bundle/StorageUtilsBundle/Doctrine/Common/Detacher/ObjectDetacher.php
src/Pim/Bundle/ConnectorBundle/Resources/config/batch_jobs.yml
src/Pim/Bundle/ConnectorBundle/Resources/config/processors.yml
src/Pim/Bundle/InstallerBundle/Resources/config/batch_jobs.yml
src/Pim/Component/Connector/Processor/Denormalization/ProductAssociationProcessor.php
src/Pim/Component/Connector/Processor/Denormalization/ProductProcessor.php

**Related to https://github.com/akeneo/pim-community-dev/pull/3599, please read it first ;)**
| Blue CI           | Y in CE (running in EE)
Import of 5k products, on my local machine, no xdebug:
* ORM:  11 minutes, small memory leak during `import_products` step (176mB at 300 products, 190mB at 2k products and 210mB at 5k products), no leak at all on the `import_associations` step (stable at 210mB)
* ODM: 4 minutes, small memory leak during `import_products` step (105mB at 300 products, 116mB at 2k products and 117mB at 5k products), no leak at all on the `import_associations` step (stable at 156mB)
Without this fix (branch 1.4)
* ODM : 3minutes …

[TR] PIM-5170: Fixes MongoDB memory leak at association import time

---

src/Pim/Bundle/UIBundle/Resources/public/js/delete-confirmation.js
src/Pim/Bundle/UIBundle/Resources/public/js/pim-dialog.js

Translate 'OK' and 'Cancel' messages in default dialogs.
These were missing, resulting in literally OK and Cancel ignoring the used language.
| Added Specs       | NA <- not applicable in this case as it's javascript only :)
| Travis CI is ok   | ? <- still running

add missing translations for default dialogs

---

CHANGELOG-1.4.md
features/product/filtering/filter_products_per_family.feature
spec/Pim/Bundle/FilterBundle/Filter/Product/FamilyFilterSpec.php
spec/Pim/Bundle/FilterBundle/Filter/ProductValue/ChoiceFilterSpec.php
src/Pim/Bundle/DataGridBundle/Resources/config/requirejs.yml
src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filter/select2-choice-filter.js
src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filter/select2-rest-choice-filter.js
src/Pim/Bundle/DataGridBundle/Resources/public/templates/filter/select2-choice-filter.html
src/Pim/Bundle/EnrichBundle/Doctrine/ORM/Repository/FamilySearchableRepository.php
src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/product.yml
src/Pim/Bundle/EnrichBundle/Resources/config/requirejs.yml
src/Pim/Bundle/EnrichBundle/Resources/public/js/formatter/choices/base.js
src/Pim/Bundle/EnrichBundle/Resources/public/spec/formatter/choices/BaseChoicesFormatterSpec.js
src/Pim/Bundle/FilterBundle/Filter/AjaxChoiceFilter.php
src/Pim/Bundle/FilterBundle/Filter/Product/FamilyFilter.php
src/Pim/Bundle/FilterBundle/Filter/Product/GroupsFilter.php
src/Pim/Bundle/FilterBundle/Filter/ProductValue/ChoiceFilter.php
src/Pim/Bundle/FilterBundle/Form/Type/Filter/AjaxChoiceFilterType.php
src/Pim/Bundle/ReferenceDataBundle/DataGrid/Filter/ReferenceDataFilter.php
src/Pim/Bundle/UIBundle/Entity/Repository/OptionRepositoryInterface.php

| Specs             | yes
| Review and 2 GTM  | 
Done in this PR :
- Refactor AjaxChoiceFilter children to avoid overriding the `getForm()` just to change the conf
- Modify the family filter type to be able to filter by codes instead of ids
- Add a new choices filter in front able to fetch choices from any rest route that return a normalized response (PEF style), not select2 formatted one
- Add a formatter that transform the normalized response into the select2 format

[TR] PIM-5232: Ajaxify product grid family filter

---

features/Context/AssertionContext.php
features/localization/product/display_localized_history.feature
features/localization/product/display_localized_history_of_complex_prices.feature
features/product/history/display_history.feature
features/product/history_update.feature
src/Pim/Component/Localization/Presenter/PricesPresenter.php

| Behats            |  y
| Micro Demo (PO)   | n
This PR changes the display in the product history.
Before: "price-EUR | 12,34"
After: "price-EUR | 12,34 €"

[TR] PIM-5034: Display currency in product history

---

CHANGELOG-1.4.md
features/Context/FeatureContext.php
features/product/associate_product.feature
src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/association_product.yml

Actually when you go to a product page, throuth the grid filtered by a category, their is a bug in the association panel, the products displayed in the datagrid are filtered by the category used in the product grid but, as the filter is hidden (you dont see the category tree in this page) you are not able to see that the grid is filtered. The quick fix it to completely remove the filter on the product association datagrid so the filter from the product grid dont apply here.
Dev Note concerning Behat: I'm trying here to use only Behat methods so I overrode some native function in order to be able to use them in …

[TR][SLA]PIM-5295: Fix association product grid category filter

---

CHANGELOG-1.4.md
features/product/filtering/filter_product_per_boolean.feature
features/product/sorting/sort_products_per_attribute.feature
src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filter/select-filter.js

Boolean filters were not working well after a page reload. This was because the refresh call was called before the filter initialisation.

PIM-5334: fix boolean filter on product grid

---

.travis.yml
Gruntfile.js

The issue is that the .less have @import xxx lines, and the path is a relative path for the less compilation, when the files are on /web folder (and not in /src/bundles).
This commit adds a app/console assets:install to copy the .less and .css into /web folder, to be closer than real compilation.
Commit needed for #5210 and #5024 .

Update Travis and Grunt to manage imports

---

CHANGELOG-1.3.md
features/Context/DataGridContext.php
features/variant-group/edit_variant_group_attribute_value.feature
src/Pim/Bundle/CatalogBundle/Doctrine/Common/Saver/GroupSaver.php

Before this fix variant group media were handled by the VariantGroupMedia manager after the variant group save. So the new media location was never properly saved.
Before this fix media attributes does not work on variant groups

PIM-5335: fix 'media save on variant group

---

CHANGELOG-1.4.md
src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/AttributeRepository.php
src/Pim/Bundle/EnrichBundle/Form/Subscriber/AddVariantGroupAxesSubscriber.php
src/Pim/Bundle/EnrichBundle/Form/Type/GroupType.php
src/Pim/Bundle/EnrichBundle/Resources/config/form_subscribers.yml
src/Pim/Bundle/EnrichBundle/Resources/config/form_types.yml

Tested on a catalog with 10k attributes. xdebug disabled.
NB: curl calls are slighty faster than real UI calls.
Mean time of 25 curls call to `/enrich/variant-group/4/edit':
* before patch: 10.068s (more than 10k requests to DB)
* after patch: 1.602s (165 requests to DB)
Mean time of 25 curls call to `/enrich/group/5/edit':
* before patch: 10.983s (more than 10k requests to DB)
* after patch: 1.237s (160 request to DB)

[TR] PIM-5211: display the variant group edit form in less than 2 sec

---

CHANGELOG-1.4.md
features/product/edit_and_remove_a_product.feature
spec/Pim/Bundle/VersioningBundle/EventSubscriber/AddRemoveVersionSubscriberSpec.php
src/Pim/Bundle/VersioningBundle/EventSubscriber/AddRemoveVersionSubscriber.php
src/Pim/Bundle/VersioningBundle/Resources/config/event_subscribers.yml

| Behats            | ok
From 1.4.0 to 1.5, remove a product add a flash message "Product cannot be deleted" but remove well the product and add the remove version. 
Bug come from the versionning. When we remove the product we try to create a version several time when the product is already deleted (and the version already added too) only if the product has a Metric product value. When we try to create the version a second time we have the product but not product values and normalizer throw an exception because it can't find the identifier product value.
We spent a lot of time with benoit to debug it and decided to fix the problem moving …

[TR] [SLA] PIM-5202: Remove version is now created on PRE_REMOVE instead of POST

---

features/export/edit_an_export.feature

| Blue CI           | :white_check_mark: 
| Review and 2 GTM  | :white_check_mark: 
This scenario has been tagged unstable because sometimes, an error occured with "Enclosure" field and form was not validated.
Then, scenario became really wrong because, instead of just display the key of decimal separator value, we displayed the value.
So, this PR fix the behat and remove tag unstable (CI has been launched 4 times, and it never failed).

Fix behat when we update an export

---

CHANGELOG-1.4.md
features/Context/FeatureContext.php
features/product/associate_product.feature
src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/association_product.yml

This reverts commit ea58d4e0c245e61a25cfa681193edb8934460925.
Conflicts:
CHANGELOG-1.4.md

Revert "PIM-5295: Fix association product grid category filter"

---

CHANGELOG-1.4.md
features/Context/FixturesContext.php
features/attribute/delete_attribute.feature
features/user/edit_user_group_and_role_assignations.feature
spec/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/QueryGenerator/AttributeDeletedQueryGeneratorSpec.php
src/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/QueryGenerator/AttributeDeletedQueryGenerator.php
src/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/QueryGenerator/NormalizedDataQueryGeneratorInterface.php
src/Pim/Bundle/CatalogBundle/Resources/config/storage_driver/doctrine/mongodb-odm.yml

Before this bug fix we didn't remove the old normalised data when we removed an old attribute. The problem was: If you remove an attribute, recreate it with the same option: you could filter on it and even if the product values where not here anymore.
I added a query generator to remove the corresponding product values in normalized data and added a behat to cover this case.

PIM-5347: fix mongo database in case of attribute removal

---

features/Context/AssertionContext.php
features/Context/NavigationContext.php

| Micro Demo (PO)   | n
This PR is just here to improve message from behat exceptions.
Before, we had message like "I can't find the notification".
Now, you have the list of available notification, very useful when you have to debug and see the text of all the displayed notifications.

PIM-5130: Improve behat message

---

features/Context/DataGridContext.php
features/Context/Page/Base/Grid.php

The goal of this PR is to improve the way the grid is tested in our behats by :
- reworking the methods that fetch information inside the grid (speed improvement)
- adding more spins (stability improvement)
- removing lots of `catch (\Exception $e)` (debuggability improvement)
- fixing a false positive case when sorting by a boolean column
- cleaning phpdoc
For example, the sorting steps ("I should be able to sort the rows by...") are around 4x faster with this implementation. Although the gain is significant on a local machine, it does not really speed up the builds on the CI (don't know why : / ).
CI is blue.

[TR] Clean behat grid context

---

features/export/view_an_export_detail_page.feature

This scenario is useless since an export job always has a channel. It's incoherent because the job is created directly in database without using the UI.
Plus it's broken on master because the validation error is not displayed anymore on the show page.

[TR] Remove incoherent scenario

---

CHANGELOG-1.4.md
spec/Akeneo/Component/FileStorage/File/FileStorerSpec.php
src/Akeneo/Component/FileStorage/File/FileStorer.php

| Changelog updated | TODO
The issue is about the upload of files through Amazon S3.
The file is sent with a stream method, without any information about the mime type. Because file is sent by stream and no information is given about mime type, it can not be guessed.
We added the mime type of the file to the options of the writer.

[SLA][TR] PIM-5405: Add content type for stream upload

---

src/Pim/Bundle/CatalogBundle/Collector/DatabaseCollector.php
src/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/Repository/ProductValueCounterRepository.php
src/Pim/Bundle/CatalogBundle/Resources/views/Collector/database.html.twig

The  `count()` inside `ProductValueCounterRepository` wasn't working witth a high volume of data and lead to an error:
`exception: distinct too big, 16mb cap`
| Blue CI           | N/A
| Review and 2 GTM  | OK

PIM-4897: count on product values is now bypassed with high volume of data

---

CHANGELOG-1.4.md
features/Context/WebUser.php
features/import/product/import_products.feature
features/product/classify_product.feature
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/categories.js

The issue is the params sent to product update. When category code is an integer, it's sent as an integer, like this:
`[ "categories" => [ 0 => 123 ] ]`
This fix cast category codes to string, like this:
`[ "categories" => [ 0 => "123" ] ]`

[SLA][TR] PIM-5331: Fix product save issue when categories having code as integer

---

CHANGELOG-1.5.md
spec/Pim/Bundle/UIBundle/Twig/StyleExtensionSpec.php
src/Pim/Bundle/UIBundle/DependencyInjection/PimUIExtension.php
src/Pim/Bundle/UIBundle/Resources/config/twig.yml
src/Pim/Bundle/UIBundle/Resources/public/css/pim.less
src/Pim/Bundle/UIBundle/Twig/StyleExtension.php

In many screens we have to highlights some variables in texts and their is no easy way to do it actually.

Added a twig extension to highlight some texts

---

CHANGELOG-1.4.md
features/Context/Page/Batch/ChangeFamily.php
spec/Pim/Bundle/EnrichBundle/Form/Type/MassEditAction/ChangeFamilyTypeSpec.php
src/Pim/Bundle/EnrichBundle/Form/Type/MassEditAction/ChangeFamilyType.php
src/Pim/Bundle/EnrichBundle/Resources/config/form_types.yml
src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/meta/change-family-modal.html
src/Pim/Bundle/EnrichBundle/Resources/translations/messages.en.yml
src/Pim/Bundle/EnrichBundle/Resources/views/MassEditAction/configure/change-family.html.twig

| Specs             |fixed
| Behats            |fixed
| Blue CI           |Yes
| Changelog updated |OK
| Review and 2 GTM  |Yes
| Micro Demo (PO)   |OK
| Migration script  |not needed
| Tech Doc          |not needed
This PR is about using an asynchronous dropdown to choose the new family for the edited products.

PIM-5233 : change mass edit family to use an ajax dropdown

---

features/Context/DataGridContext.php

Problem
-----------
The actual step `@Then /^the row "([^"]*)" should contain:$/` split the text of the cell using a comma separator to be able to do things like `Then the row "foo" should contain "foo, bar"` so you can't ensure that the expected text is really present in the datagrid cell.
More than that, splitting on a comma don't work at all if you have commas in the datagrid as it do an `array_diff` to know if the behat should fail or not, here is an example:
```
Then the row "copy_description" should contain:
| column    | value                                  |
| Condition | If name equals My nice tshirt [ en ]   |
| Condition | If …
```

Added new behat function to be able to assert a datagrid cell contains some text

---

CHANGELOG-1.4.md
features/Context/DataGridContext.php
features/Context/WebUser.php
features/product/filtering/filter_products_per_family.feature
src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filter/select2-rest-choice-filter.js
src/Pim/Bundle/EnrichBundle/Doctrine/ORM/Repository/FamilySearchableRepository.php

| Blue CI           | yellow
The issue is that when user searches a family and they are localizable families, it returns a line per translation, and the limit is < to 20.
Now, it's 20.

[TR][SLA] PIM-5418: Fix limit on localizable families search

---

CHANGELOG-1.4.md
features/attribute/create_text_attribute.feature
src/Pim/Bundle/CatalogBundle/Resources/config/validation/attribute.yml

* The CHANGELOG needs to be updated or not ? *

[TR] PIM-5021: Forbid the use of code 'category' for an attribute

---

.travis.yml
composer.json

With this PR, i want to add MongoDb bundle to our dev requirements.
It has multiple advantages : 
- No need to modify your `composer.json` when working on a Mongo evironment
- It will ALWAYS run ALL specs : you will not break specs anymore
- You will always have the good version of MongoDb bundle : i had an old 1.4 Mongo db env on wich i used to stash my composer before updating and then pop stash to quickly set my Mongo env. But by doing that, i didn't see that i was using an old version of the bundle.
| Added Specs       |no
| Added Behats      |no
| Travis CI is ok   |yes
| Changelog updated |no

Add Doctrine MongoDb to dev requirements

---

CHANGELOG-1.4.md
src/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/Saver/ProductSaver.php

Just some words to explain this PR.
3 issues are fixed here:
1. Useless completeness scheduling.
Completeness is overridden each time we save the product with this direct to db saver. No need to reschedule it, it will be done.
2. Wrong completeness generation.
The real saving part is done at the end of the `saveAll` method calling `insertDocuments` and `updateDocuments`. As long these methods are not called, the MongoDB collection current state is before the product update. In this case, the completeness is done on the "old" datas.
3. Memory leak on the product saver.
The rescheduling of the completeness is done with: `CompletenessGenerator::schedule(ProductInterface)`. It calls a clear to the collection. Accordingly, this will schedule the completeness to be removed in the UOW.
But now, …

PIM-5379: Remove completeness calculation from MongoDB saver

---

CHANGELOG-1.3.md
src/Akeneo/Bundle/StorageUtilsBundle/Doctrine/Common/Detacher/ObjectDetacher.php
src/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/ProductRepository.php
src/Pim/Bundle/CatalogBundle/Doctrine/ORM/ProductRepository.php
src/Pim/Bundle/CatalogBundle/Validator/Constraints/UniqueVariantAxisValidator.php

A cherry pick has been done from 1.4 to detach product value.
UniqueVariantAxisValidator has been reworked to avoid to hydrate products whereas we need only the id.
Result, import a rule with 3000 products inpacted:
before patch | after patch
------------ | -------------
20 minutes | 13 minutes
625Mb | 70.75Mb

PIM-5422: fix memory leak on import products

---

CHANGELOG-1.4.md
src/Pim/Bundle/EnrichBundle/Controller/Rest/AttributeController.php
src/Pim/Bundle/EnrichBundle/Resources/config/routing/attribute.yml
src/Pim/Bundle/EnrichBundle/Resources/public/js/fetcher/attribute-fetcher.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/fetcher/base-fetcher.js

The issue raised is that when there is a lot of attributes with long codes, we have a "too long URI" error.
The first workaround is to increase the limit of URI, but this PR will fix it.
This PR changes GET method into POST, only for this action.

[TR][SLA] PIM-5446: Replace rest attribute configuration action from GET to POST to prevent too long URI

---

.travis.yml
CHANGELOG-1.5.md
composer.json

| Specs             |not needed
| Behats            |not needed
The purpose of this PR is to add Mongo requirements in the dev section of composer. This way, the developer will always have the good version of Doctrine MongoDb bundle.
As a side effect, the mongo php extension become mandatory to work on pim devs.
Also, i modified the Travis build by removing xdebug for extra speed.

PIM-5450: add mongodb bundle to dev requirements

---

app/config/config_behat.yml

Behat should use the same session storage than the live application.
Also, it improves the CI stability.
| Added Specs       |no
| Added Behats      |no
| Travis CI is ok   |yes, orm and odm
| Changelog updated |no

PIM-5456: behat do not use a mock session storage

---

src/Pim/Bundle/EnrichBundle/Resources/config/bundles/fos_js_routing.yml

When you want to add new routes on the JS Router component, if they does not start by pim_ or oro_, you need to add them in that's hidden configuration.
Here it will add 5 routes (+ routes in development environment: _profiler, etc.) but it will automatically add your project routes to the JS component.
| Added Specs       | NA
| Added Behats      | NA
| Travis CI is ok   | 
| Changelog updated | Let me know if needed?

Remove specific routes for JS router component

---

CHANGELOG-1.4.md
features/datagrid/products_backtothegrid.feature
spec/Pim/Bundle/EnrichBundle/Normalizer/AttributeNormalizerSpec.php
src/Pim/Bundle/EnrichBundle/Controller/Rest/AttributeController.php
src/Pim/Bundle/EnrichBundle/Normalizer/AttributeNormalizer.php
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/attributes.js

| Blue CI           | processing
There is an issue in the PEF because when it loads, the rest attribute loads every product attribute, at each attribute the complete group is loaded, and the group contains the set of attributes. So we transfer n*n attributes (3Mb for a big project) and load in more than 2 secs.
This PR fix this with a specific context on this query to only load code.

[SLA] PIM-5492: Fix complete group loading on useless cases

---

CHANGELOG-1.4.md
features/import/product/import_products_with_invalid_data.feature
spec/Pim/Component/Connector/Processor/Denormalization/ProductProcessorSpec.php
src/Pim/Component/Connector/Processor/Denormalization/ProductProcessor.php

We introduced a regression with fix #3412 in 1.4.
The case was to allow to import products from a csv file with only the sku and the familly columns.
This applied fix in 1.4.4 removed the appliance of data filtering in product processor for new products and create too much values.
I have firstly submitted a PR with a more complex approach which prepares the removal of any empty values in the DB, but we'll do this only in a upcoming minor version, not in a patch.
With small catalog, before the fix:
```
mysql> select count(*) from pim_catalog_product_value;
+----------+
|   342029 |
+----------+
Import small_cat has been successfully executed.
real    21m1.744s
user    17m53.809s
sys 0m30.667s
```
With small catalog, after the fix:
```
+----------+
| count(*) |
+----------+
|   159676 | …
```

[TR] PIM-5476: fix issue with native csv product import and product creation

---

src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid/grid.js

| Micro Demo (PO)   | todo
For some datagrids we have to specify specific messages when there is no results. Is actually possible to  use a specific key for datagrids rendered by the backend using the following keys:
```yaml
"oro_datagrid.no_data_hint %entityHint%": "No %entityHint% exists."
"oro_datagrid.not_found_hint %entityHint%":  "No %entityHint% was found to match your search. Try modifying your search criteria ..."
```
but it is not possible when the datagrid is rendered by the javascript.
Here I basicly added the possibility to use translation keys like …

PIM-5125: Allow specific messages if datagrid is empty

---

features/Context/Page/Base/Grid.php

Attempt to fix this random fatal :
```
PHP Fatal error:  Call to a member function find() on a non-object in /var/lib/jenkins/distributed-ci/builds/pim-community-dev_1265/features/Context/Page/Base/Grid.php on line 272
```

Fix randoms on empty grid testing

---

CHANGELOG-1.3.md
features/Context/AssertionContext.php
src/Pim/Bundle/DataGridBundle/Datasource/ResultRecord/MongoDbOdm/Product/ValuesTransformer.php

When a media attribute is localized or/and scopable, we cannot use it in the grid because of an undefined index on `attributeCode` in normalizedData.
| Specs             |n
| Behats            |n
| Blue CI           |just check below ;)

PIM-5532 : display picture thumbnail in datagrid

---

CHANGELOG-1.4.md
features/product/filtering/filter_product_per_boolean.feature
src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filter/select-filter.js

https://akeneo.atlassian.net/browse/PIM-5354
| Specs             | n/a
Grid filter rendering in front works as follows :
1. filter is rendered
2. value coming from memorized grid state is set
3. optional treatment are applied (e.g. jQuery plugin initialization)
Except that for non-default filters (the ones you add via "Manage filters") the rendering is done at the end, so the value set in the DOM in previous steps is lost (at least for select filters).
The fix consist in refreshing the DOM from the value stored in the filter (because yes, filters are stateful :fire:) just after the rendering and just before jQuery multiselect …

PIM-5354: Keep select/boolean filter value after navigation

---

app/config/pim_parameters.yml
composer.json
src/Pim/Bundle/InstallerBundle/Command/DatabaseCommand.php
src/Pim/Bundle/InstallerBundle/DataFixtures/ORM/AbstractInstallerFixture.php
src/Pim/Bundle/InstallerBundle/DependencyInjection/PimInstallerExtension.php
src/Pim/Bundle/InstallerBundle/FixtureLoader/FixtureJobLoader.php

Just a proposal for an easier installation.
With this PR, we can install a catalog from [akeneo/catalogs](https://github.com/akeneo/catalogs) or even a completely new catalog outside of the project.
Now, you can use for example:
installer_data: %kernel.root_dir%/../vendor/akeneo/catalogs/master/enterprise/small/fixtures
... to directly install a catalog from path.

Change installer to be able to use other catalogs fixtures

---

spec/Akeneo/Component/Analytics/ChainedDataCollectorSpec.php
spec/Pim/Bundle/AnalyticsBundle/Controller/DataControllerSpec.php
spec/Pim/Bundle/AnalyticsBundle/DataCollector/BundlesDataCollectorSpec.php
src/Akeneo/Component/Analytics/ChainedDataCollector.php
src/Akeneo/Component/Analytics/ChainedDataCollectorInterface.php
src/Pim/Bundle/AnalyticsBundle/Controller/DataController.php
src/Pim/Bundle/AnalyticsBundle/Controller/SystemInfoController.php
src/Pim/Bundle/AnalyticsBundle/DataCollector/BundlesDataCollector.php
src/Pim/Bundle/AnalyticsBundle/DependencyInjection/Compiler/RegisterDataCollectorPass.php
src/Pim/Bundle/AnalyticsBundle/Resources/config/acl.yml
src/Pim/Bundle/AnalyticsBundle/Resources/config/controllers.yml
src/Pim/Bundle/AnalyticsBundle/Resources/config/data_collectors.yml
src/Pim/Bundle/AnalyticsBundle/Resources/config/navigation.yml
src/Pim/Bundle/AnalyticsBundle/Resources/config/routing.yml
src/Pim/Bundle/AnalyticsBundle/Resources/translations/messages.en.yml
src/Pim/Bundle/AnalyticsBundle/Resources/views/SystemInfo/index.html.twig
src/Pim/Bundle/AnalyticsBundle/Resources/views/SystemInfo/index.txt.twig

A new page mainly designed to ease the qualification by the Super Squirrels Support Squad. It displays basic information about the current PIM instance :
User can also download a plain text version to join it to a SDS ticket for example :
```
[Edition]
EE
[Version]
1.4.18
[Storage]
doctrine/mongodb-odm
[Environment]
dev
[Install time]
2016-02-10T14:19:23+01:00
[Registered bundles]
APY\JsFormValidationBundle\APYJsFormValidationBundle
AcmeEnterprise\Bundle\AppBundle\AcmeEnterpriseAppBundle
Akeneo\Bundle\BatchBundle\AkeneoBatchBundle
...
```
Content is extensible since it uses the data collectors system @nidup made for stats about PIM usage.

[TR] Report page to ease support qualification

---

src/Pim/Bundle/CatalogBundle/Command/MongoDBIndexCreatorCommand.php

When creating indexes in MongoDB, add a call to doctrine:mongodb:schema:update to make sure default collection indexes are created as well
| Specs             |no
| Behats            |no
| Changelog updated |not needed

Add doctrine schema update to create default indexes as well

---

src/Pim/Bundle/BaseConnectorBundle/Reader/File/YamlReader.php
src/Pim/Bundle/CatalogBundle/Resources/config/validation/attribute.yml
src/Pim/Bundle/ConnectorBundle/Resources/config/validation/csvReader.yml

Installation of a small catalog, 5000 products:
```
time php app/console pim:installer:db -e prod  32.76s user 1.44s system 60% cpu 56.115 total
time php7.0 app/console pim:installer:db -e prod  15.95s user 1.30s system 46% cpu 37.050 total
time php app/console akeneo:batch:job csv_product_import -e prod  1153.08s user 28.00s system 85% cpu 22:58.98 total
time php7.0 app/console akeneo:batch:job csv_product_import -e prod  379.59s user 25.28s system 69% cpu 9:46.33 total
```
| Behats            | - 
| Changelog updated |  -
| Micro Demo (PO)   | -
| Migration script  | -
| Tech Doc          | -

Make the PIM installable with PHP7

---

features/product/history/display_removed_value_history.feature
features/product/history_update.feature

- replaced "And the following products" by a real manipulation of the UI to be closer than reality.
- removed exactly same tests in 2 different files.

Fix random behat in history context and remove duplicate tests

---

features/Context/WebUser.php
features/localization/product/edit_product.feature
src/Pim/Bundle/DataGridBundle/Resources/config/requirejs.yml
src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filter/date-filter.js
src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filter/datetime-filter.js
src/Pim/Bundle/DataGridBundle/Resources/public/templates/filter/date-filter.html
src/Pim/Bundle/DataGridBundle/Resources/translations/jsmessages.en.yml
src/Pim/Bundle/DataGridBundle/Resources/translations/jsmessages.fr.yml
src/Pim/Bundle/UIBundle/Resources/public/js/pim-datepicker.js
src/Pim/Bundle/UIBundle/Resources/translations/jsmessages.en.yml
src/Pim/Bundle/UIBundle/Resources/translations/jsmessages.fr.yml

| Changelog updated | ?
This PR translates the datepicker. The translations will be done in Crowdin.
The JS part just set a configuration option to add the current locale translations, like described here.
http://www.malot.fr/bootstrap-datetimepicker/
The french translations are for demo-PO and behats.

PIM-5277: Translate datetimepicker

---

CHANGELOG-1.4.md
src/Pim/Bundle/EnrichBundle/Resources/config/requirejs.yml
src/Pim/Bundle/EnrichBundle/Resources/public/js/fetcher/fetcher-registry.js

We should not fetch all families on page refresh.
As we should only do fetchall on small collections, warmup is maybe not usefull anymore. Will be treated by PIM-5542
| Specs             |no
| Behats            |no

PIM-5575 : remove JS fetchers warmup

---

CHANGELOG-1.4.md
features/export/export_products_and_download_exported_file.feature
spec/Pim/Bundle/BaseConnectorBundle/Archiver/FileWriterArchiverSpec.php
src/Pim/Bundle/BaseConnectorBundle/Archiver/FileWriterArchiver.php
src/Pim/Bundle/EnrichBundle/Controller/JobTrackerController.php
src/Pim/Bundle/ImportExportBundle/Resources/translations/messages.en.yml

This PR replaces https://github.com/akeneo/pim-community-dev/pull/4006.
| Specs             | yes
| Review and 2 GTM  | yes
Currently there are two native archivers for exports. Their role is to copy exported files (csv, media, etc.) from the export location to the archive directory (usually under app/archive/export/...). These files are used especially to be downloaded from the job page (button "Download generated file").
**How it worked before**
- Only one file exported (usually just the csv and no media) : FileWriterArchiver is used, csv is archived
- Several files exported (csv + media) : ArchivableFileWriterArchiver is used, all files are archived in a …

PIM-5579: Enable FileWriterArchiver even for exports with several files

---

features/Context/DbSessionPurger.php
features/Context/FeatureContext.php
features/Context/Page/Base/Base.php
features/Context/Page/Base/Form.php
features/Context/Page/Product/Edit.php
features/Context/WebUser.php
features/Pim/Behat/Context/HookContext.php
features/Pim/Behat/Context/NavigationContext.php
features/attribute/delete_attribute.feature
features/localization/product/edit_product.feature
features/navigation/navigation_title.feature
features/product/edit_and_remove_a_product.feature
features/product/edit_product.feature
features/product/history/display_history.feature
features/product/history/display_removed_value_history.feature
features/product/history_update.feature

This PR replace the current Behat login behavior with a more natural one.
The current behavior is about trying to get to the target page, then apply the set login/pass when the redirection is done to the login screen.
This behavior has several drawbacks:
- it does not represent how the way use will log in the application most of the time
- it loads the target page twice (first after the redirection and then when the behat step ask for it)
- it makes Behat debugging more difficult as the application flow is not the one described in the scenario ("the i am logged in as" step is a lie)
The new behavior simply follow the scenario and logged in when requested, thus avoiding redirect and difficult to debug flow.
| Added Specs       | N.A.
| …

[TR] PIM-5412 Behat - Real natural login process

---

src/Pim/Bundle/EnrichBundle/Controller/Rest/MediaController.php

In my case, there was already a directory /tmp/pim/file_storage, but not the target directory "/tmp/pim/file_storage/b/f/8/0".
Thus, somehow the recursive mkdir-call in Symfony\Component\HttpFoundation\File\File->getTargetFile(...) failed and throw an exception.
After deleting the whole /tmp/pim directory, everything worked.
The best thing would be to have the real exception-message in the HTTP-400 result, which might be a security problem....

Return at least a minor hint, if file upload fail.

---

.travis.yml

Caching only `$HOME/.composer/cache/files` means that the Cache doesn't
invalidate because of stale Packagist metadata (which happens more often
making the cache nearly useless).

only cache downloaded packages

---

features/Context/FeatureContext.php
features/Context/Page/Product/Edit.php
features/Context/WebUser.php
features/Pim/Behat/Context/Domain/Enrich/CompletenessContext.php
features/Pim/Behat/Decorator/Completeness/BlockDecorator.php
features/Pim/Behat/Decorator/Completeness/PanelDecorator.php
features/Pim/Behat/Decorator/ElementDecorator.php
features/product/completeness/display_completeness.feature
spec/Pim/Bundle/CatalogBundle/Manager/CompletenessManagerSpec.php
src/Pim/Bundle/CatalogBundle/Manager/CompletenessManager.php
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/panel/completeness.js
src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/panel/completeness.html

Purpose of this PR is to re-order the completeness panel in the product edit from.
The first completeness shown must be that of the locale switcher or the catalog locale choose in the product grid by the user. Others completeness must be closed.
Channels in completeness must be ordered as they are in the scope switcher.
```
| Micro Demo to the PO (Story only) | ok
```

[TR] PIM-5571: sort completeness in product edit form

---

CHANGELOG-1.5.md
features/Context/DataGridContext.php
features/Context/Page/Base/Grid.php
features/attribute/delete_attribute.feature
features/product/filtering/filter_products_per_date_fields.feature
features/product/filtering/filter_products_per_text_fields.feature
features/product/filtering/filter_products_per_with_multiple_metrics.feature
features/product/filtering/filter_products_per_with_multiple_multiselect.feature
src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filter/date-filter.js
src/Pim/Bundle/UIBundle/Resources/public/js/pim-datepicker.js

```
| Added Specs                       | n/a
| Micro Demo to the PO (Story only) | n/a
| Tech Doc                          | n/a
```
**What does it fix ?**
https://akeneo.atlassian.net/browse/PIM-5509
A regression has been introduced with datepickers rework : when you filtered on a date, all date filters shared the same displayed value (but the filter was ok on backend). Also when the date filter value was memorized in session storage, it was never read again after page reload.
**How does it fix ?**
The main problem was that the front filter has …

PIM-5509: Fix grid date filters initialization

---

CHANGELOG-1.6.md
features/Context/DataGridContext.php
features/Context/FeatureContext.php
features/Context/Page/Base/Grid.php
features/Context/Page/Batch/EditCommonAttributes.php
features/Pim/Behat/Context/Domain/Enrich/GridPaginationContext.php
features/Pim/Behat/Context/NavigationContext.php
features/Pim/Behat/Decorator/ElementDecorator.php
features/Pim/Behat/Decorator/GridDecorator/PaginationDecorator.php
features/Pim/Behat/Decorator/PageDecorator/GridCapableDecorator.php
features/datagrid/datagrid_views.feature
features/datagrid/products_backtothegrid.feature
src/Pim/Bundle/DataGridBundle/Resources/views/macros.html.twig

#Ensures the product grid is correctly initialised with the its parameters stored in the session storage including the number of the page for the product grid.
- In a separate commit, the grid page size filter (number of item per page) was also incorporated in this decorator.
- fixes some phpdoc in behats.

[TR] PIM-5592: keeps page number when back to the grid

---

src/Akeneo/Bundle/BatchBundle/README.md
src/Akeneo/Bundle/BatchBundle/composer.json
src/Akeneo/Component/Batch/README.md
src/Akeneo/Component/Batch/composer.json

As follow up of issues https://github.com/akeneo/BatchBundle/issues/88 and https://github.com/akeneo/BatchBundle/issues/87
**TL;DR**
This PR is a first attempt to extract akeneo/batch and akeneo/batch-bundle to make them usable outside of the Akeneo PIM full stack in read only repositories https://github.com/akeneo/batch and https://github.com/akeneo/BatchBundle.
Batch component is now usable outside of the PIM.
There is still some work to do on BatchBundle because in dev-master, it now uses storage utils interface (to prepare the decoupling from doctrine storage), so to be extracted, it requires to extract StorageUtils and related StorageUtilsBundle in dedicated read only repositories too.
Lot of new questions about versioning, branching strategy, main repo organization to easily ship …

[DX] attempts around git subtree split to extract batch and batch bundle

---

src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.fr.yml

Adds the french translation of the quick export button necessary in the features/localization/mass-action/quick_export.feature scenario.
Bug introduced in #4125.
| Blue CI                 | Yes

Fix localized quick export

---

src/Pim/Bundle/EnrichBundle/Doctrine/ORM/Repository/AttributeSearchableRepository.php

This reference is only used in a PHP Doc. Nonetheless the path was wrong.

Fix path of AttributeInterface

---

src/Oro/Bundle/UserBundle/Entity/UserManager.php

Add use of Pim\Bundle\UserBundle\Entity\User to UserManager
fix call of User::ROLE_DEFAULT in UserManager::updateUser
When using a third party bundle to manage authentication (FR3DLdap in my case), this method is called by Oro\Bundle\UserBundle\EventListener\LoginSubscriber::onLogin.
As the default Oro\Bundle\UserBundle\Entity\User doesn't exist in your repository, the User class isn't recognized.

fix Oro\..\UserManager

---

src/Pim/Component/Catalog/Query/Filter/FieldFilterInterface.php

Fix PHPDoc for FieldFilterInterface
| Added Specs                       |n
| Added Behats                      |n
| Changelog updated                 |n
| Micro Demo to the PO (Story only) |n
| Migration script                  |n
| Tech Doc                          |n

FieldFilterInterface: $operator should not be array

---

src/Pim/Bundle/PdfGeneratorBundle/Twig/ImageExtension.php

PDFs for products containing an image didn't get rendered.
See also #4122

Fix paths in Twig ImageExtension

---

spec/Pim/Component/Connector/Writer/File/BulkFileExporterSpec.php
spec/Pim/Component/Connector/Writer/File/CsvProductWriterSpec.php
spec/Pim/Component/Connector/Writer/File/XlsxProductWriterSpec.php
src/Pim/Component/Connector/Writer/File/BulkFileExporter.php
src/Pim/Component/Connector/Writer/File/CsvProductWriter.php
src/Pim/Component/Connector/Writer/File/CsvWriter.php
src/Pim/Component/Connector/Writer/File/XlsxProductWriter.php

This PR fixes a bug with CSV Product Export, XLSX Product Export, but CSV variant group Export is ok. When we export items with media, there is no archive to download with media.
| Added Behats                      | They are in 1.4, need to be remontay Waiting for CI
| Changelog updated                 | Bug has been merge in master, no need to update

[TR] Fix archive to download when exporting items with media

---

CHANGELOG-1.6.md
features/Context/FeatureContext.php
features/Context/Page/Base/Form.php
features/Context/Page/Base/Grid.php
features/Context/WebUser.php
features/Pim/Behat/Context/Domain/Enrich/AttributeTabContext.php
features/Pim/Behat/Context/Domain/Enrich/Product/AssociationTabContext.php
features/product/associate_product.feature
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/associations.js
src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/tab/association-panes.html
src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/tab/associations.html
src/Pim/Bundle/UIBundle/Resources/public/css/form.less

The state of the following elements is now memorized in session storage (idem products grid) :
| Added Specs                       | n/a
| Tech Doc                          | n/a

PIM-5593: Keep context in the associations tab of the product edit form

---

CHANGELOG-1.6.md
features/export/export_families.feature
spec/Pim/Component/Catalog/Normalizer/Structured/FamilyNormalizerSpec.php
spec/Pim/Component/Connector/Normalizer/Flat/FamilyNormalizerSpec.php
src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/AttributeRepository.php
src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/AttributeRequirementRepository.php
src/Pim/Bundle/CatalogBundle/Resources/config/serializers.yml
src/Pim/Bundle/ConnectorBundle/Resources/config/serializer.yml
src/Pim/Bundle/EnrichBundle/Controller/Rest/FamilyController.php
src/Pim/Bundle/VersioningBundle/Resources/config/serializer/flat.yml
src/Pim/Component/Catalog/Normalizer/Structured/FamilyNormalizer.php
src/Pim/Component/Catalog/Repository/AttributeRepositoryInterface.php
src/Pim/Component/Catalog/Repository/AttributeRequirementRepositoryInterface.php

We had a scalability issue on route `/configuration/family/rest` (even using a limit). As we have to hydrate every attributes of each families in order to apply rights in the enterprise edition or some other filters we needed to optimize this part of the code as much as possible.

PIM-5542: Optimized Family normalization

---

features/Pim/Behat/Context/Domain/Collect/ImportProfilesContext.php
features/import/product/import_products_with_associations.feature
features/import/product/xlsx/import_products.feature
features/import/product/xlsx/import_products_with_associations.feature
spec/Pim/Component/Catalog/Comparator/Filter/ProductAssociationFilterSpec.php
spec/Pim/Component/Connector/ArrayConverter/Flat/Product/ValueConverter/TextConverterSpec.php
spec/Pim/Component/Connector/Processor/Denormalization/ProductAssociationProcessorSpec.php
src/Pim/Bundle/ConnectorBundle/Resources/config/array_converters.yml
src/Pim/Component/Catalog/Comparator/Filter/ProductAssociationFilter.php
src/Pim/Component/Connector/ArrayConverter/Flat/Product/ValueConverter/TextConverter.php
src/Pim/Component/Connector/Processor/Denormalization/ProductAssociationProcessor.php

**What was the issue?**
When you edit an Excel file and put a numeric value in a cell, it is stored as a number in the xlsx file.
It is a problem if it concerns a text attribute or the sku. During import you will have an error like "Attribute ... expects a string as data, interger given".
**What's the fix?**
The processor use converters located in Pim\Component\Connector\ArrayConverter\Flat\Product\ValueConverter to transform the data coming from the reader into the standard format. One of these converters is the ScalarConverter, which does nothing but build the standard format array (locale + scope + value) and handles several attribute types : texts, dates, numbers and booleans.
I created a separated TextConverter that allow to cast the value to string during conversion.
I also had to …

PIM-5696: Fix XLSX products import with numeric values in text attributes

---

CHANGELOG-1.6.md
features/Context/FixturesContext.php
features/Pim/Behat/Context/Domain/TreeContext.php
features/enrich/variant-group/display_variant_history.feature
features/enrich/variant-group/edit_variant_group.feature
features/import/product/import_products.feature
features/mass-action/edit_common_attributes-01.feature
features/product/completeness/update_completeness.feature
spec/Pim/Bundle/CatalogBundle/Doctrine/Common/Saver/AttributeSaverSpec.php
spec/Pim/Bundle/CatalogBundle/Doctrine/Common/Saver/GroupSaverSpec.php
spec/Pim/Bundle/CatalogBundle/Doctrine/Common/Saver/ProductSaverSpec.php
spec/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/Saver/ProductSaverSpec.php
spec/Pim/Bundle/CatalogBundle/EventSubscriber/ProductCategorySubscriberSpec.php
spec/Pim/Component/Connector/Writer/Doctrine/ProductWriterSpec.php
src/Pim/Bundle/CatalogBundle/Doctrine/Common/Saver/FamilySaver.php
src/Pim/Bundle/CatalogBundle/Doctrine/Common/Saver/GroupSaver.php
src/Pim/Bundle/CatalogBundle/Doctrine/Common/Saver/ProductSaver.php
src/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/CompletenessGenerator.php
src/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/Saver/ProductSaver.php
src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/ProductRepository.php
src/Pim/Bundle/CatalogBundle/EventSubscriber/ProductCategorySubscriber.php
src/Pim/Bundle/EnrichBundle/Controller/Rest/CompletenessController.php
src/Pim/Bundle/EnrichBundle/Controller/Rest/ProductController.php
src/Pim/Bundle/EnrichBundle/Normalizer/CompletenessCollectionNormalizer.php
src/Pim/Component/Connector/Writer/Doctrine/ProductWriter.php

As Julia, when I save several products, I would like to have the completeness calculated in order to always have a completeness calculated and up-to-date.
Must be covered:
Here the bulk save for products is now saving products one by one. As there are no significant overhead we keep it as it for the moment.
CE:
Create on 1121 products:
master-ODM:     1min12
PIM-5577-ODM: 2min48
master-ORM: 2min15
PIM-5577:      3min15
Update on 1121 products
master-ODM:     1min23
PIM-5577-ODM: 2min43
master-ORM: …

PIM-5577: remove schedule and reculate completeness option

---

app/AppKernel.php

Here is a way to ease the registration of the project bundles. A dedicated method has been extracted and put at the top of the AppKernel.

Add a registerProjectBundles method in the AppKernel

---

CHANGELOG-1.5.md
features/import/check_mime_type_before_import.feature
src/Pim/Bundle/ImportExportBundle/Controller/JobProfileController.php

There are constraints on our readers to check file extension before launch import. 
One of these (FileValidator) needs a Akeneo\Component\FileStorage\Model\FileInfoInterface, but the import form has not been changed when validator has added this check on FileInfoInterface
| Added Behats                      | fixed

PIM-5697: Fix import form when a file extension is not allowed

---

CHANGELOG-1.4.md
src/Pim/Bundle/CatalogBundle/Model/AbstractAttribute.php

PIM-5725: Fix reference data name of the attribute in case this attribute is not a reference data
Add a wrong configuration to your SKU attribute. In the column "properties" set:
`a:1:{s:19:"reference_data_name";s:0:"";}
`. AFAIK, it can only be done manually. So that's impossible to add a Behat on this.
During the product normalization, `""` is returned instead of `null` here https://github.com/akeneo/pim-community-dev/blob/1.4/src/Pim/Bundle/TransformBundle/Normalizer/MongoDB/ProductValueNormalizer.php#L138.
Then the product normalization is totally wrong and the product can not be saved.
| Added Behats                      | impossible …

PIM-5725: Fix reference data name of the attribute in case it's not

---

src/Pim/Bundle/CatalogBundle/Builder/ProductBuilder.php

Most of our products have about 250 attributes, but we only have few price attributes.
With this small change exporting products is 10% faster for us.

Export products performance

---

features/Pim/Behat/Context/Domain/TreeContext.php

This fix "may" fix random failures on DCI with tree element selections.
EE ODM 2 random http://core-ci.akeneo.com/job/dci_behat/3873/
Validate metric attributes of a product.Validate the number max constraint of metric attribute
Revert a product to a previous version.Successfully revert the category of a product
EE ORM 1 fails, random http://core-ci.akeneo.com/job/dci_behat/3890/
CE ORM
CE ODM

PIM-5577: Fix random behats on Tree checkboxes

---

features/Context/Page/Base/Grid.php
features/Context/catalog/footwear/families.csv
features/Pim/Behat/Context/NavigationContext.php
features/datagrid/products_backtothegrid.feature
features/family/browse_families.feature
features/family/delete_family.feature
features/product/edit_product_family.feature
src/Oro/Bundle/FilterBundle/Twig/RenderLayoutExtension.php
src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filter/product_scope-filter.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/meta/change-family.js
src/Pim/Bundle/FilterBundle/Filter/Product/ScopeFilter.php
src/Pim/Bundle/UIBundle/Resources/public/js/pim-initselect2.js

Problem is that currently the product grid has it's own state. So it means that each time the grid is rendered, the previous state is set back. When you go on a product edit form, you can switch the catalog locale and catalog scope which updates the usercontext.
The problem is that the user context is not used to configure the grid and we lose it's value each time we render a grid. 
This fix is kind of dirty but as the scope selector is a filter (and should not) it's the only way to fix it. …

PIM-5642: fix catalog scope filter from the product grid

---

CHANGELOG-1.4.md
src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid/grid.js

Bug description : 
In product edit form, under "Associations" tab :
If you click on another association type to change the current one, the datagrid is refreshed by the two next calls :
http://demo.akeneo.com/datagrid/association-product-grid?association-product-grid...
http://demo.akeneo.com/datagrid/association-group-grid?association-group-grid...
=> OK
events: { 'click .nav-tabs li': 'changeAssociationType', 'click #association-buttons button': 'changeAssociationTargets' }
But if you switch to an other main tab "Attributes" and go back then to "Associations" tab : the datagrid is reloaded with duplicate calls of the two previously listed actions :
http://demo.akeneo.com/datagrid/association-product-grid?association-product-grid... x2 …

PIM-5650: unbind events before refresh grid

---

CHANGELOG-1.4.md
spec/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/Repository/ProductRepositorySpec.php
spec/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/FamilyRepositorySpec.php
spec/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/GroupRepositorySpec.php
spec/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/ProductRepositorySpec.php
spec/Pim/Bundle/EnrichBundle/Connector/Processor/MassEdit/Product/EditCommonAttributesProcessorSpec.php
src/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/Repository/ProductRepository.php
src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/FamilyRepository.php
src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/GroupRepository.php
src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/ProductRepository.php
src/Pim/Bundle/CatalogBundle/Repository/FamilyRepositoryInterface.php
src/Pim/Bundle/CatalogBundle/Repository/GroupRepositoryInterface.php
src/Pim/Bundle/CatalogBundle/Repository/ProductRepositoryInterface.php
src/Pim/Bundle/CatalogBundle/Resources/config/storage_driver/doctrine/mongodb-odm.yml
src/Pim/Bundle/CatalogBundle/Resources/config/storage_driver/doctrine/orm.yml
src/Pim/Bundle/ConnectorBundle/JobLauncher/SimpleJobLauncher.php
src/Pim/Bundle/EnrichBundle/Connector/Processor/MassEdit/Product/EditCommonAttributesProcessor.php
src/Pim/Bundle/EnrichBundle/Resources/config/connector/processors.yml

| Blue CI            | TODO
The EditCommonAttributesProcessor has been rewored. Now the skipped products are detached from the UnitOfWork. Some methods are not directly on the product model because it hydrates lot of models and it causes memory leak...

PIM-5507 : Memory leak during mass edit attributes, mass publish

---

src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/associations.js
src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/tab/associations.html

**The problem**
In the association grid, the scope selector (which is a filter) is displayed in the filter toolbar. It is a regression as it should be shown near the reset grid button.
This problem has been introduced while changing the html element id and class of the association grid.
While all grids are instanciated with the *id* in the PIM. the association grid has a className instead of an id.
**The solution**
Discussing it with @juliensnz. It seems complicated to adapt the grid declaration of all datagrids of the pim to use the class instead of the ids.
So, in this PR I put back the id of the grid instead of the class name.
(The association grid html element declaration has been changed from Id to class in this PR:
https://github.com/akeneo/pim-community-dev/pull/4210/files)
| Q …

PIM-5700: Fix scope filter shiftting

---

CHANGELOG-1.6.md
src/Pim/Bundle/EnrichBundle/Controller/FamilyController.php
src/Pim/Bundle/EnrichBundle/Resources/config/controllers.yml

Validate family when adding or removing attributes.
It is just a first step. The second one needs to move the hardcoded validation from the controller to dedicated constraint.
| Travis CI is ok   |

Add validation in family controller

---

CHANGELOG-1.4.md
spec/Pim/Component/Connector/ArrayConverter/Flat/Product/ValueConverter/ValueConverterRegistrySpec.php
src/Pim/Bundle/ConnectorBundle/DependencyInjection/Compiler/RegisterConverterPass.php
src/Pim/Bundle/ConnectorBundle/Resources/config/array_converters.yml
src/Pim/Component/Connector/ArrayConverter/Flat/Product/ValueConverter/ValueConverterRegistry.php
src/Pim/Component/Connector/ArrayConverter/Flat/Product/ValueConverter/ValueConverterRegistryInterface.php

This PR add an ordering feature for arrays converters.
Related issue: PIM-5753 Accept numeric values for text attributes in import
Btw, we should add position tags to all of our registries to allow external extension to register their services in the right place.
_As a traitor, i will fill the DoD anyway_
| Added Specs                       |only modified
| Changelog updated                 |yes
| Micro Demo to the PO (Story only) |no
| Migration script                  |no
| Tech Doc                          |no

PIM-5753: Array converters ordered by tag priority

---

spec/Pim/Bundle/CatalogBundle/EventSubscriber/ResetUniqueValidationSubscriberSpec.php
src/Pim/Bundle/CatalogBundle/EventSubscriber/ResetUniqueValidationSubscriber.php
src/Pim/Bundle/CatalogBundle/Resources/config/event_subscribers.yml
src/Pim/Component/Connector/Processor/Denormalization/ProductProcessor.php

There is an issue on imports when you have 2 steps managing the same set of products.
The UniqueValueSet class (stateful) keeps in memory the set of product identifiers, to prevent to not have uniqueness validation errors in a batch of products. This class is not reseted after each step, and throws errors when you try to update the same product in 2 differents steps.
This PR reset the UniqueValueSet after a "save_all" event, to remove the identifiers list after a mass products save.
| Review and 2 GTM                  | no

PIM-5363: Reset the UniqueValueSet after a saveAll 

---

src/Pim/Bundle/CatalogBundle/Resources/config/doctrine/Channel.orm.yml
src/Pim/Bundle/CatalogBundle/Resources/config/doctrine/Currency.orm.yml
src/Pim/Component/Catalog/Repository/ChannelRepositoryInterface.php

Fix legacy doctrine mapping weirdness causing issue in EE ProductAsset related to channel fetched from a locale but not managed because the channel has been detached previously in the process
| Changelog updated                 | - 
| Review and 2 GTM                  | - 
| Micro Demo to the PO (Story only) | - 
| Migration script                  | - 
| Tech Doc                          | - 
…ocales from channel

PIM-5625: Currency uses tracking DEFERRED_EXPLICIT + cascade detach channel -> locales

---

src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/AttributeOptionRepository.php

Our users want to search attribute options *inside* attribute option labels.
This worked already in the filters for the product grid, but inside the PEF the user can just search at the beginning of the attribute option labels.

Search inside attribute options

---

src/Pim/Bundle/EnrichBundle/Form/Type/CategoryType.php

This PR just fixes a typo in ```Pim\Bundle\EnrichBundle\Form\Type\CategoryType```.

Fix a typo in category form type

---

CHANGELOG-1.6.md
features/filter/completeness.feature
features/filter/completeness_without_locale.feature
spec/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/Filter/CompletenessFilterSpec.php
spec/Pim/Bundle/CatalogBundle/Doctrine/ORM/Filter/CompletenessFilterSpec.php
spec/Pim/Bundle/CatalogBundle/Doctrine/ORM/Sorter/CompletenessSorterSpec.php
spec/Pim/Component/Catalog/Query/ProductQueryBuilderSpec.php
spec/Pim/Component/Connector/Reader/ProductReaderSpec.php
src/Pim/Bundle/BaseConnectorBundle/Reader/Doctrine/ODMProductReader.php
src/Pim/Bundle/BaseConnectorBundle/Reader/Doctrine/ORMProductReader.php
src/Pim/Bundle/BaseConnectorBundle/Resources/config/readers.yml
src/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/Filter/CompletenessFilter.php
src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Filter/CompletenessFilter.php
src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Join/CompletenessJoin.php
src/Pim/Bundle/CatalogBundle/Resources/config/query_builders.yml
src/Pim/Bundle/CatalogBundle/Resources/config/storage_driver/doctrine/mongodb-odm.yml
src/Pim/Bundle/CatalogBundle/Resources/config/storage_driver/doctrine/orm.yml
src/Pim/Bundle/ConnectorBundle/Resources/config/batch_jobs/csv_connector.yml
src/Pim/Bundle/ConnectorBundle/Resources/config/batch_jobs/xlsx_connector.yml
src/Pim/Bundle/ConnectorBundle/Resources/config/readers.yml
src/Pim/Component/Catalog/Exception/InvalidArgumentException.php
src/Pim/Component/Catalog/Exception/ObjectNotFoundException.php
src/Pim/Component/Catalog/Query/ProductQueryBuilder.php
src/Pim/Component/Connector/Reader/ProductReader.php

This PR introduces a new product reader. It's storage-agnostic thanks to the PQB.
It will replace the old ORM/Mongo readers, which are now deprecated.
Inspired by what has been done on [mass edit](https://github.com/akeneo/pim-community-dev/blob/master/src/Pim/Bundle/EnrichBundle/Connector/Reader/MassEdit/FilteredProductReader.php) and [EnhancedConnectorBundle](https://github.com/akeneo-labs/EnhancedConnectorBundle).
| Added Behats                      | n/a …

PIM-5653: Create a storage agnostic Product Reader using the PQB

---

CHANGELOG-1.6.md
features/filter/date.feature
features/product/filtering/filter_products_per_date_fields.feature
spec/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/Filter/DateTimeFilterSpec.php
spec/Pim/Bundle/CatalogBundle/Doctrine/ORM/Filter/DateTimeFilterSpec.php
src/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/Filter/DateFilter.php
src/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/Filter/DateTimeFilter.php
src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Filter/DateFilter.php
src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Filter/DateTimeFilter.php
src/Pim/Bundle/CatalogBundle/Resources/config/query_builders.yml
src/Pim/Bundle/CatalogBundle/Resources/config/storage_driver/doctrine/mongodb-odm.yml
src/Pim/Bundle/CatalogBundle/Resources/config/storage_driver/doctrine/orm.yml
src/Pim/Bundle/CatalogBundle/spec/Doctrine/MongoDBODM/Filter/DateFilterSpec.php
src/Pim/Bundle/CatalogBundle/spec/Doctrine/ORM/Filter/DateFilterSpec.php
src/Pim/Bundle/FilterBundle/Filter/ProductValue/AbstractDateFilter.php
src/Pim/Bundle/FilterBundle/Filter/ProductValue/DateTimeRangeFilter.php
src/Pim/Bundle/FilterBundle/Resources/config/filters.yml

**Why?**
Natively, a product can have multiple dates :
- fields "updated_at" and "created_at"
- attributes of type "pim_catalog_date"
Until now in the PQB we had only a DateFilter that handled both cases. It was complicated, buggy (with the "not between" operator for example) and it didn't allow to filter precisely on "created at" and "updated at" since all inputs were dates without time.
**What this PR does?**
- It separates the two cases with one DateFilter that handles attributes only, and one DateTimeFilter that handles fields only.
- The DateTimeFilter can now filter to the second.
- In the case of filtering the product grid, it's not the responsibility of the PQB filters anymore to add times to input values. This logic has been moved to the grid filter …

TIP-245: Extract a DateTimeFilter from DateFilter

---

features/Context/Page/Base/Grid.php
features/Context/Page/Base/ProductEditForm.php

Select2 filters crash when we try to close them by clicking direcly on the element using Selenium Driver so we use the Javascript API to ensure that the select2 closes properly

Fixed behat issues

---

CHANGELOG-1.6.md
features/Context/WebUser.php
features/Pim/Behat/Context/JobContext.php
features/import/product/import_products_with_invalid_data.feature
features/product/comments.feature
features/product/sequential_edit/sequential_edit.feature
src/Pim/Bundle/CatalogBundle/Filter/ChainedFilter.php
src/Pim/Bundle/EnrichBundle/Connector/Processor/QuickExport/ProductToFlatArrayProcessor.php
src/Pim/Bundle/EnrichBundle/Controller/Rest/ProductController.php
src/Pim/Bundle/EnrichBundle/Filter/ProductValuesEditDataFilter.php
src/Pim/Bundle/EnrichBundle/Resources/config/connector/processors.yml
src/Pim/Bundle/EnrichBundle/spec/Connector/Processor/QuickExport/ProductToFlatArrayProcessorSpec.php
src/Pim/Component/Catalog/Builder/ProductBuilderInterface.php
src/Pim/Component/Catalog/Normalizer/Structured/ProductNormalizer.php
src/Pim/Component/Connector/Normalizer/Flat/ProductNormalizer.php
src/Pim/Component/Connector/Normalizer/Flat/ProductValueNormalizer.php

**What does this PR do?**
- Quick export processor is now user aware (like the mass edit processor for example)
- Product normalizers (structured & flat) now accept several filters in context
| Added Behats                      | n/a
| Micro Demo to the PO (Story only) | in progress

PIM-5640: Apply permissions on quick export

---

features/export/product-export-builder/export_products_status.feature
src/Pim/Bundle/ConnectorBundle/Resources/translations/messages.en.yml
src/Pim/Bundle/ImportExportBundle/Resources/translations/messages.en.yml
src/Pim/Bundle/ImportExportBundle/Resources/views/JobProfile/Tab/job_content.html.twig
src/Pim/Bundle/ImportExportBundle/Resources/views/JobProfile/Tab/property_edit.html.twig
src/Pim/Component/Connector/Reader/ProductReader.php
src/Pim/Component/Connector/spec/Reader/ProductReaderSpec.php

This PR replaces https://github.com/akeneo/pim-community-dev/pull/4429. It's a simple and dumb implementation of the product export builder without changing the product reader behavior. As a matter of fact, this is not that easy to build something solid at the moment as:
* @nidup is currently rewriting the batch foundations https://github.com/akeneo/pim-community-dev/pull/4326
* the previous PR has some design drawbacks …

PIM-5428: Export product builder - export products according to their status

---

CHANGELOG-1.5.md
src/Akeneo/Bundle/ClassificationBundle/Doctrine/ORM/Repository/AbstractItemCategoryRepository.php
src/Akeneo/Component/Classification/Repository/CategoryFilterableRepositoryInterface.php
src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/association_product.yml
src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/product.yml
src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/product_group.yml
src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/product_variant_group.yml
src/Pim/Bundle/FilterBundle/Resources/config/filters.yml

I removed all category filters that were wrongly injected in some datagrids only to ensure permissions related filtering in the enterprise edition.
I also added an interface for the FilterUtility because we rely on it on the enterprise edition and could make sense in the community too.
| Tech Doc                          | /NA

PIM-5762: Removed unused filters on product datagrids

---

CHANGELOG-1.4.md
spec/Pim/Bundle/TransformBundle/Normalizer/Structured/ProductNormalizerSpec.php
src/Pim/Bundle/TransformBundle/Normalizer/Structured/ProductNormalizer.php

I’m currently working on a [JSON connector](https://github.com/damien-carcel/JsonConnectorBundle). For the product export, I use the structured ProductNormalizer, and I encountered a bug: when filtering the product values before normalizing them, the filtering on scope does not work (I got values for all channels instead of just the one I asked).
This is caused by the context passed to the filter, which does not contain the correct information. This PR intends to fix this. …

Fix product value filtering in structured ProductNormalizer

---

CHANGELOG-1.5.md
src/Pim/Bundle/EnrichBundle/Controller/FileController.php

When you upload an image and the transfer finishes, there is no image displayed.
Refers to https://github.com/akeneo/pim-community-dev/issues/3553
These scenarii fail on EE, OK in local
features/file_transformer/apply_transformations_on_images.feature:6
features/product_draft/validation/validate_textarea_attributes.feature:43 …

PIM-5710: Display image even if FileInfo doesnt exist

---

src/Pim/Bundle/UIBundle/Resources/public/css/pim.less

Previously, background was gray. Now, it's white.

PIM-5627: Set white background for wysiwyg editor on mass edit

---

CHANGELOG-1.6.md
src/Akeneo/Component/Batch/spec/Job/JobParametersFactorySpec.php
src/Pim/Bundle/ImportExportBundle/Form/DataTransformer/ConfigurationToJobParametersTransformer.php
src/Pim/Bundle/ImportExportBundle/Form/Type/JobInstanceType.php
src/Pim/Bundle/ImportExportBundle/Resources/config/form_types.yml

For now, JobParameters is directly instantiated in ConfigurationToJobParametersTransformer. This prevents to automatically fill an incomplete rawConfiguration when editing a profile of an existing job instance.
This can occur only with the job instance created before the merge of the JobParameters PR, if a job instance exists in the database with a rawConfiguration where a parameter is missing (but can be reproduced by changing the conf directly in the database, by removing the separator configuration for instance).
This PR solves this by avoiding to do a “new JobParameters()”, but use the JobParametersFactory instead. This will ensure that the default values are added if they do not exist.
| Q …

TIP-431: Ease the migration by using JobParametersFactory in ConfigurationToJobParametersTransformer

---

src/Pim/Bundle/EnrichBundle/Doctrine/ORM/Repository/AttributeGroupRepository.php
src/Pim/Bundle/EnrichBundle/Doctrine/ORM/Repository/CategoryRepository.php
src/Pim/Bundle/EnrichBundle/Doctrine/ORM/Repository/GroupRepository.php
src/Pim/Bundle/EnrichBundle/Doctrine/ORM/Repository/GroupTypeRepository.php
src/Pim/Bundle/EnrichBundle/spec/Doctrine/ORM/Repository/AttributeGroupRepositorySpec.php
src/Pim/Bundle/EnrichBundle/spec/Doctrine/ORM/Repository/GroupRepositorySpec.php
src/Pim/Bundle/EnrichBundle/spec/Doctrine/ORM/Repository/GroupTypeRepositorySpec.php

This fix the scenario features/product-group/browse_product_groups.feature
Behind the hound, it fixes several legacy issues in `findTranslatedLabels(` implementation which returns translated label or the code like "[code]" when the label is not translated.
The query is not ok because it does not return a row when the label is not translated (i fixed to use the same query than in other working implementations).

TIP-405: fix browse groups behat scenario

---

src/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/Filter/DateFilter.php
src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Filter/DateFilter.php

Fix regression made with https://github.com/akeneo/pim-community-dev/pull/4471
It breaks `pim_catalog_date` attribute on ODM 
Currently on ORM, `pim_catalog_date` is stored as a date : `2016-05-24`. but on ODM it's stored as an IsoDate: `ISODate('2016-05-24T08:13:53.0Z')`
When DateFilter is called, when we force timezone, it works on ORM because we don't care about the time, not in ODM. Hours are postponed and date is wrong.

PIM-5112: remove timezone from date filters

---

src/Pim/Bundle/ConnectorBundle/Resources/config/writers.yml
src/Pim/Component/Connector/Writer/File/FlatItemBuffer.php
src/Pim/Component/Connector/Writer/File/FlatItemBufferFlusher.php
src/Pim/Component/Connector/Writer/File/XlsxProductWriter.php
src/Pim/Component/Connector/Writer/File/XlsxSimpleWriter.php
src/Pim/Component/Connector/Writer/File/XlsxVariantGroupWriter.php
src/Pim/Component/Connector/spec/Writer/File/XlsxProductWriterSpec.php
src/Pim/Component/Connector/spec/Writer/File/XlsxSimpleWriterSpec.php
src/Pim/Component/Connector/spec/Writer/File/XlsxVariantGroupWriterSpec.php

This PR aims to:
* avoid to duplicate the "I write into multiple files" logic among all the XLSX writers (currently, the code of the methods `flush`, `areSeveralFilesNeeded`, `resolveFilePath`, `getNumberedFilePath`, and `getWriter` is copied/pasted in `XlsxProductWriter`, `XlsxSimpleWriter` and `XlsxVariantGroupWriter` )
* avoid to tie the "I write into multiple files" logic with the XLSX format. It has nothing to do with. The object `` could worker exactly the same with any flat format (xlsx, csv) that uses our `FlatItemBuffer`)
Notes:
1.  we could remove even more duplicated code if `XlsxVariantGroupWriter` and `XlsxProductWriter` extended `XlsxSimpleWriter` (as the `flush` methods are still the same). Not sure it's a good thing or not, but it works like that for the CSV.. :+1: or :-1: …

TIP-266: Extract multiple files flush logic into a dedicated class

---

CHANGELOG-1.5.md
features/Context/Page/Product/Index.php
features/Context/WebUser.php
features/product/filtering/filter_products_per_category.feature
src/Pim/Bundle/UIBundle/Resources/public/js/jquery.sidebarize.js

On product data grid, when the category panel is retracted on the left side, the number of products displayed is not accurate anymore.
For instance:
- Select a category (with more than 100 products) 
- Change the default pagination (put it to 50 products per page) 
- Then remove the category left panel = reduce it. 
- Rechange the default pagination 
- The page now displays ALL products, not only products from the selected category.
This PR fix it by setting the sidebar width to 0 (and restoring it to its previous value) rather than just hiding (and showing) it. …

PIM-5726: fix number of product displayed on Product Grid when category panel is withdrawn

---

CHANGELOG-1.5.md
features/Context/Page/Base/Base.php
features/Context/WebUser.php
features/locale/change_system_locale.feature
src/Pim/Bundle/LocalizationBundle/DependencyInjection/Configuration.php

Backport of this fix https://github.com/akeneo/pim-community-dev/commit/5d326e2ea654e5bba955e7e776c0853c267863f4

PIM-5643 : Fix default system locale was not fixed by the last PIM-5643 ticket, tagged in 1.5.2

---

CHANGELOG-1.5.md
features/product/add_attributes_to_a_product.feature
features/product/filtering/filter_products_per_category.feature
src/Pim/Bundle/EnrichBundle/Controller/Rest/ProductController.php

When one add to a product an attribute with a code containing only numbers values, it is not possible to save the product when this attribute has been filled.
See screenshot below:
As data is passed to the product updater as an array, with the attribute code as an array key, ```array_merge``` replace the numerical codes (first it encounters by 0, second by 1, etc…) so the updater doesn't understand to which attribute the value is related. Using the union operator instead of ```array_merge``` solve this. …

PIM-5801: Fix save in PEF when attribute code is only numeric

---

CHANGELOG-1.6.md
features/Context/catalog/apparel/jobs.yml
features/Context/catalog/footwear/jobs.yml
features/Pim/Behat/Context/JobContext.php
features/export/product-export-builder/export_products_by_locales.feature
src/Pim/Bundle/BaseConnectorBundle/Processor/ProductToFlatArrayProcessor.php
src/Pim/Bundle/BaseConnectorBundle/spec/Processor/ProductToFlatArrayProcessorSpec.php
src/Pim/Bundle/ConnectorBundle/Resources/translations/messages.en.yml
src/Pim/Bundle/ImportExportBundle/Form/Type/ProductExport/LocaleChoiceType.php
src/Pim/Bundle/ImportExportBundle/JobParameters/FormConfigurationProvider/ProductCsvExport.php
src/Pim/Bundle/ImportExportBundle/JobParameters/FormConfigurationProvider/ProductXlsxExport.php
src/Pim/Bundle/ImportExportBundle/Resources/config/form_types.yml
src/Pim/Bundle/ImportExportBundle/Resources/config/requirejs.yml
src/Pim/Bundle/ImportExportBundle/Resources/public/js/product-export/locales-selector.js
src/Pim/Bundle/ImportExportBundle/Resources/translations/jsmessages.en.yml
src/Pim/Bundle/ImportExportBundle/Resources/views/JobProfile/Tab/job_content.html.twig
src/Pim/Bundle/ImportExportBundle/spec/Form/Type/ProductExport/LocaleChoiceTypeSpec.php
src/Pim/Bundle/ImportExportBundle/spec/JobParameters/FormConfigurationProvider/ProductCsvExportSpec.php
src/Pim/Bundle/ImportExportBundle/spec/JobParameters/FormConfigurationProvider/ProductXlsxExportSpec.php
src/Pim/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev/jobs.yml
src/Pim/Component/Connector/Job/JobParameters/ConstraintCollectionProvider/ProductCsvExport.php
src/Pim/Component/Connector/Job/JobParameters/ConstraintCollectionProvider/ProductXlsxExport.php
src/Pim/Component/Connector/Job/JobParameters/DefaultValuesProvider/ProductCsvExport.php
src/Pim/Component/Connector/Job/JobParameters/DefaultValuesProvider/ProductXlsxExport.php
src/Pim/Component/Connector/spec/Job/JobParameters/ConstraintCollectionProvider/ProductCsvExportSpec.php
src/Pim/Component/Connector/spec/Job/JobParameters/ConstraintCollectionProvider/ProductXlsxExportSpec.php
src/Pim/Component/Connector/spec/Job/JobParameters/DefaultValuesProvider/ProductCsvExportSpec.php
src/Pim/Component/Connector/spec/Job/JobParameters/DefaultValuesProvider/ProductXlsxExportSpec.php

As Peter, I would like to choose for which locales the products are exported in order to have only the needed locale by an user or an output channel.
Example: Peter exports for the spanish translator the locales French and Spanish in order the translator enriches the spanish translation
There is a new parameter "Locale" on all products exports and published products (CSV and Excel) in a new tab "Contents".
This parameter is a list of locales with multiselection. By default all the locales of the channel are selected. If the channel is changed, the locales are updated by the locales of the channel. The user can add a locale or delete a locale.
At least one locale must be selected, the filter is manadatory. If no locale is selected, the following message is displayed "One locale must be …

PIM-5145: Add locale filter on the product export profiles

---

features/Context/DataGridContext.php
features/Context/Page/Base/Grid.php

Fixes
vendor/akeneo/pim-community-dev/features/product/filtering/filter_products_per_metric.feature:24
vendor/akeneo/pim-community-dev/features/product/filtering/filter_products_per_with_multiple_metrics.feature:44
vendor/akeneo/pim-community-dev/features/product/filtering/filter_products_per_with_multiple_metrics.feature:31
vendor/akeneo/pim-community-dev/features/product/filtering/filter_products_per_price.feature:24
vendor/akeneo/pim-community-dev/features/product/filtering/filter_products_per_with_multiple_prices.feature:33
Before, the mink method do these steps n times:
- add a filter
- checks the filtered elements are the good ones
- remove the filter
- add a filter ... and again and again.
Sometimes, it happens that the filter box reload or close itself, without any reason. This …

TIP-36: Ensure datagrid is correclty reseted before checking more filter

---

CHANGELOG-1.5.md
features/Context/DataGridContext.php
features/product/filtering/filter_products_per_option_fields.feature
src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filter/select2-choice-filter.js

When you filter on multi or simple select attributes, once you have put a value in the filter and saved it, you cannot remove this value because values are never filled into filter. You have to remove completely the filter
| Changelog updated | :white_check_mark:

PIM-5802: keep data previously filled in select2 filter

---

.travis.yml

The url `http://get.sensiolabs.org/php-cs-fixer.phar` can lead to a bumped version of php-cs-fixer (eg. an alpha 2.0 version).
By getting the explicit GitHub version, we ensure the stability of this tool.

Download always the same php-cs-fixer version

---

features/export/product-export-builder/export_products_by_locales.feature

In the Enterprise Edition we have to set job profile accesses in order to be able to access a job profil so this scenarios can't work as it.

Fix behat regressions

---

src/Pim/Component/Connector/Processor/Denormalization/FamilyProcessor.php

This PR fixes a typo in a name of a variable which came to be dynamically created. The name of the property in the class is `familyConverter`.

Fix typo in FamilyProcessor

---

CHANGELOG-1.6.md
features/export/product-export-builder/export_products_by_completeness.feature
src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Join/CompletenessJoin.php
src/Pim/Bundle/CatalogBundle/spec/Doctrine/ORM/Filter/CompletenessFilterSpec.php
src/Pim/Bundle/CatalogBundle/spec/Doctrine/ORM/Sorter/CompletenessSorterSpec.php
src/Pim/Bundle/ConnectorBundle/Resources/translations/messages.en.yml
src/Pim/Bundle/ImportExportBundle/JobParameters/FormConfigurationProvider/ProductCsvExport.php
src/Pim/Bundle/ImportExportBundle/JobParameters/FormConfigurationProvider/ProductXlsxExport.php
src/Pim/Bundle/ImportExportBundle/spec/JobParameters/FormConfigurationProvider/ProductCsvExportSpec.php
src/Pim/Bundle/ImportExportBundle/spec/JobParameters/FormConfigurationProvider/ProductXlsxExportSpec.php
src/Pim/Component/Connector/Job/JobParameters/ConstraintCollectionProvider/ProductCsvExport.php
src/Pim/Component/Connector/Job/JobParameters/ConstraintCollectionProvider/ProductXlsxExport.php
src/Pim/Component/Connector/Job/JobParameters/DefaultValuesProvider/ProductCsvExport.php
src/Pim/Component/Connector/Job/JobParameters/DefaultValuesProvider/ProductXlsxExport.php
src/Pim/Component/Connector/Reader/ProductReader.php
src/Pim/Component/Connector/spec/Job/JobParameters/ConstraintCollectionProvider/ProductCsvExportSpec.php
src/Pim/Component/Connector/spec/Job/JobParameters/ConstraintCollectionProvider/ProductXlsxExportSpec.php
src/Pim/Component/Connector/spec/Job/JobParameters/DefaultValuesProvider/ProductCsvExportSpec.php
src/Pim/Component/Connector/spec/Job/JobParameters/DefaultValuesProvider/ProductXlsxExportSpec.php
src/Pim/Component/Connector/spec/Reader/ProductReaderSpec.php

As Peter, I would like to filter on the completeness to export products in order to export only the data needed by an user or an output channel.
There is a new parameter "*Complete*" on all products exports and published products (CSV and Excel) in a new tab "Contents". This parameter is a list of 4 options to define a filter on the completeness on the selected locales:
- Complete on at least one selected locale : option by default, as today
- Complete on all selected locales
- Not complete on all selected locales
- No condition on completeness …

PIM-5426: Add completeness filter to the product export profiles

---

src/Pim/Bundle/EnrichBundle/Doctrine/ORM/Repository/FamilySearchableRepository.php

This PR extract the options filters in a protected method to allow overriding the class.
Before this PR, i could not even properly override the service:
```php
class MyFamilySearchableRepository extends FamilySearchableRepository
{
public function function findBySearch($search = null, array $options = [])
{
// the parent $qb is not available :(
}
}
```
After the PR, i can do it easily:
```php
class MyFamilySearchableRepository extends FamilySearchableRepository
{
protected function applyQueryOptions(QueryBuilder $qb, array $options)
{
parent::applyQueryOptions($qb, $options);
// i can add filters to the query builder
}
}
```
| Added Specs                       |no
| …

FamilySearchRepository: extract applyQueryOptions protected method

---

CHANGELOG-1.5.md
spec/Pim/Bundle/BaseConnectorBundle/Processor/ProductToFlatArrayProcessorSpec.php
src/Pim/Bundle/BaseConnectorBundle/Processor/ProductToFlatArrayProcessor.php
src/Pim/Bundle/BaseConnectorBundle/Resources/config/processors.yml

PR to fix a memory leak on products export.
Problem occurs when PIM is used with EnhancedConnectorBundle. This bundle has it own reader and detach the product in it (https://github.com/akeneo-labs/EnhancedConnectorBundle/blob/v1.2.0/Reader/ProductReader.php#L388). But, if an entity linked to a product (product value, metric, etc) is handled during processor, Doctrine add a reference to the product in unit of work (so in memory) and the product will never detach from it => memory leak :)
There is no problem with the original reader of the PIM because there is a `$this->entityManager->clear()` before read products
@nidup we already call `detach()` for quick export (https://github.com/akeneo/pim-community-dev/blob/master/src/Pim/Bundle/EnrichBundle/Connector/Processor/QuickExport/ProductToFla …

PIM-5824: detach product at the end of process() method

---

src/Akeneo/Component/Classification/Repository/CategoryRepositoryInterface.php

No description needed for this simple fix.

Fix Typo in CategoryRepositoryInterface::getCategoriesByCodes

---

CHANGELOG-1.5.md
features/Context/AssertionContext.php
features/product/join_an_image_to_a_product.feature
src/Pim/Bundle/CatalogBundle/Resources/config/model/doctrine/ProductValue.orm.yml
src/Pim/Bundle/EnrichBundle/Controller/Rest/ProductController.php

When adding a new media to a product, an entry is created in the table “akeneo_file_storage_file_info”. When removing the media, the entry in “akeneo_file_storage_file_info” must be kept so history is preserved, and revert is correctly done in EE.
If the user adds an attribute, upload a media, save the product, then directly remove the attribute field still containing the media, and save the product, in this case the entry in the database is deleted. This is due to the cascade remove perform by Doctrine on the product value.
This does not happen if one first removes the media (but keeps the attribute) and save the product as the product value is still here (as the field), just cleaned through JavaScript. Then, when the user removes the field, it is not linked to the media …

PIM-5712: Keep file reference in db after media removal

---

features/Pim/Behat/Context/Domain/Enrich/Product/AssociationTabContext.php

It happened when `$activeTab->getText()` that `$activeTab` was not in the DOM. We spin on it now to avoid that.

TIP-36: fix association

---

composer.json

Measure bundle is now under akeneo namespace, no needs to add it through composer

Remove measure bundle from composer

---

CHANGELOG-1.5.md
features/import/attribute/import_attributes.feature
features/product/join_an_image_to_a_product.feature
src/Pim/Component/Catalog/Updater/AttributeUpdater.php

When importing attributes without labels, no default attributes label are displayed (should be “[attribute_code]”. Things are fine if no label column is present in the imported file (default label is displayed in the family “Add attribute” drop-down, for example). However, if imported file contains empty label columns, the attribute is not displayed (see screenshot below).
This PR fixes this behavior by preventing the creation of attribute translations if label is empty. …

PIM-5711: Don't create empty attribute translations if attributes are imported with empty labels

---

src/Pim/Component/Catalog/Model/ProductInterface.php

A little PhpDoc fix. For the API and to enable IDE autocomplete.

Fix PhpDoc and remove unused namespace

---

CHANGELOG-1.4.md
features/Context/FixturesContext.php
features/enrich/variant-group/remove_products.feature
src/Pim/Bundle/CatalogBundle/Factory/GroupFactory.php
src/Pim/Component/Connector/Processor/Denormalization/GroupProcessor.php

It was not possible to remove a product from a variant group at the first attempt when the PIM is installed in MongoDB. One needs to do it twice, and the second time the product is indeed removed.
Issue was caused by the fact that at creation, the variant group doesn’t have an associated product template. The template not created during variant group import, only when saved from the UI.
This PR adds an empty ProductTemplate during group creation, directly in the GroupFactory (and only for variant groups). …

PIM-5687: Allow to remove a product from a variant group at first attempt

---

spec/Pim/Component/Catalog/Updater/FamilyUpdaterSpec.php
src/Pim/Component/Catalog/Updater/FamilyUpdater.php

This is end of my previous PR fixing FamilyUpdater. I added this very line as as soon as you get inside this method, requirement should be true. Otherwise, if the requirement existed and equaled false then it would remain... false. 

Fix requirement of families at import

---

src/Pim/Bundle/ConnectorBundle/Resources/translations/messages.en.yml

Crowdin is very strict with Yaml parsing (not like Sf parser)
This fix may avoid that:
https://crowdin.com/translate/akeneo/111/en-fr#12463

Fix Yaml translation to be parsed by crowdin

---

features/Context/AssertionContext.php
features/Context/Page/Base/ProductEditForm.php
features/product/add_new_option_to_choice_attribute.feature

This PR does 3 things:
- little refactor of a behat to avoid weird behavior
- drop gherkin function (unused)
- Add a check to fillTextField to avoid FATAL on DCI. I know, we should refactor this method, but it's not the goal of this PR, it's only to stabilize DCI.

Fix random behat

---

features/attribute/browse/view.feature
features/enrich/variant-group/add_attributes_to_a_variant_group.feature
features/enrich/variant-group/edit_variant_group_attribute_value.feature
features/product/associate_product.feature

The first scenario must be run in CE only (not the same columns expected).
The second one was a false positive in EE and is now fixed.
The last two scenarios are skipped and will be fixed in PIM-5830.

Fix for master

---

CHANGELOG-1.6.md
UPGRADE-1.6.md
features/Context/fixtures/connector_deprecated_batch_jobs.yml
src/Pim/Bundle/BaseConnectorBundle/Reader/Doctrine/ODMProductReader.php
src/Pim/Bundle/BaseConnectorBundle/Resources/config/readers.yml
src/Pim/Bundle/ConnectorBundle/Resources/config/batch_jobs/csv_connector.yml
src/Pim/Bundle/ConnectorBundle/Resources/config/batch_jobs/xlsx_connector.yml
src/Pim/Bundle/ConnectorBundle/Resources/config/readers.yml
src/Pim/Bundle/ConnectorBundle/Resources/config/writers.yml
src/Pim/Bundle/EnrichBundle/Resources/config/batch_jobs.yml
src/Pim/Bundle/InstallerBundle/Resources/config/batch_jobs.yml
src/Pim/Component/Connector/Reader/Database/BaseReader.php
src/Pim/Component/Connector/Reader/Database/ProductReader.php
src/Pim/Component/Connector/Writer/Database/BaseWriter.php
src/Pim/Component/Connector/Writer/Database/ProductAssociationWriter.php
src/Pim/Component/Connector/Writer/Database/ProductWriter.php
src/Pim/Component/Connector/Writer/Database/VariantGroupWriter.php
src/Pim/Component/Connector/spec/Reader/Database/BaseReaderSpec.php
src/Pim/Component/Connector/spec/Reader/Database/ProductReaderSpec.php
src/Pim/Component/Connector/spec/Writer/Database/BaseWriterSpec.php
src/Pim/Component/Connector/spec/Writer/Database/ProductAssociationWriterSpec.php
src/Pim/Component/Connector/spec/Writer/Database/ProductWriterSpec.php
src/Pim/Component/Connector/spec/Writer/Database/VariantGroupWriterSpec.php

Move Doctrine readers ans writers to a more generic `Database` namespace. (As we don't really use Doctrine inside). The is the twin of the *File* readers/writers.
| Migration script                  | - 

TIP-428: move Doctrine readers and writers

---

CHANGELOG-1.5.md
features/Pim/Behat/Context/NavigationContext.php
features/navigation/browse_navigation_history.feature
src/Oro/Bundle/NavigationBundle/Event/ResponseHistoryListener.php
src/Pim/Bundle/EnrichBundle/Controller/Rest/NavigationHistoryController.php
src/Pim/Bundle/EnrichBundle/Resources/config/controllers.yml
src/Pim/Bundle/EnrichBundle/Resources/config/requirejs.yml
src/Pim/Bundle/EnrichBundle/Resources/config/routing.yml
src/Pim/Bundle/EnrichBundle/Resources/config/routing/navigation_history.yml
src/Pim/Bundle/EnrichBundle/Resources/public/js/manager/history-item-manager.js
src/Pim/Bundle/EnrichBundle/Resources/views/Product/edit.html.twig
src/Pim/Bundle/NavigationBundle/DependencyInjection/PimNavigationExtension.php
src/Pim/Bundle/NavigationBundle/Resources/config/entities.yml
src/Pim/Bundle/NavigationBundle/Resources/config/repositories.yml
src/Pim/Bundle/NavigationBundle/Resources/config/savers.yml

In the history tab of the pinbar, after visiting a product page, one can see the text “Products %product.sku% | Edit” (see the screenshot below).
“%product.sku%” is not replaced by the real product SKU because the ProductController returns only the product ID (directly from the request), then all other product data are retrieved through AJAX requests.
This PR fixes this issue by providing to the template the product SKU (and only the SKU) in addition to the ID, so the history is correctly generated.
| …

PIM-5828: Fix "Product | Edit" entry in history menu

---

src/Akeneo/Bundle/BatchBundle/Command/BatchCommand.php

Help for the "config" option is wrong. It currently displays the following message:
```-c, --config=CONFIG      Override job configuration (formatted as json. ie: php app/console akeneo:batch:job -c '[{"reader":{"filePath":"/tmp/foo.csv"}}]' acme_product_import)```
The JSON syntax is wrong and should be `"{\"filePath\":\"/tmp/foo.csv\"}"`

PIM-5850: Update help for akeneo:batch:job command

---

src/Pim/Bundle/UserBundle/Resources/translations/messages.en.yml

Fix remark from Crowdin
Exact acronym is "SSL", not "Ssl".
https://crowdin.com/translate/akeneo/291/en-hu#7107

Fix SSL translation

---

features/Context/Page/Base/Form.php
features/Context/Page/Base/Grid.php
features/Context/Page/Batch/Classify.php
features/Context/Page/Category/CategoryView.php
features/Context/Page/Product/Edit.php
features/Pim/Behat/Context/NavigationContext.php
features/Pim/Behat/Decorator/Page/GridCapableDecorator.php
features/Pim/Behat/Decorator/Page/PanelableDecorator.php
features/Pim/Behat/Decorator/Tab/ComparableTabDecorator.php
features/Pim/Behat/Decorator/TabElement/ComparisonPanelDecorator.php
features/Pim/Behat/Decorator/Tree/JsNodeDecorator.php
features/Pim/Behat/Decorator/Tree/JsTreeDecorator.php

Folders in `Pim\Behat\Decorator\` should not be suffixed by Decorator
Only classes have to be.

Clean decorator namespaces

---

src/Pim/Bundle/EnrichBundle/Controller/MassEdit/AbstractMassEditController.php
src/Pim/Bundle/EnrichBundle/Controller/MassEdit/FamilyController.php
src/Pim/Bundle/EnrichBundle/Controller/MassEdit/ProductController.php
src/Pim/Bundle/EnrichBundle/Resources/config/controllers.yml

This PR allows integrators to easily declare a new Twig Template **for an existing mass edit operation**, plus the fact that they **don't need anymore to override the EnrichBundle** to add Mass Edit Operations.
PS: We could put those template paths as yml parameters too.

[WIP] Operation proposition

---

features/Context/NavigationContext.php
features/datagrid/datagrid_views.feature
features/locale/change_system_locale.feature
features/locale/change_user_locale.feature
features/localization/product/edit_product.feature
features/user/show_user.feature

This PR:
- Removes navigation specific methods to replace by "I am on the xxx page"
- Change I select xxx locale to use label instead of identifier

Remove navigation specific methods

---

CHANGELOG-1.4.md
src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid/listener/oro-column-form-listener.js

This patch prevents the association grid from sending/getting all checked rows into/from the backend and uses the state saved into the DOM instead (hidden input).
When the grid loads the "oro-column-listener" restores the state (column checked and unchecked during the session) from the DOM and applies it to the grid.
**Definition Of Done **

PIM-5863: Fix row selection in association grid

---

features/export/product-export-builder/export_products_by_categories.feature
src/Pim/Bundle/ImportExportBundle/Resources/public/js/product-export/categories-selector.js

We introduced a bug recently when we merged the product export builder "select categories" feature. A case was not covered by any test so when we changed the code it was not tested (and have not been tested manually after the code review have been fixed)
| Review and 2 GTM                  | :white_check_mark: 
| Micro Demo to the PO (Story only) | :white_check_mark: 

PIM-5421: Fix categories selector in the export builder when the channel change

---

CHANGELOG-1.5.md
features/Context/Page/Base/Grid.php
features/Context/Page/Product/Edit.php
features/family/edit_a_family.feature
features/product/filtering/filter_products_per_with_multiple_metrics.feature
spec/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/QueryGenerator/AttributeAsLabelUpdatedQueryGeneratorSpec.php
src/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/QueryGenerator/AttributeAsLabelUpdatedQueryGenerator.php

When "Attribute used as label" value is changed on the family edition screen, labels are empty on the product data grid for products of this family. This issue occurs only with mongodb storage
| Added Behats                      | yes 
| Micro Demo to the PO (Story only) | no 

PIM-5864: Attribute used as label" not displayed after being changed in the Family

---

app/check.php
composer.json

As we upgraded PHP version from 5.4 to 5.6. We apply those modifications on travis and composer.

TIP-400: PIM compatible with PHP 5.6

---

features/localization/product/display_localized_history.feature
src/Pim/Bundle/DataGridBundle/Resources/translations/jsmessages.en.yml

This very tiny PR removes useless punctuation on two translations.
This is before all for consistency with other popins in Akeneo.
| Review and 2 GTM                  | :white_check_mark: 

PIM-5490: Minor fixes

---

CHANGELOG-1.6.md
src/Pim/Bundle/UIBundle/Resources/public/css/buttons.less

Button for launching assets upload in EE do not come to its initial state after clicking. This also affect the login button and probably other ones, but these buttons are not visible long enough to see the glitch.
Here is a little set of screenshots of the login button to understand the problem:
- Initial state of the button
- clicking
- after
The "after" state should be the same than the "initial" one. This PR fixes this glitch. …

PIM-5888: Fix button outline after click

---

CHANGELOG-1.6.md
src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/AttributeRepository.php
src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/GroupRepository.php
src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Sorter/FamilySorter.php
src/Pim/Bundle/CatalogBundle/spec/Doctrine/ORM/Repository/AttributeRepositorySpec.php
src/Pim/Bundle/CatalogBundle/spec/Doctrine/ORM/Sorter/FamilySorterSpec.php
src/Pim/Bundle/DataGridBundle/Extension/Selector/Orm/Product/FamilySelector.php
src/Pim/Bundle/DataGridBundle/spec/Extension/Selector/Orm/Product/FamilySelectorSpec.php
src/Pim/Bundle/EnrichBundle/Doctrine/ORM/Repository/AttributeGroupRepository.php
src/Pim/Bundle/EnrichBundle/Doctrine/ORM/Repository/AttributeRepository.php
src/Pim/Bundle/EnrichBundle/Doctrine/ORM/Repository/CategoryRepository.php
src/Pim/Bundle/EnrichBundle/Doctrine/ORM/Repository/FamilyRepository.php
src/Pim/Bundle/EnrichBundle/Doctrine/ORM/Repository/GroupRepository.php
src/Pim/Bundle/EnrichBundle/Doctrine/ORM/Repository/GroupTypeRepository.php
src/Pim/Bundle/EnrichBundle/spec/Doctrine/ORM/Repository/AttributeGroupRepositorySpec.php
src/Pim/Bundle/EnrichBundle/spec/Doctrine/ORM/Repository/AttributeRepositorySpec.php
src/Pim/Bundle/EnrichBundle/spec/Doctrine/ORM/Repository/FamilyRepositorySpec.php
src/Pim/Bundle/EnrichBundle/spec/Doctrine/ORM/Repository/GroupRepositorySpec.php
src/Pim/Bundle/EnrichBundle/spec/Doctrine/ORM/Repository/GroupTypeRepositorySpec.php

When you create families using the csv_family_import and if you do not set any family labels, the family code is not displayed in the product grid. We should display the family code between brackets like everywhere else in the UI.
This happens only when you create families through imports. During CSV import, we import empties values instead of null values. 
| Added Behats                      |  no
| Changelog updated                 | yes 

PIM-5854: The family code is not displayed at all in the product grid when no family labels

---

src/Pim/Bundle/UIBundle/Resources/public/css/pim.less

When we had lot of categories, the last children were not visible on some browsers. The problem is that jsTree doesn't handle large amount of children very well (I think they do some calculation in javascript for height/padding). A custom fix is to add extra padding for the last children using CSS.
Note: we use an old version of jsTree (1.0-rc3). The current is 3.3.1. We need to update this later.

SDS-614: categories are not visible

---

src/Pim/Bundle/UIBundle/Resources/public/css/pim.less

Git diff :
```
-<U+2028>// SDS-614: custom fix: allow to display correctly tree with large children count<U+2028>
-.jstree > ul > li:last-child {<U+2028>
-  padding-bottom: 80px<U+2028>;
+// SDS-614: custom fix: allow to display correctly tree with large children count
+.jstree > ul > li:last-child {
+  padding-bottom: 80px;
```

SDS-614: Fix CSS encoding weird chars

---

src/Acme/Bundle/AppBundle/Resources/doc/index.md
src/Pim/Bundle/CatalogBundle/Doctrine/Common/Saver/ProductSaver.php

Hello @nidup 
Thank you very much for your response.
Yes I'm talking about the versioning change set and yes we use data from the $event->getEventType() directly.
- What is the format of the event you want to send? (paste sample json/xml please)
We use json. I pasted in some example.
- Do you want to put only the updated product fields in this event or the whole product data?
We want to put all the product data + the change set.
- How do you plan to build the content of this event in your listener/subscriber?
We use Normalizers to build the content of the events that we send to EventStore. We extended your Pim\Bundle\TransformBundle\Normalizer\Structured\ProductNormalizer and perform some formatting on its response so we don't send data which is only important for PIM (like validation …

Example of eventstore events

---

features/Context/Page/Base/Grid.php
features/Pim/Behat/Decorator/Export/Filter/MediaDecorator.php
features/export/product-export-builder/export_products_by_files.feature
features/export/product-export-builder/export_products_by_images.feature
features/export/product-export-builder/export_products_by_metrics.feature
features/export/product-export-builder/export_products_by_multiselect_reference_data.feature
features/export/product-export-builder/export_products_by_price_collections.feature
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/filters.yml
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/product_export_edit.yml
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/product_export_show.yml
src/Pim/Bundle/EnrichBundle/Resources/config/requirejs.yml
src/Pim/Bundle/EnrichBundle/Resources/public/js/filter/attribute/media.js
src/Pim/Bundle/EnrichBundle/Resources/public/templates/filter/attribute/media.html
src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml
src/Pim/Bundle/UIBundle/Resources/public/css/pim.less

Adds media filter on product export builder. This filter works both on media and file attribute types.

PIM-5635: Add media filter on product export builder

---

src/Pim/Bundle/PdfGeneratorBundle/Resources/views/Product/renderPdf.html.twig

Following issue happens when using PHP7 (still experimental support for now).

TIP-307: fix download pdf issue when using PHP7

---

features/Context/AssertionContext.php
features/Context/Page/Product/Edit.php
features/localization/product/display_localized_history_of_complex_prices.feature
features/navigation/browse_navigation_history.feature
features/product/sequential_edit/sequential_edit.feature

This PR stabilize our most unstable behat scenarios. Those scenarios was requiring at least 1.5 retry to pass. Here are the impacted scenarios:
| Feature | Line | Average attempts
| ---------- | ------ | ------------------------
| navigation/browse_navigation_history.feature | 15 | 2.2000
| product/sequential_edit/sequential_edit.feature | 41 | 2.0714
| localization/product/display_localized_history_of_complex_prices.feature | 41 | 1.7857
| export/product-export-builder/export_products_by_metric.feature | 32 | 1.5 …

TIP-474: Stabilize most randomish behat scenarios

---

composer.json

symfony/icu has been deprecated in favor of symfony/intl
Why this change?
done with 3 local measures on `pim:install:db`
before this change
* pim:install:db -e prod  65.19s user 1.08s system 77% cpu 1:25.41 total
* pim:install:db -e prod  63.59s user 0.89s system 77% cpu 1:23.13 total
* pim:install:db -e prod  65.61s user 1.08s system 76% cpu 1:27.72 total
after this change
* pim:install:db -e prod  64.32s user 1.04s system 77% cpu 1:24.76 total
* pim:install:db -e prod  63.08s user 0.94s system 77% cpu 1:22.70 total
* pim:install:db -e prod  63.98s user 0.90s system 77% cpu 1:23.44 total
* to be able to make the PIM works with Mongo and PHP7, we need to have `doctrine/mongodb-odm:1.1.0` (see https://github.com/doctrine/mongodb-odm/releases/tag/1.1.0)
* our current version of …

TIP-298: bump dependencies

---

features/export/edit_an_export.feature
features/export/product-export-builder/export_products_by_metrics.feature
features/export/product-export-builder/export_products_by_price_collections.feature
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/filters.yml
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/product_export_edit.yml
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/product_export_show.yml
src/Pim/Bundle/EnrichBundle/Resources/public/js/export/product/edit/content/data.js
src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml

The fields of the data filters, in the “content” tab of the product export, were ordered randomly. This PR intends to display them in a predefined order.
First are rendered the filters of the product “fields” plus the identifier in this precise order:
- family
- status
- complete
- update
- category
- sku
Then are rendered the attribute filters, alphabetically ordered. …

PIM-5635: Order filters in product export builder

---

src/Pim/Bundle/EnrichBundle/Resources/config/requirejs.yml
src/Pim/Bundle/EnrichBundle/Resources/public/js/export/product/edit/content/data/help.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/filter/attribute/attribute.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/filter/attribute/boolean.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/filter/attribute/date.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/filter/attribute/media.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/filter/attribute/metric.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/filter/attribute/number.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/filter/attribute/price-collection.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/filter/attribute/select.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/filter/attribute/string.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/filter/product/category.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/filter/product/category/selector.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/attributes.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/attributes/copy.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/locale-switcher.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/scope-switcher.js
src/Pim/Bundle/UIBundle/Resources/public/css/form.less
src/Pim/Bundle/UIBundle/Resources/public/css/pim.less

The goal is to have that next to the filters:
The locale and scope are saved and sent to the PQB for filtering.
Dropdowns are the same used in PEF, mass edit, etc.
TODO: unskip related behats

PIM-5635: Add context on filters

---

CHANGELOG-1.6.md
features/datagrid/display_many_datagrid_filters.feature
src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/collection-filters-manager.js

Previously some reserved keywords like "length" break the display of the product grid. This fix allow any codes to be used for attributes.

PIM-5869: Allow any codes to be used for attributes

---

spec/Pim/Bundle/NotificationBundle/EventSubscriber/JobExecutionNotifierSpec.php
src/Pim/Bundle/NotificationBundle/EventSubscriber/JobExecutionNotifier.php

Replace a wrong usage of NotImplementedExcption (from Symony intl extension) by a simple RuntimeException.

PIM-5910: fix a wrong use of NotImplementedException

---

src/Pim/Bundle/ConnectorBundle/Resources/config/archiving.yml
src/Pim/Bundle/DataGridBundle/Controller/ProductExportController.php
src/Pim/Bundle/EnrichBundle/Connector/Job/JobParameters/ConstraintCollectionProvider/ProductQuickExport.php
src/Pim/Bundle/EnrichBundle/Connector/Job/JobParameters/DefaultValuesProvider/ProductQuickExport.php
src/Pim/Bundle/EnrichBundle/Connector/Processor/QuickExport/ProductProcessor.php
src/Pim/Component/Connector/Archiver/ArchivableFileWriterArchiver.php
src/Pim/Component/Connector/Archiver/ZipFilesystemFactory.php
src/Pim/Component/Connector/Writer/File/AbstractFileWriter.php
src/Pim/Component/Connector/Writer/File/AbstractItemMediaWriter.php
src/Pim/Component/Connector/spec/Archiver/ArchivableFileWriterArchiverSpec.php
src/Pim/Component/Connector/spec/Archiver/ZipFilesystemFactorySpec.php
src/Pim/Component/Connector/spec/Writer/File/Csv/ProductWriterSpec.php
src/Pim/Component/Connector/spec/Writer/File/Csv/VariantGroupWriterSpec.php
src/Pim/Component/Connector/spec/Writer/File/Csv/WriterSpec.php
src/Pim/Component/Connector/spec/Writer/File/Xlsx/ProductWriterSpec.php
src/Pim/Component/Connector/spec/Writer/File/Xlsx/VariantGroupWriterSpec.php
src/Pim/Component/Connector/spec/Writer/File/Xlsx/WriterSpec.php
upgrades/schema/Version_1_6_20160722155535_quick_export.php

TIP-559: Rework exports: last enhancements

---

src/Pim/Bundle/EnrichBundle/Resources/config/requirejs.yml
src/Pim/Bundle/EnrichBundle/Resources/public/js/remover/product-remover.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/remover/variant-group-remover.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/saver/product-saver.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/saver/variant-group-saver.js

We used to extend the savers the bad way. Saver instances were modified by reference inside requirejs, so you could have for example a product saver on the variant group form.
I fixed also the removers, same issue.

PIM-5918: Fix conflict between saver instances

---

features/mass-action/quick_export.feature
src/Pim/Bundle/EnrichBundle/Connector/Job/JobParameters/ConstraintCollectionProvider/ProductQuickExport.php
src/Pim/Bundle/EnrichBundle/Connector/Processor/QuickExport/ProductProcessor.php
upgrades/schema/Version_1_6_20160722155535_quick_export.php

**Issue:**
When we select all entities in the product grid and quick export, the job fails because the job parameter "filters" is an empty array.
The PIM fails to validate the constraint NotBlank on this job parameter.
**Solution:**
Set the same constraint as the CSV Product export for the "filters" jobParameter
___
**This PR also contains:**
- Fixes an issue with the quick export when a warning would be thrown about a media not found.
- Reverts the quick-export migrations (seen with @aRn0D) 
___
| …

Fix quick export of all products

---

features/Pim/Behat/Context/Domain/Spread/ExportProfilesContext.php
src/Akeneo/Component/Batch/Job/Job.php
src/Akeneo/Component/Batch/Job/JobInterface.php
src/Pim/Bundle/EnrichBundle/Connector/Processor/QuickExport/ProductProcessor.php
src/Pim/Component/Connector/Processor/Normalization/ProductProcessor.php
src/Pim/Component/Connector/Processor/Normalization/VariantGroupProcessor.php
src/Pim/Component/Connector/Writer/File/AbstractItemMediaWriter.php
src/Pim/Component/Connector/spec/Processor/Normalization/ProductProcessorSpec.php
src/Pim/Component/Connector/spec/Processor/Normalization/VariantGroupProcessorSpec.php
src/Pim/Component/Connector/spec/Writer/File/Csv/ProductWriterSpec.php
src/Pim/Component/Connector/spec/Writer/File/Csv/VariantGroupWriterSpec.php
src/Pim/Component/Connector/spec/Writer/File/Xlsx/ProductWriterSpec.php
src/Pim/Component/Connector/spec/Writer/File/Xlsx/VariantGroupWriterSpec.php

This PR adds the possibility to have a working directory for batches. Within this directory you can do whatever you want (download files, create temporary files etc..). This working directory is easily accessible from your reader/processor/writer/step without having to write the same specific logic each time.
This working directory is automatically created before the job starts and is automatically destroyed once the job is terminated.
Then, in your step you can retrieve the working directory via the job execution context:
```
$workingDir = $jobExecution->getExecutionContext()->get(JobInterface::WORKING_DIRECTORY_PARAMETER);
```
What's done here:
| Added Behats …

TIP-539: allow the batches to have a working directory

---

build.xml

File `phpspec-fix` has been deleted on this PR https://github.com/akeneo/pim-community-dev/pull/4809, so all builds about specs are failed on CI

Fix specs on CI

---

src/Pim/Component/Connector/ArrayConverter/FlatToStandard/Attribute.php
src/Pim/Component/Connector/spec/ArrayConverter/FlatToStandard/AttributeSpec.php

Testing an expression in case is evil :angry: 
For example, `case false !== strpos($field, 'label-', 0)` will match with `$field = 0` :scream: 
| Added Specs                       |yes
| Changelog updated                 |no
| Review and 2 GTM                  |yes

PIM-5933: fix Attribute flat to standard converter

---

src/Pim/Bundle/ConnectorBundle/Resources/config/readers.yml
src/Pim/Component/Connector/Archiver/CsvInvalidItemWriter.php
src/Pim/Component/Connector/Reader/File/Csv/ProductReader.php
src/Pim/Component/Connector/Reader/File/Csv/Reader.php
src/Pim/Component/Connector/Reader/File/Csv/VariantGroupReader.php
src/Pim/Component/Connector/Reader/File/FileIterator.php
src/Pim/Component/Connector/Reader/File/Xlsx/ProductReader.php
src/Pim/Component/Connector/Reader/File/Xlsx/Reader.php
src/Pim/Component/Connector/spec/Reader/File/Csv/ProductReaderSpec.php
src/Pim/Component/Connector/spec/Reader/File/Csv/ReaderSpec.php
src/Pim/Component/Connector/spec/Reader/File/FileIteratorSpec.php
src/Pim/Component/Connector/spec/Reader/File/Xlsx/ProductReaderSpec.php
src/Pim/Component/Connector/spec/Reader/File/Xlsx/ReaderSpec.php

This PR add the possibilty to configure file iterators from the DI by injecting factory options.
For example, a XLSX file iterator could need read (or skip) a specific worksheet configured in the DI.
If i want options to be injected in my custom file iterator, i need the factory to inject them.
| Added Specs                       |no
| Changelog updated                 |no
| Review and 2 GTM                  |yes

File import/export: add iterator options in the DI

---

app/PimRequirements.php
composer.json
src/Pim/Bundle/CatalogBundle/Doctrine/ArrayApcCache.php

When installing the PIM master with PHP7 + php-apcu, the PIM is not usable in web, in prod mode due to the following issue:
```PHP Fatal error:  Uncaught Symfony\\Component\\Debug\\Exception\\FatalThrowableError: Fatal error: Call to undefined function Doctrine\\Common\\Cache\\apc_fetch() in /home/nico/git/pim-ce-16-orm/vendor/doctrine/cache/lib/Doctrine/Common/Cache/ApcCache.php:41\nStack trace:\n#0 /home/nico/git/pim-ce-16-orm/vendor/doctrine/cache/lib/Doctrine/Common/Cache/CacheProvider.php(212): Doctrine\\Common\\Cache\\ApcCache->doFetch('DoctrineNamespa...')\n#1 /home/nico/git/pim-ce-16-orm/vendor/doctrine/cache/lib/Doctrine/Common/Cache/CacheProvider.php(185): Doctrine\\Common\\Cache\\CacheProvider->getNamespaceVersion()\n#2 …
```

PHP7 and APCu #4829

---

CHANGELOG-1.6.md
features/import/product_variant_group/import_variant_group_with_scopable_or_localizable_data.feature
src/Pim/Component/Catalog/Updater/VariantGroupUpdater.php
src/Pim/Component/Catalog/spec/Updater/VariantGroupUpdaterSpec.php

Fix for an issue when importing variant group : the PIM deletes existing values and replaces them by the imported one's. For the scoped and/or localized attributes, it can cause data loss when processing a partial import.
**Example**
I have an attribute "description" on a variant group with this existing values : 
```
Array
(
[0] => Array
(
[locale] => en_US
[scope] => ecommerce
[data] => desc US
)
[2] => Array
(
[locale] => de_DE
[scope] => ecommerce
[data] => desc DE
)
)
```
I process an import with only this value for the attribute "description" :
```
Array
(
[description] => Array
(
[0] => Array
(
[locale] => en_US
[scope] => ecommerce
[data] => desc EN import
)
)
)
```
The en_US value will be updated but the de_DE value will be deleted from the database.
**Fix**
I replaced the …

PIM-5915: Partial update on Variant Groups remove existing data

---

CHANGELOG-1.6.md
src/Pim/Bundle/UIBundle/Resources/public/css/form.less

100% CSS fix. When validating a form, the indicator appearance which is displayed on the tabs with errors isn't clear. I adjusted it.
Before :
https://akeneo.atlassian.net/secure/attachment/28500/Screenshot_20160810_112115.png
After :
https://akeneo.atlassian.net/secure/attachment/28502/capture.jpg

PIM-5929: Fix the validation issue indicator appearance on form tabs

---

src/Pim/Component/Connector/Reader/File/FileIterator.php
src/Pim/Component/Connector/spec/Reader/File/FileIteratorSpec.php

The internal reader can be null if an exception occured before its instanciation.
| Added Specs                       |yes
| Changelog updated                 |no
| Review and 2 GTM                  |yes

FileIterator: close reader only if not null

---

features/mass-action/classify_product.feature
features/mass-action/mass_actions_on_all_entities.feature
src/Pim/Bundle/EnrichBundle/Controller/MassEdit/AbstractMassEditController.php

Fix the back button behaviour on mass-classify second step (configure)
| Tech Doc                          | Y

PIM-5926: When I go back in mass-classify products, I return to the mass-edit attributes

---

CHANGELOG-1.6.md
features/export/export_products_without_media.feature
src/Pim/Component/Connector/Processor/Normalization/ProductProcessor.php
src/Pim/Component/Connector/spec/Processor/Normalization/ProductProcessorSpec.php

When you export products without media we remove all media attributes from the generated file.
| Micro Demo to the PO (Story only) | TODO

PIM-5928: Export products without media

---

src/Pim/Bundle/CatalogBundle/Doctrine/ORM/CompletenessGenerator.php
src/Pim/Bundle/ConnectorBundle/DependencyInjection/Compiler/RegisterFlatToStandardConverterPass.php
src/Pim/Component/Connector/ArrayConverter/FlatToStandard/Product.php
src/Pim/Component/Connector/ArrayConverter/FlatToStandard/Product/AssociationColumnsResolver.php
src/Pim/Component/Connector/ArrayConverter/FlatToStandard/Product/ValueConverter/ValueConverterRegistry.php
src/Pim/Component/Connector/ArrayConverter/FlatToStandard/Product/ValueConverter/ValueConverterRegistryInterface.php
src/Pim/Component/Connector/spec/ArrayConverter/FlatToStandard/Product/AssociationColumnsResolverSpec.php
src/Pim/Component/Connector/spec/ArrayConverter/FlatToStandard/ProductSpec.php

This PR aims to reduce the time of product imports. There are two axes of improvements in this PR:
1. reduce the time spent in the completeness calculation. Adding the completeness calculation during the save of a product has a huge impact on computer with non SSD drives.
2. reduce the time spent in greedy methods (lot of CPU time) or methods that are called a very lot of times 
Note: this PR treats only the import of new products. We currently have a memory leak on the import of MongoDB updated products. @skeleton is taking care of that :)
Note: the benchmarks you'll see below have been realized on the _core-perf_ machine.
Internally, we changed quite a lot of things between the products import 1.5 and the products import master:
* the processors now receives the standard format
* which …

TIP-568: reduce time import of products

---

CHANGELOG-1.6.md
UPGRADE-1.6.md
features/Context/Page/Dashboard/Index.php
features/export/edit_an_export.feature
features/export/ensure_acl.feature
features/import/edit_an_import.feature
src/Pim/Bundle/ConnectorBundle/Resources/config/archiving.yml
src/Pim/Bundle/ConnectorBundle/Resources/config/job_defaults.yml
src/Pim/Bundle/ImportExportBundle/Controller/JobProfileController.php
src/Pim/Bundle/ImportExportBundle/Form/Type/JobInstanceFormType.php
src/Pim/Bundle/ImportExportBundle/Form/Type/JobParametersType.php
src/Pim/Bundle/ImportExportBundle/Resources/config/acl.yml
src/Pim/Bundle/ImportExportBundle/Resources/config/form_types.yml
src/Pim/Bundle/ImportExportBundle/Resources/config/view_elements/job_profile.yml
src/Pim/Bundle/ImportExportBundle/Resources/translations/messages.en.yml
src/Pim/Bundle/ImportExportBundle/Resources/views/JobProfile/Tab/history.html.twig
src/Pim/Bundle/ImportExportBundle/Resources/views/JobProfile/Tab/job_content.html.twig
src/Pim/Bundle/ImportExportBundle/Resources/views/JobProfile/create.html.twig
src/Pim/Bundle/ImportExportBundle/Resources/views/JobProfile/edit.html.twig
src/Pim/Component/Connector/Archiver/AbstractInvalidItemWriter.php
src/Pim/Component/Connector/Archiver/CsvInvalidItemWriter.php
src/Pim/Component/Connector/Archiver/XlsxInvalidItemWriter.php
src/Pim/Component/Connector/Job/JobParameters/ConstraintCollectionProvider/ProductCsvExport.php
src/Pim/Component/Connector/Job/JobParameters/ConstraintCollectionProvider/ProductXlsxExport.php
src/Pim/Component/Connector/Job/JobParameters/ConstraintCollectionProvider/SimpleCsvExport.php
src/Pim/Component/Connector/Job/JobParameters/ConstraintCollectionProvider/SimpleXlsxExport.php
src/Pim/Component/Connector/Job/JobParameters/DefaultValuesProvider/ProductCsvExport.php
src/Pim/Component/Connector/Job/JobParameters/DefaultValuesProvider/ProductXlsxExport.php
src/Pim/Component/Connector/spec/Job/JobParameters/DefaultValuesProvider/ProductCsvExportSpec.php
src/Pim/Component/Connector/spec/Job/JobParameters/DefaultValuesProvider/ProductXlsxExportSpec.php

Add four separate rights for the job profile tabs:
- Access the "General properties" in Show profile
- Access the "General properties" in Edit profile
- Access the "Content" in Show profile
- Access the "Content" in Edit profile
Moved the product export job names for the visibility checker of the content tab into a pim_parameter instead of the definition of service.
___
Problems:
- When one of the tabs (or both) are not shown, the submission of the form on save is incomplete (because possibly half of the form was not shown to the user). Hence, the need for a "Patch" form submission instead of POST (which would erase information about the job profile) coupled with validation groups.
- When a user has no rights over the edit "content" and "general properties" tab. The user is still able to …

PIM-5798: manage permission on export profiles tabs

---

features/export/create_an_export.feature
features/import/create_an_import.feature
src/Pim/Bundle/ImportExportBundle/Resources/views/ExportProfile/edit.html.twig
src/Pim/Bundle/ImportExportBundle/Resources/views/ImportProfile/edit.html.twig
src/Pim/Bundle/ImportExportBundle/Resources/views/JobProfile/edit.html.twig

Fix back button for the import/export profile edit page. Now clicking on back button display the job profile.

PIM-5924: Back button of an export edition should back to the export view

---

src/Pim/Bundle/UIBundle/Resources/public/css/pim.less

Mass edit with "select2" attributes were broken, due to a bad CSS (unreachable select2 clicking zone)
This PR fixes it.
| Review and 2 GTM                  | n

PIM-5955: Fix CSS for Select2 on mass edit

---

src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/product.yml

Previously, the first action was "Delete". It's confusing as it's not the main action in a day-to-day work.
The mass action order now is:
- Mass Edit
- Sequential Edit
- Category Edit
- Delete

PIM-5954: Change order of bulk actions in product grid

---

CHANGELOG-1.6.md
features/dashboard/display_last_operations_widget.feature
src/Pim/Bundle/DashboardBundle/Resources/public/js/last-operations-widget.js

The button was append before to know if we had data or not. Then if we had no data we hide it. That was the wrong way to do it. So, if the CI a little bit faster than usual, it has the time to clic on the button before we hide it -> the scenario pass.
Now, we wait to know if we have data or not to append the button, or to hide it if it is already here.
Scenario fixed.

PIM-5935: Fix unstable scenario about view all button in dashboard

---

CHANGELOG-1.6.md
src/Pim/Bundle/VersioningBundle/Manager/VersionManager.php

Detach the previous version to improve performances and fix a small memory leak when we import products already in database.
With the medium catalog, try to import 2500 products:
| time | memory used
------ | ------ | ------
Before fix | 32 min | 447Mo
With fix | 23 min | 341Mo

TIP-568: Improve performances on product import

---

CHANGELOG-1.6.md
src/Pim/Bundle/ConnectorBundle/Resources/translations/messages.en.yml
src/Pim/Bundle/ImportExportBundle/JobParameters/FormConfigurationProvider/ProductCsvExport.php
src/Pim/Bundle/ImportExportBundle/JobParameters/FormConfigurationProvider/ProductCsvImport.php
src/Pim/Bundle/ImportExportBundle/JobParameters/FormConfigurationProvider/ProductXlsxExport.php
src/Pim/Bundle/ImportExportBundle/JobParameters/FormConfigurationProvider/SimpleCsvExport.php
src/Pim/Bundle/ImportExportBundle/JobParameters/FormConfigurationProvider/SimpleCsvImport.php
src/Pim/Bundle/ImportExportBundle/JobParameters/FormConfigurationProvider/SimpleXlsxExport.php
src/Pim/Bundle/ImportExportBundle/JobParameters/FormConfigurationProvider/SimpleXlsxImport.php
src/Pim/Bundle/ImportExportBundle/JobParameters/FormConfigurationProvider/SimpleYamlExport.php
src/Pim/Bundle/ImportExportBundle/JobParameters/FormConfigurationProvider/SimpleYamlImport.php
src/Pim/Bundle/ImportExportBundle/JobParameters/FormConfigurationProvider/VariantGroupCsvExport.php
src/Pim/Bundle/ImportExportBundle/JobParameters/FormConfigurationProvider/VariantGroupCsvImport.php
src/Pim/Bundle/ImportExportBundle/JobParameters/FormConfigurationProvider/VariantGroupXlsxExport.php
src/Pim/Bundle/ImportExportBundle/spec/JobParameters/FormConfigurationProvider/ProductCsvExportSpec.php
src/Pim/Bundle/ImportExportBundle/spec/JobParameters/FormConfigurationProvider/ProductXlsxExportSpec.php

This PR:
- fixes some tooltips in XLSX jobs containing mentions to CSV
- fixes some tooltips in export jobs containing import descriptions
- cleans unused translation keys
Concretely, I duplicated all translation keys for xlsx and yml and remove/fix when needed (for example xlsx jobs don't need the "delimiter" key).
| Added Specs                       | n/a
| Added Behats                      | n/a
| Tech Doc                          | n/a

PIM-5938: Use distinct translations for each import/export format

---

CHANGELOG-1.5.md
src/Pim/Bundle/DataGridBundle/Resources/views/Datagrid/_views.html.twig

Fix default display of a product grid when the user have a custom view in his settings.

PIM-5862: The default custom view does not display the product grid correctly for new user

---

web/app.php

This PR add missing lines in the web/app.php file that we forgot to add when we upgrade from sf2.3 to sf2.7. If this line is not added it doesn't work with the APC cache.

Update file according to sf2.7 #4937

---

CHANGELOG-1.6.md
features/Context/Page/Base/Base.php
features/Context/Page/Base/Form.php
features/Pim/Behat/Context/JobContext.php
features/export/product-export-builder/export_products_by_families.feature
src/Pim/Bundle/EnrichBundle/Resources/public/js/filter/product/family.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/field/metric-field.js
src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml

In the product export builder, the field of the family filter is empty if no family are selected. This is confusing because the user don't know what the empty field means.
This PR fixes this problem by adding two default message: one when showing the export profile in read only, another when editing the export profile.

PIM-5952: Add default message in empty family filter

---

CHANGELOG-1.6.md
features/Pim/Behat/Context/JobContext.php
features/export/edit_an_export.feature
src/Pim/Bundle/EnrichBundle/Resources/public/js/export/product/edit/content/data.js
src/Pim/Bundle/EnrichBundle/Resources/public/templates/filter/product/family.html

Product export builder comes with a set of default filters, that cannot be removed. Those filters should always be in this order:
- family
- status
- complete
- update
- category
- product identifier
Other filters should be alphabetically sorted, but **the product identifier should always stay at the end of the list**.

PIM-5965: Fix default product export filters order

---

CHANGELOG-1.6.md
features/product/completeness/display_completeness_with_selects.feature
src/Pim/Bundle/CatalogBundle/Doctrine/ORM/CompletenessGenerator.php

Due to [this completeness optimization](https://github.com/akeneo/pim-community-dev/pull/4863), the PIM is not installable anymore on MySQL 5.7
Officially we don't support MySQL 5.7, but the latest Ubuntu ships with it. Which means a lot of devs will not understand why the PIM is not installable on their LAMP machine...
The problem is that (since the beginning of the PIM) the completeness is calculated thanks to a SQL request than is not SQL92 compliant: we select data that is not aggregated. MySQL 5.6 and 5.5 were not so strict and authorized such behaviors. MySQL 5.7 is less permissive, which leads to a problem to calculate the _required_count_ and the _ratio_.
The first commit fixes the problem. This fix is gracefully provided by your beloved CTO.
The second commit adds Behat on …

PIM-5963: be able to install PIM on MySQL 5.7

---

CHANGELOG-1.6.md
src/Pim/Bundle/EnrichBundle/Resources/public/js/export/product/edit/content/structure/attributes.js

Enable tooltip for field "attributes"

PIM-5958: In the tab "Content" of an export profile, the tooltip for the field "attributes" does not appear on mouse over

---

src/Pim/Bundle/UIBundle/Resources/public/css/less/oro.less

This PR fixes a regression between 1.5 and 1.6 on flash messages display.
Before the PR:
After:

Fix glitch on flash messages

---

src/Akeneo/Bundle/StorageUtilsBundle/spec/Doctrine/SmartManagerRegistrySpec.php

add SkipException is useless as there is already `@require Doctrine\ODM\MongoDB\MongoDBException` on spec.
Add SkipException make this build red however all specs are ok
http://core-ci.akeneo.com/view/PIM%20-%201.6/job/pim-community-dev-1-6-spec/572/console

Remove useless test as there is already @require on spec

---

build.xml

Remove useless `require-mongo` as this dependency is already in our composer.json.

Remove require-mongo as this dependency is already in composer.json

---

CHANGELOG-1.6.md
features/export/product-export-builder/export_products_by_categories.feature
src/Pim/Bundle/EnrichBundle/Resources/public/js/filter/product/category/selector.js
src/Pim/Component/Catalog/Normalizer/Structured/ChannelNormalizer.php
src/Pim/Component/Catalog/spec/Normalizer/Structured/ChannelNormalizerSpec.php

Channel normalization before the PR:
```
[
"code" => "ecommerce",
"label" => "Ecommerce",
"currencies" => [...],
"locales" => [...],
"category" => [
"id" => 1,
"code" => "master",
"labels" => [
["locale" => "en_US", "label" => "Master catalog"],
["locale" => "de_DE", "label" => "Hauptkatalog"],
["locale" => "fr_FR", "label" => "Catalogue principal"]
]
],
"conversion_units" => ""
]
```
and after:
```
[
"code" => "ecommerce",
"label" => "Ecommerce",
"currencies" => [...],
"locales" => [...],
"category" => [
"id" => 1,
"code" => "master",
"labels" => [
"en_US" => "Master catalog",
"de_DE" => "Hauptkatalog",
"fr_FR" => "Catalogue principal"
]
],
"conversion_units" => ""
]
```
This change allows to use the …

PIM-5964: Index category labels by locale code in channel normalization

---

CHANGELOG-1.6.md
features/attribute/option/import_attribute_options.feature
src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/AttributeOptionRepository.php

This little PR fixes the fact than when you import attribute_options without any labels, the value is set to "null", and no label is displayed at all.
*DISCLAIMER*
This is not the best fix. The good solution is to split the AjaxOptionController and to drop all but the SearchableRepositoryInterface to be able to use Normalizers for each options. @momoss begins to create a new one in 1.5, but we can not split all the AjaxOptionController.
The next step of this PR is to make a rework of this in "master" to avoid any BC break. …

PIM-5968: Fix back translation for attribute options when value is null

---

composer.json
features/Context/WebApiContext.php

I broke the PIM ( :kissing_heart: ) when I upgraded phpunit, the obsolete package "behat/common-contexts" is not compatible with our new version. I remove it and add usefull methods in `features/Context/WebApiContext`.

Remove obsolete "behat/common-contexts"

---

CHANGELOG-1.6.md
features/versioning/ensure_versioning_on_family.feature
src/Pim/Bundle/DataGridBundle/Resources/config/requirejs.yml
src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid-builder.js
src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid/cell/integer-cell.js

Before this fix, the version numbers were displayed as decimals. This PR fixes this bug.

PIM-5566: fix decimals in history grid

---

CHANGELOG-1.6.md
features/product-group/add_products.feature
features/product-group/remove_products.feature
src/Pim/Bundle/EnrichBundle/Form/DataTransformer/EntityToIdentifierTransformer.php
src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/product_group.yml

Fixed with this PR : Regression since 1.6, products cannot be added to groups anymore via Enrich < Group

PIM-5976: fix group products saving regression

---

src/Pim/Bundle/DataGridBundle/Twig/FilterExtension.php
src/Pim/Bundle/DataGridBundle/spec/Twig/FilterExtensionSpec.php

Test of cherry pick from https://github.com/akeneo/pim-community-dev/pull/5027 because the PR has been opened from master then changed to 1.6 but travisci show a weird diff not visible from github UI.

Cherry pick issue4494

---

src/Pim/Bundle/EnrichBundle/Resources/public/js/grid/view-selector-footer.js
src/Pim/Bundle/EnrichBundle/Resources/public/templates/grid/view-selector-footer.html

This PR make the view selector footer extensible by adding a data drop zone in template and rendering extensions.
| Added Specs                       | no need
| Added Behats                      | no need
| Changelog updated                 | no need
| Micro Demo to the PO (Story only) | no functional update

AMS-3: Make view selector footer extensible

---

src/Akeneo/Bundle/MeasureBundle/Resources/config/measure.yml

See #5062
Fixed typo for `CENTICOULOMB` and fixed ElectricCharge conversions
Fixed typo on CENTICOULOMB unit

Fixed unit conversion for ElectricCharge + typo in MeasureBundle

---

CHANGELOG-1.6.md
features/enrich/variant-group/edit_variant_browse_products.feature
src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/ProductRepository.php

In Mysql storage only, when a product is in a group (not a variant group), this one is not visible anymore in the variant group edit form,
even if the product has the axis (and, therefore, is eligible to the variant group).
When you take off the product from the group, this one is visible in  the variant group edit form.
The SQL request to know the eligible products was wrong.
| Review and 2 GTM                  | n …

PIM-5977: Fix missing products in the variant group edit form

---

.travis.yml
CHANGELOG-1.5.md
src/Pim/Bundle/CatalogBundle/Manager/AttributeValuesResolver.php
travis.php.ini

Optimization requested by a customer
When importing products, the import job fetch all attributes and iterate on each of them. The problem is there is an array_merge method in this foreach loop and it's very time consuming when there are plenty of attributes in the database.
As an example, with 14000 attributes, the loop takes about 10 minutes, and only 8 second with the optimization.
| Added Specs                       | Covered by existing one
| Added Behats                      | Covered by existing ones

Pim 5984: Optimization on product import when iterating on each existing attributes

---

CHANGELOG-1.5.md
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/associations.js

**Bug description :** 
- Go to the association tab in the PEF (for any product)
- Go to the association type page
- Add an association type
- Return to the association tab in the PEF (for any product)
- Try to associate a product to another one with the new association added juste before and save it : it fails
**Why this bug occurs :** 
When you open the association tab in the PEF, a javascript instance of the association type form is loaded.
This instance is bind to the mediator in order to listen when you check/uncheck checkboxes to associate a product to another one. This instance has a model, and this model contains association types.
Then, if you add a new association type, and you return to the association type PEF, you will not …

PIM-5973: Fix association between products with new association types

---

.travis.yml
src/Pim/Bundle/EnrichBundle/Resources/config/bundles/akeneo_batch.yml
travis.php.ini

The Akeneo batch from the EnrichBundle is configured to send mail pretending to be from akeneo.com mail servers. This is a bad idea from a security point of view. 
| Added Specs                       | no

 batch EnrichBundle edit sender e-mail address

---

CHANGELOG-1.6.md
features/Context/CommandContext.php
features/export/execute_an_export.feature
src/Akeneo/Bundle/BatchBundle/Command/BatchCommand.php

Fix for an issue with exports in command line mode.
The job instance parameters were lost if the user use a custom config.
As an example, if an user run an export with a custom file path like this :
app/console akeneo:batch:job csv_product_export -c "{\"filePath\": \"/custom/path/products.csv\"}"
The other job instance parameters are ignored, including the tree to export, so that the generated file is empty.
I solve that with a simple array_merge between default job parameters and user provided parameters.
| Changelog updated                 |  Y
| …

Pim 5982: Missing job instance parameters when using custom configuration in command line

---

CHANGELOG-1.6.md
features/Context/DataGridContext.php
features/Context/Page/Base/Grid.php
features/datagrid/display_many_datagrid_filters.feature
src/Pim/Bundle/DataGridBundle/Resources/public/lib/multiselect/jquery.multiselect.filter.js

On the product grid, it is not possible to search for an attribute's code.
For a complete explanation please see : https://akeneo.atlassian.net/browse/PIM-5536
Solution : The problem is due to `jquery.multiselect.js` which only autocomplete on the `innerHTML` (the attribute's label) and not the `value` attribute of the `<option>` tag (the attribute's code). As a quick fix, we decided with @nidup to fix the library to allow autocomplete on both `innerHTML` and `value` attribute. This has no side effect. A better approach would be to replace multiselect plugin by select2 but the refactoring is huge.
Here is an example with an attribue which code is "Attribute" and label is "Nom" :
| …

PIM-5536: Inconsistency on search fields

---

features/Context/CommandContext.php
features/Pim/Behat/Context/PimContext.php

Fix for CI :  Launch symfony commands via console absolute path.

CI fix: absolute path for symfony console

---

CHANGELOG-1.6.md
composer.json

We introduced "league/flysystem-sftp" in v1.4 and we don't even use it, the namespace is not use either in CE and EE, I dropped it here and run the full CI without encountering any issue on master https://github.com/akeneo/pim-community-dev/pull/5136.
The real issue behing this is the following one #5129 concerning the v1.6 where we would need to bump or remove this dep.
Changing our composer.json in an already released version is a very very very sensitive topic, even for bumping to the last patch in this case, it's doable because we don't use this lib into our own code, the only impact is to properly add it in project when using it for real.
| Added Behats …

Remove useless "league/flysystem-sftp" dependency to fix #5129

---

CHANGELOG-1.5.md
features/product/edit_product_with_attribute_options.feature
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/field/multi-select-field.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/field/simple-select-field.js

Multiselect & Simpleselect **didn't send the locale they were searching on** to the controller.
So now they send the locale, because if you don't, the controller grabs ALL the labels translations with a LIMIT 20, it does this:
Now that we filter by locale, we only have 20 attribute options.

PIM-5993: Fix value display issues with simple/multi select attributes

---

features/Context/DataGridContext.php
features/Pim/Behat/Decorator/Page/GridCapableDecorator.php
features/datagrid/datagrid_views.feature
src/Pim/Bundle/DataGridBundle/Resources/translations/jsmessages.en.yml
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/grid_view_selector.yml
src/Pim/Bundle/EnrichBundle/Resources/config/requirejs.yml
src/Pim/Bundle/EnrichBundle/Resources/public/js/grid/view-selector-footer-create-view.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/grid/view-selector-footer-create.js
src/Pim/Bundle/EnrichBundle/Resources/public/templates/grid/view-selector-footer-create-view.html
src/Pim/Bundle/EnrichBundle/Resources/public/templates/grid/view-selector-footer-create.html
src/Pim/Bundle/UIBundle/Resources/public/css/pim.less
src/Pim/Bundle/UIBundle/Resources/public/css/select2.less

Now the create button is render as a single button if there is only one extension. If there is more than one extension, it is a dropdown with the list of possible actions.
| Added Specs                       | no

AMS-10: Make the create button from view selector extensible

---

src/Pim/Component/Connector/Writer/File/Csv/ProductWriter.php
src/Pim/Component/Connector/Writer/File/Xlsx/ProductWriter.php
src/Pim/Component/Connector/spec/Writer/File/Csv/ProductWriterSpec.php
src/Pim/Component/Connector/spec/Writer/File/Xlsx/ProductWriterSpec.php

use the key "identifier" in the product standard format introduced in a previous PR

TIP-477: call key "identifier" from the product standard format

---

src/Pim/Component/Catalog/Updater/ChannelUpdater.php
src/Pim/Component/Catalog/Updater/CurrencyUpdater.php
src/Pim/Component/Catalog/Updater/FamilyUpdater.php
src/Pim/Component/Catalog/Updater/VariantGroupUpdater.php
src/Pim/Component/Catalog/spec/Updater/ChannelUpdaterSpec.php
src/Pim/Component/Catalog/spec/Updater/CurrencyUpdaterSpec.php
src/Pim/Component/Catalog/spec/Updater/FamilyUpdaterSpec.php
src/Pim/Component/Catalog/spec/Updater/VariantGroupUpdaterSpec.php
src/Pim/Component/Connector/ArrayConverter/FlatToStandard/Category.php
src/Pim/Component/Connector/ArrayConverter/FlatToStandard/Channel.php
src/Pim/Component/Connector/ArrayConverter/FlatToStandard/Currency.php
src/Pim/Component/Connector/ArrayConverter/FlatToStandard/Family.php
src/Pim/Component/Connector/ArrayConverter/FlatToStandard/Locale.php
src/Pim/Component/Connector/ArrayConverter/FlatToStandard/VariantGroup.php
src/Pim/Component/Connector/spec/ArrayConverter/FlatToStandard/ChannelSpec.php
src/Pim/Component/Connector/spec/ArrayConverter/FlatToStandard/CurrencySpec.php
src/Pim/Component/Connector/spec/ArrayConverter/FlatToStandard/VariantGroupSpec.php

Last PR about the standard format in imports (a previous PR has been [done](https://github.com/akeneo/pim-community-dev/pull/5096) about the standard format but mainly for products) 

TIP-496: Use the standard format in imports

---

CHANGELOG-1.5.md
features/enrich/variant-group/edit_attributes_of_a_variant_group.feature
features/enrich/variant-group/edit_variant_group_attribute_value.feature
features/import/product_variant_group/import_variant_group_with_scopable_or_localizable_data.feature
spec/Pim/Component/Catalog/Builder/LocalizableAndScopableRawValuesBuilderSpec.php
src/Pim/Bundle/CatalogBundle/Resources/config/builders.yml
src/Pim/Bundle/EnrichBundle/Form/Subscriber/TransformProductTemplateValuesSubscriber.php
src/Pim/Bundle/EnrichBundle/Resources/config/form_subscribers.yml
src/Pim/Component/Catalog/Builder/LocalizableAndScopableRawValuesBuilder.php
src/Pim/Component/Catalog/Updater/VariantGroupUpdater.php

This fixes a bug that is present only in 1.5 (and not in 1.6 or master). 
Currently on 1.5, when you have the following variant group CSV import file:
```
code;type;label-en_US;axis;description-en_US-tablet
SANDAL;VARIANT;Sandal;color,size;"new description tablet"
```
Only the value `description-en_US-tablet` will be created in database. In 1.6, no problem, the frontend correctly handles localizable and scopable values (it creates missing values by himself). That's not the case in 1.5. The edit form of the variant group `SANDAL` is totally broken.
This fix creates, **before the form is rendered**, all missing localizable and/or scopable values that are needed for the edit form to work correctly.  
This fixes does several bad things:
- there is a BC break in order to work
- it fetches all …

[SLA] PIM-5995: Fix issue with localizable and scopable attributes added to variant groups

---

CHANGELOG-1.5.md
features/enrich/variant-group/add_products.feature
features/enrich/variant-group/edit_attributes_of_a_variant_group.feature
spec/Pim/Bundle/EnrichBundle/Form/Handler/GroupHandlerSpec.php
src/Pim/Bundle/EnrichBundle/Form/Handler/GroupHandler.php
src/Pim/Bundle/EnrichBundle/Resources/config/handlers.yml

Bug: the product count is not updated after group save (work after refresh).
By refreshing the group after persist the product count is updated.

PIM-5995: fix product count on update for variant groups

---

CHANGELOG-1.5.md
src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/ProductRepository.php

* detected by a customer that has 60K products, 10M values in ORM
* this bug only occurs in ORM
When using the method `execute()` of the product query builder, a `Akeneo\Component\StorageUtils\Cursor\CursorInterface` is created is created. Each time a new page of the cursor is loaded, the method `findByIds` of the `ProductRepository` is called.
Doctrine internally caches all DQL queries. Imagine we call the method `findByIds` 3 times, with the following paramteters:
1. `[1,2,3]`
2. `[8,9]`
3. `[11,22,33,44]`
Before this fix, Doctrine would have cache the following DQLs:
1. `SELECT p FROM Product p WHERE p.id IN (1)` #(1) represents [1,2,3]
2. `SELECT p FROM Product p WHERE p.id IN (2)` #(2) represents [8,9]
3. `SELECT p FROM Product p WHERE p.id IN (3)` #(3) represents [11,22,33,44]
It …

[SLA] PIM-6006: fix small memory leak when iterating over products cursor

---

CHANGELOG-1.5.md
src/Pim/Bundle/CatalogBundle/Resources/config/storage_driver/doctrine/orm.yml

* detected by a customer that has 60K products, 10M values in ORM
* this bug only occurs in ORM
Currently we fetches products 1000 by 1000 via [the cursor](https://github.com/akeneo/pim-community-dev/blob/1.5/src/Pim/Bundle/CatalogBundle/Resources/config/storage_driver/doctrine/orm.yml#L28). The cursor is internally used by the Product Query Builder.
When you have, let's say 200 values per product, that means you directly load 200 000 objects in memory. This leads to 2 problems: 
* it represents a big amount of memory (~750MB see below)
* the table of the garbage collector, which only has [10 000 entries](https://www.sitepoint.com/better-understanding-phps-garbage-collection/), is full (remember @BitOne's presentations :) )
The more a PHP process uses the memory, the less it's fast. We …

[SLA] Boost product export performances by loading less products at the same time

---

CHANGELOG-1.5.md
features/import/product_variant_group/import_variant_group_having_products.feature
src/Pim/Component/Connector/Writer/Doctrine/VariantGroupWriter.php

When you import a variant group having associated products, it raises this issue:
VARIANT GROUP IMPORT A new entity was found through the relationship 'Pim\Component\Catalog\Model\Product#groups' that was not configured to cascade persist operations for entity: [oro_mug]. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this association in the mapping for example @ManyToOne(..,cascade={"persist"}).
The issue is that there is some detach in the "copyValuesToProducts" method (this method updates the products with new values of Variant Groups).
To fix it, we use the same order than the GroupWriter:
https://github.com/akeneo/pim-community-dev/blob/master/src/Pim/Bundle/CatalogBundle/Doctrine/Common/Saver/GroupSaver.php#L121 …

PIM-5990: Fix persist order

---

CHANGELOG-1.5.md
features/product/edit_product_with_localizable_and_scopable_attribute_options.feature
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/field/simple-select-field.js

Apply a fix of @ahocquard 
This fix can not be cherry-picked because it was done during a merge.
The issue:
When you have localizable and scopable attribute with attribute options, then you:
- save an attribute option
- set an attribute option for another scope
- swith scope then go back to the first one
- the value disappears !

[PIM-5989] Fix attribute options on localizable and scopable attribute simple select

---

CHANGELOG-1.5.md
features/attribute/option/sort_attribute_options.feature
features/enrich/variant-group/edit_variant_group_attribute_value.feature
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/field/multi-select-field.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/field/simple-select-field.js

With locale specific attributes and if you use a variant group there we a problem with the select and multi select fields.
In this PR we fix the cache management in simple/multiselect fields.

PIM-6013: fix simple and multi select cache

---

CHANGELOG-1.5.md
features/attribute/option/edit_attribute_options_02.feature
features/enrich/variant-group/edit_variant_group_attribute_value.feature
src/Pim/Bundle/EnrichBundle/Resources/public/js/pim-attributeoptionview.js

The usage of quotes in attribute options truncated the rest of the value when editing.
CI -> https://core-ci.akeneo.com/view/All/job/dci_behat/7397/

PIM-6002: Fix characters escapment with usage of quote in attribute option

---

CHANGELOG-1.5.md
features/user/create_edit_and_delete_role.feature
src/Oro/Bundle/UserBundle/Resources/config/validation.yml

The code generated from the label must be less than 30 characters (Generated from the label mean all in caps and '_' instead of spaces and add ROLE_ at the beginning of the label so 5 chars more than the label)
CI -> https://core-ci.akeneo.com/view/All/job/dci_behat/7407/

PIM-5997: Restrict to 25 characters the role label

---

.travis.yml

If xdebug is not activated for a PHP version, disabling xdebug should not crash the build.
As a bonus, we don't have to check for specific PHP versions and the build will not take 10 minutes! ;)

Travis CI: disable Xdebug does not crash Travis

---

CHANGELOG-1.5.md
features/Context/DataGridContext.php
features/Context/Page/Base/Grid.php
features/Context/Page/Element/ConfigurationPopin.php
features/Context/Spin/SpinCapableTrait.php
features/datagrid/datagrid_views.feature
features/enrich/variant-group/edit_variant_group_attribute_value.feature
features/localization/product/datagrid/display_localized_dates.feature
features/localization/product/datagrid/display_localized_numbers.feature
features/product/browse_products_by_locale_and_scope.feature
features/product/choose_and_order_products_grid_columns.feature
features/product/date.feature
features/product/display_attributes_in_the_grid.feature
features/product/edit_product_and_action.feature
features/product/filtering/filter_products_per_text_fields.feature
features/product/sorting/sort_products_per_attribute.feature
features/reference-data/product/display_reference_data_in_the_grid.feature
features/reference-data/product/sorting/sort_products_per_reference_data.feature
src/Pim/Bundle/DataGridBundle/Repository/DatagridViewRepositoryInterface.php
src/Pim/Bundle/DataGridBundle/Resources/views/Datagrid/_views.html.twig

This PR:
- Reverts https://github.com/akeneo/pim-community-dev/pull/4948 because it caused a regression (PIM-6007)
- Provides a fix for the original bug without regression (hopefully)
- Really tests the grid columns selectors popin (because it wasn't the case, nope)
- Adds behats stabilization and fix some incoherent ones
- Fixes the spin method behaviour
| Added Specs                       | n/a
| Micro Demo to the PO (Story only) | n/a

PIM-5862: Fix product grid display on a custom user view

---

CHANGELOG-1.4.md
features/Context/FixturesContext.php
features/Context/WebUser.php
features/mass-action/edit_common_attributes.feature
src/Pim/Bundle/EnrichBundle/MassEditAction/Operation/EditCommonAttributes.php

PIM-6008: Fix mass edit execution when using specials chars in text field edition
…ield edition

PIM-6008: Fix mass edit execution when using specials chars in text field edition

---

features/Context/Page/Base/Grid.php
features/attribute/browse/view.feature
features/enrich/variant-group/add_attributes_to_a_variant_group.feature
src/Pim/Bundle/DataGridBundle/Datagrid/Configuration/Product/ContextConfigurator.php

In the variant group product grid there is a `th` without any class and with an `input` inside it, it shouldn't be selected because it breaks the columns count.
Also, this PR fixes the display of axis columns in the EE products grid of the variant group. I guess it was broken since https://github.com/akeneo/pim-community-dev/pull/3619 and never spotted due to the false positives in EE.

Fix column headers selection in behat

---

CHANGELOG-1.6.md
features/export/product-export-builder/export_products_by_categories.feature
src/Pim/Bundle/EnrichBundle/Resources/public/js/filter/product/category/selector.js

When you export products with filter on categories and some of these categories have an integer as code, you can't save your export.
This PR fixes this problem by parsing category code in String.
| Added Specs                       | :no_entry_sign: 
| Added Behats                      | ☑️  
| Changelog updated                 | ☑️ 
| Review and 2 GTM                  | ☑️ 
| Migration script                  | :no_entry_sign: 
| Tech Doc                          | :no_entry_sign:

PIM-6027: Fix category filter for export builder

---

src/Akeneo/Bundle/MeasureBundle/Resources/config/measure.yml

The standard unit for energy is the Joule, not the kilo-calorie

Standard unit for energy

---

CHANGELOG-1.6.md
features/import/attribute/import_identifier.feature
src/Pim/Bundle/CatalogBundle/Resources/config/validation/attribute.yml
src/Pim/Component/Catalog/Validator/Constraints/IsIdentifierUsableAsGridFilter.php
src/Pim/Component/Catalog/Validator/Constraints/IsIdentifierUsableAsGridFilterValidator.php
src/Pim/Component/Catalog/spec/Validator/Constraints/IsIdentifierUsableAsGridFilterSpec.php
src/Pim/Component/Catalog/spec/Validator/Constraints/IsIdentifierUsableAsGridFilterValidatorSpec.php

If a user import an identifier attribute with "useable_as_grid_filter" set to 0, the import works fine but the corresponding filter isn't available anymore on the product grid.
This fix adds a validation on attribute that prevents an identifier to be not usable as grid filter.
| Added Specs                       | 🔲 
| Added Behats                      | ☑️ 
| Changelog updated                 | ☑️ 
| Review and 2 GTM                  | 🔲 
| Migration script                  | 🚫 
| Tech Doc                          | 🚫

PIM-6018: Import identifier attribute only if usable as grid filter

---

CHANGELOG-1.5.md
features/Context/DataGridContext.php
features/Context/FixturesContext.php
features/Context/catalog/default/jobs.yml
features/family/mass_edit_families.feature
src/Pim/Bundle/EnrichBundle/Connector/Reader/MassEdit/FilteredFamilyReader.php
src/Pim/Bundle/EnrichBundle/Resources/config/batch_jobs.yml

When mass editing more than 100 families (default size of the batches in our batch jobs), following error occurs:
```
A new entity was found through the relationship 'Pim\Bundle\CatalogBundle\Entity\Family#attributeAsLabel' that was not
configured to cascade persist operations for entity: [libelle_article]. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this association in the mapping for example @ManyToOne(..,cascade={"persist"}).
```
This is caused by our old CacheClearer that do not detach objects properly. This PR fix this bug by replacing, in the family mass edit job definition, the old `Pim\Bundle\BaseConnectorBundle\Writer\Doctrine\Writer` (that use this …

PIM-6026: Use doctrine base writer for family mass edit

---

CHANGELOG-1.5.md
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/field/textarea-field.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/field/wysiwyg-field.js

Create a textarea attribute and enable wysiwyg mode. 
Add the attribute to a family and mark it as required for completeness. 
Edit a product of the family. 
Open the completeness tab. 
Click on the link corresponding to the empty wysiwyg field. 
Add the focus into the concerned field
| Added Specs …

PIM-5991: Add the focus into wysiwig field

---

Jenkinsfile

Our current test matrix for Akeneo 1.6 is PHP 5.6, 7.0 and 7.1 for static analysis. This PR updates the Jenkinsfile to follow the same test matrix, and not the one of the previous Akeneo versions (PHP 5.4 to 5.6).

Update Jenkinsfile test matrix

---

src/Pim/Bundle/CatalogBundle/Filter/ChainedFilter.php

On a product page, when the user does not have access to the first locale in the locale switcher, the product information cannot load, and a JavaScript error appear in the browser console: 
`Error: locale-switcher.js:28 Uncaught TypeError: Cannot read property 'code' of undefined Pim/Bundle/EnrichBundle/Resources/public/js/product/form/locale-switcher.js line 28`
This PR fixes the problem by resetting the indexes of the array containing the filtered locales.
As this bug can only occur in Enterprise Edition, functional testing is performed in `pim-enterprise-dev` repository.
**Definition Of Done)**
| Added Behats …

PIM-6035: Fix an issue with locale switcher

---

Jenkinsfile

Allow to run behat tests with PHP 5.6, 7.0, 7.1 and MySQL 5.5 and 5.7
| Added Behats                      |:negative_squared_cross_mark:
| Migration script                  |:negative_squared_cross_mark:

Add PHP and MySQL options for behat builds

---

CHANGELOG-1.5.md
features/Context/DataGridContext.php
features/import/product/import_products_with_associations.feature
spec/Pim/Component/Connector/Processor/Denormalization/ProductAssociationProcessorSpec.php
src/Pim/Bundle/ConnectorBundle/Resources/translations/messages.en.yml
src/Pim/Bundle/InstallerBundle/Resources/config/fixtures_jobs.yml
src/Pim/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev/jobs.yml
src/Pim/Component/Connector/Processor/Denormalization/ProductAssociationProcessor.php

PIM-6019: Successfully import products without removing already existing associations when option "compare values" is disabled

---

CHANGELOG-1.6.md
features/channel/edit_channel.feature
src/Pim/Bundle/EnrichBundle/EventListener/Storage/ChannelLocaleSubscriber.php
src/Pim/Bundle/EnrichBundle/spec/EventListener/Storage/ChannelLocaleSubscriberSpec.php

When having only one channel, if you remove all the locales from the channel, and add a new one, then you end with a critical error:
```
request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ContextErrorException: "Catchable Fatal Error: Argument 1 passed to Pim\Bundle\UserBundle\Entity\User::setCatalogLocale() must implement interface Pim\Component\Catalog\Model\LocaleInterface, boolean given, called in /home/docker/pim/src/Pim/Bundle/UserBundle/EventSubscriber/UserPreferencesSubscriber.php on line 220 and defined" at /home/docker/pim/src/Pim/Bundle/UserBundle/Entity/User.php line 908 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ContextErrorException(code: 0): Catchable Fatal Error: Argument 1 passed to …
```

PIM-6025: Allow changing locales on unique channel

---

CHANGELOG-1.6.md
features/family/delete_family.feature
src/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/QueryGenerator/FamilyDeletedQueryGenerator.php
src/Pim/Bundle/CatalogBundle/Resources/config/storage_driver/doctrine/mongodb-odm.yml
src/Pim/Bundle/CatalogBundle/spec/Doctrine/MongoDBODM/QueryGenerator/FamilyDeletedQueryGeneratorSpec.php

As the family is stored directly on the product in mongoDb, we have to delete it when the family itself is deleted :) …

PIM-6031: Deleted families are still visible on the product grid

---

CHANGELOG-1.6.md
features/Context/Page/Attribute/Creation.php
features/Context/WebUser.php
features/attribute/option/create_attribute_options.feature
src/Pim/Bundle/EnrichBundle/Resources/public/js/pim-attributeoptionview.js

| Added Specs                       |  :negative_squared_cross_mark:
| Micro Demo to the PO (Story only) | :clock1: …

PIM-6033: Fix validation issue when you add an empty attribute option

---

CHANGELOG-1.7.md
src/Pim/Bundle/ImportExportBundle/ViewElement/Checker/JobNameVisibilityChecker.php

Check additional job_names supplied in the $config parameter of the job name visibility checker
| Q | A |
| --- | --- |
| Added Specs | no |
| Added Behats | no |
| Changelog updated | yes |
| Review and 2 GTM | no |
| Micro Demo to the PO (Story only) | no |
| Migration script | no |
|  Tech Doc | no |
Right now, additional job names supplied by $config are ignored. For instance, when adding a visibility checker to a custom job, the supplied job name will appear here in the $config variable. So also check that variable, together with the jobNames instance variable.

Bugfix: fix job name visibility checker to also check additional config

---

CHANGELOG-1.7.md
src/Pim/Component/Connector/ArrayConverter/FlatToStandard/Product.php

Removes unused WITH_REQUIRED_IDENTIFIER option from the flatToStandard converter because this option does not exists anymore in the job parameters option (for instance see https://github.com/akeneo/pim-community-dev/blob/5a5b1cb28288d9ab067c22f4dcb5f1c087d5fbd2/src/Pim/Component/Connector/Job/JobParameters/DefaultValuesProvider/ProductCsvImport.php#L37-L37).
It is neither used in EE.
The Identifier is definitely required for a job import. so we dropped the option from the converter inner workings. …

TIP-662: Remove unused WITH_REQUIRED_IDENTIFIER product import option

---

composer.json
src/Pim/Bundle/EnrichBundle/Resources/config/bundles/fos_rest.yml

- Upgrade bundle
- Remove unsupported xml format for the API
(Initially, we wanted to remove this bundle as we thought it was useless. But it's still used for the oro navigation and quite usefull to call exceptions in the good format depending on the URI) …

API-57: upgrade FOSRestBundle

---

CHANGELOG-1.5.md
spec/Pim/Bundle/EnrichBundle/Connector/Processor/MassEdit/Family/SetAttributeRequirementsSpec.php
src/Pim/Bundle/EnrichBundle/Connector/Processor/MassEdit/Family/SetAttributeRequirements.php
src/Pim/Bundle/EnrichBundle/Resources/config/connector/processors.yml
src/Pim/Bundle/EnrichBundle/Resources/translations/messages.en.yml

This PR calls the validation during family mass action! Today families are saved in DB without being validated. …

Call validation on family mass edit

---

CHANGELOG-1.7.md
src/Pim/Bundle/CatalogBundle/Resources/config/builders.yml
src/Pim/Bundle/CatalogBundle/Resources/config/factories.yml
src/Pim/Bundle/CatalogBundle/Resources/config/serializers.yml
src/Pim/Bundle/VersioningBundle/Denormalizer/Flat/ProductValue/PricesDenormalizer.php
src/Pim/Bundle/VersioningBundle/spec/Denormalizer/Flat/ProductValue/PricesDenormalizerSpec.php
src/Pim/Component/Catalog/Builder/ProductBuilder.php
src/Pim/Component/Catalog/Builder/ProductBuilderInterface.php
src/Pim/Component/Catalog/Denormalizer/Standard/ProductValueDenormalizer.php
src/Pim/Component/Catalog/Factory/ProductValueFactory.php
src/Pim/Component/Catalog/spec/Builder/ProductBuilderSpec.php
src/Pim/Component/Catalog/spec/Denormalizer/Standard/ProductValueDenormalizerSpec.php
src/Pim/Component/Catalog/spec/Factory/ProductValueFactorySpec.php

This PR introduces a ProductValue factory which responsibility is to solely create product values.
~This factory checks for the attribute localizable, scopable properties as well as if the locale we want the product value to be created is activated or if the scope exists.~
This factory relies on the AttributeValidatorHelper in order to check if the product value can be created within the scope and locale requested.
This simplifies our codebase as those checks were made in different layers.
This factory is being injected everywhere product values were created with new ProductValue() (eg, the ProductBuilder). …

TIP-667: Adds ProductValueFactory and replace hardcoded productValue instanciations

---

CHANGELOG-1.7.md
src/Oro/Bundle/UserBundle/Entity/Repository/GroupRepository.php
src/Oro/Bundle/UserBundle/Form/Handler/GroupHandler.php
src/Pim/Bundle/UserBundle/Entity/User.php
src/Pim/Bundle/UserBundle/Entity/UserInterface.php
src/Pim/Bundle/UserBundle/EventSubscriber/GroupSubscriber.php
src/Pim/Component/User/Updater/GroupUpdater.php
src/Pim/Component/User/Updater/UserUpdater.php

Most of our business code (components) depends on Oro/UserBundle because using the user Group entity, an interface has been introduced by @aRn0D this PR uses this interface and not the concret entity allowing to decouple all our code from Oro/UserBundle and prepare / allow a future rewriting of this part. …

Use User GroupInterface and not Group entity (decoupling)

---

CHANGELOG-1.6.md
features/export/export_channels.feature
features/import/import_channels.feature
src/Pim/Component/Catalog/Normalizer/Structured/ChannelNormalizer.php
src/Pim/Component/Catalog/spec/Normalizer/Structured/ChannelNormalizerSpec.php
src/Pim/Component/Connector/ArrayConverter/FlatToStandard/Channel.php
src/Pim/Component/Connector/spec/ArrayConverter/FlatToStandard/ChannelSpec.php

| Micro Demo to the PO (Story only) | In progress
About the import issue, here is what we have when creating a channel from fixtures for example:
```
mysql> select * from pim_catalog_channel;
+----+-------------+-----------+-----------+-----------------+
| id | category_id | code      | label     | conversionUnits | …
```

PIM-6041 and PIM-6047: Fixed Channel normalizer

---

src/Pim/Bundle/DataGridBundle/Controller/Rest/DatagridViewController.php
src/Pim/Bundle/DataGridBundle/Resources/config/updaters.yml
src/Pim/Bundle/DataGridBundle/Updater/DatagridViewUpdater.php
src/Pim/Bundle/DataGridBundle/spec/Updater/DatagridViewUpdaterSpec.php

`DatagridViewUpdater` can update the datagrid's owner with its username or an user object. 
Related to https://github.com/akeneo/pim-enterprise-dev/pull/2356
| Added Behats                      | :negative_squared_cross_mark: 
| Micro Demo to the PO (Story only) | :negative_squared_cross_mark: 
| Migration script                  | :negative_squared_cross_mark: 
| Tech Doc                          | :negative_squared_cross_mark:  …

[AMS-116]Update datagrid creator with username

---

src/Akeneo/Component/Localization/spec/Localizer/DateLocalizerSpec.php
src/Pim/Component/Catalog/spec/Normalizer/Standard/DateTimeNormalizerSpec.php
src/Pim/Component/Connector/spec/ArrayConverter/FlatToStandard/AttributeSpec.php

Some tests fails if `date.timezone` parameter is not `Europe/Paris`. Makes specs related to datetime independent of developers timezone.
See #5450 …

GITHUB-5450: Make specs independent of developers timezone

---

CHANGELOG-1.7.md
src/Pim/Bundle/EnrichBundle/Resources/config/form_types.yml

#5048 
Remove useless ```pim_enrich_image``` form type service, remove parameter of nonexistent ```Form\Type\ImageType``` class. …

GITHUB-5048: Remove useless pim_enrich_image service

---

CHANGELOG-1.7.md
features/Context/NavigationContext.php
features/Context/Page/AssociationType/Edit.php
features/association-type/create_association_type.feature
features/association-type/display_association_type_history.feature
features/association-type/edit_association_type.feature
src/Pim/Bundle/EnrichBundle/Controller/AssociationTypeController.php
src/Pim/Bundle/EnrichBundle/Controller/Rest/AssociationTypeController.php
src/Pim/Bundle/EnrichBundle/Normalizer/AssociationTypeNormalizer.php
src/Pim/Bundle/EnrichBundle/Resources/config/controllers.yml
src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/association_type.yml
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/association_type.yml
src/Pim/Bundle/EnrichBundle/Resources/config/normalizers.yml
src/Pim/Bundle/EnrichBundle/Resources/config/requirejs.yml
src/Pim/Bundle/EnrichBundle/Resources/config/routing/associationtype.yml
src/Pim/Bundle/EnrichBundle/Resources/public/js/association-type/form/delete.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/association-type/form/properties/general.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/association-type/form/save.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/properties/translation.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/remover/association-type-remover.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/saver/association-type-saver.js
src/Pim/Bundle/EnrichBundle/Resources/public/templates/association-type/tab/properties/general.html
src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml
src/Pim/Bundle/EnrichBundle/Resources/views/AssociationType/edit.html.twig
src/Pim/Bundle/EnrichBundle/spec/Form/Type/AssociationTypeTypeSpec.php
src/Pim/Bundle/EnrichBundle/spec/Normalizer/AssociationTypeNormalizerSpec.php

See #5391 
- upgrade AssociationType controller
- upgrade AssociationType rest controller
- create association type form extensions
- update requirejs.yml
- implement association type edit form js module and html template
- implement association type save form and saver js modules
- implement association type delete form and remover js modules
- upgrade association type normalizer
- update specs
- update translations
- update behats
- fix translations form event bug
- review fixes
[//]: <> (What does this …

GITHUB-5391: redo association type form

---

.travis.yml
app/phpunit.travis.xml
src/Pim/Bundle/VersioningBundle/Normalizer/Flat/ProductValueNormalizer.php
src/Pim/Bundle/VersioningBundle/tests/integration/Normalizer/Flat/ProductIntegration.php
src/Pim/Component/Catalog/tests/integration/Normalizer/Standard/AttributeOptionIntegration.php
tests/TestCase.php
tests/catalog/technical/attribute_options.csv

This PR allows to run the integration tests into Travis:
The PIM is now fully installed in Travis. That means:
- install APCu (because it's required by Symfony and it's not installed by default)
- create MySQL user and database before the install
- launch the install command
There is almost no impact on builds execution time.

API-87: Launch integration tests in Travis

---

features/product/browse_products_by_locale_and_scope.feature
src/Oro/Bundle/UserBundle/Controller/UserController.php
src/Pim/Bundle/CatalogBundle/Helper/LocaleHelper.php
src/Pim/Bundle/CatalogBundle/spec/Helper/LocaleHelperSpec.php
src/Pim/Bundle/EnrichBundle/Resources/views/MassEditAction/product/configure/edit-common-attributes.html.twig
src/Pim/Bundle/UserBundle/Context/UserContext.php
src/Pim/Bundle/UserBundle/EventListener/LocaleListener.php
src/Pim/Bundle/UserBundle/spec/Context/UserContextSpec.php

This PR changes the behavior of the datagrid locale.
Now, the dataLocale is stored in the session, therefore the user keeps its working locale when navigating in the PIM.

AMS-128: Keep working locale in session

---

CHANGELOG-1.5.md
src/Pim/Bundle/UIBundle/Controller/AjaxOptionController.php

| Changelog updated                 | :white_check_mark: 
| Review and 2 GTM                  | :red_circle:
| Micro Demo to the PO (Story only) | :white_check_mark: 
Assuming you have a "animal" tag, if you try to add "anima" you will not be able to do it as it will select animal by default. Adding the search term to the search results fix it.

PIM-6092: Always allow to create new option on select2

---

features/Context/AssertionContext.php
features/product/browse_products_by_locale_and_scope.feature
src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filter/product_scope-filter.js

This PR changes the behavior of the datagrid scope.
Now, the scope is stored in the session storage, therefore the user keeps its working scope when navigating in the PIM.
| Tech Doc                          | N/A

AMS-130: Keep working scope in session

---

tests/TestCase.php

Currently, there is a "Too many connections" error when too many tests are launched with phpunit.
Error comes from two things:
- doctrine which does not close properly connections.
- DoctrineJobRepository creates is own connection but never close it
:warning: **Warning** :warning: :
Even if we close properly connections in our tests, there is still connections unclosed in our current version of doctrine-bundle (Stof fixed this bug in this [PR](https://github.com/doctrine/DoctrineBundle/commit/2f8d7263c4c44445b51fc2d9bf71d21f7016347d)).
We can try to upgrade this bundle, launch CI and perfbench to check the impact. If there is no impact, we can merge. If not, take a look at this PR and fix directly the problem inside the PIM.
EDIT:
Upgrade to the last version of DoctrineBundle increase by …

API-88: Fix "Too many connections" error on integration tests

---

.travis.yml
CHANGELOG-1.7.md
app/config/parameters_test.yml.dist
src/Pim/Bundle/VersioningBundle/Denormalizer/Flat/ProductValue/PricesDenormalizer.php
src/Pim/Bundle/VersioningBundle/spec/Denormalizer/Flat/ProductValue/PricesDenormalizerSpec.php
src/Pim/Component/Catalog/Builder/ProductBuilder.php
src/Pim/Component/Catalog/Builder/ProductBuilderInterface.php
src/Pim/Component/Catalog/Updater/Adder/PriceCollectionAttributeAdder.php
src/Pim/Component/Catalog/Updater/Copier/PriceCollectionAttributeCopier.php
src/Pim/Component/Catalog/Updater/Setter/PriceCollectionAttributeSetter.php
src/Pim/Component/Catalog/spec/Updater/Adder/PriceCollectionAttributeAdderSpec.php
src/Pim/Component/Catalog/spec/Updater/Copier/PriceCollectionAttributeCopierSpec.php
src/Pim/Component/Catalog/spec/Updater/Setter/PriceCollectionAttributeSetterSpec.php

Right now, the ProductBuilder can add prices to the product value with two different method:
- `addPriceForCurrency` which will only add a currency, with no amount,
- `addPriceForCurrencyWithData` which add both amount and currency.
This could be done by only one method, for which the amount can be null. So `addPriceForCurrencyWithData` becomes deprecated, and only `addPriceForCurrency` is used everywhere in the PIM.
Since our integration tests are ran on Travis, it is mandatory to install the PIM. However, the minimal catalog is enough, and way faster to install than icecat_demo_dev, so a new `app/config/parameters_test.yml.dist` model is added and used by Travis. …

TIP-671: Deprecate ProductBuilder method "addPriceForCurrencyWithData"

---

CHANGELOG-1.5.md
features/import/import_families.feature
spec/Pim/Bundle/CatalogBundle/Doctrine/ORM/Sorter/FamilySorterSpec.php
spec/Pim/Bundle/DataGridBundle/Datasource/ResultRecord/MongoDbOdm/Product/FamilyTransformerSpec.php
spec/Pim/Bundle/DataGridBundle/Extension/Selector/Orm/Product/FamilySelectorSpec.php
src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/AttributeRepository.php
src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/FamilyRepository.php
src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/GroupRepository.php
src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Sorter/FamilySorter.php
src/Pim/Bundle/DataGridBundle/Datasource/ResultRecord/MongoDbOdm/Product/FamilyTransformer.php
src/Pim/Bundle/DataGridBundle/Extension/Selector/Orm/Product/FamilySelector.php
src/Pim/Bundle/DataGridBundle/spec/Extension/Selector/Orm/Product/FamilySelectorSpec.php

This is a backport of a 1.6 fix + an adaptation for mongo. What is to be reviewed is:
*  ̀CHANGELOG-1.5.md ̀
*  ̀features/import/import_families.feature ̀
*  ̀.../FamilyTransformer.php ̀
*  ̀.../FamilyTransformerSpec.php ̀
The issue is that, in some cases we store empty labels during import and only took care of the `null` case. Now we also check that the label is not empty when we replace it by the code.
| Micro …

PIM-6107: Fix an issue where family code is not displayed

---

CHANGELOG-1.6.md
features/product/associate_product.feature
src/Pim/Component/Catalog/Updater/Setter/AssociationFieldSetter.php
src/Pim/Component/Catalog/spec/Updater/Setter/AssociationFieldSetterSpec.php

This fix follow the @anaelChardan Fix on association import that broke the associations when you try to save the product from the UI. cf https://github.com/akeneo/pim-community-dev/pull/5397
| Micro Demo to the PO (Story only) | :clock1:

PIM-6110: Saving a product value clear the saved associations

---

src/Pim/Bundle/EnrichBundle/Controller/Rest/ProductController.php
src/Pim/Component/Catalog/Builder/ProductBuilder.php
src/Pim/Component/Catalog/Comparator/Attribute/BooleanComparator.php
src/Pim/Component/Catalog/spec/Comparator/Attribute/BooleanComparatorSpec.php

Since the standard format, there is a bug when you try to save a product which has already a media. It's due to a wrong condition check on an empty array.
Unfortunately, it hid a problem with boolean values.
When a product is saved with the UI, boolean product values are set to false, even if they are not modified and null in database (and only for attributes belonging to the family).
This is a well-known behaviour and it has some consequences on the draft.
When you make a proposal on a draft, boolean …

Tip 475 : fix an error thrown when saving a product with a media

---

features/Context/Page/Role/Edit.php
features/Pim/Behat/Context/Domain/System/PermissionsContext.php
features/Pim/Behat/Decorator/Permission/PermissionDecorator.php
features/api/acl/assert_acl.feature
src/Pim/Bundle/ApiBundle/Resources/config/acl.yml
src/Pim/Bundle/ApiBundle/Resources/config/acl_groups.yml
src/Pim/Bundle/ApiBundle/Resources/translations/messages.en.yml
src/Pim/Bundle/EnrichBundle/Resources/config/bundles/oro_user.yml
src/Pim/Bundle/UserBundle/Resources/views/Role/update.html.twig
src/Pim/Bundle/UserBundle/Twig/AclGroupsExtension.php

To manage permissions on API (and correctly separate web API ACL from the UI ACL), we have to create a new tab on role form.
Behat has been added to be sure the behavior works as expected, but ACLs will be really check on integration tests (in an other PR, when authentication will be done), not in behat. …

API-63: Manage the access to the web API

---

spec/Pim/Bundle/EnrichBundle/Provider/StructureVersion/ProductStructureVersionProviderSpec.php
src/Pim/Bundle/EnrichBundle/Provider/StructureVersion/ProductStructureVersionProvider.php
src/Pim/Bundle/EnrichBundle/Provider/StructureVersion/StructureVersionProviderInterface.php

This PR fixes the issue with data migration (MySQL to Mongo, or pim version upgrade) when the verionning is lost:
PHP Fatal error: Call to a member function getLoggedAt() on null in vendor/akeneo/pim-community-dev/src/Pim/Bundle/EnrichBundle/Provider/StructureVersion/ProductStructureVersionProvider.php on line 37 …

Fix versionning issue with data migration

---

tests/TestCase.php

`doAfterFixtureImport` allows to do extra things after a database initialization.
Use case: In the EE, we need to clean the rights after a data fixture import.  
| Added Specs                       | no
| Added integration tests           | no
| Review and 2 GTM                  | no
| Tech Doc                          | no

Do extra thing after the fixture import

---

src/Pim/Component/Connector/Encoder/CsvEncoder.php

If we don't close the file handler, we could have unexpected behavior on multiple use of this encoder.

CsvEncoder: close resource after reading content

---

features/export/product-export-builder/export_products_by_locales.feature

Before the TIP-322 (add business exceptions in updaters), when you update with an unknown available locale, it was silently ignored.
This behaviour has been fixed in this commit, and now, it throws an exception :
https://github.com/akeneo/pim-community-dev/commit/ec5eb1f4890213a6a6f9cf7cb6534ac11cf65109
This PR fixed behats that failed in CE (orm and odm) since the merge.
Scenarios create an attribute with an available locale "all", which is an unknown locale raising an exception now. 
[//]: <> (What does …

TIP-322: fix behat error due to an unknown available locale

---

src/Pim/Component/Catalog/Model/AbstractProductValue.php

In the case of a product value holding array values, like one linked to a `json_array` doctrine type, the actual `__toString` method will crash before of array to string conversion.

Enable array ProductValue to string

---

src/Pim/Bundle/ApiBundle/Controller/Rest/AttributeOptionController.php
src/Pim/Bundle/ApiBundle/Resources/config/controllers.yml
src/Pim/Bundle/ApiBundle/Resources/config/routing/attribute.yml
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Rest/AttributeOption/GetAttributeOptionIntegration.php

Get a single attribute option 
https://akeneo.atlassian.net/browse/API-40
Call GET 'api/rest/v1/attributes/tshirt_style/options/turtleneck'
Return 200:
```
{"code":"turtleneck","attribute":"tshirt_style","sort_order":1,"labels":{"de_DE":"Rollkragen","en_US":"Turtleneck","fr_FR":"Col roul\u00e9"}}
``` …

API-40: Get a single attribute option

---

src/Pim/Bundle/ApiBundle/Resources/config/acl.yml
src/Pim/Bundle/ApiBundle/Resources/config/acl_groups.yml
upgrades/schema/Version_1_7_20170116172612_acl.php

As authentication is not already done, there is no tests on this part (will be done in an other PR)
| Added Specs                       | :negative_squared_cross_mark: 
| Added Behats                      | :negative_squared_cross_mark: 
| Added integration tests           | :negative_squared_cross_mark: 
| Migration script                  | :white_check_mark:
| Tech Doc                          | :negative_squared_cross_mark: 
:negative_squared_cross_mark: Not …

API-58: Manage permissions to view or modify the catalog structure

---

CHANGELOG-1.7.md
app/config/config.yml
app/config/config_dev.yml
app/config/routing.yml
composer.json
src/Oro/Bundle/FilterBundle/Filter/AbstractFilter.php
src/Oro/Bundle/FilterBundle/Form/Type/Filter/FilterType.php
src/Pim/Bundle/FilterBundle/spec/Filter/ProductValue/BooleanFilterSpec.php

This PR updates the PIM to the last version of Symfony 2.7.
This version come with a new behavior on the ChoiceType field from the Form component (https://symfony.com/doc/2.7/reference/forms/types/choice.html#choices-as-values), causing the labels of the datagrid filters operators to be replaced by their codes (simple numbers, see screenshot below).
This problem is fixed by the second commit.
| …

TIP-682: Update to Symfony 2.7.23

---

.travis.yml
src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/ChannelRepository.php
src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/LocaleRepository.php

We do ugly stuff in the `ChannelRepository` and the `LocaleRepository`: overriding the `findBy` method from Doctrine EntityRepository and changing its signature. This is not allowed in PHP 7.1 anymore, so PIM installation fails.
This PR fixes this ugliness, and as we recently bump to Symfony 2.7.23, all static tests are now OK with PHP 7.1. So we can remove it from "allow_failures" in Travis!
| Review …

Remove PHP 7.1 failure allowed from travis

---

features/Context/Page/Base/Base.php
features/Context/WebUser.php

For now we have gherkin to click on buttons, but we have icon button components that can only be identified with their on-hover title.
This method allows to retrieve them.

AMS-6: Add gherkin to click on icon button

---

CHANGELOG-1.6.md
features/Context/DataGridContext.php
features/product/associate_product.feature
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/associations.js

The bug is:
- Go to a PEF
- Go to tab Associations
- Select some groups
- Save
- Go to another group
- It displays the list of previous checked groups in the new grid !
| Micro Demo to the PO (Story only) | :clock1:
| Tech Doc …

[PIM-6113] Wrong context switch on association groups

---

CHANGELOG-1.6.md
features/Context/CommandContext.php
features/technical/security.feature
src/Akeneo/Component/Console/CommandLauncher.php

Avoid UNIX command injection through curl
| Added integration tests           | :white_check_mark: :red_circle: :negative_squared_cross_mark: :clock1:
| Changelog updated                 | :white_check_mark: :red_circle: :negative_squared_cross_mark: :clock1:
| Review and 2 GTM                  | :white_check_mark: :red_circle: :negative_squared_cross_mark: :clock1: …

PIM-6062: Fix potential unix commands injection

---

phpspec.yml.dist
src/Pim/Bundle/ApiBundle/Controller/Rest/CategoryController.php
src/Pim/Bundle/ApiBundle/DependencyInjection/PimApiExtension.php
src/Pim/Bundle/ApiBundle/PimApiBundle.php
src/Pim/Bundle/ApiBundle/Resources/config/controllers.yml
src/Pim/Bundle/ApiBundle/Resources/config/normalizers.yml
src/Pim/Bundle/ApiBundle/Resources/config/serializers.yml
src/Pim/Bundle/EnrichBundle/Resources/config/bundles/fos_rest.yml
src/Pim/Component/Api/Exception/DocumentedHttpException.php
src/Pim/Component/Api/Exception/ViolationHttpException.php
src/Pim/Component/Api/Normalizer/Exception/DocumentedNormalizer.php
src/Pim/Component/Api/Normalizer/Exception/ViolationNormalizer.php
src/Pim/Component/Api/spec/Exception/DocumentedHttpExceptionSpec.php
src/Pim/Component/Api/spec/Exception/ViolationHttpExceptionSpec.php
src/Pim/Component/Api/spec/Normalizer/Exception/DocumentedNormalizerSpec.php
src/Pim/Component/Api/spec/Normalizer/Exception/ViolationNormalizerSpec.php

FosRestBundle catch exception thrown by the API and normalize them in [ExceptionNormalizer](https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/Serializer/Normalizer/ExceptionNormalizer.php), which returns errors like that:
```
{
"code": 404,
"message": "Not Found"
}
```
In the API, we need for some errors to add informations in the response.
When errors come from the updater (with an unknown field for instance), response has to return a link to the documentation of the standard format:
```
{
"code": 404,
"message": "Not Found",
"links": {
"documentation": {
"href": "https://docs.akeneo.com/..."
}
}
}
```
When errors come from the validators, response has to return all errors:
```
{
"code":422,
"message": "Validation failed"
"errors":[
{
"field": "xxx", "message": "yyy"
}
] 
} …
```

API-104: display more informations in response when an exception is thrown

---

src/Pim/Bundle/EnrichBundle/Resources/public/js/form/registry.js

I already had the problem that multiple extensions of the same module were sent by reference, which is a problem.
Maybe we should put some const of something, but this code was fixing my problem.
I make this PR to have the fix somewhere, it can be merged/discussed.

Don't return form extensions by reference

---

src/Pim/Bundle/ApiBundle/Controller/Rest/CategoryController.php
src/Pim/Bundle/ApiBundle/Resources/config/routing.yml
src/Pim/Bundle/ApiBundle/Resources/config/routing/category.yml
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Rest/Category/ListCategoryIntegration.php

Get a list of categories
https://akeneo.atlassian.net/browse/API-17
Call /api/rest/v1/categories
Response 200
```
{"items":[{"code":"master","parent":null,"labels":{"en_US":"Master catalog","de_DE":"Hauptkatalog","fr_FR":"Catalogue principal"}}]}
```
| Tech Doc …

API-17: Get a list of categories

---

src/Pim/Component/Catalog/Builder/ProductBuilderInterface.php

This method will not be needed in 1.8, thanks to the new ProductValueFactory.

TIP-681: Deprecate ProductBuilderInterface::removePricesNotInCurrency

---

src/Akeneo/Component/Classification/Updater/CategoryUpdater.php
src/Akeneo/Component/Classification/spec/Updater/CategoryUpdaterSpec.php
src/Akeneo/Component/StorageUtils/Exception/InvalidObjectException.php
src/Akeneo/Component/StorageUtils/Exception/InvalidPropertyException.php
src/Akeneo/Component/StorageUtils/Exception/InvalidPropertyTypeException.php
src/Pim/Bundle/ApiBundle/Controller/Rest/CategoryController.php
src/Pim/Bundle/ApiBundle/Resources/config/controllers.yml
src/Pim/Bundle/ApiBundle/Resources/config/routing.yml
src/Pim/Bundle/ApiBundle/Resources/config/routing/category.yml
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Rest/Category/CreateCategoryIntegration.php
src/Pim/Component/Api/Exception/ViolationHttpException.php
src/Pim/Component/Api/spec/Normalizer/Exception/ViolationNormalizerSpec.php

Implementation of the POST (=create) on the category entity.
- I've had a new business exception when the standard format has a wrong input type
- Check the standard format in the updater
- A parent category can be set to null now (impossible before)
| …

Api 19 : create a category via the API

---

app/config/pim_parameters.yml
src/Pim/Bundle/ApiBundle/DependencyInjection/PimApiExtension.php
src/Pim/Bundle/ApiBundle/Resources/config/hateoas.yml
src/Pim/Component/Api/Exception/PaginationParametersException.php
src/Pim/Component/Api/Exception/ReservedPropertyKeyException.php
src/Pim/Component/Api/Hal/HalResource.php
src/Pim/Component/Api/Hal/Link.php
src/Pim/Component/Api/Pagination/HalPaginator.php
src/Pim/Component/Api/Pagination/PaginatorInterface.php
src/Pim/Component/Api/Pagination/ParameterValidator.php
src/Pim/Component/Api/Pagination/ParameterValidatorInterface.php
src/Pim/Component/Api/spec/Hal/HalResourceSpec.php
src/Pim/Component/Api/spec/Hal/LinkSpec.php
src/Pim/Component/Api/spec/Pagination/HalPaginatorSpec.php
src/Pim/Component/Api/spec/Pagination/ParameterValidatorSpec.php

Since the last review : 
- delete interfaces LinkInterface and ResourceInterface
- some renaming (generateResource into createResource in HALReosurce for example)
- add an exception when the data in a resource use forbidden keyword (_links and _embedded)
Since the second review  : 
- fix comments about the code
- add a limit max in the parametor validator to limit the number of items returned in a paginated response
- add a basic implementation of HAL resource (first commit among the two) and remove the …

API-32: add a HAL paginator and pagination parameter validator 

---

features/Context/catalog/apparel/attributes.csv
features/enrich/variant-group/edit_attributes_of_a_variant_group.feature
src/Pim/Component/Catalog/Updater/VariantGroupUpdater.php
src/Pim/Component/Catalog/spec/Updater/VariantGroupUpdaterSpec.php

| Q | A
| --- | ---
| Bug fix? | yes
| New feature? | no 
| BC breaks? | hopefully not
| Deprecations? | no
| Fixed tickets | fixes #5491 
| Related issues/PRs | -
| License | OSL 3.0
With this PR the `VariantGroupUpdate::replaceMediaLocalePathsByStoredPaths()` is fixed to take the locale and scope of the attribute into mind. So only the correct `filePath` of the current attributes locale/scope gets updated and not all with the `filePath` of the last value iteration of the given `$attributeCode`
The behat feature [`Edit attributes of a variant group`](https://github.com/akeneo/pim-community-dev/blob/1.6/features/enrich/variant-group/edit_attributes_of_a_variant_group.feature) has two scenarios which covers the save of edited localized/scoped attributes (`Successfully edit a localizable …

Take locale and scope into mind when replacing local paths with stored

---

src/Pim/Bundle/EnrichBundle/Resources/public/templates/grid/view-selector-line.html
src/Pim/Bundle/UIBundle/Resources/public/less/lib/select2.less

This PR removes the overlay in the view selector and update the style to use the default hover color:

AMS-70: remove unused overly in view selector

---

CHANGELOG-1.6.md
src/Pim/Bundle/CatalogBundle/Command/CleanMongoDBCommand.php
src/Pim/Bundle/CatalogBundle/MongoDB/Normalizer/Document/ProductNormalizer.php

```
app/console pim:product:pim:mongodb:clean
```
This brings a new command to clean MongoDB documents and remove osolete relations with MySQL stored entities:
- attribute
- attribute options
- families
- categories
- reference data (assets included)
An out of sync state can occur when performing deletion operations on MySQL entities that cascades towers a MongoDB cleaning. If an error occurs and prevent the MongoDB query from being completely executed, it results to this out of sync situation.
This also fixes a BC in MongoDB:
BC in MongoDB JSON :
- [v1.6.7 TranslationNormalizer.php#L47](https://github.com/akeneo/pim-community-dev/blob/v1.6.7/src/Pim/Component/Catalog/Normalizer/Structured/TranslationNormalizer.php#L47)
- [v1.5.16 …

PIM-6086: cleaning+migration command for MongoDB documents

---

CHANGELOG-1.6.md
features/Pim/Behat/Decorator/Export/Filter/BaseDecorator.php
features/export/product-export-builder/export_products_by_multiselect.feature
features/export/product-export-builder/export_products_by_simpleselect.feature
src/Pim/Bundle/EnrichBundle/Resources/public/js/export/product/edit/content/data.js

This PR fixes the fact than when you try to remove an attribute of type "simple select" or "multi select" on the product export builder, it does nothing.
The issue was resolved by using the standard filter name (without '.code' at the end of the filter).
`Todo`: …

[PIM-6080] Fix simple-multi select removal on product export builder

---

phpspec.yml.dist
src/Pim/Bundle/ApiBundle/DependencyInjection/PimApiExtension.php
src/Pim/Bundle/ApiBundle/EventSubscriber/CheckHeadersRequestSubscriber.php
src/Pim/Bundle/ApiBundle/Resources/config/event_subscribers.yml
src/Pim/Bundle/ApiBundle/spec/EventSubscriber/CheckHeadersRequestSubscriberSpec.php
src/Pim/Bundle/ApiBundle/tests/integration/EventSubscriber/CheckHeadersRequestSubscriberIntegration.php
src/Pim/Bundle/EnrichBundle/Resources/config/bundles/fos_rest.yml

Valid headers in the API.
`Accept` (when you GET a resource) and `Content-Type` (when you POST/PATCH a resource) headers are not required in the API, but if one of them are in headers and are different than `application/json`, we throw a `NotAcceptableHttpException` (error 406).
Why do we accept `*/*` for a GET and `application/x-www-form-urlencoded` for POST & PATCH ?
These headers are added by Symfony, we cannot change that :)
--
Cannot merge this PR as long as there is not PATCH/POST action in the API, tests added in this PR are wrong
| Added integration tests           | …

API-35: valid headers on the API

---

app/config/security.yml
app/config/security_test.yml
src/Pim/Bundle/ApiBundle/Controller/TokenController.php
src/Pim/Bundle/ApiBundle/Resources/config/controllers.yml
src/Pim/Bundle/ApiBundle/Resources/config/routing.yml
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Token/GetAccessTokenIntegration.php

In this PR:
- New route that wraps FOS OAuth2 server and transform the response for error cases.
- New security firewall for the API.
- This firewall has been disabled to allow integration tests to pass. As we still want to test the firewall, it will be reactivated and integration tests will be reworked in another PR. …

API-50: Access token route

---

upgrades/1.3-1.4/common/MediaMigration.php

With big amount of media files managed by the PIM, the media migration from version 1.3 to 1.6 is slow (and slows down during the migration process) and its quite memory consuming.
The issue is in upgrades/1.3-1.4/common/MediaMigration.php::storeLocalMedias
The foreach loop does not detach the $fileInfo entities from the entity manager.
Detaching the entities and regular flushing/clearing the entity manager helps the garbage collector to keep the memory usage low and speeds up the migration process as the entity manager does not handle the detached entities (as long as they are not reattached anymore).
| Q | A |
| --- | --- |
| Added Specs | N |
| Added Behats | N |
| Changelog updated | N |
| Review and 2 GTM | N |
| Micro Demo to the PO (Story only) | N |
| Migration script | N |
| …

Media migration memory consumption

---

CHANGELOG-1.7.md
features/Context/WebUser.php
features/channel/edit_channel.feature
features/import/import_channels.feature
src/Akeneo/Bundle/MeasureBundle/CHANGELOG.md
src/Akeneo/Bundle/MeasureBundle/Manager/MeasureManager.php
src/Akeneo/Bundle/MeasureBundle/spec/Manager/MeasureManagerSpec.php
src/Pim/Bundle/CatalogBundle/Resources/config/updaters.yml
src/Pim/Bundle/EnrichBundle/Resources/public/js/channel/form/properties/conversion-unit.js
src/Pim/Bundle/EnrichBundle/Resources/public/templates/channel/tab/properties/conversion-unit.html
src/Pim/Component/Catalog/Updater/ChannelUpdater.php
src/Pim/Component/Catalog/spec/Updater/ChannelUpdaterSpec.php

This adds the versioning support for the conversion units of channels. (not supported 1.6).
**Solution:**
This PR fixes the way the conversionUnits are sent and saved into the channel:
```
[
"attribute_code_1" => "metric",
"attribute_code2" => "metric",
]
```
instead of:
```
[
[ "attribute_code1" =>"metric"],
[ "attribute_code2" =>"metric"]
]
```
**What does that do ?:**
This PR Adapts the channelUpdater to do some validation on the conversionUnits before setting the data from the form into the channel property.
It also adapts the way the conversionUnits are sent from the UI on save.
It also adapts the way the conversionUnits property is shown from the template.
No migration needed as the channel edit form has been pefized in 1.7 and …

Fixing channel conversion units versionning

---

tests/ConnectionCloser.php
tests/DatabasePurger.php
tests/FixturesLoader.php
tests/TestCase.php

Splitting the TestCase into smaller SRP classes will allow creating other TestCases without falling into inheritance hell.
For example we need a new ApiTestCase that will inherit from WebTestCase (so not from our main TestCase) but we still need the whole fixtures / purge logic.

Split integration TestCase into smaller classes

---

src/Pim/Bundle/EnrichBundle/Controller/ProductController.php

While migrating to V. 1.6 I've noticed an error with the undefined `$result` in the `ProductController`: `switch ($request->get('action')) {` 
It seems, that this method isn't used anymore, so it can be removed.

Remove unused redirectAfterEdit()

---

CHANGELOG-1.5.md
spec/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/Saver/ProductSaverSpec.php
spec/Pim/Bundle/CatalogBundle/MongoDB/Normalizer/Document/ProductNormalizerSpec.php
src/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/Saver/ProductSaver.php
src/Pim/Bundle/CatalogBundle/MongoDB/Normalizer/Document/ProductNormalizer.php

Backport of https://github.com/akeneo/pim-community-dev/commit/0361ec6add72b939ce849ac35347fdc32df858a5
From 1.6 to 1.5
https://github.com/akeneo/pim-community-dev/pull/5464
Was already rewritten for master.

[Backport 1.6->1.5] PIM-6038: Updated date of products is set in the mongoDB product saver

---

features/datagrid/datagrid_views.feature
src/Pim/Bundle/EnrichBundle/Resources/public/js/grid/view-selector.js

**The bug:**
- Create a custom view
- Click on Columns to customise the grid
- Remove/Add columns, click on Save
**The fix:**
The problem comes from the fetchers, the promises return the View by reference, so when we update the columns, the View from the fetcher has its columns modified too, but it should not. This fix bypass the cache of the fetcher by forcing a re-fetch. …

AMS-156: force fetching of view on columns update

---

CHANGELOG-1.6.md
features/job-tracker/display_jobs_execution_in_job_tracker.feature
src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/job_tracker.yml

This PR fix the string filter 'equals to', it does not work in the "job tracker" page.
Before :

[PIM-6140] Fix job execution 'equals to' filter

---

app/config/security_test.yml
src/Pim/Bundle/ApiBundle/tests/integration/ApiTestCase.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Rest/Attribute/GetAttributeIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Rest/Attribute/ListAttributeIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Rest/AttributeOption/GetAttributeOptionIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Rest/Category/CreateCategoryIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Rest/Category/GetCategoryIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Rest/Category/ListCategoryIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Rest/Family/GetFamilyIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Rest/Family/ListFamilyIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Token/GetAccessTokenIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/EventSubscriber/CheckHeadersRequestSubscriberIntegration.php
tests/TestCase.php

Until now the security firewall was disabled in test environment. This PR re-enables it to allow the tests to use the real OAuth workflow.
These steps are now executed for each test case:
1. create a client via the dedicated command
2. call `/api/oauth/v1/token` to get an access token
Then the token is included in every requests.
To do that we introduce a new TestCase for the API.
The good news: the integration tests are closer to the real application behavior.
The bad news: it is approximately 15% slower.

API-50: Don't bypass the firewall in integration tests

---

src/Akeneo/Component/Classification/Updater/CategoryUpdater.php
src/Akeneo/Component/Classification/spec/Updater/CategoryUpdaterSpec.php
src/Akeneo/Component/StorageUtils/Exception/InvalidPropertyTypeException.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Rest/Category/CreateCategoryIntegration.php

It's exactly the same as https://github.com/akeneo/pim-community-dev/pull/5602.
In some errors messages, we add some informations such like that:
`Property "attribute_type" does not expect an empty value (for updater attribute).`
`for updater` attribute is a technical information and should not be shown to user.
This PR deletes messages of this type in the api-web branch, because we have added a new exception "InvalidPropertyTypeException".
[//]: <> (What does this Pull Request do? reference the related …

Tip 322 : Remove technical informations in error messages

---

src/Pim/Bundle/ApiBundle/Controller/Rest/AttributeController.php
src/Pim/Bundle/ApiBundle/Resources/config/controllers.yml
src/Pim/Bundle/ApiBundle/Resources/config/routing.yml
src/Pim/Bundle/ApiBundle/Resources/config/routing/attribute.yml
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Rest/Attribute/CreateAttributeIntegration.php
src/Pim/Component/Catalog/Updater/AttributeUpdater.php
src/Pim/Component/Catalog/spec/Updater/AttributeUpdaterSpec.php
src/Pim/Component/Catalog/tests/integration/Normalizer/Standard/AttributeIntegration.php
src/Pim/Component/Connector/ArrayConverter/FlatToStandard/Attribute.php
src/Pim/Component/Connector/ArrayConverter/StandardToFlat/Attribute.php
src/Pim/Component/Connector/spec/ArrayConverter/FlatToStandard/AttributeSpec.php
src/Pim/Component/Connector/spec/ArrayConverter/StandardToFlat/AttributeSpec.php

Create a new attribute
https://akeneo.atlassian.net/browse/API-22
```
POST /api/rest/v1/attributes
```
with
```
{"code":"a_new_text","type":"pim_catalog_text","group":"attributeGroupA","unique":false,"useable_as_grid_filter":false,"allowed_extensions":[],"metric_family":null,"default_metric_unit":null,"reference_data_name":null,"available_locales":[],"max_characters":null,"validation_rule":null,"validation_regexp":null,"wysiwyg_enabled":false,"number_min":null,"number_max":null,"decimals_allowed":false,"negative_allowed":false,"date_min":null,"date_max":null,"max_file_size":null,"minimum_input_length":0,"sort_order":12,"localizable":false,"scopable":false,"labels":[]}
```
RESPONSE 200
| Added Specs …

API-22: Create a new attribute

---

CHANGELOG-1.7.md
features/Context/WebUser.php
features/dashboard/display_last_operations_widget.feature
features/datagrid/products_backtothegrid.feature
features/export/browse_export_executions.feature
features/job-tracker/display_jobs_execution_in_job_tracker.feature
features/mass-action/mass_delete.feature
features/mass-action/select_products_to_mass_edit.feature
src/Akeneo/Bundle/BatchBundle/Resources/views/Mails/notification.html.twig
src/Oro/Bundle/DataGridBundle/Extension/Toolbar/Configuration.php
src/Pim/Bundle/DashboardBundle/Resources/public/templates/last-operations-widget.html
src/Pim/Bundle/DashboardBundle/Resources/translations/jsmessages.en.yml
src/Pim/Bundle/DashboardBundle/Widget/LastOperationsWidget.php
src/Pim/Bundle/EnrichBundle/Doctrine/ORM/Repository/JobExecutionRepository.php
src/Pim/Bundle/EnrichBundle/Doctrine/ORM/Repository/JobTrackerRepository.php
src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/job_tracker.yml
src/Pim/Bundle/ImportExportBundle/Resources/config/datagrid/job_execution.yml
src/Pim/Bundle/ImportExportBundle/Resources/translations/messages.en.yml
src/Pim/Bundle/ImportExportBundle/Resources/views/Property/status.html.twig
src/Pim/Bundle/ImportExportBundle/Resources/views/Property/warning.html.twig

This PR add a warning count column on job tracker and import/export history.
| Added integration tests           |:negative_squared_cross_mark:
| Changelog updated                 | :clock1:
:red_circle: …

PIM-6093: add warning count on job execution grids

---

src/Akeneo/Component/Classification/Updater/CategoryUpdater.php
src/Pim/Bundle/ApiBundle/Controller/Rest/CategoryController.php
src/Pim/Bundle/ApiBundle/Resources/config/routing/category.yml
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Rest/Category/CreateCategoryIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Rest/Category/PartialUpdateCategoryIntegration.php

Method PATCH to update partially a category. 
It's an upsert operation : if the category does not exist, it creates it.
The code is optional in the body (already provided in the url).
In case of a creation, the code should be the same between the url query parameter and the body (if it's provided in the body).
| --------------------------------- | …

Api 30 : add partial update of a category in the API

---

src/Pim/Bundle/ApiBundle/Controller/Rest/FamilyController.php
src/Pim/Bundle/ApiBundle/Resources/config/controllers.yml
src/Pim/Bundle/ApiBundle/Resources/config/routing/family.yml
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Rest/Attribute/GetAttributeIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Rest/Attribute/ListAttributeIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Rest/AttributeOption/GetAttributeOptionIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Rest/Category/CreateCategoryIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Rest/Category/GetCategoryIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Rest/Category/ListCategoryIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Rest/Family/CreateFamilyIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Rest/Family/GetFamilyIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Rest/Family/ListFamilyIntegration.php
src/Pim/Component/Catalog/Updater/FamilyUpdater.php
src/Pim/Component/Catalog/spec/Updater/FamilyUpdaterSpec.php

This PR : 
- add the POST operation (=creation) on a family
- add checks on the structure of the standard format to avoid error 500 with invalid data provided …

Api 23 : add creation of a family in the API

---

src/Pim/Bundle/ApiBundle/EventSubscriber/CheckHeadersRequestSubscriber.php
src/Pim/Bundle/ApiBundle/spec/EventSubscriber/CheckHeadersRequestSubscriberSpec.php
src/Pim/Bundle/ApiBundle/tests/integration/ApiTestCase.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Token/GetAccessTokenIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/EventSubscriber/CheckHeadersRequestSubscriberIntegration.php

Originally, the Content-type header was not mandatory in the POST/PUT/PATCH request. And if it was specified, it should be "application/json".
A lot of clients use a Content-Type by default. For example, curl use "application/x-www-form-urlencoded" if you don't specify any Content-Type header.
Therefore, it's pretty useless to allow users to not specify anything, because the client do (or rather force) that for them...
We've chosen to force the user to specify the Content-Type header.
Moreover, a FOSRest …

Api 35 : content type header is mandatory in the API, allowing automatic JSON validation in FOS listener 

---

CHANGELOG-1.6.md
features/import/import_families.feature
src/Pim/Component/Catalog/Updater/FamilyUpdater.php
src/Pim/Component/Catalog/spec/Updater/FamilyUpdaterSpec.php

When a family is imported with a missing column in the file, requirements were removed.

PIM-6124: Import family with missing requirement column does not remove associated requirements

---

src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/ChannelRepository.php
src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/LocaleRepository.php

Hello,
I tried to install Akeneo v1.6 on PHP 7.1, and noticed some issues already fixed on master branch but not yet available on `1.6` branch (see https://github.com/akeneo/pim-community-dev/commit/a53df0fec80ffd4e4f6795caa8bef7af5691ffe6).
Looking at classes, I find another classes that doesn't respect the declaration of EntityRepository parent class functions, so this is my first contribution \o/
> ~~This commit should be also applied on `1.6` branch~~ => nope, cf @damien-carcel comment
Mickaël

Improved PHP 7.1 support

---

src/Pim/Bundle/EnrichBundle/Resources/public/js/grid/view-selector.js

- The problem: When switching from grid to other page multiple times, then going on a project and selecting another category, there is multiple times the message "You're leaving project scope."
- Why: We instanciate the View Selector in [_views.html.twig](https://github.com/akeneo/pim-community-dev/blob/master/src/Pim/Bundle/DataGridBundle/Resources/views/Datagrid/_views.html.twig), so, each time we go on the grid, we instanciate a new View Selector, and each instance listens to some events.
- Solution: Unbind view selector subscribers on route change
| Added Behats …

AMS-164: detach old view selectors in order to avoid multiple subscribers

---

UPGRADE-1.6.md

MacOS supports the "rm -rf file"-syntax but not "rm file -rf". …

Docs: Change rm command line arguments order

---

features/product/filtering/filter_products_per_group.feature
src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/GroupRepository.php

The grid fetches Groups used as filter, by sending this to the backend:
```
{type: 'code', ids: ['oro_mugs']}
```
The GroupRepository takes the `type` in account for the `SELECT` part of the query, but not in the `WHERE` part. This PR fixes it.

Fix GroupRepository: use code or id as identifier to fetch Groups

---

src/Pim/Bundle/CatalogBundle/Doctrine/Common/Saver/GroupSaver.php

During variant group saving, the protected method `copyVariantGroupValues` is called twice by the `save` method of the GroupSaver:
- once in the method `persistGroup` (renamed at the occasion in `persistGroupAndSaveAssociatedProducts` to be more explicit)
- then a second time in the `save`, just after `persistGroupAndSaveAssociatedProducts`.
This PR removes the second call to the method, which is completely useless, and further more could be source of possible bugs as product are detached at the end of the first call. …

TIP-697: Fix variant group values copy to product

---

CHANGELOG-1.7.md
features/Context/WebUser.php
features/enrich/variant-group/add_attributes_to_a_variant_group.feature
features/export/product-export-builder/export_products_by_boolean.feature
features/export/product-export-builder/export_products_by_completeness.feature
features/export/product-export-builder/export_products_by_families.feature
features/export/product-export-builder/export_products_by_identifier.feature
features/export/product-export-builder/export_products_by_locales.feature
features/export/product-export-builder/export_products_by_status.feature
features/export/product-export-builder/export_products_by_textarea.feature
features/import/import_families.feature
src/Pim/Component/Catalog/Validator/Constraints/FamilyRequirements.php
src/Pim/Component/Catalog/Validator/Constraints/FamilyRequirementsValidator.php
src/Pim/Component/Catalog/spec/Validator/Constraints/FamilyRequirementsValidatorSpec.php

Actually, you can import a family with a required attribute it is NOT in the attributes list of the family.
This PR fixes this wrong behavior and skip this item with a warning.

[PIM-6127] In the family import, the attributes required should be in the family

---

features/enrich/variant-group/edit_variant_group_attribute_value.feature
features/export/export_products_with_media.feature
features/import/attribute/import_attributes.feature
features/import/attribute/import_identifier.feature
features/import/import_invalid_csv_data.feature
features/import/import_invalid_xlsx_data.feature
features/import/product/import_products_with_invalid_data.feature
features/import/product/import_products_with_media.feature
features/import/product/xlsx/import_products_with_media.feature
features/import/product_variant_group/import_variant_group_values_with_valid_data.feature
features/localization/mass-action/edit_common_attributes.feature
features/mass-action/edit_common_attributes-01.feature
features/mass-action/edit_common_attributes_channel.feature
features/mass-action/edit_common_attributes_images.feature
features/mass-action/edit_common_attributes_metric.feature
features/mass-action/edit_common_attributes_per_families.feature
features/mass-action/select_products_to_mass_edit.feature
features/product/edit_product.feature
features/product/join_a_document_to_a_product.feature
features/product/join_an_image_to_a_product.feature
features/product/remove_product.feature
features/reference-data/mass-action/edit_common_attributes.feature
features/reference-data/variant-group/edit_variant_group_attribute_value.feature
features/update/copy_metric.feature
features/update/set_metric.feature
src/Pim/Component/Catalog/Updater/AttributeUpdater.php

Since the API, we can't pass unknown properties in the updaters. In this case, it throws an exception.
A lot of behats use legacy properties or a a syntax that is not accepted anymore.
For example "metric family" instead of "metric_family".
This PR fix them.
| Added …

Fix the attribute fixtures and behats due to property validation in attribute updater

---

CHANGELOG-1.7.md
features/import/import_families.feature
src/Pim/Bundle/CatalogBundle/Resources/config/validation/family.yml
src/Pim/Bundle/CatalogBundle/Resources/config/validators.yml
src/Pim/Component/Catalog/Validator/Constraints/FamilyAttributeAsLabel.php
src/Pim/Component/Catalog/Validator/Constraints/FamilyAttributeAsLabelValidator.php
src/Pim/Component/Catalog/spec/Validator/Constraints/FamilyAttributeAsLabelValidatorSpec.php

Prevent:
- import a family with an attribute_as_label not present in the attributes list
- import a family with an attribute_as_label not identifier nor text type

[PIM-6125] Add validator for family attribute_as_label

---

features/product/filtering/filter_products_per_option_fields.feature
src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/AttributeOptionRepository.php

This is a similar fix to #5639.
Caused by #5387 (but case wasn't cover by behats)
When filtering a grid with attribute options, then reloading the grid, the attribute options weren't display anymore because Repository was looking only for ids.
Now it looks for code when asked. …

PIM-6150: fix AttributeOptionRepository to correctly handle codes and ids

---

features/Context/AssertionContext.php
features/datagrid/datagrid_views.feature
features/product/filtering/reset_product_filters.feature
src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filter/product_scope-filter.js
src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid/action/reset-collection-action.js
src/Pim/Bundle/DataGridBundle/Resources/views/macros.html.twig

This PR solves 2 problems about the "Reset" button on the grid:
- It sets the scope to "All", which has no sense
- When you're on a view, it resets filters, but not to the initial state of the view

AMS-175: reset button keeps view filters & doesn't reset scope

---

CHANGELOG-1.6.md
features/import/product/import_products_with_invalid_data.feature
src/Pim/Bundle/ConnectorBundle/Resources/translations/messages.en.yml
src/Pim/Component/Connector/Archiver/AbstractInvalidItemWriter.php
src/Pim/Component/Connector/Reader/File/Csv/Reader.php
src/Pim/Component/Connector/Reader/File/Xlsx/Reader.php

When you import a file with the wrong column count:
- the error was not translated
- path in the error was missing
- it raises a fatal error when invalid item file was written
This PR fix all of this.

PIM-6152: Fix fatal error on import in case of wrong column count

---

src/Pim/Bundle/ApiBundle/Controller/Rest/AttributeController.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Rest/Attribute/CreateAttributeIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Rest/Category/CreateCategoryIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Rest/Category/PartialUpdateCategoryIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Rest/Family/CreateFamilyIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Rest/Family/PartialUpdateFamilyIntegration.php
src/Pim/Bundle/CatalogBundle/Entity/AssociationType.php
src/Pim/Bundle/CatalogBundle/Entity/AttributeGroup.php
src/Pim/Bundle/CatalogBundle/Entity/Category.php
src/Pim/Bundle/CatalogBundle/Entity/Family.php
src/Pim/Bundle/CatalogBundle/Entity/Group.php
src/Pim/Bundle/CatalogBundle/Entity/GroupType.php
src/Pim/Bundle/CatalogBundle/Resources/config/validation/attribute.yml
src/Pim/Bundle/CatalogBundle/Resources/config/validation/category.yml
src/Pim/Bundle/CatalogBundle/Resources/config/validation/family.yml
src/Pim/Bundle/CatalogBundle/Resources/config/validators.yml
src/Pim/Component/Catalog/Model/AbstractAttribute.php
src/Pim/Component/Catalog/Validator/Constraints/Locale.php
src/Pim/Component/Catalog/Validator/Constraints/LocaleValidator.php
src/Pim/Component/Catalog/spec/Validator/Constraints/LocaleSpec.php
src/Pim/Component/Catalog/spec/Validator/Constraints/LocaleValidatorSpec.php

This PR resolve : 
- a fatal exception when you specified a locale which is empty (dedicated commit).
I've fixed that in every labelizable entities because it's always the same logic to get the translation, and so, always the same error.
For exampbe, before the fix, this request raised an error 500 : 
```
{
"code": "category",
"parent": null,
"labels": {
"": 12
}
}
```
-It checks that the locale associated to the label exists when you create an entity
For the moment, it's checked only in entities handled by …

Api 106 : check locales key for the creation/updates of the labels in the API

---

src/Pim/Bundle/ApiBundle/Controller/Rest/AttributeController.php
src/Pim/Bundle/ApiBundle/Controller/Rest/AttributeOptionController.php
src/Pim/Bundle/ApiBundle/Resources/config/controllers.yml
src/Pim/Bundle/ApiBundle/Resources/config/routing/attribute.yml
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Rest/AttributeOption/CreateAttributeOptionIntegration.php
src/Pim/Bundle/CatalogBundle/Resources/config/validation/attribute.yml
src/Pim/Component/Catalog/Updater/AttributeOptionUpdater.php
src/Pim/Component/Catalog/Validator/Constraints/AttributeTypeForOptionValidator.php
src/Pim/Component/Catalog/spec/Updater/AttributeOptionUpdaterSpec.php
src/Pim/Component/Catalog/spec/Validator/Constraints/AttributeTypeForOptionValidatorSpec.php

Create a new attribute option
https://akeneo.atlassian.net/browse/API-29

API-29: Create a new attribute option

---

tests/ConnectionCloser.php
tests/TestCase.php

Currently there is a memory leak with our integration tests. 
When we launch a test with phpunit, Symfony boot a kernel and keep the container in property `$container`.
When a test is finished, the kernel is shutdown and `$container` set to null. This operation is repeated on each test.
Problem with our current implementation is we created our own `$container` where we kept all containers in memory (we saw it with [php-meminfo](https://github.com/BitOne/php-meminfo)). So for 444 tests, we had 444 containers, 444 unit of work, etc \o/
Other baby fix: we launch now integration tests with `debug = false` (we save ~500Mo of memory)
About `gc_collect_cycles`, I don't know why we have to call it explicitly to save so …

Reduce memory leak with integration tests

---

features/datagrid/datagrid_views.feature
src/Pim/Bundle/DataGridBundle/Controller/Rest/DatagridViewController.php
src/Pim/Bundle/EnrichBundle/Resources/public/js/grid/view-selector.js

Since PIM-6058, a user can use a view created by another user to set as his default view.
If the custom view is deleted, it was just broken.
Now we fallback on the grid default view.

AMS-176: fallback on default view if working view has been deleted

---

app/config/security.yml
src/Oro/Bundle/NavigationBundle/Resources/config/oro/routing.yml
src/Oro/Bundle/SecurityBundle/Acl/Voter/AclVoter.php
src/Pim/Bundle/ApiBundle/DependencyInjection/PimApiExtension.php
src/Pim/Bundle/ApiBundle/Resources/config/security.yml
src/Pim/Bundle/ApiBundle/Security/ActionAclVoter.php
src/Pim/Bundle/ApiBundle/tests/integration/ApiTestCase.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/AbstractProductTestCase.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Token/GetAccessTokenIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Token/RefreshTokenIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Security/AuthorizationIntegration.php
tests/Configuration.php
tests/DatabasePurger.php
tests/catalog/technical/acl.sql
tests/catalog/technical/users.csv

This PR adds an access control on the `/api/` URL pattern. It ensures that users have the "overrall_api_access" ACL granted for their role.
Since it's the first time (I guess) that we need to check ACLs not linked to any Oro annotation so early in the app (we already did but not inside the security itself) some modifications were needed inside Oro ACL implementation.
See the description in the new voter to have more info.
| …

API-93: Check API overall access

---

features/Context/AssertionContext.php
src/Pim/Bundle/EnrichBundle/Resources/public/js/formatter/date-formatter.js

This PR fixes 2 small things:
- Properly clean backslashes for the "I should not see the text" (copy paste from "I should see the text)
- Don't set value to the fake datepicker of the DateFormatter if the value can't be properly parsed by the Bootstrap Datepicker. This is to fix all the `WARNING: Encountered a JS error: 'TypeError: d is null'` we had in some behats.
| …

Small fixes

---

CHANGELOG-1.6.md
src/Pim/Component/Catalog/Comparator/Attribute/NumberComparator.php

When removing a numeric value in the PEF, it might not work and leave the previous value. This was caused by a typo and worked because of a silent Warning PHP Message:
```php
$originals = ['locale' => null, "scope" => null, "data" => 2];
var_dump(null === $originals['data']['data']);
// bool(true)
$originals = ['locale' => null, "scope" => null, "data" => '2'];
var_dump(null === $originals['data']['data']);
// PHP Warning:  Illegal string offset 'data' in /home/acme/test.php on line 9
// PHP Stack trace:
// PHP   1. {main}() /home/acme/test.php:0
// bool(false)
```
| …

PIM-6159: Fix number comparator when removing numeric value in the PEF

---

app/config/security.yml
src/Oro/Bundle/SecurityBundle/EventListener/ControllerListener.php
src/Oro/Bundle/SecurityBundle/Exception/AccessDeniedException.php
src/Pim/Bundle/ApiBundle/Controller/ChannelController.php
src/Pim/Bundle/ApiBundle/Controller/Rest/AttributeController.php
src/Pim/Bundle/ApiBundle/Controller/Rest/AttributeOptionController.php
src/Pim/Bundle/ApiBundle/Controller/Rest/CategoryController.php
src/Pim/Bundle/ApiBundle/Controller/Rest/FamilyController.php
src/Pim/Bundle/ApiBundle/Resources/config/security.yml
src/Pim/Bundle/ApiBundle/Resources/translations/messages.en.yml
src/Pim/Bundle/ApiBundle/Security/AccessDeniedHandler.php
src/Pim/Bundle/ApiBundle/tests/integration/ApiTestCase.php
src/Pim/Bundle/ApiBundle/tests/integration/Security/AuthorizationIntegration.php
src/Pim/Bundle/UserBundle/Resources/views/Role/update.html.twig
src/Pim/Bundle/UserBundle/Twig/AclGroupsExtension.php
src/Pim/Bundle/UserBundle/spec/Twig/AclGroupsExtensionSpec.php
tests/catalog/technical/acl.sql
tests/catalog/technical/users.csv

Apply permissions on each entity type (attributes, categories, etc.).
Not sure about how error messages are built in the AccessDeniedHandler, it looks not very robust.
Another solution would be to set hardcoded messages in controllers and access it via reflection. Let me know what you think. (edit: fixed with Doctrine Inflector)
This PR also contains a fix of the permissions edit form (inside the role form).
| …

API-101: Control access to a resource via ACLs

---

app/config/pim_parameters.yml

This parameter was used prior to have a background job to execute mass edit operations.

Remove mass edit limit since it's now a background job

---

src/Pim/Bundle/ApiBundle/Controller/LocaleController.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Locale/FilterLocaleIntegration.php

This PR allows to filter on locales through the API. There is only one filter available and it concerns activated locales.
| Review and 2 GTM                  | In progress
| …

API-76: Adds filtering on locales for API

---

Jenkinsfile

`php-cs-fixer` is provided by the dependencies of `akeneo/php-decoupling-detector`.
Rather than installing `php-cs-fixer` it during the CI build to have the 2.x version, it has been updated in  `akeneo/php-decoupling-detector` and can now be used directly.

Use required php-cs-fixer

---

CHANGELOG-1.7.md
features/Context/AssertionContext.php
features/Context/Page/Base/Form.php
features/export/product-export-builder/show_tooltips_and_errors.feature
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/job_instance/csv_base_export_edit.yml
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/job_instance/csv_base_export_show.yml
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/job_instance/csv_base_import_edit.yml
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/job_instance/csv_base_import_show.yml
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/job_instance/csv_product_export_edit.yml
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/job_instance/csv_product_export_show.yml
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/job_instance/csv_product_import_edit.yml
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/job_instance/csv_product_import_show.yml
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/job_instance/xlsx_base_export_edit.yml
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/job_instance/xlsx_base_export_show.yml
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/job_instance/xlsx_base_import_edit.yml
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/job_instance/xlsx_base_import_show.yml
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/job_instance/xlsx_product_export_edit.yml
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/job_instance/xlsx_product_export_show.yml
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/job_instance/xlsx_product_import_edit.yml
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/job_instance/xlsx_product_import_show.yml
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/job_instance/yml_base_export_edit.yml
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/job_instance/yml_base_export_show.yml
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/job_instance/yml_base_import_edit.yml
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/job_instance/yml_base_import_show.yml
src/Pim/Bundle/EnrichBundle/Resources/public/templates/export/common/edit/field/field.html
src/Pim/Bundle/EnrichBundle/Resources/public/templates/export/common/edit/field/text.html
src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml

On Import/Export builder the tooltips and errors validation messages were not well rendering, this PR fix the previously presented issues.
Q                                 | A

PIM-6161: Fix tooltips and validation errors rendering on Import/Export builder

---

app/config/security.yml
src/Pim/Bundle/ApiBundle/Controller/AttributeController.php
src/Pim/Bundle/ApiBundle/Controller/AttributeOptionController.php
src/Pim/Bundle/ApiBundle/Controller/CategoryController.php
src/Pim/Bundle/ApiBundle/Controller/ChannelController.php
src/Pim/Bundle/ApiBundle/Controller/FamilyController.php
src/Pim/Bundle/ApiBundle/Controller/RootEndpointController.php
src/Pim/Bundle/ApiBundle/Resources/config/controllers.yml
src/Pim/Bundle/ApiBundle/Resources/config/routing.yml
src/Pim/Bundle/ApiBundle/Resources/config/routing/attribute.yml
src/Pim/Bundle/ApiBundle/Resources/config/routing/category.yml
src/Pim/Bundle/ApiBundle/Resources/config/routing/channel.yml
src/Pim/Bundle/ApiBundle/Resources/config/routing/endpoint.yml
src/Pim/Bundle/ApiBundle/Resources/config/routing/family.yml
src/Pim/Bundle/ApiBundle/tests/integration/Controller/RootEndpointIntegration.php

Add a root endpoint to help userw to discover all routes in the API. …

API-77: add root endpoint on API

---

src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/CreateProductIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Rest/Attribute/CreateAttributeIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Rest/Category/CreateCategoryIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Rest/Family/CreateFamilyIntegration.php
src/Pim/Bundle/CatalogBundle/Resources/config/validation/attribute.yml
src/Pim/Bundle/CatalogBundle/Resources/config/validation/category.yml
src/Pim/Bundle/CatalogBundle/Resources/config/validation/family.yml
src/Pim/Component/Api/Normalizer/Exception/ViolationNormalizer.php
src/Pim/Component/Api/spec/Normalizer/Exception/ViolationNormalizerSpec.php
src/Pim/Component/Catalog/Updater/Setter/TextAttributeSetter.php
src/Pim/Component/Catalog/Validator/ConstraintGuesser/MetricGuesser.php
src/Pim/Component/Catalog/Validator/Constraints/Locale.php
src/Pim/Component/Catalog/Validator/Constraints/LocaleValidator.php
src/Pim/Component/Catalog/Validator/Constraints/RangeValidator.php
src/Pim/Component/Catalog/spec/Updater/Setter/TextAttributeSetterSpec.php
src/Pim/Component/Catalog/spec/Validator/ConstraintGuesser/MetricGuesserSpec.php

Sorry, there is some baby fix in this PR, but when I added tests, I found some bugs :)
The point `1` is the initial PR, points `2` & `3` concern bugs fix.
1) Currently, when the standard format is submitted but contain errors, fields returned are doctrine fields (eg. `metricFamily`), not standard format fields (eg. `metric_mamily`).
This PR fix it, it's not an ideal solution as we could have some fields in doctrine which are completely different in the standard format, but for the moment, it's work...
About the propertyPath added in LocaleValidator, without it when a label is wrong, previous message was `translations[0].locale` which means nothing for a user.
I founded this way, but if you have a better solution, I …

API-110: transform doctrine fields into standard format fields

---

src/Pim/Bundle/ApiBundle/Controller/CategoryController.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Rest/Category/PartialUpdateCategoryIntegration.php

API-30: catch exception from gedmo when a category is updated

---

src/Pim/Bundle/EnrichBundle/Resources/public/js/grid/view-selector-current.js

Allow an override to detect changes between grid state & view.

AMS-191: use a method to detect filters changes

---

Jenkinsfile

`php-cs-fixer` 2.0 is required by `akeneo/php-coupling-detector`, so no need to perform a global requirement anymore.

Remove useless composer global require

---

src/Pim/Bundle/EnrichBundle/Resources/views/Attribute/_js-handler.html.twig

Fixes a regression introduced by https://github.com/akeneo/pim-community-dev/pull/5727.

PIM-6167: Fix regression on attribute form: type must be readonly

---

src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Filter/PriceFilter.php
src/Pim/Bundle/CatalogBundle/spec/Doctrine/ORM/Filter/PriceFilterSpec.php
src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Price/LocalizableFilterIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Price/LocalizableScopableFilterIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Price/PriceFilterIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Price/ScopableFilterIntegration.php

PIM-6153: Allow to send empty array in PriceFilter value for EMPTY and NOT EMPTY operators

---

Jenkinsfile
tests/TestCase.php

This PR prepare the field to run the integration tests on our new Jenkins CI 1.2 both in ORM and ODM.
As for now, they are broken in ODM, their launch is commented in the Jenkinsfile so this PR can be merged. It is indeed needed for the EE PR, that works.
Integration tests will be fixed on ODM in another PR.
It also sets the date/time zone on "Europe/Paris" (because it is what was expected by the CI). This way, the tests will run the same on a system with a different configured date/time zone. …

Prepare to run integration tests on both ORM and ODM

---

CHANGELOG-1.7.md
features/Context/Page/Base/Form.php
features/Context/WebUser.php
features/Pim/Behat/Context/Domain/Enrich/AttributeTabContext.php
features/product/completeness/display_completeness.feature
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/product_edit.yml
src/Pim/Bundle/EnrichBundle/Resources/config/requirejs.yml
src/Pim/Bundle/EnrichBundle/Resources/public/js/fetcher/locale-fetcher.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/attributes.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/attributes/attribute-group-selector.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/manager/attribute-manager.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/manager/product-manager.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/manager/variant-group-manager.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/field/price-collection-field.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/attributes/completeness.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/locale-switcher.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/panel/completeness.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/save.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/provider/to-fill-field-provider.js
src/Pim/Bundle/EnrichBundle/Resources/public/templates/form/tab/attributes/attribute-group-selector.html
src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/field/field.html
src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/field/text.html
src/Pim/Bundle/UIBundle/Resources/public/less/components/Badge.less

This PR add a little marker on the pef to inform the user that he have to fill the fields of the product to complete it.
| Migration …

AMS-27: add mark on uncomplete fields

---

src/Oro/Bundle/NavigationBundle/Entity/Builder/ItemFactory.php
src/Oro/Bundle/SecurityBundle/Tests/Unit/Acl/Cache/FilesystemCacheTest.php
src/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/QueryGenerator/AttributeDeletedQueryGenerator.php
src/Pim/Bundle/DataGridBundle/Resources/public/js/multiselect-decorator.js

All grid filter current value span have class 'filter-criteria-hint' , add this on multiselect filter

PIM-5448: Add class on multiselect filter view presentation

---

src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Boolean/BooleanFilterIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/CategoryFilterIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Date/DateFilterIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/DateTimeFilterIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/FamilyFilterIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/GroupsFilterIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Media/MediaFilterIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Metric/MetricFilterIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Number/NumberFilterIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Option/OptionFilterIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Options/OptionsFilterIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Price/PriceFilterIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/String/StringFilterIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/PQB/ProductQueryBuilderIntegration.php

- Add an integration test to check if the filter throws an error when an unsupported operator is given
- Add an integration test checking that complex pqb queries (multiple filters at once) is consistent

Tip 705 add pqb tests

---

features/channel/display_channel_on_datagrid.feature
src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/ChannelRepository.php

Since #5467, we now use UI locale correctly.
Problem is that, if no translation is available for channel label, it's silently failing on the grid and the scope selector is broken.
This PR makes consistent behavior of label of scope like other entities: if no translation is available for the UI locale, it fallbacks on the code.
| …

Display channel code if no translation available in the UI Locale

---

features/Context/WebUser.php
features/Pim/Behat/Context/NavigationContext.php
features/dashboard/loading_message.feature
src/Oro/Bundle/ConfigBundle/Controller/Rest/ConfigurationController.php
src/Pim/Bundle/UIBundle/DependencyInjection/Configuration.php

On a fresh new 1.7 install, go to System/Configuration and under menu Loading Messages, you’ll see that the yes/no is set on "No" but the Loading messages do appear.
The feature should be deactivated by default when the PIM is installed.
| Review and 2 GTM                  | 1/2

PIM-6151: disable the loading messages by default

---

src/Pim/Bundle/ApiBundle/Controller/ProductController.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/SuccessListProductIntegration.php

Remove the sort on identifier on product list to improve performances (It was quite naive/very stupid to do that :p). 
With the sort, it take 20 secondes to get 10 products (on medium catalog). Without, only 1 seconde :)
About the sort on integration test, there is a diff between ORM & Mongo, products are not sorted as the same way... To have tests green in two storages, I have to sort the result. …

API-114: remove sort on identifier to improve performance

---

src/Pim/Bundle/CatalogBundle/Resources/translations/validators.en.yml

It fixes the YAML (not very well parsed by the Crowdin parser)
See this : https://crowdin.com/translate/akeneo/all/en-fr#q=%25extensions

Fix translation for Crowdin

---

src/Pim/Bundle/ApiBundle/tests/integration/ApiTestCase.php
tests/DatabasePurger.php
tests/DatabaseSchemaHandler.php
tests/FixturesLoader.php
tests/TestCase.php

As a first step to make our integration tests independent, I propose, that at the beginning of each test (except if you decided to put the option `purgeDatabaseForEachTest` to false):
- really drop the whole database schema
- recreate the database schema 
This is just a first step, to be able to merge https://github.com/akeneo/pim-community-dev/pull/5775. With that PR, tests will be slower for sure. But this is just temporary.
What we could do after the 1.7 release is setting up a 1 day squad on this topic. Its goal would be:
- be able to launch really independent tests (with `--process-isolation` for instance, or something else). For that, we need to fix our tests.
- optimize the loading of the database which is very time consuming (see the ideas of Juju and Marie) 
- run the integration …

TIP-694: isolate integration test files

---

Jenkinsfile
src/Pim/Bundle/CatalogBundle/tests/integration/Completeness/AbstractCompletenessIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/Completeness/AbstractCompletenessPerAttributeTypeIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/Completeness/AttributeType/BooleanAttributeTypeCompletenessIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/Completeness/AttributeType/DateAttributeTypeCompletenessIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/Completeness/AttributeType/FileAttributeTypeCompletenessIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/Completeness/AttributeType/IdentifierAttributeTypeCompletenessIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/Completeness/AttributeType/ImageAttributeTypeCompletenessIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/Completeness/AttributeType/MetricAttributeTypeCompletenessIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/Completeness/AttributeType/NumberAttributeTypeCompletenessIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/Completeness/AttributeType/OptionAttributeTypeCompletenessIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/Completeness/AttributeType/OptionsAttributeTypeCompletenessIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/Completeness/AttributeType/PriceCollectionAttributeTypeCompletenessIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/Completeness/AttributeType/ReferenceDataMultiAttributeTypeCompletenessIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/Completeness/AttributeType/ReferenceDataSimpleAttributeTypeCompletenessIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/Completeness/AttributeType/TextAttributeTypeCompletenessIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/Completeness/AttributeType/TextareaAttributeTypeCompletenessIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/Completeness/CompletenessForLocalisableAttributeIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/Completeness/CompletenessForNonRequiredAttributeIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/Completeness/CompletenessForScopableAndLocalisableAttributeIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/Completeness/CompletenessForScopableAttributeIntegration.php
src/Pim/Component/Catalog/Validator/AttributeValidatorHelper.php
src/Pim/Component/Catalog/spec/Validator/AttributeValidatorHelperSpec.php
src/Pim/Component/Catalog/tests/integration/Normalizer/Standard/CategoryIntegration.php
src/Pim/Component/Catalog/tests/integration/Normalizer/Standard/DateTimeIntegration.php
tests/Configuration.php
tests/FixturesLoader.php

(we'll squash commits before merging)
Add integration tests regarding the Completeness feature, it takes into account how the completeness is calculated given:
- the available attribute types in the PIM
- the localizable specificity of an attribute (as well as locale specific)
- the scopable specificity of an attribute
- the locale/scope specificities mixed
- the non required attributes do not influence the calculation
The goal is to be able to refactor the completeness without any fear of breaking something.
| Added integration …

TIP-694: Add completeness integration tests

---

src/Pim/Bundle/VersioningBundle/Normalizer/Flat/VariantGroupNormalizer.php
src/Pim/Bundle/VersioningBundle/spec/Normalizer/Flat/VariantGroupNormalizerSpec.php
src/Pim/Component/Catalog/Normalizer/Standard/VariantGroupNormalizer.php

When you install the PIM, a warning is raised when it generates the autoloader file.
There were two classes with the same name in the spec : `VariantGroupNormalizerSpec` and `GroupNormalizerSpec`.
Actually, the VariantGroupNormalizer was not tested correctly for the versioning.
This PR fixes that problem.
Moreover, I've deleted a function that was not used.
| Q …

Warning when installing the 1.7 version : fix variant groups spec 

---

src/Pim/Component/Connector/Processor/Denormalization/AbstractProcessor.php

Denormalization processors are built in a way that allow us to use them without setting any step execution in it (as it's done by a setter and not passed in the constructor).
However there is still some parts that expect `$this->stepExecution` to be always set. As a result, when we use processors inside Behat contexts for example, we can get fatal errors.
This PR fixes this case. Of course the way to go would be to redesign the batch component, this is the easiest fix without breaking everything. …

Avoid fatal error in processor if step execution is not set

---

Jenkinsfile

Currently, our CSS+JS tests are run with the command `grunt --force`. This allows us to run all the tests even if there are errors. But the problem is the CI is always green even when there are errors, so this is not good!
In this PR, the tests are only run with the command `grunt`. It will be up to the developer to run all the tests locally to ensure everything is fixed.
I also remove the multiple runs of `php-cs-fixer` to keep only one, with PHP 7 (fastest execution). …

Fix use of "grunt" and "php-cs-fixer" on CI

---

src/Pim/Bundle/ApiBundle/Controller/AttributeController.php
src/Pim/Bundle/ApiBundle/Controller/AttributeOptionController.php
src/Pim/Bundle/ApiBundle/Controller/CategoryController.php
src/Pim/Bundle/ApiBundle/Controller/ChannelController.php
src/Pim/Bundle/ApiBundle/Controller/FamilyController.php
src/Pim/Bundle/ApiBundle/Controller/LocaleController.php
src/Pim/Bundle/ApiBundle/Controller/ProductController.php
src/Pim/Bundle/ApiBundle/Doctrine/ORM/Repository/ApiResourceRepository.php
src/Pim/Bundle/ApiBundle/Doctrine/ORM/Repository/AttributeRepository.php
src/Pim/Bundle/ApiBundle/Resources/config/controllers.yml
src/Pim/Bundle/ApiBundle/Resources/config/routing/attribute.yml
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Rest/AttributeOption/ListAttributeOptionIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/RootEndpointIntegration.php
src/Pim/Component/Api/Hal/HalResource.php
src/Pim/Component/Api/Pagination/HalPaginator.php
src/Pim/Component/Api/Pagination/PaginatorInterface.php
src/Pim/Component/Api/spec/Hal/HalResourceSpec.php
src/Pim/Component/Api/spec/Pagination/HalPaginatorSpec.php

Api 31 : add get list of attribute options in the API

---

Jenkinsfile

There is a regular problem with integration tests, with the MongoDB and MySQL containers not being destroyed on the Jenkins slaves, making next builds failing.
This PR make sure both MySQL and MongoDB container names are unique to each builds to avoid this problem ever again.
Correct cleaning of the slaves will be done in another PR. …

Make DB container names unique in Jenkinsfile

---

CHANGELOG-1.7.md
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/job_instance/csv_base_import_edit.yml
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/job_instance/csv_base_import_show.yml
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/job_instance/csv_product_export_edit.yml
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/job_instance/csv_product_export_show.yml
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/job_instance/csv_product_import_edit.yml
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/job_instance/csv_product_import_show.yml
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/job_instance/xlsx_base_export_show.yml
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/job_instance/xlsx_base_import_edit.yml
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/job_instance/xlsx_base_import_show.yml
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/job_instance/xlsx_product_export_edit.yml
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/job_instance/xlsx_product_export_show.yml
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/job_instance/xlsx_product_import_edit.yml
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/job_instance/xlsx_product_import_show.yml
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/job_instance/yml_base_export_show.yml
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/job_instance/yml_base_import_edit.yml
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/job_instance/yml_base_import_show.yml

This PR removes the unused parameters from import. …

PIM-6210: fix unused fields on import profiles

---

Jenkinsfile

Due to stability issues in PHP 7.1 (mostly on new integration tests on completeness) we try to deactivate it temporarily and run it only in 5.6 and 7.0.

Deactivate integration tests for PHP 7.1

---

src/Pim/Bundle/EnrichBundle/Controller/Rest/ProductController.php
src/Pim/Bundle/EnrichBundle/Resources/config/controllers.yml
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/attributes/completeness.js

Put completeness in product meta, to avoid a fetch after product loading

Put completeness in product meta, to avoid a fetch after product loading

---

src/Pim/Bundle/UIBundle/Resources/public/less/components/Badge.less

PIM-6229: Fix badge orange color

---

CHANGELOG-1.7.md
features/Context/DataGridContext.php
features/Pim/Behat/Decorator/Page/GridCapableDecorator.php
features/datagrid/datagrid_views.feature
src/Pim/Bundle/EnrichBundle/Resources/public/js/grid/view-selector-remove-view.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/grid/view-selector-save-view.js

Bug:  You can now edit or delete another user's view (it does not have to be set as your grid default view).
FIX: only view's creator can edit or delete their views.

PIM-6200: Fix remove and save buttons on view selector

---

src/Pim/Bundle/ApiBundle/Controller/AttributeOptionController.php
src/Pim/Bundle/ApiBundle/Resources/config/routing/attribute.yml
src/Pim/Bundle/ApiBundle/tests/integration/Controller/AttributeOption/PartialUpdateAttributeOptionIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Rest/AttributeOption/CreateAttributeOptionIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Rest/AttributeOption/GetAttributeOptionIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Rest/Category/PartialUpdateCategoryIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/RootEndpointIntegration.php
src/Pim/Bundle/CatalogBundle/Resources/config/validation/attribute.yml
src/Pim/Component/Catalog/Updater/AttributeOptionUpdater.php
src/Pim/Component/Catalog/Validator/Constraints/AttributeTypeForOption.php
src/Pim/Component/Catalog/Validator/Constraints/AttributeTypeForOptionValidator.php
src/Pim/Component/Catalog/spec/Updater/AttributeOptionUpdaterSpec.php
src/Pim/Component/Catalog/spec/Validator/Constraints/AttributeTypeForOptionValidatorSpec.php

Add attribute option PATCH in Api.
Some changes have been done in the Post method too :
The attribute is optional in the body in patch and post, because it's already provided in the url.
I've changed every attribute option tests (GET, POST, PATCH) to assert on JSON instead of PHP array, in a specific commit. …

Api 36 : add attribute option patch in api

---

src/Pim/Bundle/ApiBundle/tests/integration/Controller/Attribute/CreateAttributeIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Attribute/PartialUpdateAttributeIntergration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/AttributeOption/CreateAttributeOptionIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/AttributeOption/PartialUpdateAttributeOptionIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Category/CreateCategoryIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Category/PartialUpdateCategoryIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Family/CreateFamilyIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Family/PartialUpdateFamilyIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/CreateProductIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/PartialUpdateProductIntegration.php
src/Pim/Component/Api/Normalizer/Exception/ViolationNormalizer.php
src/Pim/Component/Api/spec/Normalizer/Exception/ViolationNormalizerSpec.php

Our beloved product owner wants to change "field" to "property" in error response :)
| Micro …

API-123: change "field" to "property" in error response

---

STANDARD_FORMAT.md
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Media/CreateMediaFileIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/CreateProductIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/GetProductIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/PartialUpdateProductIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/AbstractFilterTestCase.php
src/Pim/Component/Api/tests/integration/Normalizer/ProductNormalizerIntegration.php
src/Pim/Component/Catalog/Normalizer/Standard/Product/AssociationsNormalizer.php
src/Pim/Component/Catalog/spec/Normalizer/Standard/Product/AssociationsNormalizerSpec.php
src/Pim/Component/Catalog/tests/integration/Normalizer/Standard/ProductStandardIntegration.php
tests/catalog/technical_sql/200_products.json

Fix integration tests on mongo:
- I fixed "updated" & "created" dates which were differents between mongo & orm fixtures files 
- Product values were not sorted in the same way in mongo. I added a `ksort` on the expected result and the result to work around the pb
- In the product standard format, associations were not consistent. When a product had no association, we returned:
```
"associations" => []
```
but when an association was added, we returned:
```
"associations": [
"PACK" => ["groups" => [], "products" => []],
"SUBSTITUTION" => ["groups" => [], "products" => []],
"UPSELL" => ["groups" => [], "products" => ["foo"]],
"PACK" => ["groups" => [], "products" => []]
]
```
This behavior can change between orm & …

Fix integration tests in mongo 

---

src/Pim/Bundle/ApiBundle/Resources/config/security.yml
src/Pim/Bundle/ApiBundle/Security/OAuth2.php

FosOAuthBundle returns this structure when there is an error on connection:
```
{
"error": "invalid_grant",
"error_description": "The access token provided has expired."
}
```
It does not match with our standard, so I catch the OAuth2AuthenticateException to return:
```
{
"code": 422,
"message": "The access token provided is invalid."
}
```
| …

Change response on connection error

---

app/config/pim_parameters.yml
src/Pim/Bundle/ApiBundle/Controller/AttributeController.php
src/Pim/Bundle/ApiBundle/Controller/CategoryController.php
src/Pim/Bundle/ApiBundle/Controller/FamilyController.php
src/Pim/Bundle/ApiBundle/Controller/ProductController.php
src/Pim/Bundle/ApiBundle/DependencyInjection/Configuration.php
src/Pim/Bundle/ApiBundle/DependencyInjection/PimApiExtension.php
src/Pim/Bundle/ApiBundle/Resources/config/api.yml
src/Pim/Bundle/ApiBundle/Resources/config/controllers.yml
src/Pim/Bundle/ApiBundle/Resources/config/routing/attribute.yml
src/Pim/Bundle/ApiBundle/Resources/config/routing/category.yml
src/Pim/Bundle/ApiBundle/Resources/config/routing/family.yml
src/Pim/Bundle/ApiBundle/Resources/config/routing/product.yml
src/Pim/Bundle/ApiBundle/Resources/config/stream.yml
src/Pim/Bundle/ApiBundle/Stream/StreamResourceResponse.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Attribute/PartialUpdateListAttributeIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Category/PartialUpdateListCategoryIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Family/PartialUpdateListFamilyIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/PartialUpdateListProductIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/PartialUpdateProductIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/RootEndpointIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/EventSubscriber/CheckHeadersRequestSubscriberIntegration.php
src/Pim/Bundle/EnrichBundle/Resources/config/bundles/fos_rest.yml

In order to update a list of products in one request, a PATCH on a list of products has been added in this PR.
Each line of the body should represent a standardized product in JSON.
```
{"identifier":"id_1"}
{"identifier":"id_2"}
```
Then, each line is processed one by one and forwarded in the unitary PATCH.
The response of each subrequest is returned line by line (and streamed) : 
```
{"code" :201, "line": 1, "identifier": "id_1"}
{"code" :201, "line": 2, "identifier": "id_2"}
```
Initially, there was no …

Api 112 : add a patch operation on a list of products/categories/attributes/families

---

features/Context/Page/Attribute/Creation.php
features/Context/WebUser.php
features/attribute/option/edit_attribute_options_02.feature
src/Pim/Bundle/EnrichBundle/Resources/public/templates/attribute-option/edit.html

To be consistent with API (seen with POs), it's not allowed anymore to edit code of attributeoptions via UI.
Validation on backend is already done by @ahocquard .

Disable AttributeOption code edition

---

src/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/Filter/OptionFilter.php
src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Filter/OptionFilter.php
src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Filter/OptionsFilter.php
src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Filter/StringFilter.php
src/Pim/Bundle/ReferenceDataBundle/Doctrine/ORM/Filter/ReferenceDataFilter.php

InvalidPropertyException::expectedFromPreviousException expects previous exception as 3rd argument, fixed cases passes it as first
Discovered this issue using the web API, i got 500 server error due to,
``̀`
[2017-03-13 12:44:22] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: Argument 3 passed to Akeneo\Component\StorageUtils\Exception\InvalidPropertyException::expectedFromPreviousException() must be an instance of Exception, string given, called in /home/nico/git/pim-ce-17-orm/src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Filter/OptionFilter.php on line 67" at /home/nico/git/pim-ce-17-orm/src/Akeneo/Component/StorageUtils/Exception/InvalidPropertyException.php line 224 {"exception":"[object] …

TIP-322: fix wrong arguments order for InvalidPropertyException::expectedFromPreviousException calls

---

src/Pim/Bundle/ApiBundle/Controller/ProductController.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/ErrorListProductIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/SuccessListProductIntegration.php

A couple of issues,
First,
```
./get_products --host http://pim-ce-17-orm.local/app_dev.php --accesstoken ODg5Yjg4NzhhY2IzODA4NDRhMzk2NjdhZmE0YmNiMDExZmUyYzdiODIzZDc2NjZlZDg0OWVkODFjYmUwOWViZg --search '{"categories":[{"operator":"IN","value":["winter_collection"]}]}'
if winter_collection does not exists the response is the following one,
{"code":500,"message":"Internal Server Error"}
[2017-03-13 14:35:40] request.CRITICAL: Uncaught PHP Exception Pim\Component\Catalog\Exception\ObjectNotFoundException: …
```

Fix filters on products list

---

src/Pim/Bundle/CatalogBundle/spec/Helper/LocaleHelperSpec.php

This PR is for experimental purposes. It removes an unused parameter from the test function `it_provides_current_locale` …

TIP-717: Remove unused parameter from it_provides_current_locale

---

CHANGELOG-1.7.md
src/Pim/Bundle/EnrichBundle/Resources/public/js/variant-group/form/no-attribute.js

PIM-6213: remove ticks on variant group form

---

CHANGELOG-1.7.md
features/channel/display_channel_on_datagrid.feature
features/mass-action/edit_common_attributes_scopable_localizable.feature
features/user/edit_user.feature
src/Pim/Bundle/CatalogBundle/Helper/LocaleHelper.php
src/Pim/Bundle/CatalogBundle/spec/Helper/LocaleHelperSpec.php
src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/association_product.yml
src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/product.yml
src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/product_group.yml
src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/product_variant_group.yml
src/Pim/Bundle/EnrichBundle/Resources/views/MassEditAction/product/configure/edit-common-attributes.html.twig

Translate the channel with the catalog locale everywhere in the PIM

PIM-6239: translate scope with catalog locale

---

src/Pim/Bundle/UIBundle/Resources/public/js/pim-formupdatelistener.js

This PR prevents the javascript to console an error if the flash message is missing (but logs a warning on the console)

Show warning instead of an error (if update message missing)

---

CHANGELOG-1.7.md
Jenkinsfile
features/channel/display_channel_on_datagrid.feature
features/import/product/import_products.feature
features/import/product/xlsx/import_products.feature
src/Pim/Bundle/ConnectorBundle/Resources/config/readers.yml
src/Pim/Bundle/ImportExportBundle/Controller/JobProfileController.php
src/Pim/Component/Connector/Reader/File/Csv/ProductAssociationReader.php
src/Pim/Component/Connector/Reader/File/Xlsx/ProductAssociationReader.php
src/Pim/Component/Connector/spec/Reader/File/Csv/ProductAssociationReaderSpec.php
src/Pim/Component/Connector/spec/Reader/File/Xlsx/ProductAssociationReaderSpec.php

When changing the category/group/family headers label on the job profile, the association step is not working anymore cf (https://akeneo.atlassian.net/browse/PIM-6085)

PIM-6085: Fix import association step when custom column header is used.

---

src/Pim/Bundle/UIBundle/Resources/public/less/components/product-edit-form/AssetCollectionField.less

Add missing style for asset collection field rendering on view mode

PIM-6205: Add missing style for asset collection field rendering on view mode

---

CHANGELOG-1.7.md
features/Context/catalog/footwear/attributes.csv
features/export/export_attributes.feature
src/Pim/Component/Catalog/Normalizer/Standard/AttributeNormalizer.php
src/Pim/Component/Catalog/spec/Normalizer/Standard/AttributeNormalizerSpec.php
src/Pim/Component/Connector/ArrayConverter/StandardToFlat/Attribute.php
src/Pim/Component/Connector/spec/ArrayConverter/StandardToFlat/AttributeSpec.php

When you export attribute and reimport it, you got some errors.
Depending on the attribute type I have errors on these properties, for instance for SKU:
wysiwygEnabled: This value should be null.:
decimalsAllowed: This value should be null.:
negativeAllowed: This value should be null.:
As this values are not null but they should be null as they are not using the wysiwyg or decimals values. (like the text attribute)

PIM-6250: fix attribute export

---

spec/Pim/Component/Connector/Writer/Doctrine/VariantGroupWriterSpec.php
src/Pim/Component/Connector/Writer/Doctrine/VariantGroupWriter.php

Use DetachAll for VariantGroups.
It was taking more than 1Gb to process 200 variant groups. Now it is just 200Mb.
* Updated tests.
There is a failing test on the branch 1.5. @nidup

Fix #5941 Objects was not being detached on VariantGroupImport.

---

CHANGELOG-1.7.md
src/Pim/Bundle/UIBundle/Resources/config/assets.yml
src/Pim/Bundle/UIBundle/Resources/public/less/lib/summernote.less

This PR fix Summernote style
Before / After:

PIM-6252: Fix summernote style

---

STANDARD_FORMAT.md

I changed the word array to string in the docs from akeneo api. I changed it because in the template it says the value is a string while in the docs it says it should be an array.
Discussed about this with pierre allard.
| …

Modified array to string for the updated attribute

---

CHANGELOG-1.7.md
features/product/edit_product.feature
src/Pim/Bundle/EnrichBundle/Controller/LocaleController.php
src/Pim/Bundle/EnrichBundle/Controller/Rest/AssociationTypeController.php
src/Pim/Bundle/EnrichBundle/Controller/Rest/ChannelController.php
src/Pim/Bundle/EnrichBundle/Controller/Rest/FamilyController.php

While accessing the PEF, the UI calls rest routes for listing locales, associations, families and more. If there are no permission on this groups it returns a 403.

PIM-6258: fix permission issue

---

CHANGELOG-1.7.md
features/product/edit_product.feature
src/Pim/Bundle/EnrichBundle/Resources/public/js/grid/view-selector.js

This PR fix the way we detect more results for the select2, plus it adds a method to get the "resultsPerPage" attribute to override it in EE.

PIM-6249: correctly load more results from select2 when needed

---

CHANGELOG-1.7.md
src/Oro/Bundle/UserBundle/Resources/config/navigation.yml

Wrong behavior introduced by BEM
We have to remove the hashnav from user menu to avoid glitches. (1.6 was like this)
No need for CI IMHO.

PIM-6265: Fix user menu navigation

---

features/Context/CommandContext.php
features/technical/security.feature

On the current CI, this behat passes but it raises an Exception (which is normal):
Now the CI detects if there is an Exception, so it fails.
To avoid this, we launch the command in background and explicitly wait to test the file.
Pair fixed with @pierallard 💃

Avoid to raise an exception in behats by testing the command in background

---

CHANGELOG-1.7.md
features/mass-action/edit_common_attributes.feature
src/Pim/Bundle/EnrichBundle/Resources/views/MassEditAction/product/configure/edit-common-attributes.html.twig

When the chosen channel doesn't has a scope for the selected locale it was displaying "undefined".
The fix now display the code instead of undefined.

PIM-6240: fix undefined channel on mass edit

---

app/phpunit.xml.dist
tests/TestCase.php

In `ListAttributeIntegration`, tests having a date fail if your php.ini is set with a timezone different from "Europe/Paris".
In a more general way, API tests are coupled to the timezone "Europe/Paris". The timezone for those tests sould be set with "Europe/Paris".
It does not fail on the CI, despite the fact the CI is set with "Etc/Utc", because a previous TestCase already set the time zone of the process with "Europe/Paris".
https://github.com/akeneo/pim-community-dev/blob/master/tests/TestCase.php#L35 …

Use "Europe/Paris" timezone for the integration tests of the API

---

CHANGELOG-1.6.md
features/import/edit_an_import.feature
features/import/product/import_products_with_associations.feature
src/Pim/Bundle/ConnectorBundle/Resources/config/array_converters.yml
src/Pim/Bundle/UIBundle/Resources/views/Form/pim-fields.html.twig
src/Pim/Component/Connector/ArrayConverter/FlatToStandard/Product/AttributeColumnInfoExtractor.php
src/Pim/Component/Connector/spec/ArrayConverter/FlatToStandard/Product/AttributeColumnInfoExtractorSpec.php

If you had a association type with the same code as an attribute the improt process was failing. This PR intent to fix this problem.
| Review and …

PIM-6071: add control on attribute having same code as association type

---

Jenkinsfile
app/phpunit.xml.dist

As the integration tests takes a very long time to run on the CI (almost one hour on PHP 5.6), we try in this PR to split them in smaller suites (the split is still open to discussion and can change), and run them in parallel on the Jenkins docker slaves.
Build result with this Jenkinsfile:
https://core-ci.akeneo.com/blue/organizations/jenkins/akeneo%2Fpim-community-dev/detail/PR-5988/12/pipeline/57
The longest suite is `PIM_Api_Bundle_Controllers_Base_Integration_Test` in PHP 5.6, taking 10 minutes to execute (so this is the time the "integration test" stage take).
Completeness in PHP 7.1 is commented as there is still an issue with it. It will be addressed in another PR.
| Added Specs …

Split integration tests in smaller suites

---

CHANGELOG-1.7.md
features/Context/WebUser.php
features/product/ensure_variant_read_only.feature
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/field/multi-select-field.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/field/simple-select-field.js

This PR updates simple-select-field and multi-select field to hide the 'add an option' buttons for disabled fields.   …

PIM-6071: Hide add option icon for non-editable fields

---

.php_cd.php

- Re-enable / fix coupling detector rules regarding all Akeneo components
- To prevent the introduction of future coupling regression

Fix coupling detector issues & rules for akeneo components

---

features/attribute/option/import_attribute_options.feature
features/import/import_categories.feature
src/Akeneo/Component/Localization/TranslatableUpdater.php
src/Akeneo/Component/Localization/spec/TranslatableUpdaterSpec.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Attribute/CreateAttributeIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Attribute/PartialUpdateAttributeIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/AttributeOption/CreateAttributeOptionIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/AttributeOption/PartialUpdateAttributeOptionIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Category/CreateCategoryIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Category/PartialUpdateCategoryIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Family/PartialUpdateFamilyIntegration.php
src/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/QueryGenerator/FamilyLabelDeletedQueryGenerator.php
src/Pim/Bundle/CatalogBundle/EventSubscriber/MongoDBODM/UpdateNormalizedProductDataSubscriber.php
src/Pim/Bundle/CatalogBundle/Resources/config/doctrine/Attribute.orm.yml
src/Pim/Bundle/CatalogBundle/Resources/config/doctrine/AttributeOption.orm.yml
src/Pim/Bundle/CatalogBundle/Resources/config/doctrine/Category.orm.yml
src/Pim/Bundle/CatalogBundle/Resources/config/doctrine/Family.orm.yml
src/Pim/Bundle/CatalogBundle/Resources/config/storage_driver/doctrine/mongodb-odm.yml
src/Pim/Bundle/CatalogBundle/Resources/config/updaters.yml
src/Pim/Bundle/EnrichBundle/Doctrine/ORM/Repository/AttributeOptionSearchableRepository.php
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/field/multi-select-field.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/field/simple-select-field.js
src/Pim/Component/Catalog/Updater/AttributeOptionUpdater.php
src/Pim/Component/Catalog/Updater/AttributeUpdater.php
src/Pim/Component/Catalog/Updater/FamilyUpdater.php
src/Pim/Component/Catalog/spec/Updater/AttributeOptionUpdaterSpec.php
src/Pim/Component/Catalog/spec/Updater/AttributeUpdaterSpec.php
src/Pim/Component/Catalog/spec/Updater/FamilyUpdaterSpec.php
src/Pim/Component/Connector/ArrayConverter/FlatToStandard/Category.php

Validated by PO :
When you import an empty label or set a label to `null` or "" with the API , it should  delete the label in the database. 
Before this PR, there were different behaviours : sometimes it was impossible to delete labels, sometimes it was possible...
For the moment, only the following entities have been modified (=entities of the API) :
- category
- attributes
- attribute options
- family
Note: the UI does not delete the labels and the behaviour is not very consistent with import/API.
It will …

API-106: Delete labels in the entities of API

---

CHANGELOG-1.7.md
features/Context/ViewSelectorContext.php
features/Pim/Behat/Decorator/Field/Select2Decorator.php
features/enrich/variant-group/display_variant_group.feature
src/Pim/Bundle/EnrichBundle/Resources/public/templates/variant-group/tab/properties/general.html

There was a typo in the "axes" attribute of a variant group.

PIM-6275: Fix variations not visible on Variant Group properties tab

---

CHANGELOG-1.7.md
features/enrich/variant-group/edit_variant_browse_products.feature
src/Pim/Bundle/DataGridBundle/Resources/public/js/pageable-collection.js

When we instanciate a datagrid, we instanciate a new PageableCollection.
It's done [HERE](https://github.com/akeneo/pim-community-dev/blob/1.7/src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid-builder.js#L105) in the `datagrid-builder.js`:
```js
collection = new PageableCollection(this.$el.data('data'), options);
```
The problem is that **a reference to the old `this` of existing `PageableCollection` was kept**, so the state, columns etc... 
When we call `new PageableCollection`, backbone calls `initialize` (see [HERE](https://github.com/akeneo/pim-community-dev/blob/1.7/src/Pim/Bundle/UIBundle/Resources/public/lib/backbone/backbone.js#L561)), that **we must** override to initialize our own stuff, aka **our state of the …

PIM-6283: Correctly reset state of pageable-collection when switching grids

---

CHANGELOG-1.8.md
src/Akeneo/Bundle/BatchBundle/Launcher/SimpleJobLauncher.php
src/Akeneo/Bundle/BatchBundle/Resources/config/services.yml
src/Akeneo/Bundle/BatchBundle/spec/Launcher/SimpleJobLauncherSpec.php

Fix issue #5212 
SimpleJobLauncher use a kernel.logs_dir instead of kernel.root_dir for logs

Use kernel.logs_dir instead of kernel.root_dir in SimpleJobLauncher

---

src/Pim/Bundle/CatalogBundle/Command/CleanProductTemplateCommand.php
src/Pim/Bundle/EnrichBundle/Controller/JobTrackerController.php
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/channel/edit.yml
src/Pim/Bundle/EnrichBundle/Resources/public/js/manager/attribute-manager.js

Using the PIM, there is some situations where you can have broken product templates. For example, if you created a localizable attribute, add it to a variant group then removed it to create a new one with the same code but not localizable this time. This can result into a situation where then product cannot be updated nor imported as the product template cannot be applied.
In this PR I add a command to clean product templates. This is clearly a maintenance situation and should not be used on a daily basis. …

PIM-5962: add clean product template command

---

src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml

This PR fixes translations that are parsed incorrectly for Crowdin.  …

Fix js translations for Crowdin

---

CHANGELOG-1.7.md
features/Context/WebUser.php
features/product/edit_product_with_localizable_and_scopable_attribute_options.feature
src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/attributes.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/attributes/copy.js
src/Pim/Bundle/EnrichBundle/Resources/public/templates/form/tab/attributes/copy-field.html
src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/field/field.html

This PR fixes an issue where the scope information for attribute fields (e.g. 'ecommerce, print, mobile' on a description field) was no longer being displayed.  …

PIM-6284: Scopable information are not displayed anymore nearby scopable fields

---

CHANGELOG-1.7.md
features/Context/AssertionContext.php
features/mass-action/edit_common_attributes.feature
src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/attributes.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/field/field.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/mass-edit/attributes.js

This PR fixes a bug on the mass edit common attributes screen where fields become re-enabled after switching attribute groups. It happens because the fields are re-rendered after the switch, and the field render method sets them as editable by default.
| Added Behats …

PIM-6271: Mass edit - attribute group switch unlocks the form

---

CHANGELOG-1.7.md
src/Pim/Bundle/EnrichBundle/Form/Type/AttributeRequirementType.php
src/Pim/Bundle/EnrichBundle/MassEditAction/Operation/SetAttributeRequirements.php
src/Pim/Bundle/EnrichBundle/Resources/config/form_types.yml
src/Pim/Bundle/EnrichBundle/Resources/config/mass_actions.yml
src/Pim/Bundle/EnrichBundle/spec/MassEditAction/Operation/SetAttributeRequirementsSpec.php

PIM-6118 introduced some BC breaks. This PR is to avoid BC breaks in 1.7 and use `soft deprecation` instead …

PIM-6118: Avoid BC breaks in minor release

---

CHANGELOG-1.7.md
src/Pim/Bundle/UIBundle/Resources/public/less/lib/modal.less

This PR updates the CSS for the attribute selection panel to increase the width from 560px to 800px.
| Micro …

PIM-6309: Enlarge the attribute type selection panel

---

CHANGELOG-1.7.md
features/product/completeness/display_completeness.feature
src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/attributes.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/attributes/copy.js
src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/panel/completeness.html

This PR reverses changes made in https://github.com/akeneo/pim-community-dev/pull/6034 and https://github.com/akeneo/pim-community-dev/pull/5997 to use the catalogLocale to translate labels rather than uiLocale. 
Before:
After:
| …

PIM-6277: Use catalogLocale for channel and scopable attribute labels 

---

CHANGELOG-1.7.md
features/attribute/create_text_attribute.feature
src/Pim/Bundle/EnrichBundle/Resources/views/Attribute/_js-handler.html.twig
src/Pim/Bundle/EnrichBundle/Resources/views/Attribute/form.html.twig

This PR fixes an issue in the attribute creation form when trying to submit an attribute with missing data (code, group). It adds back the behaviour of switching to the correct tab and focusing on the invalid field after submission.  This behaviour was previously removed with JSFV here - https://github.com/akeneo/pim-community-dev/pull/5863 …

PIM-6324: Fix missing error message after creating an attribute with invalid data

---

CHANGELOG-1.6.md
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/field/wysiwyg-field.js

This PR fixes two issues in the summernote wysiwyg editor: 
1. Where the editor leaves empty tags (e.g. `<p><br/><p>` in the code view, even when all content has been removed in the editing view. This was fixed by manually cleaning the empty tags onkeyup/onblur 
2. Where the corresponding model does not get updated after making an edit in the code view. This was fixed by triggering the `updateModel` method when the code view editor loses focus (like how the editing view works). 
[//]: <> (What does this Pull …

PIM-6375: Fix empty tags and content not being saved in wysiwyg 

---

CHANGELOG-1.7.md
src/Pim/Bundle/UIBundle/Resources/public/less/components/MainMenu.less

Solves this issue:
https://github.com/akeneo/pim-community-dev/issues/6061
No CI needed.

[GITHUB-6061] Fix menu display for big words

---

CHANGELOG-1.7.md
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/field/date-field.js

This PR fixes a bug where opening the date picker on the product edit page also opens the copied picker in the compare panel. This fix initializes both date pickers in the `date-field` view but only triggers the `show` event on the one that was clicked (instead of both) …

PIM-5709: Fix clicking date picker also opens date picker in compare panel

---

CHANGELOG-1.7.md
features/attribute/option/create_attribute_options.feature
src/Pim/Bundle/EnrichBundle/Controller/AttributeOptionController.php
src/Pim/Bundle/EnrichBundle/Resources/public/js/attribute-option/create.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/pim-attributeoptionview.js

This PR updates the controller and js for attribute options to display form validation errors (fixing a regression from 1.6). …

PIM-6322: Add output for attribute option form validation

---

CHANGELOG-1.7.md
src/Pim/Bundle/EnrichBundle/Resources/public/js/job/product/edit/content/structure/scope.js
src/Pim/Bundle/EnrichBundle/Resources/public/templates/export/product/edit/content/structure/scope.html

This PR fixes a bug in the channel selector for export profiles. It adds a code fallback for each channel when translations are missing. See #6004 
Before:
After: 
| Added integration tests           |  - …

PIM-6378: Fix translations for channel labels in export builder

---

CHANGELOG-1.7.md
CHANGELOG-1.8.md
app/OroRequirements.php

Fix https://github.com/akeneo/pim-community-dev/issues/5937 by removing mcrypt requirement.
After searching any mcrypt function on the project, it does not seem to be used (as stated by @gquemener and @a2xchip).
I've added a **Requirements** part in the Changelog, not really sure where to do add this modification, is this correct? …

GITHUB-5937 - Remove mcrypt requirement

---

src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/product.yml

This fix the first bug described in the issue https://github.com/akeneo/pim-community-dev/issues/5403 by removing the possibility of changing the status of a product on the product grid when not allowed. …

GITHUB-5403 - fix toggle status product grid when not allowed

---

CHANGELOG-1.7.md
src/Pim/Bundle/DataGridBundle/Extension/Formatter/Property/ProductValue/PriceProperty.php

Price field does not appear on the variation datagrid.
It happens only for MongoDB storage, when there are no property data set for a price.

PIM-6377: add sanity check in price property formatter

---

CHANGELOG-1.7.md
src/Pim/Bundle/ApiBundle/Security/OAuth2.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Token/GetAccessTokenIntegration.php

When requesting the API, when the token has expired or is invalid, the HTTP status returned should be 401 instead of 422.
This is done by throwing an "UnauthorizedHttpException" during the verification of the access token. This exception need a parameter to build the HTTP header "WWW-Authenticate" which is fetched by the OAuth exception. …

PIM-6387: fix HTTP code returned when the token is invalid or expired

---

CHANGELOG-1.8.md
src/Pim/Bundle/UIBundle/Resources/public/less/lib/summernote.less

Attempt to fix #6101 by adding two rules (ul/ol) in the summernote to display the **list-style-type** that was previously settled to none in
https://github.com/akeneo/pim-community-dev/blob/master/src/Pim/Bundle/UIBundle/Resources/public/less/base/general.less#L53
| …

GITHUB-6101 - Fix ol/ul in WYSIWYG

---

CHANGELOG-1.7.md
features/channel/create_channel.feature
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/channel/create.yml

Delete button should not be showed on create screen.
| …

PIM-6381: Remove delete button on channel create screen

---

CHANGELOG-1.7.md
src/Pim/Bundle/UIBundle/Resources/public/less/lib/summernote.less

Backport the fix https://github.com/akeneo/pim-community-dev/pull/6121 in order to fix this issue : https://github.com/akeneo/pim-community-dev/issues/6101 …

Backport GITHUB-6101 - Fix ol/ul in WYSIWYG

---

CHANGELOG-1.7.md
upgrades/schema/Version_1_7_20170504175205_clean_attribute_properties.php

Clean attributes when migrating from 1.6 to 1.7.
Related to validation rules change done in 1.7.

PIM-6402: Clean attribute properties according to new validation rules during migration

---

CHANGELOG-1.5.md
src/Pim/Bundle/CatalogBundle/EventSubscriber/MongoDBODM/SetProductsSubscriber.php

The problem occurs when the method "getProducts()" is called on an entity "Category" or "Group" to fetch products which are in several categories or groups.
The request built to fetch products in MongoDB on a lazy loading way is wrong. The value of the parameter used to find products must not be embedded in an array. Otherwise all the elements of the parameter should be setted, which it's not the desired behavior. …

PIM-6395: Fix MongoDB query built to fetch products in a LazyCollection

---

CHANGELOG-1.7.md
features/user/create_and_delete_user.feature
src/Pim/Bundle/JsFormValidationBundle/Resources/views/Constraints/EmailValidator.js.twig

When creating a user in the UI, email format is too restrictive or not enough : 
- _foo+bar@akeneo.com_ is a valid email but not accepted by the PIM due to the '+'
- _foo+bar@akeneo.intern_ is a valid email but not accepted by the PIM due to 6 characters at the end
- _foo..bar@akeneo.com_ is valid and should not (two consecutive dots)
It's due to the regex in _JsFormValidationBundle_ : 
`
/^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})$/
`
Validation has been overrided with a far better regex …

PIM-6394: Fix email validation when creating a user in order to be less restrictive

---

CHANGELOG-1.7.md
src/Akeneo/Bundle/BatchBundle/Command/BatchCommand.php

Fix JobInstance class hardcoded in
Akeneo\Bundle\BatchBundle\Command\BatchCommand::execute
In the BatchCommand, to retrieve the JobInstanceRepository the class 'Akeneo\Component\Batch\Model\JobInstance' was hardcoded,
instead to ask for the parameter 'akeneo_batch.entity.job_instance.class'
The related issue is [here](https://github.com/akeneo/pim-community-dev/issues/6159)
| …

Fix JobIntance class hardcoded

---

CHANGELOG-1.5.md
Jenkinsfile
features/product/completeness/display_completeness.feature
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/panel/completeness.js
src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/panel/completeness.html

When displaying the completeness in the PEF, it was the code of the channel that was displayed.
It should be the channel's label. This PR fixes that.
Note : it's already ok in 1.7
Note 2 : I've improved the way to parse behat XML files in the Jenkins file because I had an exception. See https://github.com/akeneo/pim-enterprise-dev/pull/2792.
| …

PIM-6405: display channel's label in the completeness panel of the PEF

---

CHANGELOG-1.8.md
src/Pim/Bundle/EnrichBundle/Resources/public/js/job/common/edit/upload-launch.js

Shows a loading mask on file upload during import. 
Thanks to SimonCarre for raising the fix and proposing a fix from which this PR is inpired https://github.com/akeneo/pim-community-dev/pull/6065

GITHUB-6065: Shows the loading mask on file upload in imports

---

CHANGELOG-1.7.md
src/Pim/Bundle/CatalogBundle/EventSubscriber/MongoDBODM/TimestampableSubscriber.php
src/Pim/Bundle/CatalogBundle/spec/EventSubscriber/MongoDBODM/TimestampableSubscriberSpec.php

PIM Version: 1.7.4
When updating existing product using ProductSaver, the created field of the product gets also updated.

GITHUB-6151: Fix MongoDB Timestampable subscriber

---

CHANGELOG-1.7.md
src/Pim/Bundle/ApiBundle/Doctrine/ORM/Repository/ApiResourceRepository.php
src/Pim/Bundle/ApiBundle/Doctrine/ORM/Repository/AttributeRepository.php
src/Pim/Bundle/ApiBundle/Doctrine/ORM/Repository/ProductRepository.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/AbstractProductTestCase.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/ListProductWithCompletenessIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/SuccessListProductIntegration.php

Add missing groupBy to fix products returned on list when filters are applied  …

PIM-6254: Fix pagination on the API when filters are applied

---

CHANGELOG-1.6.md
features/Context/Page/Attribute/Creation.php
features/Context/WebUser.php
features/attribute/option/edit_attribute_options_02.feature
src/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/QueryGenerator/MultipleOptionValueUpdatedQueryGenerator.php
src/Pim/Bundle/CatalogBundle/EventSubscriber/MongoDBODM/UpdateNormalizedProductDataSubscriber.php
src/Pim/Bundle/CatalogBundle/Resources/config/model/doctrine/ProductValue.mongodb.yml
src/Pim/Bundle/CatalogBundle/Resources/config/storage_driver/doctrine/mongodb-odm.yml
src/Pim/Bundle/CatalogBundle/spec/Doctrine/MongoDBODM/QueryGenerator/MultipleOptionValueUpdatedQueryGeneratorSpec.php
upgrades/schema/Version_1_6_20170511132057_add_mongodb_index_on_product_values_options_id.php

Update option values of attributes of type "multi-select" (from import or UI) generates slow queries on MongoDB, up to trigger timeout for big catalogs.
The problem is that the query which update products in MongoDB use the operator `$elemMatch` on a attribute without index. To add a index on each attribute of type "multi-select" is not the solution, so I used another approach.
First, I added a index on the attribute `values.optionIds` to use this one as the main condition of the update query (to retrieve all products having an option value in particular). But this doesn't allow to retrieve precisely the option value to update, because the option values are stored in an numerical array for the attributes of type "multi-select".
So, I …

Pim-6376: Fix slow MongoDB queries when editing attribute options

---

CHANGELOG-1.7.md
features/export/delete_an_export.feature
features/import/delete_an_import.feature
src/Pim/Bundle/EnrichBundle/Resources/public/js/remover/job-instance-export-remover.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/remover/job-instance-import-remover.js
src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml

Fix https://github.com/akeneo/pim-community-dev/issues/5949 - Allow to delete import/export profile on the profile page
| Migration …

GITHUB-5949 - Allow to delete import/export profile on the profile page

---

CHANGELOG-1.6.md
src/Pim/Bundle/EnrichBundle/Resources/config/bundles/akeneo_batch.yml

When you get notification by mail after a batch import for example you didn't have the right sender defined in pim_parameters.yml n your mailbox. 
Not sure if it's "normal" or a miss, but in my mind it must use the master one.

Update akeneo_batch.yml sender email

---

CHANGELOG-1.7.md
src/Pim/Bundle/EnrichBundle/Controller/Rest/AttributeGroupController.php
src/Pim/Bundle/EnrichBundle/Controller/Rest/FamilyController.php
src/Pim/Bundle/EnrichBundle/Normalizer/FamilyNormalizer.php
src/Pim/Bundle/EnrichBundle/Resources/config/normalizers.yml
src/Pim/Bundle/EnrichBundle/Resources/public/js/family/form/attributes/attributes.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/fetcher/base-fetcher.js
src/Pim/Bundle/EnrichBundle/Resources/views/Family/edit.html.twig
src/Pim/Bundle/EnrichBundle/spec/Normalizer/FamilyNormalizerSpec.php

- attributes should not be filtered when normalizing
Bug fix solution was discussed with @skeleton and @juliensnz 
The most painful in current state is that we introduce `apply_filters` request param to return filetered/unfiltered collection in response.
After discussion with Marie we came to opinion that it is not good to mix filtered/unfiltered sets in one action. And it would be good to use two different routes to fetched filtered attribute groups and unfiltered. And this way we get obtain ability to …

PIM-6196: Do not filter attributes in family enrich normalizer

---

upgrades/schema/Version_1_6_20161114150000_add_missing_set_attribute_requirements_job.php

Hi,
the mass-edit for families does not work (the final completion step fails).
Reason for this is the missing background job 'set_attribute_requirements'. This PR adds the missing job in a migration script. An existing job with the same code will be removed as it may be created manually.
The bug can be reproduces by using the mass edit functionality of families (mass-adding attributes).
The last completion step fails.
| Migration script                  | Y

Add missing job set_attribute_requirements

---

CHANGELOG-1.6.md
src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/grid.js

The URI generated to load the products in the variant groups Datagrid can be too long if there are a lot of products. Indeed, each product selection is added as an array parameter to the URI.
Given that this parameters are not used to load the datagrid elements (regardless of the entity). The solution is to remove them from the URI generation. It can be done in the Datagrid initialization by removing the property  `selection` from `options`. It hasn't consequences because the selection is handled in a specific attribute of the Datagrid (see line https://github.com/akeneo/pim-community-dev/blob/817d68366dcf2ed94dc465deded0d239c1fae6f1/src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/grid.js#L29) …

PIM-6418: Fix URL too long in variant group datagrid

---

CHANGELOG-1.7.md
src/Akeneo/Component/FileStorage/StreamedFileResponse.php
src/Pim/Bundle/ApiBundle/Stream/StreamResourceResponse.php

Two fixes for the same problem: When the PHP function `ob_flush` is called while the output buffering is disabled, then a PHP Notice is raised.
The output buffering is activated by default, but it can be disabled via the directive `output_buffering` in PHP configuration for some providers.
It happened when updating a list of resources with the API. In this case the flush is needed for the tests, so we start manually the buffering if it's not.
It also happened for the same reason when downloading a media file. In this case the flush was not required. So we have removed the flush and took advantage of this fix to improve the way to download the files. …

PIM-6392: Response contains unexpected HTML when updating a list of resources

---

upgrades/schema/Version_1_7_20161009194818_product_template.php

Migrating from `v.1.6` to `v1.7` I've got error: `Property "image" expects a string as data, "array" given.`
Paths of `image` attributes must be fixed when migrating product templates to `v1.7`

Fix paths of image attributes at pim_catalog_product_template

---

CHANGELOG-1.5.md
src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/CompletenessRepository.php

The widget of the completeness could take a lot of time to be displayed (200 seconds for a client).
It is due to an unoptimised SQL request.
It's a big problem, because during this time, the session is locked. So, the PIM is totally unavailable for the user (even with a refresh).
This problem has already been raised in this ticket: https://github.com/akeneo/pim-community-dev/issues/3771
**1. First point that this PR intends to resolve: [ABORTED]**
_IMPORTANT : This commit will be done on master due to race …

PIM 6429 : Improve the loading of the completeness widget on dashboard

---

CHANGELOG-1.7.md
src/Pim/Bundle/ApiBundle/DependencyInjection/Compiler/ContentTypeNegotiatorPass.php
src/Pim/Bundle/ApiBundle/DependencyInjection/Configuration.php
src/Pim/Bundle/ApiBundle/DependencyInjection/PimApiExtension.php
src/Pim/Bundle/ApiBundle/EventSubscriber/CheckHeadersRequestSubscriber.php
src/Pim/Bundle/ApiBundle/Negotiator/ContentTypeNegotiator.php
src/Pim/Bundle/ApiBundle/PimApiBundle.php
src/Pim/Bundle/ApiBundle/Resources/config/api.yml
src/Pim/Bundle/ApiBundle/Resources/config/event_subscribers.yml
src/Pim/Bundle/ApiBundle/Resources/config/negotiators.yml
src/Pim/Bundle/ApiBundle/spec/EventSubscriber/CheckHeadersRequestSubscriberSpec.php
src/Pim/Bundle/ApiBundle/spec/Negotiator/ContentTypeNegotiatorSpec.php

Fos Rest Bundle allows to get the best "Accept-Type" given a request.
It allows to do it thanks to https://github.com/akeneo/pim-community-dev/blob/1.7/src/Pim/Bundle/EnrichBundle/Resources/config/bundles/fos_rest.yml#L15
Unfortunately, this feature is not designed for the validation of the content-type.
We used it to validate it, it was working "by luck", because we had only one content type accepted per endpoint for the moment. But it leads to some weird behavior.
This misuse is problematic, because we …

PIM-6285: fix content type validation in the API

---

CHANGELOG-1.6.md
features/reference-data/import/import_products.feature
src/Acme/Bundle/AppBundle/Model/ProductValue.php

When importing a csv product file with a multi select reference data option code appearing twice or more for one attribute. The import job fails with an error:
`Exception SQL raised : Duplicate entry in the table that stores the values of the ref data.`
This PR intends to fix this issue by fixing the product value override to check if the reference data we want to add already exists before adding it to the multi select list.
This PR is mostly for educational purpose, so that integrators can rely on this code sample to create their on reference data correctly.
| …

PIM-6433: Prevent the insertion of duplicate multi-reference data code to break an import

---

CHANGELOG-1.7.md
src/Pim/Bundle/EnrichBundle/Resources/config/bundles/liip_imagine.yml

This PR changes the thumbnails format to PNG instead of JPG
The issue was that transparent background were deleted on the transformation.

[PIM-6399]

---

CHANGELOG-1.7.md
features/Context/DataGridContext.php
features/Context/Page/Base/Form.php
features/Context/WebUser.php
features/attribute/option/sort_attribute_options.feature
src/Pim/Bundle/EnrichBundle/Doctrine/ORM/Repository/AttributeOptionSearchableRepository.php
src/Pim/Bundle/EnrichBundle/Resources/config/repositories.yml
src/Pim/Bundle/EnrichBundle/Resources/public/js/pim-attributeoptionview.js
src/Pim/Bundle/EnrichBundle/Resources/public/templates/attribute-option/show.html
src/Pim/Bundle/UIBundle/Resources/public/less/lib/jquery-ui.less

If fixes the autosort at 2 places:
- on attribute edition, you can enable/disable autosort, and it displays result in the list directly. Old order are kept, so you can disable autosort to get back to old one.
- on PEF, attributes are displayed ordered when option is enabled.

[PIM-6420] Fix autosorting of attribute options

---

src/Pim/Component/Connector/ArrayConverter/FlatToStandard/Product/AttributeColumnInfoExtractor.php
src/Pim/Component/Connector/ArrayConverter/FlatToStandard/Product/AttributeColumnsResolver.php

This PR eases the override exploding methods to extend in protected sub-method. It has been done for attribute types.
It does not contain any BC.
| Q | A |
| --- | --- |
| Added Specs | N/A |
| Added Behats | N/A |
| Changelog updated | N/A |
| Review and 2 GTM |  |
| Micro Demo to the PO (Story only) | N/A |
| Migration script | N/A |
|  Tech Doc | N/A |

TIP-611: Ease override of AttributeColumnInfoExtractor and AttributeColumnsResolver

---

CHANGELOG-1.8.md
src/Pim/Bundle/ConnectorBundle/DependencyInjection/PimConnectorExtension.php
src/Pim/Bundle/ConnectorBundle/Doctrine/UnitOfWorkAndRepositoriesClearer.php
src/Pim/Bundle/ConnectorBundle/Resources/config/doctrine.yml
src/Pim/Bundle/ConnectorBundle/Resources/config/writers.yml
src/Pim/Bundle/ConnectorBundle/spec/Doctrine/UnitOfWorkAndRepositoriesClearerSpec.php
src/Pim/Component/Connector/Writer/Database/ProductWriter.php
src/Pim/Component/Connector/spec/Writer/Database/ProductWriterSpec.php

Currently, in the master branch, this import leaks again. We introduced regressions with the new systems about completenesses and unique data.
This PR aims to fix once and for all the problem by clearing the UoW each time we write products (at each bulk of the batch). We also have to clear all the data we have kept in our cached repositories (we could totally optimize this part, but we'll see later).
This PR works perfectly. I imported 50K products (medium catalog) without any problem.
Others PRs are planned to improve the import time.
| Added Behats                      | 
| Review and 2 …

TIP-763: fix once and for all memory leaks in products' import

---

features/Context/CatalogConfigurationContext.php
features/Context/WebUser.php
src/Pim/Bundle/CatalogBundle/Resources/config/factories.yml
src/Pim/Bundle/CatalogBundle/Resources/config/repositories.yml
src/Pim/Bundle/ConnectorBundle/Resources/config/array_converters.yml
src/Pim/Bundle/ConnectorBundle/Resources/config/doctrine.yml
src/Pim/Bundle/ConnectorBundle/Resources/config/steps.yml
src/Pim/Component/Catalog/Comparator/Filter/ProductFilter.php
src/Pim/Component/Catalog/Factory/PriceFactory.php
src/Pim/Component/Catalog/Factory/ProductValue/OptionProductValueFactory.php
src/Pim/Component/Catalog/Factory/ProductValue/OptionsProductValueFactory.php
src/Pim/Component/Catalog/Localization/Localizer/AttributeConverter.php
src/Pim/Component/Catalog/spec/Factory/PriceFactorySpec.php
src/Pim/Component/Catalog/spec/Factory/ProductValue/OptionProductValueFactorySpec.php
src/Pim/Component/Catalog/spec/Factory/ProductValue/OptionsProductValueFactorySpec.php
src/Pim/Component/Connector/ArrayConverter/FlatToStandard/Product/AttributeColumnInfoExtractor.php
src/Pim/Component/Connector/spec/ArrayConverter/FlatToStandard/Product/AttributeColumnInfoExtractorSpec.php

The following benchmarks have been executed with a subset of the medium catalog (10K products), on my local machine. Soon, we'll perform benchmarks on a proper environment to get more reliable results.
Before this PR, on master: 13:30
With this PR: 9:07
PIM 1.7  with Mongo and PHP 7.1: 10:51
We could go further in the enhancements, but the results are good enough for now. Even if the completeness is calculated in a POO way and if products are indexed in ES, with this PR, we are faster than PIM 1.7 with PHP 7.1. And we still have plenty of ways to improve the imports:
- continue to track "avoidable" MySQL queries
- find PHP hotspots with Blackfire
If somebody is interested by this topic, I'd be more than happy to help him/her :)
Before this PR:
```
jjanvier:pcd$ /usr/bin/time php7.1 …
```

TIP-763: significant and easy improvements regarding products import

---

Jenkinsfile
src/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/IndexCreator.php

We cannot use MongoDB 3.x natively, because native PHP packages from Debian 8 use "ext-mongo" 1.5, the old legacy [MongoDB driver](https://secure.php.net/manual/en/book.mongo.php), and this extension is only compatible with MongoDB 2.4 and 2.6.
However, it seems that the only method that really do not work is `$collection->getIndexInfo()`, called by our `IndexCreator` [here](https://github.com/akeneo/pim-community-dev/pull/6296/files#diff-99f42ccc8fae424876840be3441c407aR278). We use this method to count the number of created index, and stop the creation when we reach the limit of MongoDB (64 indexes). However, with MongoDB 3.x, this method always return 0 :/.
The trick here is to catch in the IndexCreator the MongoDB exception that is raised when limit is reached, and stop the index …

Allow to run the CI with Mongo 3.4

---

features/Pim/Behat/Context/Domain/TreeContext.php
features/Pim/Behat/Decorator/Tree/JsTreeDecorator.php
features/category/create_a_category.feature

In Enterprise when you create a new category tree the context of the tree was not switch to the new tree.
A behat was missing even and can be applied directly in CE.

PIM-6393: behat about context kept when creating new category tree

---

CHANGELOG-1.5.md
spec/Akeneo/Component/Batch/Step/ItemStepSpec.php
src/Akeneo/Bundle/BatchBundle/Job/DoctrineJobRepository.php
src/Akeneo/Component/Batch/Step/ItemStep.php

There is a memory leak, both on imports and exports, caused by batch [Warnings](https://github.com/akeneo/pim-community-dev/blob/1.5/src/Akeneo/Component/Batch/Model/Warning.php).
As they are added to the current step execution, in an ArrayCollection (so managed by Doctrine), [here](https://github.com/akeneo/pim-community-dev/blob/1.5/src/Akeneo/Component/Batch/Model/StepExecution.php#L453), you will end up with as many `Warning` entities in memory than you have in your import => memory leak!
The idea of this PR is to not create any `Warning` entities anymore (leaving the ArrayCollection empty), and instead inserting them directly in database.
This allows us not to do any BC break, and to keep current behavior on warning display.
Thanks to @momoss who locate the notification problem …

PIM-6129: Fix memory leak on import/export warnings

---

app/PimRequirements.php
src/Pim/Bundle/InstallerBundle/Command/DatabaseCommand.php

There is a regression since the merge of PHP 7.1 support into master.
The database was not created if it does not exist when we are installing the pim with `pim:install`.
| …

TIP-744: install the database if it does not exist with pim:install

---

src/Pim/Bundle/EnrichBundle/Doctrine/ORM/Repository/AttributeOptionSearchableRepository.php

Fix a missed comment in https://github.com/akeneo/pim-community-dev/pull/6325

Fix phpdoc typo

---

CHANGELOG-1.5.md
src/Akeneo/Bundle/StorageUtilsBundle/Doctrine/Common/Detacher/ObjectDetacher.php

Fix doctrine/mongodb-odm storage memory leak on product import with media, FileInfo object related to product media were not properly detached (Product stored in mongo and FileInfo stored in mysql) and stay in memory.
`-`: Not …

PIM-6462: Detach Product Media in ObjectDetacher for avoid leak in MongoDb Storage

---

src/Pim/Bundle/CatalogBundle/Resources/elasticsearch/index_configuration.yml
src/Pim/Component/Catalog/Builder/ProductBuilder.php

In ES 5.X was introduced the settings `mapping.total_fields.limit`. Its default value is set to 1000.
see the PR https://github.com/elastic/elasticsearch/pull/17357.
In this PR, we bump up this settings to:
- Number of fields in large catalog: 1284 (counting the columns in a CSV file)
- Multiplied by 2 (=2568) and rounded up to 3000. …

TIP-749: Fix ES index mapping total fields limit

---

CHANGELOG-1.7.md
src/Pim/Bundle/DataGridBundle/Twig/FilterExtension.php
src/Pim/Bundle/DataGridBundle/spec/Twig/FilterExtensionSpec.php

Default product filters on user profile were correctly translated if they were not attribute.
| Added Behats                      | Y (EE)

PIM-6470: Correctly translate default filters on user profile

---

CHANGELOG-1.6.md
src/Pim/Component/Connector/Writer/File/Yaml/Writer.php

This bug has been spotted while trying to export more than 100 rules. Only the last N%100 rules were exported.
This is because batch of elements to be written were overriding previous ones.
| Tech Doc                          | No
CI Not okay, but failed …

PIM-6529: allow more than 100 elements to be exported with YAML export

---

features/Context/FeatureContext.php
features/Pim/Behat/Context/HookContext.php
features/Pim/Behat/Context/JSErrorEncounteredException.php

Throw an exception when a js error is found so it can be retrieved by Behat formatters (and especially the JUnit one for Blue Ocean).
Until now it wasn't possible to see that a js error happened on a scenario by looking in your build result.

Display js errors in Blue Ocean UI

---

features/Context/FixturesContext.php
features/Context/catalog/catalog_modeling/jobs.yml
features/Pim/Behat/Context/FixturesContext.php
features/import/family_variant/csv/create_family_variant.feature
features/import/family_variant/xlsx/create_family_variant.feature
src/Pim/Bundle/CatalogBundle/Resources/config/model/doctrine/VariantAttributeSet.orm.yml
src/Pim/Bundle/CatalogBundle/Resources/translations/messages.en.yml
src/Pim/Bundle/CatalogBundle/tests/integration/Family/FamilyVariantIntegration.php
src/Pim/Bundle/ConnectorBundle/Resources/config/archiving.yml
src/Pim/Bundle/ConnectorBundle/Resources/config/array_converters.yml
src/Pim/Bundle/ConnectorBundle/Resources/config/job_constraints.yml
src/Pim/Bundle/ConnectorBundle/Resources/config/job_defaults.yml
src/Pim/Bundle/ConnectorBundle/Resources/config/jobs.yml
src/Pim/Bundle/ConnectorBundle/Resources/config/processors.yml
src/Pim/Bundle/ConnectorBundle/Resources/config/readers.yml
src/Pim/Bundle/ConnectorBundle/Resources/config/steps.yml
src/Pim/Bundle/ConnectorBundle/Resources/config/writers.yml
src/Pim/Bundle/ConnectorBundle/Resources/translations/messages.en.yml
src/Pim/Bundle/EnrichBundle/Resources/config/providers.yml
src/Pim/Component/Catalog/Model/FamilyVariant.php
src/Pim/Component/Catalog/Model/FamilyVariantInterface.php
src/Pim/Component/Catalog/Model/VariantAttributeSet.php
src/Pim/Component/Catalog/Model/VariantAttributeSetInterface.php
src/Pim/Component/Catalog/Updater/FamilyVariantUpdater.php
src/Pim/Component/Catalog/Validator/Constraints/FamilyVariantValidator.php
src/Pim/Component/Catalog/spec/Model/FamilyVariantSpec.php
src/Pim/Component/Catalog/spec/Updater/FamilyVariantUpdaterSpec.php
src/Pim/Component/Connector/ArrayConverter/FlatToStandard/FamilyVariant.php
src/Pim/Component/Connector/spec/ArrayConverter/FlatToStandard/FamilyVariantSpec.php

This PR is the first step to add import of family variants, both in CSV and XLSX. It adds the following (each point correspond to a commit of the PR):
- basic acceptance tests: 3 simple import scenarios, all of them in CSV and XLSX
- the imports themselves: basically a lot of YAML configuration, and the flat to standard FamilyVariant array converter
- a change in the way the levels are stored: it was directly set as the indexes of the array collection that contains the family variant attribute sets. However, the information seems to be lost when the family variant is loaded from database. **So instead, the last commit proposes to store this level information in database, as an attribute set field**.
I still have to implement the business rules specific to those imports, and the behat …

PIM-6330: Import new family variants

---

.gitignore
docker-compose.yml.dist
docker/akeneo-behat.conf
docker/akeneo.conf
src/Pim/Bundle/InstallerBundle/Command/AssetsCommand.php
src/Pim/Bundle/InstallerBundle/Command/InstallCommand.php
src/Pim/Bundle/InstallerBundle/Resources/config/services.yml

Add a `docker-compose.yml.dist` file, pre-configured. It uses `akeneo/apache-php:php-5.6` image for akeneo containers.
The commands `pim:install` and `pim:installer:assets` have been updated too, to add two new options:
- `symlink`: this will install the assets as relative symlinks instead of hard copy (present in both command as  `pim:install` and `pim:installer:assets`)
- `clean`: this will completely clean the artefacts of the previous pim install, or the previous assets install …

Add a Docker compose file to the PIM

---

src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/PartialUpdateProductIntegration.php
src/Pim/Component/Catalog/Comparator/Attribute/ScalarComparator.php
src/Pim/Component/Catalog/Comparator/Field/ScalarComparator.php
src/Pim/Component/Catalog/spec/Comparator/Attribute/ScalarComparatorSpec.php
src/Pim/Component/Catalog/spec/Comparator/Field/ScalarComparatorSpec.php

Since PHP 7.0 array to string conversion has been improved and now throw E_RECOVERABLE_ERROR instead of a E_NOTICE. [improve-array-to-string-conversion](https://why-cant-we-have-nice-things.mwl.be/requests/improve-array-to-string-conversion)
With the PIM API we can send invalid data like an array for a `pim_catalog_text` attribute instead string that was not an issue with PHP 5.6, before it thrown a E_NOTICE, and as the next PIM version has to support PHP 7.0, we have to fix it.
| …

API-php7-fix: Fix array to string conversion exception

---

features/Context/Page/Base/ProductEditForm.php
features/Context/Page/Product/Edit.php
features/Context/Page/VariantGroup/Edit.php
src/.htaccess
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/product/edit.yml
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/variant_group/edit.yml
src/Pim/Bundle/EnrichBundle/Resources/public/js/filter/attribute/attribute.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/attributes.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/attributes/copy.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/associations.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/categories.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/locale-switcher.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/scope-switcher.js
src/Pim/Bundle/EnrichBundle/Resources/public/templates/form/edit-form.html
src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/locale-switcher.html
src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/scope-switcher.html
src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml
src/Pim/Bundle/UIBundle/Resources/public/less/components/TitleContainer.less
src/Pim/Bundle/UIBundle/Resources/public/less/components/button/ActionButton.less

This PR only moves the 2 context selectors (scope + locale) in the main title container.
This implies a lot of changes for scope & locale events, because the hierarchy is not the same.
So all the events (pre-scope, update-scope, pre-locale, update-locale) are sent to Root instead of parents.

[PIM-6498] Move the scope + locale switchers to PEF header

---

CHANGELOG-1.7.md
features/Context/Page/Base/Form.php
features/attribute/option/sort_attribute_options.feature
src/Pim/Bundle/EnrichBundle/Doctrine/ORM/Repository/AttributeOptionSearchableRepository.php
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/field/multi-select-field.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/field/simple-select-field.js

When the `autoOptionSorting` properties of the select attribute is not set, the select type failed.
Options in select type have to be sort in terms of the current locale.
-> I added an option `locale` in the `findBySearch()` to avoid BC break.

PIM-6525: Fix attribute options auto-sorting

---

src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/field/date.html
src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/field/metric.html
src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/field/multi-select.html
src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/field/number.html
src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/field/price-collection.html
src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/field/simple-select.html
src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/field/text.html
src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/field/textarea.html
src/Pim/Bundle/UIBundle/Resources/public/less/base/variables.less
src/Pim/Bundle/UIBundle/Resources/public/less/components/product-edit-form/FieldContainer.less
src/Pim/Bundle/UIBundle/Resources/public/less/components/product-edit-form/MetricField.less
src/Pim/Bundle/UIBundle/Resources/public/less/components/product-edit-form/PriceList.less
src/Pim/Bundle/UIBundle/Resources/public/less/components/product-edit-form/TextField.less
src/Pim/Bundle/UIBundle/Resources/public/less/components/product-edit-form/TextareaField.less
src/Pim/Bundle/UIBundle/Resources/public/less/lib/select2.less

This PR updates the field design for all the localizable attributes.
It adds "fake layers" to show there is other locales availables.
only assets, file, image and boolean design does not change, every other attribute type is OK.

[PIM-6500] Update localizable field design

---

Jenkinsfile
src/Pim/Bundle/EnrichBundle/Normalizer/ProductViolationNormalizer.php
src/Pim/Bundle/EnrichBundle/spec/Normalizer/ProductViolationNormalizerSpec.php
web/app_behat.php

CI is not executed with error mode to ALL, for the integration tests and for the behat.
Moreover, in behat, the display output is Off, so you don't have any error in the output of the Ajax request. Errors are only logged in files (that we don't care at all on the CI).
CI should be strict. 
Our docker images will be changed to be strict. But we have to fix master first (to not have a red CI when we will use the new docker images).
Note: done in EE as well, but 0 error.
[//]: <> (What does this Pull Request …

Fix php error messages not catched by the CI in our tests

---

.gitignore
bin/docker/pim-front.sh
bin/docker/pim-initialize.sh

Add simple scripts to install the PIM with docker in 1.7
These scripts are simpler than those on master but at least, makes the doc simpler, as a developer using docker, on any Akeneo version, i run the same scripts (even if they internally run different things, like npm on master). If i want to move to a more advanced use, i can look at the script and manually run internal commands.
In other words, as a dev using docker, I don't want to remind subtilities between 1.7 and 1.8 installations, I'm lazy, I run the same script ;) …

Add docker install scripts for 1.7

---

src/Pim/Bundle/ApiBundle/Checker/QueryParametersChecker.php
src/Pim/Bundle/ApiBundle/spec/Checker/QueryParametersCheckerSpec.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Category/CreateCategoryIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Category/ListCategoryIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Category/PartialUpdateCategoryIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Category/PartialUpdateListCategoryIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/ErrorListProductIntegration.php
src/Pim/Bundle/VersioningBundle/tests/integration/Manager/VersionManagerIntegration.php
src/Pim/Bundle/VersioningBundle/tests/integration/Normalizer/Flat/AttributeIntegration.php
src/Pim/Component/Catalog/Model/AbstractValue.php
src/Pim/Component/Catalog/Value/PriceCollectionValue.php
src/Pim/Component/Catalog/spec/Value/PriceCollectionValueSpec.php

Fix `hasData` for PriceCollectionValue.
Remove the strict equality, it does not work when you compare number, etc. A PR will be done after to check if all types in the PIM are correctly compared.  …

API-70: Fix values

---

src/Pim/Bundle/ApiBundle/Controller/ProductController.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/ErrorListProductIntegration.php

Workaround to check the permissions on the locales even if it's not an array, as the check if it's an array is in the pqb so far deeper in the code ....
| Micro Demo …

API-213: Add missing case for many locales

---

CHANGELOG-1.8.md
src/Pim/Bundle/EnrichBundle/Controller/Rest/AttributeController.php
src/Pim/Bundle/EnrichBundle/Normalizer/AttributeNormalizer.php
src/Pim/Bundle/EnrichBundle/Normalizer/VersionedAttributeNormalizer.php
src/Pim/Bundle/EnrichBundle/Resources/config/controllers.yml
src/Pim/Bundle/EnrichBundle/Resources/config/normalizers.yml
src/Pim/Bundle/EnrichBundle/spec/Normalizer/AttributeNormalizerSpec.php
src/Pim/Bundle/EnrichBundle/spec/Normalizer/VersionedAttributeNormalizerSpec.php

**The context**
We need to load the PEF as fast as possible.
**The problem**
Among the most blocking requests : the one getting the list of attributes and the one getting the family. In Enrich, the normalized attributes are embed in the family. It appeared that the normalization of attributes was the common bottleneck.
**The solution**
In the current enrich attribute normalizer we set `created`, `updated`, `structure_version` and `model_type` keys. None of these are used in the PEF, so I split the normalizer in two : `AttributeNormalizer` and `VersionedAttributeNormalizer` (not sure about the naming), the second one decorating the first one. Then use the new one in the family normalizer and in the index route of the attribute rest controller.
For a PEF with 200 attributes :
Request | …

[PIM-6670] Optimize attributes normalization

---

behat.ci.yml
features/Pim/Behat/Extension/PimFormatter/Output/Node/EventListener/PimFeatureElementListener.php
features/Pim/Behat/Extension/PimFormatter/Output/Node/Printer/PimScenarioPrinter.php
features/Pim/Behat/Extension/PimFormatter/PimFormatterExtension.php
features/Pim/Behat/Extension/PimFormatter/ServiceContainer/Formatter/PimFormatterFactory.php

Before the upgrade Behat 2 -> Behat 3, a custom formatter was doing the job to display filepath instead of namespace of the failing behat tests in the CI.
During the migration, we realized with @anaelChardan that is was not so easy to perform the same thing with Behat 3.
After investigation, it has to be done with an extension, and here it is.
This PR is heavily inspired from the Junit Formatter. There are some copy/past of classes, because most of the classes are final (not possible to extend), and they …

Display filepath instead of namespace of the failing scenarios of the CI

---

Jenkinsfile

Dirty fix to avoid the error in the CI.
Should be properly fix with healthcheck. …

Add a dirty sleep as workaround to wait the availability of elastic search container

---

CHANGELOG-1.7.md
features/product/sorting/sort_products_per_attribute.feature
src/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/Sorter/AttributeOptionSorter.php
src/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/Sorter/IsAssociatedSorter.php
src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Sorter/EntitySorter.php
src/Pim/Bundle/CatalogBundle/Resources/config/storage_driver/doctrine/mongodb-odm.yml
src/Pim/Bundle/CatalogBundle/spec/Doctrine/MongoDBODM/Sorter/AttributeOptionSorterSpec.php
src/Pim/Bundle/CatalogBundle/spec/Doctrine/MongoDBODM/Sorter/IsAssociatedSorterSpec.php
src/Pim/Bundle/CatalogBundle/spec/Doctrine/ORM/Sorter/EntitySorterSpec.php

When you add a simple select filter and the associated column in the grid, the sorting of the column was in terms of code first and not in terms of label first. 
In ODM, I added an `AttributeOptionSorter`.
Moreover, for the `pim_catalog.doctrine.query.sorter.is_associated` service, the class was the BaseSorter which has `isAttributeSupported() { return true; }`. The compiler pass `RegisterProductQuerySorterPass` added in the `SorterRegistry` the `is_associated` service with the highest priority (30). So when we were searching for a sorter, the first one was `is_associated` with `isAttributeSupported() { return true; }` and it was not possible to find another sorter.
No pb in ORM because the class for the `is_associated` service was a dedicated one. …

PIM-6220: Fix simple select attribute option sorting in products grid

---

src/Pim/Bundle/CatalogBundle/Resources/config/serializers_standard.yml
src/Pim/Bundle/EnrichBundle/Controller/Rest/ProductModelController.php
src/Pim/Bundle/EnrichBundle/Normalizer/ProductModelNormalizer.php
src/Pim/Bundle/EnrichBundle/Provider/Form/AttributeFormProvider.php
src/Pim/Bundle/EnrichBundle/Provider/Form/FormChainedProvider.php
src/Pim/Bundle/EnrichBundle/Provider/Form/FormProviderInterface.php
src/Pim/Bundle/EnrichBundle/Provider/Form/JobInstanceFormProvider.php
src/Pim/Bundle/EnrichBundle/Provider/Form/ProductFormProvider.php
src/Pim/Bundle/EnrichBundle/Provider/Form/ProductModelFormProvider.php
src/Pim/Bundle/EnrichBundle/Resources/config/controllers.yml
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/product_model/edit.yml
src/Pim/Bundle/EnrichBundle/Resources/config/normalizers.yml
src/Pim/Bundle/EnrichBundle/Resources/config/providers.yml
src/Pim/Bundle/EnrichBundle/Resources/config/requirejs.yml
src/Pim/Bundle/EnrichBundle/Resources/config/routing.yml
src/Pim/Bundle/EnrichBundle/Resources/config/routing/product_model.yml
src/Pim/Bundle/EnrichBundle/Resources/public/js/controller/entity-with-family-variant.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/meta/family-variant.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/product-model-label.js
src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/meta/family-variant.html
src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml
src/Pim/Bundle/EnrichBundle/spec/Normalizer/ProductModelNormalizerSpec.php

This PR is the first part of PIM-6338, which is about enriching a **root** product model in the PEF.
This PR covers only the **display of a root product model** in the PEF.
-----
What will be done in another PR?
- Display the image of the product model (need common interface for product and models)
- Display only product model attributes (need rework of generateMissing)
- Behats (need to import product models, will be easier)
-----
| Added Behats                      | N (other PR)

PIM-6338: Simply display a root product model in the PEF

---

src/Pim/Bundle/EnrichBundle/Normalizer/ProductModelNormalizer.php
src/Pim/Bundle/EnrichBundle/Resources/config/normalizers.yml
src/Pim/Bundle/EnrichBundle/spec/Normalizer/ProductModelNormalizerSpec.php
src/Pim/Component/Catalog/Model/AbstractProduct.php
src/Pim/Component/Catalog/Model/ProductModel.php
src/Pim/Component/Catalog/Model/ProductModelInterface.php
src/Pim/Component/Catalog/spec/Model/ProductModelSpec.php
src/Pim/Component/Catalog/spec/Model/ProductSpec.php

This PR adds "Attribute as image" and "Attribute as label" on product model, which then can be displayed on the PEF.
-----

PIM-6338: Display image and label on product model pef

---

src/Pim/Component/Catalog/tests/integration/Normalizer/NormalizedProductCleaner.php

This resulted to errors on CI:
1) PimEnterprise\Bundle\ApiBundle\tests\integration\Controller\ProductDraft\GetProductDraftIntegration::testGetProductDraftSuccessful
Non-static method Pim\Component\Catalog\tests\integration\Normalizer\NormalizedProductCleaner::sanitizeMediaAttributeData() should not be called statically
/home/akeneo/jenkins-workspace/workspace/_pim-enterprise-dev_PR-2982-56AOGLAMMLGCQRC2MWNFGKSA3JAER44QA7NXPN3Z4YPPXLYSFUDA/vendor/akeneo/pim-community-dev/src/Pim/Component/Catalog/tests/integration/Normalizer/NormalizedProductCleaner.php:26
/home/akeneo/jenkins-workspace/workspace/_pim-enterprise-dev_PR-2982-56AOGLAMMLGCQRC2MWNFGKSA3JAER44QA7NXPN3Z4YPPXLYSFUDA/src/PimEnterprise/Bundle/ApiBundle/tests/integration/Controller/ProductDraft/GetProductDraftIntegration.php:69 …

API: Fix NormalizedProductCleaner static function

---

app/config/pim_parameters.yml
src/Akeneo/Bundle/BatchBundle/Resources/config/services.yml
src/Pim/Bundle/InstallerBundle/Resources/config/services.yml

The log files created by the export/import are currently written in a directory that is not configurable in the "pim_parameters". 
It prevents to download a log file across several instances of the PIM.
In order to allow horizontal scalability, the directory should be configurable.
This way, the cloud team can configure the path to a shared directory between all the containers/instances of the PIM.
Note: for now, batch_execute.log is …

Api 332: logs of the import/export should be in a configurable directory for the saas

---

src/Pim/Bundle/EnrichBundle/Doctrine/ORM/Repository/JobExecutionRepository.php
src/Pim/Bundle/EnrichBundle/Doctrine/ORM/Repository/JobTrackerRepository.php

When testing exports through UI, @NolwennP had some issues: the PIM was unavailable.
The reason is that I introduced a regression with https://github.com/akeneo/pim-community-dev/pull/6306 . 
The performance was very bad by adding every column in the group by for the job repositories. The request take 18 seconds in local for an export with 50000 warning (warnings were created just for testing, in reality it does not export with warnings).
And the, the session block all the other requests of the UI (looking …

TIP-425: group by only on needed column to fix regression about performance for the jobs

---

CHANGELOG-1.8.md
app/config/pim_parameters.yml
features/attribute/option/import_attribute_options.feature
features/import/check_encoding_before_import.feature
features/product-group/create_product_group.feature
src/Pim/Bundle/EnrichBundle/Controller/Rest/JobInstanceController.php
src/Pim/Bundle/EnrichBundle/Resources/config/controllers.yml
src/Pim/Bundle/InstallerBundle/Resources/config/services.yml

Path of the imported files should be configurable in order to be consume by a queue.
This path will be shared across different instances of the PIM in the Saas. …

API-333: make the path of imported files configurable for horizontal scalability

---

src/Pim/Bundle/InstallerBundle/Command/CheckRequirementsCommand.php
src/Pim/Bundle/InstallerBundle/Command/InstallCommand.php
src/Pim/Bundle/InstallerBundle/Command/PrepareRequiredDirectoriesCommand.php

The goal of this PR is that we should be able to launch check-requirements before trying to install the PIM. This thing can be done by creating some folder during the check step. Seen with @skeleton and @jjanvier.
| Added …

MIG-23: Check requirements could be launched before an install

---

app/AppKernel.php

From Symfony's [upgrade documentation](https://github.com/symfony/symfony/blob/master/UPGRADE-3.3.md#frameworkbundle):
> The server:run, server:start, server:stop and server:status console commands have been moved to a dedicated bundle. Require symfony/web-server-bundle in your composer.json and register Symfony\Bundle\WebServerBundle\WebServerBundle in your AppKernel to use them.
The bundle is already required by composer via `symfony/symfony`.
I use a lot those commands in dev and test environments.

Enable web-server bundle

---

src/Pim/Bundle/InstallerBundle/Command/AssetsCommand.php
src/Pim/Bundle/InstallerBundle/Command/InstallCommand.php

Two new options were recently added to the "pim:install" and "pim:installer:assets" commands:
- `clean` that ensure the removal of all folders that were not present when cloning the PIM from GitHub
- `symlink` that dump assets as relative symlinks
An error has been made in the option detection: the value returned by `InputInterface::getOption` was tested against `null` when it returns a boolean value.
| Tech Doc …

Fix "symlink" and "clean" options on assets and install command

---

CHANGELOG-1.7.md
features/import/view_import_items_invalid_data.feature
src/Akeneo/Component/Batch/Step/ItemStep.php
src/Akeneo/Component/Batch/spec/Step/ItemStepSpec.php

When an import fails, the details of the invalid items are no longer displayed on the import job execution details page. (clicking on the link "Display item" does not display anything)
It's because the function `DoctrineJobRepository::insertWarning` expects an array of the invalid data of the item, and not the item itself. No error was raised because the parameter `$item` is not typed. The signature of this method will be fixed on master, because we have to add this method to the interface `JobRepositoryInterface`.
| Added …

PIM-6568: Fix import items invalid data that were no longer saved

---

features/Pim/Behat/Context/Storage/ProductModelStorage.php
features/import/product_model/import_business_rules.feature
src/Pim/Bundle/CatalogBundle/EventSubscriber/ComputeEntityRawValuesSubscriber.php
src/Pim/Bundle/CatalogBundle/EventSubscriber/LoadEntityWithValuesSubscriber.php
src/Pim/Bundle/CatalogBundle/spec/EventSubscriber/ComputeEntityRawValuesSubscriberSpec.php
src/Pim/Bundle/CatalogBundle/spec/EventSubscriber/LoadEntityWithValuesSubscriberSpec.php
src/Pim/Component/Catalog/Model/AbstractProduct.php
src/Pim/Component/Catalog/Model/EntityWithFamilyVariantInterface.php
src/Pim/Component/Catalog/Model/ProductModel.php
src/Pim/Component/Catalog/Model/VariantProduct.php
src/Pim/Component/Catalog/Validator/Constraints/OnlyExpectedAttributesValidator.php
src/Pim/Component/Catalog/spec/Model/ProductModelSpec.php
src/Pim/Component/Catalog/spec/Model/VariantProductSpec.php
src/Pim/Component/Catalog/spec/Validator/Constraints/OnlyExpectedAttributesValidatorSpec.php

For product models and variant products, the method `getValues` will return its values and the parent ones. To only get the values at the current level, you need to call `getValuesForVariation` method.

PIM-6333: rework getValue method

---

CHANGELOG-1.7.md
src/Pim/Bundle/CatalogBundle/Resources/config/doctrine/AttributeOptionValue.orm.yml
src/Pim/Bundle/CatalogBundle/Resources/config/validation/attribute.yml

The current validation is not overridable and, since 1.7, it breaks the connector with CNET for attribute option labels length.
Discussing with @jjanvier , I propose this PR to make attribute option translations longer.
I will do a second PR on next release to homogeneize translations fields and fix validation issues. …

Make attribute option field longer

---

UPGRADE-1.7.md

Some customers add the security lines about the API after the key "security.firewalls.main".
Consequently, it's not possible to access to the API.
https://github.com/akeneo/pim-api-docs/issues/70 …

Improve the upgrade file when setting the security about API

---

CHANGELOG-1.7.md
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/job_instance/xlsx_product_import_edit.yml

On the edit form of the import jobs based on "xlsx_product_import", the field "Date format" is setted as "readonly" whereas it should not.

PIM-6744: Fix field configuration of xlsx product import job edit form

---

src/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/Repository/ProductRepository.php
src/Pim/Bundle/CatalogBundle/Resources/config/model/doctrine/Product.mongodb.yml

**Context**
On a project with Mongo storage, when you delete a product, a subscriber is used to clean all associations using the deleted product.
**Problem**
The query is super long with large catalogs and can even lead to timeouts.
**Solution**
- add an index on `product.associations`
- remove the `$elemMatch` clause from the query : since we know the complete DBRef object it's overkill and it prevents the index from being used …

PIM-6757: Fix scalability issue on product deletion

---

bin/docker/pim-front.sh
bin/docker/pim-initialize.sh
docker-compose.yml.dist

There was some error in `bin/docker/*` scripts, making them impossible to run... This PR fixes them.
It updates the compose file too, changing the mapping with the composer folder on the host. This will soon be explained with details in the Dockerfiles documentation.

Fix some errors in docker helper scripts

---

behat.ci.yml
behat.yml.dist
features/Pim/Behat/Context/Storage/ProductModelStorage.php
features/import/product_model/csv/create_product_model.feature
features/import/product_model/import_business_rules.feature
src/Pim/Bundle/ConnectorBundle/Resources/config/jobs.yml
src/Pim/Bundle/ConnectorBundle/Resources/config/processors.yml
src/Pim/Bundle/ConnectorBundle/Resources/config/steps.yml
src/Pim/Bundle/ConnectorBundle/Resources/translations/messages.en.yml
src/Pim/Component/Connector/Processor/Denormalization/ProductModelProcessor.php
src/Pim/Component/Connector/spec/Processor/Denormalization/ProductModelProcessorSpec.php

Product models are like categories, a tree. We decided to create 2 steps to avoid to:
* use batch size equals to 1 
* some errors related CSV file order. For instance, it avoids error when you try to link a sub product a root product model which is in memory but not flushed.
`Todo`: …

PIM-6333: Split the import product model step

---

CHANGELOG-1.8.md
features/Context/Page/Product/Index.php
src/Pim/Bundle/ApiBundle/Command/CreateClientCommand.php
src/Pim/Bundle/ApiBundle/tests/integration/ApiTestCase.php
src/Pim/Bundle/ApiBundle/tests/integration/Command/CreateClientIntegration.php

Label is now a required argument (before it was an option) by the command and mandatory when you create a client with the command line

API-324: Convert label option to mandatory argument in  command

---

features/Context/FixturesContext.php
features/import/family_variant/csv/create_family_variant.feature
features/import/family_variant/csv/update_family_variant.feature
features/import/family_variant/xlsx/create_family_variant.feature
features/import/family_variant/xlsx/create_multiple_family_variants.feature
features/import/family_variant/xlsx/update_family_variant.feature
features/import/product_model/csv/create_product_model.feature
features/import/product_model/csv/update_product_model.feature
features/import/product_model/import_business_rules.feature
features/import/product_model/xslx/create_product_model.feature
features/import/product_model/xslx/update_product_model.feature
src/Pim/Bundle/CatalogBundle/Resources/config/comparators.yml
src/Pim/Bundle/CatalogBundle/Resources/config/filters.yml
src/Pim/Bundle/CatalogBundle/Resources/config/updaters.yml
src/Pim/Component/Catalog/Model/ProductModel.php
src/Pim/Component/Catalog/Updater/ProductModelUpdater.php
src/Pim/Component/Catalog/Validator/Constraints/UniqueValueValidator.php
src/Pim/Component/Catalog/spec/Updater/ProductModelUpdaterSpec.php
src/Pim/Component/Connector/ArrayConverter/FlatToStandard/ProductModel.php
src/Pim/Component/Connector/Processor/Denormalization/ProductModelProcessor.php

This PR ensures the update of the product models through imports.
`First commit` is a cherry pick for this PR #6511, `second commit` is only some alignments automatically performed by PHPStorm, so no real interest here.
The `third commit` adds the basic behat scenarios for update through import.
The PR adds two new business rules (with according tests):
- ensure that a parent cannot be added to a root product model (`fourth commit`),
- ensure that the variant axes values set on a product model cannot be changed once defined (`fifth commit`).
I also add a scenario to ensure that update works with `comparison` parameter enabled (included in `fifth` commit).
| Added …

PIM-6472: Update product models through imports

---

features/Context/FixturesContext.php
features/import/product_model/import_business_rules.feature
src/Pim/Bundle/CatalogBundle/EventSubscriber/ResetUniqueValidationSubscriber.php
src/Pim/Bundle/CatalogBundle/Resources/config/event_subscribers.yml
src/Pim/Bundle/CatalogBundle/Resources/config/validators.yml
src/Pim/Bundle/CatalogBundle/spec/EventSubscriber/ResetUniqueValidationSubscriberSpec.php
src/Pim/Component/Catalog/Validator/Constraints/SiblingUniqueVariantAxesValidator.php
src/Pim/Component/Catalog/Validator/UniqueAxesCombinationSet.php
src/Pim/Component/Catalog/spec/Validator/Constraints/SiblingUniqueVariantAxesValidatorSpec.php

**Only the last commit is relevent, the others come from #6569, which needs to be merged first.**
For each family variant, they can only be one entity with family variant (product model or variant product) for a specific combination of variant axes values.
To ensure that, we check that such a entity does not already exists in database (already done in previous PR), but we also need to ensure there is not one in the current batch of import.
This PR introduces a new `Pim\Component\Catalog\Validator\UniqueAxesCombinationSet`, inspired from the `Pim\Component\Catalog\Validator\UniqueValuesSet` used on the products.
It stores all the MySQL ID (or if it still has none, an object hash) of the encountered entities, associated to their axes combination and family variant code (the same combination …

PIM-6333: Do not update twice a product model in a batch

---

src/Akeneo/Component/Console/CommandLauncher.php
src/Pim/Bundle/CatalogBundle/Command/IndexProductCommand.php
src/Pim/Bundle/CatalogBundle/Command/IndexProductModelCommand.php
src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/ProductModelRepository.php
src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/ProductRepository.php
src/Pim/Bundle/CatalogBundle/EventSubscriber/IndexProductModelDescendantsSubscriber.php
src/Pim/Bundle/CatalogBundle/Resources/config/event_subscribers.yml
src/Pim/Bundle/CatalogBundle/spec/Command/IndexProductCommandSpec.php
src/Pim/Bundle/CatalogBundle/spec/Command/IndexProductModelCommandSpec.php
src/Pim/Bundle/CatalogBundle/spec/EventSubscriber/IndexProductModelDescendantsSubscriberSpec.php
src/Pim/Bundle/CatalogBundle/tests/integration/Doctrine/Common/Saver/IndexingProductModelDescendantsIntegration.php
src/Pim/Component/Catalog/Repository/ProductModelRepositoryInterface.php
src/Pim/Component/Catalog/Repository/ProductRepositoryInterface.php

- Add an argument to the command pim:product:index which let's you specify product identifiers to index
- Add a command pim:product-model:index which let's you index all product models and their descendants. You can pass the product model codes as arguments.
- Changes the ProductModelDescendantSubscriber to run the indexation of product model descendants in a background job using the command above.
**Command usages**:
Indexing products:
```
$ bin/console pim:product:index --env=prod
Please specify a list of product identifiers to index or use the flag --all to index all products
$ bin/console pim:product:index --all --env=prod
66 products to index
66 products indexed
$ bin/console pim:product:index product_1 product_2 --env=prod
Some …
```

PIM-6353: index models command

---

src/Pim/Bundle/EnrichBundle/Normalizer/CompletenessCollectionNormalizer.php
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/completeness.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/locale-switcher.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/product-completeness.js
src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/completeness.html
src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/form/product-completeness.html
src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml
src/Pim/Bundle/EnrichBundle/spec/Normalizer/CompletenessCollectionNormalizerSpec.php
src/Pim/Bundle/UIBundle/Resources/public/less/components/product-edit-form/CompletenessPanel.less
src/Pim/Bundle/UIBundle/Resources/public/less/lib/bootstrap.dropdown.less

This PR adds a little dropdown to display the completeness of the current scope, to put back the click to select attributes directly.

[PIM-6758] Add dropdown for PEF completeness

---

bin/docker/pim-front.sh
bin/docker/pim-initialize.sh
docker-compose.yml.dist

[Elasticsearch image](https://hub.docker.com/_/elasticsearch/) from Docker library is deprecated. [Official image](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html) maintained by Elasticsearch developers.
This official image is to be used with Docker Compose.
It will be used in the CI v2 too.
The PR also fixes an error in the helper script, introduced when merging 1.7 into master.
| Tech Doc …

Use official Elasticsearch docker image

---

src/Pim/Component/Catalog/Validator/Constraints/SiblingUniqueVariantAxesValidator.php
src/Pim/Component/Catalog/Validator/UniqueAxesCombinationSet.php
src/Pim/Component/Catalog/spec/Validator/Constraints/SiblingUniqueVariantAxesValidatorSpec.php
src/Pim/Component/Catalog/spec/Validator/UniqueAxesCombinationSetSpec.php

The newly introduced `UniqueAxesCombinationSet` was wrong as it stored axes combinations only according to family variants. However, there can be several root product models for the same family variant, so several time the same axes combination for a family variant.
This PR updates the `UniqueAxesCombinationSet` so axes combination are now stored according to family variant and parent. …

PIM-6333: Fix "UniqueAxesCombinationSet"

---

src/Pim/Bundle/ApiBundle/Command/ListClientsCommand.php
src/Pim/Bundle/ApiBundle/Resources/config/doctrine/AccessToken.orm.yml
src/Pim/Bundle/ApiBundle/tests/integration/Client/RevokeTokenIntegration.php
upgrades/schema/Version_1_8_20170821122627_add_client_in_access_token_table.php

API-351: Instantly revoke access token on client delete

---

src/Akeneo/Bundle/ElasticsearchBundle/Cursor/AbstractCursor.php
src/Pim/Bundle/CatalogBundle/Elasticsearch/Filter/Field/ParentFilter.php
src/Pim/Bundle/CatalogBundle/Resources/config/query_builders.yml
src/Pim/Bundle/CatalogBundle/spec/Elasticsearch/Filter/Field/ParentFilterSpec.php
src/Pim/Bundle/CatalogBundle/tests/integration/Elasticsearch/IndexConfiguration/AbstractPimCatalogProductModelIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/Elasticsearch/IndexConfiguration/SearchProductsAndModelsIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/Elasticsearch/IndexConfiguration/SearchProductsIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/PQB/ProductAndProductModelQueryBuilderIntegration.php
src/Pim/Bundle/EnrichBundle/Elasticsearch/FromSizeCursor.php
src/Pim/Bundle/EnrichBundle/ProductQueryBuilder/ProductAndProductModelQueryBuilder.php
src/Pim/Bundle/EnrichBundle/spec/Elasticsearch/FromSizeCursorSpec.php
src/Pim/Bundle/EnrichBundle/spec/ProductQueryBuilder/ProductAndProductModelQueryBuilderSpec.php
src/Pim/Component/Catalog/Normalizer/Indexing/ProductAndProductModel/ProductModelNormalizer.php
src/Pim/Component/Catalog/Normalizer/Indexing/ProductAndProductModel/ProductModelPropertiesNormalizer.php
src/Pim/Component/Catalog/Normalizer/Indexing/ProductAndProductModel/ProductNormalizer.php
src/Pim/Component/Catalog/Normalizer/Indexing/ProductAndProductModel/ProductPropertiesNormalizer.php
src/Pim/Component/Catalog/spec/Normalizer/Indexing/ProductAndProductModel/ProductModelNormalizerSpec.php
src/Pim/Component/Catalog/spec/Normalizer/Indexing/ProductAndProductModel/ProductModelPropertiesNormalizerSpec.php
src/Pim/Component/Catalog/spec/Normalizer/Indexing/ProductAndProductModel/ProductNormalizerSpec.php
src/Pim/Component/Catalog/spec/Normalizer/Indexing/ProductAndProductModel/ProductPropertiesNormalizerSpec.php
src/Pim/Component/Catalog/tests/integration/Normalizer/Indexing/ProductAndProductModelIndexingIntegration.php

*Easier to read commit by commit*
The goal of this is PR is to be able, with the product and product model query builder, to display by default only entities without a parent. Soon, in the product datagrid, we'll see only the root product models and the non variant products.
For that we:
- indexed the parent code of the product models and variant products
- defined a new filter on this parent field
This PR also fixes a few glitches:
- one about numeric identifiers and our Elasticsearch cursors (basically, a product with identifier 12345 was never returned)
- simplify the "product_type" in the product and product model index
| …

PIM-6353: filter by default products and product models that don't have a parent

---

Jenkinsfile
src/Akeneo/Bundle/BatchBundle/CHANGELOG.md
src/Akeneo/Bundle/BatchBundle/Command/BatchCommand.php
src/Akeneo/Bundle/BatchBundle/EventListener/LoadJobParametersListener.php
src/Akeneo/Bundle/BatchBundle/Job/DoctrineJobRepository.php
src/Akeneo/Bundle/BatchBundle/Launcher/SimpleJobLauncher.php
src/Akeneo/Bundle/BatchBundle/Resources/config/model/doctrine/JobExecution.orm.yml
src/Akeneo/Bundle/BatchBundle/Resources/config/services.yml
src/Akeneo/Bundle/BatchBundle/spec/EventListener/LoadJobParametersListenerSpec.php
src/Akeneo/Component/Batch/Job/JobParametersFactory.php
src/Akeneo/Component/Batch/Model/JobExecution.php
src/Akeneo/Component/Batch/spec/Job/JobParametersFactorySpec.php
src/Akeneo/Component/Batch/spec/Model/JobExecutionSpec.php
src/Pim/Bundle/ConnectorBundle/Launcher/AuthenticatedJobLauncher.php
tests/integration/BatchBundle/Command/BatchCommandIntegration.php
tests/integration/BatchBundle/Job/DoctrineJobRepositoryIntegration.php

When you launch a job instance, a job execution is created.
The configuration  of this job execution  can be overridden on the fly, and there is no way to find the configuration in database because it's not stored in DB.
To be able to launch job executions in background, we have to:
- make a job execution immutable: not possible to specify a config when launching a job execution, only when we launch a job instance
- store the job parameters in database
[//]: <> (What does this Pull Request do? reference the …

API-334: store job parameters into database

---

src/Akeneo/Bundle/ElasticsearchBundle/Client.php
tests/FixturesLoader.php
tests/TestCase.php

The integration test `Pim\Component\Catalog\tests\integration\Normalizer\Standard\FamilyVariantIntegration` is currently failing on the CI. The problem came from ES index that still exists when it should not, resulting in the following error:
```bash
Elasticsearch\Common\Exceptions\BadRequest400Exception: {"error":{"root_cause":[{"type":"index_already_exists_exception","reason":"index [behat_akeneo_pim_product_and_product_model/qejbJFXvRUaddXfXJyyJ4w] already exists","index_uuid":"qejbJFXvRUaddXfXJyyJ4w","index":"behat_akeneo_pim_product_and_product_model"}],"type":"index_already_exists_exception","reason":"index [behat_akeneo_pim_product_and_product_model/qejbJFXvRUaddXfXJyyJ4w] already exists","index_uuid":"qejbJFXvRUaddXfXJyyJ4w","index":"behat_akeneo_pim_product_and_product_model"},"st …
```

Fix family variant integration test

---

CHANGELOG-1.7.md
features/import/upload_and_import_products_with_media.feature
src/Pim/Bundle/EnrichBundle/Controller/Rest/JobInstanceController.php
src/Pim/Bundle/EnrichBundle/Resources/public/js/job/common/edit/upload-launch.js

This PR fixes a regression between 1.6 and 1.7 : on 1.7 the controller has been replaced and the validation groups were forgotten, so it was possible to upload a file with a unsupported extension and launch the import (which failed with no message in the UI). …

PIM-6491: Fix file extension validation on import job upload

---

CHANGELOG-1.8.md
src/Pim/Bundle/CatalogBundle/DependencyInjection/PimCatalogExtension.php
src/Pim/Bundle/CatalogBundle/Resources/config/builders.yml
src/Pim/Bundle/CatalogBundle/Resources/config/values_fillers.yml
src/Pim/Bundle/ConnectorBundle/Resources/config/processors.yml
src/Pim/Bundle/EnrichBundle/Connector/Processor/QuickExport/ProductProcessor.php
src/Pim/Bundle/EnrichBundle/Controller/ProductController.php
src/Pim/Bundle/EnrichBundle/Normalizer/ProductNormalizer.php
src/Pim/Bundle/EnrichBundle/Resources/config/connector/processors.yml
src/Pim/Bundle/EnrichBundle/Resources/config/controllers.yml
src/Pim/Bundle/EnrichBundle/Resources/config/normalizers.yml
src/Pim/Bundle/EnrichBundle/spec/Normalizer/ProductNormalizerSpec.php
src/Pim/Component/Catalog/Builder/ProductBuilder.php
src/Pim/Component/Catalog/Builder/ProductBuilderInterface.php
src/Pim/Component/Catalog/Builder/ProductTemplateBuilder.php
src/Pim/Component/Catalog/Model/AbstractProduct.php
src/Pim/Component/Catalog/Model/EntityWithFamilyInterface.php
src/Pim/Component/Catalog/Model/EntityWithFamilyVariantInterface.php
src/Pim/Component/Catalog/Model/ProductInterface.php
src/Pim/Component/Catalog/Model/ProductModel.php
src/Pim/Component/Catalog/ValuesFiller/EntityWithFamilyValuesFillerInterface.php
src/Pim/Component/Catalog/ValuesFiller/ProductValuesFiller.php
src/Pim/Component/Catalog/spec/Builder/EntityWithValuesBuilderSpec.php
src/Pim/Component/Catalog/spec/Builder/ProductBuilderSpec.php
src/Pim/Component/Catalog/spec/Builder/ProductTemplateBuilderSpec.php
src/Pim/Component/Catalog/spec/ValuesFiller/ProductValuesFillerSpec.php
src/Pim/Component/Connector/Processor/Normalization/ProductProcessor.php
src/Pim/Component/Connector/spec/Processor/Normalization/ProductProcessorSpec.php

This PR does 2 things:
- Create a new interface `EntityWithFamilyInterface`. It's now the common interface between **products**, **variant products** and **product models**.
- Extract the logic of filling missing attributes on a product (currently in the product builder) in a dedicated service.

PIM-6338: extract "fill missing attributes" logic

---

CHANGELOG-1.8.md
src/Pim/Bundle/ApiBundle/Controller/ProductController.php
src/Pim/Bundle/CatalogBundle/Resources/config/filters.yml
src/Pim/Component/Catalog/Comparator/Filter/ProductFieldFilter.php
src/Pim/Component/Catalog/Comparator/Filter/ProductFilter.php
src/Pim/Component/Catalog/spec/Comparator/Filter/ProductFieldFilterSpec.php
src/Pim/Component/Catalog/spec/Comparator/Filter/ProductFilterSpec.php

Extract product's fields from ProductFilter to be able to use this new Filter on EE
| Micro …

API-91: extract product's fields from productFilter

---

features/Context/CatalogConfigurationContext.php
features/mass-action/mass_edit_products_and_product_models.feature
features/product/filtering/filter_products_and_product_models.feature
src/Pim/Bundle/DataGridBundle/Normalizer/ProductModelNormalizer.php
src/Pim/Bundle/DataGridBundle/Normalizer/ProductNormalizer.php
src/Pim/Bundle/DataGridBundle/spec/Normalizer/ProductModelNormalizerSpec.php
src/Pim/Bundle/DataGridBundle/spec/Normalizer/ProductNormalizerSpec.php
src/Pim/Bundle/EnrichBundle/DependencyInjection/PimEnrichExtension.php
src/Pim/Bundle/EnrichBundle/Extension/Action/Actions/NavigateProductAndProductModelAction.php
src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/product.yml
src/Pim/Bundle/EnrichBundle/Resources/config/datagrid_actions.yml
src/Pim/Bundle/EnrichBundle/Resources/config/requirejs.yml
src/Pim/Bundle/EnrichBundle/Resources/public/js/datagrid/action/navigate-product-and-product-model-action.js

2 commits for 2 different things: 
1. be able to redirect to the product or product model form on the datagrid. The other actions than edit (delete and toggle status) are **NOT** taken into account in this PR. It will be done in another PR. 
2. mass actions on products and product models: it only prepares the datagrid to be able to work with product models. It also allows our current Behats on products to be green. The mass edit actions (like edit common attributes) do **NOT** work on this branch. It will be handled in a dedicated story.
| Review and …

PIM-6352: link to edit product models & mass actions

---

features/product-model/edit_product_model.feature
src/Pim/Bundle/CatalogBundle/Resources/config/values_fillers.yml
src/Pim/Bundle/EnrichBundle/Normalizer/ProductModelNormalizer.php
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/product_model/edit.yml
src/Pim/Bundle/EnrichBundle/Resources/config/normalizers.yml
src/Pim/Bundle/EnrichBundle/Resources/config/requirejs.yml
src/Pim/Bundle/EnrichBundle/Resources/public/js/product-model/form/attributes/read-only-parent-attributes.js
src/Pim/Bundle/EnrichBundle/spec/Normalizer/ProductModelNormalizerSpec.php
src/Pim/Component/Catalog/FamilyVariant/EntityWithFamilyVariantAttributesProvider.php
src/Pim/Component/Catalog/ValuesFiller/AbstractEntityWithFamilyValuesFiller.php
src/Pim/Component/Catalog/ValuesFiller/EntityWithFamilyVariantValuesFiller.php
src/Pim/Component/Catalog/ValuesFiller/ProductValuesFiller.php
src/Pim/Component/Catalog/spec/ValuesFiller/EntityWithFamilyVariantValuesFillerSpec.php

This PR fills in missing attributes when normalizing a product model.
On the PEF, it locks (read only) the attributes coming for parents.

PIM-6338: display only level attributes of product model

---

features/product-model/edit_product_model.feature
src/Pim/Bundle/EnrichBundle/Normalizer/ProductModelNormalizer.php
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/product_model/edit.yml
src/Pim/Bundle/EnrichBundle/Resources/config/requirejs.yml
src/Pim/Bundle/EnrichBundle/Resources/public/js/product-model/form/attributes/variant-axes.js
src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml
src/Pim/Bundle/EnrichBundle/spec/Normalizer/ProductModelNormalizerSpec.php

This PR adds more business to the enrich of sub product models, such as:
- Adding a message under attributes coming from parent in the PEF
- Locking variant axis (and add message)
- Fix title of the PEF when editing a product model

PIM-6669: enrich a sub product model

---

src/Pim/Bundle/CatalogBundle/Resources/config/validation/variantproduct.yml
src/Pim/Bundle/CatalogBundle/Resources/translations/validators.en.yml
src/Pim/Bundle/CatalogBundle/tests/integration/Product/VariantProductIntegration.php
src/Pim/Component/Catalog/Validator/Constraints/SameFamilyThanParentValidator.php
src/Pim/Component/Catalog/Validator/Constraints/VariantProductParent.php
src/Pim/Component/Catalog/Validator/Constraints/VariantProductParentValidator.php
src/Pim/Component/Catalog/spec/Validator/Constraints/VariantProductParentValidatorSpec.php

Variant products contain the values corresponding to the variant axes of the last variation level. As for the sub product models, these values must be unique.
To ensure that, this PR adds to the variant products the same `SiblingUniqueVariantAxes` that is already used for product models.
It also adds a missing validation on variant product => ensure that the variant product has a parent!
| Tech Doc                          | …

PIM-6335: Variant products must have unique variant values

---

features/product/filtering/filter_products_per_date_fields.feature
features/product/filtering/filter_products_per_media.feature
features/product/filtering/filter_products_per_number_fields.feature
features/product/filtering/filter_products_per_option_fields.feature
features/product/filtering/filter_products_per_text_fields.feature
features/reference-data/product/filtering/filtering_by_multi_reference_data.feature
features/reference-data/product/filtering/filtering_by_reference_data.feature
features/reference-data/product/filtering/filtering_by_reference_data_with_locale_and_scope.feature
src/Pim/Bundle/CatalogBundle/Elasticsearch/Filter/Field/LabelOrIdentifierFilter.php
src/Pim/Component/Catalog/Model/ProductModel.php
src/Pim/Component/Catalog/Normalizer/Indexing/ProductAndProductModel/ProductModelPropertiesNormalizer.php
src/Pim/Component/Catalog/Normalizer/Indexing/ProductAndProductModel/ProductPropertiesNormalizer.php
src/Pim/Component/Catalog/spec/Model/ProductModelSpec.php
src/Pim/Component/Catalog/spec/Normalizer/Indexing/ProductAndProductModel/ProductModelPropertiesNormalizerSpec.php
src/Pim/Component/Catalog/spec/Normalizer/Indexing/ProductAndProductModel/ProductPropertiesNormalizerSpec.php

- Not empty in the datagrid does not show products that don't have the attribute.
- Add Label property in the Product and product model index
**Fixes behats:**
features/product/filtering/filter_products_per_date_fields.feature
features/product/filtering/filter_products_per_media.feature
features/product/filtering/filter_products_per_number_fields.feature
features/product/filtering/filter_products_per_option_fields.feature
features/product/filtering/filter_products_per_text_fields.feature
features/reference-data/product/filtering/filtering_by_multi_reference_data.feature
features/reference-data/product/filtering/filtering_by_reference_data.feature
features/reference-data/product/filtering/filtering_by_reference_data_with_locale_and_scope. …

PIM-6352: Fix broken behats regarding grid filtering

---

app/config/config_prod.yml

Re-active the apcu cache (previously deactivated in a PR @jjanvier, who introduces a chain provider).
Activated only in prod because in dev/behat env, it would implies to restart apache as soon as you modify about Doctrine metadata.
Before (check time to get the repository, not normal):
https://blackfire.io/profiles/85442247-1ada-4aad-99fa-f2f94a8fd0fa/graph?settings%5Bdimension%5D=wt&settings%5Bdisplay%5D=landscape&settings%5BtabPane%5D=nodes&selected=Doctrine%5CORM%5CRepository%5CDefaultRepositoryFactory%3A%3AgetRepository&callname=main()
After:
https://blackfire.io/profiles/61af15bb-8ed9-4d39-9eec-51ab1e0e812d/graph?settings%5Bdimension%5D=wt&settings%5Bdisplay%5D=landscape&settings%5BtabPane%5D=nodes&selected=&callname=main() …

(Re) Active apcu cache for Doctrine in prod

---

features/mass-action/add_products_to_variant_groups.feature
features/mass-action/mass_edit_variant_group_products.feature
src/Pim/Bundle/EnrichBundle/DependencyInjection/PimEnrichExtension.php
src/Pim/Bundle/EnrichBundle/Elasticsearch/AbstractCursor.php
src/Pim/Bundle/EnrichBundle/Elasticsearch/Cursor.php
src/Pim/Bundle/EnrichBundle/Elasticsearch/CursorFactory.php
src/Pim/Bundle/EnrichBundle/Elasticsearch/FromSizeCursor.php
src/Pim/Bundle/EnrichBundle/Elasticsearch/IdentifierResult.php
src/Pim/Bundle/EnrichBundle/Elasticsearch/IdentifierResults.php
src/Pim/Bundle/EnrichBundle/Resources/config/query_builders.yml
src/Pim/Bundle/EnrichBundle/Resources/config/readers.yml
src/Pim/Bundle/EnrichBundle/Resources/config/steps.yml
src/Pim/Bundle/EnrichBundle/spec/Elasticsearch/CursorFactorySpec.php
src/Pim/Bundle/EnrichBundle/spec/Elasticsearch/CursorSpec.php
src/Pim/Bundle/EnrichBundle/spec/Elasticsearch/FromSizeCursorSpec.php
src/Pim/Bundle/EnrichBundle/spec/Elasticsearch/IdentifierResultSpec.php
src/Pim/Bundle/EnrichBundle/spec/Elasticsearch/IdentifierResultsSpec.php
src/Pim/Component/Catalog/Model/ProductModel.php

At the moment, on the `PIM-6352` branch, the datagrid is able to display both products and product models because we introduced a new query builder factory: the `pim_enrich.query.product_and_product_model_query_builder_from_size_factory`. Internally, with a cursor, it tells Elasticsearch to look for X "things" (size) from the Yth "thing" (from). And that allows us to select any product or product model to be able to launch a mass actions.
But when a mass action is launched, this is the `pim_catalog.query.product_query_builder_factory` that is used through `pim_connector.reader.database.product` (with the refactoring of Juju, the mass actions uses the PQB to filter products according to their ID). Which means, before this PR, the mass actions where looking for products only.
So this PR:
- …

PIM-6352: product and product model query builder for mass actions

---

CHANGELOG-1.8.md
src/Pim/Bundle/ApiBundle/Controller/ProductController.php
src/Pim/Bundle/ApiBundle/Documentation.php
src/Pim/Bundle/ApiBundle/Resources/config/controllers.yml
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/ErrorListProductIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/ListProductWithCompletenessIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/SuccessLargeAndOrderedListProductIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/SuccessListProductIntegration.php
src/Pim/Component/Api/Pagination/SearchAfterHalPaginator.php
src/Pim/Component/Api/spec/Pagination/SearchAfterHalPaginatorSpec.php

At the beginning of the 1.8 when elasticsearch was used to get products, we removed the pagination_type `offset` (or `page`), because elasticsearch forbidden to process more than 10000 items, it sends this exception: 
`Result window is too large, from + size must be less than or equal to: [10000] but was [10050]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting.`
To be able to continue to browse the pages (to be able to access on the next page and the **previous** page), we twisted (a lot) the `search_after` pagination type. 
The code was horrible to code and even more to understand.
After a discussion with …

API-348: reactive "offset" pagination type on the API 

---

features/product/sequential_edit/sequential_edit_product_and_product_model.feature
src/Pim/Bundle/EnrichBundle/Controller/SequentialEditController.php

This PR is a small patch that prevents editing products having the same id that product models selected in the datagrid.
It enables this by filtering the ids of the rows selected in the datagrid (removing the product model ids).
This patch will be reworked in an upcoming PR that makes the sequential edit work for product models as well (https://akeneo.atlassian.net/browse/PIM-6360). …

PIM-6352: Make the sequential work for products

---

features/mass-action/mass_edit_variant_group_products.feature
features/product/choose_and_order_products_grid_columns.feature
features/product/filtering/filter_products_per_metric.feature
features/product/filtering/filter_products_per_price.feature

Todo:
features/product/filtering/reset_product_filters.feature:33 !
features/product/filtering/reset_product_filters.feature:20 !
features/product/filtering/reset_product_filters.feature:51 !
-> step IResetTheGrid not working because the "reset" button is out of the browser scope (not shown). So the browser does not manage to click on it. 
This scenario passes on catalog-modeling => it should have a different CSS that makes it pass.
**Fixed behats:**
features/mass-action/mass_edit_variant_group_products.feature:38 .
features/product/filtering/filter_products_per_price.feature:24 .
features/mass-action/mass_edit_variant_group_products.feature:69 .
features/product/filtering/filter_products_per_metric.feature:24 . …

PIM-6352:  fix more behats 

---

src/Pim/Bundle/EnrichBundle/Normalizer/ProductModelNormalizer.php
src/Pim/Bundle/EnrichBundle/spec/Normalizer/ProductModelNormalizerSpec.php

I don't know why I did work before, but if there is null as data for image, the normalization of product model was failing.. now it's fixed, we check for null data too.

Fix normalization of a product model with null data for image

---

src/Pim/Component/Catalog/Normalizer/Indexing/ProductAndProductModel/ProductModelPropertiesNormalizer.php
src/Pim/Component/Catalog/Normalizer/Indexing/ProductAndProductModel/ProductPropertiesNormalizer.php
src/Pim/Component/Catalog/spec/Normalizer/Indexing/ProductAndProductModel/ProductModelPropertiesNormalizerSpec.php
src/Pim/Component/Catalog/spec/Normalizer/Indexing/ProductAndProductModel/ProductPropertiesNormalizerSpec.php

Juju recently reverted the search on labels on master.
During the merge of master into our branch, I forgot to clean the normalization for the grid.
Sorry for that.

PIM-6621: fix revert of labels for products

---

CHANGELOG-1.8.md
src/Pim/Bundle/CatalogBundle/Resources/config/model/doctrine/Product.orm.yml
src/Pim/Bundle/CatalogBundle/Resources/config/model/doctrine/ProductUniqueData.orm.yml

Fix issue #6657 
In ProductUniqueData, add inversedBy for the _Product Relation_
In Product, add inversedBy for the _categories_ relation and _groups_
Update CHANGELOG
```
[Mapping]  OK - The mapping files are correct.
[Database] OK - The database schema is in sync with the mapping files.
``` …

GITHUB-6657: Fix mapping for Product and ProductUniqueData

---

src/Pim/Bundle/CatalogBundle/tests/integration/Product/CreateProductModelIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/Product/CreateVariantProductIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/Product/UpdateProductModelIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/Product/UpdateVariantProductIntegration.php
src/Pim/Component/Catalog/Updater/FamilyVariantUpdater.php
src/Pim/Component/Catalog/Updater/ProductModelUpdater.php
src/Pim/Component/Catalog/Updater/Setter/ParentFieldSetter.php
src/Pim/Component/Catalog/Validator/Constraints/NotEmptyVariantAxesValidator.php
src/Pim/Component/Catalog/spec/Updater/ProductModelUpdaterSpec.php
src/Pim/Component/Catalog/spec/Updater/Setter/ParentFieldSetterSpec.php
tests/TestCase.php

This PR ensure the immutability of some fields:
- on product models:
- family_variant
- parent
- on variant products:
- family
- parent
This will be removed in the future by allowing user to change parent and family/family variant, while managing all the side effects it implies. So meanwhile, we must ensure they really are immutable.
`OK`: …

PIM-6743: Immutable fields on product models and variant products

---

features/import/product_model/import_business_rules.feature
src/Akeneo/Component/Batch/Model/StepExecution.php
src/Akeneo/Component/Batch/spec/Model/StepExecutionSpec.php
src/Pim/Bundle/CatalogBundle/tests/integration/Product/CreateProductModelIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/Product/UpdateProductModelIntegration.php
src/Pim/Bundle/ConnectorBundle/Resources/translations/messages.en.yml
src/Pim/Component/Catalog/Updater/ProductModelUpdater.php
src/Pim/Component/Catalog/spec/Updater/ProductModelUpdaterSpec.php
src/Pim/Component/Connector/ArrayConverter/FlatToStandard/Product.php
src/Pim/Component/Connector/ArrayConverter/FlatToStandard/ProductModel.php
src/Pim/Component/Connector/Processor/Denormalization/ProductModelProcessor.php
src/Pim/Component/Connector/spec/ArrayConverter/FlatToStandard/ProductModelSpec.php
src/Pim/Component/Connector/spec/Processor/Denormalization/ProductModelProcessorSpec.php

This PR brings a few enhancements to existing product model creation/update.
- **first commit**: during import, non existing fields are handled the same way than for products, with the same error message
- **second commit**: fix the behavior of the previous PR #6686 after talking with @Delphineray => no more decrement of read product model, but a clear message indicating some have been skipped (product models with parent during the first step, product models without parent during the second)
- **third commit**: add some new business rules to fit with the variant product ones:
- a sub product model can be imported without variant family, and will in this case inherit the one from its parent
- if a family variant is specified for a sub product model, it cannot be different from the one of …

PIM-6333: Import product model enhancements

---

src/Pim/Bundle/EnrichBundle/Controller/Rest/ProductModelController.php
src/Pim/Bundle/EnrichBundle/Resources/config/acl.yml
src/Pim/Bundle/EnrichBundle/Resources/config/acl_groups.yml
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/product_model/edit.yml
src/Pim/Bundle/EnrichBundle/Resources/translations/messages.en.yml

This PR fixes some feedbacks from the product owner regarding PIM-6338 and PIM-6669:
- Remove the "delete" button
- Hide the tabs "categories" and "history" managed in other stories
- ACLs

PIM-6338: fix feedback from product owner

---

features/import/product_model/import_business_rules.feature
src/Pim/Bundle/CatalogBundle/Resources/config/updaters.yml
src/Pim/Bundle/CatalogBundle/Resources/config/validation/productmodel.yml
src/Pim/Bundle/CatalogBundle/Resources/config/validation/variantproduct.yml
src/Pim/Bundle/CatalogBundle/Resources/config/validators.yml
src/Pim/Bundle/CatalogBundle/Resources/translations/validators.en.yml
src/Pim/Bundle/CatalogBundle/tests/integration/Product/UpdateProductModelIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/Product/UpdateVariantProductIntegration.php
src/Pim/Component/Catalog/Updater/ProductModelUpdater.php
src/Pim/Component/Catalog/Validator/Constraints/ImmutableVariantAxesValues.php
src/Pim/Component/Catalog/Validator/Constraints/ImmutableVariantAxesValuesValidator.php
src/Pim/Component/Catalog/spec/Updater/ProductModelUpdaterSpec.php
src/Pim/Component/Catalog/spec/Validator/Constraints/ImmutableVariantAxesValuesSpec.php
src/Pim/Component/Catalog/spec/Validator/Constraints/ImmutableVariantAxesValuesValidatorSpec.php

This PRs adds a new set of business rules specific on variant product update.
- **first commit**: a variant product cannot loose its parent
- **second commit**: the values of the variant axes of a variant products are immutable, like for the product model.
This second commit introduces a dedicated validator that can work both on variant product and product models. To avoid duplication, it is applied on both, and previous validation on product model, that was done in the product model updater, has been removed. …

PIM-6743: Add variant product business rules for update

---

features/import/variant_product/import_business_rules.feature
products.csv
src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/EntityWithFamilyVariantRepository.php
src/Pim/Bundle/CatalogBundle/Resources/config/model/doctrine/FamilyVariant.orm.yml
src/Pim/Bundle/CatalogBundle/Resources/config/repositories.yml
src/Pim/Bundle/CatalogBundle/Resources/config/validators.yml
src/Pim/Bundle/CatalogBundle/Resources/translations/validators.en.yml
src/Pim/Bundle/CatalogBundle/spec/Elasticsearch/Indexer/ProductModelDescendantsIndexerSpec.php
src/Pim/Bundle/CatalogBundle/tests/helper/EntityBuilder.php
src/Pim/Bundle/CatalogBundle/tests/integration/Doctrine/Common/Saver/IndexingProductModelDescendantsIntegration.php
src/Pim/Component/Catalog/Repository/EntityWithFamilyVariantRepositoryInterface.php
src/Pim/Component/Catalog/Updater/ProductUpdater.php
src/Pim/Component/Catalog/Validator/Constraints/SiblingUniqueVariantAxesValidator.php
src/Pim/Component/Catalog/Validator/Constraints/VariantProductParentValidator.php
src/Pim/Component/Catalog/spec/Model/FamilyVariantSpec.php
src/Pim/Component/Catalog/spec/Model/VariantAttributeSetSpec.php
src/Pim/Component/Catalog/spec/Validator/Constraints/SiblingUniqueVariantAxesValidatorSpec.php
src/Pim/Component/Catalog/spec/Validator/Constraints/VariantProductParentValidatorSpec.php
src/Pim/Component/Connector/spec/Processor/Denormalization/AttributeFilter/ProductModelAttributeFilterSpec.php

This PR fixes some typo, where variant products were refered as "product variant".

PIM-6335: Fix naming typo on variant products

---

features/import/variant_product/import_business_rules.feature
products.csv
src/Akeneo/Component/StorageUtils/Exception/InvalidPropertyException.php
src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/EntityWithFamilyVariantRepository.php
src/Pim/Bundle/CatalogBundle/Resources/config/model/doctrine/FamilyVariant.orm.yml
src/Pim/Bundle/CatalogBundle/Resources/config/repositories.yml
src/Pim/Bundle/CatalogBundle/Resources/config/validators.yml
src/Pim/Bundle/CatalogBundle/Resources/translations/validators.en.yml
src/Pim/Bundle/CatalogBundle/spec/Elasticsearch/Indexer/ProductModelDescendantsIndexerSpec.php
src/Pim/Bundle/CatalogBundle/tests/helper/EntityBuilder.php
src/Pim/Bundle/CatalogBundle/tests/integration/Doctrine/Common/Saver/IndexingProductModelDescendantsIntegration.php
src/Pim/Component/Catalog/Repository/EntityWithFamilyVariantRepositoryInterface.php
src/Pim/Component/Catalog/Updater/ProductUpdater.php
src/Pim/Component/Catalog/Updater/Setter/ParentFieldSetter.php
src/Pim/Component/Catalog/Validator/Constraints/SiblingUniqueVariantAxesValidator.php
src/Pim/Component/Catalog/Validator/Constraints/VariantProductParentValidator.php
src/Pim/Component/Catalog/spec/Model/FamilyVariantSpec.php
src/Pim/Component/Catalog/spec/Model/VariantAttributeSetSpec.php
src/Pim/Component/Catalog/spec/Updater/Setter/ParentFieldSetterSpec.php
src/Pim/Component/Catalog/spec/Validator/Constraints/SiblingUniqueVariantAxesValidatorSpec.php
src/Pim/Component/Catalog/spec/Validator/Constraints/VariantProductParentValidatorSpec.php
src/Pim/Component/Connector/spec/Processor/Denormalization/AttributeFilter/ProductModelAttributeFilterSpec.php

Before this PR, it was already not possible to set a parent to a regular product, but an `InvalidObjectException` was thrown, which is not caught by our import/export stack. So such an attempt to transform a regular product into a variant one resulted in the failure of the import.
We now throw an `InvalidPropertyException`, which allows us to skip the product without the import failing.  …

PIM-6743: Prevent a regular product to become a variant one

---

features/import/product_model/import_business_rules.feature
src/Pim/Component/Connector/Processor/Denormalization/AttributeFilter/ProductModelAttributeFilter.php

During product model import, we filter the flat data to keep only values that should be here, like for products. It means we keep only values corresponding to attribute declared on the variant attribute set.
Problem was the filter didn't handle the case where sub product models were imported without family variant. This PR fixes the problem by using the family variant of the parent when needed.
| Tech Doc …

PIM-6333: Fix sub product model import

---

CHANGELOG-1.5.md
features/filter/identifier.feature
features/filter/string.feature
src/Oro/Bundle/FilterBundle/Filter/StringFilter.php
src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Filter/StringFilter.php

Using a filter with special char like % or _ does not work because it uses the SQL operator LIKE. To avoid this problem, we need to escape the value gave to the filter.
| Added integration tests           | no

PIM-6792: Issue on Filter when using Underscore

---

features/product-model/navigate_product_and_product_model_edit_page.feature
features/product/filtering/filter_products_and_product_models.feature
features/product/sequential_edit/sequential_edit_product_and_product_model.feature

This PR adds a dirty fix (that will removed PIM-6574) to prevent some behat because a datagrid filter is not accessible without scrolling.

Fix behat datagrid scroll

---

.gitignore
bin/docker/pim-dependencies.sh
bin/docker/pim-front.sh
bin/docker/pim-initialize.sh

This PR removes the execution of `npm install` from the script `bin/docker/pim-initialize.sh`, and put it in a new script `bin/docker/pim-dependencies.sh` with `composer update`.
This way, a developer can choose to install the PIM dependencies or not, before launching an install.

Extract dependencies install into a new Docker script helper

---

src/Akeneo/Bundle/BatchBundle/Command/ListJobsCommand.php

The command "akeneo:batch:list-jobs" is broken because it uses the Symfony table helper which is deprecated since Symfony 2.5 and has been removed since 3.0
We have to use directly the class `Table` instead. cf : http://symfony.com/doc/current/components/console/helpers/tablehelper.html …

Fix list jobs command

---

src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/PartialUpdateListProductIntegration.php
src/Pim/Component/Api/tests/integration/Normalizer/ProductNormalizerIntegration.php
src/Pim/Component/Catalog/tests/integration/Normalizer/Standard/ProductStandardIntegration.php

This PR fixes a few integration tests broken by the adding of variant product export.

PIM-6336: Add expected parent key to integration tests

---

CHANGELOG-1.7.md
features/attribute/option/sort_attribute_options.feature
src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filters-manager.js

When you open the "Asset manager" from the PEF, the selection "Manage filter" does not appear. It happens because this element was displayed behind the popin.

PIM-6804: "Manage Assets" Filter not working for products containing "Asset Collection attributes"

---

src/Akeneo/Component/StorageUtils/Repository/BaseCachedObjectRepository.php
src/Akeneo/Component/StorageUtils/spec/Repository/BaseCachedObjectRepositorySpec.php
src/Pim/Bundle/CatalogBundle/Resources/config/localization/presenters.yml
src/Pim/Component/Catalog/Localization/Presenter/PresenterRegistry.php
src/Pim/Component/Catalog/spec/Localization/Presenter/PresenterRegistrySpec.php

Issue PIM-6809.
This PR includes @ahocquard commits, as well as some comment to go further:
- @ahocquard changes improve by 30%
Two other potential improvements:
- the grid data is loaded twice, removing one of the load would improve the performances by 50% ;)
- the normalizer for the grid uses the common serializer, which takes ~10% of the total time to find the right normalizer via the `supportsNormalization` calls to all registered normalizer
| …

PIM-6809 - Improve grid perf by using attribute cache for presenters

---

features/Context/FixturesContext.php
features/Context/WebUser.php
features/Context/catalog/catalog_modeling/groups.csv
features/mass-action/mass_edit_products_and_product_models.feature
features/mass-action/quick_export_products_and_product_models.feature
src/Pim/Bundle/CatalogBundle/tests/integration/PQB/ProductAndProductModelQueryBuilderIntegration.php
src/Pim/Bundle/EnrichBundle/Connector/Reader/MassEdit/FilteredProductAndProductModelReader.php
src/Pim/Bundle/EnrichBundle/ProductQueryBuilder/ProductAndProductModelQueryBuilder.php
src/Pim/Bundle/EnrichBundle/Resources/config/readers.yml
src/Pim/Bundle/EnrichBundle/spec/Connector/Reader/MassEdit/FilteredProductAndProductModelReaderSpec.php
src/Pim/Bundle/UIBundle/Resources/public/less/pages/Default.less

Modifying the current `pim_enrich.reader.database.product_and_product_model ` reader service to use a dedicated class `\Pim\Bundle\EnrichBundle\Connector\Reader\MassEdit\FilteredProductAndProductModelReader`
Which is only used for now in order to make the existing mass_edits/quick exports actions pass to only process ProductInterface entities.
Todo:
| Migration …

PIM-6674: Mass actions only process ProductInterface.

---

CHANGELOG-1.7.md
features/update/copy_multiselect.feature
features/update/copy_simpleselect.feature
src/Pim/Bundle/CatalogBundle/Resources/config/updaters.yml
src/Pim/Component/Catalog/Updater/Copier/AbstractAttributeCopier.php
src/Pim/Component/Catalog/Updater/Copier/MultiSelectAttributeCopier.php
src/Pim/Component/Catalog/Updater/Copier/SimpleSelectAttributeCopier.php
src/Pim/Component/Catalog/spec/Updater/Copier/MultiSelectAttributeCopierSpec.php
src/Pim/Component/Catalog/spec/Updater/Copier/SimpleSelectAttributeCopierSpec.php
src/Pim/Component/Catalog/tests/integration/Updater/Copier/AbstractCopierTestCase.php
src/Pim/Component/Catalog/tests/integration/Updater/Copier/MediaAttributeCopierIntegration.php
src/Pim/Component/Catalog/tests/integration/Updater/Copier/MultiSelectAttributeCopierIntegration.php
src/Pim/Component/Catalog/tests/integration/Updater/Copier/SimpleSelectAttributeCopierIntegration.php
src/Pim/Component/Catalog/tests/integration/Updater/Setter/MediaAttributeSetterIntegration.php

There is a bug into the simple and multi select attribute copiers. We were directly copying the options from the source value into the destination value.
Problem is, when we copy, inside one product, the value from an attribute to the one of another attribute (where option codes are identical between the two attributes, of course), we end up with the destination attribute containing an option (the relation on the ID in database) from the source attribute, which should never happen!
This PR fixes this behavior by ensuring the copy is made through the option code, not the entire object, validating in the process that this option really exists for the destination attribute. …

PIM-6798: Fix select attribute copiers

---

CHANGELOG-1.7.md
Jenkinsfile
features/Context/FixturesContext.php
features/import/product_variant_group/fail_to_import_products_with_duplicated_axis_values.feature
src/Pim/Bundle/CatalogBundle/EventSubscriber/ResetUniqueValidationSubscriber.php
src/Pim/Bundle/CatalogBundle/Resources/config/event_subscribers.yml
src/Pim/Bundle/CatalogBundle/Resources/config/validators.yml
src/Pim/Bundle/CatalogBundle/spec/EventSubscriber/ResetUniqueValidationSubscriberSpec.php
src/Pim/Component/Catalog/Validator/Constraints/UniqueValueValidator.php
src/Pim/Component/Catalog/Validator/Constraints/UniqueVariantAxisValidator.php
src/Pim/Component/Catalog/Validator/UniqueAxesCombinationSet.php
src/Pim/Component/Catalog/spec/Validator/Constraints/UniqueVariantAxisValidatorSpec.php
src/Pim/Component/Catalog/spec/Validator/UniqueAxesCombinationSetSpec.php

Currently, when creating products and adding them to a variant group, we validate that there is not already a product in this variant group with the same axis values, as each axis values combination are unique for a variant group. For example, you cannot have to red t-shirts in size XL in the same variant group, if color and size are this variant group axes.
However, we did not validate this axis values uniqueness during imports inside one batch. So it was possible to import several products for a same variant group, with the same axis value combination.
This PR introduces a `UniqueAxesCombinationSet` that stores the axis value combinations and is reset after each batch. Its behavior is based on the `UniqueValuesSet`, which does the same for attributes with unique values.
| Q …

PIM-6820: Validate variant axes during imports

---

src/Pim/Bundle/ApiBundle/tests/integration/Controller/Attribute/ListAttributeIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/AttributeGroup/ListAttributeGroupIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/AbstractProductTestCase.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/DeleteVariantProductIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/GetVariantProductIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/SuccessListVariantProductIntegration.php
src/Pim/Component/Catalog/tests/integration/Normalizer/Standard/AttributeGroupIntegration.php
tests/catalog/technical/attribute_options.csv
tests/catalog/technical/attributes.csv
tests/catalog/technical/product_models.csv

Add a test for variant product (on the API) it checks the parent field is well set.

API-369-370-371: add tests for variant product API

---

features/mass-action/mass_delete_products_and_product_models.feature
src/Pim/Bundle/DataGridBundle/Extension/MassAction/Handler/DeleteProductsMassActionHandler.php
src/Pim/Bundle/DataGridBundle/spec/Extension/MassAction/Handler/DeleteProductsMassActionHandlerSpec.php

It skips the product models when a user selects some products and some product models

PIM-6818: SKIP mass delete for product models

---

src/Pim/Bundle/InstallerBundle/Command/DatabaseCommand.php

The installer fails because job instance access references job instances that should have been created, but have never been inserted in the DB.
Autopsy of the problem:
Here are the steps executed when launching the installer:
1- a subscriber load all groups and roles and attach them the "system" user. All groups and roles are now loaded in the Unit of Work, with their object hash (spl_object_hash) used as identifiers in the states map
2- remove the database
3- create the database
4- create the schema
5- install the fixtures
At some point, the new roles and groups coming from the fixtures are loaded. They then replace the ones in the Unit of Work identityMap, because they have the same database id. But when it happens, the states map still contains the old object hash, as well as the new …

PIM-6826: Makes sure the UnitOfWork is in pristine state after re-creating the DB

---

STANDARD_FORMAT.md

Questions:
- should we expose the family variants in the family? (it's done in the PR)
- about the variant products: should the key be called _parent_ or _product_model_ (called _parent_ in the PR)
- about the product models: should the key be called _parent_ or _product_model_ (called _parent_ in the PR)
- should we expose the family in the product model (it's done in the PR)
Todo:

PIM-6335: update standard format

---

CHANGELOG-1.7.md
src/Pim/Component/Connector/ArrayConverter/StandardToFlat/Product.php
src/Pim/Component/Connector/spec/ArrayConverter/StandardToFlat/ProductSpec.php

In the product standard format, codes of the product groups and product variant group are in different fields: `groups` which contains an array of code, coma separated, and `variant_group` which contains the code as a string, as a product can only have one variant group, respectively.
When converted into the flat format for the export, those codes are concatenated into a single `groups` field (the corresponding column of the exported file), the variant group being added after the other groups.
If the product is in one or several groups, but in no variant group, we end up with an additional coma at the end of the group list, this being the result of the concatenation of the groups with an empty string as variant group… This leads to invalid CSV or XLSX file that cannot be reimported.
This …

PIM-6822: Fix standard to flat product conversion

---

src/Oro/Bundle/UserBundle/Controller/ResetController.php

Fix the `\Swift_Message::newInstance()` error since this method is deprecated by SwiftMailer > 6.0.0
Replaced it with `(new \Swift_Message('My Subject'))`
Changelog depreciation : https://github.com/swiftmailer/swiftmailer/blob/v6.0.0/CHANGES#L14
New implementation : https://swiftmailer.symfony.com/docs/introduction.html#basic-usage …

Swift_Message instanciation update for SwiftMailer > v6.0.0

---

src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/product/index.yml
src/Pim/Bundle/UIBundle/Resources/public/less/components/product-edit-form/CompletenessPanel.less
src/Pim/Bundle/UIBundle/Resources/public/less/lib/select2.less

This PR fixes an issue where the product grid keeps the category tree data from other grids when switching. 

PIM-6837: Fix category tree switching in product grid

---

src/Pim/Bundle/CatalogBundle/Resources/elasticsearch/index_configuration.yml

With Leo we imported a catalog they use at presales.
This catalog contains 1000 attributes.
We already reach the limit of 3000 fields in ES with this catalog.
We decided with Benoit to upgrade this limit to 10000 fields.

TIP-749: upgrade total fields limit in ES

---

src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/attributes.js

As the missing required attributes for the product model are not computed yet (see PIM-6773 story).
We need to disable the header for product model edit forms only. 
This *quickfix* allows us to do so.
In short - do not show this for product models only: …

PIM-6773: Disable toFillFields header for product models only

---

src/Akeneo/Bundle/ElasticsearchBundle/Client.php
src/Akeneo/Bundle/ElasticsearchBundle/Exception/IndexationException.php
src/Akeneo/Bundle/ElasticsearchBundle/spec/ClientSpec.php
src/Pim/Bundle/InstallerBundle/Command/DatabaseCommand.php

During indexation, we didn't take into account ES errors that can occur.
There are 2 types of errors:
- sometimes an exception is thrown by the official ES PHP client 
- sometimes there is just a field `error` set in the response
Errors can occur for instance when we have reach the `index.mapping.total_fields.limit` parameter of Elasticsearch.
Before this PR, the indexation would silently fail. That means, you think that everything's working, but actually, your products or product models are not indexed (and thus are not available in the datagrid)
| Added Behats                      | 
| Changelog updated                 | 
| …

TIP-613: take ES errors into accound during indexation

---

features/update/remove_price.feature
src/Pim/Bundle/CatalogBundle/EventSubscriber/IndexProductsSubscriber.php
src/Pim/Bundle/CatalogBundle/spec/EventSubscriber/IndexProductsSubscriberSpec.php

see [sf doc](http://symfony.com/doc/current/event_dispatcher.html) about priority:
> The other optional tag attribute is called  priority, which defaults to 0 and it controls the order in which listeners are executed (the highest the priority, the earlier a listener is executed). This is useful when you need to guarantee that one listener is executed before another. The priorities of the internal Symfony listeners usually range from -255 to 255 but your own listeners can use any positive or negative integer. …

API-352: add priority on products indexers

---

src/Pim/Bundle/CatalogBundle/Command/QueryProductCommand.php

Due to a Sf3 deprecation https://symfony.com/doc/current/components/console/helpers/tablehelper.html
Before:
```
➜  pim-demos2.0 git:(dev2.0.0.0) ✗ bin/console pim:product:query {}     
12:17:55 ERROR     [console] Error thrown while running command "pim:product:query '{}'". Message: "The helper "table" is not defined." ["error" => Symfony\Component\Console\Exception\InvalidArgumentException { …},"command" => "pim:product:query '{}'","message" => "The helper "table" is not defined."] []
12:17:55 ERROR     [console] Command "pim:product:query '{}'" exited with code "1" ["command" => "pim:product:query '{}'","code" => 1] []
[Symfony\Component\Console\Exception\InvalidArgumentException]  
The helper "table" is not defined.                              
```
After:
```
➜  pim-demos2.0 …
```

Fix QueryProductCommand table deprecation

---

.gitignore

Fix #6824 
Add .web-server-pid to gitignore
_**Must i add this change to CHANGELOG ?**_ 
| Changelog updated                 | ?

GITHUB-6824: add .web-server-pid to gitignore

---

Jenkinsfile
app/phpunit.xml.dist
src/Pim/Bundle/VersioningBundle/tests/integration/Normalizer/Flat/VariantGroupIntegration.php
tests/FixturesLoader.php

Currently, integration tests are split manually, into small test suites, to be run in parallel on the CI. This is not ideal, as the suites are not equivalent in size, and so in running time, and we can forgot to add new set of tests in the existing suites.
This PR brings back into 1.7 the work that @ahocquard did on master (2.0), but only for CE and ORM. 
The goal is only to ensure all tests are ran, including new ones, whitout having to do anything else than writing the test.
EE tests ran from CE pull requests could be added later, as well as ODM builds. I also had to deactivate a broken test on variant group normalization (which was not ran before anyway...). It will be fixed later in another PR.
This PR also improves build time by performing a `composer update` only during checkout …

Integration tests 1.7

---

.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG-2.0.md
src/Akeneo/Bundle/BatchQueueBundle/Command/JobQueueConsumerCommand.php
src/Akeneo/Bundle/BatchQueueBundle/Command/PublishJobToQueueCommand.php

My bad: the command is "akeneo:batch:publish-job-to-queue" and not "publish-job-to-queue".

API-393: add prefix akeno:batch to the command to push a job into the queue

---

src/Pim/Bundle/NotificationBundle/Notifier.php
src/Pim/Bundle/NotificationBundle/spec/NotifierSpec.php
src/Pim/Bundle/UserBundle/Entity/UserInterface.php
src/Pim/Bundle/UserBundle/EventSubscriber/CreateUserSystemListener.php

Without this PR, the execution of rules is totally broken on EE.
```
jjanvier:ped$ sf akeneo:rule:run copy_pt_PT_mobile_description_to_print_description                                                                                                
Running rules...
1/1 [============================] 100%16:37:14 ERROR     [console] Error thrown while running command "akeneo:rule:run copy_pt_PT_mobile_description_to_print_description". Message: "A new entity was found through the relationship 'Pim\Bundle\NotificationBundle\Entity\UserNotification#user' that was not configured to cascade persist operations for entity: system. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example …
```

Do not try to notify the user System

---

CHANGELOG-2.0.md
features/product/choose_and_order_products_grid_columns.feature
features/product/edit_variant_product.feature
src/Pim/Bundle/CatalogBundle/DependencyInjection/PimCatalogExtension.php
src/Pim/Bundle/CatalogBundle/Resources/config/product_models.yml
src/Pim/Bundle/CatalogBundle/Resources/config/repositories.yml
src/Pim/Bundle/DataGridBundle/Normalizer/ProductModelNormalizer.php
src/Pim/Bundle/DataGridBundle/Resources/config/normalizers.yml
src/Pim/Bundle/DataGridBundle/spec/Normalizer/ProductModelNormalizerSpec.php
src/Pim/Bundle/EnrichBundle/Normalizer/EntityWithFamilyVariantNormalizer.php
src/Pim/Bundle/EnrichBundle/Normalizer/ProductModelNormalizer.php
src/Pim/Bundle/EnrichBundle/Normalizer/ProductNormalizer.php
src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/product.yml
src/Pim/Bundle/EnrichBundle/Resources/config/normalizers.yml
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/meta/change-family.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/variant-navigation.js
src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/form/variant-navigation/product-item.html
src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/form/variant-navigation/product-model-item.html
src/Pim/Bundle/EnrichBundle/spec/Normalizer/EntityWithFamilyVariantNormalizerSpec.php
src/Pim/Bundle/EnrichBundle/spec/Normalizer/ProductModelNormalizerSpec.php
src/Pim/Bundle/EnrichBundle/spec/Normalizer/ProductNormalizerSpec.php
src/Pim/Bundle/UIBundle/Resources/public/less/components/product-edit-form/VariantNavigation.less
src/Pim/Component/Catalog/ProductModel/ImageAsLabel.php
src/Pim/Component/Catalog/ProductModel/ProductModelImageAsLabel.php
src/Pim/Component/Catalog/spec/ProductModel/ImageAsLabelSpec.php
src/Pim/Component/Catalog/spec/ProductModel/ProductModelImageAsLabelSpec.php

Main goal of this PR is to **display image or product models in the grid and in the PEF in a smart way**.
If the attribute as image is on an entity below (product model or variant product), then it returns the first item it finds.
**Bonus fixes from other cards:**
- PIM-6451: Hide the button to edit a family on a variant product edit form
- Change label from "Complete product" to "Variant products"
- PIM-6451: Now display variant axes coming from parent as "Variant Axis" on the product edit form
- PIM-6348: Display a red label in the variant navigation if no product is complete
| Added Specs …

PIM-6356: display ascendant or descendant image for product models

---

CHANGELOG-2.0.md
features/Context/Page/Product/Index.php
features/product/filtering/filter_products_per_category.feature
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/grid/category-switcher.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/grid/category-tree.js

There was a bug when
- you expand a node
- you select this node
-> the column displayed this node and all its children.
This fix prevent it.

[PIM-6832] Fix the column category display when category node is expanded

---

CHANGELOG-1.7.md
features/import/edit_an_import.feature
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/job_instance/xlsx_product_import_edit.yml
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/job_instance/xlsx_product_import_show.yml

[SLA] PIM-6823: add missing "decimal separator" field on xlsx profil import

---

CHANGELOG-2.0.md
features/Context/DataGridContext.php
features/product-group/edit_product_group.feature
src/Pim/Bundle/AnalyticsBundle/Resources/views/SystemInfo/index.html.twig
src/Pim/Bundle/DashboardBundle/Resources/views/Dashboard/index.html.twig
src/Pim/Bundle/EnrichBundle/Resources/views/CategoryTree/form.html.twig
src/Pim/Bundle/EnrichBundle/Resources/views/CategoryTree/index.html.twig
src/Pim/Bundle/EnrichBundle/Resources/views/JobExecution/index.html.twig
src/Pim/Bundle/UIBundle/Resources/views/Default/page_elements.html.twig
src/Pim/Bundle/UIBundle/Resources/views/actions/update.html.twig
src/Pim/Bundle/UIBundle/Resources/views/actions/view.html.twig
src/Pim/Bundle/UserBundle/Resources/views/Role/update.html.twig
src/Pim/Bundle/UserBundle/Resources/views/User/update.html.twig
src/Pim/Bundle/UserBundle/Resources/views/User/view.html.twig

If moves the user badge from buttons to context dropzone.
I used this PR to refactor a little bit page_elements, to avoid lines like `page_elements('',null,null,null,null,null,null,null,null,null,null,null,null,null, 12)`

[PIM-6534] Move User badge

---

CHANGELOG-2.0.md
src/Pim/Bundle/CatalogBundle/Resources/config/model/doctrine/FamilyVariant.orm.yml

Even if it's a change to a MySQL table, it's better imo to fix that very early in the 2.0 life rather getting some really painful bugs in the future.

PIM-6446: fix variant family code uniqueness

---

CHANGELOG-2.0.md
src/Pim/Bundle/CatalogBundle/Command/CalculateCompletenessCommand.php
src/Pim/Bundle/CatalogBundle/tests/integration/Completeness/CalculateCompletenessCommandIntegration.php
tests/IntegrationTestsBundle/Launcher/CommandLauncher.php

With the rework on the completeness, products are not saved anymore when we call the `generateMissing` method.
Now to be sure ES is synchro with the db, we refresh the product index, get all products without completeness and save products in the db & ES (when we save a product, the completeness is automatically calculated)  …

PIM-6862: save products on "pim:completeness:calculate" command

---

src/Pim/Bundle/UIBundle/Resources/public/less/components/Column.less

This PR fixes the overlapping project details css glitch
Before
After

PIM-6835: Fix project view in column

---

CHANGELOG-2.0.md
features/product/history/display_variant_product_history.feature
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/CreateVariantProductIntegration.php
src/Pim/Bundle/CatalogBundle/EventSubscriber/AddUniqueAttributesToVariantProductAttributeSetSubscriber.php
src/Pim/Bundle/CatalogBundle/Resolver/FQCNResolver.php
src/Pim/Bundle/CatalogBundle/Resources/config/event_subscribers.yml
src/Pim/Bundle/CatalogBundle/Resources/config/family_variant.yml
src/Pim/Bundle/CatalogBundle/spec/EventSubscriber/AddUniqueAttributesToVariantProductAttributeSetSubscriberSpec.php
src/Pim/Bundle/VersioningBundle/Builder/VersionBuilder.php
src/Pim/Bundle/VersioningBundle/EventSubscriber/AddRemoveVersionSubscriber.php
src/Pim/Bundle/VersioningBundle/Manager/VersionManager.php
src/Pim/Component/Catalog/FamilyVariant/AddUniqueAttributes.php
src/Pim/Component/Catalog/spec/FamilyVariant/AddUniqueAttributesSpec.php

Currently, there is no version visible in the variant products history panel.
This is because of the way our versioning work: every entity versions are in the same table `pim_versioning_version`. To know to what entity a version belong, there is a field `resource_name` in that table that contains the namespace of the versioned entity.
Problem is, the variant product and regular product share the same interface, but are different entities, with different namespaces. But on the front side, they are both treated as products. So versions are fetched using the "product-history-fetcher", which looks only for the regular product namespace in the `resource_name` field.
A way to solve that would be to create two product forms, with two different routings: one for `product` and one for …

PIM-6847: Fix variant product history

---

CHANGELOG-2.0.md
features/Context/catalog/catalog_modeling/products.csv
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/DeleteVariantProductIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/Product/CreateVariantProductIntegration.php
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/variant-navigation.js
src/Pim/Bundle/EnrichBundle/Resources/public/templates/common/default-template.html
src/Pim/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev/products.csv
src/Pim/Bundle/UIBundle/Resources/public/less/components/Header.less
src/Pim/Bundle/UIBundle/Resources/public/less/components/TitleContainer.less
src/Pim/Bundle/UIBundle/Resources/public/less/lib/select2.less
src/Pim/Component/Catalog/Validator/Constraints/VariantProductParentValidator.php
src/Pim/Component/Catalog/spec/Validator/Constraints/VariantProductParentValidatorSpec.php

Currently, you can set the root product model as parent of a variant product. This shouldn't be possible.
I removed 4 products from the fixtures, because they were not valid anymore now that the validation is correct.
This PR also fixes Variant Navigation bar & dropdown (thanks @pierallard <3)

PIM-6867: Fix validation of variant product about parent

---

CHANGELOG-2.0.md
features/product-model/edit_product_model.feature
src/Pim/Bundle/EnrichBundle/Normalizer/ProductViolationNormalizer.php
src/Pim/Bundle/EnrichBundle/spec/Normalizer/ProductViolationNormalizerSpec.php

This PR adds the same validation tooltips on product models than we already have on product edit form.

PIM-6816: Display product models errors in PEF

---

src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/meta/family-variant.js

The new meta field `VARIANT` displays on which axes the products and product models are based.
However, this meta is useless on non variant products and should just not be displayed.

PIM-6863: Hide "Variant" meta in regular products

---

CHANGELOG-2.0.md
src/Akeneo/Bundle/StorageUtilsBundle/Doctrine/DBAL/Types/JsonType.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/CreateProductIntegration.php

PIM-6876: escape u001f character to workaround a mysql bug

---

CHANGELOG-2.0.md
src/Pim/Bundle/CatalogBundle/Elasticsearch/SearchQueryBuilder.php
src/Pim/Bundle/CatalogBundle/spec/Elasticsearch/SearchQueryBuilderSpec.php

- Prevents ES from using the scoring system by using "filter" context.
- Also in this "filter" context the max_clause_count search limit does not apply.
We can reach this limit when visiting the product grid in EE => a query with all the category code the current user is allowed to see is issued to ES, potentially filtering in 5K+ category codes making the product grid to break. …

TIP-809: Prevents ES from using the scoring system

---

CHANGELOG-2.0.md
features/product/display_variant_product.feature
src/Pim/Bundle/EnrichBundle/Resources/config/requirejs.yml
src/Pim/Bundle/EnrichBundle/Resources/config/routing/product.yml
src/Pim/Bundle/EnrichBundle/Resources/config/routing/product_model.yml
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/history.js
src/Pim/Bundle/VersioningBundle/Builder/VersionBuilder.php
src/Pim/Bundle/VersioningBundle/EventSubscriber/AddRemoveVersionSubscriber.php
src/Pim/Bundle/VersioningBundle/Manager/VersionManager.php

A first improvement was made in #6905 to allow variant product history to be displayed. This was done on the backend side, but was not an ideal solution (very dirty in fact).
This PR reverts the development previously made, and replaces it with a full frontend solution.
**Important** The first commit of this PR comes from my previous PR: #6929. I think I just forgot to push it... 😑  …

PIM-6847: Manage product and variant product history on frontend side

---

CHANGELOG-2.0.md
features/Context/WebUser.php
features/product-model/classify_product_model.feature
features/product/classify_variant_product.feature
src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/ProductModelCategoryRepository.php
src/Pim/Bundle/CatalogBundle/Resources/config/repositories.yml
src/Pim/Bundle/ConnectorBundle/tests/integration/Export/AbstractExportTestCase.php
src/Pim/Bundle/ConnectorBundle/tests/integration/Export/Product/ExportProductsIntegration.php
src/Pim/Bundle/EnrichBundle/Controller/AbstractListCategoryController.php
src/Pim/Bundle/EnrichBundle/Controller/ProductController.php
src/Pim/Bundle/EnrichBundle/Controller/ProductModelController.php
src/Pim/Bundle/EnrichBundle/Controller/Rest/ProductModelCategoryController.php
src/Pim/Bundle/EnrichBundle/Resources/config/acl.yml
src/Pim/Bundle/EnrichBundle/Resources/config/controllers.yml
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/product/edit.yml
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/product_model/edit.yml
src/Pim/Bundle/EnrichBundle/Resources/config/routing/product_model.yml
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/categories.js
src/Pim/Bundle/EnrichBundle/Resources/translations/messages.en.yml
src/Pim/Bundle/EnrichBundle/Resources/views/ProductModel/listCategories.json.twig
src/Pim/Component/Catalog/Repository/ProductModelCategoryRepositoryInterface.php

This PR is about the product models classification:
- it adds tests on the export
- it adds an ACL
- it adds the categories tab on the product model edit form
- it adds tests on variant products categories (ensuring ancestry categories are taken into account)
The second to last commit tries to mutualize some logic between products and models. It can be removed if you don't like it.

PIM-6343: classify product models

---

src/Pim/Bundle/CatalogBundle/Elasticsearch/Filter/Field/CategoryFilter.php
src/Pim/Bundle/CatalogBundle/spec/Elasticsearch/Filter/Field/CategoryFilterSpec.php
src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/CategoryFilterIntegration.php

The category filter IN_LIST_OR_UNCLASSIFIED does not work correctly when use multiple times this filter (and it's the case in EE for permission).
We did not discover this bug yet because in EE, the datagrid does not use the PQB filtered by permissions (on purpose?).
This bug is reproducible with the API in EE (every products are returned, even you use a filter IN_LIST_OR_UNCLASSIFIED).
For example, let's say you filter on `categoryA` and then on `categoryB` (in another service, in EE for permissions for example). It should only return product that are in `categoryA` AND in `categoryB` or not in category at all.
- Before this PR:
```
$pqb->addFilter('categories', Operators::IN_LIST_OR_UNCLASSIFIED, ['categoryA']); …
```

Fix category filter IN_LIST_OR_UNCLASSIFIED that does not support multiple usage of it

---

CHANGELOG-2.0.md
app/config/config.yml
src/Oro/Bundle/AsseticBundle/Resources/views/Assets/oro_css.html.twig
src/Pim/Bundle/EnrichBundle/DependencyInjection/PimEnrichExtension.php
src/Pim/Bundle/EnrichBundle/Resources/config/version_strategy.yml
src/Pim/Bundle/EnrichBundle/Resources/views/index.html.twig
src/Pim/Bundle/EnrichBundle/VersionStrategy/CacheBusterVersionStrategy.php
src/Pim/Bundle/EnrichBundle/spec/VersionStrategy/CacheBusterVersionStrategySpec.php

This PR adds a version strategy for our JS and CSS assets so that we can bust the cache when we release a patch version. 
E.g. 
`<script type="text/javascript" src="/dist/manifest.min.js"></script>` becomes
`<script type="text/javascript" src="/dist/manifest.min.js?2.0.1 "></script>`
`Todo`: …

TIP-808: Use version strategy for frontend assets

---

CHANGELOG-2.0.md
features/Context/Page/ProductModel/Edit.php
features/product-model/display_product_model_history.feature
features/product/history/display_variant_product_history.feature
src/Pim/Bundle/EnrichBundle/Resources/config/acl.yml
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/product_model/edit.yml
src/Pim/Bundle/EnrichBundle/Resources/config/requirejs.yml
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/history.js
src/Pim/Bundle/EnrichBundle/Resources/translations/messages.en.yml

Add a history extension for product models.

 PIM-6346: Add history on product model edit page 

---

CHANGELOG-2.0.md
features/dashboard/display_last_operations_widget.feature
features/job-execution/last-execution/export.feature
features/job-execution/last-execution/import.feature
features/job-tracker/browse_job_executions.feature
features/job-tracker/display_jobs_execution_in_job_tracker.feature
src/Pim/Bundle/DataGridBundle/Datasource/DatasourceInterface.php
src/Pim/Bundle/DataGridBundle/EventListener/AddUsernameToGridListener.php
src/Pim/Bundle/DataGridBundle/Resources/config/event_listeners.yml
src/Pim/Bundle/DataGridBundle/spec/EventListener/AddUsernameToGridListenerSpec.php
src/Pim/Bundle/EnrichBundle/Doctrine/ORM/Repository/JobExecutionRepository.php
src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/job_tracker.yml
src/Pim/Bundle/EnrichBundle/Resources/config/datagrid_listeners.yml
src/Pim/Bundle/EnrichBundle/tests/integration/Repository/JobExecutionRepositoryIntegration.php
src/Pim/Bundle/ImportExportBundle/Manager/JobExecutionManager.php
src/Pim/Bundle/ImportExportBundle/Resources/config/managers.yml

[API-389](https://akeneo.atlassian.net/browse/API-389) : As Mary, I want to only see my launched jobs in the process tracker
[API-397](https://akeneo.atlassian.net/browse/API-397): As Mary, I want to only see my launched jobs in the dashboard
[API-398](https://akeneo.atlassian.net/browse/API-398): As Mary, I want to only see my launched exports/imports
| Migration …

API-389: Only view logged user jobs in process tracker

---

CHANGELOG-2.0.md
src/Pim/Bundle/CatalogBundle/Elasticsearch/Sorter/Attribute/AbstractAttributeSorter.php
src/Pim/Bundle/CatalogBundle/spec/Elasticsearch/Sorter/Attribute/BaseAttributeSorterSpec.php
src/Pim/Bundle/CatalogBundle/spec/Elasticsearch/Sorter/Attribute/MetricSorterSpec.php
src/Pim/Bundle/CatalogBundle/spec/Elasticsearch/Sorter/Attribute/TextAreaSorterSpec.php
src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Sorter/Boolean/LocalizableScopableSorterIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Sorter/Boolean/LocalizableSorterIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Sorter/Boolean/ScopableSorterIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Sorter/Date/LocalizableScopableSorterIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Sorter/Date/LocalizableSorterIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Sorter/Date/ScopableSorterIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Sorter/Metric/LocalizableScopableSorterIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Sorter/Metric/LocalizableSorterIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Sorter/Metric/ScopableSorterIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Sorter/Number/LocalizableScopableSorterIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Sorter/Number/LocalizableSorterIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Sorter/Number/ScopableSorterIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Sorter/Option/LocalizableScopableSorterIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Sorter/Option/LocalizableSorterIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Sorter/Option/ScopableSorterIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Sorter/Text/LocalizableScopableSorterIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Sorter/Text/LocalizableSorterIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Sorter/Text/ScopableSorterIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Sorter/TextArea/LocalizableScopableSorterIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Sorter/TextArea/LocalizableSorterIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Sorter/TextArea/ScopableSorterIntegration.php

In ES, the search request will fail if there is no mapping associated with a field
Example:
You want to sort on the attribute `description` with the channel `ecommerce`. 
If in all your data, you have no result for attribute `description` and the channel `ecommerce`, ES will throw:
`{"error":{"root_cause":[{"type":"query_shard_exception","reason":"No mapping found for [values.description-textarea.mobile.en_US.preprocessed] in order to sort on","index_uuid":"xt_aOy_hT5m2Y-rNHJkSUg","index":"akeneo_pim_product_and_product_model"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"akeneo_pim_product_and_product_model","node":"OQV8VTpeTHijWclZJW0RKA","reason":{"type":"query_shard_exception","reason":"No …

PIM-6872: fix exception when attribute sorted is not in mapping

---

CHANGELOG-2.0.md
src/Pim/Bundle/PdfGeneratorBundle/Resources/views/Product/renderPdf.html.twig

Fix product PDF. Only localizable & scopable were shown

PIM-6859: Fix missing attribute values in PDF

---

CHANGELOG-2.0.md
src/Pim/Bundle/ApiBundle/Controller/ProductController.php
src/Pim/Bundle/ApiBundle/Controller/ProductModelController.php
src/Pim/Bundle/ApiBundle/Resources/config/controllers.yml
src/Pim/Bundle/ApiBundle/Resources/config/routing/product_model.yml
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/AbstractProductTestCase.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/SuccessLargeAndOrderedListProductIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/ProductModel/AbstractProductModelTestCase.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/ProductModel/LargeAndOrderedListProductModelIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/ProductModel/ListOffsetProductModelIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/ProductModel/ListSearchAfterProductModelIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/RootEndpointIntegration.php
src/Pim/Bundle/CatalogBundle/Resources/config/cursors.yml
src/Pim/Bundle/CatalogBundle/Resources/config/query_builders.yml

Add in API a route to get list of product models using "offset" or "search after" pagination mode.

API-395: Get list of product models through API

---

CHANGELOG-2.0.md
src/Pim/Bundle/EnrichBundle/Resources/config/bundles/twig.yml

When updating a standard edition installed with 2.0.0 or 2.0.1 to 2.0.x (upcoming 2.0.2), you need to add the missing configuration for asset versioning strategy in your project config.yml, if you don't, you'll have the following exception,
```
2017-10-10 11:49:46] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("There is no "frontend" asset package.")." at /srv/pim/
vendor/akeneo/pim-community-dev/src/Oro/Bundle/AsseticBundle/Resources/views/Assets/oro_css.html.twig line 9 {"exception":"[object] (Twig_Error_Runtime(code: 0): An exception has been thrown during the re
ndering of a template (\"There is no \"frontend\" asset package.\"). at /srv/pim/vendor/akeneo/pim-community-dev/src/Oro/Bundle/AsseticBundle/Reso …
```

TIP-808: avoid BC break adding version strategy for js / css

---

CHANGELOG-2.0.md
src/Akeneo/Bundle/ClassificationBundle/Doctrine/ORM/Repository/CategoryRepository.php
src/Akeneo/Component/Classification/Repository/CategoryRepositoryInterface.php
src/Pim/Bundle/CatalogBundle/Elasticsearch/Filter/Field/CategoryFilter.php
src/Pim/Bundle/CatalogBundle/spec/Elasticsearch/Filter/Field/CategoryFilterSpec.php
src/Pim/Bundle/DataGridBundle/Controller/Rest/DatagridViewController.php
src/Pim/Bundle/DataGridBundle/Manager/DatagridViewManager.php

Improve performance of the PQB when we add categories in search. 
On CE, performance won't be improved, but on EE, as we inject all granted categories in PQB, performance are better. 
Problem comes from we hydrate categories, just to check if they exist.
On datagrid, with 10000 categories:
**Before**
**After**
It has an impact on the API too:
Before: GET http://enterprise-master.local/api/rest/v1/products => 5.9s
After: GET http://enterprise-master.local/api/rest/v1/products => 1.6s
About the change in `DatagridViewManager`, I was wondering why it took so much time to get default columns (which are defined in yml). In fact to get these columns, we called `$this->datagridManager->getDatagrid($alias)` which recreate a datagrid and call again the PQB. Now we call the configuration of the …

PIM-6895: Improve performances on products datagrid

---

CHANGELOG-2.0.md
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Attribute/ListAttributeIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/AbstractProductTestCase.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/PartialUpdateProductVariantIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/SuccessListVariantProductIntegration.php
src/Pim/Bundle/VersioningBundle/tests/integration/Normalizer/Flat/AttributeIntegration.php
src/Pim/Component/Api/tests/integration/Normalizer/AttributeIntegration.php
src/Pim/Component/Catalog/tests/integration/Normalizer/Standard/AttributeIntegration.php
tests/IntegrationTestsBundle/Loader/FixturesLoader.php
tests/catalog/technical/attributes.csv

This PR fixes some broken integration tests.
There was 2 problems:
- Some tests were broken because of a fixed validation on variant axis values uniqueness,
- Other because of completeness with the following error in logs (random error, not the same tests were broken each run):
```
request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\UniqueConstraintViolationException: "An exception occurred while executing 'INSERT INTO pim_catalog_completeness (ratio, missing_count, required_count, locale_id, channel_id, product_id) VALUES (?, ?, ?, ?, ?, ?)' with params [26, 14, 19, 5, 1, 1]:  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-5-1' for key 'searchunique_idx'" at /srv/pim/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php line 66 …
```

Fix integration tests

---

CHANGELOG-2.0.md
features/Pim/Behat/Context/NavigationContext.php
features/user/edit_my_account.feature
src/Oro/Bundle/UserBundle/Form/Type/ChangePasswordType.php

Remove constraints `Valid` on the `plainPassword` field. It's useless and cause a bug with special characters when the form is validated

PIM-6894: Allow any special characters in password field

---

web/app.php

In case the PIM is running behind a Proxy (Reverse-Proxy or load-balancer), by default Symfony if not take in account X-Forwarded-* headers that allow to know to know the real request information (client IP, port, proto ...) :
http://symfony.com/doc/current/request/load_balancer_reverse_proxy.html#solution-settrustedproxies
For example if the proxy is taking charge of TLS/SSL and acces the PIM in HTTP, the application doesn't know that the client have accessed in HTTPS. So generated URL in responses will be with "http://".
This is true for example for links in the PIM API replies, but also some absolute links in PIM pages.
The Akeneo Serenity offer is using a reverse-proxy/load-balancer for scalability. The load-balancer is taking in …

TIP-814 - Enabling X-Forwarded-* headers usage if TRUSTED_PROXY_IPS defined

---

src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/AbstractProductTestCase.php
src/Pim/Bundle/VersioningBundle/Manager/VersionManager.php
src/Pim/Bundle/VersioningBundle/Normalizer/Flat/ProductModelNormalizer.php
src/Pim/Bundle/VersioningBundle/Normalizer/Flat/ProductNormalizer.php
src/Pim/Bundle/VersioningBundle/spec/Normalizer/Flat/ProductModelNormalizerSpec.php
src/Pim/Bundle/VersioningBundle/spec/Normalizer/Flat/ProductNormalizerSpec.php
src/Pim/Bundle/VersioningBundle/tests/integration/Manager/EntityWithVariantVersionIntegration.php
tests/IntegrationTestsBundle/Doctrine/JobExecution.php
tests/IntegrationTestsBundle/Resources/config/services.yml

Versioning is broken on sub product models and variant products: the generated versions can contain the data of their parents, if they have been previously updated.
This PR ensure only the data from the saved entity are put in the version change set.

PIM-6346: Fix EntityWithFamilyVariant versioning

---

CHANGELOG-2.0.md
src/Pim/Bundle/CatalogBundle/Resources/elasticsearch/index_configuration.yml
src/Pim/Bundle/CatalogBundle/tests/integration/Elasticsearch/IndexConfiguration/IndexProductsIntegration.php

If the first value of text field looks like a date, ES will set the field type as date and reject all other values for this field that don't look like date. In this case, the index is broken and products with this field cannot be indexed anymore. Easy to reproduce with this product import file on an empty index: 
```
sku;name
sku-01;"2017-01-01"
sku-02;"My name"
```
*sku-02* will generate an exception.
Once upon a time there was a search engine, called ES. As it was a nice search engine, properly indexing typed data.
But ES was talking in a non typed language called JSON.
One day, he received the following document:
`
{
name : "My super document name"
}
`
After a quick look at the *name* field content, ES decided it was clearly a text data, and wrote on the wall that the *name* field was …

Pim 6898 - Some data can break ES index and crashes new products indexing

---

src/Pim/Bundle/InstallerBundle/Command/AssetsCommand.php

Fix the path where `js/routes.js`are being generated after executing `pim:installer:assets` as described in #6983.

Fix #6983 wrong path when generating js routes

---

CHANGELOG-1.7.md
features/Context/Page/Role/Creation.php
features/user/edit_user.feature
src/Oro/Bundle/UserBundle/Controller/UserController.php
src/Pim/Bundle/UserBundle/Resources/views/User/update.html.twig

on 1.7, when you : 
- create a new role
- allow to edit users with ACL
- try to edit a user
it does not work. And this, only for new role... Why? I really don't know :( Welcome to the hell of the ACL...
A [PR](https://github.com/akeneo/pim-community-dev/pull/5979) introduced this regression. 
We checked ACL on `updateAction` but it broke the scenario written above.
The fix is really simple, I revert code added by Oliver and removed the mish-mash of redirection route. 
Indeed, before when you wanted to update your account (`user/profile/edit` route), you were redirected to `/user/update/{your_id}`. Problem, on this route, if you have not the ACL `Edit users`, a 403 error was thrown.
| Q …

PIM-6901: Fix ACL with a new role when we want to edit users

---

CHANGELOG-2.0.md
src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/product.yml

This PR fixes an issue with the broken product grid row actions because the `edit_link` was not defined in the config.

PIM-6821: Options "Edit attributes" and "classify the product" not working on the Product grid

---

CHANGELOG-2.0.md
features/product-model/ensure_tab_redirection.feature
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/product_model/edit.yml
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/categories.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/history.js
src/Pim/Bundle/EnrichBundle/Resources/public/templates/form/column-tabs.html

When you switch from a "product edit form" and "product model edit form" page, the tab extensions does not have the same name.
I added a little trick to allow configuration of the tab code to register in user context to allow context save between these 2 forms.

[PIM-6891] Keep the tab context between product and product model forms

---

CHANGELOG-2.0.md
features/attribute/delete_attribute.feature
src/Pim/Bundle/CatalogBundle/Elasticsearch/Filter/Attribute/BooleanFilter.php
src/Pim/Bundle/CatalogBundle/Resources/config/query_builders.yml
src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Boolean/BooleanFilterIntegration.php

See https://github.com/akeneo/pim-community-dev/pull/7005

 PIM-6918: fix not empty filter on boolean attribute deletion

---

bin/docker/pim-front.sh
bin/docker/pim-initialize.sh
package.json

Currently, we have two commands to build our assets with webpack:
- `webpack` which run in production environment, and so minify the code
- `webpack-watch` which build in development environment and then keep running, watching the code and building it again at each modification (which is cool!).
This PR introduces a third command: `webpack-dev`, which does a simple build like `webpack`, but in development environment, so the code will not be minified.
This would be usefull to build the assets when developping with Docker, as there is some stability issues with `webpack-watch`, and provide a development alternative anyway.
| Added …

Add a "webpack-dev" command

---

CHANGELOG-2.0.md
src/Pim/Bundle/UIBundle/Resources/public/lib/bootstrap-datetimepicker/js/bootstrap-datetimepicker.js

This PR only moves the datepickers to upper position instead of down. 

PIM-5817: move datepicker above field instead of under

---

CHANGELOG-2.0.md
src/Pim/Bundle/EnrichBundle/DependencyInjection/PimEnrichExtension.php
src/Pim/Bundle/EnrichBundle/Doctrine/ORM/Query/AscendantCategories.php
src/Pim/Bundle/EnrichBundle/Normalizer/ProductModelNormalizer.php
src/Pim/Bundle/EnrichBundle/Normalizer/ProductNormalizer.php
src/Pim/Bundle/EnrichBundle/Resources/config/normalizers.yml
src/Pim/Bundle/EnrichBundle/Resources/config/queries.yml
src/Pim/Bundle/EnrichBundle/Resources/config/requirejs.yml
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/categories.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/tree-associate.jstree.js
src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/tab/jstree-locked-item.html
src/Pim/Bundle/EnrichBundle/spec/Normalizer/ProductModelNormalizerSpec.php
src/Pim/Bundle/EnrichBundle/spec/Normalizer/ProductNormalizerSpec.php
src/Pim/Bundle/UIBundle/Resources/public/less/components/button/SelectButton.less
src/Pim/Bundle/UIBundle/Resources/public/less/lib/jquery.jstree.less
src/Pim/Component/Enrich/Query/AscendantCategoriesInterface.php

This PR is exactly the same than
https://github.com/akeneo/pim-community-dev/pull/7019
With 1 more commit it removes the little workaround we do to avoid BC Break
https://github.com/akeneo/pim-community-dev/commit/698805cc95f63de0d8fb20dae579df991d3f18ce
I did it after @SamirBoulil 's remark because Enrich\ProductModelNormalizer is a 2.0 class.

[PIM-6892] Add locked categories for product models - with BC

---

CHANGELOG-2.0.md
src/Pim/Bundle/EnrichBundle/DependencyInjection/PimEnrichExtension.php
src/Pim/Bundle/EnrichBundle/Doctrine/ORM/Query/AscendantCategories.php
src/Pim/Bundle/EnrichBundle/Normalizer/ProductModelNormalizer.php
src/Pim/Bundle/EnrichBundle/Normalizer/ProductNormalizer.php
src/Pim/Bundle/EnrichBundle/Resources/config/normalizers.yml
src/Pim/Bundle/EnrichBundle/Resources/config/queries.yml
src/Pim/Bundle/EnrichBundle/Resources/config/requirejs.yml
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/categories.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/tree-associate.jstree.js
src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/tab/jstree-locked-item.html
src/Pim/Bundle/EnrichBundle/spec/Normalizer/ProductModelNormalizerSpec.php
src/Pim/Bundle/EnrichBundle/spec/Normalizer/ProductNormalizerSpec.php
src/Pim/Bundle/UIBundle/Resources/public/less/components/button/SelectButton.less
src/Pim/Bundle/UIBundle/Resources/public/less/lib/jquery.jstree.less
src/Pim/Component/Enrich/Query/AscendantCategoriesInterface.php

This PR disable jstree items if they belongs to parent of grandparent product model.
If you find the front crappy, ask me IRL because I didn't found any solution and can list all the tested ones.

[PIM-6892] Add locked categories for product models

---

src/Pim/Bundle/LocalizationBundle/Form/Type/LocaleType.php

This is a backport of fix #7011 to 2.0 branch

[Bugfix 2.0] Add use class alias for proper form parent indication

---

CHANGELOG-2.0.md
src/Pim/Component/Catalog/ProductModel/Filter/ProductAttributeFilter.php
src/Pim/Component/Catalog/spec/ProductModel/Filter/ProductAttributeFilterSpec.php
src/Pim/Component/Catalog/tests/integration/ProductModel/Filter/ProductAttributeFilterIntegration.php

When creating a new variant product, the attribute filter was removing values for axes.
The fix takes into account axes too now, to keep their values.

 PIM-6567: Fix attributes filter to not remove axes

---

CHANGELOG-1.7.md
features/export/product-export-builder/export_products_with_attributes.feature
src/Pim/Component/Connector/Writer/File/ProductColumnSorter.php

Fix sort order for export in case of same base attributes

PIM-6939: fix sort order on export

---

CHANGELOG-2.0.md
src/Pim/Bundle/ApiBundle/tests/integration/Controller/ProductModel/CreateProductModelIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/ProductModel/PartialUpdateProductModelIntegration.php
src/Pim/Component/Catalog/Validator/Constraints/NotEmptyVariantAxesValidator.php
src/Pim/Component/Catalog/Validator/Constraints/ProductModelPositionInTheVariantTreeValidator.php

This fix prevent the empty variant axes to return a wrong error message when we try to create a sub product model that extends another sub product model. Else the validator thinks it's a variant product (as it will be on the 3 level sub_product_model_2 -> sub_product_model_1 -> root_product_model) and will return the axes on the 3 level.
| Added integration tests           | Yes

API-407: Fix too many error messages

---

.ci/Jenkinsfile
.ci/behat.community.yml
.ci/behat.enterprise.yml
.ci/k8s/pubsub_consumer_job.yaml
Dockerfile
composer.json
features/Context/AssertionContext.php
src/Akeneo/Bundle/ElasticsearchBundle/spec/Cursor/CursorSpec.php
src/Akeneo/Bundle/ElasticsearchBundle/spec/Cursor/FromSizeCursorSpec.php
src/Akeneo/Bundle/ElasticsearchBundle/spec/Cursor/SearchAfterSizeCursorSpec.php
src/Akeneo/Component/StorageUtils/spec/Cursor/PaginatorSpec.php
src/Pim/Bundle/EnrichBundle/spec/Elasticsearch/CursorSpec.php
src/Pim/Bundle/EnrichBundle/spec/Elasticsearch/FromSizeCursorSpec.php

In this pull request, in addition to the new Jenkinsfile and related files for the new continuous integration system to work, is 2 little notable changes:
In order to list all the behat scenarios we decided to use a well maintained behat extension available for both behat2 and behat3 but this library required a newer version of phpunit and phpspec so we updated it. While doing so some tests failed so we had to rewrite them, basically shouldHaveCount changed its internal implementation and now calls more function on Iterable classes. we used `$this->count()->shouldReturn(xxx);` instead.
The step `I should see history` was poorly written and worked only with very slow firefox. It tried to look at a row that was just removed by the click on the "expand" button just before.
Well it's a brand …

New continuous integration system (2.0)

---

CHANGELOG-2.0.md
src/Pim/Bundle/EnrichBundle/Resources/public/js/controller/role.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/column-tabs-navigation.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/menu/menu.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/menu/tab.js

Fix render of menu item displaying even if they don't have sub items. Before this fix, if no subsection were visible by the user, the menu was crashing. Now, You need to be able to see at least one section to see the menu item.
`OK`: Done / …

PIM-6933: fix menu display in case of acl restriction

---

CHANGELOG-1.7.md
src/Akeneo/Bundle/StorageUtilsBundle/Doctrine/ORM/Cursor/Cursor.php
src/Akeneo/Bundle/StorageUtilsBundle/spec/Doctrine/ORM/Cursor/CursorFactorySpec.php
src/Akeneo/Bundle/StorageUtilsBundle/spec/Doctrine/ORM/Cursor/CursorSpec.php
src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/ProductRepository.php

Import creates some memory leak due to doctrine. I saw that every entity is well cleared but some doctrine objects are staying in doctrine cache (SingleSelectExecutor, ParserResult, ResultSetMapping).
**How it works?!**
Doctrine uses cache on DQL to avoid to transform many times the same thing.
That's why a good practice is to use named parameters instead of directly inject values.
**Now, where is the problem?!**
When we are using the pqb, we use uniqid() to join tables. It is working pretty well (as it creates a new uniq SQL join). Just it creates a memory leak on the DQL part (as each query is a new DQL and each one creates a cache)
Here is a query example:
```SELECT o FROM Pim\Component\Catalog\Model\Product o INNER JOIN o.values filteridentifier_product59e4a6351dfd2 WITH …
```

SDS-1772: Fix memory leak on product import

---

CHANGELOG-2.0.md
src/Pim/Bundle/ApiBundle/tests/integration/Controller/ProductModel/CreateProductModelIntegration.php
src/Pim/Component/Catalog/ProductModel/Filter/ProductModelAttributeFilter.php

When no values are provided via the API it raises a 500 in the ProductModelAttributeFilter as the variantAttribtueSet variable will be null. This PR aims to fix it.
| Added integration tests           | Yes

API-411: Fix missing case when no values are provided

---

CHANGELOG-2.0.md

Introducing features in patches sometimes induces adding new jobs. We use to do doctrine migration for new jobs but as discussed with @nidup for minor versions we prefer to document this change in the changelog.
A new internal job as been introduced here https://github.com/akeneo/pim-community-dev/pull/7006. 
This PR documents it in the changelog.  …

PIM-6806: Add new job instance in the changelog
