akeneo/pim-community-dev

src/Pim/Bundle/EnrichBundle/Resources/views/MassEditAction/configure/edit-common-attributes.html.twig
| CI currently passes? | N
| Tests pass?          |  Y
| Scenarios pass?      | Y
| Fixed tickets        | PIM-4528
=> Fix mass edit behat scenarios

src/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/CompletenessGenerator.php
| CI currently passes? |n
| Fixed tickets        |PIM-4079
=> PIM-4079 : mongodb completeness

src/Pim/Bundle/EnrichBundle/Resources/translations/messages.en.yml
| Bug fix?             | n
| CI currently passes? |n
| Scenarios pass?      |n
| Fixed tickets        |PIM-4481
| DB schema updated?   |n
| Migration script?    |n
| Doc PR               |n
=> PIM-4481: Added missing keys for mass edit

spec/Pim/Bundle/EnrichBundle/Connector/Processor/MassEdit/Family/SetAttributeRequirementsSpec.php, spec/Pim/Bundle/EnrichBundle/Connector/Processor/MassEdit/Product/AddProductToVariantGroupProcessorSpec.php, spec/Pim/Bundle/EnrichBundle/Connector/Processor/MassEdit/Product/AddProductValueProcessorSpec.php, spec/Pim/Bundle/EnrichBundle/Connector/Processor/MassEdit/Product/EditCommonAttributesProcessorSpec.php, spec/Pim/Bundle/EnrichBundle/Connector/Processor/MassEdit/Product/UpdateProductValueProcessorSpec.php, src/Pim/Bundle/EnrichBundle/Connector/Processor/MassEdit/Family/SetAttributeRequirements.php, src/Pim/Bundle/EnrichBundle/Connector/Processor/MassEdit/Product/AddProductToVariantGroupProcessor.php, src/Pim/Bundle/EnrichBundle/Connector/Processor/MassEdit/Product/AddProductValueProcessor.php, src/Pim/Bundle/EnrichBundle/Connector/Processor/MassEdit/Product/EditCommonAttributesProcessor.php, src/Pim/Bundle/EnrichBundle/Connector/Processor/MassEdit/Product/UpdateProductValueProcessor.php
| CI currently passes? | N
| Scenarios pass?      | N
| Fixed tickets        | PIM-4479
| DB schema updated?   | -
=> PIM-4479: Changed Mass Edited to Processed

src/Pim/Bundle/EnrichBundle/Resources/translations/messages.en.yml
| CI currently passes? | N
| Scenarios pass?      | N
| Fixed tickets        | PIM-4478
| DB schema updated?   | N
=> PIM-4478: changed launched mass edit message

spec/Pim/Bundle/EnrichBundle/Connector/Processor/MassEdit/Family/SetAttributeRequirementsSpec.php, spec/Pim/Bundle/EnrichBundle/Connector/Processor/MassEdit/Product/AddProductToVariantGroupProcessorSpec.php, spec/Pim/Bundle/EnrichBundle/Connector/Processor/MassEdit/Product/AddProductValueProcessorSpec.php, spec/Pim/Bundle/EnrichBundle/Connector/Processor/MassEdit/Product/EditCommonAttributesProcessorSpec.php, spec/Pim/Bundle/EnrichBundle/Connector/Processor/MassEdit/Product/UpdateProductValueProcessorSpec.php, src/Pim/Bundle/EnrichBundle/Connector/Processor/MassEdit/Family/SetAttributeRequirements.php, src/Pim/Bundle/EnrichBundle/Connector/Processor/MassEdit/Product/AddProductToVariantGroupProcessor.php, src/Pim/Bundle/EnrichBundle/Connector/Processor/MassEdit/Product/AddProductValueProcessor.php, src/Pim/Bundle/EnrichBundle/Connector/Processor/MassEdit/Product/EditCommonAttributesProcessor.php, src/Pim/Bundle/EnrichBundle/Connector/Processor/MassEdit/Product/UpdateProductValueProcessor.php
| CI currently passes? |n
| Scenarios pass?      |n
| Fixed tickets        | PIM-4479
| DB schema updated?   |n
| Migration script?    |n
| Doc PR               |n
=> PIM-4479: update keys

features/product/edit_locale_specific_value.feature, spec/Pim/Bundle/EnrichBundle/Normalizer/AttributeNormalizerSpec.php, src/Pim/Bundle/EnrichBundle/Normalizer/AttributeNormalizer.php, src/Pim/Bundle/EnrichBundle/Resources/public/js/manager/attribute-group-manager.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/manager/attribute-manager.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/field/field.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/attributes.js
| Fixed tickets        | PIM-4205
=> PIM-4205: fix locale specific

src/Pim/Bundle/EnrichBundle/Resources/public/js/product/field/wysiwyg-field.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/attributes.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/attributes/copy.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/form-tabs.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/panel/completeness.js, src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/tab/attributes/copy.html, src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml, src/Pim/Bundle/UIBundle/Resources/public/css/pim.less
| New feature?          | N
| Fixed tickets        | PIM-4460, PIM-4461, PIM-4462 and PIM-4489
=> PIM-4460, PIM-4461, PIM-4462 and PIM-4489

features/Context/Page/Product/Edit.php, features/Context/WebUser.php, features/product/completeness.feature, src/Pim/Bundle/EnrichBundle/Controller/Rest/CompletenessController.php, src/Pim/Bundle/EnrichBundle/Resources/public/js/fetcher/completeness-fetcher.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/attributes.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/meta/change-family.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/panel/completeness.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/save.js, src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/meta/family.html, src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/panel/completeness.html, src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml
| Fixed tickets        | PIM-4489
=> PIM-4489: fix family change bug

src/Pim/Bundle/EnrichBundle/Resources/public/js/attribute-option/create.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/attribute-option/form.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/edit-form.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/associations.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/attributes.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/attributes/add-attribute.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/attributes/copy.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/attributes/variant-group.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/categories.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/delete.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/download-pdf.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/meta/change-family.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/meta/created.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/meta/family.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/meta/groups.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/meta/updated.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/panel/comments.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/panel/completeness.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/panel/history.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/product-label.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/save.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/sequential-edit.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/state.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/status-switcher.js
| Fixed tickets        | PIM-4598
=> PIM-4598: use consistent way to get form data and form model

src/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/CompletenessGenerator.php, src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/AttributeRepository.php, src/Pim/Bundle/CatalogBundle/Repository/AttributeRepositoryInterface.php
Needed for assets management
| New feature?         |y
| Fixed tickets        |PIM-4074
=> PIM-4074 : Add getAttributeCodesByType() in attribute repo

src/Pim/Bundle/EnrichBundle/Resources/public/js/manager/attribute-manager.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/field/price-collection-field.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/attributes.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/attributes/add-attribute.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/save.js
| New feature?         | N 
| BC breaks?           | N 
| CI currently passes? | Y 
| Scenarios pass?      | ? 
| Checkstyle issues?*  | N 
| PMD issues?**        | N 
| Changelog updated?   | N 
| Fixed tickets        | PIM-4601, PIM-4602 and PIM-4459
=> PIM-4601, PIM-4602 and PIM-4459

features/import/attribute/import_attributes.feature, spec/Pim/Component/Catalog/Updater/AttributeUpdaterSpec.php, src/Pim/Bundle/CatalogBundle/Resources/config/updaters.yml, src/Pim/Component/Catalog/Updater/AttributeUpdater.php, src/Pim/Component/Connector/ArrayConverter/Flat/AttributeStandardConverter.php
| Bug fix?             | n
| CI currently passes? | y
| Tests pass?          | y 
| Scenarios pass?      | y 
| PMD issues?**        | y
| Changelog updated?   | n
| Fixed tickets        | PIM-4595
| DB schema updated?   | n 
| Migration script?    | n
| Doc PR               | n
=> [TR] PIM-4595: Added missing columns for csv attribute import

src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/state.js
https://akeneo.atlassian.net/browse/PIM-4513
| CI currently passed? | Y
| Tests pass?          | 
| Scenarios pass?      | 
| Changelog updated?   | -
| Fixed tickets        | PIM-4513
| Related CE PR        | -
=> [TR] PIM-4513: Send a draft for approval

features/Context/Page/Product/Creation.php, features/product/create_product.feature, src/Pim/Bundle/EnrichBundle/Resources/public/js/manager/attribute-manager.js
| Fixed tickets        |PIM-4582
=> PIM-4582 : initialize prices collection if not defined

features/Context/Page/Base/Grid.php
| Fixed tickets        |PIM-4613
=> PIM-4613 : fix sorted dates features

CHANGELOG.md, spec/Akeneo/Bundle/StorageUtilsBundle/Doctrine/Common/Remover/BaseRemoverSpec.php, spec/Akeneo/Bundle/StorageUtilsBundle/Doctrine/Common/Remover/BaseRemovingOptionsResolverSpec.php, spec/Akeneo/Bundle/StorageUtilsBundle/Doctrine/Common/Saver/BaseSaverSpec.php, spec/Akeneo/Bundle/StorageUtilsBundle/Doctrine/Common/Saver/BaseSavingOptionsResolverSpec.php, spec/Akeneo/Component/FileStorage/RawFile/RawFileStorerSpec.php, spec/Pim/Bundle/CatalogBundle/Doctrine/Common/Saver/ProductSavingOptionsResolverSpec.php, src/Akeneo/Bundle/StorageUtilsBundle/Doctrine/Common/Remover/BaseRemover.php, src/Akeneo/Bundle/StorageUtilsBundle/Doctrine/Common/Remover/BaseRemovingOptionsResolver.php, src/Akeneo/Bundle/StorageUtilsBundle/Doctrine/Common/Saver/BaseSaver.php, src/Akeneo/Bundle/StorageUtilsBundle/Doctrine/Common/Saver/BaseSavingOptionsResolver.php, src/Akeneo/Component/FileStorage/RawFile/RawFileStorer.php, src/Akeneo/Component/StorageUtils/Cursor/PaginatorFactory.php, src/Pim/Bundle/CatalogBundle/Command/QueryProductCommand.php, src/Pim/Bundle/CatalogBundle/Doctrine/Common/Saver/ProductSavingOptionsResolver.php, src/Pim/Bundle/CatalogBundle/Resources/config/query_builders.yml
- http://core-ci.akeneo.com/job/pim-pr-behat/2922/consoleFull
- http://core-ci.akeneo.com/job/pim-pr-behat-mongodb/988/consoleFull
CI is blue
=> Doc updater api

src/Pim/Bundle/EnrichBundle/Resources/config/acl.yml, src/Pim/Bundle/EnrichBundle/Resources/config/navigation.yml
| Bug fix?             |
| New feature?         |
| BC breaks?           |
| CI currently passes? | y
| Scenarios pass?      | running
| Checkstyle issues?*  |
| PMD issues?**        |
| Changelog updated?   |
| Fixed tickets        | PIM-4424
http://core-ci.akeneo.com/job/pim-pr-behat/2931/
=> PIM-4424: Add a link in the menu to the process tracker

features/Context/Page/Base/Grid.php
=> [TR] fix Grid spin

src/Pim/Bundle/CatalogBundle/Command/UpdateProductCommand.php, src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/ProductRepository.php, src/Pim/Bundle/UserBundle/Provider/UserProvider.php
| Bug fix?             |
| New feature?         |
| BC breaks?           |
| CI currently passes? | y
| Scenarios pass?      | running
| Changelog updated?   | n
http://core-ci.akeneo.com/job/pim-pr-behat/2941/console
http://core-ci.akeneo.com/job/pim-pr-behat-mongodb/1001/console
=> PIM-4596: Fix return value for orm repo

src/Pim/Bundle/CatalogBundle/Command/QueryProductCommand.php, src/Pim/Bundle/CatalogBundle/Resources/config/query_builders.yml
| Bug fix?             | N (DX)
| Fixed tickets        | 
=> PIM-4446: revert the change of query product command

src/Akeneo/Component/FileStorage/RawFile/RawFileStorer.php, src/Pim/Component/Catalog/Updater/Setter/MediaAttributeSetter.php
=> Remove "flush_only_object"

src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/job_tracker.yml, src/Pim/Bundle/ImportExportBundle/Entity/Repository/JobExecutionRepository.php
| Scenarios pass?      | Running http://core-ci.akeneo.com/job/pim-pr-behat/2952/
| Fixed tickets        | PIM-4651 PIM-4650
=> PIM-4651: fix status filter and default sort order in process tracker grid

features/product/completeness.feature
2nd one will be fixed by https://github.com/akeneo/pim-community-dev/pull/2992/files#diff-a2988c5074487798f8b37dad09d7124aR249
=> PIM-4489: fix a completeness behat scenario, skip another, the fix is coming

CHANGELOG.md, features/Context/FixturesContext.php, spec/Pim/Component/Catalog/Updater/Copier/MediaAttributeCopierSpec.php, src/Akeneo/Component/FileStorage/FileFactory.php, src/Pim/Bundle/CatalogBundle/Resources/config/updaters.yml, src/Pim/Component/Catalog/Updater/Copier/MediaAttributeCopier.php
=> [POC] PIM-4526: Refactor copier to works with new media management

src/Pim/Bundle/EnrichBundle/Resources/public/js/product/field/date-field.js, src/Pim/Bundle/ReferenceDataBundle/Doctrine/ORM/Sorter/ReferenceDataSorter.php, src/Pim/Bundle/UIBundle/Resources/public/css/pim.less
| Behats             | 2 failures
| Changelog updated  | Not necessary
=> Bunch of fixes related to PEF

src/Pim/Bundle/TransformBundle/Normalizer/Flat/FileNormalizer.php
| Behats             | -
| Specs & Static     | -
=> PIM-4261: fix quick export

features/import/product/import_products_with_media.feature, features/product/validation/validate_file_attributes.feature, features/product/validation/validate_image_attributes.feature
=> PIM-4605: fix file size

CHANGELOG.md, features/Context/Page/Category/CategoryView.php, features/Context/SpinCapableTrait.php, features/Context/WebUser.php, features/product/classify_product.feature, spec/Pim/Bundle/CatalogBundle/Manager/CategoryManagerSpec.php, spec/Pim/Bundle/EnrichBundle/Form/Type/MassEditAction/ClassifyTypeSpec.php, src/Pim/Bundle/CatalogBundle/Manager/CategoryManager.php, src/Pim/Bundle/CatalogBundle/Repository/CategoryRepositoryInterface.php, src/Pim/Bundle/CatalogBundle/Resources/config/managers.yml, src/Pim/Bundle/EnrichBundle/Controller/CategoryTreeController.php, src/Pim/Bundle/EnrichBundle/Controller/ProductController.php, src/Pim/Bundle/EnrichBundle/Controller/Rest/ProductCategoryController.php, src/Pim/Bundle/EnrichBundle/Form/Type/MassEditAction/ClassifyType.php, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/categories.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/tree-associate.jstree.js, src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/tab/categories.html
| BC breaks?           |y
| Changelog updated?   |y
| Fixed tickets        |PIM-4533
=> [TR] PIM-4533 : add selected categories count

spec/Pim/Component/Catalog/Comparator/Attribute/FileComparatorSpec.php, src/Pim/Component/Catalog/Comparator/Attribute/FileComparator.php
=> PIM-4261: added missing case for file comparator

features/Context/DataGridContext.php, features/Context/Page/Base/Grid.php, features/Context/Page/Product/Edit.php, features/Context/WebUser.php, src/Pim/Bundle/DataGridBundle/DependencyInjection/PimDataGridExtension.php, src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid/action/abstract-action.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/form-tabs.js
https://akeneo.atlassian.net/browse/PIM-3980
| Behats             | -
| Specs & Static     | -
=> [TR] PIM-3980: Proposals tab

app/Resources/jenkins/behat/run_behat.sh, build.xml
=> Jenkins filtered jobs

CHANGELOG.md, spec/Pim/Bundle/BaseConnectorBundle/Reader/ORM/CategoryReaderSpec.php, src/Pim/Bundle/BaseConnectorBundle/Reader/ORM/CategoryReader.php, src/Pim/Bundle/ClassificationBundle/Doctrine/ORM/Repository/CategoryRepository.php, src/Pim/Component/Classification/Repository/CategoryRepositoryInterface.php
| Changelog updated  | y
http://core-ci.akeneo.com/job/pim-pr-behat/3041/consoleFull
=> [TR][PAM]PIM-4690: Refactor the CategoryReader

src/Pim/Bundle/UIBundle/Controller/AjaxOptionController.php, src/Pim/Bundle/UIBundle/Form/Type/AjaxEntityType.php, src/Pim/Bundle/UIBundle/Resources/public/js/pim-initselect2.js, src/Pim/Bundle/UIBundle/Tests/Unit/Controller/AjaxOptionControllerTest.php, src/Pim/Bundle/UIBundle/Tests/Unit/Form/Type/AjaxEntityTypeTest.php
https://akeneo.atlassian.net/browse/PIM-4406
=> [TR][PAM] PIM-4406: Create an asset tag if it doesn't exist

features/Context/AssertionContext.php, features/Context/NavigationContext.php, features/Context/Page/Base/Base.php, features/Context/Page/Product/Edit.php, features/Context/SpinCapableTrait.php, features/Context/WebUser.php, features/product/join_an_image_to_a_product.feature, features/product/validation/validate_file_attributes.feature, features/product/validation/validate_image_attributes.feature, src/Pim/Bundle/DataGridBundle/Datasource/ResultRecord/Orm/ObjectIdHydrator.php, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions.yml, src/Pim/Bundle/EnrichBundle/Resources/public/js/manager/product-manager.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/edit-form.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/back-to-grid.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/sequential-edit.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/state.js, src/Pim/Bundle/EnrichBundle/Resources/views/Product/edit.html.twig, src/Pim/Bundle/UIBundle/Resources/public/js/mediator.js, src/Pim/Bundle/UIBundle/Resources/public/lib/underscore/underscore.js
=> [TR] PIM-4639: fix cache clearer

CHANGELOG.md, features/association-type/create_association_type.feature, features/attribute/create_text_attribute.feature, features/family/create_family.feature, features/group-type/create_group_type.feature, features/product-group/create_product_group.feature, features/variant-group/create_variant_group.feature, src/Pim/Bundle/CatalogBundle/Command/ValidateObjectsCommand.php, src/Pim/Bundle/CatalogBundle/Resources/config/validation/associationType.yml, src/Pim/Bundle/CatalogBundle/Resources/config/validation/attribute.yml, src/Pim/Bundle/CatalogBundle/Resources/config/validation/attributegroup.yml, src/Pim/Bundle/CatalogBundle/Resources/config/validation/category.yml, src/Pim/Bundle/CatalogBundle/Resources/config/validation/channel.yml, src/Pim/Bundle/CatalogBundle/Resources/config/validation/family.yml, src/Pim/Bundle/CatalogBundle/Resources/config/validation/group.yml, src/Pim/Bundle/CatalogBundle/Resources/config/validation/grouptype.yml, src/Pim/Bundle/CatalogBundle/Resources/translations/validators.en.yml, src/Pim/Bundle/JsFormValidationBundle/Generator/FormValidationScriptGenerator.php
| Behats             | ok
| Specs & Static     | yes
| Changelog updated  | yes
=> PIM-4443: Full numeric entities code are now forbidden

CHANGELOG.md, spec/Pim/Bundle/CatalogBundle/Builder/ChoicesBuilderSpec.php, spec/Pim/Bundle/CatalogBundle/Manager/LocaleManagerSpec.php, spec/Pim/Bundle/UserBundle/Context/UserContextSpec.php, src/Pim/Bundle/CatalogBundle/Builder/ChoicesBuilder.php, src/Pim/Bundle/CatalogBundle/Builder/ChoicesBuilderInterface.php, src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/LocaleRepository.php, src/Pim/Bundle/CatalogBundle/Entity/Channel.php, src/Pim/Bundle/CatalogBundle/Manager/ChannelManager.php, src/Pim/Bundle/CatalogBundle/Manager/LocaleManager.php, src/Pim/Bundle/CatalogBundle/Model/ChannelInterface.php, src/Pim/Bundle/CatalogBundle/Model/ChosableInterface.php, src/Pim/Bundle/CatalogBundle/Resources/config/builders.yml, src/Pim/Bundle/UserBundle/Context/UserContext.php, src/Pim/Bundle/UserBundle/Resources/config/context.yml
=> [TR][PAM] PIM-4729: Add ChoicesBuilder / UserContext cleaning

features/import/product/import_products_with_invalid_data.feature, features/import/product/import_products_with_invalid_headers.feature, spec/Pim/Component/Connector/ArrayConverter/Flat/ProductAssociationStandardConverterSpec.php, spec/Pim/Component/Connector/ArrayConverter/Flat/ProductStandardConverterSpec.php, spec/Pim/Component/Connector/ArrayConverter/Flat/VariantGroupStandardConverterSpec.php, spec/Pim/Component/Connector/Processor/Denormalization/ProductAssociationProcessorSpec.php, spec/Pim/Component/Connector/Processor/Denormalization/ProductProcessorSpec.php, src/Pim/Bundle/ConnectorBundle/Resources/config/array_converters.yml, src/Pim/Component/Connector/ArrayConverter/Flat/ProductAssociationStandardConverter.php, src/Pim/Component/Connector/ArrayConverter/Flat/ProductStandardConverter.php, src/Pim/Component/Connector/ArrayConverter/Flat/VariantGroupStandardConverter.php, src/Pim/Component/Connector/Processor/Denormalization/ProductAssociationProcessor.php, src/Pim/Component/Connector/Processor/Denormalization/ProductProcessor.php
| Behats             | Running
=> PIM-4698: rework the ProductStandardConverter

features/import/product/import_products_with_invalid_data.feature, spec/Pim/Component/Connector/Processor/Denormalization/ProductProcessorSpec.php, src/Pim/Component/Connector/ArrayConverter/Flat/ProductStandardConverter.php, src/Pim/Component/Connector/Processor/Denormalization/ProductProcessor.php
=> PIM-4696: skip product during an import when the identifier is empty

features/dashboard/display_last_operations_widget.feature, features/datagrid/products_category_backtothegrid.feature
=> [TR] Put unstable tags on feature which bug sometimes

src/Pim/Component/Connector/Reader/File/CsvReader.php
Related to https://github.com/facebook/hhvm/issues/5823
=> [TR] Allow CsvReader to correctly handle the end of file for HHVM

features/Context/NavigationContext.php, features/Context/Page/Product/Edit.php
=> [TR] behat : fix label search

spec/Pim/Component/Catalog/Updater/Setter/TextAttributeSetterSpec.php, src/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/Filter/StringFilter.php, src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Filter/StringFilter.php, src/Pim/Component/Catalog/Updater/Setter/TextAttributeSetter.php
| Fixed tickets        |PIM-4581
=> PIM-4581 : empty string values should be null in database

features/Context/Page/Base/Form.php, features/Context/WebUser.php, spec/Pim/Bundle/EnrichBundle/Filter/ProductEditDataFilterSpec.php, src/Pim/Bundle/EnrichBundle/Controller/Rest/ProductController.php, src/Pim/Bundle/EnrichBundle/Filter/ProductEditDataFilter.php
=> PIM-4483: Do not allow to classify a product i am not an owner

features/mass-action/mass_edit_variant_group_products.feature, features/mass-action/quick_export.feature, features/notifications/display_notifications_when_mass_edit_jobs_are_finished.feature, spec/Pim/Bundle/NotificationBundle/EventSubscriber/JobExecutionNotifierSpec.php, src/Pim/Bundle/EnrichBundle/Resources/translations/messages.en.yml, src/Pim/Bundle/NotificationBundle/EventSubscriber/JobExecutionNotifier.php, src/Pim/Bundle/NotificationBundle/Resources/public/js/notification-list.js, src/Pim/Bundle/NotificationBundle/Resources/views/Notification/list.json.twig
Add extra information in notification as action type and created at to prepare the style revamp
=> PIM-4744: add extra information in the notifications

.gitignore, app/config/pim_parameters.yml, src/Pim/Bundle/EnrichBundle/Resources/config/bundles/oneup_flysystem.yml, src/Pim/Bundle/EnrichBundle/Resources/config/controllers.yml, src/Pim/Bundle/EnrichBundle/Resources/config/resolvers.yml, src/Pim/Component/Catalog/FileStorage.php
=> [TR] PIM-4093: rename the base catalog storage filesystem

CHANGELOG.md, features/product/create_product.feature, spec/Pim/Bundle/CatalogBundle/Validator/ConstraintGuesser/IdentifierGuesserSpec.php, src/Pim/Bundle/CatalogBundle/Resources/config/validators.yml, src/Pim/Bundle/CatalogBundle/Resources/translations/validators.en.yml, src/Pim/Bundle/CatalogBundle/Validator/ConstraintGuesser/IdentifierGuesser.php
=> PIM-4706: Added validation on sku to not allow comma or semicolon

app/Resources/jenkins/behat/run_behat.sh, src/Pim/Bundle/InstallerBundle/Command/CheckRequirementsCommand.php, src/Pim/Bundle/InstallerBundle/Command/InstallCommand.php, src/Pim/Bundle/InstallerBundle/PimDirectoriesRegistry.php, src/Pim/Bundle/InstallerBundle/Resources/config/services.yml
=> [TR] PIM-4093: define dynamically the directories to check for installation

features/Context/catalog/apparel/attributes.yml, features/product/edit_locale_specific_value.feature, src/Pim/Bundle/EnrichBundle/Filter/ProductEditDataFilter.php, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/field/field.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/attributes/copy-field.js, src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml
| Specs & Static     | Runnin'
=> PIM-4708: Handle locale specific feature in the new PEF

features/Context/Page/Product/Edit.php, features/Context/WebUser.php, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/field/media-field.js
=> [TR] PIM-4477: Be able to find the trash icon for media

features/Context/WebUser.php, src/Pim/Bundle/TransformBundle/Denormalizer/Flat/ProductValue/AttributeOptionDenormalizer.php, src/Pim/Bundle/TransformBundle/Denormalizer/Flat/ProductValue/MetricDenormalizer.php, src/Pim/Bundle/TransformBundle/Denormalizer/Flat/ProductValue/PricesDenormalizer.php
=> [TR] PIM-4751: restore a version with a media in it

CHANGELOG.md, features/Context/FixturesContext.php, features/product/edit_product_with_many_locales.feature, spec/Pim/Bundle/CatalogBundle/Doctrine/ORM/ProductRepositorySpec.php, src/Pim/Bundle/CatalogBundle/Doctrine/ORM/ProductRepository.php
=> [TR][SLA] PIM-4748: remove left joins to fix perf issue with many locales

CHANGELOG.md, features/product/filtering/filter_products.feature, spec/Pim/Bundle/FilterBundle/Filter/ProductValue/StringFilterSpec.php, src/Pim/Bundle/FilterBundle/Filter/ProductValue/StringFilter.php
=> PIM-4756: Fixed string filter that starts with '0'

CHANGELOG.md, spec/Pim/Bundle/CatalogBundle/Doctrine/ORM/ProductRepositorySpec.php, src/Pim/Bundle/CatalogBundle/Doctrine/ORM/ProductRepository.php
| Behats             | N/A
| Fixed issues | #3028
=> PIM-4758: Fixed attribute filtering on method getFullProducts

src/Pim/Bundle/EnrichBundle/Controller/FileController.php, src/Pim/Bundle/EnrichBundle/Resources/config/controllers.yml
=> [TR] PIM-4759: cache the default image

app/SymfonyRequirements.php, app/check.php, src/Pim/Bundle/EnrichBundle/Resources/translations/messages.en.yml, src/Pim/Bundle/UIBundle/Resources/public/css/notifications.less
=> PIM-4757: normalize notification translation keys

features/mass-action/quick_export.feature, src/Pim/Bundle/DataGridBundle/Controller/ProductExportController.php, src/Pim/Bundle/EnrichBundle/Connector/Reader/MassEdit/FilteredProductReader.php, src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/product.yml
=> [TR] PIM-4705: Update controller and grid to be able to configure job to launch with quick export

CHANGELOG.md, features/Context/Page/Base/Form.php, features/Context/WebUser.php, features/product/add_new_option_to_choice_attribute.feature, src/Pim/Bundle/UIBundle/Resources/public/js/pim-initselect2.js
| Bug fix?             | yes
| New feature?         | no
| BC breaks?           | no
| CI currently passes? | yes
| Scenarios pass?      | yes
| Checkstyle issues?*  | no
| PMD issues?**        | no
| Changelog updated?   | yes
| Fixed tickets        | PIM-4737
| DB schema updated?   | no
| Migration script?    | no
=> [TR] [SLA] PIM-4737: Fix a bug with the select2 cache.

CHANGELOG.md, features/Context/FixturesContext.php, features/product/edit_product.feature, spec/Pim/Bundle/CatalogBundle/EventSubscriber/TimestampableSubscriberSpec.php, spec/Pim/Bundle/VersioningBundle/EventSubscriber/TimestampableSubscriberSpec.php, src/Pim/Bundle/CatalogBundle/EventSubscriber/TimestampableSubscriber.php, src/Pim/Bundle/VersioningBundle/EventSubscriber/TimestampableSubscriber.php, src/Pim/Bundle/VersioningBundle/Resources/config/event_subscribers.yml, src/Pim/Bundle/VersioningBundle/Resources/config/storage_driver/doctrine/mongodb-odm.yml, src/Pim/Bundle/VersioningBundle/Resources/config/storage_driver/doctrine/orm.yml
=> PIM-4753: Fix updated date issues

spec/Akeneo/Component/FileStorage/RawFile/RawFileFetcherSpec.php, spec/Pim/Component/Catalog/Updater/Copier/MediaAttributeCopierSpec.php, src/Akeneo/Bundle/FileStorageBundle/Resources/config/file_storage.yml, src/Akeneo/Component/FileStorage/RawFile/RawFileFetcher.php, src/Pim/Component/Catalog/Updater/Copier/MediaAttributeCopier.php
=> [TR] Fix CI master

spec/Pim/Bundle/VersioningBundle/EventSubscriber/TimestampableSubscriberSpec.php, src/Pim/Bundle/VersioningBundle/EventSubscriber/TimestampableSubscriber.php
=> PIM-4753 (bis): More robust way to deal with updated date issue

features/export/export_products_and_download_exported_file.feature, features/import/product/import_products_and_download_imported_file.feature, spec/Pim/Bundle/BaseConnectorBundle/Archiver/FileReaderArchiverSpec.php, src/Pim/Bundle/BaseConnectorBundle/Archiver/FileReaderArchiver.php, src/Pim/Bundle/BaseConnectorBundle/Resources/config/archiving.yml
| Behats             | Y (local, only new behat)
=> [TR] PIM-4773: revert dropped archiver and add missing behat scenario

app/config/security.yml, composer.json, features/Context/FixturesContext.php, features/Context/Loader/UserLoader.php, spec/Pim/Bundle/DataGridBundle/Entity/DatagridViewSpec.php, spec/Pim/Bundle/DataGridBundle/Extension/Formatter/Property/Version/AuthorPropertySpec.php, spec/Pim/Bundle/EnrichBundle/Normalizer/VersionNormalizerSpec.php, spec/Pim/Bundle/VersioningBundle/EventSubscriber/AddUserSubscriberSpec.php, src/Pim/Bundle/CommentBundle/Resources/config/doctrine/Comment.orm.yml, src/Pim/Bundle/DataGridBundle/Entity/DatagridView.php, src/Pim/Bundle/DataGridBundle/Resources/config/doctrine/DatagridView.orm.yml, src/Pim/Bundle/UserBundle/Context/UserContext.php, src/Pim/Bundle/UserBundle/Entity/Repository/GroupRepository.php, src/Pim/Bundle/UserBundle/Entity/Repository/RoleRepository.php, src/Pim/Bundle/UserBundle/Entity/User.php, src/Pim/Bundle/UserBundle/EventSubscriber/GroupSubscriber.php, src/Pim/Bundle/UserBundle/Form/Handler/ResetHandler.php, src/Pim/Bundle/UserBundle/Form/Handler/UserHandler.php, src/Pim/Bundle/UserBundle/Normalizer/UserNormalizer.php, src/Pim/Bundle/UserBundle/Resources/config/datagrid/user-relation.yml, src/Pim/Bundle/UserBundle/Resources/config/doctrine/User.orm.yml, src/Pim/Bundle/UserBundle/Resources/config/entities.yml, src/Pim/Bundle/UserBundle/Resources/config/validation.yml, src/Pim/Bundle/VersioningBundle/Doctrine/ORM/VersionRepository.php
http://core-ci.akeneo.com/job/pim-pr-behat/3152/console
=> [TR] PIM-4781: Move User class from Oro to PIM

CHANGELOG.md, features/Context/FixturesContext.php, features/product/edit_product_with_many_locales.feature, spec/Pim/Bundle/CatalogBundle/Doctrine/ORM/ProductRepositorySpec.php, src/Pim/Bundle/CatalogBundle/Doctrine/ORM/ProductRepository.php
=> Pim 4780 / PIM-4748: remove left joins to fix perf issue with many locales

features/Context/AssertionContext.php, src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/product.yml, src/Pim/Bundle/EnrichBundle/Resources/config/requirejs.yml, src/Pim/Bundle/EnrichBundle/Resources/public/js/fetcher/base-fetcher.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/form/builder.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/field/media-field.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/attributes.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/attributes/attribute-group-selector.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/form-tabs.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/panel/history.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/panel/panels.js, src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/form-tabs.html, src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml
| Specs & Static     | ?
| Changelog updated  |
=> PIM-4765: rework history panel

src/Pim/Bundle/CommentBundle/Resources/config/doctrine/Comment.orm.yml, src/Pim/Bundle/DataGridBundle/Entity/DatagridView.php, src/Pim/Bundle/DataGridBundle/Resources/config/doctrine/DatagridView.orm.yml, src/Pim/Bundle/EnrichBundle/Resources/config/doctrine/SequentialEdit.orm.yml, src/Pim/Bundle/InstallerBundle/DataFixtures/ORM/LoadUserData.php, src/Pim/Bundle/NotificationBundle/Resources/config/doctrine/UserNotification.orm.yml, src/Pim/Bundle/UserBundle/Context/UserContext.php, src/Pim/Bundle/UserBundle/DependencyInjection/Compiler/ResolveDoctrineTargetModelPass.php, src/Pim/Bundle/UserBundle/Entity/User.php, src/Pim/Bundle/UserBundle/Entity/UserInterface.php, src/Pim/Bundle/UserBundle/Form/Handler/ResetHandler.php, src/Pim/Bundle/UserBundle/Form/Handler/UserHandler.php, src/Pim/Bundle/UserBundle/Normalizer/UserNormalizer.php, src/Pim/Bundle/UserBundle/PimUserBundle.php, src/Pim/Bundle/UserBundle/Validator/Constraints/UserPreferencesValidator.php
http://core-ci.akeneo.com/job/pim-pr-behat/3160/
=> PIM-4781: Add user interface

src/Pim/Bundle/BaseConnectorBundle/Writer/File/CsvProductWriter.php, src/Pim/Bundle/BaseConnectorBundle/Writer/File/CsvWriter.php
| Migration script?  |
| Changelog updated  |
=> [TR] PIM-4759: fix various exports

features/Context/NavigationContext.php, features/variant-group/add_products.feature
| Bug fix?             | y
| CI currently passes? | y
| Scenarios pass?      | y
| Changelog updated?   | n
| Fixed tickets        | /
=> [TR] Fix assertAddress

.gitignore, src/Pim/Bundle/UIBundle/Resources/public/js/pim-initselect2.js
Travis builds are broken because of small errors in js files, here is the fixing PR.
=> Fix jshint errors

features/Context/Page/JobTracker/Index.php
=> Fix behat assert address for job tracker

features/product/add_new_option_to_choice_attribute.feature
The way to create option from behat has been totally reworked since 1.3, that's why this scenario fails
As unstable as other scenario of this file with the PEF
=> PIM-4737: fix add new option scenario (issue post merge)

src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/meta/created.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/meta/groups.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/meta/updated.js, src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/meta/created.html, src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/meta/groups.html, src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/meta/updated.html
=> [TR] Fixes for PEF

features/Context/DataGridContext.php, features/Context/Page/Base/Form.php, features/product/associate_product.feature, src/Pim/Bundle/EnrichBundle/Resources/public/js/manager/attribute-manager.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/manager/product-manager.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/associations.js
=> [TR] Fixes on PEF

features/user/browse_roles.feature, features/user/create_edit_and_delete_role.feature
=> PIM-4759: fix PAM behats

CHANGELOG.md, features/Context/AssertionContext.php, src/Pim/Bundle/EnrichBundle/Controller/ProductController.php, src/Pim/Bundle/EnrichBundle/Controller/Rest/ProductController.php, src/Pim/Bundle/EnrichBundle/Resources/config/controllers.yml, src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/product.yml, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/product_edit.yml, src/Pim/Bundle/EnrichBundle/Resources/config/requirejs.yml, src/Pim/Bundle/EnrichBundle/Resources/config/routing/product.yml, src/Pim/Bundle/EnrichBundle/Resources/public/js/i18n.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/manager/product-manager.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/meta/family.js, src/Pim/Bundle/EnrichBundle/Resources/public/templates/i18n/flag.html, src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/meta/family.html
=> [TR] PIM-4762: rework product manager

src/Pim/Bundle/DataGridBundle/Datasource/ResultRecord/MongoDbOdm/AssociatedProductHydrator.php
| Behats             | Y (8 failing on EE but for another issue)
=> PIM-4800: avoid aggregation pipeline on empty results

spec/Pim/Component/Catalog/Comparator/Attribute/FileComparatorSpec.php, src/Pim/Bundle/TransformBundle/Normalizer/Structured/ProductValuesNormalizer.php, src/Pim/Component/Catalog/Comparator/Attribute/FileComparator.php, src/Pim/Component/Connector/ArrayConverter/Flat/ProductStandardConverter.php
| Behats             | ok
| Changelog updated  | no
=> [TR] PIM-4789: Fix FileNormalizer and FileComparator

src/Akeneo/Bundle/FileStorageBundle/Command/StoreFileCommand.php
=> [TR] PIM-4551: move the file storage command

CHANGELOG.md, spec/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/ProductRepositorySpec.php, spec/Pim/Bundle/CatalogBundle/Manager/ProductManagerSpec.php, spec/Pim/Bundle/DataGridBundle/Extension/MassAction/Util/ProductFieldsBuilderSpec.php, src/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/ProductRepository.php, src/Pim/Bundle/CatalogBundle/Manager/ProductManager.php, src/Pim/Bundle/CatalogBundle/Manager/ProductManagerInterface.php, src/Pim/Bundle/DataGridBundle/Extension/MassAction/Util/ProductFieldsBuilder.php
=> [TR] PIM-4612: Fixed Quick Export on mongo

src/Pim/Bundle/EnrichBundle/Filter/ProductEditDataFilter.php, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/associations.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/categories.js
The purpose of changes in `ProductEditDataFilter.php` is to have this class really easy to override.
=> [TR] PIM-4797: Hide the Associations tab when I am not the owner

features/Context/Page/Base/Form.php, features/user/edit_user.feature, spec/Pim/Bundle/DataGridBundle/Datagrid/Configuration/Product/FiltersConfiguratorSpec.php, spec/Pim/Bundle/DataGridBundle/EventListener/ConfigureProductFiltersListenerSpec.php, spec/Pim/Bundle/DataGridBundle/Form/Type/DatagridFilterChoiceTypeSpec.php, spec/Pim/Bundle/DataGridBundle/Twig/FilterExtensionSpec.php, src/Pim/Bundle/DataGridBundle/Datagrid/Configuration/Product/FiltersConfigurator.php, src/Pim/Bundle/DataGridBundle/DependencyInjection/PimDataGridExtension.php, src/Pim/Bundle/DataGridBundle/EventListener/ConfigureProductFiltersListener.php, src/Pim/Bundle/DataGridBundle/Form/Type/DatagridFilterChoiceType.php, src/Pim/Bundle/DataGridBundle/Resources/config/event_listeners.yml, src/Pim/Bundle/DataGridBundle/Resources/config/form_types.yml, src/Pim/Bundle/DataGridBundle/Resources/config/twig.yml, src/Pim/Bundle/DataGridBundle/Twig/FilterExtension.php, src/Pim/Bundle/UserBundle/Entity/User.php, src/Pim/Bundle/UserBundle/Entity/UserInterface.php, src/Pim/Bundle/UserBundle/Form/Type/UserType.php, src/Pim/Bundle/UserBundle/Resources/config/doctrine/User.orm.yml, src/Pim/Bundle/UserBundle/Resources/translations/messages.en.yml, src/Pim/Bundle/UserBundle/Resources/views/User/Tab/additional.html.twig, src/Pim/Bundle/UserBundle/Resources/views/User/view.html.twig, upgrades/schema/Version_1_4_20150819143301_user_product_grid_filters.php
=> PIM-3970: Define as a user preference what are the displayed filters

features/product/edit_localizable_value.feature, features/product/ensure_variant_read_only.feature, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/product_edit.yml, src/Pim/Bundle/EnrichBundle/Resources/config/requirejs.yml, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/field/field.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/attributes/copy-field.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/attributes/copy.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/attributes/locale-specific.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/attributes/localizable.js, src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/field/field.html, src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/tab/attributes/copy-field.html, src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml
=> [TR] PIM-4536: Forbid to add values for an in-existing couple Channel / Locale

app/Resources/jenkins/behat/run_behat.sh, build.xml
This PR allows to select which Behat features dir or feature file to run on the PR. Multiple values can be provided.
Example:
locale:product/download_product.feature:channel
=> will run all features from features/locale and features/channel, as well as the features/product/download_product.feature file
| Migration script?  | N.A.
| Behats             | OK
| Specs & Static     | N.A.
| Changelog updated  | N.A. (internal tooling)
=> [TR] Allow to select the Behat feature dirs or files to run on CI

features/mass-action/edit_common_attributes.feature, spec/Pim/Bundle/CatalogBundle/Model/ProductSpec.php, spec/Pim/Bundle/EnrichBundle/Connector/Processor/MassEdit/Product/EditCommonAttributesProcessorSpec.php, src/Pim/Bundle/CatalogBundle/Model/AbstractProduct.php, src/Pim/Bundle/CatalogBundle/Model/ProductInterface.php, src/Pim/Bundle/EnrichBundle/Connector/Processor/MassEdit/Product/EditCommonAttributesProcessor.php
=> PIM-4777: Fixed mass edit of an attribute inclued in a variant group

src/Pim/Bundle/EnrichBundle/Resources/config/controllers.yml, src/Pim/Bundle/EnrichBundle/Resources/public/js/fetcher/base-fetcher.js
https://akeneo.atlassian.net/browse/PIM-4793
| Behats             | OK
| Specs & Static     | No regression
=> [PAM][TR] PIM-4793: Display relevant thumbnails of assets (PEF edition)

features/Context/Page/Product/Edit.php, spec/Pim/Bundle/EnrichBundle/Normalizer/AttributeNormalizerSpec.php, src/Pim/Bundle/CommentBundle/Resources/public/css/comment.less, src/Pim/Bundle/EnrichBundle/Controller/Rest/ProductController.php, src/Pim/Bundle/EnrichBundle/Normalizer/AttributeNormalizer.php, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/field/multi-select-field.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/field/simple-select-field.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/associations.js, src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/field/multi-select.html, src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/field/simple-select.html, src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/panel/completeness.html, src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/tab/categories.html, src/Pim/Bundle/UIBundle/Resources/public/css/pim.less
=> [TR] Bunch of fixes related to PEF

features/user/edit_user.feature
=> PIM-4736: fix ci

composer.json
=> PIM-4781: change the platform branch

features/reference-data/variant-group/create_variant_group.feature, spec/Pim/Bundle/ReferenceDataBundle/DataGrid/Extension/Selector/ORM/ReferenceDataSelectorSpec.php, src/Pim/Bundle/EnrichBundle/Twig/ViewElementExtension.php, src/Pim/Bundle/ReferenceDataBundle/DataGrid/Extension/Selector/ORM/ReferenceDataSelector.php
| Behats             | ok
| Changelog updated  | no need
=> [TR] PIM-4783: Fix variant group product grid with reference data

features/Context/Page/Product/Edit.php
=> [TR] PIM-4802: fix mongo scenario

CHANGELOG-1.3.md, features/Context/FixturesContext.php, features/import/product/import_products_with_invalid_data.feature, src/Pim/Bundle/CatalogBundle/Resources/config/model/doctrine/Association.orm.yml
=> PIM-4810: Error message and import status to be modified

features/family/mass_edit_families.feature, src/Pim/Bundle/DataGridBundle/Extension/MassAction/Handler/EditMassActionHandler.php, src/Pim/Bundle/DataGridBundle/Extension/MassAction/MassActionDispatcher.php, src/Pim/Bundle/EnrichBundle/Resources/views/MassEditAction/choose.html.twig
| Migration script?  | no
| Behats             | unskiped one OK
| Changelog updated  | no
=> [TR] PIM-4796: Fix path to cancel mass actions

CHANGELOG-1.3.md, features/Context/FixturesContext.php, features/import/product/import_products_with_invalid_data.feature, src/Pim/Bundle/CatalogBundle/Resources/config/model/doctrine/Association.orm.yml
| Behats             | N/A
| Specs & Static     | N/A
=> Merge 1 3 into master

features/Context/FeatureContext.php, features/Context/NavigationContext.php, features/datagrid/products_category_backtothegrid.feature, src/Pim/Bundle/EnrichBundle/Resources/views/Product/index.html.twig
=> PIM-4538: Fixed sidebar issue on categorized grids

src/Pim/Bundle/EnrichBundle/Controller/FileController.php, src/Pim/Bundle/EnrichBundle/Resources/config/routing/media.yml
Give a route for displaying a default thumbnail by mime type
=> PIM-4499 : default thumbnail by mime type action

src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/status-switcher.js
=> [TR] PIM-4830: Update product state when updating status

features/Context/Page/Base/Form.php, features/Context/WebUser.php
https://akeneo.atlassian.net/browse/PIM-4826
| Specs & Static     | no regression
=> PIM-4826: Cannot filter by asset in the products grid

features/Context/Page/Product/Edit.php, features/Context/WebUser.php, src/Pim/Bundle/EnrichBundle/Resources/public/js/tree-view.jstree.js
https://akeneo.atlassian.net/browse/PIM-4603
| Behats             | no regression
| Specs & Static     | no regression
=> [TR][PAM] PIM-4603: Add the asset category tree in the product asset picker

spec/Pim/Bundle/AnalyticsBundle/DataCollector/VersionDataCollectorSpec.php, src/Pim/Bundle/AnalyticsBundle/DataCollector/VersionDataCollector.php, src/Pim/Bundle/AnalyticsBundle/Resources/config/data_collectors.yml
| Behats             | No diff
=> PIM-4345: add environment in analytics data collector

src/Pim/Bundle/EnrichBundle/Controller/MassEditActionController.php
| Behats             | Runned localy
=> PIM-4673: add convention for mass edit translations keys

src/Acme/Bundle/AppBundle/Resources/config/model/doctrine/ProductValue.orm.yml
=> PIM-4625: add missing indexes in acme product value

src/Pim/Bundle/UserBundle/Entity/UserInterface.php, src/Pim/Bundle/UserBundle/Resources/config/datagrid/user-relation.yml
=> PIM-4844 : fix role and group edit form access

features/Context/Page/Product/Edit.php, features/Context/WebUser.php, features/product/completeness.feature, features/product/validation/validate_number_attributes.feature, src/Pim/Bundle/EnrichBundle/Resources/config/requirejs.yml, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/attributes/attribute-group-selector.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/panel/completeness.js
=> [TR] Fix requirejs config events declaration

src/Pim/Bundle/EnrichBundle/Resources/public/js/jstree/jquery.jstree.nested_switch.js
| Migration script?  | n/a
| Behats             | no regression
| Specs & Static     | n/a
| Changelog updated  | n/a
=> [TR] PIM-4538: Category tree filter display is broken

features/Context/WebUser.php, features/acl/enforce_acl_on_history.feature, src/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/Repository/ProductCategoryRepository.php, src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/ProductCategoryRepository.php, src/Pim/Bundle/CatalogBundle/Manager/CategoryManager.php, src/Pim/Bundle/CatalogBundle/Resources/config/storage_driver/doctrine/mongodb-odm.yml, src/Pim/Bundle/CatalogBundle/Resources/config/storage_driver/doctrine/orm.yml, src/Pim/Bundle/ClassificationBundle/Doctrine/Mongo/Repository/AbstractItemCategoryRepository.php, src/Pim/Bundle/ClassificationBundle/Doctrine/ORM/Repository/AbstractItemCategoryRepository.php, src/Pim/Bundle/ClassificationBundle/Doctrine/ORM/Repository/ItemCategoryRepository.php, src/Pim/Bundle/ClassificationBundle/Resources/config/repositories.yml, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/categories.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/tree-associate.jstree.js, src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/tab/categories.html, src/Pim/Bundle/EnrichBundle/Resources/views/MassEditAction/configure/classify.html.twig, src/Pim/Bundle/EnrichBundle/Resources/views/Product/index.html.twig, src/Pim/Bundle/UserBundle/Entity/User.php, src/Pim/Bundle/UserBundle/Entity/UserInterface.php
| Behats             | missing
| Specs & Static     | missing
=> [TR][PAM] PIM-4071: Classify an asset

.php_cs.php, CHANGELOG-1.4.md, app/check.php, composer.json, src/Pim/Bundle/CatalogBundle/Version.php
| Behats             | not worst
=> PIM-4822: prepare beta3

src/Pim/Bundle/EnrichBundle/Resources/public/js/pim-init.js
https://akeneo.atlassian.net/browse/PIM-4547
| Migration script?  | n/a
| Specs & Static     | no regression
| Changelog updated  | n/a
=> [TR] PIM-4547: Save current tab when editing an asset

features/user/browse_users.feature, features/user/edit_user.feature
=> [TR] PIM-4736: unskip behat

src/Pim/Bundle/UIBundle/Resources/public/css/filterbox.less, src/Pim/Bundle/UIBundle/Resources/public/css/less/oro.less, src/Pim/Bundle/UIBundle/Resources/public/lib/select2/select2.css
=> PIM-4850: fix the height of grid filters

CHANGELOG-1.3.md, features/Context/NavigationContext.php, features/Context/Page/Category/Index.php, features/dashboard/display_links_widget.feature, spec/Pim/Bundle/DashboardBundle/Widget/LinksWidgetSpec.php, src/Pim/Bundle/DashboardBundle/Widget/LinksWidget.php
=> PIM-4845: Changed Manage families button link on the dashboard to target the list

CHANGELOG-1.3.md, features/Context/NavigationContext.php, features/Context/Page/Category/Index.php, features/dashboard/display_links_widget.feature, spec/Pim/Bundle/DashboardBundle/Widget/LinksWidgetSpec.php, src/Pim/Bundle/DashboardBundle/Widget/LinksWidget.php
| Behats             | N/A
| Specs & Static     | N/A
=> [TR] Merge 1 3 into master

composer.json
=> PIM-4859: fix batch dependencies

features/Context/Page/Category/Index.php, features/product/choose_and_order_products_grid_columns.feature, src/Akeneo/Bundle/ClassificationBundle/Doctrine/ORM/Repository/AbstractItemCategoryRepository.php
=> PIM-4861: remove useless group by to fix category filter

src/Pim/Bundle/EnrichBundle/Controller/FileController.php
=> [TR] PIM-4856: simplify filename of the downloaded file

CHANGELOG-1.3.md, features/Context/WebUser.php
=> PIM-4866: Added I should see the tab assertion method in behat

src/Pim/Bundle/CatalogBundle/DependencyInjection/PimCatalogExtension.php, src/Pim/Bundle/CatalogBundle/Resources/config/console.yml, src/Pim/Bundle/TranslationBundle/DependencyInjection/PimTranslationExtension.php, src/Pim/Bundle/TranslationBundle/Resources/config/twig.yml, src/Pim/Bundle/TranslationBundle/Resources/public/js/translator.js, src/Pim/Bundle/TranslationBundle/Twig/TranslationsExtension.php
| Behats             | OK
| Specs & Static     | OK
=> [TR] PIM-4675: Fix translation loading when no hash nav

spec/Pim/Bundle/TransformBundle/Normalizer/Flat/ProductNormalizerSpec.php, src/Akeneo/Component/Classification/CategoryAwareInterface.php, src/Akeneo/Component/Classification/TagAwareInterface.php, src/Pim/Bundle/CatalogBundle/Model/AbstractProduct.php, src/Pim/Bundle/CatalogBundle/Model/ProductInterface.php, src/Pim/Bundle/TransformBundle/Normalizer/Flat/ProductNormalizer.php, src/Pim/Bundle/TransformBundle/Normalizer/Structured/ProductNormalizer.php
http://core-ci.akeneo.com/job/pim-pr-behat/3335
=> PIM-4816: refactor methods

features/Context/AssertionContext.php, features/variant-group/add_attributes_to_a_variant_group.feature, spec/Pim/Bundle/CatalogBundle/Builder/ProductTemplateBuilderSpec.php, src/Pim/Bundle/CatalogBundle/Builder/ProductTemplateBuilder.php
| Behats             | blue
| Changelog updated  | no
=> [TR] PIM-4835: Fix prices display in variant group attribute tab

src/Pim/Bundle/EnrichBundle/Resources/views/Attribute/form_options.html.twig
```
| Bug fix?             | yes
| New feature?         |
| BC breaks?           |
| CI currently passes? |
| Tests pass?          |
| Scenarios pass?      |
| Checkstyle issues?*  |
| PMD issues?**        |
| Changelog updated?   |
```
=> Missing closing div tag

spec/Akeneo/Component/FileStorage/Formater/BytesFormaterSpec.php, src/Akeneo/Bundle/FileStorageBundle/DependencyInjection/AkeneoFileStorageExtension.php, src/Akeneo/Bundle/FileStorageBundle/Resources/config/formaters.yml, src/Akeneo/Component/FileStorage/Formater/BytesFormater.php
=> [TR] PIM-4816: add a formater to format bytes

src/Pim/Bundle/UIBundle/Resources/public/lib/backbone.bootstrap-modal.js
=> [TR] PIM-4816: add missing icons

features/rest/get-product.feature, src/Pim/Bundle/EnrichBundle/Resources/config/bundles/escape_wsse_authentication.yml, src/Pim/Bundle/UserBundle/Security/WsseUserProvider.php, src/Pim/Bundle/WebServiceBundle/Controller/Rest/ProductController.php, src/Pim/Bundle/WebServiceBundle/Resources/config/serializer/structured.yml
=> PIM-4656 : fix API authentication

src/Pim/Bundle/DashboardBundle/Resources/config/requirejs.yml, src/Pim/Bundle/DashboardBundle/Resources/public/js/completeness-widget.js, src/Pim/Bundle/DashboardBundle/Resources/public/js/last-operations-widget.js, src/Pim/Bundle/DashboardBundle/Resources/public/js/widget-container.js, src/Pim/Bundle/DashboardBundle/Resources/views/Widget/completeness.html.twig, src/Pim/Bundle/DashboardBundle/Resources/views/Widget/last_operations.html.twig
=> PIM-4873 : override last operations dashboard widget

features/product/validation/validate_number_attributes.feature
=> Remove useless EE permission on CE scenario

features/Context/AssertionContext.php, features/user/edit_my_account.feature, src/Pim/Bundle/EnrichBundle/Resources/config/bundles/liip_imagine.yml
=> PIM-4833 - Add default format for avatar_med

src/Pim/Bundle/PdfGeneratorBundle/Builder/DompdfBuilder.php, src/Pim/Bundle/PdfGeneratorBundle/Resources/views/Product/renderPdf.html.twig
@see #3288 
| Behats             |
=> PIM-4880 : fix media thumbnail generation for PDF download

features/Context/FixturesContext.php, features/product/edit_locale_specific_value.feature, features/product/ensure_completeness_display_for_locale_specific.feature, spec/Pim/Bundle/CatalogBundle/Manager/CompletenessManagerSpec.php, src/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/CompletenessGenerator.php, src/Pim/Bundle/CatalogBundle/Doctrine/ORM/CompletenessGenerator.php, src/Pim/Bundle/CatalogBundle/Manager/CompletenessManager.php, src/Pim/Bundle/CatalogBundle/Model/AbstractAttribute.php, src/Pim/Bundle/CatalogBundle/Model/AttributeInterface.php, src/Pim/Bundle/CatalogBundle/Model/ProductInterface.php, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/attributes.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/back-to-grid.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/download-pdf.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/meta/family.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/product-label.js
=> [TR] PIM-4771: fix completeness with local specific

spec/Pim/Bundle/EnrichBundle/File/FileTypeGuesserSpec.php, src/Pim/Bundle/EnrichBundle/File/FileTypeGuesser.php
| Behats             | OK
| Specs & Static     | updated OK
| Changelog updated  | no
=> [TR] PIM-4778: Refactor FileTypeGuesser to ease typesMapping addition

spec/Pim/Bundle/AnalyticsBundle/DataCollector/VersionDataCollectorSpec.php, src/Pim/Bundle/AnalyticsBundle/DataCollector/VersionDataCollector.php, src/Pim/Bundle/AnalyticsBundle/Resources/config/data_collectors.yml
=> PIM-4345: add the install time in the data collector

features/Context/Page/Product/Edit.php, features/Context/WebUser.php, features/notifications/display_notifications_when_mass_edit_jobs_are_finished.feature, features/product/validation/validate_number_attributes.feature
=> [TR] PIM-4764: We can't edit product status if we are not owner anymore

spec/Pim/Bundle/BaseConnectorBundle/Reader/File/YamlReaderSpec.php, spec/Pim/Component/Connector/Reader/Doctrine/BaseReaderSpec.php, src/Pim/Bundle/BaseConnectorBundle/Reader/File/YamlReader.php, src/Pim/Bundle/ConnectorBundle/Resources/config/readers.yml, src/Pim/Bundle/ConnectorBundle/Resources/config/writers.yml, src/Pim/Component/Connector/Reader/Doctrine/BaseReader.php, src/Pim/Component/Connector/Writer/File/YamlWriter.php
| Migration script?  | n 
http://core-ci.akeneo.com/job/pim-pr-behat/3366
=> [TR] PIM-4878: add Yaml wirter

spec/Akeneo/Bundle/StorageUtilsBundle/Doctrine/Common/Saver/BaseSaverSpec.php, spec/Pim/Bundle/CatalogBundle/Doctrine/Common/Saver/AttributeSaverSpec.php, spec/Pim/Bundle/CatalogBundle/Doctrine/Common/Saver/ChannelSaverSpec.php, spec/Pim/Bundle/CatalogBundle/Doctrine/Common/Saver/FamilySaverSpec.php, spec/Pim/Bundle/CatalogBundle/Doctrine/Common/Saver/GroupSaverSpec.php, spec/Pim/Bundle/CatalogBundle/Doctrine/Common/Saver/ProductSaverSpec.php, spec/Pim/Bundle/CatalogBundle/EventSubscriber/MongoDBODM/RemoveOutdatedProductsFromAssociationsSubscriberSpec.php, spec/Pim/Bundle/CatalogBundle/EventSubscriber/ProductCategorySubscriberSpec.php, spec/Pim/Bundle/CatalogBundle/EventSubscriber/ProductTemplateAttributeSubscriberSpec.php, spec/Pim/Bundle/VersioningBundle/EventSubscriber/AddRemoveVersionSubscriberSpec.php, src/Akeneo/Bundle/StorageUtilsBundle/Doctrine/Common/Remover/BaseRemover.php, src/Akeneo/Bundle/StorageUtilsBundle/Doctrine/Common/Saver/BaseSaver.php, src/Akeneo/Component/StorageUtils/StorageEvents.php, src/Pim/Bundle/CatalogBundle/Doctrine/Common/Saver/AttributeSaver.php, src/Pim/Bundle/CatalogBundle/Doctrine/Common/Saver/ChannelSaver.php, src/Pim/Bundle/CatalogBundle/Doctrine/Common/Saver/FamilySaver.php, src/Pim/Bundle/CatalogBundle/Doctrine/Common/Saver/GroupSaver.php, src/Pim/Bundle/CatalogBundle/Doctrine/Common/Saver/ProductSaver.php, src/Pim/Bundle/CatalogBundle/EventSubscriber/Category/CheckChannelsOnDeletionSubscriber.php, src/Pim/Bundle/CatalogBundle/EventSubscriber/CurrencyDisablingSubscriber.php, src/Pim/Bundle/CatalogBundle/EventSubscriber/MongoDBODM/RemoveOutdatedProductsFromAssociationsSubscriber.php, src/Pim/Bundle/CatalogBundle/EventSubscriber/ProductCategorySubscriber.php, src/Pim/Bundle/CatalogBundle/EventSubscriber/ProductTemplateAttributeSubscriber.php, src/Pim/Bundle/VersioningBundle/EventSubscriber/AddRemoveVersionSubscriber.php
| Behats             | Running
=> PIM-4732: Move StorageEvents

composer.json
=> PIM-4886 : change oro platform version

features/user/edit_user_group_and_role_assignations.feature
| Specs & Static     | N/A
These behat scenarios ensure that the feature work as it was not covered and actually fails on enterprise edition.
=> PIM-4892: No way to assign a user when edit a role

features/product/save_product_when_channel_has_been_removed.feature, spec/Pim/Bundle/EnrichBundle/Filter/ProductEditDataFilterSpec.php, src/Pim/Bundle/EnrichBundle/Filter/ProductEditDataFilter.php, src/Pim/Bundle/EnrichBundle/Resources/config/filters.yml
=> [TR] PIM-4902: Fix bug with channel removal and product save

CHANGELOG-1.4.md, features/reference-data/variant-group/import_with_reference_data_axis.feature, spec/Pim/Bundle/CatalogBundle/Builder/ProductBuilderSpec.php, spec/Pim/Bundle/CatalogBundle/Validator/Constraints/UniqueVariantAxisValidatorSpec.php, spec/Pim/Bundle/TransformBundle/Denormalizer/Structured/ProductValueDenormalizerSpec.php, spec/Pim/Component/Catalog/Comparator/Field/ArrayComparatorSpec.php, src/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/Repository/ProductRepository.php, src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/ProductRepository.php, src/Pim/Bundle/CatalogBundle/Model/AbstractAttribute.php, src/Pim/Bundle/CatalogBundle/Model/AbstractProductValue.php, src/Pim/Bundle/CatalogBundle/Model/AttributeInterface.php, src/Pim/Bundle/CatalogBundle/Validator/Constraints/UniqueVariantAxisValidator.php, src/Pim/Component/Catalog/Comparator/Field/ArrayComparator.php
=> PIM-4882: Cannot import products into a variant group if an axis is a reference data

src/Pim/Bundle/CatalogBundle/Manager/LocaleManager.php
=> PIM-4891 : check by code if a locale is activated

spec/Pim/Bundle/DataGridBundle/Adapter/OroToPimGridFilterAdapterSpec.php, src/Pim/Bundle/DataGridBundle/Adapter/OroToPimGridFilterAdapter.php
=> [TR] PIM-4878: Add a method to retreive object ids with oro grid filters

CHANGELOG-1.4.md, composer.json
=> [TR] PIM-4886: fix the pinbar

CHANGELOG-1.4.md, spec/Pim/Bundle/PdfGeneratorBundle/Renderer/ProductPdfRendererSpec.php, src/Pim/Bundle/PdfGeneratorBundle/Renderer/ProductPdfRenderer.php, src/Pim/Bundle/PdfGeneratorBundle/Resources/config/renderers.yml, src/Pim/Bundle/PdfGeneratorBundle/Resources/views/Product/renderPdf.html.twig
=> PIM-4880 : use generated thumbnail cache for product PDF

CHANGELOG-1.4.md, features/Context/FeatureContext.php, features/Context/FixturesContext.php, features/locale/detach_locale_from_channel.feature, spec/Pim/Bundle/EnrichBundle/EventListener/Storage/ChannelLocaleSubscriberSpec.php, src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/LocaleRepository.php, src/Pim/Bundle/CatalogBundle/Entity/Locale.php, src/Pim/Bundle/CatalogBundle/Model/LocaleInterface.php, src/Pim/Bundle/EnrichBundle/AbstractController/AbstractDoctrineController.php, src/Pim/Bundle/EnrichBundle/Controller/ChannelController.php, src/Pim/Bundle/EnrichBundle/EventListener/Storage/ChannelLocaleSubscriber.php, src/Pim/Bundle/EnrichBundle/Resources/config/event_listeners.yml
=> PIM-4887: Locales are not really disabled when removed from a channel

src/Pim/Bundle/EnrichBundle/Resources/public/js/product/field/field.js
=> PIM-4896: remove alert in js

composer.json, spec/Pim/Bundle/UserBundle/EventListener/LocalSubscriberSpec.php, src/Pim/Bundle/UserBundle/EventListener/LocalSubscriber.php, src/Pim/Bundle/UserBundle/EventListener/LocaleListener.php, src/Pim/Bundle/UserBundle/Resources/config/event_subscribers.yml
=> PIM-4869: Locale configuration is not taken into account when installed parameters is not set

CHANGELOG-1.4.md, src/Pim/Bundle/EnrichBundle/Controller/MassEditActionController.php, src/Pim/Bundle/EnrichBundle/Resources/config/controllers.yml
=> [TR] PIM-4895: Fix redirect after mass edit unpublished products

features/Context/DataGridContext.php, features/Context/Page/Base/Grid.php
=> [TR] PIM-4874: add the possibility to unselect any row of a datagrid

src/Pim/Bundle/DataGridBundle/Controller/ProductExportController.php, src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid/widget/export-widget.js, src/Pim/Bundle/ImportExportBundle/Entity/Repository/JobInstanceRepository.php
=> [TR] PIM-4760 : error if quick export not configured

CHANGELOG-1.4.md, src/Pim/Bundle/AnalyticsBundle/Resources/views/Update/last_patch.html.twig
=> [TR] PIM-4925 : patch available information

CHANGELOG-1.4.md, src/Pim/Bundle/VersioningBundle/EventSubscriber/AddVersionSubscriber.php
| Migration script?  | N.A.
| Behats             | Running
| Specs & Static     | OK
| Changelog updated  | OK
=> TR PIM 4936 - Fixes on import performances and memory leak

CONTRIBUTING.md
There is a proposal for a new contributing.md, we only discussed about story this morning so I splitted expectations about story and bug fix (we can merge in a single table if you want but it has some impacts on support and maintenance workflow).
=> Enhance contributing doc to take DOD in account

CHANGELOG-1.4.md, CONTRIBUTING.md, src/Pim/Bundle/AnalyticsBundle/Resources/views/Update/last_patch.html.twig, src/Pim/Bundle/VersioningBundle/EventSubscriber/AddVersionSubscriber.php
=> Get 1.4 patches to master

src/Pim/Component/Connector/Processor/Denormalization/AttributeProcessor.php
=> [TR] Fixed typo

features/category/edit_a_category.feature, features/export/export_variant_groups.feature, features/job-tracker/display_jobs_execution_in_job_tracker.feature, features/mass-action/mass_edit_variant_group_products.feature, features/product/comments.feature, features/reference-data/product/add_attributes_to_a_product.feature, features/user/create_and_delete_user.feature, features/user/create_edit_and_delete_group.feature, features/user/create_edit_and_delete_role.feature, features/user/update_user_preferences.feature, features/versioning/ensure_versioning_on_channel.feature
It's a huge change, I know. :)
=> Remove duplicated @javascript tags

CHANGELOG-1.4.md, features/Context/FixturesContext.php, features/Context/WebUser.php, features/Context/catalog/footwear/jobs.yml, features/mass-action/quick_export.feature, spec/Pim/Bundle/ConnectorBundle/Writer/File/ContextableCsvWriterSpec.php, src/Pim/Bundle/BaseConnectorBundle/Resources/config/writers.yml, src/Pim/Bundle/BaseConnectorBundle/Writer/File/CsvProductWriter.php, src/Pim/Bundle/BaseConnectorBundle/Writer/File/FileWriter.php, src/Pim/Bundle/ConnectorBundle/Writer/File/ContextableCsvWriter.php, src/Pim/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev/jobs.yml, src/Pim/Bundle/InstallerBundle/Resources/fixtures/minimal/jobs.yml
=> [TR] PIM-4914: Fixed Quick export file name

features/Context/Page/Base/Grid.php
| Migration script?  | n/a
| Specs & Static     | no regression
| Changelog updated  | n/a
=> [TR] PIM-4794: Display relevant thumbnails of assets (for products grid)

CHANGELOG-1.4.md, features/Context/NavigationContext.php, features/navigation/pin_pages.feature, src/Pim/Bundle/EnrichBundle/Resources/views/Product/edit.html.twig, src/Pim/Bundle/NavigationBundle/Resources/public/js/navigation.js
https://akeneo.atlassian.net/browse/PIM-4458
| Added Specs       | n/a
| Added Behats      | ok
| Travis CI is ok   | yes
=> [TR] PIM-4458: Fix name display in pinbar for product edit pages

CHANGELOG-1.4.md, features/Context/FixturesContext.php, features/import/product/import_products.feature, src/Pim/Component/Connector/Reader/File/CsvReader.php
=> [TR] PIM-4939: Fix Carriage returns randomly skipped in the import

CHANGELOG-1.4.md, spec/Pim/Bundle/CatalogBundle/Doctrine/Common/Saver/ChannelSaverSpec.php, spec/Pim/Bundle/EnrichBundle/EventListener/Storage/ChannelLocaleSubscriberSpec.php, src/Pim/Bundle/CatalogBundle/Doctrine/Common/Saver/ChannelSaver.php, src/Pim/Bundle/CatalogBundle/Manager/CompletenessManager.php, src/Pim/Bundle/EnrichBundle/EventListener/Storage/ChannelLocaleSubscriber.php, src/Pim/Bundle/EnrichBundle/Resources/config/event_listeners.yml
| Behats            | Y 
| Changelog updated | Y 
=> PIM-4955: Fixed regression on completeness computation when locales are removed from a channel

CHANGELOG-1.4.md, src/Pim/Bundle/CommentBundle/Resources/public/css/comment.less
| Added Specs       | n
| Added Behats      | n
| Travis CI is ok   | n
=> PIM-4622: CSS product comments

features/Context/AssertionContext.php
=> PIM-3625: Added click on notification feature context

CHANGELOG-1.4.md, features/Context/DataGridContext.php, features/Context/Page/Base/Grid.php, features/product/remove_product.feature, src/Pim/Bundle/CatalogBundle/Resources/config/removers.yml
https://akeneo.atlassian.net/browse/PIM-4973
| Specs             | n/a
| Blue CI           | ok
| Review and 2 GTM  | ok
=> [TR] PIM-4973: Fix product removal from PEF (in mongo)

features/Context/NavigationContext.php, spec/Pim/Bundle/UserBundle/Entity/Repository/UserRepositorySpec.php, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/form-tabs.js, src/Pim/Bundle/UserBundle/Entity/Repository/UserRepository.php, src/Pim/Bundle/UserBundle/Entity/Repository/UserRepositoryInterface.php
| Specs             | :white_check_mark: 
| Behats            | :white_check_mark:
| Blue CI           | :white_check_mark:
| Changelog updated | Not needed
| Review and 2 GTM  | :white_check_mark:
| Micro Demo (PO)   | Not needed
| Migration script  | Not needed
| Tech Doc          | Not needed
=> [TR] PIM-3511: Add findByGroups on UserRepo

features/Context/AssertionContext.php, src/Pim/Bundle/NotificationBundle/Resources/public/js/notification-list.js
=> [TR] Add a new available icon for notif

src/Pim/Bundle/NotificationBundle/Resources/public/js/notification-list.js, src/Pim/Bundle/NotificationBundle/Resources/public/templates/notification/notification-list.html, src/Pim/Bundle/NotificationBundle/Resources/views/Notification/list.json.twig
=> [TR] PIM-3511: Be able to hide report button on notifications

CHANGELOG-1.5.md, features/Context/AssertionContext.php, spec/Pim/Bundle/NotificationBundle/Factory/NotificationFactorySpec.php, src/Pim/Bundle/NotificationBundle/Entity/Notification.php, src/Pim/Bundle/NotificationBundle/Factory/NotificationFactory.php, src/Pim/Bundle/NotificationBundle/Manager/NotificationManager.php, src/Pim/Bundle/NotificationBundle/Resources/config/doctrine/Notification.orm.yml, src/Pim/Bundle/NotificationBundle/Resources/config/form_extensions/comment.yml, src/Pim/Bundle/NotificationBundle/Resources/config/requirejs.yml, src/Pim/Bundle/NotificationBundle/Resources/public/js/form/comment.js, src/Pim/Bundle/NotificationBundle/Resources/public/js/notification-list.js, src/Pim/Bundle/NotificationBundle/Resources/public/templates/comment/comment.html, src/Pim/Bundle/NotificationBundle/Resources/public/templates/notification/notification-list.html, src/Pim/Bundle/NotificationBundle/Resources/views/Notification/list.json.twig, src/Pim/Bundle/UIBundle/Resources/public/css/notifications.less, upgrades/schema/Version20151006132723.php
| Behats            |  ok
| Blue CI           | ok
| Migration script  | Done
=> [TR] PIM-2736 bis: Add comment in Notifications

CHANGELOG-1.4.md, composer.json, features/Context/NavigationContext.php, features/Context/Page/User/Profile.php, features/Context/WebUser.php, features/user/edit_my_account.feature
| Specs             |n
| Behats            |y
| Blue CI           |y
| Changelog updated |y
| Review and 2 GTM  |2
| Micro Demo (PO)   |n
| Migration script  |n
| Tech Doc          |n
=> [TR] PIM-5006 : behat to test API key generation

CHANGELOG-1.4.md, features/import/product/import_products.feature, features/import/product/import_products_with_invalid_data.feature, spec/Pim/Component/Connector/Processor/Denormalization/ProductProcessorSpec.php, src/Pim/Component/Connector/Processor/Denormalization/ProductProcessor.php
=> PIM-5016: fix product import with only sku and family columns

src/Pim/Bundle/EnrichBundle/Resources/config/requirejs.yml, src/Pim/Bundle/EnrichBundle/Resources/public/js/form/form-modal.js, src/Pim/Bundle/UIBundle/Resources/public/css/notifications.less
=> [TR] PIM-2735: Introduce the modal-form component

features/Context/NavigationContext.php, features/Context/Page/User/Profile/Show.php, features/Context/Page/User/Show.php, features/user/show_user.feature, src/Pim/Bundle/UserBundle/Resources/views/User/view.html.twig
| Blue CI           | n
| Micro Demo (PO)   | n
=> PIM-4942: Display user locale

src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid-builder.js
=> [TR] PIM-2735: Allow to register custom mass edit JS actions

features/localization/import/import_product_with_decimal.feature, spec/Pim/Component/Connector/ArrayConverter/Flat/Product/FieldSplitterSpec.php, src/Pim/Component/Connector/ArrayConverter/Flat/Product/FieldSplitter.php
| Specs             | :white_check_mark: 
| Blue CI           | :white_check_mark: 
| Review and 2 GTM  | :white_check_mark:
=> PIM-3305: fix split prices

CHANGELOG-1.5.md, spec/Pim/Component/Catalog/Updater/Adder/AdderRegistrySpec.php, spec/Pim/Component/Catalog/Updater/Copier/CopierRegistrySpec.php, spec/Pim/Component/Catalog/Updater/ProductPropertyAdderSpec.php, spec/Pim/Component/Catalog/Updater/ProductPropertyCopierSpec.php, spec/Pim/Component/Catalog/Updater/ProductPropertyRemoverSpec.php, spec/Pim/Component/Catalog/Updater/ProductPropertySetterSpec.php, spec/Pim/Component/Catalog/Updater/Remover/RemoverRegistrySpec.php, spec/Pim/Component/Catalog/Updater/Setter/SetterRegistrySpec.php, src/Akeneo/Bundle/ClassificationBundle/Doctrine/ORM/Repository/CategoryRepository.php, src/Akeneo/Component/Classification/Repository/CategoryRepositoryInterface.php, src/Pim/Bundle/CatalogBundle/Resources/config/updaters.yml, src/Pim/Component/Catalog/Updater/Adder/AdderRegistry.php, src/Pim/Component/Catalog/Updater/Adder/AdderRegistryInterface.php, src/Pim/Component/Catalog/Updater/Copier/CopierRegistry.php, src/Pim/Component/Catalog/Updater/Copier/CopierRegistryInterface.php, src/Pim/Component/Catalog/Updater/ProductPropertyAdder.php, src/Pim/Component/Catalog/Updater/ProductPropertyCopier.php, src/Pim/Component/Catalog/Updater/ProductPropertyRemover.php, src/Pim/Component/Catalog/Updater/ProductPropertySetter.php, src/Pim/Component/Catalog/Updater/Remover/RemoverRegistry.php, src/Pim/Component/Catalog/Updater/Remover/RemoverRegistryInterface.php, src/Pim/Component/Catalog/Updater/Setter/SetterRegistry.php, src/Pim/Component/Catalog/Updater/Setter/SetterRegistryInterface.php
=> PIM-4945: rework the property adder

app/config/config.yml, features/import/edit_an_import.feature, features/localization/import/import_product_with_date.feature, features/localization/import/import_product_with_decimal.feature, spec/Pim/Component/Connector/Processor/Denormalization/ProductProcessorSpec.php, spec/Pim/Component/Connector/Reader/File/CsvProductReaderSpec.php, spec/Pim/Component/Localization/Localizer/DateLocalizerSpec.php, spec/Pim/Component/Localization/Localizer/LocalizedAttributeConverterSpec.php, spec/Pim/Component/Localization/Localizer/MetricLocalizerSpec.php, spec/Pim/Component/Localization/Localizer/NumberLocalizerSpec.php, spec/Pim/Component/Localization/Localizer/PriceLocalizerSpec.php, src/Pim/Bundle/ConnectorBundle/Resources/config/readers.yml, src/Pim/Bundle/ConnectorBundle/Resources/config/validation/csvProductReader.yml, src/Pim/Bundle/ConnectorBundle/Resources/translations/messages.en.yml, src/Pim/Bundle/InstallerBundle/Resources/config/fixtures_jobs.yml, src/Pim/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev/jobs.yml, src/Pim/Bundle/LocalizationBundle/DependencyInjection/Configuration.php, src/Pim/Bundle/LocalizationBundle/DependencyInjection/PimLocalizationExtension.php, src/Pim/Bundle/LocalizationBundle/Resources/config/localizers.yml, src/Pim/Component/Connector/Processor/Denormalization/ProductProcessor.php, src/Pim/Component/Connector/Reader/File/CsvProductReader.php, src/Pim/Component/Localization/Exception/FormatLocalizerException.php, src/Pim/Component/Localization/Localizer/AbstractNumberLocalizer.php, src/Pim/Component/Localization/Localizer/DateLocalizer.php, src/Pim/Component/Localization/Localizer/LocalizedAttributeConverter.php, src/Pim/Component/Localization/Localizer/LocalizerInterface.php, src/Pim/Component/Localization/Localizer/MetricLocalizer.php, src/Pim/Component/Localization/Localizer/NumberLocalizer.php, src/Pim/Component/Localization/Localizer/PriceLocalizer.php
| Specs             | :white_check_mark: 
| Changelog updated | NO
| Micro Demo (PO)   | :white_check_mark: 
| Migration script  | NO
| Tech Doc          | :white_check_mark:
=> PIM-3071: Format the dates for the imports

src/Pim/Bundle/InstallerBundle/Resources/config/fixtures_jobs.yml, src/Pim/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev/jobs.yml
| Blue CI           | -
| Changelog updated | -
=> PIM-3071: fix product import invalid date

CHANGELOG-1.3.md, app/config/config_prod.yml
| Specs             |no additional test
| Behats            |no additional test
| Blue CI           |running
| Review and 2 GTM  |ok
=> PIM-5028 : fix log level configuration

features/Context/Page/Base/Base.php
=> [TR] PIM-2735: Add a simple fill field method to bypass PEF override method

CHANGELOG-1.3.md, src/Pim/Bundle/CatalogBundle/Resources/config/model/doctrine/Association.orm.yml
| Specs             |no new specs
| Behats            |no new behat
=> [TR] PIM-5037 : Do not cascade detach product associated entities

src/Pim/Bundle/EnrichBundle/Resources/public/js/form/form-modal.js, src/Pim/Bundle/NotificationBundle/Resources/config/validation/notification.yml, src/Pim/Bundle/UIBundle/Resources/public/css/notifications.less
| Specs             | no
| Behats            | no
| Blue CI           | Blue
| Changelog updated | no
| Micro Demo (PO)   |
| Migration script  |
=> [TR] PIM-5009: Add character counter in comment modal

CHANGELOG-1.4.md, features/product/associate_product.feature, spec/Pim/Bundle/DataGridBundle/Datasource/ResultRecord/MongoDbOdm/AssociatedProductHydratorSpec.php, src/Pim/Bundle/DataGridBundle/Datasource/ResultRecord/MongoDbOdm/AssociatedProductHydrator.php, src/Pim/Bundle/DataGridBundle/Datasource/ResultRecord/MongoDbOdm/ProductHydrator.php, src/Pim/Bundle/EnrichBundle/Controller/Rest/ProductController.php
https://akeneo.atlassian.net/browse/PIM-5035
| Behats            | ok
| Blue CI           | ok
| Changelog updated | ok
| Review and 2 GTM  | ok
=> [TR] PIM-5035: Fix products sorting in PEF associations grid

CHANGELOG-1.4.md, src/Pim/Bundle/CatalogBundle/Factory/AttributeFactory.php
| Specs             |no new spec
| Behats            |no new feature
| Blue CI           |runnin
| Review and 2 GTM  |yes
=> PIM-5046 : Fix identifier attribute not unique on creation

features/deprecated-behat/import/delete_an_import.feature, features/export/export_families.feature, src/Pim/Bundle/TransformBundle/Normalizer/Structured/FamilyNormalizer.php
| Review and 2 GTM  | Yes
| Micro Demo (PO)   | Yes
=> PIM-4683: Change column order

src/Pim/Bundle/TranslationBundle/Resources/public/js/translator.js
=> [TR] Fallback on empty translations for Jasmine specs

src/Pim/Bundle/BaseConnectorBundle/Processor/Normalization/FamilyProcessor.php
=> PIM-5053: Fix missing conf for exports

CHANGELOG-1.4.md, spec/Pim/Bundle/VersioningBundle/EventSubscriber/AddRemoveVersionSubscriberSpec.php, src/Pim/Bundle/VersioningBundle/EventSubscriber/AddRemoveVersionSubscriber.php
| Specs             |updated
| Behats            |no new feature
| Blue CI           |running
| Review and 2 GTM  |OK
=> PIM-5051 : Bulk remove throw an exception on versionning

CONTRIBUTING.md
Update the contribution instructions to the last version
=> Update contributing documentation for 1.3 branch

features/Context/Page/Category/Edit.php, features/Context/Page/Category/Node/Creation.php, features/Context/Page/Category/Tree/Creation.php, features/Context/Page/Category/Tree/Index.php, features/association-type/edit_association_type.feature, features/attribute-group/edit_attribute_group.feature, features/attribute/edit_identifier_attribute.feature, features/category/edit_a_category.feature, features/channel/edit_channel.feature, features/family/save_family_tab.feature, features/product-group/edit_product_group.feature, features/variant-group/edit_variant_group.feature, src/Pim/Bundle/EnrichBundle/Resources/public/js/controller/form.js, src/Pim/Bundle/UIBundle/Resources/public/js/pim-saveformstate.js
| Added Specs       | n
| Added Behats      | y
| Travis CI is ok   | y
=> PMI-4984: selected tab on edit forms are not maintained after save

CHANGELOG-1.3.md, spec/Pim/Bundle/TransformBundle/Converter/MetricConverterSpec.php, src/Pim/Bundle/TransformBundle/Converter/MetricConverter.php
| Specs             |yes
| Behats            |will be added in another PR
| Review and 2 GTM  |1
=> PIM-5062 : do not convert NULL metric data

src/Pim/Component/Connector/Processor/Denormalization/AbstractProcessor.php
=> PIM-5080: Fix abstract processor

CHANGELOG-1.4.md, src/Pim/Bundle/AnalyticsBundle/Resources/views/Update/last_patch.html.twig
| Specs             |no
| Behats            |no
| Blue CI           |runnin
=> [TR] PIM-4925 : Fix patch available information

CHANGELOG-1.3.md, features/import/product_variant_group/import_variant_group_with_template_values.feature, spec/Pim/Bundle/BaseConnectorBundle/Processor/Denormalization/VariantGroupProcessorSpec.php, src/Pim/Bundle/BaseConnectorBundle/Processor/Denormalization/VariantGroupProcessor.php, src/Pim/Bundle/BaseConnectorBundle/Writer/Doctrine/VariantGroupWriter.php
| Specs             |modified
| Behats            |added
| Review and 2 GTM  |yes
=> [TR] PIM-5054 : merge variant group imported template values

features/Context/Page/Base/Base.php, features/Context/Page/Base/Grid.php, features/Context/WebUser.php, spec/Pim/Bundle/EnrichBundle/Twig/AttributeGrantedExtensionSpec.php, spec/Pim/Bundle/LocalizationBundle/Twig/LocaleExtensionSpec.php, src/Pim/Bundle/EnrichBundle/Resources/config/twig.yml, src/Pim/Bundle/EnrichBundle/Twig/AttributeGrantedExtension.php, src/Pim/Bundle/LocalizationBundle/DependencyInjection/PimLocalizationExtension.php, src/Pim/Bundle/LocalizationBundle/Resources/config/twig.yml, src/Pim/Bundle/LocalizationBundle/Twig/LocaleExtension.php, src/Pim/Bundle/NotificationBundle/Resources/public/templates/notification/notification-list.html, src/Pim/Bundle/UIBundle/Resources/public/css/notifications.less
=> PIM-4354: Add a twig extension to know if attribute is granted with its code

src/Oro/Bundle/UserBundle/Controller/UserController.php, src/Pim/Bundle/UserBundle/Resources/views/User/update.html.twig, src/Pim/Bundle/UserBundle/Resources/views/User/view.html.twig
Fix flash messages on user update
=> [TR] PIM-4985: fix user update

CHANGELOG-1.4.md, features/Context/WebUser.php, features/product/products_in_group_overview.feature, src/Pim/Bundle/EnrichBundle/Controller/Rest/GroupController.php, src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/meta/group-modal.html
=> [TR] PIM-5082: Fix variant group modal display on PEF

features/Context/NavigationContext.php
cf https://github.com/akeneo/pim-community-dev/pull/3473
=> PIM-5071: fix forgotten timeout spin

CHANGELOG-1.4.md, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/attributes/attribute-group-selector.js
| Added Specs       | NA
| Added Behats      | NA
=> PIM-5084: fix attribute group sort order

features/Context/AssertionContext.php
=> [TR] PIM-4349: Allow to look for 0 notification

features/export/export_families.feature, src/Pim/Component/Connector/ArrayConverter/Flat/FamilyStandardConverter.php
| Micro Demo (PO)   | No
http://core-ci.akeneo.com/job/pim-pr-behat/3618
=> [TR] PIM-4683: fix family export

src/Pim/Component/Catalog/Updater/Copier/AbstractAttributeCopier.php
=> Fix small issues in the code

features/import/import_families.feature, src/Pim/Component/Connector/ArrayConverter/Flat/FamilyStandardConverter.php
| Review and 2 GTM  | Yes
http://core-ci.akeneo.com/job/pim-pr-behat/3618/
=> PIM-4683: fix family import

CHANGELOG-1.4.md, src/Pim/Bundle/EnrichBundle/Resources/public/js/fetcher/base-fetcher.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/fetcher/fetcher-registry.js, src/Pim/Bundle/UIBundle/Resources/views/Default/index.html.twig
| Blue CI           | n/a
| Review and 2 GTM  |2
=> [TR] PIM-5041: Fix PEF first load

CHANGELOG-1.5.md, spec/Pim/Bundle/CatalogBundle/Factory/FamilyFactorySpec.php, src/Pim/Bundle/CatalogBundle/Factory/FamilyFactory.php, src/Pim/Bundle/CatalogBundle/Resources/config/factories.yml, src/Pim/Bundle/EnrichBundle/Controller/FamilyController.php, src/Pim/Bundle/EnrichBundle/Resources/config/controllers.yml
=> Remove hardcoded family

CHANGELOG-1.4.md, features/product/edit_product.feature, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/field/metric-field.js
=> [TR] PIM-5040: Cannot change the unit of a metric

.travis.yml, CHANGELOG-1.4.md, src/Pim/Bundle/DataGridBundle/Resources/public/js/multiselect-decorator.js, src/Pim/Bundle/DataGridBundle/Resources/public/spec/MultiSelectDecoratorSpec.js, src/Pim/Bundle/TranslationBundle/Resources/public/js/translator.js
=> PIM-5119: Manage filters very slow when a lot of attributes to display

features/Context/Page/JobTracker/Index.php, features/Context/Page/User/Index.php, features/Context/Page/UserGroup/Index.php, features/Context/Page/UserRole/Index.php, features/user/create_edit_and_delete_group.feature, features/user/update_user_preferences.feature, src/Pim/Bundle/UserBundle/DependencyInjection/PimUserExtension.php, src/Pim/Bundle/UserBundle/Resources/config/view_elements/group.yml, src/Pim/Bundle/UserBundle/Resources/translations/messages.en.yml, src/Pim/Bundle/UserBundle/Resources/views/Group/Tab/general.html.twig, src/Pim/Bundle/UserBundle/Resources/views/Group/Tab/users.html.twig, src/Pim/Bundle/UserBundle/Resources/views/Group/index.html.twig, src/Pim/Bundle/UserBundle/Resources/views/Group/update.html.twig, src/Pim/Bundle/UserBundle/Resources/views/Role/index.html.twig, src/Pim/Bundle/UserBundle/Resources/views/Role/update.html.twig
| Changelog updated | n/a
| Review and 2 GTM  | 
Main change here is the rework of the old Oro user groups form to be more compatible with the new navigation.
About 10 scenarios fixed.
=> [TR] PIM-5137: Fix users management behats

CHANGELOG-1.5.md, spec/Oro/Bundle/FilterBundle/Filter/ChoiceFilterSpec.php, src/Oro/Bundle/FilterBundle/Filter/ChoiceFilter.php, src/Oro/Bundle/FilterBundle/Resources/views/Filter/layout.js.twig, src/Pim/Bundle/DataGridBundle/Resources/public/css/filter.less, src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filter/multiselect-filter.js
=> PIM-4743: Added the possibility to use optgroup in choice filters

CHANGELOG-1.4.md, features/product/edit_product.feature, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/attributes.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/attributes/copy.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/scope-switcher.js, src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/field/field.html, src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/scope-switcher.html, src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/tab/attributes/copy-field.html
=> PIM-5121: code displayed instead of label

CHANGELOG-1.4.md, spec/Pim/Bundle/DataGridBundle/Datasource/ResultRecord/MongoDbOdm/AssociatedProductHydratorSpec.php, src/Pim/Bundle/DataGridBundle/Datasource/ResultRecord/MongoDbOdm/AssociatedProductHydrator.php
Time to load the association grid with customer's data (env prod, local machine):
- before: 12s
- now: <1s
| Changelog updated |  Y
| Review and 2 GTM  | -
=> [TR] PIM-5139: fix grid association performance and sorting issues

composer.json
| Changelog updated | in batch bundle changlog
=> [TR] PIM-5120: bump BatchBundle

CHANGELOG-1.4.md, src/Pim/Bundle/UIBundle/Resources/public/css/pim.less
EE 1.4 ref env has been modified to test the behavior on IE11
| Blue CI           | -
=> [TR] PIM-5148: IE11 wrong display on multiple select attributes

CHANGELOG-1.5.md, features/Context/Page/Base/Form.php, features/Context/Page/Base/Grid.php, features/datagrid/datagrid_views.feature, spec/Pim/Bundle/DataGridBundle/DataTransformer/DefaultViewDataTransformerSpec.php, src/Pim/Bundle/DataGridBundle/DataTransformer/DefaultViewDataTransformer.php, src/Pim/Bundle/DataGridBundle/Datagrid/Configuration/Product/ContextConfigurator.php, src/Pim/Bundle/DataGridBundle/DependencyInjection/PimDataGridExtension.php, src/Pim/Bundle/DataGridBundle/EventSubscriber/DefaultViewSubscriber.php, src/Pim/Bundle/DataGridBundle/Repository/DatagridViewRepository.php, src/Pim/Bundle/DataGridBundle/Repository/DatagridViewRepositoryInterface.php, src/Pim/Bundle/DataGridBundle/Resources/config/configurators.yml, src/Pim/Bundle/DataGridBundle/Resources/config/doctrine/DatagridView.orm.yml, src/Pim/Bundle/DataGridBundle/Resources/config/repositories.yml, src/Pim/Bundle/DataGridBundle/Resources/config/subscribers.yml, src/Pim/Bundle/DataGridBundle/Resources/translations/messages.en.yml, src/Pim/Bundle/DataGridBundle/Resources/views/Datagrid/_views.html.twig, src/Pim/Bundle/DataGridBundle/Resources/views/macros.html.twig, src/Pim/Bundle/EnrichBundle/Resources/views/Product/index.html.twig, src/Pim/Bundle/UserBundle/Entity/User.php, src/Pim/Bundle/UserBundle/Entity/UserInterface.php, src/Pim/Bundle/UserBundle/Event/UserFormBuilderEvent.php, src/Pim/Bundle/UserBundle/Form/Subscriber/UserPreferencesSubscriber.php, src/Pim/Bundle/UserBundle/Form/Type/UserType.php, src/Pim/Bundle/UserBundle/Resources/config/doctrine/User.orm.yml, src/Pim/Bundle/UserBundle/Resources/config/form_types.yml, src/Pim/Bundle/UserBundle/Resources/translations/messages.en.yml, src/Pim/Bundle/UserBundle/Resources/views/User/Tab/additional.html.twig, src/Pim/Bundle/UserBundle/Resources/views/User/view.html.twig, upgrades/schema/Version20151102131708.php
| Specs             | no need
| Behats            | done
| Review and 2 GTM  | ok
| Micro Demo (PO)   | ok
| Migration script  | yes
=> [TR] PIM-5048: User can configure what is the default view for product datagrid

CHANGELOG-1.5.md, spec/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/Repository/ProductRepositorySpec.php, spec/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/ProductRepositorySpec.php, src/Pim/Bundle/CatalogBundle/Repository/ProductRepositoryInterface.php
=> PIM-4347 Made ProductDraftRepository extends Doctrine ObjectRepository

behat.yml.dist
| Specs             |n/a
| Behats            |n/a
| Blue CI           |ok
| Review and 2 GTM  |ok
| Micro Demo (PO)   |n/a
| Migration script  |n/a
| Tech Doc          |n/a
Note : CI tested only one a few features because not necessary to test all. If it works with one on core-ci, it will work for all
=> PIM-5067 : enable distributed CI with master branch

CHANGELOG-1.4.md, src/Pim/Bundle/EnrichBundle/Resources/config/assets.yml, src/Pim/Bundle/EnrichBundle/Resources/public/css/mass-edit.less, src/Pim/Bundle/EnrichBundle/Resources/views/MassEditAction/configure/layout.html.twig
=> PIM-5169: fix mass edit attribute selection

src/Pim/Bundle/CatalogBundle/Resources/config/repositories.yml, src/Pim/Bundle/DataGridBundle/Resources/config/repositories.yml
=> PIM-5200: remove product value repository

features/Context/Spin/SpinCapableTrait.php
| Specs             |na
| Behats            |na
| Changelog updated |no
| Review and 2 GTM  |yes
=> [TR] PIM-5071 : fix spin too long

CHANGELOG-1.4.md, src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/FamilyRepository.php, src/Pim/Bundle/CatalogBundle/Repository/FamilyRepositoryInterface.php, src/Pim/Bundle/EnrichBundle/Controller/Rest/FamilyController.php
| Specs             | No
| Behats            | no
| Changelog updated | Not yet
=> [SLA][TR]PIM-5194: fix perf on json family generation

src/Pim/Bundle/CatalogBundle/Manager/AttributeOptionManager.php, src/Pim/Bundle/CatalogBundle/Manager/CategoryManager.php, src/Pim/Bundle/CatalogBundle/Manager/CurrencyManager.php, src/Pim/Bundle/CatalogBundle/Manager/FamilyManager.php, src/Pim/Bundle/CatalogBundle/Manager/GroupManager.php, src/Pim/Bundle/CatalogBundle/Manager/LocaleManager.php, src/Pim/Bundle/CatalogBundle/Repository/AttributeGroupRepositoryInterface.php, src/Pim/Bundle/CatalogBundle/Repository/AttributeRepositoryInterface.php
Prepare the performance epic on attributes amount axis
=> PIM-5203: mark unused methods as deprecated

src/Akeneo/Bundle/StorageUtilsBundle/MongoDB/MongoObjectsFactory.php, src/Pim/Bundle/TransformBundle/Normalizer/MongoDB/ProductNormalizer.php
Needed by : https://github.com/akeneo-labs/DirectToMongoDBBundle/pull/4
=> [TR] PIM-5219: Include database name into entity references

features/Context/AssertionContext.php, features/Context/Page/Base/Form.php, features/Context/Page/Product/Edit.php, features/Context/WebUser.php, features/localization/product/display_localized_history.feature, features/product/date.feature, spec/Pim/Bundle/LocalizationBundle/Normalizer/VersionNormalizerSpec.php, src/Pim/Bundle/LocalizationBundle/Normalizer/VersionNormalizer.php, src/Pim/Bundle/LocalizationBundle/Resources/config/normalizers.yml
| Blue CI           | (1 scenario with Multiselect always failing)
| Micro Demo (PO)   | TODO
=> [TR] PIM-5026: Add localized version normalizer

features/export/convert_metric_values_during_product_export.feature
| Specs             |already done
| Behats            |one additionnal test
| Changelog updated |already done
=> [TR] PIM-5062 : do not convert NULL data

CHANGELOG-1.4.md, composer.json, features/Context/Page/UserRole/Edit.php, features/Context/WebUser.php, features/user/edit_user_group_and_role_assignations.feature
=> PIM-5201: fix permission on edit role

CHANGELOG-1.3.md, CHANGELOG-1.4.md, features/product/completeness.feature, src/Akeneo/Bundle/StorageUtilsBundle/MongoDB/MongoObjectsFactory.php, src/Pim/Bundle/BaseConnectorBundle/Writer/File/CsvProductWriter.php, src/Pim/Bundle/CatalogBundle/Command/PurgeCompletenessCommand.php, src/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/CompletenessGenerator.php, src/Pim/Bundle/CatalogBundle/Manager/AttributeOptionManager.php, src/Pim/Bundle/CatalogBundle/Manager/CategoryManager.php, src/Pim/Bundle/CatalogBundle/Manager/CurrencyManager.php, src/Pim/Bundle/CatalogBundle/Manager/FamilyManager.php, src/Pim/Bundle/CatalogBundle/Manager/GroupManager.php, src/Pim/Bundle/CatalogBundle/MongoDB/Normalizer/MediaNormalizer.php, src/Pim/Bundle/CatalogBundle/Repository/AttributeGroupRepositoryInterface.php, src/Pim/Bundle/CatalogBundle/Repository/AttributeRepositoryInterface.php, src/Pim/Bundle/CatalogBundle/Version.php, src/Pim/Bundle/EnrichBundle/Resources/config/assets.yml, src/Pim/Bundle/EnrichBundle/Resources/public/css/mass-edit.less, src/Pim/Bundle/EnrichBundle/Resources/views/MassEditAction/configure/layout.html.twig, src/Pim/Bundle/TransformBundle/Normalizer/MongoDB/ProductNormalizer.php, src/Pim/Bundle/VersioningBundle/Doctrine/MongoDBODM/VersionRepository.php, src/Pim/Bundle/VersioningBundle/Resources/config/model/doctrine/Version.mongodb.yml, upgrades/schema/Version20151121110000.php
=> Merge 1 4 into master

CHANGELOG-1.4.md, src/Pim/Bundle/PdfGeneratorBundle/Resources/views/Product/renderPdf.html.twig
=> [TR] [SLA] PIM-5172: Fix PDF export for text area attribute

CHANGELOG-1.4.md, spec/Pim/Component/Connector/Processor/Denormalization/ProductAssociationProcessorSpec.php, spec/Pim/Component/Connector/Processor/Denormalization/ProductProcessorSpec.php, src/Akeneo/Bundle/StorageUtilsBundle/Doctrine/Common/Detacher/ObjectDetacher.php, src/Pim/Bundle/ConnectorBundle/Resources/config/batch_jobs.yml, src/Pim/Bundle/ConnectorBundle/Resources/config/processors.yml, src/Pim/Component/Connector/Processor/Denormalization/ProductAssociationProcessor.php, src/Pim/Component/Connector/Processor/Denormalization/ProductProcessor.php
Reverts akeneo/pim-community-dev#3599
=> Revert "[TR] PIM-5170 - Fixes MongoDB memory leak at import time."

CHANGELOG-1.4.md, CHANGELOG-1.5.md, features/Context/Page/UserRole/Edit.php, features/Context/WebUser.php, features/user/edit_user_group_and_role_assignations.feature, spec/Pim/Bundle/TransformBundle/Normalizer/Flat/AttributeGroupNormalizerSpec.php, spec/Pim/Bundle/TransformBundle/Normalizer/Structured/AttributeGroupNormalizerSpec.php, spec/Pim/Bundle/VersioningBundle/EventSubscriber/AddVersionSubscriberSpec.php, src/Oro/Bundle/SecurityBundle/Acl/Persistence/AclManager.php, src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/AttributeRepository.php, src/Pim/Bundle/CatalogBundle/Repository/AttributeRepositoryInterface.php, src/Pim/Bundle/DataGridBundle/Resources/config/requirejs.yml, src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid/action/configure-columns-action.js, src/Pim/Bundle/DataGridBundle/Resources/public/templates/configure-columns-action.html, src/Pim/Bundle/PdfGeneratorBundle/Resources/views/Product/renderPdf.html.twig, src/Pim/Bundle/TransformBundle/Normalizer/Flat/AttributeGroupNormalizer.php, src/Pim/Bundle/TransformBundle/Normalizer/Structured/AttributeGroupNormalizer.php, src/Pim/Bundle/TransformBundle/Resources/config/serializer/flat.yml, src/Pim/Bundle/TransformBundle/Resources/config/serializer/structured.yml, src/Pim/Bundle/VersioningBundle/EventSubscriber/AddVersionSubscriber.php, src/Pim/Bundle/VersioningBundle/Resources/config/event_subscribers.yml, src/Pim/Bundle/VersioningBundle/Resources/config/serializer/flat.yml
=> Merge 1.4 into master

CHANGELOG-1.4.md, features/mass-action/apply_permissions_on_mass_edit_actions.feature, features/user/edit_user_group_and_role_assignations.feature, spec/Pim/Bundle/EnrichBundle/MassEditAction/Operation/OperationRegistrySpec.php, src/Pim/Bundle/EnrichBundle/MassEditAction/Operation/OperationRegistry.php, src/Pim/Bundle/EnrichBundle/Resources/config/mass_actions.yml
=> [TR] PIM-5171: Apply ACLs on mass edit actions

CHANGELOG-1.5.md, behat.yml.dist, features/Context/Formatter/JUnitFormatter.php
| Specs             |no
| Behats            |yes
| Micro Demo (PO)   |
| Migration script  |no
| Tech Doc          |no
=> PIM-5067 : add a custom JUnit formatter

CHANGELOG-1.3.md, features/export/convert_metric_values_during_product_export.feature, features/filter/option.feature, features/filter/options.feature, spec/Pim/Bundle/CatalogBundle/Doctrine/Common/Filter/ObjectIdResolverSpec.php, src/Pim/Bundle/CatalogBundle/Doctrine/Common/Filter/ObjectIdResolver.php, src/Pim/Bundle/CatalogBundle/Doctrine/Common/Filter/ObjectIdResolverInterface.php, src/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/Filter/OptionFilter.php, src/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/Filter/OptionsFilter.php, src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Filter/OptionFilter.php, src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Filter/OptionsFilter.php
=> [TR] Merge 1 3 into 1 4

CHANGELOG-1.4.md, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/field/multi-select-field.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/field/simple-select-field.js
=> PIM-5159: Attribute values appearing/disappearing when you change attribute groups

features/localization/attribute/edit_attributes_with_localized_ui.feature, features/localization/mass-action/edit_common_attributes.feature, features/localization/product/validation/validate_metric_attributes.feature, features/localization/product/validation/validate_number_attributes.feature, features/localization/product/validation/validate_price_attributes.feature, features/localization/variant-group/edit_variant_group_attribute_value.feature, src/Pim/Bundle/LocalizationBundle/Resources/translations/validators.fr.yml
| Blue CI           | Only the concerned behat were runned, blue in ee-odm environment.
| Micro Demo (PO)   | n
=> [TR] PIM-5027: Add behats for attribute validations

CHANGELOG-1.5.md, features/Context/Page/Base/Grid.php, features/localization/display_localized_numbers_in_datagrid.feature, features/localization/product/display_localized_currencies.feature, spec/Pim/Component/Localization/Factory/NumberFactorySpec.php, spec/Pim/Component/Localization/Presenter/PricePresenterSpec.php, src/Pim/Bundle/DataGridBundle/Extension/Formatter/Property/ProductValue/PriceProperty.php, src/Pim/Bundle/DataGridBundle/Resources/config/formatters.yml, src/Pim/Bundle/LocalizationBundle/DependencyInjection/PimLocalizationExtension.php, src/Pim/Bundle/LocalizationBundle/Resources/config/factories.yml, src/Pim/Bundle/LocalizationBundle/Resources/config/presenters.yml, src/Pim/Component/Localization/Factory/NumberFactory.php, src/Pim/Component/Localization/Presenter/PresenterInterface.php, src/Pim/Component/Localization/Presenter/PricePresenter.php
| Blue CI           | c.f. comment
| Micro Demo (PO)   | TODO
Always failing (on Master too)
features/variant-group/edit_variant_group_attribute_value.feature:66
=> [TR] PIM-5032: Display localized currencies in product grid

features/Context/AssertionContext.php, src/Pim/Component/Localization/Localizer/PriceLocalizer.php
| Micro Demo (PO)   | N
| Migration script  | N
| Tech Doc          | N
=> PIM-5065: fix behat context

CHANGELOG-1.4.md, src/Pim/Bundle/UIBundle/Resources/public/css/pim.less
=> PIM-5241: Add css for weird multiselect display

features/localization/attribute/edit_attributes_with_localized_ui.feature, src/Pim/Bundle/LocalizationBundle/Form/DataTransformer/NumberLocalizerTransformer.php
| Blue CI           | 2 failing tests in EE, one is corrected with https://github.com/akeneo/pim-enterprise-dev/pull/1407 
=> [TR] PIM-5254: Display localized numbers in attributes edition

CHANGELOG-1.4.md, src/Pim/Bundle/DataGridBundle/Resources/public/js/multiselect-decorator.js, src/Pim/Bundle/EnrichBundle/Resources/views/MassEditAction/configure/edit-common-attributes.html.twig
=> PIM-5238: fix scroll on multiselect for mass edit

CHANGELOG-1.4.md, src/Pim/Bundle/UserBundle/Resources/views/Security/login.html.twig
=> PIM-5177: fix login redirection

CHANGELOG-1.4.md, features/Context/FixturesContext.php, spec/Pim/Component/Connector/ArrayConverter/Flat/AttributeStandardConverterSpec.php, src/Pim/Component/Connector/ArrayConverter/Flat/AttributeStandardConverter.php
| Specs             | yes
| Review and 2 GTM  | yes
=> [TR][SLA] PIM-5235: Fix empty reference data name after attributes import

src/Pim/Bundle/DataGridBundle/Resources/public/templates/configure-columns-action.html
=> PIM-5176: Fix translation message

spec/Pim/Bundle/EnrichBundle/Connector/Processor/MassEdit/Product/EditCommonAttributesProcessorSpec.php, src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/AttributeRepository.php, src/Pim/Bundle/TransformBundle/Normalizer/Structured/AttributeGroupNormalizer.php
| Blue CI           | Yes (features attributes/family)
| Review and 2 GTM  | Todo
=> PIM-5265: use of AttributeRepositoryInterface instead of AttributeRepository

src/Pim/Bundle/EnrichBundle/Resources/config/requirejs.yml, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/panel/completeness.js
=> PIM-5136: Add extension point on the completeness panel

composer.json
Configuration file will arrive soon
=> [DX] Add akeneo/php-coupling-detector in require-dev

.php_cd
useable with "bin/coupling-detector detect src/ --config-file .php_cd" extra doc is coming
=> [DX] Add coupling detector config

CHANGELOG-1.4.md, features/product/edit_product_family.feature, src/Pim/Bundle/EnrichBundle/Controller/Rest/FamilyController.php, src/Pim/Bundle/EnrichBundle/Doctrine/ORM/Repository/FamilySearchableRepository.php, src/Pim/Bundle/EnrichBundle/Resources/config/controllers.yml, src/Pim/Bundle/EnrichBundle/Resources/config/repositories.yml, src/Pim/Bundle/EnrichBundle/Resources/config/requirejs.yml, src/Pim/Bundle/EnrichBundle/Resources/config/routing/family.yml, src/Pim/Bundle/EnrichBundle/Resources/public/js/manager/attribute-manager.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/attributes.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/meta/change-family.js, src/Pim/Bundle/EnrichBundle/Resources/public/spec/manager/AttributeManagerSpec.js, src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/meta/change-family-modal.html
| Review and 2 GTM  | 2 GTM
In order to be able to load the PEF with more than 6k families, we need to ajaxify the change family select2. Thanks @sumbobyboys for the help ;)
=> [SLA] PIM-5194: Performance issues on families

CHANGELOG-1.4.md, src/Pim/Bundle/DataGridBundle/Resources/public/js/multiselect-decorator.js, src/Pim/Bundle/EnrichBundle/Resources/views/MassEditAction/configure/edit-common-attributes.html.twig
This reverts commit ace6b42241715d1d7b72dcdf5a527e18bac68055.
Conflicts:
CHANGELOG-1.4.md
=> Revert "PIM-5238: fix scroll on multiselect for mass edit"

CHANGELOG-1.4.md, src/Pim/Bundle/UserBundle/Resources/views/Security/login.html.twig
This reverts commit 111cf69ceb5d36b8ffeab9700fd5d7af491c584b.
Conflicts:
CHANGELOG-1.4.md
=> Revert "PIM-5177: fix login redirection"

UPGRADE-1.5.md
baby PR to discuss about normalizers / denormalizers
=> Normalizer / Denormalizer organization

spec/Pim/Bundle/EnrichBundle/Normalizer/ProductViolationNormalizerSpec.php, src/Pim/Bundle/EnrichBundle/Controller/Rest/ProductController.php, src/Pim/Bundle/EnrichBundle/Normalizer/ProductViolationNormalizer.php, src/Pim/Bundle/EnrichBundle/Resources/config/normalizers.yml, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/attributes/attribute-group-selector.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/attributes/validation.js
=> PIM-5210: Use a normalizer for product violations

CHANGELOG-1.4.md, features/Context/Page/AttributeGroup/Edit.php, features/Context/Page/Product/Edit.php, features/product/order_attributes.feature, spec/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/Saver/ProductSaverSpec.php, spec/Pim/Bundle/EnrichBundle/Normalizer/AttributeNormalizerSpec.php, spec/Pim/Bundle/VersioningBundle/Doctrine/MongoDBODM/BulkVersionBuilderSpec.php, spec/Pim/Bundle/VersioningBundle/Doctrine/MongoDBODM/Saver/BulkVersionSaverSpec.php, src/Pim/Bundle/EnrichBundle/Normalizer/AttributeNormalizer.php, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/attributes.js
=> [SLA] PIM-5276: Fixed attribute ordering in the product view

CHANGELOG-1.4.md, features/navigation/navigate_using_hash_navigation.feature, src/Akeneo/Bundle/ClassificationBundle/Doctrine/ORM/Repository/AbstractItemCategoryRepository.php, src/Pim/Bundle/NavigationBundle/Resources/views/HashNav/script.js.twig, src/Pim/Bundle/UIBundle/Resources/public/js/init-layout.js
The problem was that the `mediator.bind` was called after the triggering of the event. So I overrode the script.js.twig to add the bind here
=> PIM-5282: fix reload freeze bug

CHANGELOG-1.4.md, features/Context/DataGridContext.php, src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filter/date-filter.js, src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filter/datetime-filter.js
=> PIM-5269: fix date filter on product grid

features/Context/Page/AttributeGroup/Edit.php
=> [TR] PIM-5276: Fixed behat issue about drag&drop

CHANGELOG-1.4.md, features/Context/Page/Product/Creation.php, features/mass-action/edit_common_attributes.feature, features/product/create_product.feature, spec/Pim/Bundle/EnrichBundle/Form/DataTransformer/IdentifiableModelTransformerSpec.php, spec/Pim/Bundle/EnrichBundle/Form/Factory/IdentifiableModelTransformerFactorySpec.php, spec/Pim/Bundle/EnrichBundle/Form/Type/AsyncSelectTypeSpec.php, spec/Pim/Bundle/EnrichBundle/Form/Type/ProductCreateTypeSpec.php, src/Pim/Bundle/EnrichBundle/Form/DataTransformer/IdentifiableModelTransformer.php, src/Pim/Bundle/EnrichBundle/Form/Factory/IdentifiableModelTransformerFactory.php, src/Pim/Bundle/EnrichBundle/Form/Type/AsyncSelectType.php, src/Pim/Bundle/EnrichBundle/Form/Type/ProductCreateType.php, src/Pim/Bundle/EnrichBundle/Resources/config/factories.yml, src/Pim/Bundle/EnrichBundle/Resources/config/form_types.yml, src/Pim/Bundle/EnrichBundle/Resources/config/forms.yml, src/Pim/Bundle/EnrichBundle/Resources/views/Product/create.html.twig, src/Pim/Bundle/UIBundle/Resources/public/js/pim-initselect2.js
| Specs             |y
| Behats            |y
| Blue CI           |runnin
| Changelog updated |y
| Review and 2 GTM  |2 gtm
| Micro Demo (PO)   |
| Migration script  |n
| Tech Doc          |n
Add a new form styme type to display a select2 with AJAX autocompletion.
Options required for the AjaxSelectType : 
- `route` : the route for fetching data
- `repository` : an `IdentifiableRepositoryInterface` to transform data from the form data
=> PIM-5231 : Create a product with 10k+ families

.php_cd
| Specs             |
| Behats            |
| Changelog updated |
=> [WIP] Update coupling rules

features/localization/product/validation/validate_number_attributes.feature, spec/Pim/Bundle/EnrichBundle/Normalizer/ProductViolationNormalizerSpec.php, src/Pim/Bundle/EnrichBundle/Controller/Rest/ProductController.php, src/Pim/Bundle/EnrichBundle/Normalizer/ProductViolationNormalizer.php
Fix the display of errors in the PEF with localized attributes since the merge of 1.4 in master.
| Behats            | fixed
=> Fix validation for localized attributes

features/product/add_new_option_to_choice_attribute.feature, features/product/edit_product_and_action.feature
| Specs             |n/a
| Behats            |fixed
| Changelog updated |n/a
Fix an unstable feature on 1.4 branch
=> [TR] Behat : fix unstable feature add_new_option_to_choice_attribute

features/Context/Page/Job/Show.php, features/export/view_an_export_detail_page.feature
Attempt to fix : export > view_an_export_detail_page.feature > Successfully display the validation errors
=> [TR] Fix export detail behat

features/localization/product/validation/validate_metric_attributes.feature, features/product/add_attributes_to_a_product.feature, features/product/edit_product.feature, features/product/history/display_history.feature, features/product/history_update.feature, features/product/validation/validate_metric_attributes.feature, src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/field/metric.html
| Review and 2 GTM  | :white_check_mark: 
| Micro Demo (PO)   | TODO
| Migration script  | N
| Tech Doc          | N
=> PIM-5274: translate the unit of the metric

src/Pim/Bundle/EnrichBundle/Resources/public/js/tree-associate.jstree.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/tree-view.jstree.js, src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/panel/completeness.html, src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/tab/attributes/copy.html, src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml, src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.fr.yml, src/Pim/Bundle/EnrichBundle/Resources/views/Group/Tab/property.html.twig, src/Pim/Bundle/UIBundle/Resources/translations/jsmessages.en.yml, src/Pim/Bundle/UIBundle/Resources/translations/jsmessages.fr.yml, src/Pim/Bundle/UIBundle/Resources/views/Form/pim-fields.html.twig
| Blue CI           | (always the same failing tests)
=> [TR] PIM-5278: Fix missing translations

features/Context/Page/Base/Form.php, features/Context/Page/Product/Edit.php, features/Context/catalog/footwear/attributes.yml
=> [TR] Fix Behats on master

features/localization/display_localized_numbers_in_datagrid.feature, features/localization/product/display_localized_history.feature, spec/Pim/Component/Localization/Presenter/MetricPresenterSpec.php, src/Pim/Component/Localization/Presenter/MetricPresenter.php
| Blue CI           | (always same failing)
| Micro Demo (PO)   | TODO
=> [TR] PIM-5280: Localize metric unit

CHANGELOG-1.4.md, features/Context/FixturesContext.php, features/user/edit_user_group_and_role_assignations.feature
=> PIM-5348: fix role count on behats

CHANGELOG-1.4.md, src/Akeneo/Bundle/StorageUtilsBundle/Doctrine/Common/Detacher/ObjectDetacher.php
The description of what the PR does
=> PIM-5170: Cascade detach on detachAll

CHANGELOG-1.4.md, features/Context/FeatureContext.php, features/navigation/pin_pages.feature, features/product/associate_product.feature, src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filter/product_category-filter.js, src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/association_product.yml
Already reviewed here : https://github.com/akeneo/pim-community-dev/pull/3734
=> [SLA][TR] PIM-5295: Fix association product grid category filter

features/Context/Page/Base/ProductEditForm.php, src/Akeneo/Component/StorageUtils/Repository/SearchableRepositoryInterface.php, src/Pim/Bundle/EnrichBundle/Controller/Rest/AttributeController.php, src/Pim/Bundle/EnrichBundle/Doctrine/ORM/Repository/AttributeSearchableRepository.php, src/Pim/Bundle/EnrichBundle/Resources/config/controllers.yml
| Behats            | Y http://core-ci.akeneo.com/job/dci_behat/312
| Micro Demo (PO)   | No
=> PIM-5213: refactor for EE purpose

src/Pim/Bundle/DataGridBundle/Extension/Pager/Orm/Pager.php
| Added Specs       |No
| Added Behats      |No
| Travis CI is ok   |
| Changelog updated |No
See #3610
=> Family grid and ONLY_FULL_GROUP_BY mysql mode

features/Context/Page/Base/Grid.php
This will fix broken scenarios about the proposals grid.
=> [TR] Fix cells selection in grid context

CHANGELOG-1.4.md, src/Pim/Bundle/DataGridBundle/Extension/Pager/Orm/Pager.php
It reverts the changes in the ORM pager that break a behat
=> [GITHUB-3610]: revert fix orm pager

src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml, src/Pim/Bundle/UIBundle/Resources/public/css/pim.less
About
--------
I added a twig extension sooner (https://github.com/akeneo/pim-community-dev/pull/3850) but after a discussion with our UX, he said to me that we already have a css class that do the same thing as the one I added so I reviewed it here.
We discussed to add a no-margin class too as I need it in another context and he agreed.
=> Reviewed css class naming

features/Context/CommandContext.php
| Specs             | No
| Blue CI           | CE OK, EE Pending
| Review and 2 GTM  | 1 from @skeleton via previous https://github.com/akeneo/pim-community-dev/pull/3859
=> Completeness calculation in Behats now uses CLI

.travis.yml, composer.json
| Added Specs       |no
| Added Behats      |no
| Travis CI is ok   |yes
| Changelog updated |no
=> PIM-5450: Add MongoDb bundle to dev requirements

CHANGELOG-1.4.md, features/Context/WebUser.php, features/product/add_attributes_to_a_product.feature, features/product/ensure_tab_redirection.feature, src/Pim/Bundle/EnrichBundle/Controller/SequentialEditController.php, src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/product.yml, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/form-tabs.js
| Review and 2 GTM  | Yes
EnsureDefault taking in account the isVisible method. We should also manage information coming from the grid for associations (Not really do able in a patch).
=> PIM-5395: Fix tab redirection on different right cases

features/Context/Formatter/JUnitFormatter.php, features/product/toggle_status_product.feature
| Bug fix?             | No
| Tests pass?          | Yes
| Scenarios pass?      | Yes
| Checkstyle issues?*  | No 
| PMD issues?**        | No 
| Changelog updated?   | N.A.
| Fixed tickets        | PIM-5437
| Doc PR               | No
Please note the JUnitFormatter comes from master.
=> Pim 5437 - Makes Akeneo PIM CE 1.2 compatible with DCI

src/Pim/Bundle/EnrichBundle/Controller/Rest/AttributeController.php, src/Pim/Bundle/EnrichBundle/Resources/config/routing/attribute.yml
=> [TR][SLA] PIM-5446: Bugfix on login page with attribute loading

src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid/state.js, src/Pim/Bundle/DataGridBundle/Resources/views/Datagrid/_views.html.twig, src/Pim/Bundle/DataGridBundle/Resources/views/macros.html.twig, src/Pim/Bundle/NotificationBundle/Resources/views/Notification/list.json.twig
| Behats            | ok
| Blue CI           | ok
| Changelog updated | no need
| Review and 2 GTM  | 
| Micro Demo (PO)   | ok
| Migration script  |
=> [TR] PIM-5050: Display the proposal grid when clicking on a proposal notification

.travis.yml, composer.json
| Specs             |not needed
| Behats            |not needed
| Blue CI           |runnin
| Changelog updated |not needed
=> PIM-5450: require correct version of mongo db bundle

src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/tab/association-panes.html, src/Pim/Bundle/UIBundle/Resources/public/css/pim.less
| Behats            | ok
| Blue CI           |  ok
| Changelog updated | no need
| Review and 2 GTM  | ok
| Micro Demo (PO)   |
| Migration script  |
=> [TR] PIM-5386: Association tabs are displayed one by one in PEF

CHANGELOG-1.4.md, src/Pim/Bundle/EnrichBundle/Controller/Rest/AttributeController.php, src/Pim/Bundle/EnrichBundle/Doctrine/ORM/Repository/AttributeSearchableRepository.php
| Blue CI           | processing
=> [SLA] PIM-5478: Change string to array for user_groups restriction in attribute searchable repository

features/Context/AssertionContext.php, features/Context/DataGridContext.php, features/Context/FeatureContext.php, features/Context/Page/Base/Grid.php, features/Pim/Behat/Context/HookContext.php, spec/Pim/Bundle/EnrichBundle/Twig/AttributeExtensionSpec.php, src/Pim/Bundle/EnrichBundle/Resources/config/twig.yml, src/Pim/Bundle/EnrichBundle/Twig/AttributeExtension.php
| Micro Demo (PO)   | NA
| Migration script  | 
=> PIM-5393: fix proposal display

src/Pim/Bundle/PdfGeneratorBundle/DependencyInjection/PimPdfGeneratorExtension.php, src/Pim/Bundle/PdfGeneratorBundle/Resources/config/twig.yml, src/Pim/Bundle/PdfGeneratorBundle/Resources/views/Product/renderPdf.html.twig, src/Pim/Bundle/PdfGeneratorBundle/Twig/ImageExtension.php
| Specs             | not needed
| Behats            | not needed
| Changelog updated | TODO
Move image path finding for product values, to be able to override it.
=> PIM-5105: Insert extension for image display in PDF

src/Akeneo/Component/Classification/Model/CategoryInterface.php
=> Fix phpdoc

CHANGELOG-1.4.md, src/Akeneo/Component/Console/CommandLauncher.php
| Travis CI is ok   | ?
As the Changelog is updated for the 1.4.17. I let you prepare it. This issue is not linked to a ticket.
=> Fix CommandLauncher to launch as a backend task

src/Pim/Bundle/UIBundle/Resources/public/css/buttons.less
| Micro Demo (PO)   | todo
The goal here was to customize our buttons to be able to make this kind of buttons in the datagrids:
=> Customize action button

features/Context/AssertionContext.php, features/category/edit_a_category.feature
Fix for :
features/category/edit_a_category.feature:10
features/product/toggle_status_product.feature:12
=> Fix behats

src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/job_tracker.yml, src/Pim/Bundle/EnrichBundle/Resources/translations/messages.en.yml, src/Pim/Bundle/ImportExportBundle/Resources/public/js/job-execution-view.js, src/Pim/Bundle/ImportExportBundle/Resources/translations/jsmessages.en.yml, src/Pim/Bundle/ImportExportBundle/Resources/translations/messages.en.yml
| Specs             | OK
| Blue CI           | OK
| Review and 2 GTM  | OK
| Micro Demo (PO)   | OK
=> PIM-5289: Add translation to assets mass upload

CHANGELOG-1.5.md, spec/Pim/Bundle/CatalogBundle/Validator/AttributeValidatorHelperSpec.php, spec/Pim/Bundle/EnrichBundle/Filter/ProductEditDataFilterSpec.php, spec/Pim/Bundle/EnrichBundle/Filter/ProductValuesEditDataFilterSpec.php, spec/Pim/Bundle/EnrichBundle/MassEditAction/Operation/EditCommonAttributesSpec.php, src/Pim/Bundle/CatalogBundle/Validator/AttributeValidatorHelper.php, src/Pim/Bundle/EnrichBundle/Controller/MassEditActionController.php, src/Pim/Bundle/EnrichBundle/Doctrine/ORM/Repository/AttributeSearchableRepository.php, src/Pim/Bundle/EnrichBundle/Filter/ProductEditDataFilter.php, src/Pim/Bundle/EnrichBundle/Filter/ProductValuesEditDataFilter.php, src/Pim/Bundle/EnrichBundle/MassEditAction/Operation/EditCommonAttributes.php, src/Pim/Bundle/EnrichBundle/Resources/config/filters.yml, src/Pim/Bundle/EnrichBundle/Resources/config/mass_actions.yml
| Micro Demo (PO)   | Y
| Migration script  | NA
| Tech Doc          | NA
=> PIM-5452: add readonly on mass edit attributes

CHANGELOG-1.4.md, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/attributes/add-attribute.js
| Behats            | Not possible to cover this case
=> PIM-5471: Close & destroy select2 on page change with hash-navigation

app/config/config.yml, features/localization/attribute/edit_attributes_with_localized_ui.feature, features/localization/import/import_product_with_decimal.feature, features/localization/mass-action/edit_common_attributes.feature, features/localization/product/validation/validate_metric_attributes.feature, features/localization/product/validation/validate_number_attributes.feature, features/localization/product/validation/validate_price_attributes.feature, features/localization/variant-group/edit_variant_group_attribute_value.feature, spec/Pim/Component/Localization/Validator/Constraints/NumberFormatValidatorSpec.php, src/Pim/Bundle/LocalizationBundle/Resources/config/validators.yml, src/Pim/Bundle/LocalizationBundle/Resources/translations/validators.en.yml, src/Pim/Bundle/LocalizationBundle/Resources/translations/validators.fr.yml, src/Pim/Bundle/UIBundle/Form/Type/NumberType.php, src/Pim/Bundle/UIBundle/Resources/config/forms.yml, src/Pim/Component/Localization/Validator/Constraints/NumberFormatValidator.php
| Behats            | y 
All the commits will be squashed
=> PIM-5388: Add description of the decimal separator in validations

features/locale/change_user_locale.feature, features/localization/product/edit_product.feature, src/Oro/Bundle/ConfigBundle/Resources/translations/jsmessages.en.yml, src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml, src/Pim/Bundle/EnrichBundle/Resources/translations/messages.en.yml, src/Pim/Bundle/UIBundle/Resources/translations/jsmessages.en.yml, src/Pim/Bundle/UserBundle/Resources/translations/messages.en.yml, src/Pim/Bundle/UserBundle/Resources/translations/messages.fr.yml
| Specs             | not needed
| Behats            | not needed
| Changelog updated | ?
=> PIM-5585 - PIM-5586: Add missing translations

app/config/pim_parameters.yml, composer.json, src/Pim/Bundle/InstallerBundle/Command/DatabaseCommand.php, src/Pim/Bundle/InstallerBundle/DataFixtures/ORM/AbstractInstallerFixture.php, src/Pim/Bundle/InstallerBundle/DependencyInjection/PimInstallerExtension.php, src/Pim/Bundle/InstallerBundle/FixtureLoader/FixtureJobLoader.php
Just putting this PR https://github.com/akeneo/pim-community-dev/pull/3949 in 1.4
=> JML installer for 1.4

CONTRIBUTING.md, ISSUE_TEMPLATE.md, PULL_REQUEST_TEMPLATE.md
Add github templates to ease contribution and issue creation (cf https://github.com/blog/2111-issue-and-pull-request-templates).
=> [DX] ease issue creation and contribution

features/channel/edit_channel.feature, src/Pim/Bundle/EnrichBundle/Form/Type/ConversionUnitsType.php, src/Pim/Bundle/UIBundle/Resources/views/Form/pim-fields.html.twig
```
| Review and 2 GTM                  | Y 
| Migration script                  | N 
```
=> PIM-5275: Translate unit of metrics

app/check.php
=> Update Symfony requirements

features/Context/FixturesContext.php, features/Context/Loader/UserLoader.php, features/Pim/Behat/Context/FixturesContext.php, src/Acme/Bundle/AppBundle/DependencyInjection/AcmeAppExtension.php, src/Acme/Bundle/AppBundle/Resources/config/entities.yml, src/Acme/Bundle/AppBundle/Resources/config/savers.yml, src/Akeneo/Bundle/BatchBundle/Resources/config/savers.yml, src/Akeneo/Bundle/StorageUtilsBundle/Resources/config/savers.yml, src/Pim/Bundle/ConnectorBundle/Resources/config/savers.yml, src/Pim/Bundle/DataGridBundle/Resources/config/savers.yml, src/Pim/Bundle/UserBundle/DependencyInjection/PimUserExtension.php, src/Pim/Bundle/UserBundle/Resources/config/savers.yml, src/Pim/Bundle/VersioningBundle/Resources/config/savers.yml
This PR allows to always use savers in our Behat context to continue to remove all direct use of persist / flush in the stack.
This PR also add missing savers definition and declare the base saver class in the storage utils to avoid to use the base definition of the catalog everywhere.
| ----------------------------- | ---
| Added Specs              | N
| Added Behats             | Y (only changes in contexts)
| Changelog updated    | N
| Review and 2 GTM     |
=> [DX] always use savers in behat context

src/Pim/Bundle/CatalogBundle/Resources/config/updaters.yml, src/Pim/Component/Catalog/Updater/ProductUpdater.php
to add new fields to the product (not attributes), only updating the service
=> Update ProductUpdater and pim_catalog.updater.product

CHANGELOG-1.6.md, spec/Pim/Component/Catalog/Updater/ProductUpdaterSpec.php, src/Pim/Bundle/CatalogBundle/Resources/config/updaters.yml, src/Pim/Component/Catalog/Updater/ProductUpdater.php
cf https://github.com/akeneo/pim-community-dev/pull/3980
=> [DX] fix product updater specs

build.xml, features/Context/FixturesContext.php, src/Akeneo/Bundle/StorageUtilsBundle/Doctrine/MongoDBODM/Cursor/Cursor.php, src/Akeneo/Bundle/StorageUtilsBundle/EventSubscriber/MongoDBODM/EntitiesTypeSubscriber.php
1. Fix codestyle
2. Remove the interfaces checking like in 1.4 & 1.5
=> Fix static analysis

CHANGELOG-1.4.md, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/associations.js
| Added Specs                     |n
| Added Behats                      |n
| Changelog updated                 |y
| Review and 2 GTM                  |1
| Migration script                  |n
| Tech Doc                          |n
=> [WIP] PIM-5587 : Association grid state as a private closure.

features/Context/AssertionContext.php, features/Context/Page/Base/Base.php, features/Context/Page/Base/Form.php, features/Context/WebUser.php, features/Pim/Behat/Context/Domain/TreeContext.php, features/Pim/Behat/Context/FixturesContext.php, features/attribute-group/display_attribute_group_history.feature, features/attribute/create_text_attribute.feature, features/attribute/option/create_attribute_options.feature, features/category/edit_a_category.feature, features/datagrid/datagrid_views.feature, features/enrich/variant-group/add_attributes_to_a_variant_group.feature, features/enrich/variant-group/edit_variant_group_attribute_value.feature, features/family/define_the_attribute_requirement.feature, features/family/display_family_history.feature, features/locale/change_user_locale.feature, features/localization/variant-group/edit_variant_group_attribute_value.feature, features/product/edit_product_and_action.feature, features/product/join_an_image_to_a_product.feature, features/reference-data/attribute/display_attribute_history.feature, features/user/edit_user.feature, features/user/edit_user_group_and_role_assignations.feature, features/user/update_user_preferences.feature
Things done in this PR:
- Remove all the "waits" after all the save methods
- Add spin methods waiting for flash message.
- Add a new method for checking flash messages. In fact, the previous one returns true. If I replace it by a functional one, it raises for a few tests. So, I add a new functional one, replace it when tests are not outdated, and depreciate the old one.
=> Fix random behat on save

CHANGELOG-1.3.md, features/product/filtering/filter_product_per_boolean.feature, features/product/sorting/sort_products_per_attribute.feature, src/Pim/Bundle/FilterBundle/Resources/public/js/datafilter/filter/select-filter.js
| Added Behats      | Y
| Travis CI is ok   |
=> PIM-5610: Fix boolean filter on product grid

src/Pim/Bundle/InstallerBundle/DataFixtures/AbstractLoadFixturesData.php, src/Pim/Bundle/InstallerBundle/FixtureLoader/FixtureJobLoader.php
Fix typos in installer
```
| Migration script                  | - 
```
=> Fix typos in installer

src/Pim/Bundle/CatalogBundle/Resources/config/model/doctrine/Association.orm.yml, src/Pim/Bundle/CatalogBundle/Resources/config/model/doctrine/Product.mongodb.yml, src/Pim/Bundle/CatalogBundle/Resources/config/model/doctrine/Product.orm.yml, src/Pim/Bundle/NotificationBundle/Resources/config/doctrine/UserNotification.orm.yml
Fix paths for repository classes in Doctrine mappings
```
```
=> Fix repository paths in mappings

CHANGELOG-1.5.md, src/Pim/Bundle/InstallerBundle/ComposerScripts.php
=> Fix migration script 1.4 to 1.5

src/Pim/Bundle/ConnectorBundle/Resources/config/batch_jobs.yml
=> [PIM-5098] Wrong translation key

CHANGELOG-1.6.md, features/Context/WebUser.php, features/Context/catalog/footwear/jobs.yml, features/localization/mass-action/quick_export.feature, features/mass-action/quick_export.feature, src/Pim/Bundle/EnrichBundle/Resources/config/batch_jobs.yml, src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/product.yml, src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml, src/Pim/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev/jobs.yml, src/Pim/Bundle/InstallerBundle/Resources/fixtures/minimal/jobs.yml, src/Pim/Component/Connector/Writer/File/XlsxProductWriter.php, upgrades/schema/Version_1_6_201603100000_batch_jobs.php
Adds an XLSX quick export button to the product grid.
| Migration script                  |  Yes
=> PIM-5096: Add XLSX quick export

PULL_REQUEST_TEMPLATE.md
:heart_eyes: Thanks for taking the time to contribute! You're awesome! :heart_eyes:
```
```
=> Change the contributing template

CHANGELOG-1.4.md, features/Context/Page/Product/Edit.php, features/Context/WebUser.php, features/product/ensure_completeness_display_for_locale_specific.feature, spec/Pim/Bundle/EnrichBundle/Normalizer/CompletenessCollectionNormalizerSpec.php, src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/FamilyRepository.php, src/Pim/Bundle/CatalogBundle/Manager/CompletenessManager.php, src/Pim/Bundle/EnrichBundle/Controller/Rest/CompletenessController.php, src/Pim/Bundle/EnrichBundle/Normalizer/CompletenessCollectionNormalizer.php, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/panel/completeness.js, src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/panel/completeness.html
Fix https://akeneo.atlassian.net/browse/PIM-5453
```
| Migration script                  | 
```
=> PIM-5453 : Display completeness missing labels according to the locale your are working on

CHANGELOG-1.3.md, features/Context/DataGridContext.php, features/datagrid/products_category_backtothegrid.feature, src/Pim/Bundle/DataGridBundle/Extension/Filter/FilterExtension.php
=> [SLA] PIM-5638: fix error on filter grid method

src/Pim/Bundle/DataGridBundle/Resources/views/macros.html.twig, src/Pim/Bundle/EnrichBundle/Resources/public/js/tree-view.jstree.js, src/Pim/Bundle/EnrichBundle/Resources/views/Product/index.html.twig, src/Pim/Bundle/FilterBundle/Resources/public/js/datafilter/filter/product_category-filter.js
=> [SLA] PIM-5638: fix wrong category display on published product grid

CHANGELOG-1.6.md, src/Akeneo/Bundle/BatchBundle/Job/DoctrineJobRepository.php, src/Akeneo/Bundle/BatchBundle/Resources/config/services.yml
This fix the broken master, explanation in the code itself.
I'm not fan of big comments in the code directly because it mean the code is ugly but it's the case here and we spent time understanding why this does not work, so i would keep the big comment to avoid spend time on this on future re-writing.
| Changelog updated                 | TODO
| Review and 2 GTM                  | I hope :trollface: 
=> PIM-5589: fix the import / export in EE

src/Oro/Bundle/UserBundle/Form/Type/UserApiType.php
```
```
There is no Oro\Bundle\UserBundle\Form\Type\UserType
=> Fixes #3950

CHANGELOG-1.4.md, features/Context/DataGridContext.php, features/product/classify_product.feature, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/categories.js, src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/tab/categories.html
Fix category tree does not load when 0 categories selected
=> [SLA] PIM-5656 : Fix category tree does not load when 0 categories selected	

CHANGELOG-1.5.md, features/Context/CatalogConfigurationContext.php, features/Context/DataGridContext.php, features/Context/WebUser.php, features/Pim/Behat/Context/NavigationContext.php, features/locale/change_system_locale.feature, spec/Pim/Bundle/UserBundle/EventSubscriber/LocaleSubscriberSpec.php, src/Oro/Bundle/ConfigBundle/Entity/Repository/ConfigValueRepository.php, src/Oro/Bundle/ConfigBundle/Resources/config/controllers.yml, src/Oro/Bundle/ConfigBundle/Resources/public/js/form/system/group/localization.js, src/Pim/Bundle/LocalizationBundle/DependencyInjection/Configuration.php, src/Pim/Bundle/LocalizationBundle/DependencyInjection/PimLocalizationExtension.php, src/Pim/Bundle/UserBundle/EventSubscriber/LocaleSubscriber.php, src/Pim/Bundle/UserBundle/Resources/config/event_subscribers.yml
Fix Default system locale not saved and not taken into account on login page
=> PIM-5643 : Fix default system locale

CHANGELOG-1.4.md, composer.json, features/product/classify_product.feature, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/categories.js, src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/tab/categories.html
=> Merge 1.4 1.5

src/Pim/Bundle/DataGridBundle/Resources/config/hydrators.yml
add ObjectIdHydrator for ORM to fix datagrid rules
=> PIM-5455: add ObjectIdHydrator for orm

src/Pim/Bundle/EnrichBundle/Resources/views/Product/edit.html.twig
Add a LoadingMask on Product Edit Form Loading instead of viewing a blank screen
=> PIM-5647 : Add LoadingMask on PEF loading

CHANGELOG-1.6.md, UPGRADE-1.6.md, features/Context/catalog/apparel/jobs.yml, features/export/export_groups_in_xlsx.feature, features/export/export_products_in_xlsx.feature, features/export/export_variant_groups_in_xlsx.feature, spec/Pim/Component/Connector/Normalizer/Flat/GroupNormalizerSpec.php, spec/Pim/Component/Connector/Processor/Normalization/SimpleProcessorSpec.php, spec/Pim/Component/Connector/Processor/Normalization/VariantGroupProcessorSpec.php, spec/Pim/Component/Connector/Writer/File/XlsxSimpleWriterSpec.php, spec/Pim/Component/Connector/Writer/File/XlsxVariantGroupWriterSpec.php, src/Pim/Bundle/BaseConnectorBundle/Reader/Doctrine/ORMProductReader.php, src/Pim/Bundle/BaseConnectorBundle/Resources/config/processors.yml, src/Pim/Bundle/ConnectorBundle/Resources/config/batch_jobs.yml, src/Pim/Bundle/ConnectorBundle/Resources/config/processors.yml, src/Pim/Bundle/ConnectorBundle/Resources/config/writers.yml, src/Pim/Bundle/ConnectorBundle/Resources/translations/messages.en.yml, src/Pim/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev/jobs.yml, src/Pim/Component/Connector/Normalizer/Flat/GroupNormalizer.php, src/Pim/Component/Connector/Processor/Normalization/SimpleProcessor.php, src/Pim/Component/Connector/Processor/Normalization/VariantGroupProcessor.php, src/Pim/Component/Connector/Writer/File/FlatItemBuffer.php, src/Pim/Component/Connector/Writer/File/XlsxSimpleWriter.php, src/Pim/Component/Connector/Writer/File/XlsxVariantGroupWriter.php
This PR add XLSX Variant group and Group export and handle archive for Variant Group with media.
| Added Behats                      | ok
| Changelog updated                 | no need
| Micro Demo to the PO (Story only) | Done !
=> [TR] PIM-5100: Add XLSX Variant group and Group export

features/export/export_products_and_download_exported_file.feature, src/Pim/Bundle/BaseConnectorBundle/Archiver/FileWriterArchiver.php
=> Fix download file button

src/Pim/Bundle/EnrichBundle/Form/Type/AsyncSelectType.php
=> Fix typo AsyncSelectType phpdoc

features/export/export_attributes.feature, spec/Pim/Component/Catalog/Normalizer/Structured/AttributeNormalizerSpec.php, spec/Pim/Component/Connector/Normalizer/Flat/AttributeNormalizerSpec.php, src/Pim/Component/Catalog/Normalizer/Structured/AttributeNormalizer.php
Extending list of attribute properties attribute normalizer normalize to full list. #4220
=> 4220 attr normalizer attr export

CHANGELOG-1.4.md
=> PIM-5699: Update changelog

CHANGELOG-1.4.md, upgrades/schema/Version_1_5_20160405165700_versioning.php
In 1.5 we moved model class to the catalog component. As the versioning rely on the FQCN to create and find versions we need to update the version table with the correct FQCN
| Migration script                  | Y
=> PIM-5651: add migration for versioning

features/Context/catalog/footwear/jobs.yml, features/acl/assert_acl.feature, features/acl/enforce_acl_on_history.feature, features/import/delete_an_import.feature, features/import/product_group/xlsx/import_groups.feature, features/import/product_variant_group/import_variant_group_values_with_axis_as_data.feature, features/import/product_variant_group/import_variant_group_values_with_empty_data.feature, features/import/product_variant_group/import_variant_group_values_with_file_upload.feature, features/import/product_variant_group/import_variant_group_values_with_invalid_data.feature, features/import/product_variant_group/import_variant_group_values_with_valid_data.feature, features/import/product_variant_group/import_variant_group_with_invalid_properties.feature, features/import/product_variant_group/upload_and_import_variant_groups_with_media.feature, features/import/product_variant_group/xlsx/import_variant_group_with_valid_properties.feature, src/Pim/Bundle/BaseConnectorBundle/Resources/config/batch_jobs/xlsx_connector.yml, src/Pim/Bundle/ConnectorBundle/Resources/config/readers.yml, src/Pim/Bundle/ConnectorBundle/Resources/translations/messages.en.yml, src/Pim/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev/jobs.yml
Add Xlsx Import for groups and variant groups
=> PIM-5095 : Add Xlsx Import for groups and variant groups

features/Context/catalog/footwear/families.csv, features/family/browse_families.feature, features/family/delete_family.feature, features/product/edit_product_family.feature, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/meta/change-family.js, src/Pim/Bundle/UIBundle/Resources/public/js/pim-initselect2.js
Allow the user to filter on family label also
=> PIM-5730: filter also on family labels

CHANGELOG-1.5.md, features/Context/Page/Attribute/Creation.php, features/Context/Page/Base/ProductEditForm.php, spec/Pim/Component/Catalog/Localization/Presenter/PricesPresenterSpec.php, src/Pim/Bundle/DataGridBundle/Extension/Formatter/Property/ProductValue/PriceProperty.php, src/Pim/Component/Catalog/Localization/Presenter/PricesPresenter.php
| Added Behats                      | N (behat are on EE)
=> PIM-5695: do not format with currency if data is null

src/Pim/Bundle/EnrichBundle/Resources/public/js/fetcher/base-fetcher.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/form/cache-invalidator.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/field/field.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/save.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/state.js
=> PIM-5339: remove and clean console.log

CHANGELOG-1.6.md, features/Context/catalog/footwear/jobs.yml, features/import/delete_an_import.feature, features/import/import_association_types.feature, features/import/import_attributes.feature, features/import/import_categories.feature, features/import/import_families.feature, features/import/import_options.feature, src/Pim/Bundle/BaseConnectorBundle/Resources/config/batch_jobs/csv_connector.yml, src/Pim/Bundle/BaseConnectorBundle/Resources/config/batch_jobs/xlsx_connector.yml, src/Pim/Bundle/ConnectorBundle/Resources/config/readers.yml, src/Pim/Bundle/ConnectorBundle/Resources/translations/messages.en.yml, src/Pim/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev/jobs.yml
This PR adds XLSX job import of : 
- Categories
- association types
- attributes
- options
- families
| Micro Demo to the PO (Story only) | yes
=> PIM-5097: Add catalog import jobs

src/Pim/Bundle/EnrichBundle/Resources/config/batch_jobs.yml
Scalability and performance improvement
| Changelog updated |N
=> Use default batch size instead of 1000.

features/Context/Page/Attribute/Creation.php, features/Context/WebUser.php
Add the ability to set options label in behats
=> PIM-5752: add option label in behat

features/acl/enforce_acl_on_history.feature
=> PIM-5737: split behat

features/Context/Page/Base/Grid.php, features/Context/Page/Category/CategoryView.php, features/Context/WebUser.php
=> PIM-5737: rework behat methods

spec/Pim/Bundle/TransformBundle/Normalizer/Flat/ProductValueNormalizerSpec.php, src/Pim/Bundle/TransformBundle/Normalizer/Flat/ProductValueNormalizer.php
=> Quick export: Add unit column für empty metrics

CHANGELOG-1.5.md, composer.json
To make available last improvements made in this bundle cf https://github.com/akeneo/MeasureBundle/releases/tag/0.5.0
| Review and 2 GTM                  | - 
=> [DX] Upgrade the measure bundle from 0.4.1 to 0.5.0

CHANGELOG-1.5.md, src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/product_group.yml, src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/product_variant_group.yml, src/Pim/Bundle/FilterBundle/Filter/DatasourceFilterUtilityInterface.php, src/Pim/Bundle/FilterBundle/Filter/ProductFilterUtility.php
GTMed as https://github.com/akeneo/pim-community-dev/pull/4386
=> PIM-5762: Removed unused category filters on product datagrids

CHANGELOG-1.5.md, features/product/create_product_and_save_added_attributes.feature, spec/Pim/Component/Catalog/Comparator/Attribute/NumberComparatorSpec.php, src/Pim/Component/Catalog/Comparator/Attribute/NumberComparator.php
GTMed from https://github.com/akeneo/pim-community-dev/pull/4293
=> PIM-5666: Fix number comparator

src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filter/select2-choice-filter.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/field/multi-select-field.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/field/simple-select-field.js
GTMed from https://github.com/akeneo/pim-community-dev/pull/4325
=> PIM-5754: Add labels to simple and multi select fields

features/filter/group.feature, spec/Pim/Bundle/CatalogBundle/Doctrine/ORM/Filter/GroupsFilterSpec.php, src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Filter/GroupsFilter.php
GTMed from https://github.com/akeneo/pim-community-dev/pull/4393
=> PIM-5622: Fix NOT IN operator behavior for ORM groups filter

CHANGELOG-1.5.md, src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filter/metric-filter.js, src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filter/price-filter.js
GTMed from https://github.com/akeneo/pim-community-dev/pull/4280
=> PIM-5728: Fix metric and price datagrid filter

CHANGELOG-1.5.md, features/Context/FixturesContext.php, features/Context/catalog/apparel/attributes.yml, features/Context/catalog/footwear/attributes.yml, features/import/attribute/import_attributes.feature, spec/Pim/Component/Connector/ArrayConverter/Flat/AttributeStandardConverterSpec.php, src/Pim/Component/Connector/ArrayConverter/Flat/AttributeStandardConverter.php
GTM'ed on https://github.com/akeneo/pim-community-dev/pull/4413
=> PIM-5756: Fix empty min and max numbers on attributes import

src/Akeneo/Component/StorageUtils/README.md, src/Akeneo/Component/StorageUtils/composer.json
=> [DX] Prepare storage utils library subtree split

src/Akeneo/Bundle/BatchBundle/README.md, src/Akeneo/Bundle/BatchBundle/composer.json, src/Akeneo/Bundle/MeasureBundle/README.md, src/Akeneo/Bundle/MeasureBundle/composer.json, src/Akeneo/Bundle/StorageUtilsBundle/README.md, src/Akeneo/Bundle/StorageUtilsBundle/composer.json, src/Akeneo/Component/Batch/README.md, src/Akeneo/Component/StorageUtils/README.md
=> Subtree storage utils bundle

.gitignore, src/Akeneo/Bundle/BatchBundle/.travis.yml, src/Akeneo/Bundle/BatchBundle/README.md, src/Akeneo/Bundle/BatchBundle/composer.json, src/Akeneo/Bundle/BatchBundle/phpspec.yml, src/Akeneo/Bundle/MeasureBundle/README.md, src/Akeneo/Bundle/MeasureBundle/composer.json, src/Akeneo/Bundle/StorageUtilsBundle/.travis.yml, src/Akeneo/Bundle/StorageUtilsBundle/README.md, src/Akeneo/Bundle/StorageUtilsBundle/composer.json, src/Akeneo/Component/Batch/.travis.yml, src/Akeneo/Component/Batch/README.md, src/Akeneo/Component/Batch/composer.json, src/Akeneo/Component/StorageUtils/.travis.yml, src/Akeneo/Component/StorageUtils/README.md, src/Akeneo/Component/StorageUtils/composer.json
=> Configure phpspec and travis in readonly repositories (subtree split)

features/import/browse_imports.feature
This scenario can't work in EE.
=> Launch browse exports scenario only in CE

CHANGELOG-1.6.md, src/Pim/Bundle/CatalogBundle/Doctrine/Common/Saver/ProductSaver.php, src/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/Saver/ProductSaver.php, src/Pim/Bundle/CatalogBundle/Doctrine/ORM/CompletenessGenerator.php
=> PIM-5742: Improve product saver

.php_cd_transitional.php
=> TIP-395: exclude specs from coupling detector

src/Pim/Bundle/EnrichBundle/Resources/config/requirejs.yml, src/Pim/Bundle/EnrichBundle/Resources/public/js/fetcher/fetcher-registry.js, src/Pim/Bundle/UIBundle/Resources/views/Default/index.html.twig
We used to add a warm up of the pef cache. But this is not really efficient and not relevant since the scalability fixes.
=> TIP-412: remove warmup

features/Context/Page/Base/Form.php
=> TIP-408: Remove double click on label

CHANGELOG-1.5.md, src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid/action-launcher.js
GTM from https://github.com/akeneo/pim-community-dev/pull/4440
=> PIM-5655: Hide menu after action run

src/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/Filter/DateFilter.php, src/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/Filter/DateTimeFilter.php, src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Filter/DateFilter.php, src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Filter/DateTimeFilter.php, src/Pim/Bundle/CatalogBundle/spec/Doctrine/MongoDBODM/Filter/DateFilterSpec.php, src/Pim/Bundle/CatalogBundle/spec/Doctrine/MongoDBODM/Filter/DateTimeFilterSpec.php, src/Pim/Bundle/CatalogBundle/spec/Doctrine/ORM/Filter/DateFilterSpec.php, src/Pim/Bundle/CatalogBundle/spec/Doctrine/ORM/Filter/DateTimeFilterSpec.php
=> Fix behat & path specs

composer.json
This PR finalize #4360 because i forgot to remove the bundle from composer.
=> remove nelmio api-doc from composer

CHANGELOG-1.5.md, features/Context/FeatureContext.php, features/Context/FixturesContext.php, features/Context/catalog/apparel/attributes.yml, features/Context/catalog/footwear/attributes.yml, features/Pim/Behat/Context/AttributeValidationContext.php, features/Pim/Behat/Context/FixturesContext.php, features/filter/group.feature, features/import/attribute/import_attributes.feature, features/mass-action/validate/edit_common_attributes_permissions.feature, features/product/create_product_and_save_added_attributes.feature, spec/Akeneo/Component/Localization/Presenter/BooleanPresenterSpec.php, spec/Pim/Bundle/CatalogBundle/Doctrine/ORM/Filter/GroupsFilterSpec.php, spec/Pim/Component/Catalog/Comparator/Attribute/NumberComparatorSpec.php, spec/Pim/Component/Connector/ArrayConverter/Flat/AttributeStandardConverterSpec.php, src/Akeneo/Component/Localization/Presenter/BooleanPresenter.php, src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Filter/GroupsFilter.php, src/Pim/Bundle/CatalogBundle/Resources/config/localization/presenters.yml, src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filter/metric-filter.js, src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filter/price-filter.js, src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filter/select2-choice-filter.js, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/mass_product_edit.yml, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/field/multi-select-field.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/field/simple-select-field.js, src/Pim/Component/Catalog/Comparator/Attribute/NumberComparator.php, src/Pim/Component/Catalog/Localization/Presenter/PresenterRegistry.php, src/Pim/Component/Catalog/Localization/Presenter/PresenterRegistryInterface.php, src/Pim/Component/Connector/ArrayConverter/Flat/AttributeStandardConverter.php
Commit fixing
- PIM-5728
- PIM-5762
- PIM-5666
- PIM-5727
- PIM-5754
- PIM-5763
- PIM-5622
- PIM-5756
- PIM-5655
All of these are GTMed on their own PR's.
=> [Support-branch] PIM-5728, PIM-5762, PIM-5666, PIM-5738, PIM-5727, PIM-5754, PIM-5763, PIM-5622, PIM-5756

src/Pim/Bundle/CatalogBundle/Command/CreateProductCommand.php, src/Pim/Bundle/CatalogBundle/Command/UpdateProductCommand.php, src/Pim/Bundle/CatalogBundle/Command/ValidateProductCommand.php, src/Pim/Bundle/CatalogBundle/Resources/config/validators.yml, src/Pim/Bundle/EnrichBundle/Resources/config/controllers.yml
=> Remove old product validator

features/user/update_user_preferences.feature
Fixed by this PR:
- features/user/update_user_preferences.feature:29
=> TIP-405: Stabilize behats

src/Pim/Bundle/EnrichBundle/Controller/FileController.php
My apologies, I merged https://github.com/akeneo/pim-community-dev/pull/4476 because failing scenarii were OK on local, but I forgot to push my updates before merging :(
This PR fixes it
=> PIM-5710 (2) - Fix previous PR

src/Pim/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev/attributes.csv
Welcome to the 21th century
These tests fail on DCI, but not in local.
features/file_transformer/apply_transformations_on_images.feature:6
features/revert_version/attribute_types/metric.feature:11
features/product_draft/validation/validate_textarea_attributes.feature:43
features/product_draft/validation/validate_textarea_attributes.feature:37
features/product_asset/completeness.feature:34 …
=> Add PNG to allowed extension of icecat

src/Pim/Bundle/UIBundle/Resources/public/css/buttons.less, src/Pim/Bundle/UIBundle/Resources/public/css/less/variables.less, src/Pim/Bundle/UIBundle/Resources/public/css/notifications.less, src/Pim/Bundle/UIBundle/Resources/public/css/pim.less
Only CSS, need to be GTMed by @akeneo/ux-team
=> PIM-5611: Fix notification report button position

features/mass-action/mass_edit_variant_group_products.feature
=> PIM-5384: fix behat

features/mass-action/mass_edit_variant_group_products.feature
Currently, mass edit actions have a method `getBatchJobCode()` which returns the background job to execute. It has no sens to hard code it in the class & **it forces class override just to update this string** in Enterprise Edition.
This PR aims to inject this job code via the DI, as it's only configuration. This will ease integrators job & EE overrides (See EE pull requests, it cleans useless overrides).
=> PIM-5364: Inject the mass edit operation batch job code with the DI

features/family/browse_families.feature
Related to this change https://github.com/akeneo/pim-community-dev/blame/master/features/Context/catalog/footwear/families.csv
| Migration script                  | 
=> PIM-5730: fix the browse families scenario

features/import/browse_imports.feature
The scenario does not use the column operator
=> TIP-405: fix browse imports behat scenario

src/Pim/Component/Connector/spec/Job/JobParameters/ConstraintCollectionProvider/ProductCsvExportSpec.php, src/Pim/Component/Connector/spec/Job/JobParameters/ConstraintCollectionProvider/ProductCsvImportSpec.php, src/Pim/Component/Connector/spec/Job/JobParameters/ConstraintCollectionProvider/ProductXlsxExportSpec.php, src/Pim/Component/Connector/spec/Job/JobParameters/ConstraintCollectionProvider/SimpleCsvExportSpec.php, src/Pim/Component/Connector/spec/Job/JobParameters/ConstraintCollectionProvider/SimpleCsvImportSpec.php, src/Pim/Component/Connector/spec/Job/JobParameters/ConstraintCollectionProvider/SimpleXlsxExportSpec.php, src/Pim/Component/Connector/spec/Job/JobParameters/ConstraintCollectionProvider/SimpleXlsxImportSpec.php, src/Pim/Component/Connector/spec/Job/JobParameters/ConstraintCollectionProvider/SimpleYamlExportSpec.php, src/Pim/Component/Connector/spec/Job/JobParameters/ConstraintCollectionProvider/SimpleYamlImportSpec.php, src/Pim/Component/Connector/spec/Job/JobParameters/ConstraintCollectionProvider/VariantGroupCsvExportSpec.php, src/Pim/Component/Connector/spec/Job/JobParameters/ConstraintCollectionProvider/VariantGroupCsvImportSpec.php, src/Pim/Component/Connector/spec/Job/JobParameters/ConstraintCollectionProvider/VariantGroupXlsxExportSpec.php, src/Pim/Component/Connector/spec/Job/JobParameters/DefaultValuesProvider/ProductCsvExportSpec.php, src/Pim/Component/Connector/spec/Job/JobParameters/DefaultValuesProvider/ProductCsvImportSpec.php, src/Pim/Component/Connector/spec/Job/JobParameters/DefaultValuesProvider/ProductXlsxExportSpec.php, src/Pim/Component/Connector/spec/Job/JobParameters/DefaultValuesProvider/SimpleCsvExportSpec.php, src/Pim/Component/Connector/spec/Job/JobParameters/DefaultValuesProvider/SimpleCsvImportSpec.php, src/Pim/Component/Connector/spec/Job/JobParameters/DefaultValuesProvider/SimpleXlsxExportSpec.php, src/Pim/Component/Connector/spec/Job/JobParameters/DefaultValuesProvider/SimpleYamlExportSpec.php, src/Pim/Component/Connector/spec/Job/JobParameters/DefaultValuesProvider/SimpleYamlImportSpec.php, src/Pim/Component/Connector/spec/Job/JobParameters/DefaultValuesProvider/VariantGroupCsvExportSpec.php, src/Pim/Component/Connector/spec/Job/JobParameters/DefaultValuesProvider/VariantGroupCsvImportSpec.php, src/Pim/Component/Connector/spec/Job/JobParameters/DefaultValuesProvider/VariantGroupXlsxExportSpec.php
=> TIP-424: add job parameters specs for pim connector component

CHANGELOG-1.5.md, features/export/export_families.feature, src/Pim/Bundle/BaseConnectorBundle/Processor/Normalization/FamilyProcessor.php, src/Pim/Bundle/BaseConnectorBundle/Resources/config/processors.yml
When multiple locales are activated (for instance 8 locales), exported CSV for families is not correctly formatted: some label headers are missing, hence family data are note places in the right columns.
For instance, we can have something like that:
|code           |label-en_US    |label-fr_FR          |label-de_DE          |attributes          |attribute_as_label|requirements-ecommerce|requirements-mobile|requirements-print |         |    |         |   |         |
|---------------|---------------|---------------------|---------------------|--------------------|------------------|----------------------|-------------------|-------------------|---------|----|---------|---|---------|
|webcams        |Webcams        |Webcams              |Webcams              |sku, name …
=> [SLA] PIM-5811: Fix family export with multiple locales activated

features/category/remove_a_category.feature
Fix scenario in remove_a_category.feature
| Added Behats                      | fix one
=> TIP-36: Fix scenario in remove_a_category.feature

features/reference-data/variant-group/add_products.feature
Fix
vendor/akeneo/pim-community-dev/features/reference-data/variant-group/add_products.feature:30
=> TIP-36: Fix variant group save

CHANGELOG-1.4.md
=> PIM-5820:  Fix changelog

CHANGELOG-1.6.md, features/export/product-export-builder/export_products_families.feature, src/Pim/Bundle/BaseConnectorBundle/Resources/translations/messages.en.yml, src/Pim/Bundle/EnrichBundle/Form/Type/ChangeFamilyType.php, src/Pim/Bundle/EnrichBundle/Form/Type/SelectFamilyType.php, src/Pim/Bundle/EnrichBundle/Resources/config/forms.yml, src/Pim/Bundle/EnrichBundle/spec/Form/Type/ChangeFamilyTypeSpec.php, src/Pim/Bundle/EnrichBundle/spec/Form/Type/SelectFamilyTypeSpec.php, src/Pim/Bundle/ImportExportBundle/JobParameters/FormConfigurationProvider/ProductCsvExport.php, src/Pim/Bundle/ImportExportBundle/JobParameters/FormConfigurationProvider/ProductXlsxExport.php, src/Pim/Bundle/ImportExportBundle/Resources/config/job_parameters.yml, src/Pim/Bundle/ImportExportBundle/spec/JobParameters/FormConfigurationProvider/ProductCsvExportSpec.php, src/Pim/Bundle/ImportExportBundle/spec/JobParameters/FormConfigurationProvider/ProductXlsxExportSpec.php, src/Pim/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev/jobs.yml, src/Pim/Bundle/UIBundle/Resources/views/Form/pim-fields.html.twig, src/Pim/Component/Connector/Job/JobParameters/ConstraintCollectionProvider/ProductCsvExport.php, src/Pim/Component/Connector/Job/JobParameters/ConstraintCollectionProvider/ProductXlsxExport.php, src/Pim/Component/Connector/Job/JobParameters/DefaultValuesProvider/ProductCsvExport.php, src/Pim/Component/Connector/Job/JobParameters/DefaultValuesProvider/ProductXlsxExport.php, src/Pim/Component/Connector/Reader/ProductReader.php, src/Pim/Component/Connector/spec/Job/JobParameters/ConstraintCollectionProvider/ProductCsvExportSpec.php, src/Pim/Component/Connector/spec/Job/JobParameters/ConstraintCollectionProvider/ProductXlsxExportSpec.php, src/Pim/Component/Connector/spec/Job/JobParameters/DefaultValuesProvider/ProductCsvExportSpec.php, src/Pim/Component/Connector/spec/Job/JobParameters/DefaultValuesProvider/ProductXlsxExportSpec.php, src/Pim/Component/Connector/spec/Reader/ProductReaderSpec.php
=> PIM-5427: family filter for product export

features/export/product-export-builder/export_products_by_locales.feature
Reverts akeneo/pim-community-dev#4523
=> Revert "Fixed behat regressions"

CHANGELOG-1.4.md, spec/Pim/Bundle/TransformBundle/Normalizer/Structured/ProductNormalizerSpec.php, src/Pim/Bundle/TransformBundle/Normalizer/Structured/ProductNormalizer.php
Merge 1.4 fixes into 1.5
| Review and 2 GTM                  | Waiting
=> Merge 1.4 into 1.5

features/Context/DataGridContext.php
Spins the order of the grid check.
=> Spin Datagrid order

src/Pim/Component/Connector/spec/Reader/ProductReaderSpec.php
| Review and 2 GTM                  | :ballot_box_with_check: 
=> Fixed bad merge conflict that cause a fatal error with php7

features/Context/Page/Base/Grid.php, features/Context/WebUser.php
=> TIP-36: fix select row

features/Context/WebUser.php
Fix behat context that make CI fail in 1.5. This is a fix done in master. Cherry-pick was not possible as this fix is in a huge commit, part of it not compatible with 1.5.
| Review and 2 GTM                  | Waiting
| Micro Demo to the PO (Story only) | No
=> PIM-5777: Add spin to context "the field should contain"

src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/AttributeRequirementRepository.php, src/Pim/Bundle/CatalogBundle/Resources/config/repositories.yml, src/Pim/Bundle/CatalogBundle/Resources/config/updaters.yml, src/Pim/Component/Catalog/Repository/AttributeRequirementRepositoryInterface.php, src/Pim/Component/Catalog/Updater/FamilyUpdater.php
This PR fixes a typo in the attribute requirement repository definition of service.
=> Fix name of attribute requirement repository + fix requirements management

composer.json
Reverts akeneo/pim-community-dev#4556
=> Revert "Remove measure bundle from composer"

features/filter/completeness.feature, src/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/Filter/CompletenessFilter.php, src/Pim/Bundle/CatalogBundle/spec/Doctrine/MongoDBODM/Filter/CompletenessFilterSpec.php
| Review and 2 GTM                  | :ballot_box_with_check: 
=> PIM-5426: Fix completeness filter in product export for mongodb

features/filter/completeness.feature, src/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/Filter/CompletenessFilter.php, src/Pim/Bundle/CatalogBundle/spec/Doctrine/MongoDBODM/Filter/CompletenessFilterSpec.php
Reverts akeneo/pim-community-dev#4563
=> Revert "PIM-5426: Fix completeness filter in product export for mongodb"

features/enrich/variant-group/add_products/add_products_history_updated_with_context.feature, features/enrich/variant-group/add_products/add_products_history_updated_without_context.feature
These 2 scenario are ones of the longers in the DCI, because it creates 3 products via UI.
I replaced it with an import creation to be faster (and clearer btw)
Before: 5m34.305s and 2m12.711s
After: 1m15.102s and 1m13.562s
=> Change the product creation by UI and set it with import

src/Pim/Component/Catalog/Updater/FamilyUpdater.php
Fix parameter order in FamilyUpdater
Also linked to https://github.com/akeneo/pim-community-dev/pull/4546
=> Fix parameter order in FamilyUpdater

CHANGELOG-1.5.md
Fix wrong changelog after merging fix for PIM-5711.
| Review and 2 GTM                  | N/A
=> Fix CHANGELOG

features/Pim/Behat/Decorator/Field/Select2Decorator.php
when we want to click on the DOM element it has disappeared. It happens sometimes.
So I moved it in the spin to relaunch all the process.
=> TIP-36: fix MultiselectDecorator

CHANGELOG-1.6.md, src/Akeneo/Bundle/BatchBundle/Command/PurgeJobExecutionCommand.php, src/Akeneo/Bundle/BatchBundle/Job/DoctrineJobRepository.php, src/Akeneo/Bundle/BatchBundle/Resources/config/removers.yml, src/Akeneo/Component/Batch/Job/JobRepositoryInterface.php
Add command for purge job executions
| Tech Doc                          | Y
=> PIM-5664 : Add command for purge job executions

features/product/remove_product.feature
Just replace iShouldSee by iShouldSeeTheText.
=> Fix behat iShouldSeeTheText

src/Pim/Bundle/EnrichBundle/Resources/views/JobExecution/show.html.twig, src/Pim/Bundle/UIBundle/Resources/public/css/buttons.less
=> Fix buttons style on job execution details

src/Pim/Bundle/ConnectorBundle/Resources/translations/messages.en.yml
The Crowdin users just noted that this date does not exist :trollface: 
https://crowdin.com/translate/akeneo/111/en-pt#4125
=> Fix translation date not existing

features/localization/variant-group/edit_variant_group_attribute_value.feature
=> Fix translations (Attributes)

CHANGELOG-1.5.md, features/export/export_products_with_media.feature, spec/Pim/Component/Connector/Writer/File/MediaExporterPathGeneratorSpec.php, src/Pim/Component/Connector/Writer/File/MediaExporterPathGenerator.php
| Specs             | :white_check_mark: 
| Changelog updated | :white_check_mark:
=> PIM-5844: Fix export with medias when identifier contains slash

CHANGELOG-1.5.md, features/Context/DataGridContext.php, features/export/browse_export_executions.feature, src/Akeneo/Component/Localization/Localizer/LocalizerInterface.php, src/Pim/Bundle/DataGridBundle/Resources/public/css/filter.less, src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filter/date-filter.js, src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filter/datetime-filter.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/field/date-field.js, src/Pim/Bundle/EnrichBundle/Resources/views/Attribute/_js-handler.html.twig, src/Pim/Bundle/EnrichBundle/Resources/views/VariantGroup/_js-handler.html.twig, src/Pim/Bundle/LocalizationBundle/Controller/FormatController.php, src/Pim/Bundle/UIBundle/Resources/public/js/pim-datepicker.js, src/Pim/Bundle/UserBundle/Resources/views/User/update.html.twig
- Datepicker was broken when time was activated
- Increase width of input fields
- Adapt hours format (AM/PM or 24h) according to locale
| Specs             | Not needed
| Changelog updated | :white_check_mark:
=> PIM-4346: Fix datetimepicker on grid filters

CHANGELOG-1.5.md, features/product/classify_product.feature, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/categories.js
This PR add the display of the message "There are unsaved changes." when a user changes a product categories.
=> PIM-5851: Display product state change when changing categories

features/enrich/variant-group/display_variant_history.feature, src/Pim/Bundle/CatalogBundle/Resources/config/updaters.yml, src/Pim/Component/Catalog/Updater/Remover/AbstractAttributeRemover.php, src/Pim/Component/Catalog/Updater/Remover/MultiSelectAttributeRemover.php, src/Pim/Component/Catalog/spec/Updater/Remover/MultiSelectAttributeRemoverSpec.php
=> PIM-5665 : Add Multi Select Attribute Remover

features/Context/Page/Role/Edit.php, features/Pim/Behat/Context/Domain/System/PermissionsContext.php, features/Pim/Behat/Decorator/Permission/PermissionDecorator.php
This PR clean the Permission behat cycle (Context / Decorator / Page) to fit exactly what we have to do and have a real good example.
=> [TR] Clean Behat : Fix Permission decorator context and page

features/Context/DataGridContext.php, src/Pim/Bundle/DataGridBundle/Controller/ProductExportController.php, src/Pim/Bundle/EnrichBundle/Resources/translations/messages.en.yml
=> PIM-5600: Quick export add missing label

features/export/product-export-builder/export_products_by_specific_date.feature
=> Fix failing behat

src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/filters.yml, src/Pim/Bundle/EnrichBundle/Resources/public/js/filter/product/completeness.js, src/Pim/Bundle/EnrichBundle/Resources/public/templates/filter/product/completeness.html, src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml, src/Pim/Bundle/ImportExportBundle/JobParameters/FormConfigurationProvider/ProductCsvExport.php
=> PIM-5853: Completeness filter UI

CHANGELOG-1.4.md, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/panel/history.js
Prevents the history panel from rendering additional times.
=> PIM-5389: Fix history rendering

src/Pim/Bundle/CatalogBundle/Resources/config/doctrine/AttributeGroup.orm.yml
Fix updated field of AttributeGroup entity
=> Fix updated field of AttibuteGroup entity

src/Pim/Bundle/CatalogBundle/EventSubscriber/MongoDBODM/UpdateNormalizedProductDataSubscriber.php
This PR fixes the name of a class property.
master: https://github.com/akeneo/pim-community-dev/pull/4635
1.5: https://github.com/akeneo/pim-community-dev/pull/4634
=> Fix variable name [1.4]

CHANGELOG-1.6.md, features/Pim/Behat/Context/Domain/Spread/ExportProfilesContext.php, features/export/configure_export_products_with_media.feature, src/Pim/Bundle/ConnectorBundle/Resources/translations/messages.en.yml, src/Pim/Bundle/ImportExportBundle/JobParameters/FormConfigurationProvider/ProductCsvExport.php, src/Pim/Bundle/ImportExportBundle/JobParameters/FormConfigurationProvider/ProductXlsxExport.php, src/Pim/Bundle/ImportExportBundle/spec/JobParameters/FormConfigurationProvider/ProductCsvExportSpec.php, src/Pim/Bundle/ImportExportBundle/spec/JobParameters/FormConfigurationProvider/ProductXlsxExportSpec.php, src/Pim/Component/Connector/Job/JobParameters/ConstraintCollectionProvider/ProductCsvExport.php, src/Pim/Component/Connector/Job/JobParameters/ConstraintCollectionProvider/ProductXlsxExport.php, src/Pim/Component/Connector/Job/JobParameters/DefaultValuesProvider/ProductCsvExport.php, src/Pim/Component/Connector/Job/JobParameters/DefaultValuesProvider/ProductXlsxExport.php, src/Pim/Component/Connector/Writer/File/CsvProductWriter.php, src/Pim/Component/Connector/Writer/File/XlsxProductWriter.php, src/Pim/Component/Connector/spec/Job/JobParameters/DefaultValuesProvider/ProductCsvExportSpec.php, src/Pim/Component/Connector/spec/Job/JobParameters/DefaultValuesProvider/ProductXlsxExportSpec.php, src/Pim/Component/Connector/spec/Writer/File/CsvProductWriterSpec.php, src/Pim/Component/Connector/spec/Writer/File/XlsxProductWriterSpec.php
| Tech Doc                          | N
=> PIM-5110: Add product export configuration to customize product media export policy

CHANGELOG-1.6.md, src/Akeneo/Component/Buffer/ArrayBuffer.php, src/Akeneo/Component/Buffer/BufferInterface.php, src/Akeneo/Component/Buffer/JSONFileBuffer.php, src/Pim/Bundle/ConnectorBundle/Resources/config/factories.yml, src/Pim/Bundle/ConnectorBundle/Resources/config/writers.yml, src/Pim/Component/Connector/Writer/File/Csv/ProductWriter.php, src/Pim/Component/Connector/Writer/File/Csv/VariantGroupWriter.php, src/Pim/Component/Connector/Writer/File/Csv/Writer.php, src/Pim/Component/Connector/Writer/File/FlatItemBuffer.php, src/Pim/Component/Connector/Writer/File/FlatItemBufferFlusher.php, src/Pim/Component/Connector/Writer/File/Xlsx/ProductWriter.php, src/Pim/Component/Connector/Writer/File/Xlsx/VariantGroupWriter.php, src/Pim/Component/Connector/Writer/File/Xlsx/Writer.php, src/Pim/Component/Connector/spec/Writer/File/Csv/ProductWriterSpec.php, src/Pim/Component/Connector/spec/Writer/File/Csv/VariantGroupWriterSpec.php, src/Pim/Component/Connector/spec/Writer/File/Csv/WriterSpec.php, src/Pim/Component/Connector/spec/Writer/File/FlatItemBufferFlusherSpec.php, src/Pim/Component/Connector/spec/Writer/File/FlatItemBufferSpec.php, src/Pim/Component/Connector/spec/Writer/File/Xlsx/ProductWriterSpec.php, src/Pim/Component/Connector/spec/Writer/File/Xlsx/VariantGroupWriterSpec.php, src/Pim/Component/Connector/spec/Writer/File/Xlsx/WriterSpec.php
FlatItemBuffer now extends JSONFileBuffer and is declared as a real factory
=> TIP-521: Clean FlatItemBuffer

features/Context/Page/Base/Grid.php, features/Pim/Behat/Decorator/Export/Filter/Select2Decorator.php, features/export/edit_an_export.feature, features/export/product-export-builder/export_products_by_specific_date.feature, src/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/Filter/DateTimeFilter.php, src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Filter/DateTimeFilter.php, src/Pim/Bundle/CatalogBundle/spec/Doctrine/MongoDBODM/Filter/DateTimeFilterSpec.php, src/Pim/Bundle/CatalogBundle/spec/Doctrine/ORM/Filter/DateTimeFilterSpec.php, src/Pim/Bundle/ImportExportBundle/spec/JobParameters/FormConfigurationProvider/ProductCsvExportSpec.php, src/Pim/Bundle/ImportExportBundle/spec/JobParameters/FormConfigurationProvider/ProductXlsxExportSpec.php, src/Pim/Component/Connector/spec/Job/JobParameters/DefaultValuesProvider/ProductCsvExportSpec.php
=> Pim 5853 behat

src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/product_export_edit.yml, src/Pim/Bundle/EnrichBundle/Resources/config/requirejs.yml, src/Pim/Bundle/EnrichBundle/Resources/public/js/export/product/edit/content/data.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/export/product/edit/content/data/add-filter.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/attributes/add-attribute.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/manager/attribute-manager.js, src/Pim/Bundle/EnrichBundle/Resources/public/templates/export/product/edit/content/data.html
This PR reworks the "add filter" done in the POC to be usable.
=> PIM-5635: Rework add filter module

README.md
Just correct links into the README (including a dead link and two old http links)
=> [DOC] Correct a dead link

features/Context/Page/Base/Grid.php, features/Context/Page/Base/ProductEditForm.php, features/Context/Page/Export/Edit.php, features/Pim/Behat/Decorator/Common/AddAttributeDecorator.php, features/Pim/Behat/Decorator/Export/Filter/MetricDecorator.php, features/export/product-export-builder/export_products_by_metric.feature, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/filters.yml, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/product_export_edit.yml, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/product_export_show.yml, src/Pim/Bundle/EnrichBundle/Resources/config/requirejs.yml, src/Pim/Bundle/EnrichBundle/Resources/public/js/filter/attribute/metric.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/filter/filter.js, src/Pim/Bundle/EnrichBundle/Resources/public/templates/filter/attribute/metric.html, src/Pim/Bundle/EnrichBundle/Resources/public/templates/filter/filter.html, src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml, src/Pim/Bundle/UIBundle/Resources/public/css/pim.less
Add the metric filter on the product export builder. We still need the add attribute story to be able to merge it
=> PIM-5853: add metric filter

composer.json, phpspec.yml.dist
=> TIP-298: update dep to phpspec 3.0.0

.php_cs.local.php, features/Context/Page/Base/Grid.php, features/Pim/Behat/Decorator/Export/Filter/PriceDecorator.php, features/export/product-export-builder/export_products_by_price_collections.feature, src/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/Filter/PriceFilter.php, src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Filter/PriceFilter.php, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/filters.yml, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/product_export_edit.yml, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/product_export_show.yml, src/Pim/Bundle/EnrichBundle/Resources/config/requirejs.yml, src/Pim/Bundle/EnrichBundle/Resources/public/js/filter/attribute/price-collection.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/filter/filter.js, src/Pim/Bundle/EnrichBundle/Resources/public/templates/filter/attribute/price-collection.html, src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml, src/Pim/Bundle/UIBundle/Resources/public/css/pim.less
Adds a price filter for price attribute type and use it in the product export builder.
=> PIM-5635: Add price filter in product export builder

features/Context/Page/Base/Grid.php, features/Pim/Behat/Decorator/Export/Filter/Select2Decorator.php, features/export/product-export-builder/export_products_by_multiselect_reference_data.feature, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/filters.yml, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/product_export_edit.yml, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/product_export_show.yml, src/Pim/Bundle/EnrichBundle/Resources/config/requirejs.yml, src/Pim/Bundle/EnrichBundle/Resources/public/js/filter/attribute/multiselect-reference-data.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/filter/filter.js, src/Pim/Bundle/EnrichBundle/Resources/public/templates/filter/attribute/multiselect-reference-data.html, src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml, src/Pim/Bundle/UIBundle/Resources/public/css/pim.less
Add a multiselect of reference-data type field in the product export builder.
| Migration script                  | 
| Tech Doc                          | 
Pair coded with @SamirBoulil
=> PIM-5635: Add multi select ref data filter

CHANGELOG-1.6.md, features/export/export_products.feature, features/export/xlsx/export_products.feature, src/Pim/Bundle/BaseConnectorBundle/Processor/ProductToFlatArrayProcessor.php, src/Pim/Bundle/BaseConnectorBundle/Resources/config/processors.yml, src/Pim/Bundle/BaseConnectorBundle/spec/Processor/ProductToFlatArrayProcessorSpec.php, src/Pim/Bundle/EnrichBundle/Connector/Processor/QuickExport/ProductToFlatArrayProcessor.php, src/Pim/Bundle/EnrichBundle/Resources/config/connector/processors.yml, src/Pim/Bundle/EnrichBundle/spec/Connector/Processor/QuickExport/ProductToFlatArrayProcessorSpec.php, src/Pim/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev/jobs.yml
Add filter attributes in ProductFlatArrayProcessor for filtering product attributes you want to export, only back office part at the moment.
=> PIM-5109: As Peter, I would like to choose the products attributes to export

src/Pim/Bundle/EnrichBundle/Doctrine/ORM/Repository/AttributeRepository.php, src/Pim/Bundle/EnrichBundle/Doctrine/ORM/Repository/CategoryRepository.php, src/Pim/Bundle/EnrichBundle/Form/DataTransformer/EntityToIdentifierTransformer.php, src/Pim/Bundle/EnrichBundle/Form/Type/LightEntityType.php, src/Pim/Bundle/EnrichBundle/Form/Type/ObjectIdentifierType.php, src/Pim/Bundle/EnrichBundle/Form/Type/ProductGridFilterChoiceType.php, src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/channel.yml, src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/family.yml, src/Pim/Bundle/EnrichBundle/Resources/config/form_types.yml, src/Pim/Bundle/EnrichBundle/spec/Doctrine/ORM/Repository/AttributeRepositorySpec.php, src/Pim/Bundle/EnrichBundle/spec/Form/DataTransformer/EntityToIdentifierTransformerSpec.php, src/Pim/Bundle/EnrichBundle/spec/Form/Type/ProductGridFilterChoiceTypeSpec.php, src/Pim/Bundle/UserBundle/Form/Type/UserType.php
| Micro Demo to the PO (Story only) | no 
=> PIM-5434: When no access to any category, I can't edit my profile

src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/product_export_show.yml, src/Pim/Bundle/EnrichBundle/Resources/public/js/export/product/edit/content/data.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/filter/filter.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/edit-form.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/form/registry.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form.js
Before this fix when you saved a profile and edit it again, all filters used to disappear on the first modification.
Also, small fix for the boolean filter conf in show mode.
=> PIM-5853: Fix filters rendering

src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid/action/configure-columns-action.js, src/Pim/Bundle/DataGridBundle/Resources/public/templates/configure-columns-action.html, src/Pim/Bundle/DataGridBundle/Resources/translations/jsmessages.en.yml, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/product_export_edit.yml, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/product_export_show.yml, src/Pim/Bundle/EnrichBundle/Resources/config/requirejs.yml, src/Pim/Bundle/EnrichBundle/Resources/public/js/common/column-list-view.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/export/product/edit/content/structure/attributes-selector.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/export/product/edit/content/structure/attributes.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/export/product/edit/content/structure/scope.js, src/Pim/Bundle/EnrichBundle/Resources/public/templates/export/product/edit/content/structure/attributes.html, src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml, src/Pim/Bundle/UIBundle/Resources/public/css/pim.less
First popin poc. No tests for now because the backend is not developped
=> PIM-5109: first popin POC

features/Context/Page/Base/Grid.php, features/Pim/Behat/Decorator/Export/Filter/DateDecorator.php, features/Pim/Behat/Decorator/Export/Filter/NumberDecorator.php, features/export/product-export-builder/export_product_by_attribute_date.feature, features/export/product-export-builder/export_product_by_attribute_number.feature, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/filters.yml, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/product_export_edit.yml, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/product_export_show.yml, src/Pim/Bundle/EnrichBundle/Resources/config/requirejs.yml, src/Pim/Bundle/EnrichBundle/Resources/public/js/filter/attribute/date.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/filter/attribute/number.js, src/Pim/Bundle/EnrichBundle/Resources/public/templates/filter/attribute/date.html, src/Pim/Bundle/EnrichBundle/Resources/public/templates/filter/attribute/number.html, src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml
=> PIM-5853: Add date attribute type filter

UPGRADE-1.6.md, src/Pim/Bundle/CatalogBundle/Command/MongoDBIndexCreatorCommand.php, src/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/IndexCreator.php, src/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/IndexPurger.php, src/Pim/Bundle/CatalogBundle/spec/Doctrine/MongoDBODM/IndexCreatorSpec.php, src/Pim/Bundle/CatalogBundle/spec/Doctrine/MongoDBODM/IndexPurgerSpec.php
To fix the following issue with PHP7 and MongoDB 2.6 enforcing several limitations on indexes.
`̀``
[2016-07-26 10:03:20] batch.ERROR: Encountered an error executing the step: insertDocument :: caused by :: 17280 Btree::insert: key too large to index, failing pim_ma_pcdm.pim_catalog_product.$normalizedData.description-en_US-print_1 1490 { : "<b>Streamlined Reliability</b>\nA smart, reliable option for bringing duplex printing, copying, scanning and high-speed faxing into one machine, with ..." }  
An error occurred during the fixtures execution.
Error #17280 in class MongoCursorException: insertDocument :: caused by :: 17280 Btree::insert: key too large to index, failing pim_ma_pcdm.pim_catalog_product.$normalizedData.description-en_US-print_1 1490 { : "<b>Streamlined Reliability</b>\nA …
=> TIP-307: Fix issues with PHP 7 and MongoDB 2.6

src/Pim/Bundle/UIBundle/Resources/public/css/pim.less
This PR fixes the rendering of number and date filter in product export builder.
=> PIM-5635: Fix LESS style for product export builder

CHANGELOG-1.6.md, features/Context/Page/Export/Edit.php, features/Pim/Behat/Context/Domain/Spread/ExportBuilderContext.php, features/Pim/Behat/Decorator/Common/AttributeSelectorDecorator.php, features/Pim/Behat/Decorator/Export/Structure/AttributesDecorator.php, features/export/product-export-builder/export_products_with_attributes.feature, src/Pim/Bundle/BaseConnectorBundle/Processor/ProductToFlatArrayProcessor.php, src/Pim/Bundle/EnrichBundle/Controller/Rest/AttributeController.php, src/Pim/Bundle/EnrichBundle/Doctrine/ORM/Repository/AttributeSearchableRepository.php, src/Pim/Bundle/EnrichBundle/Resources/config/requirejs.yml, src/Pim/Bundle/EnrichBundle/Resources/public/js/export/product/edit/content/structure.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/export/product/edit/content/structure/attributes-selector.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/export/product/edit/content/structure/attributes.js, src/Pim/Bundle/EnrichBundle/Resources/public/templates/export/product/edit/content/structure/attribute-list.html, src/Pim/Bundle/EnrichBundle/Resources/public/templates/export/product/edit/content/structure/attributes-selector.html, src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml, src/Pim/Bundle/UIBundle/Resources/public/css/pim.less
New scallable popin for attribute selection
=> Pim 5109 new

features/export/product-export-builder/export_products_by_metrics.feature, src/Pim/Bundle/EnrichBundle/Resources/public/js/export/product/edit/content/structure/attributes-selector.js, src/Pim/Bundle/EnrichBundle/Resources/public/templates/export/product/edit/content/structure/attribute-list.html, src/Pim/Bundle/EnrichBundle/Resources/public/templates/export/product/edit/content/structure/attributes-selector.html, src/Pim/Bundle/EnrichBundle/Resources/public/templates/filter/attribute/metric.html, src/Pim/Bundle/UIBundle/Resources/public/css/pim.less
=> PIM-5109: add trash icons

src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/product_edit.yml, src/Pim/Bundle/EnrichBundle/Resources/views/AssociationType/edit.html.twig, src/Pim/Bundle/EnrichBundle/Resources/views/Attribute/form.html.twig, src/Pim/Bundle/EnrichBundle/Resources/views/CategoryTree/form.html.twig, src/Pim/Bundle/EnrichBundle/Resources/views/Channel/edit.html.twig, src/Pim/Bundle/EnrichBundle/Resources/views/Family/edit.html.twig, src/Pim/Bundle/EnrichBundle/Resources/views/Group/_group.html.twig, src/Pim/Bundle/EnrichBundle/Resources/views/GroupType/edit.html.twig, src/Pim/Bundle/EnrichBundle/Resources/views/JobExecution/show.html.twig, src/Pim/Bundle/ImportExportBundle/Resources/views/JobExecution/show.html.twig, src/Pim/Bundle/ImportExportBundle/Resources/views/JobProfile/_show_headers.html.twig, src/Pim/Bundle/ImportExportBundle/Resources/views/JobProfile/edit.html.twig, src/Pim/Bundle/UIBundle/Resources/public/css/buttons.less, src/Pim/Bundle/UIBundle/Resources/public/css/form.less, src/Pim/Bundle/UIBundle/Resources/public/css/less/oro.less, src/Pim/Bundle/UIBundle/Resources/public/css/pim.less, src/Pim/Bundle/UIBundle/Resources/public/css/tabnav.less, src/Pim/Bundle/UIBundle/Resources/views/Default/page_elements.html.twig, src/Pim/Bundle/UserBundle/Resources/views/Role/update.html.twig, src/Pim/Bundle/UserBundle/Resources/views/User/update.html.twig
=> PIM-5900: Move backtogrid button and enable button to the title div, and fix css

features/user/update_user_preferences.feature, src/Pim/Bundle/DashboardBundle/Resources/public/css/dashboard.less, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/create/form.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/variant-group/form/properties/general.js, src/Pim/Bundle/EnrichBundle/Resources/public/templates/export/product/edit/content/structure/locales.html, src/Pim/Bundle/EnrichBundle/Resources/public/templates/export/product/edit/content/structure/scope.html, src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/create-popin.html, src/Pim/Bundle/EnrichBundle/Resources/public/templates/variant-group/tab/properties/general.html, src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml, src/Pim/Bundle/UIBundle/Resources/public/css/less/oro.less, src/Pim/Bundle/UIBundle/Resources/public/css/notifications.less, src/Pim/Bundle/UIBundle/Resources/translations/messages.en.yml, src/Pim/Bundle/UIBundle/Resources/views/Form/pim-fields.html.twig
=> PIM-5900: Change red star to 'required' for form labels

src/Pim/Bundle/EnrichBundle/Resources/public/templates/form/form-tabs.html, src/Pim/Bundle/EnrichBundle/Resources/public/templates/variant-group/tab/properties/translation.html, src/Pim/Bundle/ImportExportBundle/Resources/views/JobProfile/Tab/history.html.twig, src/Pim/Bundle/ImportExportBundle/Resources/views/JobProfile/Tab/job_content.html.twig, src/Pim/Bundle/ImportExportBundle/Resources/views/JobProfile/Tab/property_edit.html.twig, src/Pim/Bundle/ImportExportBundle/Resources/views/JobProfile/Tab/property_show.html.twig, src/Pim/Bundle/UIBundle/Resources/public/css/buttons.less, src/Pim/Bundle/UIBundle/Resources/public/css/form.less, src/Pim/Bundle/UIBundle/Resources/public/css/less/oro.less, src/Pim/Bundle/UIBundle/Resources/public/css/less/variables.less, src/Pim/Bundle/UIBundle/Resources/public/css/pim.less, src/Pim/Bundle/UIBundle/Resources/public/css/select2.less, src/Pim/Bundle/UIBundle/Resources/public/lib/bootstrap/css/bootstrap.less, src/Pim/Bundle/UIBundle/Resources/views/Form/pim-fields.html.twig
The goal is to have only one design for every form in the application:
- labels under inputs
- same font size everywhere
- same input width
- etc...
=> Pim 5900: Unify forms

src/Pim/Bundle/EnrichBundle/Controller/ProductController.php
This PR fixes a typo in the PHPDoc block
=> Fixed typo in ProductController

CHANGELOG-1.5.md, features/product/filtering/filter_products_per_text_fields.feature, src/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/Filter/StringFilter.php, src/Pim/Bundle/FilterBundle/Filter/ProductValue/StringFilter.php
Duplicate of https://github.com/akeneo/pim-community-dev/pull/4710 for the 1.5
=> PIM-5767: Issue with filter "in list" when SKU contains dashes (-)

src/Akeneo/Bundle/StorageUtilsBundle/Doctrine/Common/Saver/BaseSaver.php, src/Akeneo/Bundle/StorageUtilsBundle/spec/Doctrine/Common/Saver/BaseSaverSpec.php, src/Pim/Bundle/CatalogBundle/Doctrine/Common/Saver/AttributeSaver.php, src/Pim/Bundle/CatalogBundle/Doctrine/Common/Saver/FamilySaver.php, src/Pim/Bundle/CatalogBundle/Doctrine/Common/Saver/GroupSaver.php, src/Pim/Bundle/CatalogBundle/Doctrine/Common/Saver/ProductSaver.php, src/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/Saver/ProductSaver.php, src/Pim/Bundle/CatalogBundle/spec/Doctrine/Common/Saver/FamilySaverSpec.php, src/Pim/Bundle/CatalogBundle/spec/Doctrine/Common/Saver/GroupSaverSpec.php, src/Pim/Bundle/CatalogBundle/spec/Doctrine/MongoDBODM/Saver/ProductSaverSpec.php
Cf https://github.com/akeneo/pim-community-dev/pull/4823 
Specs added here + CI is running
=> Dispatch POST_SAVE event only after flush (+specs)

src/Pim/Component/Catalog/Model/AbstractAttribute.php
| Migration scripts                 | N
| Tech Doc                          | N
What does this Pull Request do?
Originally it was comparing if it's scopable instead localizable to retrieve the required validation depending on.
=> Akeneo isLocalizable rule fix

features/Pim/Behat/Context/Domain/Collect/ImportProfilesContext.php, src/Pim/Bundle/EnrichBundle/Resources/translations/messages.en.yml, src/Pim/Bundle/ImportExportBundle/Resources/views/JobProfile/_buttons.html.twig, src/Pim/Bundle/ImportExportBundle/Resources/views/JobProfile/_show_headers.html.twig, src/Pim/Bundle/UIBundle/Resources/public/css/form.less, src/Pim/Bundle/UIBundle/Resources/public/css/less/variables.less, src/Pim/Bundle/UIBundle/Resources/public/js/pim-fileinput.js, src/Pim/Bundle/UIBundle/Resources/views/Form/pim-fields.html.twig
This PR unify dropzones everywhere on the PIM.
| Micro Demo to the PO (Story only) | TODO
=> Pim 5920 dropzones

src/Pim/Bundle/UIBundle/Resources/public/css/pim.less, src/Pim/Bundle/UIBundle/Resources/public/css/signin.less, src/Pim/Bundle/UserBundle/Resources/views/Security/login.html.twig
It fixes bad display of the buttons, using a flex solution for the inputs.
=> PIM-5900: Fix login CSS for big buttons

src/Pim/Bundle/UIBundle/Resources/public/css/form.less, src/Pim/Bundle/UIBundle/Resources/public/css/less/oro.less, src/Pim/Bundle/UserBundle/Resources/views/User/update.html.twig
Add a cancel button, put the customer info into the very left.
=> PIM-5913: Unify user show and user edit

features/enrich/variant-group/edit_variant_group_attribute_value.feature, src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/state.js, src/Pim/Bundle/UIBundle/Resources/public/css/buttons.less
Fixes a weird translation on the "are you sure" popin
=> PIM-5900: Fix translation on popin state

UPGRADE-1.6.md
This PR re-organize a bit the upgrade doc, moving in a first section the "Migrate your standard project" and move all the stuff related to update custom code in a second section "Migrate your custom code".
This PR also add cases encountered during migrations.
=> PIM-5788: add sections in upgrade.md

UPGRADE-1.6.md
Complete the upgrade.md doc (more to come)
=> PIM-5788: add details about import / export migrations

UPGRADE-1.6.md
=> PIM-5788: add details about mass edit migrations

UPGRADE-1.6.md
=> PIM-5788: add details for Enterprise Edition migration

.phpspec/class.tpl.dist
=> Update default phpspec template.

CHANGELOG-1.6.md
=> TIP-535: re-organize changelog

CHANGELOG-1.6.md, src/Pim/Bundle/CatalogBundle/Version.php
=> PIM-5790: prepare 1.6.0-alpha2 release

CHANGELOG-1.5.md, src/Pim/Bundle/CatalogBundle/Command/CleanProductValueDuplicationsCommand.php
This new command is used to clean duplicated product values. For more information see the class description.
=> Add a duplicated product values cleaning command

src/Pim/Bundle/EnrichBundle/Resources/public/js/pim-popinform.js
This PR fixes an issue with popinform js widget, which has some bugs if used multiple times on the same page.
=> Fixed issue with pim-popinform js code

CHANGELOG-1.6.md
Changelog update for https://github.com/akeneo/pim-community-dev/pull/4867
=> #4879: Update changelog

composer.json, features/channel/edit_channel.feature, features/localization/product/datagrid/display_localized_numbers.feature
=> Remove measure-bundle from composer (this bundle is in our main repo since 1.6)

src/Pim/Component/Catalog/Model/ProductInterface.php
No description needed i think ;)
| Added Specs                       |no
| Changelog updated                 |no
=> Fix PHPdoc for better typehinting

.gitignore, src/Akeneo/Bundle/BatchBundle/.travis.yml, src/Akeneo/Bundle/BatchBundle/composer.json, src/Akeneo/Bundle/MeasureBundle/.travis.yml, src/Akeneo/Bundle/MeasureBundle/composer.json, src/Akeneo/Bundle/MeasureBundle/phpspec.yml, src/Akeneo/Bundle/StorageUtilsBundle/.travis.yml, src/Akeneo/Bundle/StorageUtilsBundle/composer.json, src/Akeneo/Bundle/StorageUtilsBundle/phpspec.yml, src/Akeneo/Bundle/StorageUtilsBundle/spec/Doctrine/Common/Remover/BaseRemoverSpec.php, src/Akeneo/Bundle/StorageUtilsBundle/spec/Doctrine/Common/Saver/BaseSaverSpec.php, src/Akeneo/Component/Batch/.travis.yml, src/Akeneo/Component/Batch/composer.json, src/Akeneo/Component/Batch/phpspec.yml, src/Akeneo/Component/StorageUtils/.travis.yml, src/Akeneo/Component/StorageUtils/composer.json, src/Akeneo/Component/StorageUtils/phpspec.yml
Fix experimental subtree split of few component (batch, storage utils, related bundles + measure bundle)
=> Fix subtree composer.json and travis

CONTRIBUTING.md
To avoid to duplicate data between doc and main repo
=> Add a link to the contributing guide

src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml
=> Change quick-export labels

features/Context/Page/Base/Grid.php, src/Pim/Bundle/EnrichBundle/Controller/Rest/FormExtensionController.php, src/Pim/Bundle/EnrichBundle/DependencyInjection/Compiler/RegisterFormExtensionsPass.php, src/Pim/Bundle/EnrichBundle/Normalizer/AttributeNormalizer.php, src/Pim/Bundle/EnrichBundle/PimEnrichBundle.php, src/Pim/Bundle/EnrichBundle/Provider/Filter/BaseFilterProvider.php, src/Pim/Bundle/EnrichBundle/Provider/Filter/FilterChainedProvider.php, src/Pim/Bundle/EnrichBundle/Provider/Filter/FilterProviderInterface.php, src/Pim/Bundle/EnrichBundle/Provider/FormExtensionProvider.php, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/filters.yml, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/product_export_edit.yml, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/product_export_show.yml, src/Pim/Bundle/EnrichBundle/Resources/config/normalizers.yml, src/Pim/Bundle/EnrichBundle/Resources/config/providers.yml, src/Pim/Bundle/EnrichBundle/Resources/public/js/export/product/edit/content/data.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/filter/attribute/attribute.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/filter/attribute/boolean.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/filter/attribute/date.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/filter/attribute/identifier.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/filter/attribute/media.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/filter/attribute/metric.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/filter/attribute/number.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/filter/attribute/price-collection.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/filter/attribute/select.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/filter/attribute/string.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/form/config-provider.js, src/Pim/Bundle/EnrichBundle/spec/Normalizer/AttributeNormalizerSpec.php, src/Pim/Bundle/ReferenceDataBundle/Enrich/Provider/Filter/ReferenceDataFilterProvider.php, src/Pim/Bundle/ReferenceDataBundle/Resources/config/providers.yml, upgrades/schema/Version_1_6_20160726103445_update_product_export_parameters.php
This PR clean small stuff on the peb. I added a filter provider to be able to customize the look of the filters (for us and integrators).
=> PIM-5902: clean and filter provider

src/Pim/Bundle/EnrichBundle/Controller/MassEdit/AbstractMassEditController.php, src/Pim/Component/Catalog/Localization/Localizer/AttributeConverter.php, src/Pim/Component/Catalog/spec/Localization/Localizer/AttributeConverterSpec.php, src/Pim/Component/Connector/spec/ArrayConverter/StandardToFlat/ProductLocalizedSpec.php
Before fix: https://blackfire.io/profiles/c5234c62-3916-432b-8a47-27e66bd26615/graph
After fix: https://blackfire.io/profiles/089d7886-7524-4363-8b0a-cb2d39972c70/graph
=> TIP-569: optimize export products

src/Pim/Bundle/ImportExportBundle/DependencyInjection/Compiler/RegisterJobNameVisibilityCheckerPass.php, src/Pim/Bundle/ImportExportBundle/PimImportExportBundle.php, src/Pim/Bundle/ImportExportBundle/Resources/config/view_elements/job_profile.yml, src/Pim/Bundle/ImportExportBundle/ViewElement/Checker/JobNameVisibilityChecker.php, src/Pim/Bundle/ImportExportBundle/spec/ViewElement/Checker/JobNameVisibilityCheckerSpec.php
This PR adds the possibility to plug new jobs on the JobNameVisibilityChecker. It also removes the EE jobs from the CE.
| Review and 2 GTM                  | Waiting for :D 
=> PIM-5951: Extensibility issue with viewElement in content tab

upgrades/schema/Version_1_6_20160804181154_versioning_index.php
| Added Specs                       | no 
| Added Behats                      | no 
| Changelog updated                 | no 
| Migration script                  | yes
=> Fix migration

features/Context/DataGridContext.php, features/Pim/Behat/Decorator/Export/Filter/StringDecorator.php, features/export/product-export-builder/export_products_by_text.feature, features/export/product-export-builder/export_products_by_textarea.feature, src/Pim/Bundle/EnrichBundle/Resources/public/js/filter/attribute/string.js
| Added Behats                      | 
=> PIM-5950: Render string filter on value update to toggle input

.travis.yml
=> Added PHP 7.1 to travis (#4889)

composer.json
=> PIM-5790: Prepare upcoming 1.7

UPGRADE-1.6.md
=> PIM-5790: Update UPGRADE.md links to 1.6 documentation

CHANGELOG-1.6.md, src/Pim/Bundle/CatalogBundle/Version.php
=> PIM-5790: prepare 1.6.0-rc1 release

CHANGELOG-1.5.md, spec/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/IndexCreatorSpec.php, src/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/IndexCreator.php
=> TIP-307: Fix issues with mongo 2.6 on 1.5

src/Pim/Bundle/CatalogBundle/Command/RemoveProductCommand.php
This command allow to query with the PQB and delete in bulk the selected products
=> PIM-5956: Add command to query and bulk delete products

src/Pim/Bundle/EnrichBundle/Resources/config/navigation.yml, src/Pim/Bundle/ImportExportBundle/Resources/config/navigation.yml
To prepare override in EE
| Review and 2 GTM                  | n
=> PIM-5921: Add priorities to menu items for best priorization overriding

CHANGELOG-1.6.md, features/export/edit_an_export.feature, features/export/product-export-builder/export_products_by_locales.feature, src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filter/product_scope-filter.js, src/Pim/Bundle/EnrichBundle/Controller/Rest/ChannelController.php, src/Pim/Bundle/EnrichBundle/Normalizer/ChannelNormalizer.php, src/Pim/Bundle/EnrichBundle/Resources/config/controllers.yml, src/Pim/Bundle/EnrichBundle/Resources/config/normalizers.yml, src/Pim/Bundle/EnrichBundle/Resources/public/js/export/product/edit/content/data/validation.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/export/product/edit/content/structure/locales.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/attributes/localizable.js, src/Pim/Bundle/EnrichBundle/Resources/public/templates/export/product/edit/content/structure/locales.html, src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml
Fix the scope dropdown position on the variant group screen
=> PIM-5922: fix scope switcher

features/Context/Page/Product/Edit.php, features/Pim/Behat/Context/NavigationContext.php
Changes the selector (more specific) to be compatible with EE published products
| Review and 2 GTM                  | n
=> PIM-5635: Set locale and scope switch more general

CHANGELOG-1.6.md, features/mass-action/quick_export.feature, features/mass-action/quick_export_grid_context.feature, features/mass-action/quick_export_with_media.feature, features/reference-data/product/display_history.feature, src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml
=> PIM-5959: Change wording of XLSX to Excel on mass actions

src/Pim/Bundle/EnrichBundle/Normalizer/ChannelNormalizer.php
Fixes the channel normalization for ce
=> PIM-5922: fix channel normalization

CHANGELOG-1.6.md, src/Pim/Bundle/EnrichBundle/Normalizer/ChannelNormalizer.php, src/Pim/Bundle/EnrichBundle/spec/Normalizer/ChannelNormalizerSpec.php, src/Pim/Bundle/UIBundle/Resources/public/css/pim.less
=> PIM-5966: Category frame has disappeared in content tab (+ other fixes)

features/Context/Page/Export/Show.php, features/Pim/Behat/Decorator/Export/Filter/UpdatedDecorator.php, features/export/product-export-builder/show_localized_dates.feature, src/Pim/Bundle/EnrichBundle/Resources/public/js/filter/product/updated.js, src/Pim/Bundle/EnrichBundle/Resources/public/templates/filter/attribute/date.html, src/Pim/Bundle/EnrichBundle/Resources/public/templates/filter/product/updated.html, src/Pim/Bundle/UIBundle/Resources/public/css/form.less
Value field of datepicker were not align as before. I removed several unneeded classes.
Updated at field datepicker was not localized. 
=> PIM-5939: Fix localization and design of date and updated at field in export builder

CHANGELOG-1.7.md, features/Pim/Behat/Context/NavigationContext.php, features/dashboard/loading_message.feature, src/Oro/Bundle/ConfigBundle/Controller/Rest/ConfigurationController.php, src/Oro/Bundle/ConfigBundle/Resources/config/controllers.yml, src/Pim/Bundle/UIBundle/DependencyInjection/Configuration.php, src/Pim/Bundle/UIBundle/Resources/config/form_extensions.yml, src/Pim/Bundle/UIBundle/Resources/config/loading_messages.txt, src/Pim/Bundle/UIBundle/Resources/config/requirejs.yml, src/Pim/Bundle/UIBundle/Resources/config/system_configuration.yml, src/Pim/Bundle/UIBundle/Resources/config/twig.yml, src/Pim/Bundle/UIBundle/Resources/public/css/progress.less, src/Pim/Bundle/UIBundle/Resources/public/js/form/system/group/loading_message.js, src/Pim/Bundle/UIBundle/Resources/public/js/templates/system/group/loading_message.html, src/Pim/Bundle/UIBundle/Resources/translations/jsmessages.en.yml, src/Pim/Bundle/UIBundle/Resources/translations/messages.en.yml, src/Pim/Bundle/UIBundle/Resources/views/Default/index.html.twig, src/Pim/Bundle/UIBundle/Twig/LoadingMessageExtension.php
This feature adds some <3 to the PIM by sharing our love with the customers. It also allow them to add there own love messages that willl be displayed during the loading screen.
| Changelog updated                 | :white_check_mark: 
| Micro Demo to the PO (Story only) | :white_check_mark: 
=> Feature loading

.php_cd, src/Pim/Component/User/Updater/GroupUpdater.php, src/Pim/Component/User/Updater/RoleUpdater.php
| Review and 2 GTM                  | N/A
=> TIP-337: Define coupling rules on PIM components

CHANGELOG-1.6.md, features/Pim/Behat/Context/Domain/ImportExportContext.php, features/Pim/Behat/Context/Domain/Spread/XlsxFileContext.php, features/export/export_products.feature, features/export/product-export-builder/export_products_with_attributes.feature, src/Pim/Bundle/ConnectorBundle/Resources/config/writers.yml, src/Pim/Bundle/EnrichBundle/Resources/config/steps.yml, src/Pim/Bundle/EnrichBundle/Resources/public/js/export/product/edit/content/structure/attributes-selector.js, src/Pim/Component/Connector/Writer/File/ColumnSorterInterface.php, src/Pim/Component/Connector/Writer/File/DefaultColumnSorter.php, src/Pim/Component/Connector/Writer/File/FlatItemBufferFlusher.php, src/Pim/Component/Connector/Writer/File/ProductColumnSorter.php, src/Pim/Component/Connector/spec/Writer/File/FlatItemBufferFlusherSpec.php, src/Pim/Component/Connector/spec/Writer/File/ProductColumnSorterSpec.php
Add sort order to the product export builder
=> PIM-5782: add sort order support on attribute selector

features/Context/Page/Base/Form.php, features/Context/WebUser.php, features/product/ensure_tab_redirection.feature
fix scenario features/product/ensure_tab_redirection.feature on 1.5
=> Backport on 1.5 the fix for form tab

CHANGELOG-1.6.md
=> PIM-5975: add details in changelog

CHANGELOG-1.6.md
=> Issue #4494 add details in changelog

features/export/create_an_export.feature, features/import/create_an_import.feature
=> Fix nonexistent step

CHANGELOG-1.5.md, app/SymfonyRequirements.php, app/check.php, src/Pim/Bundle/EnrichBundle/Controller/Rest/AttributeOptionController.php, src/Pim/Bundle/EnrichBundle/Doctrine/ORM/Repository/AttributeOptionSearchableRepository.php, src/Pim/Bundle/EnrichBundle/Normalizer/StructuredAttributeOptionNormalizer.php, src/Pim/Bundle/EnrichBundle/Resources/config/controllers.yml, src/Pim/Bundle/EnrichBundle/Resources/config/normalizers.yml, src/Pim/Bundle/EnrichBundle/Resources/config/repositories.yml, src/Pim/Bundle/EnrichBundle/Resources/config/routing/attributeoption.yml, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/field/multi-select-field.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/field/simple-select-field.js, src/Pim/Bundle/EnrichBundle/Resources/views/Product/edit.html.twig
Refresh PEF attributes labels values for multi-select and simple-select when locale is changed.
| Changelog updated                 | 
=> PIM-5777: PEF attribute values not refreshed when locale is changed

CHANGELOG-1.6.md, src/Pim/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev/jobs.yml, src/Pim/Component/Connector/Job/JobParameters/ConstraintCollectionProvider/SimpleCsvExport.php, src/Pim/Component/Connector/Job/JobParameters/ConstraintCollectionProvider/SimpleXlsxExport.php, src/Pim/Component/Connector/Job/JobParameters/DefaultValuesProvider/ProductCsvExport.php, src/Pim/Component/Connector/Job/JobParameters/DefaultValuesProvider/ProductXlsxExport.php, src/Pim/Component/Connector/Job/JobParameters/DefaultValuesProvider/SimpleCsvExport.php, src/Pim/Component/Connector/Job/JobParameters/DefaultValuesProvider/SimpleXlsxExport.php, src/Pim/Component/Connector/Job/JobParameters/DefaultValuesProvider/SimpleYamlExport.php, src/Pim/Component/Connector/Job/JobParameters/DefaultValuesProvider/VariantGroupCsvExport.php, src/Pim/Component/Connector/Writer/File/AbstractFileWriter.php, src/Pim/Component/Connector/Writer/File/AbstractItemMediaWriter.php, src/Pim/Component/Connector/Writer/File/Csv/Writer.php, src/Pim/Component/Connector/Writer/File/Xlsx/Writer.php, src/Pim/Component/Connector/spec/Job/JobParameters/DefaultValuesProvider/ProductCsvExportSpec.php, src/Pim/Component/Connector/spec/Job/JobParameters/DefaultValuesProvider/ProductXlsxExportSpec.php, src/Pim/Component/Connector/spec/Job/JobParameters/DefaultValuesProvider/SimpleCsvExportSpec.php, src/Pim/Component/Connector/spec/Job/JobParameters/DefaultValuesProvider/SimpleXlsxExportSpec.php, src/Pim/Component/Connector/spec/Job/JobParameters/DefaultValuesProvider/SimpleYamlExportSpec.php, src/Pim/Component/Connector/spec/Writer/File/Csv/ProductWriterSpec.php, src/Pim/Component/Connector/spec/Writer/File/Csv/VariantGroupWriterSpec.php, src/Pim/Component/Connector/spec/Writer/File/Csv/WriterSpec.php, src/Pim/Component/Connector/spec/Writer/File/Xlsx/ProductWriterSpec.php, src/Pim/Component/Connector/spec/Writer/File/Xlsx/VariantGroupWriterSpec.php, src/Pim/Component/Connector/spec/Writer/File/Xlsx/WriterSpec.php
=> PIM-5947: Add default filepath for export

features/localization/export/export_variant_groups_with_date.feature, features/localization/mass-action/edit_common_attributes.feature, features/localization/mass-action/quick_export.feature, features/localization/product/edit_product.feature, src/Pim/Bundle/ConnectorBundle/Resources/translations/messages.fr.yml, src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.fr.yml, src/Pim/Bundle/EnrichBundle/Resources/translations/messages.fr.yml, src/Pim/Bundle/UserBundle/Resources/translations/messages.fr.yml
To be able to merge https://github.com/akeneo/pim-community-dev/pull/5023/files
=> Fix translations before 1.6 merge

CHANGELOG-1.6.md
=> PIM-5947: update changelog

src/Pim/Bundle/DashboardBundle/Resources/views/Widget/links.html.twig
Dashboard image url FIX when Akeneo is in a subdirectory : issue #4987 
Thanks @nidup
=> Issue 4987

CHANGELOG-1.7.md
=> Add notes in changelog regarding #4987

CHANGELOG-1.6.md, features/import/product/xlsx/import_products.feature, src/Pim/Component/Catalog/Updater/Setter/SimpleSelectAttributeSetter.php, src/Pim/Component/Catalog/spec/Updater/Setter/SimpleSelectAttributeSetterSpec.php
Allow numeric value as code in Simple Select attribute
Issue #4993 
Thanks @solivier
=> Issue 4993

ISSUE_TEMPLATE.md
=> Fix broken forum links (cf #5086)

upgrades/schema/Version_1_7_20161009194818_product_template.php
=> TIP-606: add migration script to update pim_catalog_product_template table

features/Context/WebUser.php, src/Pim/Bundle/EnrichBundle/Resources/public/js/grid/view-selector.js
- Add ability to check for status button in Behat
- Fix the way we set the parent for the View Selector Footer JS form
=> AMS-10: Add label to a project

CHANGELOG-1.5.md, features/Context/DataGridContext.php, features/import/product_variant_group/import_variant_group_with_scopable_or_localizable_data.feature, spec/Pim/Component/Catalog/Updater/VariantGroupUpdaterSpec.php, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/field/multi-select-field.js, src/Pim/Component/Catalog/Updater/VariantGroupUpdater.php
**This PR is a backport of #4856 .** (thanks @fabienlem :tada: )
Behat & specs have been adapted for this 1.5 version.
=> [SLA] PIM-5985: Partial update on Variant Groups remove existing data

src/Pim/Component/Catalog/Updater/Copier/PriceCollectionAttributeCopier.php
Fix issue #5121 
Update method name making it verbose.
=> Issue #5121

CHANGELOG-1.6.md, src/Pim/Bundle/UIBundle/Resources/public/css/pim.less
=> PIM-5893: Fix products and assets category display issue on Firefox

src/Akeneo/Bundle/MeasureBundle/Family/DurationFamilyInterface.php, src/Akeneo/Bundle/MeasureBundle/Family/EnergyFamilyInterface.php, src/Akeneo/Bundle/MeasureBundle/Resources/config/measure.yml, src/Akeneo/Bundle/MeasureBundle/Resources/translations/jsmessages.en.yml, src/Akeneo/Bundle/MeasureBundle/Resources/translations/jsmessages.fr.yml, src/Akeneo/Bundle/MeasureBundle/Resources/translations/messages.en.yml, src/Akeneo/Bundle/MeasureBundle/Resources/translations/messages.fr.yml
This new measure unit is used to store legal informations about food products and food supplements.
This extend the duration family to add three units : week, month (conversion value could be discussed), year.
=> Added a new measure family for food products and food supplements. Extended Duration family.

src/Akeneo/Bundle/MeasureBundle/Family/CaseBoxFamilyInterface.php, src/Akeneo/Bundle/MeasureBundle/Resources/config/measure.yml, src/Akeneo/Bundle/MeasureBundle/Resources/translations/jsmessages.en.yml, src/Akeneo/Bundle/MeasureBundle/Resources/translations/jsmessages.fr.yml, src/Akeneo/Bundle/MeasureBundle/Resources/translations/messages.en.yml, src/Akeneo/Bundle/MeasureBundle/Resources/translations/messages.fr.yml
This new measure unit makes it possible to use a metric for case boxes packaging information.
=> Added a new measure family for case boxes packaging

CHANGELOG-1.7.md
=> Add details regarding CaseBox measure family in changelog

src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form.js
**Fix for issue #5119 **
Cleans js debug lines.
=> Issue #5119

CHANGELOG-1.5.md
=> Add changelog notes regarding Issue #5119

CHANGELOG-1.7.md, src/Pim/Bundle/DataGridBundle/Controller/Rest/DatagridViewController.php, src/Pim/Bundle/DataGridBundle/DependencyInjection/PimDataGridExtension.php, src/Pim/Bundle/DataGridBundle/Resources/config/controllers.yml, src/Pim/Bundle/DataGridBundle/Resources/config/factories.yml, src/Pim/Bundle/DataGridBundle/Resources/config/updaters.yml, src/Pim/Bundle/DataGridBundle/Updater/DatagridViewUpdater.php, src/Pim/Bundle/DataGridBundle/spec/Updater/DatagridViewUpdaterSpec.php
=> AMS-61: Add datagrid view updater

features/Context/DataGridContext.php, features/Context/Page/Batch/SetAttributeRequirements.php, features/Context/Page/Family/Edit.php, features/export/product-export-builder/export_products_by_multiselect.feature, features/export/product-export-builder/export_products_by_simpleselect.feature, features/versioning/purge_entites.feature
This PR fixes some unstable scenarios (mostly product filtering on datagrid) that fail on the new "dockerized" DCI.
Of course, for this PR, CI will be run on staging, not on production.
| Review and 2 GTM                  | :ballot_box_with_check:
=> Behat fixes

src/Akeneo/Bundle/BatchBundle/Job/DoctrineJobRepository.php
Attempt to apply https://github.com/akeneo/pim-community-dev/pull/4696 by cherry picking commits on master to avoid a lot of work applying/fixing this improvement in every upcoming version. Has been reviewed on original PR.
=> Re-work contrib mysql has gone away

CHANGELOG-1.7.md
=> Add changelog details #4696

upgrades/schema/Version_1_7_20161026140245_amount.php
Update "akeneo_batch_job_instance" table to change keys "data" to "amount" for metric & prices attributes
=> TIP-607: add a migration script for price and metric for product export builder

CHANGELOG-1.5.md, features/enrich/variant-group/edit_attributes_of_a_variant_group.feature, features/import/product_variant_group/import_variant_group_with_scopable_or_localizable_data.feature, spec/Pim/Component/Catalog/Builder/LocalizableAndScopableRawValuesBuilderSpec.php, src/Pim/Bundle/CatalogBundle/Doctrine/Common/Saver/GroupSaver.php, src/Pim/Bundle/EnrichBundle/Resources/public/js/pim-scopable.js, src/Pim/Component/Catalog/Builder/LocalizableAndScopableRawValuesBuilder.php
Following @jjanvier PR, this one indent to fix the locale specific edge case.
=> PIM-5995: fix local specific edge cases in value generation

src/Pim/Bundle/NotificationBundle/Notifier.php, src/Pim/Bundle/NotificationBundle/Resources/public/js/notification-list.js, src/Pim/Bundle/NotificationBundle/Resources/public/templates/notification/notification-list.html, src/Pim/Bundle/NotificationBundle/Resources/views/Notification/list.json.twig
This PR allow to easily change the label of the notification button
=> AMS-74: add exensibility to notifications

CHANGELOG-1.6.md, upgrades/schema/Version_1_6_20161028161514_add_missing_csv_product_quick_export.php
| Migration script                  | Y
=> Add upgrade script for missing export job to branch 1.6

features/localization/product/edit_product.feature, src/Pim/Bundle/UserBundle/Resources/translations/messages.fr.yml
This PR fixes a Crowdin change used on the features
The Crowdin PR:
https://github.com/akeneo/pim-community-dev/pull/5221/files
The issue:
https://github.com/akeneo/pim-community-dev/pull/5221/files#diff-77b9185faa934320b398a4db5170091cL74
=> [Nelson] Fix 1.5 before Nelson merge

UPGRADE-1.6.md
=> Inner typo in upgrade.md

.php_cs.php, CHANGELOG-1.5.md, UPGRADE-1.6.md, features/Context/Page/Base/Form.php, features/Context/Page/Base/Grid.php, features/enrich/variant-group/edit_variant_group_attribute_value.feature, features/import/product_variant_group/import_variant_group_with_scopable_or_localizable_data.feature, src/Pim/Bundle/BaseConnectorBundle/Resources/translations/messages.ca.yml, src/Pim/Bundle/CatalogBundle/Doctrine/Common/Saver/GroupSaver.php, src/Pim/Bundle/CatalogBundle/Resources/config/storage_driver/doctrine/orm.yml, src/Pim/Bundle/EnrichBundle/Form/Handler/GroupHandler.php, src/Pim/Bundle/EnrichBundle/Resources/config/bundles/akeneo_batch.yml, src/Pim/Bundle/EnrichBundle/Resources/config/form_subscribers.yml, src/Pim/Bundle/EnrichBundle/Resources/public/js/pim-scopable.js
This is a PR of merge 1.6 to master, but you will not find any commits of 1.6, because they are already here on master. The main commit is a revert from the previous revert.
=> [Merge] 1.6 -> master

CHANGELOG-1.5.md, features/attribute/option/edit_attribute_options_02.feature, features/attribute/option/sort_attribute_options.feature, features/enrich/variant-group/edit_variant_group_attribute_value.feature, src/Pim/Bundle/EnrichBundle/Resources/public/js/pim-attributeoptionview.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/field/multi-select-field.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/field/simple-select-field.js
=> [Merge] 1.5 -> 1.6 (PIM-6002)

CHANGELOG-1.5.md, features/user/create_edit_and_delete_role.feature, src/Oro/Bundle/UserBundle/Resources/config/validation.yml
see PIM-5997
CI -> https://core-ci.akeneo.com/job/dci_behat/7417/
=> [MERGE] 1.5 -> 1.6

src/Akeneo/Bundle/MeasureBundle/Family/DecibelFamilyInterface.php, src/Akeneo/Bundle/MeasureBundle/Family/ElectricChargeFamilyInterface.php, src/Akeneo/Bundle/MeasureBundle/Family/EnergyFamilyInterface.php
Fix family classes that should be interfaces.
=> Family classes to interfaces

CHANGELOG-1.4.md
=> PIM-6008: Fix CHANGELOG-1.4.md

Jenkinsfile, app/SymfonyRequirements.php, app/check.php, behat.ci.yml, features/Context/DataGridContext.php, features/Context/WebUser.php, package.json, src/Akeneo/Bundle/StorageUtilsBundle/Doctrine/Common/Detacher/ObjectDetacher.php, src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/LocaleRepository.php
Launch CI build through Jenkinsfile
| Q | A |
| --- | --- |
| Added Specs | N/A |
| Added Behats | N/A |
| Changelog updated | N/A |
| Review and 2 GTM | ------ |
| Micro Demo to the PO (Story only) | N/A |
| Migration script | N/A |
|  Tech Doc | N/A |
=> Add a Jenkinsfile for CI builds

CHANGELOG-1.6.md, features/Context/AssertionContext.php, features/Context/FixturesContext.php, features/Pim/Behat/Context/PimContext.php, features/mass-action/edit_common_attributes-01.feature, src/Akeneo/Bundle/BatchBundle/Launcher/SimpleJobLauncher.php
This PR prevent shell injection through the Mass-Edit form as $(pwd)
https://core-ci.akeneo.com/job/dci_behat/7534/
=> PIM-6022: Fix shell command injection in mass-edit

Jenkinsfile
This will re-allow to build nightly tests on 1.4 to master branches
=> Improve Jenkinsfile to launch full matrix for nightly builds

src/Pim/Component/Connector/Exception/InvalidItemFromViolationsException.php
=> InvalidItemFromViolationsException: fix PHPDoc

CHANGELOG-1.4.md, composer.json, features/Context/AssertionContext.php, features/Context/FixturesContext.php, features/Pim/Behat/Context/PimContext.php, features/mass-action/edit_common_attributes.feature, spec/Pim/Bundle/EnrichBundle/Connector/Processor/MassEdit/Product/EditCommonAttributesProcessorSpec.php, src/Pim/Bundle/ConnectorBundle/JobLauncher/SimpleJobLauncher.php, src/Pim/Bundle/EnrichBundle/MassEditAction/Operation/AbstractMassEditOperation.php, src/Pim/Bundle/EnrichBundle/MassEditAction/Operation/EditCommonAttributes.php
This PR fixes the Shell injection in the mass-edit form
=> PIM-6022: Fix shell Injection in Mass-Edit form

CHANGELOG-1.4.md, Jenkinsfile, behat.ci.yml, package.json, src/Akeneo/Bundle/StorageUtilsBundle/Doctrine/Common/Detacher/ObjectDetacher.php, src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/LocaleRepository.php, src/Pim/Bundle/EnrichBundle/MassEditAction/Operation/AbstractMassEditOperation.php
All is in the title!
| Added Specs                       | 🚫 
| Added Behats                      | 🚫 
| Changelog updated                 | 🚫 
| Review and 2 GTM                  | 🔲 
| Migration script                  | 🚫 
| Tech Doc                          | 🚫
=> Merge 1.5 into 1.6

CHANGELOG-1.5.md
Just forgot to update the changelog with a 2 tickets in one pr.
=> PIM-6034: Update Changelog

CHANGELOG-1.4.md, CHANGELOG-1.5.md, Jenkinsfile, features/Context/WebUser.php, features/attribute/option/edit_attribute_options_02.feature, features/enrich/variant-group/edit_variant_group_attribute_value.feature, features/family/mass_edit_families.feature, features/import/product/import_products_with_associations.feature, features/mass-action/edit_common_attributes-01.feature, src/Pim/Bundle/ConnectorBundle/Resources/translations/messages.en.yml, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/field/textarea-field.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/field/wysiwyg-field.js, src/Pim/Bundle/InstallerBundle/Resources/config/fixtures_jobs.yml, src/Pim/Component/Connector/Processor/Denormalization/ProductAssociationProcessor.php, src/Pim/Component/Connector/spec/Processor/Denormalization/ProductAssociationProcessorSpec.php
| Micro Demo to the PO (Story only) |:negative_squared_cross_mark: …
=> Merge 1.5 -> 1.6

CHANGELOG-1.4.md, CHANGELOG-1.5.md, Jenkinsfile, features/Context/WebUser.php, features/attribute/option/edit_attribute_options_02.feature, features/enrich/variant-group/edit_variant_group_attribute_value.feature, features/family/mass_edit_families.feature, features/import/product/import_products_with_associations.feature, features/mass-action/edit_common_attributes-01.feature, src/Pim/Bundle/ConnectorBundle/Resources/translations/messages.en.yml, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/field/textarea-field.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/field/wysiwyg-field.js, src/Pim/Bundle/InstallerBundle/Resources/config/fixtures_jobs.yml, src/Pim/Component/Connector/Processor/Denormalization/ProductAssociationProcessor.php, src/Pim/Component/Connector/spec/Processor/Denormalization/ProductAssociationProcessorSpec.php
=> 1.6 => Master

CHANGELOG-1.7.md, src/Oro/Bundle/UserBundle/Entity/Group.php, src/Pim/Component/User/Model/GroupInterface.php
| Added Behats                      | :negative_squared_cross_mark: 
| Micro Demo to the PO (Story only) | :negative_squared_cross_mark: 
=> Add group interface

CHANGELOG-1.6.md, features/channel/edit_channel.feature, features/family/delete_family.feature, src/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/QueryGenerator/FamilyDeletedQueryGenerator.php, src/Pim/Bundle/CatalogBundle/Resources/config/storage_driver/doctrine/mongodb-odm.yml, src/Pim/Bundle/CatalogBundle/Version.php, src/Pim/Bundle/CatalogBundle/spec/Doctrine/MongoDBODM/QueryGenerator/FamilyDeletedQueryGeneratorSpec.php, src/Pim/Bundle/EnrichBundle/EventListener/Storage/ChannelLocaleSubscriber.php, src/Pim/Bundle/EnrichBundle/spec/EventListener/Storage/ChannelLocaleSubscriberSpec.php
| Review and 2 GTM                  | 🕐
=> Merge 1.6 into master

CHANGELOG-1.7.md, UPGRADE-1.7.md, src/Pim/Bundle/DashboardBundle/Widget/Registry.php, src/Pim/Bundle/DashboardBundle/spec/Widget/RegistrySpec.php, src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filter/date-filter.js, src/Pim/Bundle/EnrichBundle/Resources/config/requirejs.yml, src/Pim/Bundle/EnrichBundle/Resources/public/js/filter/attribute/date.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/filter/product/updated.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/formatter/date-formatter.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/user-context.js, src/Pim/Bundle/UIBundle/Resources/config/assets.yml, src/Pim/Bundle/UIBundle/Resources/public/less/base/variables.less, src/Pim/Bundle/UIBundle/Resources/public/less/bemFixes.less, src/Pim/Bundle/UIBundle/Resources/public/less/components/ProjectWidget.less, src/Pim/Bundle/UserBundle/Controller/UserRestController.php, src/Pim/Bundle/UserBundle/Resources/config/controllers.yml, src/Pim/Bundle/UserBundle/Resources/config/requirejs.yml, src/Pim/Bundle/UserBundle/Resources/config/routing/user_rest.yml
| Changelog updated                 | :white_check_mark: :red_circle: …
=> AMS-83: Activity Manager widget style and Widget Registry fix

CHANGELOG-1.6.md, features/Context/FixturesContext.php, features/import/product/import_products_with_associations.feature, src/Pim/Component/Catalog/Model/AssociationInterface.php, src/Pim/Component/Catalog/Model/ProductInterface.php, src/Pim/Component/Catalog/Updater/Setter/AssociationFieldSetter.php, src/Pim/Component/Catalog/spec/Updater/Setter/AssociationFieldSetterSpec.php
| Review and 2 GTM                  | 🕐
| Micro Demo to the PO (Story only) | :negative_squared_cross_mark:  …
=> PIM-6042: Fix hard cleaning of associations

src/Pim/Bundle/DataGridBundle/Repository/DatagridViewRepository.php, src/Pim/Bundle/EnrichBundle/Resources/public/js/grid/view-selector.js
- Return public views in the view selector
- Fallback on entity code as id for select2 if the normalized entity doesn't have one
=> Some fixes

features/Context/WebUser.php
| Review and 2 GTM                  | In progress
=> PIM-6023: Add a behat step allowing us to hover an element

src/Pim/Bundle/CatalogBundle/Doctrine/ORM/CompletenessGenerator.php
cf. https://github.com/akeneo/pim-community-dev/pull/4665
=> Use `REPLACE` instead of `INSERT INTO`

features/Context/WebUser.php
| Review and 2 GTM                  | In progress
=> Add a spin to step when finding an element

src/Pim/Bundle/EnrichBundle/Connector/Processor/MassEdit/Family/SetAttributeRequirements.php
cf. https://github.com/akeneo/pim-community-dev/pull/5384
Short: the function addWarningMessage defined in AbstractProcessor expect a ProductInterface as 2nd argument. @fitn typehinted a FamilyInterface instead in Family/SetAttributeRequirements which extend AbstractProcessor.
=> Rework fitn fix to work with php>=7.0 and AbstractProcessor implementation of addWarningMessage

src/Pim/Bundle/EnrichBundle/Resources/config/bundles/fos_rest.yml
| Review and 2 GTM                  | :white_check_mark: :red_circle: :negative_squared_cross_mark: :clock1:
=> Fix wrong conf for php.7

src/Oro/Bundle/NavigationBundle/Controller/Api/NavigationItemController.php, src/Oro/Bundle/NavigationBundle/Controller/Api/PagestateController.php
Pinbar is broken since fos rest bundle upgrade, this PR fixes the issue using Response and not the removed Util/Codes class
| Migration script                  | :white_check_mark:
| Tech Doc                          | :white_check_mark: …
=> API-57: fix pinbar issue related to fos rest upgrade

CHANGELOG-1.5.md, features/datagrid/display_many_datagrid_filters.feature, spec/Pim/Bundle/CatalogBundle/Query/ProductQueryBuilderSpec.php, src/Pim/Bundle/CatalogBundle/Query/ProductQueryBuilder.php, src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/collection-filters-manager.js
| Review and 2 GTM                  | In progress
| Micro Demo to the PO (Story only) | In progress
The first commit is basically a backport of afix made on 1.6 only by @loicguillois about a similar issue (turns out its fix doesn't solve this one so I had to do an other fix)
=> PIM-6064: Fix a grid issue with attribute named ID

src/Pim/Bundle/DataGridBundle/Controller/Rest/DatagridViewController.php, src/Pim/Bundle/EnrichBundle/Resources/public/js/grid/view-selector-current.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/grid/view-selector.js, src/Pim/Bundle/EnrichBundle/Resources/public/templates/grid/view-selector-current.html, src/Pim/Bundle/UIBundle/Resources/public/less/components/ProjectWidget.less
Add some extension point after fetching the view + update style on project widget.
=> AMS-22: update style and view selector extensions

features/Context/Page/Base/Grid.php, features/enrich/variant-group/edit_variant_group_attribute_value.feature, features/product/associate_product.feature
| Review and 2 GTM                  | :red_circle:
=> PIM-5830: Unskip functional tests

CHANGELOG-1.5.md
add PIM-6022 in changelog for 1.5.15
=> Update Changelog 1.5.15

CHANGELOG-1.7.md
| Added integration tests           | :white_check_mark: :red_circle: …
=> Fix changelog typo

app/config/routing.yml, app/config/security.yml, src/Pim/Bundle/ApiBundle/Controller/Rest/CategoryController.php, src/Pim/Bundle/ApiBundle/DependencyInjection/PimApiExtension.php, src/Pim/Bundle/ApiBundle/Resources/config/controllers.yml, src/Pim/Bundle/ApiBundle/Resources/config/routing.yml, src/Pim/Bundle/ApiBundle/Resources/config/routing/category.yml, src/Pim/Bundle/ApiBundle/tests/integration/Controller/Rest/Category/GetCategoryIntegration.php, src/Pim/Bundle/VersioningBundle/tests/integration/Normalizer/Flat/CategoryIntegration.php, src/Pim/Component/Catalog/tests/integration/Normalizer/Standard/CategoryIntegration.php, tests/TestCase.php, tests/catalog/technical/categories.csv
| Added integration tests           | :white_check_mark: 
| Review and 2 GTM                  | :white_check_mark: 
:negative_squared_cross_mark: Not needed
=> API-20: Get a new category 

src/Pim/Bundle/ApiBundle/Controller/Rest/FamilyController.php, src/Pim/Bundle/ApiBundle/Resources/config/controllers.yml, src/Pim/Bundle/ApiBundle/Resources/config/routing.yml, src/Pim/Bundle/ApiBundle/Resources/config/routing/family.yml, src/Pim/Bundle/ApiBundle/tests/integration/Controller/Rest/Family/GetFamilyIntegration.php
| Review and 2 GTM                  | :white_check_mark: 
:negative_squared_cross_mark: Not needed
=> API-25: Get a single family

src/Pim/Bundle/ApiBundle/Controller/Rest/AttributeController.php, src/Pim/Bundle/ApiBundle/Resources/config/controllers.yml, src/Pim/Bundle/ApiBundle/Resources/config/routing.yml, src/Pim/Bundle/ApiBundle/Resources/config/routing/attribute.yml, src/Pim/Bundle/ApiBundle/tests/integration/Controller/Rest/Attribute/GetAttributeIntegration.php
Add controller, route and tests for getting a single attribute
| Migration script                  |:negative_squared_cross_mark:
=> API-24: Get a single attribute

CHANGELOG-1.7.md, src/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/Repository/ProductMassActionRepository.php, src/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/Repository/ProductRepository.php, src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/ProductMassActionRepository.php, src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/ProductRepository.php, src/Pim/Bundle/VersioningBundle/spec/UpdateGuesser/AttributeOptionUpdateGuesserSpec.php, src/Pim/Component/Catalog/Repository/ProductMassActionRepositoryInterface.php, src/Pim/Component/Catalog/Repository/ProductRepositoryInterface.php
Remove deprecated and never used methods from repos
| Added integration tests           | :white_check_mark: :red_circle: :negative_squared_cross_mark: :clock1:
| Changelog updated                 | :white_check_mark: :red_circle: :negative_squared_cross_mark: :clock1:
| Review and 2 GTM                  | :white_check_mark: :red_circle: :negative_squared_cross_mark: :clock1: …
=> Product repo cleanup

CHANGELOG-1.7.md, UPGRADE-1.7.md, features/Pim/Behat/Decorator/Field/MultiSelectDecorator.php, features/datagrid/datagrid_views.feature, src/Pim/Bundle/DashboardBundle/Resources/config/widgets.yml, src/Pim/Bundle/DashboardBundle/Resources/public/js/last-operations-widget.js, src/Pim/Bundle/DashboardBundle/Resources/public/templates/last-operations-widget.html, src/Pim/Bundle/DashboardBundle/Widget/CompletenessWidget.php, src/Pim/Bundle/DashboardBundle/Widget/LastOperationsWidget.php, src/Pim/Bundle/DashboardBundle/Widget/LinksWidget.php, src/Pim/Bundle/DashboardBundle/spec/Widget/CompletenessWidgetSpec.php, src/Pim/Bundle/DashboardBundle/spec/Widget/LastOperationsWidgetSpec.php, src/Pim/Bundle/DashboardBundle/spec/Widget/LinksWidgetSpec.php, src/Pim/Bundle/DataGridBundle/EventSubscriber/DefaultViewSubscriber.php, src/Pim/Bundle/DataGridBundle/Repository/DatagridViewRepository.php, src/Pim/Bundle/DataGridBundle/Repository/DatagridViewRepositoryInterface.php, src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filter/multiselect-filter.js, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/job_instance/xlsx_base_import_edit.yml, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/job_instance/xlsx_base_import_show.yml, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/job_instance/xlsx_product_import_edit.yml, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/job_instance/xlsx_product_import_show.yml, src/Pim/Bundle/EnrichBundle/Resources/config/providers.yml
This PR aggregate a selection of glitches:
- PIM-6106: As Peter, I would like to remove the escape parameter not usefull
- PIM-6081: As Julia, when I use a multiselect filter in a grid, I would like to automatically unchecked ALL
- PIM-6058: As Julia, I would like to define as default a view I have not created
- PIM-6090: As Julia, I would like to see my dashboard according to my rights
| Added integration tests           |:negative_squared_cross_mark: …
=> Multiple unfinished business rework

app/AppKernel.php, app/config/config.yml, composer.json, src/Pim/Bundle/ApiBundle/Command/CreateClientCommand.php, src/Pim/Bundle/ApiBundle/Command/ListClientsCommand.php, src/Pim/Bundle/ApiBundle/Command/RevokeClientCommand.php, src/Pim/Bundle/ApiBundle/DependencyInjection/PimApiExtension.php, src/Pim/Bundle/ApiBundle/Doctrine/ORM/Repository/ClientRepository.php, src/Pim/Bundle/ApiBundle/Entity/AccessToken.php, src/Pim/Bundle/ApiBundle/Entity/AuthCode.php, src/Pim/Bundle/ApiBundle/Entity/Client.php, src/Pim/Bundle/ApiBundle/Entity/RefreshToken.php, src/Pim/Bundle/ApiBundle/Resources/config/doctrine/AccessToken.orm.yml, src/Pim/Bundle/ApiBundle/Resources/config/doctrine/AuthCode.orm.yml, src/Pim/Bundle/ApiBundle/Resources/config/doctrine/Client.orm.yml, src/Pim/Bundle/ApiBundle/Resources/config/doctrine/RefreshToken.orm.yml, src/Pim/Bundle/ApiBundle/Resources/config/repositories.yml, upgrades/schema/Version_1_7_20170112144222_oauth.php
Done in this PR:
- installation of https://github.com/FriendsOfSymfony/FOSOAuthServerBundle (just general conf and Doctrine stuff, no firewall has been set yet, will be done in another PR)
- three commands have been added to administrate the clients: create, list and revoke.
- some kernel cleaning (don't complain it's hard to review, I just added the FOSOAuthServerBundle and reorder the rest)
| Changelog …
=> API-47: Implement OAuth2 authentication - installation & commands

CHANGELOG-1.6.md, features/Pim/Behat/Decorator/Tree/JsTreeDecorator.php, features/versioning/purge_entites.feature, src/Akeneo/Component/Console/CommandLauncher.php, src/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/QueryGenerator/FamilyLabelUpdatedQueryGenerator.php, src/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/Sorter/FamilySorter.php, src/Pim/Bundle/CatalogBundle/spec/Doctrine/MongoDBODM/QueryGenerator/FamilyLabelUpdatedQueryGeneratorSpec.php, src/Pim/Bundle/CatalogBundle/spec/Doctrine/MongoDBODM/Sorter/FamilySorterSpec.php
It fixes the next fails on the DCI
- Execute rules from the user interface.Successfully execute all rules from the user interface
- Execute rules from the user interface.Successfully execute one rule from the rule datagrid
- List all rules.Successfully execute a set of rules using bulk action
- purge product versions.Successfully purges product versions but keeps the published version
- purge versions.Successfully purges versions but keeps the first and last version of a family …
=> [PIM-6062 + PIM-5085] Fix various fails on DCI

src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/grid_view_selector.yml, src/Pim/Bundle/EnrichBundle/Resources/public/js/grid/view-selector.js
=> AMS-13: Update the way fetchers are retrieved by view selector

src/Pim/Bundle/ApiBundle/Controller/Rest/FamilyController.php, src/Pim/Bundle/ApiBundle/Resources/config/normalizers.yml, src/Pim/Bundle/ApiBundle/Resources/config/routing.yml, src/Pim/Bundle/ApiBundle/Resources/config/routing/family.yml, src/Pim/Bundle/ApiBundle/tests/integration/Controller/Rest/Family/ListFamilyIntegration.php, src/Pim/Component/Api/Normalizer/SimpleCollectionNormalizer.php, src/Pim/Component/Api/spec/Normalizer/SimpleCollectionNormalizerSpec.php
Get a list of families
https://akeneo.atlassian.net/browse/API-16
Call /api/rest/v1/families
Response 200
```
{"items":[{"code":"webcams","attributes":["description","maximum_frame_rate","maximum_video_resolution","name","picture","power_requirements","price","release_date","sku","total_megapixels","weight"],"attribute_as_label":"name","attribute_requirements":{"ecommerce":["description","maximum_video_resolution","name","price","sku","total_megapixels"],"mobile":["description","maximum_video_resolution","name","price","sku","total_megapixels"],"print":["description","maximum_video_resolution","name","price","sku","total_megapixels"]},"labels":{"en_US":"Webcams","fr_FR":"Webcams","de_DE":"Webcams"}},{"code":"mugs","attributes":["container_material","description","main_color","name","pictur …
```
=> API-16: Get a list of families

.github/PULL_REQUEST_TEMPLATE.md
This PR aims to simplify the GitHub pull request template cartouche. Please leave comment for what you'd like :)
=> Simplify the Github pull request template

src/Akeneo/Component/Batch/composer.json
I added a dependency on the composer file of the batch component to reflect the dependencies in the code. (see #5448)
=> Updated akeneo/batch component's dependencies

Jenkinsfile
| Changelog updated                 | :white_check_mark: :red_circle: :negative_squared_cross_mark: :clock1:
| Review and 2 GTM                  | :white_check_mark: :red_circle: :negative_squared_cross_mark: :clock1:
| Micro Demo to the PO (Story only) | :white_check_mark: :red_circle: :negative_squared_cross_mark: :clock1:
| Migration script                  | :white_check_mark: :red_circle: :negative_squared_cross_mark: :clock1:
| Tech Doc                          | :white_check_mark: …
=> Add default php and mysql versions for master build

features/Context/FixturesContext.php, features/Context/NavigationContext.php, features/acl/assert_acl.feature, features/acl/enforce_acl_on_history.feature, features/channel/create_channel.feature, features/channel/delete_channel.feature, features/channel/edit_channel.feature, features/export/convert_metric_values_during_product_export.feature, features/export/export_channels.feature, features/product/completeness/remove_completeness.feature, features/user/update_user_preferences.feature, features/versioning/ensure_versioning_on_channel.feature, src/Pim/Bundle/EnrichBundle/Controller/Rest/ChannelController.php, src/Pim/Bundle/EnrichBundle/Resources/public/js/channel/form/properties/general.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/channel/form/properties/general/locales.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/save.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/scope-switcher.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/saver/channel.js, src/Pim/Bundle/EnrichBundle/Resources/public/templates/channel/tab/properties/general.html, src/Pim/Bundle/EnrichBundle/Resources/public/templates/channel/tab/properties/general/category-tree.html, src/Pim/Bundle/EnrichBundle/Resources/public/templates/channel/tab/properties/general/locales.html, src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/scope-switcher.html
- Add validation error when no currencies and/or locales were set. 
- Add behat scenario
- Clean up behats
[See styleguide requirements](https://docs.akeneo.com/master/styleguide/index.php#Forms-AknFieldContainer)
=> GITHUB-5455-red

upgrades/1.3-1.4/common/MediaMigration.php
Bring back https://github.com/akeneo/pim-community-dev/pull/5159 for 1.5 branch.
=> Get back aoe bug media migration memory consumption

src/Pim/Bundle/ConnectorBundle/Resources/translations/messages.fr.yml, src/Pim/Bundle/EnrichBundle/Resources/translations/messages.fr.yml
Updated on 1.6-2017-01-28-09-19
=> Update translations from nelson

src/Akeneo/Bundle/StorageUtilsBundle/Doctrine/TableNameBuilder.php
| Added Specs                       | no
| Added integration tests           | no
=> AMS-127: Return the sql table name instead of the target entity

composer.json
https://github.com/akeneo/pim-community-dev/pull/5371
PR already GTM, I just rebased it.
=> Added "replace" configuration in the composer.json file

CHANGELOG-1.5.md, features/Context/FixturesContext.php, features/import/product/import_products_with_associations.feature, features/product/associate_product.feature, spec/Pim/Component/Catalog/Updater/Setter/AssociationFieldSetterSpec.php, src/Pim/Component/Catalog/Model/AssociationInterface.php, src/Pim/Component/Catalog/Model/ProductInterface.php, src/Pim/Component/Catalog/Updater/Setter/AssociationFieldSetter.php
Backport of these PR:
- https://github.com/akeneo/pim-community-dev/pull/5397
- https://github.com/akeneo/pim-community-dev/pull/5508
=> Backport PIM-6042 + PIM-6110

src/Pim/Bundle/UIBundle/Controller/AjaxOptionController.php
A regression was introduced when merging the previous fix of PIM-6092. Actually it worked, it was tested, then came a review where I changed the code and reran the behats, but not tested the functional "by hand". Call it a "too confidant review commit" that break things. Anyway, here is the working one.
| Added Behats                      | Already done here : https://github.com/akeneo/pim-enterprise-dev/pull/2382
| Changelog updated                 | :white_check_mark: https://github.com/akeneo/pim-community-dev/pull/5475 …
=> PIM-6092: Fixed a last minute review that broke the functionality

features/datagrid/datagrid_views.feature, src/Pim/Bundle/DataGridBundle/Resources/public/js/fetcher/datagrid-view-fetcher.js, src/Pim/Bundle/DataGridBundle/Resources/views/macros.html.twig, src/Pim/Bundle/EnrichBundle/Resources/public/js/grid/view-selector.js
Correctly switches the grid to the user default one if he has some.
=> AMS-157: correctly switch grid to the user default view

features/locale/browse_locales.feature
=> PIM-6093: fix ci

src/Pim/Bundle/ApiBundle/Controller/ProductController.php, src/Pim/Bundle/ApiBundle/Resources/config/controllers.yml, src/Pim/Bundle/ApiBundle/Resources/config/routing/product.yml, src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/AbstractProductTestCase.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/DeleteProductIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/ErrorListProductIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/GetProductIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/SuccessListProductIntegration.php
This PR contains 2 cards (as they are very simple, I developed them on the same time):
- get a single product
- delete a single product
| Review …
=> API-26/42: Get/delete a single product

src/Akeneo/Component/StorageUtils/Exception/InvalidObjectException.php, src/Akeneo/Component/StorageUtils/Exception/InvalidPropertyException.php, src/Akeneo/Component/StorageUtils/Exception/InvalidPropertyTypeException.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/Rest/Category/CreateCategoryIntegration.php
It's cherry picks from the api-web branch about business exception in updaters. It should be merged in master because we will refactor the business exception in adder and setter as well.
In fact, it should have been directly developed in master.
| Added Behats …
=> Tip 322 : merge business exception on updaters in master 

upgrades/schema/Version_1_5_20160405165700_versioning.php
The current shcema upgrade is not applied due to malformed sql query.
Backslash need to be escaped in the query. …
=> Need to escape backslash

src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/AbstractFilterTestCase.php, src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Metric/LocalizableFilterIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Metric/LocalizableScopableFilterIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Metric/MetricFilterIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Metric/ScopableFilterIntegration.php
Add integration tests on metric PQB
(as it's quite boring to write test (and for you to read), I will create a dedicated PR for each attribute)
=> API-65: add integration tests on PQB [metric]

src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Date/DateFilterIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Date/LocalizableFilterIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Date/LocalizableScopableFilterIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Date/ScopableFilterIntegration.php
=> API-65: add integration tests in PQB [date]

src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Boolean/BooleanFilterIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Boolean/LocalizableFilterIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Boolean/LocalizableScopableFilterIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Boolean/ScopableFilterIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Metric/LocalizableScopableFilterIntegration.php
=> API-65: add integration tests on PQB [boolean]

CHANGELOG-1.6.md, src/Pim/Bundle/UserBundle/Resources/views/Reset/checkEmail.html.twig, src/Pim/Bundle/UserBundle/Resources/views/Reset/request.html.twig, src/Pim/Bundle/UserBundle/Resources/views/Security/login.html.twig
Avoid to display this info (we only display it on dashboard once loggued in).
=> PIM-6149: remove pim version from login page

src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Metric/LocalizableFilterIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Metric/LocalizableScopableFilterIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Metric/MetricFilterIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Metric/ScopableFilterIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/String/LocalizableFilterIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/String/LocalizableScopableFilterIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/String/ScopableFilterIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/String/StringFilterIntegration.php
=> API-65: add integration tests on PQB [string]

src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Number/LocalizableFilterIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Number/LocalizableScopableFilterIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Number/NumberFilterIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Number/ScopableFilterIntegration.php
=> API-65: add integration tests on PQB [number]

src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Price/LocalizableFilterIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Price/LocalizableScopableFilterIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Price/PriceFilterIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Price/ScopableFilterIntegration.php
=> API-65: add integration tests on PQB [price]

src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/AbstractFilterTestCase.php, src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Boolean/BooleanFilterIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Boolean/LocalizableFilterIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Boolean/LocalizableScopableFilterIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Boolean/ScopableFilterIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Date/DateFilterIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Date/LocalizableFilterIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Date/LocalizableScopableFilterIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Date/ScopableFilterIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/DateTimeFilterIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/FamilyFilterIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/GroupsFilterIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Metric/LocalizableFilterIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Metric/LocalizableScopableFilterIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Metric/MetricFilterIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Metric/ScopableFilterIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Option/LocalizableFilterIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Option/LocalizableScopableFilterIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Option/OptionFilterIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Option/ScopableFilterIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Options/LocalizableFilterIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Options/LocalizableScopableFilterIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Options/OptionsFilterIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Options/ScopableFilterIntegration.php
=> API-65: add integration tests on PQB [option]

src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Number/LocalizableScopableFilterIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Number/NumberFilterIntegration.php
=> API-65: fix missing param

src/Pim/Bundle/UIBundle/Resources/public/less/components/ProjectWidget.less
Update style of AM widget when no project.
=> AMS-32: fix AM widget style when no project

src/Pim/Bundle/UIBundle/Resources/config/assets.yml, src/Pim/Bundle/UIBundle/Resources/public/less/components/Thumbnail.less
Add thumbnail for assets on proposal grid. …
=> PIM-6075: add thumbnails as BEM module

src/Pim/Bundle/ApiBundle/Controller/ChannelController.php, src/Pim/Bundle/ApiBundle/Resources/config/acl.yml, src/Pim/Bundle/ApiBundle/Resources/config/acl_groups.yml, src/Pim/Bundle/ApiBundle/Resources/config/controllers.yml, src/Pim/Bundle/ApiBundle/Resources/config/normalizers.yml, src/Pim/Bundle/ApiBundle/Resources/config/routing.yml, src/Pim/Bundle/ApiBundle/Resources/config/routing/channel.yml, src/Pim/Bundle/ApiBundle/tests/integration/Controller/Channel/GetChannelIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/Channel/ListChannelIntegration.php, src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/ChannelRepository.php, src/Pim/Component/Api/Normalizer/ChannelNormalizer.php, src/Pim/Component/Api/spec/Normalizer/ChannelNormalizerSpec.php, src/Pim/Component/Api/tests/integration/Normalizer/ChannelNormalizerIntegration.php
This PR is related to this feature: https://akeneo.atlassian.net/browse/API-75
It allows to list and get a channel through the API
| Changelog updated                 | ?
| …
=> API-75: Get and list channels

src/Pim/Bundle/EnrichBundle/Resources/public/js/grid/view-selector-line.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/grid/view-selector.js, src/Pim/Bundle/UIBundle/Resources/public/less/lib/select2.less
Fix style of the current project selected in the View Selector.
=> AMS-162: fix style of current project selected

features/Context/Page/Base/Form.php, src/Pim/Bundle/DataGridBundle/EventSubscriber/DefaultViewSubscriber.php, src/Pim/Bundle/DataGridBundle/Repository/DatagridViewRepository.php
=> AMS-168: Only display public view

.php_cs.php
=> Remove integration tests from php-cs-fixer

features/product/associate_product.feature
Fix unstable scenario on DCI EE ORM
=> [PIM-6113] Fix unstable CI

CHANGELOG-1.6.md, src/Pim/Component/Connector/Processor/Normalization/ProductProcessor.php
This improves product export speed when using attributes to filter with a huge number of attributes. It was the case for a client with an intensive use of it.
It appears that doing it this way improved perfs by +35% at export (uprofiler checked)
`OK`: Done …
=> PIM-6157: Improve product export speed

.php_cs.dist, Jenkinsfile
=> Merge 1.4 Jenkinsfile into 1.5

src/Pim/Bundle/ApiBundle/Controller/AttributeController.php, src/Pim/Bundle/ApiBundle/Controller/AttributeOptionController.php, src/Pim/Bundle/ApiBundle/Controller/CategoryController.php, src/Pim/Bundle/ApiBundle/Controller/FamilyController.php, src/Pim/Bundle/ApiBundle/Controller/ProductController.php, src/Pim/Bundle/ApiBundle/Resources/config/controllers.yml, src/Pim/Bundle/ApiBundle/Resources/config/routing/attribute.yml, src/Pim/Bundle/ApiBundle/Resources/config/routing/category.yml, src/Pim/Bundle/ApiBundle/Resources/config/routing/family.yml
=> Baby fix on controllers

src/Pim/Bundle/EnrichBundle/Resources/views/Attribute/_js-handler.html.twig, src/Pim/Bundle/UIBundle/Resources/config/assets.yml, src/Pim/Bundle/UIBundle/Resources/public/less/components/BreadcrumbContainer.less, src/Pim/Bundle/UIBundle/Resources/public/less/components/ColumnConfigurator.less, src/Pim/Bundle/UIBundle/Resources/public/less/components/MainMenu.less, src/Pim/Bundle/UIBundle/Resources/public/less/components/NotificationList.less, src/Pim/Bundle/UIBundle/Resources/public/less/components/TitleContainer.less, src/Pim/Bundle/UIBundle/Resources/public/less/components/product-edit-form/AssetCollectionField.less, src/Pim/Bundle/UIBundle/Resources/public/less/components/product-edit-form/FieldContainer.less, src/Pim/Bundle/UIBundle/Resources/public/less/lib/jquery.jstree.less, src/Pim/Bundle/UIBundle/Resources/public/less/lib/modal.less, src/Pim/Bundle/UIBundle/Resources/public/less/lib/select2.less
It fixes all the latest found glitches raised on uimaniacs.
=> [TIP-666] Fix BEM

src/Pim/Bundle/ApiBundle/Controller/AttributeController.php, src/Pim/Bundle/ApiBundle/Controller/CategoryController.php, src/Pim/Bundle/ApiBundle/Controller/FamilyController.php, src/Pim/Bundle/ApiBundle/Controller/ProductController.php, src/Pim/Bundle/ApiBundle/Resources/config/routing/product.yml, src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/PartialUpdateProductIntegration.php, src/Pim/Component/Catalog/Comparator/Filter/ProductFilter.php, src/Pim/Component/Catalog/Updater/ProductUpdater.php, src/Pim/Component/Catalog/Updater/Setter/EnabledFieldSetter.php, src/Pim/Component/Catalog/spec/Updater/ProductUpdaterSpec.php, src/Pim/Component/Catalog/spec/Updater/Setter/EnabledFieldSetterSpec.php, tests/catalog/technical/variant_groups.csv
Add patch method in the API.
Patch is upsert.
| Migration …
=> Api 13 : add patch of a product in the api

upgrades/schema/Version_1_7_20161009194818_product_template.php
This PR follow the work of @phaseinducer in this PR -> https://github.com/akeneo/pim-community-dev/pull/5727
=> Change attributeType to type

UPGRADE-1.7.md
The goal is to enhance the upgrade file from the 1.6 to the 1.7 :-)
=> Update Upgrage to 1.7

CHANGELOG-1.6.md, features/export/product-export-builder/export_products_by_families.feature, src/Pim/Bundle/EnrichBundle/Controller/Rest/FamilyController.php
=> PIM-6162: Fix families rendering when editing product export

UPGRADE-1.7.md
Fix grammar issues as well as the ee one
=> Fix grammar issues

CHANGELOG-1.6.md
=> PIM-6162: Update CHANGELOG-1.6.md

Jenkinsfile
Should fix issues:
* https://github.com/akeneo/continuous-integration/issues/129
* https://github.com/akeneo/continuous-integration/issues/134
* https://github.com/akeneo/continuous-integration/issues/133
* https://github.com/akeneo/continuous-integration/issues/136
=> Fix false positive, separate tests layers, clean directories after build

src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/CreateProductIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/Rest/Family/CreateFamilyIntegration.php, src/Pim/Component/Catalog/Updater/FamilyUpdater.php, src/Pim/Component/Catalog/Validator/Constraints/FamilyAttributeAsLabel.php, src/Pim/Component/Catalog/Validator/Constraints/FamilyAttributeAsLabelValidator.php, src/Pim/Component/Catalog/Validator/Constraints/FamilyRequirements.php, src/Pim/Component/Catalog/Validator/Constraints/FamilyRequirementsValidator.php, src/Pim/Component/Catalog/Validator/Constraints/HasVariantAxes.php, src/Pim/Component/Catalog/Validator/Constraints/HasVariantAxesValidator.php, src/Pim/Component/Catalog/Validator/Constraints/UniqueVariantAxis.php, src/Pim/Component/Catalog/Validator/Constraints/UniqueVariantAxisValidator.php, src/Pim/Component/Catalog/Validator/Constraints/UniqueVariantGroup.php, src/Pim/Component/Catalog/Validator/Constraints/UniqueVariantGroupValidator.php, src/Pim/Component/Catalog/spec/Updater/FamilyUpdaterSpec.php
=> API-13/23: fix family and product

Jenkinsfile
=> Minor fixes on Jenkinsfile

CHANGELOG-1.6.md, features/export/product-export-builder/export_products_by_families.feature, src/Pim/Bundle/EnrichBundle/Controller/Rest/FamilyController.php
=> Merge 1-6 into 1-7

CHANGELOG-1.7.md, UPGRADE-1.7.md
Fix these both files to match EE
=> PIM-6176: Fix UPGRADE and CHANGELOG

src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/channel/edit.yml
=> PR-5787 (cherry-pick) Save/Delete btns ordering to be consistent

src/Pim/Bundle/ApiBundle/Controller/AttributeController.php, src/Pim/Bundle/ApiBundle/Controller/AttributeOptionController.php, src/Pim/Bundle/ApiBundle/Controller/CategoryController.php, src/Pim/Bundle/ApiBundle/Controller/ChannelController.php, src/Pim/Bundle/ApiBundle/Controller/FamilyController.php, src/Pim/Bundle/ApiBundle/Controller/ProductController.php, src/Pim/Bundle/ApiBundle/DependencyInjection/PimApiExtension.php, src/Pim/Bundle/ApiBundle/Doctrine/MongoDBODM/Repository/ProductRepository.php, src/Pim/Bundle/ApiBundle/Doctrine/ORM/Repository/ApiResourceRepository.php, src/Pim/Bundle/ApiBundle/Doctrine/ORM/Repository/AttributeRepository.php, src/Pim/Bundle/ApiBundle/Doctrine/ORM/Repository/ProductRepository.php, src/Pim/Bundle/ApiBundle/Resources/config/controllers.yml, src/Pim/Bundle/ApiBundle/Resources/config/normalizers.yml, src/Pim/Bundle/ApiBundle/Resources/config/repositories.yml, src/Pim/Bundle/ApiBundle/Resources/config/storage_driver/doctrine/mongodb-odm.yml, src/Pim/Bundle/ApiBundle/Resources/config/storage_driver/doctrine/orm.yml, src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/ErrorListProductIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/SuccessListProductIntegration.php, src/Pim/Component/Api/Normalizer/ProductNormalizer.php, src/Pim/Component/Api/Repository/ApiResourceRepositoryInterface.php, src/Pim/Component/Api/Repository/AttributeRepositoryInterface.php, src/Pim/Component/Api/Repository/PageableRepositoryInterface.php, src/Pim/Component/Api/Repository/ProductRepositoryInterface.php, src/Pim/Component/Api/spec/Normalizer/ProductNormalizerSpec.php
Implements our own repositories for the API.
| …
=> API-114: create repositories for the API

Jenkinsfile
=> Rename variable in Jenkinsfile

app/config/config.yml, app/config/pim_parameters.yml, src/Pim/Bundle/ApiBundle/Controller/AttributeController.php, src/Pim/Bundle/ApiBundle/Controller/CategoryController.php, src/Pim/Bundle/ApiBundle/Controller/ChannelController.php, src/Pim/Bundle/ApiBundle/Controller/FamilyController.php, src/Pim/Bundle/ApiBundle/Controller/ProductController.php, src/Pim/Bundle/ApiBundle/DependencyInjection/Configuration.php, src/Pim/Bundle/ApiBundle/DependencyInjection/PimApiExtension.php, src/Pim/Bundle/ApiBundle/Resources/config/api.yml, src/Pim/Bundle/ApiBundle/Resources/config/controllers.yml, src/Pim/Bundle/ApiBundle/Resources/config/hateoas.yml, src/Pim/Component/Api/Pagination/ParameterValidator.php, src/Pim/Component/Api/spec/Pagination/ParameterValidatorSpec.php
=> API-125: add configuration for API

CHANGELOG-1.7.md
=> API: add changelog

CHANGELOG-1.7.md
Add BC introduced on https://github.com/akeneo/pim-community-dev/commit/7246900dbdf626c3764e8d333a0937617c8f2530#diff-9be42926d8684786e093e0f2d2e40cf5R53
=> Add one BC on Changelog

features/Pim/Behat/Decorator/ContextSwitcherDecorator.php, features/family/define_the_attribute_requirement.feature, features/family/edit_a_family.feature, features/family/remove_attribute_from_a_family.feature, features/family/set_the_attribute_used_as_label.feature, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/family/edit.yml, src/Pim/Bundle/EnrichBundle/Resources/public/js/family/form/attributes/attributes.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/family/form/properties/general/translation.js, src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml, src/Pim/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev/attributes.csv
- Change save button position
- Drop attribute removal confirmation
- Update tests …
=> GITHUB-5573: Save btn and attr removing updates

src/Pim/Bundle/EnrichBundle/Controller/CategoryTreeController.php
=> PIM-5999: Fix asset category tree

Jenkinsfile
=> Fix bad merge on Jenkinsfile

tests/DatabaseSchemaHandler.php
See https://github.com/akeneo/pim-community-dev/pull/5830
Sorry but it seems I broke EE Mongo integration tests. This PR aims to fix it.
=> TIP-694: drop / recreate mongo schema for integration tests

features/Context/DataGridContext.php, features/Pim/Behat/Decorator/Grid/Filter/ChoiceDecorator.php
This PR adds some method for behat tests.
=> AMS-184: add context & decorator method for EE

features/Context/Page/Base/Form.php, features/import/edit_an_import.feature
Fixes behats following the removal of the with header field
| Review and 2 GTM                  | NA
| Tech Doc …
=> PIM-6210: fix behats

src/Pim/Bundle/UIBundle/Resources/public/less/components/product-edit-form/TabHeader.less, src/Pim/Bundle/UIBundle/Resources/public/less/lib/modal.less
Add various fixes needed for IVB and also for details on product edit form :)
=> Few CSS fixes

UPGRADE-1.7.md
This fix add a missing sed for upgrade stuff :)
TODO: Add in standard when done
=> Add missing sed

README.md
=> Remove useless travisci badges (we now use jenkinsci)

CHANGELOG-1.7.md, features/system/configuration.feature, src/Oro/Bundle/ConfigBundle/Resources/public/js/form/system/save.js
=> PIM-6207: correctly dispatch post fetch event on system config save

CHANGELOG-1.7.md, src/Pim/Bundle/UIBundle/Resources/public/less/lib/jquery.multiselect.less
Fix UI glitch on TWA completeness filter search field.
=> PIM-6242: fix UI glitch on TWA completeness filter search field

src/Pim/Bundle/ApiBundle/tests/integration/Controller/Attribute/PartialUpdateAttributeIntegration.php
Fix typo + tests (because the test was not launched by the CI due to the typo) …
=> Fix integration of the partial attribute update 

CHANGELOG-1.7.md, features/Context/AssertionContext.php, features/Pim/Behat/Decorator/Permission/PermissionDecorator.php, features/job-tracker/display_jobs_execution_in_job_tracker.feature, src/Pim/Bundle/EnrichBundle/Controller/JobTrackerController.php, src/Pim/Bundle/EnrichBundle/Resources/config/controllers.yml
- Fix bug
- Add behats
- Fix flash messages behat
- Fix revoke rights bug …
=> GITHUB-5538-1_7: Fix job tracker permissions

CHANGELOG-1.7.md, features/Context/DataGridContext.php, features/Context/Page/Product/Index.php, features/product/filtering/filter_products.feature
=> GITHUB-3435-1_7

CHANGELOG-1.7.md, features/Context/AssertionContext.php, features/Pim/Behat/Decorator/Permission/PermissionDecorator.php, features/job-tracker/display_jobs_execution_in_job_tracker.feature, src/Pim/Bundle/EnrichBundle/Controller/JobTrackerController.php, src/Pim/Bundle/EnrichBundle/Resources/config/controllers.yml
Revert these 3 commits cause wrong merge :(
https://github.com/akeneo/pim-community-dev/pull/5817/commits
=> Revert GitHub 5538

features/mass-action/edit_common_attributes.feature
Behats for EE Pr : https://github.com/akeneo/pim-enterprise-dev/pull/2679
=> PIM-6251: improve behats

CHANGELOG-1.7.md, features/Pim/Behat/Decorator/Permission/PermissionDecorator.php, features/job-tracker/display_jobs_execution_in_job_tracker.feature, src/Pim/Bundle/EnrichBundle/Controller/JobTrackerController.php, src/Pim/Bundle/EnrichBundle/Resources/config/controllers.yml
We merged this PR
https://github.com/akeneo/pim-community-dev/pull/5817
But it breaks the DCI
So we revert it to fix the DCI.
This is the result, already GTMed on the previous PR (no really hard changes)
=> GitHub-5538

Jenkinsfile
Fixes https://github.com/akeneo/continuous-integration/issues/149
=> Fix zombie docker container
