features/Context/catalog/footwear/attributes.csv
=> PIM-6250: fix behats

CHANGELOG-1.5.md
Add details regarding the fix of memory leak in variant group.
=> Fix #5941 (add details in changelog)

Jenkinsfile
=> ci-issue-151: Fix Jenkinsfile that does not prepare the workspace well

CHANGELOG-1.7.md, UPGRADE-1.7.md
Minor fixes in markdown rendering
=> Fix markdown typos

CHANGELOG-1.7.md, features/Context/WebUser.php, features/attribute-group/list_attribute_groups.feature, src/Pim/Bundle/EnrichBundle/Form/Type/AttributeType.php
=> GITHUB-5307-1_7

CHANGELOG-1.7.md, src/Pim/Bundle/UIBundle/Resources/public/less/components/Progress.less
Progress bar of the sequential edit was not at the right color.
No CI needed.
=> PIM-6270: Fix sequential edit style

behat.ci.yml, features/Pim/Behat/Formatter/JUnitFormatter.php
=> Display filepath of the failed behat scenarios

src/Pim/Bundle/EnrichBundle/spec/Form/Type/AttributeTypeSpec.php
Fix specs
(Remove argument because the query_builder method is not "speckable")
=> GITHUB-5307: Fix specs

src/Akeneo/Component/Localization/Presenter/DatePresenter.php
DatePresenter doesn't handle multiple dates on the value field, this PR fixes that.
| Added Behats                      | OK (EE side)
=> PIM-6269: correctly handle array of dates in rule presenter

CHANGELOG-1.6.md, src/Pim/Bundle/UIBundle/Resources/views/Form/pim-fields.html.twig
=> PIM-6241: fix changelog

CHANGELOG-1.7.md
=> fix unsecable spaces in changelog

src/Pim/Bundle/EnrichBundle/MassEditAction/Operation/EditCommonAttributes.php
=> Fix phpcs fixer

src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml
| Review and 2 GTM                  | ok
| Tech Doc …
=> Fix add attribute footer count string translation

src/Pim/Bundle/CatalogBundle/Command/CleanMongoDBCommand.php
This PR fixes MongoDB cleaning of reference data and speeds up the process
| Micro Demo to the PO (Story only) | No
Version 1.7 PR : https://github.com/akeneo/pim-community-dev/pull/6041
=> 1.6 fix clean mongodb

CHANGELOG-1.7.md, src/Pim/Bundle/UserBundle/Resources/config/doctrine/User.orm.yml
Fixes the Fatal on `/permission/rest` call
| Added integration tests           | N/A
| Tech Doc                          | N/A
=> PIM-6286: Repository user

CHANGELOG-1.7.md
=> update PIM refs on changelog

features/Pim/Behat/Context/Domain/System/PermissionsContext.php
The test was always positive with permissions, whether it was granted or revoked. 
https://github.com/akeneo/pim-community-dev/blob/1.7/features/api/acl/assert_acl.feature#L17
| Changelog …
=> Fix test on acls in behat

src/Pim/Bundle/PdfGeneratorBundle/Controller/ProductController.php, src/Pim/Bundle/PdfGeneratorBundle/Renderer/ProductPdfRenderer.php, src/Pim/Bundle/PdfGeneratorBundle/Renderer/RendererRegistry.php, src/Pim/Bundle/PdfGeneratorBundle/Resources/views/Product/renderPdf.html.twig, src/Pim/Bundle/PdfGeneratorBundle/Twig/ImageExtension.php, src/Pim/Bundle/PdfGeneratorBundle/spec/Renderer/ProductPdfRendererSpec.php
See EE for full description: https://github.com/akeneo/pim-enterprise-dev/pull/2743
=> [SLA] PIM-6325: Fix thumbnails display for assets in product PDF

app/PimRequirements.php
Suggesting PHP 5 is confusing :)
=> Clarify message about APCu requirement

CHANGELOG-1.7.md, UPGRADE-1.7.md
Add missing informations in upgrade files
| …
=> Add upgrade information about array converter

CHANGELOG-1.7.md, src/Pim/Component/Catalog/Builder/ProductBuilder.php
=> PIM-6314: Fix parameters inversion

app/phpunit.xml.dist, src/Pim/Bundle/ApiBundle/Controller/AttributeGroupController.php, src/Pim/Bundle/ApiBundle/Resources/config/acl.yml, src/Pim/Bundle/ApiBundle/Resources/config/acl_groups.yml, src/Pim/Bundle/ApiBundle/Resources/config/controllers.yml, src/Pim/Bundle/ApiBundle/Resources/config/normalizers.yml, src/Pim/Bundle/ApiBundle/Resources/config/repositories.yml, src/Pim/Bundle/ApiBundle/Resources/config/routing.yml, src/Pim/Bundle/ApiBundle/Resources/config/routing/attribute_group.yml, src/Pim/Bundle/ApiBundle/Resources/translations/messages.en.yml, src/Pim/Bundle/ApiBundle/tests/integration/Controller/AttributeGroup/GetAttributeGroupIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/AttributeGroup/ListAttributeGroupIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/RootEndpointIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Security/AttributeGroupAuthorizationIntegration.php, src/Pim/Component/Api/Normalizer/AttributeGroupNormalizer.php, src/Pim/Component/Api/spec/Normalizer/AttributeGroupNormalizerSpec.php, src/Pim/Component/Api/tests/integration/Normalizer/AttributeGroupIntegration.php, tests/catalog/technical/acl.sql
Get a single attribute group
Get list of attribute groups
=> API-166: Get a single attribute group and get list of attribute groups

CHANGELOG-1.8.md
=> cosmetic issue changelog

CHANGELOG-1.8.md
=> Fix a typo in the changelog

CHANGELOG-1.7.md
PIM-6314 (Deleting a published product raises an internal error) should be in EE changelog
=> Update changelog 1.7.4

CHANGELOG-1.8.md, features/export/product-export-builder/show_tooltips_and_errors.feature, src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml
| Q | A |
| --- | --- |
| Added Specs |  - |
| Added Behats |  - |
| Changelog updated | -  |
| Review and 2 GTM | Ok  |
| Micro Demo to the PO (Story only) |-   |
| Migration script | -  |
|  Tech Doc |  - |
=> Change tooltips of the Export Builder

CHANGELOG-1.5.md, Jenkinsfile, features/product/completeness/display_completeness.feature, src/Pim/Bundle/CatalogBundle/EventSubscriber/MongoDBODM/SetProductsSubscriber.php, src/Pim/Bundle/CatalogBundle/Resources/translations/measures.fr.yml, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/panel/completeness.js, src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/panel/completeness.html
=> Merge 15 to 16

CHANGELOG-1.8.md, features/attribute-group/delete_attribute_group.feature, features/family/display_family_history.feature, features/import/import_attribute_group.feature, features/import/xlsx/import_attribute_group.feature, features/localization/product/edit_product.feature, features/localization/product/validation/validate_number_attributes.feature, features/product/edit_product_with_many_locales.feature, features/product/validation/validate_number_attributes.feature, features/reference-data/attribute/display_attribute_history.feature, src/Pim/Bundle/ApiBundle/Controller/AttributeController.php, src/Pim/Bundle/ApiBundle/Controller/AttributeGroupController.php, src/Pim/Bundle/ApiBundle/Resources/config/acl.yml, src/Pim/Bundle/ApiBundle/Resources/config/controllers.yml, src/Pim/Bundle/ApiBundle/Resources/config/routing/attribute_group.yml, src/Pim/Bundle/ApiBundle/Resources/translations/messages.en.yml, src/Pim/Bundle/ApiBundle/tests/integration/Controller/AttributeGroup/CreateAttributeGroupIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/RootEndpointIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Security/AttributeGroupAuthorizationIntegration.php, src/Pim/Bundle/CatalogBundle/Resources/config/updaters.yml, src/Pim/Bundle/CatalogBundle/Resources/config/validation/attributegroup.yml, src/Pim/Component/Catalog/Updater/AttributeGroupUpdater.php, src/Pim/Component/Catalog/spec/Updater/AttributeGroupUpdaterSpec.php, src/Pim/Component/Catalog/tests/integration/Updater/AttributeGroupUpdaterIntegration.php, src/Pim/Component/Connector/ArrayConverter/FlatToStandard/AttributeGroup.php, src/Pim/Component/Connector/spec/ArrayConverter/FlatToStandard/AttributeGroupSpec.php, tests/catalog/technical/acl.sql
Create an Attribute Group through the API
=> API-202: Create a new attribute group

features/navigation/navigation_title.feature, src/Pim/Bundle/EnrichBundle/Resources/views/Product/edit.html.twig
This fixes https://github.com/akeneo/pim-community-dev/issues/6106
=> Fix double-escaped title (#6106)

CHANGELOG-1.7.md, src/Pim/Bundle/EnrichBundle/Controller/Rest/JobInstanceController.php
Bugfix for undefined `$parametersViolations`! If there is not raw parameters defined for the job - it will fail.
=> Fix undefined $parametersViolations

src/Pim/Bundle/ApiBundle/Controller/AttributeGroupController.php, src/Pim/Bundle/ApiBundle/Resources/config/routing/attribute_group.yml, src/Pim/Bundle/ApiBundle/tests/integration/Controller/AttributeGroup/PartialUpdateAttributeGroupIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/RootEndpointIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Security/AttributeGroupAuthorizationIntegration.php, src/Pim/Bundle/CatalogBundle/Resources/config/doctrine/AttributeGroup.orm.yml, src/Pim/Bundle/CatalogBundle/Resources/config/validation/attributegroup.yml, src/Pim/Bundle/CatalogBundle/tests/integration/Validation/AttributeGroupValidationIntegration.php, src/Pim/Component/Catalog/tests/integration/Updater/AttributeGroupUpdaterIntegration.php
Add attribute group partial update, for more details look at https://akeneo.atlassian.net/browse/API-203
=> API-203: Add attribute group partial update

src/Pim/Bundle/ApiBundle/Controller/AttributeGroupController.php, src/Pim/Bundle/ApiBundle/Resources/config/controllers.yml, src/Pim/Bundle/ApiBundle/Resources/config/routing/attribute_group.yml, src/Pim/Bundle/ApiBundle/Resources/config/stream.yml, src/Pim/Bundle/ApiBundle/tests/integration/Controller/AttributeGroup/PartialUpdateListAttributeGroupIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/RootEndpointIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Security/AttributeGroupAuthorizationIntegration.php, src/Pim/Bundle/EnrichBundle/Resources/config/bundles/fos_rest.yml
Partial update a list of attribute groups
=> API-163: partial update a list of attribute groups

app/phpunit.xml.dist, src/Pim/Bundle/ApiBundle/Controller/CurrencyController.php, src/Pim/Bundle/ApiBundle/Resources/config/acl.yml, src/Pim/Bundle/ApiBundle/Resources/config/acl_groups.yml, src/Pim/Bundle/ApiBundle/Resources/config/controllers.yml, src/Pim/Bundle/ApiBundle/Resources/config/normalizers.yml, src/Pim/Bundle/ApiBundle/Resources/config/repositories.yml, src/Pim/Bundle/ApiBundle/Resources/config/routing.yml, src/Pim/Bundle/ApiBundle/Resources/config/routing/currency.yml, src/Pim/Bundle/ApiBundle/Resources/translations/messages.en.yml, src/Pim/Bundle/ApiBundle/tests/integration/Controller/Currency/GetCurrencyIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/Currency/ListCurrencyIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/RootEndpointIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Security/CurrencyAuthorizationIntegration.php, src/Pim/Component/Api/Normalizer/CurrencyNormalizer.php, src/Pim/Component/Api/spec/Normalizer/CurrencyNormalizerSpec.php, src/Pim/Component/Api/tests/integration/Normalizer/CurrencyIntegration.php, tests/catalog/technical/acl.sql
Get a single currency and get list of currencies
=> API-165_API_182: Get a single currency and get list of currencies

CHANGELOG-1.7.md, features/attribute-group/edit_attribute_group.feature, src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/attributes/attribute-group-selector.js
c.f. https://akeneo.atlassian.net/browse/PIM-6434
=> [PIM-6434] Fix attribute group order on PEF

CHANGELOG-1.7.md, features/Context/WebUser.php, features/Pim/Behat/Decorator/Common/AddSelect/AbstractAddSelectDecorator.php, features/attribute-group/list_attribute_groups.feature, src/Pim/Bundle/EnrichBundle/Controller/Rest/AttributeGroupController.php, src/Pim/Bundle/EnrichBundle/Resources/public/js/fetcher/attribute-group-fetcher.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/manager/attribute-group-manager.js
cf https://akeneo.atlassian.net/browse/PIM-6436
=> [PIM-6436] Fix attribute group limit in Product Edit Form

CHANGELOG-1.7.md, features/Context/Page/Base/Form.php, features/Context/Page/Family/Edit.php, features/Context/WebUser.php, features/Pim/Behat/Decorator/Common/AddSelect/AbstractAddSelectDecorator.php, features/Pim/Behat/Decorator/Common/AddSelect/AttributeAddSelectDecorator.php, features/attribute-group/edit_attribute_group.feature, features/attribute/use_unique_attribute.feature, src/Pim/Bundle/EnrichBundle/Doctrine/ORM/Repository/AttributeSearchableRepository.php, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/family/edit.yml, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/product_edit.yml, src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/add-select/select.js
c.f. https://akeneo.atlassian.net/browse/PIM-6428
=> [PIM-6428] Fix usage of unique attributes on Product Edit Form and Family edition

CHANGELOG-1.7.md, src/Pim/Bundle/CatalogBundle/AttributeType/ImageType.php, src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filter/datetime-filter.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/filter/attribute/attribute.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/locale-switcher.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/scope-switcher.js, src/Pim/Bundle/EnrichBundle/Resources/public/templates/filter/attribute/date.html, src/Pim/Bundle/EnrichBundle/Resources/public/templates/filter/attribute/string.html, src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/locale-switcher.html, src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/scope-switcher.html, src/Pim/Bundle/UIBundle/Resources/public/js/pim-dialogform.js, src/Pim/Bundle/UIBundle/Resources/public/less/components/LoadingMask.less, src/Pim/Bundle/UIBundle/Resources/public/less/components/button/ButtonList.less, src/Pim/Bundle/UIBundle/Resources/public/less/components/product-edit-form/FieldContainer.less
Various BEM fixes :)
TODO Rename IM-809 en PIM-6453
=> [PIM-6414] [PIM-6384] [PIM-6453] [PIM-6423]

CHANGELOG-1.5.md, src/Pim/Bundle/EnrichBundle/Resources/config/bundles/liip_imagine.yml
Cherry-pick of https://github.com/akeneo/pim-community-dev/pull/6232
=> [PIM-6399] Change format of thumbnails to PNG

UPGRADE-1.7.md
Am I the first to read this ? :p
Some problems with spacing/tabs so we couldn't see the code formatting properly.
=> Fix UPGRADE-1.7.md to use code formatting

src/Pim/Bundle/CatalogBundle/Command/IndexProductCommand.php, src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/ProductRepository.php, src/Pim/Bundle/CatalogBundle/spec/Command/IndexProductCommandSpec.php
See: https://github.com/jjanvier/pim-community-dev/pull/244 …
=> TIP-760: Index command

Jenkinsfile, src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/CompletenessRepository.php, src/Pim/Bundle/UIBundle/Resources/public/less/components/button/ButtonList.less, src/Pim/Component/Connector/ArrayConverter/FlatToStandard/Product/AttributeColumnInfoExtractor.php, src/Pim/Component/Connector/ArrayConverter/FlatToStandard/Product/AttributeColumnsResolver.php
=> Merge 1.6 into 1.7

CHANGELOG-1.8.md, src/Pim/Bundle/ApiBundle/Controller/AttributeGroupController.php, src/Pim/Bundle/ApiBundle/Controller/ChannelController.php, src/Pim/Bundle/ApiBundle/Resources/config/api.yml, src/Pim/Bundle/ApiBundle/Resources/config/controllers.yml, src/Pim/Bundle/ApiBundle/Resources/config/routing/channel.yml, src/Pim/Bundle/ApiBundle/Resources/config/stream.yml, src/Pim/Bundle/ApiBundle/tests/integration/ApiTestCase.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/Attribute/PartialUpdateListAttributeIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/AttributeGroup/PartialUpdateAttributeGroupIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/AttributeGroup/PartialUpdateListAttributeGroupIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/Category/PartialUpdateListCategoryIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/Channel/CreateChannelIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/Channel/GetChannelIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/Channel/ListChannelIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/Channel/PartialUpdateChannelIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/Channel/PartialUpdateListChannelIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/Family/PartialUpdateListFamilyIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/PartialUpdateListProductIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/RootEndpointIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Security/ChannelAuthorizationIntegration.php, src/Pim/Bundle/CatalogBundle/Resources/config/doctrine/Channel.orm.yml, src/Pim/Bundle/EnrichBundle/Resources/config/bundles/fos_rest.yml, src/Pim/Bundle/InstallerBundle/Resources/config/fixtures_jobs.yml, src/Pim/Bundle/VersioningBundle/UpdateGuesser/TranslationsUpdateGuesser.php, src/Pim/Bundle/VersioningBundle/spec/UpdateGuesser/TranslationsUpdateGuesserSpec.php, src/Pim/Component/Api/tests/integration/Normalizer/ChannelNormalizerIntegration.php, tests/catalog/technical/channels.csv
API-205: partial update a channel
API-161: partial update list of channels
=> API-205_API-161: partial update channel & partial update list channels

app/phpunit.xml.dist, src/Pim/Bundle/ApiBundle/Controller/AssociationTypeController.php, src/Pim/Bundle/ApiBundle/Resources/config/acl.yml, src/Pim/Bundle/ApiBundle/Resources/config/acl_groups.yml, src/Pim/Bundle/ApiBundle/Resources/config/controllers.yml, src/Pim/Bundle/ApiBundle/Resources/config/normalizers.yml, src/Pim/Bundle/ApiBundle/Resources/config/repositories.yml, src/Pim/Bundle/ApiBundle/Resources/config/routing.yml, src/Pim/Bundle/ApiBundle/Resources/config/routing/association_type.yml, src/Pim/Bundle/ApiBundle/Resources/translations/messages.en.yml, src/Pim/Bundle/ApiBundle/tests/integration/Controller/AssociationType/GetAssociationTypeIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/AssociationType/ListAssociationTypeIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/RootEndpointIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Security/AssociationTypeAuthorizationIntegration.php, src/Pim/Component/Api/Normalizer/AssociationTypeNormalizer.php, src/Pim/Component/Api/spec/Normalizer/AssociationTypeNormalizerSpec.php, src/Pim/Component/Api/tests/integration/Normalizer/AssociationTypeIntegration.php, src/Pim/Component/Api/tests/integration/Normalizer/CurrencyIntegration.php, tests/catalog/technical/acl.sql
API-160: Get a single association type
API-184: Get list of association types
=> API-160_API-184: Get a single association type and get list of association types

frontend/require-context.js, package.json, webpack.config.js
This PR replaces webpack's UglifyJS with [Babili](https://babeljs.io/blog/2016/08/30/babili) because it doesn't work with Babel/es6.
| Review and 2 …
=> TIP-731: Fix uglify/minify + es6

Jenkinsfile, src/Pim/Bundle/ApiBundle/Controller/AssociationTypeController.php, src/Pim/Bundle/ApiBundle/Resources/config/api.yml, src/Pim/Bundle/ApiBundle/Resources/config/controllers.yml, src/Pim/Bundle/ApiBundle/Resources/config/routing/association_type.yml, src/Pim/Bundle/ApiBundle/Resources/config/stream.yml, src/Pim/Bundle/ApiBundle/tests/integration/Controller/AssociationType/PartialUpdateAssociationTypeIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/AssociationType/PartialUpdateListAssociationTypeIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/RootEndpointIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Security/AssociationTypeAuthorizationIntegration.php, src/Pim/Bundle/EnrichBundle/Normalizer/AssociationTypeNormalizer.php, src/Pim/Bundle/EnrichBundle/Normalizer/AttributeGroupNormalizer.php, src/Pim/Bundle/EnrichBundle/Resources/config/bundles/fos_rest.yml, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/associations.js, src/Pim/Bundle/EnrichBundle/spec/Normalizer/AssociationTypeNormalizerSpec.php
=> API-207_API-159: Add partial update and partial update list association type

src/Pim/Bundle/CatalogBundle/Resources/translations/validators.pt_BR.yml, src/Pim/Bundle/ConnectorBundle/Resources/translations/messages.pt_BR.yml, src/Pim/Bundle/DataGridBundle/Resources/translations/jsmessages.de.yml, src/Pim/Bundle/DataGridBundle/Resources/translations/messages.de.yml, src/Pim/Bundle/EnrichBundle/Resources/translations/messages.de.yml, src/Pim/Bundle/EnrichBundle/Resources/translations/messages.pl.yml, src/Pim/Bundle/UIBundle/Resources/translations/jsmessages.de.yml
This PR is a re-merge of 1.7 into master, as it was done in this one: https://github.com/akeneo/pim-community-dev/pull/6218, to resolve the "squash and merge" that was performed by mistake.
=> Merge old 1.7 into master

Jenkinsfile
=> Use official akeneo Docker images

CHANGELOG-1.6.md, src/Pim/Bundle/UIBundle/Resources/public/css/pim.less
Fix scroll issue on firefox, flex-direction is already present on parent element
[JIRA PIM-6473](https://akeneo.atlassian.net/browse/PIM-6473)
=> PIM-6473: Fix scroll issue on firefox, flex-direction is already present on parent element

docker-compose.yml.dist
=> Fix docker-compose mistake

bin/docker/pim-front.sh, bin/docker/pim-initialize.sh
This PR fixes errors in the helper scripts `bin/docker/pim-initialize.sh` and `bin/docker/pim-front.sh`.
=> Fix an error in Docker helper scripts

src/Pim/Bundle/CatalogBundle/DependencyInjection/Compiler/ResolveDoctrineTargetModelPass.php, src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/ProductModelRepository.php, src/Pim/Bundle/CatalogBundle/Entity/Category.php, src/Pim/Bundle/CatalogBundle/Resources/config/entities.yml, src/Pim/Bundle/CatalogBundle/Resources/config/model/doctrine/Product.orm.yml, src/Pim/Bundle/CatalogBundle/Resources/config/model/doctrine/ProductModel.orm.yml, src/Pim/Bundle/CatalogBundle/Resources/config/repositories.yml, src/Pim/Bundle/CatalogBundle/spec/Doctrine/ORM/Repository/ProductModelRepositorySpec.php, src/Pim/Component/Catalog/Model/AbstractProduct.php, src/Pim/Component/Catalog/Model/CategoryInterface.php, src/Pim/Component/Catalog/Model/EntityWithValuesInterface.php, src/Pim/Component/Catalog/Model/ProductInterface.php, src/Pim/Component/Catalog/Model/ProductModel.php, src/Pim/Component/Catalog/Model/ProductModelInterface.php, src/Pim/Component/Catalog/Repository/ProductModelRepositoryInterface.php, src/Pim/Component/Catalog/spec/Model/ProductModelSpec.php, src/Pim/Component/Catalog/spec/Model/ProductSpec.php
This PR introduce the new `ProductModel` entity into the PIM: class, Doctrine mapping and repository.
=> PIM-6447: Introduce the product model entity

features/Pim/Behat/Context/HookContext.php, features/Pim/Behat/Context/PimContext.php
=> TIP-747: Fix behat screenshots

src/Pim/Bundle/CatalogBundle/spec/Elasticsearch/Filter/Field/DateTimeFilterSpec.php
Currently, we can't run all spec in local if our local date.timezone is not set in Etc/UTC so this PR aims to correct this problem.
| …
=> Fix spec concerning date in local

src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/attributes/add-select/attribute/select.js
This PR fixes a js error in the select attribute module
| Migration …
=> TIP-732: Fix incorrect binding for fetchItems

features/Context/Page/Family/Edit.php, features/Context/WebUser.php, features/Pim/Behat/Context/HookContext.php, features/family/set_the_attribute_used_as_label.feature, features/import/edit_an_import.feature
With the migration to Behat 3 and the rework of some screens, some scenarios became unstable again. Here's an attempt to stabilize them.
=> Stabilize behat scenarios

features/Context/FeatureContext.php
This PR fixes php-cs issues that came up after the update
| …
=> Fix php-cs issues 

features/Context/FeatureContext.php, src/Pim/Component/Connector/ArrayConverter/StandardToFlat/Product/ValueConverter/DateConverter.php
This PR merges the php-cs fixes from 1.5  …
=> Merge 1.5 to 1.6 php-cs fixes

features/Context/catalog/catalog_modeling/family_variant.csv, features/import/family_variant/import_invalid_family_variants_data.feature, features/import/family_variant/import_invalid_family_variants_file.feature, src/Pim/Bundle/InstallerBundle/Resources/config/fixtures_jobs.yml, src/Pim/Bundle/InstallerBundle/Resources/config/job_constraints.yml, src/Pim/Bundle/InstallerBundle/Resources/config/job_defaults.yml, src/Pim/Bundle/InstallerBundle/Resources/config/jobs.yml
This PR adds family variant fixtures.
=> PIM-6448: Add family variant fixtures

CHANGELOG-1.8.md, src/Akeneo/Bundle/BatchBundle/EventListener/LoggerSubscriber.php, src/Pim/Bundle/EnrichBundle/Resources/public/js/job/execution/summary-table.js, src/Pim/Bundle/EnrichBundle/Resources/public/templates/job-execution/summary-table.html
See https://github.com/akeneo/pim-community-dev/issues/6337 for issue description
Additionally, this PR fixes javascript errors in the template rendering for summary-table so that the job execution/step execution errors can be displayed. 
Original PR - https://github.com/akeneo/pim-community-dev/pull/6416
| …
=> Write invalid items process fails when it encounters a Date field in xlsx files

features/Context/Page/Base/Base.php, features/product/classify_product.feature, features/product/history/display_removed_value_history.feature, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/categories.js, src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/tab/catalog-switcher.html, src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/tab/categories.html, src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml, src/Pim/Bundle/UIBundle/Resources/public/less/components/Badge.less
Update dropdown category switcher to transform it to horizontal navtab
=> [PIM-6490] Fix PEF categories design

upgrades/schema/Version_1_8_20170404125715.php
Fix the doctrine migration command: the class name should be the same as the file
=> Correct the name of the class

src/Pim/Bundle/CatalogBundle/DependencyInjection/PimCatalogExtension.php, src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/CanHaveVariantFamilyRepository.php, src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/ProductModelRepository.php, src/Pim/Bundle/CatalogBundle/Resources/config/family_variant.yml, src/Pim/Bundle/CatalogBundle/Resources/config/repositories.yml, src/Pim/Bundle/CatalogBundle/Resources/config/validation/productmodel.yml, src/Pim/Bundle/CatalogBundle/Resources/config/validators.yml, src/Pim/Bundle/CatalogBundle/Resources/translations/validators.en.yml, src/Pim/Bundle/CatalogBundle/tests/integration/Product/ProductModelIntegration.php, src/Pim/Component/Catalog/FamilyVariant/CanHaveFamilyVariantAttributesProvider.php, src/Pim/Component/Catalog/Model/CanHaveFamilyVariantInterface.php, src/Pim/Component/Catalog/Model/ProductModel.php, src/Pim/Component/Catalog/Model/ProductModelInterface.php, src/Pim/Component/Catalog/Repository/CanHaveVariantFamilyRepositoryInterface.php, src/Pim/Component/Catalog/Repository/ProductModelRepositoryInterface.php, src/Pim/Component/Catalog/Validator/Constraints/NotEmptyVariantAxes.php, src/Pim/Component/Catalog/Validator/Constraints/NotEmptyVariantAxesValidator.php, src/Pim/Component/Catalog/Validator/Constraints/OnlyExpectedAttributes.php, src/Pim/Component/Catalog/Validator/Constraints/OnlyExpectedAttributesValidator.php, src/Pim/Component/Catalog/Validator/Constraints/SiblingUniqueVariantAxes.php, src/Pim/Component/Catalog/Validator/Constraints/SiblingUniqueVariantAxesValidator.php, src/Pim/Component/Catalog/spec/Manager/CanHaveFamilyVariantAttributesProviderSpec.php, src/Pim/Component/Catalog/spec/Validator/Constraints/NotEmptyVariantAxesValidatorSpec.php, src/Pim/Component/Catalog/spec/Validator/Constraints/OnlyExpectedAttributesValidatorSpec.php, src/Pim/Component/Catalog/spec/Validator/Constraints/SiblingUniqueVariantAxesValidatorSpec.php
This PR adds validation on product models.
=> PIM-6448: add validation for product model

src/Pim/Component/Catalog/Normalizer/Standard/ProductModelNormalizer.php, src/Pim/Component/Catalog/spec/Normalizer/Standard/ProductModelNormalizerSpec.php
=> PIM-6333: Create product model standard normalizer

src/Akeneo/Component/StorageUtils/Exception/InvalidPropertyTypeException.php, src/Akeneo/Component/StorageUtils/spec/Exception/InvalidPropertyTypeExceptionSpec.php, src/Pim/Bundle/ApiBundle/Controller/ProductController.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/ErrorListProductIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/CompletenessFilterIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Metric/MetricFilterIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Price/PriceFilterIntegration.php, src/Pim/Component/Catalog/Exception/InvalidArgumentException.php
=> API-123: Change exception message

web/app.php
This reverts commit 2452df858191c16478913d6e8aafe749e7831f82. …
=> Revert "change debugmode to false in prod"

UPGRADE-1.8.md, features/Pim/Behat/Extension/PimFormatter/PimFormatterExtension.php, web/app.php
This PR updates the webpack section of UPGRADE-1.8.md with some additional details, and also fixed the debug mode in app.php. 
| Review …
=> Update 1.8 upgrade docs

CHANGELOG-1.8.md, features/Context/WebUser.php, src/Pim/Bundle/EnrichBundle/Controller/Rest/CategoryController.php, src/Pim/Bundle/EnrichBundle/MassEditAction/Operation/MassEditOperation.php, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/mass_edit/family.yml, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/mass_edit/product.yml, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/product/edit.yml, src/Pim/Bundle/EnrichBundle/Resources/config/form_types.yml, src/Pim/Bundle/EnrichBundle/Resources/public/js/common/select2/family.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/family/mass-edit/form-model-updater.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/mass-edit/form/choose.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/mass-edit/form/family/set-requirements.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/mass-edit/form/form.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/mass-edit/form/product/change-family.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/mass-edit/form/product/change-status.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/attributes/read-only-form.js, src/Pim/Bundle/EnrichBundle/Resources/public/templates/form/edit-form.html, src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml
=> TIP-764: fix PR comments

app/PimRequirements.php
Add imagick requirement
Issue: #6483
=> Add imagick requirement

app/PimRequirements.php
pim:installer:check-requirements not check if GD and SOAP extension is installed …
=> Add requirement check GD and SOAP

CHANGELOG-1.8.md, features/Context/Page/Base/Grid.php, features/Pim/Behat/Decorator/Grid/Filter/SearchDecorator.php, features/product/filtering/filter_products_per_label_or_identifier.feature, src/Oro/Bundle/FilterBundle/Resources/config/filters.yml, src/Pim/Bundle/CatalogBundle/Elasticsearch/Filter/Field/LabelOrIdentifierFilter.php, src/Pim/Bundle/CatalogBundle/Resources/config/query_builders.yml, src/Pim/Bundle/CatalogBundle/Resources/elasticsearch/index_configuration.yml, src/Pim/Bundle/CatalogBundle/tests/integration/PQB/AbstractProductQueryBuilderTestCase.php, src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/LabelOrIdentifierFilterIntegration.php, src/Pim/Bundle/DataGridBundle/Resources/config/requirejs.yml, src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filter/label_or_identifier-filter.js, src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/product.yml, src/Pim/Bundle/FilterBundle/Filter/Product/LabelOrIdentifierFilter.php, src/Pim/Bundle/FilterBundle/Resources/config/filters.yml, src/Pim/Component/Catalog/Normalizer/Indexing/Product/PropertiesNormalizer.php, src/Pim/Component/Catalog/Normalizer/Standard/Product/PropertiesNormalizer.php, src/Pim/Component/Catalog/spec/Normalizer/Indexing/Product/PropertiesNormalizerSpec.php
This PR add the search on label/identifier on the product grid. It does a tokenised search. …
=> PIM-6621: add search on label and identifier

CHANGELOG-1.8.md, features/Pim/Behat/Decorator/Grid/Filter/CategoryDecorator.php, features/localization/product/edit_product.feature, features/localization/product/validation/validate_number_attributes.feature, src/Akeneo/Bundle/BatchBundle/Launcher/JobLauncherInterface.php, src/Pim/Bundle/ConnectorBundle/DependencyInjection/PimConnectorExtension.php, src/Pim/Bundle/ConnectorBundle/Launcher/AuthenticatedJobLauncher.php, src/Pim/Bundle/ConnectorBundle/Resources/config/job_launchers.yml, src/Pim/Bundle/ConnectorBundle/spec/Launcher/AuthenticatedJobLauncherSpec.php, src/Pim/Bundle/EnrichBundle/Controller/Rest/JobInstanceController.php, src/Pim/Bundle/InstallerBundle/Resources/config/fixtures_jobs.yml, src/Pim/Component/Catalog/Builder/EntityWithValuesBuilder.php, src/Pim/Component/Catalog/Builder/ProductBuilder.php, src/Pim/Component/Catalog/Manager/AttributeValuesResolver.php, src/Pim/Component/Catalog/Manager/AttributeValuesResolverInterface.php, src/Pim/Component/Catalog/spec/Builder/ProductBuilderSpec.php, src/Pim/Component/Catalog/spec/Manager/AttributeValuesResolverSpec.php, src/Pim/Component/Connector/ArrayConverter/FlatToStandard/Product/AttributeColumnsResolver.php, src/Pim/Component/Connector/spec/ArrayConverter/FlatToStandard/Product/AttributeColumnsResolverSpec.php, tests/FixturesLoader.php, tests/JobLauncher.php, tests/catalog/technical/jobs.yml
Apply permissions on product export in EE.
Initialise a job launcher to transform behat tests in phpunit & integration tests for export.
Since last review: 
- add an interface `AttributeValuesResolverInterface` to allow DI in EE.
- use it everywhere instead of `AttributeValuesResolver`
- add a job launcher for the import to test the completeness in EE
- update changelog + specs
| Q …
=> Api 247: apply permission on product export 

src/Pim/Component/Catalog/tests/integration/Normalizer/Indexing/ProductIndexingIntegration.php
Fix the integration tests broken by my last PR …
=> PIM-6621: fix integration tests

frontend/requirejs-utils.js, package-lock.json
This PR removes references to the 'colors' npm package
| Migration …
=> Remove references to colors npm package

Jenkinsfile
A single line but it deserves some explanations.
- checkout is done on master nodes: there are 2 master nodes
- specs/phpcs fixer/integration tests are done on nodes called "docker" (10 nodes "docker")
- behat run on master nodes (and it's the bottleneck of the CI)
**Consequences:**
If you have 2 running behat builds, the master nodes are busy and so, locked.
All the others build will wait "milestone 2" to checkout the project, because it's waiting the availability of the master nodes.
And the specs/phcs …
=> Improve the concurrency of the CI's builds

features/Pim/Behat/Decorator/ContextSwitcherDecorator.php, features/attribute-group/delete_attribute_group.feature, features/product/history/display_removed_value_history.feature, src/Pim/Bundle/DashboardBundle/Resources/views/Dashboard/index.html.twig, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/attribute/edit.yml, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/attribute_group/edit.yml, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/attribute_group/index.yml, src/Pim/Bundle/EnrichBundle/Resources/public/js/attribute-group/form/tab/attribute.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/attribute/form/choices.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/tab.js, src/Pim/Bundle/EnrichBundle/Resources/views/CategoryTree/edit.html.twig, src/Pim/Bundle/EnrichBundle/Resources/views/CategoryTree/form.html.twig, src/Pim/Bundle/EnrichBundle/Resources/views/CategoryTree/index.html.twig, src/Pim/Bundle/EnrichBundle/Resources/views/Product/index.html.twig, src/Pim/Bundle/UIBundle/Resources/public/less/components/Breadcrumb.less, src/Pim/Bundle/UIBundle/Resources/public/less/components/TabContainer.less, src/Pim/Bundle/UIBundle/Resources/public/less/components/TitleContainer.less, src/Pim/Bundle/UIBundle/Resources/public/less/components/grid/FilterBox.less, src/Pim/Bundle/UIBundle/Resources/public/less/components/grid/GridToolbar.less, src/Pim/Bundle/UIBundle/Resources/public/less/components/product-edit-form/FormContainer.less, src/Pim/Bundle/UIBundle/Resources/public/less/lib/select2.less, src/Pim/Bundle/UIBundle/Resources/public/less/lib/tabs.less
This PR fixes some glitches:
- remaining borders on some forms
- breadcrumbs missing
- user navigation missing
=> [PIM-6486+PIM-6474] Fix breadcrumbs and borders for CE

Jenkinsfile
Should be put before pim install. 
| Migration …
=> Fix the sleep waiting the availability of elastic search container

src/Pim/Bundle/ApiBundle/Checker/QueryParametersChecker.php, src/Pim/Bundle/ApiBundle/Checker/QueryParametersCheckerInterface.php, src/Pim/Bundle/ApiBundle/Controller/LocaleController.php, src/Pim/Bundle/ApiBundle/Controller/ProductController.php, src/Pim/Bundle/ApiBundle/Resources/config/checkers.yml, src/Pim/Bundle/ApiBundle/spec/Checker/QueryParametersCheckerSpec.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/Locale/FilterLocaleIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/ErrorListProductIntegration.php
=> API-340: check if the search property is valid

CHANGELOG-1.7.md
=> Update Changelog EE 1.7.X

src/Pim/Bundle/DataGridBundle/Resources/config/requirejs.yml, src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid/cell/credentials-cell.js, src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid/cell/label-cell.js, src/Pim/Bundle/DataGridBundle/Resources/public/templates/datagrid/cell/credentials-cell.html, src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/api_connection.yml, src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/association_type.yml, src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/attribute.yml, src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/channel.yml, src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/family.yml, src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/group.yml, src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/group_type.yml, src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/job_tracker.yml, src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/locale.yml, src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/product.yml, src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/variant_group.yml, src/Pim/Bundle/EnrichBundle/Resources/public/templates/job-execution/summary-table.html, src/Pim/Bundle/ImportExportBundle/Resources/config/datagrid/job_profile.yml, src/Pim/Bundle/UIBundle/Resources/public/less/components/grid/Grid.less, src/Pim/Bundle/UserBundle/Resources/config/datagrid/group-user.yml, src/Pim/Bundle/UserBundle/Resources/config/datagrid/role-user.yml, src/Pim/Bundle/UserBundle/Resources/config/datagrid/role.yml, src/Pim/Bundle/UserBundle/Resources/config/datagrid/user-group.yml, src/Pim/Bundle/UserBundle/Resources/config/datagrid/user.yml
=> API-350: Add required style on grid label’s

CHANGELOG-1.8.md, features/Pim/Behat/Context/Storage/ProductStorage.php, features/import/product_variant/import_variant_products.feature, src/Pim/Bundle/CatalogBundle/Resources/config/builders.yml, src/Pim/Bundle/CatalogBundle/Resources/config/filters.yml, src/Pim/Bundle/CatalogBundle/Resources/config/updaters.yml, src/Pim/Bundle/ConnectorBundle/Resources/config/processors.yml, src/Pim/Component/Catalog/Updater/ProductUpdater.php, src/Pim/Component/Catalog/Updater/Setter/ParentSetter.php, src/Pim/Component/Catalog/spec/Updater/ProductUpdaterSpec.php, src/Pim/Component/Catalog/spec/Updater/Setter/ParentSetterSpec.php, src/Pim/Component/Connector/ArrayConverter/FlatToStandard/Product.php, src/Pim/Component/Connector/ArrayConverter/FlatToStandard/Product/FieldConverter.php, src/Pim/Component/Connector/Processor/Denormalization/ProductProcessor.php, src/Pim/Component/Connector/spec/Processor/Denormalization/ProductProcessorSpec.php
This PR updates the product import to allow the variant product without any validation. It will add in another PR.
=> PIM-6335: Import variant product

upgrades/SchemaHelper.php, upgrades/schema/Version_1_8_20170823082403_udapte_client_label.php
=> API-347: add migration script to put id in empty label

behat.ci.yml, behat.yml.dist, features/Context/Page/ProductModel/Edit.php, features/Pim/Behat/Context/Domain/Enrich/ProductModelContext.php, features/product-model/edit_product_model.feature, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/product_model/edit.yml
This PR adds first behats for the enrich of product models.
=> PIM-6338: add behats for product model enrich

features/Context/AssertionContext.php, features/product/date.feature, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/history.js, src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/history.html, src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml, src/Pim/Bundle/UIBundle/Resources/public/images/icon-right.svg, src/Pim/Bundle/UIBundle/Resources/public/less/components/Badge.less, src/Pim/Bundle/UIBundle/Resources/public/less/components/Diff.less, src/Pim/Bundle/UIBundle/Resources/public/less/components/button/Button.less, src/Pim/Bundle/UIBundle/Resources/public/less/components/grid/Grid.less
| Added integration tests           | n
=> [PIM-6578] Update history design

features/Context/DataGridContext.php, features/product/filtering/filter_products_and_product_models.feature, src/Pim/Bundle/DataGridBundle/Datasource/ProductDatasource.php, src/Pim/Bundle/DataGridBundle/Normalizer/ProductModelNormalizer.php, src/Pim/Bundle/DataGridBundle/Normalizer/ProductNormalizer.php, src/Pim/Bundle/DataGridBundle/Resources/config/data_sources.yml, src/Pim/Bundle/DataGridBundle/Resources/config/normalizers.yml, src/Pim/Bundle/DataGridBundle/spec/Normalizer/ProductModelNormalizerSpec.php
- Introduce a new datasource to display products and product models (use PQB of products and models)
- Introduces a datagrid normalizer for the product models (May change in the future)
=> PIM-6352: Display product models and product in datagrid

features/import/variant_product/import_business_rules.feature, features/import/variant_product/import_variant_products.feature, src/Pim/Bundle/CatalogBundle/Resources/config/validation/variantproduct.yml
=> PIM-6335: Skip variant product without variant axes values

features/Context/WebUser.php, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/attribute/file.yml, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/attribute/image.yml, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/attribute/text.yml, src/Pim/Bundle/EnrichBundle/Resources/public/js/attribute/form/edit-form.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/attribute/form/properties/available-locales.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/attribute/form/properties/boolean.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/attribute/form/properties/date.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/attribute/form/properties/default-metric-unit.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/attribute/form/properties/field.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/attribute/form/properties/group.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/attribute/form/properties/localizable.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/attribute/form/properties/metric-family.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/attribute/form/properties/scopable.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/attribute/form/properties/select.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/attribute/form/properties/text.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/attribute/form/properties/type.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/controller/attribute/create.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/jstree/jquery.jstree.nested_switch.js, src/Pim/Bundle/EnrichBundle/Resources/public/templates/attribute-group/tab/attribute.html, src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml, src/Pim/Bundle/ReferenceDataBundle/Resources/public/js/attribute/form/properties/ref-data-name.js, src/Pim/Bundle/UIBundle/Resources/public/js/pim-ui.js, src/Pim/Bundle/UserBundle/Resources/views/User/update.html.twig
This is PR fixes several glitches introduced by https://github.com/akeneo/pim-community-dev/pull/6179.
=> Fix glitches on attributes form

src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/attributes.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/attributes/attribute-group-selector.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/attributes/completeness.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/provider/to-fill-field-provider.js, src/Pim/Bundle/EnrichBundle/Resources/public/templates/form/tab/attributes/attribute-group-selector.html
In this PR we add a badge on the "All attributes" selector. I also fixed the locale/scope switching bug that happened previously
=> PIM-6671: add badge on all attribute group selector

CHANGELOG-1.8.md, features/user/create_and_delete_user.feature, src/Pim/Bundle/UserBundle/Form/Subscriber/UserPreferencesSubscriber.php, src/Pim/Bundle/UserBundle/Resources/config/form_types.yml
=> PIM-6531: Have English language as default language for new users

features/product/edit_and_display_all_attributes.feature, src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml
Fix the wording of the PIM-6762 PR
=> PIM-6762: fix wording

Jenkinsfile, src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/ErrorListProductIntegration.php, src/Pim/Bundle/CatalogBundle/Resources/elasticsearch/index_configuration.yml, src/Pim/Bundle/CatalogBundle/tests/integration/Elasticsearch/IndexConfiguration/AbstractPimCatalogProductModelIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/Elasticsearch/IndexConfiguration/SearchProductsAndModelsIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/Elasticsearch/IndexConfiguration/SearchProductsIntegration.php, src/Pim/Bundle/ConnectorBundle/tests/integration/Command/AuthenticatedBatchCommandIntegration.php, src/Pim/Bundle/DataGridBundle/Datasource/ProductDatasource.php, src/Pim/Bundle/DataGridBundle/Normalizer/ProductModelNormalizer.php, src/Pim/Bundle/DataGridBundle/Normalizer/ProductNormalizer.php, src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid/cell/completeness-cell.js, src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid/cell/enabled-cell.js, src/Pim/Bundle/DataGridBundle/spec/Normalizer/ProductModelNormalizerSpec.php, src/Pim/Bundle/DataGridBundle/spec/Normalizer/ProductNormalizerSpec.php, src/Pim/Bundle/EnrichBundle/Elasticsearch/Cursor.php, src/Pim/Bundle/EnrichBundle/Elasticsearch/CursorFactory.php, src/Pim/Bundle/EnrichBundle/Elasticsearch/FromSizeCursor.php, src/Pim/Bundle/EnrichBundle/Elasticsearch/FromSizeCursorFactory.php, src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/product.yml, src/Pim/Bundle/EnrichBundle/Resources/public/js/datagrid/action/navigate-product-and-product-model-action.js, src/Pim/Bundle/EnrichBundle/spec/Elasticsearch/CursorSpec.php, src/Pim/Bundle/EnrichBundle/spec/Elasticsearch/FromSizeCursorSpec.php, src/Pim/Component/Catalog/Normalizer/Indexing/ProductAndProductModel/ProductModelNormalizer.php, src/Pim/Component/Catalog/Normalizer/Indexing/ProductAndProductModel/ProductNormalizer.php, src/Pim/Component/Catalog/spec/Normalizer/Indexing/ProductAndProductModel/ProductModelNormalizerSpec.php, src/Pim/Component/Catalog/spec/Normalizer/Indexing/ProductAndProductModel/ProductNormalizerSpec.php, src/Pim/Component/Catalog/tests/integration/Normalizer/Indexing/ProductAndProductModelIndexingIntegration.php
GTMed here https://github.com/akeneo/pim-community-dev/pull/6665 . Opened a new branch because CI build wouldn't start.
=> Rename product type & Fix catalog modeling

src/Pim/Bundle/EnrichBundle/Elasticsearch/ProductAndProductModelQueryBuilderFactory.php, src/Pim/Bundle/EnrichBundle/Resources/config/query_builders.yml, src/Pim/Bundle/EnrichBundle/Resources/config/readers.yml
Replaces https://github.com/akeneo/pim-community-dev/pull/6664 due to a Jenkins problem.
The previous PR has the 2 GTM
=> PIM-6352: small fixes

src/Pim/Bundle/CatalogBundle/Elasticsearch/Filter/Field/ParentFilter.php, src/Pim/Bundle/CatalogBundle/Resources/config/query_builders.yml, src/Pim/Bundle/CatalogBundle/Resources/elasticsearch/index_configuration.yml, src/Pim/Bundle/CatalogBundle/spec/Elasticsearch/Filter/Field/ParentFilterSpec.php, src/Pim/Bundle/CatalogBundle/tests/helper/EntityBuilder.php, src/Pim/Bundle/CatalogBundle/tests/integration/Doctrine/Common/Saver/IndexingProductModelDescendantsIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/PQB/AbstractProductAndProductModelQueryBuilderTestCase.php, src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/ParentFilterIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/PQB/ProductAndProductModelQueryBuilderIntegration.php, src/Pim/Bundle/EnrichBundle/ProductQueryBuilder/ProductAndProductModelQueryBuilder.php, src/Pim/Bundle/EnrichBundle/spec/ProductQueryBuilder/ProductAndProductModelQueryBuilderSpec.php
This PR adds an elasticsearch PQB filter for "parent" IN field.
=> PIM-6347: add IN for parent filter in ES

features/Context/Page/Base/Form.php, features/Context/WebUser.php, features/product/edit_product_and_filter_attributes.feature, src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/attributes.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/attributes/attribute-group-selector.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/group-selector.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/attribute-filter.js, src/Pim/Bundle/EnrichBundle/Resources/public/templates/form/tab/attributes/attribute-group.html
Add a filter on attributes when clicking on the attribute group header
=> PIM-6761: add filter on header click

src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/api_connection/create.yml, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/association_type/create.yml, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/export/create-profile.yml, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/family/create.yml, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/group/create.yml, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/group_type/create.yml, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/import/create-profile.yml, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/product/create.yml, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/variant_group/create.yml, src/Pim/Bundle/EnrichBundle/Resources/config/requirejs.yml, src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/creation/modal.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/product-completeness.js, src/Pim/Bundle/EnrichBundle/Resources/public/templates/form/creation/modal.html, src/Pim/Bundle/UIBundle/Resources/public/less/lib/modal.less, src/Pim/Bundle/UIBundle/Resources/public/less/pages/FullPage.less
- API connection
- Association type
- import profile
- export profile
- family
- group
- group type
- product
- variant group
=> [PIM-6576] Use new UI for creation modal

features/datagrid/products_category_backtothegrid.feature, src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid/grid.js, src/Pim/Bundle/DataGridBundle/Resources/translations/jsmessages.en.yml, src/Pim/Bundle/DataGridBundle/Resources/translations/messages.en.yml, src/Pim/Bundle/EnrichBundle/Resources/config/requirejs.yml, src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/attributes.js, src/Pim/Bundle/EnrichBundle/Resources/public/templates/common/no-data.html, src/Pim/Bundle/UIBundle/Resources/public/less/base/variables.less, src/Pim/Bundle/UIBundle/Resources/public/less/components/grid/GridContainer.less
- on datagrids
- on PEF when there is no attributes
=> [PIM-6755] Add new design for "no results"

features/user/edit_my_account.feature, src/Oro/Bundle/UserBundle/Controller/UserController.php
When you remove edit profile permissions, and you go on your own profile and change something, it displays an error saying you do not have the permission to do this, but you should as it's your own profile.
=> PIM-6258: Fix issues onuser profile permission

features/product-model/navigate_product_and_product_model_edit_page.feature
Add missing behat for the navigation in product edit form and product model edit form.
=> PIM-6352: Add missing behat testing the navigation from the product grid

features/Context/Page/Base/Grid.php, features/mass-action/mass_edit_products_and_product_models.feature, features/product-model/edit_product_model.feature, features/product/filtering/filter_products_and_product_models.feature
This PR fixes the last remaining broken behats after updating the "catalog_modeling" functional catalog.
=> PIM-6743: Fix remaining broken behats

CHANGELOG-1.5.md, features/filter/identifier.feature, features/filter/string.feature, src/Oro/Bundle/FilterBundle/Filter/StringFilter.php, src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Filter/StringFilter.php
=> Merge15 16

src/Akeneo/Bundle/BatchBundle/Command/PurgeJobExecutionCommand.php
Improve the command message, as it keeps the last job execution. (cf https://akeneo.atlassian.net/browse/PIM-5664 )
=> SDS-1215: improve command to make it more understandable

CHANGELOG-2.0.md, features/Context/catalog/apparel/jobs.yml, features/Context/catalog/catalog_modeling/jobs.yml, features/Context/catalog/footwear/jobs.yml, features/import/edit_an_import.feature, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/job_instance/csv_base_import_edit.yml, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/job_instance/csv_product_import_edit.yml, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/job_instance/csv_product_model_import_edit.yml, src/Pim/Bundle/InstallerBundle/Resources/config/fixtures_jobs.yml, src/Pim/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev/jobs.yml, tests/catalog/technical/jobs.yml
| Added integration tests           | no
=> PIM-6228: remove escape field from export builder config

src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filter/product_category-filter.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/grid/category-tree.js
=> PIM-6536: fix double load on datagrid

tests/JobLauncher.php
=> API-349: testing job launcher is able to wait for a job execution

app/config/config.yml, src/Pim/Bundle/EnrichBundle/Resources/config/bundles/doctrine.yml, src/Pim/Bundle/EnrichBundle/Resources/config/bundles/fos_auth_server.yml, src/Pim/Bundle/EnrichBundle/Resources/config/pim.yml
The more configuration we have in the files `pim.yml` and `pimee.yml`, the less we have to update the `config.yml` files of standard editions and EE dev edition.
=> Fix configurations of the bundles

src/Pim/Bundle/ConnectorBundle/tests/integration/Export/ProductModel/ExportProductModelsIntegration.php, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/job_instance/xlsx_product_model_export_edit.yml, src/Pim/Component/Connector/ArrayConverter/StandardToFlat/ProductModel.php, src/Pim/Component/Connector/Job/JobParameters/ConstraintCollectionProvider/ProductModelCsvExport.php, src/Pim/Component/Connector/Job/JobParameters/DefaultValuesProvider/ProductModelCsvExport.php, src/Pim/Component/Connector/spec/ArrayConverter/StandardToFlat/ProductModelSpec.php
Taking in account Delphine's feedback:
- fix decimal separator & datetime format
- remove categories field (until it's implemented for models)
- add the lines per file configuration for product model excel
=> PIM-6737 Delphine's feedback

src/Pim/Bundle/UIBundle/Resources/public/less/components/ColumnConfigurator.less, src/Pim/Bundle/UIBundle/Resources/public/less/components/grid/FilterBox.less, src/Pim/Bundle/UIBundle/Resources/public/less/lib/jquery.jstree.less
=> [PIM-6654] Fix style for asset picker

features/Context/DataGridContext.php, features/Pim/Behat/Decorator/Page/GridCapableDecorator.php, src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/creation/modal.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/grid/view-selector-create-view.js, src/Pim/Bundle/EnrichBundle/Resources/public/templates/form/creation/modal.html, src/Pim/Bundle/EnrichBundle/Resources/public/templates/grid/view-selector-create-view-label-input.html, src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml
Updates the creation popin with new design for view.
=> [PIM-6586] Set creation popins

src/Pim/Bundle/EnrichBundle/Resources/config/requirejs.yml, src/Pim/Bundle/EnrichBundle/Resources/public/js/controller/logout.js
The logout was broken with the new navigation, here's a quick win to make it usable again.
It reloads the page, but there's no real other solution until we rework completely the authentication.
=> PIM-6643: Fix navigation bug after logout

.gitignore, bin/docker/pim-dependencies.sh, bin/docker/pim-front.sh, bin/docker/pim-initialize.sh, docker-compose.yml.dist
This PR adds some helper scripts for Docker on Akeneo 1.6, so all maintained versions will possess the same scripts when 2.0 is released.
=> Add some helper scripts for Docker

CHANGELOG-2.0.md
Prepare the 2.0.0-ALPHA1 release
=> Prepare 2.0.0-ALPHA1 release

src/Oro/Bundle/DataGridBundle/Extension/Toolbar/Configuration.php, src/Pim/Bundle/DataGridBundle/Resources/public/lib/backbone-pageable.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/fos-routing-wrapper.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/menu/item.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/menu/tab.js, src/Pim/Bundle/EnrichBundle/Resources/public/templates/menu/item.html, src/Pim/Bundle/EnrichBundle/Resources/public/templates/menu/tab.html
=> PIM-6592: switch back to 25 items per grid and open in new tab

src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/product_model/edit.yml
=> PIM-6741: Add product model code in the PEF header

README.md
=> Update readme for 2.0 release

src/Pim/Bundle/ApiBundle/Controller/MediaFileController.php, src/Pim/Bundle/ApiBundle/Controller/ProductController.php, src/Pim/Bundle/ApiBundle/tests/integration/ApiTestCase.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/GetProductIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/SuccessLargeAndOrderedListProductIntegration.php, src/Pim/Component/Connector/Processor/Denormalization/ProductAssociationProcessor.php, src/Pim/Component/Connector/Processor/Denormalization/ProductProcessor.php, tests/JobLauncher.php
=> API-246: apply permissions on products import

src/Pim/Bundle/CatalogBundle/Command/IndexProductCommand.php, src/Pim/Bundle/CatalogBundle/Command/IndexProductModelCommand.php, src/Pim/Bundle/CatalogBundle/spec/Command/IndexProductCommandSpec.php, src/Pim/Bundle/CatalogBundle/spec/Command/IndexProductModelCommandSpec.php, src/Pim/Component/Catalog/Model/EntityWithFamilyVariantInterface.php, src/Pim/Component/Catalog/Model/ProductModel.php, src/Pim/Component/Catalog/Model/ProductModelInterface.php, src/Pim/Component/Catalog/Model/VariantProduct.php, src/Pim/Component/Catalog/Model/VariantProductInterface.php
| Changelog updated                 | 
=> PIM-6448: fix setParent API on both variants and models

src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid/cell/boolean-label-cell.js, src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid/cell/completeness-cell.js, src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid/cell/enabled-cell.js, src/Pim/Bundle/DataGridBundle/Resources/views/Property/activated.html.twig, src/Pim/Bundle/EnrichBundle/Resources/public/js/menu/item.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/menu/tab.js, src/Pim/Bundle/EnrichBundle/Resources/views/CategoryTree/index.html.twig, src/Pim/Bundle/UIBundle/Resources/public/less/base/general.less, src/Pim/Bundle/UIBundle/Resources/public/less/base/variables.less, src/Pim/Bundle/UIBundle/Resources/public/less/components/Breadcrumb.less, src/Pim/Bundle/UIBundle/Resources/public/less/components/Column.less, src/Pim/Bundle/UIBundle/Resources/public/less/components/Header.less, src/Pim/Bundle/UIBundle/Resources/public/less/components/NotificationMenu.less, src/Pim/Bundle/UIBundle/Resources/public/less/components/ProjectWidget.less, src/Pim/Bundle/UIBundle/Resources/public/less/components/TitleContainer.less, src/Pim/Bundle/UIBundle/Resources/public/less/components/button/ButtonList.less, src/Pim/Bundle/UIBundle/Resources/public/less/components/button/SelectButton.less, src/Pim/Bundle/UIBundle/Resources/public/less/components/grid/FilterBox.less, src/Pim/Bundle/UIBundle/Resources/public/less/components/grid/GridToolbar.less, src/Pim/Bundle/UIBundle/Resources/public/less/components/product-edit-form/CompletenessPanel.less, src/Pim/Bundle/UIBundle/Resources/public/less/lib/select2.less
Just style glitches raised by Lucas!
=> [style] Fix some style

src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/variant-navigation.js
Temporary put a blank placeholder.
=> Remove placeholder

upgrades/1.7-2.0/Version_2_0_20170404125715.php, upgrades/1.7-2.0/Version_2_0_20170821122627_add_client_in_access_token_table.php, upgrades/1.7-2.0/Version_2_0_20170823082403_udapte_client_label.php, upgrades/1.7-2.0/Version_2_0_20170925181205_add_default_parameters_in_job_instances.php, upgrades/SchemaHelper.php
Add "user_to_notify" key and "is_user_authenticated" key in the job instances's configuration
| …
=> Api 337: migration script to add "user_to_notify" and "is_user_authenticated" in job instance configuration

src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/grid.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/grid/table.js
=> PIM-6592: fix pagination to 25

src/Pim/Bundle/UIBundle/Resources/public/less/components/TitleContainer.less, src/Pim/Bundle/UIBundle/Resources/public/less/pages/Default.less
Fix this issue:
https://github.com/akeneo/pim-community-dev/issues/6847
=> [GIT-6847] Fix sticky header

src/Pim/Bundle/VersioningBundle/Command/RefreshCommand.php
=> Fix: The helper "progress" is not defined.

CHANGELOG-2.0.md
=> Add changelog for #6866

CHANGELOG-2.0.md
=> Add changelog for #6824

CHANGELOG-2.0.md, src/Pim/Bundle/EnrichBundle/Resources/public/js/menu/column.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/menu/item.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/menu/tab.js
Adds route params management in the menu item extension
| Added Specs                       | `-`
| Added Behats                      | `-`
| Added integration tests           | `-`
| Changelog updated                 | `-`
| Review and 2 GTM                  | `-`
| Micro Demo to the PO (Story only) | `-`
| Migration script                  | `-`
| Tech Doc                          | `-`
=> Add route params management

CHANGELOG-2.0.md, src/Pim/Bundle/ApiBundle/Controller/ProductModelController.php, src/Pim/Bundle/ApiBundle/Resources/config/controllers.yml, src/Pim/Bundle/ApiBundle/Resources/config/routing.yml, src/Pim/Bundle/ApiBundle/Resources/config/routing/product_model.yml, src/Pim/Bundle/ApiBundle/tests/integration/Controller/ProductModel/GetProductModelIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/RootEndpointIntegration.php
=> API-377: Be able to get a product model with API

src/Pim/Bundle/ApiBundle/Controller/ProductController.php, src/Pim/Bundle/ApiBundle/Resources/config/controllers.yml, src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/CreateVariantProductIntegration.php, src/Pim/Bundle/CatalogBundle/Resources/config/validation/variantproduct.yml, src/Pim/Bundle/CatalogBundle/Resources/config/validators.yml, src/Pim/Bundle/CatalogBundle/Resources/translations/validators.en.yml, src/Pim/Bundle/CatalogBundle/tests/integration/Product/CreateVariantProductIntegration.php, src/Pim/Component/Catalog/Validator/Constraints/NotEmptyFamily.php, src/Pim/Component/Catalog/Validator/Constraints/NotEmptyFamilyValidator.php, src/Pim/Component/Catalog/Validator/Constraints/NotEmptyVariantAxes.php, src/Pim/Component/Catalog/Validator/Constraints/NotEmptyVariantAxesValidator.php, src/Pim/Component/Catalog/Validator/Constraints/SameFamilyThanParent.php, src/Pim/Component/Catalog/Validator/Constraints/SameFamilyThanParentValidator.php, src/Pim/Component/Catalog/Validator/Constraints/VariantProductParent.php, src/Pim/Component/Catalog/Validator/Constraints/VariantProductParentValidator.php, src/Pim/Component/Catalog/spec/Validator/Constraints/NotEmptyFamilyValidatorSpec.php, src/Pim/Component/Catalog/spec/Validator/Constraints/NotEmptyVariantAxesValidatorSpec.php, src/Pim/Component/Catalog/spec/Validator/Constraints/SameFamilyThanParentValidatorSpec.php, src/Pim/Component/Catalog/spec/Validator/Constraints/VariantProductParentValidatorSpec.php, tests/catalog/technical/family_variants.csv
=> API-372: Create variant product though API

CHANGELOG-2.0.md, features/product-model/edit_product_model.feature, src/Pim/Bundle/EnrichBundle/Resources/public/js/product-model/form/complete-variant-product.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/variant-navigation.js
Correctly display a product model if it has no product children.
=> PIM-6861: Correctly display a product model if it has no product children

features/family/list_family_variant.feature, src/Pim/Bundle/DataGridBundle/Datasource/FamilyVariantDatasource.php, src/Pim/Bundle/DataGridBundle/Datasource/RepositoryDatasource.php, src/Pim/Bundle/DataGridBundle/EventListener/AddParametersToGridListener.php, src/Pim/Bundle/DataGridBundle/Normalizer/FamilyVariantNormalizer.php, src/Pim/Bundle/DataGridBundle/Resources/config/data_sources.yml, src/Pim/Bundle/DataGridBundle/Resources/config/normalizers.yml, src/Pim/Bundle/DataGridBundle/spec/Normalizer/FamilyVariantNormalizerSpec.php, src/Pim/Bundle/EnrichBundle/Doctrine/ORM/Repository/FamilyVariantRepository.php, src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/family_variant.yml, src/Pim/Bundle/EnrichBundle/Resources/config/datagrid_listeners.yml, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/family/edit.yml, src/Pim/Bundle/EnrichBundle/Resources/config/repositories.yml, src/Pim/Bundle/EnrichBundle/Resources/config/requirejs.yml, src/Pim/Bundle/EnrichBundle/Resources/public/js/family/form/family-variant.js, src/Pim/Bundle/EnrichBundle/Resources/public/templates/family/tab/family-variant.html, src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml
Add the family variant list page
| Micro Demo to the PO (Story only) | Done
=> PIM-6856: List family variant on family edit page

CHANGELOG-2.0.md
=> Update changelog to prepare the 2.0.1 release

CHANGELOG-2.0.md
=> API-379: update changelog with new API endpoints

composer.json
To fix reference environment deploy
=> Prepare 2.1 branch

features/job-execution/last-execution/export.feature, features/job-execution/last-execution/import.feature, src/Pim/Bundle/EnrichBundle/Resources/config/datagrid_listeners.yml
=> API-398: Only view logged user jobs in job last executions view

features/job-execution/last-execution/export.feature, features/job-execution/last-execution/import.feature, src/Pim/Bundle/EnrichBundle/Doctrine/ORM/Repository/JobExecutionRepository.php, src/Pim/Bundle/EnrichBundle/Resources/config/datagrid_listeners.yml, src/Pim/Bundle/EnrichBundle/tests/integration/Repository/JobExecutionRepositoryIntegration.php, src/Pim/Bundle/ImportExportBundle/Manager/JobExecutionManager.php, src/Pim/Bundle/ImportExportBundle/Resources/config/managers.yml
=> API-397: Only view logged user jobs in “LAST OPERATIONS” widget

Jenkinsfile, composer.json
=> Configure ci

CHANGELOG-2.0.md, features/Pim/Behat/Context/NavigationContext.php, features/acl/assert_acl.feature, src/Pim/Bundle/EnrichBundle/Resources/config/requirejs.yml
=> PIM-6865: fix acl on import profile page

CHANGELOG-2.0.md, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/api_connection/index.yml, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/association_type/index.yml, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/attribute/index.yml, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/channel/index.yml, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/common/menu.yml, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/currency/index.yml, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/family/index.yml, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/group/index.yml, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/group_type/index.yml, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/import/index-profile.yml, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/locale/index.yml, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/process_tracker/index.yml, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/user/index-group.yml, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/user/index-role.yml, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/user/index-user.yml, src/Pim/Bundle/EnrichBundle/Resources/public/js/menu/logo.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/menu/tab.js, src/Pim/Bundle/EnrichBundle/Resources/public/templates/menu/logo.html, src/Pim/Bundle/EnrichBundle/Resources/public/templates/menu/menu.html, src/Pim/Bundle/EnrichBundle/Resources/public/templates/menu/tab.html, src/Pim/Bundle/UIBundle/Resources/public/less/components/Header.less
Updates the menu order
Card says:
"dashboard, products, assets (EE), imports, exports, settings and system."
=> [PIM-6584] Update main menu order

CHANGELOG-2.0.md, src/Pim/Bundle/EnrichBundle/Resources/public/js/mass-edit/form/product/edit-common-attributes.js
=> [PIM-6881] Fix edit common attributes design

features/navigation/navigation_title.feature, features/product-model/navigate_product_and_product_model_edit_page.feature, src/Oro/Bundle/UserBundle/Resources/translations/jsmessages.en.yml, src/Pim/Bundle/EnrichBundle/Resources/public/js/controller/entity-with-family-variant.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/page-title.js, src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml, src/Pim/Bundle/EnrichBundle/Resources/translations/messages.en.yml, src/Pim/Bundle/EnrichBundle/Resources/views/CategoryTree/edit.html.twig, src/Pim/Bundle/EnrichBundle/Resources/views/CategoryTree/form.html.twig, src/Pim/Bundle/ImportExportBundle/Resources/translations/jsmessages.en.yml, src/Pim/Bundle/ImportExportBundle/Resources/translations/messages.en.yml, src/Pim/Bundle/UserBundle/Resources/views/User/update.html.twig, src/Pim/Bundle/UserBundle/Resources/views/User/view.html.twig
There are missing titles or missing parameters
=> [PIM-6776] Set page title for every page

CHANGELOG-2.0.md, src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/field/multi-select.html, src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/field/simple-select.html, src/Pim/Bundle/UIBundle/Resources/public/images/icon-remove.svg, src/Pim/Bundle/UIBundle/Resources/public/less/components/button/IconButton.less, src/Pim/Bundle/UIBundle/Resources/public/less/components/grid/FilterBox.less, src/Pim/Bundle/UIBundle/Resources/public/less/components/product-edit-form/TextField.less, src/Pim/Bundle/UIBundle/Resources/public/less/lib/select2.less
Replace old cross icons with new ones.
=> [PIM-6539] Fix cross icons

CHANGELOG-2.0.md, src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/ProductRepository.php, src/Pim/Bundle/CatalogBundle/Resources/config/repositories.yml, src/Pim/Bundle/CatalogBundle/spec/Doctrine/ORM/Repository/ProductRepositorySpec.php, src/Pim/Bundle/CatalogBundle/spec/Doctrine/ORM/Repository/VariantProductRepositorySpec.php, src/Pim/Bundle/EnrichBundle/Controller/Rest/ValuesController.php, src/Pim/Bundle/EnrichBundle/Resources/config/controllers.yml, src/Pim/Component/Catalog/Repository/ProductRepositoryInterface.php
=> PIM-6805: Remove variant group, fix some glitches

CHANGELOG-2.0.md, src/Pim/Bundle/ApiBundle/Controller/ProductController.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/CreateProductIntegration.php
=> API-394: Warn API user if he try to use “variant_group” field in POST/PATCH product

features/family/show_family_variant.feature, src/Pim/Bundle/EnrichBundle/Controller/Rest/AttributeController.php, src/Pim/Bundle/EnrichBundle/Controller/Rest/FamilyController.php, src/Pim/Bundle/EnrichBundle/Controller/Rest/FamilyVariantController.php, src/Pim/Bundle/EnrichBundle/Extension/Action/Actions/EditInModalAction.php, src/Pim/Bundle/EnrichBundle/Normalizer/FamilyVariantNormalizer.php, src/Pim/Bundle/EnrichBundle/Resources/config/controllers.yml, src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/family_variant.yml, src/Pim/Bundle/EnrichBundle/Resources/config/datagrid_actions.yml, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/family_variant/edit.yml, src/Pim/Bundle/EnrichBundle/Resources/config/normalizers.yml, src/Pim/Bundle/EnrichBundle/Resources/config/providers.yml, src/Pim/Bundle/EnrichBundle/Resources/config/requirejs.yml, src/Pim/Bundle/EnrichBundle/Resources/config/routing/family.yml, src/Pim/Bundle/EnrichBundle/Resources/public/js/datagrid/action/edit-in-modal-action.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/family-variant/form/axes.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/family-variant/form/edit.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/family-variant/form/save.js, src/Pim/Bundle/EnrichBundle/Resources/public/templates/family-variant/axes.html, src/Pim/Bundle/EnrichBundle/Resources/public/templates/family-variant/edit.html, src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml, src/Pim/Bundle/UIBundle/Resources/config/assets.yml, src/Pim/Bundle/UIBundle/Resources/public/images/connector-end.svg, src/Pim/Bundle/UIBundle/Resources/public/images/connector-start.svg, src/Pim/Bundle/UIBundle/Resources/public/less/components/FamilyVariant.less, src/Pim/Bundle/UIBundle/Resources/public/less/lib/modal.less, src/Pim/Bundle/UIBundle/Resources/public/lib/bootstrap-modal.js
This PR add the family variant show screen
=> PIM-6857: add family variant show form

src/Pim/Component/Connector/Processor/Denormalization/ProductProcessor.php
This PR fixes a EE bug (revealed by a broken integration test).
When importing a product without having the rights to even view this product, the import stop with an error. This is a wrong behavior introduced very recently (it is OK in 2.0.1), as the import should only skip the product with a warning.
The bug was caused by a filter that thrown an exception it didn't previously. This exception was only catch during product retrieval from database (after the data filtering).
The fix consists in catching the two possible exceptions at once in the same `try/catch`. …
=> Fix filtering in product imports

CHANGELOG-2.0.md
Fix an entry in the changelog that was put in 2.0.2 when it will in fact be in 2.0.3.
=> PIM-6898: Update changelog

src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/history.js
This PR makes sure that the grid actions of the history grid panel (same component used for products, product models and variant products) are correctly initialized.
=> PIM-6896: Always initialize history form actions

CHANGELOG-2.0.md, src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filter/multiselect-filter.js, src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filter/select-filter.js, src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filter/text-filter.js, src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/grid/column-inner.html, src/Pim/Bundle/UIBundle/Resources/public/less/components/Column.less, src/Pim/Bundle/UIBundle/Resources/public/less/components/NotificationList.less, src/Pim/Bundle/UIBundle/Resources/public/less/components/TitleContainer.less, src/Pim/Bundle/UIBundle/Resources/public/less/components/button/ButtonList.less, src/Pim/Bundle/UIBundle/Resources/public/less/components/button/IconButton.less, src/Pim/Bundle/UIBundle/Resources/public/less/components/grid/FilterBox.less, src/Pim/Bundle/UIBundle/Resources/public/less/lib/jquery.multiselect.less, src/Pim/Bundle/UIBundle/Resources/public/less/lib/select2.less
Go to the ticket to see the asked changes.
=> [PIM-6868] Fix CSS compilation

CHANGELOG-2.0.md, src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/family_variant.yml, src/Pim/Bundle/EnrichBundle/Resources/public/js/filter/attribute/attribute.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/locale-switcher.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/scope-switcher.js, src/Pim/Bundle/EnrichBundle/Resources/public/templates/filter/attribute/date.html, src/Pim/Bundle/EnrichBundle/Resources/public/templates/filter/attribute/media.html, src/Pim/Bundle/EnrichBundle/Resources/public/templates/filter/attribute/number.html, src/Pim/Bundle/EnrichBundle/Resources/public/templates/filter/attribute/select.html, src/Pim/Bundle/EnrichBundle/Resources/public/templates/filter/filter.html, src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/locale-switcher.html, src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/scope-switcher.html, src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/tab/catalog-switcher.html, src/Pim/Bundle/UIBundle/Resources/public/less/components/FamilyVariant.less, src/Pim/Bundle/UIBundle/Resources/public/less/components/product-edit-form/FieldContainer.less, src/Pim/Bundle/UIBundle/Resources/public/less/components/product-edit-form/TextField.less, src/Pim/Bundle/UIBundle/Resources/public/less/lib/select2.less
Fix product export builder on each fields 
Before:
Now :
=> [PIM-6848] Fix design on product export builder

CHANGELOG-2.0.md, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/product_model/edit.yml, src/Pim/Bundle/UIBundle/Resources/public/less/components/product-edit-form/FormContainer.less
I just put the right extension, and everything magically works !
=> [PIM-6903] Add compare-translate extension for product model

STANDARD_FORMAT.md
See https://github.com/akeneo/pim-community-dev/pull/6637
I merged in the wrong branch, sorry :(
Already reviewed.
=> PIM-6335: standard format

src/Akeneo/Bundle/ElasticsearchBundle/tests/integration/ResetIndexesCommandIntegration.php, tests/IntegrationTestsBundle/Launcher/CommandLauncher.php
Integration tests PR only.
Changes the way the Integration test commandLauncher run commands to accept interactive inputs.
=> TIP-810: Reset indexes command integration tests

src/Akeneo/Bundle/ElasticsearchBundle/tests/integration/ResetIndexesCommandIntegration.php
=> TIP-810: Fix integration tests

CHANGELOG-2.0.md, src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml
=> [PIM-6909] Replace products by results

CHANGELOG-2.0.md, src/Pim/Bundle/ApiBundle/Controller/ProductModelController.php, src/Pim/Bundle/ApiBundle/Resources/config/controllers.yml, src/Pim/Bundle/ApiBundle/Resources/config/routing/product_model.yml, src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/AbstractProductTestCase.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/ProductModel/CreateProductModelIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/ProductModel/PartialUpdateProductModelIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/RootEndpointIntegration.php, src/Pim/Component/Catalog/ProductModel/Filter/ProductModelAttributeFilter.php, src/Pim/Component/Catalog/Updater/FamilyVariantUpdater.php, src/Pim/Component/Catalog/spec/ProductModel/Filter/ProductModelAttributeFilterSpec.php
This PR allow updates of Product model via the API
| Added integration tests           | Yes
=> API-404: Update product model via API

features/Context/WebUser.php, src/Pim/Bundle/UIBundle/Resources/public/js/pim-dialogform.js
On this PR we fix the asset creation popin. The popin doesn't show validation error but it was already the case on 1.7. If we want to fix it, we need to invest a bit more
=> PIM-6870: fix the asset creation

src/Pim/Bundle/UIBundle/Resources/public/js/pim-dialogform.js
=> Fix broken JS code style

CHANGELOG-2.0.md
=> Update changelog, adding LocaleType bug fix

src/Pim/Bundle/UserBundle/Doctrine/ORM/Repository/UserRepository.php
Fixes the user repository in case of empty array passed
=> PIM-6935: fix user repository in case of empty group id

src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/attributes.js
Fix sort order on attribute groups for the product edit form
=> PIM-6922: fix sort order on attribute groups

src/Pim/Bundle/CatalogBundle/Command/IndexProductCommand.php, src/Pim/Bundle/CatalogBundle/spec/Command/IndexProductCommandSpec.php
=> pim:index:product command with identifiers

CHANGELOG-2.0.md, src/Pim/Bundle/ApiBundle/Controller/ProductModelController.php, src/Pim/Bundle/ApiBundle/Resources/config/api.yml, src/Pim/Bundle/ApiBundle/Resources/config/controllers.yml, src/Pim/Bundle/ApiBundle/Resources/config/routing/product_model.yml, src/Pim/Bundle/ApiBundle/Resources/config/stream.yml, src/Pim/Bundle/ApiBundle/tests/integration/Controller/ProductModel/PartialUpdateListProductModelIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/RootEndpointIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Security/CategoryAuthorizationIntegration.php, src/Pim/Component/Catalog/ProductModel/Filter/ProductModelAttributeFilter.php
This PR allow you to update a list of product models
| Added integration tests           | Yes
| Review and 2 GTM                  | 1/2
=> API-405: Update a list of Product Models

src/Pim/Bundle/ApiBundle/tests/integration/Controller/ProductModel/CreateProductModelIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/ProductModel/PartialUpdateProductModelIntegration.php, src/Pim/Component/Catalog/Updater/ProductModelUpdater.php, src/Pim/Component/Catalog/spec/Updater/ProductModelUpdaterSpec.php
=> API-408: fix wrong error message.

src/Pim/Bundle/CatalogBundle/Resources/config/event_subscribers.yml
=> TIP-816 Remove dangling reference to ProductTemplateAttributeSubscriber

CHANGELOG-1.6.md
added next version and github issue number and the cheers!
=> Update changelog with new contrib

CHANGELOG-2.0.md
=> API-408: add changelog

features/Context/Page/Product/Edit.php, features/Context/WebUser.php, features/attribute-group/list_attribute_groups.feature, src/Pim/Bundle/DataGridBundle/Resources/public/js/pageable-collection.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/attribute-group/form/list.js, src/Pim/Bundle/EnrichBundle/Resources/public/templates/form/tab/attributes/attribute-group.html, src/Pim/Bundle/UIBundle/Resources/public/less/components/button/ButtonList.less
New css class to fix the regenerate button of assets
| Added Specs                       |  NA
=> PIM-6880: fix asset regenerate button

.ci/Jenkinsfile, .ci/akeneo-behat.conf, .ci/behat.community.yml, .ci/behat.enterprise.yml, .ci/k8s/pubsub_consumer_job.yaml, Dockerfile, composer.json, features/Context/WebApiContext.php, src/Akeneo/Bundle/StorageUtilsBundle/spec/Doctrine/MongoDBODM/Cursor/CursorSpec.php, src/Akeneo/Bundle/StorageUtilsBundle/spec/Doctrine/ORM/Cursor/CursorSpec.php, src/Akeneo/Component/StorageUtils/spec/Cursor/PaginatorSpec.php
=> Add Continuous Integration v2 support

src/Pim/Bundle/CatalogBundle/Command/CleanMongoDBCommand.php
=> Avoid to index values with numerical key

CHANGELOG-1.7.md, features/import/delete_an_import.feature, src/Pim/Bundle/EnrichBundle/Resources/public/js/remover/job-instance-export-remover.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/remover/job-instance-import-remover.js, src/Pim/Bundle/EnrichBundle/Resources/public/spec/remover/JobInstanceExportRemoverSpec.js, src/Pim/Bundle/EnrichBundle/Resources/public/spec/remover/JobInstanceImportRemoverSpec.js
Original PR: https://github.com/akeneo/pim-community-dev/pull/7102 to fix #6414.
=> GIT-6414: fix mistakenly passed route parameter

CHANGELOG-2.0.md, features/product/order_attributes.feature, src/Pim/Bundle/EnrichBundle/Resources/public/js/attribute-group/form/tab/attribute.js
Fixes the sort of attributes in attribute groups.
=> PIM-6489: fix the sort of attributes in attribute groups

CHANGELOG-2.0.md, app/PimRequirements.php, app/config/config_prod.yml
https://github.com/akeneo/pim-docs/blob/master/install_pim/system_requirements/system_requirements.rst.inc
=> PIM-6833 Sync PIM requirements from the doc

.ci/Jenkinsfile, src/Pim/Bundle/ApiBundle/tests/integration/Controller/AttributeOption/PartialUpdateAttributeOptionIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/FamilyVariant/CreateFamilyVariantIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/FamilyVariant/PartialUpdateFamilyVariantIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/RootEndpointIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Security/FamilyVariantAuthorizationIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/Completeness/CalculateCompletenessOnFamilyUpdateIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/Family/UpdateFamilyVariantIntegration.php
CI green in CE: http://core-contrib-ci.akeneo.com/job/akeneo/job/pim-community-dev/job/PR-7167/4/display/redirect
=> API-400: fix integration tests due to previous PR on updating family variants with the API

src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.fr.yml
=> Fix french translations

.ci/Jenkinsfile, .ci/k8s/pubsub_consumer_job.yaml, features/export/product-export-builder/export_products_by_specific_date.feature
=> Enable verbose mode

src/Pim/Bundle/CatalogBundle/Doctrine/ORM/CompletenessGenerator.php
=> Ensure commit batch size value is always an int

src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid/cell/boolean-status-cell.js, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/attribute/create.yml, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/attributes/add-select/attribute/select.js, src/Pim/Bundle/EnrichBundle/Resources/public/templates/family/tab/attributes/toolbar.html, src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml
This PR fixes some errors on attribute forms
=> [PIM-7010] Various fixes

features/Context/DataGridContext.php, features/Context/catalog/catalog_modeling/jobs.yml, src/Pim/Bundle/EnrichBundle/Resources/config/normalizers.yml
=> PIM-6364: use the chained form provider instead of an explicit provider

.ci/Jenkinsfile
=> Do not execute integration tests tagged @ce when executing EE tests

CHANGELOG-2.1.md
For michel tag (still need manual work with it though, I tested on fork).
=> Prepare alpha release

.ci/Jenkinsfile, .ci/k8s/pubsub_consumer_job.yaml
=> enable verbose and integration test

Jenkinsfile
=> Fix checkout of EE to get the master branch instead of 2.0

src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid/column/action-column.js, src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid/product-row.js, src/Pim/Bundle/DataGridBundle/Resources/public/templates/datagrid/row/product.html
This PR updates the product-row js to make it more extensible. 
=> PIM-6481: Make product thumbnail row more extensible

src/Pim/Bundle/CatalogBundle/Version.php
=> Change version codename to unknown

CHANGELOG-2.1.md
=> Prepare changelog for alpha

CHANGELOG-2.0.md
=> PIM-6567: add command to create missing job instance in changelog

src/Pim/Bundle/EnrichBundle/Connector/Processor/MassEdit/Product/AddToExistingProductModelProcessor.php, src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/product/create-button.js, src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml, src/Pim/Bundle/EnrichBundle/spec/Connector/Processor/MassEdit/Product/AddToExistingProductModelProcessorSpec.php, src/Pim/Bundle/UIBundle/Resources/public/less/base/variables.less, src/Pim/Bundle/UIBundle/Resources/public/less/pages/FullPage.less
This PR fixes last minute remarks of my dear PO
=> [PIM-6349] Various fixes

CHANGELOG-2.0.md
=> PIM-6567: fix changelog

features/Context/FixturesContext.php
Baby improvement for our tests. On the step:
``` 
And the following product values:
| product      | attribute              | value                                   | locale | scope     |
| tshirt-white | name                   | White t-shirt                           | en_US  |           |
| tshirt-white | name                   | White t-shirt                           | en_GB  |           |
| tshirt-white | name                   | T-shirt blanc                           | fr_FR  |           |
| tshirt-white | name                   | Weißes T-Shirt                          | de_DE  |           |      
```
we will create & refresh the product `tshirt-white` 4 times :( 
It's really boring to debug, you can't have the full product with all product values.
This PR aggregates all data in …
=> Avoid to update product on each values

src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filter/search-filter.js, src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filters-list.js, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/product/index.yml
See EE PR
https://github.com/akeneo/pim-enterprise-dev/pull/3352
=> [PIM-7029] Better move of search filters

src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form.js
Fix the spread operator use on form.js
=> PIM-7024: fix spread operator use

src/Pim/Bundle/EnrichBundle/Resources/public/js/form/config-provider.js
_There is a trend (as always in javascript) about giving actual hint about problem resolution in exception. THis works really really well (in particular with Redux and React and I would like to introduce it on the PIM._
**Here is a proposition to add more contextual error messages on the PIM to ease debug:**
In this particular case, the loading of the form_extension configuration, is the first load made to the REST API. Right now, on the 2.0 (and previous version), if you misconfigured your http server, your PIM was stuck at the loading stage and only a 404 error was displayed on the javascript console.
Now, with this change, we display a more meaningful error explaining what is the real reason behind this error and how to solve it.
So …
=> Add a mod_rewrite warning

app/phpunit.xml.dist, src/Pim/Bundle/ApiBundle/tests/integration/Controller/FamilyVariant/GetFamilyVariantIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/FamilyVariant/ListFamilyVariantIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/MeasureFamily/GetMeasureFamilyIntegration.php
Allow in phpunit configuration to have risky tests. Risky tests is a test without assertion, it happens in some test, or when you throw a PHP exception which is considering as something as not tested by phpunit ¯\_(ツ)_/¯
`OK`: Done / …
=> Fix integration tests

.ci/Jenkinsfile
Cherry pick of Gaël to fix the CI.
Integration tests are always green without it.
CI is red but that means this PR works => merged !
=> Fix false positive integration tests on master 

src/Pim/Bundle/UIBundle/Resources/public/less/components/product-edit-form/AssetCollectionField.less
=> Fix asset attribute

src/Pim/Component/Api/Repository/SearchAfterPageableRepositoryInterface.php
=> API-428: add search after pagination repository interface

CHANGELOG-2.1.md, src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid/cell/complete-variant-product-cell.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/tab/history.js
This PR fixes a bunch of CSS glitches
=> PIM-6917: CSS Glitch Volume 3

features/mass-action/classify_product_model.feature, features/mass-action/mass_edit_products_and_product_models.feature, src/Pim/Bundle/EnrichBundle/Connector/Reader/MassEdit/FilteredProductAndProductModelReader.php, src/Pim/Bundle/EnrichBundle/spec/Connector/Reader/MassEdit/FilteredProductAndProductModelReaderSpec.php
=> PIM-6163: fix behats

composer.json
=> Update composer alias for branch 2.1

CHANGELOG-2.1.md, src/Pim/Bundle/ApiBundle/Controller/AttributeOptionController.php, src/Pim/Bundle/ApiBundle/Resources/config/api.yml, src/Pim/Bundle/ApiBundle/Resources/config/controllers.yml, src/Pim/Bundle/ApiBundle/Resources/config/routing/attribute.yml, src/Pim/Bundle/ApiBundle/Resources/config/stream.yml, src/Pim/Bundle/ApiBundle/tests/integration/Controller/AttributeOption/PartialUpdateListAttributeOptionIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/RootEndpointIntegration.php
API-415: Update a list of options of a simple or multi select attribute
=> API-415: Update a list of options of a simple or multi select attribute

CHANGELOG-2.1.md
Merge Philippe commit because he merged a PR on master instead of 2.1.
So we cherry-picked his commit, change the changelog and merge the PR on 2.1.
Then merge 2.1 on master for the commit on the changelog.
`-`: Not …
=> Merge 21 into master

CHANGELOG-1.7.md, src/Pim/Bundle/CatalogBundle/Doctrine/ORM/CompletenessGenerator.php
Add indexes on the temporary tables to reduce by many orders of magnitude the duration of the task.
=> PIM-7054 optimize completeness generator

src/Pim/Bundle/UIBundle/Resources/public/less/components/grid/Grid.less
This PR fixes the text truncation on gallery grid items
=> PIM-6917: Fix grid css glitches

features/Context/Page/Batch/Operation.php, features/localization/mass-action/edit_common_attributes.feature
This PR fixes a few french Behat scenarios that were broken since we merged new translations this morning.
=> Fix french translation in mass edit behats

src/Pim/Bundle/UIBundle/Resources/public/less/components/product-edit-form/TextField.less
Related to https://github.com/akeneo/pim-enterprise-dev/pull/3398
=> [PIM-6972] Fix dropzone

composer.json
This PR upgrade Symfony to the latest LTS which is 3.4.2
| Changelog updated                 | ?
=> Upgrade Symfony to 3.4.2

src/Pim/Bundle/DashboardBundle/Resources/translations/jsmessages.en.yml, src/Pim/Bundle/EnrichBundle/Resources/public/templates/family/tab/family-variant.html
Fix missing translations on Dashboard
=> [PIM-6912] Fix missing translations

CHANGELOG-2.0.md
=> Fix a typo in 2.0 changelog

CHANGELOG-1.7.md
=> Fix a typo in 1.7 changelog

src/Akeneo/Bundle/BatchQueueBundle/Command/JobQueueConsumerCommand.php
When consuming the queue, a job can run few seconds (less than 5). For example, a calculation fo the completeness when modifying a product model (and impacting children). 
In that case, most of the time was spent at waiting the next update of the healthcheck (due to the sleep in the loop). 
So, the next job to consume was not done before 5 seconds, which is wasted time. 
When there are a lot of small jobs to run, it could lead to scalability problems. For example, a lot of modification of product models. 
This commit improves it by checking more often that the process is still running far more often, but does not update the healthcheck with the same frequency (to not overload the database).
Without this optimization, it generates fails …
=> Impove update of the healthcheck in the daemon (scalability optimisation)

CHANGELOG-1.7.md
=> Merge 1.7 into 2.0

CHANGELOG-2.1.md, features/Context/FeatureContext.php, features/Context/Page/Base/ProductEditForm.php, features/Pim/Behat/Context/Domain/Enrich/CompletenessContext.php, features/Pim/Behat/Decorator/Completeness/DropdownDecorator.php, features/product-model/edit_product_model.feature, features/product-model/navigate_among_variant_entities.feature, features/product/completeness/completeness_dropdown.feature, features/product/edit_and_display_all_attributes.feature, features/product/edit_variant_product.feature, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/product/edit.yml, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/product_model/edit.yml, src/Pim/Bundle/EnrichBundle/Resources/config/requirejs.yml, src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/attributes.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product-model/form/complete-variant-product.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/attributes/read-only-parent-attributes.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/product-completeness.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/total-missing-required-attributes.js, src/Pim/Bundle/EnrichBundle/Resources/public/templates/common/default-template.html, src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/form/product-completeness.html, src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/form/total-missing-required-attributes.html, src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml, src/Pim/Bundle/UIBundle/Resources/public/less/components/TitleContainer.less, src/Pim/Bundle/UIBundle/Resources/public/less/components/product-edit-form/FieldContainer.less
This PR contains a lot of small improvements to navigate among entities on the PEF.
=> PIM-6924: Navigate to complete the missing attributes

src/Pim/Bundle/CatalogBundle/Version.php
=> Update name of the version for the 2.1

CHANGELOG-2.1.md
=> Update changelog CE 2.1

.ci/Jenkinsfile, .ci/k8s/pubsub_consumer_job.yaml, src/Pim/Bundle/ConnectorBundle/tests/integration/Export/ProductQueryBuilder/ExportProductsByFilesIntegration.php
=> CLOUD-437 : 2.0 fix gcloud image and meta tag

.ci/Jenkinsfile
=> Remove composer / yarn / npm shared cache - master

.ci/Jenkinsfile
=> Remove composer / yarn / npm shared cache - 2.0

Jenkinsfile
Fix a typo in Jenkinsfile for CI v1.
=> Fix EE version in CI v1

src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/mass_edit/product.yml, src/Pim/Bundle/EnrichBundle/Resources/public/js/mass-edit/form/product/category.js, src/Pim/Bundle/EnrichBundle/Resources/public/templates/mass-edit/form.html, src/Pim/Bundle/EnrichBundle/Resources/public/templates/mass-edit/product/category.html, src/Pim/Bundle/UIBundle/Resources/public/less/components/Steps.less, src/Pim/Bundle/UIBundle/Resources/public/less/components/TabContainer.less
On this PR, you will find some updates for the EE PR
- allows using specific fetcher for category mass edit
- fix style
- disable tree on confirm step
=> [PIM-6947] Fix mass edit

.ci/Jenkinsfile, .ci/k8s/pubsub_consumer_job.yaml
=> CLOUD-437 : 2.1 fix gcloud image and meta tag

CHANGELOG-1.7.md, src/Pim/Bundle/UserBundle/Form/Type/UserType.php
=> [PIM-7031] Fix required field

CHANGELOG-2.0.md, features/Context/catalog/catalog_modeling/jobs.yml, features/attribute-group/delete_attribute_group.feature, features/export/product-export-builder/export_variant_products_by_specific_date.feature, features/user/edit_user_group_and_role_assignations.feature, src/Pim/Bundle/CatalogBundle/Resources/config/model/doctrine/VariantAttributeSet.orm.yml, src/Pim/Bundle/CatalogBundle/tests/integration/Attribute/RemoveVariantAttributeIntegration.php, src/Pim/Bundle/EnrichBundle/Controller/Rest/AttributeGroupController.php, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/mass_edit/product.yml, src/Pim/Bundle/EnrichBundle/Resources/public/js/mass-edit/form/product/category.js, src/Pim/Bundle/EnrichBundle/Resources/public/templates/mass-edit/form.html, src/Pim/Bundle/EnrichBundle/Resources/public/templates/mass-edit/product/category.html, src/Pim/Bundle/UIBundle/Resources/public/less/components/Steps.less, src/Pim/Bundle/UIBundle/Resources/public/less/components/TabContainer.less, src/Pim/Component/Catalog/Normalizer/Indexing/Product/PropertiesNormalizer.php, src/Pim/Component/Catalog/spec/Normalizer/Indexing/DateTimeNormalizerSpec.php, src/Pim/Component/Catalog/spec/Normalizer/Indexing/Product/PropertiesNormalizerSpec.php, src/Pim/Component/Catalog/spec/Normalizer/Storage/DateTimeNormalizerSpec.php, upgrades/schema/Version_2_0_20171221083904_add_delete_cascade_on_variant_attribute_set.php
Following the merge of this PR https://github.com/akeneo/pim-community-dev/pull/7387
=> Merge 2.0 -> 2.1

CHANGELOG-2.1.md
=> PIM-7074: Fix changelog

CHANGELOG-2.0.md, features/user/create_and_delete_user.feature, src/Pim/Bundle/UIBundle/Resources/public/js/init-layout.js
Select a user on the grid, then select the secondary action and try to delete the user : nothing happens, you're not even able to go backwards or quit the page.. only Cancel button works. 
=> PIM-6955: fix delete user

CHANGELOG-2.0.md, src/Pim/Bundle/ApiBundle/Controller/MediaFileController.php, src/Pim/Bundle/ApiBundle/Resources/config/controllers.yml, src/Pim/Bundle/ApiBundle/tests/integration/Controller/Media/CreateProductMediaFileIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/Media/CreateProductModelMediaFileIntegration.php, src/Pim/Component/Catalog/Validator/Constraints/OnlyExpectedAttributesValidator.php, src/Pim/Component/Catalog/spec/Validator/Constraints/OnlyExpectedAttributesValidatorSpec.php, tests/IntegrationTestsBundle/Security/SystemUserAuthenticator.php
Be able to send update product model with media files.
=> API-543: update product model with media file via API

CHANGELOG-2.0.md, src/Pim/Bundle/UIBundle/Resources/public/less/lib/select2.less
Just a revert before patching because it breaks some behats
=> Revert of Pim 6965 

features/Pim/Behat/Context/Domain/SecondaryActionsContext.php, features/Pim/Behat/Context/NavigationContext.php, features/product-model/remove.feature
=> PIM-7067: test the UI to delete product models

CHANGELOG-2.0.md
=> PIM-6874: Fix changelog 2.0

CHANGELOG-2.0.md, src/Pim/Bundle/ApiBundle/Controller/ProductController.php, src/Pim/Bundle/ApiBundle/Resources/config/controllers.yml, src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/AbstractProductTestCase.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/CreateProductIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/CreateVariantProductIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/DeleteProductIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/DeleteVariantProductIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/ErrorListProductIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/GetProductIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/GetVariantProductIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/ListProductWithCompletenessIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/PartialUpdateListProductIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/PartialUpdateListVariantProductIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/PartialUpdateProductIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/PartialUpdateProductToVariantIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/PartialUpdateProductVariantIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/SuccessLargeAndOrderedListProductIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/SuccessListProductIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/SuccessListVariantProductIntegration.php, src/Pim/Component/Catalog/EntityWithFamilyVariant/AddParent.php
=> API-516: Be able to add parent to a product via API

docker-compose.yml.dist
Given that according to the documentation, the docker compose file is used for development and testing purposes only, the elasticsearch container can run in development mode and the documentation https://docs.akeneo.com/master/install_pim/docker/installation_docker.html#elasticsearch could be simplified because the procedure is for develpment mode. See https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run-dev-mode …
=> Run elasticsearch container in development mode

CHANGELOG-2.2.md
See contribution PR here for more details: https://github.com/akeneo/pim-community-dev/pull/6943
=> Add "aaa2000" contribution to the changelog

CHANGELOG-2.0.md, src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/SuccessListVariantProductDeltaIntegration.php, src/Pim/Component/Catalog/tests/integration/Normalizer/NormalizedProductCleaner.php
Only tests here, to be sure it works well.
=> API-566: updated filter works on product variant if its product models were updated

app/PimRequirements.php
=> Use port when checking requirements

CHANGELOG-2.0.md
=> PIM-7144: Fix changelog

docker/httpd.conf
This change is mandatory with recent version of the "httpd" image. Without it, it is not possible to run containers anymore.
https://github.com/docker-library/httpd/pull/87#commitcomment-27128090
=> Add MPM module to Apache Docker configuration

.ci/Jenkinsfile
cf https://github.com/akeneo/pim-community-dev/pull/7572
=> CLOUD-483: Use google container builder to build docker image

src/Pim/Bundle/ApiBundle/DependencyInjection/PimApiExtension.php, src/Pim/Bundle/ApiBundle/Resources/config/checkers.yml, src/Pim/Bundle/ApiBundle/Resources/config/controllers.yml, src/Pim/Bundle/ApiBundle/Resources/config/filters.yml, src/Pim/Component/Catalog/Validator/Constraints/NotEmptyVariantAxesValidator.php, src/Pim/Component/Catalog/spec/Validator/Constraints/NotEmptyVariantAxesValidatorSpec.php
- Use cached repository when needed.
- Do not rely on connector bundle in the API bundle
=> API-578/575: Fix bugs on permissions about catalog modeling

composer.json
=> Pulling up 2.2 into master

features/Pim/Behat/Context/DBALPurger.php, features/Pim/Behat/Context/HookContext.php
Delete everything in one transaction.
Avoid overriding in EE, responsible of triggering the purge two times in EE.
=> Improve database purge

features/Pim/Behat/Context/DBALPurger.php, features/Pim/Behat/Context/HookContext.php, src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.de.yml, src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.fi.yml, src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.it.yml, src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.ja.yml
=> Merge 2.0 into 2.1

src/Pim/Bundle/CatalogBundle/Version.php
=> Fix Versions.php to 2.3

CHANGELOG-2.2.md, src/Pim/Bundle/CatalogBundle/Version.php
This reverts commit b421824863018800689bde2b88f2976824a756bb.
=> Revert "Preparing version 2.2-ALPHA0"

CHANGELOG-2.1.md, features/Pim/Behat/Context/DBALPurger.php, features/Pim/Behat/Context/HookContext.php, features/job-tracker/filter_job_executions.feature, src/Pim/Bundle/DataGridBundle/Resources/translations/jsmessages.da.yml, src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/job_tracker.yml, src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.da.yml, src/Pim/Bundle/EnrichBundle/Resources/translations/messages.da.yml, src/Pim/Bundle/UIBundle/Resources/translations/jsmessages.da.yml
=> Merge 2.1 in 2.2

.ci/Jenkinsfile
This reverts commit ecceafbe0ec94024c48e77e8c6737ba14717afc1.
=> Revert "CI - Fix issue "Warning: touch(): Unable to create""

CHANGELOG-2.2.md, src/Pim/Component/Catalog/ProductModel/ImageAsLabel.php, src/Pim/Component/Catalog/spec/ProductModel/ImageAsLabelSpec.php
=> PIM-7106: Display the 1st variant product created as product model image

src/Pim/Bundle/ApiBundle/DependencyInjection/PimApiExtension.php, src/Pim/Bundle/ApiBundle/Resources/config/checkers.yml, src/Pim/Bundle/ApiBundle/Resources/config/controllers.yml, src/Pim/Bundle/ApiBundle/Resources/config/filters.yml, src/Pim/Component/Catalog/Validator/Constraints/ImmutableVariantAxesValuesValidator.php, src/Pim/Component/Catalog/Validator/Constraints/NotEmptyVariantAxesValidator.php, src/Pim/Component/Catalog/spec/Validator/Constraints/NotEmptyVariantAxesValidatorSpec.php
Temporary branch. Everything has been GTM.
=> Permissions catalog modeling

CHANGELOG-2.0.md, features/mass-action/quick_export_with_media.feature, src/Pim/Bundle/EnrichBundle/Connector/Processor/QuickExport/ProductAndProductModelProcessor.php, src/Pim/Bundle/EnrichBundle/spec/Connector/Processor/QuickExport/ProductAndProductModelProcessorSpec.php
See #7649 for the description. The fix is basically the same, but it couldn't be pulled up as it is. The name of the Processor has changed, the method `process` has been modified, as well as the interface of the values collection. And besides, there's no specs for this class in 1.6/1.7 …
=> PIM-7170 Fix media files unnecessarily generated during quick export

CHANGELOG-2.0.md, features/product/completeness/remove_completeness.feature, src/Pim/Bundle/CatalogBundle/Command/RemoveCompletenessForChannelAndLocaleCommand.php, src/Pim/Bundle/CatalogBundle/Doctrine/ORM/CompletenessRemover.php, src/Pim/Bundle/CatalogBundle/Resources/config/removers.yml, src/Pim/Bundle/CatalogBundle/spec/Doctrine/ORM/CompletenessRemoverSpec.php, src/Pim/Bundle/EnrichBundle/EventListener/Storage/ChannelLocaleSubscriber.php, src/Pim/Bundle/EnrichBundle/Resources/config/event_listeners.yml, src/Pim/Bundle/EnrichBundle/Resources/translations/messages.en.yml, src/Pim/Bundle/EnrichBundle/spec/EventListener/Storage/ChannelLocaleSubscriberSpec.php, src/Pim/Bundle/UIBundle/Resources/public/less/components/Notification.less
The process was synchronous and if a lot of products were impacted the processus was too long to finished. Moreover, there was a memory leak which does not allow to make the process asynchronous.
Each bug are fixed.
=> PIM-7155: Fix remove a locale from a channel

.ci/behat.enterprise.yml
Following the changes made https://github.com/akeneo/pim-enterprise-dev/pull/3618
=> Merge: Fix behat.enterprise.yml

.ci/Jenkinsfile, composer.json, features/Context/Page/Base/Grid.php, src/Pim/Bundle/ReferenceDataBundle/DataGrid/Extension/Formatter/Property/ReferenceDataProperty.php
This PR brings several improvements to the Jenkinsfile:
- removes some useless `composer require` calls, as dev dependencies are already present in `composer.json`
- always build the CE ORM variant of the PIM, so we can always run unit tests and code style if asked
previously, if you asked a EE ODM build only for example, unit tests and code style were not ran
- fix the versions of the dev dependencies in `composer.json`
| Migration …
=> Minor fixes on the Jenkinsfile

src/Pim/Bundle/ApiBundle/Controller/ProductModelController.php
=> Permission catalog modeling product models

CHANGELOG-2.1.md, src/Pim/Bundle/CatalogBundle/Version.php
This reverts commit 509ec32bf0c79917a6f275495e90632d5e17deaa.
=> Revert "Preparing version 2.1.5"

tests/Integration/AppKernelTest.php
=> Fix cache & logs directories for integration tests

src/Pim/Bundle/UIBundle/Resources/translations/messages.en.yml
https://crowdin.com/translate/akeneo/431/en-bs#q=page+to+poad
=> Fix translation from Crowdin

CHANGELOG-1.6.md
Add latest contrib, with thanks to the changelog.
=> Add amansilla contrib on changelog

CHANGELOG-1.6.md
=> Fix typo in CHANGELOG

CHANGELOG-2.0.md
Add Changelog for last community PR
=> GITHUB-7752: Add Changelog

CHANGELOG-2.0.md, src/Akeneo/Bundle/ElasticsearchBundle/Cursor/AbstractCursor.php, src/Akeneo/Bundle/ElasticsearchBundle/spec/Cursor/CursorSpec.php, src/Akeneo/Bundle/ElasticsearchBundle/spec/Cursor/FromSizeCursorSpec.php, src/Akeneo/Bundle/ElasticsearchBundle/spec/Cursor/SearchAfterSizeCursorSpec.php, src/Pim/Component/Connector/Reader/Database/ProductReader.php
This is a backport of https://github.com/akeneo/pim-community-dev/pull/7641
=> PIM-7183: Try to fix bug on product export

CHANGELOG-2.2.md, features/Context/catalog/apparel/users.csv, features/user/edit_user.feature, src/Pim/Bundle/UserBundle/Entity/User.php, src/Pim/Bundle/UserBundle/Entity/UserInterface.php, src/Pim/Bundle/UserBundle/Form/Type/UserType.php, src/Pim/Bundle/UserBundle/Normalizer/UserNormalizer.php, src/Pim/Bundle/UserBundle/Resources/config/doctrine/User.orm.yml, src/Pim/Bundle/UserBundle/Resources/translations/messages.en.yml, src/Pim/Bundle/UserBundle/Resources/views/User/Tab/interfaces.html.twig, src/Pim/Bundle/UserBundle/Resources/views/User/view.html.twig, src/Pim/Component/Connector/ArrayConverter/FlatToStandard/User.php, src/Pim/Component/Connector/spec/ArrayConverter/FlatToStandard/UserSpec.php, src/Pim/Component/Connector/spec/ArrayConverter/StandardToFlat/UserSpec.php, src/Pim/Component/User/Updater/UserUpdater.php, upgrades/schema/Version_2_2_20180308081108_add_user_timezone.php
Add timezone field to UserForm
=> AOB-55: Allow users to setup her own timezone

CHANGELOG-2.2.md, src/Akeneo/Bundle/BatchBundle/EventListener/LoggerSubscriber.php, src/Akeneo/Bundle/BatchBundle/Launcher/SimpleJobLauncher.php, src/Akeneo/Bundle/BatchBundle/Resources/config/services.yml, src/Akeneo/Bundle/BatchBundle/spec/EventListener/LoggerSubscriberSpec.php, src/Akeneo/Bundle/BatchBundle/spec/Launcher/SimpleJobLauncherSpec.php, src/Akeneo/Bundle/BatchQueueBundle/Command/PublishJobToQueueCommand.php, src/Akeneo/Bundle/BatchQueueBundle/Launcher/QueueJobLauncher.php, src/Akeneo/Bundle/BatchQueueBundle/Resources/config/services.yml, src/Akeneo/Bundle/BatchQueueBundle/spec/Launcher/QueueJobLauncherSpec.php, src/Akeneo/Component/Batch/Event/EventInterface.php
Fire an event when job execution is created
=> Aob 97 dispatch an event on job execution creation

src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.pl.yml
=> Merge 16 into 17

CHANGELOG-1.7.md, src/Pim/Bundle/CatalogBundle/Resources/translations/messages.pt_PT.yml, src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.pl.yml, src/Pim/Bundle/EnrichBundle/Resources/translations/messages.pl.yml, src/Pim/Bundle/ImportExportBundle/Resources/translations/messages.pl.yml, src/Pim/Bundle/UIBundle/Resources/translations/messages.sv.yml, src/Pim/Bundle/UserBundle/Resources/translations/messages.de.yml, src/Pim/Bundle/UserBundle/Resources/translations/messages.pl.yml, src/Pim/Bundle/UserBundle/Resources/translations/messages.pt_BR.yml, src/Pim/Bundle/UserBundle/Resources/translations/messages.pt_PT.yml, src/Pim/Bundle/UserBundle/Resources/translations/messages.sv.yml, src/Pim/Component/Connector/ArrayConverter/StandardToFlat/Channel.php, src/Pim/Component/Connector/spec/ArrayConverter/StandardToFlat/ChannelSpec.php
=> Merge 17 into 20

upgrades/schema/Version_2_2_20180320093100_remove_product_type.php
=> Migration: Add migration to remove the product type from product table

upgrades/schema/Version_2_2_20180228120422.php, upgrades/schema/Version_2_2_20180321103340_index_products_and_product_models.php
Add missing migrations.
- Job instance
- Reindex products & models migration
=> Migration: Add missing job instance in migration

upgrades/schema/Version_2_2_20180321135455_product_model_export_job_parameters.php
=> Migration: Add migration of job parameters

upgrades/schema/Version_2_2_20180321135455_product_model_export_job_parameters.php, upgrades/schema/Version_2_2_20180321164023_index_products_and_product_models.php
=> Migration: index as the last step

CHANGELOG-2.2.md
=> PO update changelog

upgrades/schema/Version_2_2_20180321135455_product_model_export_job_parameters.php
=> Update the migration process to avoid creating an empty filter

CHANGELOG-2.0.md
=> fix-2-0-changelog: Fix CHANGELOG-2-0.md

CHANGELOG-2.2.md, src/Pim/Bundle/DataGridBundle/Extension/Formatter/Property/DateTimeWithUserTimezoneProperty.php, src/Pim/Bundle/DataGridBundle/Resources/config/formatters.yml, src/Pim/Bundle/DataGridBundle/spec/Extension/Formatter/Property/DateTimeWithUserTimezonePropertySpec.php, src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/job_tracker.yml
Follow up to https://github.com/akeneo/pim-community-dev/pull/7820.
=> AOB-101: Apply user timezone on dates in the UI (again)

src/Pim/Bundle/EnrichBundle/Controller/Rest/ProductController.php, src/Pim/Bundle/EnrichBundle/Filter/ProductEditDataFilter.php
Remove useless filters as data are already filtered in repository.
=> PIM-7213: remove useless filters

.ci/Jenkinsfile
During a ci build, we used a very old gcloud version to build pim image, but today this version stop  working.
We upgrade and change the  image (and version too).
`-`: Not …
=> [CI]fix ci image builder version

CHANGELOG-1.7.md, src/Pim/Bundle/UIBundle/Resources/public/less/pages/Login.less, src/Pim/Bundle/UserBundle/Resources/translations/messages.en.yml, src/Pim/Bundle/UserBundle/Resources/views/Reset/reset.html.twig
Fix CSS problem on reset password page
=> PIM-7162: fix css

src/Pim/Bundle/CatalogBundle/DependencyInjection/Compiler/RegisterComparatorsPass.php
=> Fix comparators not ordered by priority

.prettierrc.json, src/Pim/Bundle/EnrichBundle/Resources/public/js/view/base.ts, webpack.config.js
This PR add support for symlink on the ce for ee developpers
=> Add symlink support for typescript

CHANGELOG-2.0.md
=> PIM-7282 : Fix changelog

src/Pim/Bundle/EnrichBundle/Resources/public/js/catalog-volume/header.ts, src/Pim/Bundle/EnrichBundle/Resources/public/js/catalog-volume/section.ts, src/Pim/Bundle/EnrichBundle/Resources/public/js/controller/catalog-volume.ts, src/Pim/Bundle/EnrichBundle/Resources/public/js/view/base-interface.ts, src/Pim/Bundle/EnrichBundle/Resources/public/templates/catalog-volume/section.html, src/Pim/Bundle/UIBundle/Resources/public/less/components/CatalogVolume.less, webpack-test.config.js
This PR fixes some typing and formatting issues in the catalog volume screen. 
=> PIM-7211: Fix typescript issues

phpspec.yml.dist
=> Add phpspec suite for acceptance tests

tests/back/Acceptance/Family/InMemoryFamilyRepository.php, tests/back/Acceptance/FamilyVariant/InMemoryFamilyVariantRepository.php, tests/back/Acceptance/Product/InMemoryProductRepository.php, tests/back/Acceptance/ProductModel/InMemoryProductModelRepository.php, tests/back/Acceptance/Resources/config/pim/repositories.yml, tests/back/Acceptance/spec/Family/InMemoryFamilyRepositorySpec.php, tests/back/Acceptance/spec/FamilyVariant/InMemoryFamilyVariantRepositorySpec.php, tests/back/Acceptance/spec/Product/InMemoryProductRepositorySpec.php, tests/back/Acceptance/spec/ProductModel/InMemoryProductModelRepositorySpec.php
This PR adds some InMemoryRepository:
- Product
- ProductModels
- Family
- FamilyVariant
| Added legacy Behats               |  Y
=> In memory repos about family and family variant and product and product models

tests/back/Acceptance/Attribute/InMemoryAttributeRepository.php, tests/back/Acceptance/AttributeGroup/InMemoryAttributeGroupRepository.php, tests/back/Acceptance/AttributeOption/InMemoryAttributeOptionRepository.php, tests/back/Acceptance/Resources/config/pim/repositories.yml, tests/back/Acceptance/spec/Attribute/InMemoryAttributeRepositorySpec.php, tests/back/Acceptance/spec/AttributeGroup/InMemoryAttributeGroupRepositorySpec.php, tests/back/Acceptance/spec/AttributeOption/InMemoryAttributeOptionRepositorySpec.php
- Attribute repository
- Attribute option repository
- Attribute group repository
For each are implemented `getIdentifierProperties`, `findOneByIdentifier`, `findBy`, and `save` methods.
Every implemented methods are unit tested.
=> Add an in memory attribute related repository

tests/back/Acceptance/Catalog/InMemoryGroupRepository.php, tests/back/Acceptance/Catalog/InMemoryGroupTypeRepository.php, tests/back/Acceptance/Resources/config/pim/repositories.yml, tests/back/Acceptance/User/InMemoryGroupRepository.php, tests/back/Acceptance/User/InMemoryRoleRepository.php, tests/back/Acceptance/User/InMemoryUserRepository.php, tests/back/Acceptance/spec/Catalog/InMemoryGroupRepositorySpec.php, tests/back/Acceptance/spec/Catalog/InMemoryGroupTypeRepositorySpec.php, tests/back/Acceptance/spec/User/InMemoryGroupRepositorySpec.php, tests/back/Acceptance/spec/User/InMemoryRoleRepositorySpec.php, tests/back/Acceptance/spec/User/InMemoryUserRepositorySpec.php
- User 
- User group
- User Roles
- Catalog group
- Catalog Group type
=> Add in memory repository for acceptance tests

CHANGELOG-2.3.md, features/mass-action/mass_edit_products_and_product_models.feature, features/mass-action/mass_update_product_models_status.feature, src/Pim/Bundle/EnrichBundle/Resources/config/readers.yml, src/Pim/Bundle/EnrichBundle/Resources/config/steps.yml
=> PIM-7284: be able to mass edit status of product models

features/family/delete_family.feature, src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Query/CountProductsWithFamily.php, src/Pim/Bundle/CatalogBundle/Resources/config/queries.yml, src/Pim/Bundle/CatalogBundle/Resources/config/removers.yml, src/Pim/Bundle/EnrichBundle/Controller/Rest/FamilyController.php, src/Pim/Component/Catalog/ProductAndProductModel/Query/CountProductsWithFamilyInterface.php, src/Pim/Component/Catalog/Updater/Remover/FamilyRemover.php, src/Pim/Component/Catalog/spec/Updater/Remover/FamilyRemoverSpec.php
=> PIM-7294 - As Julia, I don't want to remove a family with products

CHANGELOG-2.0.md
=> PIM-7297: add changelog

.ci/Jenkinsfile, .ci/behat.community.yml, .ci/behat.enterprise.yml, behat.yml.dist
=> Run legacy & acceptance tests on CI

src/Pim/Bundle/EnrichBundle/Controller/Rest/AssociationTypeController.php, src/Pim/Bundle/EnrichBundle/Controller/Rest/AttributeController.php, src/Pim/Bundle/EnrichBundle/Controller/Rest/JobInstanceController.php, src/Pim/Bundle/EnrichBundle/Controller/Rest/ProductModelController.php
=> PIM-7116: Add security check on Rest controllers

tests/front/acceptance/cucumber/step-definitions/structure/locales.js, tests/front/common/builder/association-type.js, tests/front/common/builder/attribute.js, tests/front/common/builder/channel.js, tests/front/common/builder/locale.js, tests/front/common/builder/product.js, tests/front/common/builder/user.js, tests/front/integration/pimenrich/fetcher/family-fetcher.integration.js
Fix the builder implementation after first PR.
=> Fix builder implementation

README.md
This PR solve some broken links on the README.
Signed-off-by: Freyskeyd <simon.paitrault@gmail.com>
=> Documentation: Broken links on README.md

src/Pim/Bundle/EnrichBundle/Resources/public/js/pim-attributeoptionview.js
This looks like incorrectly resolved merge conflict, which added back the hardcoded template into the, then master, now 1.7, branch, where the templates had been  outsourced earlier.
=> Partially revert 1b22956abf7bb8b79b5e24510f6824c7a83938b3.

.ci/Jenkinsfile, package.json, tests/front/common/base.jest.json, tests/front/integration/jest/integration.jest.js, tests/front/unit/jest/unit.jest.js, tests/front/unit/pimenrich/js/i18n.unit.ts, tsconfig.json
This PR add unit tests to the frontend
=> Add unit test for frontend

.ci/Jenkinsfile, tests/front/acceptance/cucumber/world.js
=> Make puppeteer in frontend acceptance tests more stable

src/Pim/Bundle/DataGridBundle/Extension/MassAction/MassActionDispatcher.php, src/Pim/Bundle/DataGridBundle/spec/Extension/MassAction/MassActionDispatcherSpec.php
See the EE PR for the full explanation.
=> PIM-7331: Simplify getRawFilters method to avoid calling useless stuff

CHANGELOG-2.3.md, src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/family_variant.yml, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/family_variant/edit.yml, src/Pim/Bundle/EnrichBundle/Resources/config/requirejs.yml, src/Pim/Bundle/EnrichBundle/Resources/public/js/common/form-modal-creator.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/datagrid/action/edit-in-modal-action.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/family-variant/form/attribute-set.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/family-variant/form/labels-container.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/family-variant/form/save.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/family/form/family-variant.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/form-tabs.js, src/Pim/Bundle/EnrichBundle/Resources/public/templates/family-variant/attribute-set.html, src/Pim/Bundle/EnrichBundle/Resources/public/templates/family-variant/edit.html, src/Pim/Bundle/EnrichBundle/Resources/public/templates/family-variant/labels-container.html, src/Pim/Bundle/EnrichBundle/Resources/public/templates/form/form-tabs.html, src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml, src/Pim/Bundle/UIBundle/Resources/public/less/components/FamilyVariant.less, src/Pim/Bundle/UIBundle/Resources/public/less/components/product-edit-form/HorizontalNavtab.less, src/Pim/Bundle/UIBundle/Resources/public/less/lib/modal.less, tests/legacy/features/family/edit_family_variant.feature
This PR adds a translations tab in the 'Edit family variant' form
=> PIM-6897: As Julia, I would like to update the family variant labels from the UI

.ci/Jenkinsfile
Fix the directory list for adding CE integration tests via the EE build
=> ADD CE integration tests via a EE build

src/Pim/Bundle/InstallerBundle/Command/DatabaseCommand.php
See full description: https://github.com/akeneo/pim-enterprise-dev/pull/3897
=> PIM-7339: Allow to mass upload assets on install

CHANGELOG-2.0.md, src/Pim/Bundle/ApiBundle/tests/integration/Controller/MeasureFamily/GetMeasureFamilyIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/MeasureFamily/ListMeasureFamilyIntegration.php, src/Pim/Component/Api/Converter/MeasureFamilyConverter.php
This PR is a rework of contribution https://github.com/akeneo/pim-community-dev/pull/7619.
- original PR was in 2.1, and wasn't merged before its end of life, this new PR is on 2.0
- changelog is updated
- integration test is fixed
See original contribution PR for context.
=> Fix measure family converter

CHANGELOG-2.2.md, src/Pim/Bundle/CatalogBundle/Command/RemoveWrongBooleanValuesOnVariantProductsBatchCommand.php, src/Pim/Bundle/CatalogBundle/Command/RemoveWrongBooleanValuesOnVariantProductsCommand.php
=> PIM-7363: fix rename of cursor factory

src/Pim/Bundle/CatalogBundle/Command/CleanRemovedAttributesFromProductAndProductModelCommand.php, src/Pim/Bundle/CatalogBundle/Command/RefreshProductCommand.php, src/Pim/Bundle/CatalogBundle/Command/RemoveWrongBooleanValuesOnVariantProductsBatchCommand.php, src/Pim/Bundle/CatalogBundle/Command/RemoveWrongBooleanValuesOnVariantProductsCommand.php
Extended PR after the PIM-7363 with the fix to the bugs we found running this command.
=> PIM-7363: fix commands to clean products

package.json, src/Pim/Bundle/EnrichBundle/DependencyInjection/Compiler/RegisterFormExtensionsPass.php, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/product/index.yml, src/Pim/Bundle/EnrichBundle/Resources/public/js/catalog-volume/header.ts, src/Pim/Bundle/EnrichBundle/Resources/public/js/i18n.ts, src/Pim/Bundle/InstallerBundle/Command/AssetsCommand.php, src/Pim/Bundle/UIBundle/Resources/public/less/components/grid/Grid.less, tests/front/unit/pimenrich/js/i18n.unit.ts, tsconfig.json, webpack.config.js, webpack/requirejs-utils.js
This PR helps to create bundles with public files outside of it. Symfony asset command is not extensible so we decided to hook into our own asset command
=> PIM-7380: make bundle structure more flexible

CHANGELOG-1.7.md, src/Pim/Bundle/EnrichBundle/Resources/translations/messages.de.yml, src/Pim/Bundle/EnrichBundle/Resources/translations/messages.fr.yml, src/Pim/Bundle/UserBundle/Resources/translations/messages.de.yml, src/Pim/Component/Catalog/spec/Updater/ChannelUpdaterSpec.php
=> Merge 1 7 into 2 0

CHANGELOG-2.3.md, src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Query/FamilyVariantsByAttributeAxes.php, src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/FamilyVariantRepository.php, src/Pim/Bundle/CatalogBundle/Elasticsearch/Filter/Field/FamilyVariantFilter.php, src/Pim/Bundle/CatalogBundle/EventSubscriber/AttributeOption/AttributeOptionRemovalSubscriber.php, src/Pim/Bundle/CatalogBundle/Resources/config/event_subscribers.yml, src/Pim/Bundle/CatalogBundle/Resources/config/queries.yml, src/Pim/Bundle/CatalogBundle/Resources/config/query_builders.yml, src/Pim/Bundle/CatalogBundle/Resources/elasticsearch/index_configuration.yml, src/Pim/Bundle/CatalogBundle/spec/Doctrine/ORM/Query/FamilyVariantsByAttributeAxesSpec.php, src/Pim/Bundle/CatalogBundle/spec/Elasticsearch/Filter/Field/FamilyVariantFilterSpec.php, src/Pim/Bundle/CatalogBundle/spec/EventSubscriber/AttributeOption/AttributeOptionRemovalSubscriberSpec.php, src/Pim/Bundle/CatalogBundle/tests/integration/Elasticsearch/IndexConfiguration/AbstractPimCatalogProductModelIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/Elasticsearch/IndexConfiguration/PimCatalogFamilyVariantIntegration.php, src/Pim/Component/Catalog/FamilyVariant/Query/FamilyVariantsByAttributeAxesInterface.php, src/Pim/Component/Catalog/tests/integration/Updater/Remover/AttributeOptionRemoverIntegration.php, tests/legacy/features/Pim/Behat/Context/NavigationContext.php, tests/legacy/features/attribute/option/delete_attribute_options.feature
=> PIM-7302: delete an attribute option is forbiden if it is a variant axis

src/Pim/Bundle/EnrichBundle/DependencyInjection/Compiler/RegisterFormExtensionsPass.php, tsconfig.json, webpack.config.js
This PR fixes the CI for ce and ee
=> PIM-7380: fix form extension listing

CHANGELOG-2.2.md, src/Pim/Bundle/UIBundle/Resources/public/less/lib/bootstrap.switch.less
See https://akeneo.atlassian.net/browse/PIM-7316
=> PIM-7316: Fix z-index on boolean fields

.ci/Jenkinsfile, Dockerfile, app/config/config_test.yml
=> Fix integration tests that were not executed

.ci/Jenkinsfile, .ci/k8s/pubsub_consumer_job.yaml
Since the last cluster update, some cluster features has been broken.
This PR fix the broken feature and use the auto-scale pools for behat and integration test.
`-`: Not …
=> CI for 1.7 : be Back

src/Pim/Bundle/UIBundle/Resources/public/less/components/Subsection.less, src/Pim/Bundle/UIBundle/Resources/public/less/components/product-edit-form/FieldContainer.less, src/Pim/Bundle/UIBundle/Resources/public/less/components/product-edit-form/TextField.less
This PR adds some style for the new fields of the enriched entity
=> PIM-7381 : Add modifier for specific input style on enriched entity

CHANGELOG-2.0.md, src/Pim/Bundle/CatalogBundle/Command/Cleaner/WrongBooleanValuesOnVariantProductCleaner.php, src/Pim/Bundle/CatalogBundle/Command/RemoveWrongValuesOnVariantProductsBatchCommand.php, src/Pim/Bundle/CatalogBundle/Command/RemoveWrongValuesOnVariantProductsCommand.php, src/Pim/Bundle/CatalogBundle/Resources/config/updaters.yml, src/Pim/Bundle/CatalogBundle/spec/Command/Cleaner/WrongValuesOnVariantProductCleanerSpec.php
Add a family filter to the clean command
=> PIM-7363: add family filter

src/Pim/Bundle/UIBundle/Resources/public/less/components/LoadingMask.less
=> PIM-7381: add loading placeholder

src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/catalog_volume/index.yml, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/common/menu.yml, src/Pim/Bundle/EnrichBundle/Resources/config/routing.yml
=> PIM-7365: move the menu for catalog volume entry

src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/GetProductIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/ProductModel/CreateProductModelIntegration.php, src/Pim/Bundle/ApiBundle/tests/integration/Controller/ProductModel/GetProductModelIntegration.php
=> API-595 API-596: Add API tests to GET & ADD associations to a product model

app/config/pim_parameters.yml, src/Pim/Bundle/CatalogVolumeMonitoringBundle/tests/Integration/Persistence/Query/CountCategoryTreesIntegration.php
=> PIM-7374: remove volume limit for the number of categorytree

tests/front/common/base.jest.json, tests/front/integration/jest/setup.js
This PR adds a jest cache folder to speed up the tests
=> PIM-7381: add jest cache

src/Pim/Bundle/EnrichBundle/Resources/public/js/catalog-volume/header.ts, src/Pim/Bundle/EnrichBundle/Resources/public/js/catalog-volume/section.ts, src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml, src/Pim/Bundle/UIBundle/Resources/public/less/components/CatalogVolume.less
Update some links and push some pixels around ✨
=> PIM-7372: Minor fixes to catalog volume screen

src/Pim/Bundle/ApiBundle/Resources/config/checkers.yml
=> Correct the deletion of the query_parameters in CE

src/Oro/Bundle/FilterBundle/Form/Type/Filter/TextFilterType.php, src/Pim/Bundle/DataGridBundle/Resources/config/attribute_types.yml, src/Pim/Bundle/DataGridBundle/Resources/config/requirejs.yml, src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter-builder.js, src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filter/identifier-filter.js, src/Pim/Bundle/DataGridBundle/Resources/translations/jsmessages.en.yml, tests/legacy/features/Context/Page/Base/Grid.php
https://github.com/akeneo/pim-community-dev/pull/8340
=> PIM-7345 : Remove "is_empty" operator on the sku filter.

tests/back/Acceptance/User/InMemoryUserRepository.php, tests/back/Acceptance/spec/User/InMemoryUserRepositorySpec.php
=> PIM-7342: Implement findOneBy in InMemoryUserRepository

src/Oro/Bundle/FilterBundle/Form/Type/Filter/TextFilterType.php, src/Pim/Bundle/DataGridBundle/Resources/config/attribute_types.yml, src/Pim/Bundle/DataGridBundle/Resources/config/requirejs.yml, src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter-builder.js, src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filter/identifier-filter.js, src/Pim/Bundle/DataGridBundle/Resources/translations/jsmessages.en.yml, tests/legacy/features/Context/Page/Base/Grid.php
=> Last bulk of PRs for the 2.3

upgrades/schema/Version_2_3_20180620102817_add_table_product_model_associations.php, upgrades/schema/Version_2_3_20180621121925_index_products_and_product_models.php
- Make sure the indexing migration is done the last.
- Add missing migrations.
=> Release 2.3: Fix migrations and add missing

CHANGELOG-2.0.md, src/Akeneo/Component/Localization/Localizer/NumberLocalizer.php, src/Akeneo/Component/Localization/spec/Localizer/NumberLocalizerSpec.php, src/Pim/Component/Catalog/Completeness/CompletenessGenerator.php, src/Pim/Component/Catalog/Completeness/CompletenessGeneratorInterface.php, src/Pim/Component/Catalog/Manager/CompletenessManager.php, src/Pim/Component/Catalog/spec/Manager/CompletenessManagerSpec.php
=> Merge 2.0 into 2.2

src/Pim/Bundle/EnrichBundle/StructureVersion/Provider/StructureVersion.php, upgrades/schema/Version_2_3_20180620134351_add_table_structure_version_last_update.php
=> 2.3 Release: add missing migration for structure version

CHANGELOG-3.0.md, UPGRADE.md, src/Akeneo/Pim/Structure/Bundle/DependencyInjection/Compiler/ResolveDoctrineTargetModelPass.php, src/Akeneo/Pim/Structure/Bundle/Resources/config/entities.yml, src/Akeneo/Pim/Structure/Bundle/Resources/config/model/doctrine/AttributeOption.orm.yml, src/Akeneo/Pim/Structure/Bundle/Resources/config/model/doctrine/AttributeOptionValue.orm.yml, src/Akeneo/Pim/Structure/Component/Model/AttributeOption.php, src/Akeneo/Pim/Structure/Component/Model/AttributeOptionInterface.php, src/Akeneo/Pim/Structure/Component/Model/AttributeOptionValue.php, src/Akeneo/Pim/Structure/Component/Model/AttributeOptionValueInterface.php, src/Akeneo/Pim/Structure/Component/spec/Model/AttributeOptionSpec.php, src/Akeneo/Pim/Structure/Component/spec/Normalizer/Standard/AttributeOptionNormalizerSpec.php, src/Akeneo/Pim/Structure/Component/spec/Normalizer/Versionning/AttributeNormalizerSpec.php, src/Akeneo/Pim/Structure/Component/spec/Normalizer/Versionning/AttributeOptionNormalizerSpec.php, src/Akeneo/Pim/Structure/Component/spec/Updater/AttributeOptionUpdaterSpec.php, src/Pim/Bundle/CatalogBundle/DependencyInjection/Compiler/ResolveDoctrineTargetModelPass.php, src/Pim/Bundle/CatalogBundle/Resources/config/entities.yml, src/Pim/Bundle/CatalogBundle/Resources/config/models.yml, src/Pim/Bundle/DataGridBundle/spec/Normalizer/Product/OptionNormalizerSpec.php, src/Pim/Bundle/DataGridBundle/spec/Normalizer/Product/OptionsNormalizerSpec.php, src/Pim/Bundle/EnrichBundle/Normalizer/AttributeOptionValueCollectionNormalizer.php, src/Pim/Bundle/EnrichBundle/Normalizer/AttributeOptionValueNormalizer.php, src/Pim/Bundle/EnrichBundle/spec/Form/Type/AttributeOptionValueTypeSpec.php, src/Pim/Bundle/EnrichBundle/spec/Normalizer/EntityWithFamilyVariantNormalizerSpec.php, src/Pim/Bundle/VersioningBundle/UpdateGuesser/AttributeOptionUpdateGuesser.php, src/Pim/Bundle/VersioningBundle/spec/UpdateGuesser/AttributeOptionUpdateGuesserSpec.php, src/Pim/Component/Catalog/spec/Value/OptionValueSpec.php, src/Pim/Component/Catalog/spec/Value/OptionsValueSpec.php
=> TIP-842: Move attribute option value model to structure sub context

CHANGELOG-2.3.md
=> Add missing changelogs for the release 2.3

tests/front/acceptance/cucumber/tools.js, tests/front/acceptance/cucumber/world.js, tests/front/common/templates/index.js
Rename the base URL for the fake url in acceptance and integration tests in front
=> PIM-7432: fix the base URl

CHANGELOG-2.3.md
=> Fix typo on the changelog

CHANGELOG-2.3.md
=> Release: Fix changelog

docker-compose.override.yml.dist, docker-compose.yml
=> Fix typo in docker-compose.yml

CHANGELOG-2.2.md, src/Pim/Bundle/UIBundle/Resources/views/Form/pim-fields.html.twig, src/Pim/Bundle/UserBundle/Resources/views/layout.html.twig
=> PIM-7454: fix tooltip error

CHANGELOG-2.0.md, src/Pim/Bundle/CatalogBundle/Doctrine/Common/Saver/ProductModelDescendantsSaver.php, src/Pim/Bundle/CatalogBundle/Resources/config/jobs.yml, src/Pim/Bundle/CatalogBundle/Resources/config/savers.yml, src/Pim/Bundle/CatalogBundle/spec/Doctrine/Common/Saver/ProductModelDescendantsSaverSpec.php, src/Pim/Bundle/EnrichBundle/Resources/public/js/i18n.js, src/Pim/Component/Catalog/Job/ComputeProductModelsDescendantsTasklet.php, src/Pim/Component/Catalog/spec/Job/ComputeProductModelsDescendantsTaskletSpec.php
=> Merge 20 into 22

CHANGELOG-2.0.md, src/Pim/Bundle/EnrichBundle/Connector/Reader/MassEdit/FilteredProductModelReader.php, src/Pim/Bundle/EnrichBundle/Connector/Reader/MassEdit/FilteredProductReader.php, src/Pim/Bundle/EnrichBundle/spec/Connector/Reader/MassEdit/FilteredProductModelReaderSpec.php, src/Pim/Bundle/EnrichBundle/spec/Connector/Reader/MassEdit/FilteredProductReaderSpec.php
Backport of #8284 . See original PR description.
| Added Specs                       | Updated
| Added integration tests           | wip
=> PIM-7478: Fix memory leak on quick export

tests/Integration/catalog/technical/jobs.yml
This just adds a csv_product_model_import job instance to the integration technical catalog; see full description in https://github.com/akeneo/pim-enterprise-dev/pull/4173
=> PIM-7455: Fix indexation issue after a product model import

src/Akeneo/Bundle/StorageUtilsBundle/Doctrine/Common/Clearer/CacheClearer.php, src/Akeneo/Bundle/StorageUtilsBundle/Resources/config/doctrine.yml, src/Akeneo/Bundle/StorageUtilsBundle/spec/Doctrine/Common/Clearer/CacheClearerSpec.php
=> PIM-7464: Add CacheClearer to clear UOW and cached repo

tests/front/common/templates/index.html
Add the flash message container in the index.html used for our acceptance test to be able to test the notification flash message on the edit forms.
=> PIM-7381 : Add the flash message container for the acceptance test

CHANGELOG-3.0.md, UPGRADE.md, src/Akeneo/Pim/Structure/Bundle/Controller/InternalApi/AttributeOptionController.php, src/Akeneo/Pim/Structure/Bundle/EventListener/AttributeOptionRemovalSubscriber.php, src/Akeneo/Pim/Structure/Bundle/Form/Type/AttributeOptionCreateType.php, src/Akeneo/Pim/Structure/Bundle/Form/Type/AttributeOptionType.php, src/Akeneo/Pim/Structure/Bundle/Form/Type/AttributeOptionValueType.php, src/Akeneo/Pim/Structure/Bundle/Form/Type/FamilyType.php, src/Akeneo/Pim/Structure/Bundle/Resources/config/services.yml, src/Akeneo/Pim/Structure/Bundle/spec/EventListener/AttributeOptionRemovalSubscriberSpec.php, src/Akeneo/Pim/Structure/Bundle/spec/Form/Type/AttributeOptionCreateTypeSpec.php, src/Akeneo/Pim/Structure/Bundle/spec/Form/Type/AttributeOptionTypeSpec.php, src/Akeneo/Pim/Structure/Bundle/spec/Form/Type/AttributeOptionValueTypeSpec.php, src/Akeneo/Pim/Structure/Bundle/spec/Form/Type/FamilyTypeSpec.php, src/Akeneo/Pim/Structure/Component/tests/Integration/ExternalApi/AttributeOptionIntegration.php, src/Akeneo/Pim/Structure/Component/tests/Integration/Normalizer/Standard/AttributeOptionIntegration.php, src/Pim/Bundle/CatalogBundle/Resources/config/event_subscribers.yml, src/Pim/Bundle/EnrichBundle/Form/Type/AttributeOptionCreateType.php, src/Pim/Bundle/EnrichBundle/Resources/config/form_types.yml
=> TIP-842: Move attritbute option classes to Structure

src/Akeneo/Pim/Structure/Bundle/Resources/config/validation/attribute.yml, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/locale-switcher.js, src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/locale-switcher.html, src/Pim/Bundle/UIBundle/Resources/public/images/attribute/icon-enriched-entity.svg, src/Pim/Bundle/UIBundle/Resources/public/less/components/button/Button.less, src/Pim/Component/Catalog/Validator/Constraints/ImmutableValidator.php, src/Pim/Component/Catalog/spec/Validator/Constraints/ImmutableValidatorSpec.php, tests/legacy/features/Context/Page/Product/Edit.php, tests/legacy/features/Context/Page/Product/Index.php, tests/legacy/features/Pim/Behat/Decorator/Export/Filter/BaseDecorator.php
Small PR to support attribute link to product for enriched entity
=> PIM-7469: add enriched entity icon

.eslintrc
Update eslint config to fix the step-definition files
=> Update eslint to fix step-definition files

CHANGELOG-3.0.md, UPGRADE.md, src/Akeneo/Channel/Component/tests/integration/Channel/UpdaterIntegration.php, src/Akeneo/Channel/Component/tests/integration/Normalizer/Standard/CurrencyIntegration.php, src/Akeneo/Channel/Component/tests/integration/Normalizer/Standard/LocaleIntegration.php, src/Akeneo/Pim/Structure/Bundle/DependencyInjection/AkeneoPimStructureExtension.php, src/Akeneo/Pim/Structure/Bundle/EventSubscriber/AddUniqueAttributesToVariantProductAttributeSetSubscriber.php, src/Akeneo/Pim/Structure/Bundle/EventSubscriber/ComputeFamilyVariantStructureChangesSubscriber.php, src/Akeneo/Pim/Structure/Bundle/EventSubscriber/RemoveAttributesFromFamilyVariantsOnFamilyUpdateSubscriber.php, src/Akeneo/Pim/Structure/Bundle/EventSubscriber/SaveFamilyVariantOnFamilyUpdateSubscriber.php, src/Akeneo/Pim/Structure/Bundle/Resources/config/event_subscribers.yml, src/Akeneo/Pim/Structure/Bundle/Resources/config/updaters.yml, src/Akeneo/Pim/Structure/Bundle/spec/EventSubscriber/AddUniqueAttributesToVariantProductAttributeSetSubscriberSpec.php, src/Akeneo/Pim/Structure/Bundle/spec/EventSubscriber/ComputeFamilyVariantStructureChangesSubscriberSpec.php, src/Akeneo/Pim/Structure/Bundle/spec/EventSubscriber/RemoveAttributesFromFamilyVariantsOnFamilyUpdateSubscriberSpec.php, src/Akeneo/Pim/Structure/Bundle/spec/EventSubscriber/SaveFamilyVariantOnFamilyUpdateSubscriberSpec.php, src/Akeneo/Pim/Structure/Component/Updater/AssociationTypeUpdater.php, src/Akeneo/Pim/Structure/Component/Updater/AttributeGroupUpdater.php, src/Akeneo/Pim/Structure/Component/spec/Updater/AssociationTypeUpdaterSpec.php, src/Akeneo/Pim/Structure/Component/spec/Updater/AttributeGroupUpdaterSpec.php, src/Akeneo/Pim/Structure/Component/tests/Integration/Normalizer/Standard/AttributeGroupIntegration.php, src/Akeneo/Pim/Structure/Component/tests/Integration/Normalizer/Standard/AttributeIntegration.php, src/Akeneo/Pim/Structure/Component/tests/Integration/Normalizer/Standard/FamilyIntegration.php, src/Akeneo/Pim/Structure/Component/tests/Integration/Normalizer/Standard/FamilyVariantIntegration.php, src/Akeneo/Pim/Structure/Component/tests/Integration/Remover/AttributeOptionRemoverIntegration.php, src/Akeneo/Pim/Structure/Component/tests/Integration/Updater/AssociationTypeUpdaterIntegration.php, src/Akeneo/Pim/Structure/Component/tests/Integration/Updater/AttributeGroupUpdaterIntegration.php, src/Pim/Bundle/CatalogBundle/Resources/config/event_subscribers.yml, src/Pim/Bundle/CatalogBundle/Resources/config/updaters.yml, src/Pim/Component/Catalog/tests/integration/Updater/AttributeGroupUpdaterIntegration.php
Once merged, everything related to Structure will have been moved. 
I'll focus on the "Enrichment" part.
=> TIP-842: Move last bits of Structure

src/Pim/Bundle/EnrichBundle/Controller/Rest/SequentialEditController.php, tests/legacy/features/mass-action/edit_common_attributes_scopable_localizable.feature
I'm not sure that we need to add a behat for that: there is no real value here
=> PIM-7482: fix sequential edit with sort

CHANGELOG-1.7.md, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/categories.js, src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/field/boolean.html, src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/tab/categories.html
=>  PIM-7429: fix category tab in product edit form

app/PimRequirements.php
=> Update requirement for Mysql 5.7.22

tests/legacy/features/product/completeness/remove_completeness.feature
=> PIM-7443: Fix behat, since PIM-7518 the completeness is compute againafter locales of a channel are deleted

src/Pim/Bundle/InstallerBundle/FixtureLoader/FixtureJobLoader.php
=> PIM-7409: Add option to the JobInstanceSaver for PIM instalation

CHANGELOG-2.3.md, src/Pim/Bundle/EnrichBundle/Doctrine/ORM/Repository/FamilySearchableRepository.php, src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/field/metric.html, tests/legacy/features/product/create_product_and_save_added_attributes.feature
=> PIM-7476: fix family select2 to have the right limit

src/Pim/Bundle/EnrichBundle/Resources/public/js/catalog-volume/header.ts, src/Pim/Bundle/EnrichBundle/Resources/public/js/catalog-volume/section.ts, src/Pim/Bundle/EnrichBundle/Resources/public/js/common/title-with-subtitle.ts, src/Pim/Bundle/EnrichBundle/Resources/public/js/controller/catalog-volume.ts, tests/front/acceptance/cucumber/tools.js
=> PIM-7433: Fix answerJson to take status into account

CHANGELOG-1.7.md, src/Pim/Bundle/EnrichBundle/Resources/public/js/job/common/edit/launch.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/job/common/edit/upload-launch.js
Not really testable by behat and not really relevant
=> PIM-7525: add loading mask on upload clic

src/Pim/Bundle/UIBundle/Resources/public/less/components/TitleContainer.less
=> PIM-7433: add shadow on focus

src/Pim/Bundle/ReferenceDataBundle/DependencyInjection/Compiler/RegisterConfigurationsPass.php
=> iterate on reference data configuration only if iterable

CHANGELOG-1.7.md
=> Update the changelog to inform integrators about the BC break of the PIM-7456

src/Akeneo/Pim/Structure/Bundle/Controller/InternalApi/AttributeController.php, src/Akeneo/Pim/Structure/Bundle/Doctrine/ORM/Repository/InternalApi/AttributeSearchableRepository.php, src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/edit-form.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/fields/field.js, src/Pim/Bundle/EnrichBundle/Resources/public/templates/form/common/fields/field.html, src/Pim/Bundle/UIBundle/Resources/public/less/components/TitleContainer.less, src/Pim/Bundle/UIBundle/Resources/public/less/lib/select2.less
=> APAI-2 identifiers mapping front

src/Pim/Bundle/EnrichBundle/Resources/public/templates/common/no-data.html
=> APAI-38: fix template due to merge master

README.md, composer.lock, internal_doc/RUNNING_THE_TESTS.md
This PR adds a new documentation in our `internal_doc` directory, listing all the tests we are currently using in the PIM, and more important, how to run them.
| Tech Doc                          | OK
=> Add documentation about how to run the tests

CHANGELOG-2.3.md, src/Pim/Bundle/UserBundle/Resources/views/layout.html.twig
- In login page click on "Forgot your password" 
- Set your mail address 
- Open the link in the mail received with the web console opened 
--> error :46 Uncaught TypeError: Cannot read property 'addEventListener' of null …
=> PIM-7536: Fix tool-tip error

src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid/grid.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/attributes.js
GTMed here => https://github.com/akeneo/pim-community-dev/pull/8559
=> Let the no-data.html template handle translations

src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid/grid.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/attributes.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/save-form.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/save.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/router.js, src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en_US.yml, src/Pim/Bundle/UIBundle/Resources/public/less/components/button/ButtonList.less
https://github.com/akeneo/pim-enterprise-dev/pull/4281
=> [ASI-90] Front part for attributes mapping

CHANGELOG-2.3.md, tsconfig.json
=> GH-8550: Exclude more folders to improve build time

src/Akeneo/Pim/Structure/Bundle/Controller/InternalApi/AttributeController.php, src/Akeneo/Pim/Structure/Bundle/Doctrine/ORM/Repository/InternalApi/AttributeSearchableRepository.php, src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid/grid.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/attributes.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/edit-form.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/fields/field.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/save-form.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/save.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/router.js, src/Pim/Bundle/EnrichBundle/Resources/public/templates/common/no-data.html, src/Pim/Bundle/EnrichBundle/Resources/public/templates/form/common/fields/field.html, src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en_US.yml, src/Pim/Bundle/UIBundle/Resources/public/less/components/TitleContainer.less, src/Pim/Bundle/UIBundle/Resources/public/less/components/button/ButtonList.less, src/Pim/Bundle/UIBundle/Resources/public/less/lib/select2.less
=> APAI-117: Merge "suggest_data" into "master"

tests/back/Acceptance/Product/InMemoryProductRepository.php, tests/back/Acceptance/spec/Product/InMemoryProductRepositorySpec.php
=> Adds InMemoryProductRepository features

CHANGELOG-2.0.md, src/Pim/Bundle/CatalogBundle/Doctrine/Common/Saver/ProductModelDescendantsSaver.php, src/Pim/Bundle/CatalogBundle/Doctrine/ORM/CompletenessRemover.php, src/Pim/Bundle/CatalogBundle/spec/Doctrine/Common/Saver/ProductModelDescendantsSaverSpec.php, src/Pim/Bundle/CatalogBundle/spec/Doctrine/ORM/CompletenessRemoverSpec.php, src/Pim/Bundle/CatalogBundle/tests/integration/Doctrine/Common/Saver/SavingProductModelDescendantsIntegration.php, src/Pim/Component/Catalog/Completeness/CompletenessRemoverInterface.php, src/Pim/Component/Catalog/Manager/CompletenessManager.php, src/Pim/Component/Catalog/spec/Manager/CompletenessManagerSpec.php
This is a backport of https://github.com/akeneo/pim-community-dev/pull/8575 for the 2.0.x.
=> Backport of PIM-7531

internal_doc/ARCHITECTURE.md
We would like your feedback about that.
What do you think about the `Platform` name? Does it fit the definition? Do you have other ideas?
To help you understand what is platform, we think about putting inside: dashboard, versionning, import/export bundle (actual UI of imports/exports), notifications
=> TIP-873: Creation of a "Platform context"

tests/back/Acceptance/Locale/InMemoryLocaleRepository.php
On every request, the locale repository is called for it's locales. On the test_fake environment the InMemoryLocaleRepository::getLocales was called.
This PR implements it.
=> PIM-7433: Implement needed function in locale repository

CHANGELOG-3.0.md, UPGRADE.md, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/values_fillers.yml, src/Akeneo/Pim/Enrichment/Component/Product/ValuesFiller/AbstractEntityWithFamilyValuesFiller.php, src/Akeneo/Pim/Enrichment/Component/Product/ValuesFiller/EntityWithFamilyValuesFillerInterface.php, src/Akeneo/Pim/Enrichment/Component/Product/ValuesFiller/EntityWithFamilyVariantValuesFiller.php, src/Akeneo/Pim/Enrichment/Component/Product/ValuesFiller/ProductValuesFiller.php, src/Akeneo/Pim/Enrichment/Component/spec/Product/ValuesFiller/EntityWithFamilyVariantValuesFillerSpec.php, src/Akeneo/Pim/Enrichment/Component/spec/Product/ValuesFiller/ProductValuesFillerSpec.php, src/Pim/Bundle/EnrichBundle/Connector/Processor/QuickExport/ProductAndProductModelProcessor.php, src/Pim/Bundle/EnrichBundle/Controller/ProductController.php, src/Pim/Bundle/EnrichBundle/Controller/ProductModelController.php, src/Pim/Bundle/EnrichBundle/Normalizer/ProductModelNormalizer.php, src/Pim/Bundle/EnrichBundle/Normalizer/ProductNormalizer.php, src/Pim/Bundle/EnrichBundle/spec/Connector/Processor/QuickExport/ProductAndProductModelProcessorSpec.php, src/Pim/Bundle/EnrichBundle/spec/Normalizer/ProductModelNormalizerSpec.php, src/Pim/Bundle/EnrichBundle/spec/Normalizer/ProductNormalizerSpec.php, src/Pim/Component/Connector/Processor/Normalization/ProductProcessor.php, src/Pim/Component/Connector/spec/Processor/Normalization/ProductProcessorSpec.php
First PR a (quite long) serie. My goal is to move the content of the Catalog component (mostly into `Akeneo\Pim\Enrichment\Component\Product`).
I'll merge all those PRs into the branch TIP-874, and I'll launch only one CI at the and. I'll update CHANGELOG and launch specs locally on each sub PR.
=> TIP-874: move values filler

.eslintrc, src/Pim/Bundle/EnrichBundle/Resources/public/js/i18n.ts, src/Pim/Bundle/UIBundle/Resources/public/less/components/product-edit-form/FieldContainer.less, tests/front/acceptance/cucumber/world.js, tests/front/unit/pimenrich/js/i18n.unit.ts
=> PIM-7492: add image item

features/product/filtering/filter_products.feature
Because:
It's a new legacy behat and it's unstable because the "refresh" is not working as expected in a lot of cases (next step is executed before the refresh).
`-`: Not …
=> Stabilize a behat by deleting it

CHANGELOG-2.2.md
=> Merge 22 into 23

composer.json, composer.lock
I recently tagged `php-coupling-detector`. And as I'd like to make new improvements on it, let's use this tag in the PIM.
=> Tag for php-coupling-detector

.ci/Jenkinsfile, .gitignore, CHANGELOG-3.0.md, UPGRADE.md, bin/check-pullup, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/normalizers.yml, src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/ExternalApi/ProductModelNormalizer.php, src/Akeneo/Pim/Enrichment/Component/spec/Product/Normalizer/ExternalApi/ProductModelNormalizerSpec.php, src/Akeneo/Tool/Bundle/ApiBundle/Resources/config/normalizers.yml, src/Akeneo/Tool/Bundle/ConnectorBundle/Resources/config/writers.yml, src/Akeneo/Tool/Component/Connector/Writer/Database/JobInstanceWriter.php, src/Akeneo/Tool/Component/Connector/spec/Writer/Database/JobInstanceWriterSpec.php
You'll find an example of failing build here https://ci.akeneo.com/blue/organizations/jenkins/akeneo%2Fpim-community-dev/detail/PR-8691/5/pipeline:
```
+ bin/check-pullup
The directory "src/Pim/Bundle/DashboardBundle" exists whereas it shouldn't. This folder has been moved to "src/Akeneo/Platform".
The directory "src/Pim/Component/Api" exists whereas it shouldn't. This folder was dispacthed **mainly** among "src/Akeneo/Channel", "src/Akeneo/Pim", "src/Akeneo/Tool", "and many others...".
Still a few classes to dispatch before finishing the pull up. Keep going! 
Take a look at the definitions of the big set of features, they can help you: https://github.com/akeneo/pim-community-dev/blob/master/internal_doc/ARCHITECTURE.md#you-said-bounded-contexts.
And don't hesitate to ask for the help of …
```
=> Script to launch on the CI to enforce good pull-up

bin/check-pullup
Just updating the check pull up script.
=> TIP-878: move EE Catalog component

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/Grid.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/FieldContainer.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/FormContainer.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/HorizontalNavtab.less, src/Pim/Bundle/UIBundle/Resources/public/images/icon-lock2.svg
For https://github.com/akeneo/pim-enterprise-dev/pull/4432
=> APAI-139: Add lock icon

CHANGELOG-1.7.md, src/Pim/Bundle/EnrichBundle/Normalizer/VersionNormalizer.php, src/Pim/Bundle/EnrichBundle/Resources/config/normalizers.yml, src/Pim/Bundle/EnrichBundle/spec/Normalizer/VersionNormalizerSpec.php, src/Pim/Component/Catalog/Localization/Presenter/PresenterRegistry.php, src/Pim/Component/Catalog/Localization/Presenter/PresenterRegistryInterface.php, src/Pim/Component/Enrich/Converter/StandardToEnrich/ProductValueConverter.php, src/Pim/Component/Enrich/spec/Converter/StandardToEnrich/ProductValueConverterSpec.php
In order to improve PEF performances, this PR reduces the number of queries and loaded rows from DB.
On the main route (/enrich/product/rest/{product_id}),this PR allows:
- to reduce SQL queries count from 474 to 275
- to reduce PHP function calls from 260k to 210k
| Tech Doc …
=> PIM-7614 Improve performance and reduces SQL queries on PEF

src/Akeneo/Platform/Bundle/UIBundle/Resources/config/assets.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/images/icon-check-green.svg, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/QuickEdit.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/Subsection.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/Switch.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/button/Button.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/FieldContainer.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/TextField.less, src/Pim/Bundle/InstallerBundle/Command/AssetsCommand.php, src/Pim/Bundle/InstallerBundle/Event/InstallerEvents.php, webpack.config.js
in custom bundles
Add events in the install command to be able to add custom less files by listening to this events and dump them in the web/bundles folder
=> PIM-7550: add posibility for custom bundle to add less resources

app/config/config_test_fake.yml, tests/back/Acceptance/FileStorage/InMemoryFileStorer.php, tests/back/Acceptance/Resources/config/pim/file_storage.yml, tests/back/Acceptance/spec/FileStorage/InMemoryFileStorerSpec.php
=> Einrich upload image back

composer.lock, src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/save.js
It can happen than, when saving something in the PIM, we need the flash message not to disappear after a few seconds, but to stay indefinitely, until the user close the message by himself. This way we are sure he/she read it.
=> APAI-19: Save notification can be permanent

CHANGELOG-2.3.md, src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/field/boolean.html
=> PIM-7613: Fix translations of boolean attributes

.ci/Dockerfile, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/serializers_standard.yml, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/updaters.yml, src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Standard/Product/AssociationsNormalizer.php, src/Akeneo/Pim/Enrichment/Component/Product/Updater/ExternalApi/ProductModelUpdater.php, src/Akeneo/Pim/Enrichment/Component/tests/integration/Normalizer/NormalizedProductCleaner.php, src/Akeneo/Pim/Enrichment/Component/tests/integration/Normalizer/Standard/ProductStandardSortedCollectionIntegration.php, src/Akeneo/Tool/Bundle/ApiBundle/tests/integration/Controller/Product/AbstractProductTestCase.php
=> pull-up 2.3 -> master : fix CI

src/Pim/Bundle/EnrichBundle/Resources/public/templates/common/no-data.html
Just needed for https://github.com/akeneo/pim-enterprise-dev/pull/4574 :)
=> [APAI-203] Add className for no data template

CHANGELOG-2.3.md, composer.json, composer.lock
<!--- (If you've never contributed to this repository before, please read https://github.com/akeneo/pim-
=> PIM-7601: Update Symfony to 3.4.4

src/Akeneo/Platform/VersionProvider.php, src/Akeneo/Platform/spec/VersionProviderSpec.php
The edition has been added to the full version name. It avoids to override the version template in EE edition.
=> TIP-878: Improve version display

CHANGELOG-2.0.md, src/Pim/Bundle/UIBundle/Resources/public/less/components/product-edit-form/TextField.less
=> PIM-7645: Remove FF css style

tests/back/Acceptance/User/InMemoryUserRepository.php, tests/back/Acceptance/spec/User/InMemoryUserRepositorySpec.php
=> Implements findBy method for in memory user repo

tests/back/Acceptance/User/InMemoryUserRepository.php, tests/back/Acceptance/spec/User/InMemoryUserRepositorySpec.php
=> Remove array from constructor to pass the validation

src/Pim/Bundle/DataGridBundle/Controller/ProductGridController.php, src/Pim/Bundle/DataGridBundle/Query/ListAttributesUseableAsColumnInProductGrid.php, src/Pim/Bundle/DataGridBundle/Query/Sql/ListAttributesUseableAsColumnInProductGrid.php, src/Pim/Bundle/DataGridBundle/Resources/config/controllers.yml, src/Pim/Bundle/DataGridBundle/Resources/config/queries.yml, src/Pim/Bundle/DataGridBundle/Resources/config/routing/datagrid.yml
No pagination for the columns for the moment.
=> PIM-7527: change datagrid endpoint to list all available columns at once

src/Akeneo/Tool/Bundle/ApiBundle/tests/integration/Controller/Attribute/ListAttributeIntegration.php, src/Akeneo/Tool/Bundle/ApiBundle/tests/integration/Controller/Family/ListFamilyIntegration.php, src/Akeneo/Tool/Bundle/ApiBundle/tests/integration/Controller/FamilyVariant/ListFamilyVariantIntegration.php, tests/legacy/features/pim/structure/attribute/export/export_attributes_csv.feature
=> Tag tests as critical

tests/back/Acceptance/Attribute/InMemoryAttributeRepository.php, tests/back/Acceptance/spec/Attribute/InMemoryAttributeRepositorySpec.php
=> Implement InMemoryAttributeRepository::getAttributeTypeByCodes()

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/DescriptionHeader.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/button/Button.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/FieldContainer.less
https://github.com/akeneo/pim-enterprise-dev/pull/4652/files
=> APAI-287 - Style for EE

src/Oro/Bundle/UserBundle/Controller/UserController.php
See https://github.com/akeneo/pim-enterprise-dev/pull/4658
=> PIM-7649: update author of a draft when username is modified

src/Akeneo/Platform/Bundle/UIBundle/Resources/config/assets.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/Image.less
=> PIM-7435: add image component

.ci/Dockerfile, .ci/php.ini, .ci/vhost.conf, CHANGELOG-3.0.md, app/PimRequirements.php, composer.json, composer.lock, docker-compose.yml, src/Akeneo/Pim/Enrichment/Bundle/tests/Integration/Family/RemoveFamilyVariantIntegration.php, src/Akeneo/Pim/Enrichment/Component/Product/Connector/Writer/Database/ProductAssociationWriter.php, src/Akeneo/Pim/Enrichment/Component/spec/Product/Connector/Job/JobParameters/DefaultValueProvider/ProductModelCsvExportSpec.php, src/Akeneo/Pim/Enrichment/Component/spec/Product/Connector/Writer/Database/ProductAssociationWriterSpec.php, src/Akeneo/UserManagement/Component/Model/User.php, src/Oro/Bundle/DataGridBundle/Extension/Action/Actions/NavigateAction.php, src/Pim/Bundle/EnrichBundle/Controller/Rest/SequentialEditController.php
This PR makes the PIM fully work with PHP 7.2, and set it as the only accepted version for future Akeneo PIM 3.0.
=> Update to PHP 7.2

src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/Resources/translations/jsmessages.en_US.yml, src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/translations/jsmessages.en_US.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/base/variables.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/DescriptionHeader.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/ProjectWidget.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/TabContainer.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/TitleContainer.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/button/ActionButton.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/button/Button.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/FilterBox.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/Grid.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/FieldContainer.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/FormContainer.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/lib/font-awesome.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/lib/jquery.multiselect.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/lib/select2.less, src/Akeneo/UserManagement/Bundle/Resources/config/datagrid/user-group.yml, src/Akeneo/UserManagement/Bundle/Resources/translations/jsmessages.en_US.yml, src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filters-manager.js, src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/grid.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/common/item-picker.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/mass-edit/form/product/associate.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/pim-attributeoptionview.js, src/Pim/Bundle/EnrichBundle/Resources/public/templates/common/no-data.html, src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/field/multi-select.html, src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/field/simple-select.html, src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en_US.yml, src/Pim/Bundle/EnrichBundle/Resources/translations/messages.en_US.yml
=> APAI-294 Few fixes on identifiers mapping screen

src/Akeneo/Tool/Bundle/ApiBundle/tests/integration/Controller/Category/GetCategoryIntegration.php, src/Akeneo/Tool/Bundle/ApiBundle/tests/integration/Controller/Category/ListCategoryIntegration.php, src/Akeneo/Tool/Bundle/ApiBundle/tests/integration/Controller/Category/PartialUpdateCategoryIntegration.php, src/Akeneo/Tool/Bundle/ApiBundle/tests/integration/Controller/Category/PartialUpdateListCategoryIntegration.php, tests/legacy/features/pim/enrichment/category/create_a_category.feature, tests/legacy/features/pim/enrichment/category/export_categories_csv.feature, tests/legacy/features/pim/enrichment/category/import_categories.feature, tests/legacy/features/pim/enrichment/category/list_categories.feature
=> Add critical usecases for the categories

tests/back/Acceptance/Family/InMemoryFamilyRepository.php, tests/back/Acceptance/spec/Family/InMemoryFamilyRepositorySpec.php
=> add support for findAll() in InMemory family repository

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/Dropdown.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/Image.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/FieldContainer.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/FormContainer.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/TextField.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/TextareaField.less
=> PIM-7435: add style for record edit

CHANGELOG-3.0.md, app/PimRequirements.php, src/Akeneo/Platform/CommunityRequirements.php, src/Akeneo/Platform/Requirement.php
This PR aims to put the PIM technical requirements definition inside the src/ directory so it can be re-used by CE standard and EE dev and standard.
=> Moves requirements inside CE so it can be use in standard

src/Oro/Bundle/PimDataGridBundle/Datagrid/Configuration/Product/ContextConfigurator.php
=> PIM-7527: handle user filters on the datagrid

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/QuickEdit.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/Grid.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/FieldContainer.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/FormContainer.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/TextField.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/TextareaField.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/pages/Default.less, src/Pim/Bundle/EnrichBundle/Resources/config/bundles/doctrine.yml, tests/front/acceptance/cucumber/decorators/common/create-element-decorator.js, tests/front/acceptance/cucumber/tools.js
=> PIM-7435: fix review comments

CHANGELOG-2.3.md, src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filter/choice-filter.js
=> PIM-7670: Issue on SKU filters when changing context

CHANGELOG-2.3.md, src/Pim/Bundle/EnrichBundle/Controller/Rest/ChannelController.php, src/Pim/Bundle/EnrichBundle/Normalizer/ChannelNormalizer.php, src/Pim/Bundle/EnrichBundle/Resources/public/js/channel/form/properties/general/locales.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/controller/channel/edit.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/fetcher/base-fetcher.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/attributes.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/field/field.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/attributes.js, src/Pim/Bundle/EnrichBundle/spec/Normalizer/ChannelNormalizerSpec.php
| Added legacy Behats               | No
| Added acceptance tests            | No
=> PIM-7673: fix channel right filter on edit form

src/Akeneo/Platform/Bundle/UIBundle/Resources/config/assets.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/Checkbox.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/Dropdown.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/Header.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/LoadingMask.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/button/ActionButton.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/FieldContainer.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/TextareaField.less
=> PIM-7435: add checkbox style

src/Akeneo/Pim/Enrichment/Bundle/AkeneoPimEnrichmentBundle.php, src/Akeneo/Pim/Enrichment/Bundle/DependencyInjection/Compiler/RegisterCategoryItemCounterPass.php, src/Akeneo/Platform/Bundle/UIBundle/DependencyInjection/Compiler/RegisterFormExtensionsPass.php, src/Akeneo/Platform/Bundle/UIBundle/DependencyInjection/Compiler/RegisterGenericProvidersPass.php, src/Akeneo/Platform/Bundle/UIBundle/DependencyInjection/Compiler/RegisterViewElementsPass.php, src/Akeneo/Platform/Bundle/UIBundle/DependencyInjection/Reference/ReferenceFactory.php, src/Akeneo/Platform/Bundle/UIBundle/PimUIBundle.php, src/Pim/Bundle/EnrichBundle/PimEnrichBundle.php
=> TIP-860: Move compiler pas to the right BC

.ci/Jenkinsfile, internal_doc/REPRODUCE_CI_BUILD.md
This PR adds the doc to reproduce a CI build by ourself.
It fixes a mistake on the jenkins file.
=> Extra docs nanou

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/Grid.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/pages/Default.less
=> PIM-7680: Style for a flexible grid

src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/FollowUp/GetCompletenessPerChannelAndLocale.php, src/Akeneo/Pim/Enrichment/Bundle/tests/Integration/Storage/ElasticsearchAndSql/FollowUp/GetCompletenessPerChannelAndLocaleIntegration.php
Add forgotten Integration test 
=> PR linked - https://github.com/akeneo/pim-community-dev/pull/8496/files
=> PIM-7499: Add integration test

CHANGELOG-2.3.md, src/Pim/Bundle/CatalogBundle/Elasticsearch/Filter/Field/ParentFilter.php, src/Pim/Bundle/CatalogBundle/spec/Elasticsearch/Filter/Field/ParentFilterSpec.php
=> PIM-7727: parent filter search case insensitive

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/DescriptionHeader.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/LoadingMask.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/Grid.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/pages/Default.less
=> PIM-7680: fix po review comments

.gitignore, bin/docker/pim-setup.sh
=> Add docker-setup

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/Dropdown.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/Image.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/Grid.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/pages/FullPage.less
=> PIM-7719: improve grid display

CHANGELOG-2.0.md
Forgotten in https://github.com/akeneo/pim-community-dev/pull/8993.
=> PIM-7751: Fix changelog

src/Pim/Bundle/EnrichBundle/Resources/public/templates/form/common/fields/simple-select-async.html
=> [APAI-130] Display attribute option button inline

CHANGELOG-3.0.md, src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Attribute/IdentifierFilter.php, src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Attribute/TextAreaFilter.php, src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Attribute/TextFilter.php, src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Field/IdentifierFilter.php, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/TitleContainer.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/Grid.less, src/Akeneo/Tool/Component/Elasticsearch/QueryString.php
- Move the QueryString class in the Tool directory as we need it on the ReferenceEntity search as well.
- Small CSS fixes
=> Einrich fix feedbacks

.ci/Jenkinsfile
You are annoyed to wait like 15 minutes for a green check whereas you've checked "no" for all available checkboxes? This PR is for you, no build time.
Warning:
This PR does not encourage you to not run the CI, please be very careful about the tests and the CI, it is really important. Use this trick only if you are sure that you didn't break anything!
| …
=> Dot not build images if it is not needed

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/images/red_arrow.svg, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/Dropdown.less
see https://github.com/akeneo/pim-enterprise-dev/pull/4837 for screenshot
=> APAI-318: add validation error BEM element for dropdown

composer.lock, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/lib/select2.less
This little icon is used in a family list in EE, but its placement was bad, being placed directly under the end of the label (see first screenshot below).
This PR moves the icon a the right end of the list, as you can see below:
=> APAI-306: Fix robot icon position in list

webpack.config.js
=> Fix the reload exclude pattern to make it work with reference entity

upgrades/schema/Version_2_3_20180716135306_update_job_instances.php, upgrades/schema/Version_3_0_20181030150153_update_versioning_entities.php
This migrate namespaces from good old 2.3 to 3.0
=> TIP-880-versionning

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/mass-edit/form/form.js, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/MessageBox.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/mass-edit/form.html
https://github.com/akeneo/pim-enterprise-dev/pull/4875
=> APAI-303: Allow next button to hide on mass edit

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/FieldContainer.less
Create a new kind of container with the robot icon on the left.
=> APAI-306: Add family attribute mapping status container

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/Image.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/pages/FullPage.less, src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filters-column.ts, src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/column-selector.ts
=> PIM-7719: update image uploader look

.ci/Jenkinsfile, tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/GetProductEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/GetProductModelEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/LargeAndOrderedListProductModelEndToEnd.php, tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/Price/LocalizableScopableFilterIntegration.php, tests/back/Pim/Structure/Integration/AttributeGroup/Query/FindAttributeGroupOrdersEqualOrSuperiorToIntegration.php
=> TIP-860: Move the last enrichment integration tests to test folder

tests/back/Acceptance/AttributeOption/InMemoryAttributeOptionRepository.php, tests/back/Acceptance/spec/AttributeOption/InMemoryAttributeOptionRepositorySpec.php
=> Add findCodesByIdentifiers implementation for attribute option inMemory repository

.ci/Jenkinsfile, behat.yml.dist, tests/back/Pim/Enrichment/Acceptance/Context/EnrichmentFollowUpContext.php, tests/back/Pim/Enrichment/Acceptance/Resources/config/behat/services.yml, tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/GetProductEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/GetProductModelEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/LargeAndOrderedListProductModelEndToEnd.php, tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/Price/LocalizableScopableFilterIntegration.php, tests/back/Pim/Structure/Integration/AttributeGroup/Query/FindAttributeGroupOrdersEqualOrSuperiorToIntegration.php
=> TIP-860: Move enrichment acceptance tests to test folder

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/base/animations.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/Image.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/QuickEdit.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/Subsection.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/button/Button.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/FormContainer.less
=> PIM-7719: improve attribute list look to match mockups

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/router.js
https://github.com/akeneo/pim-enterprise-dev/pull/4939
=> [APAI-366] Fix Forbidden message

CHANGELOG-1.7.md, CHANGELOG-2.0.md, composer.lock, src/Pim/Bundle/CatalogBundle/Doctrine/Common/Saver/ProductModelDescendantsSaver.php, src/Pim/Bundle/CatalogBundle/Doctrine/Common/Saver/ProductSaver.php, src/Pim/Bundle/CatalogBundle/Doctrine/ORM/CompletenessRemover.php, src/Pim/Bundle/CatalogBundle/spec/Doctrine/Common/Saver/ProductModelDescendantsSaverSpec.php, src/Pim/Bundle/CatalogBundle/spec/Doctrine/Common/Saver/ProductSaverSpec.php, src/Pim/Bundle/CatalogBundle/tests/integration/Completeness/CalculateCompletenessCommandIntegration.php, src/Pim/Component/Catalog/Completeness/CompletenessGenerator.php, src/Pim/Component/Catalog/Completeness/CompletenessGeneratorInterface.php, src/Pim/Component/Catalog/Completeness/CompletenessRemoverInterface.php, src/Pim/Component/Catalog/Manager/CompletenessManager.php, src/Pim/Component/Catalog/Model/AbstractCompleteness.php, src/Pim/Component/Catalog/spec/Completeness/CompletenessGeneratorSpec.php, tests/legacy/features/family/define_the_attribute_requirement.feature
=> Merge 2.0 into 2.3

src/Pim/Bundle/CatalogBundle/Doctrine/ORM/CompletenessRemover.php
Remove deprecation notice from the CompletenessRemover. Those of the Completeness remover interface were already removed in a previous PR.
=> Remove deprecation

CHANGELOG-2.3.md, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/common/menu.yml
=> [PIM-7778] Fix ACL on Catalog Volume Monitoring

CHANGELOG-2.3.md, src/Pim/Bundle/AnalyticsBundle/Controller/SystemInfoController.php
The ACL works for UI, but not for controller.
=> PIM-7828: Fix ACL on System Info

CHANGELOG-2.3.md, src/Pim/Bundle/AnalyticsBundle/Controller/SystemInfoController.php, src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filter/date-filter.js, src/Pim/Bundle/DataGridBundle/Resources/public/templates/filter/date-filter.html, src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/common/menu.yml, src/Pim/Bundle/EnrichBundle/Resources/config/routing/product.yml, src/Pim/Bundle/EnrichBundle/Resources/public/js/datagrid/action/toggle-product-action.js, src/Pim/Bundle/NotificationBundle/Resources/views/Notification/list.json.twig
- https://github.com/akeneo/pim-community-dev/pull/9098
- https://github.com/akeneo/pim-community-dev/pull/9099
- https://github.com/akeneo/pim-community-dev/pull/9101
- https://github.com/akeneo/pim-community-dev/pull/9105
- https://github.com/akeneo/pim-community-dev/pull/9109/
=> Several fixes for 2.3

tests/legacy/features/pim/enrichment/product/pef/display_variant_product.feature, tests/legacy/features/pim/enrichment/product/pef/edit_product.feature, tests/legacy/features/pim/enrichment/product/pef/edit_product_and_filter_attributes.feature, tests/legacy/features/pim/enrichment/product/pef/edit_variant_product.feature, tests/legacy/features/pim/enrichment/product/pef/join_an_image_to_a_product.feature, tests/legacy/features/pim/enrichment/product/pef/switch_product_locale.feature, tests/legacy/features/pim/enrichment/reference-data/attribute/add_attribute.feature, tests/legacy/features/pim/enrichment/reference-data/export/export_attributes.feature, tests/legacy/features/pim/enrichment/reference-data/export/export_products_with_reference_data.feature, tests/legacy/features/pim/enrichment/reference-data/import/import_attributes.feature, tests/legacy/features/pim/enrichment/reference-data/import/import_products.feature, tests/legacy/features/pim/enrichment/reference-data/mass-action/edit_common_attributes.feature, tests/legacy/features/pim/enrichment/reference-data/product/completeness.feature, tests/legacy/features/pim/enrichment/reference-data/product/display_reference_data_in_the_grid.feature, tests/legacy/features/pim/enrichment/reference-data/product/edit_product.feature
=> New session

tests/legacy/features/pim/enrichment/product/datagrid/browse_products_by_locale_and_scope.feature, tests/legacy/features/pim/enrichment/product/datagrid/filtering/filter_product_per_boolean.feature, tests/legacy/features/pim/enrichment/product/datagrid/filtering/filter_products.feature, tests/legacy/features/pim/enrichment/product/datagrid/filtering/filter_products_and_product_models.feature, tests/legacy/features/pim/enrichment/product/datagrid/filtering/filter_products_per_category.feature, tests/legacy/features/pim/enrichment/product/datagrid/filtering/filter_products_per_completeness.feature, tests/legacy/features/pim/enrichment/product/datagrid/filtering/filter_products_per_date_fields.feature, tests/legacy/features/pim/enrichment/product/datagrid/filtering/filter_products_per_group.feature, tests/legacy/features/pim/enrichment/product/datagrid/filtering/filter_products_per_label_or_identifier.feature, tests/legacy/features/pim/enrichment/product/datagrid/filtering/filter_products_per_metric.feature, tests/legacy/features/pim/enrichment/product/datagrid/filtering/filter_products_per_option_fields.feature, tests/legacy/features/pim/enrichment/product/datagrid/filtering/filter_products_per_price.feature, tests/legacy/features/pim/enrichment/product/datagrid/filtering/filter_products_per_text_fields.feature, tests/legacy/features/pim/enrichment/product/datagrid/filtering/filter_products_per_with_multiple_dates.feature, tests/legacy/features/pim/enrichment/product/datagrid/filtering/filter_products_per_with_multiple_metrics.feature, tests/legacy/features/pim/enrichment/product/datagrid/filtering/filter_products_per_with_multiple_multiselect.feature, tests/legacy/features/pim/enrichment/product/datagrid/filtering/filter_products_per_with_multiple_number_fields.feature, tests/legacy/features/pim/enrichment/product/datagrid/filtering/filter_products_per_with_multiple_prices.feature, tests/legacy/features/pim/enrichment/product/datagrid/filtering/filter_products_per_with_multiple_text_fields.feature, tests/legacy/features/pim/enrichment/product/datagrid/filtering/filter_products_with_multiple_simpleselect.feature, tests/legacy/features/pim/enrichment/product/datagrid/products_backtothegrid.feature, tests/legacy/features/pim/enrichment/product/datagrid/products_category_backtothegrid.feature
=> Tag datagrid scenarios as critical

.ci/Jenkinsfile, CHANGELOG-3.0.md, UPGRADE.md, src/Akeneo/Pim/Enrichment/Component/Product/EntityWithFamilyVariant/KeepOnlyValuesForVariation.php, src/Akeneo/Pim/Structure/.php_cd.php, src/Akeneo/Pim/Structure/Bundle/Doctrine/ORM/Saver/FamilySaver.php, src/Akeneo/Pim/Structure/Bundle/EventListener/AttributeOptionRemovalSubscriber.php, src/Akeneo/Pim/Structure/Bundle/Resources/config/savers.yml, src/Akeneo/Pim/Structure/Component/Model/AttributeRequirement.php, src/Akeneo/Pim/Structure/Component/Model/CommonAttributeCollection.php, src/Akeneo/Pim/Structure/Component/Model/FamilyVariant.php, src/Akeneo/Pim/Structure/Component/Model/FamilyVariantInterface.php, src/Akeneo/Pim/Structure/Component/Normalizer/InternalApi/AttributeGroupNormalizer.php, src/Akeneo/Pim/Structure/Component/Normalizer/InternalApi/GroupTypeNormalizer.php, src/Akeneo/Pim/Structure/Component/Normalizer/Standard/AssociationTypeNormalizer.php, src/Akeneo/Pim/Structure/Component/Normalizer/Standard/AttributeGroupNormalizer.php, src/Akeneo/Pim/Structure/Component/Normalizer/Standard/AttributeNormalizer.php, src/Akeneo/Pim/Structure/Component/Normalizer/Standard/GroupTypeNormalizer.php, src/Akeneo/Pim/Structure/Component/Validator/Constraints/ImmutableVariantAxesValidator.php, tests/back/Pim/Enrichment/Specification/Component/Product/EntityWithFamilyVariant/CheckAttributeEditableSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/EntityWithFamilyVariant/EntityWithFamilyVariantAttributesProviderSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/EntityWithFamilyVariant/KeepOnlyValuesForVariationSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Model/CommonAttributeCollectionSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/Indexing/ProductAndProductModel/ProductModelNormalizerSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/Indexing/ProductModel/ProductModelNormalizerSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/ProductModel/Filter/ProductModelAttributeFilterSpec.php, tests/back/Pim/Structure/Specification/Bundle/Doctrine/ORM/Saver/FamilySaverSpec.php, tests/back/Pim/Structure/Specification/Component/Model/CommonAttributeCollectionSpec.php, tests/back/Pim/Structure/Specification/Component/Model/FamilyVariantSpec.php, tests/back/Pim/Structure/Specification/Component/Updater/FamilyVariantUpdaterSpec.php
=> TIP-897: Enable coupling php detector for structure bounded context

tests/legacy/features/pim/enrichment/product/mass-action/sequential-edit/sequential_edit_product_and_product_model.feature
=> Fix behat filter

src/Akeneo/UserManagement/Component/Model/User.php, tests/back/UserManagement/Specification/Component/Model/UserSpec.php
=> TIP-898: Validate the user properties

src/Akeneo/UserManagement/Component/Factory/DefaultProperty.php, src/Akeneo/UserManagement/Component/Factory/SimpleDefaultProperty.php, src/Akeneo/UserManagement/Component/Factory/UserFactory.php, src/Akeneo/UserManagement/Component/Model/User.php, tests/back/UserManagement/Specification/Component/Factory/SimpleDefaultPropertySpec.php, tests/back/UserManagement/Specification/Component/Factory/UserFactorySpec.php
=> TIP-898: Setup default properties

src/Akeneo/Platform/Bundle/UIBundle/Resources/config/assets.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/OptionEditor.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/Subsection.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/lib/modal.less
Add style for Manage option screens
=> PIM-7769: add option manager style

CHANGELOG-1.7.md, src/Pim/Bundle/DataGridBundle/Twig/FilterExtension.php, src/Pim/Bundle/DataGridBundle/spec/Twig/FilterExtensionSpec.php, src/Pim/Bundle/UserBundle/Resources/views/User/view.html.twig
=> Merge 1.7 -> 2.0

CHANGELOG-1.7.md, CHANGELOG-2.0.md, src/Pim/Bundle/DataGridBundle/Twig/FilterExtension.php, src/Pim/Bundle/DataGridBundle/spec/Twig/FilterExtensionSpec.php, src/Pim/Bundle/EnrichBundle/Resources/public/templates/form/common/fields/textarea.html, src/Pim/Bundle/UserBundle/Resources/views/User/view.html.twig
=> Merge 2.0 -> 2.3

Makefile, src/Akeneo/Pim/Enrichment/.php_cd.php, src/Akeneo/Pim/Enrichment/Bundle/Form/Type/GroupType.php, src/Akeneo/Pim/Enrichment/Component/Product/Connector/Job/EnsureConsistentAttributeGroupOrderTasklet.php
=> TIP-896: coupling rules for enrichment

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/OptionEditor.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/lib/select2.less
=> PIM-7859: fix css

upgrades/schema/Version_3_0_20181128084612_migrate_users.php
This script migrates user to the new format with Json properties
=> Migrate users

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/OptionEditor.less
=> PIM-7832: add style fixes to option editor

Makefile
This PR adds the support for docker in makefile
=> Add docker support in makefile

Makefile
It adds a help command which will be the default command if you type make.
To add a documentation for a command add ## the comment add the ends of the PHONY target
```
→ make
Akeneo Pim Community Dev available targets:
If you want to use docker, use an environment variable DOCKER=true
channel-coupling               Run the coupling-detector on Channel
coupling                       Run the coupling-detector on Everything
enrichment-coupling            Run the coupling-detector on Enrichment
structure-coupling             Run the coupling-detector on Structure
user-management-coupling       Run the coupling-detector on User Management
```
| …
=> Add a help command for the makefile

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/TitleContainer.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/lib/select2.less
=> PIM-7238: select2 style

src/Akeneo/Pim/Enrichment/Bundle/Resources/public/js/product/field/reference-multi-select-field.js, src/Akeneo/Pim/Enrichment/Bundle/Resources/public/js/product/field/reference-simple-select-field.js, src/Akeneo/Pim/Structure/Component/AttributeTypes.php, src/Akeneo/Pim/Structure/Component/Model/FamilyVariant.php, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/product_model/add_child.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/fields/simple-select-async.js, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/fields/values/reference-entity.js, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product-model/form/creation/variant.js, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/lib/select2.less
This PR adds support for reference entities attributes as variant axis
=> PIM-7720: add variant axis basics

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/fields/values/reference-entity.js
This fis is temporary to be able to run builds on the CI again
=> PIM-7720: fix install on reference entity

src/Akeneo/Pim/Enrichment/.php_cd.php, src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/CategoryController.php, src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/MassEditController.php, src/Akeneo/Pim/Enrichment/Component/Product/Association/AssociationClassResolver.php
=> Review coupling Enrichment

CHANGELOG-2.3.md, src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/column-tabs-navigation.js
=> PIM-7898: Fix tab navigation when the column is collapsed

tests/legacy/features/pim/enrichment/product/datagrid/datagrid_views.feature
=> Tag critical tests about datagrid views

internal_doc/extensibility/product_grid.md, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml, src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/ProductGrid/FetchProductAndProductModelRows.php, src/Akeneo/Pim/Enrichment/Component/Product/Grid/Query/AddAdditionalProductModelProperties.php, src/Akeneo/Pim/Enrichment/Component/Product/Grid/Query/AddAdditionalProductModelPropertiesRegistry.php, src/Akeneo/Pim/Enrichment/Component/Product/Grid/Query/AddAdditionalProductProperties.php, src/Akeneo/Pim/Enrichment/Component/Product/Grid/Query/AddAdditionalProductPropertiesRegistry.php, src/Akeneo/Pim/Enrichment/Component/Product/Grid/ReadModel/AdditionalProperties.php, src/Akeneo/Pim/Enrichment/Component/Product/Grid/ReadModel/AdditionalProperty.php, src/Akeneo/Pim/Enrichment/Component/Product/Grid/ReadModel/Row.php, src/Oro/Bundle/PimDataGridBundle/Normalizer/ProductAndProductModelRowNormalizer.php, src/Oro/Bundle/PimDataGridBundle/spec/Normalizer/ProductAndProductModelRowNormalizerSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Grid/Query/AddAdditionalProductModelPropertiesRegistrySpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Grid/Query/AddAdditionalProductPropertiesRegistrySpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Grid/Query/FetchProductAndProductModelRowsParametersSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Grid/ReadModel/AdditionalPropertiesSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Grid/ReadModel/AdditionalPropertySpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Grid/ReadModel/RowSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Grid/ReadModel/RowsSpec.php
See with @fitn :
For now, we document it internally as we don't have such cookbook.
=> PIM-7660: add an extension point in the datagrid

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/fields/simple-select-async.js, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/DescriptionHeader.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/button/ButtonList.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/FilterBox.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/FieldContainer.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/mass-edit/form.html
Show fixed tickets here 
https://github.com/akeneo/design/projects/2
=> APAI-448: Style fixes

src/Akeneo/Tool/Bundle/ApiBundle/tests/integration/Controller/Media/CreateProductMediaFileIntegration.php, src/Akeneo/Tool/Bundle/ApiBundle/tests/integration/Controller/Media/CreateProductModelMediaFileIntegration.php, src/Akeneo/Tool/Bundle/ApiBundle/tests/integration/Controller/Media/DownloadMediaFileIntegration.php, src/Akeneo/Tool/Bundle/ApiBundle/tests/integration/Controller/Media/ListMediaFileIntegration.php
=> Critical use case for medias

tests/legacy/features/pim/enrichment/product/mass-action/quick-export/quick_export.feature, tests/legacy/features/pim/enrichment/product/mass-edit/change_product_parent.feature, tests/legacy/features/pim/enrichment/product/mass-edit/classify_product.feature, tests/legacy/features/pim/enrichment/product/mass-edit/classify_product_model.feature, tests/legacy/features/pim/enrichment/product/mass-edit/edit-common-attribute/edit_common_attributes.feature, tests/legacy/features/pim/enrichment/product/mass-edit/edit-common-attribute/edit_common_attributes_images.feature, tests/legacy/features/pim/enrichment/product/mass-edit/edit-common-attribute/edit_common_attributes_metric.feature, tests/legacy/features/pim/enrichment/product/mass-edit/edit-common-attribute/edit_common_attributes_product_model.feature, tests/legacy/features/pim/enrichment/product/mass-edit/edit-common-attribute/edit_common_attributes_scopable_localizable.feature, tests/legacy/features/pim/enrichment/product/mass-edit/edit-common-attribute/edit_common_localized_attributes.feature, tests/legacy/features/pim/enrichment/product/mass-edit/mass_actions_on_all_entities.feature, tests/legacy/features/pim/enrichment/product/mass-edit/mass_add_to_existing_product_model.feature, tests/legacy/features/pim/enrichment/product/mass-edit/mass_edit_products_and_product_models.feature
=> Critical use cases for bulk actions

.circleci/config.yml, .circleci/run_behat.sh, .circleci/run_phpunit.sh
=> Mark phpunit step as failed when at least one test fail

tests/legacy/features/Context/Page/Base/Form.php
Fixes
tests/legacy/features/pim/enrichment/product/validation/validate_text_attributes.feature:69
tests/legacy/features/pim/enrichment/product/validation/validate_metric_attributes.feature:56
tests/legacy/features/pim/enrichment/product/completeness/remove_completeness.feature:25
=> circleci: fix another tests

src/Akeneo/Pim/Structure/Bundle/Controller/InternalApi/AttributeOptionController.php, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/attribute-option/create.js, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/attribute-option/form.js, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/attribute-option/form.html, tests/legacy/features/Context/Page/Base/Form.php
Fix weird design on the attribute option creation
https://github.com/akeneo/design/issues/60
=> design-60: Fix add option modal

src/Oro/Bundle/PimDataGridBundle/Resources/public/templates/filter/search-filter.html
https://github.com/akeneo/pim-enterprise-dev/pull/5236
=> APAI-480: Fix front search

.circleci/config.yml
Enable static front test on Circle CI
=> CircleCI - Run static front tests

.circleci/config.yml
=> CircleCI - Run acceptance back tests

.circleci/config.yml
=> Modify crontab configuration and the branch to launch

CHANGELOG-2.3.md, src/Pim/Bundle/ConnectorBundle/Resources/translations/messages.en.yml
Fix missing translations on product model import
=> PIM-7934: Fix translations of product model import

CHANGELOG-3.0.md, src/Akeneo/Pim/Structure/Bundle/Resources/config/validation/attribute.yml, tests/back/Pim/Structure/Integration/Attribute/Validation/GlobalConstraintsIntegration.php
Add constraints on attribute code - not allow to create an attribute with code "attributes".
=> PIM-7927: Fix constraints on attribute code

package.json, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/attributes/completeness.js, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/OptionEditor.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/FieldContainer.less
Bump webpack web server and various CSS fixes
=> PIM-7862: fix multiple tickets

src/Akeneo/Channel/.php_cd.php, src/Akeneo/Pim/Enrichment/.php_cd.php, src/Akeneo/Pim/Structure/.php_cd.php, src/Akeneo/UserManagement/.php_cd.php
=> Add ticket number to coupling issues

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/Subsection.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/Grid.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/GridContainer.less, tests/front/common/base.jest.json
See https://github.com/akeneo/pim-enterprise-dev/pull/5340
=> PIM-7915: add style for EE

CHANGELOG-3.0.md, composer.lock, src/Akeneo/Platform/Bundle/AnalyticsBundle/DataCollector/StorageDataCollector.php, src/Akeneo/Platform/Bundle/AnalyticsBundle/Resources/config/data_collectors.yml, var/SymfonyRequirements.php, yarn.lock
This PR includes the DB Port number on the DSN that is used on the system information page.
=> Fix DSN to consider the port number on system information page

src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/base/variables.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/TextareaField.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/form/common/fields/textarea-monospaced.html, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/form/tab/section-large.html
Add visual components needed by the SSO (can be reused for other use cases).
=> AOB-334: Add visual components

src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/fields/copiable-text.ts, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/fields/field.js, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/button/IconButton.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/form/common/fields/copiable-text.html, src/Akeneo/UserManagement/Bundle/Controller/SecurityController.php
=> Aob 335 - Add copiable text field

composer.json
Update repository dependencies
- "twig/extensions" from "1.2.0" to "1.3.0"
Force repository dependencies
- "twig/twig" to "1.36.0" (in order to not bump to 2.x version)
As those packages are required by "simplesamlphp/simplesamlphp" who is required for the SSO of the Onboarder projec! …
=> Update "twig/extensions" and "twig/twig"

.ci/Dockerfile
=> Migrate nodeJS 8.x to 10.x

composer.lock, package.json, src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filters-column.ts, yarn.lock
=> Update front dependencies

tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/PartialUpdateListProductEndToEnd.php, tests/legacy/features/pim/enrichment/product/datagrid/filtering/filter_products.feature, tests/legacy/features/pim/enrichment/product/export/export_products.feature, tests/legacy/features/pim/enrichment/product/import/import_products.feature, tests/legacy/features/pim/enrichment/product/pef/edit_product.feature
=> Add tag for migration scenario

tests/back/Integration/TestCase.php
Container is used before starting the install of the DB to get the kernel path for the configuration files.
https://github.com/akeneo/pim-enterprise-dev/blob/master/tests/back/Pim/WorkOrganization/Integration/TeamworkAssistant/TeamworkAssistantTestCase.php#L42
| Tech Doc …
=> Fix integration tests in EE

composer.lock, docker-compose.yml, yarn.lock
This PR update the `docker-compose.yml` file to use the new `akeneo/node:10` image, to fit the Akeneo 3.0 requirements.
=> Use "akeneo/node" image in docker-compose

src/Oro/Bundle/UserBundle/Controller/UserController.php, src/Pim/Bundle/UserBundle/Resources/config/removers.yml
=> PIM-7962: use baseRemover to delete user to do not use doctrine events

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/FieldContainer.less
see https://github.com/akeneo/pim-enterprise-dev/pull/5493
=> PIM-7835: fix css for fields

.circleci/config.yml
=> Modify the target branch for the nightly builds of Circle CI

.ci/Jenkinsfile, CHANGELOG-3.0.md, UPGRADE.md, app/config/pim_parameters.yml, bin/docker/pim-setup.sh, composer.json, composer.lock, docker-compose.yml, src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/SearchQueryBuilder.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/elasticsearch/product_mapping.yml, src/Akeneo/Pim/Enrichment/Bundle/Resources/elasticsearch/settings.yml, tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/SearchQueryBuilderSpec.php
=> TIP-1041: ES6 Support

.circleci/config.yml
=> Increase CircleCi parallelism

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/Notification.less
=> APAI-494: Add a "robot" notification icon

.ci/Jenkinsfile
=> CI improvement 2.3

.ci/Jenkinsfile
=> [WIP] ci-pimprovement 2.0

.ci/Jenkinsfile
=> improvement 3.x

src/Oro/Bundle/PimDataGridBundle/Resources/config/requirejs.yml, src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/action/delete-action.js, src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/action/delete-confirm.ts
https://github.com/akeneo/pim-enterprise-dev/pull/5515
=> APAI-471: Extract confirm dialog for datagrid entity deletion

.circleci/config.yml
=> Change the parallelism

src/Akeneo/Tool/Bundle/BatchQueueBundle/tests/integration/Launcher/QueueJobLauncherIntegration.php
=> Delete check on auto increment id to stabilize test

tests/legacy/features/pim/enrichment/category/list_categories.feature, tests/legacy/features/pim/enrichment/category/remove_a_category.feature, tests/legacy/features/pim/enrichment/product-group/import_groups.feature, tests/legacy/features/pim/enrichment/product/datagrid/datagrid_views.feature, tests/legacy/features/pim/enrichment/product/datagrid/products_category_backtothegrid.feature, tests/legacy/features/pim/enrichment/product/mass-edit/apply_permissions_on_mass_edit_actions.feature, tests/legacy/features/pim/enrichment/product/pef/comments.feature, tests/legacy/features/pim/enrichment/product/pef/edit_product.feature, tests/legacy/features/pim/enrichment/product/pef/join_a_document_to_a_product.feature, tests/legacy/features/pim/structure/attribute/option/edit_attribute_options.feature, tests/legacy/features/platform/export/execute_an_export.feature, tests/legacy/features/user-management/group/create_edit_and_delete_group.feature, tests/legacy/features/user-management/role/create_edit_and_delete_role.feature
=> Fix stability of the tests by using a spin

src/Akeneo/UserManagement/Bundle/Form/Handler/ResetHandler.php
Fix user reset password action, who use the `process` method, who was burned with AbsractUserHandler
=> Fix ResetHandler it fixes the reset action

.circleci/config.yml, .circleci/docker-compose.override.yml.dist, .circleci/run_behat.sh, .circleci/run_phpunit.sh, .gitignore, bin/docker/pim-setup.sh
This PR:
- backports the Circle CI configuration and script to 2.0
=> #9469 CircleCI configuration for 2.0

upgrades/schema/Version_3_0_20181030150153_update_versioning_entities.php
=> Paginate versioning update

.circleci/config.yml, .circleci/docker-compose.override.yml.dist, .circleci/run_behat.sh, .circleci/run_phpunit.sh, bin/docker/pim-setup.sh, composer.json
=> #9468 Backport Circle CI configuration on 2.3

UPGRADE.md
Copy/paste of the EE `UPGRADE.md` guide where all EE particularities have been removed.
=> Migration guide for CE

UPGRADE.md
=> Fix upgrade3

tests/legacy/features/Pim/Behat/Context/NavigationContext.php, tests/legacy/features/acl/assert_acl.feature
Done in mobreview with @arnolanglade  and @grena .
=> GITHUB-9476: stabilize acl scenario

composer.json
=> Merge 3.0 into 3.0.1

CHANGELOG-3.0.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/menu/help.html
Getting a 404 error when trying to access "Help" menu in version 3.0.
=> PIM-8044: Fix link to helpdesk

composer.json
Incorrect alias on dev-master and the others are useless
=> Remove composer branch aliases

CHANGELOG-3.0.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/product/field/boolean.html
=> PIM-8028: Fix labels for boolean values

tests/back/Acceptance/AttributeOption/InMemoryAttributeOptionRepository.php, tests/back/Acceptance/spec/AttributeOption/InMemoryAttributeOptionRepositorySpec.php
=> Fix attribute option repository for in memory implementation

tests/legacy/features/pim/enrichment/product/import/import_products.feature
=> Critical imports

Makefile
A simple makefile consists of "rules" with the following shape:
```
target ... : prerequisites ...
command
...
...
```
A **target** is usually the name of a file that is generated by a program; examples of targets are executable or object files. A target can also be the name of an action to carry out, such as `clean' (see section Phony Targets).
A **prerequisite** is a file that is used as input to create the target. A target often depends on several files.
A **command** is an action that make carries out. A rule may have more than one command, each on its own line. Please note: you need to put a tab character at the beginning of every command line! This is an obscurity that catches the unwary. 
Extra information …
=> Introduce makefile with basic target

CHANGELOG-3.0.md, src/Akeneo/UserManagement/Bundle/Controller/ResetController.php
This PR fixes the 500 error when resetting a password. According to IM-824 the same message should be returned for an existent or non-existent user. 
=> PIM-8057: [SLA] Fix 500 error when requesting "forgot password"

CHANGELOG-2.0.md, src/Pim/Bundle/CatalogBundle/tests/integration/Completeness/AbstractCompletenessTestCase.php, src/Pim/Bundle/CatalogBundle/tests/integration/Completeness/UpdateMissingAttributesIntegration.php, src/Pim/Component/Catalog/Completeness/CompletenessGenerator.php
Backport of https://github.com/akeneo/pim-community-dev/pull/9522
=> PIM-8058: Backport PIM-8020 to update missing attributes

Makefile, make-file/channel.mk, make-file/enrichment.mk, make-file/structure.mk, make-file/user-management.mk
A simple makefile consists of "rules" with the following shape:
```
target ... : prerequisites ...
command
...
...
```
A **target** is usually the name of a file that is generated by a program; examples of targets are executable or object files. A target can also be the name of an action to carry out, such as `clean' (see section Phony Targets).
A **prerequisite** is a file that is used as input to create the target. A target often depends on several files.
A **command** is an action that make carries out. A rule may have more than one command, each on its own line. Please note: you need to put a tab character at the beginning of every command line! This is an obscurity that catches the unwary. 
Extra information [here](https://ftp.gnu.org/old-gnu/Manuals/make-3.79.1/html_chapter/make_2.ht …
=> Improve makefile

CHANGELOG-3.0.md, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/datagrid/association_product_model.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/mass_edit/change_parent_product.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/attributes.js, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/TitleContainer.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/FilterBox.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/form/creation/modal.html, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/mass-edit/product/update-entity-with-family-variant-parent.html, src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/messages.en_US.yml, src/Akeneo/UserManagement/Bundle/Resources/translations/jsmessages.en_US.yml, src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/metric-filter.js, src/Oro/Bundle/PimDataGridBundle/Resources/public/templates/filter/metric-filter.html
=> PIM-8143: Fix missing translations

CHANGELOG-3.0.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/VariantNavigation.less
Component of Variant Navigation was broken due to dropdown refactoring.
Each line is now 100% full size, and completeness is aligned on the right.
=> PIM-8145: Fix design on variant navigation

CHANGELOG-3.0.md, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/renderers.yml
In the PEF, there is a 500 internal error when trying to load the PDF.
EE PR : https://github.com/akeneo/pim-enterprise-dev/pull/5721
=> PIM-8017: Fix PDF generation

CHANGELOG-2.0.md, src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Query/VariantProductRatio.php
Before we were using the Doctrine Query Builder and it was taking the wrong path.
Now we use a subquery and help him with a DISTINCT. (See the CODE)
=> SLA-8054: Fix slow mysql query due to wrong path

CHANGELOG-3.0.md, src/Akeneo/Pim/Structure/Bundle/Resources/config/form_extensions/attribute/reference_data_multi.yml, src/Akeneo/Pim/Structure/Bundle/Resources/config/form_extensions/attribute/reference_data_simple.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/attribute/boolean.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/attribute/date.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/attribute/file.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/attribute/image.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/attribute/metric/create.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/attribute/metric/edit.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/attribute/number.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/attribute/price.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/attribute/select.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/attribute/text.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/attribute/textarea.yml
The available locales field was not multiple.
=> PIM-8153: Fix locale specific field to allow multiple locales

CHANGELOG-3.0.md, src/Akeneo/Pim/Enrichment/Bundle/Resources/views/CategoryTree/form.html.twig, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/ProjectWidget.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/FieldContainer.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/lib/select2.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/product/field/field.html, src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_US.yml
Various design fixes (several cards because they are very little ones)
- missing translations
- invisible spaces on labels
- weird alignment on widget selector
- multiselect alignment
=> PIM-8144 + 8143 + 8156

tests/legacy/features/pim/structure/association-type/create_association_type.feature
=> Fix unstable scenario

tests/legacy/features/Context/Page/Base/Grid.php
Add a test decorator for grid filter with type "reference entity".
=>  PIM-8130: add test decorator for reference entity attributes 

internal_doc/enrichment/product_grid_extensibility.md, internal_doc/index.md
=> PIM-7660: fix the documentation to add an additional property in the datagrid

UPGRADE.md
In UPGRADE.md we don't talk about restart php7.2-fpm.
EE: https://github.com/akeneo/pim-enterprise-dev/pull/5733
=> Add restart fpm in UPGRADE

.circleci/config.yml
https://github.com/akeneo/pim-community-dev/issues/9640
=> CI-9640: Homogenize Behat job name

.circleci/config.yml, .circleci/docker-compose.override.yml.dist, .circleci/run_behat.sh, .circleci/run_phpunit.sh, .gitignore, behat.yml.dist, bin/docker/pim-setup.sh, composer.json, src/Pim/Bundle/CatalogBundle/tests/integration/Completeness/AbstractCompletenessPerAttributeTypeTestCase.php, src/Pim/Bundle/CatalogBundle/tests/integration/Completeness/AbstractCompletenessTestCase.php, src/Pim/Bundle/CatalogBundle/tests/integration/Completeness/AttributeType/BooleanAttributeTypeCompletenessIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/Completeness/AttributeType/DateAttributeTypeCompletenessIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/Completeness/AttributeType/FileAttributeTypeCompletenessIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/Completeness/AttributeType/IdentifierAttributeTypeCompletenessIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/Completeness/AttributeType/ImageAttributeTypeCompletenessIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/Completeness/AttributeType/MetricAttributeTypeCompletenessIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/Completeness/AttributeType/NumberAttributeTypeCompletenessIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/Completeness/AttributeType/OptionAttributeTypeCompletenessIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/Completeness/AttributeType/OptionsAttributeTypeCompletenessIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/Completeness/AttributeType/PriceCollectionAttributeTypeCompletenessIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/Completeness/AttributeType/ReferenceDataMultiAttributeTypeCompletenessIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/Completeness/AttributeType/ReferenceDataSimpleAttributeTypeCompletenessIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/Completeness/AttributeType/TextAttributeTypeCompletenessIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/Completeness/AttributeType/TextareaAttributeTypeCompletenessIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/Completeness/CompletenessForLocalisableAttributeIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/Completeness/CompletenessForNonRequiredAttributeIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/Completeness/CompletenessForScopableAndLocalisableAttributeIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/Completeness/CompletenessForScopableAttributeIntegration.php
22 tests are failing. Merging.
=> Setup circleci for 1.7

CHANGELOG-3.0.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/base/variables.less
DSM compliant
http://creative.yull.design/typography/
=> PIM-8165: Increase font sizes

CHANGELOG-2.3.md, src/Pim/Bundle/EnrichBundle/Resources/public/templates/export/product/edit/content/structure/attributes-selector.html
=> PIM-8162: use the catalog locale in product export builder

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/Dropdown.less
=> PIM-8154: Fix Validation rule dropdown overlapped with the sticky footer 

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/fields/field.js, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/form/common/fields/field.html
Needed by https://github.com/akeneo/pim-enterprise-dev/pull/5469.
=> AOB-337: Introduce warnings for common fields

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/CatalogVolume.less
- Add style for catalog volume monitoring
=> PIM-7863: Add style

composer.json, composer.lock
=> Update Symfony to 3.4.23

CHANGELOG-3.0.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/catalog-volume/header.ts
=> PIM-8195: Fix JS error on catalog volume monitoring screen

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/FieldContainer.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/lib/select2.less
=> PIM-8168: add style for multiple link on reference entity

.gitignore, composer.json, composer.lock, src/Akeneo/Tool/Bundle/ApiBundle/tests/integration/ApiTestCase.php, tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/Boolean/BooleanFilterIntegration.php, tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/Boolean/LocalizableFilterIntegration.php, tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/Boolean/LocalizableScopableFilterIntegration.php, tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/Boolean/ScopableFilterIntegration.php, tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/Date/DateFilterIntegration.php, tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/Date/LocalizableFilterIntegration.php, tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/Date/LocalizableScopableFilterIntegration.php, tests/back/Pim/Enrichment/Integration/PQB/Filter/Attribute/Media/LocalizableFilterIntegration.php, tests/back/Pim/Enrichment/Integration/Product/Export/Writer/YamlWriterIntegration.php
I update to PHPUnit 8.
The few removed annotation you see is because it raises a Warning as it will be removed in PHPUnit 9. I won't do all of them, so if you can remove some of them when you can that would be great (Boyscoot mode) …
=> Update To PHPUnit 8

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/Column.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/FilterBox.less
=> PIM-7933: Display the number of records and results for an entity in the grid

CHANGELOG-2.3.md, src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Query/DescendantProductIdsQuery.php, src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Query/DescendantProductModelIdsQuery.php, src/Pim/Bundle/CatalogBundle/Resources/config/queries.yml, src/Pim/Bundle/CatalogBundle/tests/integration/Doctrine/ORM/Query/DescendantProductIdsIntegration.php, src/Pim/Bundle/CatalogBundle/tests/integration/Doctrine/ORM/Query/DescendantProductModelIdsIntegration.php, src/Pim/Component/Catalog/ProductModel/Query/DescendantProductIdsQueryInterface.php, src/Pim/Component/Catalog/ProductModel/Query/DescendantProductModelIdsQueryInterface.php
=> PIM-8187: Adds queries to fetch descendants product model ids and product ids

CHANGELOG-3.0.md, src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filters-column.ts, src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/cell/boolean-label-cell.js
=> PIM-8217: Fix missing translations on product grid (Filters, Done, Yes and No)

CHANGELOG-3.0.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/family/form/attributes/attributes.js
=> PIM-8221: Fix missing translations on family attributes tab (Required, Not required)

CHANGELOG-2.3.md, src/Pim/Bundle/ApiBundle/Resources/config/routing/product_model.yml, src/Pim/Bundle/EnrichBundle/Resources/config/routing/product_model.yml
See
https://github.com/akeneo/pim-community-dev/pull/8258/commits/58f5fe0091955d26589f570e30281470572647ba
=> PIM-8222: Fix product model issues when SKU contains / (create variant through UI and get product models via API)

CHANGELOG-3.0.md, src/Akeneo/Pim/Structure/Bundle/Resources/translations/jsmessages.en_US.yml, src/Akeneo/Tool/Bundle/ConnectorBundle/Resources/translations/jsmessages.en_US.yml, src/Oro/Bundle/PimDataGridBundle/Resources/translations/messages.en_US.yml
=> PIM-8223 and PIM-8224: Fix missing translations

.circleci/config.yml
Since the last merge, end-to-end tests are not executed anymore, because we changed the way to list and execute tests (we list tests from phpunit instead of using grep/globbing).
`OK`: Done / …
=> Use the scripts to list tests from phpunit in order to execute end to end tests

src/Pim/Bundle/EnrichBundle/Resources/public/js/attribute/form/edit-form.js, src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/edit-form.js
This is a backport of https://github.com/akeneo/pim-community-dev/pull/9614/commits/c560ddb3fbe598a9019f8e707ef632e7a847c904 (done in 3.0.7). Needed for the onboarder.
=> AOB-280: Fix scroll on forms

tests/back/Pim/Enrichment/EndToEnd/Category/ExternalApi/CreateCategoryEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/Media/ListMediaFileEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/SuccessListProductEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/VariantProduct/ExternalApi/SuccessListVariantProductEndToEnd.php
=> Critical use cases api

Makefile
Since the introduction of the Makefile in the pim, the front install process has changed.
It is important to impact the Makefile uptodate to keep it usefull 
=> fix broken target

src/Pim/Bundle/ApiBundle/Controller/ProductModelController.php, src/Pim/Bundle/ApiBundle/Doctrine/ORM/Repository/ProductModelRepository.php, src/Pim/Bundle/ApiBundle/Resources/config/repositories.yml
Introduce ProductModelRepository in Api bounded context which is used in EE.
=> PIM-8231: Product model drafts/proposals through API are well applied

composer.json
We are not compatible with doctrine/collections 1.6
=> Hotfix: require doctrine/collections 1.5.0 fixed version

internal_doc/architecture/context_map.md
Add "(Enterprise Edition only)" for assets
=> Update assets with "(Enterprise Edition only)"

composer.json, composer.lock
We are not compatible with doctrine/collections 1.6
=> Hotfix: fixed doctrine/collections requirement

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/Column.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/button/IconButton.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/FilterBox.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/Grid.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/GridContainer.less, src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/multiselect-filter.js, src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/select-filter.js, src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/text-filter.js
https://github.com/akeneo/pim-enterprise-dev/pull/5907
=> PXD-83: Fix proposals page

composer.json
Same fix than on 3.0 : https://github.com/akeneo/pim-community-dev/pull/9811
and master : https://github.com/akeneo/pim-community-dev/pull/9818
=> Fix target platform

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/FilterBox.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/lib/select2.less, tests/front/unit/jest/unit.jest.js
=> PIM-8182: adding simple option filter

CHANGELOG-3.0.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/images/icon-edit-white.svg, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/mass-edit/form/product/associate.js, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/Badge.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/TabContainer.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/TitleContainer.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/button/IconButton.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/FilterBox.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/GridContainer.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/GridToolbar.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/attribute-group/tab/attribute.html, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/attribute-option/edit.html, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/attribute-option/show.html, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/common/form-container.html, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/product/tab/associations.html, src/Akeneo/UserManagement/Bundle/Resources/views/Role/update.html.twig
Contains design fixes listed in the commits list
=> PXD: Various fixes (2)

tests/front/unit/jest/unit.jest.js
This PR adds the config for reporting code coverage in our jest unit tests
=> Add back code coverage report on jest unit tests

composer.json, composer.lock
Upgrades Twig to get passed this issue: https://symfony.com/blog/twig-sandbox-information-disclosure
Solves #9787
=> Upgrade Twig to v1.38.3

CHANGELOG-3.0.md, src/Akeneo/UserManagement/Bundle/Resources/views/Group/update.html.twig
=> PIM-8267: fix user's group delete translation

tests/back/Acceptance/AttributeOption/InMemoryAttributeOptionRepository.php, tests/back/Acceptance/spec/AttributeOption/InMemoryAttributeOptionRepositorySpec.php
| Added acceptance tests            | OK
=>  DAPI-151: Fix InMemoryAttributeOptionRepository::findBy

CHANGELOG-1.7.md
=> Merge 20 into 23

src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/ProductGridFilterController.php
=> Fix PIM-8272: add a check for a non existing option

CHANGELOG-1.7.md, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/doctrine/Product/Product.orm.yml
=> Merge 23 into 30

src/Akeneo/Pim/Enrichment/Bundle/Category/Query/Sql/GetCategoryCodesByProductIdentifiers.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml, tests/back/Pim/Enrichment/Integration/Category/Query/Sql/GetCategoryCodesByProductIdentifiersIntegration.php
Query to get category codes by a list of product identifiers
| Changelog updated                 | SHOULD I ?
=> TIP-1077: Query to get category codes by product identifiers

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/FilterBox.less
=> PIM-8184: add filter hint style

src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/ProductController.php, src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/ProductModelController.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/connector/use_cases.yml, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/controllers.yml, src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/ApplyProductSearchQueryParametersToPQB.php, src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/ListProductModelsQuery.php, src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/ListProductModelsQueryHandler.php, src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/Validator/ListProductModelsQueryValidator.php, src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/Validator/ValidatePagination.php, tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/ListProductModelWithCompletenessEndToEnd.php, tests/back/Pim/Enrichment/EndToEnd/Product/ProductModel/ExternalApi/ListSearchAfterProductModelEndToEnd.php, tests/back/Pim/Enrichment/Specification/Component/Product/Connector/UseCase/ApplyProductSearchQueryParametersToPQBSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Connector/UseCase/ListProductModelsQueryHandlerSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Connector/UseCase/ListProductsQueryHandlerSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Connector/UseCase/Validator/ListProductModelsQueryValidatorSpec.php
https://github.com/akeneo/pim-community-dev/pull/9889
Merged in the wrong branch
=> TIP-1143: Create Product Model Query

src/Akeneo/Pim/Enrichment/Bundle/Product/Query/Sql/GetValuesAndPropertiesFromProductIdentifiers.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml, tests/back/Pim/Enrichment/Integration/Product/Query/Sql/GetValuesAndPropertiesFromProductIdentifiersIntegration.php
=> TIP-1051: Add GetValuesAndPropertiesFromProductIdentifiers

src/Akeneo/Pim/Enrichment/Bundle/Product/Query/Sql/GetProductAssociationsByProductIdentifiers.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml, tests/back/Pim/Enrichment/Integration/Product/Query/Sql/GetProductAssociationsByProductIdentifiersIntegration.php
The goal of this PR is given a list of product identifiers, get a list of product associated by type.
| Added integration tests           | y
=> TIP-1080: Get associations by product identifiers

src/Akeneo/Pim/Enrichment/Bundle/Product/Query/Sql/GetProductModelAssociationsByProductIdentifiers.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml, tests/back/Pim/Enrichment/Integration/Product/Query/Sql/GetProductModelAssociationsByProductIdentifiersIntegration.php
This PR fetches product model associations by product identifiers
=> TIP-1081: Fetch product models associations by product identifiers

src/Akeneo/Pim/Enrichment/Bundle/Product/Query/Sql/GetCategoryCodesByProductIdentifiers.php, src/Akeneo/Pim/Enrichment/Bundle/ProductModel/Query/Sql/GetCategoryCodesByProductModelCodes.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml, tests/back/Pim/Enrichment/Integration/Product/Query/Sql/GetCategoryCodesByProductIdentifiersIntegration.php, tests/back/Pim/Enrichment/Integration/ProductModel/Query/Sql/GetCategoryCodesByProductModelCodesIntegration.php
Get category codes by product models
=> TIP-1131 categories by product model

src/Akeneo/Pim/Enrichment/Bundle/ProductModel/Query/Sql/GetProductModelsAssociationsByProductModelCodes.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml, tests/back/Pim/Enrichment/Integration/ProductModel/Query/Sql/GetProductModelsAssociationsByProductModelCodesIntegration.php
=> TIP-1135: Get Product Models assocations by product Models codes

src/Akeneo/Pim/Enrichment/Bundle/ProductModel/Query/Sql/GetGroupAssociationsByProductModelCodes.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml, tests/back/Pim/Enrichment/Integration/ProductModel/Query/Sql/GetGroupAssociationsByProductModelCodesIntegration.php
=> TIP-1133: Get Group Associations by Product Model Codes

src/Akeneo/Pim/Enrichment/Bundle/ProductModel/Query/Sql/GetValuesAndPropertiesFromProductModelCodes.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml, tests/back/Pim/Enrichment/Integration/ProductModel/Query/Sql/GetValuesAndPropertiesFromProductModelCodesIntegration.php
=> TIP-1136: Get Values and Properties from Product Model Codes

src/Akeneo/Pim/Enrichment/Bundle/ProductModel/Query/Sql/GetGroupAssociationsByProductModelCodes.php, src/Akeneo/Pim/Enrichment/Bundle/ProductModel/Query/Sql/GetProductModelsAssociationsByProductModelCodes.php, src/Akeneo/Pim/Enrichment/Bundle/ProductModel/Query/Sql/GetValuesAndPropertiesFromProductModelCodes.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml, tests/back/Pim/Enrichment/Integration/ProductModel/Query/Sql/GetGroupAssociationsByProductModelCodesIntegration.php, tests/back/Pim/Enrichment/Integration/ProductModel/Query/Sql/GetProductModelsAssociationsByProductModelCodesIntegration.php, tests/back/Pim/Enrichment/Integration/ProductModel/Query/Sql/GetValuesAndPropertiesFromProductModelCodesIntegration.php
You can read it Commit by Commit
does this Pull Request do? reference the related issue?) --->
=> TIP-1133 / TIP-1135 / TIP-1136

composer.json, composer.lock
Mainly to take into account fixes done by Symfony for several CVEs.
- https://symfony.com/blog/symfony-3-4-23-released
- https://symfony.com/blog/symfony-3-4-24-released
- https://symfony.com/blog/symfony-3-4-25-released
- https://symfony.com/blog/symfony-3-4-26-released
=> Bump symfony version to 3.4.26

src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_base_export_edit.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_product_export_edit.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_product_model_export_edit.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_base_export_edit.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_product_export_edit.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_product_model_export_edit.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/yml_base_export_edit.yml
cf. https://github.com/akeneo/pim-community-dev/pull/9885 for the description
| Changelog updated                 | 
| Micro Demo to the PO (Story only) | TODO
=> TIP-1091: Hide the file path property for cloud edition

.circleci/config.yml, src/Akeneo/Pim/Enrichment/Bundle/Command/CleanRemovedAttributesFromProductAndProductModelCommand.php, src/Akeneo/Pim/Enrichment/Bundle/Command/PurgeCompletenessCommand.php, src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Attribute/TextAreaFilter.php, src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Attribute/TextFilter.php, src/Akeneo/Pim/Enrichment/Bundle/PdfGeneration/Builder/DompdfBuilder.php, src/Akeneo/Pim/Enrichment/Component/Product/Connector/Processor/Denormalizer/ProductProcessor.php, src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/DateValueFactory.php, src/Akeneo/Pim/Enrichment/Component/Product/Updater/Setter/MediaAttributeSetter.php
This reverts commit 330b864379391179e0e04f242dbe02a97f383674 which breaks the EE test tests/back/Pim/Permission/Integration/Import/Product/ImportProductsWithCategoriesIntegration.php::testToSkipProductsWithNotViewableCategoriesWithPermissions
I'll dig next week to understand exactly what happens
=> Revert "Fix possibly undefined variables"

src/Akeneo/Pim/Structure/Bundle/DependencyInjection/AkeneoPimStructureExtension.php, src/Akeneo/Pim/Structure/Bundle/Query/PublicApi/AttributeOption/Sql/GetExistingAttributeOptionCodes.php, src/Akeneo/Pim/Structure/Bundle/Resources/config/queries.yml, src/Akeneo/Pim/Structure/Component/Query/PublicApi/AttributeOption/GetExistingAttributeOptionCodes.php, tests/back/Pim/Structure/Integration/AttributeOption/GetExistingAttributeOptionCodesFromOptionCodesSqlIntegration.php
=> TIP-X: Get existing option codes from option codes

src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/ProductModelController.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/connector/use_cases.yml, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/controllers.yml, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/cursors.yml, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/normalizers.yml, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/query_builders.yml, src/Akeneo/Pim/Enrichment/Bundle/Storage/ORM/Connector/GetConnectorProductModels.php, src/Akeneo/Pim/Enrichment/Bundle/Storage/ORM/Connector/GetMetadataForProductModel.php, src/Akeneo/Pim/Enrichment/Component/Product/Connector/ReadModel/ConnectorProductModel.php, src/Akeneo/Pim/Enrichment/Component/Product/Connector/ReadModel/ConnectorProductModelList.php, src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/ListProductModelsQuery.php, src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/ListProductModelsQueryHandler.php, src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/ExternalApi/ConnectorProductModelNormalizer.php, src/Akeneo/Pim/Enrichment/Component/Product/ProductModel/Query/GetConnectorProductModels.php, src/Akeneo/Pim/Enrichment/Component/Product/ProductModel/Query/GetMetadataInterface.php, tests/back/Pim/Enrichment/Specification/Bundle/Storage/ORM/Connector/GetConnectorProductModelsSpec.php, tests/back/Pim/Enrichment/Specification/Bundle/Storage/ORM/Connector/GetConnectorProductsFromWriteModelSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ReadModel/ConnectorProductModelListSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ReadModel/ConnectorProductModelSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Connector/UseCase/ListProductModelsQueryHandlerSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/ExternalApi/ConnectorProductModelNormalizerSpec.php
This PR introduces a read model for ProductModels for the API.
=> TIP-1086: Create a product model read model for the API

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/images/icon-erase.svg, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/button/IconButton.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/lib/select2.less
See https://github.com/akeneo/pim-enterprise-dev/pull/6033
=> PIM-8292: add completeness to record selector

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/Grid.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/FieldContainer.less
see https://github.com/akeneo/pim-enterprise-dev/pull/6033
=> PIM-8284: add bottom border on record grid rows

docker-compose.yml
=> Add default value for Elasticsearch Java OPS

src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_product_import_show.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/import/switcher-item.js, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/import/switcher.js
=> TIP-1092 Hide import now button from the import profile export

.circleci/config.yml
This PR adds temporary a nightly build on 3.2-tmp branch
=> Add nightly on 3.2-tmp

src/Akeneo/Tool/Bundle/VersioningBundle/Manager/VersionManager.php
Just add a commend to deprecate the non real-time versioning that leads to issues and is not used anymore.
A PR is in progress in 2.3: https://github.com/akeneo/pim-enterprise-dev/pull/6060 to remove the last use of this method …
=> PIM-8298: Deprecate not real-time versioning

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/lib/jquery.multiselect.less
=> DAPI-221: be able to fully read the filter title in the dropdown of Franklin Subscription filter

frontend/build/compile-less.js
This PR lets the less compilation script create the web/css folder if it doesn't already exist. 
=> Create web/css folder if it doesn't exist

.circleci/config.yml, .circleci/local-object-storage-setup.sh, .gitignore, composer.json, composer.lock, docker-compose.override.yml.dist, docker-compose.yml
This PR makes the CI uses an object storage for catalog when running the tests
=> TIP-1162 Uses object storage on CI

internal_doc/architecture/context_map.md
=> Add the last definitions of bounded context

CHANGELOG-3.0.md, src/Oro/Bundle/PimDataGridBundle/Resources/config/controllers.yml
Use authenticated job launcher for quick_export from datagrid
=> PIM-8325: Use authenticated job launcher

CHANGELOG-2.3.md, webpack.config.js
=> PIM-8330: Allow installation folder to contain src... for webpack

CHANGELOG-3.0.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/lib/flags.less
=> PIM-8329: Add serbian CS flag

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/Grid.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/lib/jquery.multiselect.less
=> DAPI - feature branch (only frontend commits)

.circleci/local-object-storage-setup.sh, .gitignore, src/Akeneo/Platform/Bundle/ImportExportBundle/Controller/InternalApi/JobInstanceController.php, src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/controllers.yml, src/Akeneo/Platform/config/bundles/oneup_flysystem.yml, src/Akeneo/Tool/Bundle/ConnectorBundle/EventListener/FetchRemoteFileBeforeImport.php, src/Akeneo/Tool/Bundle/ConnectorBundle/Resources/config/event_listeners.yml, src/Akeneo/Tool/Component/Batch/Job/JobParameters.php, src/Akeneo/Tool/Component/Connector/Job/JobFileLocation.php, src/Akeneo/Tool/Component/Connector/spec/Job/JobFileLocationSpec.php
Make sure uploaded files for import are managed by Flysystem and download them before executing the import job.
=> TIP-1123 - Uploading and reading from Flysystem for import

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/fetcher/attribute-fetcher.js, tests/front/unit/jest/unit.jest.js
=> PIM-8142: add cache to attribute fetcher

src/Akeneo/Pim/Enrichment/Bundle/Product/Query/Sql/GetExistingReferenceDataCodes.php, src/Akeneo/Pim/Enrichment/Bundle/Resources/config/factories.yml, src/Akeneo/Pim/Enrichment/Component/Product/Factory/NonExistentValuesFilter/NonExistentReferenceDataMultiSelectValuesFilter.php, src/Akeneo/Pim/Enrichment/Component/Product/Factory/NonExistentValuesFilter/NonExistentReferenceDataSimpleSelectValuesFilter.php, src/Akeneo/Pim/Enrichment/Component/Product/Factory/ValueCollectionFactory.php, src/Akeneo/Pim/Enrichment/Component/Product/Query/GetExistingReferenceDataCodes.php, src/Akeneo/Pim/Structure/Bundle/Query/PublicApi/AttributeTypes/Sql/SqlGetAttributes.php, src/Akeneo/Pim/Structure/Component/Query/PublicApi/AttributeType/Attribute.php, tests/back/Pim/Enrichment/Specification/Component/Product/Factory/NonExistentValuesFilter/NonExistentReferenceDataMultiSelectValuesFilterSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Factory/NonExistentValuesFilter/NonExistentReferenceDataSimpleSelectValuesFilterSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Factory/ValueCollectionFactorySpec.php
Already GTMd in https://github.com/akeneo/pim-community-dev/pull/9997
=> TIP-1158: Add filter for reference data options (#9997)

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/sequential-edit.js
Trigger a new event `pim_enrich:form:sequential-edit` on the product edit form when we are in the context of a sequential edit.
=> DAPI-138: New event when starting sequential edit

src/Akeneo/Pim/Enrichment/Bundle/Resources/config/factories.yml, src/Akeneo/Pim/Enrichment/Component/Product/Factory/NonExistentValuesFilter/NonExistentPriceCollectionValueFilter.php, tests/back/Pim/Enrichment/Specification/Component/Product/Factory/NonExistentValuesFilter/NonExistentPriceCollectionValueFilterSpec.php
This PR adds the filter on the price collection.
=> TIP-1158: Add price collection value filter

CHANGELOG-3.0.md, src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/search-filter.js, src/Oro/Bundle/PimDataGridBundle/Resources/public/templates/filter/search-filter.html
The bug is described in the code in comment as it's a little bit tricky.
| Added legacy Behats               | n
| Added acceptance tests            | n
| Added integration tests           | n
=> PIM-8257: Fix user grid filter set when creating a new user

src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Connector/SqlGetConnectorProducts.php
Batch create a valueCollection
=> TIP-1158: Use create multiple from storage format

src/Akeneo/Pim/Enrichment/Component/Product/Connector/ReadModel/ConnectorProduct.php, tests/back/Pim/Enrichment/Specification/Component/Product/Connector/ReadModel/ConnectorProductSpec.php
=> TIP-1157: Handle empty associations

CHANGELOG-2.3.md, src/Pim/Bundle/UIBundle/Resources/public/less/components/grid/Grid.less
=> PIM-7321: Fix blinking grid elements in gallery mode

src/Akeneo/UserManagement/Bundle/Controller/Rest/UserController.php, src/Akeneo/UserManagement/Bundle/Resources/config/controllers.yml
| Review and 2 GTM                  | GTM (mob review)
=> PIM-8317: Provide a decimal separator in the UserContext in the front

CHANGELOG-3.0.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.en_US.yml, src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/jsmessages.fr_FR.yml, src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/label_or_identifier-filter.js
Goal: display "Rechercher sur libellé ou identifiant" instead of "Rechercher sur Label or identifier"
=> PIM-8366: Translate the placeholder in the quick search input

CHANGELOG-2.3.md, src/Pim/Bundle/UIBundle/Resources/public/less/components/TabContainer.less
=> PIM-7596: Fix margins on datagrids under tabs

src/Akeneo/Pim/Enrichment/Component/Product/Factory/ValueCollectionFactory.php, tests/back/Pim/Enrichment/Specification/Component/Product/Factory/ValueCollectionFactorySpec.php
Remove duplicate attribute codes ;)
=> TIP-1158: optimize the get of attribute codes

.circleci/config.yml, src/Akeneo/Pim/Enrichment/Bundle/Command/CleanRemovedAttributesFromProductAndProductModelCommand.php, src/Akeneo/Pim/Enrichment/Bundle/Command/PurgeCompletenessCommand.php, src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Attribute/TextAreaFilter.php, src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Attribute/TextFilter.php, src/Akeneo/Pim/Enrichment/Bundle/PdfGeneration/Builder/DompdfBuilder.php, src/Akeneo/Pim/Enrichment/Component/Product/Connector/Processor/Denormalizer/ProductProcessor.php, src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/DateValueFactory.php
This fixes possibly undefined variables.
=> Set phpstan to level 1

src/Akeneo/Pim/Enrichment/Component/Product/Model/AbstractProduct.php, src/Akeneo/Pim/Enrichment/Component/Product/Model/Events/BusinessEventsAwareInterface.php, src/Akeneo/Pim/Enrichment/Component/Product/Model/ProductInterface.php, tests/back/Pim/Enrichment/Specification/Component/Product/Model/ProductSpec.php
=> Add spec on categorized events

src/Akeneo/Pim/Enrichment/Component/Product/Model/AbstractProduct.php, src/Akeneo/Pim/Enrichment/Component/Product/Model/Events/AddParentToProduct.php, src/Akeneo/Pim/Enrichment/Component/Product/Model/Events/CategorizedProduct.php, src/Akeneo/Pim/Enrichment/Component/Product/Model/Events/ChangedParentOfProduct.php, src/Akeneo/Pim/Enrichment/Component/Product/Model/Events/UncategorizedProduct.php, tests/back/Pim/Enrichment/Specification/Component/Product/Model/ProductSpec.php
=> TIP-1171: add event when adding or changing the parent of a product

src/Akeneo/Pim/Enrichment/Component/Product/Model/AbstractProduct.php, src/Akeneo/Pim/Enrichment/Component/Product/Model/Events/ProductAddedToGroup.php, src/Akeneo/Pim/Enrichment/Component/Product/Model/Events/ProductRemovedFromGroup.php, tests/back/Pim/Enrichment/Specification/Component/Product/Model/ProductSpec.php
=> TIP-1171: Add events when product is added or removed from a group

src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Indexing/ProductAndProductModel/ProductPropertiesNormalizer.php
=> Remove dead code

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/FilterBox.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/Grid.less
=> PIM-8355: fix review comments

src/Akeneo/Pim/Enrichment/Bundle/Controller/ExternalApi/ProductController.php, src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/LoadEntityWithValuesSubscriber.php, src/Akeneo/Pim/Enrichment/Component/Product/Builder/EntityWithValuesBuilder.php, src/Akeneo/Pim/Enrichment/Component/Product/Builder/EntityWithValuesBuilderInterface.php, src/Akeneo/Pim/Enrichment/Component/Product/Builder/ProductBuilder.php, src/Akeneo/Pim/Enrichment/Component/Product/Model/AbstractProduct.php, src/Akeneo/Pim/Enrichment/Component/Product/Model/Events/ValueAdded.php, src/Akeneo/Pim/Enrichment/Component/Product/Model/Events/ValueDeleted.php, src/Akeneo/Pim/Enrichment/Component/Product/Model/Events/ValueEdited.php, src/Akeneo/Pim/Enrichment/Component/Product/Model/ProductInterface.php, tests/back/Pim/Enrichment/Integration/Doctrine/Common/Saver/ProductSaverIntegration.php, tests/back/Pim/Enrichment/Integration/EntityWithFamilyVariant/ChangeVariantFamilyStructureIntegration.php, tests/back/Pim/Enrichment/Integration/Fixture/EntityBuilder.php, tests/back/Pim/Enrichment/Integration/Product/DeleteUniqueValueInDatabaseIntegration.php, tests/back/Pim/Enrichment/Specification/Bundle/EventSubscriber/LoadEntityWithValuesSubscriberSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Builder/EntityWithValuesBuilderSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Builder/ProductBuilderSpec.php, tests/back/Pim/Enrichment/Specification/Component/Product/Model/ProductSpec.php
=> Tip 1171 values

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/FilterBox.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/Grid.less
Reverts akeneo/pim-community-dev#10184
=> Revert "PIM-8355: fix review comments"

CHANGELOG-2.3.md, CHANGELOG-3.0.md
We need to keep supported changelogs for previous versions to trace bug fixes
=> Add CHANGELOGS for supported versions

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/Progress.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/FieldContainer.less, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/HorizontalNavtab.less
- It adds a flat style to the progress bar element.
- Cleanup of some Franklin Insights specific styles that have been moved directly into the EE and FI bounded context.
Needed by this EE PR [DAPI-270](https://github.com/akeneo/pim-enterprise-dev/pull/6250)
| Tech Doc …
=> DAPI-270: Add flat style to progress bar & cleanup Franklin styles

CHANGELOG-3.1.md, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/attributes/copy-field.js, src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/field/wysiwyg-field.js
Fix wysiwig rendering on compare/translate
=> PIM-8419: Fix wysiwig in copy

CHANGELOG-3.0.md, src/Akeneo/Pim/Enrichment/Bundle/PdfGeneration/Renderer/ProductPdfRenderer.php, tests/back/Pim/Enrichment/Specification/Bundle/PdfGeneration/Renderer/ProductPdfRendererSpec.php
=> PIM-8427: Fix PDF export of product to expose all attributes
