CHANGELOG-2.0.md
features/attribute/browse/view.feature
src/Pim/Bundle/DataGridBundle/Resources/public/js/pageable-collection.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/controller/role.js

Remove filter state coming from url and repopulate it with the proper filter from the actual filters
The fix is not really a real fix but more a "rustine". The problem is that the filters coming from the locale storage are not override by the actual DOM filters. So the fix is to remove the filters coming from the locale storage after the first load. That way the state is well applied after a reload but you can filter after it. 
| Review and 2 …

PIM-6923: fix search filter on datagrid

---

CHANGELOG-2.0.md
src/Pim/Bundle/EnrichBundle/Resources/public/templates/form/tab/attributes/create-modal-content.html
src/Pim/Bundle/UIBundle/Resources/public/less/components/button/Button.less

This PR moves the images for the create attribute popin icons to CSS so that they can be overridden 

PIM-6878: Make attribute creation icons extensible 

---

CHANGELOG-2.0.md
src/Akeneo/Bundle/ElasticsearchBundle/Refresh.php
src/Akeneo/Bundle/ElasticsearchBundle/spec/RefreshSpec.php
src/Pim/Bundle/CatalogBundle/Command/IndexProductCommand.php
src/Pim/Bundle/CatalogBundle/Command/IndexProductModelCommand.php
src/Pim/Bundle/CatalogBundle/Elasticsearch/Indexer/ProductIndexer.php
src/Pim/Bundle/CatalogBundle/Elasticsearch/Indexer/ProductModelDescendantsIndexer.php
src/Pim/Bundle/CatalogBundle/Elasticsearch/Indexer/ProductModelIndexer.php
src/Pim/Bundle/CatalogBundle/spec/Command/IndexProductCommandSpec.php
src/Pim/Bundle/CatalogBundle/spec/Command/IndexProductModelCommandSpec.php
src/Pim/Bundle/CatalogBundle/spec/Elasticsearch/Indexer/ProductIndexerSpec.php
src/Pim/Bundle/CatalogBundle/spec/Elasticsearch/Indexer/ProductModelDescendantsIndexerSpec.php
src/Pim/Bundle/CatalogBundle/spec/Elasticsearch/Indexer/ProductModelIndexerSpec.php

Remove the waiting time between each batch of 100 items when indexing products and products model from the command lines.
The refresh strategy is now at disable, relying on the standard refreshing feature of Elasticsearch without waiting for it to take effect.
More details here:
https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-refresh.html
Reindexing icecat_demo_dev results:
- before: 28s
- after: 9s …

TIP-819 Remove wait refresh for indexing commands

---

CHANGELOG-2.0.md
features/user/edit_my_account.feature
src/Pim/Bundle/UserBundle/Form/Subscriber/UserPreferencesSubscriber.php

en_US was always the displayed UI locale on the user edit interfaces edition.
Now we correctly displayed the saved UI locale and if it's a user creation, we put the en_US as default locale.

PIM-6914: Fix Default UI locale shown for new user

---

STANDARD_FORMAT.md

Fix some errors in the standard documentation :
- Products don't have any parent neither family variant.
- Variant products don't have any family variant.
- Product models don't have any groups.

Fix product standard format documentation

---

CHANGELOG-1.7.md
src/Pim/Bundle/UIBundle/Resources/public/less/components/grid/GridContainer.less

PIM-6904: Horizontal scrollbar should be at the bottom of the screen instead to be at the end of the grid

---

CHANGELOG-2.0.md
src/Pim/Bundle/CatalogBundle/Command/IndexProductCommand.php
src/Pim/Bundle/CatalogBundle/Command/IndexProductModelCommand.php
src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/ProductModelRepository.php
src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/ProductRepository.php
src/Pim/Bundle/CatalogBundle/spec/Command/IndexProductCommandSpec.php
src/Pim/Bundle/CatalogBundle/spec/Command/IndexProductModelCommandSpec.php
src/Pim/Component/Catalog/Repository/ProductModelRepositoryInterface.php
src/Pim/Component/Catalog/Repository/ProductRepositoryInterface.php

The offset-limit method cannot handle consequent volume of data because it has an exponential response time. The search after method provides a linear response time.
See https://www.eversql.com/faster-pagination-in-mysql-why-order-by-with-limit-and-offset-is-slow/ for some detals.
| Review and 2 GTM                  | WIP

PIM-6948 Uses search after instead of offset limit

---

src/Pim/Bundle/ApiBundle/tests/integration/ApiTestCase.php

Fix the CI failing since 9 days.
A cache on ACL is responsible of this error. This cache is kept between the tests.
When you are loading different catalogs, it can fail, because the ACL are not the same for the users.
This cache stores user and associated role. So, it's a cache on data (probably a problem for horizontal scalability..). …

Delete cache on acl between integration tests of the API

---

CHANGELOG-2.0.md
src/Pim/Bundle/CatalogBundle/Command/IndexProductCommand.php
src/Pim/Bundle/CatalogBundle/Command/IndexProductModelCommand.php
src/Pim/Bundle/CatalogBundle/spec/Command/IndexProductCommandSpec.php
src/Pim/Bundle/CatalogBundle/spec/Command/IndexProductModelCommandSpec.php
src/Pim/Component/Catalog/Normalizer/Indexing/FamilyNormalizer.php

This is the last obvious batch of perf optimization for products indexing. The next step could be to totally short circuit Doctrine and object hydration by working with arrays, but that would only provides a performance increase about to 2x, maybe 3x top.
This is not bad, but that would the cost in maintainability would be quite high (no objects, very different way of manipulating data compared to the rest of the program, etc...).  …

TIP-824 Reduce indexing time by around 20%

---

CHANGELOG-1.7.md
features/product/associate_product.feature
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/associations.js

Fixes the association removal when going back to the pef

PIM-6960: fix association type deletion on pef

---

CHANGELOG-2.0.md

PIM-6922: Fix sort order on attribute groups
PIM-6880: Remove the old variation asset icon
added to 2.0.6
PIM-6922: Fix sort order on attribute groups
removed from 2.0.5

Update changelog 2.0.5 and 2.0.6

---

CHANGELOG-2.0.md
features/Context/FixturesContext.php
features/Context/Page/Base/Grid.php
features/datagrid/datagrid_views.feature
src/Pim/Bundle/EnrichBundle/EventListener/CloseSessionListener.php
src/Pim/Bundle/EnrichBundle/Resources/config/event_listeners.yml
src/Pim/Bundle/EnrichBundle/spec/EventListener/CloseSessionListenerSpec.php
src/Pim/Bundle/UserBundle/Context/UserContext.php
src/Pim/Bundle/UserBundle/spec/Context/UserContextSpec.php

To not delete!
ETA: end September
Done: Green CI :)
Solution validated by @BitOne and @jjanvier
This PR aims to resolve:
- Concurrent AJAX requests
Concurrent AJAX requests are not really executed in parallel, due to lock on sessions.
So, even if the requests are sent in parallel, they are really executed on the server one after the other.
Screenshot here: https://akeneo.atlassian.net/browse/PIM-4153?jql=text%20~%20%22non-blocking%22
- Long request should not freeze the PIM
If a pending request is taking too much time, it freezes the PIM: the PIM is totally unavailable for the user (even with a refresh).
Of course, a request taking too much time should not happen. But if it occurs, it should not freeze the PIM anyway. 
See this ticket …

IM-825: allow concurrent AJAX request by closing the session in a listener

---

CHANGELOG-2.0.md
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/product/edit.yml

This PR moves the 'Completeness' tab link in the product edit form under 'Attributes'

PIM-6838: Reorder completeness tab in PEF

---

CHANGELOG-2.0.md
src/Pim/Bundle/DataGridBundle/Datasource/ProductDatasource.php

When data have not yet been loaded on the cursor, a count() call executes the ES query and load the objects.
But the foreach calls rewind() on the same cursor, triggering another load of the exact same data, with the exact same query.
By putting the count() after the foreach() the data are loaded in the cursor, and the count() really counts loaded data and don't trigger any data loading.
| Review and 2 GTM                  | WIP
| Micro Demo to the …

PIM-6891 Count only when object have been loaded, not before

---

CHANGELOG-2.0.md
src/Pim/Bundle/EnrichBundle/Resources/config/requirejs.yml
src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/simple-view.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/menu/resizable.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/grid/category-switcher.js
src/Pim/Bundle/EnrichBundle/Resources/views/CategoryTree/form.html.twig
src/Pim/Bundle/EnrichBundle/Resources/views/CategoryTree/index.html.twig
src/Pim/Bundle/UIBundle/Resources/public/less/components/ColumnConfigurator.less
src/Pim/Bundle/UIBundle/Resources/public/less/lib/jquery-ui.less
src/Pim/Bundle/UIBundle/Resources/public/less/pages/Default.less

This PR updates the category panels so that they can be resized. The resized width is saved in localStorage and restored when the panel is loaded. 
The panels that were updated: 
Asset picker (in the EE PR https://github.com/akeneo/pim-enterprise-dev/pull/3276)
Product category filter
Categories index (and asset categories in EE)
Categories edit (and asset categories in EE) …

PIM-6967: Allow category panels to be resized

---

src/Pim/Bundle/EnrichBundle/Resources/public/js/common/property.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/fields/boolean.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/fields/field.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/fields/select.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/fields/values/boolean.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/fields/values/metric.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/fields/values/simple-select-async.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/fields/values/text.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/fields/values/values-behavior.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/product-model/form/add-child/fields-container.js
src/Pim/Bundle/EnrichBundle/Resources/public/templates/attribute/tab/properties/group.html
src/Pim/Bundle/EnrichBundle/Resources/public/templates/form/common/fields/boolean.html
src/Pim/Bundle/EnrichBundle/Resources/public/templates/form/common/fields/date.html
src/Pim/Bundle/EnrichBundle/Resources/public/templates/form/common/fields/field.html
src/Pim/Bundle/EnrichBundle/Resources/public/templates/form/common/fields/select.html
src/Pim/Bundle/EnrichBundle/Resources/public/templates/form/common/fields/simple-select-async.html
src/Pim/Bundle/EnrichBundle/Resources/public/templates/form/common/fields/text.html
src/Pim/Bundle/EnrichBundle/Resources/public/templates/form/common/fields/textarea.html

Until now when you used common fields it was possible to configure it like this :
```
my-code-field:
...
config:
fieldName: code
label: pim_enrich.form.someform.label.code
my-name-field:
...
config:
fieldName: name
label: pim_enrich.form.someform.label.name
```
The `fieldName` was used as a key to store the value in the root model.
The drawback was that all your values would be at the same level :
```
{
code: 'michel',
name: 'Michel',
...
}
```
This PR aims at adding some flexibility, for example you can now do :
```
my-code-field:
...
config:
fieldName: code
label: pim_enrich.form.someform.label.code
my-name-field:
...
config:
fieldName: values.name
label: pim_enrich.form.someform.label.name
```
then your root model will look like this …

Improve common fields to be able to use property paths as field names

---

CHANGELOG-2.0.md
src/Pim/Bundle/CatalogBundle/Elasticsearch/Indexer/ProductModelDescendantsIndexer.php
src/Pim/Bundle/CatalogBundle/spec/Elasticsearch/Indexer/ProductModelDescendantsIndexerSpec.php

Indexing product models from icecat_demo_dev catalog
- before: 90s 
- after: 4s

PIM-6997 Fixes slow product model indexing by passing proper refresh options

---

CHANGELOG-2.0.md
src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filters-manager.js
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/attribute/edit.yml
src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/simple-view.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/product-model/form/add-child.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/grid/category-switcher.js
src/Pim/Bundle/EnrichBundle/Resources/public/templates/product_model/add-child-form.html
src/Pim/Bundle/UIBundle/Resources/public/less/components/grid/FilterBox.less
src/Pim/Bundle/UIBundle/Resources/public/less/components/product-edit-form/AssetCollectionField.less
src/Pim/Bundle/UIBundle/Resources/public/less/pages/Default.less
src/Pim/Bundle/UIBundle/Resources/public/less/pages/FullPage.less

This PR updates the product grid to always keep the category panel open (even when the main column is collapsed). We also remove the outside click except for the filter button.
Before
After
This PR also includes PIM-6986 which is for switching the modal illustration for the add variant form based on the model type. 
| Tech Doc …

PIM-6992: Keep category panel open

---

CHANGELOG-1.7.md
src/Akeneo/Bundle/StorageUtilsBundle/Doctrine/Common/Detacher/ObjectDetacher.php
src/Akeneo/Bundle/StorageUtilsBundle/spec/Doctrine/Common/Detacher/ObjectDetacherSpec.php

We have a customer that imports 200K products with a CSV file in MongoDB. And the step "association import" leaks badly. The import crashes telling all memory has been consumed.
Imports have not changed that much since 1.6. So how is it possible we have a memory leak on the product import? We should have seen it before.
- It happens only with MongoDB
- When there is no associations, the association step is very fast. And even if it leaks, we usually don't have time to observe it.
- The leak increases slowly, which means, unless you don't import many many products (like 50K+), you won't pay attention to it.
The fix here bypasses a Doctrine bug about the detach. It removes unnecessary objects from the private variables of the unit of work. So such kind of dirty tricks? Because in a 1.7 …

[SLA] PIM-6995: sweets in the object detacher

---

CHANGELOG-2.0.md
src/Pim/Bundle/DataGridBundle/Normalizer/ProductModelNormalizer.php
src/Pim/Bundle/DataGridBundle/Normalizer/ProductNormalizer.php
src/Pim/Bundle/DataGridBundle/spec/Normalizer/ProductModelNormalizerSpec.php
src/Pim/Bundle/DataGridBundle/spec/Normalizer/ProductNormalizerSpec.php
src/Pim/Bundle/EnrichBundle/Normalizer/ProductModelNormalizer.php
src/Pim/Bundle/EnrichBundle/Normalizer/ProductNormalizer.php
src/Pim/Bundle/EnrichBundle/spec/Normalizer/ProductModelNormalizerSpec.php
src/Pim/Bundle/EnrichBundle/spec/Normalizer/ProductNormalizerSpec.php
src/Pim/Bundle/UserBundle/Context/UserContext.php
src/Pim/Bundle/UserBundle/spec/Context/UserContextSpec.php
src/Pim/Component/Catalog/Model/AbstractProduct.php
src/Pim/Component/Catalog/Model/ProductModel.php
src/Pim/Component/Catalog/spec/Model/ProductModelSpec.php
src/Pim/Component/Catalog/spec/Model/ProductSpec.php

Since 2.0 if a "scopable" attribute is setted as label in a family, the product label displayed is still the identifier.
The goal of this PR is to fix this bug to have the same behavior that in 1.7. In a future patch the behavior of a "scopable" "attribute as label" will be changed to be identical to the locales.
Technically, the product normalizer of the EnrichBundle gets the label for each locale, but the scope is not used. 
Before 2.0 the scope was used in the method `getValue` in`Pim/Component/Catalog/Model/AbstractProduct.php`, but it was rewritten and there's no longer a default value (the property `scope` of this class)
The scope must be passed to `getValue` from `getLabel`, and to it from the normalizer. We could used again the …

PIM-6959: scopable text attributes cannot be used as Label

---

src/Pim/Bundle/EnrichBundle/Resources/public/js/family-variant/form/attribute-set.js

If one of the attributes in one of the axes was not viewable by the user, the page was failing

PIM-6985: fix right error on family variant screen

---

tests/IntegrationTestsBundle/Loader/FixturesLoader.php
tests/catalog/technical/acl.sql

Endpoint to get a single category asset in EE.
As ACl is a nitghmare to test, (pure sql with hardcoded ID), I had to change the way to load ACL to not rely on hardcoded id anymore, but on ID generated by the database.
It was impossible to load it in EE without it.
I tried at first to abstract it properly without using pure SQL, but I can't understand at all how it works. …

Api 438: get a single category asset with the API

---

CHANGELOG-2.1.md
features/Context/Page/Base/Grid.php
features/Pim/Behat/Decorator/Grid/Filter/SearchDecorator.php
features/product/filtering/filter_products_per_label_or_identifier.feature
src/Pim/Bundle/CatalogBundle/Elasticsearch/Filter/Field/LabelOrIdentifierFilter.php
src/Pim/Bundle/CatalogBundle/Resources/config/query_builders.yml
src/Pim/Bundle/CatalogBundle/Resources/elasticsearch/index_configuration.yml
src/Pim/Bundle/CatalogBundle/spec/Elasticsearch/Filter/Field/LabelOrIdentifierFilterSpec.php
src/Pim/Bundle/CatalogBundle/tests/integration/PQB/AbstractProductQueryBuilderTestCase.php
src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/LabelOrIdentifierFilterIntegration.php
src/Pim/Bundle/DataGridBundle/Resources/config/requirejs.yml
src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filter/label_or_identifier-filter.js
src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filters-list.js
src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/product.yml
src/Pim/Bundle/EnrichBundle/Resources/public/templates/common/default-template.html
src/Pim/Bundle/FilterBundle/Filter/Product/LabelOrIdentifierFilter.php
src/Pim/Bundle/FilterBundle/Resources/config/filters.yml
src/Pim/Bundle/FilterBundle/spec/Filter/Product/LabelOrIdentifierFilterSpec.php
src/Pim/Bundle/UIBundle/Resources/public/less/components/TitleContainer.less
src/Pim/Component/Catalog/Normalizer/Indexing/Product/PropertiesNormalizer.php
src/Pim/Component/Catalog/Normalizer/Indexing/ProductAndProductModel/ProductModelPropertiesNormalizer.php
src/Pim/Component/Catalog/Normalizer/Indexing/ProductAndProductModel/ProductPropertiesNormalizer.php
src/Pim/Component/Catalog/Normalizer/Indexing/ProductModel/ProductModelPropertiesNormalizer.php
src/Pim/Component/Catalog/Normalizer/Standard/Product/PropertiesNormalizer.php
src/Pim/Component/Catalog/spec/Normalizer/Indexing/Product/PropertiesNormalizerSpec.php
src/Pim/Component/Catalog/spec/Normalizer/Indexing/ProductAndProductModel/ProductModelPropertiesNormalizerSpec.php
src/Pim/Component/Catalog/spec/Normalizer/Indexing/ProductAndProductModel/ProductPropertiesNormalizerSpec.php
src/Pim/Component/Catalog/spec/Normalizer/Indexing/ProductModel/ProductModelPropertiesNormalizerSpec.php
src/Pim/Component/Catalog/tests/integration/Normalizer/Indexing/ProductAndProductModelIndexingIntegration.php
src/Pim/Component/Catalog/tests/integration/Normalizer/Indexing/ProductIndexingIntegration.php

Add search on label and identifiers. We did some benchmark on my machine to test if this will work with big catalogs
Here are the result with 4.7 million products and 1000 calls:
```
Concurrency Level: 1
Time taken for tests: 36.238 seconds
Complete requests: 1000
Failed requests: 1
(Connect: 0, Receive: 0, Length: 1, Exceptions: 0)
Total transferred: 2893001 bytes
Total body sent: 1156000
HTML transferred: 2615001 bytes
Requests per second: 27.60 /sec (mean)
Time per request: 36.238 [ms] (mean)
Time per request: 36.238 [ms] (mean, across all concurrent requests)
Transfer rate: 77.96 [Kbytes/sec] received
31.15 kb/s sent
109.11 kb/s total
Connection Times (ms)
min mean[+/-sd] median max
Connect: 0 0 0.1 0 1
Processing: 18 36 14.4 35 380 …
```

PIM-6621: add search on label and identifier

---

CHANGELOG-1.7.md
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/product_edit.yml

When the ACL "Add attribute to a product" is unchecked you must not see the SELECT "Add an attribute" on the PEF

PIM-7017: Permission on "Add attribute to a product" is not properly applied

---

CHANGELOG-2.0.md
src/Pim/Bundle/CatalogBundle/Resources/config/event_subscribers.yml
src/Pim/Bundle/ConnectorBundle/Resources/config/writers.yml
src/Pim/Component/Connector/Writer/Database/ProductModelDescendantsWriter.php
src/Pim/Component/Connector/spec/Writer/Database/ProductModelDescendantsWriterSpec.php

Fix a memory leak in product model import
Remove duplicated event subscriber

PIM-7045: Inject doctrine clearer in ProductModelDescendantsWriter to avoid memory leak

---

CHANGELOG-2.0.md
src/Oro/Bundle/UserBundle/Form/Handler/AbstractUserHandler.php
src/Pim/Bundle/UserBundle/Resources/views/Reset/reset.html.twig

Fix reset, it was throwing an error 500 after validating form
Fix reset password style
Now looks like that

PIM-7035: Fix User Reset action

---

src/Pim/Bundle/ApiBundle/Resources/config/checkers.yml

Currently, it is not possible to filter products by `updated` or `created` property as described in the API docs.
This PR should fix this.

Query checker config fix

---

CHANGELOG-2.1.md
src/Pim/Bundle/ApiBundle/Controller/MediaFileController.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Attribute/ListAttributeIntegration.php

When getting a media file with the API, the storage is not checked. As a result, in EE, it is possible to get an asset reference or variation file. This should not happen.
This PR adds the verification of the storage used when retrieving the media, accepting only media coming from the catalog storage.
Test is added in EE.
`-`: Not …

API-443: Prevent getting asset via media file url

---

CHANGELOG-2.0.md
src/Pim/Bundle/CatalogBundle/Entity/AttributeOptionValue.php
src/Pim/Bundle/CatalogBundle/spec/Entity/AttributeOptionSpec.php

PIM-7011: XLS Options Import - Simple select attribute option cannot be updated for options with numeric codes

---

CHANGELOG-2.0.md
src/Pim/Component/Connector/ArrayConverter/FlatToStandard/FieldConverterInterface.php
src/Pim/Component/Connector/ArrayConverter/FlatToStandard/Product/FieldConverter.php
src/Pim/Component/Connector/ArrayConverter/FlatToStandard/ProductModel.php
src/Pim/Component/Connector/ArrayConverter/FlatToStandard/ProductModel/FieldConverter.php
src/Pim/Component/Connector/spec/ArrayConverter/FlatToStandard/ProductModel/FieldConverterSpec.php
src/Pim/Component/Connector/spec/ArrayConverter/FlatToStandard/ProductModelSpec.php
src/Pim/Component/Connector/spec/ArrayConverter/FlatToStandard/ProductSpec.php

The product model array convert only accept string for the following field `code`, `categories`, `parent` and `family_variant` but these fields should be scalars. For instance, if I want to create a product model with a integer as a code, it should be possible because the code validation rules is `\/^[^,;]+$/`. The regex used to validate the code of other entities is `/^[a-zA-Z0-9_]+$/` for you information. That means that you can create a family with a code 1234 for instance.
| Changelog …

PIM-7037: Product Model Import - Error the field "code" should contain a string

---

CHANGELOG-2.0.md
src/Pim/Bundle/DataGridBundle/Normalizer/ProductAssociationNormalizer.php
src/Pim/Bundle/DataGridBundle/spec/Normalizer/ProductAssociationNormalizerSpec.php

The normalizer called the method `Product::getLabel()` with a locale but without the channel. The identifier was returned all the time because we could not find the value without the channel.
| Micro Demo to the PO (Story only) | yes

PIM-7039: Association grid, scopable attributes used as labels do not appear

---

CHANGELOG-2.0.md
src/Pim/Bundle/EnrichBundle/Resources/public/js/family/form/variants/add-family-variant-fields-container.js

The serialized attribute labels look like 
```
[
'en_US': 'label',
'fr_FR': 'label'
]
```
but when there is no translation configured for an attribute, the normalizer return an empty array. So trying to get something that does not exist raise an error and break the select render.
| Javascript test                      | I did not find them, weird :trollface: 
| …

PIM-6980: Missing labels for attribute prevent you from creating a variant family

---

CHANGELOG-2.1.md
src/Pim/Bundle/DataGridBundle/Datasource/AssociatedProductDatasource.php
src/Pim/Bundle/DataGridBundle/Normalizer/ProductAssociationNormalizer.php
src/Pim/Bundle/DataGridBundle/Resources/config/normalizers.yml
src/Pim/Bundle/DataGridBundle/spec/Normalizer/ProductAssociationNormalizerSpec.php
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/associated-product-row.js

This PR fixes a bug where setting asset collection for "attribute used as image" on a family caused the wrong image data to be returned for a product in the association grid. Now the image normalizer is used to return the correct image filePath (before it was returning the original filename). 
| Tech Doc                          | …

PIM-7051: Fix image normalization for associated products

---

CHANGELOG-2.1.md
src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid-builder.js
src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid/grid.js
src/Pim/Bundle/DataGridBundle/Resources/translations/jsmessages.en.yml
src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/association_product.yml
src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/attributes.js
src/Pim/Bundle/EnrichBundle/Resources/public/templates/common/no-data.html
src/Pim/Bundle/UIBundle/Resources/public/less/components/grid/GridContainer.less

This PR updates the product associations grid to replace the empty message and illustrations with custom ones. Any other grid can be customised the same way by specifying the options in the datagrid yml: 
```diff
datagrid:
association-product-grid:
options:
+            emptyGridOptions:
+                hint: grid.empty_results.associated_product.hint
+                subHint: grid.empty_results.associated_product.subHint
+                imageClass: AknGridContainer-noDataImage--associations
``` …

PIM-7046: Add ability to customise empty grid message and pic

---

CHANGELOG-2.0.md
features/mass-action/mass_add_to_existing_product_model.feature
src/Pim/Component/Catalog/Validator/Constraints/NotEmptyVariantAxesValidator.php
src/Pim/Component/Catalog/spec/Validator/Constraints/NotEmptyVariantAxesValidatorSpec.php

I make a mistake on rebase - already 2 GTM on it : 
https://github.com/akeneo/pim-community-dev/pull/7307

PIM-7030: not allow null Metric data Attribute for NotEmptyVariantAxesValidator // BIS

---

src/Pim/Bundle/CatalogBundle/tests/integration/Doctrine/ORM/Repository/ProductMassActionRepositoryIntegration.php
src/Pim/Bundle/DataGridBundle/Extension/MassAction/Handler/DeleteProductsMassActionHandler.php

When removing a variant product (belonging to a product model) via a mass delete on Enterprise Edition, the product is removed from Elasticsearch, but not from MySQL.
This is caused by a wrong service declaration, only in EE, and only for variant products. This PR adds the same integration tests on the `ProductMassActionRepository` than the EE pull request to prevent any future regression. …

PIM-7059: Test product and variant product mass deletion

---

features/mass-action/mass_edit_products_and_product_models.feature
src/Pim/Bundle/EnrichBundle/Connector/Reader/MassEdit/FilteredProductAndProductModelReader.php
src/Pim/Bundle/EnrichBundle/spec/Connector/Reader/MassEdit/FilteredProductAndProductModelReaderSpec.php

Change the message by "This bulk action doesn't support Product models entities yet." instead of "Bulk actions do not support Product models entities yet."

PIM-7053: change message warning about not support Product models entities for bulk actions

---

src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Field/GridCompletenessFilterIntegration.php
src/Pim/Bundle/EnrichBundle/ProductQueryBuilder/ProductAndProductModelQueryBuilder.php
src/Pim/Bundle/EnrichBundle/Resources/config/query_builders.yml
src/Pim/Bundle/EnrichBundle/Resources/config/readers.yml
src/Pim/Bundle/EnrichBundle/spec/ProductQueryBuilder/ProductAndProductModelQueryBuilderSpec.php

What's done here:
- re organize the `query_builders.yml` file to understand what's used by the grid, what's used by the mass edit
- add specs and docs for the P&PMQB class
- remove a useless service

PIM-6357: clean P&PM query builder for mass edit

---

src/Pim/Bundle/EnrichBundle/Resources/public/js/family/form/attributes.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/family/form/family-variant.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/family/form/variants/add-family-variant-fields-container.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/family/form/variants/add-family-variant-form.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/family/form/variants/add-family-variant-header.js

Some weird JavaScript code style was spotted in the last merge of 2.0 into 2.1. The problems came from 2.0, not from the merge itself. This PR fixes it.

Fix some JS code style on family variant forms

---

CHANGELOG-2.0.md
src/Pim/Bundle/EnrichBundle/Resources/public/templates/form/tab/attributes/copy.html
src/Pim/Bundle/UIBundle/Resources/config/assets.yml
src/Pim/Bundle/UIBundle/Resources/public/less/components/product-edit-form/AttributeActions.less

In Version 2.0.7 the PEF, when clicking on the "Compare/Translate" option, the close button is missing and "locale" and "Channel" are misaligned.
This is a regression, it was fine in V2.0.6

PIM-7032: change css from AttributeActions to ActionButton

---

CHANGELOG-2.0.md
features/attribute-group/delete_attribute_group.feature
features/user/edit_user_group_and_role_assignations.feature
src/Pim/Bundle/EnrichBundle/Controller/Rest/AttributeGroupController.php

If you remove an attribute group, you cannot access the attributes belonging to this group anymore. 
They cannot be moved to another group.
Expected behaviour: 
- you cannot remove an attribute group if you have attributes in it
- you can never remove the OTHER attribute group
If you have attributes in your attribute group, the pim should display a message. 
In 1.6 we displayed: “Attribute group can’t be removed as it contains attributes” I suggest (a bit long): “Attribute group containing attributes cannot be removed. Please remove its attributes prior to delete it.”  …

Pim 7063: Add validation for AttributeGroup - cannot remove AttributeGroup containing attributes and cannot remove AttributGroup "other"

---

CHANGELOG-1.6.md
features/reference-data/product/sorting/sort_products_per_reference_data.feature
src/Pim/Bundle/ReferenceDataBundle/Doctrine/ORM/Sorter/ReferenceDataSorter.php

Let's say you have a simple-select reference data named `color`, and you create an attribute to use it, its code being `color` too, and make this attribute usable in grid filter.
You'll then be able to add a column for this attribute in the product grid and you'll see the values in the column.
But the moment you sort on this attribute, the values will disappear (and be back if you sort on an other attribute or reinitialize the grid). This bug is caused by a wrong datagrid query in the simple-select reference data sorter, fixed by this PR. The problem is present only in ORM.
| Review and 2 …

PIM-7041: Fix reference data sorter

---

CHANGELOG-2.0.md
features/product/sequential_edit/sequential_edit_product_and_product_model.feature
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/sequential-edit.js

Sequential edit doesn't work when selecting more than two product models.

PIM-7070: fix sequential edit for product models

---

CHANGELOG-2.0.md
src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Query/AttributeIsAFamilyVariantAxis.php
src/Pim/Bundle/CatalogBundle/Resources/config/queries.yml
src/Pim/Bundle/CatalogBundle/spec/Doctrine/ORM/Query/AttributeIsAFamilyVariantAxisSpec.php
src/Pim/Bundle/CatalogBundle/tests/integration/Attribute/Query/AttributeIsAFamilyVariantAxisIntegration.php
src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid/action/delete-action.js
src/Pim/Bundle/EnrichBundle/Controller/Rest/AttributeController.php
src/Pim/Bundle/EnrichBundle/Resources/config/controllers.yml
src/Pim/Bundle/EnrichBundle/Resources/translations/messages.en.yml

We cannot delete an attribute use as family variant axis (business rule). When the front send a request to remove an attribute, we check if the attribute belongs to a family variant before. 
| Added integration tests           | yes

PIM-6812: Change the message when delete an attribute as variant axis

---

CHANGELOG-2.0.md
src/Pim/Component/Catalog/Model/ValueCollection.php

It could be called "Improve indexation performance of ValueCollection when deleting values" but I prefer baiting title :trollface: 
Each time we delete a product value in the value collection, we iterate over all the values, just to refresh the attribute index.
So, the more we have values, slower it is to re-index the attributes.
In CE and EE, when loading the datagrid, 30% of the time is taken by the re-indexation of the values with product with more than 500 product values.
The fix is an easy workaround, that will work for a lot of things as it improves directly the model.
The datagrid is still too slow, but a little bit less.
| …

PIM-7079: improve datagrid loading by 30% with big products

---

CHANGELOG-2.0.md
src/Pim/Bundle/CatalogBundle/EventSubscriber/SaveFamilyVariantOnFamilyUpdateSubscriber.php
src/Pim/Bundle/CatalogBundle/Resources/config/event_subscribers.yml
src/Pim/Bundle/CatalogBundle/spec/EventSubscriber/SaveFamilyVariantOnFamilyUpdateSubscriberSpec.php

During a family import, family variants are loaded in the unit of work but they are not detached after the family saving. At the end of the job we send notification to user, notification are saved in database. So the `flush` method is called here that means that the previous loaded family variant are synchronize with the DB but cascade persist is not configured between Family and Family Variant.
We got this error:
```
A new entity was found through the relationship 'Pim\Component\Catalog\Model\FamilyVariant#family' that was not configured to cascade persist operations for entity: Accessories. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this association in the …
```

PIM-7048: Family imports return a cascade persist issue when families have variant family

---

CHANGELOG-2.0.md
features/Context/Page/Attribute/Creation.php
features/attribute/option/sort_attribute_options.feature
features/product/history/display_removed_value_history.feature
src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/AttributeOptionRepository.php
src/Pim/Bundle/CatalogBundle/Resources/config/doctrine/Attribute.orm.yml
src/Pim/Bundle/EnrichBundle/Doctrine/ORM/Repository/AttributeOptionSearchableRepository.php
src/Pim/Bundle/EnrichBundle/Normalizer/EntityWithFamilyVariantNormalizer.php
src/Pim/Bundle/EnrichBundle/Resources/public/js/pim-attributeoptionview.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/variant-navigation.js
src/Pim/Bundle/EnrichBundle/spec/Normalizer/EntityWithFamilyVariantNormalizerSpec.php
src/Pim/Bundle/VersioningBundle/Normalizer/Flat/ValueNormalizer.php

Sometimes where sort_order are the same (ex all with 1 at the initialization of the PIM), they are not displalyed on the same order in the different places of the PIM.
I added a new sort with code to ensure at each place of the PIM they are sorted by code if they have the same sort_order.

[PIM-7049] Fix random sort of attribute options

---

CHANGELOG-2.0.md
src/Akeneo/Bundle/StorageUtilsBundle/Doctrine/Common/Detacher/ObjectDetacher.php
src/Akeneo/Component/StorageUtils/Cache/CacheClearerInterface.php
src/Akeneo/Component/StorageUtils/Detacher/ObjectDetacherInterface.php
src/Pim/Bundle/ConnectorBundle/Resources/config/processors.yml
src/Pim/Component/Connector/Processor/Normalization/ProductProcessor.php

Doing a product export on our test environments raised a `Can not allocate memory` after 20-30 minutes of computing.
After running a PHP MemInfo, we saw that some `VariantProduct` entities were still loaded in memory, though Doctrine services.
The fix simply changes the `detach` method to a direct call to `clear()` of UnitOfWork.
The performances are better with the UoW clear:
- Before the fix: 1227 products / minute
- After the fix: 1842 products / minutes
| Tech Doc …

[PIM-7080] Fix memory leak on product export

---

CHANGELOG-2.0.md
src/Pim/Bundle/ApiBundle/Controller/ProductModelController.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/ProductModel/PartialUpdateProductModelIntegration.php
src/Pim/Bundle/ConnectorBundle/Resources/config/processors.yml
src/Pim/Component/Catalog/ProductModel/Filter/ProductModelAttributeFilter.php
src/Pim/Component/Catalog/Updater/ProductModelUpdater.php
src/Pim/Component/Catalog/spec/ProductModel/Filter/ProductModelAttributeFilterSpec.php
src/Pim/Component/Catalog/spec/Updater/ProductModelUpdaterSpec.php

Forbid the use of a non-existing attribute in product models creation and update,
Throw exception when trying to create or update a product model with a non-existing attribute,
it will throw an exception like that:
Property \"a_description\" does not exist. Check the expected format on the API documentation.
| Tech Doc …

API-544: Forbid the use of an non existing attribute in product models creation and update

---

CHANGELOG-2.1.md
features/Context/FeatureContext.php
features/Context/Page/Batch/Operation.php
features/localization/mass-action/edit_common_attributes.feature
src/Pim/Bundle/EnrichBundle/Normalizer/IncompleteValuesNormalizer.php
src/Pim/Bundle/EnrichBundle/Normalizer/ProductModelNormalizer.php
src/Pim/Bundle/EnrichBundle/Normalizer/ProductNormalizer.php
src/Pim/Bundle/EnrichBundle/Resources/config/normalizers.yml
src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/attributes.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/attributes/attribute-group-selector.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/attribute-filter-missing-required.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/attribute-filter.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/attributes/completeness.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/total-missing-required-attributes.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/provider/to-fill-field-provider.js
src/Pim/Bundle/EnrichBundle/spec/Normalizer/IncompleteValuesNormalizerSpec.php
src/Pim/Bundle/EnrichBundle/spec/Normalizer/ProductModelNormalizerSpec.php
src/Pim/Bundle/EnrichBundle/spec/Normalizer/ProductNormalizerSpec.php
src/Pim/Component/Catalog/EntityWithFamily/IncompleteValueCollection.php

We used to get missing required attributes with the completeness, then apply some permissions on frontend side, but now the backend sends only missing required attributes for the current user, taking in account its permissions.

PIM-7066: fix permissions problems on required missing attributes

---

features/export/product-export-builder/export_variant_products_by_specific_date.feature
features/export/variant_product/csv/export_variant_products.feature
features/export/variant_product/xlsx/export_variant_products.feature

I broke the (green :trollface: ) CI when I merged this PR: https://github.com/akeneo/pim-community-dev/pull/7411
When exporting variant products, missing values about the price were not exported.
Headers of the export were `code;price-EUR` instead of `code;price-EUR;price-USD`.
With PO, we decided to fix the scenarios, because displaying `price-USD`was the expected behavior.
So, why the refactoring we did with Anaël broke the scenarios?
- ProductModel PM1 : price[EUR, 10]
- VariantProduct VP1 : parent[PM1]
1. we add missing prices to the variant product VP1 https://github.com/akeneo/pim-community-dev/blob/2.0/src/Pim/Component/Catalog/ValuesFiller/AbstractEntityWithFamilyValuesFiller.php#L131 
2. to do that, it deletes the price product …

Pim 7079: fix behats about the refactoring of value collection

---

CHANGELOG-2.0.md
src/Pim/Bundle/VersioningBundle/Builder/VersionBuilder.php
src/Pim/Bundle/VersioningBundle/Normalizer/Flat/CollectionNormalizer.php
src/Pim/Bundle/VersioningBundle/spec/Builder/VersionBuilderSpec.php
src/Pim/Bundle/VersioningBundle/spec/Normalizer/Flat/CollectionNormalizerSpec.php

This aims to make the history useable when some attributes have a numeric code. Before, using array_merge, the code was normalized from '12345678' to '1' because array_merge reindexes the array.
Use array_replace instead fix this bug by reusing the key. Furthermore, array_replace conserve the ensemblist union from the right to the left. …

PIM-7065 Fix versioning when attribute code is numeric

---

CHANGELOG-2.0.md
src/Pim/Bundle/EnrichBundle/Normalizer/CompletenessCollectionNormalizer.php
src/Pim/Bundle/EnrichBundle/spec/Normalizer/CompletenessCollectionNormalizerSpec.php

During generation of data using data generator, we encountered a problem because it generates numeric channel code on the completeness normalizer. This PR aims to allow it.

PIM-7087: Fix completeness normalizer on numeric channel code

---

CHANGELOG-2.0.md
features/Context/WebUser.php
features/mass-action/mass_delete_products_and_product_models.feature
src/Pim/Bundle/DataGridBundle/Extension/MassAction/Handler/DeleteProductsMassActionHandler.php
src/Pim/Bundle/DataGridBundle/Resources/config/mass_actions.yml
src/Pim/Bundle/DataGridBundle/Resources/public/js/pageable-collection.js
src/Pim/Bundle/DataGridBundle/Resources/translations/messages.en.yml
src/Pim/Bundle/DataGridBundle/spec/Extension/MassAction/Handler/DeleteProductsMassActionHandlerSpec.php

In the product grid, delete action is not working as expected, when all product are selected : only the 25 products on the first page are deleted.
Don't allow to delete more than 1000 products.

PIM-6968 - fix mass delete product

---

CHANGELOG-2.0.md
src/Pim/Bundle/UIBundle/Resources/public/less/lib/select2.less

When your view/project's name is too short (like 'tot'), you can select it but it doesn't appear.
It's like nothing is selected.

PIM-6965: show short view names in the grid

---

src/Pim/Bundle/DataGridBundle/Resources/views/macros.html.twig
src/Pim/Bundle/EnrichBundle/Resources/config/requirejs.yml
src/Pim/Bundle/EnrichBundle/Resources/public/js/form/builder.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/menu/logo.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/page-title.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/grid/table.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/router.js

For the onboarder, we need to configure the dashboard and the logo routes.
Currently, the dashboard route is hardcoded in router.js. To fix that, we added the configuation `indexRoute` in the requirejs.yml. But it did not work, why ? Because the path `pimenrich/js/router` is duplicated in the config file with two different key (`pim/router` & `pim-router`), that's why we removed the key `pim-router` and replace it by `pim/router` in js files.
Thanks @phaseinducer for his help :)
| …

AOB-17: add configuration for routes

---

CHANGELOG-2.0.md
src/Pim/Bundle/UIBundle/Resources/public/lib/bootstrap/js/bootstrap.js

This PR fixes a bug in the display of dropdown lists. The logic to calculate whether to render a dropdown above/below was not right - it wasn't taking into account the max possible height of the list (with scrollbars).
Before
After …

PIM-6874: Fix select attribute groups from PEF when there are more than 25

---

CHANGELOG-2.0.md
src/Oro/Bundle/ConfigBundle/Config/ConfigManager.php

In System --> Configuration, when changing the "Enable loading messages" and saving and modifying the message and saving again, if we reload the page the enable loading message backs to "no"

PIM-7086: fix save configuration in OroBundle

---

CHANGELOG-2.0.md
src/Pim/Bundle/ApiBundle/Controller/ProductController.php
src/Pim/Bundle/ApiBundle/Resources/config/controllers.yml
src/Pim/Bundle/ApiBundle/tests/integration/Controller/ProductModel/CreateProductModelIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/ProductModel/PartialUpdateProductModelIntegration.php
src/Pim/Component/Api/Normalizer/Exception/ViolationNormalizer.php
src/Pim/Component/Api/spec/Normalizer/Exception/ViolationNormalizerSpec.php

The ProductModelController for the API didn't use the right validator, indeed it used the `@validator` service instead of the `@pim_catalog.validator.product_model'`.
Moreover the normalizer of this type of Exception (`ViolationNormalizer::class`) worked only for `ProductInterface::class`, I have switched it to `EntityWithValuesInterface::class`
Green CI, rebased it for the CHANGELOG afterward: https://ci.akeneo.com/blue/organizations/jenkins/akeneo%2Fpim-community-dev/detail/PR-7431/8/pipeline …

API-567: validation on product models

---

CHANGELOG-2.0.md
src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/product.yml
src/Pim/Bundle/UIBundle/Resources/public/js/pim-dialog.js

In the product grid, when selecting products for mass delete, "DELETE" translation is missing.

PIM-7085: mass delete translation missing

---

CHANGELOG-2.0.md
src/Pim/Bundle/UIBundle/Resources/public/less/lib/select2.less

When your view/project's name is too short (like 'tot'), you can select it but it doesn't appear.
It's like nothing is selected.

PIM-6965: Show short view|project name in the grid

---

CHANGELOG-1.7.md
features/family/remove_attribute_from_a_family.feature
features/family/set_the_attribute_used_as_label.feature
features/reference-data/product/sorting/sort_products_per_reference_data.feature
src/Pim/Bundle/EnrichBundle/Resources/public/js/family/form/attributes/attributes.js
src/Pim/Bundle/EnrichBundle/Resources/public/templates/family/tab/attributes/attributes.html
src/Pim/Bundle/UIBundle/Resources/public/less/components/grid/Grid.less

This PR fixes an issue in the family edit attributes screen where all panels were being reopened after any change was made (e.g add/remove attribute or group). Now the panel state is restored on re-render 

PIM-7064: [SLA] Keep family attribute panel state on edit

---

CHANGELOG-2.0.md
src/Pim/Bundle/CatalogBundle/EventSubscriber/LoadEntityWithValuesSubscriber.php
src/Pim/Bundle/CatalogBundle/Resources/config/event_subscribers.yml
src/Pim/Bundle/DataGridBundle/Datasource/ProductDatasource.php
src/Pim/Bundle/DataGridBundle/EventSubscriber/FilterEntityWithValuesSubscriber.php
src/Pim/Bundle/DataGridBundle/EventSubscriber/FilterEntityWithValuesSubscriberConfiguration.php
src/Pim/Bundle/DataGridBundle/PimDataGridBundle.php
src/Pim/Bundle/DataGridBundle/Resources/config/data_sources.yml
src/Pim/Bundle/DataGridBundle/Resources/config/subscribers.yml
src/Pim/Bundle/DataGridBundle/spec/Datasource/ProductDatasourceSpec.php
src/Pim/Bundle/DataGridBundle/spec/EventSubscriber/FilterEntityWithValuesSubscriberSpec.php

POC is validated.
For more information, see description here: https://github.com/akeneo/pim-community-dev/pull/7430
I did some benchmarks with products containing 3000 product values on EE, and it is ok (900 ms on my computer, on an not optimised config).
Note: it solves the problem to load the product data of the datagrid. 
Datagrid metadata are still pretty slow to load: the more you have "attribute useable as grid filter", the slower it is.
Green CI: https://ci.akeneo.com/blue/organizations/jenkins/akeneo%2Fpim-community-dev/detail/PR-7461/6/pipeline/
| Added …

PIM-7103: improve performance of the datagrid

---

CHANGELOG-1.6.md
features/datagrid/datagrid_views.feature
src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filter/select2-choice-filter.js
src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filter/select2-rest-choice-filter.js

This PR updates the simple select filters to restore the correct filter label on render when loading a saved view. Previously, the filter was still applied but was displaying the wrong value. 

PIM-7058: Restore select2 filter label on render

---

CHANGELOG-2.0.md
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/job_instance/xlsx_product_model_import_edit.yml
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/locale-switcher.js
src/Pim/Component/Catalog/Factory/ValueCollectionFactory.php
src/Pim/Component/Catalog/spec/Factory/ValueCollectionFactorySpec.php

Fix double user menu on product import
Fix access to product edit form when default locale is not viewable
Fix on attribute removal and re-creation with another type

PIM-7082: remove double user menu on product import edit form

---

src/Pim/Bundle/EnrichBundle/Event/CategoryEvents.php

Deprecated CategoryEvents, used to set default permissions on category creation by the UI

API-392: Deprecated CategoryEvents, should be remove in 2.2

---

CHANGELOG-2.0.md
src/Akeneo/Bundle/ElasticsearchBundle/Cursor/Cursor.php
src/Pim/Bundle/EnrichBundle/Doctrine/Counter/CategoryProductsCounter.php
src/Pim/Bundle/EnrichBundle/Resources/config/category_counters.yml
src/Pim/Bundle/EnrichBundle/spec/Doctrine/Counter/CategoryProductsCounterSpec.php
src/Pim/Bundle/EnrichBundle/tests/integration/Doctrine/Counter/CountProductsPerCategoriesIntegration.php

This PRs changes the way we count the number of products in category tree.
Now we use ES index to retrieve the number of product per category.
**This results in a small performance improvement**.
For **103k products**:
- Before (MySQL COUNT): `200~300ms`
- After (ES): `50~150ms`
_Tested on my machine (Intel Core i7, 8Gb RAM, SSD)_ …

PIM-6355: Fix count by categories in the grid to count products

---

CHANGELOG-2.0.md
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/PartialUpdateProductToVariantIntegration.php
src/Pim/Component/Catalog/EntityWithFamily/CreateVariantProduct.php
src/Pim/Component/Catalog/tests/integration/EntityWithFamily/CreateVariantProductFromProductIntegration.php

UoW::registerManaged seems to not like the fact the m2m associations are already hydrated.
This fix resolves the problem by not generating an extra set of `DELETE` queries on the related `groups` and `categories` m2m associations.

PIM-7102: do not hydrate product variant with m2m associations to avoid unit of work messing up

---

CHANGELOG-2.1.md
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/CreateProductIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/CreateVariantProductIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/PartialUpdateProductIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/PartialUpdateVariantProductIntegration.php

This PR updates and adds some tests about product association throught the API, for both creation and partial updates:
- associate  a non variant product  to a product model
- associate a variant product to a product model (this model being the variant product ancestor)
- test the response when associating to a product model that does not exists
Bad formating of the `associations.*.product_models` field is already unit tested. …

API-565 & API-445: Associated product and variant product to product model

---

src/Pim/Bundle/CatalogBundle/Resources/config/model/doctrine/ProductModel.orm.yml
src/Pim/Bundle/CatalogBundle/Resources/config/model/doctrine/VariantProduct.orm.yml

The Doctrine mapping of the `VariantProduct` and `ProductModel` entities is currently invalid.
This PR fixes the wrong `inversedBy` configuration. There is no need to run `doctrine:schema:update` for this, so no migration script needed.

Fix a bug in Doctrine mapping

---

CHANGELOG-2.0.md
src/Pim/Component/Catalog/Normalizer/Indexing/Product/PropertiesNormalizer.php
src/Pim/Component/Catalog/Normalizer/Indexing/ProductAndProductModel/ProductPropertiesNormalizer.php
src/Pim/Component/Catalog/Normalizer/Indexing/ProductModel/ProductModelPropertiesNormalizer.php
src/Pim/Component/Catalog/spec/Normalizer/Indexing/Product/PropertiesNormalizerSpec.php
src/Pim/Component/Catalog/spec/Normalizer/Indexing/ProductModel/ProductModelPropertiesNormalizerSpec.php
src/Pim/Component/Catalog/tests/integration/Normalizer/Indexing/ProductIndexingIntegration.php

When we delete a product model, its product variants are not un-indexed from the "product" index.
It's simply because the deletion query is based on "ancestors.ids" but we don't put the "ancestors.ids" in this index.

PIM-7105: Fix un-index variant product on deletion

---

CHANGELOG-2.0.md
src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/form/variant-navigation/product-item.html
src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/form/variant-navigation/product-model-item.html
src/Pim/Bundle/UIBundle/Resources/public/less/components/product-edit-form/VariantNavigation.less

This PR fixes a small display issue with variant axes completeness by adding text-overflow:ellipsis and the full title on hover. 
**Before**
**After**

PIM-7111: Fix display bug on variant axis completeness

---

CHANGELOG-2.0.md
src/Pim/Bundle/EnrichBundle/Resources/public/js/menu/item.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/menu/tab.js

This PR fixes a bug where clicking cancel on an 'unsaved changes' dialog when editing a form was useless and didn't stop the page from navigating away. 

PIM-6908: Fix cancel action on leaving page confirmation

---

CHANGELOG-2.0.md
features/Pim/Behat/Context/Domain/Enrich/CompletenessContext.php
features/product/completeness/display_completeness.feature
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/product-completeness.js
src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/form/product-completeness.html

Fix an issue with the completeness tab in the product edit form where the locale/scope information was outdated and not matching the completeness percentage badge. 

PIM-6913: Fix completeness wrong locale/scope

---

CHANGELOG-2.0.md
features/Context/catalog/catalog_modeling/jobs.yml
features/Pim/Behat/Context/JobContext.php
features/import/import_families.feature
src/Pim/Bundle/CatalogBundle/EventSubscriber/ComputeCompletenessOnFamilyUpdateSubscriber.php
src/Pim/Bundle/CatalogBundle/EventSubscriber/ComputeFamilyVariantStructureChangesSubscriber.php
src/Pim/Bundle/CatalogBundle/EventSubscriber/SaveFamilyVariantOnFamilyUpdateSubscriber.php
src/Pim/Bundle/CatalogBundle/Resources/config/event_subscribers.yml
src/Pim/Bundle/CatalogBundle/Resources/config/query_builders.yml
src/Pim/Bundle/CatalogBundle/spec/EventSubscriber/ComputeCompletenessOnFamilyUpdateSubscriberSpec.php
src/Pim/Bundle/CatalogBundle/spec/EventSubscriber/ComputeFamilyVariantStructureChangesSubscriberSpec.php
src/Pim/Bundle/CatalogBundle/spec/EventSubscriber/SaveFamilyVariantOnFamilyUpdateSubscriberSpec.php
src/Pim/Bundle/ConnectorBundle/Resources/config/jobs.yml
src/Pim/Bundle/ConnectorBundle/Resources/config/steps.yml
src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml
src/Pim/Component/Catalog/Job/ComputeFamilyVariantStructureChangesTasklet.php
src/Pim/Component/Catalog/spec/Job/ComputeFamilyVariantStructureChangesTaskletSpec.php
src/Pim/Component/Catalog/tests/integration/EntityWithFamilyVariant/ChangeVariantFamilyStructureIntegration.php
src/Pim/Component/Connector/Job/ComputeDataRelatedToFamilyVariantsTasklet.php
src/Pim/Component/Connector/spec/Job/ComputeDataRelatedToFamilyVariantsTaskletSpec.php
tests/IntegrationTestsBundle/Jobs/JobExecutionObserver.php
tests/IntegrationTestsBundle/Resources/config/services.yml

This PR is one of more to come regarding the improvements of the user experience/performance on the import jobs that triggers a "compute_product_models_descendants" job.
**What is 'compute_product_models_descendant' is supposed to do ?**
Well it's kind of greedy approach but, we mainly used this job when an information has changed in the "structure" domain. Like, let's say "an attribute as been removed from a family", or "an attribute has been moved up a level in the family variant". 
We use this job to iterate over all the descendants of a root product model, to reindex the right information in ES or to recompute the completeness of the products.
**Get it, what's the issue?**
The issue is that it's not clear when this job is run from a …

PIM-7057: Compute product models in dedicated step for family import

---

src/Pim/Component/Catalog/Validator/Constraints/ImmutableVariantAxesValuesValidator.php

When permissions are applied, if attributes in axes are not viewable in EE, `$newValue = $entity->getValue($code);` returns `null`. 
What's annoying me is that it's modification for the EE applied in CE. But I don't have any idea to do that in another way. …

API-574: fix validation of axes that are not viewable with EE permissions

---

src/Pim/Component/Connector/Reader/File/ArrayReader.php
src/Pim/Component/Connector/Reader/File/Csv/ProductAssociationReader.php
src/Pim/Component/Connector/Reader/File/Csv/ProductModelReader.php
src/Pim/Component/Connector/Reader/File/Csv/ProductReader.php
src/Pim/Component/Connector/Reader/File/Csv/Reader.php
src/Pim/Component/Connector/Reader/File/FileReaderInterface.php
src/Pim/Component/Connector/Reader/File/FlatFileIterator.php
src/Pim/Component/Connector/Reader/File/Xlsx/ProductAssociationReader.php
src/Pim/Component/Connector/Reader/File/Xlsx/ProductModelReader.php
src/Pim/Component/Connector/Reader/File/Xlsx/ProductReader.php
src/Pim/Component/Connector/Reader/File/Xlsx/Reader.php
src/Pim/Component/Connector/Reader/File/Yaml/Reader.php
src/Pim/Component/Connector/spec/Reader/File/ArrayReaderSpec.php
src/Pim/Component/Connector/spec/Reader/File/Csv/ProductAssociationReaderSpec.php
src/Pim/Component/Connector/spec/Reader/File/Csv/ProductModelReaderSpec.php
src/Pim/Component/Connector/spec/Reader/File/Xlsx/ProductAssociationReaderSpec.php
src/Pim/Component/Connector/spec/Reader/File/Xlsx/ProductModelReaderSpec.php

All our file readers share the same characteristics : they are item step elements, they receive a StepExecution, and they must be flushable.
We applied the [interface segregation principle](https://en.wikipedia.org/wiki/Interface_segregation_principle) here. I don't know if it's justified or not, but it's worth noting that all file readers always implement these 3 interfaces and never other ones than these 3. It probably means that the combination of the 3 behaviors should be explicit.
The problem is very visible when you try to add a dependency to a file reader or to decorate one : you never need something that can only flush or just be "step execution aware" (whatever that means). You mainly need to read something and it feels like …

AOB-10: Aggregate interfaces to allow dependencies to file readers

---

CHANGELOG-2.2.md
src/Pim/Bundle/CatalogBundle/Elasticsearch/AbstractCursor.php
src/Pim/Bundle/CatalogBundle/Elasticsearch/Cursor.php
src/Pim/Bundle/CatalogBundle/Elasticsearch/CursorFactory.php
src/Pim/Bundle/CatalogBundle/Elasticsearch/IdentifierResult.php
src/Pim/Bundle/CatalogBundle/Elasticsearch/IdentifierResults.php
src/Pim/Bundle/CatalogBundle/Elasticsearch/ProductAndProductModelQueryBuilderFactory.php
src/Pim/Bundle/CatalogBundle/Resources/config/query_builders.yml
src/Pim/Bundle/CatalogBundle/spec/Elasticsearch/CursorFactorySpec.php
src/Pim/Bundle/CatalogBundle/spec/Elasticsearch/CursorSpec.php
src/Pim/Bundle/CatalogBundle/spec/Elasticsearch/IdentifierResultSpec.php
src/Pim/Bundle/CatalogBundle/spec/Elasticsearch/IdentifierResultsSpec.php
src/Pim/Bundle/CatalogBundle/spec/Elasticsearch/ProductAndProductModelQueryBuilderFactorySpec.php
src/Pim/Bundle/DataGridBundle/Resources/config/mass_actions.yml
src/Pim/Bundle/EnrichBundle/Elasticsearch/FromSizeCursor.php
src/Pim/Bundle/EnrichBundle/Resources/config/queries.yml
src/Pim/Bundle/EnrichBundle/Resources/config/query_builders.yml
src/Pim/Bundle/EnrichBundle/Resources/config/readers.yml
src/Pim/Component/Catalog/Query/ProductAndProductModelQueryBuilder.php

This PR is the first step to allow the EE catalog rules to work with the product models.
For that, we need to use the "product and product model query builder", which was only used for the mass edit. So this query builder was placed in the PimEnrichBundle.
However, as we now need it for the rules, it is time to move it into the Catalog component.
`OK`: …

PIM-6367: Move into the Catalog component the "product and product model query builder"

---

CHANGELOG-2.2.md
composer.json

Following a discussion with @nicolas-grekas, it would be nice if Akeneo PIM users could easily thanks the OOS projects being part of Akeneo including himself by sending stars on github. 
Here it is
| Changelog updated                 | :white_check_mark: 

Add symfony/thanks Composer plugin

---

CHANGELOG-1.7.md
src/Pim/Component/Catalog/Updater/Adder/AssociationFieldAdder.php
src/Pim/Component/Catalog/Updater/Setter/AssociationFieldSetter.php
src/Pim/Component/Catalog/spec/Updater/Adder/AssociationFieldAdderSpec.php

Related to https://github.com/akeneo/pim-community-dev/pull/5373
The solution provided is to support the association type having a code which is a string representing an integer (ie, "666").
The standard format representation of the associations goes like:
```
{
"XSELL": {
"groups": ["group1", "group2"],
"products": ["AKN_TS1", "AKN_TSH2"]
},
"UPSELL": {
"groups": ["group3", "group4"],
"products": ["AKN_TS3", "AKN_TSH4"]
}
}
```
So in our usecase, when updating a product, the front sends to the back the following representation:
```
{
"666": {
"groups": ["group1", "group2"],
"products": ["AKN_TS1", "AKN_TSH2"]
},
}
```
When json_decoding it, the representation becomes in PHP:
```
[
666 => [
"groups": ["group1", "group2"],
"products": …
```

PIM-7130: Fix product update when association type code is an integer

---

CHANGELOG-2.1.md
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/GetProductIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/GetVariantProductIntegration.php

Add phpunit tests on getProduct / getVariantProduct with association on ProductModel

API-446: Add tests get Product / VariantProduct with association on ProductModel

---

src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/attributes.js

Prior to this fix, the label translated would use the uiLocale, now it
uses the catalogLocale.

PIM-7144: Fix translated label of attribute groups in the PEF

---

features/Context/FixturesContext.php

When creating products or product models for behat tests, only the corresponding Elasticsearch index was refreshed (product index, or product model index), when they should systematically all be refreshed (including the "product and product model" index).
This is needed for an EE pull request, but will be usefull for any behat tests involving products and product models. …

PIM-6367: Refresh all ES indexes in behat

---

.ci/Jenkinsfile

Using Google container builder instead of directly docker will get rid of inode leak via the docker overlay storage layer. This will allow the cloud team to notre recreate the cluster every two week and even reduce the size of the disks to reduce the cost.
A note on performance: builds will be longer by 3 minutes on average. We will work later on the performances but for now we have to work on stability and costs.

CLOUD-483: Use google container builder to build docker image

---

CHANGELOG-2.0.md
features/Context/FixturesContext.php
features/mass-action/mass_edit_many_products_at_once.feature
src/Pim/Bundle/EnrichBundle/Connector/Reader/MassEdit/FilteredProductAndProductModelReader.php
src/Pim/Bundle/EnrichBundle/spec/Connector/Reader/MassEdit/FilteredProductAndProductModelReaderSpec.php

When mass editing a number of product greater than the batch size an error was throw
`A new entity was found through the relationship 'Pim\Component\Catalog\Model\Completeness#locale' that was not configured to cascade persist operations for entity: en_US. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this association in the mapping for example @ManyToOne(..,cascade={"persist"}).`.
With @jjanvier we found that the bug was due to a problem of architecture in our Reader/Writer:
Info:
- The Cursor used in the Reader loads a page of 50 products during `->next()` if there is no more product left in its current page.
- When the batch size (100) is reached, the Writer clears all repositories and doctrine UOW just after …

PIM-7131: Fix mass add product values when number of products selected is greater than batch size

---

CHANGELOG-2.2.md
src/Pim/Bundle/CatalogBundle/Resources/config/builders.yml
src/Pim/Bundle/CatalogBundle/tests/integration/Completeness/AttributeType/BooleanAttributeTypeCompletenessIntegration.php
src/Pim/Component/Catalog/Builder/ProductBuilder.php
src/Pim/Component/Catalog/spec/Builder/ProductBuilderSpec.php

When a product is created, the product builder automatically set to `false` all boolean values, so we don't end up with a boolean value being null or non existant. According to comment in the code, it was primarily made to fix a bug on proposals.
But this create a wrong behavior on variant product. If you have a boolean attribute on its product model, then a variant product is created, the product builder will set a boolean value for this attribute to the variant product, when it should not.
In the worst case scenario, you can end up with a product model having the value to true, and the variant product to false...
The fix here consists in removing this dirty fix, as it is not needed anymore.
The UI works now fine with our new product single storage, and the proposals behave correctly: if …

PIM-6367: Do not add boolean values on product creation anymore

---

CHANGELOG-2.2.md
src/Akeneo/Bundle/BatchBundle/Job/DoctrineJobRepository.php
src/Akeneo/Component/Batch/Job/JobRepositoryInterface.php
src/Akeneo/Component/Batch/Step/ItemStep.php
src/Akeneo/Component/Batch/spec/Step/ItemStepSpec.php

**Problem**
In 1.5.23 @damien-carcel wrote a fix for a memory leak (https://github.com/akeneo/pim-community-dev/pull/6300). The solution was to persist step warnings direcly using the DBAL, and for that he created a dedicated method `insertWarning` in the `DoctrineJobRepository`. But since it was a patch he didn't want to do a BC break, so the method was used by the `ItemStep` without being part of the contract.
**Solution**
As stated in the original PR, the new method should be part of an interface. I added this method in the `JobRepositoryInterface` even if it can feel weird because doing it in a separated interface would imply adding a new dependency to `ItemStep` and rewriting all the step definitions (plus it would be a lot of work …

PIM-6129 cleaning : Expose the warnings persistance method through an interface to be able to depend on it properly

---

features/Context/Page/Base/ProductEditForm.php
features/Context/Page/Product/Edit.php

Field icons could currently be only tested on products. This PR allows that both (variant) products and product models can, only by moving a method from a class to the one it inherits from.

PIM-7166: Get field icons on both products and product models

---

app/config/config_dev.yml

I guess I found a bug affecting all 2.X versions.
I found the bug while testing some import/export customization where I was using the dev front controller app_dev.php and see who all Ajax request were performed to the prod front controller app.php. In fact all or at least all routes genereated in JS by the FOSJsRoutingBundle are wrong when using the environment.
After debugging I found that the base_url under web/js/routes.js is empty what is ok if you're using prod but it should be app_dev.php when using dev.
This PR fix the problem.

Fix #7614 wrong base_url for js routes when using dev environment

---

CHANGELOG-2.1.md
features/job-tracker/filter_job_executions.feature
src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/job_tracker.yml

amazing SLA, the filter of the status of the datagrid was not correctly configured.

[SLA] PIM-7168: fix "status" filter on job tracker datagrid

---

CHANGELOG-2.2.md
src/Pim/Component/Catalog/Model/FamilyVariant.php
src/Pim/Component/Catalog/Model/FamilyVariantInterface.php
src/Pim/Component/Catalog/spec/Model/FamilyVariantSpec.php

Add a new method in the family variant to know to which variant level an attribute belongs too (if it belongs to the family of the family variant at all).

PIM-7165: Add "FamilyVariantInterface::getLevelForAttributeCode"

---

.ci/Jenkinsfile
CHANGELOG-1.6.md
src/Pim/Bundle/DataGridBundle/Adapter/OroToPimGridFilterAdapter.php
src/Pim/Bundle/DataGridBundle/Extension/MassAction/Actions/Export/ExportMassAction.php
src/Pim/Bundle/DataGridBundle/Extension/MassAction/Actions/SequentialEdit/SequentialEditAction.php
src/Pim/Bundle/DataGridBundle/Extension/MassAction/MassActionDispatcher.php
src/Pim/Bundle/DataGridBundle/Resources/config/mass_actions.yml
src/Pim/Bundle/DataGridBundle/Resources/config/requirejs.yml
src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid/action/abstract-action.js
src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid/action/mass-action.js
src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid/action/sequential_edit-action.js
src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid/widget/export-widget.js
src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid/widget/sequential_edit-action.js
src/Pim/Bundle/DataGridBundle/spec/Extension/MassAction/Actions/Export/ExportMassActionSpec.php
src/Pim/Bundle/DataGridBundle/spec/Extension/MassAction/MassActionDispatcherSpec.php
src/Pim/Bundle/EnrichBundle/Controller/MassEdit/AbstractMassEditController.php
src/Pim/Bundle/EnrichBundle/Controller/SequentialEditController.php
src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/product.yml
src/Pim/Bundle/EnrichBundle/Resources/config/routing/sequential_edit.yml
src/Pim/Bundle/EnrichBundle/Resources/views/MassEditAction/configure.html.twig

When doing a mass-edit in 1.6 and 1.7 (mass-edit has been reworked in
2.0 <3 @juliensnz), the ids of the products selected in the
datagrid would be passed on all the mass-edit steps through the
URL parameter "values".
When submitting the form to create the mass-edit operation, the form
would be submitted via a POST http verb, but the selected Ids would still be
passed on to the controller using the URI parameter.
This submit action would sometimes not execute because the URL would be
too long.
**Mass Actions**: (like edit_common_attributes)
Passing the selected Ids from the datagrid to the mass-edit
(without using a url query parameter)
First thing, we need to get rid of the mecanism that passes on the
selected ids to the mass-edit …

PIM-7132: Fix "url too long" when doing a mass edit (once and for all)

---

src/Pim/Component/Catalog/Model/FamilyVariantInterface.php

I forgot a `@throws` in a previous PR, and only saw it during a new EE pull request...

PIM-7186: Add missing phpdoc

---

.ci/Jenkinsfile

Add a notification in Slack when a build is finished. 
It's red when it's failing, green when it's ok. There are maybe some edge cases not spotted, so please check your build on the UI for now.
Unfortunately, it's not possible to have the git branch name easily, so it will be the PR name in the notification.
Branch name would imply to do a `curl` to the github API to guess the branch from the PR number. A little bit too much for a notification...
Another thing: the generated link is for the old Jenkins, not blue Ocean. Not very important for now.
As the slack user is different from the github user (and no way to do the mapping easily), you have to fill an text input when configuring the build:
It's possible to notify several users, …

Add slack notification when Ci build is finished

---

CHANGELOG-1.6.md
features/mass-action/quick_export_with_media.feature
src/Pim/Bundle/EnrichBundle/Connector/Processor/QuickExport/ProductProcessor.php

When a products grid context quick export is performed, the products media files are generated even if no attribute of type media are selected in the grid context.
To fix this bug without doing BC breaks, I added a filter on the product values that are used to fetch the media, to keep only those that are selected from the context.
I didn't add specs because there isn't any for this class, and it no longer exists in 2.0
I did another PR to fix this bug for version 2.0 and beyond.
CI green except failing tests due to CI instability (issue raised). Tests are ok in local: merge.
| Added Specs …

PIM-7170 Fix media files unnecessarily generated during quick export

---

bin/docker/pim-front.sh
bin/docker/pim-initialize.sh
docker-compose.yml.dist

This PR adds small improvements to the Docker Compose file and helper scripts:
- use `rm` command to delete cache, but only in containers (so it prevent deleting anything on the user machine outside of the PIM project)
- fix some minor default in YAML syntax
- remove `PHP_XDEBUG_REMOTE_HOST` as it is not needed most of the time (and is documented anyway)
- put more folder/files in read-only
- change the mapping of the port to avoid using already used ports on the host machine
| Changelog updated                 | -- …

Small Docker Compose enhancements

---

CHANGELOG-1.6.md
src/Pim/Bundle/CatalogBundle/Command/CleanMongoDBCommand.php

An issue has been raised whenever a user would use the CleanMongoDBCommand
with products having reference data.
This command is used to clean the mongoDB when some data (families /
attributes) are not in sync with the Mysql DB (ie, entities have been
deleted from mysql but not in mongodb).
**Problem:**
The command would remove the values of reference data attributes even
when the selected attribute option still existed in mysql.
**Solution:**
This error was due to wrong check in the command. This patch fixes it.
| Added …

PIM-7182: Fix CleanMongoDB command

---

app/config/config_dev.yml

It brokes behat environment. Don't know why but it does.
Reverts akeneo/pim-community-dev#7615

Revert "Fix #7614 wrong base_url for js routes when using dev environment"

---

features/Pim/Behat/Context/HookContext.php
src/Pim/Bundle/ApiBundle/tests/integration/ApiTestCase.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/SuccessLargeAndOrderedListProductIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/ProductModel/LargeAndOrderedListProductModelIntegration.php
src/Pim/Bundle/InstallerBundle/Command/DatabaseCommand.php
tests/IntegrationTestsBundle/Loader/FixturesLoader.php

Reset Es indexes between tests (behat, integration), the main goal is to not worry about potential new indexes added in the future 

reset-es-index: Reset Es indexes between tests (behat, integration)

---

CHANGELOG-1.6.md
src/Pim/Component/Connector/Processor/Normalization/ProductProcessor.php
src/Pim/Component/Connector/spec/Processor/Normalization/ProductProcessorSpec.php

A client has about 150 000 variant groups and when running a product export, we can see a memory leak. The export is running slower and slower.
Benoit investigated the issue and the 1st analysis shows a memory leak on the "ProductTemplate", which is part from Variant Groups.
The fix is to detach groups at the end of `Normalization\ProductProcessor::process`, before detaching the products.
| …

PIM-7169: Fix a memory leak on product export

---

CHANGELOG-1.6.md
src/Pim/Bundle/EnrichBundle/Controller/Rest/FamilyController.php

When you select more than 20 families to export in the Family Field, only 20 are displayed whereas they are all well exported.
Expected behaviour: all selected families should be displayed in the family field.

PIM-7151: Remove family limit used on export profile

---

.ci/Jenkinsfile

The CI uses an extension provided by luigio/fastest to show all the
scenarios of the project.
This extension uses a formatter to show the message which is configured
in the '.ci/behat.community.yml' file with an output_path.
When a path that does not exist is set to this output_path, the
extension cannot create the file to output in resulting in this error.
Fix:
Make sure the path exists prior to list scenarios. …

Fix ci: regarding the warning: "touch()"

---

.ci/Jenkinsfile

Today, we can't launch a full CE/EE build when my CE branch is based on E.E
The CI will take EE master as default, which is not what we want.

Make 2.2 the default EE branch on the CI

---

CHANGELOG-2.2.md
features/family/delete_family_variant.feature
src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Query/CountEntityWithFamilyVariant.php
src/Pim/Bundle/CatalogBundle/Resources/config/queries.yml
src/Pim/Bundle/CatalogBundle/Resources/config/removers.yml
src/Pim/Bundle/CatalogBundle/tests/integration/Doctrine/Query/CountEntityWithFamilyVariantIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/Family/RemoveFamilyVariantIntegration.php
src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid/action/abstract-action.js
src/Pim/Bundle/EnrichBundle/Controller/Rest/FamilyVariantController.php
src/Pim/Bundle/EnrichBundle/Resources/config/acl.yml
src/Pim/Bundle/EnrichBundle/Resources/config/controllers.yml
src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/family_variant.yml
src/Pim/Bundle/EnrichBundle/Resources/config/requirejs.yml
src/Pim/Bundle/EnrichBundle/Resources/config/routing/family_variant.yml
src/Pim/Bundle/EnrichBundle/Resources/public/js/family-variant/form/delete.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/remover/family-variant.js
src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml
src/Pim/Bundle/EnrichBundle/Resources/translations/messages.en.yml
src/Pim/Component/Catalog/ProductAndProductModel/Query/CountEntityWithFamilyVariantInterface.php
src/Pim/Component/Catalog/Updater/Remover/FamilyVariantRemover.php
src/Pim/Component/Catalog/spec/Updater/Remover/FamilyVariantRemoverSpec.php

**Reviewable by commit**
Be able to remove the a family variant if, and only if, there is no product models / variant products belonging to it.
| Added legacy Behats               | Ok

PIM-6329: Remove family variant

---

.ci/behat.enterprise.yml

This PR fixes an error on the tag list in the `behat.yml` used by the CI on EE builds (launched from a CE PR). The `@ce` tag was not take into accont, running CE behats that should not have been, ending on red builds.

Fix tag filtered on EE builds

---

.ci/behat.enterprise.yml
CHANGELOG-1.7.md
src/Pim/Bundle/ConnectorBundle/DependencyInjection/PimConnectorExtension.php
src/Pim/Bundle/ConnectorBundle/Doctrine/Common/Detacher/StoredProductDetacher.php
src/Pim/Bundle/ConnectorBundle/Doctrine/Common/Detacher/StoredProductDetacherInterface.php
src/Pim/Bundle/ConnectorBundle/Resources/config/detachers.yml
src/Pim/Bundle/ConnectorBundle/Resources/config/processors.yml
src/Pim/Bundle/ConnectorBundle/Resources/config/writers.yml
src/Pim/Bundle/ConnectorBundle/spec/Doctrine/Common/Detacher/StoredProductDetacherSpec.php
src/Pim/Component/Connector/Processor/Normalization/ProductProcessor.php
src/Pim/Component/Connector/Writer/File/AbstractItemMediaWriter.php
src/Pim/Component/Connector/spec/Processor/Normalization/ProductProcessorSpec.php
src/Pim/Component/Connector/spec/Writer/File/Csv/ProductWriterSpec.php
src/Pim/Component/Connector/spec/Writer/File/Xlsx/ProductWriterSpec.php

There is currently a memory leak on product export, caused by associated products not being detached.
The idea to fix this is to get the associations of an exported product, detach all the products they contain, then finally detach the exported product.
However, there is a problem here: some of the detached associated products could be in the batch too, needing to be exported later. In this case, we would need not to detach them as associated products, but wait they are normalized and passed to the writer, except we cannot predict if an associated product will be in the batch or not.
The solution proposed here is to stop detaching the exported products one by one in the processor, as they are currently, and to store them in a new detacher dedicated to product export. Then the detach …

PIM-7164: Detach associated products during export

---

CHANGELOG-1.7.md
src/Oro/Bundle/UserBundle/Controller/ResetController.php
src/Oro/Bundle/UserBundle/Resources/config/navigation.yml
src/Oro/Bundle/UserBundle/Resources/config/oro/routing.yml
src/Pim/Bundle/UserBundle/Resources/translations/messages.en.yml
src/Pim/Bundle/UserBundle/Resources/views/Reset/request.html.twig
src/Pim/Bundle/UserBundle/Resources/views/Reset/sendEmail.html.twig

**Context:**
When a user asks for a new password the pim will show a message to the user indicating the email address the email has been set or tell the user if the username/email is invalid.
**Problem:**
This is a security issue as an attacker can then guess if a username/elam exists or not.
**Solution:**
Print out a standard message, in all cases, saying that an email has been set to the user.
| Review and 2 …

IM-824: Fix security issue when requesting password

---

bin/docker/pim-front.sh
bin/docker/pim-initialize.sh

This PR fixes an error made in the last 1.7 →2.0 merge. The docker-compose scripts were not updated correctly according to the last changes in 1.7.

Fix docker-compose scripts

---

CHANGELOG-2.0.md
src/Pim/Bundle/ConnectorBundle/Resources/config/processors.yml

**Before**:
180 000 query when doing a `pim:install`, more than 80000 requests to get the attributes.
2 minutes to install the catalog (!).
**After**:
80 000 query when doing a `pim:install`.
1m15 to install the catalog.
Free optimisation (37.5%). That's why I think it worths to do it in 2.0 (LTS).
Green CI except unstable test on ACL: https://ci.akeneo.com/blue/organizations/jenkins/akeneo%2Fpim-community-dev/detail/PR-7730/1/tests
| …

Fix product import performance by using cached repository

---

.ci/Jenkinsfile

When launching a CI, first step performed by Jenkins is to build the PIM. In CE 1.7, the build matrix can provide 4 builds: CE ORM, CE ODM, EE ORM and EE ODM.
Currently, the CE ORM build is always performed, which is a waste of time and CI resources. It is really needed only for: unit tests, integration tests and behat CE ORM. They are indeed ran very often, but not always: we sometime run the CI several times, only wanting ODM behats, in which cases CE ORM is useless.
This PR propose a fix so Jenkins build only what is really needed in the matrix.
| …

Build only what is really needed on the CI

---

CHANGELOG-1.7.md
src/Pim/Bundle/VersioningBundle/Doctrine/MongoDBODM/VersionRepository.php
src/Pim/Bundle/VersioningBundle/Purger/VersionPurger.php

We currently have a memory leak on the version purger in MongoDB. This is probably caused by the same bug in the Doctrine ODM detach method that was already affecting the product, that was fixed in the PR [PIM-6995](https://github.com/akeneo/pim-community-dev/pull/7136).
The same fix was tried on versions [in this PR](https://github.com/akeneo/pim-community-dev/pull/7545), but saddly did not worked: the memory didn't increased, but the versions were no longer removed...
This new PR seems to fix the issue for good: the memory is stable around 110 MiB (tested with the data of the client that raised the bug), and versions are indeed deleted. …

PIM-7134: Clear repository during version purge

---

.ci/behat.community.yml
.ci/behat.enterprise.yml
behat.yml.dist
features/Context/FeatureContext.php
features/Pim/Behat/Context/ImportFileContext.php
features/Pim/Behat/Context/JobContext.php
features/import/import_currencies.feature
features/import/product/import_products.feature

All our import and export Behat currently uses the UI to work.
We log in, configure our job, go to the job page, and click on the "Launch" button of the UI.
This is very time consuming because we boot a browser and Selenium.
This is also useless, as jobs can be launched and tested directly via a CLI.
So, that's the idea of this PR. To test imports/exports via the CLI instead of the UI.
This is not perfect. The ideal would to turn most of those system tests into real acceptance tests. But it's more work. 
**With that simple way of doing, each refactored Behat is twice faster.**
This PR works as is and can be considered as an example to rewrite all other import and export tests.
- we created a new job context, to not pollute the original one. The new one is dedicated to a job you've …

PoC: Remove UI from import tests

---

CHANGELOG-2.0.md
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/job_instance/xlsx_product_model_import_edit.yml

In the XLSX import profile for product models, the decimal separator field was missing and the date format fields was misconfigured to be readonly, this PR fixes these issues.
Before
After
`-`: …

PIM-7217: [SLA]  Fix missing and disabled fields in product model import

---

src/Pim/Bundle/EnrichBundle/Controller/AttributeOptionController.php

Use the exception code as HTTP status is wrong since
will produce invalid HTTP responses e.g. a response where
the HTTP status is 0.
The HTTP status should be one of the defined in the following
class Symfony\Component\HttpFoundation\Response as constants.

Fix #7760 wrong HTTP status on response

---

src/Pim/Bundle/UIBundle/Resources/public/less/components/product-edit-form/FieldContainer.less

Changes on Less rules, to display properly the Warning Icon after a field is required.

Fix #7752 wrong position of warning icon

---

CHANGELOG-2.0.md
src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filter/select2-rest-choice-filter.js

On the select2-rest-filter we had an extra call made to retrieve all the options while we already made the call to retrieve only the category selected. So this extra call was unnecessary and it added slowness. For instance, when the client have lot of families and the family filter is used we could see slowness on the product grid loading. …

PIM-7167 Slowness when going back to the Product grid when a family is used in the filter

---

tests/Integration/IntegrationTestsBundle/Fixture/EntityWithValue/Builder/ProductModel.php
tests/Integration/IntegrationTestsBundle/Resources/config/services.yml

This fixes a mistake introduced in https://github.com/akeneo/pim-community-dev/pull/7677.
Since builders are stateful and are declared as services, the instances are shared by default. This can lead to weird behaviors like values being shared between two calls.
A "better" solution would be to not declare them as services, but dependencies injection would be another problem at this point.
Relying on the DI is a not perfect but acceptable answer right now.

Fixtures builder instances should not be shared

---

CHANGELOG-1.7.md
src/Pim/Component/Connector/ArrayConverter/StandardToFlat/Channel.php
src/Pim/Component/Connector/spec/ArrayConverter/StandardToFlat/ChannelSpec.php

The Channel Export was wrong regarding conversion_units, it converted like that
| conversion_units |
| KILOGRAM, DECIMETER |
instead of:
| conversion_units |
| weight:KILOGRAM, size:DECIMETER |
`OK`: Done / …

PIM-7069: Fix Channel Export conversion units

---

CHANGELOG-2.0.md
features/Context/FixturesContext.php
features/family/multiple_page_selection.feature
features/product/multiple_page_selection.feature
src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid/header-cell/select-all-header-cell.js
src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid/row.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/grid/mass-actions.js

In the family and product data grids, when you select items on a page, then change page, the mass action panel disappear, and the selection seems to be lost (see animation just above).
In fact, it is not, the datagrid information is still here: you can see it if you come back on the first page and place the cursor above the row you selected, you'll see it is still selected. Only the display of the mass actions is messed up (as you can see above, again).
This PR contains in fact 3 fixes:
- the `count` of the `mass-action` module is not reset anymore when the user change page on the grid,
- in `select-all-header-cell` module, correct class is added on already selected items, so they stay selected when changing page and getting back,
- when selecting "all visibles", only not already selected …

PIM-7214: Select products and families on multiple grid pages

---

CHANGELOG-2.0.md
src/Pim/Bundle/UIBundle/Resources/public/less/components/grid/Grid.less

The sorting arrows are wrongly displayed in the wrong way, in all grids.
An upward arrow should indicates ascending order and a downward arrow descending order. 

PIM-7215: Fix wrong direction of sorting arrow in the grids

---

src/Pim/Bundle/EnrichBundle/Connector/Reader/MassEdit/ProductAndProductModelReader.php

The `ProductAndProductModelReader` is not correctly initialized each time it is used, the `firstRead` property being set to `true` only when the service is instantiated.
This leads to a wrong behavior if the reader is used twice in two steps of the same job (it is the case for mass edits with rule execution in EE): the first entity of the cursor is just skipped.
| Tech Doc …

PIM-7187: Fix product and product model reader

---

CHANGELOG-2.0.md
src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid/action/delete-action.js
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/attribute/edit.yml

When deleting an attribute linked to a published product, an exception is thrown here: https://github.com/akeneo/pim-enterprise-dev/blob/2.0/src/PimEnterprise/Bundle/WorkflowBundle/EventSubscriber/PublishedProduct/CheckPublishedProductOnRemovalSubscriber.php#L105
And not catched here: https://github.com/akeneo/pim-community-dev/blob/2.0/src/Pim/Bundle/EnrichBundle/Controller/Rest/AttributeController.php#L342
Thus, the error is thrown by the server and it is not a JSON one, the javascript has to be aware of that.
See tests in this PR: https://github.com/akeneo/pim-enterprise-dev/pull/3703 
| Added Specs …

PIM-7152: Fix errors due to deletion of attributes

---

CHANGELOG-2.0.md
src/Akeneo/Bundle/ClassificationBundle/Doctrine/ORM/Repository/CategoryRepository.php
src/Akeneo/Component/Classification/Repository/CategoryRepositoryInterface.php
src/Pim/Bundle/CatalogBundle/Elasticsearch/Filter/Field/CategoryFilter.php
src/Pim/Bundle/CatalogBundle/spec/Elasticsearch/Filter/Field/CategoryFilterSpec.php

This PR removes the check on categories code before querying them onto ES (which is basically a where clause so not very useful). 
If we query with non existing codes, ES will return nothing.
Here are the blackfire graphs which help us: https://blackfire.io/profiles/2d08bfe2-f93a-48e1-b6ad-7c50ad026069/graph 
https://blackfire.io/profiles/c6fa2c28-6ca0-4b13-a335-88c2ea47180c/graph  …

PIM-7255: Reduce slowness on product grid

---

CHANGELOG-2.0.md
src/Pim/Bundle/ConnectorBundle/tests/integration/Export/Writer/YamlWriterIntegration.php
src/Pim/Component/Connector/Writer/File/Yaml/Writer.php

There were two problems:
- First one: 
The file was never deleted as it was in FILE_APPEND mode, now the Writer is stateful (shame on me) because in case of a batch we need, first to overwrite the file and then append in it.
- Second one:
During a batch, the header was written each time, but we had this kind of file:
```YAML
rules:
rule_1: coucou
rule_100: plop
rules:
rule_101: ahahah
```
So when we imported the file only a part of this one was imported, here is where the ugly stuff comes.
The Yaml is a structured format so we do have to respect it, in order to avoid to repeat the header we had 3 solutions:
- First one: Write only one time the file when all item would have been processed
- Pro: The file is written one time only and it …

PIM-7129: Fix the yaml writer

---

CHANGELOG-2.2.md
features/Context/FixturesContext.php
features/Context/catalog/default/users.csv
features/product/date.feature
features/product/filtering/filter_products_per_date_fields_with_user_timezone.feature
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/SuccessListVariantProductDeltaIntegration.php
src/Pim/Bundle/CatalogBundle/Elasticsearch/Filter/Field/DateTimeFilter.php
src/Pim/Bundle/DashboardBundle/Widget/LastOperationsWidget.php
src/Pim/Bundle/DashboardBundle/spec/Widget/LastOperationsWidgetSpec.php
src/Pim/Bundle/DataGridBundle/Normalizer/DateTimeNormalizer.php
src/Pim/Bundle/DataGridBundle/spec/Normalizer/DateTimeNormalizerSpec.php
src/Pim/Bundle/EnrichBundle/Controller/Rest/VersioningController.php
src/Pim/Bundle/EnrichBundle/Normalizer/ProductModelNormalizer.php
src/Pim/Bundle/EnrichBundle/Normalizer/ProductNormalizer.php
src/Pim/Bundle/EnrichBundle/Normalizer/VersionNormalizer.php
src/Pim/Bundle/EnrichBundle/Resources/config/controllers.yml
src/Pim/Bundle/EnrichBundle/Resources/config/normalizers.yml
src/Pim/Bundle/EnrichBundle/spec/Normalizer/ProductModelNormalizerSpec.php
src/Pim/Bundle/EnrichBundle/spec/Normalizer/ProductNormalizerSpec.php
src/Pim/Bundle/FilterBundle/Filter/ProductValue/DateTimeRangeFilter.php
src/Pim/Bundle/FilterBundle/Resources/config/filters.yml
src/Pim/Bundle/FilterBundle/spec/Filter/ProductValue/ChoiceFilterSpec.php
src/Pim/Bundle/LocalizationBundle/Controller/FormatController.php
src/Pim/Bundle/LocalizationBundle/Resources/config/controllers.yml
src/Pim/Bundle/UserBundle/Context/UserContext.php

The users have now the possibility to set their own timezone (done in https://github.com/akeneo/pim-community-dev/pull/7789).
The second part of this feature is to apply this timezone on dates and datetimes displayed in the UI.
There are still some places where dates are in UTC but the most visible ones are ok (PEF meta, history, last operations, product grid). Another PR will follow.  …

AOB-100: Apply user timezone on dates in the UI

---

.ci/behat.community.yml
.ci/behat.enterprise.yml
CHANGELOG-2.0.md
behat.yml.dist
features/Context/FeatureContext.php
features/Pim/Behat/Context/Storage/AttributeOptionStorage.php
features/attribute/option/import_attribute_options.feature
src/Akeneo/Component/Batch/Event/EventInterface.php
src/Akeneo/Component/Batch/Step/ItemStep.php
src/Akeneo/Component/Batch/spec/Step/ItemStepSpec.php
src/Pim/Bundle/ConnectorBundle/DependencyInjection/PimConnectorExtension.php
src/Pim/Bundle/ConnectorBundle/EventListener/ResetProcessedItemsBatchSubscriber.php
src/Pim/Bundle/ConnectorBundle/Resources/config/event_listeners.yml
src/Pim/Bundle/ConnectorBundle/spec/EventListener/ResetProcessedItemsBatchSubscriberSpec.php
src/Pim/Component/Connector/Processor/Denormalization/AbstractProcessor.php
src/Pim/Component/Connector/Processor/Denormalization/Processor.php
src/Pim/Component/Connector/spec/Processor/Denormalization/ProcessorSpec.php

**What's the problem?**
When there are two items with the same identifier(s) in an import file that don't exist yet in the PIM, and they're processed in the same batch, then an MySQL error is thrown. 
It doesn't concern products import. The process is different and the duplication problem already handled.
It's about all the import jobs processed in [this generic Processor](https://github.com/akeneo/pim-community-dev/blob/2.0/src/Pim/Component/Connector/Processor/Denormalization/Processor.php)
Indeed, the items are read and processed one by one, but they're written by batch (100 items by default). There's no problem if the duplicate items already exists, they are simply updated twice; but if they don't exist, two distinct entities are created and persisted at the same time with the same …

PIM-7237: fix integrity constraint violation during import

---

src/Pim/Component/Connector/Validator/Constraints/FilterDataValidator.php

This fixes a weird error when you wanted to validate a product export builder configuration with the filter validator. This validator was not passing the context properly.
`-`: …

Fix PEB filter validator

---

CHANGELOG-2.0.md
src/Pim/Component/Connector/ArrayConverter/FlatToStandard/Product/FieldSplitter.php
src/Pim/Component/Connector/spec/ArrayConverter/FlatToStandard/Product/FieldSplitterSpec.php

This PR fixes an issue in product import of prices for multiple currencies. 
Previously, in `ArrayConverter/FlatToStandard/Product/FieldSplitter`, price values were split like this:
`123 EUR, ARS,23423 AUD` --> `['123 EUR', 'ARS,23423 AUD']`
This led to a fail in the product import when you have some currencies blank and some filled: 
`values[retail_price].data[3].data: This value should be a valid number.: ARS,23423 AUD`
So users could not override existing values with blank ones if they wished (which is the expected behaviour). I fixed this by updating the FieldSplitter splitPrices method to handle the case where we have blank values before the currency:
`123 EUR, ARS,23423 AUD` --> `['123 EUR', 'ARS', '23423 AUD']` 
**Definition Of …

PIM-7243: [SLA] issue on currencies in CSV and XLSX product imports

---

CHANGELOG-2.0.md
src/Pim/Bundle/CatalogBundle/Doctrine/Common/Saver/ProductSaver.php
src/Pim/Bundle/CatalogBundle/spec/Doctrine/Common/Saver/ProductSaverSpec.php

When there are duplicate products in an import file and these products are updated (not created) in the same process batch, then it generates a MySQL error on the completeness of the product.
New completeness objects are generated and persisted for each product. When there is a duplicated product, the first completeness objects are replaced by new instances in the product, but they have already been persisted, so Doctrine does two `Insert` statements when `Flush` is called.
The simple way to fix that without changing the completeness re-calculation behavior, is to remove the duplicates. It also has the advantage to prevent other similar problems.
| …

PIM-7244: Fix duplicated entry during products import

---

src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid/cell/boolean-status-cell.js

On EE 2.0, all attributes are indicated as 'smart attributes' on the grid.
Also filter on smart attribute won't work.
==> [PR on EE](https://github.com/akeneo/pim-enterprise-dev/pull/3700)
boolean-status-cell always show "yes" when the value is 0.
| Changelog updated                 | on EE
`-`: …

PIM-6919: Fix show boolean label for boolean-status-cell

---

CHANGELOG-2.0.md
src/Pim/Bundle/CatalogBundle/EventSubscriber/ResetUniqueValidationSubscriber.php
src/Pim/Bundle/CatalogBundle/Resources/config/event_subscribers.yml
src/Pim/Bundle/CatalogBundle/spec/EventSubscriber/ResetUniqueValidationSubscriberSpec.php
src/Pim/Bundle/ConnectorBundle/EventListener/ClearBatchCacheSubscriber.php
src/Pim/Bundle/ConnectorBundle/Resources/config/event_listeners.yml
src/Pim/Bundle/EnrichBundle/Connector/Processor/MassEdit/Family/SetAttributeRequirements.php
src/Pim/Bundle/EnrichBundle/Connector/Reader/MassEdit/FilteredFamilyReader.php
src/Pim/Bundle/EnrichBundle/spec/Connector/Reader/MassEdit/FilteredFamilyReaderSpec.php
src/Pim/Component/Connector/Writer/Database/ProductModelDescendantsWriter.php
src/Pim/Component/Connector/Writer/Database/ProductModelWriter.php
src/Pim/Component/Connector/Writer/Database/ProductWriter.php
src/Pim/Component/Connector/spec/Writer/Database/ProductModelDescendantsWriterSpec.php
src/Pim/Component/Connector/spec/Writer/Database/ProductModelWriterSpec.php
src/Pim/Component/Connector/spec/Writer/Database/ProductWriterSpec.php

See the SLA 7237 for more details. In a nutshell, when there are no writing during a product import (and when "Compare values" is enabled) then the cache of the repositories and the UnitOfWork are not cleared.
The goal of this PR is to delegating the responsibility of clearing the UOW and the repositories caches in a dedicated subscriber. 
I had to change `FilteredFamilyReader` because it loaded all the families at once. When the UOW is cleared, all the remaining families (in the next batch loop) were considered as new entities. 
| Added legacy Behats               | …

PIM-7240: Add subscriber to clear the cache between each job step batch

---

.ci/Jenkinsfile
src/Pim/Bundle/ConnectorBundle/Resources/config/steps.yml
src/Pim/Bundle/EnrichBundle/Resources/config/pim.yml
src/Pim/Bundle/EnrichBundle/Resources/config/steps.yml

The product size varies a lot between users of the PIM and we cannot have the same value for the batch size for each client. That's why I introduce a new parameter to set the batch size: `pim_job_batch_size`. You need to set it in your config.yml file to be able to override the default value.
```
parameters:
pim_job_batch_size: 12
``` …

PIM-7239: introduce pim_job_batch_size

---

features/Pim/Behat/Extension/PimFormatter/Output/Node/EventListener/JUnitDurationListener.php
features/Pim/Behat/Extension/PimFormatter/Output/Node/Printer/PimScenarioPrinter.php
features/Pim/Behat/Extension/PimFormatter/ServiceContainer/Formatter/PimFormatterFactory.php

See https://github.com/Behat/Behat/issues/820
Higlhy inspired from https://github.com/higrow/Behat/commit/eabe3346303034ba9426b84b4791a660abfaf2b5
This PR adds the duration of a behat scenario in the Junit result. …

Add duration into the junit report of the behat

---

CHANGELOG-2.0.md
src/Pim/Component/Connector/Archiver/FileReaderArchiver.php
src/Pim/Component/Connector/spec/Archiver/FileReaderArchiverSpec.php

To archive an import file, its content is loaded in memory using `file_get_contents`. Guess what happens when the file is big...
To fix that I used `putStream` instead of `put` and simply open the import file instead of loading its content. It's not perfect because we shouldn't use any PHP function on a file like that, but it would require too much changements for a simple patch. …

PIM-7241: Fix memory consumption issue when archiving an import file

---

CHANGELOG-2.0.md
features/attribute/edit_identifier_attribute.feature
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/attribute/identifier/edit.yml

This PR fixes the identifier attribute edit form to add the breadcrumbs, delete secondary action and user section.
Before
After

PIM-6945: Fix missing header elements on identifier attribute edit form

---

CHANGELOG-1.7.md
src/Pim/Bundle/FilterBundle/Resources/translations/messages.en.yml

Add translation "is not empty" for filters in the grid.

PIM-7119: Fix missing translation on filters

---

CHANGELOG-1.7.md
src/Pim/Bundle/CatalogBundle/Resources/config/validators.yml
src/Pim/Component/Catalog/Validator/ConstraintGuesser/DecimalGuesser.php
src/Pim/Component/Catalog/spec/Validator/ConstraintGuesser/DecimalGuesserSpec.php

When importing a product with a very long numeric that is longer than 10 digits (max length in the DB), MySQL will convert the number to the max possible, which is "9999999999.9999" (in the UI you see 9999999999.
As this number is a decimal, if the field is set to not allow decimal, it's not possible to save the product anymore.
Expected behaviour: add a validation on import to not allow number greater than the limit
| Micro …

PIM-7264: Add validation on import decimal number greater than limit in MySQL

---

CHANGELOG-1.7.md
src/Pim/Bundle/UserBundle/Resources/views/User/update.html.twig

Cancel button were always redirecting on Admin user profile, now if you press cancel button when editing a user, it redirect you on the users grid

PIM-6825: fix cancel button redirection on user profile edit

---

CHANGELOG-2.0.md
src/Pim/Bundle/EnrichBundle/Resources/translations/messages.en.yml

Some attribute's translations are missing in system attributes:
Image
Variant products

PIM-7257: Add missing translations in product grid

---

CHANGELOG-2.0.md
src/Pim/Bundle/CatalogBundle/tests/integration/EventSubscriber/LoadEntityWithValuesSubscriberIntegration.php
src/Pim/Component/Catalog/Exception/InvalidOptionsException.php
src/Pim/Component/Catalog/Factory/Value/OptionsValueFactory.php
src/Pim/Component/Catalog/Factory/ValueCollectionFactory.php
src/Pim/Component/Catalog/spec/Factory/Value/OptionsValueFactorySpec.php
src/Pim/Component/Catalog/spec/Factory/ValueCollectionFactorySpec.php

When an attribute option was removed and if this option was linked to a value inside a product, instead of just remove this option from values, we were throwing an exception without create values with good options.  …

PIM-7259: Remove only attribute's option removed for multi select attribute

---

CHANGELOG-2.2.md
src/Pim/Bundle/CatalogBundle/Command/RemoveWrongBooleanValuesOnVariantProductsCommand.php
src/Pim/Bundle/CatalogBundle/Elasticsearch/Filter/Field/ParentFilter.php
src/Pim/Bundle/CatalogBundle/Resources/config/query_builders.yml
src/Pim/Bundle/CatalogBundle/spec/Command/RemoveWrongBooleanValuesOnVariantProductsCommandSpec.php
src/Pim/Bundle/CatalogBundle/spec/Elasticsearch/Filter/Field/ParentFilterSpec.php

If variant product has values on boolean attributes that should belong to the parents, this parent will remove those values.

PIM-7263: Purging command for boolean values on variant products

---

CHANGELOG-2.0.md
src/Pim/Bundle/EnrichBundle/Controller/Rest/AttributeController.php
src/Pim/Bundle/EnrichBundle/Resources/public/js/controller/attribute/edit.js

Today, we use the same route to view an attribute in the PEF (which is in enrich part) and to view an attribute in the settings part. It's a mistake because the behavior is not the same. We need to apply permissions on the enrich part, but not in the settings part. 
As this subject is quite complex and should be rethink/rework, I made the same logic than all other routes (because the same mistake is done on family for instance), that's means: add an option in the URL to define if permissions have to be apply 
| Added …

PIM-7252: add option to do not apply permissions on attribute settings page

---

CHANGELOG-2.0.md
src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/product_group.yml
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/group/edit.yml
src/Pim/Bundle/EnrichBundle/Resources/public/js/group/form/products.js
src/Pim/Bundle/EnrichBundle/Resources/public/templates/form/grid.html
src/Pim/Bundle/UIBundle/Resources/public/less/components/grid/FilterBox.less

This PR fixes a regression created in https://github.com/akeneo/pim-community-dev/pull/7877 by using the old datafilter-builder instead of the new filters-list/filters-manage form extensions.  …

PIM-7275: Fix regression on group products grid filters

---

CHANGELOG-2.0.md
src/Pim/Bundle/EnrichBundle/Resources/public/js/common/breadcrumbs.js

We had an SLA on the breadcrumbs links doesn't work after the save on the attribute edit page. The problem was due to backbone want to make the click event but the element can't be find as it was render again by the JS after the save. …

PIM-6962 : Fix breadcrumb links after the save on edit page.

---

CHANGELOG-2.0.md
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/CreateProductIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/PartialUpdateProductToVariantIntegration.php
src/Pim/Bundle/CatalogBundle/EventSubscriber/AddBooleanValuesToNewProductSubscriber.php
src/Pim/Bundle/CatalogBundle/Resources/config/event_subscribers.yml
src/Pim/Bundle/CatalogBundle/spec/EventSubscriber/AddBooleanValuesToNewProductSubscriberSpec.php
src/Pim/Bundle/CatalogBundle/tests/integration/Completeness/AttributeType/BooleanAttributeTypeCompletenessIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/Product/AddBooleanValuesToNewProductIntegration.php
src/Pim/Component/Catalog/Builder/ProductBuilder.php

To avoid to handle "three-values" boolean, it had been decided to add default values for boolean attributes when a product is created.
The problem is that for a variant product, all the boolean attributes of the family are added, while only the attributes of the related level of the variant family should be added.
To fix that I choose to extract the boolean adding in a dedicated subscriber listening the event `StorageEvents::PRE_SAVE` . It couldn't be done anymore in `ProductBuilder` because when `ProductBuilder::create` is called for a variant product, the parent is not yet known (it's done in the updater). …

PIM-7267: Fix boolean attributes not added to variant product

---

.php_cd_v3.php
composer.json

Here is a fist version of the coupling detector rules according to the folder reorganization we "ideally target".
Rules have been defined by forbidding what shouldn't be used in a particular folder. Ideally, we should define the opposite: what a folder should only be able to use. But it's much more complex (as we also have to take into account the external dependencies like Symfony components). This first step will at least allow us to decouple properly the different "big set of features" we have.
| Review and 2 …

TIP-850: Define coupling detector rules

---

CHANGELOG-2.3.md
features/product-model/edit_product_model_and_filter_attributes.feature
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/product/edit.yml
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/product_model/edit.yml
src/Pim/Bundle/EnrichBundle/Resources/config/requirejs.yml
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/attribute-filter-all.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/attribute-filter-at-this-level.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/attribute-filter-missing-required.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/attribute-filter.js
src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml

Add the filter "All attributes of current level" to product edit form to display only attributes at the current level.
| Added legacy Behats               | Yes

PIM-6795: add filter to display only attribute at this level

---

CHANGELOG-2.0.md
features/mass-action/edit_common_attributes.feature
src/Pim/Bundle/EnrichBundle/Resources/public/js/mass-edit/form/product/add-to-existing-product-model.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/mass-edit/form/product/add-to-group.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/mass-edit/form/product/category.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/mass-edit/form/product/change-family.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/mass-edit/form/product/edit-common-attributes.js
src/Pim/Bundle/EnrichBundle/Resources/public/templates/mass-edit/product/category.html
src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/tab/categories.html
src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml
src/Pim/Bundle/EnrichBundle/Twig/CategoryExtension.php
src/Pim/Bundle/UIBundle/Resources/public/less/lib/jquery.jstree.less
src/Pim/Bundle/UIBundle/Resources/public/less/pages/Default.less

Prior to this PR, there was missing validation when configuring a mass-edit.
For instance, in a "change family" mass-edit we didn't check if the user actually choose a family before running the mass-edit job.
This PR adds those checks for the mass-edits of categories (remove, move, add), groups, edit attributes, family and add to existing product model. …

PIM-7260: Add validation in the 'configure' step of mass edits

---

CHANGELOG-2.0.md
src/Oro/Bundle/UserBundle/Controller/UserController.php
src/Pim/Bundle/UserBundle/Resources/views/User/update.html.twig

Flash message doesn't appear when edit user.

PIM-6999: Fix flash message on edit user

---

CHANGELOG-2.0.md
features/Context/FixturesContext.php
features/Pim/Behat/Context/Domain/Enrich/GridPaginationContext.php
features/Pim/Behat/Decorator/Grid/PaginationDecorator.php
features/user/edit_user_group_and_role_assignations.feature
src/Pim/Bundle/UserBundle/Resources/config/datagrid/group-user.yml
src/Pim/Bundle/UserBundle/Resources/config/datagrid/role-user.yml

Only 25 users are displayed in the user grid for Role or Group edition, it seems that the pagination is missing.

PIM-6993: Fix to add pagination in list of users in group and roles

---

.ci/Jenkinsfile
src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid/pagination-input.js

When we have more than 10 000 products on the product grid, we couldn't access to the last page.  We got an Elasticsearch error because it has a limitation of 10000 records set by the "max_rescore_window" parameter.
So to solve this problem, we decided to remove the button to access to the last page in the pagination. We know that it doesn't solve completely the problem. The client will get the problem if he want to display the 10000th product and more. However,  he has to go at least on the 400th page to see this error. So we admit that he will probably make a search or filter these products instead to use the pagination.
| …

PIM-7043 : Fix to add the last page into the pagination only if the total records is under 10000.

---

CHANGELOG-1.7.md
src/Akeneo/Bundle/StorageUtilsBundle/Doctrine/Common/Detacher/ObjectDetacher.php

This PR fixes an issue introduced in #7136, which results in totally emptying MongoODM UnitOfWork's `originalDocumentData`, `embeddedDocumentRegistry` and `parentAssociations` properties when calling `Akeneo\Bundle\StorageUtilsBundle\Doctrine\Common\Detacher\ObjectDetacher::detach()` method on a Product or ProductValue.
| Tech Doc …

Fix ObjectDetacher::detach for MongoODM

---

CHANGELOG-2.2.md
src/Pim/Bundle/EnrichBundle/Connector/Writer/MassEdit/ProductAndProductModelWriter.php
src/Pim/Bundle/EnrichBundle/spec/Connector/Writer/MassEdit/ProductAndProductModelWriterSpec.php
src/Pim/Component/Connector/Processor/Normalization/ProductProcessor.php
src/Pim/Component/Connector/Writer/Database/ProductWriter.php
src/Pim/Component/Connector/spec/Processor/Normalization/ProductProcessorSpec.php

The implementation of the "cache clearer" has been changed, and now the Doctrine UoW is cleared. This as resulted to the bug described in PIM-7281 : the product models exports are broken.
When 2 product models with the same variant family are exported, an error is thrown. The UoW is cleared between each product write, and given that the variant family property in a product model is lazy loaded, Doctrine can't load the variant family of the second product model. 
Since the PR #7815 the calls to clear the cache during jobs executions are done in a subscriber that listen to a new event dispatched from `ItemStep` between each batch. So the fix is just to remove the calls to `EntityManagerClearerInterface::clear` that are still done inside …

PIM-7281: Fix inappropriate calls to the cache clearer

---

CHANGELOG-2.3.md
features/Context/FixturesContext.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/GetVariantProductIntegration.php
src/Pim/Bundle/CatalogBundle/DependencyInjection/Compiler/ResolveDoctrineTargetModelPass.php
src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/AssociationTypeRepository.php
src/Pim/Bundle/CatalogBundle/Resources/config/entities.yml
src/Pim/Bundle/CatalogBundle/Resources/config/model/doctrine/Product.orm.yml
src/Pim/Bundle/CatalogBundle/Resources/config/model/doctrine/ProductAssociation.orm.yml
src/Pim/Bundle/VersioningBundle/spec/Normalizer/Flat/ProductNormalizerSpec.php
src/Pim/Component/Catalog/Builder/ProductBuilder.php
src/Pim/Component/Catalog/Builder/ProductBuilderInterface.php
src/Pim/Component/Catalog/Model/AbstractAssociation.php
src/Pim/Component/Catalog/Model/AssociationAwareInterface.php
src/Pim/Component/Catalog/Model/AssociationInterface.php
src/Pim/Component/Catalog/Model/ProductAssociation.php
src/Pim/Component/Catalog/Model/ProductAssociationInterface.php
src/Pim/Component/Catalog/Model/ProductInterface.php
src/Pim/Component/Catalog/Repository/AssociationTypeRepositoryInterface.php
src/Pim/Component/Catalog/Updater/Setter/AssociationFieldSetter.php
src/Pim/Component/Catalog/spec/Builder/ProductBuilderSpec.php
src/Pim/Component/Catalog/spec/Model/ProductSpec.php
src/Pim/Component/Connector/spec/Writer/Database/ProductAssociationWriterSpec.php

**Prepare product models associations**
This PR is the first preparation step to be able to use associations with product models. To do so, we introduce the `AssociationAwareInterface` to extract the association features from the Product class.
We also rename `Association` into `ProductAssociation`. Do you feel the `ProductModelAssociation` coming? :smiley: 
| Added Specs                       | Updated
| Migration …

Introduce the AssociationAwareInterface

---

CHANGELOG-2.0.md
src/Akeneo/Bundle/StorageUtilsBundle/Doctrine/ORM/MappingsOverrideConfigurator.php
src/Pim/Bundle/CatalogBundle/Doctrine/ResolveTargetDiscriminatorMapForProductSubscriber.php
src/Pim/Bundle/CatalogBundle/Resources/config/event_subscribers.yml
src/Pim/Bundle/CatalogBundle/Resources/config/model/doctrine/AbstractProduct.orm.yml
src/Pim/Bundle/CatalogBundle/spec/Doctrine/ResolveTargetDiscriminatorMapForProductSubscriberSpec.php

Today, product and variant product classes are "hardcoded" in the discriminator map of the AbstractProduct mapping (see ).
Which it's impossible to easily override the Product or the VariantProduct classes.
This PR solves this problem.
Therefor, it closes the tickets SDS-2513 and SDS-2496.
**This PR should be reverted on 2.2.**

PIM-7216: Resolve target discriminator map for products

---

CHANGELOG-2.0.md
features/Context/Page/Base/Form.php
features/Context/WebUser.php
features/Pim/Behat/Decorator/Field/Select2Decorator.php
features/category/display_category_history.feature
features/family/list_family_variant.feature
features/family/remove_attribute_from_a_family.feature
features/product-model/create_product_model.feature
src/Pim/Bundle/EnrichBundle/Controller/Rest/FamilyVariantController.php
src/Pim/Bundle/EnrichBundle/Doctrine/ORM/Repository/FamilyVariantSearchableRepository.php
src/Pim/Bundle/EnrichBundle/Resources/config/controllers.yml
src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/family_variant.yml
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/mass_edit/add_to_existing_product_model.yml
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/product_model/create.yml
src/Pim/Bundle/EnrichBundle/Resources/config/repositories.yml
src/Pim/Bundle/EnrichBundle/Resources/config/routing/family_variant.yml
src/Pim/Bundle/EnrichBundle/Resources/public/js/product-model/form/creation/variant.js

This PR adds a missing pagination on the Family variant grid in the family edit form, and fixes the search/pagination in the `select2` on the 'create product model' form, as well as the 'add to existing product model' mass action form
`Todo`: …

PIM-7299: Add pagination for family variants on several screens

---

CHANGELOG-2.0.md
src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filter/choice-filter.js
src/Pim/Bundle/UIBundle/Resources/public/less/lib/select2.less

When we add a long list of values in the SKU filters, we can't see the update button anymore. This is because the popup is too big compare to the window.
So to solved that, I had to fix the max height and add the scroll on the popup. Also, I have to update the position of the popup when we add a value in the select2.
| Migration …

PIM-7304 : Fix the SKU filter to be able to be scrollable

---

CHANGELOG-2.0.md
src/Akeneo/Bundle/BatchQueueBundle/Queue/DatabaseJobExecutionQueue.php
src/Akeneo/Bundle/BatchQueueBundle/Queue/JobExecutionMessageRepository.php
src/Akeneo/Bundle/BatchQueueBundle/spec/Queue/DatabaseJobExecutionQueueSpec.php

A same job can executed by two different daemons, with obvious consequences:
- concurrent INSERT on primary key
- job failing
- etc
In theory, it's impossible to execute the same job by two different daemons, due to a locking strategy that I implemented with the database. 
But it occurs when you have a lot of daemons (for example 10, probability to have the bug increases with the number of daemons). 
Also, it has more chance to occur when you have a lot of "fast" job in the queue, such as "akeneo_batch_job_execution_queue".
The problem is due to the locking strategy that was not robust enough, allowing a race condition to consume a job two times.
**Explication of the race condition:**
- Expected behavior:
| Daemon 1 …

[SLA] PIM-7313: prevent the same job to be executed by two different daemons due to race condition

---

CHANGELOG-2.0.md
features/family/define_the_attribute_requirement.feature
src/Pim/Component/Catalog/Updater/FamilyUpdater.php
src/Pim/Component/Catalog/spec/Updater/FamilyUpdaterSpec.php

This PR fixes an issue when trying to add an attribute requirement for a family, and the attribute requirement already exists but its `required` property is set to `false` (which is the case for newly created channels) …

PIM-7312: Fix attribute requirements update for a newly created channel

---

CHANGELOG-2.0.md
src/Pim/Bundle/CatalogBundle/Command/CalculateCompletenessCommand.php

Calculation of the completeness is the origin of a lot of problems with the support, due to multiple cron executed concurrently to calculate it (because the previous one is not finished).
The error is a violation of database integrity.
I know that this fix is not working if the customer is doing the cron across multiple servers, as the locking is with a `flock`.
But the cron of the completeness should be configured on only one server, so it's not really a problem.
It will fix 90% of problems in an easy way.
| Added …

PIM-7321: prevent concurrent calculation of the completeness 

---

CHANGELOG-2.0.md
src/Pim/Component/Catalog/Model/ProductModel.php
src/Pim/Component/Catalog/spec/Model/ProductModelSpec.php

When you have a violation on a product model when applying rules, the product model can not be cast as string:
https://github.com/akeneo/pim-enterprise-dev/blob/2.0/src/PimEnterprise/Component/CatalogRule/Engine/ProductRuleApplier/ProductsValidator.php#L69
It is the case of the product.
So, an exception is thrown:
"CATCHABLE FATAL ERROR: OBJECT OF CLASS PIM\COMPONENT\CATALOG\MODEL\PRODUCTMODEL COULD NOT BE CONVERTED TO STRING" …

PIM-7322: Fix cast of a product model as string to format correctly violations

---

CHANGELOG-2.0.md
src/Pim/Component/Connector/Reader/Database/ProductModelReader.php
src/Pim/Component/Connector/spec/Reader/Database/ProductModelReaderSpec.php

Since #7815 The UnitOfWork is cleared between each job execution batch. The problem is that there was an error in the database `ProductModelReader` so the items of the next batch were loaded from the database before the last current batch item is processed.
This problem has been fixed for the `ProductReader` in #7641 on 2.2 and brought back to 2.0, but not for the `ProductModelReader` because it doesn't exist on 2.2. So I just report the same fix but on `ProductModelReader`
| Added …

PIM-7317: Fix iterator misuse in the database product model reader

---

src/Pim/Bundle/CatalogBundle/tests/integration/Elasticsearch/IndexConfiguration/AbstractPimCatalogProductModelIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/Elasticsearch/IndexConfiguration/SearchProductsAndModelsIntegration.php

- Search on categories does not work properly today
- I propose a solution to make it work by indexing additional information and changing the way we search products and product models in the datagrid
- ES integration tests have been updated:
- Updated dataset https://github.com/akeneo/pim-community-dev/blob/0bc9783562812cd62caed2f34b6dd23da1c25aed/src/Pim/Bundle/CatalogBundle/tests/integration/Elasticsearch/IndexConfiguration/AbstractPimCatalogProductModelIntegration.php
- Working ES request samples are in this file https://github.com/akeneo/pim-community-dev/blob/0bc9783562812cd62caed2f34b6dd23da1c25aed/src/Pim/Bundle/CatalogBundle/tests/integration/Elasticsearch/IndexConfiguration/SearchProductsAndModelsIntegration.php
Prior to this PR, the search of product models in the datagrid was …

PIM-6784: Improve the search of product models with categories in the datagrid

---

composer.json

This allows to easily set the Elasticsearch hosts in an automated deployment environment.

Add index_hosts to the incenteev parameters.

---

.ci/behat.enterprise.yml
CHANGELOG-2.2.md
src/Pim/Bundle/CatalogBundle/Elasticsearch/Filter/Field/CompletenessFilter.php
src/Pim/Bundle/CatalogBundle/Resources/config/query_builders.yml
src/Pim/Bundle/CatalogBundle/spec/Elasticsearch/Filter/Field/CompletenessFilterSpec.php
src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Field/CompletenessFilterIntegration.php

We got an SLA that we couldn't have a completeness rule condition with the operator '='
on the completeness. However in the documentation, we specify that we can add custom rules on the completeness with the operators '=', '!=', '<', '>' (https://docs.akeneo.com/2.2/manipulate_pim_data/rule/general_information_on_rule_format.html#completeness). The completeness filter used on the product and product model index doesn't accept those operators.
To fix it, I added the missing operators on the service declaration of the completeness filter and implemented the ES query for each operator use case.
| Added Specs …

PIM-7310 : Fix completeness in rule's conditions

---

CHANGELOG-2.2.md
src/Akeneo/Bundle/BatchBundle/Job/DoctrineJobRepository.php

The command akeneo:batch:purge-job-execution as a memory leak (only a flush in a final execution). 

PIM-7305: correct memory leak on purge job command

---

CHANGELOG-2.0.md
features/family/browse_families.feature
src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filters-button.js
src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filters-list.js

This fixes an issue where the family grid search bar was no more usable when coming back from a family edit form.

PIM-7325: Fix family grid search filter

---

CHANGELOG-1.7.md

Missing PIM ticket in CE 1.7.20

added - PIM-7239 in changelog

---

.ci/Jenkinsfile
.ci/behat.enterprise.yml

Fixes the default path for legacy behats in nightly builds.

Fix default legacy features path for nightly builds

---

CHANGELOG-2.0.md
features/attribute-group/list_attribute_groups.feature
src/Pim/Bundle/EnrichBundle/Resources/public/js/attribute-group/form/list.js

The PIM takes the UI locale into account to display the attribute group names and not the catalog locale.
The PIM should display the labels for the catalog locale not the UI locale.
Regression since 1.7.
`OK`: Done / …

PIM-7338: Attribute groups label used catalog locale (not UI locale) in grid

---

CHANGELOG-2.0.md
features/product/filtering/filter_products.feature
src/Pim/Bundle/CatalogBundle/Elasticsearch/Filter/Attribute/AbstractAttributeFilter.php
src/Pim/Bundle/CatalogBundle/Elasticsearch/Filter/Attribute/TextAreaFilter.php
src/Pim/Bundle/CatalogBundle/Elasticsearch/Filter/Attribute/TextFilter.php
src/Pim/Bundle/CatalogBundle/Elasticsearch/Filter/IdentifierFilter.php
src/Pim/Bundle/CatalogBundle/spec/Elasticsearch/Filter/IdentifierFilterSpec.php
src/Pim/Component/Catalog/Query/Escaper/QueryString.php

`Pim\Bundle\CatalogBundle\Elasticsearch\Filter\IdentifierFilter` uses ES query_string clauses for `CONTAINS`, `DOES NOT CONTAIN` and `STARTS WITH` operators, so the values have to be escaped (see [elasticsearch documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#_reserved_characters))
Fixes #7806 
| Added legacy Behats               | Ok
| Micro Demo …

PIM-7334: Fix identifier filter with special characters

---

CHANGELOG-2.0.md
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/product-completeness.js
src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/form/product-completeness.html

Nobody complained since 2.0 so maybe that's not that important to test. I can add one if needed

PIM-7337: fix completeness popup when no label on attribute

---

CHANGELOG-2.0.md
features/family/remove_attribute_from_a_family.feature
src/Pim/Bundle/PdfGeneratorBundle/Resources/views/Product/renderPdf.html.twig

Boolean values set to false used to not be displayed at all in PDF exports, and `true` was rendered as `1`. This PR allows rendering boolean values as translated "Yes" or "No" in PDF exports

PIM-7351: Fix boolean values display in product PDF

---

.ci/Jenkinsfile
.ci/bin/start-elasticsearch
CHANGELOG-2.3.md
Dockerfile
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/PartialUpdateListVariantProductIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/ProductModel/CreateProductModelIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/ProductModel/PartialUpdateListProductModelIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/ProductModel/PartialUpdateProductModelIntegration.php
src/Pim/Bundle/CatalogBundle/Resources/config/entity_with_family_variant.yml
src/Pim/Bundle/CatalogBundle/Resources/translations/validators.en.yml
src/Pim/Bundle/CatalogBundle/tests/integration/Product/CreateProductModelIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/Product/CreateVariantProductIntegration.php
src/Pim/Component/Catalog/Exception/AlreadyExistingAxisValueCombinationException.php
src/Pim/Component/Catalog/Model/ProductModel.php
src/Pim/Component/Catalog/Repository/EntityWithFamilyVariantRepositoryInterface.php
src/Pim/Component/Catalog/Validator/Constraints/UniqueVariantAxis.php
src/Pim/Component/Catalog/Validator/Constraints/UniqueVariantAxisValidator.php
src/Pim/Component/Catalog/Validator/UniqueAxesCombinationSet.php
src/Pim/Component/Catalog/Value/OptionValue.php
src/Pim/Component/Catalog/spec/Exception/AlreadyExistingAxisValueCombinationExceptionSpec.php
src/Pim/Component/Catalog/spec/Model/ProductModelSpec.php
src/Pim/Component/Catalog/spec/Validator/Constraints/UniqueVariantAxisValidatorSpec.php
src/Pim/Component/Catalog/spec/Validator/UniqueAxesCombinationSetSpec.php
tests/legacy/features/import/product_model/import_with_invalid_data.feature
tests/legacy/features/product-model/add_product_model_children.feature

When changing the parent of a variant product or a product model, or when creating a new one, we need to ensure there is not already an other variant product or product model with the same axis values.
The previous validation message was not explicit enough, as it didn't mention which entities were impacted (updated/created one, nor already existing one).
This PR updates this message, and also makes the distinction between variant products and product models.
| Added legacy Behats               | Updated
| Added integration tests           | Updated …

PIM-7330: Better validation message on sibling duplicate

---

Dockerfile

Our CI is using `php:7.1-fpm` image from the Docker library. This night, the image was updated from Debian Jessie to Stretch, removing some usefull tools from it, and making our build fail.
This PR fixes the base image to `php:7.1.16-fpm` so we are sure this won't happen again.

Fix CI build

---

tests/legacy/features/Context/FixturesContext.php
tests/legacy/features/export/product_model/csv/export_product_models.feature
tests/legacy/features/export/product_model/xlsx/export_product_models.feature

After a mess with CI - rebase - CI - rebase again … (you know what I mean), two behats were broken, but only on EE, not CE. This was caused by empty variations being generated differently in CE and EE (because of permissions in EE) from our behat fixtures (not a real-use PIM issue).
This PR fixes those two scenarios. …

Fix tests on product model export with association

---

CHANGELOG-1.7.md
src/Pim/Component/Catalog/Updater/ChannelUpdater.php
src/Pim/Component/Catalog/spec/Updater/ChannelUpdaterSpec.php

When you edit the channel and set a conversion unit to his default value "do not convert", it don't update it (so the previous conversion is still used).
Phpspec : OK
Tests …

PIM-7336: Fix setConversionUnits of ChannelUpdater to accept empty value

---

CHANGELOG-1.7.md
src/Akeneo/Bundle/BatchBundle/Job/DoctrineJobRepository.php

This fix is a backport of https://github.com/akeneo/pim-community-dev/pull/8021 into 1.7

PIM-7385: Fix memory leak on purge job command

---

CHANGELOG-2.2.md
src/Pim/Bundle/DataGridBundle/Datasource/AssociatedProductDatasource.php
src/Pim/Bundle/DataGridBundle/spec/Datasource/AssociatedProductDatasourceSpec.php

There is an issue when you associate a product and a product model with the same id.
The Datagrid do not display duplicates with the same "id" field (not used in the association grid).
We just added a specific label for splitting product and product models.

[PIM-7367] Fix associations of product and product model with same ids

---

CHANGELOG-2.0.md
src/Pim/Bundle/DataGridBundle/Resources/public/templates/datagrid/cell/history-diff-cell.html
src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/history.html
src/Pim/Bundle/UIBundle/Resources/public/less/components/grid/Grid.less

[PIM-7040] Fix bad history display on large strings

---

CHANGELOG-2.2.md
src/Pim/Bundle/CatalogBundle/Elasticsearch/Filter/IdentifierFilter.php
src/Pim/Bundle/CatalogBundle/Resources/config/query_builders.yml
src/Pim/Bundle/CatalogBundle/spec/Elasticsearch/Filter/IdentifierFilterSpec.php
src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Field/IdentifierFilterIntegration.php

Since we added a parent filter in the 2.1 version, we got the "IS EMPTY" operator on the SKU filter. However, when we try to filter on this operator we get a 500 error. This is because the EMPTY operator wasn't added on the Identifier filter. To make the fix we added this operator.
P.S : The operator "IS EMPTY" shouldn't exist on the SKU filter because we get all the time no result (only products have a sku). So, we will have to create a dedicated filter type for the SKU. It will be done on 2.3 with this bulletproof ticket (https://akeneo.atlassian.net/browse/PIM-7345). …

PIM-7315 : 500 on "IS EMPTY" operator for the SKU filter

---

CHANGELOG-2.2.md
src/Pim/Bundle/CatalogBundle/Doctrine/Common/Saver/ProductModelDescendantsSaver.php
src/Pim/Bundle/CatalogBundle/Resources/config/savers.yml
src/Pim/Bundle/CatalogBundle/spec/Doctrine/Common/Saver/ProductModelDescendantsSaverSpec.php

When you save a product model:
- The product model is saved in database
- The product model is indexed in ES (post save event)
- The completeness is computed for all product model children (post save event)
- The product model indexation is done
- The job which computes product completeness is finished
Problem is that when the indexation is done, the product completeness computation job is not finished. That means the ratio of complete product models may change during this task so we need to index again the product model. If we don't do that it may break the complete filter on the grid because wrong data was indexed in ES.
| …

PIM-7388: [SLA] Completeness filter on product grid for models does not work as expected

---

CHANGELOG-2.0.md
src/Pim/Bundle/UIBundle/Resources/public/less/components/SquareList.less

[PIM-7014] Fix attribute creation page with large strings

---

CHANGELOG-2.2.md
src/Pim/Bundle/EnrichBundle/Controller/Rest/AssociationTypeController.php

It was a typo on association type rest controller, it raises a Forbidden to get an association type event if you have the permissions.

PIM-7319: Fix association display on product edit form when managing the association type permissions

---

CHANGELOG-2.0.md
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/attribute-filter.js

The event selector for displaying attributes was too generic, and clicking on "Display" title of the Dropdown implies everything removed from the page.

PIM-6846: Fix bug on click in Display Attributes button on Product edit form

---

CHANGELOG-2.0.md
src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filters-manager.js
src/Pim/Bundle/DataGridBundle/Resources/public/templates/datagrid/add-filter-select.html

Previously, when you set a sort order like 100000000 on an attribute group, the grid was unable to load.
Why ? Because on the function sorting the attribute groups, it generated an array of 1000000000 elements... And it crashed.
Second thing is that if 2 attribute groups had the same sort order, it puts the second encountered one at the end of the list.
Now, the sort is a little bit complex, but it works as designed and does not fail.
IMHO, this is not "easily" testable (and have no interest) …

PIM-7311: Fix the product grid filters list with a sort order is a huge number

---

features/product-model/edit_product_model.feature
src/Pim/Bundle/EnrichBundle/Controller/Rest/ProductModelController.php

In `Pim\Bundle\EnrichBundle\Controller\Rest\ProductModelController::postAction()`, the normalization context was different from the other actions (no `filter_types` key provided, which resulted in applying the default filters: https://github.com/akeneo/pim-community-dev/blob/2f4f43f99f864d725b3515d59b6c0243fe9ddf5e/src/Pim/Component/Catalog/Normalizer/Standard/ProductModelNormalizer.php#L49
One of these filters is `pim_enrich.filter.product_value.channel`, which filters values for scopable attributes when the value's channel is not in the user context. 
Problem is: the context's channels are provided by the `Pim\Bundle\UserBundle\Context::toArray()` method which is wrong (it returns chanlles' labels instead of codes, see #8207)
This results in every scopable value being filtered unless …

PIM-7382: Fix scopable attributes disappearing from edit form after editing a product model

---

CHANGELOG-2.0.md
src/Pim/Bundle/ApiBundle/Controller/ProductModelController.php
src/Pim/Bundle/ApiBundle/Resources/config/normalizers.yml
src/Pim/Component/Api/Normalizer/ProductModelNormalizer.php
src/Pim/Component/Api/spec/Normalizer/ProductModelNormalizerSpec.php

When listing product models with the API, only the ten last where returned.
As the default limit is ten, we didn't see that. But if you increase the limit to 20, it returns only the ten last elements.
The issue is that that the Collecton normalizer was never used: so, it uses wrong the default normalizer of Symfony, that is not working properly with our cursors (problem of key).
The origin of this error is that we have to use the API normalizer instead of "standard" normalizer.
It fixes another error as well:
- links were not generated for media product values (spec is explicit)
| Added Specs …

PIM-7391: Fix offset pagination when listing product models with the API

---

CHANGELOG-2.2.md
src/Pim/Bundle/CatalogBundle/Elasticsearch/Filter/Attribute/OptionFilter.php
src/Pim/Bundle/CatalogBundle/spec/Elasticsearch/Filter/Attribute/OptionFilterSpec.php
src/Pim/Bundle/CatalogBundle/tests/integration/Elasticsearch/IndexConfiguration/PimCatalogOptionIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/Elasticsearch/IndexConfiguration/PimCatalogOptionsIntegration.php

When using 'NOT IN' operator with `Pim\Bundle\CatalogBundle\Elasticsearch\Filter\Attribute\OptionFilter`, an 'exists' filter clause for the field is appended to the query. This results in products with an empty value for the attribute (either with a null/empty array value, or not indexed yet in ES) not being returned by the query.
This PR removes this filter clause.
Downside: Now the query returns: 
- products with this attribute but with a different value as the one(s) provided
- products with an empty value for this attribute
- BUT also products **without this attribute** (that's also the current behaviour of other filter/operator couples - e.g EMPTY operator with most of the attribute filters)
| …

PIM-7386: Fix 'NOT IN' operator not taking empty values into account for select fields

---

CHANGELOG-2.2.md
features/import/product/import_products_with_invalid_headers.feature
src/Pim/Component/Connector/ArrayConverter/FlatToStandard/Product.php
src/Pim/Component/Connector/spec/ArrayConverter/FlatToStandard/ProductSpec.php

The previous error message was really confusing.
Now, it is more explicit, explaining why the field is "unknown".
| Added legacy Behats               | y

PIM-7393: Improve error message when importing fields without locale or scope specification

---

CHANGELOG-2.0.md
src/Pim/Bundle/DataGridBundle/Datasource/AssociatedProductDatasource.php

The pagination of the associated product did not work at all.
All of this is completely dropped in 2.1 with product models and all that !

PIM-7009: Fix bug with pagination on associated products page on product edit form

---

CHANGELOG-2.0.md
src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filter/abstract-filter.js

In the case of criteria with big size, it badly displays it to the bottom of the page.
Now, if a place can not be found up or down, it simply displays it on top of the page.

PIM-7383: Fix in-list product filters

---

CHANGELOG-1.7.md
src/Pim/Bundle/UserBundle/Resources/config/datagrid/group-user.yml
src/Pim/Bundle/UserBundle/Resources/config/datagrid/role-user.yml

The multiple sorting into grid is a weird experience of sorting, not very natural. 
We remove this sorting option into the "System / Users Management / Groups / Users" grid and "System / Users Management / Roles / Users" grid and use a natural column by column sorting.
| Tech Doc …

PIM-7370 - Sort filters on group and role grids are not consistent

---

CHANGELOG-1.7.md
src/Pim/Bundle/CatalogBundle/EventSubscriber/MongoDBODM/UpdateNormalizedProductDataSubscriber.php

…  as they cannot appear in the normalizedData anyway.
see https://github.com/akeneo/ElasticSearchBundle/pull/163

PIM-7253: do not schedule queries to update normalized data for newly created entities

---

CHANGELOG-2.0.md
src/Pim/Bundle/EnrichBundle/Resources/public/js/filter/product/category/selector.js

On 2.X, it is not possible to modify the categories in the product import profile (both XLS and CSV), if the categories have a numeric code, it is not possible to unselect categories. 
For 2.0.X this concerns Product Export in CSV and XLSX
For 2.2.X, this concerns Product Export in CSV and XLSX and Product Model Export in CSV and XLSX …

PIM-7398: Fix unselect category in the tree with numeric code

---

CHANGELOG-1.7.md
src/Pim/Bundle/ApiBundle/Resources/config/routing/product.yml

Not really testable:
- fake request use a fake router
- ideally, it should test it with apache as it is infrastructure stuff
I tested and it works with GET and PATCH:
- /products//my_identifier  ("/my_identifier")
- /products/my_identifier/  ("/my_identifier/")
- /products/my_id/entifier  ("my_id/entifier")
| Micro Demo to the PO (Story only) | Todo? …

PIM-7394: add slash as an allowed character for the identifier of a product in the API

---

CHANGELOG-2.0.md
src/Pim/Bundle/EnrichBundle/Resources/config/routing/category.yml
src/Pim/Bundle/EnrichBundle/Resources/public/js/filter/product/category/selector.js

This PR fixes a bug in the export product category selection. Previously, selecting many categories caused the request to `/rest/{identifier}/selected-children` to fail with a `414 Request-URI Too Large` error because we were appending every selected category to the url as a query parameter. 
I changed this method to a POST to send the selected categories in the body instead.  …

PIM-7411: [SLA] Use json post for selected categories in product export

---

CHANGELOG-2.3.md
src/Pim/Component/Catalog/EntityWithFamily/IncompleteValueCollection.php
src/Pim/Component/Catalog/EntityWithFamily/IncompleteValueCollectionFactory.php
src/Pim/Component/Catalog/EntityWithFamily/RequiredValue.php
src/Pim/Component/Catalog/EntityWithFamily/RequiredValueCollection.php
src/Pim/Component/Catalog/EntityWithFamily/RequiredValueCollectionFactory.php
src/Pim/Component/Catalog/Model/AbstractValue.php
src/Pim/Component/Catalog/Model/ValueCollection.php
src/Pim/Component/Catalog/spec/EntityWithFamily/IncompleteValueCollectionFactorySpec.php
src/Pim/Component/Catalog/spec/EntityWithFamily/IncompleteValueCollectionSpec.php
src/Pim/Component/Catalog/spec/EntityWithFamily/RequiredValueCollectionFactorySpec.php
src/Pim/Component/Catalog/spec/EntityWithFamily/RequiredValueCollectionSpec.php
src/Pim/Component/Catalog/spec/EntityWithFamily/RequiredValueSpec.php
src/Pim/Component/Catalog/spec/Validator/UniqueAxesCombinationSetSpec.php
tests/back/Acceptance/spec/Product/InMemoryProductRepositorySpec.php

**Context:**
The calculation of the completeness of products is a two step process.
It basically starts in this class: `Pim\Component\Catalog\Completeness\CompletenessCalculator::Calculate`
**1. Build the list of required values based on the attribute requirements.**
Based on the attribute requirements of the family, we generate a
`Pim\Component\Catalog\EntityWithFamily\RequiredValueCollection`, which holds a list of `\Pim\Component\Catalog\EntityWithFamily\RequiredValue`.
Basically, this object holds a reference for each required value for:
- An attribute
- A channel
- A locale
Important note:
Conviniently, this RequiredValue extends `Pim\Component\Catalog\Model\ValueInterface` which
gives us the opportunity to get the value of a …

PIM-7347: Fix completeness for locale specific attributes

---

CHANGELOG-2.0.md
src/Pim/Bundle/EnrichBundle/Controller/Rest/GroupController.php

I went too fast on the PIM-7389 and there was a but about the search.
This PR fixes the fact than the search was not active on the select2.

[PIM-7426] Fix search on add to group mass edit

---

behat.yml.dist
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/field/field.js
src/Pim/Component/Catalog/Normalizer/Standard/Product/ProductValueNormalizer.php
tests/legacy/features/Context/FeatureContext.php
tests/legacy/features/Pim/Behat/Context/Domain/Enrich/ProductContext.php
tests/legacy/features/Pim/Behat/Context/ImportExportFileContext.php

When normalizing product values, we always sort them, as we usually don't care about the order. However, to be able to sort assets in asset collection, in EE, we need to be able to prevent this sorting.
This PR 
- extracts this sorting in a dedicated, protected method, so it can be overridden in EE, specifically for the asset collection attribute type,
- reworks some behat contexts, so two steps that were dedicated to variant products can also be used on regular products too (it also removes some useless stuff from one of this context)
| Changelog …

PIM-7405: Extract ordering in ProductValueNormalizer

---

CHANGELOG-2.2.md
src/Pim/Bundle/ConnectorBundle/Resources/config/writers.yml

The product export builder allows to select attributes to export and reorder them.
It's working fine for the product exports but not for product models exports.

PIM-7399: Fix order attributes on Product model export

---

CHANGELOG-2.3.md
src/Pim/Bundle/DataGridBundle/Datasource/AssociatedProductDatasource.php
src/Pim/Bundle/DataGridBundle/Datasource/AssociatedProductModelDatasource.php
src/Pim/Bundle/DataGridBundle/spec/Datasource/AssociatedProductModelDatasourceSpec.php
src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/association_product.yml
src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/association_product_model.yml
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/associated-product-row.js

This PR removes the button to delete an association if this one comes from inheritance (from parents).
So if you can delete it, you'll have the cross (as of nowadays):
But if you can't, it's not displayed:
---- 
**Note that it also complement the fix made on https://github.com/akeneo/pim-community-dev/pull/8206 (PIM-7367) to handle associations displayed on root and sub product models.**
----  …

PIM-7001: Don't display remove button on an association if it comes from inheritance

---

CHANGELOG-2.3.md
src/Akeneo/Component/Versioning/Model/VersionableInterface.php
src/Pim/Bundle/EnrichBundle/Resources/config/readers.yml
src/Pim/Bundle/EnrichBundle/Resources/config/steps.yml
src/Pim/Bundle/EnrichBundle/Resources/public/js/mass-edit/form/product/associate.js
src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml
src/Pim/Bundle/EnrichBundle/Resources/translations/messages.en.yml
src/Pim/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev/jobs.yml
src/Pim/Bundle/InstallerBundle/Resources/fixtures/minimal/jobs.yml
tests/legacy/features/Context/Page/Batch/Operation.php
tests/legacy/features/mass-action/mass_associate.feature

Currently, when we try to bulk associate products to product model, it will in fact make associations with all the variant products.
We now can associate directly to product models so we don't need to associate to it's children.
This is done very simply just by using the 'grouped' reader which will apply associations on the selected items without fetching the children.
| Added legacy Behats               | Updated
| Tech Doc …

PIM-7308: bulk associate to product models

---

src/Pim/Bundle/InstallerBundle/Command/DatabaseCommand.php
src/Pim/Bundle/UIBundle/Resources/public/less/components/LoadingMask.less
tests/front/acceptance/cucumber/world.js
tests/front/unit/jest/unit.jest.js

This PR adds options to install the db without indexation and without fixtures. Those options are useful for testing purpose. It also fixes front unit tests and adds a placeholder loading less componnent …

PIM-7381: add more option to the database command for a lighter install

---

CHANGELOG-1.7.md
src/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/IndexCreator.php

We had a problem with locks on big mongo db database when trying to reindex data.
After digging into the code, it appears that this timeout comes from trying to get the index info while some indexes where still under processing.
This PR adds a loop over this get index info function to wait for the lock released.
Note: in tests on client environment, the loop is just used one time.
| Tech Doc …

PIM-7400: ensureIndexes uses a retry loop

---

CHANGELOG-2.3.md
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/attribute-filter.js

Now we keep context filter for attributes:

PIM-7390: In the Product Edit Form, we now keep the context of attributes filter (missing, all, level specific...)

---

CHANGELOG-2.3.md
src/Oro/Bundle/FilterBundle/Form/Type/Filter/TextFilterType.php
src/Pim/Bundle/CatalogBundle/Elasticsearch/Filter/Attribute/IdentifierFilter.php
src/Pim/Bundle/CatalogBundle/Elasticsearch/Filter/Field/IdentifierFilter.php
src/Pim/Bundle/CatalogBundle/Resources/config/query_builders.yml
src/Pim/Bundle/CatalogBundle/spec/Elasticsearch/Filter/Attribute/IdentifierFilterSpec.php
src/Pim/Bundle/CatalogBundle/spec/Elasticsearch/Filter/Field/IdentifierFilterSpec.php
src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Field/IdentifierFilterIntegration.php

Since we added a parent filter in the 2.1 version, we got the "IS EMPTY" operator on the SKU filter lin to this PR https://github.com/akeneo/pim-community-dev/pull/7312. 
This behavior was because we added the is_empty choice on the TextTypeFilter to have it on the parent filter (https://github.com/akeneo/pim-community-dev/blob/2.3/src/Oro/Bundle/FilterBundle/Form/Type/Filter/TextFilterType.php#L59). 
However, the operator choices for the parent filter are hardcoded on the frontend (https://github.com/akeneo/pim-community-dev/blob/2.3/src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filter/parent-filter.js#L13).  
So, we could remove this is_empty on the TextTypeFilter as it's not used by the parent filter on the frontend …

PIM-7345 : Remove the is_empty operator on the SKU filter

---

.ci/Jenkinsfile
.ci/builder.yaml
.gitignore
Dockerfile
composer.lock

> Thanks to @ClementGautier for his help on the edition of those files.
This PR removes the `composer.lock` file from our `.gitignore`. This way we gain time when installing the PIM.
The PR ensures **we still launch a `composer update` on our Nightly builds**, but that we use the `composer.lock` file when running tests on our PR builds.

Use & track composer.lock to speed up install time

---

.ci/Jenkinsfile

I missed to give the argument when we launch a EE build through the CE.

Add the composer command arg when running a EE build through the CE

---

CHANGELOG-2.2.md
src/Pim/Bundle/DataGridBundle/Datasource/AssociatedProductDatasource.php
src/Pim/Bundle/DataGridBundle/spec/Datasource/AssociatedProductDatasourceSpec.php

We were using the identifier filter to find associated products. If an attribute is called "identifier" the pqb was not able to know what to do. I fixed it by using Ids instead.
| Added legacy Behats               | No
| Added acceptance tests            | No
`-`: …

PIM-7438: fix usage of identifier attribute on association grid

---

CHANGELOG-2.0.md
src/Akeneo/Component/Localization/Localizer/NumberLocalizer.php
src/Akeneo/Component/Localization/spec/Localizer/NumberLocalizerSpec.php

For some locales (Swedish for instance), the minus symbol is not a `-` symbol but a `−` (yes, it's not the same character ;) ). To avoid that, we force the sign to always have the common sign `-` …

PIM-7415: Force the minus symbol for number on localization

---

CHANGELOG-2.3.md
src/Pim/Bundle/VersioningBundle/Resources/config/guessers.yml
src/Pim/Bundle/VersioningBundle/UpdateGuesser/AssociationsUpdateGuesser.php
src/Pim/Bundle/VersioningBundle/UpdateGuesser/VersionableUpdateGuesser.php
src/Pim/Bundle/VersioningBundle/spec/UpdateGuesser/AssociationsUpdateGuesserSpec.php
tests/legacy/features/mass-action/mass_associate.feature

Mass associating products does not generate versioning because the product itself is not modified. It is then not detected as changing , hence the absence of version.
With this PR, we trigger a product versionning when a ProductAssociation is updated.

PIM-7430: association versioning

---

CHANGELOG-2.0.md
src/Pim/Component/Catalog/Completeness/CompletenessGenerator.php
src/Pim/Component/Catalog/Completeness/CompletenessGeneratorInterface.php
src/Pim/Component/Catalog/Manager/CompletenessManager.php
src/Pim/Component/Catalog/spec/Manager/CompletenessManagerSpec.php

Original issue was a memory leak when exporting products.
**Before the fix PIM-7348 (https://github.com/akeneo/pim-community-dev/pull/8109):**
- we want to export products
- we trigger calculation for all products with missing completeness
- and this calculation was never saved... so it was totally useless
- this calculation load every products in memory with missing completeness (which means a potential memory leak)
The piece of responsible of it is here:
https://github.com/akeneo/pim-community-dev/blob/2.3/src/Pim/Component/Catalog/Completeness/CompletenessGenerator.php#L56
What does it mean?
It means that we never have a lot of missing completeness, or all our customers would complain about memory leak...
It means also that this …

PIM 7447: do not trigger calculation of completeness before exporting products

---

src/Pim/Bundle/ApiBundle/Controller/ProductModelController.php
src/Pim/Bundle/ApiBundle/Resources/config/checkers.yml
src/Pim/Bundle/ApiBundle/Resources/config/controllers.yml
src/Pim/Bundle/ApiBundle/Resources/config/normalizers.yml
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/AbstractProductTestCase.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/ProductModel/ListProductModelWithCompletenessIntegration.php
src/Pim/Bundle/CatalogBundle/Resources/config/query_builders.yml
src/Pim/Component/Api/Normalizer/ProductModelNormalizer.php
src/Pim/Component/Catalog/spec/Normalizer/Storage/Product/AssociationsNormalizerSpec.php

As Filips, I'd like to get a filtered list of product models
Ex : ?search={"length":[{"operator": ">","value":{"amount":"10","unit":"METER"}}]}
As Filips, I'd like to get a list of product models with filtered product values
Ex : ?channel=ecommerce
`-`: …

API-593: Add possibility to filter a list of product models in the API

---

CHANGELOG-2.2.md
src/Pim/Bundle/EnrichBundle/Doctrine/ORM/Query/CountImpactedProducts.php
src/Pim/Bundle/EnrichBundle/spec/Doctrine/ORM/Query/CountImpactedProductsSpec.php
src/Pim/Bundle/EnrichBundle/tests/integration/Doctrine/ORM/Query/CountImpactedProductsIntegration.php

When selecting "all" for bulk actions AND a filter on a parent identifier to have only the variants of a certain product model, the product count displayed in the bulk action confirmation equals 0.
This is because we don't have the `parent` field indexed in the products index and we must use the product and product model index where the field `parent` exists.
Note: we could also fix the product index, but it's less doable in a patch.
This PR uses the product and product model index and filter on product entity types to achieve the same filter result.
| Added Specs                       | Fixed …

PIM-7442: Bulk actions ALL - count not taking into account variants

---

CHANGELOG-2.0.md
src/Pim/Bundle/CatalogBundle/Doctrine/Common/Saver/ProductModelDescendantsSaver.php
src/Pim/Bundle/CatalogBundle/Resources/config/jobs.yml
src/Pim/Bundle/CatalogBundle/Resources/config/savers.yml
src/Pim/Bundle/CatalogBundle/spec/Doctrine/Common/Saver/ProductModelDescendantsSaverSpec.php
src/Pim/Component/Catalog/Job/ComputeProductModelsDescendantsTasklet.php
src/Pim/Component/Catalog/spec/Job/ComputeProductModelsDescendantsTaskletSpec.php

This PR fixes memory leak on product model descendants computation. Nothing is detached so every product and linked entities are kept in Doctrine UOW.
Tasklet does need to detach as product model descendants saver clears UOW + cached repositories.

PIM-7396: Improve performances on Compute Model Descendants

---

.gitignore
docker-compose.override.yml.dist
docker-compose.yml

This PR aims to finish the clean up the `docker-compose.yml` file on `master` branch, and keep in it only what is mandatory to have a working PIM. As the port mapping of the Apache container is mandatory, it was placed in a previous PR in a `.env.yml.dist` file that the developer needs to copy and configure first (this way, the Apache output ports can still be configured).
Every other configuration is to be placed in `docker-compose.override.yml`, at the developer's convenience. A `.dist` example is added.
If this PR is accepted, it will be ported to EE and standard editions, and documentation will be updated.
| Added acceptance …

Improve usage of docker-compose

---

CHANGELOG-2.3.md
src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/attributes.js

Until now, product and product model fields were not aware of the entity they belonged too.
With this PR, we send to the form data (meaning, the edited entity) into the field context..

PIM-7465: Set front-end entity into field context

---

CHANGELOG-1.7.md
src/Pim/Bundle/FilterBundle/Filter/CategoryFilter.php
src/Pim/Bundle/FilterBundle/spec/Filter/CategoryFilterSpec.php

PIM-7366: Avoid loading children by code then reloading all ids from the codes.
This does a little bit of cleanup as well, as we properly use the right filter's operator instead
of reinventing it.
| Added legacy Behats               | N.A.
| Added acceptance tests            | N.A.
| Added integration tests           | N.A. …

PIM-7366 Use CHILDREN operators instead of redoing it

---

.gitignore
composer.lock

We tried to add composer.lock on EE and CE but reverted them because we had some synchronization issues. But we should have kept the lock on CE because the main issues are between EE and CE.
The CI already manage the presence of the composer.lock so we can gain some time and remove some dependencies issues.

Add composer.lock and use it

---

tests/back/Acceptance/Attribute/InMemoryAttributeRepository.php
tests/back/Acceptance/spec/Attribute/InMemoryAttributeRepositorySpec.php

the findBy method in attribute repository didn't accept array for criteria filter values.

Fix memory attribute repository to support array values as filter

---

CHANGELOG-1.7.md
features/export/product-export-builder/export_products_by_families.feature
src/Pim/Bundle/VersioningBundle/Resources/config/guessers.yml
src/Pim/Bundle/VersioningBundle/UpdateGuesser/FamilyAttributeRequirementUpdateGuesser.php
src/Pim/Bundle/VersioningBundle/spec/UpdateGuesser/FamilyAttributeRequirementUpdateGuesserSpec.php
src/Pim/Component/Catalog/Updater/FamilyUpdater.php
src/Pim/Component/Catalog/spec/Updater/FamilyUpdaterSpec.php

This PR avoid generating lots of DELETE and INSERT queries by removing or adding only attributes that have been removed or added to the family at save time.

PIM-7373 Avoid deleting and reinsert all attributes relation at family save

---

CHANGELOG-1.7.md
src/Pim/Bundle/CatalogBundle/Doctrine/Common/Filter/CategoryFilter.php

The category filter checks that every single parameter provided is in the correct format. When we need to apply a filter to thousands of categories, this check is very costly especially as it's useless because we just got the category ids from the database.
A new option has been added to avoid checking type of parameters.
| Review and 2 GTM                  | WIP
| …

PIM-7461 Allow to avoid type check on category filter

---

src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/CreateVariantProductIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/PartialUpdateProductToVariantIntegration.php
src/Pim/Bundle/CatalogBundle/Resources/config/validation/product.yml
src/Pim/Bundle/CatalogBundle/tests/integration/Product/CreateVariantProductIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/Validation/OnlyExpectedAttributesValidationIntegration.php
src/Pim/Component/Catalog/Validator/Constraints/OnlyExpectedAttributes.php

There was a missing constraint on products to prevent:
- To set attributes on a product if the attribute is not in the family
- To set attributes on a variant product if the attribute is not in the attribute set (on the level)

Add constraint on products to check expected attributes

---

CHANGELOG-1.7.md
src/Pim/Bundle/EnrichBundle/Resources/public/templates/export/common/edit/meta.html

This PR fixes a bug where in the export and import profile headers the job code was shown instead of the label. 

PIM-7474: Show job profile label instead of code in the headers

---

CHANGELOG-2.0.md
src/Pim/Bundle/EnrichBundle/Resources/public/js/i18n.js

For the locales with multiples underscore like 'az_Cyrl_AZ' the flag don't appear.

PIM-7460: Fix locale flag for locales with two underscores.

---

CHANGELOG-2.2.md
features/attribute-group/create_attribute_group.feature
src/Pim/Bundle/EnrichBundle/Controller/Rest/AttributeGroupController.php
src/Pim/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev/attribute_groups.csv

When creating a new attribute group, the sort order was null (so ended by 0 in database).
Now we correctly increment the sort order on creation.
| Added legacy Behats               | Y

[SLA] PIM-7413: Newly created attribute group is correctly sorted after existing ones

---

src/Pim/Bundle/VersioningBundle/UpdateGuesser/FamilyAttributeRequirementUpdateGuesser.php
src/Pim/Bundle/VersioningBundle/spec/UpdateGuesser/FamilyAttributeRequirementUpdateGuesserSpec.php

Fixes Behat broken from PIM-7373 merge.

PIM-7373 Fixes versioning guesser when deleting family

---

CHANGELOG-2.0.md
features/export/export_products.feature
features/export/xlsx/export_products.feature
src/Pim/Component/Connector/Reader/Database/ProductReader.php

This PR fixes a bug in the product export summary where the read count was out of sync with the write count. 

PIM-7462: Fix step execution read count

---

behat.yml.dist
features/Context/FeatureContext.php
features/Pim/Behat/Context/PimContext.php
features/user/create_and_delete_user.feature

Use spin + delete dead code.
Should fix random on tests/legacy/features/user/edit_user_group_and_role_assignations.feature:33 on master

Stabilize behat by overriding method of MinkContext with spin

---

src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/fields/simple-select-async.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/label.js

Fixes an annoying case that happen often in creation mode : your model is empty so the `labels` index doesn't even exist and you get an error in `i18n.getLabel()` method.

Avoid error when no label is set

---

CHANGELOG-2.0.md
src/Pim/Component/Connector/Writer/File/AbstractItemMediaWriter.php
src/Pim/Component/Connector/spec/Writer/File/Csv/ProductWriterSpec.php
src/Pim/Component/Connector/spec/Writer/File/Xlsx/ProductWriterSpec.php

The date used to generate the names of the files of an export (the file itself and the archive) must be exactly the same to the nearest second. It was not necessarily the case because a new date is generated for each file (in a different instance of the same writer class), so the seconds could be different between the export file and the archive.
I arbitrarily chose to use the start time of the job step execution because it's the simplest solution to have the same date in the different instances of the writers. It doesn't really have any functional meanings to choose this date but the exact value itself doesn't matter as long as it indicates the time at which the export was executed. And I don't see a better way to do it without doing …

PIM-7480: Fix generation of export file name with a date

---

CHANGELOG-1.7.md
src/Pim/Bundle/EnrichBundle/Resources/views/AttributeGroup/_js-handler.html.twig

French quotes are escaped when translated.
I used the raw filter to not escape them, and added the `striptags` filter to avoid script injection in translation files.

PIM-7466: do not escape quotes for translation

---

ARCHITECTURE.md

Here the definition of each bounded context provider by our dear Product Owners.
I hope it will help people to understand better "what should go where".
(I don't know if we should those kind of files, like `STANDARD_FORMAT.md`, in a particular folder or not. Something like `reference_doc`?)

Bounded context definitions

---

CHANGELOG-2.3.md
src/Pim/Bundle/EnrichBundle/Normalizer/LocaleNormalizer.php
src/Pim/Bundle/EnrichBundle/Resources/public/templates/attribute-group/tab/attribute.html
src/Pim/Bundle/EnrichBundle/Resources/public/templates/export/product/edit/content/structure/attribute-list.html
src/Pim/Bundle/EnrichBundle/spec/Normalizer/LocaleNormalizerSpec.php

In Attribute group Edition, attributs labels translation use ui locale when we should use catlaog locale.

PIM-7488: use catalog locale for attributes list in attribute groups

---

CHANGELOG-3.0.md
UPGRADE.md
src/Oro/Bundle/DataGridBundle/Common/IterableObject.php
src/Oro/Bundle/DataGridBundle/Datagrid/Common/MetadataIterableObject.php
src/Oro/Bundle/DataGridBundle/Datagrid/Common/ResultsIterableObject.php
src/Oro/Bundle/DataGridBundle/Datagrid/Common/ResultsObject.php
src/Oro/Bundle/DataGridBundle/Datagrid/Datagrid.php
src/Oro/Bundle/DataGridBundle/Datagrid/DatagridInterface.php
src/Oro/Bundle/DataGridBundle/Extension/AbstractExtension.php
src/Oro/Bundle/DataGridBundle/Extension/Acceptor.php
src/Oro/Bundle/DataGridBundle/Extension/Action/ActionConfiguration.php
src/Oro/Bundle/DataGridBundle/Extension/Action/ActionExtension.php
src/Oro/Bundle/DataGridBundle/Extension/ExtensionVisitorInterface.php
src/Oro/Bundle/DataGridBundle/Extension/Formatter/FormatterExtension.php
src/Oro/Bundle/DataGridBundle/Extension/Formatter/Property/PropertyConfiguration.php
src/Oro/Bundle/DataGridBundle/Extension/GridViews/GridViewsExtension.php
src/Oro/Bundle/DataGridBundle/Extension/MassAction/MassActionExtension.php
src/Oro/Bundle/DataGridBundle/Extension/Pager/OrmPagerExtension.php
src/Oro/Bundle/DataGridBundle/Extension/Sorter/OrmSorterExtension.php
src/Oro/Bundle/DataGridBundle/Extension/Toolbar/ToolbarExtension.php
src/Oro/Bundle/DataGridBundle/Tests/Unit/Datagrid/DatagridTest.php
src/Oro/Bundle/DataGridBundle/Tests/Unit/Extension/AbstractExtensionTest.php
src/Oro/Bundle/DataGridBundle/Tests/Unit/Extension/AcceptorTest.php
src/Oro/Bundle/FilterBundle/Grid/Extension/OrmFilterExtension.php
src/Pim/Bundle/DataGridBundle/Extension/Filter/FilterExtension.php
src/Pim/Bundle/DataGridBundle/Extension/Pager/PagerExtension.php
src/Pim/Bundle/DataGridBundle/Extension/Sorter/SorterExtension.php

tested 2.3 with PHP 7.2, got a fatal error:
PHP Fatal error: Cannot use Oro\Bundle\DataGridBundle\Common\Object as Object because 'Object' is a special class name
this pull request is created with PHPStorm refactor function (required small manual work afterward) to prevent this issue. Was easily reproduced by simply entering product grid in admin.
Note: Feel free to prepare the PR with your own naming conventions, I simply want to show what's necessary to make the issue go away correctly.
Especially I'm not sure if MetadataObject needs to be also renamed (again - not sure about naming convention behind it, but this is what PHPStorm refactor suggested so I'm sure there's a good reason it was also renamed) …

prevent Fatal Error: Cannot use Oro\Bundle\DataGridBundle\Common\Object as Object because 'Object' is a special class name

---

CHANGELOG-1.7.md
src/Pim/Bundle/EnrichBundle/Resources/views/AttributeGroup/_js-handler.html.twig

When the traduction contains one `'` the javascript is wrecked
Using double-quotes in JS solves the issue

PIM7466: fix attribute group translation again

---

src/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/Repository/ProductRepository.php
src/Pim/Component/Catalog/Validator/Constraints/UniqueVariantAxisValidator.php

A proposition of https://akeneo.atlassian.net/browse/SDS-3526 : 
Without the fix, validators compare the product id from query (type string) with the validated product id (type object(MongoId)). Even if the value are the same, the test fail because of type and the product is not save.
This validation is made when during variant group save. When propagation are applied on product, product are validated before save. …

Cast entity id for comparaison with MongoObject

---

CHANGELOG-2.3.md
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/job_instance/csv_product_model_export_edit.yml
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/job_instance/xlsx_product_model_export_edit.yml
tests/legacy/features/export/product_model/csv/export_product_models.feature
upgrades/schema/Version_2_3_20180716135306_update_job_instances.php

The filter on the identifier for the product models exports is broken. It uses the attribute "sku" instead of the field "identifier".
I fixed the form extension configuration for the CSV and XLSX exports, and I added a migration script to fix the existing export profiles that have a filter on the attribute "sku".
| Migration …

PIM-7517: fix the product models export filter on identifier

---

CHANGELOG-2.0.md
features/locale/detach_locale_from_channel.feature
src/Pim/Bundle/CatalogBundle/Resources/config/jobs.yml
src/Pim/Bundle/EnrichBundle/Resources/translations/messages.en.yml
src/Pim/Component/Catalog/Job/ComputeCompletenessOfProductsFamilyTasklet.php
src/Pim/Component/Catalog/spec/Job/ComputeCompletenessOfProductsFamilyTaskletSpec.php

When a family is edited, if changes affect the product completeness (like adding or removing a required attribute), completeness is recalculated for all products of this family. This is done by the batch job `compute_product_models_descendants`.
There is a memory leak in this job: products are detached, but not their associations. As a consequence, the process will eventually end up out of memory and crash.
This PR uses the Doctrine cache clearer instead of the product detacher in `Pim\Component\Catalog\Job\ComputeCompletenessOfProductsFamilyTasklet` to solve this memory leak.
It was succesfully tested on a catalog that was know to have the problem. When editing a family with 200K products (containing associations), the batch job stayed under 80 MB.
I also fixed an unstable behat …

PIM-7452: Fix memory leak when reinitializing family completeness

---

src/Pim/Bundle/EnrichBundle/Resources/config/bundles/liip_imagine.yml
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/field/media-field.js
src/Pim/Bundle/UIBundle/Resources/public/less/components/TitleContainer.less

Less code to add this style to container images:
I could extract that in a dedicated component but not sure for now. What do you think? This PR improves also the thumbnail quality to comply with retina screens. …

PIM-7433: better thumbnail quality for retina and new image upload

---

CHANGELOG-1.7.md
src/Pim/Bundle/EnrichBundle/Resources/config/pim.yml

A lot of screens are using validation (grid, pef, etc...), but every time a HTTP request for those screens is made, the validation configuration is read from disk and the YML is interpreted, leading to slowness.
| Review and 2 GTM                  | WIP

PIM-7473 - Enable cache for validation mapping

---

composer.json

It has been accidentally removed here: https://github.com/akeneo/pim-community-dev/commit/72d86c77d733dd493f7ec98f92a582236f089a72#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780

Add AppKernel to the composer autoload (non dev)

---

CHANGELOG-2.3.md
src/Pim/Bundle/EnrichBundle/Controller/Rest/VersioningController.php
tests/legacy/features/product/date.feature

PIM-7528: Do not use User timezone for product/product model versionning normalization

---

CHANGELOG-2.0.md
src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/fields/simple-select-async.js

When we were creating a product model on an axis of a family variant which it's a reference-data-simple-select, we didn't have the infinite scroll pagination.

PIM-7519 : Fix Infinite scroll on the reference-data-simple-select

---

CHANGELOG-1.7.md
src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/field/boolean.html

SLA qualified as high priority  ¯\_(ツ)_/¯

PIM-7540: Fix translations of boolean attributes

---

.ci/Jenkinsfile
CHANGELOG-2.3.md
src/Pim/Bundle/EnrichBundle/Controller/CategoryTreeController.php
src/Pim/Bundle/UserBundle/EventSubscriber/UserPreferencesSubscriber.php
src/Pim/Bundle/UserBundle/spec/EventSubscriber/UserPreferencesSubscriberSpec.php

A fatal error is thrown when we want to delete a category tree because of a bad refacto :/

PIM-7529: Fix method with missing parameter when a tree is removed

---

src/Pim/Bundle/EnrichBundle/Resources/config/query_builders.yml

Tested on a catalog with 1 000 000 products and 20 000 categories.
This fix allows to have a gain of ~800 ms (from 2.5 seconds to 1.7 seconds to get data from the grid).
The PQB requests Elasticsearch 3 times for the datagrid. It's due to the batch size at 10. 
Each ES request takes more than 400 ms. 
For a total of 1.2 seconds, which is a lot. 
Batch size at 10 was done for memory leak purpose due to problems with the garbage collector and circular references during a long running batch.
It's useless for HTTP requests. 
Note: it's the same thing for the API. It's an HTTP call, so we don't care about the garbage collector.
The batch size slows down the whole API for nothing, as we don't handle memory leaks in the API.
We are currently …

PIM-7546: fix the batch size of the cursor for the datagrid

---

composer.lock
tests/front/common/base.jest.json

An dependency seems to have been updated recently and broke our front-end unit tests. This PR fixes it. Read the following discussion for a better understanding of the problem and its solution: https://github.com/jsdom/jsdom/issues/2304

Fix front unit tests

---

CHANGELOG-1.7.md
src/Oro/Bundle/UserBundle/Controller/RoleController.php
src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid/action/delete-action.js
src/Pim/Bundle/UserBundle/DependencyInjection/PimUserExtension.php
src/Pim/Bundle/UserBundle/Doctrine/ORM/Query/IsThereUserWithoutRole.php
src/Pim/Bundle/UserBundle/EventSubscriber/RemoveRoleSubscriber.php
src/Pim/Bundle/UserBundle/Resources/config/event_subscribers.yml
src/Pim/Bundle/UserBundle/Resources/config/queries.yml
src/Pim/Bundle/UserBundle/Resources/config/removers.yml
src/Pim/Bundle/UserBundle/tests/integration/RemoveRoleIntegration.php
src/Pim/Component/User/Exception/ForbiddenToRemoveRoleException.php

Forbid to remove a role if a user won't have role after deletion. 
A user without role has no sense on the PIM. 
Moreover, there is a little thing "funny" on the PIM: if a user without role want to connect to the PIM, the application will try to find the role "ROLE_USER" which is a role defined as a default role (don't ask me why...) and then update the user to associated him to "ROLE_USER" role. That's mean a user without role can have much more access than before to the PIM after an authentification \o/
| Added acceptance …

PIM-7453: forbid to remove a role if user won't have role after deletion

---

CHANGELOG-1.7.md
features/product/filtering/filter_products.feature
src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid/action/reset-collection-action.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/grid/view-selector.js

This PR fixes an issue for the reset collection action in the datagrid. Currently, we store the initial state of the filters, and when we click reset, we revert to those filters. 
If we set the family to e.g. 'Accessories' and then change to another page, if we come back to the grid and click reset, it doesn't remove 'Accessories' because the initial state now includes this filter. This behaviour is a bug and it also happens when the user has a view selected.  
To fix this issue - first for the default view I updated the reset-collection-action to correctly reset the state using `initialState` instead of `_initState`. For a selected view, we now store the initial view filters so that when the user clicks reset we can revert to them. …

[SLA] PIM-7538: Reset datagrid state correctly

---

CHANGELOG-2.3.md
src/Pim/Bundle/UserBundle/Resources/config/datagrid/user.yml

This PR is a rework of https://github.com/akeneo/pim-community-dev/pull/8579 to rebase and update the changelog. 

GITHUB-8578 - Fixed wrong labels displayed in the 'active/inactive' filters in user grid

---

CHANGELOG-2.2.md
src/Pim/Bundle/CatalogBundle/Doctrine/Common/Saver/ProductModelDescendantsSaver.php
src/Pim/Bundle/CatalogBundle/Doctrine/ORM/CompletenessRemover.php
src/Pim/Bundle/CatalogBundle/spec/Doctrine/Common/Saver/ProductModelDescendantsSaverSpec.php
src/Pim/Bundle/CatalogBundle/spec/Doctrine/ORM/CompletenessRemoverSpec.php
src/Pim/Component/Catalog/Completeness/CompletenessRemoverInterface.php
src/Pim/Component/Catalog/Manager/CompletenessManager.php
src/Pim/Component/Catalog/spec/Manager/CompletenessManagerSpec.php

The first focus has been to find on which step the "compute product models descendants" was slower.
**73% of the time was about indexing**. 
I took a look at a PR @BitOne did on October 2017: https://github.com/akeneo/pim-community-dev/pull/7074. His PR was taking profit of the `index_refresh` option given to the indexer. 
> The refresh strategy is now at disable, relying on the standard refreshing feature of Elasticsearch without waiting for it to take effect, cf https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-refresh.html
So I tried to apply the same option when indexing products & product models in the step. The result is immediate:
**Time of the "compute product models descendants" step** _(tested on the staging …

[SLA] PIM-7531: improve indexation time for "compute product models descendants" step

---

CHANGELOG-2.3.md
src/Pim/Bundle/ApiBundle/Controller/ProductController.php
src/Pim/Bundle/ApiBundle/Controller/ProductModelController.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/SuccessListProductIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/SuccessListVariantProductDeltaIntegration.php
tests/back/Integration/IntegrationTestsBundle/Sanitizer/DateSanitizer.php

For date manipulations, we only deal with UTC timezone.
As the documention of the API says, when filtered search on "created" or "updated" properties are done within the API, the date values are intended to be on the timezone of the server configuration. (see [ON CREATION OR UPDATE DATE](https://api.akeneo.com/documentation/filter.html#on-creation-or-update-date-2) filter api documentation).
As the date provided in the search criteria do not handle the timezone modifier (not a ISO format with the +/- hours) we force the date value to be considered as a DateTime object that will be created with the default date.timezone value of the server.
| …

Pim 7541 - Fix timezone settings for API requests

---

CHANGELOG-2.0.md
src/Pim/Bundle/EnrichBundle/Provider/StructureVersion/StructureVersionProvider.php
src/Pim/Bundle/EnrichBundle/spec/Provider/StructureVersion/StructureVersionProviderSpec.php
src/Pim/Bundle/VersioningBundle/Doctrine/ORM/VersionRepository.php
src/Pim/Bundle/VersioningBundle/Repository/VersionRepositoryInterface.php

With too many versions in `pim_versioning_version` table, the query was too slow and broke the PEF (`getNewestLogEntryForRessources()` is only called in it).
FYI, we could only reproduce the bug with a custo on category (the client overidden the table)
| Tech Doc …

PIM-7559: Fix versionning query too slow on the PEF

---

CHANGELOG-2.3.md
src/Pim/Bundle/UIBundle/Resources/views/Form/pim-fields.html.twig

Since we don't use jQuery on the old login pages anymore when the reset password form was validated it threw an error. This PR updates the old twig to use pure js to trigger the form change instead. 
`OK`: Done / …

PIM-7537: Use pure JS for reset password trigger form change

---

CHANGELOG-2.3.md
src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filter/text-filter.js
src/Pim/Bundle/UIBundle/Resources/public/less/components/grid/FilterBox.less

This PR fixes a display issue when filtering with many SKUs on the group grid 
Before
After

PIM-7552: Fix sku filter display bug

---

CHANGELOG-2.3.md
src/Pim/Bundle/CatalogBundle/Resources/config/validation/attribute.yml

When you set 'label' as code, it raises some bugs on the datagrid because the 'label' attribute is generated automatically.
You can not, for example, use the filters on the "label" field.

PIM-7543: Forbid usage of 'label' code for attributes to prevent UI bugs

---

CHANGELOG-2.3.md
app/config/security.yml
src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid/widget/export-widget.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/grid.js

This PR fixes the fact that the user is not redirected to the login page automatically when the session timed out.
There is no tests because the behavior is untestable on the CI, but it works by putting the `gc_maxlifetime` to a little value (like 10s)

PIM-7545: Redirect to login page when user is not authenticated anymore

---

CHANGELOG-2.3.md
src/Pim/Bundle/DataGridBundle/Resources/config/controllers.yml
src/Pim/Bundle/DataGridBundle/Resources/config/routing/datagrid_view.yml
src/Pim/Bundle/EnrichBundle/Resources/public/js/grid/view-selector.js

When the user create more than 20 views, he can not access to the "load more" select2 feature.
Why ? Because there was a test saying "if there is 20 results from the back, please show the "load more"". But there is a function it automatically adds the default view to this list... So the results are 21, and it always fail.
Now, it did the test of 20 === 20 before adding the default view.
I use this PR to better format the file, and to remove a useless route (not used in EE too)
I can not add a test because we don't have any methods to scroll down into a select2. If you want me to add this one, I can try to make something.
| Added …

 PIM-7569: Fix limit of 20 results for view selector

---

CHANGELOG-2.3.md
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/PartialUpdateVariantProductIntegration.php
src/Pim/Component/Catalog/EntityWithFamilyVariant/KeepOnlyValuesForVariation.php
src/Pim/Component/Catalog/Model/AbstractValue.php
src/Pim/Component/Catalog/spec/EntityWithFamilyVariant/KeepOnlyValuesForVariationSpec.php

In some cases, using loose comparison (`==`) can result in a `nesting level too deep - recursive dependency ?` fatal error when working on large collections, especially if you're comparing objects.
It can also happen with `in_array()` without the strict flag.
This error occurred at two places :
- In `Pim\Component\Catalog\EntityWithFamilyVariant\KeepOnlyValuesForVariation::updateEntitiesWithFamilyVariant()`
Solution : stop comparing objects and compare codes instead (it's lighter). We don't need to compare full objects in this case.
- In `Pim\Component\Catalog\Model\AbstractValue::isEqual()`
This one is trickier. I rolled back a change made in [this PR](https://github.com/akeneo/pim-community-dev/pull/6430/files#diff-a11e715648fb0a71e3f5 …

[SLA] PIM-7573: Fix "nesting level too deep" error during family import

---

CHANGELOG-2.3.md
src/Pim/Bundle/EnrichBundle/ProductQueryBuilder/ProductAndProductModelQueryBuilder.php
src/Pim/Bundle/EnrichBundle/spec/ProductQueryBuilder/ProductAndProductModelQueryBuilderSpec.php
tests/legacy/features/Context/Page/Base/Grid.php

**Context:**
Following the wonderful work made by @ahocquard https://github.com/akeneo/pim-community-dev/pull/8312 on improving the
scalability of the search on categories, the "aggregated" search of
product models with categories was not working properly.
**Problem:**
In his refactoring, he introduces a new way to filter on categories on
the product grid. Before his changes when a user would select a category
in the category tree with the "include children" flag set to "yes". The
whole list of categories would be passed on to the back-end (category
selected + children) instead of using the IN_CHILDREN operator available
with the category filter.
@ahocquard fixes does just that, it uses the IN_CHILDREN operator
instead of the IN_LIST with a big list of category codes.
**Solution:**
Make …

PIM-7509: Fix search on categories with product models

---

src/Pim/Bundle/ApiBundle/Resources/config/checkers.yml

With the fix done on  EE : https://github.com/akeneo/pim-enterprise-dev/pull/4402 The service `pim_api.checker.query_parameters` has become useless.
I existed only for the EE (see #8347 )

PIM-7563: remove unused generic checker service

---

CHANGELOG-2.0.md
src/Pim/Component/Connector/Writer/File/AbstractFileWriter.php
src/Pim/Component/Connector/spec/Writer/File/Csv/WriterSpec.php
src/Pim/Component/Connector/spec/Writer/File/Xlsx/WriterSpec.php

Same fix than https://github.com/akeneo/pim-community-dev/pull/8432.

PIM-7574: Use step start time to name exported files instead of current time

---

src/Pim/Component/Catalog/Validator/Constraints/LocaleValidator.php
src/Pim/Component/Catalog/spec/Validator/Constraints/LocaleValidatorSpec.php

On the onboarder, we have acceptance tests failing if value is null.

Do not try to validate a locale if value is null

---

tests/legacy/features/attribute-group/display_attribute_group_history.feature
tests/legacy/features/versioning/ensure_versioning_on_attribute_group.feature

On this EE PR (https://github.com/akeneo/pim-enterprise-dev/pull/4406) we add the versioning on the rights property (EE only feature). Problem is that it will change the result of those scenario if they are run on a EE build (more versions, different properties, etc).
I don't think we should duplicate those scenarios in EE just to check that the rights are well versioned (it's not a critical use case).
No ci will run on this PR of course
| …

PIM-7568: remove scenario from ee build

---

src/Pim/Bundle/EnrichBundle/Resources/public/js/product/grid/category-switcher.js

Needs for the EE. When a user has no permission on any categories, we want to hide the category filter.
If you have permission on at least one category, the label will always be filled (even if there is no translation, the code will be the label).
The only way to have an empty label is when you don't have permission or if there is no category.
I don't find a better way to do that, if it's not GTM, I will need a frontend dev.
| Changelog …

PIM-7586: do not show category switcher when there is no label

---

CHANGELOG-2.0.md
src/Pim/Bundle/EnrichBundle/Resources/config/requirejs.yml
src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/attributes/attribute-group-selector.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/mass-edit/form/product/edit-common-attributes.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/mass-edit/attributes.js
src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/form/mass-edit/attributes.html
src/Pim/Bundle/UIBundle/Resources/public/less/components/button/ButtonList.less

In the mass edit, when no attribute is chosen yet the filter is useless, so it shouldn't be displayed.
Also transform this :
into this :

PIM-7557: Don't display attribute group filter if there is no choices

---

CHANGELOG-2.3.md
src/Pim/Bundle/EnrichBundle/Normalizer/ProductNormalizer.php
src/Pim/Bundle/EnrichBundle/Resources/config/normalizers.yml
src/Pim/Bundle/EnrichBundle/spec/Normalizer/ProductNormalizerSpec.php

We got an SLA because the UI locale was used instead of the Catalog locale to normalize the image from a localizable asset when we save the product.

PIM-7414 : Use catalog locale to normalize the image when we save the product

---

CHANGELOG-2.3.md
src/Akeneo/Bundle/ElasticsearchBundle/Command/ResetIndexesCommand.php

Allows to use the command with the --no-interaction parameter

PIM-7600: change the default return value to true of ResetIndexesCommand

---

CHANGELOG-2.0.md
src/Pim/Bundle/EnrichBundle/Resources/config/acl.yml
src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/family_variant.yml
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/family/edit.yml
src/Pim/Bundle/EnrichBundle/Resources/translations/messages.en.yml

An Acl was missing for manage family variant (add/edit), so with only List families permissions you could edit a family variant

PIM-7595: Add missing acl on family variant managment

---

tests/legacy/features/Context/Page/Product/Edit.php
tests/legacy/features/Context/WebUser.php

This PR updates a Behat step. This step is used in one EE scenario to check if the status switcher available in the PEF is hidden as it should be with a particular permission setting.
Problem is, we just introduced a new status switcher on the PEF, in EE only, and as the behat step was using the component class to detect the button, the scenario failed because it couldn't make the difference between the 2 switchers.
This PR fixes the issue by detecting the switcher using a CSS class specific to the product status switcher, instead of a generic one.
This behat step is quite bad in fact. If you try to see if the switcher is visible, everything's fine. But if, like in the EE scenario that was failing, you try to see if it is **not** visible, then you have to wait for the end of the spin, …

APAI-142: Detect only product status switcher

---

CHANGELOG-2.3.md
src/Pim/Bundle/UserBundle/Command/CreateUserCommand.php

This is an interactive SF command allowing to easily create a PIM user.
At first I needed to be able to create a user without the help of the usual form because when the LDAP bundle is installed the password field is hidden on purpose (since password are not managed by the PIM). But I still wanted to be able to set it, because it's needed for the API authentication, so the command was a reasonable solution.
Another solution would have been to flag the LDAP users in database and change the form behavior but we decided that modifying the schema was a bit heavy for such a small use case. Plus the command can be used for other cases.
| …

[SLA] PIM-7610: Add a command to create users

---

CHANGELOG-2.3.md
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/common/menu.yml

Remove 'Process tracker' link on the dashboard when user has no "View process tracker" permission

PIM-7618: Hide the dashboard "Process tracker" link if no permission

---

CHANGELOG-2.3.md
src/Pim/Bundle/EnrichBundle/Resources/public/js/common/column-list-view.js

The "System" pseudo attribute group had a 0 index, which could mess up the attribute groups display order in the columns configurator in case of an attribute group with sortOrder = 0.

PIM-7626: Fix attribute groups order in the product grid's column configurator

---

CHANGELOG-2.3.md
src/Pim/Bundle/ApiBundle/Controller/ProductController.php
src/Pim/Bundle/ApiBundle/Controller/ProductModelController.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/SuccessListProductIntegration.php

`url/api/rest/v1/product-models?limit=100&pagination_type=search_after&search={"updated":[
{"operator":"BETWEEN","value": ["2018-08-26 22:40:10","2018-08-26 23:40:10"]}]}`
Got this error 
`2018-08-27 00:18:51 request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: DateTime::createFromFormat() expects parameter 2 to be string, array given" at /home/akeneo/releases/20180824090748/akeneo/vendor/akeneo/pim-community-dev/src/Pim/Bundle/ApiBundle/Controller/ProductModelController.php line 647` …

PIM-7631: Fix API filter product and product model on date with between operator

---

CHANGELOG-2.3.md
src/Oro/Bundle/FilterBundle/Filter/StringFilter.php
src/Oro/Bundle/FilterBundle/spec/Filter/ChoiceFilterSpec.php
src/Oro/Bundle/FilterBundle/spec/Filter/StringFilterSpec.php

This PR allows to handle the `is empty` and `is not empty` operators in the StringFilter, thus fixing the "Description" filter on the assets grid

PIM-7609: Handle 'empty' and 'not empty' filter types in string filter

---

.ci/Jenkinsfile
composer.lock
src/Akeneo/Pim/Enrichment/Bundle/tests/Integration/Doctrine/Common/Saver/ProductSaverIntegration.php
src/Akeneo/Pim/Enrichment/Component/tests/integration/Normalizer/Indexing/ProductAndProductModelIndexingIntegration.php
src/Akeneo/Pim/Enrichment/Component/tests/integration/Normalizer/Indexing/ProductIndexingIntegration.php
src/Akeneo/Pim/Enrichment/Component/tests/integration/Normalizer/Standard/ProductStandardIntegration.php
src/Akeneo/Pim/Enrichment/Component/tests/integration/Normalizer/Storage/EntityWithValuesStorageIntegration.php
src/Akeneo/Tool/Bundle/ApiBundle/tests/integration/Controller/Product/CreateProductIntegration.php
src/Akeneo/Tool/Bundle/ApiBundle/tests/integration/Controller/Product/GetProductIntegration.php
src/Akeneo/Tool/Bundle/ApiBundle/tests/integration/Controller/Product/GetVariantProductIntegration.php
src/Akeneo/Tool/Bundle/ApiBundle/tests/integration/Controller/Product/PartialUpdateProductToVariantIntegration.php
src/Akeneo/Tool/Bundle/ApiBundle/tests/integration/Controller/ProductModel/CreateProductModelIntegration.php
src/Akeneo/Tool/Bundle/ApiBundle/tests/integration/Controller/ProductModel/GetProductModelIntegration.php
src/Akeneo/Tool/Bundle/ApiBundle/tests/integration/Controller/ProductModel/ListOffsetProductModelIntegration.php
src/Akeneo/Tool/Bundle/ApiBundle/tests/integration/Controller/ProductModel/PartialUpdateListProductModelIntegration.php
src/Akeneo/Tool/Bundle/ApiBundle/tests/integration/Controller/ProductModel/PartialUpdateProductModelIntegration.php
src/Akeneo/Tool/Component/Api/tests/integration/Normalizer/ProductNormalizerIntegration.php

There was an issue with the last pull-up, we messed things on the namespace of a class used in integration tests.
This PR fixes the issue, and fix the new branch `2.x` of the `jenkins-k8s-utils` library in the Jenkinsfile.

Fix wrong namespace in integration tests

---

CHANGELOG-2.3.md
composer.lock
src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filter/choice-filter.js

The identifier filter "SKU" on the product grid is not initialized properly. Its default operator "in list" should present a multi-input , but it is initialized as a simple string filter. So it is impossible to input several product identifiers.
This PR extracts the initialization into dedicated private methods, so they can be called when switching operator (which already work) and at first rendering too (which didn't work before). …

PIM-7628: Fix identifier filter initialization

---

CHANGELOG-2.3.md
src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Repository/FamilyRepository.php
src/Pim/Bundle/EnrichBundle/Doctrine/ORM/Repository/FamilySearchableRepository.php
src/Pim/Bundle/EnrichBundle/Doctrine/ORM/Repository/FamilyVariantSearchableRepository.php
src/Pim/Bundle/EnrichBundle/tests/integration/Repository/FamilySearchableRepositoryIntegration.php
src/Pim/Bundle/EnrichBundle/tests/integration/Repository/FamilyVariantSearchableRepositoryIntegration.php

This PR allows the user to search for families and family variants on their code and translation labels, regardless of the current locale.
These searches are used by autocomplete selects, mainly in the enrichment context (product grid filters, product/product model creation modals, product mass actions)
| Tech Doc …

PIM-7484: Search families and family variants regardless of the current locale

---

CHANGELOG-2.3.md
src/Pim/Bundle/EnrichBundle/Controller/FileController.php
src/Pim/Bundle/EnrichBundle/Resources/config/routing/media.yml

**Problem**
On a scalable frontend architecture some image were not delivered properly to the browser that requested the media.
You may have the choice to share the `web/media/cache` folder across several frontend (with whatever shared storage technology (nfs, glusterfs, ...)) but in our case we want each frontend server to have it's own cache.
**Actual behavior**
The true image file is generated on demand with a specific route that handle the image resizing, the storage on `web/media/cache` folder and the response is a http redirect to the real resource.
The following request: `media/show/xxx.jpg/thumbnail_small` (R1) will redirect to `media/cache/thumbnail_small/xxx.jpg` (R2)
In a scalable architecture with :
- a load balancing …

PIM-7612 allow scalable frontend architecture for media content delivery

---

.ci/Jenkinsfile
CHANGELOG-2.3.md
src/Akeneo/Bundle/ElasticsearchBundle/IndexConfiguration/Loader.php

**The problem**
ElasticSearch config is not currently overridable. As contrary to what is said in https://docs.akeneo.com/2.3/maintain_pim/common_issues/index.html#the-limit-of-total-fields-is-reached-in-elasticsearch, it's not currently possible to change the total_fields.limit value.
The problem comes from the use of `array_merge_recursive` with associative arrays. Instead of overriding the first array entry with the second, instead it will create an array containing both values.
Per the [doc](http://php.net/manual/fr/function.array-merge-recursive.php)
> If the input arrays have the same string keys, then the values for these keys are merged together into an array, and this is done recursively
**The solution**
By using `array_replace_recursive`, the config keys are replace and the …

PIM-7635: fix elasticsearch config override

---

src/Pim/Bundle/ApiBundle/tests/integration/Controller/ProductModel/ListOffsetProductModelIntegration.php

One of the integration tests is way too long to execute (almost 2 minutes) and do not work anymore with the new CI settings. This PR diminish the number of product models generated (10001 were generated when 201 is enough).

Fix integration test too long to execute

---

CHANGELOG-2.3.md
src/Pim/Bundle/VersioningBundle/Doctrine/ORM/VersionRepository.php
src/Pim/Bundle/VersioningBundle/Purger/VersionPurger.php
src/Pim/Bundle/VersioningBundle/Repository/VersionRepositoryInterface.php
src/Pim/Bundle/VersioningBundle/Resources/config/repositories.yml

In 1.7 we remove Akeneo cursor from purge command to put doctrine Paginator (by the way it is not an iterrator)
So put cursor back instead of doctrine Paginator who load all data and memory leak occurs
`OK`: Done / …

PIM-7594: Put cursor back instead of doctrine Paginator who load all data and memory leak occurs

---

CHANGELOG-2.0.md
src/Pim/Bundle/EnrichBundle/Connector/Writer/MassEdit/ProductAndProductModelWriter.php
src/Pim/Bundle/EnrichBundle/Resources/config/writers.yml

**Problem**
When edit an attribute that is at product model level on a bulk action, the completeness of the descendants is not computed.
There is a subscriber that handle the completeness computation asynchronously (add a job in the queue) but if its not a "unitary" saved entity its skip the computation. As we are in a bulk action, it's not unitary. 
This check is certainly due to performance needs and i don't think that we have to remove it.
**Solution**
On the bulk action product and product model writer step, if there is product models, i add a job in the queue with all the product models to compute.
| …

Pim 7637 Completeness not calculated on variant products after bulk action edition on attributes

---

src/Pim/Bundle/UserBundle/EventListener/CreateSystemUserForCommandsListener.php
src/Pim/Bundle/UserBundle/Resources/config/event_subscribers.yml
src/Pim/Bundle/UserBundle/Security/SystemUserToken.php

**Why ?**
To run system commands (especially installer commands) and still be able to use permissions, we create a system user on-the-fly and set it in a `UsernamePasswordToken`.
The problem is that the `UsernamePasswordToken` is only supported by the `DaoAuthenticationProvider`. This provider is loaded only when a `login_form` is declared in a security firewall, so we coupled two things completely unrelated. And when we want to use a different firewall configuration, the installer is broken.
**Solution**
Use a dedicated token for the system user, and since it's authenticated by default there is no need for an authentication provider (nor a firewall listener).
| Q …

Use a dedicated system user token instead of UsernamePasswordToken for commands

---

CHANGELOG-3.0.md
src/Pim/Bundle/DataGridBundle/Resources/public/js/fetcher/datagrid-view-fetcher.js

- Cache default/default column requests - saves ~250ms
Fixes PIM-7505 PIM-7506

PIM-7506: Cache default column/views requests on the datagrid

---

src/Akeneo/Platform/Bundle/InstallerBundle/Command/DatabaseCommand.php
src/Akeneo/Platform/Bundle/InstallerBundle/Event/InstallerEvent.php
src/Akeneo/Platform/spec/Bundle/InstallerBundle/Event/InstallerEventSpec.php

Creates a dedicated `InstallerEvent` dispatched during installation. It extends `GenericEvent` (that were formerly dispatched) in order to avoid BC breaks, and holds a CommandExecutor, so that listeners/subscribers can launch commands using the same output as the original command.
| …

Create a dedicated InstallerEvent

---

CHANGELOG-2.3.md
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/field/multi-select-field.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/field/simple-select-field.js

The issue is:
- Create a simple/multi ref data
- Do all the stuff to display it in the PEF
- Select a value on the field
- Change locale
- It does not change the value according to the locale.
The bug is:
There is a cache to do not execute the query if it is already done previously. But this query is not re-executed even if the URL has changed. And on the case of the Ref Data, the URL changes to include dataLocale=xx_xx in it.
The fix is:
I added a condition to clear the promise cache if the URL change. …

[PIM-7598] Fix locale change on reference data on simple and multi select

---

CHANGELOG-2.3.md
src/Pim/Bundle/EnrichBundle/Resources/public/js/filter/product/completeness.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/job/product/edit/content/data.js
src/Pim/Bundle/InstallerBundle/Resources/fixtures/icecat_demo_dev/jobs.yml
tests/legacy/features/Context/catalog/apparel/jobs.yml
tests/legacy/features/Context/catalog/catalog_modeling/jobs.yml
tests/legacy/features/Context/catalog/footwear/jobs.yml

This PR fixes 2 issues:
- First issue is that the Product exports (CSV/XLSX) were not initialized with the right values (the values it can be set by UI)
- Second issue is that the history adds lines even if the user does nothing because the `configuration` is a JSON and the order of its components changes.
So this PR fix it with:
- addition of the missing locales in the completeness. If the completeness is set to "Complete on at least one selected locale", it should set the context-locales to the current locales (fr, en, de).
- update the code it updates the `configuration` field to keep the order of the fields.
| Added …

PIM-7647: Export products various errors

---

CHANGELOG-2.3.md
src/Pim/Bundle/UIBundle/Resources/public/lib/slimbox2/slimbox2.js

Slimbox has a known bug (found a lot of times in Google), when images are larger than the screen.
I show a lot of crappy solutions, the less crappy I found was this one.
It checks the height/width of the window before open the image.
And no, it can be done with full CSS, even using `!important`, because of the animation of it :(
I directly updated the library file. If you have better solutions, I'm all ears.
| Micro Demo …

[PIM-7648] Fix slimbox for big images

---

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/LoadingMask.less
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/QuickEdit.less
webpack/config-loader.js

Most of the time, when we do a registry in front (for fetchers or controller) we pass path to the module and then the module require them with `require`
problem with this solution is that `require` is async
So here is a small PR to add a "symfony like" service system that replace any `@my/module/path` by `require('my/module/path')`
what's cool is that, it doesn't make the code bigger, it is totally retro compatible with our current code (and integrator's one) and allow us to remove all those async requires
Allow to define require in the requirejs conf to be able to synchronously require modules by configuration an ease the creation of registries
| …

PIM-7560: add require in conf

---

CHANGELOG-2.3.md

PIM-7484 was in 2.3.6 instead of 2.3.7

Move PIM-7484 to 2.3.7 patch

---

CHANGELOG-2.3.md
src/Pim/Bundle/CatalogBundle/Elasticsearch/Filter/Field/Product/CompletenessFilter.php
src/Pim/Bundle/CatalogBundle/spec/Elasticsearch/Filter/Field/Product/CompletenessFilterSpec.php
src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Field/Product/CompletenessFilterIntegration.php
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/filters.yml
src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml

In the product export builder, we can choose what kind of completeness we want, and one of them is "Complete on at least one locale" with the operator `>=` which is a mistake because this operator checks the completeness for all activated locales. 
That's mean if you configure your export builder to export only products completed on the locale `de_DE`, if your product is completed on the locale `fr_FR`, it will be exported.
I changed this operator to `GREATER_OR_EQUALS_THAN_ON_AT_LEAST_ONE_LOCALE` and changed the pqb to be able to add multiple locales (it's validated by PO).
| Added Specs …

PIM-7653: Fix product export builder when completeness should export products complete on at least one locale

---

CHANGELOG-2.3.md
src/Pim/Bundle/CatalogBundle/Resources/config/serializers_standard.yml
src/Pim/Component/Catalog/Normalizer/Standard/TranslationNormalizer.php
src/Pim/Component/Catalog/spec/Normalizer/Standard/TranslationNormalizerSpec.php
tests/legacy/features/export/export_channels.feature
tests/legacy/features/import/import_channels.feature

All is in title, if a locale is disabled, we do not expose it in the standard format (so in UI, API, export).

[SLA] PIM-7658: do not expose disabled locale

---

src/Akeneo/Pim/Enrichment/Bundle/Command/IndexProductCommand.php
src/Akeneo/Pim/Enrichment/Bundle/Command/IndexProductModelCommand.php
src/Akeneo/Pim/Enrichment/Bundle/spec/Command/IndexProductCommandSpec.php
src/Akeneo/Pim/Enrichment/Bundle/spec/Command/IndexProductModelCommandSpec.php

Progress status of indexation commands is very annoying, let's get some eye candy for DevOps guys
```
$ bin/console -e=prod pim:product:index --all
133492 products to index
14300/133492 [==>-------------------------]  10%
```
```
$ bin/console -e=prod pim:product-model:index --all
68279 product models to index
6900/68279 [>---------------------------]  10%
```

Add ProgressBar component in indexer commands

---

bin/check-pullup
src/Oro/Bundle/PimDataGridBundle/Resources/config/data_sources.yml
src/Oro/Bundle/PimDataGridBundle/Resources/config/extensions.yml
src/Oro/Bundle/PimDataGridBundle/Resources/config/mass_actions.yml
src/Oro/Bundle/PimDataGridBundle/Resources/config/pagers.yml
src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/product.yml
src/Pim/Bundle/EnrichBundle/Resources/config/requirejs.yml
src/Pim/Bundle/EnrichBundle/Resources/public/js/controller/mass-edit.js

> Isn't it dirty (or at least weird) to add some Enterprise Edition related parameters in the datagrid services?
Yes it is. But decoupling those services per context isn't possible because of the grid architecture. Overriding those services (like it was before this PR) is not acceptable : we want to get rid of the Datagrid Bundle override and enforce context decoupling. So here is the last solution. Please note that the _PimDataGridBundle_ is considered as technical debt.
Let's take example of the `pim_datagrid.extension.pager.pager_resolver` service. The logic is more or less the same for the other services. This service is overridden in Enterprise Edition for adding the grids `published-product-grid` and `proposal-grid`.
My first wish was to create a pager service per context:
- pager A …

TIP-873: remove EE datagrid bundle

---

CHANGELOG-2.3.md
src/Pim/Bundle/EnrichBundle/Controller/Rest/ProductController.php
src/Pim/Bundle/EnrichBundle/Controller/Rest/ProductModelController.php
src/Pim/Bundle/EnrichBundle/Resources/config/controllers.yml
src/Pim/Bundle/EnrichBundle/Resources/config/filters.yml

01.	Logged in as Admin, select a product model in the grid 
02. In another browser, logged in as Mary, select a product variant from the product model selected by Admin. 
03. With Admin, edit any product model attributes, SAVE. 
04. With Mary, any product variant attribute, SAVE. 
05. It fails.
The error is due to the fact that we don't filter product values coming from the parent.
As in the import or in the API, we have to filter it.
I reproduced it also with a product model and its parent.
Note: As it's about concurrency, it is not testable (and I think it would be overkill to do that).
Note 2: 
I check in the backend if it's a creation of a product or an update by checking if the product has an id or not.
I do it because when …

PIM-7652: Fix concurrent edition with the parent of a product or a product model in the UI

---

CHANGELOG-2.3.md
src/Pim/Bundle/EnrichBundle/Doctrine/ORM/Repository/FamilySearchableRepository.php
src/Pim/Bundle/EnrichBundle/tests/integration/Repository/FamilySearchableRepositoryIntegration.php

We got an SLA about the search on the families. When we're searching on the family with a limit of element, we couldn't get all the results expected if it has a family with the same translated label on different locales.
For instance : 
- Two families : 
{ code : accessories, label : {'en_US': 'Accessories', 'fr_FR': 'Accessories', 'fr_BE': 'Accessories'}}
{ code : clothing, label : {'en_US': 'Clothes', 'fr_FR': 'Vêtement'}}
- we want to make a search on 'c' with a limit of 3 elements
- we will get only one result (Accessories) instead of two (Accessories and Clothes)
This bug is because of we didn't do a DISTINCT on the query to get only one row by label matched with the search parameter. …

PIM-7659: Fix search on the families to get one result by label

---

CHANGELOG-3.0.md
UPGRADE.md
src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/EventListener/InstallDatabase.php
src/Akeneo/Platform/Bundle/InstallerBundle/Command/DatabaseCommand.php
src/Akeneo/Platform/CommunityRequirements.php
src/Akeneo/Platform/Requirement.php
src/Akeneo/Tool/Bundle/StorageUtilsBundle/tests/integration/Utf8mb4SupportIntegrationTest.php
src/Pim/Bundle/EnrichBundle/Resources/config/bundles/doctrine.yml
src/Pim/Bundle/EnrichBundle/StructureVersion/EventListener/TableCreator.php
upgrades/schema/Version_3_0_20180823184342_switch_to_utf8mb4.php

This PR changes the default charset from utf8 to utf8mb4, allowing support for more UTF8 characters. 
| Added acceptance tests            | Done

TIP-879 Uses utf8mb4 instead of MySQL flawed utf8

---

composer.json
composer.lock

Now that we are using PHP 7.2, we need to update the monolog bundle version to fix a countable issue.
See here for more details: https://github.com/symfony/monolog-bundle/issues/223

Bump Symfony monolog bundle version to 3.1.2 for PHP 7.2

---

CHANGELOG-2.3.md
src/Pim/Bundle/CatalogBundle/tests/integration/PQB/ProductAndProductModelQueryBuilderIntegration.php
src/Pim/Bundle/EnrichBundle/ProductQueryBuilder/ProductAndProductModelQueryBuilder.php
src/Pim/Bundle/EnrichBundle/ProductQueryBuilder/ProductAndProductModelQueryBuilderFactory.php
src/Pim/Bundle/EnrichBundle/ProductQueryBuilder/ProductAndProductModelSearchAggregator.php
src/Pim/Bundle/EnrichBundle/Resources/config/query_builders.yml
src/Pim/Bundle/EnrichBundle/spec/ProductQueryBuilder/ProductAndProductModelQueryBuilderFactorySpec.php
src/Pim/Bundle/EnrichBundle/spec/ProductQueryBuilder/ProductAndProductModelQueryBuilderSpec.php
src/Pim/Bundle/EnrichBundle/spec/ProductQueryBuilder/ProductAndProductModelSearchAggregatorSpec.php

Refactor the way we aggregate ES search results for datagrid, introduce a ProductAndProductModelSearchAggregator.
This aggregator adds all the necessary clauses to remove children when a parent is displayed in search results.
Example:
Model -> in category "headphone"
Variant -> parent "model" -> herited of his parent
When you search on "Audio and video" subcategory, (parent of Headphone), both model & variant appear. …

PIM-7629: Refactor the way we aggregate ES search results for datagrid

---

CHANGELOG-2.3.md
src/Pim/Bundle/EnrichBundle/ProductQueryBuilder/ProductAndProductModelQueryBuilder.php
src/Pim/Bundle/EnrichBundle/spec/ProductQueryBuilder/ProductAndProductModelQueryBuilderSpec.php

The product grid does not display product variants when filtering on groups. 
The filter that exclude products having a parent in the PQB must not be added when filtering on groups.
`-`: …

PIM-7619: Fix search on groups for the variant products

---

CHANGELOG-2.3.md
src/Pim/Bundle/DataGridBundle/Datasource/AssociatedProductDatasource.php
src/Pim/Bundle/DataGridBundle/spec/Datasource/AssociatedProductDatasourceSpec.php

We got an SLA on the associated product list. We couldn't display the list when the product limit on the page is already reached before to get the product models associated.

PIM-7671 : Fix display associated products even if the product limit is reached before to display the product models on the page.

---

CHANGELOG-2.3.md
composer.lock
src/Pim/Bundle/EnrichBundle/Controller/Rest/JobExecutionController.php
src/Pim/Bundle/EnrichBundle/Normalizer/JobExecutionNormalizer.php
src/Pim/Bundle/EnrichBundle/Normalizer/VersionNormalizer.php
src/Pim/Bundle/EnrichBundle/Resources/config/controllers.yml
src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/last_executions.yml
src/Pim/Bundle/EnrichBundle/Resources/config/normalizers.yml
src/Pim/Bundle/EnrichBundle/spec/Normalizer/JobExecutionNormalizerSpec.php
src/Pim/Bundle/EnrichBundle/spec/Normalizer/VersionNormalizerSpec.php
src/Pim/Bundle/EnrichBundle/spec/ProductQueryBuilder/ProductAndProductModelQueryBuilderSpec.php
src/Pim/Bundle/NotificationBundle/Controller/NotificationController.php
src/Pim/Bundle/NotificationBundle/Resources/views/Notification/list.json.twig
src/Pim/Bundle/NotificationBundle/spec/Controller/NotificationControllerSpec.php
src/Pim/Component/Connector/spec/Job/ComputeDataRelatedToFamilyRootProductModelsTaskletSpec.php
src/Pim/Component/Connector/spec/Job/ComputeDataRelatedToFamilySubProductModelsTaskletSpec.php

This PR fixes inconsistencies in the datetime shown in the UI. Several are displayed using the server timezone, when it should use the one defined in the current user settings.
The fixes affect:
- the notifications,
- the product history displayed in the PEF side information => **commit cherry-picked from https://github.com/akeneo/pim-community-dev/pull/8774**,
- import/export start and end time => fixed on the job execution datagrid (in the job profile page) and the job execution detailed view. The process tracker datagrid was already OK.
| …

PIM-7668: Always display datetime according to current user timezone

---

CHANGELOG-2.3.md
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/field/wysiwyg-field.js

A bug prevents from inserting a link when a user mass-edit a text area with the WYSIWYG enabled.
The pop-in window appears, but the "modal-backdrop" mask stays on it.
The pop-in has a higher z-index to stay atop the "modal-backdrop", and this works fine on the PEF.
The problem is that the mass-edit form is in a bootstrap modal, and the pop-in is declared in this modal, but the mask is not (t is not even in the HTML page body, but in a `div` element placed directly at the very end of the `html` tag, after the `body`).
As a result, the mask z-index always win, because even if it is lower than the pop-in z-index, it is higher than the bootstrap modal z-index, so the pop-in one is ignored.
The (very dirty) fix consists in moving the "modal-backdrop" in the bootstrap modal, so …

PIM-7656: Fix link insertion in wysiwyg mass edit field

---

CHANGELOG-2.3.md
src/Pim/Bundle/CatalogBundle/tests/integration/EventSubscriber/LoadEntityWithValuesSubscriberIntegration.php
src/Pim/Component/Catalog/Factory/Value/ValueFactoryInterface.php
src/Pim/Component/Catalog/Factory/ValueCollectionFactory.php
src/Pim/Component/Catalog/Factory/ValueFactory.php
src/Pim/Component/Catalog/spec/Factory/ValueCollectionFactorySpec.php
src/Pim/Component/Catalog/spec/Factory/ValueFactorySpec.php
src/Pim/Component/ReferenceData/Factory/Value/ReferenceDataCollectionValueFactory.php
src/Pim/Component/ReferenceData/spec/Factory/Value/ReferenceDataCollectionValueFactorySpec.php

EE PR : https://github.com/akeneo/pim-enterprise-dev/pull/4730
This PR add a fix to prevent an asset collection to be empty on the PEF when one or multiple assets of the collection are deleted. An exception was thrown in the ReferenceDataCollectionValueFactory that stopped the loading of ALL the assets of the attribute asset collection.
I tried a first iteration by just removing the thrown exception, but it broke the rules & product import. So we decided to add an optionnal parameter to choose if we want to ignore unknown reference data or not. …

PIM-7664: an exception is not thrown anymore when the asset cannot be loaded

---

src/Pim/Bundle/EnrichBundle/Resources/public/js/controller/product/index.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/grid/view-selector.js

When requesting the datagrid, there is always a query executed before starting all the other ones:
'http://demo.akeneo.com/configuration/locale/rest?activated=true'
As we deactivate very very barely a locale, we can put in cache this query.
It will save from 60 to 100ms.
=> this call is already in cache, but the product index.js clear this value every time. I just remove this line.
Merged because has random but CI is green according to @Doodoune.
| …

PIM-7624: Remove the clear from product grid about activated locales cache

---

CHANGELOG-2.3.md
src/Pim/Bundle/EnrichBundle/Resources/config/controllers.yml
src/Pim/Bundle/EnrichBundle/Resources/config/mass_actions.yml

The jobs launched from the UI with the "mass-edit" actions didn't use the authenticated job launcher. So the user was not passed to the job processors. To apply permissions in EE on these actions, an ugly trick was done to overwrite the token with one created from the user that launch the mass edit.
Now, all the jobs launched from the mass edit controller will have the option "is_user_authenticated" to true.
This fix will allow to use the authorization checker without doing the trick. (cf https://github.com/akeneo/pim-enterprise-dev/pull/4700) …

PIM-7672: Fix the mass edit controller to launch jobs with authentication

---

CHANGELOG-2.3.md
src/Pim/Bundle/EnrichBundle/Resources/config/routing/media.yml
src/Pim/Bundle/UserBundle/Entity/User.php

PIM-7612 introduced a problem with some routing of liip_imagine. This extra route makes it retro-compatible with some generated urls.
Also, the user's avatar URL was missing a leading `/`, which was interpreted by the browser as a relative url, thus breaking the top right avatar image on URLs with sub paths.

PIM-7674: fix Avatar image broken on dashboard

---

.ci/Dockerfile
.ci/Jenkinsfile
.ci/builder.yaml

The goal of this PR is to reduce docker build time when you have no change on composer.json and composer.lock.
If you change the composer.json on your PR the docker build won't use the cache for the composer step.
Otherwise, docker build will reuse the previous layer that match with images built on the master branch (nightly).
| …

[WIP] decrease build time by using docker layer cache

---

src/Akeneo/Pim/Enrichment/Bundle/Resources/config/serializers_storage.yml
src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Indexing/Value/ValueCollectionNormalizer.php
src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Storage/Product/ProductValuesNormalizer.php
src/Akeneo/Pim/Enrichment/Component/spec/Product/Normalizer/Indexing/Value/ValueCollectionNormalizerSpec.php
src/Akeneo/Pim/Enrichment/Component/spec/Product/Normalizer/Storage/Product/ProductValuesNormalizerSpec.php

The normalization of PV is time consuming for the PHP process and the complexity is not linear.
As stated it in this article [No array_merge In Loops](https://github.com/dseguy/clearPHP/blob/master/rules/no-array_merge-in-loop.md), array_merge is inefficient in a loop.
```
$result = [];
foreach ($source as $list) {
$result = array_merge($result, $list);
}
```
At first loop, array_merge copy the variable `$result` having a size of 1.
At second loop, array_merge copy the variable `$result` having a size of 2.
At third loop, array_merge copy the variable `$result` having a size of 3.... etc
The complexity is `*O(n^2)* (where n is the number of PV).  
Explanation: 1 + 2 + 3 + ....  is a suite. Formula: O(n*(n+1)/2) => O(n^2/2) => O(n^2)
Use …

Improve storage and indexation normalization performance by using variadic function

---

CHANGELOG-2.3.md
src/Pim/Component/Catalog/Value/OptionValue.php
src/Pim/Component/Catalog/spec/Value/OptionValueSpec.php

Fix null option values string casting.
Null options values should return the option code string instead of `null` in the `__toString` method.

PIM-7694: fix null options values string casting

---

CHANGELOG-2.3.md
src/Pim/Component/Catalog/Normalizer/Indexing/Product/PropertiesNormalizer.php
src/Pim/Component/Catalog/Normalizer/Indexing/ProductAndProductModel/ProductModelPropertiesNormalizer.php
src/Pim/Component/Catalog/Normalizer/Indexing/ProductModel/ProductModelPropertiesNormalizer.php
src/Pim/Component/Catalog/Validator/Constraints/FamilyAttributeAsLabelValidator.php
src/Pim/Component/Catalog/spec/Normalizer/Indexing/Product/PropertiesNormalizerSpec.php
src/Pim/Component/Catalog/spec/Normalizer/Indexing/ProductModel/ProductModelPropertiesNormalizerSpec.php
src/Pim/Component/Catalog/spec/Validator/Constraints/FamilyAttributeAsLabelValidatorSpec.php

In some files, we make a direct call to `$family->getAttributeAsLabel()->getCode()`
without checking that the family has an actual 'attributeAsLabel' (it can be null e.g. if the attribute was deleted)
In the case of the PropertiesNormalizers, this leads to errors during indexation, thus preventing from saving the product/product model.
`Todo`: …

PIM-7731: check for attribute as label not null

---

CHANGELOG-2.3.md
package.json
tests/legacy/features/Context/Page/Base/ProductEditForm.php

In a product edit form, when adding a line (enter) in a text attribute with the option "rich text editor" enabled, the page is scrolled back to the top.

PIM-7740: bump summernote version to fix scroll glitches

---

CHANGELOG-2.3.md
src/Pim/Component/Catalog/ValuesFiller/EntityWithFamilyVariantValuesFiller.php
src/Pim/Component/Catalog/spec/ValuesFiller/EntityWithFamilyVariantValuesFillerSpec.php

If an attribute has a numeric code and is in a family variant, it makes product models creation crash. 
It's because a bad usage of `array_merge`

PIM-7746: Fix issue when an attribute code is numeric

---

CHANGELOG-2.3.md
src/Oro/Bundle/UserBundle/Form/Handler/AclRoleHandler.php
src/Pim/Bundle/EnrichBundle/Resources/public/js/controller/role.js
src/Pim/Bundle/EnrichBundle/Resources/public/templates/error/error.html
src/Pim/Component/User/Updater/RoleUpdater.php
src/Pim/Component/User/spec/Updater/RoleUpdaterSpec.php

Two problems solved in this pull request.
**Problem 1**: "The role label update action (by UI or by Import) lead to an ACL failure"
**Problem 2**: "An error is displayed to the user on permission update even if the change is correctly applied"
Why two fixes in one PR ?
The second problem was put into relief by the first one in the issue raised by the customer. 
**Problem:**
In the `oro_access_group` table you've three colums (id, role, label).
The `role` value is used in the code to check if you're granted to do some actions in the pim.
The ACL used to check your permissions is computed and store within your session stored in database. The `role` is used as a code and must be immutable (see …

Pim 7724 / 7726 - Firefox : Error 0 during roles saving and Issue when changing a role's name

---

CHANGELOG-2.3.md
src/Pim/Component/Connector/ArrayConverter/FlatToStandard/User.php
src/Pim/Component/Connector/spec/ArrayConverter/FlatToStandard/UserSpec.php

Boolean conversion is not working for user on the fields `enabled` and `email_notifications`
Other converters (like the `Boolean`) don't make strict string comparison, so we fix this converter by using a loose comparison.

PIM-7747: convert boolean strings in User converter

---

src/Pim/Bundle/EnrichBundle/Resources/config/datagrid/job_tracker.yml

The filter on status in the process tracker crashes because it needs to be aliased.

PIM-7751: Fix filters "Type" and "Status" in the process tracker

---

features/Pim/Behat/Decorator/Common/AttributeSelectorDecorator.php

The click to clear attributes list in export builder is unstable because it does not wait for the list to be empty.
I added a spin counting the item to ensure that this list is empty.

Fix clear attributes selector decorator in export builder

---

.ci/Jenkinsfile

Fix the deprecated gcloud command that will be removed at the end of the month
```
(DEPRECATED) Submit a build using the Google Cloud Build service.
This command is deprecated and will be removed on or after 2018-10-31. Please use gcloud builds submit instead.
```
see https://cloud.google.com/sdk/gcloud/reference/container/builds/submit for more information.
| Micro Demo …

Fix deprecated ci command

---

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/TextField.less

**Because they are grey by default in Firefox.**

Set explicit white background for light inputs

---

CHANGELOG-3.0.md
src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/DateValueFactory.php
src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/MediaValueFactory.php
src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/MetricValueFactory.php
src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/OptionValueFactory.php
src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/OptionsValueFactory.php
src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/PriceCollectionValueFactory.php
src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/ReferenceDataValueFactory.php
src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/ScalarValueFactory.php
src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/ValueFactoryInterface.php

A "@todo" has been forgotten in the last pull-up  from 2.3
See the original PR : https://github.com/akeneo/pim-community-dev/pull/8918

Fix forgotten bc-break to manage

---

CHANGELOG-2.3.md
src/Pim/Bundle/FilterBundle/Filter/ProductValue/DateTimeRangeFilter.php

A validation was missing in the `DateTimeRangeFilter` causing a fatal error instead of just ignoring the filter when no value was set.

PIM-7759: Date range grid filters should be ignored when no value is set

---

CHANGELOG-2.3.md
src/Pim/Component/Enrich/Job/DeleteProductsAndProductModelsTasklet.php
src/Pim/Component/Enrich/spec/Job/DeleteProductsAndProductModelsTaskletSpec.php

**Before this PR**:
The deletion of products and product models through the grid is handled
by a Tasklet called `DeleteProductsAndProductModelsTasklet` (https://github.com/akeneo/pim-community-dev/blob/f98e07d7fc7a33bdeb7705c2f927a98395e98c95/src/Pim/Component/Enrich/Job/DeleteProductsAndProductModelsTasklet.php#L128).
The way we fetch the product and product models to delete takes
advantage of the filters the users has set on the grid, passed onto the
tasklet and used along side the PQB.
In this version, we would also add a filter on the 'parent' property
to look for root product models (no parent) and simple products (no
parent as well).
Hence, the deletion would only work for those types of products and
product models.
The deletion of sub-product models and variant product models would …

PIM-7758: Fix product and product model deletion

---

src/Pim/Component/Catalog/Validator/Constraints/ActivatedLocale.php
src/Pim/Component/Catalog/Validator/Constraints/ActivatedLocaleValidator.php
src/Pim/Component/Catalog/spec/Validator/Constraints/ActivatedLocaleValidatorSpec.php

For the onboarder, we need validate a supplier which must contain an activated locale. Problem with the ActivatedLocaleValidator, it accepts only a Locale entity, while on the onboarder, we valide a DTO (which contains the locale code)
Edit:
I did not want to add an other validator like `ActivatedLocaleCodeValidator`. Ideally, in the future, we will only validate DTO, so we will have code to validate, not the entity linked
| Changelog …

Be able to validate an activated locale when the locale is a string

---

tests/back/Acceptance/User/InMemoryGroupRepository.php

If you warmup the cache of the fake test environment on the fly, it works: the compiler compile.
If your warmup the cache with the command, it doesn't work: the container does not compile. 
`OK`: …

PIM-7750: fix in memory repository to compile the kernel

---

CHANGELOG-2.3.md
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/GetProductIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/SuccessListProductIntegration.php
src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Query/FindActivatedCurrencies.php
src/Pim/Bundle/CatalogBundle/Resources/config/factories.yml
src/Pim/Bundle/CatalogBundle/Resources/config/queries.yml
src/Pim/Bundle/CatalogBundle/tests/integration/Doctrine/Common/Saver/ProductSaverIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/Doctrine/Query/FindActivatedCurrenciesIntegration.php
src/Pim/Bundle/ConnectorBundle/tests/integration/Export/AbstractExportTestCase.php
src/Pim/Bundle/ConnectorBundle/tests/integration/Export/ProductQueryBuilder/ExportProductsByFamiliesIntegration.php
src/Pim/Bundle/VersioningBundle/tests/integration/Normalizer/Flat/ProductIntegration.php
src/Pim/Component/Api/tests/integration/Normalizer/ProductNormalizerIntegration.php
src/Pim/Component/Catalog/Channel/Query/FindActivatedCurrenciesInterface.php
src/Pim/Component/Catalog/Factory/Value/PriceCollectionValueFactory.php
src/Pim/Component/Catalog/spec/Factory/Value/PriceCollectionValueFactorySpec.php
src/Pim/Component/Catalog/tests/integration/Normalizer/Indexing/ProductAndProductModelIndexingIntegration.php
src/Pim/Component/Catalog/tests/integration/Normalizer/Indexing/ProductIndexingIntegration.php
src/Pim/Component/Catalog/tests/integration/Normalizer/Standard/ProductStandardIntegration.php
src/Pim/Component/Catalog/tests/integration/Normalizer/Storage/EntityWithValuesStorageIntegration.php
tests/legacy/features/import/product/import_products_with_invalid_data.feature
tests/legacy/features/localization/product/validation/validate_price_attributes.feature

**Problem:**
When showing a product, and ultimately, hydrating its price collection values we do not check if the currencies coming from the database are still activated in the channel. hence, we hydrate those prices regardless.
When the user wants to do a modification on the product and saves it, those "old" prices are sent to the backend alongside with the updates, and a violation error occurs because 🎉  you cannot set a price on a product for a currency not activated by the channel :)
**The user cannot update the price anymore through the UI**
**Proposed solution:**
The solution is to:
- filter out the prices that have a currency not activated in the channel of the value at hydration time (for scopable prices attributes).
- filter …

PIM-7765: Add checks channel/currency in PriceCollectionFactory

---

src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/catalog_volume/index.yml
src/Pim/Bundle/EnrichBundle/Resources/config/requirejs.yml
src/Pim/Bundle/EnrichBundle/Resources/public/js/catalog-volume/header.ts
src/Pim/Bundle/EnrichBundle/Resources/public/js/catalog-volume/section.ts
src/Pim/Bundle/EnrichBundle/Resources/public/templates/catalog-volume/average-max.html
src/Pim/Bundle/EnrichBundle/Resources/public/templates/catalog-volume/number.html
src/Pim/Bundle/EnrichBundle/Resources/translations/jsmessages.en.yml
src/Pim/Bundle/UIBundle/Resources/public/less/components/CatalogVolume.less

There was a string on translations keys which should not be here.
I replaced it in the conf to not translate it.

[Translations] Fix wrong translation link (not translatable)

---

CHANGELOG-2.3.md
src/Pim/Bundle/VersioningBundle/Command/RefreshCommand.php

When you save some change on a product (with a rule version not refresh on it) during the execution of the versioning command, that create doublon.
Example : 

PIM-7771: Fix refresh versioning command about duplicate version's rule

---

CHANGELOG-2.0.md
src/Pim/Bundle/CatalogBundle/Doctrine/Common/Saver/ProductModelDescendantsSaver.php
src/Pim/Bundle/CatalogBundle/Doctrine/Common/Saver/ProductSaver.php
src/Pim/Bundle/CatalogBundle/Doctrine/ORM/CompletenessRemover.php
src/Pim/Bundle/CatalogBundle/spec/Doctrine/Common/Saver/ProductModelDescendantsSaverSpec.php
src/Pim/Bundle/CatalogBundle/spec/Doctrine/Common/Saver/ProductSaverSpec.php
src/Pim/Bundle/CatalogBundle/tests/integration/Completeness/CalculateCompletenessCommandIntegration.php
src/Pim/Component/Catalog/Completeness/CompletenessGenerator.php
src/Pim/Component/Catalog/Completeness/CompletenessGeneratorInterface.php
src/Pim/Component/Catalog/Completeness/CompletenessRemoverInterface.php
src/Pim/Component/Catalog/Manager/CompletenessManager.php
src/Pim/Component/Catalog/Model/AbstractCompleteness.php
src/Pim/Component/Catalog/Model/CompletenessInterface.php
src/Pim/Component/Catalog/spec/Completeness/CompletenessGeneratorSpec.php

We have a lot of concurrent `INSERT INTO` to save the completeness in the database that generates SQL errors because of duplicated keys. For example: Integrity constraint violation: 1062. Duplicate entry 'X-XX-XXXXXX' for key 'searchunique_idx'
Currently, when we save a product, we remove all the completeness in the database, we compute it again and we save its all in the database.
In this PR, to avoid the concurrent `INSERT INTO` that could generate a duplicated key, we change the behavior of the completeness computing: we don't remove the existing product completenesses, but we update the existing ones by updating their ratio and we add or delete completenesses if we need.
The downside of this is that we had to make mutable the Completeness object.
| Tested with Icecat demo dev | …

PIM-7757: Reduce a lot the risk of inserting duplicate completenesses.

---

src/Pim/Bundle/AnalyticsBundle/DataCollector/AttributeDataCollector.php
src/Pim/Bundle/AnalyticsBundle/Resources/config/data_collectors.yml
src/Pim/Bundle/AnalyticsBundle/Resources/translations/messages.en.yml
src/Pim/Bundle/AnalyticsBundle/spec/DataCollector/AttributeDataCollectorSpec.php

Add new axis : 
Average number of attributes by family: For each family, you count its number of attributes. Then you compute the average for all the families.
It already exist in the Volume Monitoring Screen so already tested with integration tests. 
| Tech Doc …

PIM-7621: Add average number of attributes per family into System Informations data

---

src/Pim/Component/Catalog/Completeness/CompletenessRemoverInterface.php

The completeness remover methods are not to be removed.

Remove deprecation notice on CompletenessRemover

---

CHANGELOG-2.3.md
composer.lock
src/Pim/Bundle/EnrichBundle/Resources/public/js/family-variant/form/attribute-set.js

In the variant family configuration, at the variant attributes screen, it is not possible to move a group of attributes if the group contains a large number of attributes:
This drag'n'drop is managed by the `sortable` widget from JQuery UI. The issue is fixed by removing the use of its [`containment` option](https://api.jqueryui.com/sortable/#option-containment), as it is useless here: the sortable lists use all the window.
As a result, the drag'n'drop behaves as expected: …

Fix drag'n'drop of huge attribute group in family variant

---

CHANGELOG-2.3.md
src/Pim/Bundle/VersioningBundle/Normalizer/Flat/AttributeNormalizer.php
src/Pim/Bundle/VersioningBundle/spec/Normalizer/Flat/AttributeNormalizerSpec.php
src/Pim/Bundle/VersioningBundle/tests/integration/Normalizer/Flat/AttributeIntegration.php

Remove options values label from versioning
**Why?**
After an import of 20000 options for an attribute, it generate 200 new versions of the attribute (1 each 100 options imported),if you look a the 200th attribute history in the `options` sections, you have the 19900 options normalized (code + localized labels) in old values and 20000 options normalized (code + localized labels) in new values, such a big amount of data.
If you import more options you get more and more closer to the MySQL `max_allowed_packet` limit, and you get a warning `Warning: Error while sending QUERY packet.`who make the import failed.
So the first solution is to increase the `max_allowed_packet` and no more warning happends, but functionally speaking it has no …

PIM-7767: Remove options values label from versioning

---

CHANGELOG-2.3.md
src/Pim/Bundle/CatalogBundle/Resources/config/validation/attribute.yml
src/Pim/Bundle/CatalogBundle/tests/integration/Validation/Attribute/GlobalConstraintsIntegration.php

"family" code was known to bug the PIM, but Family (capital F) does the same.
We need to prevent the use of the code family, whatever its case is.
FAmily, faMily, FAMILY, family, Family, famILY...

PIM-7783: Fix constraint on attribute name

---

CHANGELOG-2.3.md
src/Pim/Bundle/NotificationBundle/Resources/views/Notification/list.json.twig

This PR fixes the injection of HTML code in the notifications template

PIM-7776: Fix injection in the job's label in notification area

---

CHANGELOG-2.3.md
src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filter/date-filter.js
src/Pim/Bundle/DataGridBundle/Resources/public/templates/filter/date-filter.html

Fix the fact that the date filter on grids was rendered without any real values and with the default one.

PIM-7774: Fix refresh of grid date filter

---

CHANGELOG-2.3.md
src/Pim/Bundle/EnrichBundle/Resources/config/routing/product.yml
src/Pim/Bundle/EnrichBundle/Resources/public/js/datagrid/action/toggle-product-action.js

The URL for toggling status was accessible with a GET method.
I fixed this by disallowing this method, and allowing a POST.
This method was used on the Datagrid, so I changed the method type to allow enable/disable from the grid.

PIM-7773: Fix routing issues with product status toggle

---

CHANGELOG-2.3.md
src/Pim/Bundle/EnrichBundle/Resources/config/controllers.yml
src/Pim/Bundle/EnrichBundle/Resources/config/query_builder.yml
src/Pim/Bundle/EnrichBundle/Resources/config/query_builders.yml

Fix product gap between product grid and sequential edit when selecting `All` option.
The sequential edit use a cursor factory that does not take in account the product and product model search aggregator [Introduce here](https://github.com/akeneo/pim-community-dev/pull/8875)
This PR introduce a dedicated `ProductAndProductModelQueryBuilderFactory` for sequential edit
`pim_enrich.query.product_and_model_query_sequential_edit_builder_factory`, in order to have the same behavior as the product grid search …

PIM-7823: Fix product gap between product grid and sequential edit when selecting `All` option

---

CHANGELOG-2.3.md
src/Pim/Bundle/FilterBundle/Filter/ProductValue/ChoiceFilter.php
src/Pim/Bundle/FilterBundle/Resources/config/filters.yml
src/Pim/Bundle/FilterBundle/spec/Filter/ProductValue/ChoiceFilterSpec.php
src/Pim/Bundle/ReferenceDataBundle/DataGrid/Filter/ReferenceDataFilter.php
src/Pim/Bundle/ReferenceDataBundle/Resources/config/datagrid/filters.yml

When an attribute option, used in the filter of a view, is removed => the view cannot be loaded.

PIM-7824: Fix the option filter

---

CHANGELOG-2.3.md
src/Pim/Bundle/EnrichBundle/Resources/config/pim.yml
src/Pim/Component/Connector/Processor/Denormalization/ProductAssociationProcessor.php
src/Pim/Component/Connector/Processor/Denormalization/ProductModelAssociationProcessor.php
src/Pim/Component/Connector/spec/Processor/Denormalization/ProductAssociationProcessorSpec.php
src/Pim/Component/Connector/spec/Processor/Denormalization/ProductModelAssociationProcessorSpec.php
tests/legacy/features/import/product/import_products_with_associations.feature
tests/legacy/features/import/product/import_products_with_product_model_associations.feature
tests/legacy/features/reference-data/import/import_products.feature

This PR increases product import performances, by
- increasing the batch size
- avoiding loading product and comparing in association step when there's no association defined in the file
This PR allows up to 4x performance increase for product imports.
About the batch size: this one was setup at 10 products some month ago following a memory problem. It seems that performance problems are more important now than memory problem with the switch to 10. So we are rolling back on this point.
We will provide a chapter in the troubleshooting section of the documentation, for people to better undrerstand the usage and impact of this parameter.
| …

PIM-7852 Increase product import performance and fix association model import

---

CHANGELOG-2.3.md
src/Pim/Bundle/EnrichBundle/Resources/public/js/controller/user.js

When editing user information, we need to reload the page in order to have fresh information on UI.
**Problem**:
If there is validation errors (minimum number of characters not respected or so), the user is not saved and we want to display to the user that he entered wrong data in the form. But as we automatically reload the page the user didn't have the time to see his mistake.
**Solution**:
Check on the xhr response if we have validation error and reload or not the page.
| Added …

PIM-7853 - do not reload page if there is a form validation error

---

CHANGELOG-2.3.md
src/Pim/Component/Catalog/Updater/AttributeOptionUpdater.php

Before, there was a warning like "unable to update code from xxx to XXX" because of case insensitive on attribute option codes.
This PR fixed it by only updating immutable code if entity is new.

PIM-7791: Suppress warning on attribute option in case of case sensitive codes

---

.gitignore
CHANGELOG-2.3.md
src/Oro/Bundle/UserBundle/Resources/config/validation.yml
src/Pim/Bundle/CatalogVolumeMonitoringBundle/tests/Integration/Persistence/Query/CountUsersIntegration.php
src/Pim/Bundle/UserBundle/DependencyInjection/PimUserExtension.php
src/Pim/Bundle/UserBundle/Resources/config/validators.yml
src/Pim/Bundle/UserBundle/Validator/Constraints/ValueShouldNotContainsBlacklistedCharacters.php
src/Pim/Bundle/UserBundle/Validator/Constraints/ValueShouldNotContainsBlacklistedCharactersValidator.php
src/Pim/Bundle/UserBundle/spec/Validator/Constraints/ValueShouldNotContainsBlacklistedCharactersValidatorSpec.php

**Problem**:
Some "dangerous" characters could be persisted in database via user form inputs.
**Solution**:
Add a validator that blacklist some characters `<, >, &, "`

PIM-7831 add blacklisted characters validator

---

CHANGELOG-2.0.md
src/Pim/Bundle/EnrichBundle/Resources/public/templates/form/common/fields/textarea.html

The extra linebreak on the closing textarea tag and the 4 spaces before the <%- cause the textarea to be pre-populated.
Github issue: https://github.com/akeneo/pim-community-dev/issues/7532

GITHUB-7532: Fix the prepoluation of textarea field

---

CHANGELOG-2.3.md
src/Pim/Component/Catalog/Model/AbstractProduct.php
src/Pim/Component/Catalog/Model/ProductModel.php
src/Pim/Component/Catalog/spec/Model/ProductModelSpec.php

Blackfire report : https://blackfire.io/profiles/258f0dc2-0633-4e68-b8ee-94e2431ee806/graph?settings%5Bdimension%5D=wt&settings%5Bdisplay%5D=focused&settings%5BtabPane%5D=nodes&selected=Pim%5CComponent%5CCatalog%5CBuilder%5CEntityWithValuesBuilder%3A%3AaddOrReplaceValue&callname=Pim%5CComponent%5CConnector%5CProcessor%5CNormalization%5CProductProcessor%3A%3Aprocess
Issue was in the fillMissingValues, which was generating a complete ValueCollection for each value to fill (2.618.913 calls)
With this PR, we don't create a value collection anymore and write explicitly to check in this level then in the parent.
For 535 product models:
Previous timing: 21 minutes (0.42 pm/s)
Current timing: 1 minute (8.92 pm/s)
Improvement: 21 times faster.
| …

PIM-7865: Improve performances on Product model export

---

CHANGELOG-3.0.md
bin/check-pullup
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/fields/field.js
src/Akeneo/UserManagement/Bundle/Context/UserContext.php
src/Akeneo/UserManagement/Bundle/Resources/config/form_extensions/edit.yml
src/Akeneo/UserManagement/Bundle/Resources/config/model/doctrine/User.orm.yml
src/Akeneo/UserManagement/Bundle/Resources/config/normalizers.yml
src/Akeneo/UserManagement/Component/Factory/DefaultProperty.php
src/Akeneo/UserManagement/Component/Factory/SimpleDefaultProperty.php
src/Akeneo/UserManagement/Component/Factory/UserFactory.php
src/Akeneo/UserManagement/Component/Model/User.php
src/Akeneo/UserManagement/Component/Model/UserInterface.php
src/Akeneo/UserManagement/Component/Normalizer/UserNormalizer.php
src/Akeneo/UserManagement/Component/Updater/UserUpdater.php
tests/back/UserManagement/Specification/Component/Factory/SimpleDefaultPropertySpec.php
tests/back/UserManagement/Specification/Component/Factory/UserFactorySpec.php
tests/back/UserManagement/Specification/Component/Model/UserSpec.php
tests/back/UserManagement/Specification/Component/Normalizer/UserNormalizerSpec.php
tests/back/UserManagement/Specification/Component/Updater/UserUpdaterSpec.php

This PR allows extension in the User without overriding it. 
How we did that ? 
- The user now has a bag of properties which can be added from where you want
What does it implies?
We have to compose at a lot of places, factory, normalizer, updater in order to make it possible, that's why we had to change them a little bit to make them work. …

TIP-897: Redesign user model to allow extension

---

src/Oro/Bundle/PimFilterBundle/Filter/ProductValue/ChoiceFilter.php

We need to override this method in EE for Reference Entity filter

Change `filterOnlyExistingOptions` visibility

---

CHANGELOG-2.3.md
src/Pim/Component/Catalog/Normalizer/Standard/Product/MetricNormalizer.php
src/Pim/Component/Catalog/spec/Normalizer/Standard/Product/MetricNormalizerSpec.php

Allow the "0" value in non decimal metric value.

PIM-7885: Allow "0" for non decimal metric value

---

src/Akeneo/Platform/Bundle/UIBundle/DependencyInjection/Compiler/RegisterFormExtensionsPass.php

When you load the PIM, it will add all the extensions contained in `form_extensions.yml` files and `form_extensions` folders, bundle per bundle.
The extensions are loaded file by file, using a Symfony finder.
Imagine you have 2 files: `/form_extensions/file1.yml` and `/form_extensions/file2.yml`, in the same bundle, and these 2 files contain a form_extension with exactly the same `code`, but not the same configuration.
You can not know what file will be loaded first, and which extension will be finally used.
We already had this previous issue on a previous PR, and the loading order were not the same on a local computer and on the CI computers.
So, locally, it works, but not in the CI. Thanks @sebglon for helping me finding this issue :tada: .
The solution is to sort (bundle per bundle) …

Sort form extensions pass

---

CHANGELOG-2.0.md
features/Context/FixturesContext.php
features/export/export_products.feature
features/import/product/import_products_with_optional_values.feature
features/localization/export/export_products_with_date.feature
features/localization/export/export_products_with_decimal.feature
features/mass-action/edit_common_attributes_channel.feature
features/product/remove_attributes_from_product.feature
features/reference-data/export/export_products_with_reference_data.feature
features/reference-data/product/display_reference_data_in_the_grid.feature
features/reference-data/product/sorting/sort_products_per_reference_data.feature
src/Pim/Bundle/CatalogBundle/tests/integration/Product/RemoveOptionalAttributeIntegration.php
src/Pim/Component/Connector/Processor/Denormalization/ProductProcessor.php
src/Pim/Component/Connector/spec/Processor/Denormalization/ProductProcessorSpec.php

Problem: When we import a product and the "family" column is not set, we can bypass the family attributes and are able to set optional attributes to product that have a family (_and thus **should not have optional attributes**_).
Solution: If the `family` column is not set in the imported file, we fetch the product by its identifier and then its family.
| Micro Demo …

PIM-7855: Optional attributes are added when family column is not in the imported product file

---

src/Akeneo/Tool/Bundle/ApiBundle/tests/integration/EventSubscriber/CheckHeadersRequestSubscriberIntegration.php

This integration test was testing that we could access to "/" using an api authenticated user which is not a relevant test.

AOB-286 - remove useless api test

---

CHANGELOG-2.3.md
src/Pim/Bundle/EnrichBundle/Resources/public/js/fetcher/attribute-group-fetcher.js

We have several requests that are sent 3 or 4 times, like this one:
[...]/rest/attribute-group/?options%5Blimit%5D=-1

PIM-7897: Add cache to fetchAll in attribute group fetcher

---

src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/column-selector.ts

jQuery types were updated here https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30144
So we have to update some typehinting
This will fix the broken front-end build

Update jQuery event object typehinting

---

CHANGELOG-2.3.md
src/Pim/Bundle/CatalogBundle/Resources/config/jobs.yml
src/Pim/Component/Catalog/Job/ComputeFamilyVariantStructureChangesTasklet.php
src/Pim/Component/Catalog/spec/Job/ComputeFamilyVariantStructureChangesTaskletSpec.php

The "ComputeFamilyVariantStructureChangesTasklet" try to make a saveAll on the product repository with too many products in memory (for our client is 6500)

PIM-7901: Fix memory leak on "compute_family_variant_structure_changes" job

---

CHANGELOG-2.3.md
src/Pim/Bundle/EnrichBundle/Resources/public/js/family/form/variants/add-family-variant-fields-container.js

PIM-7908: fix variant family creation if an attribute doesn't have a translation for the current locale

---

CHANGELOG-2.0.md
src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/field/boolean.html

-- Regression --
Boolean values still appear as pim_common.yes or pim_common.no in PEF and in mass edit.

PIM-7886: Fix translations of boolean attributes

---

CHANGELOG-1.7.md
src/Pim/Bundle/InstallerBundle/Command/AssetsCommand.php

Allow users to set regional locales for UI (en_NZ, pt_PT and pt_BR)

PIM-7841: Allow users to set regional locales for UI (en_NZ, pt_PT and pt_BR)

---

CHANGELOG-2.0.md
app/PimRequirements.php

Backport check port in PimRequirements for 2.0 version (it already exist on 2.3 & master)

PIM-7871 && GITHUB-7932: Backport check port in PimRequirements for 2.0 version

---

CHANGELOG-1.7.md
features/Context/WebUser.php
features/mass-action/quick_export_grid_context.feature
src/Pim/Bundle/DataGridBundle/Controller/ProductExportController.php
src/Pim/Bundle/EnrichBundle/Connector/Job/JobParameters/ConstraintCollectionProvider/ProductQuickExport.php
src/Pim/Bundle/EnrichBundle/Connector/Processor/QuickExport/ProductProcessor.php

Before, it exports every activated locales in a grid context quick export.
Now, it only exports selected one.
| Added legacy Behats               | y

PIM-7911: Export only selected locale for product grid quick export with datagrid context

---

CHANGELOG-2.0.md
src/Pim/Bundle/NotificationBundle/Resources/public/js/notifications.js

Before, when you navigate between pages, old Timeout were not cleared.
So, if you click on a product then the product grid then a product then the product grid 20 times, you will run 20 timeout, and 30 seconds later, it will raise a tornado of "count_unread" notifications.
To prevent this, we store the setTimeout identifier in the session storage, then stop it before trying to create another timeout. …

PIM-7902: Fix unnecessary calls for unread messages count on page navigation

---

CHANGELOG-3.0.md
src/Akeneo/Platform/Bundle/InstallerBundle/Command/DatabaseCommand.php
upgrades/schema/Version_3_0_20181205151719_add_configuration_table.php

This PR introduces a new `pim_configuration` table. A generic way to store configuration. It's a very simple table with a unique key and a JSON field.
For the moment it's only used for the SSO feature but as we want to make more and more features SaaS compatible, we'll need to do that again soon. It doesn't make any sense to create a new specific table for each feature/component with only one record inside.
| …

AOB-283: Add "pim_configuration" table

---

CHANGELOG-2.3.md
src/Pim/Bundle/ImportExportBundle/Resources/config/datagrid/job_profile.yml

Do not show delete icon on import/export profile if the user doesn't have the right to delete.

PIM-7866: do not show delete icon on import/export profile

---

CHANGELOG-2.3.md
src/Pim/Bundle/EnrichBundle/Resources/public/js/job/product/edit/content/structure/attributes-selector.js

PIM-7892: allow to filter on active catalog locale when adding an attribute to the product export filters

---

src/Akeneo/UserManagement/Bundle/Controller/GroupController.php
src/Akeneo/UserManagement/Bundle/Resources/config/removers.yml

This PR introduce the use of the base remover to delete a user group and have access to the the remover's events.

PIM-7930: use remover to delete user group

---

src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml
src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductGrid/FetchProductModelRowsFromCodes.php
src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductGrid/ProductModelImagesFromCodes.php
tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/ProductGrid/FetchProductAndProductModelRowsIntegration.php
tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductGrid/AssertRows.php
tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductGrid/FetchProductModelRowsFromCodesIntegration.php
tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductGrid/ProductGridFixturesLoader.php

This is maybe one of the most complicated rule for for the read models.
When you display a product model, you have an image (attribute as image).
As the attribute as image is not necessary in the product model or its parent level, you have to get it from its first created child (a child can be a sub  product model or a variant product, depending of where is the attribute as image).
Our storage is perfect to handle product model feature when getting data from the bottom (variant  product) to the top (root product model).
But it is pretty complicated to do it from top to bottom (actually, it is not designed for it). 
I enumerate in the phpdoc all the possibilities. 
It replaces this "simple" class (but not that much when you dive into the …

PIM-7660: get images of product models in the datagrid

---

src/Oro/Bundle/PimDataGridBundle/Datasource/ProductAndProductModelDatasource.php
src/Oro/Bundle/PimDataGridBundle/Resources/config/data_sources.yml
src/Oro/Bundle/PimDataGridBundle/spec/Datasource/ProductAndProductModelDatasourceSpec.php

We check permission just for security reason, in case of a malicious AJAX request.
UI already filters the locale and attributes according to the permissions of the user.
Here, we just check that the locale and the attributes are visible by the user if we forge the request.  …

PIM-7660: apply permissions on the product datagrid

---

bin/check-pullup

Now that every specification has been moved, we can check that there should not be any file in the `spec/` directory (especially useful while pulling up 2.3 towards master)

Do not allow spec/ directory anymore in master

---

CHANGELOG-2.0.md
src/Pim/Bundle/VersioningBundle/Normalizer/Flat/AttributeNormalizer.php
src/Pim/Bundle/VersioningBundle/spec/Normalizer/Flat/AttributeNormalizerSpec.php
src/Pim/Bundle/VersioningBundle/tests/integration/Normalizer/Flat/AttributeIntegration.php

This is a backport of PIM-7767 (https://github.com/akeneo/pim-community-dev/pull/9080)
Please see description of original fix: https://github.com/akeneo/pim-community-dev/pull/9080
| Added Specs                       | Fixed
| Added integration tests           | Fixed

PIM-7920: Remove options values label from versioning

---

CHANGELOG-2.3.md
src/Pim/Bundle/CatalogBundle/Elasticsearch/Filter/Field/ParentFilter.php
src/Pim/Bundle/CatalogBundle/Resources/elasticsearch/index_configuration.yml
src/Pim/Bundle/CatalogBundle/spec/Elasticsearch/Filter/Field/ParentFilterSpec.php
src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Field/ParentFilterIntegration.php

Basically revert the fix done for the PIM-7727 and fix it with Elasticsearch configuration.

PIM-7910: parent filter is now case insensitive

---

tests/back/Acceptance/Locale/InMemoryLocaleRepository.php

Implements the method `getActivatedLocales` of the `InMemoryLocaleRepository`.

APAI-383: Implement InMemoryLocaleRepository "getActivatedLocales"

---

CHANGELOG-2.3.md
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/attribute_group/create.yml
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/channel/create.yml

Breadcrumb missing when you create Attribute group or Channel :
http://demo.akeneo.com/#/configuration/attribute-group/create
http://demo.akeneo.com/#/configuration/channel/create
cf https://github.com/akeneo/pim-community-dev/issues/8482
`Todo`: …

GITHUB-8482: Fix missing breadcrumbs - cheers @userz58!

---

CHANGELOG-2.3.md
src/Pim/Bundle/UserBundle/Entity/UserInterface.php
src/Pim/Bundle/UserBundle/Form/Type/UserType.php
src/Pim/Bundle/UserBundle/Resources/views/User/Tab/general.html.twig
src/Pim/Bundle/UserBundle/Resources/views/User/view.html.twig

In order to be in conformity with the new European measures on the protection of personal data RGPD (General Data Protection Regulation), it was decided to hide the field "Date of birth" from the user creation in version 2.3 only.
It will be removed in version 3.0.
EE part: https://github.com/akeneo/pim-enterprise-dev/pull/5277 …

PIM-7899: Norm RGPD - Hide the field "Date of Birth"

---

CHANGELOG-3.0.md
src/Akeneo/UserManagement/Bundle/Resources/config/form_extensions/edit.yml
src/Akeneo/UserManagement/Bundle/Resources/config/form_extensions/show.yml
src/Akeneo/UserManagement/Bundle/Resources/config/model/doctrine/User.orm.yml
src/Akeneo/UserManagement/Bundle/Resources/config/validation.yml
src/Akeneo/UserManagement/Bundle/Resources/translations/jsmessages.en_US.yml
src/Akeneo/UserManagement/Component/Model/User.php
src/Akeneo/UserManagement/Component/Model/UserInterface.php
src/Akeneo/UserManagement/Component/Normalizer/UserNormalizer.php
src/Akeneo/UserManagement/Component/Updater/UserUpdater.php
tests/back/UserManagement/Specification/Component/Normalizer/UserNormalizerSpec.php
tests/front/common/builder/user.js
upgrades/schema/Version_3_0_20181227141616_remove_birthdate.php

In order to be in conformity with the new European measures on the protection of personal data RGPD (General Data Protection Regulation), it was decided to remove the field "Date of birth" from the user creation form in version 3.0 only.
EE part : https://github.com/akeneo/pim-enterprise-dev/pull/5291

PIM-7839: Remove date of birth

---

CHANGELOG-2.3.md
src/Pim/Component/Catalog/ProductModel/Filter/ProductAttributeFilter.php
src/Pim/Component/Catalog/spec/ProductModel/Filter/ProductAttributeFilterSpec.php

In an import product definition you can "enable" or "disable" the comparison of the values of the product you try to update.
In "enable comparison" mode, if the value of an element is identical to the one in database, the product is skipped.
In "disable comparison" mode, we persist the data values as is.
For a regular "product" (not a variant product) the "parent" column in an import file must be absent or when the import file have mixed "product" and "variant product", the column "parent" is here but empty for "products".
**Problem**
When "disable comparison" is set to a product import job definition, and when you import a file containing mixed product, we try to update the product and set the parent value with an empty string. …

PIM-7926 - Set the parent attribute to null instead of an empty string

---

src/Oro/Bundle/PimDataGridBundle/Datagrid/Configuration/Product/SelectedAttributesConfigurator.php

Since the pagination of the *useable attributes as filter* this test fails due to missing refactoring. The filter format for the MassAction is not the same as the AjaxFilterFormat.
`-`: Not …

PIM-7527: Fix failing test with Mass Actions

---

src/Akeneo/UserManagement/Bundle/Controller/GroupController.php
src/Akeneo/UserManagement/Bundle/Resources/translations/jsmessages.en_US.yml
src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/action/delete-action.js

When a user group deletion error occurs, we now display a modal with the error message to the user.

PIM-7915: Display a modal on deletion error

---

tests/back/Integration/TestCase.php

The activated local for the user is the first activated locale in DB.
The problem is that this locale is loaded from the previous test.
Depending of the order of the tests, it can be a problem.
The solution is just to create the user after loading the DB.
| Tech Doc …

Fix failing test

---

CHANGELOG-1.7.md
src/Pim/Bundle/VersioningBundle/Builder/VersionBuilder.php
src/Pim/Bundle/VersioningBundle/spec/Builder/VersionBuilderSpec.php

Versioning does not differentiate between "0123" and "123" in text fields.

PIM-7940: Fix comparison in versioning system

---

tests/back/Channel/EndToEnd/Channel/ExternalApi/PartialUpdateListChannelEndToEnd.php

This endpoint should not exist.
It is to patch in mass the channel... 
One of the test is unstable because a background process is triggered in the previous (remove completeness of channel and locale).
There is a conflict with the previous test, because it REPLACE a line after deletion of the whole database.
Then, when load the dump, there is a primary key error because the line already exist.
It's very tricky to fix for no value at all.
| …

Remove useless unstable tests of thepatch of channels

---

src/Oro/Bundle/PimDataGridBundle/Query/Sql/ListProductGridAvailableColumnGroups.php
src/Oro/Bundle/PimDataGridBundle/Query/Sql/ListProductGridAvailableColumns.php

When a column is unknown in the datagrid configuration, it returns null by default which is incompatible with the concatenation with the first array. I force the method to return [] if column is not found. …

Force to return an array to avoid compilation error if one of the path is null

---

CHANGELOG-1.7.md
src/Pim/Bundle/UserBundle/Resources/views/User/update.html.twig
src/Pim/Bundle/UserBundle/Resources/views/User/view.html.twig

PIM-7953: Fix user profile back button and cancel button link on viewand update user template

---

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/catalog-volume/section.ts

This PR fixes the incorrect translation key on the catalog volume monitoring screen for mean/max

Fix missing translations on catalog volume screen

---

CHANGELOG-2.3.md
src/Pim/Bundle/EnrichBundle/Normalizer/EntityWithFamilyVariantNormalizer.php
src/Pim/Bundle/EnrichBundle/Normalizer/ProductModelNormalizer.php
src/Pim/Bundle/EnrichBundle/Normalizer/ProductNormalizer.php
src/Pim/Bundle/EnrichBundle/Resources/config/normalizers.yml
src/Pim/Bundle/EnrichBundle/spec/Normalizer/EntityWithFamilyVariantNormalizerSpec.php
src/Pim/Bundle/EnrichBundle/spec/Normalizer/ProductModelNormalizerSpec.php

It is not possible to display the PEF for a product model or a variant product if we have the following conditions:
image as label is an asset collection attribute
asset used in the product model/variant product is localized
selected language for the interface (in the user account) is not one of the activated locale
The issue comes from the "internal_api" normalizers of the product models and variant products:
- Pim\Bundle\EnrichBundle\Normalizer\ProductModelNormalizer
- Pim\Bundle\EnrichBundle\Normalizer\EntityWithFamilyVariantNormalizer
respectively.
The "image" property is normalized using the context locale (the locale of the user interface) when it should use the catalog default locale.
This same issue was already fixed for non-variant products in …

PIM-7961: Fix localizable assets used as main image for family and added to product product model

---

.gitignore
CHANGELOG-3.0.md
bin/check-services-instantiability

This PR adds a new command that checks container service instantiability.
A non instantiable service can mean either:
- dead code: the service is used nowhere, so it can be removed safely (and maybe the associated class)
- code non covered by tests: it's a real service, but no test uses this part, so the CI didn't failed.
For now, we have 16 dead (non instantiable) services on master.
Note: Maybe this PR should be an external tools as it's clearly not linked to the PIM itself.
| Added …

TIP-1018: Command to check services instantiability

---

CHANGELOG-3.0.md
src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml
src/Akeneo/Pim/Enrichment/Bundle/Resources/config/writers.yml
src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Connector/Writer/File/Flat/GenerateHeadersFromAttributeCodes.php
src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Connector/Writer/File/Flat/GenerateHeadersFromFamilyCodes.php
src/Akeneo/Pim/Enrichment/Component/Product/Connector/Processor/Normalization/ProductProcessor.php
src/Akeneo/Pim/Enrichment/Component/Product/Connector/Writer/File/Csv/ProductWriter.php
src/Akeneo/Pim/Enrichment/Component/Product/Connector/Writer/File/FlatFileHeader.php
src/Akeneo/Pim/Enrichment/Component/Product/Connector/Writer/File/GenerateFlatHeadersFromAttributeCodesInterface.php
src/Akeneo/Pim/Enrichment/Component/Product/Connector/Writer/File/GenerateFlatHeadersFromFamilyCodesInterface.php
src/Akeneo/Pim/Enrichment/Component/Product/Connector/Writer/File/Xlsx/ProductWriter.php
src/Akeneo/Tool/Component/Connector/Writer/File/AbstractItemMediaWriter.php
src/Akeneo/Tool/Component/Connector/Writer/File/FlatItemBuffer.php
tests/back/Pim/Enrichment/Integration/Product/Export/ProductQueryBuilder/ExportProductsByPriceCollectionsIntegration.php
tests/back/Pim/Enrichment/Integration/Storage/Sql/Connector/Writer/File/Flat/AssertHeaders.php
tests/back/Pim/Enrichment/Integration/Storage/Sql/Connector/Writer/File/Flat/GenerateHeadersFromAttributeCodesIntegration.php
tests/back/Pim/Enrichment/Integration/Storage/Sql/Connector/Writer/File/Flat/GenerateHeadersFromFamilyCodesIntegration.php
tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Processor/Normalization/ProductProcessorSpec.php
tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Writer/File/Csv/ProductWriterSpec.php
tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Writer/File/FlatFileHeaderSpec.php
tests/back/Pim/Enrichment/Specification/Component/Product/Connector/Writer/File/Xlsx/ProductWriterSpec.php
tests/legacy/features/pim/enrichment/product/mass-action/quick-export/quick_export_grid_context.feature

In order to get all possible columns in a flat export file, we fill all the products loaded from the DB with all possible values but with empty data.
This is pretty inefficient, as this creates a lot of value objects that will generate at the end the exact same headers.
This PR changes the algorithm to generate the headers only at the end of the export by collecting all the families of the products exported and when the writer is flushed, by generating all the headers for the collected families attributes information.
The benchmark shows that even with products totally filled this solution is still faster (1.4x times) and goes up to 6x times faster with products lightly filled.
Benchmark result (Reference catalog with 10k products in …

TIP-899: Improve product export performance by computing headers at the end

---

CHANGELOG-3.0.md
app/AppKernel.php
bin/check-services-instantiability
composer.json
composer.lock
src/Akeneo/Platform/CommunityRequirements.php
src/Akeneo/Platform/config/bundles/escape_wsse_authentication.yml
src/Akeneo/Platform/config/pim.yml
src/Oro/Bundle/ConfigBundle/Resources/config/services.yml

This PR cleanups the following services that are not instantiable:
- `escape_wsse_authentication`
- `liip_imagine.binary.loader.prototype.filesystem`
- `oro_config.form.config_subscriber`
In the case of the WSSE service, we remove as well the bundle and the SOAP requirements. WSSE is an extension of the SOAP protocol in order to secure Webservice access. This is not used by Akeneo PIM. …

TIP-1018: Removes SOAP and WSSE, cleanups Imagine and oro user

---

src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/attribute/create.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/attribute/edit.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/save-form.js

This PR fixes the redirect after save on attribute.
The main problem is that sometime we use {code} and sometimes we use {identifier} as route parameters and we use them in front to call some routes. Yeah, I know... It's a hell. …

Fix edit: add parameters for redirectRoute

---

composer.json

We use this library [here](https://github.com/akeneo/pim-community-dev/blob/master/src/Oro/Bundle/PimDataGridBundle/Normalizer/ProductAndProductModelRowNormalizer.php#L10) so we need it as a prod dependency.
**Note**: we didn't see the issue on CI because it is also an indirect dev dependency linked to phpspec.
`OK`: …

Add Webmozart assert library dependency

---

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/menu/help.html

The help center is now for multiple products (not only the PIM). The current link now goes to the index of the help center which is not the index of the PIM help center.
So I updated the link to be correct. …

Update help link with new url

---

CHANGELOG-2.3.md
src/Pim/Bundle/CatalogBundle/EventSubscriber/SaveFamilyVariantOnFamilyUpdateSubscriber.php
src/Pim/Bundle/CatalogBundle/spec/EventSubscriber/SaveFamilyVariantOnFamilyUpdateSubscriberSpec.php

This fix basically revert the fix done in this PR in the 2.0 branch : https://github.com/akeneo/pim-community-dev/pull/7368.
When a family is saved, a subscriber catch the save event and detach all the family variants, but it has a side effect on the API and generates this error :
```
request.CRITICAL: Uncaught PHP Exception Doctrine\ORM\ORMInvalidArgumentException: "A new entity was found through the relationship 'Pim\Bundle\CatalogBundle\Entity\Family#familyVariants' that was not configured to cascade persist operations for entity: Pim\Component\Catalog\Model\FamilyVariant@0000000053b43252000000001bcb5ec2. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this …
```

PIM-7965: do not call the detacher anymore

---

composer.lock
docker-compose.yml.dist

This PR update the `docker-compose.yml.dist` file to use the new `akeneo/node:8` image.

Use "akeneo/node" image in docker-compose

---

CHANGELOG-2.3.md
src/Pim/Bundle/EnrichBundle/Resources/views/CategoryTree/form.html.twig

The twig view is shared for products & assets categories so we need to use the `acl` key to apply the good ACL to the good page. 

PIM-7967: fix ACL on asset categories

---

tests/legacy/features/Behat/Context/Domain/Spread/ExportBuilderContext.php
tests/legacy/features/Context/DataGridContext.php
tests/legacy/features/pim/enrichment/product/export/export_products_by_multiselect.feature
tests/legacy/features/pim/enrichment/product/export/export_products_by_simpleselect.feature

When checking that a filter is not displayed, we were waiting the timeout of the spin (50 seconds).
So, this test took 4 minutes at doing nothing except waiting:
https://github.com/akeneo/pim-community-dev/blob/master/tests/legacy/features/pim/enrichment/product/datagrid/filtering/filter_products.feature#L53
Now it takes, 30 seconds.
| Micro Demo to the …

Don't wait 50 seconds when checking filter existence to ensure it is not displayed

---

tests/legacy/features/Context/Page/Base/Grid.php
tests/legacy/features/Context/WebUser.php

It should stabilize the tests, but not sure. Let's see and delete commit if it's useless.
After launching a job and then checking something in the UI, ES indexes are sometimes not up to date.
So, the scenario could fail as the result is not as expected.
Ok, that's the why of this fix.
But it's hard to reproduce these problems in local. For example, on my machine, I have to launch the test more than 20 times before failing. And it's hard to know if you really fixed it once you "fixed" it.
Here is a tip to reproduce it:
I modified on the fly the "refresh" parameter of the ES index, during the install of the fixtures:
```
curl -X PUT \
http://elastic:changeme@localhost:9211/behat_akeneo_pim_product_proposal/_settings \
-H 'Content-Type: …
```

Test circle pit stabilize ee

---

CHANGELOG-2.3.md
src/Pim/Bundle/PdfGeneratorBundle/Resources/views/Product/renderPdf.html.twig

Special chars were not correctly displayed (ex: "β" was displayed as a "?"). The HTML generated by the PIM was OK, the unicode support for DOMPDF was enabled. According to DOMPDF documentation, `the PDF needs access to a font that supports the characters used in the document` and Helvetica doesn't seem to support some characters like the "β", at least during the PDF rendering.
So I switched the font to use the recommanded one (DejaVu) and it fixed the problem. The font is very similar to the previous one so there is no real change in the generated PDF.
| Added …

PIM-7969: fix special chars in PDF export

---

upgrades/schema/Version_3_0_20180717082451_add_file_info_to_user.php

This PR sets the migration script adding the file_info field a little bit earlier as it is needs later.

Fix order of migration script

---

CHANGELOG-2.3.md
package.json

According to the documentation, we have to support nodejs `≥ 6.11.0 - 8.2.1`.
A recent dependency of dependency update needs only nodejs `≥ 8`.
We force this dependency to an older version in order to respect our requirements. …

Fix js dependencies

---

.circleci/config.yml

Prevent to trigger the approval job  on CircleCI when merging a pull request in master

---

.circleci/config.yml
src/Akeneo/Tool/Bundle/ElasticsearchBundle/IndexConfiguration/Loader.php
src/Akeneo/Tool/Bundle/ElasticsearchBundle/spec/IndexConfiguration/LoaderSpec.php
src/Akeneo/Tool/Bundle/ElasticsearchBundle/spec/IndexConfiguration/conf1.yml
src/Akeneo/Tool/Bundle/ElasticsearchBundle/spec/IndexConfiguration/conf2.yml

ES config loader is not correct when merging mappings configuration (from extensions for example):
- properties must be replaced to allow override
- dynamic_templates must be appended to allow adding attribute types
It fixes this kind of error: https://github.com/akeneo/ExtendedAttributeTypeBundle/issues/64
And I already modified this loader, fixing properties merging and screwing dynamic_templates merging in #8807 . :sob: 
This time, i take care of the two use cases. …

Fix ES config loader

---

src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filters-column.ts

This PR fixes the bug when selecting a column in the datagrid and displaying the filter columns

PIM-8016: Fix duplicate filters in search

---

src/Akeneo/UserManagement/Bundle/Resources/config/model/doctrine/Group.orm.yml
src/Akeneo/UserManagement/Bundle/Resources/config/model/doctrine/Role.orm.yml

Weird regression detected by migrating reference entities.

Fix smallint type for ORO tables like in 2.3

---

src/Akeneo/Pim/Enrichment/Component/Product/Grid/ReadModel/Row.php

Remove strict typehint on $image attribute as in EE it could be an Asset (ReferenceData)

Remove strict typehint on $image attribute as in EE it could be an Asset (ReferenceData)

---

src/Akeneo/UserManagement/Bundle/EventListener/RemoveRoleSubscriber.php
tests/back/UserManagement/Integration/Bundle/RemoveRoleIntegration.php
upgrades/schema/Version_3_0_20180131154710_add_role_user_if_needed.php

the ROLE_USER is not removable + we create it in the migration if needed

Fix ROLE_USER removal

---

.gitignore
CHANGELOG-2.3.md
src/Pim/Bundle/CatalogBundle/EventSubscriber/AttributeCreationSubscriber.php
src/Pim/Bundle/CatalogBundle/Resources/config/event_subscribers.yml
src/Pim/Bundle/CatalogBundle/spec/EventSubscriber/AttributeCreationSubscriberSpec.php
src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/attributes.js

When you add attributes in an attribute groups, attributes don't have sort order.
=> Now, when you save a new attribute, by default the sort order is incremented in terms of the higher sort order in the attribute group. It helps to sort by sort order in front.
When you fetch attributes by identifiers in front, at the end of the fetchByIdentifers() method in the base fecther, we do a _.pluck(attributes, identifiers). So the array of attributes it returns is sorted by same order than the order of the identifiers you give.
=> Now we sort attributes we fetched first by sort order. However, sometimes there is no so we sort by id. We sort by id because it is the way attributes are shown in the attribute group when there is no sort order. So …

PIM-8008:Fix attribute sort order in PEF

---

CHANGELOG-2.3.md
src/Pim/Bundle/EnrichBundle/Resources/public/js/pim-attributeoptionview.js
src/Pim/Bundle/EnrichBundle/Resources/public/templates/attribute-option/show.html
src/Pim/Bundle/UIBundle/Resources/public/less/components/grid/Grid.less

When the attribute options grid is sortable the content of the row was not selectable.
Now to move the row the cursor is on the icon and not on the full row.

PIM-8007: Content of sortable attribute options are now copyable

---

CHANGELOG-2.3.md
src/Pim/Bundle/EnrichBundle/Resources/public/js/datagrid/action/edit-in-modal-action.js
src/Pim/Bundle/EnrichBundle/Resources/public/js/family/form/family-variant.js
src/Pim/Bundle/UIBundle/Resources/public/less/lib/modal.less

Before this bug, when you go on the pef and you open a manage asset modal, and then you go on the modal to edit a family variant there were a double cancel button, a big footer and an OK button in it. Those elements were not part of the "normal" modal.
I didn't find the bug but I found a way to remove those elements when they appear. …

PIM-7943: Fix duplicate popin mask in family variant edit form

---

composer.json

- Fix the dev-master alias
- We dont' need aliases on **comparable** branches
Documentation: https://getcomposer.org/doc/articles/aliases.md

Fix 3.0 composer aliases

---

CHANGELOG-2.0.md
src/Akeneo/Bundle/ElasticsearchBundle/Client.php
src/Pim/Bundle/CatalogBundle/EventSubscriber/Category/UpdateIndexesOnCategoryDeletion.php
src/Pim/Bundle/CatalogBundle/Resources/config/event_subscribers.yml
src/Pim/Bundle/CatalogBundle/Resources/config/queries.yml
src/Pim/Bundle/CatalogBundle/tests/integration/Classification/UpdateIndexesOnCategoryDeletionIntegration.php
src/Pim/Bundle/CatalogBundle/tests/integration/Elasticsearch/IndexConfiguration/AbstractPimCatalogTestCase.php
src/Pim/Component/Catalog/Category/GetDescendentCategoryCodes.php
src/Pim/Component/Catalog/tests/integration/Category/CategoryTreeFixturesLoader.php
src/Pim/Component/Catalog/tests/integration/Category/GetDescendentCategoryCodesIntegration.php

When a category is deleted the products and product models under it still contains the category in ES, so if it was the last category of the current tree they were linked to, you can never find them again because they won't appear in "unclassified". Same issue for the exports.
This PR fixes that by updating the indexes after the deletion.
For more details about the implementation, see the description of the subscriber.
We chose to call the ES API directly and not do a full save + reindex products because it's way faster and save us from adding a new job (very costly in a patch).
| Added Specs …

PIM-7889: Update ES indexes on category deletion

---

src/Akeneo/UserManagement/Bundle/Resources/config/datagrid/user.yml
src/Akeneo/UserManagement/Component/Normalizer/UserNormalizer.php
tests/legacy/features/user-management/user/edit_my_account.feature

During the PEFization of the user form, the view mode has been removed. But we need it when the user has the "view user" rights only.
The view form still exists, it's just never used currently. By removing the ACL check on the grid, a user without edit rights can still navigate to the edit route, but the front controller instantiates either the edit form or the view form depending on the permissions. This is possible thanks to the normalizer.
"Sa tombe en marche" like @pierallard would say.
This behavior is different from what was done in < 2.3 where you were forced to pass by the view mode to access the edit form. **Now the view mode is used only when you don't have the edit rights**.
Validated by @bgouraud.
**Definition Of Done (for …

PIM-8025: Bring the user view mode back to life

---

CHANGELOG-3.0.md
src/Akeneo/Pim/Enrichment/Component/Product/Completeness/CompletenessGenerator.php
tests/back/Pim/Enrichment/Integration/Completeness/AbstractCompletenessTestCase.php
tests/back/Pim/Enrichment/Integration/Completeness/UpdateMissingAttributesIntegration.php

Fix completeness on Product save. Since completeness refactor (we update completeness instead of removing and insert new one) missing attributes were not updated.
Fix `assertMissingAttributeCodes` in integration tests. There was an `assertEquals(sort(something), sort(another))` but sort returns bool so it was always true. :clap:  …

PIM-8020: Fix wrong count on missing required attributes in the completeness

---

composer.json

We need to use the `dev-3.0` alias in our CI builds.

Add composer dev-3.0 alias

---

CHANGELOG-2.3.md
src/Akeneo/Bundle/ElasticsearchBundle/IndexConfiguration/Loader.php
src/Akeneo/Bundle/ElasticsearchBundle/spec/IndexConfiguration/LoaderSpec.php
src/Akeneo/Bundle/ElasticsearchBundle/spec/IndexConfiguration/conf1.yml
src/Akeneo/Bundle/ElasticsearchBundle/spec/IndexConfiguration/conf2.yml

ES config loader is not correct when merging mappings configuration (from extensions for example):
- properties must be replaced to allow override
- dynamic_templates must be appended to allow adding attribute types
It's a backport of #9423 

PIM-8050: Fix ElasticSearch mappings loader

---

composer.json
composer.lock

As stated [here](https://github.com/doctrine/orm/releases/tag/v2.6.0), 2.5.14 is and will be the last patch of Doctrine ORM 2.5.
That would be cool if our 3.0 LTS could benefit of it.
Wait for https://github.com/akeneo/pim-community-dev/pull/9528 to be merged (To not conflict with the `composer.lock`)

Upgrade Doctrine ORM to latest patch

---

CHANGELOG-3.0.md
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/mass-edit/form/product/associate.js

This PR updates the template for the mass action product association modal to fix the broken display. 

PIM-8019: Fix broken bulk product association modal

---

CHANGELOG-2.3.md
src/Pim/Bundle/CatalogBundle/Elasticsearch/Filter/Field/SelfAndAncestorFilterLabelOrIdentifier.php
src/Pim/Bundle/CatalogBundle/Resources/config/query_builders.yml
src/Pim/Bundle/CatalogBundle/Resources/config/serializers_indexing.yml
src/Pim/Bundle/CatalogBundle/spec/Elasticsearch/Filter/Field/SelfAndAncestorFilterLabelOrIdentifierSpec.php
src/Pim/Bundle/CatalogBundle/tests/integration/PQB/Filter/Field/SelfAndAncestorFilterLabelOrIdentifierIntegration.php
src/Pim/Bundle/EnrichBundle/Connector/Reader/MassEdit/FilteredProductAndProductModelReader.php
src/Pim/Bundle/EnrichBundle/Connector/Reader/MassEdit/ProductAndProductModelReader.php
src/Pim/Bundle/EnrichBundle/Doctrine/ORM/Query/CountImpactedProducts.php
src/Pim/Bundle/EnrichBundle/ProductQueryBuilder/ProductAndProductModelQueryBuilder.php
src/Pim/Bundle/EnrichBundle/spec/Connector/Reader/MassEdit/FilteredProductAndProductModelReaderSpec.php
src/Pim/Bundle/EnrichBundle/spec/Connector/Reader/MassEdit/ProductAndProductModelReaderSpec.php
src/Pim/Bundle/EnrichBundle/spec/Doctrine/ORM/Query/CountImpactedProductsSpec.php
src/Pim/Bundle/EnrichBundle/tests/integration/Doctrine/ORM/Query/CountImpactedProductsIntegration.php
src/Pim/Component/Catalog/Normalizer/Indexing/Product/PropertiesNormalizer.php
src/Pim/Component/Catalog/Normalizer/Indexing/ProductAndProductModel/ProductModelPropertiesNormalizer.php
src/Pim/Component/Catalog/Normalizer/Indexing/ProductAndProductModel/ProductPropertiesNormalizer.php
src/Pim/Component/Catalog/spec/Normalizer/Indexing/ProductAndProductModel/ProductModelPropertiesNormalizerSpec.php
src/Pim/Component/Catalog/spec/Normalizer/Indexing/ProductAndProductModel/ProductPropertiesNormalizerSpec.php
src/Pim/Component/Catalog/tests/integration/Normalizer/Indexing/ProductAndProductModelIndexingIntegration.php

When searching on "label or identifier" in the datagrid, and selecting all the results for a mass-action, the filters used are passed as they are to the batch job that will perform the mass action.
We then face an issue with product models and variant products, as the datagrid PQB returns only the elements of one level: those containing the value you are searching for.
But in the mass edit, we need to return both the element containing the value and its children, as the effect of the mass action could be performed on them (for instance, the search returns a product model, but the action is to activate products, so it will be performed on the variant products, not on their parents).
For instance, consider that the following example, where the label is on the sub product model:
| Data we …

PIM-7939: Search on ancestors labels and codes

---

src/Pim/Bundle/EnrichBundle/Resources/public/js/router.js

PR to avoid this kind of comments... https://twitter.com/jonathan_pollak/status/1093458003108478978
Right now, we catch every exceptions happening during the rendering of a page to display a custom error. Problem is: if an error occurs during runtime (but not linked to the http request itself) it can create 200 errors (which doesn't makes sense)
| Micro …

Remove weird 200 error

---

CHANGELOG-3.0.md
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/base/general.less

The space disappeared in the labels because the font is too small.
I manually added a padding between label and emphasis elements.

PIM-8144: Fix space on label required

---

CHANGELOG-3.0.md
src/Akeneo/Platform/Bundle/UIBundle/DependencyInjection/Configuration.php

Previously, default system locale was "Catalan", because "en" was not found.
Now, default system locale is "en_US" to be able to show "English (United States)" again.

PIM-8129: Fix default system locale

---

CHANGELOG-3.0.md
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/FormContainer.less

There was 2 rules defined eating themselves.
I added a constraint to avoid this.

PIM-8146: Fix centered alignment on drag & drop fields

---

CHANGELOG-3.0.md
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/lib/bootstrap.switch.less

Boolean fields and info box were in the same place
https://drive.google.com/open?id=1utf3RXSQH7dv7GPfvRHqlQjy0sHXw4Kc
I added a space on the right to align with every other fields.

PIM-8147: Fix design issue on boolean fields

---

CHANGELOG-3.0.md
upgrades/schema/Version_3_0_20180717082452_migrate_avatars.php
upgrades/schema/Version_3_0_20180823184342_switch_to_utf8mb4.php

We cannot update the user because of a migration error.
The `image` should be replaced by `file_info_id` and set to null.

Fix avatars migration

---

CHANGELOG-2.0.md
features/category/list_categories.feature
src/Pim/Bundle/EnrichBundle/Resources/translations/messages.en.yml

Fix the label of the category tree creation button.
| Added legacy Behats               | Ok

Fix category tree label

---

CHANGELOG-3.0.md
src/Akeneo/Platform/Bundle/DashboardBundle/Resources/views/Dashboard/index.html.twig
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/controller/user.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/user-main-image.ts
src/Akeneo/UserManagement/Component/Updater/UserUpdater.php

This PR fixes 3 bugs:
- User can now delete its avatar (before, it does nothing)
- When user changes its avatar, it's not mandatory to reload the page to show changes on user navigation button
- It displays the user image in Dashboard page.

PIM-8053: Various fixes on Avatars

---

CHANGELOG-3.0.md
src/Akeneo/Pim/Enrichment/Bundle/Resources/config/command.yml
src/Akeneo/Tool/Component/StorageUtils/Cursor/Paginator.php

The cursor paginator used to mass publish products called the method `$cursor->next()` at a bad moment. It resulted that a product entity was hydrated but not returned by the paginator between each loop. The Doctrine entity manager is cleared between each page, so this product is detached when it should not, because it's returned in the next page.
I took the opportunity to fix the definition of the Paginator factory to use the same value for the page size that the cursor factory.
| Added …

PIM-8135: Fix cursor paginator sequence

---

CHANGELOG-2.3.md
Makefile
src/Pim/Bundle/EnrichBundle/Controller/Rest/AttributeController.php

I don't know why it was put at the end, but if the parameters `options` was passed to the controller in addition of another option if wasn't taken in account.
No spec existed before (should I add some?). I won't add behat as it is not critical at all. …

PIM-8131 labels cannot be used for search in bulk action

---

CHANGELOG-3.0.md
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/attribute/form/edit-form.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/controller/user.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/edit-form.js
src/Akeneo/UserManagement/Bundle/Resources/config/form_extensions/edit.yml
src/Akeneo/UserManagement/Bundle/Resources/translations/jsmessages.en_US.yml
src/Akeneo/UserManagement/Component/Updater/UserUpdater.php
tests/legacy/features/user-management/role/edit_user_role_assignations.feature

- Groups are not mandatory (a user can have 0 group)
- State was missing
- Avoid scrolltop when form is re-rendered (to be validated with PO)

PIM-8157: Errors on user edit

---

bin/docker/pim-dependencies.sh
bin/docker/pim-front.sh
bin/docker/pim-initialize.sh

I fixed shell scripts as well to fail as soon as a command fail (`set -e`).
It is a best practice in shell (better than `&&` for each command).

GITHUB-9628: make the shell script failing when a shell command return a non zero code

---

CHANGELOG-2.0.md
src/Pim/Bundle/EnrichBundle/Resources/public/js/filter/attribute/attribute.js

When you add a filter on a localisable attribute in the export builder, you cannot change the selected locale.
It's a backport of a fix done in 2.3 : https://github.com/akeneo/pim-community-dev/commit/629258992516c37964ccd1e63a4565ccdea07b56#diff-630631ab716dc8283c33f67b00849fbf
| Tech …

PIM-8141: Fix attribute filter selection in export profile edition

---

CHANGELOG-3.0.md
src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/jsmessages.en_US.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/form-modal.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/mass-edit/form/product/associate.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/pim-dialog.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/meta/groups.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/bootstrap-modal/bootstrap-modal.js

Some crosses were deleted in 3.0.
The rule is that we always show the cross. So we removed the condition.
This PR includes some missing translations (boyscoutism)

PIM-8164: Always show cross on modals

---

CHANGELOG-2.3.md
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/job_instance/xlsx_product_export_edit.yml

Removing an ACL that has nothing to do with exports

PIM-8155: Fix bad ACL set on xlsx product export edit form

---

CHANGELOG-2.3.md
src/Pim/Bundle/EnrichBundle/Controller/Rest/AssociationTypeController.php

The ACL on the internal API end-point to get an association type prevents to add associations on a product if the user doesn't have the right.
Seen with PO, this ACL shouldn't be applied on this end-point.

PIM-8056: Remove bad ACL on the internal API end-point that get an association-type

---

CHANGELOG-3.0.md
src/Akeneo/Pim/Structure/Bundle/DependencyInjection/AkeneoPimStructureExtension.php
src/Akeneo/Pim/Structure/Bundle/Resources/config/commands.yml

The command is not registered anymore because it has been moved to better reflect the bounded contexts. I chose to not move the command to keep the good organisation and I register it as a service.

PIM-8167: register command "pim:reference-data:check"

---

.circleci/config.yml
.circleci/docker-compose.override.yml.dist
.circleci/run_behat.sh

**Execute php cs and acceptance tests even if phpspec step is failing**
As documented in Circle CI, a failing step prevent the next one to be executed.
So we add this key to prevent that behavior:
```
when: always
````
**https://github.com/akeneo/pim-community-dev/issues/9506 https://github.com/akeneo/pim-community-dev/issues/9507 Improve the naming of the junit files by using scenario name instead of only an uuid**
Note: We still use uuid to avoid any conflict if some feature files have the same name. 
Before:
After:
**https://github.com/akeneo/pim-community-dev/issues/9466 Improve the render of the behat scenarios by putting all junit files in the same directory**
See screenshot above to know how it works.
Note: with the new suite Franklin in 3.0, behat generates two files `all.xml` and …

Add screenshots, logs and improve test render for Circle CI

---

.circleci/config.yml
.circleci/find_phpunit.sh
.circleci/run_phpunit.sh
composer.lock

We now decided to use PHPUnit to generate the tests we want to execute because by using "*Integration.php" it is very unconvenient, you can't have abstract that is named the same etc... And, moreover what is better than PHPUnit to list PHPUnit tests to launch? :P
| Tech Doc …

GITHUB-9451: Use PHPUnit to list tests

---

CHANGELOG-3.0.md
src/Akeneo/Platform/CommunityRequirements.php

MySql version can be in the form '5.7.22-log' and we should accept this valid version.
See https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_version

PIM-8168: accept MySql version with suffix in requirements check

---

CHANGELOG-3.0.md
src/Akeneo/Tool/Component/Console/CommandLauncher.php

If we have spaces in kernel root, the command launcher try to launch the bad command, like 
`/usr/bin/php /srv/pim pim/bin/console my:command`
After the fix, the command will be:
`/usr/bin/php '/srv/pim pim'/bin/console my:command` which is executable.

PIM-8152: accept spaces in kernel root dir when executing commands

---

CHANGELOG-3.0.md
src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/ProductGrid/ProductModelImagesFromCodes.php
tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductGrid/FetchProductModelRowsFromCodesIntegration.php
tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductGrid/ProductGridFixturesLoader.php

We display images in the datagrid.
Images is the image of the value in the attribute "attribute as main picture", defined in the family.
When we have product models, the problem is pretty complex as the attribute can be at any level.
Here the different combination:
- if attribute as main picture is in common attributes, we display the images of the root product model (with 1 or 2 levels) :heavy_check_mark:  
- if it's at level 1, and there are 2 levels, we display the image of the first product model having an image :red_circle: 
- if it's in at level 1, and there are 1 level, we display the image of the variant product (because level 1 is variant product) :heavy_check_mark: 
- if it's in at level 2, and there are 2 levels, we display …

PIM-8051: display the image value of a product model when the image is in a subproduct model

---

.circleci/config.yml
tests/legacy/features/Pim/Behat/Extension/PimFormatter/Output/Node/EventListener/PimFeatureElementListener.php
tests/legacy/features/Pim/Behat/Extension/PimFormatter/Output/Node/Printer/PimScenarioPrinter.php

Sorry, two PR in one but it's the same files to modify and it's pretty long to test.
**https://github.com/akeneo/pim-community-dev/issues/9511 generate an error in Circle CI when there is a JS error**
When there is a JS error, the build is red in circle CI, because the return code of the command is 1.
But the error is not displayed at all in the result and it seems that there are no failed behat.
This i confusing as the build is red... so you have to search in the logs the error.
This is  because Circle CI does not parse correctly the Junit output files.
Correctly parsed:
```
<testcase name="tests/legacy/features/update/add_association.feature:6"  file="tests/legacy/features/update/add_association.feature:6" status="failed" …
```

GITHUB-9511: generate an error in Circle CI when there is a JS error in a behat and split by timing

---

CHANGELOG-2.0.md
src/Pim/Bundle/EnrichBundle/Controller/Rest/AttributeOptionController.php
src/Pim/Bundle/EnrichBundle/Resources/config/routing/attributeoption.yml
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/field/multi-select-field.js

When we have a lots of options in the multi-select attribute, we can have an error because of the URI being too long. 
This fix aims to change the call for options from http GET to POST, when we will not have this kind of limitation.
Related to #3876
`OK`: Done / …

PIM-8174: Fix too long URI for multi-select with a lots of options

---

CHANGELOG-2.3.md
src/Akeneo/Bundle/ElasticsearchBundle/Command/ResetIndexesCommand.php
src/Akeneo/Bundle/ElasticsearchBundle/spec/Command/ResetIndexesCommandSpec.php

A customer has a problem on its proposal.
In order to fix that, we need to re-index all the ES of the PIM.
But he has several thousands of products and the problem is not on the product.
So, we added the possibility to re-index only a specific index to fix this kind of problems on a production environment.
```
bin/console akeneo:elasticsearch:reset-indexes -i akeneo_pim_product -i akeneo_pim_product_model
``` …

PIM-8175: add the possiblity to filter on one or several index names when resetting ES indexes

---

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/HorizontalNavtab.less

Add a new sticky Modifier and Element on the HorizontalNavtab styles.
Used by Franklin Insights attributes mapping page.
`::before` and `::after` are there to set a `background-color` on the Element `padding`.
Hard-coded `top` values are specifics to the attributes mapping page for now, awaiting a generic solution.
| Migration …

DAPI-22: Add sticky Modifier and Element on HorizontalNavtab style

---

tests/legacy/features/pim/structure/attribute-group/list_attribute_groups.feature

Fix https://github.com/akeneo/pim-community-dev/issues/9700
**Problem:**
- Step 1 : We go on the channel page in the UI.
- Step 2 We add german locale to the channel, but not through the UI!  `And I add the "german" locale to the "tablet" call directly the channel repository and saver.
- Step 3: Then we save the channel through the UI, but the "german" locale is not in the channel in the UI, reverting what is done at the previous step...
Then, we try to use the german locale a the locale of the user.
Most of the time it works, because steps 3 is not finished in the background, so the channel has the locale...
**How to reproduce:**
Impossible to reproduce the problem (even in an infinite loop).
I had to carefully read the code.
We just …

GITHUB-9700: fix unstable test

---

CHANGELOG-3.0.md
src/Akeneo/Pim/Structure/Bundle/Doctrine/ORM/Repository/InternalApi/AttributeSearchableRepository.php
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/family/form/attributes/toolbar/add-select/attribute/select.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/family/mass-edit/toolbar/add-select/attribute/select.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/i18n.ts

When adding new attribute(s) to a family by search, we sent a request with the search term AND all the attributes already in the family in an `excluded_identifiers` array. But when there are a lot of attributes in the family, we end up with a very large array of POST parameters that goes beyond the PHP `max_input_vars` limit.
This PR will fix the issue by sending only the family code instead of all the family attributes. The attributes are then excluded server side. …

PIM-8178: fix family attributes selector

---

src/Oro/Bundle/AsseticBundle/Command/OroAsseticDumpCommand.php
src/Oro/Bundle/AsseticBundle/DependencyInjection/OroAsseticExtension.php
src/Oro/Bundle/AsseticBundle/Factory/OroAssetManager.php
src/Oro/Bundle/AsseticBundle/Node/OroAsseticNode.php
src/Oro/Bundle/AsseticBundle/Parser/AsseticTokenParser.php
src/Oro/Bundle/AsseticBundle/Resources/views/Assets/oro_css.html.twig
src/Pim/Bundle/EnrichBundle/Resources/views/index.html.twig

To move the Onboarder UI to the pim-onboarder bundle we need to apply two different styles on the PIM (with different colors, etc.), the overridden style being in the bundle.
We didn't want to add a top-level css class because it would mean to duplicate the less in the bundle.
We chose instead to find a way to build several stylesheets (one with the native style, and another with the native style plus some overrides) and switch between them when needed.
The issue is that the less compilation is handled by the Oro Assetic bundle and has been designed to always generate only one css file from the less.
I chose to twist a concept introduced by Oro Assetic : the asset groups. Originally it's used for debugging purpose. You can specify some …

AOB-376: Modify Oro Assetic to be able to compile several css stylesheets

---

CHANGELOG-3.0.md
src/Akeneo/Platform/Bundle/AnalyticsBundle/Resources/views/Update/last_patch.html.twig

Also see https://github.com/akeneo/pim-enterprise-dev/pull/5812

PIM-8189: Fix display of new patch availability on dashboard

---

CHANGELOG-2.3.md
src/Pim/Bundle/EnrichBundle/Normalizer/EntityWithFamilyVariantNormalizer.php
src/Pim/Bundle/EnrichBundle/spec/Normalizer/EntityWithFamilyVariantNormalizerSpec.php

Before, the order for metric values was only do by string comparison.
["10 Kilogram"] was < ["100 Kilogram"].
Now, the quantity is extracted as a float, so it's ordered like this:
["Kilogram", 10] > ["Kilogram", 100]

PIM-7966: Fix variant product order on variant product navigation in case of metric variations

---

src/Akeneo/Platform/Bundle/DashboardBundle/Resources/views/Dashboard/index.html.twig

Very minor bug to fix. In dev mode, we can have a 500 error because a twig variable is not defined.
After the fix, no error anymore, but a screen not very usefull anyway

PIM-8210: Fix twig variable not defined

---

CHANGELOG-2.3.md
src/Pim/Component/Connector/Archiver/ArchivableFileWriterArchiver.php
src/Pim/Component/Connector/Archiver/WriteStreamZipArchiveAdapter.php
src/Pim/Component/Connector/Archiver/ZipFilesystemFactory.php
src/Pim/Component/Connector/spec/Archiver/ArchivableFileWriterArchiverSpec.php

> Note: we used feedback of @mmetayer on his previous work on this: no close/reopen, no memory leak; so it seems we found the best of both worlds here.
We override the flysystem/zip-archive-adapter to use `ZipArchive::addFile` (which internally uses https://github.com/nih-at/libzip/blob/4c612cb79672016c0f077b9c511e77df82b35023/lib/zip_source_filep.c#L484
Tested by trying to import a 100MB file using 1MB of max php ram:
```
dd if=/dev/urandom bs=10M count=10 of=/tmp/test
php -d memory_limit=1M zip.php
```
```php
// zip.php
<?php
use Pim\Component\Connector\Archiver\WriteStreamZipArchiveAdapter;
use League\Flysystem\Config;
require(__DIR__.'/vendor/autoload.php');
$a = new WriteStreamZipArchiveAdapter('/tmp/test.zip');
$a->writeStream('test', fopen('/tmp/test', 'r'), new Config); …
```

PIM-8197 Use ZipArchive::addFile to avoid too much ram consumption

---

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/ProjectWidget.less

Add a loadingMask Element to the ProjectWidget styles.
Required by: https://github.com/akeneo/pim-enterprise-dev/pull/5806

DAPI-29: Add loadingMask Element to ProjectWidget styles

---

bin/docker/pim-dependencies.sh
composer.lock

- composer update to have the correct Twig version (twig 1.38.0 breaks the PIM)
- docker must use composer install and not composer update

Update Twig version

---

CHANGELOG.md
src/Akeneo/Pim/Enrichment/Bundle/Resources/config/serializers_indexing.yml
src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Indexing/ProductAndProductModel/ProductPropertiesNormalizer.php
tests/back/Pim/Enrichment/Integration/Normalizer/Indexing/ProductAndProductModelIndexingIntegration.php
tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/Indexing/ProductAndProductModel/ProductPropertiesNormalizerSpec.php

This PR adds a way to index additional product properties without having to extends or rewrite the existing product properties normalizer. We needed this to index the franklin insights status of products (subscribed or not) and be able to filter on this data in the search form.
Everything is done by the dependency injection of Symfony : any service with the correct tag will be injected in the product properties normalizer. With this way there is no BC break in the community and it will allow us in the future to index more properties. …

DAPI-19: ProductPropertiesNormalizer accepts optional normalizers to be able to index additional product properties

---

src/Oro/Bundle/PimDataGridBundle/tests/Integration/Query/Sql/ListProductGridAvailableColumnGroupsIntegration.php
src/Oro/Bundle/PimDataGridBundle/tests/Integration/Query/Sql/ListProductGridAvailableColumnsIntegration.php

Those tests must not be ran with the EE dependency injection because the EE adds a new column in the datagrid and has dedicated tests.

DAPI-20: run ListProductGridAvailableColumnGroupsIntegration and ListProductGridAvailableColumnsIntegration integration tests only in CE

---

Makefile

Before reviewing this PR you should have a look to https://github.com/akeneo/pim-community-dev/pull/9677
What the command pim:installer:asset does ?
* Dump require JS paths
* Dump JS form extensions
* Copy all assets from bundles to web folder
* Dump JS translations
* Dump js routes
Do I need to run these commands every time? No!
* I only need to dump require JS paths if I changed/added any `requirejs.yml` file.
* I only need to dump JS form extensions if I changed/added any `form_extensions.yml` file.
* I only need to dump copy assets if I changed/added any file located `/Resources/public/` from my bundle.
* I only need to dump JS translations if I changed/added any `jsmessages*.yml`
* It depends on the routes stored in the Symfony container, so unfortunately we need to …

Use the power of makefile to install the pim assets

---

CHANGELOG-2.0.md
src/Oro/Bundle/DataGridBundle/Extension/MassAction/MassActionParametersParser.php
src/Pim/Bundle/EnrichBundle/Resources/config/routing/mass_edit/rest.yml
src/Pim/Bundle/EnrichBundle/Resources/public/js/controller/mass-edit.js

It's a "simple" GET to POST query change. A little bit crappy, but no other solution were found.

PIM-8212: Allow mass edition of hundreds of manually selected elements in a grid (prevent 414 Too Long URI)

---

src/Pim/Bundle/ApiBundle/Resources/config/routing/product_model.yml

This route is in conflict with an API route on EE: `pimee_api_product_model_draft_get`
The fix is quite ugly and will not allow the use of a draft suffix in SKU, but i cannot change an API route.

PIM-8222: do not accept /draft in a product SKU

---

CHANGELOG-3.0.md
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/lib/dropdown.less

This PR fixes the 'missing' datepicker on the mass edit of date attributes. This bug was caused by the modal z-index being greater than the datepicker one (changed here: https://github.com/akeneo/pim-community-dev/commit/e979b5d4ee3f07285478e89564f45970348d18e4#diff-29deae46280c716e5de2e4532c7dff32R13). …

PIM-8136: Fix display order of datepicker

---

src/Pim/Bundle/CatalogBundle/Doctrine/MongoDBODM/CompletenessGenerator.php
src/Pim/Component/Catalog/Model/FamilyInterface.php
src/Pim/Component/Catalog/Repository/FamilyRepositoryInterface.php

When we change the requirement of an attribute in a family, it is not always removed from the table. It can be present with a `required = false` property.
But when we fetch requirements for completeness, we didn't test for `required` and these non required attributes were taken into account in the completeness.
This PR solves the issue by testing for the `required` property before adding the attribute in the completeness calculation. …

PIM-8228: fix incorrect completeness

---

CHANGELOG-3.0.md
src/Akeneo/UserManagement/Bundle/Controller/ResetController.php

PIM-8128: Fix the display of reset password confirmation message

---

CHANGELOG-3.0.md
src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/column-selector.ts

This PR fixes a bug where columns that were loaded by a view disappeared when the user added a new column using the selector on the datagrid. 
When a view is loaded, we take the columns loaded from the datagrid metadata which don't include a 'code' property but instead a 'name'. In the available-columns endpoint this property is called 'code'. We normalize it in the column selector but the normalized value was not being used when the data was merged. So in the end, adding a column updated the datagrid state with something like `name, updated, image,,,,` because some columns had an undefined code. 
| Added …

PIM-8227: Get columns by code/name in selector

---

CHANGELOG-2.3.md
src/Pim/Component/Catalog/Validator/Constraints/OnlyExpectedAttributesValidator.php

This PR prevent Nesting level too deep – recursive dependency exception.
Explained in #9023 issue

PIM-8176: Fix OnlyExpectedAttributesValidator

---

CHANGELOG-2.3.md
src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/field/text.html

When the text field is disabled and the text too long we can not see all the text. We added a title to be able to see the full text on hover.

PIM-8230: Show on hover information for a read-only text in product edit form

---

CHANGELOG-3.0.md
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/CompletenessPanel.less

This PR fixes the display of long channel labels in the completeness widget on the dashboard.
Before
After

PIM-8196: Fix long channel labels on completeness widget

---

CHANGELOG-3.0.md
src/Akeneo/Pim/Structure/Bundle/Controller/InternalApi/AttributeController.php
tests/back/Pim/Structure/EndToEnd/Attribute/InternalApi/SearchAttributeEndToEnd.php

Query params for `options` are not working on the internal API that fetch the attribute collection.
Example:
Any call to `/rest/attribute` with a query param of `options[identifiers][]=name` will not get a result for the name identifier only, but will get a list of all the attributes.
Linked to #9621 …

PIM-8237: Fix the query params on search attributes

---

CHANGELOG-2.3.md
src/Pim/Bundle/EnrichBundle/Resources/public/js/form/common/save-buttons.js

Fix the initialize method of save-buttons.js to correctly reset its internal state.
The internal events object was keeping dangling references to previously added events.

PIM-8245: Fix initialize of save-buttons extension

---

CHANGELOG-3.0.md
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/requirejs.yml

This PR fixes an issue where `pim/model/attribute` was not found if it was declared after `pim/model/attribute-group`. We had a similar issue for JS files which was solved by using `$` to denote an exact match for searching module aliases. We have the same issue with TS files now. This fix will allow the installation to work while we fix the underlying problem. At the moment this problem breaks installations that depend on pim-enterprise-standard.  …

Fix load order of pim/model/attribute in requirejs

---

composer.json
composer.lock
phpstan.neon
src/Akeneo/Pim/Enrichment/Bundle/Command/RemoveWrongBooleanValuesOnVariantProductsBatchCommand.php

This extension allows us to identify : 
- undefined Symfony services
- services that are declared private but called publicly from the container
Also, this will be needed as soon as we'll try to reach level 2 of phpstan.
For instance, if have something like:
```php
$someService = $container->get('some-service-id');
$someService->someMethod();
```
Without the extension, phpstan will raise an error because it does not know what is `$someService` and therefore if the method `someMethod()` exists. With the extension, phpstan will detect `$someService` is an instance of the class `SomeAwesomeService` and therefore will be able to check if the method `someMethod` exists.

Upgrade Phpstan to install Symfony's extension

---

CHANGELOG-3.0.md
src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filters-selector.ts

**Problem:**
Filter on families in the product grid.
Filter on identifier in the product grid.
Add a new filter: filters on families and identifier are reset on the screen (but still applied for the research).
**Technical explanation:**
When adding a filter in 3.0, we trigger the global render of all enabled filters.
There are two main steps:
1. the filter module render https://github.com/akeneo/pim-community-dev/blob/3.0/src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filters-selector.ts#L108
2. the restore of the filter state https://github.com/akeneo/pim-community-dev/blob/3.0/src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filters-selector.ts#L132
When doing the first step, sometime, it changes the …

PIM-8241: Do not reset filter display when adding a new filter in the product datagrid

---

CHANGELOG-2.3.md
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/meta/family-variant.js

Fixes "undefined" displayed in the product form if the variant family does not have a label for the selected context locale.

PIM-8251: display variant family code in sidebar if no translated label

---

CHANGELOG-3.0.md
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/lib/jquery.multiselect.less

PXD-98: Fix panel content size for filters selector column

---

tests/back/Acceptance/AttributeOption/InMemoryAttributeOptionRepository.php
tests/back/Acceptance/spec/AttributeOption/InMemoryAttributeOptionRepositorySpec.php

Enhance the `InMemoryAttributeOptionRepository` to support the _relation syntax_ of the doctrine `findBy` method.
E.g.
```php
$attributeOptionRepository->findBy([
'attribute.code' => 'color',
'code' => 'red'
]);
``` …

DAPI-151: Fix InMemory repository to support findBy syntax

---

CHANGELOG-3.0.md
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/form/tab/attributes/copy.html

PIM-8258: Fix missing translation for "copy none"

---

CHANGELOG-3.0.md
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_base_export_show.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_base_import_show.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_product_export_show.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_product_import_show.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_product_model_export_show.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_product_model_import_show.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_base_export_show.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_base_import_show.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_product_export_show.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_product_import_show.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_product_model_export_show.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_product_model_import_show.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/yml_base_export_show.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/yml_base_import_show.yml

The button to edit an import/export profile must not be displayed if the user has not the permission to edit.
I didn't add tests for that. The only way to do it would be to add end-to-end tests, and it's not a critical use case.

PIM-8252: Add ACL on the edit import/export profile button

---

CHANGELOG-3.0.md
src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/datagrid/export_profile.yml
src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/datagrid/import_profile.yml
src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/datagrid/job_profile.yml

ACLs were not applied on jobs profile grid, import and export.
To do his and be able of settings diffeent ACLs, i had to deport the configuration from the upper `job_profile` grid to its children because it's not possible to override partially in Oro ActionExtension. …

PIM-8252: fix acl for profiles grid buttons

---

CHANGELOG-3.0.md
src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/translations/jsmessages.en_US.yml
src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/translations/jsmessages.fr_FR.yml

For the record, the translation is not free because of this line: https://github.com/akeneo/pim-community-dev/blob/3.0/src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/action/delete-confirm.ts#L25
So i have to add the exact translation key
`OK`: Done / …

PIM-8271: Fix import/export delete translation

---

CHANGELOG-3.0.md
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/Grid.less
src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/cell/product-and-product-model-label-cell.js

This PR add a max size on the product grid columns. If the cell content is too long, the content is truncated. The full content is however available on the cell rollover (using a title HTML attribute)
Before : 
After : …

PIM-8259: add a max width and a title attribute to the label field in the product grid

---

src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/product/index.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/Column.less
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/FilterBox.less
src/Oro/Bundle/PimDataGridBundle/Resources/config/requirejs.yml
src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/label_or_identifier-filter.js
src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filters-column.ts
src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filters-manager.js
src/Oro/Bundle/PimDataGridBundle/Resources/public/templates/filter/filter-column.html
src/Oro/Bundle/PimDataGridBundle/Resources/public/templates/filter/filter-group.html

Needed for EE PR.
Two modules are used to display filters panel. One was dedicated to products and another one is used in all other grids. The product panel is more customizable and according to Pierre, the fact that we have two modules comes from a merge into master error. We should only have the product module because even if it was specific, it is customizable, paginable and runs with a query which does not hydrate all attributes.
That's why I decided to make it more generic and reuse it in proposal grid (CE PR). Next step is to remove the second module and replace it everywhere with the generic one.
| …

DAPI-58: Make the grid filter column not specific to product

---

src/Pim/Bundle/CatalogBundle/Resources/config/model/doctrine/Product.orm.yml

The problem is that if you try to save a product which had a completeness on a non-actived locale, the completeness won't be removed.
| Changelog updated                 | TODO

PIM-8262: Make Doctrine remove completeness orphans

---

CHANGELOG-3.0.md
src/Akeneo/Platform/Bundle/InstallerBundle/Command/DatabaseCommand.php

Today when we install the PIM, we can't play doctrine:migrations:migrate as it will try to apply the same changes. This change make doctrine:migrations know that it is already at the latest state.
The command executor takes care of the environment ;) …

PIM-8239: Set latest migration during fresh install

---

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/Grid.less

PIM-8259: remove the white-space:nowrap statement for all grid cells

---

CHANGELOG-3.0.md
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_product_import_show.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/xlsx_product_model_import_show.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/FormContainer.less

On some imports, the "Download and import" button is not well placed, it's above the drag and drop zone, it should be always below the drag and drop zone.
This PR fixes it by setting some missing positions in the form extensions.
**Before**
**After**

PIM-8274: Fix misplaced button on imports/exports

---

CHANGELOG-1.7.md

The CHANGELOG was not edited while fixing this bug.

PIM-8255: Fix version entity detached during the purge

---

CHANGELOG-3.0.md
src/Akeneo/Pim/Enrichment/Bundle/AkeneoPimEnrichmentBundle.php
src/Akeneo/Pim/Enrichment/Bundle/DependencyInjection/Compiler/ConfigureAxisValueLabelsNormalizerPass.php
src/Akeneo/Pim/Enrichment/Bundle/Resources/config/normalizers.yml
src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/AxisValueLabelsNormalizer/AxisValueLabelsNormalizer.php
src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/AxisValueLabelsNormalizer/MetricNormalizer.php
src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/AxisValueLabelsNormalizer/SimpleSelectOptionNormalizer.php
src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/EntityWithFamilyVariantNormalizer.php
tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/InternalApi/AxisValueLabelsNormalizer/MetricNormalizerSpec.php
tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/InternalApi/AxisValueLabelsNormalizer/SimpleSelectOptionNormalizerSpec.php
tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/InternalApi/EntityWithFamilyVariantNormalizerSpec.php

This PR extract the label normalization for EntityWithFamilyVariantNormalizer in dedicated classes and allows to inject more normalizers, for example to normalize EE specific attribute type labels. …

PIM-8233: extract attribute normalization in dedicated classes

---

CHANGELOG-3.0.md
src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/ProductGridFilterController.php

The "Product grid filters" field available under your user account profile, does not allow search on attribute labels only codes. By passing the catalog locale in search options, search is enabled on attribute code AND attribute labels.

PIM-8272: Product grid filter search on label

---

CHANGELOG-3.0.md
src/Akeneo/UserManagement/Bundle/Controller/Rest/UserController.php
src/Akeneo/UserManagement/Bundle/Resources/config/form_extensions/profile.yml
src/Akeneo/UserManagement/Bundle/Resources/config/routing/user_rest.yml
src/Akeneo/UserManagement/Component/Normalizer/UserNormalizer.php
tests/back/UserManagement/Specification/Component/Normalizer/UserNormalizerSpec.php
tests/legacy/features/user-management/user/edit_my_account.feature

Users should be able to edit their own account information even if they are not granted the`pim_user_user_edit` permission (every field except `User groups` and `Roles`).
This PR creates a new `pim-user-profile-form` extension which is displayed when the logged user edits his account but does not have the `pim_user_user_edit` permission.  …

PIM-8286: Allow a user to edit his/her own account

---

src/Akeneo/Pim/Enrichment/Bundle/Product/Query/Sql/GetGroupAssociationsByProductIdentifiers.php
src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml
tests/back/Pim/Enrichment/Integration/Product/Query/Sql/GetGroupAssociationsByProductIdentifiersIntegration.php

Get Groups associated from product identifiers

TIP-1079: Fetch group associations by product identifiers

---

CHANGELOG-2.3.md
src/Pim/Bundle/VersioningBundle/Normalizer/Flat/ValueNormalizer.php
src/Pim/Bundle/VersioningBundle/spec/Normalizer/Flat/ValueNormalizerSpec.php

PIM-8288: keep locale-specific but non-localizable attribute values in the flat normalization to make them appear in the product changeset

---

CHANGELOG-2.3.md
src/Pim/Component/Catalog/Model/AbstractMetric.php
src/Pim/Component/Catalog/spec/Factory/MetricFactorySpec.php
src/Pim/Component/Connector/ArrayConverter/FlatToStandard/Product/ValueConverter/MetricConverter.php
src/Pim/Component/Connector/spec/ArrayConverter/FlatToStandard/Product/ValueConverter/MetricConverterSpec.php
tests/legacy/features/import/product/import_products_with_invalid_data.feature

Before:
When importing a product file like this:
```
sku;weight;weight-unit
111;;GRAM
```
The converter will create a Metric `{amount: 'GRAM', unit: null}` instead of `{amount: null, unit: 'GRAM'}`.
This Metric will raise a validation because `"GRAM"` is not a valid amount, instead of simply skip this metric.
| Tech Doc …

PIM-8290: Fix flat to standard conversion of metrics, with unit filled and empty amount

---

CHANGELOG-3.0.md
src/Akeneo/Pim/Enrichment/Bundle/Widget/CompletenessWidget.php
tests/back/Pim/Enrichment/Specification/Bundle/Widget/CompletenessWidgetSpec.php

PIM-8291: Use the UI locale in Completeness dashboard widget

---

CHANGELOG-3.0.md
src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datagrid/column-selector.ts

PIM-8285: force the presence of column.code if not provided by the backend

---

src/Akeneo/Pim/Enrichment/Bundle/ProductModel/Query/Sql/GetProductAssociationsByProductModelCodes.php
src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml
tests/back/Pim/Enrichment/Integration/ProductModel/Query/Sql/GetProductAssociationsByProductModelCodesIntegration.php

This PR adds a query to get the product associations given a list of product model codes

TIP-1134: Create a query to get product association of product models

---

tests/back/Acceptance/User/InMemoryRoleRepository.php
tests/back/Acceptance/spec/User/InMemoryRoleRepositorySpec.php

The InMemoryRoleRepository must implement the RoleRepositoryInterface which is used as type for the https://github.com/akeneo/pim-community-dev/blob/3.0/src/Akeneo/UserManagement/Component/Factory/UserFactory.php#L62
EDIT: we also removed the `strtolower(str_replace('ROLE_', '', $index))` in the `InMemoryRoleRepository::save` that is not compatible with the real behavior done in https://github.com/akeneo/pim-community-dev/blob/3.0/src/Akeneo/UserManagement/Component/Model/Role.php#L74
| …

InMemoryRoleRepository must implement RoleRepositoryInterface

---

src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/job_instance/csv_product_import_show.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/import/switcher-item.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/import/switcher.js

We must not display the `Import now` switcher item (import profile) in the SAAS edition because this is not SAAS compliant. More information are available [here](https://akeneo.atlassian.net/secure/RapidBoard.jspa?rapidView=67&projectKey=TIP&view=planning&selectedIssue=TIP-1092&epics=visible&selectedEpic=TIP-1087).
Before:
After:
To hide this, an new env var named EDITION is given to webpack:
```bash
$ yarn requirements && NODE_PATH=node_modules EDITION=cloud  webpack --config $npm_package_config_source/webpack.config.js
```
Webpack make this var global and make it accessible via `process.env.EDITION` in the application (example [here](https://github.com/akeneo/pim-community-dev/pull/9885/files#diff-0baa3075248b34fc2e17c4730dc78852R3)). …

TIP-1092 Hide import now button from the import profile export

---

CHANGELOG-3.0.md
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/form/history.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/Grid.less
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/product/history.html

This PR adds a class to the history panel to allow it to be scrolled horizontally. This fixes an issue where the restore button wasn't visible unless the user fully expanded their browser window. 
`OK`: Done / …

PIM-8287: Fix horizontal scroll on history panel

---

frontend/build/update-extensions.js

This PR fixes a bug where the `update-extensions` script that collects and merges the form extensions would break if there was an empty .yml file.  

Allow empty form extension .ymls to be ignored during the build

---

webpack.config.js

We have a bug in the configuration of `ts-loader` in the webpack config. Since we tell ts-loader to exclude certain files from the build, e.g. a file with a path matching any of these terms: `/lib|node_modules|vendor|tests|src|packages/` it also excluded project folders like `/src/code/my-pim-project`, causing the build to break. This PR fixes this issue by making the excluded files relative to the project directory.  …

Fix exclude folders to make them relative

---

.circleci/config.yml
CHANGELOG-2.3.md
composer.json
composer.lock
src/Pim/Bundle/FilterBundle/Form/Type/Filter/AjaxChoiceFilterType.php
src/Pim/Bundle/FilterBundle/Form/Type/UnstructuredType.php

We have intl issues on CE 2.3 which is linked to Intl.
See https://github.com/symfony/symfony/issues/31089 for more information.
We also must apply a patch done in 3.0 on AjaxFilter necessary with this Symfony version.
See #9528 
And thx @ahocquard  for helping me on the subject.

PIM-8318: Fix CE 2.3 CI

---

webpack.config.js

We tagged a 3.1.0, but we have a deployment problem. We are not able to deploy properly on `demo.akeneo.com` for instance with the current ansible scripts. In the current ansible scripts, there is no `yarn run less` command that is launched. Which means the PIM is deployed without any CSS.
Benoit doesn't want us to change the ansible scripts. That would mean we introduce a BC break in the build process in a minor version. 
This PR is a transparent way to solve the problem. Thanks to @tamarasaurus for the solution.
```bash
jjanvier:pcd$ docker-compose run --rm node yarn run webpack                                            
WARNING: The ES_JAVA_OPTS variable is not set. Defaulting to a blank string.
yarn run v1.13.0
$ yarn requirements && webpack --config webpack.config.js --env=prod
$ …
```

Launch yarn run less during yarn run webpack

---

CHANGELOG-2.3.md
src/Pim/Bundle/CatalogBundle/Resources/elasticsearch/index_configuration.yml

In the ES product indexes the fields `ancestors.codes` and `ancestors.labels` are not correctly mapped. They don't have any normalizer defined so the textual search is case sensitive.
It's a problem to count the products impacted by a mass edit action. All the product variants must be counted so these two fields are used to search on the product models parents.

PIM-8289: Fix search on label or identifier for product variants ancestors

---

CHANGELOG-3.0.md
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/bootstrap-modal/bootstrap-modal.js

This PR adds a simple check on the picture before adding the `AknFullPage-content--withIllustration` class. On the `onboarder` & `pim-onboarder` adding this class for a modal without picture broke it (titles were display on the left instead of being centered).
| Tech Doc …

AOB-472: Fix missing variable check template bootstrap modal

---

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/common/property.js

The property accessor component uses dots to split the property path to access data. This works well when all properties in the path doesn't contains any dots.
Unfortunately, in askFrankly bounded context, some properties contains dots in their names.
So this PR adds a way to properly escape dots in property names and then is able to put them back in the property name during the update phase.
This modification will not impact any other code and will not change existing behaviour
| …

DAPI-224: accept dots in paths

---

tests/legacy/features/localization/attribute/display_localized_attribute_history.feature

On recent version patch version of PHP, the behavior of INTL to format number is different for the french format.
I detected that by removing all docker images in local to pull up new version. The problem can be reproduced on version of PHP 7.1 (2.0) and 7.2 (3.0).
Note: I didn't see anything in PHP changelog about it :disappointed: 
**Unstability explanation**
It explains why on the CI it's the scenario fails: it's very probably due to the cache of the docker image.
It's different between the circle CI container. Older version of the FPM image are running this test as success, most recent one as failing.
**Before:**
It formats "12 456,789" with a non breakable space for french locale (unicode character: `\u00a0`) . Then, in the …

GITHUB-9927: fix narrow breakable space in the test since new version  of PHP

---

CHANGELOG-2.3.md
src/Pim/Bundle/EnrichBundle/Controller/AttributeOptionController.php

The bug is that under certain conditions, an attribute option is re-created after being deleted. It has been triggered by a custom code of a client, but the real cause is in the PIM. 
When an attribute option is removed, a version of the attribute is created, and its "updated at" date is updated. It occurs in a event suscriber, after that the attribute option has been removed from the Doctrine UOW and deleted in the database. (remove + flush)
The problem is that if the attribute is fully hydrated with its options collection before that the attribute option is removed, this attribute option is still in the collection but with `null` as id (the entity has been removed from the Doctrine UOW). So when the attribute is saved to persist the date of the udpate, the UOW considers that there's a …

PIM-8323: Fix issue on attribute option removing

---

CHANGELOG-2.3.md
src/Pim/Bundle/EnrichBundle/Resources/public/js/job/common/edit/upload-launch.js
tests/legacy/features/product/edit_product.feature

Cherry pick of this commit https://github.com/akeneo/pim-community-dev/pull/8495 to add a loading mask to prevent the user to click several time on "Upload and Import" when the import takes time.
`OK`: Done / …

PIM-8319: add loading mask on upload clic

---

CHANGELOG-3.2.md
src/Akeneo/Tool/Bundle/BatchQueueBundle/Command/JobQueueConsumerCommand.php
src/Akeneo/Tool/Bundle/BatchQueueBundle/Queue/DatabaseJobExecutionQueue.php
src/Akeneo/Tool/Bundle/BatchQueueBundle/Queue/JobExecutionMessageRepository.php
src/Akeneo/Tool/Bundle/BatchQueueBundle/spec/Queue/DatabaseJobExecutionQueueSpec.php
src/Akeneo/Tool/Bundle/BatchQueueBundle/tests/integration/Command/JobQueueConsumerCommandIntegration.php
src/Akeneo/Tool/Component/BatchQueue/Queue/JobExecutionQueueInterface.php
tests/back/Integration/IntegrationTestsBundle/Launcher/JobLauncher.php

This PR allows launching a consumer for dedicated jobs using their job instance codes as a parameter.
For instance, for some mass edit jobs, we can launch something like this:
`romain@dandelion:~/workspace/pim/pim-ee$ bin/console --env=prod akeneo:batch:job-queue-consumer-daemon -j update_product_value -p add_product_value -p remove_product_value`
| Micro Demo to the …

DAPI-242: Improve Job execution queue filtering by job instance codes

---

CHANGELOG-3.0.md
src/Akeneo/Channel/Bundle/Resources/config/datagrid/channel.yml
src/Akeneo/Pim/Enrichment/Bundle/Resources/config/datagrid/group.yml
src/Akeneo/Pim/Structure/Bundle/Resources/config/datagrid/association_type.yml
src/Akeneo/Pim/Structure/Bundle/Resources/config/datagrid/attribute.yml
src/Akeneo/Pim/Structure/Bundle/Resources/config/datagrid/group_type.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/attribute-group/form/list.js

Avoid showing 403 error on entities edit pages by preventing click on the line and hiding the edit button when edit resource is not granted.
Hide remove action from the grid when the resource is not granted.
`OK`: …

PIM-8254: Avoid showing 403 error on entities edit pages and disable remove action when not granted

---

CHANGELOG-3.0.md
src/Akeneo/Tool/Bundle/BatchBundle/Command/PurgeJobExecutionCommand.php

When the command was launched with the option `--days=0` condition we wrote was wrong and had behaved as we passed nothing.

PIM-8283: Command akeneo:batch:purge-job-execution now works with option --days=0.

---

CHANGELOG-2.3.md
src/Pim/Bundle/DataGridBundle/Resources/public/templates/filter/search-filter.html

255 character has been choose because identifier are limited to 255 characters.

PIM-8276: Label or identifier search input is now limited to 255 characters.

---

CHANGELOG-3.0.md
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/bootstrap-modal/bootstrap-modal.js

This PR adds a simple check on the `illustrationClass` variable before adding the `AknFullPage-content--withIllustration` class. On the `onboarder` & `pim-onboarder` adding this class for a modal without picture/illustration broke it (titles were display on the left instead of being centered). …

AOB-472: Fix broken style modals

---

CHANGELOG-2.3.md
src/Pim/Bundle/LocalizationBundle/DependencyInjection/PimLocalizationExtension.php
src/Pim/Bundle/LocalizationBundle/Resources/config/translator.yml
src/Pim/Bundle/LocalizationBundle/Translator/TranslatorDecorator.php
src/Pim/Bundle/LocalizationBundle/spec/Translator/TranslatorDecoratorSpec.php

When you have an error in your translation file, it breaks the page.
For exemple, remove the coma between 1 and Inf in `'{0} Complete|{1} 1 missing value|]1,Inf] %count% missing values'`.
The fix works well for php classes AND the default twig extension `transchoice()`.
| Tech Doc …

PIM-8334: Handles error during translator choice

---

CHANGELOG-3.0.md
src/Akeneo/Platform/Bundle/UIBundle/Http/FormAuthenticationEntryPoint.php
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/services.yml

The current problem is that we currently have problems like that: 
```
benoit@tec:/tmp$ wget http://pim-ce-master.local/-2019-01-23 18:35:19- http://pim-ce-master.local/Resolving pim-ce-master.local (pim-ce-master.local)... 127.0.0.1Connecting to pim-ce-master.local (pim-ce-master.local)|127.0.0.1|:80... connected.HTTP request sent, awaiting response... 401 Unauthorized
```
That what we get now:
```
wget http://localhost:8081
--2019-05-10 17:07:17--  http://localhost:8081/
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:8081... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://localhost:8081/user/login [following]
--2019-05-10 17:07:24-- …
```

PIM-8013: Fix 401 redirection on non-authorized page

---

CHANGELOG-3.0.md
src/Akeneo/Pim/Enrichment/Bundle/Resources/translations/messages.en_US.yml
src/Akeneo/Pim/Enrichment/Bundle/Resources/views/CategoryTree/form.html.twig
src/Akeneo/Platform/Bundle/UIBundle/Resources/translations/messages.en_US.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/views/Default/page_elements.html.twig

All is in the PR title, i need a clear message when trying to remove category.
To do that, I have to add the error message as a parameter to a Twig macro (aw yeah) to be able to customize it.

PIM-8282: fix error message when removing category tree linked to a channel

---

CHANGELOG-2.3.md

cf https://github.com/akeneo/pim-community-dev/pull/9740
We removed 3 validators without adding BC breaks.

Fix changelog for PIM-8214

---

CHANGELOG-3.0.md
src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filters-column.ts

When searching in the filter list of the product grid, if you select then unselect a filter the current search result is discarded (it shouldn't):
Before
After

PIM-8242: Fix search render of product grid filters

---

CHANGELOG-3.0.md
src/Akeneo/UserManagement/Bundle/Controller/Rest/UserController.php
src/Akeneo/UserManagement/Bundle/Resources/config/controllers.yml

This is basically a port of #9378 on the new UserController, it allows to trigger Akeneo storage events when deleting a user

PIM-8343: Use BaseRemover instead of ObjectManager to delete a user

---

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/SequentialEdit.less
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/bootstrap-modal/bootstrap-modal.js

Mini fix for the UI (seen with Camille):
1. Remove the `cursor: pointer` from a non-clickable element:
Before
After
2. Fix the default option `picture` for the bootstrap modal. It is broken on the EE approval comment popup where a global picture object exists in the scope and the path is replaced by `[Object]` because there is no default value for the options.
| Micro …

Fix sequential edit ui

---

src/Akeneo/Pim/Enrichment/Bundle/Product/Query/Sql/GetExistingReferenceDataCodes.php
src/Akeneo/Pim/Enrichment/Bundle/Resources/config/factories.yml
src/Akeneo/Pim/Enrichment/Component/Product/Factory/NonExistentValuesFilter/NonExistentReferenceDataMultiSelectValuesFilter.php
src/Akeneo/Pim/Enrichment/Component/Product/Factory/NonExistentValuesFilter/NonExistentReferenceDataSimpleSelectValuesFilter.php
src/Akeneo/Pim/Enrichment/Component/Product/Factory/NonExistentValuesFilter/NonExistentSimpleSelectValuesFilter.php
src/Akeneo/Pim/Enrichment/Component/Product/Factory/ValueCollectionFactory.php
src/Akeneo/Pim/Enrichment/Component/Product/Query/GetExistingReferenceDataCodes.php
src/Akeneo/Pim/Structure/Bundle/Query/PublicApi/AttributeTypes/Sql/SqlGetAttributes.php
src/Akeneo/Pim/Structure/Component/Query/PublicApi/AttributeType/Attribute.php
tests/back/Pim/Enrichment/Specification/Component/Product/Factory/NonExistentValuesFilter/NonExistentReferenceDataMultiSelectValuesFilterSpec.php
tests/back/Pim/Enrichment/Specification/Component/Product/Factory/NonExistentValuesFilter/NonExistentReferenceDataSimpleSelectValuesFilterSpec.php
tests/back/Pim/Enrichment/Specification/Component/Product/Factory/ValueCollectionFactorySpec.php

This PR adds a couple of filters for the value collection factory to filter reference data multi/single select options. 

TIP-1158: Add filter for reference data options

---

src/Pim/Bundle/CatalogBundle/Resources/config/validators.yml
src/Pim/Bundle/EnrichBundle/Controller/AttributeOptionController.php
src/Pim/Component/Catalog/Validator/Constraints/AttributeTypeForOptionValidator.php

I created a custom attribute in order to override default simple select attribute type.
When I submitted my first option the controller returned a 400 without any messages. The problem was due to the fact that the method getFormErrors only return errors for child forms so I overrided it to also return global form errors.
I also used parameter in the AttributeTypeForOptionValidator class to handle supported attribute types like a lot of your services because otherwise, we have to override your class instead of just the parameter of your service.
(cf https://github.com/akeneo/pim-community-dev/pull/9780)

EE contribution - Attribute option form errors and validator

---

CHANGELOG-2.3.md
src/Pim/Bundle/EnrichBundle/Resources/public/templates/family-variant/attribute-set.html
src/Pim/Bundle/EnrichBundle/Resources/public/templates/product/form/variant-navigation/navigation.html
src/Pim/Bundle/UIBundle/Resources/public/less/components/FamilyVariant.less
src/Pim/Bundle/UIBundle/Resources/public/less/components/product-edit-form/VariantNavigation.less
src/Pim/Bundle/UIBundle/Resources/public/less/lib/select2.less

PIM-8347: Fix variant navigation display in case of long attribute labels

---

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/fetcher/locale-fetcher.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/grid/locale-switcher.js

This PR does 2 things:
- the locale fetcher now caches active locales based on the `filter_locales` param in searchOptions argument (prior to this, it always returned the same result, regardless of the search options)
- in the product grid's locale switcher, if the current locale (in the UserContext) is not available (e.g because of permissions issues), it fallbacks to the first available locale and updates the UserContext accordingly. This check is done in `configure()` rather than `render()`, so the other components are aware of this change sooner
see https://akeneo.atlassian.net/browse/PIM-8336 for more info
| Added …

PIM-8336: Fix product grid's locale switcher cache

---

CHANGELOG-2.3.md
src/Pim/Bundle/DataGridBundle/Resources/public/js/datafilter/filter/price-filter.js
src/Pim/Bundle/FilterBundle/Filter/ProductValue/PriceFilter.php
tests/legacy/features/Pim/Behat/Decorator/Grid/Filter/PriceDecorator.php
tests/legacy/features/product/filtering/filter_products_per_price.feature

Hide the currency selector on the product grid price filters **empty** and **not empty**.
The goal is to not confuse the user and make them believe the price will be filtered on the selected currency (which is not the case).
Before:
After:
Also, fix a bug where if you reload the page with a price filter **empty** or **not empty** the form will display an input type text: …

PIM-8346: Fix product grid price filters

---

CHANGELOG-2.3.md
src/Akeneo/Bundle/StorageUtilsBundle/Resources/config/doctrine.yml
src/Pim/Bundle/CatalogBundle/Doctrine/ORM/QueryBuilderUtility.php

* What was the issue
Today, you can override basic entities by using ConfigureMappingsSubscriber and
- defining a new class
- defining a `mapping_override`
- defining a new ORM mapping.
An entity can have mapping (many to one, one to many, etc) to Interfaces, as we have a compiler pass to get real classes instead of these Interfaces (ResolveTargetEntityListener)
The issue is that the compilation to transform Interfaces to real classes was done before the override of entity. This implies an error during hydratation because Interfaces entities were not found.
* What causes the issue 
This issue exists since we upgraded Symfony from 3.4.4 to 3.4.26. We didn't find anything in the Symfony Changelog related to this issue.
* What is the solution
The solution is to change the priority of the …

PIM-8351: Fix entity overriding priority

---

src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Connector/SqlGetConnectorProducts.php
tests/back/Pim/Enrichment/Integration/Storage/Sql/Connector/SqlGetConnectorProductsIntegration.php

TIP-1157: Fix query when there is no association type in the catalog

---

web/app.php

Add comments for those who use HTTPS from a reverse proxy. By setting the environment variable `TRUSTED_PROXY_IPS` the PIM will generate absolute URL (per instance in the API) with the protocol HTTPS event if the server is on HTTP.

PIM-8352: Add comment about trusted proxy and HTTPS

---

CHANGELOG-3.0.md
src/Akeneo/Pim/Enrichment/Bundle/Command/PurgeCompletenessCommand.php

The command `pim:completeness:purge` launches several sub commands `pim:completeness:purge-products`, and they can be be very slow for some clients. One of them has a "timeout" error during the process.
As workaround, we have to launch each `pim:completeness:purge-products` process withtout timeout. The performance problems can be solved in a second time.

PIM-8374: Fix timeout when launching the completeness purge command

---

CHANGELOG-3.0.md
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/grid/mass-actions.js

Before:
- You select All : it selects 1000 products
- You select All visible: it keeps the 1000 products
Now:
- You select All: it selects 1000 products
- You select All visible: it selects 25 products.

PIM-8375: Fix counter on grids when user selects all results then select all visible results

---

CHANGELOG-2.3.md
src/Pim/Bundle/EnrichBundle/Resources/public/templates/mass-edit/form.html

When you mass edit, the current and validated steps are annoted as green in the bottom of the page.
They were delayed, as they were 1 step late.

PIM-6829: Fix mass edit enabled steps

---

CHANGELOG-3.2.md
src/Akeneo/Platform/Bundle/InstallerBundle/Resources/fixtures/minimal/users.csv
src/Akeneo/Tool/Bundle/ApiBundle/tests/integration/ApiTestCase.php
src/Akeneo/UserManagement/Bundle/Command/CreateUserCommand.php
tests/back/Integration/TestCase.php
tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/DeleteProductEndToEnd.php
tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/CategoryTree/ListChildrenCategoriesWithCountIncludingSubCategoriesIntegration.php
tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/CategoryTree/ListChildrenCategoriesWithCountNotIncludingSubCategoriesIntegration.php
tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/CategoryTree/ListRootCategoriesWithCountIncludingSubCategoriesIntegration.php
tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/CategoryTree/ListRootCategoriesWithCountNotIncludingSubCategoriesIntegration.php
tests/back/Platform/Integration/CatalogVolumeMonitoring/Persistence/Query/CountUsersIntegration.php
tests/back/UserManagement/Integration/Bundle/RemoveRoleIntegration.php

This PR improves the command to create a new user.
It allows the command to be launched non interactively (very useful for ops) like:
`pim:user:create kbeck secretp@ssw0rd kbeck@example.com Kent Beck en_US --admin -n`
The command can still be launched interactively, which is great for devs.
The command can now also add the admin role to the user with the `--admin` option.
Also, the admin user has been removed from the minimal catalog as it forces the ops to hack the PIM for a new SAAS instance. Also, it was kind of a security issue.

TIP-1117: Improve command to create new users

---

src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/price-filter.js

Price filter default was not currently initialized.
When we render the criteria for the first time, we must use the first currency available.

PIM-8386: Fix price filter default currency

---

CHANGELOG-2.3.md
src/Pim/Bundle/CatalogBundle/Command/CleanRemovedAttributesFromProductAndProductModelCommand.php

PIM-8385: Fix timeout when launching the clean attributes command

---

CHANGELOG-2.3.md
src/Pim/Bundle/EnrichBundle/Controller/Rest/ProductModelController.php
src/Pim/Bundle/EnrichBundle/Normalizer/VariantNavigationNormalizer.php
src/Pim/Bundle/EnrichBundle/spec/Normalizer/VariantNavigationNormalizerSpec.php

Type hint constructor with interface instead of concrete class to facilitate extension points.
Fixes #8429 

PIM-8378: fix DI for EntityWithFamilyVariantNormalizer injection

---

src/Akeneo/UserManagement/Bundle/Controller/Rest/UserController.php
tests/front/common/builder/user.js

- The key was wrong
- I updated the user context mock for the front-end tests with a decimal separator

PIM-8317: Fix decimal separator in user context & mock

---

CHANGELOG-2.3.md
src/Pim/Bundle/EnrichBundle/Resources/public/js/i18n.ts

This PR updates the i18n script to prevent `getFlag` from throwing an error for a badly formatted locale - e.g. 'test'. Like with an empty locale, it will return no flag; 

PIM-7583: Prevent js error for locales without country

---

CHANGELOG-2.3.md
src/Pim/Bundle/EnrichBundle/Resources/public/js/i18n.ts

Reverts akeneo/pim-community-dev#10130
This PR is to revert the fix and wait for a better solution e.g. validating the format of locales

Revert "PIM-7583: Prevent js error for locales without country"

---

CHANGELOG-2.3.md
src/Pim/Bundle/CatalogBundle/Resources/config/serializers_standard.yml
src/Pim/Bundle/VersioningBundle/Resources/config/serializer/flat.yml
src/Pim/Bundle/VersioningBundle/spec/Normalizer/Flat/AttributeOptionNormalizerSpec.php
src/Pim/Component/Catalog/Normalizer/Standard/AttributeOptionNormalizer.php
src/Pim/Component/Catalog/spec/Normalizer/Standard/AttributeOptionNormalizerSpec.php

Same fix as https://github.com/akeneo/pim-community-dev/pull/8877 : we don't expose disabled locales in attribute options standard format.

PIM-8381: do not expose disabled locales in attribute options export

---

CHANGELOG-3.0.md
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/family/mass-edit/toolbar/add-select/attribute/select.js

This PR fixes an issue in the mass edit family screen where the attribute groups inside the attribute selector were not being loaded. In this PR, the select2 component has been updated to fetch the attribute groups and populate them in the results.  …

PIM-8315: Fix undefined attribute groups in family mass edit

---

CHANGELOG-2.3.md
src/Akeneo/Bundle/BatchQueueBundle/Command/JobQueueConsumerCommand.php
src/Akeneo/Bundle/BatchQueueBundle/Queue/DatabaseJobExecutionQueue.php
src/Akeneo/Bundle/BatchQueueBundle/Queue/JobExecutionMessageRepository.php
src/Akeneo/Bundle/BatchQueueBundle/spec/Queue/DatabaseJobExecutionQueueSpec.php
src/Akeneo/Bundle/BatchQueueBundle/tests/integration/Command/JobQueueConsumerCommandIntegration.php
src/Akeneo/Component/BatchQueue/Queue/JobExecutionQueueInterface.php
tests/back/Integration/IntegrationTestsBundle/Launcher/JobLauncher.php

Backport from master into 2.3 of PR #9988
Works exactly the same. There is one difference in the code though, assertStringContainsString() method is not available in the PhpUnit version of the 2.3, so I had to use something else. …

PIM-8384: Improve Job execution queue filtering by job instance codes

---

src/Akeneo/Pim/Enrichment/Bundle/StructureVersion/EventListener/StructureVersionUpdater.php
tests/back/Pim/Enrichment/Specification/Bundle/StructureVersion/EventListener/StructureVersionUpdaterSpec.php

- Before:
Install icecat CE: 4 sec  in this query (~install 100 sec)
- After:
Install icecat CE: 1 sec in this query (~install 97 sec)
3% improvement for 3 lines of code (on small catalog, in CE, but it's free).
It was not speced neither covered by integration test, just a behat that seems to be removed in 3.0.
| …

TIP-1177: do not refresh structure version table when Product or Product model are saved

---

CHANGELOG-3.0.md
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/lib/jquery.multiselect.less
src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filters-column.ts

GTM by Stéphane for the UI.
Credits for the fix: @pierallard 
Before:
After:

PIM-8412: Fix wrong display of too long attribute group labels when filtering in the datagrid

---

CHANGELOG-2.3.md
src/Pim/Bundle/UIBundle/Resources/config/assets.yml
src/Pim/Bundle/UIBundle/Resources/public/less/lib/bootstrap.tooltip.less

The default tooltip was too short and was unreadable.
We added a minimal width to prevent this.

PIM-7942: Fix tooltip minimal width

---

CHANGELOG-3.2.md
src/Akeneo/Pim/Enrichment/Bundle/ProductQueryBuilder/ProductAndProductModelQueryBuilder.php
tests/back/Pim/Enrichment/Specification/Bundle/ProductQueryBuilder/ProductAndProductModelQueryBuilderSpec.php

The original need is to add a filter on the draft status in the product grid (see https://github.com/akeneo/pim-enterprise-dev/pull/5949). To do so, the solution is to filter by the Ids of the products and product models that have a draft on the chosen status. 
The problem is that when this is combined with a filter on a category, the product variants that match the draft status filter are not displayed. It's because the ES query is modified by `ProductAndProductModelSearchAggregator` to aggregate the product variants in their product model. It adds a `must not` clause to exclude products whose parents match the category.
The simplest solution is to not add the aggregation clauses in the ES query if there is a filter on the Id. It makes sense for the operators `IN` and `=` but it's …

DAPI-137: Do not aggregate results in the PQB when there is a filter on id

---

src/Akeneo/UserManagement/Bundle/Command/CreateUserCommand.php

This PR updates the create user command to add an admin user into every group. Currently, after creating an admin user using this command, the admin user is only in the default 'All' group, which doesn't have permission to edit the product identifier. This problem causes the akeneo-data-generator to fail when inserting products. 
| …

Add admin user to groups

---

CHANGELOG-3.2.md
UPGRADE.md
src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Field/AncestorCodeFilter.php
src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Field/AncestorIdFilter.php
src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Field/ParentFilter.php
src/Akeneo/Pim/Enrichment/Bundle/Resources/config/query_builders.yml
src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/ApplyProductSearchQueryParametersToPQB.php
src/Akeneo/Pim/Enrichment/Component/Product/Connector/UseCase/Validator/ValidateProperties.php
tests/back/Pim/Enrichment/EndToEnd/Product/Product/ExternalApi/ListProducts/SuccessListProductEndToEnd.php
tests/back/Pim/Enrichment/Integration/Elasticsearch/IndexConfiguration/SearchSelfAndAncestorsIntegration.php
tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Filter/Field/AncestorIdFilterSpec.php

Description in the docs PR : https://github.com/akeneo/pim-api-docs/pull/268/files

TIP-1145: Add parent filter

---

CHANGELOG-2.3.md
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/field/wysiwyg-field.js
src/Pim/Bundle/UIBundle/Resources/public/js/pim-wysiwyg.js

PIM-8417: Disable HTML prettify for WYSIWYG field

---

src/Akeneo/Pim/Enrichment/Component/Product/Factory/Read/ValueCollectionFactory.php
src/Akeneo/Pim/Enrichment/Component/Product/Factory/WriteValueCollectionFactory.php
src/Akeneo/Pim/Structure/Bundle/Query/PublicApi/Attribute/Sql/SqlGetAttributes.php
src/Akeneo/Tool/Component/StorageUtils/Cache/LRUCache.php
src/Akeneo/Tool/Component/StorageUtils/spec/Cache/LRUCacheSpec.php
tests/back/Pim/Enrichment/Specification/Component/Product/Factory/Read/ValueCollectionFactorySpec.php
tests/back/Pim/Enrichment/Specification/Component/Product/Factory/WriteValueCollectionFactorySpec.php
tests/back/Pim/Structure/Integration/Attribute/Query/SqlGetAttributesIntegration.php

We modified the behavior of the interface GetATtributes to return `null` when an attribute does no exist.
`['my_attribute' => Attribute()...), 'unknown_attribute' => null'`
The check with isset is enough to know if the attribute exist.
Note: it makes failing the generator (I don't know why though, but it raised a bug) …

TIP-1173: fix value collection when attribute does not exist

---

src/Akeneo/Platform/Bundle/ImportExportBundle/Controller/JobExecutionController.php
src/Akeneo/Tool/Component/Connector/LogArchiver.php
src/Akeneo/Tool/Component/Connector/LogKey.php
src/Akeneo/Tool/Component/Connector/spec/LogArchiverSpec.php
src/Akeneo/Tool/Component/Connector/spec/LogKeySpec.php
upgrades/schema/LocalLogToObjectStorage.php
upgrades/schema/LocaleArchivesToObjectStorage.php
upgrades/schema/RelocateException.php
upgrades/schema/archived_files_local_filesystem_to_object_storage.php
upgrades/schema/archived_logs_local_filesystem_to_object_storage.php

Migration scripts for our SAAS NFS PIM towards non NFS. To achieve that we now store some files (import/export logs, import/export archives, product medias) in object storage instead of locally. 

TIP-1180: migrate local files to object storage

---

CHANGELOG-3.0.md
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/VariantNavigation.less
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/lib/select2.less

PIM-8414: Fix the product variant breadcrumb size

---

CHANGELOG-3.1.md
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/Grid.less

Small images were not well displayed in the grids.
Before:
After:

PIM-8447: Fix grids thumbnails display

---

CHANGELOG-2.3.md
src/Oro/Bundle/FilterBundle/Filter/SearchFilter.php

Underscore '_' is a special character in MySQL like queries and we must escape them in the search terms.
Wilcards examples: https://www.guru99.com/wildcards.html

PIM-8450: Fix assets search with underscore in the code

---

CHANGELOG-3.0.md
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/form_extensions/product_model/edit.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/save-buttons.js

Apply 'edit atributes permissions' for the display of product model Save button 

PIM-8460: do not display Save button without permission on PM

---

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/mass-edit/form/form.js

DAPI-139: trigger an event at the end of the mass edit confirm action

---

CHANGELOG-2.3.md
composer.json

EE: https://github.com/akeneo/pim-enterprise-dev/pull/6357
An integrator has an issue with Intl - (internal ref SDS-11138)
This is fixed by Symfony in the v3.4.28

PIM-8469 - Upgrade symfony version

---

CHANGELOG-3.1.md
src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/public/js/last-operations-widget.js
src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/public/templates/last-operations-widget.html

The bug was due to a js comparison of ```"6"===6``` which is false.
Now, ```6===6```.

PIM-8467: Fix warning counts in case of failed jobs in last operations widget

---

CHANGELOG-2.3.md
app/config/config.yml
app/config/pim_parameters.yml
src/Pim/Bundle/EnrichBundle/Resources/config/pim.yml

By moving this configuration in `pim.yml` we will not have to repeat it in EE dev or standard.

PIM-8449: AKENEO_PIM_URL in community config

---

CHANGELOG-3.1.md
src/Akeneo/Pim/Structure/Bundle/Controller/InternalApi/AttributeGroupController.php
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/attribute-group/form/list.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/templates/attribute-group/list.html

Before, there was no check of permission about the attribute group sort.
Now, if you unselect the role, it will
- check in the backend controller
- do not display handles
- do not allow sort
| Added legacy Behats               | n
| Added acceptance tests            | n
| Added integration tests           | n

PIM-8475: Fix permission of sorting attribute groups

---

CHANGELOG-3.0.md
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/field/wysiwyg-field.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/lib/summernote.less
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/pages/FullPage.less

Before (in fact, there was nothing at all before, but it's a screenshot from 2.3)
Now

PIM-8477: Fix rich text area link dialog

---

CHANGELOG-3.0.md
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/field/wysiwyg-field.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/FilterChoice.less
src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/metric-filter.js
src/Oro/Bundle/PimDataGridBundle/Resources/public/js/datafilter/filter/price-filter.js
src/Oro/Bundle/PimDataGridBundle/Resources/public/templates/filter/metric-filter.html

Fixes a lot of issues on price and metric filters in the datagrid
- when number is too long, it was overriding the unit
- when operator was "empty", unit was still displayed
- sometimes, it was impossible to clic on validate because the popin was too down
| Added legacy Behats               | n
| Added acceptance tests            | n
| Added integration tests           | n

PIM-7894: Fix metric and price filters design

---

CHANGELOG-3.0.md
src/Akeneo/Platform/Bundle/ImportExportBundle/Controller/InternalApi/JobInstanceController.php
src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/translations/jsmessages.en_US.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/job/common/edit/upload-launch.js

PIM-8463: display an explicit error message when an uploaded file is too big on import profiles

---

CHANGELOG-3.1.md
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/lib/select2/select2.css

When there is a long label for a simple select option, the 'X' (remove) button is not clickable. This PR adds some space between the end of the label and the button. 
Before
After

PIM-8481: Fix space between long labels and buttons in simple selects

---

CHANGELOG-2.3.md
src/Akeneo/Bundle/BatchBundle/Command/PurgeJobExecutionCommand.php
src/Akeneo/Bundle/BatchQueueBundle/Query/SqlDeleteJobExecutionMessageOrphansQuery.php
src/Akeneo/Bundle/BatchQueueBundle/Resources/config/services.yml
src/Akeneo/Bundle/BatchQueueBundle/tests/integration/Query/SqlDeleteJobExecutionMessageOrphansQueryIntegration.php
src/Akeneo/Component/BatchQueue/Query/DeleteJobExecutionMessageOrphansQueryInterface.php

The old job executions can be deleted from the database with the command `akeneo:batch:purge-job-execution`. The problem is that it doesn't delete the messages related to these job executions in the queue.
To fix this problem I added a query function that deletes job execution message orphans, and I call it in the purge command. I think that it's better to keep the queue system decoupled instead of adding a foreign key with a "delete cascade" constraint. …

PIM-8480: Remove the job execution message orphans after a job execution purge

---

CHANGELOG-3.2.md
src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Indexer/ProductIndexer.php
src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Indexer/ProductModelIndexer.php
tests/back/Integration/IntegrationTestsBundle/Loader/FixturesLoader.php
tests/back/Pim/Enrichment/Integration/Storage/Sql/ProductGrid/ProductGridFixturesLoader.php
tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Indexer/ProductIndexerSpec.php
tests/back/Pim/Enrichment/Specification/Bundle/Elasticsearch/Indexer/ProductModelIndexerSpec.php

We should not `wait_for` index refresh when indexing products in ES.
It means it wait the next refresh from ES, which is every 1 sec by default. 
Most of the time, it is disabled but not everywhere. It is not a best practice to use it, as it impacts performance.
So by default, we should disable it (it's disable by default in ES if not provided explicitely).
On Icecat catalog, we have a performance gain of at least 10 seconds during the installation (1m45 => 1m35).
We have a gain of 1 minute during integration tests also, for free.
On association step during product import, as the batch size is at 1 during import for this step, we were waiting most of the time a refresh in ES on icecat catalog (several calls per product with refresh, 2 …

TIP-1190: Disable the wait of the refresh of the index when indexin in ES, by default

---

CHANGELOG-3.0.md
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/Grid.less
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/lib/select2.less

Some images are displayed deformed in the dropdowns. It's the case for the reference entity attributes in the PEF.
The solution is to add the CSS rule "object-fit: contain" as it has been done for the images in the grids : https://github.com/akeneo/pim-community-dev/blob/b1363e675e4d9795c20634ac73936c58f034c5e1/src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/Image.less#L165

PIM-8447: Fix deformed images in dropdowns

---

src/Akeneo/Pim/Enrichment/Bundle/Product/Query/Sql/Completeness/SqlSaveProductCompletenesses.php
src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml
src/Akeneo/Pim/Enrichment/Component/Product/Model/Projection/ProductCompletenessCollection.php
src/Akeneo/Pim/Enrichment/Component/Product/Query/SaveProductCompletenesses.php
tests/back/Pim/Enrichment/Integration/Product/Query/Sql/Completeness/SaveProductCompletenessesIntegration.php
tests/back/Pim/Enrichment/Specification/Component/Product/Model/Projection/ProductCompletenessCollectionSpec.php

Query to save completenesses projection model to database. Introduces a ProductCompletenessCollection object.

TIP-1159: Save completeness from projection model

---

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/attributes/create-button.js

Disable the creation of attribute "akeneo_asset_multiple_link" and "akeneo_asset_single_link" from the UI

PIM-8430: Remove asset_multiple link and asset_single_link attributes from product

---

CHANGELOG-2.3.md
src/Pim/Bundle/EnrichBundle/Resources/public/js/product/form/variant-navigation.js

This PR fixes a bug on the variant navigation where select2 dropdowns and form modals wouldn't close after clicking the back button. 

PIM-7935: Close variant select dropdowns on page navigation

---

CHANGELOG-3.1.md
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/FilterBox.less

This PR fixes the wrapping of filters for the inline filter box on reference entity records. 

PIM-8488: Fix wrapping of inline filters on records

---

CHANGELOG-3.0.md
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/VariantNavigation.less

This PR fixes an issue on the product model variant dropdowns where the badges weren't positioned correctly. 

PIM-8441: Fix badge positioning on PM dropdowns

---

CHANGELOG-3.0.md
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/channel/form/properties/conversion-unit.js

The number of metric attributes displayed in the channel edit page for the conversion is limited to 20 by default. 
Ideally the display of these attributes should be re-work to handle a large number of attributes, but it's not doable in a patch.
As workaround the limit is forced to 1000 for this page.

PIM-8534: Fix missing metric attributes on channel page

---

CHANGELOG-3.1.md
src/Akeneo/Pim/Enrichment/Bundle/PdfGeneration/Renderer/ProductPdfRenderer.php
src/Akeneo/Pim/Enrichment/Bundle/Resources/config/renderers.yml
src/Akeneo/Pim/Enrichment/Bundle/Resources/views/Product/renderPdf.html.twig
tests/back/Pim/Enrichment/Specification/Bundle/PdfGeneration/Renderer/ProductPdfRendererSpec.php

Before this fix, only the attribute code was displayed in the pdf for simple and multi select attributes.
We must display the selected and translated option labels in the PDF instead.

PIM-8540: Display option label in product PDF

---

CHANGELOG-3.2.md
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/common/select2/family.js

When we want to change the family of products in a bulk action you get a select field where the labels are filled from the uiLocale. 
But this locale is not always used. 
So with this fix, the labels are filled with data from the selected catalogLocale.
Cf community PR : https://github.com/akeneo/pim-community-dev/pull/10314

Fixed family locale on product mass edit

---

CHANGELOG-3.1.md
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/FilterBox.less

The filter caret can become invisible when the option label is very long. Ticket raised for reference entities, but i think it can be everywhere. The solution is to set the max width of the text inherit from the max width of its parent
**Before:**
**After:**

PIM-8549: Fix filter caret being overwritten

---

CHANGELOG-3.0.md
src/Akeneo/Pim/Enrichment/Bundle/Resources/config/normalizers.yml
src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/AxisValueLabelsNormalizer/MetricNormalizer.php
tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/InternalApi/AxisValueLabelsNormalizer/MetricNormalizerSpec.php

Fix display of metric as variant axis in PEF.

PIM-8555: Fix display of metric as variant axis in PEF

---

src/Akeneo/Pim/Structure/Component/AttributeTypes.php
src/Akeneo/Pim/Structure/Component/Model/FamilyVariant.php
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/form/common/attributes/create-button.js

From a functional point of view, it makes no sense to have a "single link asset" attribute type for product, so this PR removes it.

 PIM-8556: remove single asset link attribute type 

---

CHANGELOG-3.1.md
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/field/wysiwyg-field.js

This pull request aims to fix the rendering issue of "Add link" modal dialogs when there are multiple Textarea attributes with "Rich Text editor" option enabled on the product edition page.

PIM-8564: Wysiwyg - Add a link is broken when multiple rich textarea

---

CHANGELOG-2.3.md
src/Pim/Bundle/DataGridBundle/Resources/public/js/datagrid/action/delete-action.js
tests/legacy/features/family/delete_family.feature

This PR updates the grids to show a flash message instead of an old style modal when there is a deletion error. 

PIM-8484: Show flash message instead of deprecated modal on deletion

---

src/Akeneo/Pim/Enrichment/.php_cd.php
src/Akeneo/Pim/Enrichment/Bundle/Product/Query/Sql/SqlGetAttributeLabels.php
src/Akeneo/Pim/Enrichment/Bundle/Product/Query/Sql/SqlGetChannelLabels.php
src/Akeneo/Pim/Enrichment/Bundle/Resources/config/normalizers.yml
src/Akeneo/Pim/Enrichment/Bundle/Resources/config/queries.yml
src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/EntityWithFamilyVariantNormalizer.php
src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/ProductCompletenessCollectionNormalizer.php
src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/ProductNormalizer.php
src/Akeneo/Pim/Enrichment/Component/Product/Query/GetAttributeLabelsInterface.php
src/Akeneo/Pim/Enrichment/Component/Product/Query/GetChannelLabelsInterface.php
tests/back/Pim/Enrichment/Integration/Product/Query/Sql/Completeness/GetProductCompletenessesIntegration.php
tests/back/Pim/Enrichment/Integration/Product/Query/Sql/SqlGetAttributeLabelsIntegration.php
tests/back/Pim/Enrichment/Integration/Product/Query/Sql/SqlGetChannelLabelsIntegration.php
tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/InternalApi/EntityWithFamilyVariantNormalizerSpec.php
tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/InternalApi/ProductCompletenessCollectionNormalizerSpec.php
tests/back/Pim/Enrichment/Specification/Component/Product/Normalizer/InternalApi/ProductNormalizerSpec.php

The internal ProductCompletenessCollection Normalizer was too complex because it loads a lot of useless things just for getting labels.
We extracted it into 2 queries to only channel and attribute labels.

Tip 1159 simplify normalizer

---

src/Akeneo/Tool/Bundle/ElasticsearchBundle/Client.php
src/Akeneo/Tool/Bundle/ElasticsearchBundle/IndexConfiguration/UpdateIndexMapping.php

Index name does not accept lowercase characters.
Since the tag BETA, the index, which has the version in the naming, cannot be created.
Note: version name is useful in the index for the UX, when we will re-index data. …

Fix creation of index having uppercase character due to version BETA and preventing the PIM to be installed

---

upgrades/schema/LocalLogToObjectStorage.php
upgrades/schema/LocaleArchivesToObjectStorage.php
upgrades/schema/archived_files_local_filesystem_to_object_storage.php
upgrades/schema/archived_logs_local_filesystem_to_object_storage.php

The current behavior leads to problems during Serenity migrations. If a command exits with an error code (non 0), the other commands are not taken into account.
This is not what we want. It's a "normal" use case that some files can not be relocated. They probably have purged on the disk.
We now just exit -1 if no file at all have been relocated. It's probably the sign of something going wrong.

TIP-1180: do not fail when a file can not be relocated

---

src/Akeneo/Tool/Bundle/BatchQueueBundle/Command/PublishJobToQueueCommand.php
src/Akeneo/Tool/Bundle/BatchQueueBundle/Resources/config/services.yml
src/Akeneo/Tool/Bundle/BatchQueueBundle/spec/Command/PublishJobToQueueCommandSpec.php
src/Akeneo/Tool/Bundle/BatchQueueBundle/tests/integration/Queue/PublishToJobQueueIntegration.php
src/Akeneo/Tool/Component/BatchQueue/Queue/PublishJobToQueue.php

Currently to push a new job into the queue, we use the command `PublishJobToQueueCommand`. But if we need this logic somewhere else in the PIM without calling a command with a new php process etc.. we can't. 
So I've extracted the logic to push (publish) a job into the queue into a dedicated service. …

Extract push job to queue logic into a dedicated service

---

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/grid/FilterBox.less

PIM-8535: prevent filter popup from being hidden behind the left menu

---

src/Akeneo/Tool/Bundle/BatchQueueBundle/tests/integration/Command/JobQueueConsumerCommandIntegration.php

Fixes a phpunit >=8 deprecation warning when using assertContains to compare strings

Fix phpunit deprecation

---

CHANGELOG-3.1.md
src/Akeneo/Platform/Bundle/ImportExportBundle/Widget/LastOperationsFetcher.php
tests/back/Platform/Specification/Bundle/ImportExportBundle/Widget/LastOperationsFetcherSpec.php

The `Akeneo\Platform\Bundle\ImportExportBundle\Query\GetLastOperationsInterface` returns the date as a string, so it was never converted by the presenter

PIM-8577: Convert dates to user timezone in last operations widget

---

CHANGELOG-3.0.md
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/field/wysiwyg-field.js

This pull request aims to fix the rendering issue of "Add link" modal dialogs when there are multiple Textarea attributes with "Rich Text editor" option enabled on the product edition page.
`OK`: …

PIM-8564: Wysiwyg - fix "add link" modal dialogs when multiple rich textarea

---

app/AppKernel.php
app/config/routing.yml
composer.json
composer.lock
src/Akeneo/UserManagement/Bundle/Controller/GroupController.php
src/Akeneo/UserManagement/Bundle/Controller/RoleController.php

This PR simply bumps a few dependencies to the last patches.
This is necessary in order to be able to upgrade Symfony to the version 4.
See https://github.com/akeneo/pim-community-dev/pull/10395

TIP-901: update dependencies

---

CHANGELOG-3.0.md
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/product/field/wysiwyg-field.js

Edit link was not visble because hidden under the backdrop mask.

PIM-8582: Fix wysiwyg edit link not visible.

---

.circleci/config.yml
composer.json
src/Akeneo/Platform/CommunityRequirements.php

This PR optimizes the class autoloading: we don't need to load classes in production if we only use them for test and there were some duplicated loading rules too.
Some post scripts are removed because we don't need them. Our install command do the same job, it is a pity to do two times the same job to install the PIM. We will save a little bit time to build our PIM :) …

TIP-1198 Don't need to check if web/bundle exist

---

CHANGELOG-2.3.md
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/job_instance/csv_product_model_import_show.yml
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/job_instance/xlsx_product_model_import_show.yml

The import profile shows "undefined" instead of CSV or XLSX

PIM-8349: import profile shows "undefined" instead of CSV or XLSX

---

CHANGELOG-2.3.md
src/Oro/Bundle/AsseticBundle/DependencyInjection/OroAsseticExtension.php

One case hasn't been expected in https://github.com/akeneo/pim-community-dev/pull/9696 : the PIM doesn't define stylesheet groups natively, but when an extension does (the Onboarder bundle for example) some less files from other extensions might be ignored.
With this PR, less file groups not included in any stylesheet are now included in the main stylesheet (pim.css) by default, so the behavior will be the same as before for integrators.
| Changelog …

SDS-11392: Include less files in main stylesheet by default

---

src/Akeneo/Pim/Enrichment/Bundle/Resources/config/datagrid/association_group.yml
src/Akeneo/Tool/Bundle/MeasureBundle/Resources/translations/jsmessages.en_US.yml
src/Akeneo/Tool/Bundle/MeasureBundle/Resources/translations/messages.en_US.yml
src/Akeneo/UserManagement/Bundle/Resources/config/event_subscribers.yml
src/Akeneo/UserManagement/Bundle/Resources/config/model/doctrine/User.orm.yml

Duplicated keys in YAML files trigger errors with Symfony4.

TIP-901: Remove duplicated keys in YAML files

---

CHANGELOG-3.1.md
src/Akeneo/Tool/Component/Connector/Archiver/AbstractInvalidItemWriter.php
src/Akeneo/Tool/Component/Connector/spec/Archiver/CsvInvalidItemWriterSpec.php

This PR fix a bug in the error reporting file at the end of an import process, when a cell in the file has a data (an empty space in my case...) but with no header defined for the whole column.
`OK`: …

PIM-8557: remove empty headers when building the error reporting file

---

src/Akeneo/Pim/Enrichment/Bundle/Storage/ElasticsearchAndSql/FollowUp/GetCompletenessPerChannelAndLocale.php
tests/back/Pim/Enrichment/Integration/PQB/AbstractProductQueryBuilderTestCase.php
tests/back/Pim/Enrichment/Integration/Storage/ElasticsearchAndSql/FollowUp/GetCompletenessPerChannelAndLocaleIntegration.php

This PR improves the ES queries and integration test for `Akeneo\Pim\Enrichment\Bundle\Storage\ElasticsearchAndSql\FollowUp\GetCompletenessPerChannelAndLocale` after the ES index merge done in https://github.com/akeneo/pim-community-dev/pull/10224. The queries now include filtering by `document_type` for products, and explicitly exclude product models.  …

TIP-1185: Improve integration test for completeness dashboard calculation

---

src/Akeneo/Channel/Bundle/Resources/config/controllers.yml
src/Akeneo/Pim/Enrichment/Bundle/Resources/config/controllers.yml
src/Akeneo/Pim/Structure/Bundle/Resources/config/controllers.yml
src/Akeneo/Platform/Bundle/AnalyticsBundle/Resources/config/controllers.yml
src/Akeneo/Platform/Bundle/CatalogVolumeMonitoringBundle/Resources/config/controllers.yml
src/Akeneo/Platform/Bundle/DashboardBundle/Resources/config/controllers.yml
src/Akeneo/Platform/Bundle/ImportExportBundle/Resources/config/controllers.yml
src/Akeneo/Platform/Bundle/NotificationBundle/Resources/config/controllers.yml
src/Akeneo/Platform/Bundle/UIBundle/Resources/config/controllers.yml
src/Akeneo/Tool/Bundle/ApiBundle/Resources/config/controllers.yml
src/Akeneo/UserManagement/Bundle/Resources/config/controllers.yml
src/Oro/Bundle/ConfigBundle/Resources/config/controllers.yml
src/Oro/Bundle/PimDataGridBundle/Resources/config/controllers.yml

With Symfony4, all services are private by default. Including the controllers. Which means, if you update the PIM to Symfony4, you'll have this kind of error:
`[2019-07-25 19:21:36] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "Controller "pim_user.controller.security_rest" cannot be fetched from the container because it is private. Did you forget to tag the service with "controller.service_arguments"?" at /srv/pim/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Controller/ContainerControllerResolver.php line 71 {"exception":"[object] (InvalidArgumentException(code: 0): Controller \"pim_user.controller.security_rest\" cannot be fetched from the container because it is private. Did you forget to tag the service with \"controller.service_arguments\"? at …

TIP-901: make controllers public

---

CHANGELOG-2.3.md
src/Pim/Bundle/EnrichBundle/Resources/public/js/mass-edit/form/product/product-model-field.js

PIM-7741: use the catalog locale when choosing a new parent product model

---

src/Akeneo/Platform/Bundle/UIBundle/Resources/public/less/components/product-edit-form/AssetCollectionField.less

PIM-8571: truncate the asset description on the PEF

---

upgrades/schema/remove_orphan_archives.php

Log examples:
```
jjanvier:pcd$ docker-compose exec fpm php upgrades/schema/remove_orphan_archives.php                       
Removing orphan directories in the local archive storage /srv/pim/app/archive...
Removing orphan job execution directories...
- Looking for job execution directories to remove in /srv/pim/app/archive/export/csv_attribute_export.
- Looking for job execution directories to remove in /srv/pim/app/archive/export/csv_product_export.
- Job execution directory /srv/pim/app/archive/export/csv_product_export/22 found.
- Looking for job execution directories to remove in /srv/pim/app/archive/import/csv_attribute_import.
- Job execution directory /srv/pim/app/archive/import/csv_attribute_import/32 found.
- Directory /srv/pim/app/archive/import/csv_attribute_import/32 removed. …
```

Add logs to orphan archives removal

---

CHANGELOG-2.3.md
src/Pim/Bundle/ApiBundle/tests/integration/Controller/ProductModel/PartialUpdateListProductModelIntegration.php
src/Pim/Bundle/CatalogBundle/Doctrine/ORM/Query/SqlGetValuesOfSiblings.php
src/Pim/Bundle/CatalogBundle/Resources/config/queries.yml
src/Pim/Bundle/CatalogBundle/Resources/config/validators.yml
src/Pim/Bundle/CatalogBundle/tests/integration/Doctrine/ORM/Query/SqlGetValuesOfSiblingsIntegration.php
src/Pim/Component/Catalog/EntityWithFamilyVariant/Query/GetValuesOfSiblings.php
src/Pim/Component/Catalog/Validator/Constraints/UniqueVariantAxisValidator.php
src/Pim/Component/Catalog/spec/Validator/Constraints/UniqueVariantAxisValidatorSpec.php

Use SQL queries instead of repos to get the values of siblings in UniqueVariantAxisValidator.
It avoids getting updated values if a sibling was previously updated but not persisted (hello Doctrine UOW) -> see [this test](https://github.com/akeneo/pim-community-dev/pull/10461/files#diff-49da1a039638d0f0b9294b0593520f98R281) for instance
| …

TIP-1200: Use SQL queries in UniqueVariantAxisValidator

---

CHANGELOG-2.3.md
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/CreateVariantProductIntegration.php
src/Pim/Bundle/ApiBundle/tests/integration/Controller/Product/PartialUpdateVariantProductIntegration.php
src/Pim/Bundle/EnrichBundle/Normalizer/EntityWithFamilyVariantNormalizer.php
src/Pim/Bundle/EnrichBundle/Resources/config/form_extensions/product_model/add_child.yml
src/Pim/Bundle/EnrichBundle/spec/Normalizer/EntityWithFamilyVariantNormalizerSpec.php
src/Pim/Component/Catalog/Validator/Constraints/UniqueVariantAxisValidator.php
src/Pim/Component/Catalog/spec/Validator/Constraints/UniqueVariantAxisValidatorSpec.php

see #10318 
It also fixes the validation of variant axis uniqueness in case of a boolean variant axis and a `false` value, and the display of such values in the navigation ('0' is now displayed for false values instead of an empty string previously)
`OK`: Done / …

PIM-7888: Fix creation of a product model / variant product with a boolean attribute as axis

---

CHANGELOG-3.0.md
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/attribute-group/form/tab/attribute.js
src/Akeneo/Platform/Bundle/UIBundle/Resources/public/js/attribute-group/form/tab/select.js

Even if the user does not have the view rights on the attribute group "Other", he should be able to add attributes to other attribute group. This PR fix the calls by passing `rights: 0` to the fetcher to get all attributes without checking rights.
`OK`: Done / …

PIM-8589: Fix add attribute to attribute group

---

upgrades/schema/remove_orphan_archives.php

The remove of the job directory deletes files with existing jobs execution (so that should not be removed).
It comes from the fact we use job instance code instead of job name. The directory name is based on the job name not on the job instance code.
So, if the job instance code is not the same than the job name, it removes the directory. …

Fix remove orphan archives
